### ISSUE TITLE
How to use BrowserMob Proxy Integration in a Junit test

### ISSUE THREAD

**Issue by breinjhel** [serenity-bdd/serenity-core#100]
Hi, 

Is there any docs on how to use the BrowserMob Proxy module?
I have tried this code but it wont work.

```
BrowserMobFixtureService service;
ProxyServer server;	

@Before
public void setup() {
    service = new BrowserMobFixtureService();
    server = service.getProxyServer();
}
```

And is there an update for it to use the latest BMP version which is using a new server called LittleProxy and not the Jetty server anymore.

Thanks.

**Comment by cliviu** [comment]
hi @breinjhel . In which way is the code not working ?

**Comment by cliviu** [comment]
hi @breinjhel , you can try this code :
```java
  BrowserMobFixtureService service;
  ProxyServer proxy;

  @Before
  public void setup() {
        ClasspathFixtureProviderService classpathFixtureProviderService = new ClasspathFixtureProviderService();
        List<FixtureService> fixtureServices = classpathFixtureProviderService.getFixtureServices();
        for(FixtureService fixtureService: fixtureServices){
            if(fixtureService instanceof BrowserMobFixtureService ) {
                service = (BrowserMobFixtureService) fixtureService;
                service.setup();
                proxy = service.getProxyServer();
            }
        }
 }
```

**Comment by cliviu** [comment]
currently only the Jetty version is supported

**Comment by breinjhel** [comment]
Hi @cliviu ,

Thanks Ill try it out tomorrow. I can see in the logs that BMP was already running but I wasnt sure how to get the server object so I can get some HAR files on it.

**Comment by breinjhel** [comment]
Hi @cliviu ,

Doesnt the service automatically instantiate and setup itself? So in your code why do you run service.setup(). That would run it twice already. I just wanted to get the existing service Server object. Is there a proper documentation on how to use the module? I just want to create and retrieve a Har file with it. So that i can get all network request on my automation.

Thanks

**Comment by breinjhel** [comment]
As far as I know. The BrowserMobFixtureService automatically setup when my test run. So if I add another setup in my @Before method heres what happens:
1. @Before method runs and initializes BrowserMobFixtureService, setups then start server opens in port 49153
2. Running the test another initialization  of BrowserMobFixtureService is created. I think this is an auto loading function in Serenity. So now it creates another port which is 49154
3. Browser uses 49154 port as proxy
4. I want to get my proxy server's har file but now its always empty since my proxy which is 49153 is not used.

How do I get the ProxyServer object of the auto initialization of BrowserMobProxy. I have used your code and what I get is a null object and still needs to be initialized.

**Comment by cliviu** [comment]
hi, can you please post your test method ? , or better, your complete test class ? Thanks

**Comment by breinjhel** [comment]
```
   @RunWith(SerenityRunner.class)
   public class LoginTest{
    @Managed
	WebDriver driver;


    EnvironmentVariables b;


        // On first creation of webdriver the BrowserMob Proxy is created and its all good 
	@Test
	public void shouldLoginWithCorrectCredentials(){
               // Login Here
               
               // But I want to access the Har object here from the Proxy Server
	}
}
```

**Comment by cliviu** [comment]
sorry about the setup() method, normally is not necessary to call it 

getting the har should work like this 
```
private ProxyServer getProxyServer() {
        FixtureProviderService classpathFixtureProviderService = Injectors.getInjector().getInstance(FixtureProviderService.class);
        List<FixtureService> fixtureServices = classpathFixtureProviderService.getFixtureServices();
        for(FixtureService fixtureService: fixtureServices){
            if(fixtureService instanceof BrowserMobFixtureService) {
                BrowserMobFixtureService service = (BrowserMobFixtureService) fixtureService;
                return service.getProxyServer();
            }
        }
        return null;
    }
```
from the ProxyServer you can get the Har

**Comment by breinjhel** [comment]
Hi, 

Thanks thats what I needed. But now the problem for me is that when BMP is setup it doesnt create a har first right? like getProxyServer().newHar("sample"). What is the best way to create the har file because currently I cant place it in @Before since the webdriver instance is not yet created on that phase so what I did is

	@Test
	public void shouldNotLoginWithBadCredentials(){
		// GIVEN
		steps.open_login_page();


        // Setup the Har file here cause only after opening the browser creates the ProxyServer object. is there a better way?
		setupHar();

		// WHEN
		steps.login("asdsa&*^/", "asds1%%$^");

		// THEN
		steps.user_is_not_logged_in_due_to_invalid_credentials();

        // Print the har logs
		printAllHar();
	}

**Comment by breinjhel** [comment]
I just want to create the Har file as soon as the ProxyServer object is instantiated so I can get all the request right after the browser opens.

**Comment by cliviu** [comment]
hmm, you can try as workaround to access the proxied driver in setup to force the proxy instantiation and then to initialize the har ... hopefully is works 
```
@Before
    public void setup() {
          .....
          WebDriver proxiedDriver = ((WebDriverFacade) loginPage.getDriver()).getProxiedDriver();
          .....
          setupHar();  // setup har for being available in the test method
    }
```

**Comment by breinjhel** [comment]
Thanks @cliviu , will try that tomorrow hopefully it works. You've been a great help.

**Comment by cliviu** [comment]
you're welcome @breinjhel . I hope it helps
