### ISSUE TITLE
@Manual tagged scenarios not shown in reports

### ISSUE THREAD

**Issue by saranyas** [serenity-bdd/serenity-core#1000]
Hi,

Using @Manual tag in story file and using serenity version 1.5.5. But manual test scenarios not shown in the report.

Automated | 439 | 425 (97%) | 0 (0%) | 13 (3%) | 1 (0%)
Manual | 0 | 0 (0%) | 0 (0%) | 0 (0%) | 0 (0%)
Total | 439 | 425 (97%) | 0 (0%) | 13 (3%) | 1 (0%)

**Comment by wakaleo** [comment]
Have you tried using the latest versions?

**Comment by vuthelinh** [comment]
@saranyas 
you should use post 2 annotations : @Test and @Manual together

Try with this
```
@Test
@Manual
public void showManualTestOnReport(){ 
         // TODO: Something Test
}
```

**Comment by wakaleo** [comment]
Presuming fixed/working as designed.
