### ISSUE TITLE
webdriver.base.url is not working

### ISSUE THREAD

**Issue by BladeDark** [serenity-bdd/serenity-core#1001]
I set the parameter name in the serenity.properties as
webdriver.base.url=https://www.google.co.th
After executing, It did not open as setting up

**Comment by wakaleo** [comment]
Could you share the code where you expect the page to open to this URL?

**Comment by mmanach** [comment]
I know that my issue is not totally linked to this one, but in my case : 
When I run this command line : 
```
gradle test -Dwebdriver.driver=chrome -Dwebdriver.base.url=https://test.com aggregate
```
My -D params are not resolved.
(but in my serenity.properties, they are ok)

For working, I need to redefine the test task in my gradle.build : 
```
test {
    options {
        systemProperties(System.getProperties())
    }
}
```
An now, my -D params are resolved.

**Comment by wakaleo** [comment]
That is expected behaviour I believe - yiu need to pass in the properties form the cmd line to the test process

**Comment by mmanach** [comment]
@wakaleo sorry, I didn't understand what you mean ?

**Comment by BladeDark** [comment]
It can passing value instead of defining value in serenity.properties
as example:
test verify -Dwebdriver.base.url=https://ecom-staging-dat.worldticket.net

I closed this issued

**Comment by mmanach** [comment]
@BladeDark Are you using maven ?
