### ISSUE TITLE
Browser interaction not works on print page view

### ISSUE THREAD

**Issue by khalistan** [serenity-bdd/serenity-core#1002]
I have one step which click on one button who just bring print view of page. After opening this page, next step is not being executed. Thread waiting somewhere and then it gets time out. It could be core selenium bug, so i will also report this to selenium. It could also possible that this feature is not supported.

**To reproduce issue:**

1. write a step which execute this javaScript --> ` window.print();`  (or just open chrome driver and on console enter window.print(); then a Print view page should open)
2. write any another step
Now executor, will execute first step will take too much time (timeout) to another step.

**Expected**
On print view page, all the dom element should be intractable.

**Environment**
Image(s): selenium/node-chrome-debug 3.5.3, selenium/hub 3.5.3
Docker Version: 17.07.0-ce
OS: Linux
seleniumVersion = 2.53.1
htmlUnitDriverVersion = 2.52.0
jUnitVersion = 4.12
serenityVersion = 1.4.1-rc.7
serenityJiraVersion = 1.1.3-rc.5
**Also testet on**
OS: Linux
version.org.seleniumhq.selenium.selenium-firefox-driver = 3.0.1
version.org.seleniumhq.selenium.selenium-java = 3.0.1
version.org.seleniumhq.selenium.selenium-support = 3.0.1
version.junit.junit = 4.+

**Comment by wakaleo** [comment]
Sounds like a Selenium or Selenium Driver issue. Your versions are very old, so you could try updating to the latest versions of everything.

**Comment by khalistan** [comment]
I just tested on selenium 3.0.* an problem is there

**Comment by wakaleo** [comment]
OK, thanks for checking. I will close this issue and let you open one with the Selenium team.

**Comment by khalistan** [comment]
ok. Thanks for checking and I have register bug to selenium. Any one who is looking this issue can trace bug here https://github.com/SeleniumHQ/selenium/issues/4998
