### ISSUE TITLE
How to close ad overlay popup when not sure when is it displayed

### ISSUE THREAD

**Issue by lilyhoang** [serenity-bdd/serenity-core#1003]
When I run script, sometime the system has a overlay popup suddenly displayed.
How to I handle it that whenever popup is display, then close it before continue the test

Thanks
![2017-11-03_16-44-23](https://user-images.githubusercontent.com/20644391/32367927-780b4e5a-c0b6-11e7-9a6a-2ca898239ba4.png)

**Comment by wakaleo** [comment]
Hi Lily, this is a usage question rather than a bug, could you ask it on the Rocket Chat channel (http://serenity-bdd.rocket.chat), on StackOverflow (tagged with #serenitybdd) or on the Google Groups list?

**Comment by lilyhoang** [comment]
Thanks Wakaleo :)
