### ISSUE TITLE
HTML Report: Is is possible to implement expansion/collapse of tasks to exist below top-level task?

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1004]
One of the amazing selling points of the screenplay pattern is in how it provides enhanced html reporting e.g. a detailed audit trail of all tasks within a step, including all test data via the task drill-down:

![image](https://user-images.githubusercontent.com/626941/32373853-373f5146-c093-11e7-9a7e-7d3e4c58b70a.png)

This feature alone is probably enough of a reason for a project team to migrate away from 'vanilla' cucumber to cucumber with screenplay. This really helps provide the necessary diagnostic information about why a test has failed, especially one that is has a lot of navigation (e.g. in the test setup). The fact that the html report by default, collapses this detail out of view underneath the parent step is good in that the top level report appears initially uncluttered.

However, when the step is expanded, every single child task & interaction is immediately expanded which then provides an extremely cluttered view. Here is an example of that from one of our project scenarios:

![image](https://user-images.githubusercontent.com/626941/32373583-d29e968a-c091-11e7-8b50-ff41b98c472e.png)

Because screenplay encourages task decomposition, the number of tasks that can appear can run into hundreds (my above example is nearly 450). So the requirement is this: Can the expand/collapse feature be applied for every level in the test step, so that different levels are then progressively unveiled?

I'm sure there may be some complexities to this question and perhaps some undesirable consequences (not sure how this might affect the serenity-js users @jan-molak?) I'm happy to attempt a PR of this but want a quick heads up with the authors before I spend too much time on it!

**Comment by wakaleo** [comment]
You are more then welcome to tweak the freemarker templates to do this, it would be a great feature.

**Comment by jan-molak** [comment]
@nbarrett - Serenity/JS generates `json` reports compatible with Serenity BDD, so I don't see any issues with this change. In fact, I'd really welcome this PR :-)

**Comment by nbarrett** [comment]
Closing this as https://github.com/serenity-bdd/serenity-core/pull/1780 will deliver this functionality.
