### ISSUE TITLE
Upload is not working in selenium grid environment 

### ISSUE THREAD

**Issue by sello4354** [serenity-bdd/serenity-core#1006]
I am using the following code snippet : 
 upload(System.getProperty("user.dir") + cohortsDirectory + file).fromLocalMachine().to(uploadCohort);

i am getting file not found exception . The driver is expecting to get the file using the local file directory structure in the remote machine  . 

i am using serenity-core 1.65 and serenity-cucumber 1.5.15

**Comment by wakaleo** [comment]
That's what `fromLocalMachine()` does - it activates the LocalFileDetector, which looks for files on the remote machine. Where are you expecting to look for the file?

**Comment by sello4354** [comment]
I was expecting it to look for the file  in the remote machine but not using the same directory structure (C:\Users\James\Documents\cohorts\patient.xml) because the remote node does not have a  user account named "James". I thought during the transfer of the file Serenity place the file in temporary file location .

**Comment by wakaleo** [comment]
The Serenity code simply wraps the WebDriver code in a fluent API for convenience, the underlying logic is performed by WebDriver. See https://saucelabs.com/blog/selenium-tips-uploading-files-in-remote-webdriver.

**Comment by sello4354** [comment]
I was able to upload my file without any problem using the above remotewebdriver example . This is the version of selenium-java I used 3.0.1

**Comment by wakaleo** [comment]
Could you share the code that you used?

**Comment by sello4354** [comment]
Selenium code:
@BeforeClass
    public void init() throws MalformedURLException {
        DesiredCapabilities dc = DesiredCapabilities.chrome();
        driver = new RemoteWebDriver(new URL("http://x.x.x.x:4448/wd/hub"), dc);
        driver.setFileDetector(new LocalFileDetector());
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.manage().window().maximize();
        driver.get("http://x.x.x.x/quality/#");
        driver.navigate().to(new URL("http://x.x.x.x/quality/#/cohorts"));
    }

    @Test()
    public void testUploadonCohort() {
        driver.findElement(By.xpath(".//button[text()='Import Cohort']")).click();
        WebElement selectWE = driver.findElement(By.xpath(".//select"));
        Select select = new Select(selectWE);
        select.selectByVisibleText("NSQIP XML Import Patient List");
        driver.findElement(By.xpath(".//div/div[2]/div/div[2]/div[2]/div[2]/input")).sendKeys("test_cohorts_name");
        driver.findElement(By.xpath(".//div/div/div/div[2]/div/div[2]/div[3]/div[2]/input")).sendKeys("test_cohorts_name");
        driver.findElement(By.xpath(".//input[@id='fileupload']")).sendKeys("src\\test\\resources\\cohorts\\NSQIP.xml");
        driver.findElement(By.xpath(".//button[text()='Import Data']")).click();
        driver.findElement(By.xpath("//div/div[2]/div[2]/button")).click();
    }

**Comment by wakaleo** [comment]
I can't reproduce any issues with the uploading logic, your best bet would be to step into the Serenity code to see how it works (it's just a very thin wrapper around the WebDriver code).

**Comment by sello4354** [comment]
After looking into the ConfigureFileDetector  class , I added the following code in my test class and got class cast exception  
 logger.info("driver info :" + getDriver().getClass());
        ((RemoteWebDriver) getDriver()).setFileDetector(new LocalFileDetector());
        upload(cohortsDirectory + file).fromLocalMachine().to(uploadCohort);

INFO - driver info :class net.thucydides.core.webdriver.WebDriverFacade
**Exception** 
java.lang.ClassCastException: net.thucydides.core.webdriver.WebDriverFacade cannot be cast to org.openqa.selenium.remote.RemoteWebDriver
	at com.qpid.auotmation.quality.pages.CohortsPage.importCohort(CohortsPage.java:106)
	at com.qpid.auotmation.quality.steps.serenity.CohortsSteps.importCohort(CohortsSteps.java:31)
	at com.qpid.auotmation.quality.steps.serenity.CohortsSteps$$EnhancerByCGLIB$$704e18f6.CGLIB$importCohort$0(<generated>)
	at com.qpid.auotmation.quality.steps.serenity.CohortsSteps$$EnhancerByCGLIB$$704e18f6$$FastClassByCGLIB$$befae191.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:425)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:410)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:385)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:133)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:62)
	at com.qpid.auotmation.quality.steps.serenity.CohortsSteps$$EnhancerByCGLIB$$704e18f6.importCohort(<generated>)
	at com.qpid.auotmation.quality.steps.CohortsStepsDef.enters_file_type_cohort_name_cohort_description_and_file(CohortsStepsDef.java:32)
	at ?.enters file type "QPID Patient List", cohort name "test_QPID_Patient_List",cohort description "test_description" and file "Qpid_Patient.xlsx"(src/test/resources/features/Cohorts.feature:6)

**Comment by wakaleo** [comment]
That won't work, because getDriver() returns a WebDriverFacade, not a RemoteDriver. In any case, you shouldn't need to to this at that level - the LocalFileDetector is added when you call fromLocalMachine().

**Comment by sello4354** [comment]
I debugged the issue while running my tests  and this is what i found out : 
The ConfigureFileDetector class, which is invoked by the fromLocalMachine method , is not setting the LocalFileDetector since "driver instanceof RemoteWebDriver" evaluates to false .

**Comment by wakaleo** [comment]
What driver are you using for the remote tests?

**Comment by sello4354** [comment]
chrome

**Comment by wakaleo** [comment]
Could you propose a PR?
