### ISSUE TITLE
broken junit xml report

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#1008]
Hello @wakaleo ,

Since I updated serenity to version 1.6.6, the junit xml report generated (by gradle test task) seems to be broken.
Indeed, on jenkins, the reports are "not found" (all was ok with version 1.5.9).

I try with version 1.6.9 and everything seems to be back in order, but in changelogs I did not find any cause...

Here in attachment the list of junit xml generated files.

![junit xml results](https://user-images.githubusercontent.com/29480659/32444166-e4334e82-c301-11e7-97a1-8db6aff871d1.png)

**Comment by wakaleo** [comment]
Thanks for the heads up - this could be related to some changes in the Gradle plugin. Could you confirm that it works correctly in version 1.6.9 and 1.7.0?

**Comment by wakaleo** [comment]
Seems OK in 1.7.0.
