### ISSUE TITLE
Could not initialize class net.serenitybdd.core.pages.DefaultTimeouts

### ISSUE THREAD

**Issue by MiguelPanadero** [serenity-bdd/serenity-core#1011]
Hi there,

Thanks for your help in advance, I am upgrading serenity to the last version on my BDD project. I am receiving the following error when I run the suite: 

> java.lang.NoClassDefFoundError: Could not initialize class net.serenitybdd.core.pages.DefaultTimeouts
	at net.thucydides.core.webdriver.WebDriverFacade.defaultImplicitWait(WebDriverFacade.java:79)
	at net.thucydides.core.webdriver.WebDriverFacade.<init>(WebDriverFacade.java:65)
	at net.thucydides.core.webdriver.WebdriverProxyFactory.proxyFor(WebdriverProxyFactory.java:67)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.newDriver(SerenityWebdriverManager.java:64)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.instantiatedThreadLocalWebDriver(SerenityWebdriverManager.java:222)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getWebdriver(SerenityWebdriverManager.java:110)
	at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getDriver(ThucydidesWebDriverSupport.java:128)
	at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getPages(ThucydidesWebDriverSupport.java:189)
	at net.serenitybdd.core.Serenity.getPages(Serenity.java:187)
	at net.serenitybdd.core.Serenity.getDefaultDependencyInjectors(Serenity.java:83)
	at net.serenitybdd.core.Serenity.getDependencyInjectors(Serenity.java:74)
	at net.serenitybdd.core.Serenity.resetDependencyInjectors(Serenity.java:67)
	at net.serenitybdd.core.Serenity.done(Serenity.java:166)
	at net.serenitybdd.core.Serenity.done(Serenity.java:153)
	at cucumber.runtime.formatter.SerenityReporter.assureTestSuiteFinished(SerenityReporter.java:617)
	at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:313)

My pom.xml configuration is the following:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
	
	
	<parent>
		<groupId>xxx</groupId>
		<artifactId>bdd</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	
	
	
    <artifactId>automation-tests</artifactId>
    <packaging>jar</packaging>
    <name>Automation Tests</name>
    <description>Automation Tests written in Cucumber under the Serenity framework.</description>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <sonar.projectName>Automation Tests</sonar.projectName>
        
        <sonar.sources>src/test</sonar.sources>
        <sonar.test.exclusions>src/test/**/*</sonar.test.exclusions>

        
        <serenity.version>1.7.0-rc.1</serenity.version>
        <serenity.maven.version>1.7.0-rc.1</serenity.maven.version>
        <serenity.cucumber.version>1.6.2</serenity.cucumber.version>

        
        <write-classes>-Dwrite.classes=false</write-classes>
        <clean-classes>-Dclean.classes=true</clean-classes>
        <included-adapters>-Dincluded.adapters=coverage:complexity:dependency</included-adapters>
        <serenity-parameters>${write-classes} ${clean-classes} ${included-adapters} -noverify</serenity-parameters>
        <headless-parameters>-Djava.awt.headless=true</headless-parameters>
        <memory-parameters>-XX:PermSize=128m -XX:MaxPermSize=256m -Xms512m -Xmx1024m</memory-parameters>

        
        <tag-options />
        <tag-param></tag-param>

        
        <diff.match.threshold>0.05</diff.match.threshold>
		
        
        <webdriver.driver>chrome</webdriver.driver>
        <selenium.webdriver.repo>https://internal.repo/repository-3.6.0.json</selenium.webdriver.repo>
        <webdriver.chrome.driver>${basedir}/drivers/chromedriver-windows-32bit.exe</webdriver.chrome.driver>
        <webdriver.ie.driver>${basedir}/drivers/internetexplorerdriver-windows-32bit.exe</webdriver.ie.driver>
        <webdriver.phantomjs.driver>${basedir}/drivers/phantomjs-windows-32bit.exe</webdriver.phantomjs.driver>

    </properties>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>net.serenity-bdd</groupId>
                    <artifactId>serenity-screenplay</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.serenity-bdd</groupId>
                    <artifactId>serenity-screenplay-webdriver</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>1.8.6</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>net.coobird</groupId>
            <artifactId>thumbnailator</artifactId>
            <version>0.4.4</version>
        </dependency>
        <dependency>
            <groupId>org.frontendtest.components</groupId>
            <artifactId>image-comparison</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>3.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>3.7.0</version>
        </dependency>
        <dependency>
            <groupId>ru.yandex.qatools.ashot</groupId>
            <artifactId>ashot</artifactId>
            <version>1.5.2</version>
        </dependency>
        <dependency>
            <groupId>cglib</groupId>
            <artifactId>cglib-nodep</artifactId>
            <version>3.2.4</version>
        </dependency>
        <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy</artifactId>
            <version>1.7.5</version>
        </dependency>
        
        <dependency>
            <groupId>javax.jcr</groupId>
            <artifactId>jcr</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.jackrabbit</groupId>
            <artifactId>jackrabbit-jcr-commons</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.adobe.aem</groupId>
            <artifactId>uber-jar</artifactId>
            <classifier>apis</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.sling</groupId>
            <artifactId>org.apache.sling.commons.json</artifactId>
            <version>2.0.16</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>23.0</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.10</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.2</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>bdd</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>enforce</id>
                                <configuration>
                                    <rules>
                                        <requireUpperBoundDeps />
                                    </rules>
                                </configuration>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <forkMode>once</forkMode>
                            <argLine>-javaagent:${project.parent.basedir}/serenity/serenity.jar ${headless-parameters} ${tag-param} ${serenity-parameters} ${memory-parameters}</argLine>
                        </configuration>
                    </plugin>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <includes>
                                <include>**/cucumber/*.java</include>
                                <include>**/cucumber/*/*.java</include>
                            </includes>
                            <reuseForks>true</reuseForks>
                            <forkMode>once</forkMode>
                            <runOrder>alphabetical</runOrder>
                            <argLine>${headless-parameters} ${tag-param} ${memory-parameters}</argLine>
                            <systemPropertyVariables>
                                <diff.match.threshold>${diff.match.threshold}</diff.match.threshold>
                                <serenity.outputDirectory>${serenity.outputDirectory}</serenity.outputDirectory>
                                <webdriver.driver>${webdriver.driver}</webdriver.driver>
                                <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
                                <webdriver.ie.driver>${webdriver.ie.driver}</webdriver.ie.driver>
                                <webdriver.phantomjs.driver>${webdriver.phantomjs.driver}</webdriver.phantomjs.driver>
                                <phantomjs.binary.path>${webdriver.phantomjs.driver}</phantomjs.binary.path>
                                <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                                <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                            </systemPropertyVariables>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>com.github.webdriverextensions</groupId>
                        <artifactId>webdriverextensions-maven-plugin</artifactId>
                        <version>3.1.2</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>install-drivers</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <repositoryUrl>${selenium.webdriver.repo}</repositoryUrl>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <source>1.8</source>
                            <target>1.8</target>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>net.serenity-bdd.maven.plugins</groupId>
                        <artifactId>serenity-maven-plugin</artifactId>
                        <version>${serenity.maven.version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>net.serenity-bdd</groupId>
                                <artifactId>serenity-core</artifactId>
                                <version>${serenity.version}</version>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <id>serenity-reports</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>aggregate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>

My mvn dependency:tree looks like:

[INFO] bdd:aviva-group-automation-tests:jar:1.21.2-SNAPSHOT
[INFO] +- net.serenity-bdd:serenity-core:jar:1.7.0-rc.1:compile
[INFO] |  +- com.google.inject:guice:jar:4.1.0:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:provided
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- cglib:cglib:jar:3.2.5:compile
[INFO] |  |  \- org.apache.ant:ant:jar:1.9.6:compile
[INFO] |  |     \- org.apache.ant:ant-launcher:jar:1.9.6:compile
[INFO] |  +- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  +- org.objenesis:objenesis:jar:2.6:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.21:provided
[INFO] |  +- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  +- io.cucumber:cucumber-core:jar:2.1.0:compile
[INFO] |  |  +- info.cukes:cucumber-html:jar:0.2.6:compile
[INFO] |  |  +- io.cucumber:cucumber-jvm-deps:jar:1.0.6:compile
[INFO] |  |  +- io.cucumber:gherkin:jar:5.0.0:compile
[INFO] |  |  \- io.cucumber:tag-expressions:jar:1.0.1:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:compile
[INFO] |  +- io.vavr:vavr:jar:0.9.0:compile
[INFO] |  |  \- io.vavr:vavr-match:jar:0.9.0:compile
[INFO] |  +- net.serenity-bdd:serenity-report-resources:jar:1.7.0-rc.1:compile
[INFO] |  +- commons-io:commons-io:jar:2.5:provided
[INFO] |  +- com.opera:operadriver:jar:1.5:compile
[INFO] |  |  +- com.opera:operalaunchers:jar:1.1:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:2.4.1:compile
[INFO] |  |  +- commons-jxpath:commons-jxpath:jar:1.3:compile
[INFO] |  |  \- org.ini4j:ini4j:jar:0.5.2:compile
[INFO] |  +- com.codeborne:phantomjsdriver:jar:1.4.3:compile
[INFO] |  +- org.eclipse.jetty:jetty-util:jar:9.4.5.v20170502:compile
[INFO] |  +- org.eclipse.jetty:jetty-io:jar:9.4.5.v20170502:compile
[INFO] |  +- org.seleniumhq.selenium:htmlunit-driver:jar:2.27:compile
[INFO] |  +- io.appium:java-client:jar:5.0.4:compile
[INFO] |  |  +- commons-validator:commons-validator:jar:1.6:compile
[INFO] |  |  |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  |  |  \- commons-digester:commons-digester:jar:1.8.1:compile
[INFO] |  |  +- org.springframework:spring-context:jar:5.0.0.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-aop:jar:5.0.0.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-beans:jar:5.0.0.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-core:jar:5.0.0.RELEASE:compile
[INFO] |  |  |  |  \- org.springframework:spring-jcl:jar:5.0.0.RELEASE:compile
[INFO] |  |  |  \- org.springframework:spring-expression:jar:5.0.0.RELEASE:compile
[INFO] |  |  +- org.aspectj:aspectjweaver:jar:1.8.11:compile
[INFO] |  |  \- org.openpnp:opencv:jar:3.2.0-1:compile
[INFO] |  +- org.codehaus.groovy:groovy:jar:2.4.12:compile
[INFO] |  +- net.sf.opencsv:opencsv:jar:2.0:compile
[INFO] |  +- commons-beanutils:commons-beanutils-core:jar:1.8.3:compile
[INFO] |  +- joda-time:joda-time:jar:2.7:compile
[INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.9:compile
[INFO] |  |  +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  |  \- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.5:provided
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- org.freemarker:freemarker:jar:2.3.23:compile
[INFO] |  +- net.sourceforge.jexcelapi:jxl:jar:2.6.12:compile
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |  +- net.sourceforge.htmlunit:htmlunit:jar:2.27:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.3:compile
[INFO] |  +- org.fluentlenium:fluentlenium-core:jar:0.10.2:compile
[INFO] |  +- com.jhlabs:filters:jar:2.0.235:compile
[INFO] |  +- org.asciidoctor:asciidoctor-java-integration:jar:0.1.4:compile
[INFO] |  |  \- org.jruby:jruby-complete:jar:1.7.4:compile
[INFO] |  +- org.imgscalr:imgscalr-lib:jar:4.2:compile
[INFO] |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.1.1.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.0.0:compile
[INFO] |  +- javax.el:javax.el-api:jar:2.2.4:compile
[INFO] |  +- org.glassfish.web:javax.el:jar:2.2.4:compile
[INFO] |  +- xalan:xalan:jar:2.7.2:compile
[INFO] |  +- xalan:serializer:jar:2.7.2:compile
[INFO] |  +- org.awaitility:awaitility:jar:3.0.0:compile
[INFO] |  +- com.typesafe:config:jar:1.3.1:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.10.3:compile
[INFO] |  +- com.google.jimfs:jimfs:jar:1.1:compile
[INFO] |  +- es.nitaur.markdown:txtmark:jar:0.16:compile
[INFO] |  \- com.vladsch.flexmark:flexmark-all:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-abbreviation:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-anchorlink:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-aside:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-autolink:jar:0.26.4:compile
[INFO] |     |  \- org.nibor.autolink:autolink:jar:0.6.0:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-definition:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-emoji:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-escaped-character:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-footnotes:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-issues:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-tables:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-tasklist:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-users:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-jekyll-front-matter:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-jekyll-tag:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-ins:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-xwiki-macros:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-superscript:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-tables:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-toc:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-typographic:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-yaml-front-matter:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-formatter:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-html-parser:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-jira-converter:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-pdf-converter:jar:0.26.4:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-core:jar:0.0.1-RC9:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-pdfbox:jar:0.0.1-RC9:compile
[INFO] |     |  |  \- org.apache.pdfbox:pdfbox:jar:2.0.4:compile
[INFO] |     |  |     \- org.apache.pdfbox:fontbox:jar:2.0.4:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-rtl-support:jar:0.0.1-RC9:compile
[INFO] |     |  |  \- com.ibm.icu:icu4j:jar:58.1:compile
[INFO] |     |  \- com.openhtmltopdf:openhtmltopdf-jsoup-dom-converter:jar:0.0.1-RC9:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-profile-pegdown:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-util:jar:0.26.4:compile
[INFO] |     \- com.vladsch.flexmark:flexmark-youtrack-converter:jar:0.26.4:compile
[INFO] +- net.serenity-bdd:serenity-junit:jar:1.7.0-rc.1:compile
[INFO] +- net.serenity-bdd:serenity-rest-assured:jar:1.7.0-rc.1:compile
[INFO] |  \- io.rest-assured:rest-assured:jar:3.0.2:compile
[INFO] |     +- org.codehaus.groovy:groovy-xml:jar:2.4.6:compile
[INFO] |     +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:compile
[INFO] |     +- io.rest-assured:json-path:jar:3.0.2:compile
[INFO] |     |  +- org.codehaus.groovy:groovy-json:jar:2.4.6:compile
[INFO] |     |  \- io.rest-assured:rest-assured-common:jar:3.0.2:compile
[INFO] |     \- io.rest-assured:xml-path:jar:3.0.2:compile
[INFO] +- net.serenity-bdd:serenity-cucumber:jar:1.6.2:compile
[INFO] +- io.cucumber:cucumber-java:jar:2.1.0:compile
[INFO] +- io.cucumber:cucumber-junit:jar:2.1.0:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.21:test
[INFO] +- org.codehaus.groovy:groovy-all:jar:1.8.6:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] +- com.googlecode.lambdaj:lambdaj:jar:2.3.3:compile
[INFO] |  \- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] +- org.assertj:assertj-core:jar:1.7.0:test
[INFO] +- net.coobird:thumbnailator:jar:0.4.4:compile
[INFO] +- org.frontendtest.components:image-comparison:jar:1.0:compile
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:3.7.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:3.7.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.7.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.7.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.7.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.7.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.7.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.7.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.7.0:compile
[INFO] |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  \- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] +- org.seleniumhq.selenium:selenium-server:jar:3.7.0:compile
[INFO] |  +- com.beust:jcommander:jar:1.48:compile
[INFO] |  +- org.w3c.css:sac:jar:1.3:compile
[INFO] |  +- net.sourceforge.cssparser:cssparser:jar:0.9.23:compile
[INFO] |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.27:compile
[INFO] |  +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.27:compile
[INFO] |  +- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  +- org.seleniumhq.selenium:jetty-repacked:jar:9.4.5.v20170502:compile
[INFO] |  +- org.eclipse.jetty:jetty-client:jar:9.4.5.v20170502:compile
[INFO] |  +- org.eclipse.jetty:jetty-http:jar:9.4.5.v20170502:compile
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:provided
[INFO] |  +- org.eclipse.jetty.websocket:websocket-api:jar:9.4.5.v20170502:compile
[INFO] |  +- org.eclipse.jetty.websocket:websocket-client:jar:9.4.5.v20170502:compile
[INFO] |  +- org.eclipse.jetty.websocket:websocket-common:jar:9.4.5.v20170502:compile
[INFO] |  +- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.15:compile
[INFO] +- org.seleniumhq.selenium:selenium-support:jar:3.7.0:compile
[INFO] +- ru.yandex.qatools.ashot:ashot:jar:1.5.2:compile
[INFO] +- cglib:cglib-nodep:jar:3.2.4:compile
[INFO] +- net.bytebuddy:byte-buddy:jar:1.7.5:compile
[INFO] +- javax.jcr:jcr:jar:2.0:provided
[INFO] +- org.apache.jackrabbit:jackrabbit-jcr-commons:jar:2.2.0:compile
[INFO] +- com.adobe.aem:uber-jar:jar:apis:6.2.0:compile
[INFO] +- org.apache.sling:org.apache.sling.commons.json:jar:2.0.16:provided
[INFO] +- org.projectlombok:lombok:jar:1.16.12:compile
[INFO] +- com.google.guava:guava:jar:23.0:provided
[INFO] |  +- com.google.code.findbugs:jsr305:jar:1.3.9:provided
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.0.18:provided
[INFO] |  +- com.google.j2objc:j2objc-annotations:jar:1.1:provided
[INFO] |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:provided
[INFO] +- commons-codec:commons-codec:jar:1.10:compile
[INFO] \- com.google.code.gson:gson:jar:2.8.2:compile

Thanks for your help.

**Comment by wakaleo** [comment]
java.lang.NoClassDefFoundError is some kind of dependency conflict - hard to say more. Try with version 1.7.0 and see if you can identify any dependency conflicts.

**Comment by wakaleo** [comment]
Closed for lack of activity
