### ISSUE TITLE
Pending annotation in orverridden methods not working properly

### ISSUE THREAD

**Issue by ElkeFenger** [serenity-bdd/serenity-core#1013]
**Example:**
_package: web.test.data_
```
public class DataTests {
   @Before
   public void setUser() {
      ...
   }

   @Test
   public void whenTestingThis() {
      ...
   }
}

```
_package: web.additional.test.data_
```
public class DataTests extends web.test.data.DataTests {
   @Pending
   public void whenTestingThis() {
      System.out.print("Hello");
   }
}
```

**Description:**
Executing the second test method "whenTestingThis" with the @Pending annotation will cause the execution of the @Before method of the super class. After that the test execution stops and it's indicated that the test is pending.
If the annotations @Test and @Override are added to the second method the test is right away stopped as it's recognized that the test is pending.

**Comment by wakaleo** [comment]
You should not have @Pending by itself, you should always have the @Test annotation on tests, even pending ones.

**Comment by wakaleo** [comment]
Closed for lack of activity (or presumed answered)
