### ISSUE TITLE
serenity-screenplay : Could not instantiate new WebDriver instance

### ISSUE THREAD

**Issue by stalexmr** [serenity-bdd/serenity-core#1015]
Hello,

I have downloaded default serenity-screenplay-webdriver form archetype and try to launch project, but always get this error:

[main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Timed out waiting 45 seconds for Firefox to start.

Part of my default pom.xml:

<serenity.version>1.7.0</serenity.version>
<webdriver.driver>firefox</webdriver.driver>

Can you help me or give any advise?

**Comment by wakaleo** [comment]
Do you have geckodriver in your system path?

**Comment by stalexmr** [comment]
Yes,

I have FireFox - 56.0 (64-bit) and geckodriver - v0.19.1 in my system path.

**Comment by wakaleo** [comment]
The message indicates a WebDriver issue with connecting to the browser (eg a geckodriver issue of some kind), rather than a Serenity issue

**Comment by stalexmr** [comment]
I figured out. 
Just had to restart the local system, sorry for disturbing.

**Comment by wakaleo** [comment]
Thanks for updating.
