### ISSUE TITLE
Not able to run serenity & selenium cucumber tests with firefox browser

### ISSUE THREAD

**Issue by narottamgla** [serenity-bdd/serenity-core#1018]
Dependency details:
    
 ```
        serenity.version>1.7.2</serenity.version>
        <serenity.cucumber.version>1.6.4</serenity.cucumber.version>
```

Other details:
OS: Win10
browser: Firefox 56.02

**Comment by Lynderyn** [comment]
Is the issue the following error?

Class cast exception: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.openqa.selenium.internal.Locatable

If so, I am getting the same issue and this is the first line of the stack trace:
at net.serenitybdd.core.pages.WebElementFacadeImpl.getCoordinates (WebElementFacadeImpl.java:1109)

**Comment by wakaleo** [comment]
Do you have a Selenium dependency defined in your project?

**Comment by narottamgla** [comment]
No. However this issue is got resolved after Serenity upgrade. but now i am stuck with 
[Issue-1019](https://github.com/serenity-bdd/serenity-core/issues/1019)

**Comment by wakaleo** [comment]
I'll close this one then.
