### ISSUE TITLE
HTML report is not getting generated with Serenity & Selenium Cucumber

### ISSUE THREAD

**Issue by narottamgla** [serenity-bdd/serenity-core#1019]
**Dependency details:**
    
 ```
        serenity.version>1.7.2</serenity.version>
        <serenity.cucumber.version>1.6.4</serenity.cucumber.version>
```

**Other details:**
OS: Win10
browser: Chrome 61/Firefox 56.02

**Exception message:**
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.7.2:aggregate (serenity-reports) on project testproject: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.7.2:aggregate failed: A required class was missing while executing net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.7.2:aggregate: com/google/common/collect/ImmutableList

**Comment by wakaleo** [comment]
You may have an incompatible version of Guava in your dependencies

**Comment by narottamgla** [comment]
Using Below Guava version:

```
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>23.3-jre</version>
</dependency>
```

Could you please help me which version i need to use?
Thanks.

**Comment by wakaleo** [comment]
We are trying to remove Guava dependencies from Serenity as they are always changing the API. Try with 23, it just let Serenity decide

**Comment by narottamgla** [comment]
Same issue with with 23 version as well

**Comment by wakaleo** [comment]
It’s a dependency conflict of some kind, try doing a dependency analysis on your pom file

**Comment by narottamgla** [comment]
Hello wakaleo,
Below is the githublink for project:
https://github.com/narottamgla/selenium-test

Will be great if you can help me to solve this issue.
Thanks

**Comment by wakaleo** [comment]
Your project works just fine with guava 23.0

**Comment by narottamgla** [comment]
With guava 23.0 , its giving below error to me:

Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (default) on project selenium-test: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: com/google/common/base/Function
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[ERROR] at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:362)

**Comment by wakaleo** [comment]
I can't reproduce this issue with the project you provided, I suspect it may be an issue with your maven repository.

**Comment by narottamgla** [comment]
Thanks @wakaleo for your help and it was maven issue only.

**Comment by wakaleo** [comment]
Thanks for the update.
