### ISSUE TITLE
Need to generate result in different format

### ISSUE THREAD

**Issue by ankitlodha** [serenity-bdd/serenity-core#1025]
Hi,

I need to generate result in different format. Need snapshots of executed testcases in individual folders instead of snapshots of entire execution in single folder. As later we need to attach these snapshot in QC against test cases. Can we tweak code to create folders at the result location and then place individual test cases snapshots there. Please suggest.

**Comment by wakaleo** [comment]
You would need to write a custom reporter. This is a question, not a bug, so the GitHub is not an appropriate forum for this sort of query. Please ask on StackOverflow with the #serenitybdd tag, or on RocketChat (https://serenity-bdd.rocket.chat)

**Comment by ankitlodha** [comment]
Hi,

Sure. Will use stackoverflow or Rocket Chat for such questions. Can you please guide how can we write custom reporter and bypass existing reporting. If you like I can post same question on stackoverflow or rocket chat

**Comment by wakaleo** [comment]
We'll add this to the documentation backlog.
