### ISSUE TITLE
Jbehave scenarios and stories marked with @ignore are still executed

### ISSUE THREAD

**Issue by lega-land** [serenity-bdd/serenity-core#1026]
Updating from serenity-core 1.2.4 and serenity-jbehave 1.1.0 to serenity-core 1.7.4 and serenity-jbehave 1.33.0.

Simplest case with `@ignore` still executes scenario but marks it as ignored in Serenity report.

**story_test.story:**
```
Scenario: scenario 1
Meta:
@ignore
When print '1'

Scenario: scenario 2
When print '2'
```
**Step definitions class:**
```
package test.jbehave;

import net.thucydides.core.annotations.Steps;
import org.jbehave.core.annotations.When;

public class StepDefinitions {
    @Steps
    TestSteps steps;

    @When("print '$value'")
    public void print(String value) {
        steps.print(value);
    }
}
```
**TestSteps class:**
```
package test.jbehave;

import net.thucydides.core.annotations.Step;

public class TestSteps {

    @Step
    public void print(String value) {
        System.out.println(value);
    }
}
```
**StoryTest runner:**
```
package test.jbehave;

import net.serenitybdd.jbehave.SerenityStory;

public class StoryTest extends SerenityStory {
}
```
**Running StoryTest runner output:**
```
1
When print '1'

Story name for stories/story_test.story => TestTag{name='Story test', type='story'}
Story name for stories/story_test.story => TestTag{name='Story test', type='story'}
Scenario: scenario 2
2
When print '2'



(AfterStories)

Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=false,verboseFiltering=false,storyTimeouts=50000,threads=1,failOnStoryTimeout=false]

(BeforeStories)Running story stories/story_test.story

(stories/story_test.story)
Story name for stories/story_test.story => TestTag{name='Story test', type='story'}
Story name for stories/story_test.story => TestTag{name='Story test', type='story'}
Using timeout for story story_test.story of 50000 secs.
Scenario: scenario 1
Meta:
@ignore 

Generating reports view to 'C:\git\test\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 2 stories (of which 0 pending) containing 2 scenarios (of which 0 pending)
```
**Serenity report** shows that scenario 1 was ignored:
![image](https://user-images.githubusercontent.com/12608090/32747124-76ef6058-c8c0-11e7-9b0a-2609dc3f19c3.png)

**Comment by wakaleo** [comment]
This is normal behaviour. @Step methods are still run in ignored scenarios, unless you mark the steps with `@Step(callNestedMethods = false)`. WebDriver call will always be disabled, however.

**Comment by lega-land** [comment]
Added `@Step(callNestedMethods = false)` in TestStep class - scenario still run.
Tried without `@Steps` in StepDefinitions class - scenario still run.

**Comment by wakaleo** [comment]
If you remove the @Steps annotation, Serenity will have no control over them, so they will run normally (JBehave has no understanding of the @ignore tag). Code in the JBehave step definitions (@Given, @When and @Then methods) will always be executed, it is the contents of the @Step-annotation methods that will be skipped. 

If you think there is still an issue, please attach a sample project, or, better still, step into the code to understand how it works.

**Comment by lega-land** [comment]
We had step `page.open()` and it doesn't open the page as scenario is ignored, but Serenity tries to perform `@WhenPageOpens` which in our case sets browser height and width. And as browser wasn't opened, exception is thrown.
We removed this method and used serenity.browser.width and serenity.browser.height options.

**Comment by wakaleo** [comment]
Thanks for the update. Could you check with serenity-core 1.8.1; the PageObject.open() method now checks the state of the driver as well.

**Comment by lega-land** [comment]
The same behavior with serenity-core 1.8.1 and serenity-jbehave 1.34.0.
`org.jbehave.core.failures.BeforeOrAfterFailed: Method cleanAllClientParameters (annotated with @BeforeScenario in class com.tests.jbehave.utils.CustomJUnitStory) failed: net.serenitybdd.core.pages.UnableToInvokeWhenPageOpensMethods: Could not execute @WhenPageOpens annotated method: null`

**Comment by wakaleo** [comment]
Can you provide a sample project? Otherwise, put a breakpoint in the code and see if you can come up with a fix yourself.
