### ISSUE TITLE
Running with -Dtag try to launch all other tests after

### ISSUE THREAD

**Issue by stalexmr** [serenity-bdd/serenity-core#1028]
Hello, I have two test methods:

```
    @WithTagValuesOf({"feature:integration"})
    @Test
    public void myFirstMethod() {}

    @Test
    public void mySecondMethod() {}
```

I run this command:
mvn clean -Dtags=feature:integration failsafe:integration-test serenity:aggregate

And I see, that after first tagged test:
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.563 s 

The second test try to run:
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s

Can I do so, to prevent this behavior, cause I have about 1000 test and this logging confuse a little bit?

**Comment by wakaleo** [comment]
Not that I know of: I believe that reporting is done automatically by JUnit, not Serenity, and is not controlled by Serenity.
