### ISSUE TITLE
Improve readability of "View stack trace" dialog

### ISSUE THREAD

**Issue by awallat** [serenity-bdd/serenity-core#103]
When showing the dialog, the stack trace has a hard to read color. An update to "grey" as in commit c4033ea, would be helpful.

Moreover it would look nicer if the Exception wouldn't be written in the header of the dialog, but formatted in the body and the stacktrace at the end.

Otherwise this dialog is very helpful in finding errors quickly!

**Comment by wakaleo** [comment]
Should be fixed in 1.1.6
