### ISSUE TITLE
multiple calls to function  initPagesObjectUsing(driver);

### ISSUE THREAD

**Issue by pavi200863** [serenity-bdd/serenity-core#1031]
GetDriver() function is  calling   initPagesObjectUsing(driver) function , which is  being called again  ThucydidesWebDriverSupport.initialize  function also , do we require to call initPagesObjectUsing(driver) this in each getDriver() function ? 

public static WebDriver getDriver() {

        initialize();

        if (webdriverManagerThreadLocal.get() == null) {
            return null;
        }

        WebDriver driver;

        if (defaultDriverType.get() != null) {
            driver = getWebdriverManager().getWebdriver(defaultDriverType.get());
        } else {
            driver = (getWebdriverManager().getCurrentDriver() != null) ?
                    getWebdriverManager().getCurrentDriver() : getWebdriverManager().getWebdriver();
        }

        initPagesObjectUsing(driver);

        return driver;

    }

**Comment by wakaleo** [comment]
I'm not sure to be honest; if it is causing you problems, why not write a unit test to reproduce the incorrect behaviour and propose a PR?
