### ISSUE TITLE
Can't interact browser with server 

### ISSUE THREAD

**Issue by lilyhoang** [serenity-bdd/serenity-core#1033]
I got a problem as following , pls help !!!
Browser started by serenity can't communicate with server. 

When I click on Search button, Console returns TypeError: t is undefined.  but Its still ok when I start browser by manually.

![123](https://user-images.githubusercontent.com/20644391/32976167-db886ef2-cc43-11e7-8c8b-613800338ee5.png)

**Comment by wakaleo** [comment]
Those look like Driver errors - you might have an incompatible version of geckodriver or chromedriver.

**Comment by wakaleo** [comment]
Closed for lack of activity.
