### ISSUE TITLE
can you give compatible versions of Serenity jbehave and Serenity maven version

### ISSUE THREAD

**Issue by siva90144** [serenity-bdd/serenity-core#1035]
Can you give tabler format for  corresponding compatible versions for below core components
 
<serenity.version>1.2.4</serenity.version>
<serenity.maven.version>1.2.4</serenity.maven.version>		<serenity.jbehave.version>1.13.0</serenity.jbehave.version>

**Comment by wakaleo** [comment]
Since this is a question, not a bug, could you raise it on RocketChat (http://serenity-bdd.rocket.chat) or on the Serenity BDD mailing list?

Thanks.
