### ISSUE TITLE
geckodriver.exe hangs after WebDriverFacade.quit()

### ISSUE THREAD

**Issue by lega-land** [serenity-bdd/serenity-core#1038]
FireFox 57.0, geckodriver 0.19.1, serenity-core 1.8.1

I'm running hundreds of features in few threads and each time test ends it calls WebDriverFacade.quit(). For Chrome both chrome.exe and chromedriver.exe are closing at this moment. But for FireFox - firefox.exe closes and geckodriver.exe doesn't. Thus in time host becomes overwhelmed with geckodriver.exe process and testing hangs.

May you please take a look?

**Comment by lega-land** [comment]
There is no such problem if I use pure Selenium WebDriver:
```
System.setProperty("webdriver.gecko.driver", "C:\\geckodriver.exe");
WebDriver driver = new FirefoxDriver();
driver.get("http://google.com");
Thread.sleep(5000);
driver.quit();
```

**Comment by wakaleo** [comment]
Thanks for raising this, we will investigate. Serenity uses the GeckoDriverService rather than creating a direct FirefoxDriver, so the logic is different.

**Comment by wakaleo** [comment]
I'm not seeing this behaviour, could you provide a sample project? If you would like to investigate, the DriverServicePool class is a good place to start.

**Comment by lega-land** [comment]
looks like it's serenity-jbehave issue.
geckodriver closes with serenity-junit and serenity-cucumber.

**Comment by lega-land** [comment]
A bit of more research.
Serenity-cucumber doesn't close neither chromedriver.exe nor geckodriver.exe when `quit()` is called, only chrome.exe and firefox.exe are closed. But new driver process doesn't start when next feature starts. There is always one driver process is running. It only dies when main runner ends (maven or IDEA in my cases). Don't know if that's OK.

Serenity-jbehave works the same way except new geckodriver.exe is started for each story. Thus host is overwhelmed with geckodriver.exe processes until maven/IDEA end tests execution.

**Comment by wakaleo** [comment]
Thanks for your research. Yes, that's the way the service pools are meant to work. The normal process is to create one instance of chromedriver and geckodriver, which is terminated when the JVM shuts down (so at the end of the test run, not after each test). There must be something odd going on with the JBehave lifecycle calls. I know JBehave has very weird ways of using threads (so the same test can have several threads involved, which makes threadlocal variables very tricky). Have a look at what is happening in the net.serenitybdd.jbehave.SerenityReporter class.

**Comment by lega-land** [comment]
I've already debugged a lot. Still can't find the reason.

**Comment by wakaleo** [comment]
I suspect it might be thread-related. JBehave might be trying to obtain the gecko service pool from a different thread for each test. If I recall correctly, the GeckoDriverService is not threadsafe, so Serenity uses an extended version which is thread safe (ThreadsafeGeckoDriverService). So maybe put some breakpoints in the ThreadsafeGeckoDriverService class to see when it is being called and from which threads.

**Comment by lega-land** [comment]
Looks like `ThreadsafeGeckoDriverService.threadLocalDriverService` becomes cleared during `SerenityReporter.afterScenario`. And when new scenario starts and tries to open a page new geckodriver starts during DriverServicePool.start().
Unfortunately I'm not good with Threads, thus I can't investigate the problem thoroughly. I'd appreciate help here. Thanks!!!

**Comment by wakaleo** [comment]
This is tricky and largely due to the fact that the GeckoDriver is not threadsafe. Will probably get round to investigating further in the coming weeks.

**Comment by lega-land** [comment]
Thanks John! Looking forward for a fix :)

**Comment by lega-land** [comment]
any news on this?

**Comment by lega-land** [comment]
Ok. I'll try with latest versions
