### ISSUE TITLE
Story missing in the report if it fails/throws exception in @BeforeStory method

### ISSUE THREAD

**Issue by nikolaykolev** [serenity-bdd/serenity-core#104]
If a story has @BeforeStory and it throws an exception in the before story method it does not show in the report at all. I'm building with maven, serenity version 1.1.2.

**Comment by wakaleo** [comment]
Is this a duplicate of https://github.com/serenity-bdd/serenity-jbehave/issues/13? If not, it should be in the serenity-behave project.

**Comment by nikolaykolev** [comment]
opened it there, sorry and thanks
