### ISSUE TITLE
Jbehave GivenStories break steps in report

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#1040]
Hi @wakaleo , 

Here an example of a story.file : 
```
Add a new cluster in TMC

Meta:
@issue #TMC-XXXX

Lifecycle:
Before:
Given ...
After:
Outcome: ANY
Then ...

Scenario: Should add a new cluster
Given ...
When ...
Then ...
```

I wanted to re-use existing story with GivenStories : http://jbehave.org/reference/latest/given-stories.html

So now my story looks like :
```
Add a new cluster in TMC

Meta:
@issue #TMC-XXXX

Lifecycle:
After:
Outcome: ANY
Then ...

GivenStories : path/to/myAfterScenario

Scenario: Should add a new cluster
Given ...
When ...
Then ...
```

But now in the report, I only have the **Preconditions** step : 
![image](https://user-images.githubusercontent.com/29480659/33214198-2ab0e1a8-d12b-11e7-8fa2-7544383a3d1e.png)

Is it the correct way to use GivenStories ?

Thanks

**Comment by wakaleo** [comment]
I consider GivenStories to be an anti pattern - Gherkin should not be used for reusable components, and especially not entire stories - so the correct way would be to avoid them entirely. As for the reporting issue here, I will take a look but it may not be for a while.

**Comment by mmanach** [comment]
@wakaleo Can you explain why you think it's an antipattern ? 

For example, if all your tests include the same first login step, how would you do to not have to rewrite these same steps for each scenario?

**Comment by wakaleo** [comment]
A story is a story: it has inputs, actions, and expected outcomes. If you have a login step, it is, as you call it, as step, not a story. So it should be a reusable method (using @Step) or Task (with Screenplay). Then you just have a step "Given Joe is logged on" or "Given Joe is viewing his clusters", which calls this step. And the story that checks the outcome also calls this step.

**Comment by wakaleo** [comment]
Closing as Serenity does not officially support GivenStories
