### ISSUE TITLE
output.formats=xml,json,html => broken links in html reports

### ISSUE THREAD

**Issue by s2oBCN** [serenity-bdd/serenity-core#1041]
Hi John,
I found that if in the **serenity.properties** you put  output.formats=**xml**,json,html then the links in the html reports for the navigation into the detail of a test execution will be broken.

The reason why is the coincidence of two things:
- When the "aggregate" task is executed, it builds the "testOutcomes" from FormatConfiguration.getPreferredFormat(). And if "output.formats=xml,json,html" then it will return XML. And the "testOutcome" will be generated from the **"acceptance-test-run" xml.**

- Then the generated ids of the "testOutcomes" in this aggregation task are taken from the "user-story">id of the "acceptance-test-run" xml. => but this is not equal to the initial id of the testOutcome that was used to generate the html reports of the execution of the tests.

Example:
- json: (usualy used in the aggregation task)
> 
                    {
                        "name": "Match longer descriptions",
                        "id": "demo-of-matching-possibilities;match-longer-descriptions",
                        "testSteps": ["
                       ...
> 
- acceptance-test-run" xml file:
>
                    <acceptance-test-run title="Match longer...
                        <user-story id="demo-of-matching-possibilities"
                    ...
>

I'm sorry I can not make a pull request with the changes in order to solve the problem, because there's more than one option and I don't know which one can you prefer...

The tests are Cucumber features, in this project https://github.com/s2oBCN/demo-cucumber-selenium-web-testing you can add  output.formats=xml,json,html and see that the links to the detailed executions report are broken. But, take into account that if you are using IntelliJ, it will cache the first execution of the "aggregate" task properties. So maybe you have  to restart IntelliJ between the change of the serenity.properties (this was main problem that drives me crazy until finally discovered the behavior).

**Comment by wakaleo** [comment]
Thanks for raising this. The XML format has been discontinued for a while now, so we will probably just remove it entirely. Is there are reason you are producing XML output?

**Comment by s2oBCN** [comment]
Well, it was just because we are generating a junit file per feature. 
But, changing the format to json (even it's not a json, it doesn't matters) it's enought.

**Comment by wakaleo** [comment]
Can you use the SERENITY-JUNIT* files generated by Serenity?

**Comment by s2oBCN** [comment]
No, because we add as properties, into the xml, the tags of the cucumber's scenarios

**Comment by wakaleo** [comment]
Gotcha. Are you able to use the JSON format instead?

**Comment by wakaleo** [comment]
Gotcha. Are you able to use the JSON format instead?

**Comment by s2oBCN** [comment]
Yes, without problems!

**Comment by wakaleo** [comment]
Closing this as the JSON format has replaced the XML and the XML format is no longer supported

**Comment by karthickg3** [comment]
Hi how did you do this?

**Comment by karthickg3** [comment]
I want to merge all json into one jason and transform to xls report to write into jenkins. Please help

we used saxon previously but after upgrade link broken

thanks

**Comment by wakaleo** [comment]
Load the test outcomes into memory using the Serenity APIs

**Comment by karthickg3** [comment]
Sorry which API and how? We are actually using maven serenity and this is done in a batch file btw.

The command is as below


REM TO CONVERT MULTIPLE XML FILES INTO ONE
java -cp "C:\Program Files\SaxonHE\saxon9he.jar" net.sf.saxon.Transform -t -xsl:%XML_REPORT_HOME%\multiple_to_single_xml_transform.xsl -o:%XML_REPORT_HOME%\%TEST_PROJECT_NAME%\multiple_to_single_xml_transform.xml -it:main path=file:///%TEST_PROJECT_DIR%/target/site/serenity

REM TO CREATE THE FINAL XML FILE THAT WILL BE THE INPUT TO XML-EXCEL-CONVERTER
java -cp "C:\Program Files\SaxonHE\saxon9he.jar" net.sf.saxon.Transform -t -xsl:%XML_REPORT_HOME%\FinalResults\final_results_transform_Serenity.xsl -o:%XML_REPORT_HOME%\%TEST_PROJECT_NAME%\%filedatetime%\TestResult_%buildVersion%.xml -it:main path=file:///%COMBINED_XML_LOCATION%/%TEST_PROJECT_NAME%

REM TO CONVERT FINAL XML FILE TO OUTPUT EXCEL FILE
cd %XML_TO_EXCEL_UITILITY_LOCATION%

java -jar xml-excel-converter-0.0.1-SNAPSHOT.jar -inputXml=%COMBINED_XML_LOCATION%/%TEST_PROJECT_NAME%/%filedatetime%/TestResult_%buildVersion%.xml -outputExcel=%XML_REPORT_HOME%/%TEST_PROJECT_NAME%/%filedatetime%/TestResult_%buildVersion%.xlsx
REM :endif

:: if NOT "%content%"=="True" echo The smoketest is not executed. Program is exiting. Please enter any key to exit this!!!!
