### ISSUE TITLE
how to stop test and set test pass or fail using serenity core

### ISSUE THREAD

**Issue by drvgao** [serenity-bdd/serenity-core#1043]
Hi,
It is not an issue, it's about to how to do. I search for this but did not find the ans. It might be very simple question. 

But could you please let me know, how to stop a serenity bdd test and set test outcome as PASS or FAIL.

**Comment by wakaleo** [comment]
Hi,

Github is not a great place to put questions like this: the Google Groups or Rocket Chat (http://serenity-bdd.rocket.chat) forums are likely to get a quicker response.

If you want to stop a test and set the outcome to fail, just throw an exception of your choice. Forcing it to stop and pass would require specific logic in your test case.

**Comment by drvgao** [comment]
Thank you wakaleo!
