### ISSUE TITLE
Serenity Report Exception

### ISSUE THREAD

**Issue by SumantaSarathiChakraborty** [serenity-bdd/serenity-core#1045]
While executing with Serenity latest versions I am getting the following exception:

I have story files in multiple folders and subfolders. Please help.

Failure when constructing testnet.serenitybdd.core.exceptions.SerenityManagedException: org.apache.commons.io.FileUtils.listFilesAndDirs(Ljava/io/File;Lorg/apache/commons/io/filefilter/IOFileFilter;Lorg/apache/commons/io/filefilter/IOFileFilter;)Ljava/util/Collection;
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:215)

**Comment by wakaleo** [comment]
This is a dependency conflict of some sort, probably to do with one of the apache commons libraries. But the line number would indicate that you might not be using the latest versions. What versions are you using?

**Comment by SumantaSarathiChakraborty** [comment]
serenity-core - 1.8.1
serenity-maven-plugin- 1.8.1
serenity-jbehave - 1.34.0
commons-io- 2.6

After upgrading to latest versions only I am getting this exception.

**Comment by wakaleo** [comment]
You will need to check your pom.xml for dependency conflicts. But SerenityReportingRunner.java:215 is an empty line in version 1.34.0; are you sure the error is correct?

**Comment by SumantaSarathiChakraborty** [comment]
I am getting this exception now after cleaning up the POM:

Failure when constructing test  Time elapsed: 1.436 sec  <<< ERROR!
net.serenitybdd.core.exceptions.SerenityManagedException: org.apache.commons.io.FileUtils.listFilesAndDirs(Ljava/io/File;Lorg/apache/commons/io/filefilter/IOFileFilter;Lorg/apache/commons/io/filefilter/IOFileFilter;)Ljava/util/Collection;
	at net.thucydides.core.files.TheDirectoryStructure.maxDepth(TheDirectoryStructure.java:58)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.lambda$maxDirectoryDepthIn$0(FileSystemRequirementsTagProvider.java:150)
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)


I am not sure whether this helps you to understand the issue.

**Comment by wakaleo** [comment]
Try using commons-io 2.5

**Comment by SumantaSarathiChakraborty** [comment]
I have tried with 2.5 as well but the same exception thrown.

**Comment by wakaleo** [comment]
It sound's like a project-specific problem. Can you create a sample project that reproduces the issue? If we can confirm that it is a Serenity issue, we can place it on the backlog. Alternatively, if you need help more quickly or with your specific project, we would be happy to help out in the context of one of our commercial support contracts (see https://johnfergusonsmart.com/serenity-bdd-mentoring#support).
