### ISSUE TITLE
Can't clicking on element

### ISSUE THREAD

**Issue by truyenkv** [serenity-bdd/serenity-core#1047]
Hi Everyone,
I have a table contain username, email, role. Username is enable for click. My data make sure that one argumant => find 1 element. I run script for click on username as "$("//*[contains(text(),'"+user+"']").waitUntilClickable().click(); " and I got issue below:
[main] ERROR net.serenitybdd.core.Serenity - TEST FAILED AT STEP Open detail user screen: a1
[main] ERROR net.serenitybdd.core.Serenity - The following error occurred: Expected enabled element was not enabledBuild info: version: '3.7.0', revision: '2321c73', time: '2017-11-02T22:22:35.584Z'System info: host: 'KVTRUYEN', ip: '10.64.0.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'Driver info: driver.version: unknown

But in fact, I can manual click element. Did you get it? Can you give me the mistake, please share with me many solutions.
Thanks!

**Comment by wakaleo** [comment]
This is unlikely to be a Serenity or Selenium defect, but more a usage issue, so http://serenity-bdd.rocket.chat would be a more appropriate place to ask the question. 

A few usage tips:

$("//*[contains(text(),'"+user+"']") will resolve the element. If you call click(), waitUntilClickable() will not do much more (Serenity automatically waits until it is clickable). Serenity is telling you that Selenium says that the element you have located with your XPath is not enabled. This usually means that the element is not enabled. It could be covered by another element, or it could be that your XPath matches several entries and the first one is invisible or not clickable. 

I will close this here; please feel free to continue the conversation on http://serenity-bdd.rocket.chat, or if you find evidence that this is indeed a Serenity defect.

**Comment by truyenkv** [comment]
Thank you!

**Comment by sudhir-kunchakuri** [comment]
i am getting below ElementClickInterceptedException when trying to click on button.. below is code snippet which i am using..
@wakaleo  :Need your  advice in over coming this error.


Error:
========
org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <a href="#customer/results/IN02729824/linkcontact/IN02729828" aria-disabled="false" data-attach-point="link-contact" class="button button--primary nowrap " data-attr-customer-code="IN02729824" data-attr-contact-code="IN02729828" aria-label="Link roger Federer">...</a> is not clickable at point (545, 17). Other element would receive the click: <div class="utility-bar"></div>

my Step def:
==============
  theActorInTheSpotlight()
                .attemptsTo(
                        Scroll.to(ContactCreatePage.LINK_CONTACT_BUTTON).andAlignToTop()
                );
        theActorInTheSpotlight()
                .attemptsTo(
                        ContactCreateTask.click_on_link_contact_button_to_create_obo_contact()
                );

My Task Method:
================
 public static Performable click_on_link_contact_button_to_create_obo_contact() {
        return Task.where("click on link contact button to create obo contact")
                .then(WaitUntil.the(ContactCreatePage.LINK_CONTACT_BUTTON, WebElementStateMatchers.isPresent()))
                .then(Click.on(ContactCreatePage.LINK_CONTACT_BUTTON))
                .then(WaitUntil.the(PortalPageHeader.CONTACTS_LIST_PAGE_HEADING, WebElementStateMatchers.containsText(PortalPageHeader.CONTACTS_LIST_PAGE_HEADING_MESSAGE))
                .then(WaitUntil.the(ContactsListPage.ADD_CONTACT_BUTTON_PRIOR_HAVING_AT_LEAST_ONE_CONTACT, WebElementStateMatchers.isPresent()))
                );
    }

My Xpath:
============
    public static Target LINK_CONTACT_BUTTON = Target.the("Link contact button")
//            .located(By.xpath("//*[@id=\"Duplicates\"]/tbody/tr/td[5]/a"));
                .located(By.xpath("//a[contains(text(),'Link Contact')]"));

**Comment by globalworming** [comment]
Another element would receive the click.

Check what element that is and deal with it. Usually these are "accept cookie" banners. Accept cookies, hide the element with JS or scroll a bit further.

**Comment by sudhir-kunchakuri** [comment]
i used mouse move over and then issue resolved.. Thanks for your inputs :)

**Comment by diviercp** [comment]
> Utilicé el movimiento del mouse y luego el problema se resolvió. Gracias por sus aportes :)

Como lo hiciste?
