### ISSUE TITLE
When using SauceLabs in combination with screenshots, jobs are created twice in SauceLabs

### ISSUE THREAD

**Issue by debae** [serenity-bdd/serenity-core#105]
I started with the serenity jbehave archetype, so I'm using my AcceptatnceTestSuite which extends SerenityStories to start my selenium tests.
The maven command I'm calling executing is : mvn clean verify -Dsaucelabs.url=http://xxxxx:xxxx-xxx-xxx-xxx@ondemand.saucelabs.com:80/wd/hub -Dsaucelabs.access.key=xxxx-xxxx-xxxx-xxxx -Dsaucelabs.user.idxxxxxx -Dwebdriver.base.url=https://www.xxxxxx.com -Dcapability.combination="{browserName:chrome, platform:Windows 8, version:44.0, build:${bamboo.branch.name}_${bamboo.buildNumber}}" -Dmaven.failsafe.debug=true

Whenever a screenshot will be made with the Photographer a new Driver is created which also triggers a new test/job in SauceLabs. So the end result is a Job which goes through my selenium scenario and another job which has taken empty screenshots ...

This only occurs in combination with a RemoteWebDriver, because when using my local chrome I do not have this behavior and screenshots are working correctly.

**Comment by debae** [comment]
We added our own EventListener and added 
```java
ThucydidesWebdriverManager.inThisTestThread().registerDriverCalled("remote").forDriver(driver);
```
This resulted into the same driver for executing tests and taking screenshots

**Comment by wakaleo** [comment]
Nicely done - this should be integrated somewhere into the core.

On 11 August 2015 at 08:09, Baerten Dennis <notifications@github.com> wrote:

> We added our own EventListener and added
>
> ThucydidesWebdriverManager.inThisTestThread().registerDriverCalled("remote").forDriver(driver);
>
> This resulted into the same driver for executing tests and taking
> screenshots
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/105#issuecomment-129735710>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________
