### ISSUE TITLE
getDriver() method can't be used with appium TouchAction method

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#1052]
<img width="668" alt="screen shot 2017-12-05 at 8 46 48 pm" src="https://user-images.githubusercontent.com/308490/33627385-a4dd461c-d9fd-11e7-858b-0ceedee626a8.png">

Please refer to attached screen shot, I can't use `getDriver()` method with appium `TouchAction` method as it gives compilation error "... can't be applied to org.openqa.selenium.WebDriver"

I tried below but it throws exception

`TouchAction tapCoordinates = new TouchAction((MobileDriver)getDriver());`

**Comment by wakaleo** [comment]
`getDriver()` returns a `WebDriverFacade`, and cannot be all things to all clients. You will need to retrieve the proxied driver and cast it, e.g. something like `new TouchAction((MobileDriver) getDriver().getProxiedDriver())`

**Comment by vikramvi** [comment]
sorry wrong flag, got it working with below

`TouchAction tapCoordinates = new TouchAction(((IOSDriver)((WebDriverFacade) getDriver()).getProxiedDriver()));`
