### ISSUE TITLE
SernityRunner execution is not happening with JUnit

### ISSUE THREAD

**Issue by Jyothishkumarav** [serenity-bdd/serenity-core#1055]
I have written api test cases Using Junit. I would like to Run those using Serenity Runner. But its not happening. Test cases were executed as normal Junit Test cases. So report file is also not generated.

aggregate phase has been executed.but still its is not generating  the report.

------------------------------------------------------
 T E S T S
-------------------------------------------------------
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Running apitest.APITest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.038 sec - in apitest.APITest
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- serenity-maven-plugin:1.7.2:aggregate (serenity-reports) @ AppApiTests ---
[INFO] current_project.base.dir: 
AppApiTests
[INFO] Generating test results for 0 tests
[INFO] 0 requirements loaded after 0 ms
[INFO] 0 related requirements found after 0 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 0 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 40 ms
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18:verify (default) @ AppApiTests ---
[INFO] Failsafe report directory: 
AppApiTests\target\failsafe-reports

**Comment by wakaleo** [comment]
How are you trying to run your tests with Serenity?

**Comment by Jyothishkumarav** [comment]
I can see my test were executed but report files were partially generated and i am missing index.html file

**Comment by Jyothishkumarav** [comment]
@wakaleo  am triggering from maven using mvn clean verify

**Comment by Jyothishkumarav** [comment]
Adding to above @wakaleo am using a mutimodule project . when i checked the console i can see.
4 Scenarios (4 passed)
6 Steps (6 passed)
0m11.387s

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.492 sec - in webtest.TestCore
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

Results :




Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- serenity-maven-plugin:1.7.2:aggregate (serenity-reports) @ AppFeatureTests ---
[INFO] current_project.base.dir: 
AppFeatureTests
[INFO] Generating test results for 0 tests
[INFO] 0 requirements loaded after 0 ms
[INFO] 0 related requirements found after 0 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 0 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 40 ms

**Comment by wakaleo** [comment]
You need to run the aggregate task in the module containing the tests, not in the parent module.

**Comment by wakaleo** [comment]
Closed for lack of activity.
