### ISSUE TITLE
Wrong font-awesome icon for IE

### ISSUE THREAD

**Issue by obecker** [serenity-bdd/serenity-core#1057]
The class `net.thucydides.core.model.TitleBuilder` defines several icons to be displayed in the HTML report depending on the current context. For the context `ie` the icon class currently is `fa-ie`.

See line 28 in `TitleBuilder`:

    FONTAWESOME_ICONS_FOR_COMMON_CONTEXTS.put("ie", "<i class=\"fa fa-ie\" aria-hidden=\"true\"></i>");

However, the included font-awesome styles don't know an icon for `fa-ie`, instead the class to be used is `fa-internet-explorer`. So please change the css class in the line above from `fa-ie` into `fa-internet-explorer`.

**Comment by obecker** [comment]
By the way, it is not clear to me why the context is `ie`, but the driver is `iexplorer`. What is the correct way to specify a webtest for the internet explorer? Currently both driver names (`ie` and `iexplorer`) seem to work - however with different context outputs in the report (`ie` creates the wrong font-awesome icon, `iexplorer` creates the text `IEXPLORER`).

**Comment by wakaleo** [comment]
Thanks for raising this. Could you submit a PR?

**Comment by obecker** [comment]
Done. By the way: the `context` property isn't documented on http://thucydides.info/docs/serenity/#_serenity_system_properties_and_configuration

**Comment by wakaleo** [comment]
Thanks for your contribution! I will make sure the context property appears in the new (in-progress) documentation.

**Comment by obecker** [comment]
Fixed in 1.8.5
