### ISSUE TITLE
Using ngWebdriver with Serenity

### ISSUE THREAD

**Issue by PadmajaSampath** [serenity-bdd/serenity-core#1058]
Hi,

I am trying to use ngWebdriver with Serenity Core and I have issues with dependencies in pom.xml.

I have serenity core version 1.7.0 and 0.9.1 as ngWebdriver. 

I tried various other versions and nothing helped. I am new to this, so any help would be appreciated,

Thanks

**Comment by wakaleo** [comment]
How are you trying to use ngWebDriver with Serenity?

**Comment by PadmajaSampath** [comment]
Thanks for getting back.

Trying to automate AngularJS application using Serenity. I am interested mostly on the wait function. Cant use Protractor. So trying to figure out this option.

Hope that makes sense.

**Comment by wakaleo** [comment]
Do you have a code sample? There is no built-in integration with ngWebDriver, so it would depend how you are calling the library.

**Comment by PadmajaSampath** [comment]
I am just trying out with a sample from Web. See below:

**Using IE instead of Chrome **

public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver", "c:\\Grid\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
                driver.get("http://juliemr.github.io/protractor-demo/");
		ngDriver = new NgWebDriver((JavascriptExecutor) driver);
		ngDriver.waitForAngularRequestsToFinish();
                driver.findElement(ByAngular.model("first")).sendKeys("2");
                driver.findElement(ByAngular.model("second")).sendKeys("2");
                //driver.findElement(By.id("gobutton")).click();
                driver.findElement(ByAngular.buttonText("Go!")).click();
        }
	ngDriver.waitForAngularRequestsToFinish();

**Comment by PadmajaSampath** [comment]
**pom.xml** 

**<serenity.version>1.7.0</serenity.version>**

<dependencies>
	
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.5</version>
		</dependency>
		
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>com.paulhammant</groupId>
			<artifactId>ngwebdriver</artifactId>
			<version>0.9.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.5.2</version>
		</dependency>
		
		<dependency>
    		<groupId>org.apache.poi</groupId>
    		<artifactId>poi-ooxml</artifactId>
    		<version>3.9</version>
		</dependency>
	
		<dependency>
		  <groupId>com.oracle</groupId>
		  <artifactId>ojdbc6</artifactId>
		  <version>11.2.0.4</version>
		</dependency> 
	
	</dependencies>

**Comment by wakaleo** [comment]
The code sample you gave doesn't have any Serenity logic in it. What are you expecting Serenity to do?

**Comment by PadmajaSampath** [comment]
Hi

**Without** ngWebDriver dependency from pom.xml (serenity core version 1.4.0) my test pack runs successfully.

If I include ngWebDriver dependency (version 0.9.1) in pom.xml I get the following error.
java.lang.NoSuchMethodError: org.openqa.selenium.support.pagefactory.Annotations.buildByFromFindBy(Lorg/openqa/selenium/support/FindBy;)Lorg/openqa/selenium/By;

No changes in code / test classes. So was just trying to understand is there a serenity core version in pom.xml I could use which is compatible with ngWebDriver.

Thanks for listening.

**Comment by wakaleo** [comment]
You have a dependency conflict, most likely with the version of Selenium that ngWebDriver is using.

**Comment by PadmajaSampath** [comment]
Thanks. But I am not sure how to get around this as I couldn't get much info on the compatible versions from maven repository (ngWebDriver). Says 2.35 for org.selenium.

Any thoughts on getting around this problem would be of great help.

**Comment by wakaleo** [comment]
Try using the most recent versions of each library.

**Comment by PadmajaSampath** [comment]
Thanks. I think the issue was to do with IE. I tried with Chrome and all works like a charm. Thanks for the help. But we use IE as our standard browser :-(

**Comment by wakaleo** [comment]
OK, I'll close this. On a site note, you are making life a bit hard with IE ;-)
