### ISSUE TITLE
Double registration BaseStepListener

### ISSUE THREAD

**Issue by ihostage** [serenity-bdd/serenity-core#106]
If i have in Cucumber step class constructor with Pages parameter

```java
public class CucumberSteps {
    ...
    public CucumberSteps(Pages pages) {}
    ...
}

```

i got error

```
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
	at net.thucydides.core.steps.BaseStepListener.getCurrentTestOutcome(BaseStepListener.java:212)
	at net.thucydides.core.steps.BaseStepListener.updateExampleTableIfNecessary(BaseStepListener.java:470)
	at net.thucydides.core.steps.BaseStepListener.currentStepDone(BaseStepListener.java:550)
	at net.thucydides.core.steps.BaseStepListener.stepFinished(BaseStepListener.java:465)
	at net.thucydides.core.steps.StepEventBus.stepFinished(StepEventBus.java:289)
	at net.serenitybdd.cucumber.SerenityReporter.result(SerenityReporter.java:522)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy19.result(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.result(JUnitReporter.java:111)
	at cucumber.runtime.Runtime.runStep(Runtime.java:309)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
```

Initial registration ``BaseStepListener`` performed in ``SerenityListeners:registerListeners``. But if i have ``constructor(Pages)`` 

```java
SerenityObjectFactory.createNewPageEnabledStepCandidate(...)
...
Serenity:initialize(...)
...
Serenity:initStepListener(...)
``` 
registered ``BaseStepListener`` again.

Check ```(!registeredListeners.contains(listener))``` not worked for this case.

**Comment by ihostage** [comment]
Now, i use work around :smile:
```java
public class CucumberSteps {
    @ManagedPages
    private Pages pages;

```

**Comment by wakaleo** [comment]
Using the Pages class or the @ManagedPages annotation is no longer necessary - simply declare your page objects in your step libraries.

**Comment by ihostage** [comment]
Yes, that's what I do :smile:  But if I want to use ``pages().isCurrentPageAt(PageObject.class)`` in steps, I need constructor injection Pages object. Or is there another option?

**Comment by wakaleo** [comment]
That does sound like a bug then, but the annotation would be a better way,
especially if it works :-)

On 8 August 2015 at 05:23, Sergey Morgunov <notifications@github.com> wrote:

> Yes, that's what I do [image: :smile:] But if I want to use
> pages().isCurrentPageAt(PageObject.class) in steps, I need constructor
> injection Pages object. Or is there another option?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/106#issuecomment-128908235>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by ihostage** [comment]
Yes :+1: but to be honest, I use ``CucumberSteps extend ScenarioSteps``. I know it's not right and I need to use ``@Steps`` injection SerenitySteps in my CucumberSteps (as written in the documentation). But I really want to use ScenarioSteps in CucumberSteps.

**Comment by wakaleo** [comment]
Why do you need ScenarioSteps in CucumberSteps? It's just a convenience class, your step libraries don't need to extend it.

**Comment by ihostage** [comment]
I don't like, what "CucumberSteps" is proxy. I store data in session variables and my Steps is mix "CucumberSteps" and "SerenitySteps".
That my example. I can simultaneously:
1. Inject UserSteps by Serenity ``@Steps`` annotation
2. Mapping step of cucumber to methods of UserSteps

```java
public class WebSteps extends ScenarioSteps {
    LoginPage loginPage;

    @Steps
    UserSteps user;

    public WebSteps(Pages pages) {
        super(pages);
    }

    @Step
    @When("^...$")
    public void openLoginPage() {
        loginPage.open();
        currentPageShouldBeLoginPage();
    }

    @Step
    @And("^...$")
    public void typeLoginAndPassword() {
        loginPage.auth(user.login(), user.password());
    }

    @Step
    @Then("^...$")
    public void currentPageShouldBeLoginPage() {
        pages().isCurrentPageAt(LoginPage.class);
    }

}
```
Similarly UserSteps
```java
public class UserSteps extends ScenarioSteps {

   private static final String LOGIN_VARIABLE_NAME = UserSteps.class.getCanonicalName() + "#login";

    private static final String PASSWORD_VARIABLE_NAME = UserSteps.class.getCanonicalName() + "#password";

    @Step
    @Given("^... (.+)$")
    public void shouldExist(final String login) {
        assertThat(login, not(isEmptyOrNullString()));
        ...
        setSessionVariable(LOGIN_VARIABLE_NAME).to(login);
    }

    public String login() {
        return sessionVariableCalled(LOGIN_VARIABLE_NAME).toString();
    }

    public String password() {
        return sessionVariableCalled(PASSWORD_VARIABLE_NAME).toString();
    }

}
```
You revert changes in this commit https://github.com/serenity-bdd/serenity-core/commit/7ae80bfa70188b94cae87d94fbd0820091d958dc? Something wrong?

**Comment by wakaleo** [comment]
The use of ScenariosSteps and the @Step annotation in WebSteps is redundant
- Serenity will work fine with just the @Given, @When and @Then annotations
from Cucumber.

If you need the Pages variable, just declare a variable of type Pages;

private Pages pages

You don't need to extend ScenarioSteps or have a constructor.

So in both cases here you don't need the ScenarioSteps class.

The code you have in UserSteps would work fine without extending the
ScenarioSteps class
Commit 7ae80bf
<https://github.com/serenity-bdd/serenity-core/commit/7ae80bfa70188b94cae87d94fbd0820091d958dc>
  broke a lot of unit tests and was preventing me doing a release - I will
come back to it later on to figure out what is going on.

On 12 August 2015 at 15:13, Sergey Morgunov <notifications@github.com>
wrote:

> I don't like, what "CucumberSteps" is proxy. I store data in session
> variables and my Steps is mix "CucumberSteps" and "SerenitySteps".
> That my example. I can simultaneously:
> 1. Inject UserSteps by Serenity @Steps annotation
> 2. Mapping step of cucumber to methods of UserSteps
>
> public class WebSteps extends ScenarioSteps {
>     LoginPage loginPage;
>
>     @Steps
>     UserSteps user;
>
>     public WebSteps(Pages pages) {
>         super(pages);
>     }
>
>     @Step
>     @When("^...$")
>     public void openLoginPage() {
>         loginPage.open();
>         currentPageShouldBeLoginPage();
>     }
>
>     @Step
>     @And("^...$")
>     public void typeLoginAndPassword() {
>         loginPage.auth(user.login(), user.password());
>     }
>
>     @Step
>     @Then("^...$")
>     public void currentPageShouldBeLoginPage() {
>         pages().isCurrentPageAt(LoginPage.class);
>     }
>
> }
>
> Similarly UserSteps
>
> public class UserSteps extends ScenarioSteps {
>
>    private static final String LOGIN_VARIABLE_NAME = UserSteps.class.getCanonicalName() + "#login";
>
>     private static final String PASSWORD_VARIABLE_NAME = UserSteps.class.getCanonicalName() + "#password";
>
>     @Step
>     @Given("^... (.+)$")
>     public void shouldExist(final String login) {
>         assertThat(login, not(isEmptyOrNullString()));
>         ...
>         setSessionVariable(LOGIN_VARIABLE_NAME).to(login);
>     }
>
>     public String login() {
>         return sessionVariableCalled(LOGIN_VARIABLE_NAME).toString();
>     }
>
>     public String password() {
>         return sessionVariableCalled(PASSWORD_VARIABLE_NAME).toString();
>     }
>
> }
>
> You revert changes in this commit 7ae80bf
> <https://github.com/serenity-bdd/serenity-core/commit/7ae80bfa70188b94cae87d94fbd0820091d958dc>?
> Something wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/106#issuecomment-130317734>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by ihostage** [comment]
Yes, if i have ``Pages``-member in all step classes, it worked :smile: But, i want have ``Pages``-member in parent class (``ScenarioSteps`` good example). But if ``Pages`` in parent class, it not injected without ``Pages``-constructor.
Instance in my example:
```java
WebSteps - NOT NULL
    |---- pages - NOT NULL
    |---- UserSteps - NOT NULL
            |---- pages - NULL
```
Becouse pages is not member of ``UserSteps``, it is member ``ScenarioSteps``.

**Comment by wakaleo** [comment]
That is a bug that could be fixed.

On 12 August 2015 at 15:48, Sergey Morgunov <notifications@github.com>
wrote:

> Yes, if i have Pages-member in all step classes, it worked [image:
> :smile:] But, i want have Pages-member in parent class (ScenarioSteps
> good example). But if Pages in parent class, it not injected without Pages
> -constructor.
> Instance in my example:
>
> WebSteps - NOT NULL
>     |---- pages - NOT NULL
>     |---- UserSteps - NOT NULL
>             |---- pages - NULL
>
> Becouse pages is not member of UserSteps, it is member ScenarioSteps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/106#issuecomment-130328211>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by ihostage** [comment]
Ok. I thought, what Pages constructor is right way for this case.
I need create another issue and pull request? :smile:

**Comment by ihostage** [comment]
I think this should help, but need to check
```patch
diff --git a/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java b/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java
index fdf8d47..eec98ef 100644
--- a/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java
+++ b/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java
@@ -8,6 +8,7 @@ import net.serenitybdd.core.di.DependencyInjector;
 import net.serenitybdd.core.injectors.EnvironmentDependencyInjector;
 import net.sf.cglib.proxy.Enhancer;
 import net.sf.cglib.proxy.MethodInterceptor;
+import net.thucydides.core.annotations.Fields;
 import net.thucydides.core.guice.Injectors;
 import net.thucydides.core.pages.Pages;
 import net.thucydides.core.steps.di.DependencyInjectorService;
@@ -200,7 +201,7 @@ public class StepFactory {
     }

     private <T> boolean hasAPagesField(final Class<T> stepLibraryClass) {
-        ImmutableSet<Field> fields = copyOf(stepLibraryClass.getDeclaredFields());
+        ImmutableSet<Field> fields = copyOf(Fields.of(stepLibraryClass).allFields());
         return Iterables.any(fields, ofTypePages());

     }
```

**Comment by wakaleo** [comment]
Yes, that should work. There should be a unit test for that somewhere.

On 12 August 2015 at 16:43, Sergey Morgunov <notifications@github.com>
wrote:

> I think this should help, but need to check
>
> diff --git a/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java b/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java
> index fdf8d47..eec98ef 100644--- a/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java+++ b/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java@@ -8,6 +8,7 @@ import net.serenitybdd.core.di.DependencyInjector;
>  import net.serenitybdd.core.injectors.EnvironmentDependencyInjector;
>  import net.sf.cglib.proxy.Enhancer;
>  import net.sf.cglib.proxy.MethodInterceptor;+import net.thucydides.core.annotations.Fields;
>  import net.thucydides.core.guice.Injectors;
>  import net.thucydides.core.pages.Pages;
>  import net.thucydides.core.steps.di.DependencyInjectorService;@@ -200,7 +201,7 @@ public class StepFactory {
>      }
>
>      private <T> boolean hasAPagesField(final Class<T> stepLibraryClass) {-        ImmutableSet<Field> fields = copyOf(stepLibraryClass.getDeclaredFields());+        ImmutableSet<Field> fields = copyOf(Fields.of(stepLibraryClass).allFields());
>          return Iterables.any(fields, ofTypePages());
>
>      }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/106#issuecomment-130347880>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by ihostage** [comment]
Sorry. And in ``injectPagesInto`` function
```patch
@@ -174,7 +175,7 @@ public class StepFactory {
         if (ScenarioSteps.class.isAssignableFrom(stepLibraryClass))  {
             ((ScenarioSteps) newStepLibrary).setPages(pages);
         } else if (hasAPagesField(stepLibraryClass)) {
-            ImmutableSet<Field> fields = copyOf(stepLibraryClass.getDeclaredFields());
+            ImmutableSet<Field> fields = copyOf(Fields.of(stepLibraryClass).allFields());
             Field pagesField =  Iterables.find(fields, ofTypePages());
             pagesField.setAccessible(true);
             try {
```

**Comment by wakaleo** [comment]
Could you do a pull request?

On 12 August 2015 at 16:50, Sergey Morgunov <notifications@github.com>
wrote:

> Sorry. And in injectPagesInto function
>
> @@ -174,7 +175,7 @@ public class StepFactory {
>          if (ScenarioSteps.class.isAssignableFrom(stepLibraryClass))  {
>              ((ScenarioSteps) newStepLibrary).setPages(pages);
>          } else if (hasAPagesField(stepLibraryClass)) {-            ImmutableSet<Field> fields = copyOf(stepLibraryClass.getDeclaredFields());+            ImmutableSet<Field> fields = copyOf(Fields.of(stepLibraryClass).allFields());
>              Field pagesField =  Iterables.find(fields, ofTypePages());
>              pagesField.setAccessible(true);
>              try {
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/106#issuecomment-130351380>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by ihostage** [comment]
Yes, of course
