### ISSUE TITLE
Dashboard Settings not working with Gradle plugin

### ISSUE THREAD

**Issue by Saieph** [serenity-bdd/serenity-core#1060]
Using serenity (core, rest-assured, report-resources) version 1.8.5, and serenity-cucumber version 1.6.5 : 
When I execute my unit runners for cucumber, I expect the aggregated report to conform to my serenity properties. I have this switch set: `dashboard.tag.list = capability,feature,story`.
However, I am observing that the generated report is still including tags on the dashboard.

![screen shot 2017-12-12 at 12 04 32 pm](https://user-images.githubusercontent.com/7396713/33897877-a480fdbc-df34-11e7-9474-ab640c6dadf4.png)

**Comment by tfrothingham** [comment]
Also seeing this issue using Junit runs, currently using serenity 1.8.21
