### ISSUE TITLE
JBehave scenario's numbers are hidden in the report

### ISSUE THREAD

**Issue by ThirumalaiVigneshM** [serenity-bdd/serenity-core#1061]
Hi,

The JBehave scenario's numbers are hidden in the serenity report. 
Ex: Scenario: 2. TC12959: Verify 7 days are shown in desktop view

Ref the screenshot of the report.

Also, the serenity report is not preserving the execution order of scenarios in the story file in its report.

<img width="120" alt="screen shot 2017-12-14 at 14 16 34" src="https://user-images.githubusercontent.com/34517182/33996834-519619dc-e0da-11e7-976f-c7747b0b2e38.png">

**Comment by wakaleo** [comment]
This is JBehave related, could you raise the issue in the serenity-jbehave project?

**Comment by ThirumalaiVigneshM** [comment]
Sure Thank You. 

Will you be able to  reply for my comment in [](https://github.com/serenity-bdd/serenity-core/issues/678). It will be very helpful. 

Thanks,
Thiru
