### ISSUE TITLE
Screenshot configuration does not work correctly at task/interaction/performable level

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1065]
If screenshots are configured as per the [Serenity BDD Tip: fine-tuning screenshots in your living documentation](https://johnfergusonsmart.com/serenity-bdd-tip-fine-tuning-screenshots-living-documentation/) article, any of the suggested values cause screenshots to always be configured at the top level. (This is putting aside the typo in the article that states that `for_failure` can be used which causes a run-time exception - `for_failures` is the correct value.)

This can be demonstrated by configuring [these settings](https://github.com/nbarrett/serenity-core/commit/d4130dcdcf825a0710d0dd79032bd2b7342e9c41#diff-2df175a8eb511fd0b821bd680106a822R1) on the to-do journey demo and running the tests using `DeleteTodos`. This causes the report to appear as follows (e.g. you can't avoid screenshots on the top level steps unless they are non-screenplay cucumber steps):

![image](https://user-images.githubusercontent.com/626941/34172406-dc2a40d8-e4e9-11e7-8e17-63a2e1377eb6.png)

Note that I've created a branch [here](https://github.com/nbarrett/serenity-core/tree/issue-1065) with all those changes made and serenity wound to the latest version e.g.

```
 <serenity.version>1.8.12</serenity.version>
 <serenity.cucumber.version>1.6.7</serenity.cucumber.version>
```

**Comment by wakaleo** [comment]
Hmmm, I don’t think this is possible with Screenplay. This feature looks at the stack trace of the current method, to see if any calling methods have the annotation in question. But with Screenplay, you pass round objects and it’s less clear what will appear in the stack trace. I’m happy to be proved wrong though

**Comment by nbarrett** [comment]
I'm confused with your comment @wakaleo - the configuration and article are specifically about screenplay aren't they? Or are you saying those settings only work for a Junit flavour of screenplay and not cucumber? Note that after some playing around, I can get screenshots to not show at the top level as long as remove ALL of the following properties:
```
serenity {
take.screenshots.for.performables = for_failures
take.screenshots.for.interactions = for_failures
take.screenshots.for.questions = for_failures
take.screenshots.for.tasks = for_failures
...
}
```
...and just have: 
```
serenity {
take.screenshots= for_failures
...
}
```

**Comment by wakaleo** [comment]
Sorry, it must be a different issue then. Those should work everywhere, so that would be a bug.
