### ISSUE TITLE
Can not generate reports when running failed cucumber scenario outline

### ISSUE THREAD

**Issue by DuanYuePeng** [serenity-bdd/serenity-core#1066]
serenity-core 1.6.5, serenity-cucumber 1.5.15  

I have a scenario outline, like this:  
```
Feature: view page
  Just view some page

  @debug
  Scenario Outline: view some page
    Given Alan is a client
    When Alan view the <Page Name> page
    Then Alan should see the <Page Name> page

    Examples:
    | Page Name |
    | index     |
    | login     |
```
When I run it using the following cucumber option `@target/test-classes/cucumber-failed.txt`, serenity can not generate reports. The content of 'cucumber-failed.txt' is as below  
```
features/view/view_page.feature:13
```
Please notice that it is the second example of the scenario outline. When I am using the first example, the issue won't reproduce.

So I traced the source code and I found there may be a bug in SerenityReporter.java
```
private void finishExample() {
        StepEventBus.getEventBus().exampleFinished();
        exampleCount--;
        if (exampleCount == 0) {
            examplesRunning = false;
            List<Step> steps = currentScenarioDefinition.getSteps();
            StringBuffer scenarioOutlineBuffer = new StringBuffer();
            for(Step step : steps) {
                scenarioOutlineBuffer.append(step.getKeyword()).append(step.getText()).append("\n\r");
            }
            String scenarioOutline = scenarioOutlineBuffer.toString();
            table.setScenarioOutline(scenarioOutline);
            generateReports();
        } else {
            examplesRunning = true;
        }
    }
```
In this case, the exampleCount did not reach 0, because the first scenario example did not run. So, the generateReports never got executed.

I have a very simple project which can reproduce this issue, as below

[simple_serenity.zip](https://github.com/serenity-bdd/serenity-core/files/1573763/simple_serenity.zip)

**Comment by wakaleo** [comment]
Thanks for identifying this issue. The problem seems to come from an incorrect evaluation of the number of examples to be executed at line 383 of the same file (in the current version). If you would like to troubleshoot further and find a way to correctly calculate this value for this scenario, I'd be happy to review a PR.

**Comment by DuanYuePeng** [comment]
That's fine. I'll do it.

**Comment by DuanYuePeng** [comment]
I created the [pull request](https://github.com/serenity-bdd/serenity-cucumber/pull/122), please review.

**Comment by wakaleo** [comment]
Merged into the code base and deployed
