### ISSUE TITLE
Unable to override webdriver.provided.{type} property at run time 

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1071]
On my project I have a separate `DriverSource` implementation for each of the supported browsers, as they have project-specific configuration requirements which can't be configured using basic serenity.driver.capabilities properties. The wiring to the `DriverSource` implementation works fine if a value is hard-coded in the serenity.conf file e.g.  
 
```
webdriver.provided.mydriver = com.acme.MyPhantomJSDriver
```

However, if I try to provide a runtime system property override for `webdriver.provided.mydriver` that specifies the required implementation, this value is ignored (e.g. it uses only the existing value in serenity.conf). 

If I omit the webdriver.provided.{type} property in serenity.conf then the following exception is thrown:

```
Caused by: java.lang.NullPointerException: No provider implementation was specified in 'webdriver.provided.'mydriver
```

What am I doing wrong please? Version-wise, I'm still at serenity 1.5.7 due to our project's continued dependency on cucumber 1.x (this problem was discussed in #1020).

**Comment by nbarrett** [comment]
My project workaround has been to physically re-write the `serenity.conf` property at run-time but I'd like to not have to do this. Any thoughts please @wakaleo ?

**Comment by nbarrett** [comment]
Might this be fixed in 1.9.9 too?

**Comment by wakaleo** [comment]
Have you tried?

**Comment by nbarrett** [comment]
Yes, I've tried in 1.9.10 and I still get the same. for instance
```
    @Before
    public void before() {
        System.setProperty("webdriver.provided.ucdriver", "uk.gov.dwp.universe.serenity.browser.UCHtmlUnitDriver");
}
```
throws
```
java.lang.NullPointerException: No provider implementation was specified in 'webdriver.provided.'ucdriver

	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:805)
	at net.thucydides.core.webdriver.ProvidedDriverConfiguration.getDriverSource(ProvidedDriverConfiguration.java:32)
```

**Comment by nbarrett** [comment]
I think I can see what's wrong now. In `net.thucydides.core.webdriver.ProvidedDriverConfiguration`
on line 31 there is
`environmentVariables.getProperty("webdriver.provided." + providedDriverType)`

But if this was replaced by `SystemEnvironmentVariables.createEnvironmentVariables().getProperty("webdriver.provided." + providedDriverType)` then it would pick up the system property override. 

Want me to raise a PR for this?

**Comment by wakaleo** [comment]
Sure, please do!

**Comment by chronicideas** [comment]
Would love for this to be addressed

**Comment by nbarrett** [comment]
Sorry, I'll do this this week! I found another workaround by using a TypeSafe config file (serenity.conf) and using an environment variable instead which is overridable instead but this is not an obvious solution.

**Comment by chronicideas** [comment]
Thanks for replying so quickly! For the workaround with serenity.conf, if I want to overwrite the value do I just setProperty or is it still read as an environment variable? Sorry hope that makes, sense been a long day. I’ve created a dockerised selenium Grid and I use two custom drivers with WebDriverManager and want to run two jobs on my Jenkins slave agent, one for my Custom chrome driver and one for my custom Firefox driver (where I set the class as a value for one of my properties in the serenity.properties currently)

**Comment by nbarrett** [comment]
Hi @chronicideas - I think what you should be able to do is something like this:
```
webdriver {
  driver = provided
  provided.type = mydriver
  provided.mydriver = my.default.driver.named.CustomDriverOne
  provided.mydriver = ${?my_overriden_driver}
}
```

Where `my_overriden_driver` is an environment variable. If this is not set, the test would use `my.default.driver.named.CustomDriverOne`, but if it was set, it would use this value instead.

**Comment by chronicideas** [comment]
Thanks Nick. I ended up doing something similar to this but good to know that it falls back to the default one. Cheers.

**Comment by chronicideas** [comment]
Hi there, any updates on this possibly? cheers.
