### ISSUE TITLE
Any method to do a SOAP request using Serenity 

### ISSUE THREAD

**Issue by cksoman** [serenity-bdd/serenity-core#1073]
I want to test a soap request using Serenity,Could you please suggest any method

**Comment by wakaleo** [comment]
This is a question, not a defect, so it would be better raised on the Serenity User Groups or the Rocket Chat channel (http://serenity-bdd.rocket.chat). There is no special support for SOAP in Serenity, but you would just invoke your SOAP service in exactly the same way as you would do from normal Java code.
