### ISSUE TITLE
How to add WebDriverEventListener to driver?

### ISSUE THREAD

**Issue by jetfree7** [serenity-bdd/serenity-core#1077]
Hi guys,

I have a need to check some condition before every click. This problem can be resolved by implementing new WebDriverEventListener and registering it in webdriver.
After a long search, I didn't find a good possibility to do this. Point me please if I missed something.

**Comment by wakaleo** [comment]
You could use a custom driver and add the listener there. Alternatively you use Screenplay and implement your own Click interaction class.

**Comment by jetfree7** [comment]
Thanks!

**Comment by skhandekar1** [comment]
Please can someone explain with example how to do this. Not everyone is a guru in java programming. I am struggling a lot in getting this working
