### ISSUE TITLE
report generation is broken

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#1079]
1.8.20 in this version, with command 

mvn clean verify -Dcucumber.options="src/test/resources/features/SmavaWebAnalyticsDataTableUserStories.feature"

report generation is not working

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:35 min
[INFO] Finished at: 2018-01-11T14:11:46+01:00
[INFO] Final Memory: 34M/412M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project WebAnalytics_Automation_RegressionTesting: There are test failures.
```
pom.xml

https://gist.github.com/vikramvi/34ed1fad4f38dbfac48b186d702e17ef

**Comment by wakaleo** [comment]
It says there are test failures. To generate the report after test failures, yo need to use the maven-failsafe-plugin, not the maven-surefire-plugin

**Comment by oleksandrkol** [comment]
Hi, I use latest versions of Serenity, but also have issue with reports.
Dependencies in Gradle:

compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.8.20'
compile group: 'net.serenity-bdd', name: 'serenity-report-resources', version: '1.8.20'
compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.8.20'
compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '1.8.20'

5:21:58 PM: Executing task 'aggregate'...
This file was not a valid JSON Serenity test report: 0565107ef2bcbb246e4e6a29d8bcbcc407e3aa7a002fc81cdc7ee8fd07e0e7d4.json
java.lang.NumberFormatException: For input string: "2018-01-09T16:38:20.646+02:00[Europe/Helsinki]"

In this file I have "startTime": "2018-01-09T16:38:20.646+02:00[Europe/Helsinki]"
and if I change it to, like "startTime": 1514467611614 it works ok.
Is it an issue in datetime serialization inside Serenity?

**Comment by vikramvi** [comment]
@wakaleo  adding maven-failsafe-plugin fixed the issue.

@oleksandrkol  you can refer to working pom.xml https://gist.github.com/vikramvi/db74c2b65319d938b5d19da0405405ae

I'm closing this issue as resolved working

**Comment by pacho0323** [comment]
A mi tambien me sale este error:
> Task :aggregate
Generating Serenity Reports for Traductor to directory C:\Users\juan\eclipse-wor
kspace\Traductor\target\site\serenity
this file was not a valid JSON Serenity test report: 2b7517a7a845615f77f2ee1bce4
be6f6e73cdabbf2a84416dcc4738a0620a6d0.json
java.lang.NumberFormatException: For input string: "2018-09-23T12:13:15.759-05:0
0[America/Bogota]"
Merging requirements = []
Merging requirements = []
Merged requirements set = []
java.nio.file.NoSuchFileException: target\site\serenity
java.nio.file.NoSuchFileException: target\site\serenity
java.nio.file.NoSuchFileException: target\site\serenity
java.nio.file.NoSuchFileException: target\site\serenity

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:com
mand_line_warnings

BUILD SUCCESSFUL in 6s
5 actionable tasks: 1 executed, 4 up-to-date

Estoy usando gradle alguien me puede decir como lo soluciono?

el build gradle lo tengo asi:

apply plugin: 'java-library'

// In this section you declare where to find the dependencies of your project
repositories {
    mavenLocal()
    jcenter()
}

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.1.1") 
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'  

dependencies {
 testCompile 'net.serenity-bdd:serenity-core:1.1.1'                  
    testCompile 'net.serenity-bdd:serenity-junit:1.1.1'                
    testCompile('junit:junit:4.12')
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('org.slf4j:slf4j-simple:1.7.7')
   
compile group: 'net.serenity-bdd', name: 'serenity-cucumber', version: '1.9.15'
// compile group: 'net.serenity-bdd', name: 'serenity-core', version: '1.9.45'
testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.3.1'
//compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '1.8.20'
}
gradle.startParameter.continueOnFailure = true
