### ISSUE TITLE
PageFactory fix is not working since 1.8.0

### ISSUE THREAD

**Issue by risinek** [serenity-bdd/serenity-core#1081]
Hello, 
we just updated dependencies in maven project, and found out that the PageFactory is not resolving issue, when _Can not set io.appium.java_client.MobileElement field com.*******.emailField to org.openqa.selenium.remote.RemoteWebElement_ error appears, when using MobileElements on Pages.
Seems like this code does not work since 1.8.0.. I can't figure out, what's wrong and how to use it now with latest serenity-core version.

`public class AppiumPageObject extends PageObject {
	public AppiumPageObject(WebDriver driver) {
		super(driver);
		PageFactory.initElements(new AppiumFieldDecorator(((WebDriverFacade) getDriver()).getProxiedDriver()), this);
	}`

**Comment by wakaleo** [comment]
I believe this is a known bug in the appium Java client. Have you tried with 1.8.21 which uses the latest appium beta version?

**Comment by risinek** [comment]
Thanks for you answer, it is probably same issue as you mentioned - #1053.. I tried again with serenity 1.8.21, java-client 6.0.0-BETA2 and appium server 1.7.1, but still the same problem. I will follow that 1053 issue for more info.

**Comment by cliviu** [comment]
@risinek: I have a question: What happens when you are using a version > 1.8.0   but no AppiumPageObject but normal PageObject ?

**Comment by risinek** [comment]
AppiumPageObject is just extended PageObject, I created it to add PageFactory config.. If I use directly PageObject, it should be the same as removing he PageFactory line

**Comment by cliviu** [comment]
@risinek, and, when you remove the PageFactory line, still have the issue ?

**Comment by risinek** [comment]
yes

**Comment by narendra-chandratre** [comment]
Any working solution?

**Comment by wakaleo** [comment]
@narendra-chandratre Issues like this are generally project-related and can be fixed more easily if we can review your project directly. If this work would be helpful for your organisation, we have a number of support options that would enable us to place a higher priority on the issue (see http://johnfergusonsmart.com/serenity-bdd-mentoring/#support).
