### ISSUE TITLE
 Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.8.21:check failed: THUCYDIDES TEST FAILURES: ERROR COUNT: 0 FAILURE COUNT: 1 COMPROMISED COUNT: 0

### ISSUE THREAD

**Issue by nkhand** [serenity-bdd/serenity-core#1082]
While executing Serenity:Check Goal to trigger build failure if Failed Tests , SERENITY TEST OUTCOMES are shown properly and Build Failure is triggered , but after that always getting below error : 

Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.8.21:check failed: THUCYDIDES TEST FAILURES: ERROR COUNT: 0 FAILURE COUNT: 1 COMPROMISED COUNT: 0
Caused by: net.thucydides.core.reports.TestOutcomesFailures: THUCYDIDES TEST FAILURES: ERROR COUNT: 0 FAILURE COUNT: 1 COMPROMISED COUNT: 0
	at net.thucydides.core.reports.ResultChecker.checkTestResultsIn(ResultChecker.java:68)

I have set testFailureIgnore to true in POM for failsafe  ,but still this error is not gone . I want the build to exit cleanly . Please suggest .

**Comment by wakaleo** [comment]
That looks like the normal behaviour; the plugin throws an exception with an error message if there are failures. What behaviour are you expecting?

**Comment by wakaleo** [comment]
A system exit could interfere with other plugins

**Comment by wakaleo** [comment]
Feel free to do some research on maven plugins and propose a PR if you find a more elegant solution

**Comment by wakaleo** [comment]
Possibly fixed in the next release

**Comment by wakaleo** [comment]
Fixed in 1.9.0
