### ISSUE TITLE
How to send email/notification with report summary

### ISSUE THREAD

**Issue by mohamedzouaghi** [serenity-bdd/serenity-core#1083]
Hi there,

I'm using Serenity (1.8.1) with cucumber (1.6.5) and I'd like to send email/notifications (at the end of the test) with summary of test outcomes. From what I found in documentation, I don't think this option is proposed by Serenity. That's fine, I can write down an emailer module myself. But I need to know two things:
1- Where can I put the emailer-call? Meaning, which class is run after all scenarios are completed?
2- Which classes would have the scenarios overall outome (so that I can use it to populate email content)

Context: We'll be using Serenity to manage 1000's of scenarios, 10's of applications involving 10's of teams.

Thanks,

**Comment by wakaleo** [comment]
This would normally be something you would do with your CI server (e.g. on Jenkins). Do you have a use case where it is not done in a CI context?

**Comment by mohamedzouaghi** [comment]
Ok so from your reply I understood there was some helper that could generate java classes from JSON output files. And thus can be used to send emails? 
So I went ahead and tested net.thucydides.core.reports.TestOutcomes and its seems to be working pretty well (Even though I only tried a simple example). Ok fair enough. I can add a Jenkins step that do this job.

The only downside though, is when we want to send information that aren't in the report (custom classes that were added for custom treatment) this won't be possible, since they weren't added to the report. Which limit a bit what we could send.
For instance: If I want to send specific logs traces alongside with test results (in some particular situation) this won't be possible. It makes failure analysis easier while keeping the report cleaner. (In this case the report is meant for high level managers, and those notifications are more for QA/Dev teams)

Anyway, I'm ok with using the TestOutcomes.

In a related matter, what if I want to make tear down like treatment, after all scenarios are run (like close connection, or cleanup), where should I put my code (knowing I'm using Cucumber)?

Note: Btw the [TestOutcomes documentation](https://github.com/serenity-bdd/serenity-documentation/blob/master/src/asciidoc/importing-test-outcomes.adoc) is a bit outdated, could you please updated? Thanks

**Comment by mohamedzouaghi** [comment]
Guys, does anyone have an answer to this:

>In a related matter, what if I want to make tear down like treatment, after all scenarios are run (like close connection, or cleanup), where should I put my code (knowing I'm using Cucumber)? 


Or should I go ahead and close this?

**Comment by wakaleo** [comment]
Cucumber doesn't have any hooks that to run after all of the tests are finished, only the @After annotation which runs after each scenario.
