### ISSUE TITLE
Not all list of markdown types are suported in 'serenity-junit' HTML index report.

### ISSUE THREAD

**Issue by Ajeshks2510** [serenity-bdd/serenity-core#1084]
<serenity.version>1.8.21</serenity.version>
<serenity.maven.version>1.8.21</serenity.maven.version>
<artifactId>serenity-junit</artifactId>

Final index report generated with Markdown enabled at "enable.markdown=step" level are not formatted as per 'Markdown-Cheatsheet'[Reference:](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
As per the issue [#545](https://github.com/serenity-bdd/serenity-core/issues/545), markdown support added in HTML report for serenity-core versions 1.2.1-rc.1 and above.
But, the report I have generated using serenity-junit is not showing all the supported Markdown items rather than  **, __,  [], ` `,  and tables.

Can you confirm this is the expected behavior, if not kindly share the list of supported markdowns that would be available in HTML report for formatting. 

### I am looking for how to add a Pop-up in existing index report when I select a link which shows inside a list of data.

.

**Comment by wakaleo** [comment]
What you are looking for is not possible in markdown; the markdown support is designed for emphasis or simple formatting, not for extensions to the reporting template. We use Flexmark (https://github.com/vsch/flexmark-java/wiki) for the markdown rendering, which supports most standard Markdown tags.

**Comment by Ajeshks2510** [comment]
@wakaleo Appreciated!
Can you tell me why basic markdowns such as **Heading, indenting, lists, marking** are not working with report. I am using "0.26.4" of flexmark-java. Is there any specific configuration is required for applying standard formatting?
As pointing to my need of adding an extension to Current HTML report is possible?

**Comment by centu81** [comment]
Did you find any solution, I'm having the same issue.
