### ISSUE TITLE
xPath.compile fails to differentiate between CSS or xPath, and it fails the locator strategies

### ISSUE THREAD

**Issue by gkushang** [serenity-bdd/serenity-core#1085]
**This is a valid CSS:** `some-state>div>h4`.

**Serenity TARGET:** 
``` public static final Target LABEL = Target.the("Some Label").locatedBy("some-state>div>h4");```

We want to find an element by CSS, and above Target definition is correct as per Docs. But because the xpath.Compile in `net.serenitybdd.core.selectors` fails to identify it's a CSS, it returns as By.xPath - which is a wrong assumption. 

As a result, it throws ElementNotFound exception.

xPath.compile fails to differentiate between CSS or xPath

**Comment by wakaleo** [comment]
You need to do 
```
public static final Target LABEL = Target.the("Some Label").located(By.cssSelector("some-state>div>h4"));

```

**Comment by gkushang** [comment]
yeah, it's an option and other option would be to,

```
public static final Target LABEL = Target.the("Some Label").locatedBy("css:some-state>div>h4");
``` 

I wondered becasue the doc says `locatedBy` can take either CSS or xPath but somehow the XPathFactory fails to differentiate at compilation.

Thanks @wakaleo, for the quick response!
