### ISSUE TITLE
BeanMatcherAsserts: java.lang.NullPointerException when value is null

### ISSUE THREAD

**Issue by GianniGiglio** [serenity-bdd/serenity-core#1086]
Hi,

nullpointer in methode: private static String beanDescription(Object bean)

    propertyTerms.add(propertyValueOf(descriptor.getDisplayName(), getter.invoke(bean).toString()));

if getter.invoke(bean) returns null then calling toString causes nullpointer

**Comment by wakaleo** [comment]
Thanks for spotting this; could you suggest a PR for a fix?

**Comment by wakaleo** [comment]
That should work. Could you create a PR with a unit test or two?

**Comment by GianniGiglio** [comment]
Sure

**Comment by IvanLiulko** [comment]
Hi guys,
faced with the same issue.
Have you a plan to fix it?
Thanks.

**Comment by wakaleo** [comment]
Happy to review a PR
