### ISSUE TITLE
Serenity incompatible with JDK7

### ISSUE THREAD

**Issue by ihostage** [serenity-bdd/serenity-core#109]
```
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigFactory : Unsupported major.minor version 52.0
```

[Binary Releases for Typesafe Config](https://github.com/typesafehub/config#binary-releases)

**Comment by StarWindMoonCloud** [comment]
which version includes the fix?

**Comment by mikezx6r** [comment]
1.1.17-rc.1 is the only released version with it in it.
