### ISSUE TITLE
Exclude selenium-dependency

### ISSUE THREAD

**Issue by thokari** [serenity-bdd/serenity-core#1090]
Hi, I noticed that `serenity-junit` has a transitive dependency on Selenium, which i don't need, and since Selenium is a *pretty big* library, I wanted to exclude it.

Getting this error tough:
```
java.lang.NoClassDefFoundError: org/openqa/selenium/support/pagefactory/FieldDecorator
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:100)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:661)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:885)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:808)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:285)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:217)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:893)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:134)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:16)
	at net.serenitybdd.junit.runners.SerenityRunner.<init>(SerenityRunner.java:100)
```

I am pretty sure I do not depend on Selenium...
Any idea what might be the problem here?

**Comment by wakaleo** [comment]
Currently `serenity-core` needs Selenium, even if you don't use it.

**Comment by thokari** [comment]
Ok, thanks!

**Comment by eitzenbe** [comment]
Hi @wakaleo We would be interested in resorting / dropping this dependency in Serenity.
If you could provide us with some background we would be willing to work on a PR to drop selenium dependency in serenity
br
Thomas

**Comment by wakaleo** [comment]
> Hi @wakaleo We would be interested in resorting / dropping this dependency in Serenity. If you could provide us with some background we would be willing to work on a PR to drop selenium dependency in serenity br Thomas

Unfortunately Selenium is deeply embeded in the Serenity core code, so extracting it would be a lot of work. However if you would like to try, the place to start would be the StepEventBus class.

**Comment by eitzenbe** [comment]
I'll give it a look

**Comment by eitzenbe** [comment]
@wakaleo Hmmm yeah seems really deeply interworking, unneccessarily from an architectural point of view, would also need some architecture discussions probably with you.... I will discuss it in the team and will come back to you later this month
br
Thomas

**Comment by eitzenbe** [comment]
After some discussion within the team we have the following "proposal": 
We could think about introducing a facade class to the WebDriver from Selenium and keeping all that stuff you have inside of serenity. Now if selenium is not in the dependency than its a NOOP Facade, if present it would instantiate a selenium webdriver
That should minimize the efforts, alas its not a clean solution, but a really clean solution of separation would be too much work for us to spend on this topic.
@wakaleo Whats your thought on this? Would you be able to join/support us?
br
Thomas

**Comment by wakaleo** [comment]
Possibly. The WebDriverManagerFacade class already does this to some extent, but there are some dependencies on drivers that would be need to be catered for. Feel free to come up with a more concrete proposal, it would be a good thing to get working

**Comment by eitzenbe** [comment]
@wakaleo  Hmm started to poke a few holes just to see how the path behind looks like, but seeing strange errors in main branch (like expecting Optionals for members which are clearly not Optional).... What is a safe working branch to base upon?

**Comment by wakaleo** [comment]
The main branch should work

**Comment by eitzenbe** [comment]
![image](https://user-images.githubusercontent.com/5560776/201940186-072086ab-1080-4179-876d-72da5d8fd80e.png)
nope?

**Comment by globalworming** [comment]
what java version are you using?

**Comment by eitzenbe** [comment]
11

**Comment by eitzenbe** [comment]
which one should I use?

**Comment by globalworming** [comment]
> which one should I use?

don't know. but optional not being found sounds like intelliJs project settings still got java 7 or something like that

**Comment by globalworming** [comment]
![image](https://user-images.githubusercontent.com/2108984/201944625-1b9655a1-1099-486a-b27b-c80415e987ee.png)

so you got some different cucumber version somehow. i see `io.cucumber:messages:19.1.4` in my dependencies

**Comment by eitzenbe** [comment]
are you building via maven or via gradle?

**Comment by globalworming** [comment]
maven

**Comment by globalworming** [comment]
so.. the root pom and gradle properties definitely have different cucumber versions set 🤔

**Comment by eitzenbe** [comment]
gradle: 7.2.3
maven: 7.8.1

That explains it ;) now switching to maven

**Comment by eitzenbe** [comment]
@wakaleo forked and committed first proposal/draft/wip
https://github.com/eitzenbe/serenity-core/tree/decouple_selenium_appium
Can we talk about it?

**Comment by eitzenbe** [comment]
@globalworming would you be available for some architctural discussion?

**Comment by wakaleo** [comment]
Had a quick look - looks promising so far.

**Comment by eitzenbe** [comment]
@wakaleo  OK so my next step would be to introduce a new serenity-selenium module and refactor the shit out of serenity-core. I am still a bit unsure where to introduce the cut but will try to mimimize MY efforts ;)
This would leave serenity-core only with a dependency of selenium-api and dynamic Class.forName() checks with reflection instantiation of any object needed. OK?
Do you have any proposal about where to apply the cut or am I on my "own" here ;)

br
Thomas

**Comment by eitzenbe** [comment]
@wakaleo I have pushed the split code, it compiles (as a first step) but lots of tests still fail, wondering if someone from the core team could lend me a hand in sorting these out, there are a large set of test cases that break due to testsuite member being null....

**Comment by eitzenbe** [comment]
@wakaleo forked and committed first proposal/draft/wip
https://github.com/eitzenbe/serenity-core/tree/decouple_selenium_appium
Can we talk about it?

**Comment by wakaleo** [comment]
What errors are you getting?

**Comment by eitzenbe** [comment]
working on it roughly 1600 are already OK, will get back here when it gets tough

**Comment by eitzenbe** [comment]
ok so the stats currently are:
serenity-selenium:
[ERROR] Tests run: 678, Failures: 5, Errors: 2, Skipped: 4
serenity-core new
[ERROR] Tests run: 1106, Failures: 12, Errors: 3, Skipped: 1

@wakaleo would anyone from the core team be willing to take a look at the remaining issues, maybe shared session (Code with me on Intellij or zoom)

**Comment by eitzenbe** [comment]
@wakaleo  Good morning John, Is there any slot where one from the core team could jump onto a session with me to clarify the remaining issues with the branch/fork?
