### ISSUE TITLE
Remove ASCII-art-logging

### ISSUE THREAD

**Issue by thokari** [serenity-bdd/serenity-core#1091]
Serenity prints huge banners before and after every test
TEST STARTED
:-) TEST PASSED 
etc.

I find this unnecessarily takes up a lot of screen space, and is also not needed, because at least in my case, I am always using the search function to navigate logs.

Also, the smiley faces might give a ... weird or wrong impression, since it is not at all obvious that it originates from the framework and not because some developer was feeling like making a questionable joke.

Is there a way to disable (only) these banners from the logs?

**Comment by wakaleo** [comment]
```
serenity.logging=QUIET
```

**Comment by thokari** [comment]
Yes, I know about that one, but I *do* want the start and end of Steps to get logged...

**Comment by wakaleo** [comment]
That would be an easy PR if you want to an another logging level - have a look at the ConsoleLoggingListener class.

**Comment by thokari** [comment]
I am right now, wondering if `THUCYDIDES_CONSOLE_HEADINGS = MINIMAL` could possibly do the trick already. I might submit a PR.

**Comment by wakaleo** [comment]
Indeed, that might do the trick as well.

**Comment by thokari** [comment]
Apparently it does! Closing this issue :)
