### ISSUE TITLE
Timeout for steps

### ISSUE THREAD

**Issue by volnoboy** [serenity-bdd/serenity-core#1095]
This is not a bug, but a feature request. I am using Jbehave.

I didn't find any feature similar to Junit: **@Test(timeout = 100)**

Is it possible to have a timeout in @Step annotation or generally set timeout for scenario or story? 

story.timeout.in.secs - **is not an option, it is not behaving correctly**

**Comment by mithuns** [comment]
Are you keeping this property 
   ` story.timeout.in,secs=300`
In serenity.properties file at the root of your project ?

**Comment by wakaleo** [comment]
story.timeout.in.secs is a JBehave attribute that is not actually related to individual story timeouts - it puts an absolute time limit on your whole test run, and crashes out of the JVM if this timeout is exceeded.

**Comment by wakaleo** [comment]
Hard timeouts on tests or steps are generally not a great idea - they are a common cause of flaky tests and random test failures, unless you set them extremely high (in which case, what’s the point?). If you really need this feature in one of your steps , why not just code it yourself in Java?

**Comment by volnoboy** [comment]
I keep everything in serenity.properties file. Look, we need this feature, I have already coded it myself. The solution with @Step annotation would be much cleaner. For monitoring production in real time, this is very useful.

**Comment by wakaleo** [comment]
Happy to review a pull request.
