### ISSUE TITLE
Double features in serenity report

### ISSUE THREAD

**Issue by GrBojan** [serenity-bdd/serenity-core#1096]
After running test with "mvn clean verify" and generating reports there are same feature in two places https://prnt.sc/i7onqi and http://prntscr.com/i7oonp.
And this is the feature file:  http://prntscr.com/i7opeh

**Comment by wakaleo** [comment]
Can you provide a sample project to reproduce the issue?

**Comment by GrBojan** [comment]
Here is a demo project: https://github.com/GrBojan/demoProjectSerenity

**Comment by wakaleo** [comment]
Fixed many years ago.
