### ISSUE TITLE
How to get the description of a Performable?

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1097]
I've got some `Interactions` in my project that manage browser windows e.g. ensure that the number of browser windows increase or decrease, following the performing of another task. However I'm having trouble getting the description of the injected `Performable`  to annotate the browser management task. In the below example a regular `toString()` of the `Performable` doesn't work:
```
    public InNewWindowPerform(Performable performTask) {
        this.performTask = performTask;
    }

    @Override
    @Step("{0} creates new browser window following running of #performTask")
```
Is there a Serenity Step method I can call to get the `@Step` annotation string from `performTask` above please?

**Comment by wakaleo** [comment]
Hmmm, not easily as the processing is done elsewhere. You might be able to use AnnotatedStepDescription:

```
        ExecutedStepDescription description = new ExecutedStepDescription(SampleTestSteps.class, "an_annotated_step");
        AnnotatedStepDescription annotatedStepDescription = AnnotatedStepDescription.from(description);
        assertThat(annotatedStepDescription.getName(), is("A step with an annotation"));
```

**Comment by nbarrett** [comment]
thanks @wakaleo - this looks exactly what I'm after! I'll have a try and see how I get on.

**Comment by nbarrett** [comment]
Actually. I created this method as`new ExecutedStepDescription()` not possible due to being protected:

```
    public static String taskName(Class<? extends Performable> performable) {
        ExecutedStepDescription description = ExecutedStepDescription.of(performable, "an_annotated_step");
        AnnotatedStepDescription annotatedStepDescription = AnnotatedStepDescription.from(description);
        return annotatedStepDescription.getAnnotatedTitle();
    }
```

However this threw the following exception:

`No test method called net.thucydides.core.steps.ExecutedStepDescription@71238fc2 was found in class `...

**Comment by scooti9** [comment]
@nbarrett maybe you know when I have a class with a few Performable methods and I want to add @step annotations that to be able see grouped steps from this Performable methods. How can I do this?
