### ISSUE TITLE
Is not working - click action

### ISSUE THREAD

**Issue by sampadrout** [serenity-bdd/serenity-core#1098]
I am using latest serenity.version = 1.8.21 and appium version 1.7.2. Below click action is not working:
@FindBy(id="com.thinkrite.assistant:id/buttonSignIn")
private WebElementFacade signIn;

public void enterCredentials(){
		element(signIn).waitUntilClickable().click();
	}
Any solution here!

**Comment by cliviu** [comment]
hi, @sampadrout , please always define "is not working" when you are reporting a problem with some stack trace or some description of the failure. 

Can you please try serenity-core 1.8.22-rc.2 ?

**Comment by sampadrout** [comment]
Updated the subject. Here is the stack trace.
[HTTP] --> POST /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/element {"using":"id","value":"com.thinkrite.assistant:id/buttonSignIn"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.thinkrite.assistant:id/buttonSignIn","d0504b0e-a685-4629-9bf0-90357c5a1d28"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.thinkrite.assistant:id/buttonSignIn","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.thinkrite.assistant:id/buttonSignIn","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.thinkrite.assistant:id/buttonSignIn' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.thinkrite.assistant:id/buttonSignIn]
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"8"}
[HTTP] <-- POST /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/element 200 512 ms - 87 
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"8"}}
[HTTP] --> POST /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/timeouts {"type":"implicit","ms":2000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",2000,"d0504b0e-a685-4629-9bf0-90357c5a1d28"]
[debug] [BaseDriver] Set implicit wait to 2000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/timeouts 200 5 ms - 76 
[HTTP] --> GET /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/element/8/name {}
[debug] [MJSONWP] Calling AppiumDriver.getName() with args: ["8","d0504b0e-a685-4629-9bf0-90357c5a1d28"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"className","elementId":"8"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"className","elementId":"8"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getAttribute
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"android.widget.Button"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.getName() result: "android.widget.Button"
[HTTP] <-- GET /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/element/8/name 200 24 ms - 95 
[HTTP] --> GET /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/element/8/attribute/id {}
[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["id","8","d0504b0e-a685-4629-9bf0-90357c5a1d28"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"id","elementId":"8"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"id","elementId":"8"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- GET /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/element/8/attribute/id 500 9 ms - 164 
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getAttribute
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"This element does not have the 'id' attribute"}
[HTTP] --> POST /wd/hub/session/d0504b0e-a685-4629-9bf0-90357c5a1d28/execute {"script":"return (typeof jQuery === 'function')","args":[]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["return (typeof jQuery === 'function')",[],"d0504b0e-a685-4629-9bf0-90357c5a1d28"]

**Comment by sampadrout** [comment]
Well i am closing this issue as i got the root cause. Thanks for you time.
