### ISSUE TITLE
Serenity - Wait for Angular (asynchronous script timeout: result was not received in 30 seconds)

### ISSUE THREAD

**Issue by PadmajaSampath** [serenity-bdd/serenity-core#1101]
Hi,

We are trying to use Selenium to automate the Angular JS application and have our wait function as below. (Suggested by Serenity)

 public void waitForAngularRequestsToFinish() {
        if ((boolean) getJavascriptExecutorFacade().executeScript(
                "return (typeof angular !== 'undefined')? true : false;")) {
            getJavascriptExecutorFacade()
                    .executeAsyncScript(
                            "var callback = arguments[arguments.length - 1];"
                                    + "angular.element(document.body).injector().get('$browser').notifyWhenNoOutstandingRequests(callback);");
        }
    }

But we get this 30 seconds error and our application is dealing with a service for some tests which might take a bit longer. Not sure where this 30 seconds is mentioned.

Are we using the best solution for Angular JS with Serenity? Please advice.

Thanks

**Comment by wakaleo** [comment]
Have you tried using the ngWebDriver implementation:
```
    public void waitForAngularRequestsToFinish() {
        JavascriptCompatibleVersion.of(getDriver()).ifPresent(
                driver -> new NgWebDriver(driver).waitForAngularRequestsToFinish()
        );
    }
```

(This method is the current implementation in the Serenity PageObject, so if you are inside a Serenity PageObject, you can just call this method directly)

**Comment by PadmajaSampath** [comment]
Thanks. We thought of using the custom built code than the NgWebdriver library.

Is this what is recommended by Serenity for Angular Apps ?

**Comment by PadmajaSampath** [comment]
BTW, We are using Serenity Core BDD 1.4.0 version

**Comment by wakaleo** [comment]
ngWebDriver was added since then. Yes, it is the preferred solution.

**Comment by PadmajaSampath** [comment]
Hi Wakaleo,

Tried with 1.8.20 (Serenity -Core) and we still get a timeout with 0 seconds error wherever we use waitForAngularRequestsToFinish().

Below is the implementatin from the PageObject Class.

public void waitForAngularRequestsToFinish() {
        JavascriptCompatibleVersion.of(getDriver()).ifPresent(
                driver -> new NgWebDriver(driver).waitForAngularRequestsToFinish()
        );
    }

Is there anything specific we need to do ? I can attach the error soon.

**Comment by PadmajaSampath** [comment]
Same script works when tried with implicit waits removing waitForAngularRequestsToFinish()

**Comment by wakaleo** [comment]
waitForAngularRequestsToFinish() simply calls ngWebDriver - if there are any issues, please raise them on the ngWebDriver project.

**Comment by Nesay-hub** [comment]
new NgWebDriver((JavascriptExecutor) this.driver).waitForAngularRequestsToFinish(); causing issue

******Exception occurred org.openqa.selenium.ScriptTimeoutException: asynchronous script timeout: result was not received in 30 seconds

**Comment by wakaleo** [comment]
> new NgWebDriver((JavascriptExecutor) this.driver).waitForAngularRequestsToFinish(); causing issue
> 
> ******Exception occurred org.openqa.selenium.ScriptTimeoutException: asynchronous script timeout: result was not received in 30 seconds

waitForAngularRequestsToFinish() simply calls ngWebDriver - if there are any issues, please raise them on the ngWebDriver project.
