### ISSUE TITLE
[Help] JUnit Manual Step Output in Report

### ISSUE THREAD

**Issue by mikeastarb** [serenity-bdd/serenity-core#1103]
Hello, I am using Serenity 1.8.21 to run a suite of JUnit tests. I have a group of tests that I would like to mark as manual but also have something in the Steps in the HTML report. Currently, my tests seem to be ignored completely and under "Manual Steps" nothing is listed.

Currently, I am marking the tests with the @manual annotation and have stepped through the code to see what happens. Looking through the source code of StepEventBus, I see that testIsManual() method has a notation on it that the test method will be marked as pending but the test will still be executed to record the steps. However, moving a class higher to SerenityRunner in the markAsManual() method, the test immediately finishes and the runChild() method immediately returns.

Is this kind of manual reporting supported in Serenity? I've tried to check documentation, but finding anything around this issue has been difficult.

My test looks similar to the following

```
// TestFeature.java

// imports

@Narrative(text= { "not important"})
@RunWith(SerenityRunner.class)
public final class TestFeature {
    @Steps
    private MySteps mySteps;

    @Test
    @Manual
    public void myTest() {
        mySteps.doFirst();
        mySteps.doSecond();
    }
}

// MySteps.java

// imports

public class MySteps {
    @Step("This is the first step")
    public void doFirst() {
        return;
    }

    @Step("This is the second step")
    public void doSecond() {
        return;
    }
}
```

The text "This is the first step" and "This is the second step" is what I am looking to see in the final report for this test case.

**Comment by wakaleo** [comment]
The @Manual test is designed to be a marker/reminder, not a test script format. This is the current expected behaviour - it was introduced to fix a defect involving code being executed even if the test was flagged as manual.

**Comment by mikeastarb** [comment]
Hey @wakaleo thank you for the explanation of the tag

I am left with a question though of how steps make it into the Manual Steps list in the generated report (or at least it appears to me to be a manual steps list)

![image](https://user-images.githubusercontent.com/7879578/35995578-ce565a44-0ce1-11e8-97e8-078d2eba5351.png)

If that's not used, is there any recommended way of documenting manual tests cases alongside automated test cases in Serenity? Or is the recommendation to document manual tests outside of Serenity completely?

**Comment by wakaleo** [comment]
It used to be done that way, but we removed that feature because folks complained about it.

**Comment by mikeastarb** [comment]
Cool, I can understand that. Thanks again for the context! I'll take this info to my team and discuss what we would like to do moving forward regarding our manual test scenarios

**Comment by mikeastarb** [comment]
Wanted to do my civic duties and post what I think is a solution to my issue:

At the start of each of my manual tests I've found I can call `StepEventBus.getEventBus().testIsManual()` myself. This does not stop methods from executing, but will mark all of the steps as ignored in our results file and appropriately report them as manual tests (seems like this gets back to the old functionality). Since my team codes with aborted test cases in mind, we handle running partial sets of steps and having our methods execute is not a functional issue. It will cost time to run any methods that may have automation in them, but that's an acceptable loss for me currently.
