### ISSUE TITLE
The page object class looks dodgy

### ISSUE THREAD

**Issue by sampadrout** [serenity-bdd/serenity-core#1104]
When i am running the serenity test for appium, getting the error: The page object class XXX looks dodgy: Failed to instantiate page (java.lang.IllegalArgumentException: Can not set net.serenitybdd.core.pages.WebElementFacade field XXX to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4) Any help here?

**Comment by cliviu** [comment]
Please use serenity-core 1.8.22-rc.2

**Comment by sampadrout** [comment]
It works fine now. Thanks a ton.
