### ISSUE TITLE
Gradle plugin not compatible with Gradle 5.0

### ISSUE THREAD

**Issue by RemonSinnema** [serenity-bdd/serenity-core#1110]
I'm getting the following warning when running `serenity-gradle-plugin` 1.8.21 with Gradle 4.5.1:

```
A problem was found with the configuration of task ':checkOutcomes'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - No value has been specified for property '$1'.

```

**Comment by wakaleo** [comment]
Possibly fixed in the latest version.

**Comment by RemonSinnema** [comment]
I don't see anything later than 1.8.21 in the Maven Central Repository. Is the fix in any publicly available binary version?

**Comment by wakaleo** [comment]
The latest is 1.9.0-rc.1: http://search.maven.org/#search%7Cga%7C1%7Cserenity-core

**Comment by RemonSinnema** [comment]
Confirmed that 1.9.0-rc.1 fixes the issue.
