### ISSUE TITLE
Failed to start appium driver instance

### ISSUE THREAD

**Issue by sampadrout** [serenity-bdd/serenity-core#1111]
When i am trying to start appium server, it throws connection refused. I am using serenity core v1.8.22-rc.2. Below is the error:
FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class io.appium.java_client.AppiumDriver: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (Connection refused

**Comment by vikramvi** [comment]
@sampadrout you can try https://github.com/vikramvi/AppiumSerenityPOC and let me know if you still face above error

- appium server starting and stopping needs to be handled by your code, Serenity can't do those actions for you

**Comment by sampadrout** [comment]
Thanks @vikramvi I am having the code to do that but wondering whats the use of @Managed(uniqueSession = true)
WebDriver appiumDriver;

### Here i start and stop the appium server:
public class TestSuiteRunner {
	
    @BeforeClass
    public static void startAppium() {
        startAppiumServer();
    }

    @AfterClass
    public static void stopAppium() {
        stopAppiumServer();
    }   
}

**Comment by vikramvi** [comment]
@sampadrout  Please refer to http://www.thucydides.info/docs/serenity/ for the answer
