### ISSUE TITLE
Keeping browser open for entire feature file is not working

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#1113]
I've multiple user stories under feature file and I run it as below

```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features="src/test/resources/features/SmavaWebAnalyticsDataTableUserStories.feature")
public class SmavaHomePageTest {
    //@Managed(clearCookies=Never, uniqueSession=false )
    @Managed(uniqueSession = true)
    WebDriver driver;
}
```

But I've observed that after each of the user stories execution browser is getting closed.

`serenity.use.unique.browser = true
`
didn't work either.  Please review

**Comment by wakaleo** [comment]
The Serenity/Cucumber integration manages it's own driver, the @Managed annotation is only used for JUnit. Try:

```
serenity.restart.browser.for.each=feature
```

**Comment by vikramvi** [comment]
Thanks for detailed clarifications.

Reference: ThucydidesSystemProperty.java , WhenConfiguringWhenABrowserShouldRestart.groovy
