### ISSUE TITLE
jira description not fetched by the report

### ISSUE THREAD

**Issue by sampadrout** [serenity-bdd/serenity-core#1114]
### I have the following in serenity.properties file:
jira.url = https://xxxx.ama.com/
jira.project = AMA - iOS
jira.root.issue.type = Story
jira.username = XXXX
jira.password = XXXX

In the report index.html, i am not seeing the description fetched from Jira. Is there anything i am missing here?

### Here is my pom.xml:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>com.ama</groupId>
    <artifactId>AMA_Automation_RegressionTesting</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>AMA Project</name>
    <description>AMA automation testing with BDD Approach using Serenity, Cucumber</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.8.22-rc.2</serenity.version>
        <serenity.junit.version>1.8.21</serenity.junit.version>
        <serenity.cucumber.version>1.6.10</serenity.cucumber.version>
        <serenity.jira.version>1.8.0</serenity.jira.version>
    </properties>

    <repositories>
      <repository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
      </repository>
    </repositories>
    <pluginRepositories>
      <pluginRepository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray-plugins</name>
        <url>http://jcenter.bintray.com</url>
      </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>${serenity.jira.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-requirements-provider</artifactId>
            <version>${serenity.jira.version}</version>
        </dependency>
        <dependency>
        	<groupId>org.slf4j</groupId>
        	<artifactId>slf4j-jdk14</artifactId>
        	<version>1.7.25</version>
        </dependency>
	    <dependency>
	        <groupId>ch.qos.logback</groupId>
	        <artifactId>logback-classic</artifactId>
	        <version>1.1.3</version>
	    </dependency>
		<dependency>
		    <groupId>ch.qos.logback</groupId>
		    <artifactId>logback-core</artifactId>
		    <version>1.1.3</version>
		</dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.20.1</version>
                <configuration>
                    <includes>
                        <include>**/*.java</include>
                    </includes>
                    
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>1.8.22-rc.2</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    
			        
			        <dependency>
                    	<groupId>net.serenity-bdd</groupId>
                    	<artifactId>serenity-jira-requirements-provider</artifactId>
                    	<version>${serenity.jira.version}</version>
                	</dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by mithuns** [comment]
Do you have the Meta tags in your story file ? 
```
Meta:
@issue #FH-17
```
Trying checking this out ?
[integration_with_jira](http://thucydides.info/docs/serenity-staging/#_integrating_with_jira)

**Comment by sampadrout** [comment]
i guess meta tag is for jbehave. Can i use it for cucumber as well?

**Comment by mithuns** [comment]
Aah right, 
_`Serenity lets you associate JBehave stories or JUnit tests with a JIRA card using the @issue meta tag (illustrated above), or the equivalent @Issue annotation in JUnit`_
try using the feature way, I believe you would need to instead use 'Feature' in your story file and add that dependency, to the reporting plugin.
[feature_coverage](http://thucydides.info/docs/serenity-staging/#_feature_coverage)

**Comment by sampadrout** [comment]
@mithuns i have already tried this. But still not working. Any help here.

Feature: Login page scenarios

@Issue:IOSTRA-3532
@android @ios @regression

Scenario: FTUX - Existing User login
Given User is on login page
When Enter valid credentials
Then User is shown calendar page
Then Select Local Calendar
Then Accept calendar Alert
Then Select EWS Calendar
Then Tap Done
Then Display EWS page to enter details
Then Enter Exchange Account details
