### ISSUE TITLE
serenity.maintain.session = true  doesn't seems to work as expected

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#1116]
I used this property in order to check google analytics which recognizes users if s/he visits again to same webpage

- launch webpage, goto a link in that
- close browser
- open browser
- repeat step 1

But I'm not getting correct google analytics flag, it does work when checked manually.

This is again tested wrt Gherkin Syntax in a feature file.

**Comment by wakaleo** [comment]
You will need to dig into the code to see what is going on, and what this flag does; I believe is is experimental and the mileage varies depending on the site

**Comment by wakaleo** [comment]
The session referred to is the Serenity in-memory cache - it is unrelated to the browser.
