### ISSUE TITLE
How to prepare json file from feature file ?

### ISSUE THREAD

**Issue by dipakbachhav** [serenity-bdd/serenity-core#1117]
I am trying to test my post method using  api but i want to post my json with feature file data
```
Feature: Testing a REST API 
       Scenario: Create sturent account using post method
       Given api is up and running for post method
       When i create json with below valuues and hit rest api

 | Student_id            |Name       |   CityName    | State  |PostCode    |Tel            |
 |      0101             |Andrew     |  Leeds        |        | SO143FT    | 345345345345  |
 |      0102             |Smith      |  NewCastle    |        | SO143LN    | 345345345345  |
       Then Status is 201

```
Below is the json file i want to prepare from above feature file. Can you please help me with the same.?
```
 {
            "Student_id": 0101,
            "Name": "test",
            "CityName": "test",
            "State": "TT",
            "PostCode": 89098,
            "Tel": "(000)- 000-0000",

        }
```

**Comment by wakaleo** [comment]
Just creat a Student class with those fields, and pass in a list of Students to your step definition.

**Comment by wakaleo** [comment]
As this is a question, the best forum is on the https://serenity-bdd.rocket.chat channels.

**Comment by dipakbachhav** [comment]
Hi @wakaleo : Thank you for your reply. Could you please help me with example because i am new to above and unable to implement it .

**Comment by eliasturki** [comment]
Hello
@dipakbachhav  Could you please help me with example  How to prepare json file from feature file !!!
