### ISSUE TITLE
Dynamic solutions for running Serenity tests in parallel runs 

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1119]
Hi,

In the documentation for parallel batch runs, I noticed that the setup in Jenkins for copying artifacts over to the aggregation job are manually created, 1 build step per node i.e.:
thucydides-batch-showcase/BATCH_NUMBER=1
thucydides-batch-showcase/BATCH_NUMBER=2
thucydides-batch-showcase/BATCH_NUMBER=3

Is there a dynamic solution where we could avoid manually creating new build steps in Jenkins to add them to 'BATCH_NUMBER=100' , or in scenarios where VM counts keep changing on a daily basis?

http://thucydides.info/docs/serenity-staging/#_running_serenity_tests_in_parallel_batches

![image](https://user-images.githubusercontent.com/19309438/35954278-cf27d2a4-0cc3-11e8-9ece-5ad65b88a638.png)

**Comment by timothyjmtan** [comment]
Just replying to my own question,
the Copy Artifacts plugin does this:
![image](https://user-images.githubusercontent.com/19309438/35954542-467801ac-0cc5-11e8-99b3-7740c6222d74.png)

I suppose

**Comment by wakaleo** [comment]
Not at this stage.
