### ISSUE TITLE
Detail reports for steps not coming.It is working for one project but does no work for the other.

### ISSUE THREAD

**Issue by nivrutha** [serenity-bdd/serenity-core#1120]
![snip2](https://user-images.githubusercontent.com/29226866/35958859-06613fe4-0cc9-11e8-8945-34fe73b66786.PNG)
![snip1](https://user-images.githubusercontent.com/29226866/35958842-f9993ed8-0cc8-11e8-8f87-96741f88dab4.PNG)

This is my pom.xml
<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.fmr.PR000163</groupId>
		<artifactId>neo.distribution.functional-tests</artifactId>
		<version>17.01.0.1</version>
	</parent>
	<artifactId>neo.distribution.functional-tests.cucumber</artifactId>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		 <serenity.version>1.4.0</serenity.version>
        <serenity.cucumber.version>1.1.34</serenity.cucumber.version>
       
	</properties>

	<build>
		<plugins>			
  <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/AppTest.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>		 <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-requirements-provider</artifactId>
                        <version>1.1.3-rc.5</version>
                    </dependency>
                </dependencies>
            </plugin>
		
		</plugins>
	</build>
	<dependencies>
	 
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
          </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
          </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>1.1.3-rc.5</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-requirements-provider</artifactId>
            <version>1.1.3-rc.5</version>
        </dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jms</artifactId>
		</dependency>
		<dependency>
			<groupId>org.fitnesse</groupId>
			<artifactId>fitnesse</artifactId>
			<version>20151230</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>

		<dependency>
			<groupId>com.jayway.awaitility</groupId>
			<artifactId>awaitility</artifactId>
			<version>1.7.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.sourceforge.htmlunit</groupId>
			<artifactId>htmlunit</artifactId>
			<version>2.20</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>xalan</groupId>
					<artifactId>xalan</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xerces</groupId>
					<artifactId>xercesImpl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.jcraft</groupId>
			<artifactId>jsch</artifactId>
			<version>0.1.53</version>
		</dependency>
		
		<dependency>
			<groupId>com.oracle.jdbc</groupId>
			<artifactId>ojdbc6</artifactId>
			<version>11.2.0.3</version>
		</dependency>
		<dependency>
			<groupId>commons-dbcp</groupId>
			<artifactId>commons-dbcp</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.53.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-htmlunit-driver</artifactId>
			<version>2.45.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.14</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.14</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20090211</version>
		</dependency>
		<dependency>
			<groupId>org.skyscreamer</groupId>
			<artifactId>jsonassert</artifactId>
			<version>1.2.0</version>
		</dependency>
		
		<dependency>
			<groupId>cn.guoyukun.jdbc</groupId>
			<artifactId>db2jcc</artifactId>
			<version>1.4.2</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.8.7</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.8.7</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.8.7</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.security</groupId>
			<artifactId>oauth2-client</artifactId>
			<version>2.22.1</version>
		</dependency>
		<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>SPSWebservicesCommon</artifactId>
			<version>4.0.30</version>
		</dependency>

		<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>CurrencyServiceDataAccess</artifactId>
			<version>1.0.9</version>
		</dependency>

		<dependency>
			<groupId>org.xmlunit</groupId>
			<artifactId>xmlunit-core</artifactId>
			<version>2.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-moxy</artifactId>
			<version>2.19</version>
		</dependency>

		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.2.0</version>
		</dependency>
		<dependency>
		   <groupId>com.sun.jersey</groupId>
		   <artifactId>jersey-bundle</artifactId>
		   <version>1.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
		</dependency>
		<dependency>
			<groupId>com.ezpaas.frf</groupId>
			<artifactId>frf-config-utils</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.fimt.asts.frf</groupId>
			<artifactId>frf-secret</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>com.fimt.asts.frf</groupId>
			<artifactId>frf-password-decrypter</artifactId>
			<version>1.1.1</version>
		</dependency>		
		<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>neo.platform.utilities</artifactId>
			<version>${spsgrk.platform.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>neo.platform.framework.common</artifactId>
			<version>${spsgrk.platform.version}</version>
		</dependency>
			<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>neo.business.utilities</artifactId>
			<version>${spsgrk.businesscommon.version}</version>
		</dependency>
	</dependencies>
</project>

**Comment by wakaleo** [comment]
Have you tried with the latest version of Serenity?

**Comment by nivrutha** [comment]
I am getting this error while using latest versions . 

com.google.common.util.concurrent.ExecutionError: java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByJQL(JerseyJiraClient.java:124)
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getRequirements(JIRARequirementsProvider.java:114)
	at net.thucydides.core.requirements.RequirementsProvided.by(RequirementsProvided.java:15)
	at net.thucydides.core.requirements.reports.MultipleSourceRequirmentsOutcomeFactory.buildRequirementsOutcomesFrom(MultipleSourceRequirmentsOutcomeFactory.java:53)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:152)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:237)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:183)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)

This is my pom.xml

<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.fmr.PR000163</groupId>
		<artifactId>neo.distribution.functional-tests</artifactId>
		<version>17.01.0.1</version>
	</parent>
	<artifactId>neo.distribution.functional-tests.cucumber</artifactId>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		 <serenity.version>1.8.21</serenity.version>
        <serenity.cucumber.version>1.6.10</serenity.cucumber.version>
       
	</properties>

	<build>
		<plugins>			
  <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/AppTest.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>		 <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-requirements-provider</artifactId>
                        <version>1.8.0</version>
                    </dependency>
                </dependencies>
            </plugin>
		
		</plugins>
	</build>
	<dependencies>
	 
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
          </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
          </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>1.8.0</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-requirements-provider</artifactId>
            <version>1.8.0</version>
        </dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jms</artifactId>
		</dependency>
		<dependency>
			<groupId>org.fitnesse</groupId>
			<artifactId>fitnesse</artifactId>
			<version>20151230</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>




















		<dependency>
			<groupId>com.jayway.awaitility</groupId>
			<artifactId>awaitility</artifactId>
			<version>1.7.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.sourceforge.htmlunit</groupId>
			<artifactId>htmlunit</artifactId>
			<version>2.20</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>xalan</groupId>
					<artifactId>xalan</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xerces</groupId>
					<artifactId>xercesImpl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.jcraft</groupId>
			<artifactId>jsch</artifactId>
			<version>0.1.53</version>
		</dependency>
		
		<dependency>
			<groupId>com.oracle.jdbc</groupId>
			<artifactId>ojdbc6</artifactId>
			<version>11.2.0.3</version>
		</dependency>
		<dependency>
			<groupId>commons-dbcp</groupId>
			<artifactId>commons-dbcp</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.53.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-htmlunit-driver</artifactId>
			<version>2.45.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.14</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.14</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20090211</version>
		</dependency>
		<dependency>
			<groupId>org.skyscreamer</groupId>
			<artifactId>jsonassert</artifactId>
			<version>1.2.0</version>
		</dependency>
		
		<dependency>
			<groupId>cn.guoyukun.jdbc</groupId>
			<artifactId>db2jcc</artifactId>
			<version>1.4.2</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.8.7</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.8.7</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.8.7</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.security</groupId>
			<artifactId>oauth2-client</artifactId>
			<version>2.22.1</version>
		</dependency>
		<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>SPSWebservicesCommon</artifactId>
			<version>4.0.30</version>
		</dependency>

		<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>CurrencyServiceDataAccess</artifactId>
			<version>1.0.9</version>
		</dependency>

		<dependency>
			<groupId>org.xmlunit</groupId>
			<artifactId>xmlunit-core</artifactId>
			<version>2.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-moxy</artifactId>
			<version>2.19</version>
		</dependency>

		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.2.0</version>
		</dependency>
		<dependency>
		   <groupId>com.sun.jersey</groupId>
		   <artifactId>jersey-bundle</artifactId>
		   <version>1.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
		</dependency>
		<dependency>
			<groupId>com.ezpaas.frf</groupId>
			<artifactId>frf-config-utils</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.fimt.asts.frf</groupId>
			<artifactId>frf-secret</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>com.fimt.asts.frf</groupId>
			<artifactId>frf-password-decrypter</artifactId>
			<version>1.1.1</version>
		</dependency>		
		<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>neo.platform.utilities</artifactId>
			<version>${spsgrk.platform.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>neo.platform.framework.common</artifactId>
			<version>${spsgrk.platform.version}</version>
		</dependency>
			<dependency>
			<groupId>com.fmr.PR000163</groupId>
			<artifactId>neo.business.utilities</artifactId>
			<version>${spsgrk.businesscommon.version}</version>
		</dependency>
	</dependencies>
</project>

**Comment by wakaleo** [comment]
You have references to old versions of selenium and htmlunit in your pom, yo need to remove these.

**Comment by nivrutha** [comment]
![mavendependencies](https://user-images.githubusercontent.com/29226866/36023913-03379ab2-0d86-11e8-8695-a773121678d2.PNG)

**Comment by nivrutha** [comment]
Maven dependencies are not getting updated . I am not sure how to solve the problem.Any idea on this

**Comment by wakaleo** [comment]
Looks like a Maven/Eclipse issue

**Comment by nivrutha** [comment]
What to do for the same. I am not able to find the downloaded maven dependencies for the project also..

**Comment by wakaleo** [comment]
Start with a fresh Serenity project (e.g. https://github.com/serenity-bdd/serenity-cucumber-starter) and move your code across.

**Comment by nivrutha** [comment]
Getting the below error

java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.thucydides.core.webdriver.SupportedWebDriver.<clinit>(SupportedWebDriver.java:29)
	at net.thucydides.core.configuration.SystemPropertiesConfiguration.lookupSupportedDriverTypeFor(SystemPropertiesConfiguration.java:261)
	at net.thucydides.core.configuration.SystemPropertiesConfiguration.getDriverType(SystemPropertiesConfiguration.java:102)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getDefaultDriverType(SerenityWebdriverManager.java:174)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getWebdriver(SerenityWebdriverManager.java:116)
	at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getDriver(ThucydidesWebDriverSupport.java:128)
	at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getPages(ThucydidesWebDriverSupport.java:189)
	at net.serenitybdd.core.Serenity.getPages(Serenity.java:187)
	at net.serenitybdd.core.Serenity.getDefaultDependencyInjectors(Serenity.java:83)
	at net.serenitybdd.core.Serenity.getDependencyInjectors(Serenity.java:73)
	at net.serenitybdd.core.Serenity.resetDependencyInjectors(Serenity.java:66)
	at net.serenitybdd.core.Serenity.done(Serenity.java:166)
	at net.serenitybdd.core.Serenity.done(Serenity.java:153)
	at cucumber.runtime.formatter.SerenityReporter.assureTestSuiteFinished(SerenityReporter.java:662)
	at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:286)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:116)
	at cucumber.runner.EventBus.send(EventBus.java:28)

My pom.xml
<?xml version="1.0"?>
<project
       xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
       xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
       <modelVersion>4.0.0</modelVersion>
       <parent>
              <groupId>com.fmr.PR000163</groupId>
              <artifactId>neo.taxation.functional-tests</artifactId>
              <version>17.01.0.1</version>
       </parent>
       <artifactId>neo.taxation.functional-tests.cucumber</artifactId>
       <properties>
              <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
              <jersey.version>2.22.2</jersey.version>
              
              <serenity.version>1.8.19</serenity.version>
        <serenity.cucumber.version>1.6.9</serenity.cucumber.version>
       </properties>
       <build>
       <plugins>
              <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.16</version>
                
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/AppTest.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>                    
                     <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>1.8.20</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                   <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-requirements-provider</artifactId>
                        <version>1.8.0</version>
                    </dependency> 
                </dependencies>
            </plugin>                    
       </plugins>
       </build>
       <dependencies>
              <dependency>
                     <groupId>org.springframework</groupId>
                     <artifactId>spring-core</artifactId>
              
              </dependency>
              <dependency>
                     <groupId>org.springframework</groupId>
                     <artifactId>spring-test</artifactId>
                     
                     
              </dependency>
              <dependency>
                     <groupId>org.springframework</groupId>
                     <artifactId>spring-context</artifactId>
                     
              </dependency>
              <dependency>
                     <groupId>org.springframework</groupId>
                     <artifactId>spring-beans</artifactId>
              
              </dependency>





















       
              <dependency>
                     <groupId>commons-io</groupId>
                     <artifactId>commons-io</artifactId>
                     <version>2.4</version>
              </dependency>
                     <dependency>
                     <groupId>org.json</groupId>
                     <artifactId>json</artifactId>
                     <version>20090211</version>
              </dependency>
              <dependency>
                     <groupId>commons-dbcp</groupId>
                     <artifactId>commons-dbcp</artifactId>
                     <version>1.4</version>
              </dependency>
              <dependency>
                     <groupId>com.jcraft</groupId>
                     <artifactId>jsch</artifactId>
                     <version>0.1.53</version>
              </dependency>
              <dependency>
                     <groupId>com.fasterxml.jackson.core</groupId>
                     <artifactId>jackson-core</artifactId>
                     <version>2.8.7</version>
              </dependency>
              <dependency>
                     <groupId>com.fasterxml.jackson.core</groupId>
                     <artifactId>jackson-annotations</artifactId>
                     <version>2.8.7</version>
              </dependency>
              <dependency>
                     <groupId>com.fasterxml.jackson.core</groupId>
                     <artifactId>jackson-databind</artifactId>
                     <version>2.8.7</version>
              </dependency>
              <dependency>
                     <groupId>org.glassfish.jersey.containers</groupId>
                     <artifactId>jersey-container-servlet</artifactId>
                     <version>${jersey.version}</version>
              </dependency>
              <dependency>
                     <groupId>org.glassfish.jersey.ext</groupId>
                     <artifactId>jersey-spring3</artifactId>
                     <version>${jersey.version}</version>
                     <exclusions>
                           <exclusion>
                                  <groupId>org.springframework</groupId>
                                  <artifactId>spring-beans</artifactId>
                           </exclusion>
                     </exclusions>
              </dependency>
              <dependency>
                     <groupId>org.glassfish.jersey.media</groupId>
                     <artifactId>jersey-media-json-jackson</artifactId>
                     <version>2.22.2</version>
              </dependency>
              <dependency>
                     <groupId>com.fasterxml.jackson.core</groupId>
                     <artifactId>jackson-databind</artifactId>
                     <version>2.6.7</version>
              </dependency>
              <dependency>
                     <groupId>com.sun.jersey</groupId>
                     <artifactId>jersey-client</artifactId>
                     <version>1.8</version>
              </dependency>
              <dependency>
                     <groupId>junit</groupId>
                     <artifactId>junit</artifactId>
                     <version>4.12</version>
                     
              </dependency>
              
              <dependency>
                     <groupId>com.ezpaas.frf</groupId>
                     <artifactId>frf-config-utils</artifactId>
                     <version>1.0.2</version>
              </dependency>
              <dependency>
                     <groupId>com.fimt.asts.frf</groupId>
                     <artifactId>frf-secret</artifactId>
                     <version>1.1.1</version>
              </dependency>
              <dependency>
                     <groupId>com.fimt.asts.frf</groupId>
                     <artifactId>frf-password-decrypter</artifactId>
                     <version>1.1.1</version>
              </dependency>
              <dependency>
                     <groupId>com.fmr.PR000163</groupId>
                     <artifactId>neo.platform.utilities</artifactId>
                     <version>${spsgrk.platform.version}</version>
                     <exclusions>
                           <exclusion>
                                  <groupId>org.apache.logging.log4j</groupId>
                                  <artifactId>log4j-jcl</artifactId>
                           </exclusion>
                                  <exclusion>
                                  <groupId>org.apache.logging.log4j</groupId>
                                  <artifactId>log4j-api</artifactId>
                           </exclusion>
                                  <exclusion>
                                  <groupId>org.apache.logging.log4j</groupId>
                                  <artifactId>log4j-core</artifactId>
                           </exclusion>
                     </exclusions> 
              </dependency>
              <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
           
        </dependency>
              <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>1.8.0</version>
        </dependency>
              <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-requirements-provider</artifactId>
                        <version>1.8.0</version>
                    </dependency>
   <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>3.8.1</version>
    </dependency>
    
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>htmlunit-driver</artifactId>
    <version>2.29.0</version>
</dependency>
 
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-support</artifactId>
    <version>3.8.1</version>
</dependency>
 
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-remote-driver</artifactId>
    <version>3.8.1</version>
</dependency>
 
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-chrome-driver</artifactId>
    <version>3.8.1</version>
</dependency>
 
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-api</artifactId>
    <version>3.8.1</version>
</dependency>
     
              
       </dependencies>
</project>

Actually I explicitly added selenium jars since it downloaded 2.53.1.Kindly help me on this.

**Comment by wakaleo** [comment]
NoClassDefFoundError is pretty much always due to a dependency conflict (see for example https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html). You need to identify where the conflict is coming from; only then can you figure out how to fix your pom.xml.

**Comment by nivrutha** [comment]
I need to look for what conflicts I did not get you.I am having a look at dependency hierarchy in pom editor in eclipse.Serenity automatically downloads a specific version of selenium know..For the latest version I am using what does it download.Usually it downloads  2.53.1.Should Jersey dependencies be used.

**Comment by wakaleo** [comment]
As this is a usage/configuration problem, not a defect, could you close the issue here and continue the conversation on https://serenity-bdd.rocket.chat, where more people might be able to contribute?

**Comment by wakaleo** [comment]
(If Serenity is downloading Selenium 2.53.1 then you are using an old version of Serenity).

**Comment by nivrutha** [comment]
I am not able to connect to https://serenity-bdd.rocket.chat

**Comment by nivrutha** [comment]
I am using serenity newer version only
