### ISSUE TITLE
Serenity Properties question

### ISSUE THREAD

**Issue by s1apped** [serenity-bdd/serenity-core#1122]
Hi,

Could you please tell me if it's possible to not display some Related Tags e.g Capabilities,Epics,Features,Issues,Tags?

Tried using below serenity.properties entry but it didn't work
dashboard.excluded.tag.list=feature

Thanks

**Comment by wakaleo** [comment]
Where do you want to exclude the tags from?

**Comment by s1apped** [comment]
There is Related Tags section on report and I would like to hide/ don't display for example Featues, Tags, Issues.
![image](https://user-images.githubusercontent.com/32245059/35975379-ce04e952-0cdc-11e8-8675-953bd0fa0a23.png)

**Comment by wakaleo** [comment]
That’s not supported at this stage

**Comment by dev0101** [comment]
Hi,
I had the same issue today.
I would like "Feature" doesn't appear in the report, so i wrote in the serenity.properties 
dashboard.excluded.tag.list=feature, but it doesn't seem to work.
The features still appearing
![image](https://user-images.githubusercontent.com/7986863/40789989-077194c8-64f4-11e8-8536-58cb523c7bc6.png)

I use the serenity version : 1.9.12

Is it possible to do this?

Thanks
