### ISSUE TITLE
@Story annotation and how it should be handled by report

### ISSUE THREAD

**Issue by marakeusz** [serenity-bdd/serenity-core#1124]
Hi.

I am using the latest version: 1.8.21

My test packages looks like:
![image](https://user-images.githubusercontent.com/22429323/36015285-2a36dcda-0d6e-11e8-8b14-4e246d395864.png)

I added relation between those two parcicular classes by putting
`@Story(ManageCertificateProvidersStory.class)` in ManageCertificateProvidersStoryAdditionalTest.class.

I needed to create separate class for parameterised tests but I still wanted to have one story for all of those tests.

Report is handling it _partialy-well_.
In the story page of **Manage certificate providers story** I can see the tests from both classes.

But on the **Stories** page the class with _additional_ tests is also listed:
![image](https://user-images.githubusercontent.com/22429323/36015571-4ab8d098-0d6f-11e8-924b-837d3791cdf9.png)
and it is empty.

I wonder if this is an expected behaviour and is it any way to not include such class (since it is  assigned to other story).

**Comment by wakaleo** [comment]
The @Story annotation isn't used anymore. Currently, in JUnit, each class maps to a story, so we don't have a way to do this.

**Comment by marakeusz** [comment]
Ah, I had the feeling `@Story` should not to be used anymore.
Too bad. It would be a great way to organize those parameterised tests.

Thanks anyway.

**Comment by marakeusz** [comment]
Probably marking the `@Story` as deprecated would be a good idea (if it is not used anymore), but nonetheless it is not an issue.
