### ISSUE TITLE
Is it possible to use serenity-bdd for a native iOS project

### ISSUE THREAD

**Issue by dhoskins** [serenity-bdd/serenity-core#1127]
Can serenity-bdd be used for a native iOS testing project using XCTest? I cannot see any examples or documentation around this.

**Comment by wakaleo** [comment]
Serenity is a Java library. XCTest is an Objective-C/swift library. So no.

**Comment by MOPBernie** [comment]
@wakaleo is there any other way to use serenity for iOS native apps?

**Comment by dhoskins** [comment]
I would suggest that there is a need for much greater and easier to read documentation around this project. The manner in which my question was addressed carries a suggestion that this ought to have been obvious to me. 

But upon browsing serenity-bdd.info I can see only a single mention of Java, in relation to a possible language in which to write acceptance tests.
