### ISSUE TITLE
Serenity Core Latest Version Hangs like forever with mass exception being thrown when an assertion fails and compromised exception present in serenity property file

### ISSUE THREAD

**Issue by imram** [serenity-bdd/serenity-core#1128]
Dear Sir,

Please refer the demo repo I have created for reproducing the issue and also to capture the execution logs/ stack trace in each use cases for your analysis.

Repo: https://github.com/imram/serenitybddIssues.git

# **CASE 1: VERSIONS:**
  <serenity.version>1.8.21</serenity.version>
  <serenity.cucumber.version>1.6.10</serenity.cucumber.version>

**Scenario 1:  WHEN ALL ASSERTION STEPS  PASSED**
EXPECTED: NO ERRORS, EVERYTHING WORKS.
ACTUAL: AS EXPECTED.
LOG FILE INSIDE REPO: test_success_keeping_both_assertion_pass.txt

**Scenario 2:  WHEN ONE OF THE ASSERTIONS FAILED AND COMPROMISED EXCEPTION IS COMMENTED OUT.**

EXPECTED: ASSERTION ERROR REPORTED. GET STOPPED QUICKLY.
ACTUAL: AS EXPECTED. no issues

**Scenario 3:  WHEN ONE OF THE ASSERTIONS FAILED AND COMPROMISED EXCEPTION PRESENT.**
EXPECTED: ASSERTION ERROR REPORTED AND EXECUTION STOPS QUICLY, i.e. MVN COMMAND COMPLETES QUICKLY. 
ACTUAL: ASSERTION ERROR REPORTED IS FINE, EXECUTION DOES NOT STOP FOR LONG TIME AND EXCESSIVE EXCEPTION STACKS GOT GENERATED IN LOG AND THROWING BACK AND FORTH **AS IF IN INFINITE LOOP**.  JUST FOR ONE COMRPROMISED EXCEPTION AND JUST ONE SCENARIO REPO HAS. I HAD TO INCREASE INTELLIJ's max file limit size to capture entire LOG. 
**LOG FILE INSIDE REPO: test_failserenityversion121_cucumber1610.txt**

# **CASE 2: VERSIONS:**
  <serenity.version>1.8.1</serenity.version>
  <serenity.cucumber.version>1.6.5</serenity.cucumber.version>

**SCENARIO 1 and 2 IS SAME AS IN CASE 1. NO ISSUES.**

**Scenario 3:  WHEN ONE OF THE ASSERTIONS FAILED AND COMPROMISED EXCEPTION PRESENT.**
EXPECTED: ASSERTION ERROR REPORTED AND EXECUTION STOPS QUICLY, i.e. MVN COMMAND COMPLETES QUICKLY. 
ACTUAL: ASSERTION ERROR REPORTED IS FINE, EXECUTION DOES NOT STOP FOR TIME BEING AND WARNING KEPT ON PRINTING FOR LONG TIME AND THEN EXECUTION STOPS.
**LOG FILE INSIDE REPO: test_fail_serenityversion_181_cucumberversion165.txt**

_NOTE: serenity-maven-plugin has dependency already present referencing current project, please refer the pom file in repo._

Thank you for your help in advance!!

**Comment by imram** [comment]
Dear Sir, Thank you for your such a quick turn around. Glad to see that scenario 3 has been fixed, however it seems it broke the generate report. Please refer issue created: https://github.com/serenity-bdd/serenity-core/issues/1129 for details.

**Comment by wakaleo** [comment]
The update is in master now but it’s not yet been released

**Comment by wakaleo** [comment]
It will be in 1.9.0-rc.2
