### ISSUE TITLE
Serenity BDD Report Not Reflecting Failed Tests in Report and Generating Incorrect Result in 1.9.0-rc.1 release 

### ISSUE THREAD

**Issue by imram** [serenity-bdd/serenity-core#1129]
Repo: https://github.com/imram/serenitybddIssues.git

I verified following use cases in my repo above and here are result.
Use Case: I have two Asserion Steps in Step Definition after When Step.
Scenario 1. First Then Step Assertion Failed
Expected: Console shows then Failure. Report should Show the First Assertion Step Failed and Second Skipped.
Actual: Console Shows Failure as Expected. BDD Dashboard shows unexpectedly 100% Passed. If you open Acceptance Test Page, All steps showing SUCCESS. One more observation, second assertion step entry which was expected to be present but status as Skipped, is Missing.

Please Refer Log File: test_post_fix_FirstAssertionFailed.txt in repo

Scenario 2. First Then Step Assertion Passed and Second Failed
Expected: Console shows second then Failure. BDD Report should Show the First Assertion Step Passed and Second Failed.
Actual: Console Shows Failure as Expected for second one. BDD Dashboard shows unexpectedly 100% Passed. If you open Acceptance Test Page, All steps showing SUCCESS including Second Assertion as well. 

Please Refer Log File: test_post_fix_SecondAssertionStepFailed.txt in repo

Scenario 3: Both Assertion Step expected to pass.
Result: No Issues.

**Comment by dfontde** [comment]
Hi, we have the same scenario occurring with version 1.8.21

**Comment by mmanach** [comment]
Hi, 

Seems that there are some issues with the version 1.9.0-rc.1.

Please can you try with the 1.9.0-rc.3 to check if you still encounter this error ?

https://github.com/serenity-bdd/serenity-core/issues/1131

**Comment by imram** [comment]
@mmanach I just reran my demo provided in desc against rc3, it still generated wrong report. Report Says 100% passed, however console log is showing failure as expected:
java.lang.AssertionError: Failing Second Step Assertion
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at OfferEligibilityStepDefinitions.cardholderShouldBeAbleToSeeFollowingLinkToApplyForOffer(OfferEligibilityStepDefinitions.java:32)
        at ✽.CardHolder should be able to see following link to apply for offer(/Users/ramgupta/IdeaProjects/acceptancetest/src/test/resources/features/eligibility/bag_eligibility.feature:12)

[INFO] Running Checking Eligibility
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.095 s <<< FAILURE! - in Checking Eligibility

**Comment by mmanach** [comment]
Maybe the version of serenity-cucumber (1.6.10) is not ready with the latest rc3, need to ask @wakaleo about this topic.

**Comment by wakaleo** [comment]
Errors are correctly reporting with serenity-core 1.9.0-rc.4 and serenity-cucumber 1.6.13 - could you confirm?
