### ISSUE TITLE
Duplicate rows in report when run tests by tags

### ISSUE THREAD

**Issue by Abeldyaevadd** [serenity-bdd/serenity-core#1130]
Hello!
In our test framework we use running tests by tags. One test can have several tags.
For example:
```
 @WithTagValuesOf({"payments", "limits"}).
 @Test
 public void check_main_page() {
```

Then we run test with maven by tags. Sometimes we pass 2 or more tags in maven command line.
`-Dtags=payments,limits.`

In this case, "check_main_page" test will run 1 time, but in report we have 2 duplicate lines for this test.
Can we set up report to has only unique rows?

serenity-core 1.6.0, serenity-maven-plugin 1.6.0., selenium-java 3.5.3,

**Comment by wakaleo** [comment]
This is not currently supported for JUnit; feel free to propose a PR though.
