### ISSUE TITLE
serenity bdd junit test results

### ISSUE THREAD

**Issue by tfarrar** [serenity-bdd/serenity-core#1132]
Our QA team has a remote webserive we use to collect test results.  After running each test I would like to upload test results to the to this web server using the Issues annotation.  What is my best way to implement this use Serenity bdd junit screenplay framework?  I  thought you might have some special hooks into the framework were I can easily get pass/fail results.

**Comment by tfarrar** [comment]
Thanks for the idea,  that does sound like a better solution to upload the results after the tests are complete.  I was looking for an example of how to create custom reporting in serenity.  Do you have link handy with the info or GitHub location I and refer to.

Thanks
Tim

**Comment by wakaleo** [comment]
It's not hard (implementing an interface and adding some metadata to your source path), but I need to write it up properly.

**Comment by tfarrar** [comment]
I was able to implement a solution using your GitHub example. https://github.com/serenity-bdd/serenity-cli
using -  CLIOutcomeReportGenerator  class.

Now I am trying to figure out the best way to start the post test report generator.  Currently I am using maven pom.xml to start my build with the goal "clean verify" Do you have an suggestions?

**Comment by tfarrar** [comment]
I am use this maven plugin to run post report generator... mvn exec:java

       <plugin>
      <groupId>org.codehaus.mojo</groupId>
      <artifactId>exec-maven-plugin</artifactId>
      <version>1.2.1</version>
      <executions>
        <execution>
          <goals>
            <goal>java</goal>
          </goals>
        </execution>
      </executions>
      <configuration>
        <mainClass>com.classpath</mainClass>
      </configuration>
    </plugin>

**Comment by wakaleo** [comment]
You can also register a reporter class to be executed at the same time at the other aggregate reports; unfotunately I haven’t written much about this feature as yet, but if you look at the ReportServices class (from memory) you should be able to see how it works.
