### ISSUE TITLE
Proxy settings ignored with PhantomJS

### ISSUE THREAD

**Issue by gdowmont** [serenity-bdd/serenity-core#1138]
To run my test from Jenkins I need to connect to the service using specific authenticated proxy. I have tried with Chrome however in the recent versions it does not support authentication when using google.switches.

So I have started experimenting with Firefox and PhantomJS.

Following is the part of my config that configures proxy and PhantomJS and the settings seem to be ignored when running the tests. I do not see any activity on the proxy at all and the tests just time out in the same manner as running them without the proxy config.

`
serenity.proxy.http=proxy-address
serenity.proxy.http_port=port
serenity.proxy.type=http
serenity.proxy.user=user
serenity.proxy.password=password
webdriver.driver=phantomjs
phantomjs.binary.path=/usr/bin/phantomjs
`

I am using serenity-core 1.8.21.

I have tested PhantomJS with my proxy from the command line like `/usr/bin/phantomjs --proxy=proxy-address:port --proxy-auth=user:password` and I was able to connect to the site behind.

I am at a loss and running out of ideas on how to get this configured to make it work.

If you have got any ideas how to get it configured I would greatly appreciate any help.

**Comment by wakaleo** [comment]
Could you post this in serenity-bdd.rocket.chat?
