### ISSUE TITLE
isMobileDriver() method fails with AndroidWebDriver 

### ISSUE THREAD

**Issue by raulfandinoolaya** [serenity-bdd/serenity-core#1139]
Using ScreenPlay and Appium, Serenity creates an AndroidWebDriver as the driver, when the isMobileMethod method receives that kind of driver returns false.  

This method should check if the driver that receives is a child class of AppiumDriver class. 

repository/net/serenity-bdd/serenity-core/1.8.21/serenity-core-1.8.21.jar!/net/serenitybdd/core/pages/WebElementFacadeImpl.class:843

Current method: 

    private boolean isMobileDriver() {
        return ThucydidesWebDriverSupport.getDriverClass() == AppiumDriver.class;
    }

**Comment by ricardorlg** [comment]
That method should check if driver class is assignable from AppiumDriver

**Comment by wakaleo** [comment]
Could you propose a PR?

**Comment by ricardorlg** [comment]
I can make that fix or perhaps @raulfandinoolaya can make the pr

**Comment by raulfandinoolaya** [comment]
I can do it, thanks!

**Comment by ricardorlg** [comment]
@wakaleo I've just sent the PR.

**Comment by ricardorlg** [comment]
should we close this?

**Comment by wakaleo** [comment]
Yes, it will be in the next release
