### ISSUE TITLE
WebElementFacade#type does sometimes not enter the value

### ISSUE THREAD

**Issue by derTobsch** [serenity-bdd/serenity-core#114]
The first input field in the second row has not been filled. That does happen sometimes, i would say every 10-20% and maybe only when the input fields are filled within a loop. I have no clue when it does happen, because it is very hard to get this error on the local machine. But when the tests will be run by Jenkins it does happen sometimes.
When we start the test over they will probably success. 

Does anyone have an idea what can be the failure??

![scaled_5f8d594de148aadd74b9fbd3311204eb_none](https://cloud.githubusercontent.com/assets/5683677/9304710/4a62f9ec-44eb-11e5-99d9-d2734c3d316a.png)

That is the code for this section:
<pre>
for (int i = 0; i < 3; i++) {
      find(By.cssSelector(format(FULL_TRANSPORT_PRICE, i))).type(input);
      find(By.cssSelector(format(EMPTY_TRANSPORT_PRICE, i))).type(input);
}
</pre>

We are using:
serenity-junit.version: 1.1.4
serenity-maven.version: 1.1.3
serenity-core.version: 1.1.4

**Comment by wakaleo** [comment]
This sounds like a Selenium/timing issue.

**Comment by derTobsch** [comment]
yes is does and because of that it is almost impossible to debug it..:/

**Comment by wakaleo** [comment]
I think this is not a Serenity code issue but rather an issue with how Selenium interacts with this UI. If you can get it working in raw Selenium, the same code should work with Serenity,
