### ISSUE TITLE
is it possible to consolidate release version?

### ISSUE THREAD

**Issue by tremkonzah** [serenity-bdd/serenity-core#1141]
Is it possible to consolidate release version?
Something like an elastic stack using same version number for all library

When serenity-core release with new version, other serenity repo (cucumber, jbehave, etc) will be release too and will use same version number

now we have to add
```
<serenity.version>1.8.21</serenity.version>
<serenity.cucumber.version>1.6.10</serenity.cucumber.version>
```

this will simplified maven properties for serenity, only add one line and avoid version conflict too
`<serenity.version>1.8.21</serenity.version>`

**Comment by wakaleo** [comment]
Probably not. The life cycles for each module are not related, and the Cucumber and jbehave modules don’t always need to be updated when core is updated (usually they don’t).
