### ISSUE TITLE
Serenity Report - ScreenShots - The Previous/Next Arrows don't diplay against a white background

### ISSUE THREAD

**Issue by AaronDohertyHmh** [serenity-bdd/serenity-core#1142]
**Versions**  
`<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.8.1</serenity.version>
        <serenity.cucumber.version>1.6.5</serenity.cucumber.version>
        <selenium.version>3.7.1</selenium.version>
        <serenity.maven.version>1.8.0</serenity.maven.version>
        <maven.failsafe.plugin.version>2.20.1</maven.failsafe.plugin.version>
        <maven.compiler.plugin>3.6.1</maven.compiler.plugin>`  

**Problem**  
When scrolling through the screenshots in the Serenity Reports for a Scenario.
Anytime the previous / next arrows are against a white background
They don't display, 
However against a dark background they display.

**Please see screenshots**

![serenityscreenshotissue](https://user-images.githubusercontent.com/25454063/36533147-a0273538-17ba-11e8-8c8d-c9ee35e24a2a.png)
![serenityscreenshotissue1](https://user-images.githubusercontent.com/25454063/36533159-a6758408-17ba-11e8-8fd4-d112535b3a40.png)

**Comment by wakaleo** [comment]
Well spotted. Those arrows are part of the javascript slideshow library (so not directly controlled by Serenity), but some CSS in the Serenity code base might be able to help - I would suggest playing round with the Serenity stylesheet to get something you are happy with, and submitting a PR.
