### ISSUE TITLE
index.html is not generated with below serenity version

### ISSUE THREAD

**Issue by rajapcs** [serenity-bdd/serenity-core#1143]
index.html is not generated with below serenity version. I am using Firefox browser.
Browser version - 57
geckodriver version - 0.19.0

<dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>1.8.21</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>1.8.21</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jbehave</artifactId>
            <version>1.35.0</version>
        </dependency>

                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>1.8.21</version>

**Comment by wakaleo** [comment]
We can't do much without a more detailed description of the issue. Have you configured the failsafe plugin to run the Serenity aggregate task? Are you seeing any error messages? Can you provide a sample project?

**Comment by rajapcs** [comment]
Thank you ...Added the Maven-failsafe-plugin which resolves the issue.
