### ISSUE TITLE
want to avoid @ignore tag in serenity report

### ISSUE THREAD

**Issue by dan0935** [serenity-bdd/serenity-core#1145]
I am using jbehave with Serenity. I have 5 scenario in story file and out of which 4 are without @ignore tag,1 with @ignore tag.

I want to exclude my @ignore scenario in serenity report.Currently its still show up in report as ignored:1.I want my test to pass 100% without showing ignored :1 in report.something like(4 passed|0 ignored|0 skipped)

I am using below format for my ignore scenario
 Scenario:abc 
Meta: 
@ignore
When 
Then

Thanks

**Comment by wakaleo** [comment]
This is the intended behaviour of the @ignored annotation. If you want to exclude a scenario completely, you need to use the JBehave metafilters

**Comment by dan0935** [comment]
Thanks for your prompt reply

**Comment by dan0935** [comment]
Which JBehave metafilters we can use to exceude ignore scenarios in our report?

**Comment by wakaleo** [comment]
See http://jbehave.org/reference/stable/meta-filtering.html

**Comment by liviudanu-ellation** [comment]
@dan0935 ,as a more simple solution you can try to remove `@test` annotation and use `@ignore` instead of it. This will not include the test into the report as you driver will not see it.
