### ISSUE TITLE
Index.html not generated for Serenity Rest Assured project types when a Junit assertion fails!

### ISSUE THREAD

**Issue by Ajeshks2510** [serenity-bdd/serenity-core#1147]
POM with below details.

> <properties>
		<serenity.version>1.8.4</serenity.version>
		<serenity.maven.version>1.8.21</serenity.maven.version>
		<junit.version>4.12</junit.version>
		<slf4j.version>1.6.1</slf4j.version>
		<maven.failsafe.plugin.version>2.20.1</maven.failsafe.plugin.version>
		<maven.compiler.plugin.version>3.7.0</maven.compiler.plugin.version>
		<jackson.version>2.6.1</jackson.version>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>2.4.9</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>${jackson.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>${jackson.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.junit</groupId>
			<artifactId>junit5-engine</artifactId>
			<version>5.0.0-ALPHA</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>2.0.0-rc2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.6.1</version>
		</dependency>
		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.4.0</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>${maven.failsafe.plugin.version}</version>
				<configuration>
					<includes>
						<include>**/*.java</include>
					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

![projectstructure](https://user-images.githubusercontent.com/17585475/36594623-e699663e-18c4-11e8-9ca2-c2ebed6357d2.png)

> I am following the code flow to trigger the service calls and verification's.

![serenityrunnerclass](https://user-images.githubusercontent.com/17585475/36594855-ea07a7da-18c5-11e8-81f3-2337912d46c9.png)

![stepclass](https://user-images.githubusercontent.com/17585475/36594890-04f083c8-18c6-11e8-9fca-ad3960cf98c2.png)

- Tests failed as expected, but when I check for "Index.html" it is not generated though assertion failed.
Am I missing anything specific or the implementation is not supported by Serenity?

> Maven Console output

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.bhge.apitests.AceTest.UControllerTest
420 [main] INFO net.serenitybdd.core.Serenity - [36m

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat      
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
 Learn Serenity BDD online at http://serenity-dojo.com                               
-------------------------------------------------------------------------------------
[0m
856 [main] INFO net.serenitybdd.core.Serenity - Test Suite Started: User management controller test
1119 [main] INFO net.serenitybdd.core.Serenity - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: getAllUsers
-------------------------------------------------------------------
1119 [main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
7827 [main] ERROR net.serenitybdd.core.Serenity - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED: Get all users
--------------------------------------------------------------------------
8015 [main] ERROR net.serenitybdd.core.Serenity - TEST FAILED AT STEP Get all users call
8016 [main] ERROR net.serenitybdd.core.Serenity - Verify the Status Codes are Equal :
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.8 sec <<< FAILURE!
getAllUsers(ceTest.UllerTest)  Time elapsed: 6.935 sec  <<< FAILURE!
java.lang.AssertionError: Verify the Status Codes are Equal : 
	at TestSteps.UControllerTestSteps.getAllUsersCall(UtrollerTestSteps.java:42)
	at .AcviceTest.UsrollerTest.getAllUsers(UrTest.java:28)

Results :

Failed tests:   getAllUsers(iceTest.UsllerTest): Verify the Status Codes are Equal : 

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.043 s
[INFO] Finished at: 2018-02-23T18:01:15+05:30
[INFO] Final Memory: 29M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project AcerviceTest: There are test failures.
[ERROR] 
[ERROR] Please refer to \eclipse-workspace\AceTest\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wakaleo** [comment]
Make sure you have the same serenity-maven-plugin and serenity-core versions, but I can't see where the aggregate plugin is being called - are you running 'mvn test' or 'mvn verify'?

**Comment by Ajeshks2510** [comment]
Aggregate plugin is called inside maven plugin @Wakaleo. It was working as expected for pass scenarios. But in the case of Assertion fail only, the index report was not generated.

**Comment by wakaleo** [comment]
There is no relation between a failing test and generating the report if the aggregate plugin is being called from maven during the 'verify' phase. Try using the same version for the maven plugin and serenity-core; there could be a version conflict.

**Comment by Ajeshks2510** [comment]
sure @wakalo. I will update and try.

**Comment by Ajeshks2510** [comment]
@wakaleo : Sorry! It's not not working even for latest version of Serenity and Plugin.
`<properties>
		<serenity.version>1.9.0-rc.3</serenity.version>
		<serenity.maven.version>1.9.0-rc.3</serenity.maven.version>
		<junit.version>4.12</junit.version>
		<slf4j.version>1.6.1</slf4j.version>
		<maven.failsafe.plugin.version>2.20.1</maven.failsafe.plugin.version>
		<maven.compiler.plugin.version>3.7.0</maven.compiler.plugin.version>
		<jackson.version>2.6.1</jackson.version>
		<java.version>1.8</java.version>
	</properties>`

It's not creating index.html only in case of "Test Fail". For pass scenario, index.html generated with individual test details as expected. Is there any logical dependency with the Project implementation while using "Aggregate" of Maven.
Can you please take to 'Index.html' creation area when a 'Test Fail' happened.?

**Comment by wakaleo** [comment]
If you bind the aggregate task to the verify maven phase, it should generate the test reports regardless of whether the test passes or fails, so something odd is apparently happening when the your tests fail. Could you provide a sample project?

**Comment by Ajeshks2510** [comment]
@wakaleo  Below attached a sample project where tests failed and index not generated. As I am working behind a corporate firewall on Windows 10 x64 machine, not able to share original project. But the attached is same as my original project in terms of design and calls(except api values). Only abnormal behavior I am facing in report part in terms of assertion.

[testfailcall.zip](https://github.com/serenity-bdd/serenity-core/files/1758852/testfailcall.zip)

**Comment by wakaleo** [comment]
Your pom.xml file is incorrectly configured. You need to configure the surefire plugin to not run the Serenity tests, e.g.

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>2.20</version>
	<configuration>
		<skip>true</skip>
	</configuration>
</plugin>
```

**Comment by wakaleo** [comment]
See http://maven.apache.org/surefire/maven-surefire-plugin/ and http://maven.apache.org/surefire/maven-failsafe-plugin/. This is a Maven configuration question, unrelated to Serenity.

**Comment by Ajeshks2510** [comment]
@wakaleo Thanks for your comments. I am closing this issue as my code worked for pom with surefire plugin.

**Comment by Deepaksgithub** [comment]
Hi All,

Am able to fetch the CSRF token but when I use the same for posting it to some other POST request , I receive CSRF validation failed. I use serenity rest assured.Any help on this please.
@wakaleo

**Comment by Ajeshks2510** [comment]
Does the first CSRF token is valid for next POST request if you trigger the
request from any other client? If not, you have to get the latest token for
second POST.

**Comment by Deepaksgithub** [comment]
Yes it’s still valid and I don’t use the CSRF for any request , for the first request only am facing 403 error .I assume that I should pass all the cookie with the request . Seeing how to pass the all the cookie .@https://github.com/Ajeshks2510
