### ISSUE TITLE
SerenityRest - Pending steps result in different behavior in @After

### ISSUE THREAD

**Issue by philhinco** [serenity-bdd/serenity-core#1148]
Hello everyone.

I'm currently using Serenity BDD to write integration/regression tests for our company's REST API.

I'm now writing tests for two similar features that behave slightly differently in different "modes".
I'm using tags to tag tests that require an authenticated user. I also wrote a class that contains the `@Before` and `@After` hooks for those tags (ie `@Before("@authenticated")`).

In those `@Before` and `@After` tags I mostly do startup/cleanup things (such as login a test user, etc) or clean the user's profile so the tests do not affect each other.

Now for those two specific tests we do not have the infrastructure up yet to test one step of the tests (verifying that a confirmation mail was sent to the user). Due to that I have those steps in the Feature file but not in the step definitions yet. This causes the test to "fail" as pending, which is expected.

When those tests fail, as expected, the `@After` hook for `@authenticated` is called. In there I clean up the user. 

What is not expected that, for to me unknown reasons, when calling our API to clean up the user in the first of those two tests, SerenityRest returns a *stubbed* version of Response/ValidatableResponse which then, bad for me, returns null from the .as(YourClass.class) call to map to a custom object, causing a NPE.
In the second of those two tests, however, the same code works and returns a normal Response/ValidatableResponse, not causing a NPE when calling .as(YourClass.class).

One weird thing I observed is that, when adding the Step definitions for the pending steps and putting a breakpoint at the throwing of the PendingException, the breakpoint is passed when in the first test, but not in the second.

Does anyone know what the issue could be here?

**Comment by wakaleo** [comment]
This is normal behaviour - when a test fails, Serenity stubs out the REST api to avoid sending unnecessary subsequent queries.

**Comment by philhinco** [comment]
@wakaleo But then why does the same not happen in the next test? The next test (which also has the step missing/just throws PendingException) runs through fine with the REST call working

**Comment by wakaleo** [comment]
I think it will only stub the API out if a failure occurs. I recognise that this is not optimal for REST calls, so will think about some options to make this more flexible.

**Comment by philhinco** [comment]
I've now eliminated what had caused an earlier AssertionFailure, but it still runs into the NPE.

It would be nice if the stubbing would not occur after a PendingException is thrown or if SerenityRest became "unstubbed" once entering `@After` hooks. What I expect would be the behavior I see if I replace `SerenityRest.given` with `RestAssured.given`, which marks the step as Pending.

**Comment by wakaleo** [comment]
Please feel free to dig into the code, we could do with some help maintaining this section of the code base.

**Comment by ManiKalyani234** [comment]
HI Philhinco, What versions of serenity and serenity-cucumber you are using ? I am getting net/serenitybdd/rest/decorators/request/RequestSpecificationInitialisation error when I my tests calling @before method ? Could you please help me ?
