### ISSUE TITLE
rest-assured aggregated reports missing when using custom `filter`

### ISSUE THREAD

**Issue by witoldsz** [serenity-bdd/serenity-core#1149]
Hi,
code like this works just fine:

```java
given()
  .baseUri("http://…")
  .port(4040)
.when()
  .get("…")
.then()
  .statusCode(200)
  .etc…
```

Once I add a custom filter, let it be as simple as:

```java
given()
  .baseUri("http://…")
  .port(4040)
  .filter((req, res, ctx) -> ctx.next(req, res)) //as simple as it can be
.when()
  .etc…
``` 

, then the aggregated report is missing the requests from "steps" section (with that green "REST Query" buttons).

I am using my custom filter to perform a custom authentication.

HOWEVER:

When I configure my filter like this:

`SerenityRest.filters(…my_filter_here…);`

Then it works, but this is not acceptable, because each test appends new filter, and the filter itself depends on an `Actor` preforming the action, so no `static` configuration suits the case.

**Comment by wakaleo** [comment]
Can you have a look at the code and propose a PR? It might be a new API feature that hasn’t been wrapped by Serenity

**Comment by witoldsz** [comment]
Believe me, I have tried. The amount of indirections, proxies, fly-through classes and what else – made me failed. I am sorry. Will try again, hopefully.

**Comment by wakaleo** [comment]
Canyon provide a sample project?

**Comment by witoldsz** [comment]
@wakaleo Would it be possible to create a failing integration test for this bug, within `serenity-core`?

**Comment by wakaleo** [comment]
Certainly, be my guest!

**Comment by cliviu** [comment]
It should be fixed in the next version
