### ISSUE TITLE
All Serenity Properties for Appium

### ISSUE THREAD

**Issue by Warren25** [serenity-bdd/serenity-core#1151]
What are ALL the serenity properties for Appium?

I have and read and examined the documentation here: http://www.thucydides.info/docs/serenity/

AND

The Appium Serenity project here: https://github.com/vikramvi/AppiumSerenityPOC

I am currently using these appium-related properties:
appium.platformName
appium.deviceName
**appium.newCommandTimeout**
appium.app
**appium.noReset**
appium.automationName

The properties in bold are not presented in either of the two sources above, and quite frankly, I guessed that they would work, and they do. This implies that there are other serenity-appium properties, however I know that not ALL appium capabilities are supported from this link: https://appium.io/docs/en/writing-running-appium/caps/

What I would like is an official list of supported Appium capabilities. Where is that documentation? 

Any help on this is appreciated.

**Comment by wakaleo** [comment]
Any property that starts with "appium" will be passed through, both with and without the "appium" prefix.

**Comment by Warren25** [comment]
@wakaleo Ah, I understand now. Thank you for your quick response. I guess this question can be closed.

**Comment by wakaleo** [comment]
See the previous response.
