### ISSUE TITLE
java.lang.IllegalArgumentException: Can not set net.serenitybdd.core.pages.WebElementFacade field

### ISSUE THREAD

**Issue by PratapSingh09** [serenity-bdd/serenity-core#1152]
java.lang.IllegalArgumentException: Can not set net.serenitybdd.core.pages.WebElementFacade field

Below Code used:
@androidfindby(id = "com.awe.wed:id/see_more")
private WebElementFacade seeMoreIcon;

public class MobilePageObject extends PageObject {

public MobilePageObject(final WebDriver driver) {

super(driver, new Predicate<PageObject>() {

  public boolean apply(PageObject page) {

    PageFactory.initElements(
        new AppiumFieldDecorator(((WebDriverFacade) page.getDriver()).getProxiedDriver(),
            page.getImplicitWaitTimeout().in(TimeUnit.SECONDS), TimeUnit.SECONDS),
        page);

    return true;
  }

});
}

Error:

[main] WARN net.thucydides.core.pages.Pages - Failed to instantiate page of type class com.itv.android.page.HomePage ({})
java.lang.IllegalArgumentException: Can not set net.serenitybdd.core.pages.WebElementFacade field com.itv.android.page.HomePage.seeMoreIcon to io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$3c371404
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArg

Dependency used:
serenity.version>1.2.5-rc.1</serenity.version>
<serenity.cucumber.version>1.1.28</serenity.cucumber.version>
<serenity.maven.version>1.2.5-rc.1</serenity.maven.version>

And tried to changes it to 1.9.0.rc.3 but did not found dependency

Pom Used:
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<serenity.version>1.2.5-rc.1</serenity.version>
		<serenity.cucumber.version>1.1.28</serenity.cucumber.version>
		<serenity.maven.version>1.2.5-rc.1</serenity.maven.version>
		<surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
		<maven.test.failure.ignore>true</maven.test.failure.ignore>
		<log4j.version>1.2.17</log4j.version>
	</properties>

	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>https://mvnrepository.com</url>
		</repository>
	</repositories>
	

	<dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.6</version>
		</dependency>
		
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.7</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>1.0.47</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>1.7.0</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					<systemPropertyVariables>
						<file>kpn.373-sit.apk</file>
						<appium.host>127.0.0.1</appium.host>
						<appium.port>4723</appium.port>
						<implicit.wait>200</implicit.wait>
						<platform.name>Android</platform.name>
						<device.name>4f5e98fe</device.name>
						<no.reset>true</no.reset>
						<appium.log>info</appium.log>
					</systemPropertyVariables>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					
					<includes>
						<include>**/Run*.java</include>
						<include>**/test/**/*.java</include>
						<include>**/features/**/*.java</include>
					</includes>
					<systemProperties>
						<surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
						<surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
					</systemProperties>
					<encoding>${project.build.sourceEncoding}</encoding>
					<argLine>-Xmx512m</argLine>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<fork>true</fork>
					<executable>C:\Program Files\Java\jdk1.8.0_144\bin\javac.exe</executable>
					
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by cliviu** [comment]
HI @PratapSingh09 . It is not necessary anymore to use the MobilePageObject. Use directly the PageObject.

**Comment by wakaleo** [comment]
In addition, you will need to upgrade to at least 1.8.x.

**Comment by himym42** [comment]
Hi @wakaleo and @cliviu .
for me using PageObject is working since 1.9.0.
Many Thanks ;-)

**Comment by wakaleo** [comment]
Thanks for the update :-)
