### ISSUE TITLE
@Title annotation not allowing to set value run-time via parameterization (Serenity Rest BDD).

### ISSUE THREAD

**Issue by Ajeshks2510** [serenity-bdd/serenity-core#1153]
I am Running 'Rest Assured Serenity Tests' from Java in windows platform. My tests are referenced in Excel and I want to run with the value provided in 'Description'. This can be different for different tests and Iterations. When I performed the operation, it's not allowing me to access the way given below:

`public static String collectedFromExcel = "";
	
	@Title(value=collectedFromExcel)
	@Test
	public void getAllUsers() {
		for (int i = 0; i < 5; i++) {
			userManagementControllerTestSteps.getAllUsersCall();
		}
	}`
I am getting the error as 'The value for annotation attribute Title.value must be a constant expression'. When I check the Implementation of 'Title' annotation, it is accepting String value. 
`public @interface Title {
    String value();
}`

Also test annotation access the optional value as: `Title titleAnnotation = testMethod.get().getAnnotation(Title.class);`

Is there any way I can feed title values run-time and create that in Report?

**Comment by wakaleo** [comment]
This is not possible with Java annotations.
