### ISSUE TITLE
can't run serenity appium without .apk file

### ISSUE THREAD

**Issue by Prasannajnaeyulu** [serenity-bdd/serenity-core#1154]
I have an app already installed in my mobile. I just want to launch the app. and run the tests on it.
But, I am getting the following error if I ignore appium.app property from serenity.properties file

Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (The browser under test or path to the app needs to be provided in the appium.app or appium.browserName property.

webdriver.driver= appium
appium.hub = http://127.0.0.1:4723/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1.1
appium.deviceName = CB51234567
appium.appPackage = com.sample.test.dev
appium.appActivity = com.sample.test.dev.ui.login.LoginActivity
appium.noReset = true

**Comment by wakaleo** [comment]
This is an appium usage question, not a Serenity defect - could you close it and repost the question on https://serenity-BDD.rocket.chat?

**Comment by Prasannajnaeyulu** [comment]
I think this is possible in appium. If you don't specify the app property, It will find the installed app by its appPackage property. But, It looks like the validation on app. property seems to be mandated in serenity core as per the exception. So, Its rejecting it. Something needs to be fixed from serenity-core library so opening the issue.

**Comment by wakaleo** [comment]
Feel free to look into the code and propose a PR if you see something not behaving as it should.

**Comment by Prasannajnaeyulu** [comment]
Sure @wakaleo. Right now, I am trying to use serenity for mobile automation. But, It seems to have issues with webdriver creation and using androidfindby annotations with MobileElement, WebElementfacade etc.. So, I am bit worried is it worth use this now? Or better to stick to appium client without serenity. Looks like the appium Integration with serenity is not stable.

**Comment by wakaleo** [comment]
The appium integration is largely community supported, you should ask on Rocket Chat as there are many users who use Serenity and Appium together.

**Comment by Prasannajnaeyulu** [comment]
we can achieve this by simply setting the app property to empty value as per help received from rocket chat. Thanks for that. So, closing this issue.
webdriver.driver= appium
appium.hub = http://127.0.0.1:4723/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1.1
appium.deviceName = CB51234567
**_appium.app =_** 
appium.appPackage = com.sample.test.dev
appium.appActivity = com.sample.test.dev.ui.login.LoginActivity
appium.noReset = true
