### ISSUE TITLE
compatibility issues while upgrading serenity core version

### ISSUE THREAD

**Issue by Prasannajnaeyulu** [serenity-bdd/serenity-core#1155]
I am using serenity core 1.8.1. I am just trying to upgrade serenity-core with new version 1.8.21 to just check androidfindby annotation working with webelementfacade. But, I end up having a strange issue as follows. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (default) on project eqm-auto: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: net/thucydides/core/pages/PageObject
[ERROR]         at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR]         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[ERROR]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[ERROR]         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR]         at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR]         at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[ERROR]         at java.security.AccessController.doPrivileged(Native Method)
[ERROR]         at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[ERROR]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR]         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
[ERROR]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR]         at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
[ERROR]         at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:96)
[ERROR]         at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:311)
[ERROR]         at org.apache.maven.surefire.junit4.JUnit4Provider.setTestsToRun(JUnit4Provider.java:191)
[ERROR]         at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:134)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.ClassNotFoundException: net.thucydides.core.pages.PageObject
[ERROR]         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR]         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
[ERROR]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR]         ... 20 more
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by wakaleo** [comment]
It’s a dependency conflict - make sure you have the latest version of everything

**Comment by Prasannajnaeyulu** [comment]
I have 
		<serenity.version>1.8.1</serenity.version>
		<serenity.maven.version>1.8.1</serenity.maven.version>
		<serenity.cucumber.version>1.6.3</serenity.cucumber.version>

using higher serenity cucumber version is throwing some other problem

**Comment by wakaleo** [comment]
The latest versions can generally be found here: https://github.com/serenity-bdd/serenity-cucumber-starter/blob/master/pom.xml. Since this is not an issue with the Serenity code, could you please close this and repost the question on the Serenity Rocket Chat channel?

**Comment by ricardorlg** [comment]
@Prasannajnaeyulu with last version serenity and appium works without problems, in rocket chat you can find posts about that, this can be closed.

**Comment by wakaleo** [comment]
Thanks @ricardorlg
