### ISSUE TITLE
proxy with pac file

### ISSUE THREAD

**Issue by LordOfYoro** [serenity-bdd/serenity-core#1160]
Hello, 
I want to use a proxy with pac file because, my organization haven't got any other alternative to access internet.
We need to set up link to proxy.pac file for all browsers and we couldn't find a way to do it with serenity.
Is there any system property or serenity.property to do it ?

Thanks a lot.

**Comment by wakaleo** [comment]
You will need to code this yourself, possibly  via a custom driver

**Comment by hollandjake** [comment]
@wakaleo is this still the case? Does serenity not natively support PAC file proxies?

**Comment by wakaleo** [comment]
How would it work in Selenium? Using the Selenium 3 configuration standards you can do most things in the serenity.conf file now

**Comment by hollandjake** [comment]
We were creating a proxy like this

```
Proxy proxy = new Proxy();
proxy.setProxyType(Proxy.ProxyType.PAC);
proxy.setProxyAutoconfigUrl("some.url.to.pac.file");
```

**Comment by hollandjake** [comment]
It seems serenity is supporting this already but it has been blocked by some logic net.serenitybdd.core.webdriver.driverproviders.ConfiguredProxy
