### ISSUE TITLE
Serenity BDD With Cucumber Running Parallel using cucumber-jvm-parallel-plugin generating corrupted Report

### ISSUE THREAD

**Issue by imram** [serenity-bdd/serenity-core#1164]
Demo Repo: https://github.com/imram/serenitybddIssues

mvn clean verify Log File inside Repo: https://github.com/imram/serenitybddIssues/blob/master/parallelExecution.txt

Hello,
I am using cucumber-jvm-parallel-plugin plugin to generated test runner for my serenity bdd with cucumber BDD Tests. As long as parallelScheme is FEATURE things works good. But when I am changing to SCENARIO, it generates report after execution which does not look right and as all acceptance tests will show pass with showing no steps and one of them will bundle all the step definitions.

I am trying to achieve the SCENARIO SCHEME based Parallel execution for my acceptance tests. As of now have not been able to successful per the Demo project. Neither it runs good and shows Errors as seen in Log File mentioned above, nor its report generates correctly.

Could you please look into it and advise.

Thanks in advance.

Regards
Ram

**Comment by wakaleo** [comment]
For a number of reasons, the current implementation of this plugin will not work with Serenity running parallel scenarios, due to both the way the plugin is implemented, and the way the Seenity reports need to be generated. So this is not something we will be supporting at this stage.

**Comment by imram** [comment]
@wakaleo Thank you so much for your reply. Looking forward to see it as new feature for Serenity BDD with cucumber at some point of time in future 💯
