### ISSUE TITLE
Generating test results for 0 tests: when developing reports in Jbehave using serenityBDD

### ISSUE THREAD

**Issue by edurb** [serenity-bdd/serenity-core#1167]
I am trying to generate a report using serenity plugin. I have updated the pom file with plugin and dependency. When I run the tests as maven install, I see the Generating test results for 0 tests as output. The serenity report shows the blank chart. Anyone who has come across this issue. 
Here is the pom file:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>jbehave-web-webdriver</groupId>

	<artifactId>jbehave-web-webdriver</artifactId>

	<version>1.0</version>

	<name>JBehave WebDriver Stories</name>

	<description>

Stories verifying behaviour of jbehave-web-trader-runner example application, using the WebDriver API of Selenium 2.

</description>

	<packaging>jar</packaging>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<jbehave.webapp.name>trader-runner</jbehave.webapp.name>

		<maven.compiler.source>1.7</maven.compiler.source>

		<maven.compiler.target>1.7</maven.compiler.target>

	</properties>

	<dependencies>
		<dependency>

			<groupId>org.jbehave.web</groupId>

			<artifactId>jbehave-web-selenium</artifactId>

			<version>3.6-beta-2</version>

			<scope>compile</scope>

			<optional>true</optional>

		</dependency>

		<dependency>

			<groupId>org.seleniumhq.selenium</groupId>

			<artifactId>selenium-java</artifactId>

			<version>2.48.2</version>

		</dependency>

		<dependency>

			<groupId>org.jbehave</groupId>

			<artifactId>jbehave-core</artifactId>

			<version>4.0.4</version>

		</dependency>

		<dependency>

			<groupId>org.jbehave</groupId>

			<artifactId>jbehave-core</artifactId>

			<version>4.0.4</version>

			<classifier>resources</classifier>

			<type>zip</type>

			<scope>test</scope>

		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jbehave</artifactId>
			<version>1.24.0</version>
		</dependency>

		

		<dependency>

			<groupId>org.freemarker</groupId>

			<artifactId>freemarker</artifactId>

			<version>2.3.20</version>

			<optional>true</optional>

		</dependency>

		<dependency>
			<groupId>com.saucelabs</groupId>
			<artifactId>saucerest</artifactId>
			<version>1.0.35</version>
		</dependency>

		

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>1.2.3</version>
		</dependency>
	</dependencies>

	<build>

		<resources>

			<resource>

				<directory>src/main/java</directory>

				<filtering>false</filtering>

			</resource>

		</resources>

		<plugins>

			

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.0</version>

				<configuration>
					<encoding>${project.build.sourceEncoding}</encoding>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>1.2.3</version>

				<executions>
					<execution>
						<id>serenity-reports</id>

						<phase>post-integration-test</phase>

						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<includes>
						<include>**/WebStories.java</include>
					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

<img width="1017" alt="screen shot 2018-03-15 at 11 07 19 am" src="https://user-images.githubusercontent.com/13241075/37471832-0f8687bc-2841-11e8-9654-78fdc7364fb6.png">

**Comment by wakaleo** [comment]
Looks like a uMaven config issue, unrelated to Serenity - no tests are being detected by Maven.

**Comment by edurb** [comment]
@wakaleoI am not sure what's wrong in the maven config, do you have an issue which I can refer to for more details.

**Comment by wakaleo** [comment]
It’s not a Serenity bug, so it would be better to close the issue here and ask the Serenity community for some help on https://serenity-bdd.rocket.chat
