### ISSUE TITLE
Error loading a jdbc driver

### ISSUE THREAD

**Issue by jdmesalosada** [serenity-bdd/serenity-core#1168]
Hi everyone, 

I have a project where I need to connect to AS400 in order to get some data for my preconditions for this I'm using AS400JDBCDriver:

```
private static final String driver = "com.ibm.as400.access.AS400JDBCDriver";

Class.forName(driver);
```

but I'm getting the following error: 

net.serenitybdd.core.exceptions.SerenityManagedException: com.ibm.as400.access.AS400JDBCDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

I already added the jar jt400 into my classpath, but I'm unable to run my project.

Also I created another project to test the connection and it worked but it fails when I run with serenity.

Thanks in advanced.

**Comment by wakaleo** [comment]
Probably a dependency conflict - check the underlying error message and do a dependency analysis on your project to look for conflicts.

**Comment by wakaleo** [comment]
Closed for lack of activity.
