### ISSUE TITLE
Phantom

### ISSUE THREAD

**Issue by ddt-tdd** [serenity-bdd/serenity-core#117]
Hi,

In PhantomJSCapabilityEnhancer.java file in the function setSecurityOptions() the parameter "--ssl-protocol=any" is hardcode. This gives problems with my vulnerability scanner (OWASP zaproxy) to automise the vulnerability scanning.
Is it possible to make this a parameter, which can be given in maven or the serenity.properties file?

Greetings,
David Tillemans

**Comment by wakaleo** [comment]
Sure, that would be easy enough - I'll put it in the backlog.

On 27 August 2015 at 21:03, DDT <notifications@github.com> wrote:

> Hi,
>
> In PhantomJSCapabilityEnhancer.java file in the function
> setSecurityOptions() the parameter "--ssl-protocol=any" is hardcode. This
> gives problems with my vulnerability scanner (OWASP zaproxy) to automise
> the vulnerability scanning.
> Is it possible to make this a parameter, which can be given in maven or
> the serenity.properties file?
>
> Greetings,
> David Tillemans
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/117>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by ddt-tdd** [comment]
I've forked the serenity-core and added the patch for 2 files:
feat: added a environment variable PHANTOMJS_SSL_PROTOCOL which can be set on 'sslv2', 'sslv3', 'tlsv1' and 'any'. 

You can perform pull from https://github.com/ddt-tdd/serenity-core

How can I write some test code according to Serenity coding guidelines? (I use serenity on an other environment :-( and cannot develop on this environment)
