### ISSUE TITLE
not able to run Firefox in headless mode with @Managed annotation

### ISSUE THREAD

**Issue by fabiobravaglieri** [serenity-bdd/serenity-core#1170]
Hi Team, 
I tried to run my simple web test with serenity core 1.9.3 with both Firefox (59.0) and Chrome (65.0) webdrivers (geckodriver v0.20) and everything works fine in "headed mode".
When I try to run in headless mode with @Managed annotation:

```
@RunWith(SerenityRunner.class)
public class FlickrSearchTest {


    @Managed(driver="chrome")
    WebDriver driver;
```
launching this test with command:

`
mvn -Dheadless.mode=true test
`

it works fine.
When I change the web driver annotation "chrome" to "firefox", the test passes as well but Firefox does not run in headless mode.

I've found this cahngelog that should apply to my situation: 
https://github.com/serenity-bdd/serenity-core/blob/master/CHANGELOG.md#v180 

Is there a bug?

Thanks,
Fabio

**Comment by wakaleo** [comment]
The Firefox support for headless mode is a bit inconsistent, and the normal capability-based approach doesn't seem to work in the current versions. You can use the `gecko.firefox.options` property to get the same effect:

```
gecko.firefox.options = {"args": ["-headless"]}
```

**Comment by fabiobravaglieri** [comment]
Thank you for the answer!
It works fine.
Fabio
