### ISSUE TITLE
Implication of Skipping a part of the framework

### ISSUE THREAD

**Issue by Afez89** [serenity-bdd/serenity-core#1173]
Hi @wakaleo  i understand for Serenity BDD implementation, you would require 1) Feature, 2) StepDef, 3) Steps 4)Page Files. What if i decide to skip a component like 3) Steps and just link 2) to 4). What is the implication?

**Comment by wakaleo** [comment]
As this is a question, could you close this issue and ask your question on https://serenity-bdd.rocket.chat instead?
