### ISSUE TITLE
Serenity overwrites xml/json reports during re-run

### ISSUE THREAD

**Issue by Vovanchik** [serenity-bdd/serenity-core#118]
I am using re-run feature from surfire plugin in maven build to run serenity tests with junit if it was failed.

After some time I noticed that serenity instead of creating new xml/json file during re-run overwrite it. Previously it was working well. During re-run additional file was created with status of re-run.

Please investigate this issue.

**Comment by cliviu** [comment]
Hi, what was the last serenity version where the files were not overwritten ?

**Comment by Vovanchik** [comment]
Hi, hard to say. For sure it work's in thucydided. :)

**Comment by cliviu** [comment]
Can you post your maven command line  please ?

**Comment by YamStranger** [comment]
Hello @Vovanchik.  Thanks for this issue, but it seems that nobody can reproduce it. It seems that this issue already fixed, or now it is not an issue - so I close it.  

Thanks!
