### ISSUE TITLE
FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver

### ISSUE THREAD

**Issue by muli09** [serenity-bdd/serenity-core#1185]
When execute code in linux through Jenkins getting the below error but the same code is working on my local mac book.

I tried with chrome as well .

23711 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'md-bdadev-190.verizon.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.21.2.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'md-bdadev-190.verizon.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.21.2.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver

Please suggest me

**Comment by wakaleo** [comment]
“Could not instantiate new WebDriver instance” is a Selenium driver issue, unrelated to Serenity. Make sure geckodriver is correctly installed and available and that Firefox is the most recent version.

**Comment by muli09** [comment]
but I able to execute the same code in my local  and even for chrome also getting sam e error.

TEST STARTED: Apply keyword search to check if data is returned
-------------------------------------------------------------------
/home/builds/ConvergenceUiAutomation/chromedriver: /home/builds/ConvergenceUiAutomation/chromedriver: cannot execute binary file
Mar 28, 2018 8:56:28 AM org.openqa.selenium.os.UnixProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 126 (Exit value: 126)
23282 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.chrome.ChromeDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Timed out waiting for driver server to start.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'md-bdadev-190.verizon.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.21.2.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: unknown
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Timed out waiting for driver server to start.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'md-bdadev-190.verizon.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.21.2.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: unknown
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:135)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:147)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:138)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:108)
	at net.thucydides.core.webdriver.WebDriverFacade.manage(WebDriverFacade.java:378)
	at net.palomar.showcase.cucumber.steps.serenity.SerenitySteps.do_login(SerenitySteps.java

**Comment by wakaleo** [comment]
These are all selenium installation issues unrelated to Serenity. It would be better to post a question in the Serenity chat or on one of the Selenium mailing lists

**Comment by wakaleo** [comment]
Closing as this is a selenium configuration issue, not a Serenity one.
