### ISSUE TITLE
Cannot make Serenity report display examples values in Scenario outlines titles

### ISSUE THREAD

**Issue by jakimcho** [serenity-bdd/serenity-core#1188]
Hello,
I guess I'm not the first one asking this question, but all other issues and posts I found till now did not help me.
I have a cucumber feature file with a scenario outline that has examples placeholders in its title:
```
@sanity-check
  Scenario Outline: Player tries to complete Personal details form with <validation_type> in the <field>
    When the player completes Personal details form on Buy Credits page:
      | title   | first_name   | last_name   | date_of_birth   |
      | <title> | <first_name> | <last_name> | <date_of_birth> |
    Then validation "<validation_massage>" for "<field>" should appear on Personal details form

    Examples:
      | validation_type    | field         | title | first_name        | last_name                 | date_of_birth | validation_massage                      |
      | blank field        | title         |       | Automation        | Automation                | 02-27-1995    | This field is required                  |
      | numeric characters | first name    | Mr    | Automation1       | Automation                | 02-27-1995    | Please enter only alphabetic characters |
      .............................
      .............................
      .............................
```

My intention is to have more descriptive scenarios titles for each scenario outline run in the report. Something like the one I get in cucumber report:

![cucumber_html](https://user-images.githubusercontent.com/6280772/38196339-1f6271c0-368b-11e8-959a-f44b98167e68.PNG)
The examples placeholders in scenario titles are populated with the values from the examples table

But in serenity report I'm getting:
![serenity_report](https://user-images.githubusercontent.com/6280772/38196353-413dceb6-368b-11e8-9b52-436ba6b07268.PNG)
The examples placeholders in scenario titles are **not** populated with the values from the examples table

I'm using `serenity-core` and `serenity-maven-plugin` versions - `1.9.4`

**Comment by wakaleo** [comment]
This is a serenity-cucumber issue, could you raise the issue against that project so that we can track it more accurately?

**Comment by jakimcho** [comment]
Hello,
Issue is moved to serenity-cucumber project: [issue 138](https://github.com/serenity-bdd/serenity-cucumber/issues/138)
