### ISSUE TITLE
Need help setting up Serenity with Selenium Grid

### ISSUE THREAD

**Issue by copavan** [serenity-bdd/serenity-core#1190]
How do I make Serenity work with Selenium Grid. I have set up both Hub and Node machines. I've updated Serenity.properties file as below to have the same test run in parallel on different browsers, but this isn't working. Can someone help me correct the configuration.

webdriver.remote.driver = chrome
webdriver.remote.url=http://xx.xx.xx.xx:5566/wd/hub
webdriver.remote.driver = firefox
webdriver.remote.url=http://yy.yy.yy.yy:5577/wd/hub
webdriver.remote.driver = ie
webdriver.remote.url=http://zz.zz.zz.zz:5588/wd/hub

**Comment by wakaleo** [comment]
As this is a question rather than a defect, could you ask it on https://serenity-bdd.rocket.chat?
