### ISSUE TITLE
@step not getting disaplayed in index.html

### ISSUE THREAD

**Issue by banuts** [serenity-bdd/serenity-core#1192]

**Comment by banuts** [comment]
The execution is happening correctly and the snapshots are also getting captured 
In index.html the pie chart is also getting generated 
But when the scenario name is being clicked in index.html there is no given when then from the JIRA story getting displayed

**Comment by wakaleo** [comment]
Can you provide a sample project?

**Comment by banuts** [comment]
It’s from Finacle product

**Comment by wakaleo** [comment]
Maybe post the question on https://serenity-bdd.rocket.chat, it sounds like a usage problem.
