### ISSUE TITLE
Tests shows skipped after assertion failure inside a loop for "serenity-core 1.9.0-rc.3"

### ISSUE THREAD

**Issue by Ajeshks2510** [serenity-bdd/serenity-core#1200]
Serenity report, index.html shows test steps are skipped, when a step in middle failed during iterative execution.
I am executing @Tests from serenity runner class in which each @Step methods are called iteratively. When a step at middle index failed, reaming subsequent steps are shown as Skipped in report.
I am looking for a solution to run my @Steps with different data provided from @Test method and perform a validation inside @Step irrespective of failure. But if a failure happened for one index, that information need to be included inside report and proceed further with remaining iterations.

`@Steps
	TestSteps testSteps;`
`@Title()
	@Test
	public void performIteration {
		for(int i=0;i<4;i++) {
			testSteps.verifyDataForEach(i);
		}
	}`

Inside @Step implementation

import org.junit.gen5.api.Assertions;

`@Step
	public void verifyDataForEach(int i) {
		if(i==1) {
				Assertions.assertFalse(true);
		}else {
			Assertions.assertFalse(false);
		}
	}`

Outcome:

![steps_skipped](https://user-images.githubusercontent.com/17585475/38569347-a3dc2dfa-3d08-11e8-8ed3-c685e505b514.png)

Is it possible to continue Steps execution even after an assertion failed in any ways of using Serenity Reporting module? There are scenarios required run steps if we use customized implementation of @Tests.

**Comment by wakaleo** [comment]
This is expected behaviour - steps after a failure will be skipped. Use soft assertions (not @step methods) or data-driven tests for this.
