### ISSUE TITLE
Version of Serenity is hardcoded in serenity-version.properties

### ISSUE THREAD

**Issue by anthrax-0** [serenity-bdd/serenity-core#1202]
It seems that Serenity version was accidentally frozen in serenity-version.properties and was 1.8.1 for the last couple of months.
 As this version is shown in the main index.html it makes it hard to verify if the update to new dependency version was successful.
 As we don't use Serenity with Selenium, I could only test my reverse[ commit ](https://github.com/anthrax-0/serenity-core/commit/c6fe95f29b013ad7aed8691a0c58ecdd29964b12) with a limited set of tests and so no pull request is created before full tests can be run.

**Comment by wakaleo** [comment]
Fixed.
