### ISSUE TITLE
empty report after aggregation

### ISSUE THREAD

**Issue by Prasannajnaeyulu** [serenity-bdd/serenity-core#1205]
I am using serenity maven plugin for aggregating the reports. If I run the tests using CucumberWithSerenity runner with one specific feature tag say,  -Dcucumber.options="--tags @Login" then I am getting the aggregated report with all the scenarios of Login feature in the report. 

But, if I run the specific scenarios/features with multiple tags say, -Dcucumber.options="--tags @Login, @book-appointment" then I am getting the empty report as shown in the attached screenshot.

I am using..
serenity-core 1.9.6
serenity-maven-plugin 1.9.2
serenity-cucumber 1.9.3

Have you seen below, total 9 scenarios have been executed successfully. But in the aggregation report its just said like 0 tests and I got empty report as in the attached screenshot.
![empty_report](https://user-images.githubusercontent.com/2508680/38626842-634f88e8-3da5-11e8-950d-dff6a5e07ad6.png)

Excerpts from console:
==============
**9 Scenarios (9 passed)**
42 Steps (42 passed)
9m51.021s

**Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 591.971 sec - in**
com.auto.CucumberSerenityTestRunner

Results :

**_Tests run: 9, Failures: 0, Errors: 0, Skipped: 0_**

[INFO]
[INFO] --- serenity-maven-plugin:1.9.2:aggregate (serenity-reports) @ mobile-auto ---
[INFO] current_project.base.dir: C:\workspace\automation\mobile-auto
**_[INFO] Generating test results for 0 tests_**
[INFO] 6 requirements loaded after 399 ms
[INFO] 6 related requirements found after 400 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 442 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 2269 ms
![empty_report](https://user-images.githubusercontent.com/2508680/38629210-518d0f08-3dab-11e8-9f01-1a5c6606de16.png)

**Comment by wakaleo** [comment]
I'm unable to reproduce this at all - could you provide a sample project?

**Comment by Prasannajnaeyulu** [comment]
Hi @wakaleo I am running with CucumberWithSerenity using maven failsafe plugin and using the following versions....
serenity-core 1.9.6
serenity-maven-plugin 1.9.2
serenity-cucumber 1.9.3

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features="src/test/resources/features/")
public class CucumberSerenityTestRunner {}

**Comment by Prasannajnaeyulu** [comment]
Hi @wakaleo This is the sample project to reproduce the Issue.
https://github.com/Prasannajnaeyulu/serenity-report-aggregation-failure

**Comment by wakaleo** [comment]
If you are using the cucumber.options parameter, you need to use the correct Cucumber tags syntax (see https://github.com/cucumber/cucumber/tree/master/tag-expressions), e.g.

```
mvn clean verify -Dcucumber.options="--tags '@sample1 or @sample2'"
```
