### ISSUE TITLE
[Screenplay]  is there a screenplay class to upload file?

### ISSUE THREAD

**Issue by romainbb** [serenity-bdd/serenity-core#1210]
Hello,

I use serenity with the screenplay implementation, and for several tests I need to upload files from html forms.

I saw that we can use the upload method: upload(filename).to(logoField);

But does it exist a screenplay class like Enter.theFile(filename).into(target) (or is it foreseen?)

My temporary solution is to implement an Interaction class to make the upload.

Thanks for your answer.

**Comment by wakaleo** [comment]
No, but you are welcome to contribute one.

**Comment by romainbb** [comment]
Thanks for your answer.
If my solution works well, I'll propose you :)

**Comment by giangnd2508** [comment]
Another solution for that is Enter value into Input tag.
