### ISSUE TITLE
Not Issue: Question : IS there any way we can connect remote desktop using serenity

### ISSUE THREAD

**Issue by prat23k** [serenity-bdd/serenity-core#1211]
Hi,

I have a scenario that i have to connect windows remote desktop and execute tests on tool.

Is it possible through serenity.

Thanks

**Comment by wakaleo** [comment]
It is possible if you can do it with Java. Otherwise, probably not.

**Comment by prat23k** [comment]
Thanks @wakaleo , yes i thought of doint with Java, could you help me which library i can use.

Thanks

**Comment by wakaleo** [comment]
I'm not aware of any libraries to do that with Windows (it's doable for Unix though).

**Comment by prat23k** [comment]
Ok thank you
