### ISSUE TITLE
Question: How to rerun failed cucumber tests?

### ISSUE THREAD

**Issue by sisihaha** [serenity-bdd/serenity-core#1213]
Noticed that there was a pull request #694 introduced property test.retry.count.cucumber. Seems that rerun  failed cucumber tests is supported.
I tried to add test.retry.count.cucumber=1 to serenity.properties. However, rerun did not happen.
Any idea how to rerun failed cucumber tests? Please advise. Thank you.

**Comment by cliviu** [comment]
hi @sisihaha .. No, unfortunately is currently not supported. It worked for some previous version of cucumber.

**Comment by sisihaha** [comment]
Hi @cliviu 
Thanks for the quick response. Now I use maven-failsafe-plugin to rerun the failed tests instead.
