### ISSUE TITLE
Incorrect tests number generated in Serenity report for scenario outline, when parallelScheme is SCENARIO for cucumber-jvm-parallel-plugin

### ISSUE THREAD

**Issue by sisihaha** [serenity-bdd/serenity-core#1214]
When parallelScheme is SCENARIO for cucumber-jvm-parallel-plugin, the tests number for scenario outline with multiple rows of examples is always only 1 in Serenity report.
Hit this issue, when using serenity-core 1.9.8 and serenity-cucumber 1.9.4.
Please help to look into it. Thank you.

Note:
Does not hit the issue in the same situation, when using serenity-core 1.5.8 and serenity-cucumber 1.1.36.

**Comment by wakaleo** [comment]
This is not currently supported as cucumber-jvm-parallel-plugin runs all the examples in an example table as separate scenarios, which messes with the Serenity event architecture. serenity-core 1.5.8 used Cucumber 1.x, which had a different event model.

**Comment by sisihaha** [comment]
Thank you for the quick response.
