### ISSUE TITLE
Unable to capture network traffic when integrated with JUnit test

### ISSUE THREAD

**Issue by AllysonYuShiong** [serenity-bdd/serenity-core#1218]
Hi guys, I'm unable to get network traffic when I integrated with my JUnit test but I'm able to get traffic if I'm using driver call method. 
For example, JUnit test that is unable to get traffic:
```
landingPageSteps.openLandingPage()
                .headerSteps.clickOnSearchButton();
searchPageSteps.typeInSearchField(“movie”);
```

Example of driver call method that can get network traffic:
```
driver.get(“https://testing.com”);
WebElement searchButton = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div[2]/div/div/div[2]/div[1]/div[1]"));
        searchButton.click();
        WebElement searchField = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div[5]/div[1]/div[2]/div/div/input"));
        searchField.clear();
        searchField.sendKeys("movie");
```

These are my findings on other versions of browsermob proxy:

Maven Dependency | Version | Able to get traffic when integrated with existing script? (Y/N) | Able to get traffic when integrated with driver call method? (Y/N)
-- | -- | -- | --
<groupId>net.lightbody.bmp</groupId><artifactId>browsermob-core</artifactId> | 2.1.5, 2.1.4, 2.1.3 | N | Y
<groupId>net.serenity-bdd</groupId><artifactId>serenity-browsermob-plugin</artifactId> | 1.9.7 | N | Y
<groupId>net.lightbody.bmp</groupId><artifactId>browsermob-legacy</artifactId> | 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0 | Y(Traffic is encrypted) | Y(Traffic is encrypted)
<groupId>net.lightbody.bmp</groupId><artifactId>browsermob-rest</artifactId> | 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.1.0-beta-6, 2.1.0-beta-5, 2.1.0-beta-4, 2.1.0-beta-3, 2.1.0-beta-2, 2.1.0-beta-1 | Y(Traffic is encrypted)Only version 2.1.0-beta-5 and above can capture traffic | Y(Traffic is encrypted)Only version 2.1.0-beta-5 and above can capture traffic

I'm able to get network traffic by following the solution provided here:
https://github.com/serenity-bdd/serenity-core/issues/100
but the network traffic is encrypted as such:
`{"name":"Age","value":"373936"},{"name":"Alt-Svc","value":"hq=\":443\"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=\":443\"; ma=2592000; v=\"43,42,41,39,35\""}],"content":{"size":1599,"mimeType":"text/html","text":"\n\u000B\n\tTranslate\u0012�\u0012\bٌ�\t\u0012�\u0012\r�s�?\u0015j��?\u001D�99�%�<�*\u0007\n\u0000\u0015}E�?*\t\n\u0002la\u0015�\u0007��*\t\n\u0002de\u0015'\u001Am?*\n\n\u0003und\u0015Ս\u0000>*\t\n\u0002da\u0015\u0012�\u0013?*\t\n\u0002fi\u0015ڑ`

**Comment by wakaleo** [comment]
Maybe ask this on https://serenity-bdd.rocket.chat, as the browser mob plugin for Serenity is a community contribution.

**Comment by wakaleo** [comment]
Your best bet would be to dig into the code to see what is going on.

**Comment by jdoriyastpl** [comment]
Hi @AllysonYuShiong ,

I was trying to implement Browsermobproxy , facing issue
 **No implementation for net.thucydides.core.fixtureservices.FixtureProviderService was bound.
  while locating net.thucydides.core.fixtureservices.FixtureProviderService**

Code:
`   @Before
    public void setup() {
          // setup har for being available in the test method
        setupHar();
    }
    private BrowserMobProxy getProxyServer() {
//        ClasspathFixtureProviderService classpathFixtureProviderService = new ClasspathFixtureProviderService();
        FixtureProviderService classpathFixtureProviderService = Injectors.getInjector().getInstance(FixtureProviderService.class);
        List<FixtureService> fixtureServices = classpathFixtureProviderService.getFixtureServices();
        for(FixtureService fixtureService: fixtureServices){
            if(fixtureService instanceof BrowserMobFixtureService) {
                BrowserMobFixtureService service = (BrowserMobFixtureService) fixtureService;
                return service.getProxyServer();
            }
        }
        return null;
    }
    private void setupHar() {
        getProxyServer().newHar("test.com");

    }
`

Please help if you know the solution !

**Comment by vladyslavpetrov** [comment]
> Hi @AllysonYuShiong ,
> 
> I was trying to implement Browsermobproxy , facing issue
> **No implementation for net.thucydides.core.fixtureservices.FixtureProviderService was bound. while locating net.thucydides.core.fixtureservices.FixtureProviderService**
> 
> Code:
> ` @before
> public void setup() {
> // setup har for being available in the test method
> setupHar();
> }
> private BrowserMobProxy getProxyServer() {
> // ClasspathFixtureProviderService classpathFixtureProviderService = new ClasspathFixtureProviderService();
> FixtureProviderService classpathFixtureProviderService = Injectors.getInjector().getInstance(FixtureProviderService.class);
> List fixtureServices = classpathFixtureProviderService.getFixtureServices();
> for(FixtureService fixtureService: fixtureServices){
> if(fixtureService instanceof BrowserMobFixtureService) {
> BrowserMobFixtureService service = (BrowserMobFixtureService) fixtureService;
> return service.getProxyServer();
> }
> }
> return null;
> }
> private void setupHar() {
> getProxyServer().newHar("test.com");
> 
> ```
> }
> ```
> 
> `
> 
> Please help if you know the solution !

`FixtureProviderService classpathFixtureProviderService = WebDriverInjectors.getInjector().getInstance(FixtureProviderService.class);`
