### ISSUE TITLE
incorrect serenity report when using tags and multiple example tables in scenario outline

### ISSUE THREAD

**Issue by lnm2** [serenity-bdd/serenity-core#1219]
There is an empty serenity report when executing less than two scenario outlines using tags and multiple example tables in one scenario outline.

Feature file: 

@login
Scenario Outline: Login test with valid credentials 
       Given I navigate to the login page 
	When I am logged on with the username <username> and password <password> 
	Then I will be directed to the home page 
	And I log out 

@one
	Examples: 
		| username  | password   |
		| user1         | Password1 |
@two
	Examples: 
		| username  | password  |
		| User2        | Password2 |
@three
	Examples: 
		| username | password |
		| User3       | Password3|

Maven command: mvn clean verify -Dcucumber.options="--tags @login --tags @one,@two" 
executes the scenarios with data from example table one and two as expected and generates a populated report file that says 3 tests were passed but should only say 2 passed and 2 were executed.

Maven command: mvn clean verify -Dcucumber.options="--tags @login --tags @one" 

executes the scenario with data from example table one, but generates a report file that says 0 tests ran.

serenity core version 1.8.1
serenity cucumber version 1.6.5

**Comment by cliviu** [comment]
Please use the new cucumber style tags https://github.com/cucumber/cucumber/blob/master/tag-expressions/README.md

**Comment by lnm2** [comment]
It does not make a difference

**Comment by lnm2** [comment]
It works in the cucumber report, so I guess the problem is in serenity

**Comment by cliviu** [comment]
Can you please try with the latest serenity products and with the new cucumber tags ? It should work

**Comment by lnm2** [comment]
That looks to be working better now!
From the documentation, for the line: --tags @foo --tags @bar becomes --tags '@foo and bar'
Is there an @ missing in front of the bar? 

It does not work without the @ for me but works well with the @
Thanks again.

**Comment by bar** [comment]
@lnm2 I'm not sure what you mean but @ foo has probably nothing to do with this, as do I :)
