### ISSUE TITLE
Report generation hangs

### ISSUE THREAD

**Issue by AAnahit** [serenity-bdd/serenity-core#122]
Hi,

I have created simple Java project using Serenity with JBehave integration. I have defined modules/features and .story -es of the product and test scenarios and don't have any implementation yet and while running "mvn clean verify" on my local environment without making any changes report generation fails with different reasons about 40% of time while running it several times in a row.

I have captured at least two exceptions that appear most frequently:
![issue - test report generation - report generation failed error](https://cloud.githubusercontent.com/assets/13278484/9591524/f236dff2-5009-11e5-9308-a29c09e0c4d4.png)

![issue - test report generation - nullpointerexception](https://cloud.githubusercontent.com/assets/13278484/9591592/5ef32fce-500a-11e5-95a8-947518e59498.png)

I use the following versions for the Serenity and its plugins:
serenity-core - 1.1.3
serenity-maven-plugin - 1.1.5
serenity-jbehave - 1.1.0

Can you please have a look at this issue  ? I would really appreciate any support and feedback on this.

Thanks a lot in advance!

**Comment by wakaleo** [comment]
My Googling suggests this is a Windows issue (see http://stackoverflow.com/questions/12308878/file-overwrite-in-java-user-mapped-section-open-error). Next version will have an attempted work-around.

**Comment by AAnahit** [comment]
Thanks a lot for the quick feedback on this!

Is the fix available under the version 1.1.3 of the serenity core? I use this version as higher versions seem not support Java 7

**Comment by wakaleo** [comment]
No, it will be available in version 1.1.8. All versions should support Java
7 - what issues are you having?

On 1 September 2015 at 14:55, AAnahit <notifications@github.com> wrote:

> Thanks a lot for the quick feedback on this!
>
> Is the fix available under the version 1.1.3 of the serenity core? I use
> this version as higher versions seem not support Java 7
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/122#issuecomment-136586468>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by AAnahit** [comment]
Unsupported major-minor version 52 exception, I found out that is caused by the one of the dependencies that the latest version of the serenity-core has.

**Comment by wakaleo** [comment]
Do you know which dependency?

On 1 September 2015 at 15:03, AAnahit <notifications@github.com> wrote:

> Unsupported major-minor version 52 exception, I found out that is caused
> by the one of the dependencies that the latest version of the serenity-core
> has.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/122#issuecomment-136587533>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by AAnahit** [comment]
I don't remember which one exactly that was, but I have rechecked again by upgrading
serenity-core - 1.1.6
serenity-maven-plugin - 1.1.6

and there were no issues related to Java version so far.

Thank you!
