### ISSUE TITLE
Serenity with dialog of windows

### ISSUE THREAD

**Issue by Jun12121988** [serenity-bdd/serenity-core#1221]
Can serenity control windows dialog, such as alert, open dialog, save dialog, ... and take screenshot of them? 

I am searching about serenity. And my envirnment is below:
IE9
Window7

Thank first

**Comment by wakaleo** [comment]
Serenity uses Selenium, and Selenium can only take screenshots of dialogs if they are part of the HTMLpage, not JavaScript alerts.

**Comment by Jun12121988** [comment]
Thank A lot
