### ISSUE TITLE
Error javax/annotation/Priority on JDK9

### ISSUE THREAD

**Issue by krystianstarczewski** [serenity-bdd/serenity-core#1226]
Hi, 
i'm upgrading my service to JDK9 and noticed a problem when i run from mvn verify serenity tests with some annotation:

ERROR [2018-04-27 11:30:33,427] net.serenitybdd.core.Serenity: javax/annotation/Priority

java.lang.NoClassDefFoundError: javax/annotation/Priority
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority

Already added dependency to                 
                <groupId>javax.annotation</groupId>
                <artifactId>javax.annotation-api</artifactId>

Nothing more in logs, don't have those annotation in my code looks like it's used somewhere in serenity. Checked on serenity 1.8.12 and 1.9.12 is there version compliant with JDK9/10 ?

All tests runned from IntelliJ pass.

**Comment by wakaleo** [comment]
JDK 9 contains major breaking changes and is not currently supported.

**Comment by krystianstarczewski** [comment]
Problem was with maven-failsafe-plugin, upgrade version to 2.21.0 resolved this error.

**Comment by wakaleo** [comment]
Thanks for the update @krystianstarczewski
