### ISSUE TITLE
Control screenshots in HTML report of test result.

### ISSUE THREAD

**Issue by Jun12121988** [serenity-bdd/serenity-core#1229]
Is there a way to get file name of screenshot belongs to each step in HTML report by code? Can I replace the path of screenshot of step by another one after test was run?

**Comment by wakaleo** [comment]
You could parse the JSON test report for the test - they are all listed there. What problem are you trying to solve?

**Comment by Jun12121988** [comment]
First, thank you for the reply.

I use AutoIT and Java clipboard to take png image of dialogs which not a part of HTML page. Then I want to define these images for somewhere(ex. path screenshot of each step, ...) by code to display them into HTML test report.
I got the JSON test report file for the test, but name of file is difficult to guess. When create a testscript, can I take this file name at @after phase (Junit) to parse it to change something on it?

※My searching result about Senenity BDD also need to know a importance function that it can take and control dialogs which not a part of HTML page. In case Serenity BDD can not, it can work with other tools(such as AutoIT,...) together?
