### ISSUE TITLE
Running tests as JUNIT doesn't display "Examples" names.

### ISSUE THREAD

**Issue by Bratok17** [serenity-bdd/serenity-core#1231]
Hi,
I wanted to update our project's serenity version from 1.2.1-rc6 to the newer 1.9+. I discovered when running my tests as JUnit, the immediate output doesn't display the "Examples" names, instead if repeats the "Scenario outline" for each line of "Examples" table. I tried running the demo project for Screenplay pattern "TODOMVC" with the following serenity versions:
        <serenity.version>1.9.0-rc.3</serenity.version>
        <serenity.maven.version>1.9.0-rc.3</serenity.maven.version>
        <serenity.cucumber.version>1.6.13</serenity.cucumber.version>

And this is how the JUNIT looks in my Ecplise. 

![image](https://user-images.githubusercontent.com/38926055/39549955-36517c12-4e25-11e8-8d1e-cd0c92bb2f59.png)

Running the project as mvn clean verify generates serenity reports as expected, with "Examples" names.

**Comment by wakaleo** [comment]
This sounds like a Cucumber 2.x / Eclipse integration issue, rather than a Serenity one. Is there anything that might suggest it is related to Serenity?

**Comment by Bratok17** [comment]
It seems you are correct. I only assumed as the runner was with @RunWith(CucumberWithSerenity.class). Apologies for creating this in error.
