### ISSUE TITLE
Drived Provided Windows Application Driver

### ISSUE THREAD

**Issue by juancamiloau** [serenity-bdd/serenity-core#1232]
We have a Page Object Model implementation with a provided driver, this driver is Windows Application Driver, we enter HomePage.open() in a try statement to control a POST  (The following error occurred: Command not implemented: POST: /session/FB85138D-50EA-4ABF-BBF4-267B0C04AAE5/url), and works. 

We try to do the same thing using screenplay, and we can not control the POST error, we use actor.attempsTo(Open.url(any)), and put the code in a try statament, but does not works.

If we use only Open.url without actor.attempsTo, does works open the application, but when the actor.attempsTo a interaction like doing a click, we get another error The appium.platformName needs to be specified (either IOS or ANDROID).

As windows application driver is a appium based driver, we cannot set the appium capability platformName as Windows, only allows android or iOS.

Do you have some examples using a Windows Driver or do you think is possible allow as Windows Driver to the screenplay roadmap? Or how can we fix the errors?

Regards

@wakaleo  @ricardorlg @cliviu @vikramvi

**Comment by wakaleo** [comment]
As this is a question, rather than a defect, could you raise it on https://serenity-dojo.rocket.chat for more visibility?
