### ISSUE TITLE
Unable to connect Step definitions with feature files

### ISSUE THREAD

**Issue by UtsaChakraborty** [serenity-bdd/serenity-core#1239]
Hi ,

I am new to serenity Cucumber BDD framework.
All my Serenity tests are skipped while the project is built successfully. As per the logs , the step definitions are not found. PFB the runner class:

package runners;
import org.junit.runner.RunWith; 

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
		features= {"src/test/resources/Feature"}, //source folder path for Feature files
		glue = {"src/test/java/stepdefinitions"} //source folder path for Stepdefinition files
		)
public class TestRunner {
	}

P.S : I have marked skip as false in surefire plugin
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.21.0</version>
                <configuration>
                    <skip>false</skip>
                </configuration>
            </plugin>

**Comment by wakaleo** [comment]
The glue should be a package name, not a directory. I would also recommend using the stc/test/resources/features as your feature directory as this is the default convention for the Serenity reports

**Comment by UtsaChakraborty** [comment]
Now it is able to locate the step definitions... Thank you

**Comment by kushalpuri333** [comment]
Hi I am using both correctly i.e. src/test/resources/features and glue is package name but still its giving an error "undefined step definitions" although my test case is running fine.

**Comment by wakaleo** [comment]
If the code is running correctly then this is an IDE issue.
