### ISSUE TITLE
CustomListener.stepFailed() - StepEventBus.getEventBus().getCurrentStep() always returns "Optional.absent"

### ISSUE THREAD

**Issue by Ostryak** [serenity-bdd/serenity-core#124]
I have custom listener, where wants to perform some actions with failed steps.
But when I'm trying to get StepEventBus.getEventBus().getCurrentStep() I always get Optional.absent() in stepFailed method

I performed some investigations and found following:
1 -  Order of listeners is (StepEventBus.getEventBus().getAllListeners()):
   * net.thucydides.core.steps.BaseStepListener@d8bd53
   * CustomListener@aeb16b

2 -  when BaseStepListener.stepFinished executed, then
   ```java
        public void stepFinished() {
            updateSessionIdIfKnown();//step is returned by getCurrentStep
            takeEndOfStepScreenshotFor(SUCCESS);//step is returned by getCurrentStep
            currentStepDone(SUCCESS);//here step is not returned by getCurrentStep
    //        markCurrentStepAs(SUCCESS);
            pauseIfRequired();
        }
```

3 - currentStepDone contains following code:
```java
                TestStep finishedStep = currentStepStack.pop();
```

4 - getCurrentStep returns object from stack:
```java
    currentStepStack.peek()
```

So, as I understood the problem is following:
BaseStepListener cleans stack, and then getCurrentStep returns Optional.absent, because stack is empty.

**Comment by cliviu** [comment]
hi,  you can try (as a workaround) to manage(store/reset) the current step in your customListener in stepStarted() method. At that time the current step should already be set by the BaseStepListener

**Comment by YamStranger** [comment]
@Ostryak Hello!

It seems that advice of @cliviu helped you to solve your problem. 

Please close this issue if so. 

Thanks!

**Comment by YamStranger** [comment]
It seems that this issue already fixed, and can be closed.
