### ISSUE TITLE
Switch to `InheritableThreadLocal`

### ISSUE THREAD

**Issue by thokari** [serenity-bdd/serenity-core#1242]
I would like to write a test that does some concurrent activity.

For example:
```
someSteps.while_calling_endpoint_A_every_X_milliseconds_for_Y_seconds()
otherSteps.when_changing_some_data_using_endpoint_B()
someSteps.then_the_endpoint_A_will_not_have_shown_any_errors_during_that_time()
```

So assuming that in `someSteps` I would like to create a new Thread, then I will have the problem that the `ThreadLocal` variables (from other `shared` Steps) for that new thread is basically gone / `null`.

I propose to change every instance of `ThreadLocal` involved in Step decoration to `InheritableThreadLocal` in order to be able to create concurrent checking Threads from within `@Steps`, that can still access shared `@Steps`.

**Comment by wakaleo** [comment]
Would you like to submit a PR?

**Comment by wakaleo** [comment]
I think in the context you describe, the InheritableThreadLocal approach should work. Please feel free to test it out and provide a PR if it works.

**Comment by wakaleo** [comment]
This is potentially doable but causes problems with the SerenityParameterizedRunner, which runs separate tests in parallel in separate threads. Feel free to see if you can get it to work.
