### ISSUE TITLE
Report always shows last feature as run even when it's not

### ISSUE THREAD

**Issue by lewisob** [serenity-bdd/serenity-core#1245]
Difficult to explain this one.

Lets say I have 10 features, and I run some tests from some but not all of these features.
When I view the serenity report the index.html page is as expected, it shows the results of any scenarios run, and only the scenarios that were run. All good.
But, when I click on the Features tab so I can view the requirement_type_feature.html file, it lists all features as expected and the ones that were run are marked with a pass or fail but also the last feature (features are listed A-Z) is ALWAYS marked as run even when no scenarios from this feature were run.

Example.
Lets say I have a.feature, b.feature, c.feature, d.feature, e.feature and each feature has 2 scenarios.
I run feature b and c, 1 scenario in feature b has failed so 1/4 scenarios has failed in total.
The report shows that 50% of tests in feature b have passed and 100% have passed in feature c.
BUT, feature e in the report shows that 4 tests run and 1 failed. So it's like the last feature is treated as an overall summary?

**Comment by wakaleo** [comment]
Any chance of a sample project?

**Comment by lewisob** [comment]
Sure, is it possible to send privately?

**Comment by wakaleo** [comment]
Sure, just send it by email (see the address at https://johnfergusonsmart.com)

**Comment by lewisob** [comment]
Hi @wakaleo. Did you get a chance to have a look at the report I sent through?

**Comment by lewisob** [comment]
@wakaleo I noticed today that this issue doesn't occur on Windows, only Mac.
