### ISSUE TITLE
Test case status shows pass status for failure conditions

### ISSUE THREAD

**Issue by NageswarPattipati** [serenity-bdd/serenity-core#1246]
Hi Team,

I want to write a method for a scenario where the test case will fail if the given condition is not matched.
i.e I am applying the coupon code to my order and want to validate the cart total amount before applying and after applying the coupon code.
Here when the final price is not equal to the Subtotal+coupon code my test case should fail.

For this, I am using  assert(actualCartAmount.equals(totalValue)); 

But it's not working when there is a mismatch between the values my test case still pass.  so whenever the values are not matching my test case should fail and display the failure status in the serenity.

The possible way is print the amount in the console, but here the problem is until we see the console we will not come to know the actual status.

Please help me to overcome from this issue.

Thanks
Nageswar.

**Comment by wakaleo** [comment]
What assertion library are you using?

**Comment by NageswarPattipati** [comment]
Junit 4.12

Thanks
Nageswar

**Comment by NageswarPattipati** [comment]
Thanks for the needful help, we have added the AssertJ to our workspace and now the assert functionality is working as expected 

Regards,
Nageswar.

**Comment by NageswarPattipati** [comment]
Is there any possible way to Assert the images!

**Comment by wakaleo** [comment]
What are you trying to assert about which images?

**Comment by ilzul** [comment]
You can check this tool https://github.com/yandex-qatools/ashot. It seems to do exactly what you need

**Comment by NageswarPattipati** [comment]
Hi Jhon,

I have added an Item to Wishlist and the wishlist and the wishlist will not have the product name and the product will be there till the cookies expire, so I want to compare the product details page image with the wishlist product image.

Thanks
Nageswar.

**Comment by NageswarPattipati** [comment]
Hi John,

We have moved to serenity from the Selenium webdriver Page Object model, and we are unable to implement the multi-browser functionality i.e 2 different browsers execution.

Is there any possible way to implement this functionality! 

Please do the needful help on the same.

Thanks
Nageswar.

**Comment by wakaleo** [comment]
Hi @NageswarPattipati,

This appears to be a question that is unrelated to this issue, so would be better asked on https://serenity-bdd.rocket.chat. In answer to your question, you can run multiple browsers in a single test very easily using the Screenplay pattern.

**Comment by NageswarPattipati** [comment]
Thanks For the timely response and I apology for asking multiple questions on this issue.

Thanks
Nageswar
