### ISSUE TITLE
Appium > Need to automate two android app in a single script.

### ISSUE THREAD

**Issue by imamhasan-augmedix** [serenity-bdd/serenity-core#1249]
Appium > Need to automate two android app in a single script. Please note, The two apps are installed in two different android devices where android OS are also different.
How can i managed that two drivers in serenity?

**Comment by wakaleo** [comment]
You can manage two drivers quite easily using the Screenplay pattern. Multiple drivers in the same test are not supported in conventional Serenity however.

**Comment by imamhasan-augmedix** [comment]
Can i use two appium driver also at a time? 
Note: the two drivers will manage two separate devices with different app at a time.

**Comment by imamhasan-augmedix** [comment]
**Advance sorry if my question is not appropriate as i did not use screenplay pattern before.** 
In serenity.properties, i added appium capabilities in my current project. 
The capabilities will also be different for different appium drivers. So in screen play pattern, how can i differentiate the different capabilities of two appium driver? Does not it read from serenity.properties file in screenplay pattern?

**Comment by pascaH** [comment]
Any news on this? I'm also interested in having 2 or more driver instances in a single test. Currently I'm blocked at the same point with the serenity properties configuration. 
Thank you in advance.
