### ISSUE TITLE
null values not handled when generating reports

### ISSUE THREAD

**Issue by afoltin** [serenity-bdd/serenity-core#125]
serenity-report-resources, version 1.1.9:
default.ftl 
line 313 fails if status code is not provided

serenity-core, version 1.1.9
net.thucydides.core.reports.html.Formatter
line 83 fails if provided text is null

**Comment by verhagen** [comment]
@afoltin Can you close this issue ? Thx

**Comment by afoltin** [comment]
Sorry, didn't realise closing was up to me
