### ISSUE TITLE
Test execution started taking more time after upgrading to serenity-core 1.9.17

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#1252]
Hello,

I'm trying to upgrade serenity to the latest version, but there is some general issue with afterScenario and afterStory steps - they started taking much more time...

**serenity-core from 1.9.8 to 1.9.17**
**serenity-jbehave from 1.39.0 to 1.40.0**

`14:09:50.293 [pool-1-thread-1] DEBUG n.t.core.steps.StepInterceptor - STEP DONE: verifyLinkWithTextIsNotVisible

14:09:50.297 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - afterScenario : Menu navigation
14:13:46.533 [pool-1-thread-1] INFO  n.t.c.steps.ConsoleLoggingListener - 
TEST PASSED: Menu navigation

14:13:46.564 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - afterStory false

(AfterStories)
14:13:46.705 [main] DEBUG n.s.jbehave.SerenityReporter - before story AfterStories

14:13:46.709 [main] DEBUG n.s.jbehave.SerenityReporter - afterStory false
/usr/bin/stty: standard input: Inappropriate ioctl for device
14:17:01.447 [main] DEBUG n.thucydides.core.steps.StepEventBus - Registering custom listener net.serenitybdd.plugins.jira.JiraStepListener@44286963`

**Comment by wakaleo** [comment]
I don’t recall any changes that would affect performance in those releases - maybe take a look at the got log to see if anything l

**Comment by ilzul** [comment]
Well, I've tried different things... still cannot upgrade to the latest version, test execution started taking much more time  :( 
my suspicious is afterScenario method from SerenityReporter.
Which contains StepEventBus.getEventBus().testFinished();
testFinished(outcome) in the BaseStepListener has 2 lines:

getCurrentTestOutcome().addIssues(storywideIssues);
        // TODO: Disable when run from an IDE
getCurrentTestOutcome().addTags(storywideTags);

The first one works fast, the second takes a lot of time (

@wakaleo, could you please suggest how can I fix that ?

**Comment by ilzul** [comment]
Some more logs related to AfterStories
`(AfterStories)
12:10:13.880 [main] DEBUG n.s.jbehave.SerenityReporter - before story AfterStories

12:10:13.883 [main] DEBUG n.s.jbehave.SerenityReporter - afterStory false
12:10:13.889 [main] DEBUG n.t.core.reports.ReportService - Reporting formats: [JSON, HTML]
12:10:13.902 [main] DEBUG n.t.core.reports.ReportService - Found reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@4eb45fec(format = Optional[XML])
12:10:13.902 [main] DEBUG n.t.core.reports.ReportService - Found reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@211febf3(format = Optional[JSON])
12:10:13.902 [main] DEBUG n.t.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@211febf3
12:10:14.005 [main] DEBUG n.t.core.reports.ReportService - Found reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@2bebb74f(format = Optional[HTML])
12:10:14.005 [main] DEBUG n.t.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@2bebb74f
12:10:14.006 [main] DEBUG n.t.core.reports.ReportService - Reporting formats: [JSON, HTML]
12:10:14.024 [main] DEBUG n.t.core.reports.ReportService - Generating reports for 2 test outcomes using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@211febf3
12:10:14.025 [pool-4-thread-1] DEBUG n.t.core.reports.ReportService - Processing test outcome Test:01 - Create
12:10:14.026 [pool-4-thread-1] DEBUG n.t.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@211febf3: Generating report for test outcome: Test:01 - Create
12:10:14.026 [main] DEBUG n.t.c.r.j.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
12:10:14.026 [pool-4-thread-1] DEBUG n.t.c.r.json.JSONTestOutcomeReporter - Generating JSON report for 01 - Create to file C:\AT\qatest\target\site\serenity\11444d7718d6e182ad666cae872c7663260394f53b8d862488b86fb467c8192b.json (using temp file C:\AT\qatest\target\site\serenity\11444d7718d6e182ad666cae872c7663260394f53b8d862488b86fb467c8192b.json93be8d37-b0ea-4810-bf57-7aa7c85c84d7)
12:10:14.027 [pool-4-thread-2] DEBUG n.t.core.reports.ReportService - Processing test outcome Test:02 - update
12:10:14.027 [pool-4-thread-2] DEBUG n.t.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@211febf3: Generating report for test outcome: Test:02 - update
12:10:14.027 [pool-4-thread-2] DEBUG n.t.c.r.json.JSONTestOutcomeReporter - Generating JSON report for 02 - update to file C:\AT\qatest\target\site\serenity\917bfc052d91d6486074575af67a011f0f91bb0e6e1dcfa13ec24b32feea8fe0.json (using temp file C:\AT\qatest\target\site\serenity\917bfc052d91d6486074575af67a011f0f91bb0e6e1dcfa13ec24b32feea8fe0.json7961efcc-d3eb-4b2f-bbb7-20b85cadfa45)
12:10:14.072 [pool-4-thread-1] DEBUG n.t.core.reports.ReportService - Processing test outcome Test:01 - Create done
12:10:14.082 [pool-4-thread-2] DEBUG n.t.core.reports.ReportService - Processing test outcome Test:02 - update done
12:10:14.128 [main] DEBUG n.t.core.reports.ReportService - Shutting down executor service
12:10:14.129 [main] DEBUG n.t.core.reports.ReportService - Reports generated in: 105 ms
12:10:14.129 [main] DEBUG n.t.core.reports.ReportService - Generating reports for 2 test outcomes using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@2bebb74f
12:10:14.130 [main] DEBUG n.t.c.r.j.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
12:10:14.133 [pool-5-thread-1] DEBUG n.t.core.reports.ReportService - Processing test outcome Test:01 - Create
12:10:14.133 [pool-5-thread-1] DEBUG n.t.core.reports.ReportService - net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@2bebb74f: Generating report for test outcome: Test:01 - Create
12:10:14.133 [pool-5-thread-1] DEBUG n.t.c.r.h.HtmlAcceptanceTestReporter - GENERATE TEST OUTCOME REPORT FOR 01 - Create in 11444d7718d6e182ad666cae872c7663260394f53b8d862488b86fb467c8192b
12:10:14.142 [pool-5-thread-2] DEBUG n.t.core.reports.ReportService - Processing test outcome Test:02 - update
12:10:14.142 [pool-5-thread-2] DEBUG n.t.core.reports.ReportService - net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@2bebb74f: Generating report for test outcome: Test:02 - update
12:10:14.142 [pool-5-thread-2] DEBUG n.t.c.r.h.HtmlAcceptanceTestReporter - GENERATE TEST OUTCOME REPORT FOR 02 - update in 917bfc052d91d6486074575af67a011f0f91bb0e6e1dcfa13ec24b32feea8fe0
12:13:19.942 [pool-5-thread-2] DEBUG n.t.c.r.RequirementsTagProvider - Requirements found:[Requirement{name='Administration', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Application', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Configuration', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='FileStory', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Integration', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Library', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Messages', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Prerequisites', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Queries', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Reference data', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Rma', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Security', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Supervision', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Templates', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Test', type='story' parent = 'null', cardNumber='JIRA-41672'}, Requirement{name='Utilities', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Workflow', type='2.area' parent = 'null', cardNumber='null'}]
12:13:19.944 [pool-5-thread-1] DEBUG n.t.c.r.RequirementsTagProvider - Requirements found:[Requirement{name='Administration', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Application', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Configuration', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='FileStory', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Integration', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Library', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Messages', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Prerequisites', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Queries', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Reference data', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Rma', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Security', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Supervision', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Templates', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Test', type='story' parent = 'null', cardNumber='JIRA-41672'}, Requirement{name='Utilities', type='2.area' parent = 'null', cardNumber='null'}, Requirement{name='Workflow', type='2.area' parent = 'null', cardNumber='null'}]
12:13:19.986 [pool-5-thread-2] DEBUG n.t.c.r.BaseRequirementsService - Requirement found for test outcome 02 - update-[JIRA-41672]: Optional[Requirement{name='Test', type='story' parent = 'null', cardNumber='JIRA-41672'}]
12:13:19.987 [pool-5-thread-1] DEBUG n.t.c.r.BaseRequirementsService - Requirement found for test outcome 01 - Create-[JIRA-41672]: Optional[Requirement{name='Test', type='story' parent = 'null', cardNumber='JIRA-41672'}]
12:13:20.001 [pool-5-thread-1] DEBUG n.t.c.r.BaseRequirementsService - Requirement found for test outcome 01 - Create-[JIRA-41672]: Optional[Requirement{name='Test', type='story' parent = 'null', cardNumber='JIRA-41672'}]
12:13:20.002 [pool-5-thread-2] DEBUG n.t.c.r.BaseRequirementsService - Requirement found for test outcome 02 - update-[JIRA-41672]: Optional[Requirement{name='Test', type='story' parent = 'null', cardNumber='JIRA-41672'}]
12:13:20.094 [pool-5-thread-1] DEBUG n.t.c.r.h.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR Test:01 - Create in 11444d7718d6e182ad666cae872c7663260394f53b8d862488b86fb467c8192b.html in directory target\site\serenity  
12:13:20.094 [pool-5-thread-2] DEBUG n.t.c.r.h.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR Test:02 - update in 917bfc052d91d6486074575af67a011f0f91bb0e6e1dcfa13ec24b32feea8fe0.html in directory target\site\serenity  
12:13:20.098 [pool-5-thread-2] DEBUG n.t.c.r.h.HtmlAcceptanceTestReporter - Generating report in 917bfc052d91d6486074575af67a011f0f91bb0e6e1dcfa13ec24b32feea8fe0.html
12:13:20.098 [pool-5-thread-1] DEBUG n.t.c.r.h.HtmlAcceptanceTestReporter - Generating report in 11444d7718d6e182ad666cae872c7663260394f53b8d862488b86fb467c8192b.html
12:13:20.453 [pool-5-thread-1] DEBUG n.t.c.r.h.HtmlAcceptanceTestReporter - Generated report 11444d7718d6e182ad666cae872c7663260394f53b8d862488b86fb467c8192b.html in 355 ms
12:13:20.453 [pool-5-thread-1] DEBUG n.t.core.reports.ReportService - Processing test outcome Test:01 - Create done
12:13:20.453 [pool-5-thread-2] DEBUG n.t.c.r.h.HtmlAcceptanceTestReporter - Generated report 917bfc052d91d6486074575af67a011f0f91bb0e6e1dcfa13ec24b32feea8fe0.html in 355 ms
12:13:20.454 [pool-5-thread-2] DEBUG n.t.core.reports.ReportService - Processing test outcome Test:02 - update done
12:13:20.454 [main] DEBUG n.t.core.reports.ReportService - Shutting down executor service
12:13:20.454 [main] DEBUG n.t.core.reports.ReportService - Reports generated in: 186325 ms
12:13:20.973 [main] DEBUG n.thucydides.core.steps.StepEventBus - Registering custom listener net.serenitybdd.plugins.jira.JiraStepListener@55fdf7f9`

It seems like RequirementsTagProvider took 3 minutes, but in the past it was working much faster...

**Comment by wakaleo** [comment]
If you can isolate the version change that caused the change in behaviour, it would help. The RequirementsTagProvider code hasn't changed in a very long time.

**Comment by martinkus** [comment]
Hello I am also facing the same issue when updating from 1.9.7 to 1.9.19. I've tracked the issue down to FileSystemRequirementsTagProvider getRequirements method. The class itself did not have any changes recently, however the rate at which it loads requirements has slowed down significantly.

e.g.
when running on 1.9.7 loading a few requirements takes milliseconds

```
2018-05-24 15:45:09,878 [main] TRACE FileSystemRequirementsTagProvider:142 - Loading requirements from 
2018-05-24 15:45:09,898 [main] TRACE FileSystemRequirementsTagProvider:142 - Loading requirements from 
2018-05-24 15:45:09,902 [main] TRACE FileSystemRequirementsTagProvider:142 - Loading requirements from 
2018-05-24 15:45:09,918 [main] TRACE FileSystemRequirementsTagProvider:142 - Loading requirements from 
2018-05-24 15:45:09,932 [main] TRACE FileSystemRequirementsTagProvider:142 - Loading requirements from 
2018-05-24 15:45:09,939 [main] TRACE FileSystemRequirementsTagProvider:142 - Loading requirements from 
2018-05-24 15:45:09,943 [main] TRACE FileSystemRequirementsTagProvider:142 - Loading requirements from 
2018-05-24 15:45:09,946 [main] TRACE FileSystemRequirementsTagProvider:142 - Loading requirements from 
```

While running on 1.9.19 the very same loading now takes 8 seconds

```
2018-05-24 15:46:51,321 [main] TRACE FileSystemRequirementsTagProvider:140 - Loading requirements from 
2018-05-24 15:46:51,967 [main] TRACE FileSystemRequirementsTagProvider:140 - Loading requirements from 
2018-05-24 15:46:52,578 [main] TRACE FileSystemRequirementsTagProvider:140 - Loading requirements from 
2018-05-24 15:46:53,955 [main] TRACE FileSystemRequirementsTagProvider:140 - Loading requirements from 
2018-05-24 15:46:55,333 [main] TRACE FileSystemRequirementsTagProvider:140 - Loading requirements from 
2018-05-24 15:46:57,489 [main] TRACE FileSystemRequirementsTagProvider:140 - Loading requirements from 
2018-05-24 15:46:58,888 [main] TRACE FileSystemRequirementsTagProvider:140 - Loading requirements from 
2018-05-24 15:46:59,471 [main] TRACE FileSystemRequirementsTagProvider:140 - Loading requirements from 
```

(I have removed filepaths from logs)

I'll keep investigating but hopefully this would trigger an aha moment.

**Comment by ilzul** [comment]
Hi @wakaleo 
For me this issue started happening in serenity-core v.1.9.9.
Please let me know if you need any additional information
Thanks in advance

**Comment by wakaleo** [comment]
It’s very hard to test here; maybe checkout 1.9.9 locally and do a local build to try to figure out which commit made a difference

**Comment by martinkus** [comment]
Morning, @wakaleo @ilzul 
I've tracked down the issue to commit https://github.com/serenity-bdd/serenity-core/commit/84eac250f345461adcdbf7da192edeccb7cf02e9
Looks like the slowdown is caused by huge amount of calls to listDirectories method (in RootDirectory.java) which does a full walk through the project dir. 

``` java
    private static List<Path> listDirectories(Path path) {
        List<Path> files = new ArrayList<>();
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(path)) {
            for (Path entry : stream) {
                if (Files.isDirectory(entry)) {
                    files.add(entry);
                    files.addAll(listDirectories(entry));
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return files;
    }
```

If I set ThucydidesSystemProperty.SERENITY_REQUIREMENTS_DIR the call to to listDirectories is bypassed and performance is back to normal.

``` java
    private static List<File> getResourceDirectories(Path root, EnvironmentVariables environmentVariables) {
        if (ThucydidesSystemProperty.SERENITY_REQUIREMENTS_DIR.isDefinedIn(environmentVariables)) {
            return new ArrayList<>();
        } else {
            return listDirectories(root).stream()
                    .filter(path -> path.endsWith("src/test/resources"))
                    .map(Path::toFile)
                    .collect(Collectors.toList());
        }
    }
```

A workaround is to set your requirements directory manually in serenity.properties
serenity.requirements.dir = path/to/your/requirements

**Comment by ilzul** [comment]
Wow, @martinkus Thanks a lot for your investigation.
This issue has gone after setting the serenity.requirements.dir property.
