### ISSUE TITLE
serenity-scala integration using sbt-plugin

### ISSUE THREAD

**Issue by abhijeetardale** [serenity-bdd/serenity-core#1253]
Hi, 

I am working on sbt-scala plugin for serenity-sbt integration. I did initial draft of plugin and its working. I am able to generate the serenity reports with scala-serenity-cucumber project using sbt test/testOnly commands. 
Now I am trying to test it for features like Jira integration and It will be great if you give me some guideline/pointer for testing serenity framework and enhancing the plugin so that it will be useful others. 
I would like to the contribution for plugin development.

cheers,
Abhijeet

**Comment by abhijeetardale** [comment]
Hi,

As i said, I am working on Scala SBT project and developed draft version of SBT plugin. Also we are able to generate serenity reports using this plugin.
Please check the attached report for both Scala and java project using "serenity-demos/cucumber-webtests" projects which is replicated in Scala however we are facing few issues with reports we are as follows:
1. missing few tabs in reports like Releases, Capabilities and Features
2. Related tags  missing information for Capabilities

however while generating the its giving us the below message which says 0 requirements loaded :

[pool-5-thread-3] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Generating test results for 9 tests
[pool-5-thread-3] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - 0 requirements loaded after 100 ms
[pool-5-thread-3] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - 0 related requirements found after 100 ms
[pool-5-thread-3] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Generating test outcome reports: true

## Serenity Report with Java and Maven 

![serenity_report_with_java_maven](https://user-images.githubusercontent.com/26648207/40646004-ec177e5c-631f-11e8-96b5-6fdbe537f8cc.PNG)



## Serenity Report with Scala and SBT

![serenity_report_with_scala_sbt](https://user-images.githubusercontent.com/26648207/40646008-f02d2776-631f-11e8-85fc-6af1eca80e7f.PNG)


You might know about this error, it will be great help if you give us the some points to resolve this issues.

Regards,
Abhijeet

**Comment by wakaleo** [comment]
Hi Abhijeet,

This looks like great progress. The lack of Features and Capabilities is usually due to the requirements reporting not being set up. Is the source code in a publicly-available repo? I will take a look if I can see anything obvious.

**Comment by abhijeetardale** [comment]
Hi John,

thanks for reply, i have tried with different combinations of "serenity.test.requirements.basedir" but it doesn't help. 

Please check the  "sbt plugin" at https://github.com/abhijeetardale/serenity-sbt-plugin  and "scala project" used at https://github.com/abhijeetardale/serenityPOC. 
Step to run the project are as follows:
1. copy the plugin and publish it locally using 'sbt clean publishLocal' 
2. copy scala project and run the test using 'sbt clean test'

please let me know if you need further help, the generated report is as follows: 
![serenity_report_with_scala_sbt](https://user-images.githubusercontent.com/26648207/40874872-5af302ec-666d-11e8-9841-479a9ce4ac60.PNG)


Regards,
Abhijeet

**Comment by abhijeetardale** [comment]
any update/clue, how you tried it?

**Comment by wakaleo** [comment]
Just had a quick look at the code, but can't see anything obvious. I will need to drill deeper into the code. The problem is most likely the requirements are not being loaded correctly. Put a breakpoint in MultiSourceRequirementsService or RequirementsReports to see what requirements are being found.
