### ISSUE TITLE
aggregate not running

### ISSUE THREAD

**Issue by lnm2** [serenity-bdd/serenity-core#1256]
When testFailureIgnore is set to false in the  maven-surefire-plugin, the build is marked as failed if there are any failed tests, which is what I want, but the index.html for the serenity report is not generated.

**Comment by lnm2** [comment]
If it is set to true and there are failing tests, the build is marked as successful and there is an index,html.
But jenkins/gitlab runner would think that the build passed.

**Comment by lnm2** [comment]
I would like the build to be marked as failed if there are failing tests and the index.html to be generated.
If I use mvn serenity:aggregate, it does not reach this because if there are failures, maven does not execute any more goals/targets,

**Comment by wakaleo** [comment]
This all sounds like normal Maven behaviour. You can run serenity:check to force the build to fail based on the results of the previous tests.

**Comment by lnm2** [comment]
wow, that works. Thank you so much:)
