### ISSUE TITLE
find by iOS predicate is not working when using @iOSXCUITFindBy

### ISSUE THREAD

**Issue by andrecnogueira** [serenity-bdd/serenity-core#1258]
Hey guys,

I noticed we are sending wrong commands to Appium when one uses @ iOSXCUITFindBy. I tested the same annotation using pure Appium and it has worked just fine.

I have the following notation:

@ iOSXCUITFindBy(iOSNsPredicate = "type == 'XCUIElementTypeButton' AND label == 'I don\\'t have a favorite team'")
    private WebElementFacade noFavouriteButton;

When my code interacts with this element I see the following in Appium logs:

[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","noFavouriteButton","14621b4e-ec9f-4e76-a409-078e545afa6b"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/CA3A8787-19C1-4EC0-9F1E-6090A0B71C57/element] with body: {"using":"**id**","value":"**noFavouriteButton**"}

Notice we call Appium using id rather than predicate string and send the actual field name as value, noFavouriteButton, instead of "type == 'XCUIElementTypeButton' AND label == 'I don\'t have a favorite team'"

I managed to get it working on Serenity by getting the proxy driver and calling:

driver.findElement(MobileBy.iOSNsPredicateString("type == 'XCUIElementTypeButton' AND label == 'I don\\'t have a favorite team'")).click();

See the difference on Appium logs:

[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-ios predicate string","type == 'XCUIElementTypeButton' AND label == 'I don\\'t have a favorite team'","6da59343-cf19-4ab8-99a4-e5bd42c13197"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/79A808CF-56C5-4F17-9BD2-F074A8B654CE/element] with body: **{"using":"predicate string","value":"type == 'XCUIElementTypeButton' AND label == 'I don\\'t have a favorite team'"}**
[debug] [JSONWP Proxy] **Got response with status 200**: {"value":{"ELEMENT":"768E44E6-AB8C-4AFE-91C4-E9FB804088C2"},"sessionId":"79A808CF-56C5-4F17-9BD2-F074A8B654CE","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"768E44E6-AB8C-4AFE-91C4-E9FB804088C2"}
[HTTP] <-- POST /wd/hub/session/6da59343-cf19-4ab8-99a4-e5bd42c13197/element **200** 180 ms - 122

I am able to reproduce this issue in different Serenity versions. At the moment I am using serenity-core:1.9.19 with Appium server 1.7.2. I tried to update to newer Appium server, but nothing has changed.

Please, let me know if you need any other information. Would love to see this working in the next release :)

André

**Comment by Invictum** [comment]
Hi @andrecnogueira

Locating with field name as ID is used - this is default Serenity behaviour. It is the last chance strategy to resolve locators  for undefined elements.

I suppose you need to supply your own `CustomFindByAnnotationService` and define how to resolve Appium related annotations.

Check `CustomFindByAnnotationService` and `ClasspathCustomFindByAnnotationProviderService` javadoc for more details.

**Comment by andrecnogueira** [comment]
Hey @Invictum 
Is there any way to override this default serenity behaviour by using Appium @ iOSXCUITFindBy ? I don't think creating my own approach is the right action if we already have a solution provided by Appium.

**Comment by Invictum** [comment]
@andrecnogueira 
I do not see such ability in a code. You should tell Serenity how to work with Appium complex annotation.
This is natural way to fit Serenity facility in accordance to your project needs.

**Comment by andrecnogueira** [comment]
@Invictum , do you know how this implementation should look like? I've been trying to do so, but did not work at all...

**Comment by Invictum** [comment]
@andrecnogueira 

Implement `CustomFindByAnnotationService` with logic for `@iOSXCUITFindBy` resolving
```
public class IOSXCuteFindByAnnotationService implements CustomFindByAnnotationService {

    @Override
    public boolean isAnnotatedByCustomFindByAnnotation(Field field) {
        // Match on desired annotation
        return field.isAnnotationPresent(iOSXCUITFindBy.class);
    }

    @Override
    public By buildByFromCustomFindByAnnotation(Field field) {
        iOSXCUITFindBy annotation = field.getAnnotation(iOSXCUITFindBy.class);
        String locatorString = annotation.iOSNsPredicate();
        if (!locatorString.isEmpty()) {
            return MobileBy.iOSNsPredicateString(locatorString);
        }
        ...
        throw new IllegalArgumentException("Unable to locate field " + field);
    }
}
```

Register your implementation with service loader.
Let's assume `IOSXCuteFindByAnnotationService` class is located in `com.package` package, so full class name is `com.package.IOSXCuteFindByAnnotationService`.
Create a text file `resources/META-INF/services/net.serenitybdd.core.annotations.findby.di.CustomFindByAnnotationService` with following content `com.pack.IOSXCuteFindByAnnotationService`

For now Serenity knows how to extract and build `iOSNsPredicate` from `@ iOSXCUITFindBy`
If you are planning to use other locator types from `@iOSXCUITFindBy` add related logic to `buildByFromCustomFindByAnnotation` method.

**Comment by andrecnogueira** [comment]
@Invictum , many thanks! It worked like a charm. I am closing this issue.

**Comment by vikramvi** [comment]
@Invictum under https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/serenitybdd/core/annotations/findby/How.java, there is enum for `IOS_NS_PREDICATE_STRING`.
Please clarify in this case why do I need to use `CustomFindByAnnotationService` ?
cc: @andrecnogueira

**Comment by vikramvi** [comment]
@Invictum can you please clarify per above comment ?

**Comment by Invictum** [comment]
@vikramvi
You are right, in this particular case How approach is acceptable.

**Comment by vikramvi** [comment]
@Invictum I didn't understand your last comment 

> ...particular case How approach is acceptable.

Can you please clarify in detail ?
