### ISSUE TITLE
Question: Be able to run a task using screenplay based in data from a csv

### ISSUE THREAD

**Issue by LucasGrc** [serenity-bdd/serenity-core#1259]
Is there a way to run a certain task using the screenplay pattern base on the data from a csv file?
For example login then create as many users as there are in the csv file and then logout.

Thanks in advance for your help.

**Comment by wakaleo** [comment]
Sure, within a task you could load the data, then loop through each row and call another task to create the users.

**Comment by LucasGrc** [comment]
Thanks for your answer, I was able to to do it but not if is the best way, let me show you:

This is my test:

```
    public void should_be_able_to_create_as_many_daily_notes_as_needed() throws Throwable {
        givenThat(anna).wasAbleTo(OpenTheApplication.onTheLoginPage());
        and(anna).wasAbleTo(Login.intoTheApp());
        and(anna).wasAbleTo(CreateAPatient.withTheName("Jane", "Smith"));
        and(anna).wasAbleTo(CreateNote.forTheNewlyPatientCreated());

        withTestDataFrom("testdata/dailyNotes.csv").
                run(dailyNotesDataDriven).
                createDailyNote(anna);
    }
```

This is the model class that extends from `ScenarioSteps` that executes the task, as this was my first try I have only one column in the csv file to iterate to "ptEvaluationTimeMinutes"

```
public class DailyNotesDataDriven extends ScenarioSteps {
    private String ptEvaluationTimeMinutes;

    public void setPtEvaluationTimeMinutes(String ptEvaluationTimeMinutes) {
        this.ptEvaluationTimeMinutes = ptEvaluationTimeMinutes;
    }

    public DailyNotesDataDriven(Pages pages) {
        super(pages);
    }

    public void createDailyNote(Actor actor) {
        when(actor).attemptsTo(CreateDailyNote.fillForm(this.ptEvaluationTimeMinutes));
    }
```

Using `withTestDataFrom` I was able to get the csv file be loaded in the serenity report. 

I know this may be count as support but I just need an advice on how to do this in a better way and get the data from the csv file loaded in the serenity report, thanks in advance for your help and time.
