### ISSUE TITLE
Empty report after updating to latest library versions

### ISSUE THREAD

**Issue by dileepguntamadugu** [serenity-bdd/serenity-core#1260]
I'm getting empty reports without any content or screenshots. However I see that the screenshots and other required reporting source files are getting generated properly in the respective folders. Just that they are not appearing in the report.

Below are the versions of my jars and plugins

Serenity Version - 1.9.19
Serenity Maven Version - 1.9.19
Serenity Cucumber Version - 1.9.7
Maven Compiler Plugin - 3.3
Maven Failsafe and Surefire Plugins - 2.19.1

I suspect that there should be some dependency jars version conflicts. Any help is much appreciated.

In the attached screen shots two scenarios were actually executed and passed. But the actual report is blank.
![serenity_empty_reports](https://user-images.githubusercontent.com/36641816/40620979-4763764a-62de-11e8-9c7f-aad9daa5ffee.PNG)

**Comment by wakaleo** [comment]
This indicates that no tests are being run at all. Do you see any evidence of the test execution in the console output?

**Comment by dileepguntamadugu** [comment]
Uploaded a wrong screenshot @wakaleo , 

I'd identified the issue now. I was running the tests with fail safe plugin as a result when more than one test(s) were run with the tags and one of them fails the report was blank.

Now, I'm running my tests using sure-fire plugin and don't see this issue anymore.

Thank you.

**Comment by sumit-global** [comment]
@wakaleo @dileepguntamadugu 
Could you please share your pom.xml, I am facing same issue but unable to run serenity with surefire plugin.

Thanks in advance.
