### ISSUE TITLE
Error using tags in Junit with parametrized tests

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1261]
Using the SerenityParametrizedRunner class and tagging some tests, causes that serenity doesn't find any test to execute. This is happening in the last version.

**Comment by wakaleo** [comment]
@cliviu any ideas on this?

**Comment by ricardorlg** [comment]
The problem happens when serenity is trying to get the tags associated to the method name, It always gets an empty list, but if I run in debug I can get the tags, is really weird.

**Comment by wakaleo** [comment]
Hmmm, could be related to threads and thread-local variables maybe?

**Comment by ricardorlg** [comment]
I think so.

**Comment by cliviu** [comment]
Hmm, we have not changed anything regarding threading, but can you provide a short test project to help us reproduce the problem?

**Comment by ricardorlg** [comment]
sure, I will upload an example code.

**Comment by dileepguntamadugu** [comment]
This issue still exists would be great if a fix is available

**Comment by wakaleo** [comment]
PRs are welcome

**Comment by heikikiisler** [comment]
This seems to be working now with 2.0.42

**Comment by wakaleo** [comment]
Cool, I will close this issue then - Thanks for the update
