### ISSUE TITLE
Use new FirefoxOptions() over DesiredCapabilities.firefox()

### ISSUE THREAD

**Issue by RoiEXLab** [serenity-bdd/serenity-core#1266]
Running Serenity using firefox leads to the following spammed message in the logs:
```
INFORMATION: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Jun 01, 2018 12:03:29 PM org.openqa.selenium.remote.DesiredCapabilities firefox
```
There are some variations where exactly the "deprecated" method is being called, but the message should be pretty clear: No more usage anywhere, use the newer, better alternative.
While this isn't breaking anything this error message is pretty annoying and makes actual error messages harder to find.

Fixing this should be pretty easy (and the same problem should be present for all the other browsers as well see [the DesiredCapabilities class](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/DesiredCapabilities.java) for more information), because it's really just an alternative API that returns an object of more or less the same type. (Same superclass).

I'd appreciate if this could get fixed soon.

**Comment by wakaleo** [comment]
Happy to review a PR on this.

**Comment by mmanach** [comment]
Hi @RoiEXLab , 

What are your versions of : 

- Serenity core
- Firefox browser
- geckodriver
 
Thanks !

**Comment by RoiEXLab** [comment]
@mmanach
I don't know the exact versions, but they are pretty much outdated.
Firefox version should be 51, serenity version is like 10 releases behind.
Not sure about the driver version.
However I verified the issue still occurs using the latest version of serenity core.

**Comment by RoiEXLab** [comment]
Would be nice to see this reopened.
I don't know what exactly makes the Options objects different from desired capabilities, but the log statements are annoying nevertheless and should probably be interpreted as sort-of-deprecation

**Comment by wakaleo** [comment]
This refactoring severely broke the chrome integration, so it has been tabled for now.
