### ISSUE TITLE
FileToUpload on windows/unix

### ISSUE THREAD

**Issue by olmorigolo** [serenity-bdd/serenity-core#1267]
Hello,

we are using the FileToUpload class in our tests. We run our tests on windows and unix machines.
After updating from a very old version (1.1.x) to 1.9-rc.3 our tests using this component do not run any more on windows machines.

In fact, the implementation of the method to(...) does not work for relative paths on windows. (FileNotFoundException)

I had to fix the implementation using a already available method in FileToUpload. The stripLeadingSlashFrom method.

Before
 `
public void to(WebElement uploadFileField) {
        String filePath = this.uploadableFilePathTo(uploadFileField).forFile(this.resolvedFilename);
        this.checkThatFileExistsFor(filePath);
        uploadFileField.sendKeys(new CharSequence[]{this.osSpecificPathOf(filePath)});
    }
`

After 
` 
    public void to(WebElement uploadFileField) {
        String filePath = this.uploadableFilePathTo(uploadFileField).forFile(this.resolvedFilename);
        this.checkThatFileExistsFor(stripLeadingSlashFrom(filePath));
        uploadFileField.sendKeys(new CharSequence[]{this.osSpecificPathOf(stripLeadingSlashFrom(filePath))});
    }
`

This works for us, but I do not know if anybody else ever encountered the same problem and I am wondering how they fixed it.

Best regards,
Olmo

**Comment by wakaleo** [comment]
Thanks for investigating this. It cold be a bug - if you can submit this as a PR I will take a look.
