### ISSUE TITLE
Need to get sessionId when driver is as remotedriver i.e browserstack

### ISSUE THREAD

**Issue by jdoriyastpl** [serenity-bdd/serenity-core#1268]
Hi @wakaleo ,

Can you please tell , how can I get sessionId so that I can update the browerstatus session with pass or fail status.!!
Here is what capabilities set in property file:
`browserstack.os = Windows
browserstack.os_version = 10
browserstack.browser = Chrome
browserstack.browser_version = 66.0
browserstack.acceptSslCerts = true
browserstack.local=true
browserstack.build = Aramark_Sanity
browserstack.project = Aramark App
browserstack.debug=true
browserstack.resolution=1366x768`

**Comment by wakaleo** [comment]
The session ID is recorded in the test outcome. You can try `ThucydidesWebDriverSupport.getSessionId()`

**Comment by jdoriyastpl** [comment]
Thanks @wakaleo , It works

**Comment by ravibabu1408** [comment]
Hi @wakaleo, Currently i am running serenity bdd tests with browser stake, Session is created in browser stack but the input capabilities are not taking,  and running default os and browser. can you please help me on the?
webdriver {
  driver = "remote"
  remote.url = "https://hub.browserstack.com/wd/hub"
    browserstack.user="test"
    browserstack.key="test"

    capabilities {
    browserName = "Firefox"
    #
    # Any BrowserStack-specific options go in the 'bstack:options' section
    #
    "bstack:options" {
      os = "Windows"
      osVersion = "11"
      browserVersion = "107.0"
      local = false
      resolution = "1920x1200"
      #seleniumVersion = "4.6.0"
      video = true
      idleTimeout = 300
      buildName= "browserstack-build-1"
      #browserstack.networkLogs=true
      #browserstack.consoleLogs=errors
      debug= true
      consoleLogs=errors
    }

thanks

**Comment by ravibabu1408** [comment]
Thanks @wakaleo for your quick response, May i know why Chrome 118 was show instead Firefox 107 as per the input capabilities.?

**Comment by wakaleo** [comment]
I don't know; the browser config code is relatively simple, the best would be to debug and see what it is doing under the hood and sending to Browserstack.
