### ISSUE TITLE
Add support for the new notation for Cucumber tags

### ISSUE THREAD

**Issue by YiannisDermitzakis** [serenity-bdd/serenity-core#1269]
When using multiple cucumber tags, with the notation that Serenity supports, Cucumber complains:

```
WARNING: Found tags option '~@ignore'. Support for '~@tag' will be removed from the next release of Cucumber-JVM. Please use 'not @tag' instead.
WARNING: Found tags option '@env=dev,@env=demo'. Support for '@tag1,@tag2' will be removed from the next release of Cucumber-JVM. Please use '@tag or @tag2' instead
```

From a cursory look, `TagScanner` & `TestTag` classes should be updated. I could further look into it and provide a pull request if there is interest.

**Comment by wakaleo** [comment]
Thanks; this is a Cucumber warning related to the feature file contents; Serenity Cucumber no longer uses the TagScanner class and actually only supports the new tags notation.

**Comment by YiannisDermitzakis** [comment]
Thanks for the clarification John! I was confused as I only found tutorials using the old notation ([here](https://johnfergusonsmart.com/running-serenity-bdd-tests-with-tags/) and [here](https://github.com/serenity-bdd/serenity-documentation/blob/master/src/asciidoc/tags.adoc)).

I have been trying to get tags (both old and new notation) to work in my project but had no success so far. They are ignored. Perhaps you could point me to some up-to-date information?

Anyhow, this issue is clearly not needed.

**Comment by YiannisDermitzakis** [comment]
When I say that the tags are ignored, these are my settings for the old notation in the serenity.conf:
```
cucumber {
  options="--tags @smoke-test --tags ~@env=dev"
}
```
.. and the new:
```
cucumber {
  options="--tags '@smoke-test and (not @env=dev)'"
}
```

@smoke-test is a Feature level tag. With both notations, the scenarios tagged "@env=dev" are still run.
