### ISSUE TITLE
Dynamically defining download directory at runtime with SerenityParameterizedRunner.class

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1272]
I am currently using the SerenityParameterizedRunner for data-driven tests. In each test, I am looking for a way to:
1) create a folder (that is unique to each set of data)
2) download files into this folder. 
3) repeat Step 1 & 2 for each set of data

Setting the download directory is relatively straightfoward:
`        chromePrefs.put("download.default_directory", "path\to\file" + UUID.randomUUID().toString());
`

However as the webdriver initialization only happens once, all files for all tests are still downloaded to the same folder.

Trying to workaround this issue, I then tried using the @Managed annotation:
`@Managed(uniqueSession = true, clearCookies = ClearCookiesPolicy.BeforeEachTest)
`
`
public WebDriver hisBrowser;
`

However this doesn't seem to work. I'm guessing that somehow it is not initializing a new browser instance for each dataset...

Can I get some advice on dynamically specifying download folders at runtime, for SerenityParameterizedRunner please?

**Comment by Saieph** [comment]
Definitely having the same problem in my harness as well.
