### ISSUE TITLE
serenity.console.colors=true is not working

### ISSUE THREAD

**Issue by muli09** [serenity-bdd/serenity-core#1273]
I have used the below property in serinity.propeties file but i cant see the results in color.

serenity.console.colors=true

**Comment by wakaleo** [comment]
Does your OS support ANSI colours on the console? Prior to Windows 10, for example Windows Console does not support ANSI colours.

**Comment by wakaleo** [comment]
Closed for lack of activity

**Comment by eitzenbe** [comment]
its happening to me when I use tail -f on nohup.out for example, but that seems to be related to tail nto being able to deal with it properly

**Comment by eitzenbe** [comment]
@wakaleo I would like to reopen this as when I run the tests with nohup the file nohup.out contains ANSI color sequences that are shown when I do more on the file from MY messages but the TEST banner lines are all without colors. I can provide test logs....
[simplycolor.log](https://github.com/serenity-bdd/serenity-core/files/4389086/simplycolor.log)

Here you see the self created ANSI color sequences that work but not from serenity. When not redirecting the console shows colors

**Comment by wakaleo** [comment]
What OS are you running on?

**Comment by wakaleo** [comment]
(The class to look into is `net.thucydides.core.reports.AsciiColors`, if you want to poke around).

**Comment by eitzenbe** [comment]
its on centos7

**Comment by eitzenbe** [comment]
I will have some time late of April, might be checking around then
