### ISSUE TITLE
Serenity Core update cucumberVersion to 3.0.0 

### ISSUE THREAD

**Issue by s1apped** [serenity-bdd/serenity-core#1274]
Hi,

I just have a question. Are you planning to update Serentity Core dependencies to cucumber 3.0.0?

Thanks,
Matt

**Comment by wakaleo** [comment]
Yes. But it looks like a non-backward compatible change that may require refactoring your existing Cucumber tests.

**Comment by s1apped** [comment]
Cool. Do you have any eta?

**Comment by wakaleo** [comment]
Probably within the next month or so.

**Comment by mleegwt** [comment]
In 
https://github.com/serenity-bdd/serenity-cucumber/pull/160/commits the change to cucumber 3.0.x is reverted. What is the issue causing the revert?

**Comment by wakaleo** [comment]
Backward compatibility issues with existing Gherkin scenarios.

**Comment by mleegwt** [comment]
Thanks for responding. Any plans for progressing to 3.0 despite the backward compatibility issues?

**Comment by wakaleo** [comment]
At some point, but we need to analyse the regressions and discuss with the Cucumber teams, as it can have a big impact on existing test suites.

**Comment by wakaleo** [comment]
Serenity now works with Cucumber 2 and Cucumber 4.

**Comment by ju1ianj0rdan** [comment]
@wakaleo @mleegwt @s1apped If anyone is able to help answer this question for me it would be extremely helpful. Is there compatibility between my project  running Serenity 3.2.3, that depends on a Serenity RestAssured project which uses Serenity 2.0.70? I'm having issues when trying to access certain API calls, and I'm wondering if both projects need to be on the same version of serenity

**Comment by wakaleo** [comment]
> @wakaleo @mleegwt @s1apped If anyone is able to help answer this question for me it would be extremely helpful. Is there compatibility between my project running Serenity 3.2.3, that depends on a Serenity RestAssured project which uses Serenity 2.0.70? I'm having issues when trying to access certain API calls, and I'm wondering if both projects need to be on the same version of serenity

 The RestAssured integration is just a thin wrapper around RestAssured, so there shouldn't be any major issues upgrading.
