### ISSUE TITLE
NullPointerException at PageObject.openPageAtUr

### ISSUE THREAD

**Issue by hugoamo** [serenity-bdd/serenity-core#1277]
friends I ask for help with this error that appears at the time of running the tests, fails !!, the error tells me that openPageAtUrl is null, but I declared the parameter @DefaultUrl (value = "https://www.xxxxx.com" )

¿what could be happening?

java.lang.NullPointerException
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:860)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:761)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:749)
	at steps.AccesoLoginSteps.paginaInicio(AccesoLoginSteps.java:20)
	at definitions.LoginDefinitions.queelAccesorTieneCredencialesValidas(LoginDefinitions.java:18)
	at ✽.que el accesor tiene credenciales validas(src/test/resources/feature/login.feature:11)

**Comment by wakaleo** [comment]
Hard to say without knowing what version you are using

**Comment by hugoamo** [comment]
@wakaleo this is the structure of my grable

repositories {
    mavenLocal()
    jcenter()
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.1.1")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'

dependencies {
    testCompile 'net.serenity-bdd:serenity-core:1.1.1'
    testCompile 'net.serenity-bdd:serenity-junit:1.1.1'
    testCompile('junit:junit:4.12')
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('org.slf4j:slf4j-simple:1.7.7')

    compile 'net.serenity-bdd:serenity-core:1.9.9'
    compile 'net.serenity-bdd:serenity-junit:1.9.9'
    compile 'net.serenity-bdd:serenity-cucumber:1.9.5'
    compile 'net.serenity-bdd:serenity-screenplay:1.9.9'
    compile 'net.serenity-bdd:serenity-screenplay-webdriver:1.9.9'
}
gradle.startParameter.continueOnFailure = true

**Comment by wakaleo** [comment]
Update to the most recent version of Serenity and if the problem persists, step into the PageObject class to see what it is doing

**Comment by wakaleo** [comment]
Have you set up the driver using the @Managed annotation?

**Comment by hugoamo** [comment]
I have it declared

package steps;

import net.thucydides.core.annotations.Step;
import pages.HomePages;


public class AccesoLoginSteps {


    /*@Managed(uniqueSession = true)
    WebDriver driver;*/

    private HomePages paginaInicio = new HomePages ();

    @Step
    public void paginaInicio(){
        paginaInicio.open ();
    }

    @Step
    public boolean validarMenu() {
         boolean validarmenu;
         validarmenu=paginaInicio.validarMenu ();
         return validarmenu;
    }
    @Step
    public void ingresoRecuersos() {
        paginaInicio.ingresarCredenciales ( "Bancolombia" );
    }

}

**Comment by hugoamo** [comment]
@wakaleo hi, this is the [project](https://github.com/hugoamo/Suramasivos.git)

**Comment by wakaleo** [comment]
It should be declared in the same class as the tests

**Comment by hugoamo** [comment]
thank you very much
