### ISSUE TITLE
Using @Steps along with @Autowired

### ISSUE THREAD

**Issue by remould** [serenity-bdd/serenity-core#1279]
In my project, I am using the `SpringIntegrationSerenityRunner` to use Spring features. The steps declarations in the JUnit test classes are annotated with both `@Steps` and `@Autowired` (from Spring). The reason I am autowiring the steps classes is that, my steps classes depend on other services which needs to be auto wired by the spring container.

The tests execute fine, but the aggregated report does not show the steps. Since the instantiation of the steps classes are done by Spring in my case, the Serenity framework does not seem to be tracking the steps, as they are already instantiated.

Following is a sample test :

```
@RunWith(SpringIntegrationSerenityRunner.class)
@SpringBootTest(classes = AppConfig.class)
public class CreateAService {

    @Steps
    @Autowired
    private ServiceManagementAPISteps serviceManagementAPISteps;

    @Test
    public void shouldCreateAServiceSuccessfullyWithValidParameters() {
        serviceManagementAPISteps.createService("input1", "input2");
    }
}
```

Any suggestions will be appreciated. Thanks.

**Comment by wakaleo** [comment]
You shouldn't need the SpringIntegrationSerenityRunner, just the serenity-spring dependency. Not sure if it recognises @SpringBootTest though.

**Comment by remould** [comment]
It doesn't work without the `SpringIntegrationSerenityRunner`. This runner recognizes `@SpringBootTest` . I think the problem is in the way the test outcomes are generated. The steps are not being read by Serenity.

I'm using Serenity version 1.9.22 .

**Comment by olyv** [comment]
@remould, I have similar issue and I assume this happens because serenity and spring are creating components in different contexts -- spring and guice. As a result, spring doesn't know about @Steps. In my case methods annotated as Steps are not able to embed screenshot in report or write a message to report
