### ISSUE TITLE
Inconsistent reporting of Rest Assured tests

### ISSUE THREAD

**Issue by varun** [serenity-bdd/serenity-core#128]
HI.

When executing junit-webtests got the following error

ERROR:

**SEVERE: Error executing FreeMarker template**
**FreeMarker template error:**
**The following has evaluated to null or missing:**
**==> restQuery.statusCode  [in template "freemarker/default.ftl" at line 313, column 51]**

```
rest().relaxedHTTPSValidation()
      .get("https://api.github.com/repos/varun/.vim")
      .then().statusCode(200)
      .and().body("id", equalTo(7994328));
```

**Build is marked as success**

However StatusCode and the response of the request is not captured by reports.

![screen shot 2015-09-08 at 10 00 07](https://cloud.githubusercontent.com/assets/22036/9730781/c0e38d76-5610-11e5-8291-36792b878ed4.png)

**When I execute the following (Which is provided by the Junit-webtests project)**

```
rest().given()
      .contentType("application/json")
      .content(jsonPet)
      .post("http://petstore.swagger.io/v2/pet");
```

everything seems to be fine in reports and the console output ( no errors ) 

![screen shot 2015-09-08 at 10 03 58](https://cloud.githubusercontent.com/assets/22036/9730819/f67624a8-5610-11e5-8bfd-2801ec24a8b1.png)

Rest assured reports are inconsistent when I have used any HTTP (with any method GET, POST ) endpoint other than the provided one (http://petstore.swagger.io/v2/) in examples

I am I missing something here?

As mentioned above I have used **Junit-webtests** example project from serenity-demos 

Thank you.

**Comment by bassmake** [comment]
Hi,
are there any news on this issue?

**Comment by YamStranger** [comment]
@bassmake, @varun thanks for reporting this issue. We working on it.

**Comment by dsmt** [comment]
@YamStranger, great!
It also would be nice to support other types of requests such as delete, patch and so on

**Comment by YamStranger** [comment]
@dsmt please create different issue for your request. Thanks

**Comment by bassmake** [comment]
Hello,
we discovered what is the problem for our situation. In `net.serenitybdd.rest.SerenityRest` there is
```
    private static boolean shouldRecordResponseBodyFor(Response result) {
        return result.getContentType().endsWith("/json") || result.getContentType().endsWith("/xml") || result.getContentType().endsWith("/text");
    }
```

and if the content type is `application/json;charset=utf-8` it will not match the condition.
Should I create separate ticket for that or it is related?

**Comment by YamStranger** [comment]
@bassmake don't worry, I will test this solution and it will be included to repo as soon as possible. Thanks for your investigation!

**Comment by YamStranger** [comment]
>@YamStranger, great!
It would also be nice to support other types of requests such as delete, patch and so on

@dsmt thanks for your request about others types of requst. If you want track progress of this enhancement you can create new issue, because this issue will be closed when @varun problem will be solved.

**Comment by savita20** [comment]
@wakaleo Hello John,
Please find below is my code snippet:
`package com.restapi.test.resources.steps;

import cucumber.api.java.Before;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.When;
import io.restassured.RestAssured;
import net.serenitybdd.rest.Ensure;
import org.apache.http.HttpStatus;
import static net.serenitybdd.rest.SerenityRest.lastResponse;
import static net.serenitybdd.rest.SerenityRest.when;
import static org.hamcrest.CoreMatchers.equalTo;

public class VerifyCountryCodeSteps {

    @Before
    public void set_the_base_uri() {
        RestAssured.baseURI="http://services.groupkt.com/";
    }
    @Given("^I set up the base URI$")
    public void i_set_up_the_base_URI() {
        when().get("state/get/IND/all").then().statusCode(200);
    }


    /**
     * @param countryCode
     * Here we are trying to pass path param which we will get from scenario outline
     */
    @When("^I pass this given country code (.*)")
    public void i_pass_this_given_country_code(String countryCode) {
        when().get("state/get/{country_cod}/all", countryCode).then().statusCode(HttpStatus.SC_OK);
        lastResponse().prettyPrint();
        Ensure.that("Verify the message for total records", response -> response.body("RestResponse.messages".trim(), equalTo("[Total [36] records found.]".trim())));
    }
}
`
1. The above is my code. I am trying to verify the message. However it shows me following error:
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Ensure that Verify the message for total records
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 1 expectation failed.JSON path RestResponse.messages doesn't match.Expected: [Total [36] records found.]  Actual: [Total [36] records found.]
where there is not difference between actual and expected still it shows me error.

2. And another this I am not sure how can I able to verify message without [] this braces. 
If I want to verify just "Total [36] records found." message. 

3. Can I able to save this response into any string variable?
