### ISSUE TITLE
Mobile emulator execution shows zoomed screenshot in serenity report

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1281]
I have configured mobile emulator in my application .Execution is successful but in serenity report under section of **overall Test result** column name **screenshot** displays zoomed screenshot .

How to show a normal screenshot in report?

**Comment by wakaleo** [comment]
I don’t think this is supported by the JavaScript library we use for the Screenshot carousel  at the moment (I think it requires all the images to be of a determined size. Feel free to play round with the screenshot page to see if you can find a way though

**Comment by JeffGaly** [comment]
sure.I will try to implement that .
