### ISSUE TITLE
Application related errors in serenity report

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1282]
I wish to add application specific error message in serenity report so that we can consolidate the list of errors under tags.

Can i override serenity report class and make a custom errors to be added in my report.

**Comment by wakaleo** [comment]
Currently:
 - You can create domain-specific errors as described in http://thucydides.info/docs/articles/semantic-exceptions.html;  
 - You can customise the appearance of tags as described here: https://github.com/serenity-bdd/serenity-core/commit/0e7cf03dee3ba7f

**Comment by JeffGaly** [comment]
@wakaleo thanks for your prompt response.My application is stable with Gherkin language with step libraries ,methods .Now how it will impact if i migrate to screenplay pattern .Is there any other way to override the serenity report for application error.

**Comment by wakaleo** [comment]
You don't need to use Screenplay to apply these techniques.

**Comment by JeffGaly** [comment]
any sample project which may help me in implementing these techniques will be grateful.

**Comment by JeffGaly** [comment]
@wakaleo any sample project to implement these technique?

**Comment by wakaleo** [comment]
Have a look at https://github.com/serenity-bdd/screenplay-pattern-todomvc/commit/4af945f653ada5bde2ff8519797626a137c97b3c. Create a custom assertion and set the `serenity.tag.failures` property to true in your serenity configuration file.
