### ISSUE TITLE
Issue in SpringDependecyInjector in serenity-spring module

### ISSUE THREAD

**Issue by remould** [serenity-bdd/serenity-core#1283]
What is the intention of having `DependencyInjector`s? Is it to inject dependencies in test classes or step classes?

The `SpringDependecyInjector` in the serenity-spring module looks like it is designed to autowire deps in test classes, but it never gets called. However, it gets called with a `Step` class instead of a test class, after setting up step libraries.

**Comment by wakaleo** [comment]
The SpringDependecyInjector is automatically loaded when you include serenity-spring in your dependencies, and injects Spring dependencies into @Step-annotated objects (it has no control over the tests).
