### ISSUE TITLE
Getting Error "No implementation for net.thucydides.core.fixtureservices.FixtureProviderService was bound.".

### ISSUE THREAD

**Issue by jdoriyastpl** [serenity-bdd/serenity-core#1285]
Hi @wakaleo ,

Can you please tell me , What's wrong here?
Using inside my SteDef class
> `@Before
    public void setup() {
          // setup har for being available in the test method
        setupHar();
    }
    private BrowserMobProxy getProxyServer() {
//        ClasspathFixtureProviderService classpathFixtureProviderService = new ClasspathFixtureProviderService();
        FixtureProviderService classpathFixtureProviderService = Injectors.getInjector().getInstance(FixtureProviderService.class);
        List<FixtureService> fixtureServices = classpathFixtureProviderService.getFixtureServices();
        for(FixtureService fixtureService: fixtureServices){
            if(fixtureService instanceof BrowserMobFixtureService) {
                BrowserMobFixtureService service = (BrowserMobFixtureService) fixtureService;
                return service.getProxyServer();
            }
        }
        return null;
    }
    private void setupHar() {
        getProxyServer().newHar("test.com");

    }
`

**Comment by jdoriyastpl** [comment]
Here is Build.gradle content:
`defaultTasks 'clean','test','aggregate'

repositories {
    mavenLocal()
    jcenter()
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.9.25")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'
apply from: "$rootDir/gradle/libraries.gradle"


sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile libs.slf4jApi,
            libs.logback
    compile 'net.serenity-bdd:serenity-browsermob-plugin:1.9.25'

    testCompile libs.test.serenity.core,
            libs.test.serenity.screenplay,
            libs.test.serenity.screenplayWebdriver,
            libs.test.serenity.cucumber,
            libs.test.junit,
            libs.test.assertj
}

test {
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

gradle.startParameter.continueOnFailure = true

test.finalizedBy(aggregate)`

**Comment by wakaleo** [comment]
Have you tried including the serenity-browsermob-plugin in your dependencies?

**Comment by jvsanten** [comment]
Was running into the same issue. Changing
`FixtureProviderService classpathFixtureProviderService = Injectors.getInjector().getInstance(FixtureProviderService.class);`
to
`FixtureProviderService classpathFixtureProviderService = Injectors.getInjector().getInstance(ClasspathFixtureProviderService.class);`
fixed it for me. At least to the point where I can get the fixtureProviderService again.
