### ISSUE TITLE
Target found with located() but not with locatedBy()

### ISSUE THREAD

**Issue by straurob** [serenity-bdd/serenity-core#1286]
Using serenity-core 1.9.22.

The webpage I'd like to automate contains this:
```
<div>
  <span class="add>Add new entry</span>
</div>
```

To locate the element I use this statement:
`Target.the("'add new entry'").locatedBy("span.add");`

The result is that the element is **not found**.

If I use this statement instead the element **can be located**:
`Target.the("'add new entry'").located(By.cssSelector"span.add");`

Is this some kind of bug or is my first statement wrong?

**Comment by wakaleo** [comment]
The selector text is both valid XPath and CSS, so Serenoty defaults to using XPath. It is very hard to determine if an expression is valid CSS for various reasons, so we can’t use CSS as a default. So your work-around is the only option in this case.

**Comment by wakaleo** [comment]
You can also use a prefix, e.g. Target.the("'add new entry'").locatedBy("css:span.add")
