### ISSUE TITLE
Issue in requirements generation when using JUnit

### ISSUE THREAD

**Issue by remould** [serenity-bdd/serenity-core#1287]
When using JUnit, the aggregated report does not show the requirements, features, stories tabs.

I have the following property defined in serenity.properties as follows :
serenity.requirement.types=components,features,stories

Following is the report I got :
![screenshot](https://user-images.githubusercontent.com/30017128/42016464-3fbdd37e-7ac9-11e8-9163-f294bb0eb445.PNG)

The tabs for components,features,stories are not shown in the highlighted area. Also the requirement tab does not show the features and stories.

**Comment by wakaleo** [comment]
Have you followed the instructions given here?
http://thucydides.info/docs/serenity-staging/#_modelling_requirements_in_junit

**Comment by remould** [comment]
This is the output I m getting from the 'aggregate' goal of the serenity maven plugin:

[INFO] --- serenity-maven-plugin:1.9.22:aggregate (generate-serenity-report) @ api-tests ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/D:/m2/com/google/inject/guice/4.1.0/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] current_project.base.dir: D:\work\publisher\test-suites\api-tests
[INFO] Generating test results for 1 tests
[INFO] 0 requirements loaded after 53 ms
[INFO] 0 related requirements found after 53 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 92 ms
[INFO] Configured report threads: 40
[INFO] Test results for 1 tests generated in 1153 ms

**Comment by remould** [comment]
Attached a sample project.

[api-tests.zip](https://github.com/serenity-bdd/serenity-core/files/2145460/api-tests.zip)

**Comment by cliviu** [comment]
Hi @remould . One of the problems is that serenity.properties was not in the root directory of your project. If you move it in to the root of the project the requirements will be correctly generated. It may have been some problem in your pom.xml also.   

If you want to have a clean fresh start with the serenity project I suggest that you use the existing serenity maven template projects. 
Simply run **mvn archetype:generate -Dfilter=serenity** and choose your desired template. Then replace the serenity version inside the pom.xml   with the latest version. 

By the way, Java 10 is not yet supported by  Serenity.

**Comment by remould** [comment]
Thanks. It works after moving the file to the project root directory. So does it mean that the serenity.properties file is read only by the serenity-maven-plugin ?

**Comment by cliviu** [comment]
the serenity.properties file is expected by the serenity-maven plugin to be in the project root directory

**Comment by cliviu** [comment]
Please close the issue if your questions are answered. Thanks !

**Comment by remould** [comment]
Thanks. Got all the info I needed.
