### ISSUE TITLE
Recursive or cyclic reference checking for projects with a huge amount of step classes

### ISSUE THREAD

**Issue by martinkus** [serenity-bdd/serenity-core#1288]
Morning,
I've been using serenity for a while now (and quite enjoying it), however I ran into a small issue.

Environment:
- We use serenity option step.creation.strategy = legacy
- We have 100+ step classes that all reference each other.
- serenity-core version is 1.9.19

When running any scenario I get RecursiveOrCyclicStepLibraryReferenceException that is thrown from StepAnnotations.java class ensureThatThisFieldIsNotCyclicOrRecursive method.

Method in question:

```
private void ensureThatThisFieldIsNotCyclicOrRecursive(StepsAnnotatedField stepsAnnotatedField) {
        StackTraceElement[] stackTrace = new Exception().getStackTrace();
        long levelsOfNesting = Stream.of(stackTrace).filter( element -> element.getMethodName().equals("instantiateAnyUnitiaializedSteps"))
                                     .count();

        if (levelsOfNesting > MAX_ALLOWED_STEP_LIBRARY_NESTING) {
            String message = String.format(
                    "A recursive or cyclic reference was detected for the @Steps-annotated field %s in class %s. " +
                    "You may need to use @Steps(shared=true) to ensure that the same step library instance is used everywhere.",
                    stepsAnnotatedField.getFieldName(), stepsAnnotatedField.getFieldClass().getName());
            throw new RecursiveOrCyclicStepLibraryReferenceException(message);
        }
    }
```
It checks whether the level of nesting is more than 16 levels deep and throws an exception. Problem is that with a huge number of step classes the level of nesting goes even deeper. I'm attaching a sample project that reproduces this behavior. [serenity-cucumber-starter-master.zip](https://github.com/serenity-bdd/serenity-core/files/2145044/serenity-cucumber-starter-master.zip)

My questions would be:
- Was the number 16 chosen on purpose? Setting it to something like 10000 would still catch recursion but would allow deeper nesting.
- Does it make sense to check for cyclic references when using the legacy step creation strategy (since they are all singleton anyways)? We could only check if using the new strategy.

Anyhow please let me know what you think and I'll make an appropriate pull request.

**Comment by wakaleo** [comment]
16 is arbitrary, but 10000 might take a while to fail; you could propose a PR to make this a system parameter with a sensible (possibly larger than 16) default.
