### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by rajapcs** [serenity-bdd/serenity-core#1293]
I have an customized cucumber project(Developed from Cucumber JUnit) with Gosu script. I want to integrate Serenity with it as I need a good reporting.

Can you suggest any method of doing it.

Thanks in Advance.

**Comment by wakaleo** [comment]
I have no familiarity with Gosu.

Since this is a question not a defect, could you please close the issue and raise it in https://serenity-bdd.rocket.chat, which is the best forum for questions?

**Comment by wakaleo** [comment]
Closing as this is a question rather than a defect.
