### ISSUE TITLE
java.lang.NullPointerException: No BaseStepListener has been registered

### ISSUE THREAD

**Issue by kutzi** [serenity-bdd/serenity-core#1295]
Upgraded to serenity-core/serenity-cucumber 1.9.27/1.9.8 and got this already twice:
(previous versions 1.9.17/1.9.7)

```(Id: 22) [main] ERROR SerenityMain - Exception in Cucumber runtime
java.lang.NullPointerException: No BaseStepListener has been registered
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:900)
	at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:133)
	at net.thucydides.core.steps.StepEventBus.updateCurrentStepTitle(StepEventBus.java:578)
	at cucumber.runtime.formatter.SerenityReporter.handleTestStepStarted(SerenityReporter.java:306)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$3(SerenityReporter.java:119)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.api.TestStep.run(TestStep.java:79)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.Runtime.runFeature(Runtime.java:119)
	at cucumber.runtime.Runtime.run(Runtime.java:104)
	at cucumber.runtime.Runtime$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at SerenityMain.run(SerenityMain.groovy:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at SerenityMain.main(SerenityMain.groovy:26)```

**Comment by kutzi** [comment]
Will downgrade and check if the error really disappears

**Comment by wakaleo** [comment]
Could you check with 1.9.28 and 1.9.10 to see if the error disappears? 1.9.28 is built with cucumber 3.0.0. Failing that, I will roll back the 3.0.0 upgrade.

**Comment by cliviu** [comment]
hi @kutzi , please provide also a small project to reproduce the issue. How are you running the tests  ?

**Comment by kutzi** [comment]
@cliviu sorry, but that would be very much down on my priority list to provide a test project. So don't expect there anythig soon

**Comment by kutzi** [comment]
```    private static byte run(String[] argv, ClassLoader classLoader) throws IOException {
        RuntimeOptions runtimeOptions = new RuntimeOptions(new ArrayList<String>(asList(argv)))

        ResourceLoader resourceLoader = new MultiLoader(classLoader)
        Configuration systemConfiguration = Injectors.getInjector().getInstance(Configuration.class)
        Runtime runtime = CucumberWithSerenity
                .createSerenityEnabledRuntime(resourceLoader, classLoader, runtimeOptions, systemConfiguration)
        runtime.run()
        return runtime.exitStatus()
    }
```
That's how we start Serenity.
If you have any specific question, please let me know.

To create a compehensive, small project to reproduce the issue - I currently lack the time for that. Sorry

**Comment by wakaleo** [comment]
@kutzi is there a reason you are not running the tests through Maven or Gradle?

**Comment by cliviu** [comment]
@kutzi your way of starting Serenity will not work anymore with the new version. I will take a look to see if I can find an alternative

**Comment by mrcjbf** [comment]
did anyone figure out this error yet? I am still running into it.  I have tried everything in this thread and every link I can find online and I can't make any progress.  in the class StepEventBus.class, this method, the baseStepListener is always null: 

 public void updateOverallResults() {
        this.baseStepListener.updateOverallResults();
    }

java.lang.NullPointerException
	at net.thucydides.core.steps.StepEventBus.updateOverallResults(StepEventBus.java:686)
	at net.serenitybdd.screenplay.EventBusInterface.updateOverallResult(EventBusInterface.java:29)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:115)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:86)
	at net.serenitybdd.screenplay.Actor.has(Actor.java:73)

**Comment by wakaleo** [comment]
Are you running the tests with the Serenity runner?

**Comment by mrcjbf** [comment]
I am using a test runner file like this:  

package com.frontlineinsurance.automation.examples.discovery;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import cucumber.api.testng.AbstractTestNGCucumberTests;
import cucumber.api.testng.CucumberFeatureWrapper;
import cucumber.api.testng.TestNGCucumberRunner;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import net.serenitybdd.cucumber.CucumberWithSerenityRuntime;
import org.junit.runner.RunWith;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        plugin = {"pretty",
                "html:target/cucumber-reports/cucumber-pretty",
                "json:target/cucumber-reports/cucumber-pretty/cucumber.json" ,
                "junit:target/cucumber-reports/cucumber-pretty/cucumber.xml"},
        features = "src/test/resources/features/gpa/new_quote/bind_policy", tags = { "@chris" },
        glue = { "com.automation.examples.discovery.steps" }
)

public class Gpa_test_runner extends AbstractTestNGCucumberTests {

}

**Comment by mrcjbf** [comment]
and when I just run that runner file from inside the IDE the tests work.  I am trying to use this xml to run the runner file:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Selenium Grid - AMP">
    <test name="Smoke Tests">
        <classes>
            <class name="com.automation.examples.discovery.Gpa_test_runner" />
        </classes>
    </test>
</suite>

**Comment by mrcjbf** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Selenium Grid - AMP">
    <test name="Smoke Tests">
        <classes>
            <class name="com.automation.examples.discovery.Gpa_test_runner" />
        </classes>
    </test>
</suite>
`

**Comment by mrcjbf** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Selenium Grid - AMP">
    <test name="Smoke Tests">
        <classes>
            <class name="com.automation.examples.discovery.Gpa_test_runner" />
        </classes>
    </test>
</suite>

**Comment by mrcjbf** [comment]
I can't upload an xml snippet

**Comment by wakaleo** [comment]
Are you trying to run the tests with TestNG?

**Comment by mrcjbf** [comment]
yes.  I'm trying to set them up to run nightly through jenkins, and I am getting some guidance from another dev at my job, and he said all I need to do is figure out how to run the features by running that testng xml file

**Comment by mrcjbf** [comment]
but this dev knows zero about serenity and cucumber so he wasn't able to help me

**Comment by wakaleo** [comment]
Serenity doesn’t support TestNG

**Comment by mrcjbf** [comment]
no way really? no wonder I haven't been able to figure it out.  do you know if there is a way to run the features in a similar way, from an xml file through jenkins, using junit?

**Comment by wakaleo** [comment]
Just don’t extend the TestNG base class and run with the JUnit runner insteas

**Comment by mrcjbf** [comment]
thank you very much.  I got so into trying to fix errors I didn't take a second to step back and see if there was a broader problem

**Comment by kutzi** [comment]
Back to the original issue: @cliviu did you already manage to find a new way how I could run it?

**Comment by cliviu** [comment]
@kutzi currently we have switched back to Cucumber 2.x.x

**Comment by kutzi** [comment]
That means that it should work again?

**Comment by kutzi** [comment]
I upgraded to 1.9.30/1.9.12 and immediately encountered the issue again

**Comment by wakaleo** [comment]
Can you provide a sample project? We are not seeing this problem locally.

**Comment by kutzi** [comment]
Sorry, but I probably won't find the time to provide a sample project sometime soon

**Comment by kutzi** [comment]
What I don't get from the reading code: is the baseStepListener optional or not?
That seems to hint that it's optional
```
/**
     * A reference to the base step listener, if registered.
     */
    private BaseStepListener baseStepListener;
```
but in the codepath from the stacktrace it's not handled as this, i.e. getBaseStepListener() is called without checking isBaseStepListenerRegistered() first

**Comment by kutzi** [comment]
I found out that this always, consistently happens for the same feature file. I'll share the content of the file - stripped from all potential confidential content - in case it helps:

```
Feature:
    Make sure that the xyz rewrite rules still work.
    Description: a
    b
    c
    d

  Scenario Outline: Test if the rewrite anchor points are still present on a Ticket Page
    Given the customer opens the <TicketPage>
    Then validate that in the bodyElement the marker attribute mainBody is present

# TODO: adapt and re-enable these tests:
#    Then ensure that the stickyPricebarDiv contains the sticky-pricebar class attribute
#    Then ensure that the countDownDiv contains the coundown class attribute


    Examples:
    |TicketPage|
    |games.APage|
    |games.BPage|
    |games.CPage|
    |games.DPage|
```

**Comment by wakaleo** [comment]
If baseStepListener is null, your test hasn't set up Serenity correctly. If you are starting Serenity using custom logic as mentioned above, you may run into problems if the internal Serenity or Cucumber APIs change. However if this is a case, this isn't a Serenity defect but rather a usage error. We could help with this as part of one of the professional support packages (https://johnfergusonsmart.com/serenity-bdd-mentoring/) if you need further help.

**Comment by cliviu** [comment]
@kutzi, the problem is that after **"Feature:"** you need to start with the feature description. The problem is that you start with the feature description on the next line.

**Comment by kutzi** [comment]
Thanks @cliviu, that did the trick!
Note that this did work before (in 1.9.17), but as you pointed out, this syntax was never allowed, so I wouldn't call it a regression.

**Comment by erdelyizsolt** [comment]
I don`t know if it is late, but try to write your feature description right after Feature: keyword...not with an Enter below...yes it is odd, but I countered with the same issue, and that was the solution...

**Comment by wakaleo** [comment]
That's the Gherkin syntax
