### ISSUE TITLE
how serenity works to get RelatedTags,%passed and Test count details in aggregate report 

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1296]
I want to check how serenity works to call the **Relatedtag** names and **test count** of the tags under TestCount Tab in aggegrate report .Though i find in report classes i could see only the tag name but i couldn't find the test count .Any suggestions will be grateful.

**Comment by JeffGaly** [comment]
Hi John can you help in sharing the testcount class details .

**Comment by JeffGaly** [comment]
@wakaleo any help on which java class it calls to get the test count details under the tag column in index.html file ?

**Comment by wakaleo** [comment]
Have a look at the HtmlAggregateStoryReporter class.

**Comment by JeffGaly** [comment]
yes I already started to gaze  that class for index report details .I Will explore that.

**Comment by JeffGaly** [comment]
@wakaleo i found the methods which returns the total test count of the **Related tags** of type :"**Errors**" but i couldn't find the individual count of the error tags .

eg :In index.html report if **Related tags** has a Tag called "**Errors**" under Error i get five different exceptions so i wish to retrieve the individual count of the each exceptions .

any suggestions will be helpful .

**Comment by JeffGaly** [comment]
Hi John,
any suggestions will be grateful
