### ISSUE TITLE
Can we get Test case time without using reports?

### ISSUE THREAD

**Issue by Kavetipreetamkumar** [serenity-bdd/serenity-core#1301]
Hello,

I am working on grafana so I want to display time on metric, I am thinking is there any way that I can able take time without using reports, if yes what I have to do, if no how I have to use reports for influx db, like is there any resource id etc....

wanted to know Can we get Test case time without using reports.
is there any call back method to call after execution?

**Comment by wakaleo** [comment]
You might be able to use the following in an @After annotated method:
````
StepEventBus.getEventBus().getBaseStepListener().latestTestOutcome().get().getDurationInSeconds()
```

**Comment by Kavetipreetamkumar** [comment]
Just to confirm,method added in  @after annotation will be called after test case execution? 
if yes, In that method, can I get an object which will have the details of the executed test case? like test cases status ?

**Comment by wakaleo** [comment]
The latestTestOutcome() should give you all the test details

**Comment by Kavetipreetamkumar** [comment]
Adding to above conversation, I have multiple steps in on test case how I can get time for each step

**Comment by wakaleo** [comment]
Closed for lack of activity (presumed answered).
