### ISSUE TITLE
Cucumber tests missing in serenity report when one test fails

### ISSUE THREAD

**Issue by dianacarmen** [serenity-bdd/serenity-core#1305]
Hello,

When some cucumber tests fail, all tests are missing in the serenity report. Here is a link with a sample project:
https://drive.google.com/file/d/1c7N4m9jmnLHKAe89xvics5eX4Wzp4Rko/view?usp=sharing

There are some tests wo Cucumber, and they are displayed in the report.
In this project, you can correct the failing test and then all the tests will be displayed.
I have verified all I could find, from the posts and template projects about cucumber setup...

Please help me solve this.

Thank you,
Diana

**Comment by dianacarmen** [comment]
[serenity-cucumber-reports.zip](https://github.com/serenity-bdd/serenity-core/files/2196796/serenity-cucumber-reports.zip)
I have also attached the project here.

**Comment by cliviu** [comment]
Hi, can you please try to run only the cucumber features ?  It may be a problem when mixing Junit/Cucumber tests

**Comment by dianacarmen** [comment]
Hi,

Yes, I tried that. It’s the same result.
Then the reports are completely empty (wo the junit tests).

Thanks,
Diana

**Comment by dianacarmen** [comment]
Hi,

Yes, I tried that and the result is the same.
The report is empty, wo the junit tests.

Thanks

**Comment by cliviu** [comment]
I have tried to remove the jUnit test (Persona_Interacts_With_GooglePage.java) and the report was just fine, one failed test(because of the wrong css selector) and one successful test. I'm not sure where  the problem is,

**Comment by dianacarmen** [comment]
Weird ... I deleted the junit tests and this is the output:
[serenity-cucumber-reports-target.zip](https://github.com/serenity-bdd/serenity-core/files/2200869/serenity-cucumber-reports-target.zip)

I deleted the existing serenity folder and ran the project using gradlew test aggregate.

**Comment by dianacarmen** [comment]
Could this be linked to some environment issue?Any ideas what should I check?

**Comment by cliviu** [comment]
hi @dianacarmen . The problem is the "tags = {"~@newItemXTMCatTool"}" from the @CucumberOptions of the FeatureRunnerTest. Remove that option and you will see the reports.

**Comment by dianacarmen** [comment]
So now we're one step forward: only the green test is displayed in the report, but at least it's not empty anymore.
I've tried also changing these:
serenity.test.root = com.serenity.cucumber.features 
serenity.outputDirectory = target.site.serenity
serenity.sourcesDirectory = target.site.serenity

But I got the same result.

[log.txt](https://github.com/serenity-bdd/serenity-core/files/2206208/log.txt)

**Comment by cliviu** [comment]
so you mean that the failed test is not displayed in the report  ?

**Comment by dianacarmen** [comment]
Yes, exactly

**Comment by cliviu** [comment]
Strange, I will compare your log file with mine to check for differences

**Comment by cliviu** [comment]
The problem is that in both of your feature files you have the same name for the Feature and for the Scenario Outline. If you choose  different names for the Scenario Outline you will see both results in your test report. I hope that this answers your question.

**Comment by cliviu** [comment]
Can you please close the issue if it answers your question ?

**Comment by dianacarmen** [comment]
Hi Liviu,
Sorry I had little time to check this. I think it works this time, please give me 2 more days to confirm.
Thank you

**Comment by dianacarmen** [comment]
Hi Liviu,
Your suggestion solved my reports, I close this issue.
Multumesc :-)

**Comment by cliviu** [comment]
Ok, thanks ! 
Cu placere :-)
