### ISSUE TITLE
Properties in serenity.driver.capabilities passed incorrectly 

### ISSUE THREAD

**Issue by tempuser14** [serenity-bdd/serenity-core#1306]
We set the driver capabilities for our tests like this:
`mvn clean verify -Prc -Dcontext=chrome -Dinjected.tags="browser:chrome" -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.url="http://zalenium.domain/wd/hub" -Dserenity.driver.capabilities="build:project-rc;name:chromeTest"`

1. The problem is that after updating the version from 1.9.17 to 1.9.27 properties from `serenity.driver.capabilities` (e.g `build` or `name`) get the value `false`. With `1.9.17` it works correctly.
2. Is there a way to set dynamically during test execution driver capabilities in a managed `@Managed WebDriver`?

**Comment by wakaleo** [comment]
Can you identify the version that this error first happened?

**Comment by tempuser14** [comment]
It broke with version 1.9.27 (last working version is 1.9.26).

**Comment by tempuser14** [comment]
Closing this because this was fixed in the next commit after 1.9.27 (any version afterwards should work again).
