### ISSUE TITLE
Serenity not generating full reports with Cucumber

### ISSUE THREAD

**Issue by alexriordan** [serenity-bdd/serenity-core#1307]
Serenity version: 1.9.28
Serenity cucumber version: 1.9.10
Test class:
`@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features = "src/test/resources/features")
public class PrepExpressTestSuite {
}`

The test case executes. But Serenity provides this warning, and then I don't anything generated in the report: `[pool-1-thread-1] WARN cucumber.runtime.SerenityBackend - It looks like you are running a feature using @RunWith(Cucumber.class) instead of @RunWith(CucumberWithSerenity.class). Are you sure this is what you meant to do?`

Can someone explain why? I am not running RunWith(Cucumber.class), so why would that error message be generated?

**Comment by alexriordan** [comment]
hi @cliviu serenity 1.9.30, for some reason, rolls back the cucumber version to 2.4 (instead of 3.0.2), so this causes compilaiton errors for me.

**Comment by cliviu** [comment]
yes, the latest version rolls back the cucumber version to 2.4. But this should work fine with  serenity cucumber 1.9.12. Which compile errors do you have  ?

**Comment by alexriordan** [comment]
@cliviu i was leveraging the cucumber features for 3.0.2 - cucumber expressions and data table transformers. these are not included in cucumber 2.4.

**Comment by cliviu** [comment]
hmm, we have currently rolled back to cucumber 2.4 because of breaking changes of the cucumber3.0.2. 
Do you have an empty report?

**Comment by alexriordan** [comment]
@cliviu yes I can show a report. the report itself gets generated, but no steps/screenshots/etc any of the good reporting features apply.
[report.zip](https://github.com/serenity-bdd/serenity-core/files/2199416/report.zip)

**Comment by cliviu** [comment]
I'm not sure if it works, but try to add (plugin="cucumber.runtime.formatter.SerenityReporter")  to the @CucumberOptions(plugin="cucumber.runtime.formatter.SerenityReporter",features="...")

**Comment by cliviu** [comment]
?

**Comment by dianacarmen** [comment]
This has also happened to me and it seemed to be a dependency conflict. This is how I solved it:
I made sure I only have serenity-core dependencies, no cucumber-dependencies. 
This is how  my pom.xml looks like:
  <properties>
    <serenity.version>1.9.20</serenity.version>
    <serenitycucumber.version>1.9.8</serenitycucumber.version>
    <junit.version>4.12</junit.version>
    <selenium.version>3.12.0</selenium.version>
  </properties>

    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-cucumber</artifactId>
      <version>${serenitycucumber.version}</version>
      <exclusions>
        <exclusion>
          <artifactId>cucumber-core</artifactId>
          <groupId>io.cucumber</groupId>
        </exclusion>
      </exclusions>
    </dependency>

I hope this helps.

**Comment by alexriordan** [comment]
@cliviu Your suggestion seems to have resolved the non-generation of reports. Could you link me to the reason why cucumber-3.0.2 needed to be rolled back for serenity so I can see what other breaking changes the integration caused?

**Comment by Hendrione** [comment]
can you check the feature file?? make sure to reformat it before to run. Because when you add the feature name with more than 1 spaces it will give errors like that.
Feature:  feature a (this will error)

**Comment by wakaleo** [comment]
Closed for lack of activity
