### ISSUE TITLE
Serenity Rest Assured Always Getting -1 when Measuring Response Time

### ISSUE THREAD

**Issue by Hendrione** [serenity-bdd/serenity-core#1309]
On rest assured version 2.8.0 or higher, it support us to measure response time by using method **time()** or **timeIn()** (please check: https://github.com/rest-assured/rest-assured/wiki/ReleaseNotes28). When I use given() method in **net.serenitybdd.rest.SerenityRest.given** or **net.serenitybdd.rest.RestRequests.given**, it always giving the response time -1. But when I use the given() method provided by rest assured (i**o.restassured.RestAssured.given**), it gives me correct response time.

Here is my code:
```
long time = net.serenitybdd.rest.RestRequests.given()
.log().all().queryParam("page", 0)
.queryParam("size", 100)
.get("https://myproject.com/api/master/projects").timeIn(TimeUnit.MILLISECONDS);

long time2 = io.restassured.RestAssured.given()
.log().all().queryParam("page", 0)
.queryParam("size", 100)
.get("https:/myproject.com/api/master/projects").timeIn(TimeUnit.MILLISECONDS);

System.out.println("Using serenity given:"+time);
System.out.println("Using rest assured given:"+time2);
```

Here is my response:
```
Using serenity given:-1
Using rest assured given:985
```

I am getting struggle because without using **given()** on serenity library, the serenity report doesn't give the api report.

**Comment by Hendrione** [comment]
I already check the code. It is error because in **ResponseDecorated** class it is not override **getTime()** and **getTimeIn()** methods. Because in rest assured they using **groovyresponse** but in Serenity it use variable **core** inside **ResponseDecorated** class. Shall I do pull request for this?

**Comment by Hendrione** [comment]
Why this issue is getting closed?

**Comment by wakaleo** [comment]
It closed automatically as it is fixed in https://github.com/serenity-bdd/serenity-core/commit/26cf362d901f5ca74582c004aaae0511a9b13ae7. It will be available in the next release.
