### ISSUE TITLE
narrative.md and root overview.md is not displayed in the report. Serenity with Cucumber

### ISSUE THREAD

**Issue by centu81** [serenity-bdd/serenity-core#1312]
Pre:
Versions:
        <serenity.version>1.9.30</serenity.version>
        <serenity.maven.version>1.9.30</serenity.maven.version>
        <serenity.cucumber.version>1.9.12</serenity.cucumber.version>

Default feature structure: src\resources\features\
src\resources\features\overview.md

Actions:
- Run tests
- aggregate

Results:
narrative.txt works with themes and capabilities, but narrative.md not.
overview.md is not displayed in requirements at all.

**Comment by wakaleo** [comment]
This should be fixed in the next release (1.9.32)

**Comment by Bmaopp** [comment]
Hi,
I think https://github.com/serenity-bdd/serenity-core/commit/8ba37605be3b2e6ccec1d26dbb808eb2fef5414c causes me to see an add for nivo-slider in my report. Can I turn the inclusion of .md files off somehow?

**Comment by wakaleo** [comment]
No. But this change is unrelated to the nivo-slider component - what behaviour are you seeing?

**Comment by Bmaopp** [comment]
I have set serenity.requirement.types=epic,feature,story. The content of target/site/serenity/nivo-slider/3.2/README.md is now displayed as a story.

**Comment by wakaleo** [comment]
OK, that could be related. Could you raise a separate issue linked to this one?
