### ISSUE TITLE
Serenity.recordReportData().andContents() - Spaces not displayed

### ISSUE THREAD

**Issue by centu81** [serenity-bdd/serenity-core#1313]
Spaces are not displayed properly:

Code preparing string:
```
               String FORMAT = "|%-20s|%-20s|" + System.lineSeparator();
                StringBuilder str = new StringBuilder();
                str.append(String.format(FORMAT,"URL", "Token"));
```

Serenity report:
![image](https://user-images.githubusercontent.com/16413434/42933102-38102d76-8b44-11e8-8484-7219f8631ea4.png)

**Comment by wakaleo** [comment]
Please feel free to have a look at the code and propose a PR.
