### ISSUE TITLE
unsupported driver exception sporadically in local or jenkins execution

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1317]
Still no solution found for this sporadic driver exception though we give the latest version of selenium jar.

Error:
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver

**Comment by wakaleo** [comment]
Serenity is just reporting an exception thrown by your custom driver; this doesn’t look like a serenity issue as such.

**Comment by wakaleo** [comment]
Closed for lack of activity
