### ISSUE TITLE
All my scenarios are being ignored

### ISSUE THREAD

**Issue by alexriordan** [serenity-bdd/serenity-core#1318]
Using serenity 1.9.28 + serenity-cucumber 1.9.10

When executing from a feature file, all my scenarios are being marked as "ignore" by Serenity. I can put a breakpoint within the step definitions and step through all my code, but nothing happens - no browser opens, nothing.

Only the last test in my feature file executes, but it is still being marked as ignored by Serenity. Furthermore, it seems like my glue code is not being loaded either.

I'm at a complete loss as to what to do right now. I am not using the dryRun = true option, either. Everything was working yesterday.

**Comment by alexriordan** [comment]
Just resolved this. By placing an "@ignore" tag on ONE of my feature files (not all of them), this disabled ALL of them. Not sure if this is a cucumber or serenity issue.

**Comment by wakaleo** [comment]
Could you provide a sample project with this behaviour?

**Comment by wakaleo** [comment]
Closed for lack of activity
