### ISSUE TITLE
Retries in Gradle does not work

### ISSUE THREAD

**Issue by HNygard** [serenity-bdd/serenity-core#132]
I'm having problems using retries for Serenity tests when using Gradle. The first try opens the browser and then fails (as expected - I'm trying to get the retries working). The second try stops on assertion in the Gradle Junit plugin. I have tracked down the issue to [JUnitTestEventAdapter.java line 55/56](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/groovy/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapter.java#L56). It seems like the code have a defense against running the same test twice.

How is the retry logic suppose to work? Where is there an example of usage?

I'm running this on Windows in Firefox.

Notice the following to lines in the log:

    12:16:43.663 [Test worker] WARN  n.s.junit.runners.SerenityRunner - searching_for_dogs_should_find_the_wikipedia_entry failed, making attempt 2. Max retries: 3

And:

    12:17:03.628 [Test worker] DEBUG n.s.j.r.RetryFilteringRunNotifier - Test failed: hnytest.SearchingOnGoogleStory: Unexpected start event for searching_for_dogs_should_find_the_wikipedia_entry(hnytest.SearchingOnGoogleStory)
    java.lang.AssertionError: Unexpected start event for searching_for_dogs_should_find_the_wikipedia_entry(hnytest.SearchingOnGoogleStory)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestEventAdapter.testStarted(JUnitTestEventAdapter.java:55) ~[na:na]

Here is the log when trying:

	12:16:01.433 [Screenshot Processor] INFO  n.t.c.s.SingleThreadScreenshotProcessor - Processing screenshot: C:\Users\hny\AppData\Local\Temp\screenshot6713885676143358147
    12:16:05.840 [Test worker] INFO  net.serenitybdd.core.Serenity - STEP FAILED: net.thucydides.core.pages.WrongPageError: This is not the page you're looking for: I was looking for a page compatible with class hnytest.GoogleHomePage but I was at the URL https://www.google.no/?gfe_rd=cr&ei=PM0DVtSuHISA8QecqKXoAw&gws_rd=ssl
    12:16:05.840 [Test worker] INFO  n.t.core.steps.StepInterceptor - STEP FAILED: open_home_page - This is not the page you're looking for: I was looking for a page compatible with class hnytest.GoogleHomePage but I was at the URL https://www.google.no/?gfe_rd=cr&ei=PM0DVtSuHISA8QecqKXoAw&gws_rd=ssl
    12:16:05.842 [Screenshot Processor] INFO  n.t.c.s.SingleThreadScreenshotProcessor - Processing screenshot completed
    net.thucydides.core.pages.WrongPageError: This is not the page you're looking for: I was looking for a page compatible with class hnytest.GoogleHomePage but I was at the URL https://www.google.no/?gfe_rd=cr&ei=PM0DVtSuHISA8QecqKXoAw&gws_rd=ssl
    12:16:07.681 [Test worker] DEBUG n.s.j.r.RetryFilteringRunNotifier - Test failed: searching_for_dogs_should_find_the_wikipedia_entry(hnytest.SearchingOnGoogleStory): This is not the page you're looking for: I was looking for a page compatible with class hnytest.GoogleHomePage but I was at the URL https://www.google.no/?gfe_rd=cr&ei=PM0DVtSuHISA8QecqKXoAw&gws_rd=ssl
    net.thucydides.core.pages.WrongPageError: This is not the page you're looking for: I was looking for a page compatible with class hnytest.GoogleHomePage but I was at the URL https://www.google.no/?gfe_rd=cr&ei=PM0DVtSuHISA8QecqKXoAw&gws_rd=ssl
    	at hnytest.GoogleSearchSteps.open_home_page(GoogleSearchSteps.java:22) ~[test/:na]
    	at hnytest.SearchingOnGoogleStory.searching_for_dogs_should_find_the_wikipedia_entry(SearchingOnGoogleStory.java:33) ~[test/:na]
    12:16:07.688 [Test worker] DEBUG n.s.j.r.RetryFilteringRunNotifier - Test finished: searching_for_dogs_should_find_the_wikipedia_entry(hnytest.SearchingOnGoogleStory)
    12:16:07.782 [Test worker] INFO  net.serenitybdd.core.Serenity - 
               __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
      _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
     (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
      _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
     (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
              \_\                                                            

    TEST FAILED: Searching for dogs should find the wikipedia entry
    --------------------------------------------------------------------------
    12:16:07.786 [Test worker] INFO  net.serenitybdd.core.Serenity - RELATED ISSUES: 
    12:16:07.786 [Test worker] INFO  net.serenitybdd.core.Serenity - 
      _____ _    ___ _     _   _ ____  _____ 
     |  ___/ \  |_ _| |   | | | |  _ \| ____|
     | |_ / _ \  | || |   | | | | |_) |  _|  
     |  _/ ___ \ | || |___| |_| |  _ <| |___ 
     |_|/_/   \_\___|_____|\___/|_| \_\_____|
                                         

    This is not the page you're looking for: I was looking for a page compatible with class hnytest.GoogleHomePage but I was at the URL https://www.google.no/?gfe_rd=cr&ei=PM0DVtSuHISA8QecqKXoAw&gws_rd=ssl
    12:16:43.663 [Test worker] WARN  n.s.junit.runners.SerenityRunner - searching_for_dogs_should_find_the_wikipedia_entry failed, making attempt 2. Max retries: 3
    12:16:43.669 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
    12:16:43.669 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
    12:16:43.669 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:12801][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
    12:16:43.669 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 12][route: {}->http://localhost:12801][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
    12:16:43.669 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {}->http://localhost:12801
    12:16:43.672 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to localhost/127.0.0.1:12801
    12:16:43.672 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connection established 127.0.0.1:58004<->127.0.0.1:12801
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request DELETE /session/83347469057f667422e441723be81675 HTTP/1.1
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 >> DELETE /session/83347469057f667422e441723be81675 HTTP/1.1
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 >> Host: localhost:12801
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 >> Connection: Keep-Alive
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 >> User-Agent: Apache-HttpClient/4.4.1 (Java/1.8.0_05)
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 >> Accept-Encoding: gzip,deflate
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 >> "DELETE /session/83347469057f667422e441723be81675 HTTP/1.1[\r][\n]"
    12:16:43.673 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 >> "Host: localhost:12801[\r][\n]"
    12:16:43.674 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 >> "Connection: Keep-Alive[\r][\n]"
    12:16:43.674 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 >> "User-Agent: Apache-HttpClient/4.4.1 (Java/1.8.0_05)[\r][\n]"
    12:16:43.674 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 >> "Accept-Encoding: gzip,deflate[\r][\n]"
    12:16:43.674 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 >> "[\r][\n]"
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 << "HTTP/1.1 200 OK[\r][\n]"
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 << "Content-Length:72[\r][\n]"
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 << "Content-Type:application/json; charset=utf-8[\r][\n]"
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 << "Connection:close[\r][\n]"
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 << "[\r][\n]"
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.wire - http-outgoing-12 << "{"sessionId":"83347469057f667422e441723be81675","status":0,"value":null}"
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 << HTTP/1.1 200 OK
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 << Content-Length:72
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 << Content-Type:application/json; charset=utf-8
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG org.apache.http.headers - http-outgoing-12 << Connection:close
    12:16:43.790 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-12: Shutdown connection
    12:16:43.791 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
    12:16:43.791 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-12: Close connection
    12:16:43.791 [Forwarding quit on session 83347469057f667422e441723be81675 to remote] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 12][route: {}->http://localhost:12801][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
    12:16:56.004 [Test worker] DEBUG n.s.j.r.RetryFilteringRunNotifier - Test started: searching_for_dogs_should_find_the_wikipedia_entry(hnytest.SearchingOnGoogleStory)
    12:17:03.628 [Test worker] DEBUG n.s.j.r.RetryFilteringRunNotifier - Test failed: hnytest.SearchingOnGoogleStory: Unexpected start event for searching_for_dogs_should_find_the_wikipedia_entry(hnytest.SearchingOnGoogleStory)
    java.lang.AssertionError: Unexpected start event for searching_for_dogs_should_find_the_wikipedia_entry(hnytest.SearchingOnGoogleStory)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestEventAdapter.testStarted(JUnitTestEventAdapter.java:55) ~[na:na]
    	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:115) ~[junit-4.11.jar:na]
    	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:61) ~[junit-4.11.jar:na]
    	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:112) ~[junit-4.11.jar:na]
    	at net.serenitybdd.junit.runners.RunNotifierDecorator.fireTestStarted(RunNotifierDecorator.java:36) ~[serenity-junit-1.1.13.jar:na]
    	at net.serenitybdd.junit.runners.RetryFilteringRunNotifier.fireTestStarted(RetryFilteringRunNotifier.java:41) ~[serenity-junit-1.1.13.jar:na]
    	at org.junit.internal.runners.model.EachTestNotifier.fireTestStarted(EachTestNotifier.java:43) ~[junit-4.11.jar:na]
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:269) ~[junit-4.11.jar:na]
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) ~[junit-4.11.jar:na]
    	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:440) [serenity-junit-1.1.13.jar:na]
    	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:60) [serenity-junit-1.1.13.jar:na]
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) ~[junit-4.11.jar:na]
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) ~[junit-4.11.jar:na]
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) ~[junit-4.11.jar:na]
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) ~[junit-4.11.jar:na]
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) ~[junit-4.11.jar:na]
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) ~[junit-4.11.jar:na]
    	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:249) [serenity-junit-1.1.13.jar:na]
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86) [gradle-plugins-2.5.jar:2.5]
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49) [gradle-plugins-2.5.jar:2.5]
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64) [gradle-plugins-2.5.jar:2.5]
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50) [gradle-plugins-2.5.jar:2.5]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
    	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-2.5.jar:2.5]
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-2.5.jar:2.5]
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32) [gradle-messaging-2.5.jar:2.5]
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) [gradle-messaging-2.5.jar:2.5]
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source) [na:na]
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106) [gradle-plugins-2.5.jar:2.5]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
    	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-2.5.jar:2.5]
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-2.5.jar:2.5]
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360) [gradle-messaging-2.5.jar:2.5]
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54) [gradle-base-services-2.5.jar:2.5]
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40) [gradle-base-services-2.5.jar:2.5]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
    	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
    12:17:03.629 [Test worker] DEBUG n.thucydides.core.steps.StepEventBus - Test suite started for class hnytest.SearchingOnGoogleStory
    12:17:03.629 [Test worker] INFO  net.serenitybdd.core.Serenity - Test Suite Started: Searching on google story
    12:17:03.683 [Test worker] INFO  n.t.core.reports.ReportService - Reporting formats: [JSON, XML, HTML]
    12:17:03.687 [Test worker] INFO  n.t.core.reports.ReportService - Found reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@7d732286(format = Optional.of(XML))
    12:17:03.687 [Test worker] INFO  n.t.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@7d732286
    12:17:03.693 [Test worker] INFO  n.t.core.reports.ReportService - Found reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@d4fc77(format = Optional.of(JSON))
    12:17:03.693 [Test worker] INFO  n.t.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@d4fc77
    12:17:03.743 [Test worker] INFO  n.t.core.reports.ReportService - Found reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6c7de128(format = Optional.of(HTML))
    12:17:03.743 [Test worker] INFO  n.t.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6c7de128
    12:17:03.747 [Test worker] INFO  n.t.core.reports.ReportService - Generating reports for 0 test outcomes using: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@7d732286
    12:17:03.747 [Test worker] INFO  n.t.c.r.j.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
    12:17:03.747 [Test worker] INFO  n.t.core.reports.ReportService - Reports generated in: 0 ms
    12:17:03.747 [Test worker] INFO  n.t.core.reports.ReportService - Generating reports for 0 test outcomes using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@d4fc77
    12:17:03.747 [Test worker] INFO  n.t.c.r.j.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
    12:17:03.747 [Test worker] INFO  n.t.core.reports.ReportService - Reports generated in: 0 ms
    12:17:03.747 [Test worker] INFO  n.t.core.reports.ReportService - Generating reports for 0 test outcomes using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6c7de128
    12:17:03.747 [Test worker] INFO  n.t.c.r.j.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
    12:17:03.747 [Test worker] INFO  n.t.core.reports.ReportService - Reports generated in: 0 ms

Gradle config. Environment stuff (starting/stopping web server, database clean, etc) is left out. Notice the max.retries is set to 3.

    /**
     * Possible values for THUCYDIDES_TAKE_SCREENSHOTS:
     * - FOR_FAILURES
     * - FOR_EACH_ACTION
     * - BEFORE_AND_AFTER_EACH_STEP
     * - AFTER_EACH_STEP
     */
    String serenityTakeScreenshots = 'FOR_FAILURES';
    if(project.hasProperty('THUCYDIDES_TAKE_SCREENSHOTS')) {
        serenityTakeScreenshots = (THUCYDIDES_TAKE_SCREENSHOTS as String)
    }
    
    def bddTestUrl = "http://www.google.com"

    def browsers = [
        ['name': 'firefox', 'driverName': 'firefox', 'driver': null],
        ['name': 'chrome',  'driverName': 'chrome',  'driver': 'chromedriver_win32_2.14.exe']
    ]

    // Setting properties on the project before loading Serenity plugin. This is due to the code in applyPlugin in
    // Serenity Gradle Plugin. It saves the outputDirectory (config) in a variable when applying plugin, not when using
    // the task.
    // See https://github.com/serenity-bdd/serenity-core/blob/e8c1a874c9030db021b596943c4ab3a166f7be8c/serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy#L17
    def serenityReportDirectory_whereWeTellSerenityToPutTheReports = 'build-gradle/reports/serenity/'
    ext.serenity = [
        projectKey: "ProjectName",
        outputDirectory: serenityReportDirectory_whereWeTellSerenityToPutTheReports,
        sourceDirectory: serenityReportDirectory_whereWeTellSerenityToPutTheReports
    ]
    apply plugin: 'net.serenity-bdd.aggregator'
    // Remove Serenity checkOutcomes task as dependency for "check". We do a build, then in a different Jenkins jobs we run
    // BDD tests, so checkOutcomes will always fail in the "build run" if de don't remove this dependency.
    check.taskDependencies.values -= "checkOutcomes"

    browsers.each { def browser ->
        tasks.create(name: "test_bdd_${browser.name}_Gradle", type: Test) {

            group = 'BDD Tests'
            description = "BDD Testing for ${browser.name}"

            // Always run
            outputs.upToDateWhen { false }

            // Serenity - Aggregate HTML report
            finalizedBy 'aggregate'
            // Serenity - fail, if test fails
            finalizedBy 'checkOutcomes'

            // show standard out and standard error of the test JVM(s) on the console
            testLogging.showStandardStreams = true

            systemProperty 'webdriver.driver', browser.driverName
            (browser.driver != null ? systemProperty("webdriver.${browser.driverName}.driver", browser.driver) : '')
            systemProperty 'webdriver.base.url', bddTestUrl
            systemProperty 'serenity.take.screenshots', serenityTakeScreenshots

            systemProperty 'serenity.browser.width', 1280
            systemProperty 'serenity.native.events', false

            systemProperty 'max.retries', 3

            // Each test outputs to this directory
            systemProperty 'serenity.outputDirectory', serenityReportDirectory_whereWeTellSerenityToPutTheReports
            systemProperty 'thucydides.outputDirectory', serenityReportDirectory_whereWeTellSerenityToPutTheReports

            // Serenity report aggregator reads from this directory
            systemProperty 'serenity.source', serenityReportDirectory_whereWeTellSerenityToPutTheReports
            systemProperty 'thucydides.source', serenityReportDirectory_whereWeTellSerenityToPutTheReports

            include 'hnytest/SearchingOnGoogleStory.class'
        }
    }

SearchingOnGoogleStory.java:

    package hnytest;
    
    import net.serenitybdd.junit.runners.SerenityRunner;
    import net.thucydides.core.annotations.Managed;
    import net.thucydides.core.annotations.ManagedPages;
    import net.thucydides.core.annotations.Steps;
    import net.thucydides.core.pages.Pages;
    import org.junit.Test;
    import org.junit.runner.RunWith;
    import org.openqa.selenium.WebDriver;
    
    @RunWith(SerenityRunner.class)
    public class SearchingOnGoogleStory {
    
        @Managed
        public WebDriver webdriver;
    
        @ManagedPages(defaultUrl = "http://www.google.com")
        public Pages pages;
    
        @Steps
        public GoogleSearchSteps steps;
    
        @Test
        public void searching_for_cats_should_find_the_wikipedia_entry() {
            steps.open_home_page();
            steps.searchFor("cats");
            steps.resultListShouldContain("Cat - Wikipedia, the free encyclopedia");
        }
    
        @Test
        public void searching_for_dogs_should_find_the_wikipedia_entry() {
            steps.open_home_page();
            steps.searchFor("dogs");
            steps.resultListShouldContain("Dog - Wikipedia, the free encyclopedia");
        }
    
        @Test
        public void searching_for_hamsters_should_find_the_wikipedia_entry() {
            steps.open_home_page();
            steps.searchFor("hamsters");
            steps.resultListShouldContain("Hamster - Wikipedia, the free encyclopedia");
        }
    }

**Comment by HNygard** [comment]
[BlockJUnit4ClassRunner](https://github.com/junit-team/junit/blob/master/src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java#L77) returns a Description in describeMethod(method). The hashCode() of this object is the same for each retry.

The hashCode() is based on the unique identifier for Description. This is the name of the test. The name of the test is created by testName() in BlockJUnit4ClassRunner, which can be overriden by SerenityRunner.

I'm not completely sure if my code works as expected, but will submit a commit for it.

**Comment by wakaleo** [comment]
Could you make a pull request and I will try it out.

**Comment by YamStranger** [comment]
Hello @HNygard thanks for reporting this issue. Please try add 
```
systemProperty 'junit.retry.tests', true
```
 to your tests. We will update documentation soon.

**Comment by HNygard** [comment]
@YamStranger : Which framework will pick up that? Serenity does not use 'junit.retry.tests' AFAIK and Google have no hits on that.

**Comment by HNygard** [comment]
@wakaleo : Sorry, I don't have the time to create a pull request with the changes I created. I haven't verified that it works as intended.

**Comment by YamStranger** [comment]
@HNygard We have bug - that tests retrying enabled when somebody set max.repeats more than 0, without junit.retry.tests=true. In this case some internal initialization will not take part ([enabling](https://github.com/serenity-bdd/serenity-core/blob/d40c9654f3d9228ab7978705a72067d9ad5a7620/serenity-junit/src/main/java/net/serenitybdd/junit/runners/SerenityRunner.java#L313)), as result - strange  behaving. I am working on this issue, but as fast solution you can set system property junit.retiry.tests to true, I should work.

**Comment by YamStranger** [comment]
Hi @HNygard 
I am not sure that you include in your gradle build script this [recomendation](http://thucydides.info/docs/serenity-staging/#_building_serenity_projects_in_gradle) about gradle.startParameter.continueOnFailure = true. 

Gradle during its work generate his own report and notify about it status. Serenity has own report, and it builds during aggregation task.

If retrying will enabled and you have some testMethod that fails on first fire and succeed of second:
1.  gradle report will be red, and contains one successful run and one fail run
2. serenity aggregated report will be green - because second run was successful. 

Without that option gradle build will fail and aggregation will not start at all (and you will not see that retrying was success).

**Comment by YamStranger** [comment]
@HNygard this issue fixed under 1.1.22-rc.5. 

Please close it, if so

**Comment by hypery2k** [comment]
is there any possibility to remove the failed testMethod from the gradle report?

**Comment by YamStranger** [comment]
Hello @hypery2k 

No, all executed methods will be included in report (if it was failed during first run, and success during second run both will be in log, but only success will be in aggregated report)

**Comment by hypery2k** [comment]
is there any possibility to not lead to a build failure in gradle then?

**Comment by YamStranger** [comment]
@hypery2k sure: 

please follow recommendations how to build test with serenity-bdd and serenity gradle plugin: 
http://thucydides.info/docs/serenity-staging/#_building_serenity_projects_in_gradle

To make gradle to continue executing of your tests after some tests are failed you should use ( as described in gradle manual):
```
gradle.startParameter.continueOnFailure = true
```

**Comment by hypery2k** [comment]
I already did this, but in Jenkins the build is failed and the serenity report is green :(

**Comment by YamStranger** [comment]
Did you use property ? 
```
serenity.console.colors = true
```

if not: 

If retry enabled, and first try - failed, second - finished successful - you expect that gradle build will be green or jenkins will be green. 
If build configured properly, than build contains next parts: 
1) gradle run tests
2) during test execution json/xml reports are generated (serenity-bdd internal reports, as well as junit compatible )
3) gradle execute serenity-gradle-plugin to aggregate reports and analyse results and fail build if something wrong. 

First of all gradle execute tests and make build fail if during test execution some method with configured retries had failed retry.

when executed goal 
```
gradle aggregate
```
serenity-gradle-plugin will aggregate report (generate html report), during analysing result, in case if retries are configured and method should be green (first retry is failed, second is green for example) - build will success, if method should be red (both retries are failed) - plugin will fail the build. 

I see two ways to make your gradle build green: 
for both of them you should ignore result of gradle build, and mark your build green/red based on:
1)  junit compatible reports generated by serenity
2) executing `gradle aggregate` to make serenity-gradle-plugin responsible for failing/mark green test results for tests created with serenity.

**Comment by YamStranger** [comment]
Also I found that there is some jenkins plugin for serenity bdd:
https://wiki.jenkins-ci.org/display/JENKINS/Thucydides+Plugin
BUT it is not our plugin, and I have no idea if it will work with latest version (plugin updated in 2013).

For now we did not develop any plugins for CI

**Comment by hypery2k** [comment]
thanks for the hint. I now using this JUnit pattern in Jenkins and it's working with the retry stuff:
```
target/site/serenity/SERENITY-JUNIT-*.xml
```
