### ISSUE TITLE
Tests run but "Generating test results for 0 tests"

### ISSUE THREAD

**Issue by dev0101** [serenity-bdd/serenity-core#1320]
Hello,

I use Serenity BDD + cucumber, sometimes the reports aren't generated.
It depends on tags i used :
--tags ~@test : no reports
without tags : no reports
--tags @critique : i have reports

i use this versions :
<serenity.version>1.9.31</serenity.version>
<serenity.maven.version>1.9.31</serenity.maven.version>
<serenity.cucumber.version>1.9.12</serenity.cucumber.version>

When i have no reports i have this in the console :
[ERROR] Tests run: 79, Failures: 4, Errors: 14, Skipped: 0
...
[INFO] Generating test results for 0 tests
[INFO] 41 requirements loaded after 439 ms
[INFO] 41 related requirements found after 439 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 554 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 2773 ms

**Comment by wakaleo** [comment]
You need to use the new Cucumber tag syntax (https://github.com/cucumber/cucumber/tree/master/tag-expressions). (see https://github.com/serenity-bdd/serenity-cucumber/issues/129)

**Comment by dev0101** [comment]
Even without tags i have this issue

**Comment by wakaleo** [comment]
What does your test runner look like?

**Comment by dev0101** [comment]
package com.tests.automatedtests.runners;

import org.junit.runner.RunWith;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import cucumber.api.CucumberOptions;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features= {"src/test/resources/features"}, 
				glue="com.tests.automatedtests.glue")
public class GlobalRunner {
}

**Comment by wakaleo** [comment]
Are you setting the tags property anywhere in the pom.xml or serenity.properties?

**Comment by dev0101** [comment]
no

**Comment by wakaleo** [comment]
Try comparing your project with https://github.com/serenity-bdd/serenity-cucumber-starter.

**Comment by dev0101** [comment]
the differences are :

- i don't have <configuration><tags>${tags}</tags></configuration>
is it required?

- the Serenity version : 
i have 1.9.31 instead of 1.9.26

- the Serenity Cucumber version : 
i have 1.9.12 instead of 1.9.8

- the maven-failsafe-plugin and maven-surefire-plugin : 
i have 2.21.0 instead of 2.20

I gonna try to use this version

**Comment by dev0101** [comment]
I have the same issue using the versions : 
the Serenity version : 1.9.26
the Serenity Cucumber version :1.9.8
the maven-failsafe-plugin and maven-surefire-plugin : 2.20

**Comment by wakaleo** [comment]
I don't think it's related to the versions (this is a common use case), rather something to do with your feature files or project structure. I would need to look at the project directly. You can ask for help from the Serenity community on https://serenity-bdd.rocket.chat or get some professional help with one of the Serenity Support packages (https://johnfergusonsmart.com/serenity-bdd-mentoring#support)

**Comment by dev0101** [comment]
ok, thank you for your help

**Comment by PrasadNutalapati** [comment]
This guy Wakaleo is surprising me ! He built a wrapper around existing open source projects like JUnit, Cucumber etc., and he evangelized it a LOT ! Published some blogspots, presented at few seminars and for the questions about his framework, he wants every one to buy a package and pay ???? As his name says it, he is really 'smart'.

**Comment by PrasadNutalapati** [comment]
Solved by Wakaleo's suggestion(else where) to comparing pom.xml from 
`https://github.com/serenity-bdd/screenplay-pattern-todomvc `

**Comment by handresc1127** [comment]
I had the same problem, solved it using "cucumber.options" instead of "tags".
Examples:

Ok - Generating test results for n tests
mvn -Dcucumber.options="--tags ''" clean install
mvn -Dcucumber.options="--tags '@Tag1'" clean install
mvn -Dcucumber.options="--tags @Tag1" clean install

Error Generating test results for 0 tests
mvn -Dtags=@Tag1 clean install

**Comment by brcros** [comment]
> Solved by Wakaleo's suggestion(else where) to comparing pom.xml from `https://github.com/serenity-bdd/screenplay-pattern-todomvc `

It would be great to have the missing detail... i experienced the same error using serenity-rest pom and cannot really compare pom.xml. thank you.
