### ISSUE TITLE
Serenity WaitUntil API question

### ISSUE THREAD

**Issue by ghitarist** [serenity-bdd/serenity-core#1321]
How to use this elegant module " import **net.serenitybdd.screenplay.waits.WaitUntil** ?
I've tried to implement this waiting technique in my tests but it never worked. 
However, Target.resolveFor(actor).waitUntilPresent() achieves the goal, as expected.

I had tried all available WaitUntil combinations using different target types and WebElementStateMatchers, nothing ever worked for my script.

```
@RunWith(SerenityRunner.class)
public class SendBoxCPEGroupSetPageNr {

    @org.junit.Before
    public void set_the_stage() {
        OnStage.setTheStage(new OnlineCast());
    }

    @Test
    @Step
    public void thatAdminIsLoggedIn() throws Throwable {
       
        //NOT WORKING, row executed but no wait happens
        WaitUntil.the(TableGrid.LOADING_COMPLETE, isPresent());
        //WORKING, waits until element is generated, only after execute next row of the script.
        TableGrid.LOADING_COMPLETE.resolveFor(theActorInTheSpotlight()).waitUntilPresent();
        
        givenThat(theActorInTheSpotlight()).has(Click.on(CPEGroupTab.EXPAND_ALL));
```

**Comment by wakaleo** [comment]
WaitUntil is a performable, so it needs to be performed by an actor, eg actor.attemptsTo(WaitUntil...

**Comment by ghitarist** [comment]
May I kindly ask you open a ticket to add the functionality for the end user to be able to use the WaitUntil.the() pattern in context of a static method also. If not, could you please make it impossible to be used outside the actor.atteptsTo() methods (or any other performable... method, so that the end user might see a warning, an error or a suggestion to not use it the 'wrong' way. 
I've spent too much time figuring out why WaitUntil is not working in my tests.
I would be happy as an end user to find a usage suggestion in official serenity documentation
http://www.thucydides.info/docs/serenity/
