### ISSUE TITLE
Serenity Loads the stories too slowly

### ISSUE THREAD

**Issue by SumantaSarathiChakraborty** [serenity-bdd/serenity-core#1323]
Hi,

We have a large scale of story files which we execute parallaly. Serenity takes almost 50% time in loading the story files. In console it prints all the story files content section one by one and then starts execution. What I understand is it loads the stories first which takes lot of time.

Is there any way by which I can reduce the loading time? Please suggest. 

Thanks & Regards,
Sumanta

**Comment by wakaleo** [comment]
What version and BDD framework are you using?

**Comment by SumantaSarathiChakraborty** [comment]
Latest serenity with Jbehave..

**Comment by wakaleo** [comment]
JBehave has known issues with large numbers of tests, with no solution that I know of. I would recommend migrating to Cucumber if possible.
