### ISSUE TITLE
Issue with firefox with jBehave Serenity

### ISSUE THREAD

**Issue by dan0935** [serenity-bdd/serenity-core#1324]
I am using jbehave serenity and when I run my story, Firefox open but script not able to enter url in that

My versions are :  

Firefox : 61.0.1(64 bit)
<serenity.version>1.9.7</serenity.version>
<serenity.jbehave.version>1.38.0</serenity.jbehave.version>
geckodriver : v0.21.0

Maven command which I am using to run is -
clean verify -Dwebdriver.driver=firefox -Dmetafilter="+scenarioname" -Dglobal.properties.file="propertlyfilename"

**Comment by wakaleo** [comment]
Try with the latest versions of everything, including geckodriver

**Comment by dan0935** [comment]
Are these not the latest version of firefox/serenity/jbehave version and gecko driver?

**Comment by wakaleo** [comment]
See http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22serenity-core%22 and http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22serenity-jbehave%22

**Comment by dan0935** [comment]
this issue has been resolved.Thanks
