### ISSUE TITLE
Report aggregation failing due to null 'has' (facts) on CastMember

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1325]
I've just upgraded my Serenity project to the latest, namely:

core: 1.9.31
cucumber: 1.9.12

And exception is being thrown during aggregation (HtmlAggregateStoryReporter) with:
 
```
FTL stack trace ("~" means nesting-related):
	- Failed at: #if (castMember.hasFacts())  [in template "freemarker/default.ftl" at line 192, column 53]
----
```

Code is blowing up at `CastMember:57`

![image](https://user-images.githubusercontent.com/626941/43643311-d6e32ff4-9722-11e8-95dd-e404c98f5891.png)

I haven't defined any facts on my actors yet but I'd assume this is an optional setup?

**Comment by wakaleo** [comment]
It should be optional, yes, hence the conditional - could it be a library conflict with Maven or Gradle?

**Comment by nbarrett** [comment]
Thanks @wakaleo for quick response. Okay, will look into. We use BUCK so I have to hand-pick dependencies. I'll go through them in more detail.

**Comment by nbarrett** [comment]
Hmmm, I can't see how CastMember gets instantiated with this member null:
`private final List<String> has;` 

When I put a breakpoints on, neither of the public constructors are called so perhaps it's using some deserialisation mechanism?

**Comment by nbarrett** [comment]
Actually, I did a quick experiment and did this in the setup 

'actor.has(new DummyFact(actor.getName()));'

And now the reports render fine:

![image](https://user-images.githubusercontent.com/626941/43646813-d031aa7c-972d-11e8-9d31-0d60b119de96.png)

Do you think this could still be a dependency issue?

**Comment by wakaleo** [comment]
That is odd - maybe place a breakpoint to see what the code is doing?

**Comment by wakaleo** [comment]
Could you do a PR to check for null?

**Comment by nbarrett** [comment]
Sure okay.... only thing is that I can't reproduce this on a serenity demo project (e.g. the recent updated [journey-demo](https://github.com/serenity-bdd/serenity-demos/tree/master/serenity-journey-demo)), so I think it might be something strange about my project setup. I'll continue to investigate as it's not clear why this is happening. Does the aggregate reporting instantiate the java objects by json deserialisation?
