### ISSUE TITLE
Scripts run fine on Firefox but in stack trace I am getting this message

### ISSUE THREAD

**Issue by dan0935** [serenity-bdd/serenity-core#1326]
<serenity.version>1.9.31</serenity.version>
<serenity.jbehave.version>1.42.0</serenity.jbehave.version>
gecko driver version : v0.21.0

Scripts run fine on Firefox but in stack trace I am also getting this messages.How to get  rid of this messages

1533312294114	addons.manager	DEBUG	Application has been upgraded
1533312294168	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider", "XPIInternal"]
1533312294172	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1533312294227	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1533312294232	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1533312294232	addons.manager	DEBUG	Starting provider: XPIProvider
1533312294233	addons.xpi	DEBUG	startup
1533312294234	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1533312294252	addons.xpi	INFO	Removing all system add-on upgrades.
1533312294254	addons.xpi	DEBUG	checkForChanges
1533312294255	addons.xpi	DEBUG	Loaded add-on state: ${}
1533312294267	addons.xpi	DEBUG	New add-on activity-stream@mozilla.org in app-system-defaults
1533312294272	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1533312294275	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1533312294279	addons.xpi	DEBUG	New add-on followonsearch@mozilla.com in app-system-defaults
1533312294282	addons.xpi	DEBUG	New add-on formautofill@mozilla.org in app-system-defaults
1533312294284	addons.xpi	DEBUG	New add-on onboarding@mozilla.org in app-system-defaults
1533312294287	addons.xpi	DEBUG	New add-on screenshots@mozilla.org in app-system-defaults
1533312294289	addons.xpi	DEBUG	New add-on webcompat-reporter@mozilla.org in app-system-defaults
1533312294291	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1533312294294	addons.xpi	DEBUG	getInstallState changed: true, state: {}
1533312294306	addons.xpi-utils	DEBUG	Opening XPI database C:\Users\bhardwajd\AppData\Local\Temp\rust_mozprofile.EPgWHqHqg4tG\extensions.json
1533312294308	addons.xpi-utils	DEBUG	New add-on activity-stream@mozilla.org installed in app-system-defaults
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1533312294396	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
1533312294446	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1533312294473	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 26
1533312294479	addons.xpi-utils	DEBUG	New add-on followonsearch@mozilla.com installed in app-system-defaults
1533312294503	addons.xpi-utils	DEBUG	New add-on formautofill@mozilla.org installed in app-system-defaults
1533312294584	addons.xpi-utils	DEBUG	New add-on onboarding@mozilla.org installed in app-system-defaults
1533312294613	addons.xpi-utils	DEBUG	New add-on screenshots@mozilla.org installed in app-system-defaults
1533312294652	addons.xpi-utils	DEBUG	New add-on webcompat-reporter@mozilla.org installed in app-system-defaults
1533312294662	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults

**Comment by wakaleo** [comment]
This is a GeckoDriver issue - see some suggestions here: https://stackoverflow.com/questions/41387794/how-do-i-disable-firefox-logging-in-selenium-using-geckodriver and http://www.automationtestinghub.com/disable-firefox-logs-selenium/. I'd be happy to consider a PR to incorporate this automatically in the Serenity Firefox support code.

**Comment by dan0935** [comment]
Issue has been resolved
