### ISSUE TITLE
Cucumber + Jira integration ticket status workflow update

### ISSUE THREAD

**Issue by grzegorzmlynarczyk** [serenity-bdd/serenity-core#1327]
Hi,

I saw a similar ticket, but it's dead since almost 2 years, so I'm creating a new one.
I've got a problem with two way integration with Jira. I am able to pull requirements, stories and tickets from jira to my reports, and to produce comments under those tickets if necessary. However, the status of the ticket is never updated in Jira. 

I'm attaching following files for clarity (all links and usernames had to be erased):

[log.txt](https://github.com/serenity-bdd/serenity-core/files/2262736/log.txt)
[pom.txt](https://github.com/serenity-bdd/serenity-core/files/2262738/pom.txt)
[serenityproperties.txt](https://github.com/serenity-bdd/serenity-core/files/2262741/serenityproperties.txt)

Here's my workflow:

```
`when 'OPEN', {
    'success' should: 'Resolve Issuexx'
}

when 'REOPENED', {
    'success' should: 'Resolve Issue'
}

when 'RESOLVED', {
    'failure' should: 'Reopen Issue'
}

when 'IN PROGRESS', {
    'success' should: ['Stop Progress','Resolve Issue']
}

when 'CLOSED', {
    'failure' should: 'Reopen Issue'
}
`
```
 I've already tried sticking to the default plugin workflow, changing the cases of the statuses, and also using thucydides properties - nothing seems to work.

**Comment by wakaleo** [comment]
Could you please open this issue in serenity-jira rather than serenity-core?

**Comment by grzegorzmlynarczyk** [comment]
Sure, sorry for trouble - here's the link under serenity-jira:
https://github.com/serenity-bdd/serenity-jira/issues/89
