### ISSUE TITLE
[WARNING] Failed to load requirements: gherkin.ParserException$CompositeParserException: Parser errors:

### ISSUE THREAD

**Issue by vaibhav2701** [serenity-bdd/serenity-core#1329]
We were using serenity + jbehave for our test framework for long but with older version of serenity. Recently we moved to the latest version and although the old tests work fine and reports get generated we are observing a whole lot of exceptions in the console after execution is complete.

Serenity version currently:
<serenity.version>1.9.31</serenity.version>
<serenity.jbehave.version>1.42.0</serenity.jbehave.version>

Results :
![serenity](https://user-images.githubusercontent.com/38987527/43759405-c2e8449a-9a3c-11e8-8d11-035c928b2d88.PNG)

**Comment by wakaleo** [comment]
Interesting. Can you share a sample project that reproduces the issue?

**Comment by vaibhav2701** [comment]
Hi.

i cant upload the original project but am uploading a project which has a similar problem. Its a maven project and when i do a 'mvn clean install' from command prompt on it i get that error. It has some other issue because of which it is not finding the feature file but that is not what concerns me right now.

Thanks.
[TestXYZ.zip](https://github.com/serenity-bdd/serenity-core/files/2266012/TestXYZ.zip)

**Comment by dtanedo** [comment]
Hi @vaibhav2701 ,

I also got hit with the same error. Maybe you can try the Scenario Outline builder.
<img width="433" alt="screen shot 2018-09-10 at 7 49 42 pm" src="https://user-images.githubusercontent.com/16568535/45295882-c69d7400-b532-11e8-9355-326311313d1f.png">

**Comment by vaibhav2701** [comment]
Hi,

Any help on this will be appreciated. we are still struggling with those Parser Exceptions - "Failed to load requirements: gherkin.ParserException$CompositeParserException: Parser errors:"

I have attached the demo project in my previous post which shows the errors. Any help will be appreciated

**Comment by wakaleo** [comment]
You are using JBehave story syntax in a .feature file (which should be Cucumber Gherkin syntax). If you have to use JBehave, you need to rename your feature files as .story files.

**Comment by vaibhav2701** [comment]
I tried to rename the feature file to .story file but still i am getting the same exception. The exception is clearly mentioning cucumber in it whereas we are using jbehave dependencies in pom. Is it that i have to exclude something from pom that will fix it??
[ParserException.txt](https://github.com/serenity-bdd/serenity-core/files/2400898/ParserException.txt)
[pom.xml.txt](https://github.com/serenity-bdd/serenity-core/files/2400899/pom.xml.txt)

**Comment by wakaleo** [comment]
renaming the *.feature file to *.story (and updating the runner class accordingly) fixes the issue: [TestXYZ.zip](https://github.com/serenity-bdd/serenity-core/files/2400957/TestXYZ.zip)

**Comment by vaibhav2701** [comment]
Thanks a lot :). Found the issue. Finally it worked for me on my real project. In our original pom.xml we had an extra plugin which was not there in the TestXYZ.zip project. When I removed it, the project is now building fine. The plugin is shown in BOLD.

<plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.18.1</version>
            <configuration>
               <skip>true</skip>
               <testFailureIgnore>true</testFailureIgnore>
               <forkCount>0</forkCount>
            </configuration>
         </plugin>
		 **<plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-install-plugin</artifactId>
            <version>2.5.2</version>
         </plugin>**
         <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.18.1</version>
            <configuration>
               <includes>
                  <include>**/*TestSuite.java</include>
               </includes>
               <forkCount>3</forkCount>
               <reuseforks>true</reuseforks>
               <threadCount>3</threadCount>
               <argLine>-Xmx512m</argLine>
               <parallel>methods</parallel>
               <systemPropertyVariables>
                  <webdriver.driver>${webdriver.driver}</webdriver.driver>
               </systemPropertyVariables>
            </configuration>
            <executions>
               <execution>
                  <goals>
                     <goal>integration-test</goal>
                     <goal>verify</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.2</version>
            <configuration>
               <source>1.7</source>
               <target>1.7</target>
            </configuration>
         </plugin>
         <plugin>
            <groupId>net.serenity-bdd.maven.plugins</groupId>
            <artifactId>serenity-maven-plugin</artifactId>
            <version>${serenity.version}</version>
            <executions>
               <execution>
                  <id>serenity-reports</id>
                  <phase>post-integration-test</phase>
                  <goals>
                     <goal>aggregate</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
      </plugins>
