### ISSUE TITLE
Finding out how many remaining tests left to execute

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1330]
Hi, 
Is there a way (e.g. API call or otherwise) to find out, during test execution, how many remaining tests are there left? The business case for this would be to give the test requester an ETA of sorts. 

Currently I don't have a quantifiable way to do so. Thanks!

**Comment by wakaleo** [comment]
Not at the moment, and it would be quite hard to do for a general case.
