### ISSUE TITLE
I am getting exception Caused by: java.lang.NullPointerException: null at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:300) ~[serenity-jira-plugin-1.8.0.jar:na].While trying to modify the code of serenity-jira-plugin source code .I am not able to set up the workspacebecause of the below error 

### ISSUE THREAD

**Issue by nivrutha** [serenity-bdd/serenity-core#1332]
Maven Error is 
[ERROR] Failed to execute goal org.codehaus.mojo:axistools-maven-plugin:1.4:wsdl2java (default) on project thucydides-jira-plugin: Execution default of goal org.codehaus.mojo:axistools-maven-plugin:1.4:wsdl2java failed: A required class was missing while executing org.codehaus.mojo:axistools-maven-plugin:1.4:wsdl2java: org/apache/commons/discovery/tools/DiscoverSingleton
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:axistools-maven-plugin:1.4
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/repo/org/codehaus/mojo/axistools-maven-plugin/1.4/axistools-maven-plugin-1.4.jar
[ERROR] urls[1] = file:/C:/repo/javax/activation/activation/1.1.1/activation-1.1.1.jar
[ERROR] urls[2] = file:/C:/repo/javax/mail/mail/1.4/mail-1.4.jar
[ERROR] urls[3] = file:/C:/repo/commons-logging/commons-logging/1.1/commons-logging-1.1.jar
[ERROR] urls[4] = file:/C:/repo/log4j/log4j/1.2.12/log4j-1.2.12.jar
[ERROR] urls[5] = file:/C:/repo/logkit/logkit/1.0.1/logkit-1.0.1.jar
[ERROR] urls[6] = file:/C:/repo/avalon-framework/avalon-framework/4.1.3/avalon-framework-4.1.3.jar
[ERROR] urls[7] = file:/C:/repo/javax/servlet/servlet-api/2.3/servlet-api-2.3.jar
[ERROR] urls[8] = file:/C:/repo/org/json/json/20090211/json-20090211.jar
[ERROR] urls[9] = file:/C:/repo/org/codehaus/plexus/plexus-compiler-api/1.5.3/plexus-compiler-api-1.5.3.jar
[ERROR] urls[10] = file:/C:/repo/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[11] = file:/C:/repo/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar
[ERROR] urls[12] = file:/C:/repo/axis/axis/1.4/axis-1.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.commons.discovery.tools.DiscoverSingleton
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by nivrutha** [comment]
Null pointer is due there is a comment with Anonymous user and so the below line is giving error
private IssueComment convertToComment(JsonObject fieldObject)  {
        return new IssueComment(fieldObject.getAsJsonPrimitive("self").getAsString(),
                                fieldObject.getAsJsonPrimitive("id").getAsLong(),
                                fieldObject.getAsJsonPrimitive("body").getAsString(),
                                **fieldObject.getAsJsonObject("author").getAsJsonPrimitive("name").getAsString());**
    }

**Comment by wakaleo** [comment]
This looks like a missing or conflicting dependency. Could you raise it in https://github.com/serenity-bdd/serenity-jira/issues rather than here?
