### ISSUE TITLE
@FindBy issue 

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#1335]
Hello @wakaleo,

- serenity version : 1.9.34
- serenity gradle : 1.9.34
- jbehave : 1.42

I have a strange issue when locating an element. But sorry, I will not be able to provide any reproducible case for this 😞 
I have a WebElement of type "textarea".

When I try to interact with this element with serenity's FindBy annotation : 
```
    @FindBy(xpath = "//div[@id='definition']/textarea")
    private WebElementFacade textArea;
    ...

textArea.sendKeys("test");

```

I always got error : `WebElement is not available`. 
Needless to say, I already try to debug this event with wait, click/clear, focus, etc.

**But it's working well when I use classic Selenium to get this element**  : 

```
getDriver().findElement(By.xpath("//div[@id='definition']/textarea")).sendKeys("test"}");

```
Do you have any clue about a difference between @FindBy and classical findElement ? 

Thanks !

**Comment by mmanach** [comment]
Ok thanks, it's working too 🙂 
Next step : try to understand what is going on with @FindBy

**Comment by wakaleo** [comment]
I would just use the inline lookups (but have constants instead of inlined strings of course).

**Comment by mmanach** [comment]
Ok so for you using @FindBy is no longer the "right way" / good practice ?

**Comment by wakaleo** [comment]
I find direct lookup via constant locators more reliable and just as readable.

**Comment by mmanach** [comment]
Ok. I think we can close for now because we have a fix, but it would be great to understand the underlying behavior of @finby. Thanks !
