### ISSUE TITLE
Not able to switch native to web view in iOS? 

### ISSUE THREAD

**Issue by yogeshggit** [serenity-bdd/serenity-core#1337]
I am not able to switch from native to web view in iOS application . I tried using below code it is not working not able to switch

Set contextHandles = driver.getContextHandles();

for (String s : contextHandles)

{

System.out.println(“content :”+ s);

if(s.contains(“WEBVIEW”)) {

driver.context(s);

}

}

can someone please help how switch from native to web view

always getting below error

Driver info: driver.version: AppiumDriver

at io.appium.java_client.AppiumDriver.getContextHandles(AppiumDriver.java:227)

at ZDebugTests.iOSTest.main(iOSTest.java:50)

Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List

at io.appium.java_client.AppiumDriver.getContextHandles
can someone please help here

**Comment by wakaleo** [comment]
This looks like a version or dependency conflict of some kind. Do a dependency analysis to look for conflicting libraries.

**Comment by yogeshggit** [comment]
you mean appium desktop version i need to upgrade

**Comment by wakaleo** [comment]
Ask the question on https://serenity-bdd.rocket.chat, there are many Seren

**Comment by wakaleo** [comment]
Do you have a reason that leads you to believe this is a Serenity issue? It sounds like an Appium dependency or version issue. Have you asked the Appium folk?

**Comment by wakaleo** [comment]
Closed for lack of activity
