### ISSUE TITLE
Appium starts two sessions instead of one

### ISSUE THREAD

**Issue by risinek** [serenity-bdd/serenity-core#1339]
## The problem

My test are often failing with error 
```
2018-08-08 13:20:12:459 - [UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
```
That doesn't say much, so I was looking into logs last few days and finally found some misbehave. For some reason, appium starts multiple session even though it should be just one. 

See the logs on gist:
First session with id `23bfb660-5917-42cb-89ec-b1cc33fe5b82` went OK. Test passed. Then second test started and session with id `f1a77107-e37d-456b-9649-88c631be7208` started, but right after that session id `c6315881-224a-4dae-ac65-a2a1e3348ffc` starts.. 
No idea why this is happening. When the second session is started, then the error with `ECONNRESET` is thrown and test fails

I filled this exact issue on Appium github issue tracker https://github.com/appium/appium/issues/11163#issue-348745181 , but they confirmed, that it looks like client problem.. Is it possible, that serenity may start more session because of some timeout? Because it looks like the client sends 2 requests to create session instead of one, which causes the ECONNRESET on device's uiautomator2 server and the test fails. 

## Environment

* Appium version (or git revision) that exhibits the issue: >=1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.x
* Desktop OS/version used to run Appium: OS X High Sierra, Mac Mini
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI

* serenity version: 1.9.22

## Details

Using Serenity, maven. Appium server is on remote machine. ADB server is running on the same machine as Appium server and multiple devices are connected via USB to that machine.
Appium server ran with parameters `--relaxed-security --log-timestamp --session-override`

## Link to Appium logs

https://gist.github.com/risinek/9f5745ce941fd222f242565883a03cd3

**Comment by wakaleo** [comment]
Have you tried with Serenity 1.9.35, which uses the latest Appium version? Serenity just wraps and calls the Appium driver, so unless you have a specific stack trace indicating an issue with the Serenity code, this is unlikely to be a Serenity issue.

**Comment by wakaleo** [comment]
I wouldn't think so as this would mean that there would likely  be multiple drivers for other drivers as well, but feel free to dig into the code to see what it does. Best place to start is the `AppiumDriverProvider` class.

**Comment by risinek** [comment]
I will try.. Thanks for pointing me to that class.
