### ISSUE TITLE
Report shows object reference when using GivenWhenThen.seeThat(Question, Predicate)

### ISSUE THREAD

**Issue by nu75h311** [serenity-bdd/serenity-core#1341]
Because ```Predicate``` does not have a ```toString()```, the validation is done but the report shows something like:

> Then the name of the selected folder should be java.util.function.Predicate$$Lambda$121/1225554563@6d0b0da6

**Comment by wakaleo** [comment]
It is impossible to associate a meaningful toString() or any other label with an anonymous lambda. To avoid this issue, use GivenWhenThen.seeThat(String, Question, Predicate) instead.

**Comment by nu75h311** [comment]
I tried:
```seeThat("BLABLABLA ", TheSelectedLoadFolder.name(), isEqual(directoryPath))```
got:

> Then BLABLABLA should be java.util.function.Predicate$$Lambda$116/2055276126@2149594a

```<serenity.screenplay.version>1.9.35</serenity.screenplay.version>```

Am I missing something?

**Comment by wakaleo** [comment]
```
        actor.should(
                seeThat("the total price", ThePrice.total(), equalTo(100)),
                seeThat("the VAT", ThePrice.vat(throwError), equalTo(vat)),
                seeThat("the price with VAT", ThePrice.totalWithVAT(), equalTo(120))
        );
```

**Comment by nu75h311** [comment]
I guess there is no good way to use Predicates instead of Matchers, then.

**Comment by wakaleo** [comment]
Predicates should work too:

```
    public static <T> Consequence<T> seeThat(String subject, Question<? extends T> actual, Predicate<T> expected) {
        return new PredicateConsequence(subject, actual, expected);
    }
```

**Comment by wakaleo** [comment]
What version are you using?

**Comment by nu75h311** [comment]
Version 1.9.35.

I just ran:
```theActorInTheSpotlight().should(seeThat("MATCHER", TheSelectedLoadFolder.name(), equalTo(directoryPath)));```

to get:

> hen MATCHER should be 'CD_testData_01'


and:
```theActorInTheSpotlight().should(seeThat("PREDICATE", TheSelectedLoadFolder.name(), isEqual("")));```

to get:
> Then PREDICATE should be java.util.function.Predicate$$Lambda$121/1730813026@490c7a83

**Comment by wakaleo** [comment]
What type is your Predicate?

**Comment by nu75h311** [comment]
String

**Comment by wakaleo** [comment]
Is it a Java 8 Predicate?

**Comment by nu75h311** [comment]
Yep

**Comment by wakaleo** [comment]
Interesting. Here is some working code with Java 8 Predicates:
```
    @Test
    public void shouldBeAbleToPurchaseSomeItemsWithDeliveryUsingPredicates() {
        givenThat(dana).has(purchased().anApple().thatCosts(10).dollars(),
                andPurchased().aPear().thatCosts(5).dollars());

        when(dana).attemptsTo(haveThemDelivered);

        then(dana).should(seeThat(theTotalCost(), Predicate.isEqual(15)));
    }
```

**Comment by nu75h311** [comment]
I just ran the serenity-screenplay module tests and for this ```shouldBeAbleToPurchaseSomeItemsWithDeliveryUsingPredicates()``` test the Serenity report shows:

> Then Total cost should be java.util.function.Predicate$$Lambda$121/1638631856@144ab983

while for ```shouldBeAbleToPurchaseSomeItemsWithDelivery()``` I got beautiful

> Then total cost should be (15)
> Then thank you message should be 'Thank you'

The test works, but the report is showing this Predicate object.

**Comment by wakaleo** [comment]
The problem is that the Predicate class has no toString(). The solution will not be pretty.

**Comment by nu75h311** [comment]
That is what I meant in the first comment. I should have worded it better.

**Comment by wakaleo** [comment]
To use Predicates properly, you need to be able to pass a String description as well. For example:
```
        then(dana).should(seeThat("Total cost", theTotalCost(),
                                   matches("is equal to 15", isEqual(15))));
```
