### ISSUE TITLE
How can I run tests throuth selenium server but using provided driver?

### ISSUE THREAD

**Issue by jetfree7** [serenity-bdd/serenity-core#1347]
What I mean:
in serenity.properties we have:
`webdriver.driver=provided
webdriver.provided.type=mydriver
webdriver.provided.mydriver=com.readnaturally.qa.drivers.RniCustomDriverFactory
thucydides.driver.capabilities=mydriver`

in RniCustomDriverFactory.java I have:
` @Override
    public WebDriver newDriver() {
        String browserName = propertiesLoader.getProperty("webdriver.browser");
        EventFiringWebDriver driver = new EventFiringWebDriver(this.initializeWebDriver(browserName));
        driver.register(new CustomEventListener());
        return driver;
    }`

Due to personal reasons I need to run my test with selenium server. If I specify:
`webdriver.remote.url=http://localhost:4444/wd/hub
webdriver.remote.driver=chrome`
It will not use my DriverFactory.

The question is how to run it with selenium server but using my RniCustomDriverFactory?

Thanks!

**Comment by wakaleo** [comment]
Serenity cannot simultaneously configure your driver using the system properties (which needs to be done when the driver created), and let you create your own driver. If you use a custom driver it is up to you to configure everything.

**Comment by jetfree7** [comment]
Ok, another question then, how can I register AbstractWebDriverEventListener in the needed driver? Considering the fact that we use selenium server?

**Comment by wakaleo** [comment]
It might be easier to ask the question on https://serenity-bdd.rocket.chat

**Comment by wakaleo** [comment]
Without using custom drivers, you can access the driver instance with getDriver().getProxiedDriver()

**Comment by jetfree7** [comment]
ok, thanks
