### ISSUE TITLE
[Questions] How to switch between two webdriver while running

### ISSUE THREAD

**Issue by Hendrione** [serenity-bdd/serenity-core#1349]
Hi All,

I have problem while doing testing using Serenity. I need to test mobile apps. But after several steps, I need to access Web using Web Browser to continue the test. Is it possible to switch the webdriver while running the serenity? How can we do that? In my Example I need to switch from AndroidDriver to Chromedriver.

**Comment by wakaleo** [comment]
You can do this very easily with Screenplay. As this is a question and not a defect, could you post it on https://serenity-bdd.rocket.chat?

**Comment by Hendrione** [comment]
Oh yah I already tried using screenplay. Ok will post it there. Thanks
