### ISSUE TITLE
Parameterized test not showing up in serenity report

### ISSUE THREAD

**Issue by mleegwt** [serenity-bdd/serenity-core#1350]
Based on http://serenity-bdd.info/docs/serenity/#_using_test_data_from_csv_files I created an even simpler test. one without steps. This test succeeds, however it does not appear in the serenity report.

For reproduction I have added the test in the serenity-smoketests project (in https://github.com/mleegwt/serenity-core branch master) I updated it to build correctly. The tests were a bit out of date, still referring to browse-the-web instead of serenity-screenplay-webdriver. 
The tests that use the webdriver fail, since my installation is broken, no webdriver possibilites are enabled (context to reproduce what I see happening, I don't expect this to affect the result). According to the results in the comments below the surprising result is that when the webdriver can be used the parameterized tests work, but are in the report incorrectly. Details provided in the comments below.

**Comment by mleegwt** [comment]
![image](https://user-images.githubusercontent.com/7868114/44619387-de63cf80-a885-11e8-8e2b-dc436e37014e.png)

**Comment by mleegwt** [comment]
Interestingly the result is different when the Webtarget tests succeed, as illustrated by the screenshot below.

![image](https://user-images.githubusercontent.com/7868114/44630715-5f909480-a962-11e8-84a4-779de0b433b8.png)

The interesting thing is that while the tests marked "Test tag" succeeded according to the JUnit test report, according to this report the tests are still pending. The expected result is " Passing".

**Comment by wakaleo** [comment]
Fixed in 2.0.5
