### ISSUE TITLE
Screenshots in serenity report not coming when Provided driver is used 

### ISSUE THREAD

**Issue by nkhand** [serenity-bdd/serenity-core#1353]
Hi,

Trying to get screenshots in serenity reports with JBehave . 

Using my own WebdriverFactory , so implemented DriverSource as below ; 
public class LocalDriverFactory implements DriverSource {
		@Override
		public WebDriver newDriver() {
			return LocalDriverManager.getInstance().getDriver();
		}

		@Override
		public boolean takesScreenshots() {
			return true;
		}}

Serenity.properties has below values : 

webdriver.driver = provided
webdriver.provided.type = chrome
webdriver.provided.chrome = com.macys.mst.artemis.selenium.LocalDriverFactory
serenity.driver.capabilities = provided

In JBehave Step Definition , initialising Webdriver as below : 

	@Managed
	public WebDriver driver; 

With this implementation , driver is coming as null . 

serenity-core version : 1.8.21
serenity-jbehave : 1.35.0
serenity-maven-plugin : 1.8.21

**Comment by nkhand** [comment]
Yes . We use our own webdriver factory and webdriver manager ( to manage
threads) , and in the test get the current thread instance for webdriver .

But this way , we are not getting screenshots in the serenity reports.

Regards,

**Comment by nkhand** [comment]
Thanks for your reply.
How do I use serenity webdriver directly with JBehave step definition ,
which has annotations ( Given , when then ) . In these, no @Steps or @Test
annotations is used .

We have large test suites so don't want to change existing step definitions
much .
Tried just using @Managed for webdriver in one step definition , along with
webdriver.driver = chrome in serenity.properties , but this way driver is
coming as null .

Either way please suggest some solution . Thanks a lot for help

Regardz

**Comment by wakaleo** [comment]
`SerenityWebdriverManager.inThisTestThread().getCurrentDriver()`

**Comment by wakaleo** [comment]
Presuming answered.
