### ISSUE TITLE
Encountering task 'clean' not found while executing serenity tests

### ISSUE THREAD

**Issue by kahmad07** [serenity-bdd/serenity-core#1354]
Hi,

Encountering an exception Task 'clean' not found in root project when running test cases as part Jenkins pipeline.
This is the method which executes the test and it resides in a groovy file which is part of the pipeline.
The method is invoked from the repo which has all the test cases through the JenkinsFile.

```
def runSerenity(repo, repoBranch, credentialsId) {

		node('docker-maven-slave') {
			echo "-------------------------------"
			echo "Start serenity test cases"
			stage('Serenity')
			git url: "${repo}", repoBranch: "${repoBranch}", credentialsId: "${credentialsId}"

			def versionCache = env.JAVA_VERSION
			def javaHomeCache = env.JAVA_HOME

			env.JAVA_VERSION = '1.8.0'
			node('docker-gradle-slave') {
				sh '''
				. /etc/profile.d/jenkins.sh
		    	 	gradle clean test aggregate
		    	 	'''
			}
			env.JAVA_VERSION = versionCache
			env.JAVA_HOME = javaHomeCache

			publishHTML(target: [
			reportName: 'Serenity Report',
			reportDir: 'target/site/serenity',
			reportFiles: 'index.html',
			keepAll: true,
			alwaysLinkToLastBuild: true,
			allowMissing: false
			])
		}
echo "-------------------------------"
echo "End serenity test cases"
}
return this 
```

The exception which is encountered is 

```
+ gradle clean test aggregate

FAILURE: Build failed with an exception.

* What went wrong:
Task 'clean' not found in root project
```

All serenity dependencies required are in place in build.gradle file. 
Test cases run fine on my local along with the proper report.

**Comment by wakaleo** [comment]
This is a Jenkins/Gradle config question rather than a defect, so Github is probably not the best place to get project-specific help - you can ask for some help form the Serenity community at https://serenity-bdd.rocket.chat or raise a ticket with one of our commercial support packages (https://johnfergusonsmart.com/serenity-bdd-mentoring/#support).

**Comment by wakaleo** [comment]
Closing as not a Serenity defect.
