### ISSUE TITLE
scalatest exception leads to UnrecognisedException on the Serenity report

### ISSUE THREAD

**Issue by thiagoampj** [serenity-bdd/serenity-core#1356]
Hi, 
We can't use `scalatest` Matchers and `serenity` to have nice serenity reports 
scalatest `org.scalatest.Matchers` throws `org.scalatest.exceptions.TestFailedException` 
This exception does not have constructors  expected by Serenity code in :
https://github.com/serenity-bdd/serenity-core/blob/f8ef5b90b1c6ef04bd876a6a59fd996bcc2bb228/serenity-model/src/main/java/net/thucydides/core/model/stacktrace/FailureCause.java#L164

`FailureCause` contains the `originalCause` which could be used instead of re-instantiate the Exception. Is there any reason for throwing UnrecognisedException?
With net.serenitybdd.core.exceptions.UnrecognisedException, the report doesn't show anything significant, even the exception message is lost.

I moved back to use Junit assertions, but would be nice to have that support.
Thanks

**Comment by wakaleo** [comment]
Your best bet would be to propose a PR to cater for the constructors you need, as there are currently no sample tests in Scalia and it would be a fair bit of work to add them.

**Comment by thiagoampj** [comment]
Hi Wakaleo, 
For now I replaced all the scalatest assertions to JUnit assertions with hamcrest. 
scalatest `TestFailedException` has a constructor that could be used, I will propose a PR asap. 
Thanks

**Comment by wakaleo** [comment]
Thanks

**Comment by patrickvkb** [comment]
Hi, have any steps been taken with respect to this enhancement request?
