### ISSUE TITLE
Screenshot are not capturing in serenity with Jbehave framework.

### ISSUE THREAD

**Issue by ganeshraja88** [serenity-bdd/serenity-core#1359]
Hi, I have created scripts using serenity with Jbehave framework. Scripts are running successfully but screenshots are not captured post execution.  I have mentioned the screen capturing in serenity property file. So can you please anyone check and let me know the solution to capture screenshots.
Thanks in advance.

serenity.take.screenshots.for.tasks=FOR_EACH_ACTION
serenity.take.screenshots.for.tasks=BEFORE_AND_AFTER_EACH_STEP
OR
serenity.take.screenshots=FOR_EACH_ACTION
serenity.take.screenshots=BEFORE_AND_AFTER_EACH_STEP

**Comment by wakaleo** [comment]
Could be a driver issue. Can you provide a sample project that reproduces the issue?
