### ISSUE TITLE
not able to access methods related to appium

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#1361]
I've tried below 2 ways but can't access the appium java client methods directly

`1. ((WebDriverFacade)getDriver()).getProxiedDriver().resetApp();
`
it throws error cannot resolve method resetApp

`2. getDriver().resetApp() doesn't work either
`
Please clarify if something has changed with serenity framework recently ?

**Comment by wakaleo** [comment]
What class does resetApp() come from?

**Comment by vikramvi** [comment]
It comes from `public interface InteractsWithApps`

https://appium.github.io/java-client/io/appium/java_client/InteractsWithApps.html#resetApp--

```
All Known Implementing Classes:
AndroidDriver, AppiumDriver, IOSDriver, WindowsDriver
```

**Comment by wakaleo** [comment]
Have you tried casting the proxied driver to InteractsWithApps?

**Comment by vikramvi** [comment]
I tried below but didn't work 

`        (InteractsWithApps)((WebDriverFacade)getDriver()).getProxiedDriver().resetApp()
`

**Comment by wakaleo** [comment]
I'm not sure, nothing much changes in the Appium code except updates to the Appium version - maybe the API has changed?

**Comment by vikramvi** [comment]
My understanding was if I set `webdriver.driver = appium` then driver type should be  `AppiumDriver`. 
If this is correct, then I think typecast is not needed. Please clarify if my understanding is wrong here

**Comment by wakaleo** [comment]
Have a look at the `AppiumDriverProvider` class. It creates either an `AndroidDriver` or an `IOSDriver` depending on the value of `appium.platformName`.

**Comment by pisarenco92** [comment]
@vikramvi Could you try `(AppiumDriver<MobileElement>) ((WebDriverFacade) getDriver()).getProxiedDriver().resetApp();`

**Comment by vikramvi** [comment]
@wakaleo @pisarenco92 sorry my mistake, I could get it working as below

`((AppiumDriver)((WebDriverFacade) getDriver()).getProxiedDriver()).terminateApp("org.wordpress.android");`

**Comment by baligit** [comment]
Working:
 `((WebDriverFacade) getDriver()).getCapabilities().getCapability("platformName") `
output: iOS
