### ISSUE TITLE
Need to set ExperimentalOption outside "prefs"

### ISSUE THREAD

**Issue by VPazzini** [serenity-bdd/serenity-core#1363]
Currently all the given chrome_preferences are added to "prefs", but I need to set a ExperimentalOption outside "prefs".
This is the current implementation:
`
private void addPreferencesTo(ChromeOptions options) {
        Map<String,Object> chromePreferences =  ChromePreferences.startingWith("chrome_preferences.").from(environmentVariables);
        if (!chromePreferences.isEmpty()) {
            options.setExperimentalOption("prefs", chromePreferences);
        }
    }
`

Would it be possible to add something like this?

`
    private void addExperimentalOptionsTo(ChromeOptions option) {
        Map<String, Object> chrome_experimental_options = ChromePreferences.startingWith("chrome_experimental_options.").from(environmentVariables);
        if (!chrome_experimental_options.isEmpty()) {
            for (String key : chrome_experimental_options.keySet()) {
                options.setExperimentalOption(key, chrome_experimental_options.get(key));
            }
        }
    }
`

**Comment by wakaleo** [comment]
Sure, please propose a PR with some tests and I will take a look.

**Comment by VPazzini** [comment]
hey @wakaleo, would it be possible to make a new release ? Thanks

**Comment by wakaleo** [comment]
Released in 1.9.42
