### ISSUE TITLE
net.thucydides.core.webdriver.exceptions.ElementShouldBeEnabledException: Expected enabled element was not enabled

### ISSUE THREAD

**Issue by di14sha** [serenity-bdd/serenity-core#1366]
net.thucydides.core.webdriver.exceptions.ElementShouldBeEnabledException: Expected enabled element was not enabled

**Comment by wakaleo** [comment]
That means you are trying to interact with a disabled element.

**Comment by di14sha** [comment]
how to enable it?
Am new to serenity
Can you please help me out?

**Comment by wakaleo** [comment]
It’s not a Serenity defect so it would be better to ask on the community chat at https://serenity-bdd.rocket.chat and close it here.
