### ISSUE TITLE
Adding jbehave meta tags on serenity reports

### ISSUE THREAD

**Issue by VPazzini** [serenity-bdd/serenity-core#1368]
Is there a way to add JBehave meta tags on serenity reports?

**Comment by wakaleo** [comment]
Yes, just add the tags to the story files and they will appear.

**Comment by VPazzini** [comment]
Where? I can not find them

**Comment by wakaleo** [comment]
```
Meta:
@tag capability:a capability

Scenario: A scenario that works
Meta:
@tags domain:a domain, iteration: iteration 1, security
@end-to-end
Given I have an implemented JBehave scenario
And the scenario works
When I run the scenario
Then I should get a successful result

```

**Comment by VPazzini** [comment]
I meant on the reports. Do the tags need to be @tag or would the @end-to-end also appear on the report?

**Comment by wakaleo** [comment]
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/55986/45326630-4d127f80-b54c-11e8-961d-408408975436.png">

**Comment by VPazzini** [comment]
ok, I understand now, thanks. I wanted to all my meta tags to be display including the ones that do not have the @tag(s)
