### ISSUE TITLE
Better log message in html reports

### ISSUE THREAD

**Issue by Micky002** [serenity-bdd/serenity-core#1369]
When there is a bug on the page and an element doesn't become visible i get an error message like:
`Expected enabled element was not enabled` in the html reports.

This comes when i use `WebElementFacade.waitUntilClickable`.

Is there a way to get a message like:
`Timed out after 5000 milliseconds: Proxy element for: DefaultElementLocator 'By.id: xyz' to be clickable` to see which element was not clickable.

Or must i do a PR to get this functionality since it is not possible.

**Comment by wakaleo** [comment]
PRs are welcome but you may find (like I did) that identifying an element in a readable way is virtually impossible in a general case (Serenty already does what it can). Basically, once you have a web element, you cannot know how it was located.

**Comment by Micky002** [comment]
When you have a webelement and call the toString method then you get a nice string which shows the original locating method and the used value (`By.id: xyz`)

**Comment by wakaleo** [comment]
In that case, PR away! This wasn’t the general behaviour I observed, so it may have changed or be driver-dependent

**Comment by Micky002** [comment]
Ok i will test if this is driver dependent before.

**Comment by wakaleo** [comment]
I believe this is implemented ins 2.0.42
