### ISSUE TITLE
Split the library in core and classic

### ISSUE THREAD

**Issue by verhagen** [serenity-bdd/serenity-core#137]
**Why:** Making it easier for new users to understand, what is new and what is there for backwards compatibility

At the moment I see that there are new package names with `net.serenitybdd` and the classic package name `net.thucydides`. These _classic_ packages are there, probably for backwards compatibility. To make it, as easy as possible, for users of older version, to move to the latest version.

For new users this is as long as all these _old_ and _new_ package names are used within the same jar, quite confusing. Especially as not all classes / annotations have a new  counterpart, in `net.serenitybdd`. Maybe for a reason, as the concepts have changed / are no longer used / needed. But as long as they are in the same jar, it is not clear how it should be interpreted.

My suggestion would be to split the older stuff `net.thucydides` into a separate library something like `serenity-classic.jar`. So users just starting with Serenity-BDD, only need the `serenity-core.jar` dependency. And the loyal users from the start can include the `serenity-classic.jar` in their dependencies.

**Comment by RobWin** [comment]
+1

**Comment by fokion** [comment]
:+1:

**Comment by mikezx6r** [comment]
John can confirm/deny my analysis. I was contributing a bit to the project around the time the rename took place, so this is my understanding of the state of things.

Your interpretation doesn't tell the whole story.

When Thucydides was renamed, some effort was made to move code to the new package name. Yes, it's as easy as 'IntelliJ, move this package and publish' from a coding perspective,
BUT this would require releasing a new version of Serenity, and anyone that wants new features would have to migrate all their code to the new package names. That's a lot of overhead, for no return, and an unpleasant experience.

Some items were migrated as they were internal. In other cases, new implementation was created, and the existing Thucydides implementation was Deprecated. And in others, existing functionality remained in the Thucydides package, and new functionality is implemented in the Serenity packages.

There are 2 approaches to writing tests, and both are valid. PageObject and Actor. So I don't think there's a lot of code that's there for 'backwards compatibility' that isn't marked Deprecated.

If there is, then I agree that having a 'serenity-legacy' package that contains all of that would be beneficial.

Do you have a few examples of what you refer to?

**Comment by wakaleo** [comment]
Spot on Mike. It's a lot of work for not much benefit, as you would always need both Jar files anyway. Splitting out the Webdriver code would have more tangible benefit, but even that is non-trivial.

**Comment by wakaleo** [comment]
Not worth the ROI at this stage.
