### ISSUE TITLE
ComplainWith is not working with seeThatResponse consequence

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1370]
I'm using serenity screenplay rest, and I notice that using complain with is not working with serenity seeThatResponse consequence, looks like the complainwith method is not invoked after a failure serenity doesn't use my own exception or message.

**Comment by wakaleo** [comment]
Thanks for noticing this. Could you propose a PR?

**Comment by ricardorlg** [comment]
sure, I will upload a PR with also some changes to Rest interactions in order to allow logging on execution. I have another question, askfor call doesn't add subject value to step name in the report, this is because is called outside  Consequence wrapper?

**Comment by wakaleo** [comment]
Could you give an example of what you mean?

**Comment by wakaleo** [comment]
Yes, I think, since the question is getting invoked inside the setup and before the reporting has started.
