### ISSUE TITLE
I am getting ProvisionException while running serenity BDD/Cucumber Appium based project. Anyone please help me with this below wired error:

### ISSUE THREAD

**Issue by PratapSingh09** [serenity-bdd/serenity-core#1376]
Running com.itv.android.Run
[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   loglevel: info
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> GET /wd/hub/status {}
[HTTP] <-- GET /wd/hub/status 200 879 ms - 72 
[HTTP] --> GET /wd/hub/status {}
[HTTP] <-- GET /wd/hub/status 200 876 ms - 72 

0 Scenarios
0 Steps
0m0.000s

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 17.376 sec <<< FAILURE! - in com.itv.android.Run
com.itv.android.Run  Time elapsed: 17.138 sec  <<< ERROR!
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: No enum constant net.thucydides.core.logging.LoggingLevel.VERB
  at net.thucydides.core.steps.ConsoleLoggingListener.<init>(ConsoleLoggingListener.java:200)
  while locating net.thucydides.core.steps.ConsoleLoggingListener
  at net.thucydides.core.guice.ThucydidesModule.configure(ThucydidesModule.java:67)
  while locating net.thucydides.core.steps.StepListener annotated with interface net.thucydides.core.logging.ThucydidesLogging

1 error
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1009)

Run class:

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features = {"src/test/resources/features/AndroidApp"})
public class Run {

  @BeforeClass
  public static void startAppium() {
    startAppiumServer();
  }
  @AfterClass
  public static void stopAppium() {
    stopAppiumServer();
  }
}
hierarichy images for my feature file:
![image](https://user-images.githubusercontent.com/17722170/45598890-e2958f80-b9e2-11e8-88ed-3e852242fb32.png)

**Comment by wakaleo** [comment]
Are you still getting this? Looks like a dependency conflict.

**Comment by napindc** [comment]
i am still getting same  issue
