### ISSUE TITLE
Screenshot in Firefox

### ISSUE THREAD

**Issue by hariharanravichandran** [serenity-bdd/serenity-core#1377]
Hi All,

Our web Application has many page with 2 to 4 Jsp(frames) embedded in it. When we run our test in chrome. we are getting the screenshot of whole browser window. Incase of Firefox, the Jsp (or frame) which is being focused is captured in the screenshot.

Please help us to get the full screenshot in the Report.

**Comment by wakaleo** [comment]
This is driver specific behaviour (unrelated to Serenity or even Selenium), so we can’t do much about this at the moment.
