### ISSUE TITLE
Test method tags not working in parameterized test class with JUnit

### ISSUE THREAD

**Issue by heikikiisler** [serenity-bdd/serenity-core#1378]
In an example test class:
```
import net.serenitybdd.junit.runners.SerenityParameterizedRunner;
import net.thucydides.core.annotations.WithTag;
import net.thucydides.junit.annotations.TestData;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@RunWith(SerenityParameterizedRunner.class)
public class TagsTest {

    @TestData
    public static Collection<Object[]> testData() {
        List<Object[]> list = new ArrayList<>();
        list.add(new String[]{""});
        return list;
    }

    public TagsTest(String a) {
    }

    @Test
    @WithTag("a")
    public void a() {
        System.out.println("a");
    }

    @Test
    @WithTag("b")
    public void b() {
        System.out.println("b");
    }

    @Test
    @WithTag("c")
    public void c() {
        System.out.println("c");
    }

}
```
When running tests with `-Dtags="a"`, test `a()` gets run normally but when using  `-Dtags="b"` or  `-Dtags="c"`, no tests get run. In fact it seems like only the test with the alphabetically first method name can be run.

In a similar non-parameterized class using `@RunWith(SerenityRunner.class)` instead of `@RunWith(SerenityParameterizedRunner.class)`, the problem does not exist and all tests can be run normally.

Tested with Serenity JUnit versions 1.9.25 and 1.9.45

Have the tags been used incorrectly or is this a bug? Any kind of help would be appreciated.

**Comment by wakaleo** [comment]
Thanks for the connection, I believe they are effectively related. Typically a parameterised test in JUnit only has one method, which may be why this has not surfaced before. 

Not sure when we will get to this. If you would like to try a fix yourself and do a PR, the ParameterizedTestRunner would be the best place to start - it may just be some logic that is missing from the normal JUnitRunner class.

**Comment by heikikiisler** [comment]
I did not see a simple fix after a quick look and just used multiple classes with inheritance as a workaround.

Example classes:

```
@RunWith(SerenityParameterizedRunner.class)
public abstract class TagsTest {

    @TestData
    public static Collection<Object[]> testData() {
        List<Object[]> list = new ArrayList<>();
        list.add(new String[]{""});
        return list;
    }

    TagsTest(String a) {
    }

    // Other shared logic

}
```
```
@WithTag("a")
public class TestA extends TagsTest {

    public TestA(String a) {
        super(a);
    }

    @Test
    public void a() {
        System.out.println("a");
    }

}
```

I hope this can help others with the same problem.

**Comment by heikikiisler** [comment]
Ended up fixing this after all with #1614.
