### ISSUE TITLE
Not able to run Serenity tests in parallel batches

### ISSUE THREAD

**Issue by KP2205** [serenity-bdd/serenity-core#1382]
How do we know if serenity.batch.size/count properties are being honored or not because I see only one chrome instance getting launched and test cases running one after another.

My understanding is that if it is running in parallel then at least two chrome instance should launch and console logs should also show that.

I am using below lines in serenity.properties file.
`serenity.batch.count=1
serenity.batch.size=1
serenity.batch.number=1`

**Comment by wakaleo** [comment]
Serenity batches do not run tests in parallel, they run a nominated subset of a test suite.

**Comment by KP2205** [comment]
Hi, my question is more basic, I want to know if serenity is honoring my batch settings (batch size, batch number) at all. I don't see any logs in console showing that, e.g. "....running batch x..." sort of things. All of my test-cases are run one-after another no matter what batch settings I chose.

**Comment by nbarrett** [comment]
Hi @KP2205 - One thing that is important to realise is that batching:
a) only works when you run the tests from maven, not run run via a junit runner directly, say from the IDE
b) only currently works for Junit tests (e.g. those run with `@RunWith(SerenityRunner.class)`). Cucumber batching will be available on the next release of Serenity Cucumber v1.9.15 and should work according to [the documentation](https://serenity-bdd.github.io/theserenitybook/latest/serenity-parallel.html))

**Comment by KP2205** [comment]
Hi @nbarrett 
Thanks for the information.
I am a newbie so could you please help me out what command should I run to test it via maven?

**Comment by nbarrett** [comment]
Hey @KP2205 - in its simplest form this would be `mvn verify` from the root of your project where your pom.xml is, but there are various other VM arguments that can also be supplied such as tagging as described in the [reference manual](http://thucydides.info/docs/serenity-staging/#_junit)
