### ISSUE TITLE
IFrame value is persisted across two test runs

### ISSUE THREAD

**Issue by a-set** [serenity-bdd/serenity-core#1383]
If there are two test runs and driver instance is destroyed at the end of the first one, the iFrame value should also be cleared out.

**### Example Scenario**

**Test A**
     Task A -> works with element on Frame A
     Task B  -> works with element on default content
     Task C  -> works with element on Frame A

**Test B**
      Task A -> works with element on Frame A
      Task B  -> works with element on default content
      Task C  -> works with element on default content

**Test C**
      Task A -> works with element on Frame A

Output
Test A -> Pass
Test B  -> Task A - fails ( Element not found)
Test C   -> Pass

I am running this in whatever mode destroys the driver instance between individual test runs ( I think it's the uniquesession=false) 

**Likely reason for failure**
At the end of Test A, the _currentIFrame_ value in _IFrameSwitcher_ is not cleared out and has Frame A as it's value. 
When the same Task A is run in Test B. The  _switchToFrame_ method thinks that Frame A is already selected. Since it's a new driver instance at this point, No command has been sent out to the driver to actually switch the frame. It works in Test C because Test B leaves the currentIFrame value as default content. 

I work around this issue by adding an extra TASK 0 at the beginnning of every test to check the banner, which causes the Frame to switch back to default content

**Comment by nbarrett** [comment]
Hi @a-set - could you create a branch with a unit test reproducing your problem? There are similar examples that feature targets in iframes in the serenity screenplay webdriver unit test e.g.:  [net.serenitybdd.screenplay.webtests.integration.WhenDanaBrowsesTheWeb](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay-webdriver/src/test/java/net/serenitybdd/screenplay/webtests/integration/WhenDanaBrowsesTheWeb.java#L215)
