### ISSUE TITLE
No data in report running specific scenario through cucumberoptions

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1384]
Hi, not sure if this is a bug or maybe a misunderstood of mine,  but when in my runner I specify a scenario to run no report is being generated, for example:

`@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
   features = {"src/test/resources/features/test/test.feature:10"},
   plugin = {"pretty"},
   strict = true,
   monochrome = true
)
public class DefinitionTestSuite{}`

**Comment by nbarrett** [comment]
"src/test/resources/features/test/test.feature:10" looks like the wrong syntax for specifying a feature. What happens if you remove :10 from the end?

**Comment by ricardorlg** [comment]
if I remove the :10 all scenarios will run, I just want to run a specific one using cucumber options, It runs without a problem but the report is empty.

**Comment by nbarrett** [comment]
How about using [tags](https://docs.cucumber.io/cucumber/api/#tags)?

**Comment by ricardorlg** [comment]
Yes Its an option, there are other ways, I just report this to know if maybe is a bug, sometimes when I'm implementing some scenarios I just want to run one of them without the need to run all features, and see in report if something was wrong or to see how titles for screenplay actions looks.

**Comment by wakaleo** [comment]
I don't think "src/test/resources/features/test/test.feature:10" is a valid syntax in the Cucumber runner.
