### ISSUE TITLE
Can Serenity reports be all in same (non-English) language ?

### ISSUE THREAD

**Issue by Dapangma** [serenity-bdd/serenity-core#1388]
Hi,

I have my tests and feature files in French and it works well. But I'd like to make a step further. Reports are generated in a mix of English for template fields and French for test reports, like Capabilities : Consulter
Is it possible to avoid Frenglish and have pure French (or other language) reports ? I did not see anything about that so I suppose it is not possible for now. This would be quite handy though.

Thanks in advance.

**Comment by wakaleo** [comment]
That would be a good idea. You can override words like Capability and Feature by overriding the requirement types (though it probably would not be able to get the plural forms correct for some words), but at the moment the templates are English only. It is mostly just free marker templates, but there is no multi-language support at the moment. Happy to consider PRs though.
