### ISSUE TITLE
Serenity + Appium latest on iOS real device is still very slow.

### ISSUE THREAD

**Issue by mihaiserdeanyopeso** [serenity-bdd/serenity-core#1392]
Serenity + Appium latest on iOS real device is still very slow. Can you give us some hints on how to make it run faster? We have fluent Waits and are not using hardcoded timeouts. 
We have latest Serenity, latest Appium, iPhone 8 connected via USB.

On Android everything works fast.

**Comment by wakaleo** [comment]
I think this is unrelated to Serenity, as last time I checked Appium with IOS limits the number of queries, which makes the testing very slow. Maybe ask the question on https://serenity-bdd.rocket.chat.
