### ISSUE TITLE
Gradle plugin class SerenityPlugin is not thread-safe

### ISSUE THREAD

**Issue by ariksher-nex** [serenity-bdd/serenity-core#1396]
I have project with 2 modules, that each uses serenity,
when I run `gradle clean --parallel` I see that 2 modules get mixed:

> Execution failed for task ':**module1**:clearReports'
> java.io.IOException: Unable to delete directory /root/**module2**/target/site/serenity

I looked at code and seems that in order to fix it need to remove the following data member:
    **Path reportDirectory
    Path historyDirectory**
and make them local variables to the method named apply.

**Comment by wakaleo** [comment]
Could you propose a PR?

**Comment by ariksher-nex** [comment]
> Could you propose a PR?

will do (its my first one here).
:-)

**Comment by wakaleo** [comment]
Fixed in 2.0.5

**Comment by ariksher-nex** [comment]
sorry for the compilation problem. 
please try PR #1409 .
