### ISSUE TITLE
Running interception of tests based on multiple tags

### ISSUE THREAD

**Issue by BushnevYuri** [serenity-bdd/serenity-core#1398]
Hello,

I know that Cucumber+Serenity allows running tests in a very flexible way. For example,
`mvn clean verify -Dcucumber.options="--tags ~@color=green --tags @color=blue"`
will allow running all blue but not green tests. 

Is there anything similar if I use Serenity via classic tags (net.thucydides.core.annotations.WithTagValuesOf)? 

For example, if I will run it like this:
`-Dtest.env=Development -Dtags='ProdCompatible:true'`
then it will run all tests with Development tag and ProdCompatible:true tag as well while I would like to run the only interception. 

Maybe somebody was already looking into that? Will be very glad if there are any suggestions for some obvious way or workaround. 

Sorry, didn't find the better community place to ask the question.

**Comment by wakaleo** [comment]
The usual place to ask questions is https://serenity-bdd.rocket.chat. No, there is no equivalent of the Cucumber tag DSL in other implementations.
