### ISSUE TITLE
ignored tag doesn't work when a scenario has two examples

### ISSUE THREAD

**Issue by foven** [serenity-bdd/serenity-core#1402]
HI, I have a scenario has two examples, when i set a ignored (or pending) tag to it and run, the second example would keep running and this caused test failed. except i comment the second example, does there have any other ways to resolve this problem?
![image](https://user-images.githubusercontent.com/5477686/46776672-42abf700-cd3f-11e8-848a-fc72cb7a0313.png)
![image](https://user-images.githubusercontent.com/5477686/46776745-8e5ea080-cd3f-11e8-9f99-dc29a516dd85.png)

OS:win7
serenity version: 1.9.36

Thanks in advance.

**Comment by wakaleo** [comment]
(Not so much #wontfix as #not-possible-with-the-current-Cucumber-APIs)

**Comment by foven** [comment]
hi Wakaleo, thank you for your answers first. and sorry for my bad description,
i met two problem when i ran my tests.
1.the first problem is if i set ignored or pending tag to the scenario that has two examples. like following:
@ignored
scenario outline: xxx
given i have two test case that named "test"
when xx
then xx

example:
 |test|
|first test|
|second test|

when i run this scenario, the first will ignored, but the second one will keep running.

2.the second problem is even though I set the ignored or pending tag, the scenario still failed then cause maven build failure. I guess your solution is answer this problem. 
Actually i have used serenity @step libraries, and tried to use pending too, but it doesn't work.
![image](https://user-images.githubusercontent.com/5477686/46856019-f395bd00-ce37-11e8-9a34-099be9b5ef75.png)
![image](https://user-images.githubusercontent.com/5477686/46856054-05776000-ce38-11e8-890c-243fffac1d84.png)
