### ISSUE TITLE
Broken Links in Serenity Report when Underscore is Used in Scenario Title

### ISSUE THREAD

**Issue by Warren25** [serenity-bdd/serenity-core#1403]
Serenity-Core Version: 2.0.4
Serenity-Cucumber Version: 1.9.14

In my latest serenity report, I am not able to view the details of any scenario that has an underscore in the scenario title.

Example Scenario Title: View Test Page_Metrics

**Comment by Warren25** [comment]
Example of broken link:

![image](https://user-images.githubusercontent.com/17141304/46811337-8f440200-cd40-11e8-90eb-c84001bf6fde.png)

**Comment by wakaleo** [comment]
Current workaround - avoid using underscores

**Comment by wakaleo** [comment]
Fixed in 2.0.5
