### ISSUE TITLE
Unable to get SelectedVisibleTextValue for disabled dropdown

### ISSUE THREAD

**Issue by thomastan1234** [serenity-bdd/serenity-core#1404]
[Serenity 1.9.36] When using SelectedVisibleTextValue, the code checks that the element needs to be enabled. Hence for disabled dropdown, it returns the below exception.

net.thucydides.core.webdriver.exceptions.ElementShouldBeEnabledException: Expected enabled element was not enabled

**Comment by wakaleo** [comment]
Would it work if the element is not enabled?

**Comment by thomastan1234** [comment]
It works if the element is enabled.

**Comment by wakaleo** [comment]
So the check that the element is valid is needed then?

**Comment by thomastan1234** [comment]
The check that the element is enabled shouldn’t be needed. Reason being there are disabled dropdown with selected value.

**Comment by wakaleo** [comment]
Or will the select work even with a disabled element?
