### ISSUE TITLE
TouchAction cannot be applied to (int, int)

### ISSUE THREAD

**Issue by sampadrout** [serenity-bdd/serenity-core#1406]
When i am trying to code a swipe, following code says "press (io.appium.java_client.touch.offset.Point Option) in TouchAction cannot be applied to (int, int)". Any solution will be highly apriciated.
        TouchAction swipe = new TouchAction(getDriver);
        swipe.press(1030, 995);
        swipe.moveTo(19, 991)
        swipe.release();
        swipe.perform();

**Comment by wakaleo** [comment]
This is an Appium question about an Appium class - you will probably get a better response in the Appium community or maybe on https://serenity-bdd.rocket.chat. 

Closing as unrelated to the Serenity code base.
