### ISSUE TITLE
On which branch is development done?

### ISSUE THREAD

**Issue by verhagen** [serenity-bdd/serenity-core#141]
What is in branch _master_ ? And what is in branch _version-1.1-dev_ ?

My idea was that development for version 1.1 would be taking place in _version-1.1-dev_. But seams the latest commits are done in _master_ and it also contains all kind of changes for the next 1.1 release.

Can someone explain these branches and where they are used for ?

**Comment by wakaleo** [comment]
All work is done on master at this stage.

On 8 October 2015 at 00:59, Tjeerd Verhagen <notifications@github.com>
wrote:

> What is in branch *master* ? And what is in branch *version-1.1-dev* ?
>
> My idea was that development for version 1.1 would be taking place in
> *version-1.1-dev*. But seams the latest commits are done in *master* and
> it also contains all kind of changes for the next 1.1 release.
>
> Can someone explain these branches and where they are used for ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/141>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by verhagen** [comment]
Checking the [branches](https://github.com/serenity-bdd/serenity-core/branches) it is clear that master is the main branch, as it contains the last changes.
Maybe even easier seen through the [Graph - network](https://github.com/serenity-bdd/serenity-core/network).
Thx for the quick reply!
