### ISSUE TITLE
Screenshot for desktop application

### ISSUE THREAD

**Issue by sumit-global** [serenity-bdd/serenity-core#1410]
Hi,

I am using serenity report for my desktop application(mainframe), I need to take screenshot for every step is performed, for web we can use serenity.properties to manage screenshot but of this kind of requirements what will be the best way to embed desktop screenshot in serenity report.

**Comment by wakaleo** [comment]
Screenshots are only supported for WebDriver, but if you take the screenshots manually, you could attach them as evidence to your test report like this:

```
        Serenity.recordReportData()
                .withTitle("My mainframe screenshot")
                .downloadable()
                .asEvidence()
                .fromFile(Paths.get("myscreenshot.png"));
```

**Comment by sumit-global** [comment]
thanks for swift response @wakaleo 
I am not using Steps of serenity, could you please help in where I need to call above method, after every step?

Thanks in advance.

**Comment by wakaleo** [comment]
The best way would be to wrap your existing code in a Serenity step method (just as a wrapper for your actual code

**Comment by wakaleo** [comment]
Presuming answered.
