### ISSUE TITLE
Serenity Rest Assured not printing the rest query in the index.html report

### ISSUE THREAD

**Issue by silviya123** [serenity-bdd/serenity-core#1414]
Version tested: 
serenity Core Version=2.0.7 
serenity Rest Version=2.0.7 
serenity Cucumber Version=1.9.18

Test scenario:

Post a SOAP request.//with proxy
given().headers(headermap).proxy("sample-xxxxxx.test.xxxxx.com.au", 8080).when().body(payLoadWithRequestData).post(endPointUrl);

The request is getting posted and getting the correct response. But the RestQuery is not printed in the index.html.

I checked the same for another request which doesn't have proxy and the RestQuery is present in the index.html with all the details.(Header,request,respone,cookies)

Could you please assist.

**Comment by wakaleo** [comment]
I can't reproduce this; could you be more precise about what you mean by "the RestQuery is not printed in the index.html"?

**Comment by silviya123** [comment]
Hi John,

I mean the Rest Query is not displayed in the generated Serenity report. 
And this is occurring only when a request has proxy  added to it.

Thanks
Silviya

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces the issue?

**Comment by silviya123** [comment]
[mp-001_api_test.zip](https://github.com/serenity-bdd/serenity-core/files/2485973/mp-001_api_test.zip)

Attached the project, along with the target folder

**Comment by silviya123** [comment]
Hi John,

Could you please help on this.

Thanks
Silviya

**Comment by wakaleo** [comment]
It is on the backlog, and will most likely get looked at eventually. But since this is an open source project, there is no SLA or guarantee of response. If this is an urgent problem, you may want to consider some of the commercial support options: https://johnfergusonsmart.com/serenity-bdd-mentoring/#support

**Comment by silviya123** [comment]
Ok Thanks John. As a workaround we are now using recordReportData() and it working as expected.

Thanks
Silviya

**Comment by wakaleo** [comment]
@silviya123 That is a good work-around. I had a quick look and it looks like it is not a trivial fix, so may take some time.

**Comment by karthikmkulkarni** [comment]
@wakaleo is this fix done ? if so can you please help me the serenity version to be used for the same? Thanks in advance!
@silviya123

**Comment by wakaleo** [comment]
I don't think any work has been done on this.
