### ISSUE TITLE
NoSuchElementException is not catched when isPresent() is called

### ISSUE THREAD

**Issue by vzakharchuk** [serenity-bdd/serenity-core#1415]
Hey there, 

The code below works fine, it catches the exception and returns boolean.
`element(LOCATOR).isPresent()`.

Next example will fail with NoSuchElementException in case child element is absent in DOM. 
`element(PARENT_ELEMENT_LOCATOR).then(CHILD_ELEMENT_LOCATOR).isPresent()`. 

Despite the fact that NotFoundException is catched in `isPresent()`.
Could you please throw some light on it?

**Comment by wakaleo** [comment]
If element(PARENT_ELEMENT_LOCATOR) is not present than this will throw an exception.
