### ISSUE TITLE
[serenity-report-resources] There is a bug on the home.ftl report template 

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [serenity-bdd/serenity-core#1417]
There is a bug on the report template that is throwing an error on the console:
![image](https://user-images.githubusercontent.com/39963236/47249344-c8d3d780-d3e8-11e8-9095-645858625c73.png)

Here is the cause:
https://github.com/serenity-bdd/serenity-core/blob/486cfab82422ae3bdb05bd5fe1a4782df016bc83/serenity-report-resources/src/main/resources/freemarker/home.ftl#L74

**Comment by wakaleo** [comment]
Thanks for noticing this. Would you like to propose a PR?

**Comment by otoniel-isidoro-sofist** [comment]
#1418
