### ISSUE TITLE
Set Manual Test Result in feature files?

### ISSUE THREAD

**Issue by stoconnor** [serenity-bdd/serenity-core#1422]
With the recent commit, we now have a way to set Test Results for Manual tests.
"Initial version of results for `@Manual` tests - experimental"

Is it possible to set these test results in Gherkin Feature files? Have tried @Manual(result = TestResult.SUCCESS) but didn't work.

Also, is `@manual` with lowercase still used? I upgraded to the latest Serenity recently and having `@manual` at the top of a feature file caused all Steps in all features to be Ignored. Replaced it with `@Manual` and works as expected.

**Comment by wakaleo** [comment]
It's experimental, not for general use yet.

**Comment by stoconnor** [comment]
No problem, I will close this issue and keep an eye out for further updates 👍
