### ISSUE TITLE
Running Cucumber scenarios in parallel with Serenity JUnit in Gradle project 

### ISSUE THREAD

**Issue by sheerintaj** [serenity-bdd/serenity-core#1423]
I am using serenity framework with combination of gradle & Junit to run the test.I am searching for a way to run the scenarios in parallel using gradle, but i always find parallel execution using maven.Can anyone tell how to run cucumber scenarios in parallel using Gradle,JUnit & Serenity.

**Comment by wakaleo** [comment]
This is a question, not a defect - could you ask it on https://serenity-bdd.rocket.chat?
