### ISSUE TITLE
Timing information seems to be missing on Serenity 2.x reporting

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1425]
Firstly thanks for latest reporting upgrade 👍 - looking very swish.

A fix for this may well be in the pipeline already, but it seems that summary timing information is missing on the new reports. For instance on the old version we see a **_Test Result Summary_** table at every drill-down level:

![image](https://user-images.githubusercontent.com/626941/47507418-111c4b00-d86a-11e8-8989-2c6b41151727.png)

However on the new reporting (I just upgraded to 2.0.10) there doesn't seem to be any summary timing available:

![image](https://user-images.githubusercontent.com/626941/47507487-2db88300-d86a-11e8-8bd0-8e8a2997b910.png)

This timing information is really handy so would be great to get this retrofitted please?

**Comment by wakaleo** [comment]
That would be useful. I'm not sure if I'll have time to do it straight away, but please feel free to have a go (the new reporting is all in Kotlin, so it's quite pleasant to work with)

**Comment by nbarrett** [comment]
thanks @wakaleo - ah you beat me to it! Kotlin's definitely on my to-learn list so will collaborate on something soon, no doubt 👍
