### ISSUE TITLE
Execute method before each step

### ISSUE THREAD

**Issue by manevpe** [serenity-bdd/serenity-core#1426]
### Feature Request
Expose a method to execute an action before or after each step, similar to how capture screenshot can be called before and after each step. The step name should be available as well.

### Use Case
We are using Zalenium, which provides a feature to annotate the videos produced, with custom text for each step.
For this to work - we need to call a method before each step and send data to Zalenium, that "Step ABC" is starting.
We would like to do this in one place, that just takes the step name, instead of thousands of times for each step separately.

**Comment by wakaleo** [comment]
Implement the `StepListener` interface and register it with the StepEventBus, e.g.
```
StepEventBus.getEventBus().registerListener(myListener)
```

**Comment by manevpe** [comment]
Worked like a charm!
Thanks @wakaleo
