### ISSUE TITLE
withTimeoutOf method doesn't work

### ISSUE THREAD

**Issue by foven** [serenity-bdd/serenity-core#1430]
Hi all,
I have encountered a problem.I want to change the timeout when using findBy but it doesn't work. the codes are followed below :
```java
    private boolean isQuoteSuccess(WebElementFacade company) {
        try {
            return "报价失败".equals(company.findBy(By.cssSelector("div.fs18.red")).withTimeoutOf(300, TimeUnit.SECONDS).getText()) ? false : true;
        } catch (NoSuchElementException e) {
            return true;
        }
    }
```
I also use setWaitForTimeout， but it doesn't  work.

**Comment by wakaleo** [comment]
That is not how the withTimeoutOf() method works. You are telling Serenity/Selenium to find the element, and _then_ configure the wait logic (that's just how Java evaluates expressions). You need to put the withTimeoutOf() expression at the start, e.g. `withTimeoutOf(300, TimeUnit.SECONDS).findBy(By.cssSelector("div.fs18.red")).getText().`. The `company` field will always be evaluated with the default timeout (which you can override with the `webdriver.wait.for.timeout` property), but your milage may vary depending on the HTML page design (i.e. the element may already be present but not displayed, in which case the timeout will have no effect). In this case it would be better to use a single CSS selector, e.g. company.findBy(By.cssSelector("div.fs18.red")).withTimeoutOf(300, TimeUnit.SECONDS).getText()` will not do what you think it will do. You are telling Serenity/Selenium to find the element, and _then_ configure the wait logic (that's just how Java evaluates expressions). You need to put the withTimeoutOf() expression at the start, e.g. 

`withTimeoutOf(300, TimeUnit.SECONDS).findBy(By.cssSelector("#company-list div.fs18.red")).getText().`

**Comment by foven** [comment]
> That is not how the withTimeoutOf() method works. You are telling Serenity/Selenium to find the element, and _then_ configure the wait logic (that's just how Java evaluates expressions). You need to put the withTimeoutOf() expression at the start, e.g. `withTimeoutOf(300, TimeUnit.SECONDS).findBy(By.cssSelector("div.fs18.red")).getText().`. The `company` field will always be evaluated with the default timeout (which you can override with the `webdriver.wait.for.timeout` property), but your milage may vary depending on the HTML page design (i.e. the element may already be present but not displayed, in which case the timeout will have no effect). In this case it would be better to use a single CSS selector, e.g. company.findBy(By.cssSelector("div.fs18.red")).withTimeoutOf(300, TimeUnit.SECONDS).getText()` will not do what you think it will do. You are telling Serenity/Selenium to find the element, and _then_ configure the wait logic (that's just how Java evaluates expressions). You need to put the withTimeoutOf() expression at the start, e.g.
> 
> `withTimeoutOf(300, TimeUnit.SECONDS).findBy(By.cssSelector("#company-list div.fs18.red")).getText().`

hi wakaleo, thank you for your reply. there have many company , so i can't using By.cssSelector("#company-list div.fs18.red") directly, because this way will found out all of "div.fs18.red". how can i change default timeout temporarily before using findBy?

**Comment by wakaleo** [comment]
As this is a usage question, could you close the issue here and continue the conversation on https://serenity-bdd.rocket.chat?

**Comment by foven** [comment]
yes
