### ISSUE TITLE
jqplot folder is missing in serenity report

### ISSUE THREAD

**Issue by vzakharchuk** [serenity-bdd/serenity-core#1431]
build.gradle file
dependencies {
    compile group: 'junit', name: 'junit', version:'4.12'
    compile group: 'org.assertj', name: 'assertj-core', version:'3.9.1'
    compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.9.7'
    compile group: 'net.serenity-bdd', name: 'serenity-spring', version: '2.0.10'
    compile group: 'net.serenity-bdd', name: 'serenity-journey', version:'1.1.24'
    compile group: 'net.serenity-bdd', name: 'browse-the-web', version:'1.1.34'
    compile group: 'net.serenity-bdd', name: 'serenity-rest-assured', version:'1.9.19'
    compile group: 'net.serenity-bdd', name: 'serenity-cucumber', version:'1.9.5'
    compile group: 'net.serenity-bdd', name: 'serenity-junit', version:'1.9.7'
    compile group: 'io.cucumber', name: 'cucumber-java', version: '2.4.0'
    compile group: 'org.aeonbits.owner', name: 'owner', version: '1.0.9'
    compile 'org.awaitility:awaitility:3.0.0'
    compile group: 'javax.mail', name: 'mail', version: '1.4.7'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.8.8'
    compile group: 'org.mongodb', name: 'mongo-java-driver', version: '3.7.1'
    compile group: 'ru.yandex.qatools.ashot', name: 'ashot', version: '1.3'
    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.11.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.1'
    compile 'org.jfrog.artifactory.client:artifactory-java-client-services:+'
    compile group: 'net.lingala.zip4j', name: 'zip4j', version: '1.3.2'
    compile group: 'org.jodd', name: 'jodd-mail', version: '3.9.1'
    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.5'
    compile group: 'org.apache.poi', name: 'poi-ooxml', version: '3.9'
    testCompile group: 'ch.qos.logback', name: 'logback-classic', version: '0.9.26'
    testCompile group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '7.0.0.jre8'
    compile group: 'com.jayway.jsonpath', name: 'json-path', version: '2.4.0'

    cucumberRuntime files("${jar.archivePath}")
}

Run tests with `test -Dcucumber.options="--tags @MyTag"`. 
jqplot folder is not present in build/reports/serenity, that's why the report is broken.

**Comment by wakaleo** [comment]
What are you seeing in the reports?

**Comment by vzakharchuk** [comment]
Thanks for the prompt reply. 
![1](https://user-images.githubusercontent.com/16746586/47722389-02170d80-dc5b-11e8-95ca-1a263674b781.jpg)

Here is the screenshot  -> [](url)

**Comment by wakaleo** [comment]
Looks like you have a mix of serenity versions- take a look at the starter projects (eg https://github.com/serenity-bdd/serenity-cucumber-starter) to see what versions you should have in your Pom file.

**Comment by vzakharchuk** [comment]
It appears to be fixed by downgrading serenity-spring dependency version to 1.9.7.
Thx
