### ISSUE TITLE
Feature Descriptions duplicated/misformatted on Serenity 2.x reporting

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1435]
In the **Functional Coverage Overview** section of the new Serenity 2.x reporting, Feature descriptions appear twice with one of the appearances being incorrectly formatted - when they contain `-` characters. For instance if the Feature title is `Person completing to-dos on behalf of other`, it appears as in the report as an ignored feature, but then appears below as an included feature as `Agent completing to dos on behalf of other`. Attached is an example of a report from our latest build:

(image deleted due to client confidentiality)

Regarding a fix, I think it would probably be better to honour exactly the formatting that is in the original feature file as the reformatting can also upset the appearance of acronyms. There is also a further formatting that is applied when Feature is displayed in the Specification view as it then appears TitleCased as `Feature: Person Completing To-Dos On Behalf Of Other`.

**Comment by wakaleo** [comment]
I think doing that was non trivial, but I’m open to pull requests if you can find a way

**Comment by nbarrett** [comment]
Yes, confirmed this problem has now been resolved thanks @wakaleo 👍
