### ISSUE TITLE
How to Build Serenity-BDD libraries

### ISSUE THREAD

**Issue by verhagen** [serenity-bdd/serenity-core#144]
After the last updates on _master_ I do get a few compile issue like:

__Error:__ The waitfor(String) method is ambigue for the type ObjectPage (line995)

      public WebElementFacade waitFor(WebElement webElement) {
          return waitFor($(webElement));
      }

Can anyone describe the developer set up used for compiling the Serenity-BDD libraries ?

**Comment by rrussell39** [comment]
I am also seeing compile issues when I type 'gradle build' in the serenity-core directory:
.../serenity-core/serenity-core/src/main/java/net/serenitybdd/core/photography/PhotoSession.java:13: error: package java.util.stream does not exist
import java.util.stream.Collectors;
                       ^
.../serenity-core/serenity-core/src/main/java/net/serenitybdd/core/photography/ScreenshotNegative.java:8: error: cannot find symbol
import java.util.Optional;
                ^
  symbol:   class Optional
  location: package java.util
.../serenity-core/serenity-core/src/main/java/net/serenitybdd/core/photography/ScreenshotNegative.java:18: error: cannot find symbol
        this.blurLevel = Optional.ofNullable(blurLevel).orElse(BlurLevel.NONE);
                         ^
  symbol:   variable Optional
  location: class ScreenshotNegative

I get his against the head commit (020fd6fa6e101f659b812f434fe3114259b5f71f) or the 1.1.14 tag.

**Comment by wakaleo** [comment]
Looks like some trailing Java 8 imports, I'll take a look.

On 13 October 2015 at 07:07, rrussell39 <notifications@github.com> wrote:

> I am also seeing compile issues when I type 'gradle build' in the
> serenity-core directory:
> .../serenity-core/serenity-core/src/main/java/net/serenitybdd/core/photography/PhotoSession.java:13:
> error: package java.util.stream does not exist
> import java.util.stream.Collectors;
> ^
> .../serenity-core/serenity-core/src/main/java/net/serenitybdd/core/photography/ScreenshotNegative.java:8:
> error: cannot find symbol
> import java.util.Optional;
> ^
> symbol: class Optional
> location: package java.util
> .../serenity-core/serenity-core/src/main/java/net/serenitybdd/core/photography/ScreenshotNegative.java:18:
> error: cannot find symbol
> this.blurLevel = Optional.ofNullable(blurLevel).orElse(BlurLevel.NONE);
> ^
> symbol: variable Optional
> location: class ScreenshotNegative
>
> I get his against the head commit (020fd6f
> <https://github.com/serenity-bdd/serenity-core/commit/020fd6fa6e101f659b812f434fe3114259b5f71f>)
> or the 1.1.14 tag.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/144#issuecomment-147505732>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by wakaleo** [comment]
You need Gradle and Java 7 (or Java 8) to compile. To run the tests, you
need web driver set up for Chrome and PhantomJS. What JDK are you using?

On 13 October 2015 at 04:20, Tjeerd Verhagen <notifications@github.com>
wrote:

> After the last updates on *master* I do get a few compile issue like:
>
> *Error:* The waitfor(String) method is ambigue for the type ObjectPage
> (line995)
>
>   public WebElementFacade waitFor(WebElement webElement) {
>       return waitFor($(webElement));
>   }
>
> Can anyone describe the developer set up used for compiling the
> Serenity-BDD libraries ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/144>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by mikezx6r** [comment]
The Optional in ScreenshotNegative has been removed. The project should work with JDK7 and another place where Java stream was being used instead of Groovy. Hopefully this has rectified the build issues, so please try again.

**Comment by verhagen** [comment]
Current checked out version from git, contains some issues:

_The method waitFor(String) is ambiguous for the type PageObject_

class `net.serenitybdd.core.pages.PageObject`

    public WebElementFacade waitFor(WebElement webElement) {
        return waitFor($(webElement));
    }

**Comment by YamStranger** [comment]
Hello @verhagen. Can you check this now, it should work. Also for build please use gradlew in root directory, to be sure that you use the same version of gradle/groovy and used in stream. Thanks
