### ISSUE TITLE
Serenity doesnt give the actual error. It wraps it with null reference exception

### ISSUE THREAD

**Issue by myusoof** [serenity-bdd/serenity-core#1440]
when I try to hit restassure with openApivalidation filter
given().relaxedHTTPSValidation().baseUri("https://petstore.swagger.io/v2")
            .filter(validationFilter)
            .header("api_key", "special-key")
            .when()
            .get("/pet/adss")
            .then().log().status().extract();
I get the following error because it is expecting integer instead of string.
{
  "messages" : [ {
    "key" : "validation.request.parameter.schema.type",
    "level" : "ERROR",
    "message" : "Instance type (string) does not match any allowed primitive type (allowed: [\"integer\"])",
    "context" : {
      "requestPath" : "/v2/pet/adss",
      "parameter" : {
        "name" : "petId",
        "in" : "path",
        "description" : "ID of pet to return",
        "required" : true,
        "schema" : {
          "type" : "integer",
          "format" : "int64"
        }
      },
      "location" : "REQUEST",
      "requestMethod" : "GET"
    }
  } ]
}. 
But when I try with Serenityrest, I am getting null reference exception which doesnt tell me the actual reason for the failure from openApivalidation.

SerenityRest.given().relaxedHTTPSValidation().baseUri("https://petstore.swagger.io/v2")
            .filter(validationFilter)
            .header("api_key", "special-key")
            .when()
            .get("/pet/adss")
            .then().log().status().extract();

**Comment by wakaleo** [comment]
Could you provide a sample project that reproduces the issue?

**Comment by cliviu** [comment]
hi @myusoof ,  it would be helpful if you can provide a minimal sample project that can help us to reproduce the issue. The problem is with the creation of  the openApiValidationFilter
