### ISSUE TITLE
Default auto instrumentation causing undesirable output in reports

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1444]
There are lots of examples in my Screenplay projects where I do not wish there to be any output in the report, or perhaps only when a conditional performable is true. After upgrading to 2.0.13 I now have undesirable output in reports for classes that should never have instrumentation. For instance in the following, I have purposefully not instrumented StoreOrBackupData as its only function is to execute a conditional performable and then execute one / another / no task(s):

```public class StoreOrBackupData implements Interaction {

    @Override
    public <T extends Actor> void performAs(T actor) {
        CacheScenarioState cacheScenarioState = actor.abilityTo(CacheScenarioState.class);
        actor.attemptsTo(
            Check.whether(cacheScenarioState.scenarioCachingApplicable())
                .andIfSo(Restore.scenario(cacheScenarioState.getScenario()))
                .otherwise(Store.scenario(cacheScenarioState.getScenario())));
    }
}
```

However when I now run the test suite, I see `Bat cache store or backup data` at the level above where `Store` or `Restore` output would normally appear.  (Bat cache is the name of my 'system' actor that is responsible for restoring data).

However we now have another problem! Not only is the output undesirable, it's grammatically incorrect. This because of the convention in screenplay for naming classes as verbs `StoreOrBackupData`, whereas if we were to annotate the `@Step` we would generally write in the current tense e.g. `{0} stores or backs up data`. So I can't really see how auto instrumentation can/should take place as performing this transformation is not at all straightforward. It seems [from your latest blog](https://johnfergusonsmart.com/creating-tasks-in-serenity-screenplay/), that I now have to opt-in to the `CanBeSilent` interface and implement the `isSilent()` method as well - but that's quite an intrusive thing to do, to just return my test suite back to the 'quiet and correct' state it was in before I upgraded 😄

**Comment by wakaleo** [comment]
Have a look at the code in the Actor class (and possibly the StepInterceptor), I think it would be easy enough to add a property to revert to "legacy mode". You can use the IsSilent interface (which has no methods) if you are sure your task should never be instrumented.

**Comment by nbarrett** [comment]
Thanks for adding the property @wakaleo - that seems like a step in the right direction. However I still see a couple of problems:
* Even though I am setting `manual.task.instrumentation=true`, the auto-instrumentation still seems to be happening as can be seen in the task description:
![image](https://user-images.githubusercontent.com/626941/48065986-355e1d00-e1c4-11e8-81ca-ead09eff57d4.png)
* It seems that the instantiation of Tasks seems different in >= v2.0.13 such that it seems to be bypassing the internal behaviour inside public constructors that I have used. For instance here is the innards of one such problem task where amongst other things, we change the state of SERENITY_DRY_RUN** 

```
 public RestoreScenario(Scenario scenario) {
        this.scenario = scenario;
        this.dbDump = DBDump.instance(scenario);
        this.backupName = dbDump.backupName();
        setProperty(SERENITY_DRY_RUN, false);
    }
```
This then causes my scenario to not work correctly as dry run stays set for the whole scenario. If the bypassing of constructor behaviour is true, then I find it a little concerning. I'm sure I'm not alone in having a strong preference for immutable design as it helps clarify behaviour/lifecycle of class instances by means of constructor(s) always initialising final fields.

*** I can imaging you saying dry run should never be manipulated by the test but right now in our codebase this creates a very useful skippable concept that allows us to bypass long setup stages which significantly speeds up our builds.

**Comment by wakaleo** [comment]
Could you take a look in the code and see what you can suggest? Not sure how much time I will have on this this week

**Comment by wakaleo** [comment]
Could you try with 2.0.15?

**Comment by nbarrett** [comment]
Hi @wakaleo - I've given 2.0.15 a spin but unfortunately it's still not possible to turn off auto-instrumentation.  Having put a breakpoint in InstrumentedTask, it seems that all tasks return `true` for `isInstrumented()` in the following code, therefore the OR condition will always return true:

```
 public static <T extends Performable> T of(T task) {
        if (isInstrumented(task) || !shouldInstrument(task)) {
            return task;
        }
        return (T) instrumentedCopyOf(task, task.getClass());
    }
```

In my testing, I used the following calling conventions:

* `actor.attemptsTo(new InitialiseBrowserWindow());`
* `actor.attemptsTo(instrumented(InitialiseBrowserWindow.class));`

where the above Task has no `@Step` annotation on it:

```
public class InitialiseBrowserWindow implements Interaction {

    @Override
    public <T extends Actor> void performAs(T actor) {
...
```

**Comment by nbarrett** [comment]
I'll raise a PR for this as soon as I can get tests running locally and write some tests for this 😸

**Comment by nbarrett** [comment]
Hi @wakaleo - I've spent some time on this by creating some unit tests in [a branch](https://github.com/serenity-bdd/serenity-core/compare/master...nbarrett:1444-default-auto-instrumentation-causing-undesirable-output) in commit: 0602dee4a83c194eef21341bce49ce3bda9d25d4

However things are not quite there yet:
- I've added unit tests for when MANUAL_TASK_INSTRUMENTATION is true
- 2 tests still failing as intended behaviour is still not correct despite an attempt to change logic in InstrumentedTask
