### ISSUE TITLE
Asp.Net MVC Serenity How To Fix "BasedOnRowAttribute"

### ISSUE THREAD

**Issue by lingoontech** [serenity-bdd/serenity-core#1447]
Hello; 

I need help for asp.net MVC serenity : 1 Error : **System.InvalidOperationException: 'BasedOnRowAttribute value (IndoorNavigationPortal.IndoorNavigation.Columns.QrInfoColumns) must be set to a subclass of IndoorNavigationPortal.IndoorNavigation.Columns.QrInfoColumns!'**

QRInfoColumns Code : 

`
namespace IndoorNavigationPortal.IndoorNavigation.Columns
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;
    using IndoorNavigationDB;

    [ColumnsScript("IndoorNavigation.QRInfo")]
    [BasedOnRow(typeof(Entities.QRInfoRow))]
    public class QrInfoColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId")]
        public Int32 QrId { get; set; }

        [EditLink , DisplayName("Db.IndoorNavigation.QRInfo.QRName")]
        public String QrName { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRContent")]
        public String QrContent { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRVideo")]
        public String QrVideo { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRVoice")]
        public String QrVoice { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRText")]
        public String QrText { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRImage")]
        public String QrImage { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DXPosition"), AlignRight, Width(200)]
        public Decimal Model3DxPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DYPosition"), AlignRight, Width(200)]
        public Decimal Model3DyPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DZPosition"), AlignRight, Width(200)]
        public Decimal Model3DzPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DXRotation"), AlignRight, Width(200)]
        public Decimal Model3DxRotation { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DYRotation"), AlignRight, Width(200)]
        public Decimal Model3DyRotation { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DZRotation"), AlignRight, Width(200)]
        public Decimal Model3DzRotation { get; set; }
    }
}`

Thank you all for comments.

**Comment by wakaleo** [comment]
Wrong Serenity
