### ISSUE TITLE
How To Fix : System.InvalidOperationException: 'BasedOnRowAttribute value  ... Must be set to a subclass of "Columns.cs"

### ISSUE THREAD

**Issue by lingoontech** [serenity-bdd/serenity-core#1448]
Hi;

I need fix to : Title error : System.InvalidOperationException: 'BasedOnRowAttribute value (IndoorNavigationPortal.IndoorNavigation.Columns.QrInfoColumns) must be set to a subclass of IndoorNavigationPortal.IndoorNavigation.Columns.QrInfoColumns!'

Error Image : https://i.hizliresim.com/oVLG0b.jpg

My Columns Code Page : 

`
namespace IndoorNavigationPortal.IndoorNavigation.Columns
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;
    using IndoorNavigationDB;

    [ColumnsScript("IndoorNavigation.QRInfo")]
    [BasedOnRow(typeof(Entities.QRInfoRow))]
    public class QrInfoColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId")]
        public Int32 QrId { get; set; }

        [EditLink , DisplayName("Db.IndoorNavigation.QRInfo.QRName")]
        public String QrName { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRContent")]
        public String QrContent { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRVideo")]
        public String QrVideo { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRVoice")]
        public String QrVoice { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRText")]
        public String QrText { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.QRImage")]
        public String QrImage { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DXPosition"), AlignRight, Width(200)]
        public Decimal Model3DxPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DYPosition"), AlignRight, Width(200)]
        public Decimal Model3DyPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DZPosition"), AlignRight, Width(200)]
        public Decimal Model3DzPosition { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DXRotation"), AlignRight, Width(200)]
        public Decimal Model3DxRotation { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DYRotation"), AlignRight, Width(200)]
        public Decimal Model3DyRotation { get; set; }

        [EditLink, DisplayName("Db.IndoorNavigation.QRInfo.Model3DZRotation"), AlignRight, Width(200)]
        public Decimal Model3DzRotation { get; set; }
    }
}
`

**Comment by wakaleo** [comment]
We can’t help you, this repo is for Serenity BDD, not the totally unrelated .net Serenity project
