### ISSUE TITLE
Update the serenity rest assured version to 3.2.0

### ISSUE THREAD

**Issue by csnthsh120** [serenity-bdd/serenity-core#1452]

**Comment by wakaleo** [comment]
Pull Requests welcome

**Comment by csnthsh120** [comment]
The serenity rest assured version is still at 3.0.5 which was released 1 Year back. Can we update the rest assured version to the latest.

**Comment by wakaleo** [comment]
Here is the process: clone the repo, change the version, update to cater for any API changes in REST Assured, make sure the tests run (at least for the serenity-rest-assured and the screenplay-rest modules) and raise a pull request.

**Comment by csnthsh120** [comment]
@wakaleo  : Hahaha, thank you very much for the detailed explanation. I am a developer myself and know the process. Will create a PR once I finished updating and testing.

**Comment by wakaleo** [comment]
RestAssured version 3.3.0 is integrated into serenity-rest 2.0.42
