### ISSUE TITLE
saucelabs options (SaucelabsRemoteDriverCapabilities) need to be updated for selenium 3.11.0 or later

### ISSUE THREAD

**Issue by enortonAtAdobe** [serenity-bdd/serenity-core#1455]
https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta#SeleniumW3CCapabilitiesSupport-Beta-CheckingforUseofNewCapabilities

https://github.com/serenity-bdd/serenity-core/blob/v2.0.17/serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/SaucelabsRemoteDriverCapabilities.java

Note: Since Sauce Labs updated their marionette (gecko) driver from 0.19.1 to 0.23.0, experiencing that tests can no longer run in Firefox because 'ms' parameter is only used in JWP, but W3C expects 'implicit' on the 'timeouts' command

**Comment by wakaleo** [comment]
Fixed in 2.0.18
