### ISSUE TITLE
How to run scenario outline multiple time for list of data

### ISSUE THREAD

**Issue by sumit-global** [serenity-bdd/serenity-core#1458]
Hi @wakaleo 

I know it's not a right platform to ask questions.
I want to run my scenario outline examples with different set of data and data is dynamic for examples.

**For eg:**
I am having java List say L which contains values of country like USA, INDIA UK and so on.(which will generated dynamically) and I want to run my examples with set of data for eg:

Examples:
|Country| State| Region|
|USA      | ABC  | DEF     |
|USA      | GHI  | JKL       |
|USA      | MNO  | PQR  |

Now I want above examples will run for first USA and then for INDIA and so on(as per data in list)

I tried to make it run by using following

**public class ABC {
@Test
public void run() throws Throwable {
for(String s: L){
net.serenitybdd.cucumber.cli.Main.main(new String[] { "-g", "Path of Step Defs","Path of feature file" });
}
}
}**

and running above class as "**clean verify -Dit.test=Abc.java**"

It is running fine for first data from list and report generated successfully, but it is not running for rest of data. Please suggest how can I achieve above part.

Thanks in advance.

**Comment by wakaleo** [comment]
Cucumber doesn't support dynamic example lists. It would be more usual just to have multiple examples tables in the same feature file, e.g.

Examples: USA
|Country| State| Region|
|USA | ABC | DEF |
|USA | GHI | JKL |
|USA | MNO | PQR |

Examples: India
|Country| State| Region|
| India | ABC | DEF |
| India | GHI | JKL |
| India | MNO | PQR |

**Comment by sumit-global** [comment]
Thanks for reply. But size of list isn’t fixed so i think multi examples will not work here..

**Comment by wakaleo** [comment]
You could do it easily enough in Screenplay by making a dynamic list of tasks or consequences. If you are trying to do it with Cucumber, you are probably using the wrong tool - what you are doing is test scripting, and Cucumber is not a test scripting tool.

**Comment by sumit-global** [comment]
Can I refer "https://github.com/serenity-bdd/serenity-screenplay-train-demo" for screenplay functionality?

**Comment by wakaleo** [comment]
Yes, or http://github.com/serenity-bdd/screenplay-pattern-todomvc.
