### ISSUE TITLE
Interactions patch and options are truncated

### ISSUE THREAD

**Issue by IronRB** [serenity-bdd/serenity-core#1460]
I have a user story in which I use a patch, when I use the patch interaction, I observe the reports of serenity and I am surprised that the consumption has been made with options, the same test has been carried out, the interactions have been exchanged and obtained the same result. that is, use options and the consumption was with patch.
Attached screenshots of github interactions exchanged in serenity rest assured.

![interactions github](https://user-images.githubusercontent.com/45204578/48780067-fdb4a200-eca6-11e8-9bc3-12403ce5786f.PNG)
![interactions github2](https://user-images.githubusercontent.com/45204578/48780117-2177e800-eca7-11e8-82ab-dc0eba6c3d08.PNG)

**Comment by wakaleo** [comment]
Well spotted - if you provide a pull request, I will include it in the next release

**Comment by wakaleo** [comment]
Fixed in 2.0.18
