### ISSUE TITLE
Serenity + Selenoid Chrome issue

### ISSUE THREAD

**Issue by AndriySinchuk** [serenity-bdd/serenity-core#1462]
I use serenity + cucumber and decide to try Selenoid with docker images of browsers and
when i choose Firefox docker image everything is fine, but in case of chrome there are an error:

14824 [main] ERROR net.serenitybdd.core.pages.PageObject - Could not execute @WhenPageOpens annotated method: null
15094 [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: Check chart with filtered object
---------------------------------------------------------------------
15094 [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Login with credentials: xxxxxxxxxxxxxxxxxxxxxxxxxx
15095 [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - unknown error: failed to change window state to maximized, current state is normal  (Session info: chrome=70.0.3538.67)  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-39-generic x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 0 millisecondsBuild info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'System info: host: 'andriy-To-be-filled-by-O-E-M', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-39-generic', java.version: '1.8.0_191'Driver info: org.openqa.selenium.remote.RemoteWebDriverCapabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.43.600233 (523efee95e3d68..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:33719}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 70.0.3538.67, webStorageEnabled: true}Session ID: 14fec0b8cf8155928c8ad8f6759212c0Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'System info: host: 'andriy-To-be-filled-by-O-E-M', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-39-generic', java.version: '1.8.0_191'Driver info: driver.version: unknown
15208 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener -

**Comment by wakaleo** [comment]
I believe there is a bug in the chromedriver when you use the Selenium maximise screen command - you need to use chrome switches and not the Serenity property

**Comment by AndriySinchuk** [comment]
If i find workaround i will post it there

**Comment by AndriySinchuk** [comment]
The workaround is adding env variable ENABLE_WINDOW_MANAGER=true
