### ISSUE TITLE
NamedUrls is retrieved from wrong class.

### ISSUE THREAD

**Issue by vzakharchuk** [serenity-bdd/serenity-core#1464]
Hey, 

I have class A which is extended by class B. Class A is annotated with `@DefaultUrl("http://webdriver.base.url/app/main#")`
Class B doesn't contain any kind of annotations. 
Class A is injected as page object to Cucumber step definition class. 
The method openPage() there is calling the method `page.open()` in class A. The class B is not used at all. 
But when the test run I found out that in this part of the code in PageUrls.java 
`    private Optional<String> getDeclaredDefaultUrl() {
        DefaultUrl urlAnnotation = pageObject.getClass().getAnnotation(DefaultUrl.class);
...........}`

the `pageObject` is object of class B, but not class A. 

Could you please clarify is this the correct behaviour?

**Comment by vzakharchuk** [comment]
I believe that it is caused by this method in PageObject.java
`    private void setupPageUrls() {
        setPageUrls(new PageUrls(this));
    }`

`this` appeared to be class B, not class A. 
Maybe it is caused because of next hierarchy PageObject -> MyAbstractClass -> Class A -> Class B.

Anyway, thanks for the feedback.

**Comment by wakaleo** [comment]
If you propose a PR to add this capability ability I will be happy to review it.
