### ISSUE TITLE
Maven Serenity Cucumber Test Pending...

### ISSUE THREAD

**Issue by mdjahidurrahman** [serenity-bdd/serenity-core#1465]
Hello,
My Test is pending with snippets where i have snippets. Here is the error. please help. Thanks.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/mdjah/.m2/repository/com/google/inject/guice/4.2.0/guice-4.2.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
1349 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - [36m

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat      
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
 Learn Serenity BDD online at http://serenity-dojo.com                               
-------------------------------------------------------------------------------------
[0m
1359 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Test Facebook smoke scenario
1617 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: Test login with valid credentials
-------------------------------------------------------------------(test-facebook-smoke-scenario;test-login-with-valid-credentials)
2031 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - TEST PENDING
2035 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - TEST PENDING
2036 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - TEST PENDING
2037 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - TEST PENDING
2040 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
          __  _____ _____ ____ _____   ____  _____ _   _ ____ ___ _   _  ____ 
 _       / / |_   _| ____/ ___|_   _| |  _ \| ____| \ | |  _ \_ _| \ | |/ ___|
(_)____ / /    | | |  _| \___ \ | |   | |_) |  _| |  \| | | | | ||  \| | |  _ 
 |_____/ /     | | | |___ ___) || |   |  __/| |___| |\  | |_| | || |\  | |_| |
(_)   /_/      |_| |_____|____/ |_|   |_|   |_____|_| \_|____/___|_| \_|\____|
                                                                                

TEST PENDING: Test login with valid credentials
---------------------------------------------------------------------------------
2745 [pool-2-thread-1] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: stepDefinition

1 Scenarios ([33m1 undefined[0m)
4 Steps ([33m4 undefined[0m)
0m0.863s

You can implement missing steps with the snippets below:

@Given("^Open Browser and start application$")
public void open_Browser_and_start_application() throws Exception {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@When("^I enter valid USERNAME and valid PASSWORD$")
public void i_enter_valid_USERNAME_and_valid_PASSWORD() throws Exception {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^User shall able to login$")
public void user_shall_able_to_login() throws Exception {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^Application should closed$")
public void application_should_closed() throws Exception {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

[CucumberProject.zip](https://github.com/serenity-bdd/serenity-core/files/2611015/CucumberProject.zip)

**Comment by wakaleo** [comment]
"Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils". Looks like a Guice bug.

**Comment by wakaleo** [comment]
Your sample project uses very out-dated versions of Serenity; try with more recent versions.

**Comment by mdjahidurrahman** [comment]
I have gave a try and it's work. Thanks so much for support.
