### ISSUE TITLE
WebElementFacade declared at class level is not getting recognized

### ISSUE THREAD

**Issue by vaijiNeel** [serenity-bdd/serenity-core#1466]
Example:
public class myPageObj extends PageObject{

public myPageObj (WebDriver driver) {
    super(driver);
}

@FindBy(xpath = "//button[@title='Search']")
private WebElementFacade XPATH_SEARCH_BTN;

public void verifyBtn(){
  logger.info("search btn xpath - " + XPATH_SEARCH_BTN);
  XPATH_SEARCH_BTN.click();
}
} The logger.info doesn't print the xpath. I get: search btn xpath - DefaultElementLocator 'by id or name "XPATH_SEARCH_BTN"'

If I declare it inside the verifyBtn() method it works fine. Could someone shed light why element declared at class level is not getting recognized?

**Comment by wakaleo** [comment]
You are calling the toString() method on the web element - this is the expected result.

**Comment by vaijiNeel** [comment]
Sorry I forgot to type toString() in logger.info in above code/question, but I had that in my original code. It use to work earlier in a different project. I created a new maven project and copied the code. After that it stopped working, and I don't see any error or warning issued. The click event doesn't happen either. If I declare it inside the method as follows, it works fine:
public void verifyBtn(){
WebElementFacade XPATH_SEARCH_BTN= find(ByXPath.xpath("//button[@title='Search']"));
logger.info("search btn xpath - " + XPATH_SEARCH_BTN.toString());
XPATH_SEARCH_BTN.click();
}

**Comment by wakaleo** [comment]
Closed - presumed question answered.
