### ISSUE TITLE
Do you know how to set timeout for every step?

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#1467]
hi, 
 i have a problem, my test scenario have more than 30 steps, and One step took more than 30 minutes to execute shell script on linux server, However, if the step exceeds 30 minutes, it will timeout and terminate the   test scenario.  Do you know how to set the step timeout?

**Comment by wakaleo** [comment]
Is this using JBehave?

**Comment by ChrisD1990** [comment]
yes, i use JBehave

**Comment by wakaleo** [comment]
This is an issue with JBehave (unrelated to Serenity). Set the `story.timeout.in.secs` to a very high value - this is the total execution time of _all_ the tests in the test suite.

**Comment by ChrisD1990** [comment]
ok, i see, thanks for your replay. have a good day
