### ISSUE TITLE
still issues with SauceLabs in serenity 2.0.18

### ISSUE THREAD

**Issue by enortonAtAdobe** [serenity-bdd/serenity-core#1468]
Thanks for the fix for #1455 in commit 3dd499eed088bc7120aead0a02fab69f18478935

However, there appears to be more changes required per the document https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta#SeleniumW3CCapabilitiesSupport-Beta-CheckingforUseofNewCapabilities than just the file called out in the original issue.  As now with serenity 2.0.18, it is no longer possible to execute tests in Chrome browser (Firefox did work).

SauceLabs suggested: Can you try setting "w3c" to true in chromeOptions? See the note on this at https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta

I am not familiar with where all the SauceLabs or browser driver related api calls are in Serenity to itemize where calls need to be udpated based on that wiki.  And I'm also not certain the current suggestion from SauceLabs is the only further change needed.

**Comment by wakaleo** [comment]
Can you try out some changes in the `SaucelabsRemoteDriverCapabilities` class and propose a PR?

**Comment by enortonAtAdobe** [comment]
I can give it a try :)  I think that that might not be the only class that needs updating though.  It might take me some time too.

**Comment by maheshkukrani** [comment]
hey guys, i ran into the same issues while upgrading the serenity version from 2.0.15 to latest(2.0.48). i opened another issue but after debugging and looking into this issue i realized you guys already gave it a try to add the experimental options. So do i need to set this manually as for saucelabs w3c should be true  ? I see that you support both saucelabs and browserstack and hence you cannot set them to default ?

**Comment by maheshkukrani** [comment]
Ok more update - so for chrome adding this in serenity.properties solves it - chrome.experimental_options.w3c=true
what about firefox other than the option of implementing a custom driver?

**Comment by enortonAtAdobe** [comment]
I was able to get this working for all browsers, with the following properties:
saucelabs.platform="${PLATFORM}"
saucelabs.browserName=${BROWSER}
saucelabs.browser.version=${BROWSER_VERSION}

**Comment by maheshkukrani** [comment]
Referring #1678 for all the combinations i had tried. i tried your suggestion too but it doesn't work.
so this is what i set exactly-

saucelabs.url=********
saucelabs.test.name=test
saucelabs.platform=macOS 10.12
saucelabs.browserName=firefox
saucelabs.browser.version=66
saucelabs.access.key=*******
saucelabs.user.id=*********

**Comment by enortonAtAdobe** [comment]
Sorry - one other property we specify: saucelabs.seleniumVersion=3.141.59
We've got this set in the serenity.properties file:

**Comment by enortonAtAdobe** [comment]
note too, this seleniumVersion corresponds to the one we specify in our java project via our maven pom file as well

**Comment by maheshkukrani** [comment]
Gr8, this worked fine!. i haven't tested it for all browsers but  at least that i was trying worked.
