### ISSUE TITLE
Newest Serenity Assertions not honoring line breaks (\n's)

### ISSUE THREAD

**Issue by scruff220** [serenity-bdd/serenity-core#1471]
I was trying out the latest Serenity with my current Java, Rest Assured, Serenity framework.

In the 1.x versions we would construct our error messages like

```
String message = "Excluded lists do not match...\nExpected: "+EXPECTED_LIST+"\nActual: "+ACTUAL_LIST;
Assert.assertTrue(message, <boolean expression>);
```

For 1.x this would give us a red "View Details" button and would print out:

```
Excluded lists do not match...
Expected: [list values]
Actual: [list values]
```

But in 2.0.19/20 it shows up under the test results as an assertion error (no more button needed to press but it only shows the first line) that looks like this:
```
Excluded lists do not match...
```

It basically doesn't honor anything after the first "\n" it hits and I can't find a way to get to the full error to display so I'm left with just the first line (or getting rid of the \n's and having a longer un-formatted message that isn't as useful.

Is this a defect or is there a better way to structure my error messages other than using "\n" ... I do like a lot of the updates & would like to switch over but wanted to check on this because it may prevent us.

Thanks for all the hard work on 2.0!!

**Comment by wakaleo** [comment]
It would probably be easier to use Hamcrest or AssertJ rather than building your messages from scratch, e.g.
```
        assertThat(myList).containsAll(expectedValues);
```
That said I am not seeing this behaviour in 2.0.28:

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/55986/50354402-58117e80-0543-11e9-972f-15490134961d.png">

**Comment by scruff220** [comment]
Okay, tried Hamcrest & 2.0.28 ... still no second line ... here are the same failure for 2.0.28 vs. 1.9.25

`LINE 487: assertThat(testResult.getFailMessage(), testResult.isPassing());`

1.9.25
[https://drive.google.com/open?id=12wzzyK5zHJ2SGlzRRU8w3Dyz-0VAphA9](url)

2.0.28
[https://drive.google.com/open?id=1hSAWfys6R5Z7aMSvIbMQw79QNsnmXqkN](url)

**Comment by scruff220** [comment]
(Sorry, I didn't have the permission set on those links ... now they should work)

**Comment by wakaleo** [comment]
Could you reproduce this in a sample project?

**Comment by wakaleo** [comment]
Seems to work in 2.0.42

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/55986/55552847-75272300-56d6-11e9-9450-c2d3bd386f99.png">

**Comment by scruff220** [comment]
Yes, THANK YOU! Very happy to see this!

**Comment by Tamas-Demeny** [comment]
Hello, I am experiencing this issue in Serenity version 3.6.12
