### ISSUE TITLE
Driver closes after each scenario execution

### ISSUE THREAD

**Issue by JenniferPerezBedoya** [serenity-bdd/serenity-core#1473]
Using

Serenity 2.0.17
Serenity-Cucumber 1.9.20
Serenity-Screenplay 2.0.17
Appium 1.9.1
Xcode 9.4

The serenity driver is closed after each scenario execution. This occurs when multiple scenarios exist within a Feature/Story. Scenarios doesn't depend each other, but when running tests on Kobiton (a cloud device farm), we faced that after each scenario execution, driver.quit() is called, so the device session ends. What device needs to keep session open, is only to call driver.closeApp(), driver.quit() must be called only when all test suite ends.

StepDefinitions are designed following the next example (driver management is let to serenity): https://github.com/serenity-bdd/journey-planner/blob/master/src/test/java/planner/cucumber/PlanAJourneyStepDefinitions.java

**Comment by ricardorlg** [comment]
try to use serenity.restart.browser.for.each system property

**Comment by JenniferPerezBedoya** [comment]
That works if I don't need to close the app, but I need to restart the app without restarting the driver.

**Comment by wakaleo** [comment]
That case isn’t supported, but you are welcome to play round and propose a PR.

**Comment by ricardorlg** [comment]
In that case, I will suggest playing with before/after hooks and use appium close and app in background https://discuss.appium.io/t/want-to-restart-android-application-in-a-single-appium-session-without-deleting-uninstalling-it/13561

**Comment by JenniferPerezBedoya** [comment]
Thanks Ricardo, I've tried what you proposed me but still getting the same error, I've created custom driver but when a scenario ends, the driver sessionID is set to null so the driver cannot be used again. I don't know if it's maybe a cucumber's issue but driver.quit() is still called.

**Comment by ricardorlg** [comment]
I think you should also use this property serenity.restart.browser.for.each

**Comment by JenniferPerezBedoya** [comment]
It works Ricardo, thank you so much for your help!.

**Comment by ricardorlg** [comment]
Great, @wakaleo I think this can be closed.

**Comment by JenniferPerezBedoya** [comment]
Ricardo, do you know a way to close the driver when all cucumber features are executed?

**Comment by ricardorlg** [comment]
Mmm is not closing?  Well I think you can create and after all hook and call quit directly @wakaleo what do u think?

**Comment by ricardorlg** [comment]
mmm I think u can use an after all hook and call quit on driver,
