### ISSUE TITLE
conditional hiding row from grid in serenity 

### ISSUE THREAD

**Issue by nareshIntelegain** [serenity-bdd/serenity-core#1474]
I have user table and there is Status column with bit datatype i want to show only Status=1 i.e. active user only from record

**Comment by wakaleo** [comment]
You will need to give a bit more context. Is this a defect or a usage question?

**Comment by nareshIntelegain** [comment]
How can i show only acive data in datagrid,

**Comment by wakaleo** [comment]
What datagrid?

**Comment by nareshIntelegain** [comment]
Serenity datagrid 

 var UserGrid = /** @class */ (function (_super) {
            __extends(UserGrid, _super);
            function UserGrid(container) {
                return _super.call(this, container) || this;
            }
            UserGrid.prototype.getColumnsKey = function () { return "Administration.User"; };
            UserGrid.prototype.getDialogType = function () { return Administration.UserDialog; };
            UserGrid.prototype.getIdProperty = function () { return Administration.UserRow.idProperty; };
            UserGrid.prototype.getIsActiveProperty = function () { return Administration.UserRow.isActiveProperty; };
            UserGrid.prototype.getLocalTextPrefix = function () { return Administration.UserRow.localTextPrefix; };
            UserGrid.prototype.getService = function () { return Administration.UserService.baseUrl; };
            UserGrid.prototype.getDefaultSortBy = function () {
                return [Administration.UserRow.Fields.Username];
            };
            UserGrid.prototype.getButtons = function () {
                var _this = this;
                var buttons = _super.prototype.getButtons.call(this);
                buttons.push(CVC.Common.PdfExportHelper.createToolButton({
                    grid: this,
                    onViewSubmit: function () { return _this.onViewSubmit(); }
                }));
                return buttons;
            };

          

            UserGrid = __decorate([
                Serenity.Decorators.registerClass()
            ], UserGrid);
            return UserGrid;
        }(Serenity.EntityGrid));

**Comment by wakaleo** [comment]
This is the Serenity BDD repository, which is a Java project; I think you have the wrong project.
