### ISSUE TITLE
Serenity + cucumber how to rerun failed tests

### ISSUE THREAD

**Issue by AndriySinchuk** [serenity-bdd/serenity-core#1476]
Is there are any possibility to automatically rerun failed cucumber scenarios?   
I use serenity core 2.0.11, serenity-cucumber 1.9.18,

**Comment by vuthelinh** [comment]
Should to try with this .
[Rerun Failed Tests in JUnit](https://www.swtestacademy.com/rerun-failed-test-junit/)

**Comment by wakaleo** [comment]
No, that won’t work. The feature exists, but I need to write it up

**Comment by AndriySinchuk** [comment]
And how much time approximately need to implement this functionality? It`s really important feature because  i have a task to automatically create tasks in jira with failed tests and without rerurns some number of false tasks will be created, and my suite is too large and complicated to painfully rewrite it without cucumber. 
Btw tasks in jira are generated when report is aggregated?

**Comment by AndriySinchuk** [comment]
> Should to try with this .
> [Rerun Failed Tests in JUnit](https://www.swtestacademy.com/rerun-failed-test-junit/)

Thank you for reply, i tried this approach before and it unable to rerun failed cucumber scenarios.

**Comment by wakaleo** [comment]
@AndriySinchuk if you need this quickly please raise a support ticket to allow it to be taken care of as a priority. (see https://johnfergusonsmart.com/serenity-bdd-mentoring#support)

**Comment by william0096** [comment]
Any answer on this??? I'm actually using the following command with maven "mvn verify  -Dfailsafe.rerunFailingTestsCount=2", and it works properly, but I still have the issue with gradle, did someone solve it?

**Comment by ssuriset1** [comment]
@william0096  Could you please let us know the exact steps to implement this?

**Comment by miroslaf** [comment]
@wakaleo any progress? I am currently trying to get tests to rerun but with no success as any documented option won't work..

**Comment by Swetha-pa** [comment]
can someone suggest how to rerun failed stories in serenity jbehave

**Comment by wakaleo** [comment]
This feature exists in Cucumber but I don’t think it exists in JBehave

**Comment by ssuriset1** [comment]
Hi John,

Can you help me with how to rerun failed scenarios in serenity cucumber?

**Comment by wakaleo** [comment]
It's a standard Cucumber feature; see for example https://www.qaautomation.co.in/2019/01/re-running-failed-scenarios-in-cucumber-junit.html

**Comment by ssuriset1** [comment]
Hi John,

In my framework, I am generating runner classes at runtime to
achieve parallel execution. In this case, how can I run the failed
scenarios automatically?

Ex: pom.xml

Under this "src/test/resources/features/LM" I have multiple feature files.

Using this plugin, I am managing the fork count at runtime.

=====================================================================
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.21.0</version>
<configuration>
<forkCount>${forkCount}</forkCount>
<systemPropertyVariables>
<java.awt.headless>true</java.awt.headless>
</systemPropertyVariables>
<includes>
<include>**/*IT.class</include>
</includes>
</configuration>
</plugin>
=====================================================================

<profile>
<id>ui_lm</id>
<build>
<plugins>
<plugin>
<groupId>com.github.temyers</groupId>
<artifactId>cucumber-jvm-parallel-plugin</artifactId>
<version>4.2.0</version>
<executions>
<execution>
<id>generateRunners</id>
<phase>generate-test-sources</phase>
<goals>
<goal>generateRunners</goal>
</goals>
<configuration>


<glue>

<package>com.qa.stepDefinitions</package>
</glue>
<outputDirectory>target/generated-test-sources/cucumber</outputDirectory>
<featuresDirectory>src/test/resources/features/LM</featuresDirectory>
<cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>

<namingPattern>Parallel{c}IT</namingPattern>
<parallelScheme>FEATURE</parallelScheme>
<customVmTemplate>src/test/resources/cucumber-serenity-runner.vm</customVmTemplate>
</configuration>
</execution>
</executions>
</plugin>
</plugins>
</build>
</profile>
========================================================================

This is my "cucumber-serenity-runner.vm" file.
=========================================================================
#parse("/array.java.vm")
#if ($packageName)
package $packageName;

#end##
import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
strict = true,
features = {"$featureFile"},
plugin = #stringArray($plugins),
monochrome = true,
#if(!$featureFile.contains(".feature:") && $tags)
tags = #stringArray($tags),
#end
glue = #stringArray($glue))
public class $className {
}
==========================================================================

Please help me.
