### ISSUE TITLE
Serenity junit overwrites reports in parallel execution

### ISSUE THREAD

**Issue by sandaliqbal1** [serenity-bdd/serenity-core#1477]
I'm running junit test suites in parallel using maven-surefire plugin. Basically the suites contain same classes so same tests are executed on different devices but serenity is overwriting the result of one test suite with another. Ideally it should consider the suite name as well while generating the reports. Surefire reports have correct result for each suite. Please suggest a solution for this.

Steps to reproduce:
Create two junit testsuite classes but include the same testclass in both of them. Now run the suites in parallel by setting parallel=suites in surefire and including the suite classes. The serenity reports will have result for only one set of testcases. Others are perhaps overwritten

**Comment by wakaleo** [comment]
You can use test contexts for this: https://johnfergusonsmart.com/running-tests-different-environments-browsers-serenity-bdd/

**Comment by wakaleo** [comment]
You can use any value you want for a context. I'm not sure how you would set the context programmatically though.

**Comment by sandaliqbal1** [comment]
Even with context it will set the same context for the both the suites and hence again overwrite the results. Is there a way I can set the context for each thread separately perhaps through test listener in testSuiteStarted method?

**Comment by sandaliqbal1** [comment]
I have figured out the problem which is in BaseStepListener. Basically when you are getting latestTestOutcome you are always getting the last element from testOutcomes list which is getting overwritten when accessed by two threads at the same time. I made a fix by having a ThreadLocal currentTestOutcome field and setting it when the test starts and returning it in getCurrentTestOutcome and latestTestOutcome methods but unfortunately I'm not authorized to raise a PR. Can you tell me how can I raise a PR for the same?

**Comment by wakaleo** [comment]
Well spotted! The PR process is explained quite well here: https://help.github.com/articles/about-pull-requests

Or if it a simple change you can just share the modified class and a unit test that demonstrates the fix and I will integrate the changes by hand

**Comment by sandaliqbal1** [comment]
When I try to raise the PR it gives me unauthorized error. I also made a change in TestOutcome class to set the context programmatically as that is what will help in generating different output files for the same test when run in multi-threaded mode. I'm attaching both the files in zip here.
[serenity.zip](https://github.com/serenity-bdd/serenity-core/files/2807223/serenity.zip)

**Comment by sandaliqbal1** [comment]
I have added few more ThreadLocals in BaseStepListener and also in JunitStepListener. To test the fix you can run any maven project with surefire plugin and set parallel=methods and run a single test class having couple of methods. Without the fix the serenity report will show only one test method showing all the steps from all the tests and other tests will show 0 steps whereas with this fix all the methods will show proper respective steps. Again attaching the files as zip. Also request you to run your integration tests only on these changes and not combine them with other changes as we do not know which change is causing test failures.
[serenity.zip](https://github.com/serenity-bdd/serenity-core/files/2840237/serenity.zip)

**Comment by sandaliqbal1** [comment]
Hi was there a chance to try the fix?

**Comment by wakaleo** [comment]
Not yet - did you run the unit and integration tests on your side?

**Comment by wakaleo** [comment]
The code has changed since; I really need this as a PR or a patch.

**Comment by sandaliqbal1** [comment]
Well I can go gradle test and check the results. Whats the expected result? Do all tests pass or are there any known failures?

**Comment by sandaliqbal1** [comment]
I ran the tests with the fix and am getting same test result as with master branch with latest code without my fix. 
Attaching the patch file here.
[0001-fixing-report-overwrite-issue.patch.zip](https://github.com/serenity-bdd/serenity-core/files/2893386/0001-fixing-report-overwrite-issue.patch.zip)

**Comment by vanhai493** [comment]
Dear all!
Has this problem been resolved yet? And which version serenity has this fix?
Thank so much!

**Comment by testifyqa** [comment]
I am also wondering what the latest with this is, I am getting my test overwritten with whatever context was used in the latest job :(

**Comment by testifyqa** [comment]
Thanks for making a fix @wakaleo , looking forward to it :)

**Comment by testifyqa** [comment]
Hi @wakaleo, I have updated serenity-core to 2.2.10 but still have an issue where my test reports only show test against one browser context. Here is a snippet from my Jenkinsfile, wondering if I am maybe doing something wrong ?? Thanks.

`parallel (
                 firefox_lightning_tests: {
                     withEnv(['DRIVER=utils.drivers.remote.RemoteFirefoxDriver',
                            'TEST_REPORT_DIR=firefox-reports']) {
                         stage('Run tests in parallel against Firefox') {
                             catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                 sh './gradlew -Dcontext=firefox testParallel'
                                 sh 'ls -a firefox-reports'
                                 sh 'cp -r firefox-reports/. target/site/serenity'
                             }
                         }
                     }
                 },
                 chrome_lightning_tests: {
                     withEnv(['DRIVER=utils.drivers.remote.RemoteChromeDriver',
                            'TEST_REPORT_DIR=chrome-reports']) {
                         stage('Run tests in parallel against Chrome') {
                             catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                 sh './gradlew -Dcontext=chrome testParallel'
                                 sh 'ls -a chrome-reports'
                                 sh 'cp -r chrome-reports/. target/site/serenity'
                             }
                         }
                     }
                 }
             )`

I've noticed that the contents in chrome-reports and firefox-reports are identical which may be part of the cause, any ideas on how to get both browser contexts showing in my report possibly? cheers.

**Comment by wakaleo** [comment]
I'm not sure, you will probably have to dig into the code to see what it is doing.

**Comment by wilmargutierrez** [comment]
Hi everyone,

this looks very similar to the problem I have. I use some of the test classes more than once in different test suites. These are snippets taken from some of my jUnit test suites:

```
@Suite.SuiteClasses({
        AppliesForCardTest.class,
        PostponesApplicationTest.class
	…
})
public class PostponementTestScenario { }


@Suite.SuiteClasses({
        AppliesForCardTest.class,
        RejectsApplicationTest.class
	…
})
public class RejectionTestScenario { }


@Suite.SuiteClasses({
        AppliesForCardTest.class,
        ApprovesApplicationTest.class
	…
})
public class ApprovalTestScenario { }

```
As you can see, a new application is always the starting point in every test scenario. But the test report only includes the last run of it. So, if the test `AppliesForCardTest` of one of the first scenarios fails I lose the information and have to fall back to the Serenity log file in order to analyze the causes (that is, without screenshots :| ).

If you guys think this is something different, I’d be more than happy to raise an extra bug report with more information.

Thanks a lot in advance.

**Comment by BaoTran14** [comment]
Hi all,
 Using serenity version 2.2.2 resolved this issue for me.
