### ISSUE TITLE
Serenity generate report without a pie chart and with duplicated test details sections

### ISSUE THREAD

**Issue by Denys22605** [serenity-bdd/serenity-core#1478]
Notes: 

serenity-core-version : 2.0.20
Browser: Chrome, Firefox, Safary

In the browser's console following error: 

Uncaught TypeError: Cannot read property 'PieRenderer' of undefined
    at HTMLDocument.<anonymous> (index.html?_ijt=tf5lk1uj5476drg53jae70ttmr:81)
    at j (jquery-1.11.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1.min.js:2)
    at Function.ready (jquery-1.11.1.min.js:2)
    at HTMLDocument.J (jquery-1.11.1.min.js:2)

Here is the screenshot: 

![image](https://user-images.githubusercontent.com/17333676/49585679-b5b0a300-f967-11e8-9577-30139377eede.png)

**Comment by wakaleo** [comment]
Can you provide a project that reproduces the issue?

**Comment by Denys22605** [comment]
> Can you provide a project that reproduces the issue?

Unfortunately, I can't. This is the working project and sharing the source code is strictly forbidden by our company. But I'm ready to present you as much information, as you need. I can provide you a part of my pom.xml (if needed)

**Comment by wakaleo** [comment]
I would need to see the full project, or a similar project that has the same issue.

**Comment by wakaleo** [comment]
What version are you using?

**Comment by Denys22605** [comment]
I'm using maven to run my tests. 
And there is the following error in IDE's console when I'm trying to aggregate the HTML report (serenity: aggregate) -> 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M1:verify (default) on project verity_qa_framework: There are test failures.
[ERROR]
[ERROR] Please refer to D:\QA\olpsdk\test\verity_qa_framework\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Denys22605** [comment]
> What version are you using?
serenity-core -> 2.0.20
serenity-jbehave -> 1.44.0
maven-failsafe-plugin -> 3.0.0-M1

**Comment by wakaleo** [comment]
The report is a 1.9.x report - are you sure all your dependencies are up to date?

**Comment by Denys22605** [comment]
> The report is a 1.9.x report - are you sure all your dependencies are up to date?

Yes. Here is the screenshot of the >mvn versions:display-dependency-updates command

![image](https://user-images.githubusercontent.com/17333676/49586230-42a82c00-f969-11e8-8677-e4c8386bd351.png)

**Comment by wakaleo** [comment]
You mention 2.0.20 but your report is 1.x, so you have a 1.x dependency somewhere. Check your serenity maven plugin version

**Comment by lukacmilos** [comment]
Hi all,
I have the same problem. I'm using following dependency:
![2018-12-13_09h49_36](https://user-images.githubusercontent.com/33930331/49926703-77ae0480-febc-11e8-8a31-5fe7b7c2e509.jpg)

**Comment by wakaleo** [comment]
Check your Maven plugin version

**Comment by lukacmilos** [comment]
Hi,
you are right, I forgot update serenity-gradle-plugin. Now it works.
