### ISSUE TITLE
capability with a colon

### ISSUE THREAD

**Issue by Oagile** [serenity-bdd/serenity-core#1479]
Hi, 

I have a driver capability that i want to set "e34:token". on the serenity.properties i have serenity.driver.capabilities="e34:token:cccccccccccc" . The problem i'm having is the capability that i want to set has a colon in it :-(,  is there a way for me to programatically set capability before the driver is instantiated?  

On my old tests i have something like this :
ChromeOptions options = new ChromeOptions();
 options.setCapability("e34:token", "cccccccccccc");

     try {
                    driver = new RemoteWebDriver(new URL("http://xxxxxx.xxxxxx.xx/wd/hub"), options);
                } catch (MalformedURLException e) {
                    e.printStackTrace();
                }

Below is the exception that i'm getting with serenity
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'LW09643872', ip: '172.27.248.48', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: DefaultRemoteDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (A test token needs to be provided via the e34:token capability. http://x.x.x.xx:xxx/ui/test-projects/selfservice

**Comment by wakaleo** [comment]
Could you post your serenity.properties or serenity.conf file?

**Comment by Oagile** [comment]
# Define the default driver
#webdriver.driver=chrome
webdriver.gecko.driver=src/drivers/geckodriver.exe
webdriver.chrome.driver=src/drivers/chromedriver.exe
webdriver.wait.for.timeout=20000

chrome.switches=--args -disable-extensions
chome_preferences.disable_infobars=true
chome.switches=useAutomationExtension=false

serenity.logging=QUIET
webdriver.remote.url=http://xxxxxxx.xxxxx.xx/wd/hub
webdriver.remote.os=WINDOWS
serenity.driver.capabilities="e34:token:ccccccccc"

**Comment by Oagile** [comment]
The exception is 

---------------------------------------------------------------------
[main] ERROR net.serenitybdd.core.Serenity - TEST FAILED AT STEP Given user navigates to SGATE homepage on his browser
[main] ERROR net.serenitybdd.core.Serenity - Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (A test token needs to be provided via the e34:token capability. http://x.x.x.x:xxxx/ui/test-projects/selfservice
[main] ERROR net.serenitybdd.core.Serenity -

**Comment by Oagile** [comment]
Hi John, any recommendations?

**Comment by wakaleo** [comment]
Handling the colon needs a change to the code, but your reports mention Firefox rather than chrome, so you may also need to add serenity.remote.driver=chrome.

**Comment by Oagile** [comment]
Much appreciated I have updated remote driver,

I guess handling it the colon will be on future releases?

**Comment by Oagile** [comment]
much appreciated Liviu, with the code that you have commited i guess the below config should work? 

serenity.driver.capabilities="e34:token:ccccccccc"

Where can i get the build artifact of serenity-core that contains your commit? i understand that it won't be a released version

**Comment by cliviu** [comment]
hi @Oagile , yes, it should work 
` def "should allow capabilities containing two colons"() {
        given:
        environmentVariables.setProperty("serenity.driver.capabilities","e34:token:ccccccccc")
        when:
        def capabilitySet = new CapabilitySet(environmentVariables)
        then:
        capabilitySet.capabilities == ["e34:token":"ccccccccc"]
    }
    def "should allow capabilities containing multiple colons"() {
        given:
        environmentVariables.setProperty("serenity.driver.capabilities","e34:token1:token2:ccccccccc")
        when:
        def capabilitySet = new CapabilitySet(environmentVariables)
        then:
        capabilitySet.capabilities == ["e34:token1:token2":"ccccccccc"]
    }`  Stay tuned, a new version will come out soon I think.

**Comment by Oagile** [comment]
awesomeness @cliviu

**Comment by wakaleo** [comment]
Fixed.

**Comment by Oagile** [comment]
much appreciated, i guess that will be this dependency 

<dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-core</artifactId>
    <version>2.0.33</version>
</dependency>

**Comment by wakaleo** [comment]
Yes. The rule is that all options need to be prefixed with “—“

**Comment by Oagile** [comment]
awesomeness, busy updating project dependencies. 

hmmm not sure if i follow John .i.e. regarding the prefix.  e.g?

**Comment by wakaleo** [comment]
Actually, the prefix (two dashes) is only needed for Chrome options

**Comment by Oagile** [comment]
ooh got that...  much appreciated

**Comment by Oagile** [comment]
bummer, i have removed the quotes.... all good...

Happiness :-)

**Comment by Paulo1661** [comment]
Hi, i want to pass this option : serenity.driver.capabilities=se:downloadsEnabled:true.
But doesn't work as i expected
