### ISSUE TITLE
How to display passed assertion details in serenity report under steps ?

### ISSUE THREAD

**Issue by shreyasarjun** [serenity-bdd/serenity-core#1481]
I have a rest assured script as follow

.body(CARTID_LABEL, equalTo(ReusableMethods.stringToInteger(cartId)), 
			  CUSTOMERID_LABEL, equalTo(ReusableMethods.stringToInteger(customerId)),
		      SITE_LABEL, equalTo(site),
		      ZIPCODE_LABEL, equalTo(ReusableMethods.stringToInteger(zipCode)),
		      STOREID_LABEL, equalTo(storeId),  
		      COUPONCODE_LABEL, equalTo(couponCode),
		      ITEMIDC_LABEL, equalTo(ReusableMethods.stringToInteger(itemId)),
		      IVMC_LABEL, equalTo(ivm),
		      PROMOIDC_LABEL, equalTo(promoId),
		      PROMOTYPEC_LABEL, equalTo(promoType),
		      PROMONAMEC_LABEL, equalTo(promoName));

If anything is failed then failed assertions report is looks awesome. But I just want to make sure these are all things I have verified and I want to display passed assertions details also in my serenity report.

As of now, My report looks like this.
Then step is displaying only step description. But I just want display like expected value matched with actual value successfully or something like that.
![serenityreport](https://user-images.githubusercontent.com/13919078/49784274-b750e100-fd42-11e8-98e8-569283d56661.jpg)

**Comment by shreyasarjun** [comment]
Thanks a lot @wakaleo . Now its looks fine.
![report](https://user-images.githubusercontent.com/13919078/49792073-da39c000-fd57-11e8-8dec-cc1e9e8a7b48.jpg)

**Comment by phamhiepst** [comment]
> Thanks a lot @wakaleo . Now its looks fine.
> ![report](https://user-images.githubusercontent.com/13919078/49792073-da39c000-fd57-11e8-8dec-cc1e9e8a7b48.jpg)

Could you please guide me how can print all soft assertion result to report like this? Thanks

**Comment by wakaleo** [comment]
You would need to write your own wrapper around (for example) the soft assertion feature in AssertJ, catch any exceptions and record them as discussed about.

**Comment by mghiraw** [comment]
Hi any new on this. Did someone make a wrapper for this.
We have tons of hamcrest assertions. 
The auditors wants to see in the report what we are checking without looking in the code.

**Comment by globalworming** [comment]
@mghiraw like @wakaleo suggested it is preferred to provide readable step descriptions or add additional step description with evidence https://serenity-bdd.github.io/theserenitybook/latest/living-documentation.html#_adding_additional_evidence

**Comment by mghiraw** [comment]
Thankx!

**Comment by helciodasilva** [comment]
**Solution:** https://assertj.github.io/doc/#assertj-core-assertion-description-consumer
