### ISSUE TITLE
serenity aggregate goal appears to be slow running

### ISSUE THREAD

**Issue by felixvolz** [serenity-bdd/serenity-core#1485]
I run 30 tests in Serenity (serenity, junit, maven), eahc test takes ~5 seconds to run and the building of the aggregated report takes 219 seconds. As I increase unit tests (up to 140 tests) I see the report generation get slower and slower

- I'm a novice Serenity user; is this an expected generation time? 
- How can I tune Serenity for optimal speed - I'm not sure what options I have (e.g. parallezation, increase java memory, specific serenity settings)

![image](https://user-images.githubusercontent.com/6946906/49867396-7bab3980-fe5e-11e8-937a-915c77d2ae2a.png)

When I look in my output folder, I can see the aggregated report html (highlighted) slowly growing in size till it eventually completed.
![image](https://user-images.githubusercontent.com/6946906/49867543-f6745480-fe5e-11e8-8c39-05b9ca50da59.png)

`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<version>0.0.1-SNAPSHOT</version>
	<name>xx</name>
	<properties>
		<serenity.version>2.0.20</serenity.version>		
		<serenity.maven.version>2.0.20</serenity.maven.version>
        <slf4j.version>1.7.7</slf4j.version>
		<junit.version>4.12</junit.version>
		<soapui.maven.version>5.2.1</soapui.maven.version>
		<maven.surefire.plugin.version>2.19.1</maven.surefire.plugin.version>
		<maven.failsafe.plugin.version>2.19.1</maven.failsafe.plugin.version>
		<maven.compiler.plugin.version>3.2</maven.compiler.plugin.version>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.0</version>
		</dependency>
	    <dependency>
		    <groupId>com.jgoodies</groupId>
		    <artifactId>forms</artifactId>
		    <version>1.0.7</version>
	    </dependency>
		<dependency>
  			<groupId>com.smartbear.soapui</groupId>
 			<artifactId>soapui-maven-plugin</artifactId>
  			<version>${soapui.maven.version}</version>
		</dependency>
		<dependency>
			<groupId>jxl</groupId>
			<artifactId>jxl</artifactId>
			<version>2.6.12</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.poi</groupId>
		    <artifactId>poi</artifactId>
		    <version>3.17</version>
		</dependency> 
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire.plugin.version}</version>
				<configuration>
					<runOrder>alphabetical</runOrder>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>${maven.failsafe.plugin.version}</version>
				<configuration>
					<includes>
						<include>**/*.java</include>
					</includes>
					<argLine>-Xmx4096</argLine>
					<systemPropertyVariables>
						<TestEnv>${TestEnv}</TestEnv>
					</systemPropertyVariables>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<groupId>xx</groupId>
	<artifactId>xx</artifactId>
</project>`

**Comment by wakaleo** [comment]
Big reports take time, but 219 seconds seems a lot. Not normal but could be project-specific - maybe create a project that reproduces the issue, or raise a support ticket so we can look at the project directly.

**Comment by felixvolz** [comment]
Thx - I'll see if  I can reproduce in a shareable project
