### ISSUE TITLE
Maven Build is not marked as failed when the tests contain errors

### ISSUE THREAD

**Issue by rakeshnambiar** [serenity-bdd/serenity-core#1486]
Maven Build is not marking as failed when the tests contain error.

        <serenity.version>2.0.11</serenity.version>
        <serenity.maven.version>2.0.11</serenity.maven.version>
        <serenity.cucumber.version>1.9.20</serenity.cucumber.version>

Tests in error: 
  ERROR: While clicks on the View button from the Suggested Authors section
  ERROR: While Checking the Suggested ORCID Authors
  ERROR: While Selecting the Articles for Claiming

Tests run: 25, Failures: 0, Errors: 3, Skipped: 0

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:34 min
[INFO] Finished at: 2018-12-11T17:38:52+00:00
[INFO] Final Memory: 47M/161M
[INFO] ------------------------------------------------------------------------

**Comment by wakaleo** [comment]
This is usually related to your maven/surefire/failsafe setup, and unrelated to Serenity. Try asking on the Serenity community chats at https://serenity-bdd.rocket.chat

**Comment by rakeshnambiar** [comment]
Thanks, @wakaleo

**Comment by wakaleo** [comment]
Closing as not a Serenity issue.
