### ISSUE TITLE
SilentPeformable is not silent in the report

### ISSUE THREAD

**Issue by zsirohey** [serenity-bdd/serenity-core#1487]
I faced this issue in the following use case:

```java
theActorInTheSpotlight().attemptsTo(
        Check.whether(aRequiredConditionIsMet())
                .otherwise(EndPerformance.because("the required condition was not met..."))
);
```

In the case that aRequiredConditionIsMet() produces true, there is nothing defined for andIfSo, meaning that the default outcome for true will be executed, which is found in `ConditionalPeformable` and is `outcomeToPerform.put(true, new Performable[]{ new SilentPerformable() });`.

The execution of this SilentPerformable should not produce anything in the report; however, the following is produced.

![image](https://user-images.githubusercontent.com/25011604/49874923-c2148000-fded-11e8-9688-270b28f606ba.png)

This can also simply be reproduced by:

```java
theActorInTheSpotlight().attemptsTo(
        new SilentPerformable()
);
```

I think this could simply be fixed by implementing the `IsSilent` interface marker in SilentPerformable.

**Comment by wakaleo** [comment]
Fixed in 2.0.25
