### ISSUE TITLE
Cannot use Jquery annotation method with @FindBy

### ISSUE THREAD

**Issue by anoopsivarajan** [serenity-bdd/serenity-core#1488]
Hi
I am using the page object model with Serenity @FindBy annotation and with method jquery.

Example:
`  
@FindBy(jquery = "div:contains('A red apple')'")
   private WebElementFacade body;`

When I run the tests, Serenity is failing to locate the object and throws the managed exception. Find by jquery will be very useful feature as I migrating a very large custom framework to Serenity cucumber BDD. Do you think this will work only with apps which use the JQuery library? 

`net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: unknown error: Syntax error, unrecognized expression: div:contains('A red apple')'
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'CI-LT-019', ip: '192.168.200.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11'
Driver info: org.openqa.selenium.remote.RemoteWebDriver`

**Comment by anoopsivarajan** [comment]
Thanks @wakaleo . The JQuery selectors are working fine after setting the magic flag. I couldn't find any documentation on this, it will be good if you could add this to the reference manual.

**Comment by leidyu24** [comment]
Hi, I want to know where I set the flag, I present the same problem, I already set serenity.jquery.integration to true, but it generates the following error: org.openqa.selenium.NoSuchElementException: Timed out after 10 seconds. Element not found
