### ISSUE TITLE
How to change serenity report logo ?

### ISSUE THREAD

**Issue by shreyasarjun** [serenity-bdd/serenity-core#1489]
I want to change serenity logo image in my serenity report.
I have tried using below path solution but it doesn't worked me.
https://stackoverflow.com/questions/38913415/serenity-reports-logo-change

Could you please explain how to change serenity logo ?

**Comment by wakaleo** [comment]
This is not currently supported but you could modify the freemarker templates to add this option and propose a PR.

**Comment by timothyjmtan** [comment]
@shreyasarjun  https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request

**Comment by asvdw** [comment]
I had to customize the report for a client some years ago. This is how I did it:
https://github.com/serenity-bdd/serenity-core/issues/1032

But imho you should let credits to serenity, such a good (and open source) work needs to be acclaimed...

**Comment by wakaleo** [comment]
Closing, presume answered by @asvdw
