### ISSUE TITLE
Please bring back an option to see how many test failed by tag on main page (like it was in version 1.x.x)

### ISSUE THREAD

**Issue by etsybaev** [serenity-bdd/serenity-core#1490]
Since the Serenity version, there is no more option to see how many tests failed by each tag on the main page.  Such option exists in Serenity v 1.x.x. Now tag marked by red even if one test of 100 failed. To see how many tests failed you need to open it by tag. Previously It was very useful to see how many tests passed/failed for each particular tag, especially when you change some basic related to many tags.
For me particularly this is major inconvenience that prevents me to update serenity from v1.x.x to v 2.x.x
Many thanks in advance.
![image](https://user-images.githubusercontent.com/4688354/50150135-c2b58680-02c5-11e9-89ed-172a8a95b877.png)

**Comment by wakaleo** [comment]
In 2.0.27 you can use the `report.tagtypes` property to give the list of tag types you would like to appear on the home page.
