### ISSUE TITLE
Get Ability by implemented Interface

### ISSUE THREAD

**Issue by miles-mason** [serenity-bdd/serenity-core#1493]
When accessing an Ability through an Actor e.g. `BrowseTheWeb.as(actor).methodCall()` it's necessary to name the Ability class directly. However, in more complex Ability structures, we may not care about the exact Ability class, and instead just want any Ability that implements a particular Interface.

This could be achieved with a factory like `UseAnAbility.of(actor).thatAllows(MyInterface).methodFromMyInterface()`

I'm happy to submit a Pull Request for this, but I'm looking to generate some discussion about the exact wording / implementation.

**Comment by wakaleo** [comment]
That seems like a good idea, I'd be happy to review a PR with the change and some tests to illustrate how it works.

**Comment by wakaleo** [comment]
Will be available in 2.0.28
