### ISSUE TITLE
Updating dependencies of jaxb libraries

### ISSUE THREAD

**Issue by svaidya401** [serenity-bdd/serenity-core#1495]
The dependency on jaxb-core, jaxb-impl and jaxb-api use version `2.2.1`. This version uses `{tools.jar}` through an environment variable. 
Tools.jar is not supported for java 10 and gives problem during build process if it is not present in the JDK.
Recommendation is to update jaxb-core , jaxb-impl and jaxb-api to latest 2.3.1 which do not have dependency on `tools.jar`

**Comment by wakaleo** [comment]
Updated in 2.0.27
