### ISSUE TITLE
java.lang.ClassCastException caused by toString() in BrowseTheWeb after upgrade to 2.0.26

### ISSUE THREAD

**Issue by dmalecki001** [serenity-bdd/serenity-core#1496]
Hi,

our team has encountered an issue, which shuts all our WebDriver initialisations.
After upgrading from 2.0.17 to 2.0.26 we receive the following error:

[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
                                                                                  
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat      
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
 Learn Serenity BDD online at http://serenity-dojo.com                               

[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: 01 Create new venue request

[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 

TEST STARTED: 01.2 The user attempts to approve new venue in the CRM

(01-create-new-venue-request;01.2-the-user-attempts-to-approve-new-venue-on-the-crm)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is 72.0.3626.7
[main] INFO io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\dmalecki\.m2\repository\webdriver\chromedriver\win32\72.0.3626.7\chromedriver.exe
Starting ChromeDriver 72.0.3626.7 (efcef9a3ecda02b2132af215116a03852d08b9cb) on port 8942
Only local connections are allowed.
gru 19, 2018 2:33:06 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
                                   
TEST FAILED WITH ERROR: 01.2 The user attempts to approve new venue in the CRM

[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Given The user can browse the web with "chrome" browser
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - com.sun.proxy.$Proxy16 cannot be cast to net.thucydides.core.webdriver.WebDriverFacade

java.lang.ClassCastException: com.sun.proxy.$Proxy16 cannot be cast to net.thucydides.core.webdriver.WebDriverFacade

	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.toString(BrowseTheWeb.java:88)
	at net.serenitybdd.screenplay.Actor.can(Actor.java:80)
	at com.pwc.ctech.flex.stepDefinitions.coreStepDefinitions.gui.InitialiseDriverStepDefinitions.lambda$new$0(InitialiseDriverStepDefinitions.java:17)
	at ✽.The user can browse the web with "chrome" browser(src/test/resources/features/01NewVenueRequest.feature:16)

Failed scenarios:
src/test/resources/features/01NewVenueRequest.feature:15 # 01.2 The user attempts to approve new venue in the CRM

1 Scenarios (1 failed)
5 Steps (1 failed, 4 skipped)
0m7.520s

java.lang.ClassCastException: com.sun.proxy.$Proxy16 cannot be cast to net.thucydides.core.webdriver.WebDriverFacade
	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.toString(BrowseTheWeb.java:88)
	at net.serenitybdd.screenplay.Actor.can(Actor.java:80)
	at com.pwc.ctech.flex.stepDefinitions.coreStepDefinitions.gui.InitialiseDriverStepDefinitions.lambda$new$0(InitialiseDriverStepDefinitions.java:17)
	at ✽.The user can browse the web with "chrome" browser(src/test/resources/features/01NewVenueRequest.feature:16)

Process finished with exit code -1

After close inspection I have found out that toString() in 2.0.17 was:

public String toString() {
        return "browse the web with " + this.webdriverManager.getDefaultDriverType();
    }
which simply displayed "FIREFOX" in the report.
And the new version is:

    public String toString() {
        if (this.getDriver().toString().contains("Mock")) {
            return "browse the web with a mock browser";
        } else {
            String driverName = ((WebDriverFacade)this.getDriver()).getDriverName();
            return "browse the web with " + driverName;
        }
    }

which means that the cast to WebDriverFacade causes this issue.
Unless I am wrong :D

Kind regards
Damian Malecki

**Comment by wakaleo** [comment]
Can you try with 2.0.27?

**Comment by nbarrett** [comment]
Thanks for raising @dmalecki001 - I was about to do the same!

**Comment by wakaleo** [comment]
Should be fixed in 2.0.27

**Comment by dmalecki001** [comment]
This error is no longer being experienced in 2.0.27.
Thank you for fixing!
