### ISSUE TITLE
Single for Different DB tables (not linked)

### ISSUE THREAD

**Issue by nathanealg** [serenity-bdd/serenity-core#1497]
I am wondering if there is a way to do the following:

Create a 'Check' form, link to a database and table (this is fine).  But on this form I would like to pull in data from a different database and table and put that into a list format onto the 'Check' form.

Then when the Save/Update button is pressed,  I don't want to save the data from database 2.  But save the rest of information inputted into the Check form.

Anyone know a way to do this?

**Comment by wakaleo** [comment]
Are you sure this issue is related to Serenity BDD?

**Comment by nathanealg** [comment]
Not a issue with Serenity I believe, probably more how-to.  Could not find anywhere to post help and it looked like this was the place.

**Comment by wakaleo** [comment]
No, I mean I think you have the wrong project.

**Comment by nathanealg** [comment]
ah, okay.  Will close this call.  Thanks

**Comment by nathanealg** [comment]
.
