### ISSUE TITLE
Remove legacy stuff

### ISSUE THREAD

**Issue by hypery2k** [serenity-bdd/serenity-core#15]
Would be nice to rename thucydides.properties to serenity.properties. Also the report folder within the site should be named serenity.
Seems that the reporting with maven is not working correctly: https://martinreinhardt-online.de/jenkins/job/serenity_maven_sample/

**Comment by wakaleo** [comment]
This is three separate points, but I think they are all addressed in version 1.0.35: you can now use either thucydides.properties or serenity.properties, and the reports are generated in target/site/serenity.

If you can reproduce the reporting issue with 1.0.35, please open a separate issue.
