### ISSUE TITLE
Qualifier doesn't work

### ISSUE THREAD

**Issue by qantium** [serenity-bdd/serenity-core#150]
Hi!

Here is my parametrized test
```
import java.util.Arrays;
import java.util.Collection;
import net.serenitybdd.junit.runners.SerenityParameterizedRunner;
import net.thucydides.junit.annotations.Qualifier;
import net.thucydides.junit.annotations.TestData;
import net.thucydides.junit.annotations.UseTestDataFrom;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(SerenityParameterizedRunner.class)
@UseTestDataFrom("\\AuthNegative.csv")
public class AuthNegative {

    public String phone;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Qualifier
    public String getQualifier() {
        return phone;
    }
    
    @Test
    public void negativeAuthorizeWithPhone() {}
    
}
```
My data file:
PHONE
25452345234
45234522423

So after I have runned it, I see report
![negative authorize with phone](https://cloud.githubusercontent.com/assets/14546177/10605318/183c20f4-7733-11e5-95e9-f9af4bf0fb66.jpg)

Why there are no phone data in the title of iteration?

**Comment by verhagen** [comment]
Can you update the issue, and apply [Markdown](https://guides.github.com/features/mastering-markdown/), for the shown __Code__. See Example - Code. Thx

**Comment by cliviu** [comment]
Please try to include this field in your test, even if you are not using it: 

```java
 @Managed
 public WebDriver driver;
```

**Comment by YamStranger** [comment]
@qantium Hi! Thanks for writing us!

To see parameters in your report you should organize your tests using step libraries, you can find more details there [Writing Serenity Step Libraries](http://thucydides.info/docs/serenity/#_writing_serenity_step_libraries) 
Also, here is example of [well organized Data-driven test](http://thucydides.info/docs/serenity/#_data_driven_tests)

In your situation it would be better create additional class
```
public class AuthorizationSteps {
    @Step
    public void authorizeWithPhone(String phone) {
    }
}
```

and reuse it as steps class in your code
```

...
    private String phone;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Qualifier
    public String getQualifier() {
        return phone;
    }

    @Steps
    AuthorizationSteps steps;

    @Test
    public void negativeAuthorizeWithPhone() {
        steps.authorizeWithPhone(this.phone);
    }
}
```

as result you will receive beautiful report with necessary data, like this:

![image](https://cloud.githubusercontent.com/assets/1667699/10728493/feb4a8e2-7bea-11e5-8037-e09ea41fcd91.png)

**Comment by qantium** [comment]
Thanks a lot!

**Comment by andreiaionitoaiesv** [comment]
Tried the suggestion solution on v2.0.20 doesn't work. Does it matter if i use serenity-rest-assured?
