### ISSUE TITLE
HtmlTable rowDataFrom() returns duplicated record list in case of headings provided

### ISSUE THREAD

**Issue by IvanLiulko** [serenity-bdd/serenity-core#1500]
Hi,
faced with issue with following statement:
List<Map<Object, String>> tableRows = HtmlTable.withColumns("title", "events", "participants").readRowsFrom(table);
It returns duplucated data with headings names and with column nums:
"1" -> "Title"
"2" -> "4 events"
"3" -> "6 participants"
"title" -> "Title"
"events" -> "4 events"
"participants" -> "6 participants"
However if headings provided, I expect that it have to be returned following:
"title" -> "Title"
"events" -> "4 events"
"participants" -> "6 participants".

Looks like issue in rowDataFrom() method with loop where twice put implemented:
        for(Iterator var5 = headings.iterator(); var5.hasNext(); **rowData.put(column, cell)**) {
            String heading = (String)var5.next();
            cell = this.cellValueAt(column++, cells);
            if (!StringUtils.isEmpty(heading)) {
                **rowData.put(heading, cell)**;
            }
        }

have you a plan to fix it?

**Comment by wakaleo** [comment]
What is the structure of your table. This feature works as intended for simple tables with headings and rows, but you are welcome to provide a pull request if you can think of improvements. See ReadingTableData https://github.com/serenity-bdd/serenity-core/blob/f8ef5b90b1c6ef04bd876a6a59fd996bcc2bb228/serenity-core/src/test/java/net/thucydides/core/pages/integration/ReadingTableData.java.
