### ISSUE TITLE
override manual test result: can set ie SKIPPED, but not SUCCESS

### ISSUE THREAD

**Issue by asvdw** [serenity-bdd/serenity-core#1501]
Good morning,

I know there is some work in progress about it, but I need to set the result for manual tests with my own logic (grab results for external file or db). 

Default behaviour is, as I understand, to run steps in dry mode, so there is an exception in steps requiring Selenium and PageObjects (net.thucydides.core.pages.WrongPageError) but in the report, the test will be marked as Manual and Pending.

So far, I can change result implementing my own StepListener with this code:
```
public class MyListener implements StepListener {
[...]
    @Override
    public void testIsManual() {
        TestOutcome lastOutcome = getLastOutcome();
        lastOutcome.overrideAnnotatedResult(TestResult.SKIPPED);
        System.out.println(lastOutcome.getAnnotatedResult());
    }

    private TestOutcome getLastOutcome() {
        int lastIndex = StepEventBus.getEventBus().getBaseStepListener().getTestOutcomes().size() - 1;
        return StepEventBus.getEventBus().getBaseStepListener().getTestOutcomes().get(lastIndex);
    }
```

That works: I can see my test in the report marked as Skipped. Great.

But now If I change TestResult.SKIPPED to testResult.SUCCESS the test appears as FAILED in the report.

What's wrong ? Can I set result to SUCCESS ?

Thank you
        serenity.version: 2.0.27
        serenity.cucumber.version: 1.9.21

**Comment by wakaleo** [comment]
At the moment, @Manual tests are not really meant to be used for anything more than placeholders for, well, manual tests. At some point we intend to add the possibility to force the result in the annotation, with a timestamp to say when the test was last checked, but this hasn't been done yet. At the moment, it would be potentially misleading to mark a @Manual test as passing, as if the test is running in CI you probably can't guarantee that it was actually manually tested when the CI build was run.

**Comment by asvdw** [comment]
Yes, I understand, that's why I try to implement my own project-specific log, so using a custom listener looks fine.

I think I'm not so far of what I need, but what I can't understand is why I can set result to Skipped, ignored, compromised, ... but NOT success.

I can publish a demo project, and maybe help to fix it. 
You know the best way to scare off managers is to speak about money, but I can try if I make my proof on concept workable...

**Comment by wakaleo** [comment]
Test results on @Manual steps are supported in 2.0.60 onwards.
