### ISSUE TITLE
The of() method is not supported for By-type Targets

### ISSUE THREAD

**Issue by vuthelinh** [serenity-bdd/serenity-core#1502]
Hi @wakaleo 

This log `The of() method is not supported for By-type Targets` shows when I use it to locate element with mobile.

```
	public static final Target MENU_ITEM = Target.the("sub menu")
			.located(By.xpath("//android.widget.TextView[@text='{0}']"));
```

**Comment by wakaleo** [comment]
This is intentional, we can only do string substitutions with String-based locators, as with the other locator types we don't have access to the string once the locator is created.
