### ISSUE TITLE
Remote driver creation failed (Chrome)

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [serenity-bdd/serenity-core#1506]
Hi all!

When running my test in parallel I'm pretty often meet creating webdriver exception: 

> [pool-1-thread-8] WARN net.serenitybdd.core.webdriver.servicepools.ChromeServicePool - Remote driver creation failed (Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.), falling back on default driver creation

**Versions using:**
Serenity - 2.0.27
chromedriver - 2.45
Google Chrome - 71
maven-failsafe-plugin - 2.22.0

**Paralelization executing through:**
```
<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.22.0</version>
				<configuration>
					<parallel>classes</parallel>
					<threadCountClasses>4</threadCountClasses>
					<!--<forkCount>1</forkCount>-->
					<rerunFailingTestsCount>2</rerunFailingTestsCount>
					<systemPropertyVariables>
						<chrome.capabilities.acceptInsecureCerts>true</chrome.capabilities.acceptInsecureCerts>
						<webdriver.chrome.driver>${project.basedir}/src/main/resources/drivers/chromedriver
						</webdriver.chrome.driver>
						<webdriver.gecko.driver>${project.basedir}/src/main/resources/drivers/geckodriver
						</webdriver.gecko.driver>
					</systemPropertyVariables>
				</configuration>
```

Also using **@Concurrent(threads = "4")** anotations in test clases

I would be glad to see any helpful suggestionsfom my case!

**Comment by wakaleo** [comment]
I don't think this is related to Serenity - "Remote driver creation failed" means that no ChromeDriver instance could be created. This can happen when you run too many web tests in parallel. "Too many" will depend on your machine and environment.

**Comment by DmitriyKapeliukh** [comment]
> I don't think this is related to Serenity - "Remote driver creation failed" means that no ChromeDriver instance could be created. This can happen when you run too many web tests in parallel. "Too many" will depend on your machine and environment.

Running 4-5th threads on MacBook Pro with core i7 and 16 gb RAM (I think its pretty enough to create 4 driver instance in one time). Please see attached console logs.

**Comment by DmitriyKapeliukh** [comment]
Running 4-5th threads on MacBook Pro with core i7 and 16 gb RAM (I think its pretty enough to create 4 driver instance in one time). Please see attached console logs.
<img width="1548" alt="screen shot 2018-12-21 at 3 06 45 pm" src="https://user-images.githubusercontent.com/12435225/50344163-8470cf00-0532-11e9-8e35-aebed0294f43.png">

**Comment by wakaleo** [comment]
Do you have any evidence that this is related to the Serenity driver instantiation code? It appears to be purely chromedriver-related. Selenium just creates the driver instances, it is not responsible for how well they cope with load or parallel execution. Maybe put some breakpoints in the DriverServicePool class to see what is happening.

**Comment by DmitriyKapeliukh** [comment]
What I found during debugging the exception. Seems like remote wendriver could not be initialized because it can not connect to the localhost. Any suggestions?
<img width="1268" alt="screen shot 2018-12-21 at 5 04 32 pm" src="https://user-images.githubusercontent.com/12435225/50348939-e6d1cb80-0542-11e9-8674-b3255e0d7626.png">

**Comment by wakaleo** [comment]
Not really - have you asked the ChromeDriver team?

**Comment by DmitriyKapeliukh** [comment]
A similar issue was created in the chrome driver thread.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2714&can=2&start=0&num=100&q=&colspec=ID%20Status%20Pri%20Owner%20Summary&groupby=&sort=

Still no idea which way use to investigate my problem(.

**Comment by DmitriyKapeliukh** [comment]
Hi all!
Chromium group found root cause of this issue and made a commit.
Expecting that new version of chromedriver will contain this fix.

Details:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2714#c12
