### ISSUE TITLE
Browserstack experimental capabilities for chome not working 

### ISSUE THREAD

**Issue by tux4ever** [serenity-bdd/serenity-core#1507]
Since the version 2.21 we cannot execute the chrome tests on browserstack. In the ChromeDriverCapabilities class the w3c option was added to the experimental options by default and cannot be removed, just disabled. Unfortunately browserstack throws the exception "The property '#/' contains additional properties ["w3c"] outside of the schema when none are allowed in chromeOptions" if this property is provided". 

Can you provide a property to completely disable the experimental capabilities for chrome?

**Comment by wakaleo** [comment]
Will be fixed in 2.0.31
