### ISSUE TITLE
Implementating new Ability and destroying the Ability instance after Test

### ISSUE THREAD

**Issue by Dickseng** [serenity-bdd/serenity-core#1509]
Hi,

We are trying to add new Abilities such as Kafka.
After the test is complete, we need to destroy the Kafka consumer, so that there is no leak.

Right now we are doing in the @After annotation.

Wondering if there is a way for the actor to release all abilities and destroy them accordingly in the test lifecycle.
Like how webdriver.quit is handled in the background.

**Comment by nbarrett** [comment]
You could use this Onstage which is a static instance:

```
    @Before
    public void setup(){
        OnStage.setTheStage(new OnlineCast());
    }
```

Then in your test
```
        Actor joe = OnStage.theActorCalled("joe");
        joe.can(DoSomething.withKafka());
```

Then afterwards you can dismiss your cast and all their abilities:

```
    @After
    public void teardown(){
        OnStage.drawTheCurtain();
    }
```
