### ISSUE TITLE
Steps are still executed after test suspend

### ISSUE THREAD

**Issue by frouleau** [serenity-bdd/serenity-core#151]
If I use a AssumptionViolatedException during a step to mark the test as suspended, further step are still executed.
In `StepInterceptor.skipTestMethod()`, the if condition is too restrictive. It should be 
`if ((this.aPreviousStepHasFailed() || testIsPending()) && !this.shouldExecuteNestedStepsAfterFailures()) { `

**Comment by wakaleo** [comment]
Could you submit a pull request?

**Comment by frouleau** [comment]
Done.

**Comment by frouleau** [comment]
Pull request (#152) passed test.
