### ISSUE TITLE
Puppeter support to Serenity

### ISSUE THREAD

**Issue by nshiveg** [serenity-bdd/serenity-core#1512]
Hi John,

Do we have the Puppeter (Goggle provided one) support to serenity? Since our organization(Nokia) are pretty much interested to bring down the Puppeter into our automation framework. 

Regards
Nithin H S

**Comment by wakaleo** [comment]
I’m not familiar with Puppeteer, but since it is a node library, it might make more sense to ask about Puppeteer integration with Serenity/JS.
