### ISSUE TITLE
Support for WinAppDriver for Windows

### ISSUE THREAD

**Issue by RStrizhak** [serenity-bdd/serenity-core#1513]
Hi @wakaleo,

Do you plan to add into Serenity support of Appium Windows Driver ([WinAppDriver](http://appium.io/docs/en/drivers/windows))?

Thanks.

**Comment by wakaleo** [comment]
Not at this stage (I have no way of testing it), but Pull Requests are welcome.

**Comment by pascalra** [comment]
It would be great to have support also for WinAppDriver.

**Comment by wakaleo** [comment]
See previous comment
