### ISSUE TITLE
Accessing a function from a custom web driver

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1514]
Hello. 

I have a custom Web Driver I created:

    public class CustomChromeDriver extends ChromeDriver {
        ...

        public String getDownloadPath(){
            return this.downloadPath;
        }
    }

Also created a relevant custom DriverSource for it:

    public class ChromeDriverSource implements DriverSource {
        @Override
        public WebDriver newDriver() {
            return new ChromeCustomDriver();
        }

        @Override
        public boolean takesScreenshots() {
            return true;
        }
    }

In my test, I am using the above driver as such:

    @Managed(uniqueSessions=true)
    public WebDriver hisBrowser;

I'm able to use the driver successfully. However I am unable to access the getDownloadPath() function, as hisBrowser is of the parent type WebDriver class. 

Is there a way I can access the getDownloadPath() method still?

**Comment by justinhinze** [comment]
If hisBrowser is an instance of CustomChromeDriver try casting it.
`((CustomChromeDriver)hisBrowser).getDownloadPath();`

**Comment by wakaleo** [comment]
You may need to get the proxied driver, e.g. 
```
((CustomChromeDriver)((WebDriverFacade) hisBrowser).getProxiedDriver()).getDownloadPath();
```

**Comment by timothyjmtan** [comment]
Thanks! I will try this out and take it from here. Closing ticket.
