### ISSUE TITLE
How to write custom reporter?

### ISSUE THREAD

**Issue by sandaliqbal1** [serenity-bdd/serenity-core#1515]
@wakaleo 
I want to write a custom reporter for serenity. I wrote a class that implements AcceptanceTestReporter interface and overrode some of the methods but I dont see this reporter getting executed. Can anyone list the steps needed to write and register a custom reporter with serenity?

**Comment by sandaliqbal1** [comment]
Any answers?

**Comment by wakaleo** [comment]
Since this is a usage question and not a defect, stackoverflow or the RocketChat Serenity community (https://serenity-bdd.rocket.chat) would be a better place to ask the question.

**Comment by ssmuthukumaran** [comment]
For creating custom listener you can follow this [page](https://schenkweb.nl/2017/07/11/serenity-bdd-register-a-custom-listener/)
