### ISSUE TITLE
ChromeDriver configuration issues

### ISSUE THREAD

**Issue by jonfreedman** [serenity-bdd/serenity-core#1516]
Using Serenity 2.0.30 I am having issues passing various configuration properties through to Chrome 66.0.3359.139 using ChromeDriver 2.40.

I am attempting to use the following in my `serenity.properties` file:

    chrome.switches=--no-first-run --disable-extensions --headless --window-size=3400,1200
    chrome.experimental_options.useAutomationExtension=false

Based on comparing the ChromeDriver log output from my code vs a colleague who uses Selenium directly we have observed that
 * Serenity is prefixing all arguments with `--` based on [`OptionSplitter`](https://github.com/serenity-bdd/serenity-core/blob/f7e355abcb734d8019df5e94822e415fda88da6c/serenity-core/src/main/java/net/thucydides/core/webdriver/chrome/OptionsSplitter.java) but adds the `test-type` argument without the `--` prefix twice in [`ChromeDriverCapabilities`](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/ChromeDriverCapabilities.java)
 * Whatever options I attempt to set are visible in the log file but not in the `chrome.exe` command line although adding `--no-first-run` does appear to prevent a single test launching Chrome twice.

e.g.

    [0.738][INFO]: COMMAND InitSession {
       "capabilities": {
          "firstMatch": [ {
             "acceptInsecureCerts": false,
             "browserName": "chrome",
             "goog:chromeOptions": {
                "args": [ "test-type", "--no-first-run", "--disable-extensions", "--headless", "--window-size=3400,1200", "test-type" ],
                "extensions": [  ],
                "useAutomationExtension": false,
                "w3c": true
             }
          } ]
       },
       "desiredCapabilities": {
          "acceptInsecureCerts": false,
          "browserName": "chrome",
          "chrome.switches": "--no-first-run --disable-extensions --headless --window-size=3400,1200",
          "goog:chromeOptions": {
             "args": [ "test-type", "--no-first-run", "--disable-extensions", "--headless", "--window-size=3400,1200", "test-type" ],
             "extensions": [  ],
             "useAutomationExtension": false,
             "w3c": true
          },
          "platform": "ANY",
          "version": ""
       }
    }
    [0.741][INFO]: Populating Preferences file: {
       "alternate_error_pages": {
          "enabled": false
       },
       "autofill": {
          "enabled": false
       },
       "browser": {
          "check_default_browser": false
       },
       "distribution": {
          "import_bookmarks": false,
          "import_history": false,
          "import_search_engine": false,
          "make_chrome_default_for_user": false,
          "show_welcome_page": false,
          "skip_first_run_ui": true
       },
       "dns_prefetching": {
          "enabled": false
       },
       "profile": {
          "content_settings": {
             "pattern_pairs": {
                "https://*,*": {
                   "media-stream": {
                      "audio": "Default",
                      "video": "Default"
                   }
                }
             }
          },
          "default_content_settings": {
             "geolocation": 1,
             "mouselock": 1,
             "notifications": 1,
             "popups": 1,
             "ppapi-broker": 1
          },
          "password_manager_enabled": false
       },
       "safebrowsing": {
          "enabled": false
       },
       "search": {
          "suggest_enabled": false
       },
       "translate": {
          "enabled": false
       }
    }
    [0.746][INFO]: Populating Local State file: {
       "background_mode": {
          "enabled": false
       },
       "ssl": {
          "rev_checking": {
             "enabled": false
          }
       }
    }
    [0.767][INFO]: Launching chrome: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-prompt-on-repost --disable-web-resources --enable-logging --full-memory-crash-report --ignore-certificate-errors --load-extension="C:\Users\foo\AppData\Local\Temp\scoped_dir22880_15218\internal" --logging-level=1 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12518 --safebrowsing-disable-auto-update --safebrowsing-disable-download-protection --use-mock-keychain --user-data-dir="C:\Users\foo\AppData\Local\Temp\scoped_dir22880_8941" data:,
    [19.156][INFO]: RESPONSE InitSession {
       "acceptSslCerts": true,
       "applicationCacheEnabled": false,
       "browserConnectionEnabled": false,
       "browserName": "chrome",
       "chrome": {
          "chromedriverVersion": "2.4.226107"
       },
       "cssSelectorsEnabled": true,
       "databaseEnabled": true,
       "handlesAlerts": true,
       "javascriptEnabled": true,
       "locationContextEnabled": true,
       "nativeEvents": true,
       "platform": "Windows NT",
       "rotatable": false,
       "takesScreenshot": true,
       "version": "66.0.3359.139",
       "webStorageEnabled": true
    }
    [19.162][INFO]: COMMAND GetSessionCapabilities {

    }
    [19.162][INFO]: RESPONSE GetSessionCapabilities {
       "acceptSslCerts": true,
       "applicationCacheEnabled": false,
       "browserConnectionEnabled": false,
       "browserName": "chrome",
       "chrome": {
          "chromedriverVersion": "2.4.226107"
       },
       "cssSelectorsEnabled": true,
       "databaseEnabled": true,
       "handlesAlerts": true,
       "javascriptEnabled": true,
       "locationContextEnabled": true,
       "nativeEvents": true,
       "platform": "Windows NT",
       "rotatable": false,
       "takesScreenshot": true,
       "version": "66.0.3359.139",
       "webStorageEnabled": true
    }
    [19.189][INFO]: COMMAND SetWindowSize {
       "handle": "current",
       "height": 1200,
       "width": 3400,
       "windowHandle": "current"
    }
    [29.231][INFO]: RESPONSE SetWindowSize unknown error: cannot get automation extension

Where my colleague's log looks like

     "desiredCapabilities":{
        "browserName":"chrome",
        "goog:chromeOptions":{
             "args":["test-type","disable-extensions","start-maximized","log-path=c:\\temp\\chromedriver.log"],
             "prefs":{
                "download.default_directory":"c:\\Temp\\AppData\\Local\\Temp\\tmp161Ctmp",
                "download.prompt_for_download":"false",
                "profile.default_content_settings.popups":0
            },
             "useAutomationExtension":false
        },
        "loggingPrefs":{
             "browser":"ALL"
        }    
    }

It appears that Serenity should be updated to not add the `--` prefix as well as only setting `test-type` once.

**Comment by jonfreedman** [comment]
Annoyingly if I use ChromeDriver 2.45 I can see these command line switches passed to Chrome as expected but the driver is not compatible with the locked down version of Chrome I have on my desktop.  Is there a compatibility matrix for Serenity with ChromeDriver?

**Comment by wakaleo** [comment]
Serenity just passes the options you provide to WebDriver, so it’s more a question of WebDriver/Chrome compatibility I think

**Comment by jonfreedman** [comment]
Glad you can confirm the `--` makes no difference, I agree that it looks like a WebDriver issue - I am trying to get access to a machine with the latest version of Chrome to test on.

**Comment by wakaleo** [comment]
I'll made the test-type option configurable in the next version so you can turn it off just in case.

**Comment by jonfreedman** [comment]
That might be useful - also note that you're setting it twice...

**Comment by jonfreedman** [comment]
I can confirm that the switches are passed as expected from Serenity -> WebDriver -> Chrome when using ChromeDriver 2.45 so I'm closing the issue.

**Comment by jonfreedman** [comment]
My colleague kindly did some research on this using Selenium directly, for Chrome 64 + ChromeDriver 2.37 / Chrome 66 + ChromeDriver 2.40 args are only passed through to Chrome by using `chrome.switches=--args` and further to that different versions of Chrome expect arguments with different prefixes e.g.

* ChromeDriver 2.37 & 2.40
`chrome.switches=--args -disable-extensions`
* ChromeDriver 2.45
`chrome.switches=--disable-extensions`

I'm not sure how interested you are in supporting old versions of Chrome/ChromeDriver
