### ISSUE TITLE
How can i use different test data for multiple test methods inside a test class?

### ISSUE THREAD

**Issue by skaluva** [serenity-bdd/serenity-core#1517]
hi,
I want to use different test data for different test methods in serenity. In straight junit, i could find various alternatives. But in serenity, im not able to find a way to do it. My scenario:
TestClass
  Test Method 1 with test data 1
  Test Method 2 with test data 2

> @TestData                                               
>     public static Collection<Object[]> testData() throws IOException{
>     	
>     }

Tried to use `SerenityParameterizedRunner` but each test method executes with all test data, which is causing failures during  execution.

Please suggest.

**Comment by wakaleo** [comment]
What would you do in plain JUnit?

**Comment by skaluva** [comment]
@wakaleo there is a plugin available to support my requirement in junit where i can provide test data specific to test method.
https://github.com/TNG/junit-dataprovider

I'm not sure how can i use it with serenity.

**Comment by wakaleo** [comment]
The Serenity parameterised runner extends the normal JUnit one, which doesn't support this feature. It may be possible when we implement JUnit 5 integration (not sure, haven't checked).

**Comment by bahunov** [comment]
Any update on this?

**Comment by kishoreccaus** [comment]
Even I was looking for this option. Sad to hear its not available.

**Comment by Saurav6789** [comment]
Any update on this issue ?
