### ISSUE TITLE
Not able to generate Serenity Report/ BDD Strories display with Springboot and SpringRunner 

### ISSUE THREAD

**Issue by muralij2ee6** [serenity-bdd/serenity-core#1518]
Hi,

My Stories Runner class is
-------------------------------

@RunWith(SpringRunner.class)
@ContextConfiguration(locations = { "classpath:applicationContext-serenity.xml" })
public class StoriesRunnerIT extends JUnitStories implements ApplicationContextAware {

	private ApplicationContext context;

	@Override
	public Configuration configuration() {
		return new MostUsefulConfiguration().useStoryLoader(new LoadFromClasspath(this.getClass())).useStoryReporterBuilder(new StoryReporterBuilder());
	}

	@Override
	public InjectableStepsFactory stepsFactory() {
		return new SpringStepsFactory(configuration(), context);
	}

	@Override
	protected List<String> storyPaths() {		
		return Arrays.asList("stories/testone.story","stories/testtwo.story");
	}

	@Override
	public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
		this.context = applicationContext;
	}

}

Step class
--------------------
@Component
public class testone extends Steps {

	@Autowired
	private BeanSteps beanSteps;

	@Given("some scenario")
public void method(){
}

My Pom Has all dependecies sereneity-core, failsafe, serenity-bdd with versions 2.18.1, 1.4.0 , 1.4.0

![image](https://user-images.githubusercontent.com/30026215/50985867-f5206100-14ca-11e9-80eb-f9a31ca58cce.png)

BDD is not displaying all stories list in JUNIT console as above.

For Maven Run serenity report is generated with no major details.
Console Log:

OutputDirectory : C:\DEV\Git\springboot\BillingPaymentManagement\bdd\target\site\serenity
Merging requirements = [Requirement{name='', type='story' parent = 'null', cardNumber='null'}, Requirement{name='Returned payment conversion bank', type='feature' parent = 'null', cardNumber='null'}, Requirement{name='Returned payment conversion credit card', type='feature' parent = 'null', cardNumber='null'}]
Merging requirements = []
Merged requirements set = [Requirement{name='', type='story' parent = 'null', cardNumber='null'}, Requirement{name='Returned payment conversion bank', type='feature' parent = 'null', cardNumber='null'}, Requirement{name='Returned payment conversion credit card', type='feature' parent = 'null', cardNumber='null'}]
[INFO] REPORTS GENERATED IN C:\DEV\Git\springboot\BillingPaymentManagement\bdd\target\site\serenity
[INFO] REPORT HOME PAGE: C:\DEV\Git\springboot\BillingPaymentManagement\bdd\target\site\serenity\index.html
[INFO] Generating release reports for: []

-----------------------------------------------------------------------------------------------

Seems like it is not picking up the stories properly for serenity report as well as Junit Console.

Any help is greatly appreciate it.

Thanking you,

Regards

**Comment by wakaleo** [comment]
You are running your test as a Spring integration test (`@RunWith(SpringRunner.class)`). You need to use the Serenity runner to produce the Serenity integration.
