### ISSUE TITLE
Robot class in headless chrome is not working

### ISSUE THREAD

**Issue by kbeleta** [serenity-bdd/serenity-core#1519]
Hi I'm using robot for some actions _(i.e. Copy+Pasting path for file upload, keyboard key press)_ in headless chrome but it seems that it's not working, but does work perfectly in regular instance. any suggestion/alternatives? 
i.e:
`Robot robot = new Robot();`
`robot.keyPress(KeyEvent.VK_ESCAPE);`
`robot.keyRelease(KeyEvent.VK_ESCAPE);`

serenity.property
`webdriver.driver=chrome`
`webdriver.chrome.driver = C:\\chromedriver.exe`
`chrome.switches=--headless`

**Comment by wakaleo** [comment]
Can you share the code that does work using the Robot class?

**Comment by kbeleta** [comment]
The same robot code is working in a regular browser instance(chrome, IE, firefox), but NOT when using headless chrome.

**Comment by wakaleo** [comment]
I doubt the Robot class can work in headless mode, since it interacts with the real UI.

**Comment by kbeleta** [comment]
I already tried chord `org.openqa.selenium.Keys;` and actions `org.openqa.selenium.interactions.Actions;` and both didn't work. any suggestions?

**Comment by RomanGlazNew** [comment]
> If that doesn’t work it could be a ChromeDriver bug.
any news about this bug ?

**Comment by wakaleo** [comment]
Closing as not directly related to Serenity.

**Comment by mounahn** [comment]
> I already tried chord `org.openqa.selenium.Keys;` and actions `org.openqa.selenium.interactions.Actions;` and both didn't work. any suggestions?

I'm facing similar issue. 
Did you find any solution???

**Comment by wakaleo** [comment]
This is a Selenium or Chromedriver issue, so better to ask those teams.

**Comment by ppushpanayagam** [comment]
@kbeleta If the element is input type then you can use sendKeys to send the absolute path of the file. This should work.
