### ISSUE TITLE
Delete request is saying executing PUT request

### ISSUE THREAD

**Issue by pradeepyadav-Sc** [serenity-bdd/serenity-core#1523]
I think interaction step description needs update, 
because   it says : @Step("{0} executes a PUT on the resource #resource")
It should be DELETE

![screen shot 2019-01-15 at 1 08 55 pm](https://user-images.githubusercontent.com/24438259/51165808-6c893280-18c7-11e9-9ffb-7ece37bf0eeb.png)

https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay-rest/src/main/java/net/serenitybdd/screenplay/rest/interactions/Delete.java

**Comment by wakaleo** [comment]
Well spotted, thanks
