### ISSUE TITLE
Appium server is never started for single device

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1526]
When a single device is used, and no hub is defined Apiium server pool is not starting the server, if multiple devices are used the server is started in the method localServerUrlFor but for a single device the method configuredAppiumUrl never starts the server.

**Comment by wakaleo** [comment]
The Appium server pool code is pretty experimental, and is entirely community driven, so if you can see any improvements, PRs are welcome.

**Comment by wakaleo** [comment]
Not I’m principle - I love Kotlin! The serenity-email module is 100% Kotlin. Not so much stuff in the other modules as I haven’t set up the gradle scripts.

**Comment by ricardorlg** [comment]
Yeah, I love Kotlin too, and extension methods are just perfect for serenity screenplay implementation.
