### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by verhagen** [serenity-bdd/serenity-core#153]
Already started the improvement, see [documentation-improvements](https://github.com/verhagen/serenity-core/tree/documentation-improvements).

__Questions__
Where are the following artifacts used for?
- `browse-the-web`
- `serenity-rest-assured`
- `serenity-sample-alternative-resources`
- `serenity-test-utils`

Are they for (end) users? Or for the development of the Serenity-BDD framework? Can someone give some background? So I know, if the need to be some where in the README.md, or not.

__PS:__ _See also the linked document, search for `@@@TODO Where are these artifacts used for?`_

**Comment by verhagen** [comment]
@wakaleo Could you have a look at the above update? And explain where the mentioned packages are used for?

So I can make the final changes and create a PR. Thx

**Comment by wakaleo** [comment]
These are new library that haven't been property documented yet:
  - browse-the-web adds WebDriver capabilities to the Journey pattern code in serenity-journey
  - serenity-rest-assured adds support for Rest-Assured

The other two are used in the Serenity build.
