### ISSUE TITLE
Aggregate task could not locate custom exception classes

### ISSUE THREAD

**Issue by ssmuthukumaran** [serenity-bdd/serenity-core#1530]
We are using     serenity core version - 2.0.20,  serenity cucumber version 1.9.21
After test execution is complete on trying to run aggregate gradle task, getting error saying 
Could not find error class: Campus.exceptions.ConfigurationException(Campus.exceptions.ConfigurationException)
java.lang.ClassNotFoundException: Campus.exceptions.ConfigurationException

Do we need to add any dependencies to gradle for these exception classes?

**Comment by ssmuthukumaran** [comment]
not seeing this after upgrading to serenity core version 2.0.34

**Comment by ssmuthukumaran** [comment]
Issue happens when we clear the cache and run aggregat task.
am not sure how to add them as dependency for net.serenity-bdd:serenity-gradle-plugin
am using it as follows 

My **build.gradle** contains following 
buildscript {
repositories {
mavenCentral()
jcenter()
}
dependencies {
classpath("net.serenity-bdd:serenity-gradle-plugin:2.0.20")
}
}

apply plugin: 'net.serenity-bdd.aggregator'

**Serenity.properties** contains:
Serenity.fail.on = serenity.exceptions.ResponseNotReceived

on executing aggregate task getting exception

Could not find error class: serenity.exceptions.ResponseNotReceived(serenity.exceptions.ResponseNotReceived)
java.lang.ClassNotFoundException: serenity.exceptions.ResponseNotReceived
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)

Not sure how to link custom exceptions as dependency to serenity-gradle-plugin in build.gradle

**Comment by wakaleo** [comment]
I presume you need to add a dependency I  your application classes to the gradle plugin, but I don’t know offhand the way to do that (I presume it must be in the gradle docs somewhere)

**Comment by ssmuthukumaran** [comment]
Went through gradle docs couldn't find a way to specify dependencies for a plugin.
Is there any other way to resolve this.

**Comment by wakaleo** [comment]
It’s prettly clearly a gradle issue - the aggregate function needs to be able to find your custom class to use it in the reports, and the gradle plugin doesn’t have this class on its classpath. You get the Sam thing with maven, and need to add a reference to the maven project in the plugin dependencies. I assume there is something similar for gradle plugins. Have you asked the Gradle community?

**Comment by ssmuthukumaran** [comment]
This issue got resolved with serenity version 2.0.49.
