### ISSUE TITLE
Target support multi located element on Android and iOS both

### ISSUE THREAD

**Issue by vuthelinh** [serenity-bdd/serenity-core#1531]
As QA Engineer. I would like to have new feature for Target. That can located mobile element base on the configuration in `serenity.properties`

If `appium.platformName=ANDROID` the Target will be return to **AndroidElement** otherwise **iOSElement**

Finally, We expect the code is like below

```
public static final Target BOX_CHAT = 
            Target.the("box chat filed")
                        .located(MobileBy.id("android_element_id"))
                        .otherLocated(MobileBy.id("iOS_element_id"));
```

**Comment by wakaleo** [comment]
Sounds like a good idea. Maybe something like this:
```
public static final Target BOX_CHAT = 
            Target.the("box chat filed")
                        .locatedForAndroid(MobileBy.id("android_element_id"))
                        .locatedForIOS(MobileBy.id("iOS_element_id"));
```

Could you propose a PR?

**Comment by miles-mason** [comment]
This would be super useful for us too.

**Comment by vuthelinh** [comment]
@Hi @wakaleo 

I have no more experience to create PR on git. Base on the guide here [creating-a-pull-request-from-a-fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

I hope that is correct way. If not pls correct me

**Comment by wakaleo** [comment]
Yes, the GitHub docs are the best source for how to do a PR.

**Comment by miles-mason** [comment]
I'll submit a PR for this since we'll be using this feature shortly.

**Comment by vuthelinh** [comment]
@miles-mason 
I have created one [1535](https://github.com/serenity-bdd/serenity-core/pull/1535)

but have no unit test first. If you can write unit test for this feature. Pls create other one

**Comment by miles-mason** [comment]
#1553 submitted

**Comment by vuthelinh** [comment]
@miles-mason 
Thanks a lot. 

This feature already done v2.0.39
