### ISSUE TITLE
Multiple CSV files are not picked during test execution

### ISSUE THREAD

**Issue by GangadharanS** [serenity-bdd/serenity-core#1537]
Hello guys,

I try to use multiple csv files as input data for my test using @UseTestDataFrom annotation.
and getting following error,

net.thucydides.core.csv.FailedToInitializeTestData

Any immediate help would really be appreciated.

**Comment by wakaleo** [comment]
This is most likely a project specific issue. The CSV import capabilities are documented in https://serenity-bdd.github.io/theserenitybook/latest/junit-data-driven.html. If time is important to you,  have you considered the commercial support packages? See https://johnfergusonsmart.com/serenity-bdd-mentoring/#support

**Comment by GangadharanS** [comment]
@wakaleo 
Thanks for your reply.   I have already gone through the serenity BDD doc. and used annotation like this,
@RunWith(SerenityParameterizedRunner.class)
@UseTestDataFrom("./src/test/resources/CSVs/Types.csv, ./src/test/resources/CSVs/Schedules.csv")
public class Objects_DDT extends CSVHelper {

But my code runs with different iterations mentioned in Types.csv but Schedules.csv doesnt get started.
Am i doing anything wrong here.

my CSV uses comma seperator only.

Thanks
Gangadhar

**Comment by GangadharanS** [comment]
Can Someone help me out on this

**Comment by wakaleo** [comment]
It sounds like a problem with your test classes - possibly the field names in your class don't match the Excel columns.

**Comment by wakaleo** [comment]
Closed for lack of activity
