### ISSUE TITLE
Differentiating between test-cases that can be run in parallel and those that cannot?

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1538]
I'm executing a bunch of test-cases via Selenium Grid fashion. This unraveled an issue where I've found that some test-cases can be run in parallel execution, and some that cannot (i.e. forced to run them sequentially as running in parallel will cause them to affect each other's result).

I would like to check if there is currently a way to handle the orchestration of such test-cases (by way of an annotation, etc) so that the above can be achieved when we run the entire suite in Selenium Grid?

**Comment by wakaleo** [comment]
Seren

**Comment by timothyjmtan** [comment]
thx.
