### ISSUE TITLE
Not precise test method name converting in the log (Maven)  

### ISSUE THREAD

**Issue by NadyaEvstafyeva** [serenity-bdd/serenity-core#1539]
The name of the test method is:
"SYSTEM_Availability_test"
Expected: to be converted to "SYSTEM Availability test"
Actual: "SYSTEM  availability test" (two spaces after "SYSTEM")

**Comment by wakaleo** [comment]
The naming convention assumes either snake_case, camelCase or TitleCase, so the text above confuses the formatting. There will be a fix for this specific case in the next release.

**Comment by wakaleo** [comment]
Fixed in 2.0.34
