### ISSUE TITLE
Iframe

### ISSUE THREAD

**Issue by sonet114882** [serenity-bdd/serenity-core#1540]
Hey john,
i am not able to switch the iframe ..... into my serenity project i have initialize driver.switchto.frame(ID) in my step library. when i run my main test it gives me null point exception . could u please help me out from that...

**Comment by wakaleo** [comment]
Sounds like a usage problem. Have you asked the Serenity community on https://serenity-bdd.rocket.chat?

**Comment by vuthelinh** [comment]
@sonet114882 
You should refer [issues-1374](https://github.com/serenity-bdd/serenity-core/issues/1374)
