### ISSUE TITLE
Add extension to the Chrome Options using SerenityBDD

### ISSUE THREAD

**Issue by samangipudi** [serenity-bdd/serenity-core#1543]
Hi,

I am trying to add an extension to the chrome using serenity.properties file. But I am not able to achieve it. Is there any way to do it?

**Comment by wakaleo** [comment]
See also: https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html

**Comment by RJ05** [comment]
Just did a quick check, this works:

`public class ChromeDriverWithExtension implements DriverSource {
   @Override
    public WebDriver newDriver() {
        try {
            ChromeOptions options = new ChromeOptions();
            options.addExtensions(new File("extension.crx"));
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability(ChromeOptions.CAPABILITY, options);
            return new ChromeDriver(options);
        }
        catch (Exception e) {
            throw new Error(e);
        }
    }

    @Override
    public boolean takesScreenshots() {
        return true;
    }`

`webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = au.com.acme.ChromeDriverWithExtension
thucydides.driver.capabilities = mydriver`

**Comment by wakaleo** [comment]
Using a custom driver is probably the best option at this atage

**Comment by thePantz** [comment]
For anyone that comes across this, use `chrome.extension = path/to/extension.crx`
