### ISSUE TITLE
Firefox NotConnectedException while executing simple Serenity test case by Jeff Nyman

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1546]
I am just starting off on Serenity-Cucumber JVM project with a back ground of Java development and Selenium. As a pre-cursor, I am implementing the 3 part tutorial by Jeff Nyman as a testing ground.
When the test is executed with 'mvn clean verify', the build is Successful. It opens the firefox browser which is just empty. It did not navigate to the URL I had given. And throws these below errors.
**I believe this could NOT be a firefox or gecko driver issue because for the following dependency versions, the Selenium version COULD NOT be > 3.0 **
_```

1. <artifactId>serenity-core</artifactId>version>1.1.36</version>
2. <artifactId>serenity-junit</artifactId><version>1.1.36</version>
3. <artifactId>serenity-cucumber</artifactId><version>1.1.8</version>

```_
**BTW, how can I make the test use the Chrome browser ? I installed 'ChromeDriver.exe ver 2.54' on mac and given it's path in the steps library like below for no use.
 System.setProperty("webdriver.chrome.driver","‎⁨/⁨Users/⁨pnutala/⁨Applications⁩/chromedriver"); **

**Firefox Not Connected Errors:--**
_

```
> [main] INFO net.serenitybdd.core.Serenity - Test Suite Started: Add new todos
> Feature: Add new todos
> [main] INFO net.serenitybdd.core.Serenity -
TEST STARTED: Add a new todo

1. [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.build.directory : null

2. [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.reporting.OutputDirectory : null

3. [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - OutputDirectory : /Users/pnutala/eclipse-photon-workspace/serenity-with-cucumber/target/site/serenity
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

_871	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{a44d6e84-ef80-b241-bfec-dc7f341fddc1}","version":"3.0.0","type":"webextension","updateURL":null,"optionsURL":null,"optionsType":null,"optionsBrowserStyle":true,"aboutURL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"developers":null,"translators":null,"contributors":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"installDate":1544133218000,"updateDate":1544133218000,"applyBackgroundUpdates":1,"path":"/Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi","skinnable":false,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"toolkit@mozilla.org","minVersion":"59.0b5","maxVersion":null}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"userPermissions":{"permissions":["webRequest","webRequestBlocking"],"origins":["<all_urls>"]},"icons":{},"iconURL":null,"icon64URL":null,"blocklistState":0,"blocklistURL":null,"startupData":null,"hidden":true,"installTelemetryInfo":null,"location":"app-system-defaults"}_

4. [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

5. Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows: 

```
Please help me sort this out, so that I can proceed further with my main project.
_

**Comment by wakaleo** [comment]
Not much I can do with this, but most likely a geckodriver/firefox version issue.

**Comment by PrasadNutalapati** [comment]
Mr. John Ferguson Smart;
I have updated the comments because I prematurely posted the issue with out any comments.
Please take a look and help.
Seriously appreciated.

**Comment by wakaleo** [comment]
The versions are too old for recent versions of Firefox - start with http://github.com/serenity-bdd/serenity-cucumber-starter, this has the correct versions.

**Comment by PrasadNutalapati** [comment]
Thanks for the suggestion.
Otherwise, I switched to the  latest ChromeDriver 2.45 or 2.46.
Project working just fine.
