### ISSUE TITLE
Parameterized findBy on WebElementFacade level

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#1549]
`PageObject` class contains a few handy methods to find elements by parameterized xpath/css locators:
```java
    public <T extends net.serenitybdd.core.pages.WebElementFacade> T findBy(String xpathOrCssSelector, Object... arguments) {
        return element(withArguments(xpathOrCssSelector,arguments));
    }

    public List<net.serenitybdd.core.pages.WebElementFacade> findAll(String xpathOrCssSelector, Object... arguments) {
        return findAll(xpathOrCssSelector(withArguments(xpathOrCssSelector,arguments)));
    }
```

Using them I can write more readable code (without `String.format`) when I need to find an element by dynamic locator:
```java
WebElementFacade header = page.findBy("//div[text()='{0}']", "Greetings!");
```

However, these methods are missed on `WebElementFacade` level, so I still have to use `String.format` when I have to find nested elements in context of other `WebElementFacade`:

```java
WebElementFacade message = header.findBy(String.format("//h1[text()='%s']", text));
```

It would be nice to have parameterized `findBy` methods on `WebElementFacade` too.

**Comment by wakaleo** [comment]
Good idea, I'll include these in the next release.
