### ISSUE TITLE
TestOutcome object returns .isError()=true but .getError() = 0

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1550]
For the `TestOutcome` object, I'm seeing instances from my tests where I get the following:

```
TestOutcome outcome = ...  // initialization of object;
outcome.isError() // returns true
outcome.getErrorCount() // returns 0
```

An example to reproduce the above would be a divided by zero exception:

    public void dividedByZero(){
        int i = 123/0;
    }

Is this expected? 

I'm expecting that anytime `.isError()` returns true, the `.getErrorCount()` should always be > 0...

**Comment by wakaleo** [comment]
That would be unusual, but could happen. These are internal API methods with specific usages; the getErrorCount() method counts the number of leaf steps with a result of Error, whereas isError() checks the overall status, so if you set the result manually, or an error occurs outside a step, this could happen.

**Comment by timothyjmtan** [comment]
Aha - I believe then that in my case, it could be due to the error occurring outside a step. Thanks for the advice!
