### ISSUE TITLE
Issue in requirements generation in serenity BDD reports

### ISSUE THREAD

**Issue by zeeshanasgharr** [serenity-bdd/serenity-core#1554]
When using JUnit, the aggregated report does not show the requirements, features, stories tabs.

I have the following property defined in serenity.properties as follows :
serenity.test.root=com.apiautomation.cucumber.steps
serenity.requirement.types=epic,features,stories
max.retries=2
junit.retry.tests=true

![serenity](https://user-images.githubusercontent.com/33282252/52207262-b51c8600-289e-11e9-83a8-5d5c47bad63e.PNG)

**Comment by zeeshanasgharr** [comment]
![jira-serenity](https://user-images.githubusercontent.com/33282252/52207406-2d834700-289f-11e9-8528-e696af9c38c6.PNG)
Here is what I am getting on console

**Comment by wakaleo** [comment]
What does your test package structure look like (the file hierarchy under src/test/java)?

**Comment by zeeshanasgharr** [comment]
![project_structure](https://user-images.githubusercontent.com/33282252/52212656-df763f80-28ae-11e9-9d17-19eb09b85877.PNG)
Here is the project Structure

**Comment by wakaleo** [comment]
If you are using Serenity Cucumber your features directory should be `src/test/resources/features` and you don't need `serenity.test.root`.

**Comment by zeeshanasgharr** [comment]
I have done the said changes in my project. Now no test populate in the report

**Comment by wakaleo** [comment]
I would need to see your full project

**Comment by zeeshanasgharr** [comment]
![new_report](https://user-images.githubusercontent.com/33282252/52215530-0b48f380-28b6-11e9-93a8-5dbcd9ff0512.PNG)
This is new report. Sure Let me know how we can connect for full project. As this is not on git yet. We are using gitlab and repos are private

**Comment by wakaleo** [comment]
Did you update your test runner to point to src/test/resources/features?

**Comment by zeeshanasgharr** [comment]
Its already pointing to that. I have have the previous version and its working fine

**Comment by wakaleo** [comment]
Not much we can do without a sample project reproducing the issue

**Comment by zeeshanasgharr** [comment]
No problem, Problem is sorted out . Thanks a lot for your quick responses

**Comment by JeffGaly** [comment]
hi zeeshanasgharr  how did you fix the issue ?What is the version you are using ?
