### ISSUE TITLE
Executing on Experitest Cloud 

### ISSUE THREAD

**Issue by Errr0rr404** [serenity-bdd/serenity-core#1556]
Hello 
I was trying to run my codes on Experitest Cloud server. but for that, i need to pass an access key and some setProperty. Is there any way can we declare that with serenity?

**Comment by wakaleo** [comment]
I have no knowledge of Experitest Cloud; how would you do this in normal Selenium?

**Comment by Errr0rr404** [comment]
figured a way out .. used provided webDriver in the properties file and created a new driver with required capabilities of the Experitest Cloud.

**Comment by dipakbachhav** [comment]
Hi @Errr0rr404 : 
Can you please let me know how you have resolved this issue?

**Comment by onlybiju** [comment]
@wakaleo From selenium, we are passing like below. 
  private static final String ACCESS_KEY = "some_key";
   private RemoteWebDriver driver;
    private URL url;
    private DesiredCapabilities dc = new DesiredCapabilities();

public void setUp() throws Exception {
        dc.setCapability("testName", "Quick Start Chrome Browser Demo");
        **dc.setCapability("accessKey", ACCESS_KEY);**
        dc.setCapability(CapabilityType.BROWSER_NAME, "chrome");
        driver = new RemoteWebDriver(new URL("https://company.experitest.com/wd/hub"), dc);
    }

**Comment by onlybiju** [comment]
@dipakbachhav @Errr0rr404 @wakaleo  
Let me know if you found any solution to pass ACCESS_KEY from serenity.properties file?

**Comment by wakaleo** [comment]
Any property in the `webdriver` section of `serenity.conf` will be passed to WebDriver as a capability, e.g.
```
    webdriver {
      # Driver must be remote for Saucelabs
      driver = remote
      base.url = "https://bdd-flyer.herokuapp.com"

      # W3C Capabilities
      screenResolution = "1280x1024"
      strictFileInteractability = true
      unhandledPromptBehavior = "ignore"
    }
```

**Comment by onlybiju** [comment]
Thanks a lot @wakaleo , that helps.

**Comment by nannsz** [comment]
https://bdd-flyer.herokuapp.com
This url does not available at all 

The following error is showing on the page.
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
