### ISSUE TITLE
Touch Action cannot be appplied.

### ISSUE THREAD

**Issue by sebastianciocan** [serenity-bdd/serenity-core#1561]
Hello
When I try to use the touch actions the following message appears.
press(io.appium.java_client.touch.offset.PointOption) in TouchAction cannot be applied to (io.appium.java_client.MobileElement)

new TouchAction((MobileDriver) getDriver()).press(element).waitAction(Duration.ofMillis(1000)).release().perform();

**Comment by sebastianciocan** [comment]
I've managed to make it work with:
TouchAction action = new TouchAction(getProxiedDriver());
        action.longPress(ElementOption.element(getDriver().findElement(By.id(idSelector))))
                .release().perform();

**Comment by wakaleo** [comment]
getDriver() will return a WebDriverFacade, which is not a MobileDriver, so your solution is probably the best.
