### ISSUE TITLE
Serenity reports shows 0 steps but test passed if junit.Assume is used in before method

### ISSUE THREAD

**Issue by BushnevYuri** [serenity-bdd/serenity-core#1562]
Hello guys,

We will be very glad if you can help with a fix or point out the place where it can be fixed.
We want to ignore some tests based on some conditions via before method. If you use "junit.Assume" which doesn't match condition then the test is marked as ignored in JUnit as expected (standard usage of this method). This is quite common way of ignoring tests in JUnit and it works perfect in case you use just JUnit itself. But serenity report shows this test as passed anyway having 0 steps inside. 

How we ignore:
`
 @Before
 public void beforeMethod() {
     org.junit.Assume.assumeTrue(someCondition());
 }
`

Serenity report: 
<img width="1038" alt="screenshot 2019-02-07 at 12 04 52" src="https://user-images.githubusercontent.com/4463392/52403984-9dc4df00-2ad0-11e9-9890-a2b9c49b22a6.png">

**Comment by wakaleo** [comment]
This would be in the JUnitRunner class in serenity-junit, which I don't think would know what to do with an Assume failure, so it must just ignore it but not trigger the correct outcome in the StepEventBus. Please feel free to take a look.

**Comment by BushnevYuri** [comment]
@wakaleo Thanks. Unfortunately, couldn't find easy tweak. Will try to back to it later.

**Comment by adeellis** [comment]
**Additional info which may help:**
I have 0 steps showing on my report but all tests have passed which seems like similar behaviour to the original post. 
I am running a project with JUnit tests only (no cucumber tests, no cucumber dependencies in the pom). 
If I use serenity versions 2.1.6, 2.2.0, 2.2.2, 2.2.5  the steps show correctly on the report when I drill into them. 
The steps disappear in version 2.2.12 and later versions.
If I run the same project with a later version of serenity e.g. 2.2.12 (with no changes made to my project) the steps show as 0 in the report. The tests still all are running successfully as I can see them in the console and on the report home page.

https://github.com/serenity-bdd/serenity-core/#what-is-the-latest-stable-version-i-should-use

**Comment by anshulchhajed** [comment]
Can we use @Autowired instead of @Steps annotation?

**Comment by wakaleo** [comment]
No

**Comment by sandy340** [comment]
any suggestion for above problem as i have tried all versions as mentioned above but still step showing 0 
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/37815639/184701770-1e12ec63-5ade-4fa2-ac3b-9aa9e71bbc36.png">

**Comment by wakaleo** [comment]
> any suggestion for above problem as i have tried all versions as mentioned above but still step showing 

You are commenting on a closed issue relating to an old version of Serenity - you might need to provide some more details about the problem you are having.
