### ISSUE TITLE
Mockito dependency in main

### ISSUE THREAD

**Issue by dbirch-cognitoiq** [serenity-bdd/serenity-core#1571]
We're seeing an issue with our unit tests for our project failing due to 2.0.40 pulling a Mockito dependency into main.

From what I can see, a mocked Step object is returned in the StepInterceptor in the skipStepMethod.

Is there any way this could be achieved without having to use Mockito as this is currently causing us some issues?

I will have a look through the code and see if I can suggest a different way!

**Comment by wakaleo** [comment]
Have a look, but I have tried and failed to remove the need for Mockito in the past - there is simply no equivalent library that would do the same job in one particular case.

**Comment by dbirch-cognitoiq** [comment]
I think our particular issue is caused by the mockito-core being 2.23.4, which is slightly newer than 2.23.0 which is pulled in by the latest published PowerMockito version.

I could probably just force the version for Serenity back to 2.23.0 for now, which would solve our immediate issues. Given the usage in main I can't see an issue with this.

As a quick fix for me and anyone else using PowerMockito, and given it is only used for a single mock in main, would a quick fix be to just push this back to 2.23.0 (or some even earlier version) in the gradle.properties to avoid these kind of conflicts?

**Comment by wakaleo** [comment]
That would make sense.

**Comment by dbirch-cognitoiq** [comment]
No worries, I'll do that now :)
