### ISSUE TITLE
I can't run the TestRunner.java file to generate StepDefinitions instead it is kicking off the serenity tests

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1572]
1. I created a feature file in src/test/resources/datahub/ExtractExecutionHistory.feature
2. Created stepdefinitions file in src/test/java/stepdefinitions/ExtractExecutionHistoryStepDefinitions.java
3. Created a Steps file in src/test/java/steps/PramaDatahubPageStep.java
4. Created Runner file in src/test/java/ExtractExecutionHistoryTestRunner.java and it's contents are as follows...
`import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import cucumber.api.SnippetType;
import net.serenitybdd.cucumber.CucumberWithSerenity;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
	    features = "src/test/resources/datahub/ExtractExecutionHistory.feature",
		dryRun = false,
		strict = false,
	    // glue = "src/test/java/stepdefinitions/",
	    //tags = { "~@wip","~@notImplemented","@sanity" },
	    plugin = {"pretty", "html:target/cucumber-html-report"}, //pretty, progress, rerun, usage
       //	plugin = { "pretty" }, //pretty, progress, rerun, usage
		snippets = SnippetType.CAMELCASE	// CAMELCASE,UNDERSCORE	
	    )
public class ExtractExecutionHistoryTestRunner {
}`

When I right click the TestRunner file and run as JUnit test.. it is kicking off Serenity tests instead of generating the stepdefinition stub methods. What is the mistake I am doing ? 

Your help is appreciated.

**Comment by wakaleo** [comment]
What do you mean "it is kicking off Serenity tests"? 

For info, the Cucumber convention is to put feature files in and under src/test/resources/features.

**Comment by PrasadNutalapati** [comment]
I mean  it is running the serenity tests like invoking the website, logging in and acting on the page like clicking etc., The proper serenity-cucumber test runs.
You are correct about the location of feature files. But our team is following this approach.
Do you think it is because of it this is happening?

**Comment by wakaleo** [comment]
I don't know why it would do that, I would need to see the whole project. What do you mean "the proper serenity-cucumber test". As opposed to what?

**Comment by PrasadNutalapati** [comment]
OK. Ok. John !
It is unfair to ask you to solve my mess.
I will correct the location of the feature file. As per info, do you think, my test runner is in proper place ?

**Comment by wakaleo** [comment]
As per Java conventions, it should be in its own package and not in the root package. But I would expect that class to only run scenarios in the feature file you referenced. However, if you run mvn clean verify, it will also run any other test runner classes as well.

**Comment by PrasadNutalapati** [comment]
John !
Great info !
Do you  think src/main/java/runner/TestRunner.java is a good choice ?

**Comment by wakaleo** [comment]
Yes, that would work.

**Comment by PrasadNutalapati** [comment]
I am taking that src/main/java/runner/TestRunner.java is a good choice.
Thank you very much John, for spending time to help me out of your very busy activities.

**Comment by PrasadNutalapati** [comment]
Good things ! 
After I moved TestRunner.java to src/main/java/starter/TestRunner.java, when I right click and say 'run as JUnit Test' it is generating step definition stub methods(Given, When, Then etc.) instead of running the serenity tests like when we do 'mvn clean verify'.
Thanks John ! For guiding !

**Comment by PrasadNutalapati** [comment]
I take back my words ! Sorry John !
After moving TestRunner.java to src/main/java/runner/TestRunner.java, the right click and Run as "JUnit test" worked well to output stepdefinitions(@Given, @When,@Then that kind of thing.) instead of running the Serenity tests.
Also my pom.xml contains...
`<plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <includes>
                        <include>**/*TestRunner.java</include>
                    </includes>`
to make sure the failsafe plugin picks up the TestRunner and runs the tests.

But after completing all the implementation of methods, when I ran 'mvn clean verify', it DID NOT execute the tests, instead said 
```
**[INFO] Generating test results for 0 tests**
Then I moved my TestRunner.java back to `src/test/java/starter/ExtractExecutionHistoryTestRunner.java`

it started giving below console output

[INFO] BUILD SUCCESS, but
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 5, Time elapsed: 1.875 s
[INFO] Results:
[INFO] 
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1
```
What is the deal here ? Why is the framework so flaky ?

**Comment by wakaleo** [comment]
This is nothing to do with the framework, but more to do with your maven configuration. Check the configuration of your surefire and failsafe plug-ins to make sure they find the right runner classes

**Comment by PrasadNutalapati** [comment]
Sure. 100% agree.
Thanks for suggesting the answer.
This is to do with the plug-ins and/or pom.xml file.
I forgot but tweaking either of places, this has gone away. Very tricky and fragile, in fact.

**Comment by ashasingh85** [comment]
Hi PrasadNutalapati, Could you please let me know what changes have you done to make it run? As I am also facing the same issue.
