### ISSUE TITLE
When ran the TestRunner.java file, asked "to implement missing steps", even when that same step was copied to stepDefinitions file.

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1573]
When I am starting off with a feature file, I have a simple 3 or 4 step feature file.  When I ran the Runner file and the step definition stub methods are generated by JUnit in the console, I copied and pasted in to the step definitions file. My featue file is 
`Scenario Outline: Navigate to Extract History page from the List page 
               Given the User logs into the PRAMA Datahub website successfully with userId "<uId>" and passcode "<pacman_passcode>"
               **Then the User lands on  page “<title>”**
               When status column-cell has value “Ready”
               When last run column-cell has “uId” and “some date” populated
 	           Then the User is redirected to the extract page
 	           
Examples:	
	|  uId        |              pacman_passcode                                          | title  |
    | pnxxxutala |  UL#3aLm@Qs%fT#%*@n*!47l                               | Datahub|`

Later I added an additional @Then step, which is duly reported as below, which I copied to the step definitions file and implemented the actions also. But still I am getting the same message again, and again. Why it is not recognizing the @Then step, which was added  ?

`You can implement missing steps with the snippets below:

@Then("^the User lands on  page “Datahub”$")
public void theUserLandsOnPageDatahub() {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}`

Your help is highly appreciated.

**Comment by wakaleo** [comment]
Try @Then("^the User lands on page \“Datahub\”$")

**Comment by PrasadNutalapati** [comment]
Thanks for the input John !
My intention is to supply 'title' with a value 'Datahub' as an input from the table.

**Comment by wakaleo** [comment]
In that case in needs to be a regular expression, e.g.

```
@Then("^the User lands on page \“(.*)\”$")
public void theUserLandsOnPage(String pageName) {
```

**Comment by PrasadNutalapati** [comment]
Connecting the feature file with StepDefinitions java file is a major trick with Serenity or even Cucumber project.

- NEVER EVER, NEVER EVER EDIT YOUR FEATURE FILE WITH MS WORD and copy it over to IDE. 
The quotation marks are NOT compatible.

- Plus please check your exact feature-scenario step string with the string above the @Given-When-Then step. They need to match 100%.

- Some times the IDE introduces {String} in place of a "some string" in the scenario step. You need to replace it with regEx like..\"([^\"]*)\" or an equivalent.

**Comment by saifeddinenas** [comment]
Anyone reading this and writing his features in french you need to know that (é, è, à, ê...) or any kinf of those letters will generate the issue.
