### ISSUE TITLE
Reports not aggregated when rerunFailingTestsCount is set to a value

### ISSUE THREAD

**Issue by abhilashsiyer** [serenity-bdd/serenity-core#1574]
So, I was looking to get the rerunFailingTests from surefire plugin into my serenity project. I configured my pom as below : 

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M3</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit47</artifactId>
                        <version>3.0.0-M3</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <skipTests>false</skipTests>
                    <rerunFailingTestsCount>1</rerunFailingTestsCount>
                </configuration>
            </plugin>

So, when I run my tests using mvn clean test serenity:aggregate -Dtags=xxx

The failed case did re run but I couldn't find index.html in target/site/serenity. 

I do get an aggregated report when tests pass or fail , when I don't have rerunFailingTestsCount and use clean verify to run the tests.

 Its only when I have the rerunFailingTestsCount property set and I have a test failure, I don't get an aggregated report.

Any advise on any configuration that needs to be done ?

**Comment by wakaleo** [comment]
You will need to give a bit more detail...

**Comment by abhilashsiyer** [comment]
@wakaleo Thanks for the quick reply mate ! I have updated the details above.

**Comment by wakaleo** [comment]
I’ve  not used that feature (it’s a feature of the maven surefire plugin, not Serenity); but surefire will fail the build before it gets to the aggregate phase if there are failures, so it’s probably normal behaviour. Have you tried with the failsafe plugin?

**Comment by abhilashsiyer** [comment]
Right, that makes sense. When I run serenity:aggregate after , Then I would get an aggregate report which is fine in my CI pipeline. Closing this issue.
