### ISSUE TITLE
ElementNotVisibleException:  Timed out after 2 seconds. Element not available

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1579]
I am trying to click a table cell of a column called 'status' having a value like 'Ready' to click.
When the page can accommodate only so many rows, and those rows with status as 'Ready' are not visible unless you scroll down, I am getting this error.
```
[ERROR] Navigate to Extract History page from the List page(Data Extract List Page)  Time elapsed: 19.26 s  <<< ERROR!
org.openqa.selenium.ElementNotVisibleException: 
Timed out after 2 seconds. Element not available
```
When the test is running when I scroll the page manually, the test is succeeding, otherwise failing throwing the above error.

Can we make Selenium to scroll the page down, when it is necessary ?

**Comment by wakaleo** [comment]
It depends on whether the elements are in the DOM and not visible, or (as with some JS components) they are generated dynamically as you scroll down. For the first case, you can use a Selenium action to move to the element in question (or use the `moveTo()` method in Serenity). If it is the second case, it is harder as Selenium can only interact with things already present in the dom.

This is more a question for the https://serenity-bdd.rocket.chat community.

**Comment by PrasadNutalapati** [comment]
Some how this issue is related to one another issue I reported at
https://github.com/serenity-bdd/serenity-core/issues/1595

So, closing the issue.
