### ISSUE TITLE
Report: Cannot gennerate right text when question using lambda expression

### ISSUE THREAD

**Issue by giang-nguyen-niteco** [serenity-bdd/serenity-core#1580]
When I used funtion lambda in Question, I got the wrong text in report. I follow the guide in:
https://serenity-bdd.github.io/theserenitybook/latest/screenplay-selenium-tasks.html#_reading_text

Serenity version: 2.0.40
OS: Window 10
Chrome: 71.0.3578.98
Chromedriver: 2.46

![2019-02-18_9-45-50](https://user-images.githubusercontent.com/44698518/52925212-aafc8c00-3362-11e9-923a-fb8f32b99074.png)

![2019-02-18_9-44-51](https://user-images.githubusercontent.com/44698518/52925215-b059d680-3362-11e9-94cb-241861ff437d.png)

**Comment by wakaleo** [comment]
If you use lambdas for questions you need to include a description in the should() method, eg “theActor.should(seeThat(“the user name”, TheUser.name(), equalTo(“Tim”)))”

**Comment by giang-nguyen-niteco** [comment]
Thank you so much! It works.

**Comment by scooti9** [comment]
@wakaleo what if I use lambda for Question and then I have variable eg. `private static Question<String> whiteColor;` and I want use this variable in @Step

eg.
`@Step("{0} see that cancel button have appropriate colors for #whiteColor and #blueColor after hover")`

What can I do in this situation?
