### ISSUE TITLE
Could not changes Firefox timeout capabilities through serenity driver capability  

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [serenity-bdd/serenity-core#1582]
<img width="1233" alt="screen shot 2019-02-18 at 2 27 39 pm" src="https://user-images.githubusercontent.com/12435225/52953840-4b69a500-3391-11e9-9d84-3723ece4d3e9.png">
Hi all.

I want to change Firefox timeout properties and I set 
**serenity.driver.capabilities=timeouts:{implicit:60000, pageLoad:60000, script:60000};** 
into serenity.properties file. But while debugging a test I saw that timeouts do not change.

May I do something wrong?

**Comment by wakaleo** [comment]
How would you do this in plain Selenium?
