### ISSUE TITLE
Support attaching multiple files to a Scenario or Example

### ISSUE THREAD

**Issue by miles-mason** [serenity-bdd/serenity-core#1583]
We've been using the functionality [described here](https://serenity-bdd.github.io/theserenitybook/latest/living-documentation.html#_adding_additional_evidence) to attach additional information to our tests. Unfortunately only one file is supported per step, so just the last file which we attach is displayed on the report. To get around this, I created an `Interaction` so a new step is created per file we have to attach. But this falls over if a preceding step fails, because all subsequent steps are skipped. Thus, we get no attached logs on a failing scenario, which is precisely when we need them most.

Desired behaviour:
Multiple files can be attached in an `@After` hook, which are unique per example or scenario and are always attached regardless of whether the scenario passes or fails.

**Comment by wakaleo** [comment]
Implemented in 2.0.42
