### ISSUE TITLE
withAction().keyDown(Keys.SHIFT) throws org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement for Firefox

### ISSUE THREAD

**Issue by lega-land** [serenity-bdd/serenity-core#1584]
This code 
```
loginPage.open();
        loginPage.withAction()
                .doubleClick(loginPage.find(By.cssSelector("tr.odd:nth-child(1) > td:nth-child(2)")))
                .keyDown(Keys.SHIFT)
                .click(loginPage.find(By.cssSelector("tr.odd:nth-child(3) > td:nth-child(3)")))
                .keyUp(Keys.SHIFT)
                .perform();
```
throws
```
org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '...', ip: '...', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteKeyboard.pressKey(RemoteKeyboard.java:46)
	at org.openqa.selenium.interactions.KeyDownAction.perform(KeyDownAction.java:46)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:34)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:642)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:595)
``` 
`loginPage` is using `@DefaultUrl("https://datatables.net/")` for example.

'Pure' selenium code has no errors:
```
WebDriver driver = new RemoteWebDriver(new URL("localhost:4444/wd/hub"), DesiredCapabilities.firefox());
        driver.get("https://datatables.net/");

        new Actions(driver)
                .doubleClick(driver.findElement(By.cssSelector("tr.odd:nth-child(1) > td:nth-child(2)")))
                .keyDown(Keys.SHIFT)
                .click(driver.findElement(By.cssSelector("tr.odd:nth-child(3) > td:nth-child(3)")))
                .keyUp(Keys.SHIFT)
                .perform();
```
Also no problem with `WebDriver driver = new FirefoxDriver();`

Firefox 65.0.1
Geckodriver 0.24.0
serenity-core 2.0.40
serenity-cucumber 1.9.31

**Comment by wakaleo** [comment]
Can you provide a sample project to reproduce the issue?

**Comment by lega-land** [comment]
`Tests` class contains JUnit tests for 'pure' selenium cases and `CucumberFeatureRunner` for CucumberWithSerenity runner class.
[keyDown.zip](https://github.com/serenity-bdd/serenity-core/files/2880135/keyDown.zip)

**Comment by lega-land** [comment]
A bit of digging:
I see the difference in workflow at `org\openqa\selenium\interactions\Actions.java` method `perform`. While selenium 'performs' in line 639 `((Interactive) driver).perform(sequences.values())`, serenity goes via line 642 `fallBack.perform()` because of ClassCastException `net.thucydides.core.webdriver.WebDriverFacade cannot be cast to org.openqa.selenium.interactions.Interactive`. So looks like the fix might be to make `WebDriverFacade`  implement `Interactive`

**Comment by wakaleo** [comment]
That would be logical - I will take a look later this week, or feel free to make a PR (it should be a pretty simple change)

**Comment by lega-land** [comment]
Also in `net.serenitybdd.core.pages.PageObject#withAction` it seams strange to check `getDriver() instanceof WebElementFacade`. Shouldn't it be `getDriver() instanceof WebDriverFacade`?

**Comment by lega-land** [comment]
@wakaleo just opened PR. Please take a look. Thanks!

**Comment by wakaleo** [comment]
Will be deployed in 2.0.41

**Comment by lega-land** [comment]
@wakaleo Thanks! And please take a look at corrected fix https://github.com/serenity-bdd/serenity-core/pull/1587. Looks like better fix

**Comment by lega-land** [comment]
@wakaleo is there ETA for 2.0.41? Really waiting for it :)
