### ISSUE TITLE
WebElement is locatable using cssSelector, xpath in the browser, plus in the Serenity code, it is found to be not null, but it is NotPresent, NotClickable, NotEnabled. How to deal with it?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1585]
This may be a Serenity issue or Selenium issue or Angular issue. I don't know..
I am having a button element with the following html code. This is an angular website, though.
```
<div class="col-xs-12 col-sm-3 col-sm-push-6 col-lg-3" css="1">
<button class="btn btn-secondary pull-right" style="background-color: #00A6CA; border-color:#00A6CA;" type="button">
<span aria-hidden="true" class="fa tufa-plus-circle-o" style=""></span>
NEW EXTRACT 
</button>
</div>
```
I used xpath as **_//button[contains(text(),'NEW EXTRACT ')]_** and css Selector as **'button.btn.btn-secondary.pull-right'**. Both identified the button one on one (not multiple) in the browser console. When I used either of them in the  page object code like...
               ```
 System.out.println("@@@@@@@@@@@ is NOT null> "+(newExtractBtn != null));
		System.out.println("@@@@@@@@@@@ to string> "+newExtractBtn.toString());
		System.out.println("@@@@@@@@@@@ is present> "+newExtractBtn.isPresent());
		Thread.sleep(10000);
		System.out.println("@@@@@@@@@@@ Thread sleep for 10sec");
		newExtractBtn.waitUntilEnabled();
		System.out.println("@@@@@@@@@@@ waited until enabled");
		newExtractBtn.waitUntilPresent();

I also tried chaining the wait methods like...
newExtractBtn.waitUntilPresent.waitUntilClickable().click()  with no better result.
```
I am getting out put as 
@@@@@@@@@@@ is NOT null> true
@@@@@@@@@@@ to string> ExtractExecutionHistoryPage.newExtractBtn
@@@@@@@@@@@ is present> false
@@@@@@@@@@@ Thread sleep for 10sec

 

> net.thucydides.core.webdriver.exceptions.ElementShouldBeEnabledException: Expected enabled element was not enabled
> Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for ExtractExecutionHistoryPage.newExtractBtn to be enabled (tried for 5 second(s) with 100 milliseconds interval)

As the exception saying can we make the Serenity wait for some bigger wait like 10 sec instead of 5 sec ? Or would it solve the problem ?

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/theserenitybook/latest/page-objects.html#_working_with_asynchronous_pages for details on Serenity waits. But if Selenium says the element cannot be interacted with, then it is usually the case. Ensure that the element you are interacting with is the one you think it is.

**Comment by PrasadNutalapati** [comment]
Thank you very much John !
I will be studying the asynchronous _pages you had suggested.
BTW, I am wondering the chaining the wait methods from Serenity have no such effect ? Like 
WebElementFacadeElm.waitUntilPresent().waitUntilEnabled().waitUntilClickable().click();
Or should I be calling them one after another sequentially?

**Comment by PrasadNutalapati** [comment]
From the exception message...
```
net.thucydides.core.webdriver.exceptions.ElementShouldBePresentException: 
Expected condition failed: waiting for ExtractExecutionHistoryPage.newExtractBtn to be present (tried for 5 second(s) with 100 milliseconds interval)

Caused by: org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for ExtractExecutionHistoryPage.newExtractBtn to be present (tried for 5 second(s) with 100 milliseconds interval)
```

I am looking for any means of overriding the default 5 sec wait period with 100millisecond polling interval, in Serenity ? With this, meaning by increasing it to 10sec or so, I believe the element would become Enabled and Clickable even though, it is physically seen on the page! Right ?

**Comment by PrasadNutalapati** [comment]
Some how this issue is caused by the issue I reported at
https://github.com/serenity-bdd/serenity-core/issues/1595.
So closing.
