### ISSUE TITLE
empty page

### ISSUE THREAD

**Issue by punkratz312** [serenity-bdd/serenity-core#1588]
Hi,

I´m trying to use serenity just by taking the example but its not working at all.
The Webdriver does not open any page, so nothing can work. 

Please see my test and the outcome:

![serenity](https://user-images.githubusercontent.com/8830888/53099258-b1873100-3525-11e9-8e9c-0746180c250c.png)

![empty page](https://user-images.githubusercontent.com/8830888/53099254-ad5b1380-3525-11e9-9a22-a2a21d2577d7.png)

**Comment by wakaleo** [comment]
That is usually a WebDriver/browser compatibility issue

**Comment by ricardorlg** [comment]
Can you post your code, are un opening the page from the steps class?

**Comment by punkratz312** [comment]
> That is usually a WebDriver/browser compatibility issue

firefox acts just the same

**Comment by punkratz312** [comment]
@ricardorlg plz see the screenshot, there is no more other serenity code i guess

**Comment by punkratz312** [comment]
@wakaleo any idea why the scenarion wont work at all user page gets not injected if i remove the WebDriver variable in the test. Even tho i set it via application.properties it only works if i declare this unwanted unused variable. thanks

**Comment by wakaleo** [comment]
This symptom indocates an incompatibility between your driver (geckodriver/chromdriver), the version of the browser and/or the version of Selenium,. Make sure you have the latest versions of all. It is unrelated to Serenity or to your code.

**Comment by wakaleo** [comment]
Try starting with one of the starter projects (e.g. https://github.com/serenity-bdd/serenity-junit-starter) which have all the latest versions included.

**Comment by wakaleo** [comment]
For JUnit UI tests, you need to declare a Webdriver variable. That's just the way it works.

**Comment by punkratz312** [comment]
@wakaleo will try that. thanks for the quick response.

**Comment by punkratz312** [comment]
@wakaleo I tried the example: https://github.com/serenity-bdd/serenity-junit-starter

It works but there is no browser interaction so its not what my issue is about.

**Comment by punkratz312** [comment]
@wakaleo I´ve adopted the example, same issue. In my example i used the same latest version 2.0.40 so i guess chrome evolved and serenity or whatever is on chars for compatibility has not.

![image](https://user-images.githubusercontent.com/8830888/53152610-4b96ba00-35b6-11e9-8fba-5c6b389ebc62.png)

**Comment by wakaleo** [comment]
Have you called open() on that page?

**Comment by punkratz312** [comment]
@wakaleo nope. But now i did and it solved the issue. As i understood the documentation this should be done automatically by webdriver i guess.

**Comment by wakaleo** [comment]
No, you need to call the open() method to tell Webdriver to open the browser at the starting page
