### ISSUE TITLE
Search box in an angular website can't be filled with text 

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1589]
This issue is related with another issue already asked in this forum.
https://github.com/serenity-bdd/serenity-core/issues/1585 

While trouble shooting this problem, I tested with another web element which is a search box, whose code is like....
```
<div class="col-xs-12 col-sm-3 col-sm-push-7 col-lg-3" xpath="1">
<input class="form-control" ng-model="filterText" placeholder="Quick Search" type="text">
</div>
```
I used **ngWebDriver** to interact with this angular website elements as below.
```
waitForAngularRequestsToFinish();
ChromeDriver.findElement(ByAngular.model("filterText")).sendKeys("ABCD");
```
Not only I could not fill the input box, I am also getting the following exception.
```
org.openqa.selenium.NoSuchSessionException: 
Session ID is null. Using WebDriver after calling quit()?
```

Please help me, identifying the problem.

**Comment by wakaleo** [comment]
Could you post more of the code you are using?

**Comment by PrasadNutalapati** [comment]
Thanks for coming to rescue John ! I desperately needed it.
The web page code is as given below, next to a problematic button from the issue reported previously https://github.com/serenity-bdd/serenity-core/issues/1585 

```
<div class="row">
<div class="col-xs-12 col-sm-3 col-sm-push-7 col-lg-3">
<input class="form-control" ng-model="filterText" placeholder="Quick Search" type="text">
</div>
<div class="col-xs-12 col-sm-3 col-sm-push-6 col-lg-3">
<button class="btn btn-secondary pull-right" style="background-color: #00A6CA; border-color:#00A6CA;" type="button">
<span aria-hidden="true" class="fa tufa-plus-circle-o" style="margin-right: 5px;">
</span>
NEW EXTRACT 
</button>
</div>
</div>
```
The code I used to enter text in to the search box is 
```
waitForAngularRequestsToFinish();// Let angular finish it's asynchronous application processing.
PageUtilities.getDriver().findElement(ByAngular.model("filterText")).sendKeys("ABCD");
```
PageUtilities.getDriver() returns the ChromeDriver instance, which is a WebDriver.

I am getting this exception.
```
org.openqa.selenium.NoSuchSessionException: 
Session ID is null. Using WebDriver after calling quit()?
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MCHIFVFXP0E5', ip: 'fe80:0:0:0:31:c066:f58b:c2ad%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.3', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO]
```

**Comment by wakaleo** [comment]
Are you managing the driver yourself? Why do you need the `PageUtilities` class?

**Comment by PrasadNutalapati** [comment]
I am using PageUtilities for some helper methods, which might be needed by any test case any where.
Given below.
```
public class PageUtilities {
	public static WebDriver chromeDriver;
	public static NgWebDriver ngdriver;

	
	
    /**
     * Configures the Chromedriver for the underlying Selenium
     * based on which operating system you are using.
     */
	public static void configureChromeDriver() {
        String os = System.getProperty("os.name").toLowerCase();
        if(os.contains("mac")) {
            System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + ("/chromedriver"));
        }else {
            System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + ("\\chromedriver.exe"));
        }
    }

    /**
     * Sets and loads the Chromedriver for running the test steps
     */
	public static void setChromeDriver(PageObject pageAtHand) {
		chromeDriver = getDriver();
        pageAtHand.setDriver(chromeDriver);
        pageAtHand.getDriver().manage().deleteAllCookies();
    }
	/**
	 * Provides you the WebDriver instance of the ChromeBrowser.
	 * @return
	 */
	public static WebDriver getDriver() {
	  if(chromeDriver == null) {
		chromeDriver = new ChromeDriver();
        chromeDriver.manage().window().maximize();
	  }
      return chromeDriver;
	}
```

**Comment by wakaleo** [comment]
If you are using Serenity you should let Serenity manager the driver instances; the code you have shown will not work with Serenity

**Comment by PrasadNutalapati** [comment]
Point accepted.
How do I get the instance of the WebDriver(), particularly ChromeDriver in my case, whenever I need it ? Will you please point me to the API call, how to get the instance ?

Appreciate the guidance.

**Comment by wakaleo** [comment]
Call getDriver() in any PageObject or UIInteractionSteps class. But you hardly ever use the driver directly in Seenity. If you need to find an element on the fly, use the find() method.

https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html

**Comment by PrasadNutalapati** [comment]
Awesome !
Ignorance of me !
```
@RunWith(SerenityRunner.class)                                              
public class WhenWritingWebTestsInSerenity {
------
--------
}
```
Normally we were told to use **<TestRunner>.java** class with the following
```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        features= "path\to\feature \file"
         glue .    = "stepdefinitions folder"
       ------
          ---------
}
```
The testing class<blah_blah_StepDefintions.java> starts with the implementation of feature file, Step Definitions. How and where from this annotation and WhenWritingWebTestsInSerenity class come from ?
```
@RunWith(SerenityRunner.class)                                              
public class WhenWritingWebTestsInSerenity {
```
In spite your great work, I am having big problem of different documentation(blog, website, github ) advocate different way of setting up the project (where to keep which file(s)) and how to write your test classes. This is over and above philosophical dilemma(how to write Scenarios, making them independent, atomic, each Scenario step is global etc.) around Cucumber, which Serenity wraps around.

It would be immensely beneficial to folks who are low experienced, Testers pushed hard by the Clients to be productive sooner, etc., if you could consolidate one simple feature test with few Scenarios under it, in to a pdf document or as part of the Serenity BDD book. Continue the same example in your entire documentation. Sticking to one good example throughout either Serenity-Java or JS or XXX, would be providing more familiarity and deeper understanding.
It would alleviate bothering you on the github where it is more dedicated to Serenity development problems than low level questions by folks like me.

**Comment by PrasadNutalapati** [comment]
Some how this problem is related to the issue I posted
https://github.com/serenity-bdd/serenity-core/issues/1595 
So closing the issue.
