### ISSUE TITLE
Migration from PageObject to Screenplay framework

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1590]
Hello,

We have a project that we would like to write our automation scripts for using Screenplay framework.

Currently we have a mature, old automation project which was written in the Serenity PageObject framework.

Short of rewriting every single line of code, we're wondering if there's a smart way to 'migrate' as much as possible (looking mostly at the page object locators and steps) over to Screenplay (i.e. Targets, Tasks and Actions)?

Just wanted to ask if you have a migration guide or tips on how we can do this?

Thanks!

**Comment by wakaleo** [comment]
A good way to start is to first refactor to an Action Classes-based approach first (see https://johnfergusonsmart.com/page-objects-that-suck-less-tips-for-writing-more-maintainable-page-objects/) - this is less of a big jump to make.
