### ISSUE TITLE
General performance overhead (very slow, in general)

### ISSUE THREAD

**Issue by hurjup** [serenity-bdd/serenity-core#1591]
Having a framework using cucumber and rest-assured (sort of similar to https://github.com/serenity-bdd/serenity-cucumber-starter), I see a serious performance overhead. It seems to be independent of versions (1.9.45 or 2.0.40), and it is even observable on the official documentation ("Last updated 2016-07-15 12:22:46 UTC") too - see http://thucydides.info/docs/serenity-staging/images/serenity-test-report.png for example.
In more details every step (step definition class level) adds about 1.5-2secs overhead, and every step it has (steps class level) adds another 0.5secs.
So far I could not improve these figures (like following #743, etc).

It has many side effects from my point of view:
- I can't catch UI changes quicker than ~2seconds in a structured way (e.g. separate step)
- For API testing at last I had to write a separate cucumber + rest-assured based framework (same versions to the one used in my Serenity framework), _and it is blazing fast_.

Is the observed performance normal so to be accepted, or is there any way to significantly improve it?

**Comment by wakaleo** [comment]
I'd like to investigate this further, could you provide a sample project that illustrates the difference? The only real difference between Serenity Rest Assured and plain Rest Assured is a ByteBuddy layer (unless you are also doing UI testing in the same tests?)

**Comment by wakaleo** [comment]
Also, are you combining web testing and REST API interactions in the same test?

**Comment by centu81** [comment]
Facing simial issues with overhead in Steps and even more overhead when using SerenityRest.

**Comment by wakaleo** [comment]
Without a sample project to reproduce the issue, this isn't very actionable. The best thing would be for you to do some performance analysis on your actual project to try to pinpoint any bottlenecks. There shouldn't be any noticeable overhead simply from using Steps unless you are doing UI tests, in which case there is some overhead due to screenshots.

**Comment by matthieu-vergne** [comment]
Hello,

With some colleagues, we faced almost the same issue : a delay of about 10 seconds to run the first test.

Here is the project that shows the problem: [testSerenity.zip](https://github.com/serenity-bdd/serenity-core/files/3477914/testSerenity.zip)
The command is `mvn clean verify -Pit`.

And a runtime screen (we are not on a slow network):
![TestResult](https://user-images.githubusercontent.com/1774210/62638759-68ddfb80-b93e-11e9-8b30-770c5ef50bf7.PNG)

We hope it's a good example to investigate.
Thanks in advance

**Comment by wakaleo** [comment]
I have reproduced the issue but I have no idea what it is caused by. It may be related to the ByteBuddy instrumentation. I will put this on the backlog of things to investigate, but if this is important for your projects I would suggest looking into the code on your own side or raising a commercial support ticket so that someone can dedicate more time to digging into the issue.

**Comment by wakaleo** [comment]
This is caused by the ByteBuddy instrumentation when you use RestAssured and Serenity. There should be some improvements in 2.0.69. There will always be a delay for the first RestAssured test though.

**Comment by krys86** [comment]
Hello,
would it be possible to exclude the ByteBuddy dependency with Maven, or it is required for both frameworks to work?
Thanks in advance

**Comment by wakaleo** [comment]
It is how the Serenity/RestAssure integration works, so that is not possible. It creates a one-off delay of a few seconds when the first RestAssured test is executed - I don’t think it can be reduced much further.

**Comment by krys86** [comment]
Clear,
no troubles, I will just increase the test timeout to 30 secs so won't fail.
Is only annoying during local development/test phase, but is few seconds..I can survive :)

Thanks a lot for your explaination.
