### ISSUE TITLE
WebDriver does not instantiate in grid setup

### ISSUE THREAD

**Issue by vaibhav2701** [serenity-bdd/serenity-core#1592]
Hi,

we use a combination of jbehave/serenity for our tests. we are trying to run our tests on a remote grid. There is some data setup happening in our tests in the @BeforeStories section which takes upto 5 mins.
When we run the tests locally they run fine but on grid we get the below error:

```
ERROR WebDriverFacade:152 - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.chrome.ChromeDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Unable to parse remote response: <html><head><title>504 Gateway Timeout</title></head>
<body><h1>Gateway Timeout</h1>
<p>Server error - server xx.xxx.xxx.232 is unreachable at this moment.<br><br>Please retry the request or contact your administrator.<br></p>
<!--Zscaler/5.6--></body></html>
```
If we turn off the data setup step, the browser launches on remote machine and tests execute normally. So it looks like the time spent in data setup causes something to timeout. Is there any serenity timeout value which can be increased or are we doing something wrong?

**Comment by wakaleo** [comment]
There might be a chromedriver or grid option for this, but without seeing the exact code I can’t really say.

**Comment by vaibhav2701** [comment]
We figured out the issue and it had nothing to do with Serenity or Jbehave. The data setup was making a call to a method which was internally setting a proxy as System Property which was causing the issue. Fixing the code solved the problem. Thanks for your inputs though :)

**Comment by wakaleo** [comment]
Thanks for the detailed update!
