### ISSUE TITLE
Referring to your Serenity BDD book, can a @Test annotation encompass a complete scenario, as part of running SerenityRunner.class ?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1594]
Hello !
I am referring to your Serenity bdd book @ https://serenity-bdd.github.io/theserenitybook/latest/step-libraries.html. Very in the beginning, you seem to be enclosing a set of @Given @When @Then step definitions inside a method, which is annotated with a tag @Test.
 
```
@Test
public void members_should_start_with_Bronze_status() {
        // GIVEN
        tracy.joins_the_frequent_flyer_program();
        // THEN
        tracy.should_have_a_status_of(Bronze);
    }
```

1. How would you choose the name of the method ? From the step line describing **Scenario:** keyword?
2. Would this be possible only when you use **@RunWith(SerenityRunner.class)** annotation just before declaration of StepDefinition class? How about if you were using **@RunWith(CucumberWithSerenity.clas)** instead?
3. What is the best place of declaring this annotation ? In the TestRunner.java file or as you have shown in side the stepdefinition class file ?
4. What is the role of serenity.properties at the root  of the project  Vs. TestRunner.java file ? Can we use exclusively one instead of both ?

SORRY FOR THESE MANY QUESTIONS. On behalf of JUnit-Cucumber-Serenity Test Developers, 
I am saying this 
**"We are struggling, not having a definitive documentation"**.
I know it is in the nature of the beast. Because Serenity can be used in conjunction with all the above
 technologies and a single, simple answer would be difficult.

**Comment by wakaleo** [comment]
This is more a question for Stack Oveflow. The Serenity Book talks exclusively about JUnit integration until the chapter where Cucumber is explicitly introduced.

**Comment by PrasadNutalapati** [comment]
Wow !
What a speedy response! Thanks for you dedication John !
I will be posting the question in StackOverflow.
