### ISSUE TITLE
A feature file having two individual scenarios having weird web locator problems !

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1595]
I have a feature file, having two scenarios, one for login to website, another one doing some actions on the logged in page.
If I arrange the feature file with all the step definitions in just one scenario it is working fine, especially line highlighted in the first feature file given below. And if the same feature file
arranged as having two scenarios gives a web locator problem, even though in the StepDefinitions.java, Steps.java and Pageobject.java files, I give the same code entirely including the code to locate the web element.
The first scenario (with Outline) is just doing the login to the website. No objects stored, or any thing.
The second scenario is trying to verify some data on the page like whether row with userid and date being populated.
The problem is with the second feature file where I introduced the `second scenario keyword`, because it is rightfully another separate scenario.

**NOTE:- The code used to code the stepdefinitions, and to locate the web element in the  two places (maintained as SEPARATE PROJECTS) is the SAME.**

Please help me identify the problem. Driving me insane.
----------------------------------The feature file runs FINE.-----------------------------------
**Feature:** Data Extract List Page

In order to test DataHub UI, 

I want to specify the features of Extract History Page

  **Scenario Outline:** Navigate to Extract History page from the List page 

    Given the User opens the PRAMA Datahub website

     When the User types in userId "<uId>" and pacman passcode "<pacman_passcode>"

      And the User clicks on submit button

     Then the User lands on page "<title>"  

     

     When status column-cell has status "Ready" value

     _And last run column-cell has userid and date populated (**NOTE:working fine**)_

     And the User clicks on last run column cell of first extract record

      Then the User is navigated to the Execution History "execution_history" page

     

     When the execution history page shows "completed" status

     And the User clicks on extract record header

     Then verify number of records greater than zero

     And file name is a valid string

  

    Examples: 

      | uId | pacman_passcode .  | title   | 

      | xxx | kT7&)cP^jhK&xze    | Datahub |  

> -------------------This feature file CAN'T find a web element (the first after login)-----------

**Feature**: Data Extract List Page

  In order to test DataHub UI, 

  I want to specify the features of Extract History Page

**Scenario**: User logs in to prama datahub website 
```
Given the User opens the PRAMA Datahub website

When the User types in userId "xxxxx" and pacman passcode "kT7&)cP^jhK&"

  And the User clicks submit button

Then the User lands on page "Datahub"
```
 

 **Scenario:**Navigate to Extract History page from the Extract List page
```
   Given User logs in to prama datahub website

    When status column-cell has status "Ready" value

    And last run column-cell has userid and date populated (**NOTE: throwing web element locator exception HERE**)

     And the User clicks on last run column cell of first extract record

    Then the User is navigated to the Execution History "execution_history" page
```

**UPDATE:** 
Just for kicks, when I commented out the suspected 'Scenario' keyword and accompanying
@Given step, which are practically not do any thing new, the web locators are found, **_NO PROBLEMO !_**
What the fun is happening here ?
There is no storage of any data from the first login scenario, no nothing.
Simply logged in, asked for the web locator.

-------------------------------------------------------------------------
**Feature:** Data Extract List Page

  In order to test DataHub UI, 

  I want to specify the features of Extract History Page

**Scenario**: User logs in to prama datahub website 

Given the User opens the PRAMA Datahub website

When the User types in userId "pxxxx" and pacman passcode "kT7&)cP^jhK&(YB*VUcMiMSo0@1kwYxze"

  And the User clicks submit button

Then the User lands on page "Datahub"

 

 **#**_Scenario_:Navigate to Extract History page from the Extract List page

   **#**Given User logs in to prama datahub website_ (**NOW THE PROBLEM HAS GONE AWAY !!**)

    When status column-cell has status "Ready" value

     And last run column-cell has userid and date populated

     And the User clicks on last run column cell of first extract record

    Then the User is navigated to the Execution History "execution_history" page

     

    When the execution history page shows "completed" status

     And the User clicks on extract record header

    Then verify number of records greater than zero

     And file name is a valid string

**Comment by wakaleo** [comment]
This sounds like a test-specific and usage issue, so better for StackOverflow.

**Comment by PrasadNutalapati** [comment]
I agree with you here !
But would you mind giving me a pointer, where most probably I should be looking ? 
Like is it in pom.xml ? Or feature file ? serenity.properties ? Serenity.conf ?
Thanks for your help,
