### ISSUE TITLE
How to use a long project name without overlapping the breadcrumbs line?

### ISSUE THREAD

**Issue by SchnuckySchuster** [serenity-bdd/serenity-core#1597]
Hi there,

In the test report I need to show what version of the application under test was tested and also the version of the tests that were running.

I'm using -D=serenity.project.name="..."
The test result does seem not to like long project names.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/3406054/53322406-a04e7380-38db-11e9-89a5-d75b670e1e3b.png">

Is there an other way to print this information without disturbing the test result layout and without manipulating the css of the generated report after the fact that it was generated?

**Comment by wakaleo** [comment]
No, not really. If you can figure out a change to the CSS to make that work, I'd be happy to include it.

**Comment by SchnuckySchuster** [comment]
Are you happy with me giving you screenshots on how I changed the style in the browser on the fly?

If so:

I've set the element with id=projectname-banner style  width: 70%

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3406054/53324408-05589800-38e1-11e9-8c37-e018e0fd11e7.png">

and of element with id=projectname  I deleted some style properties 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3406054/53324537-4d77ba80-38e1-11e9-804c-2050e5fda797.png">

**Comment by wakaleo** [comment]
A pull request would be more effective; I won't have time to experiment with this for a while.

**Comment by SchnuckySchuster** [comment]
Ok, I'll do it

Mit besten Grüßen,
Gerhard Schuster 

Festnetz: 	08637/986157
Mobil: 		0179/1006330

Am 25.02.2019 um 09:44 schrieb John Ferguson Smart <notifications@github.com>:

A pull request would be more effective; I won't have time to experiment with this for a while.

**Comment by SchnuckySchuster** [comment]
Hi John,

I’m not much of a developer. I do not quite know how to set things up in order to send you a pull request.

I can do send you the changed file.

in core.css this is the change I’ve made as screenshot


and as text
#projectname-banner {
    float:right;
    width:70%
}

.projectname {
    font-family: "Helvetica Neue Light", "HelveticaNeue-Light", "Helvetica Neue", Calibri, Helvetica, Arial, sans-serif;
    font-weight:normal; font-size:2em; color:#428bca; position:relative;
}

This is the entire file

Mit besten Grüßen,
Gerhard Schuster

Festnetz: 08637/986157
Mobil:      0179/1006330

**Comment by SchnuckySchuster** [comment]
I've sent you the pull request

**Comment by wakaleo** [comment]
Should be fixed in 2.0.41
