### ISSUE TITLE
Is this Chrome Driver issue or Serenity issue? Please check.

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1598]
When I run my tests, they complete OK. And at the end, I see this multi-line display

TEST PASSED: User logs in to prama datahub website
----------------------------------------------------------------------------
`2019-02-26 09:52:03.687 chromedriver[60698:6259125] pid(60698)/euid(118122254) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!`

These lines run around more than 4500 times before recovering on it's own and print
`09:52:07.760 [Darkroom Processing Line] DEBUG net.serenitybdd.core.photography.DarkroomProcessingLine - Processing screenshot image in /var/screenshots/screenshot-6198953999898481422`

When I run the chromedriver on my mac terminal, I get this version..
`ChromeDriver 2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189) on port 9515`

Not that it is any bug or problem for me, but a nuisance, as it fills up the console and I need to scroll a loooong time to see the other debug output. That is all. 
Just for you FYI.

**Comment by wakaleo** [comment]
It’s a chromedriver message, due to a bug in the Mac OS version of chromedriver. Nothing Serenoty can do about it unfortunately.

**Comment by PrasadNutalapati** [comment]
I felt the same. It is not any roadblock but some inconvenience.
Closing the issue.
