### ISSUE TITLE
Do you have development document about serentity-core?

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#1599]
hi 

Do you have development document about serentity-core, i want to develop on my machine for study the test framewark, but i can't find the dev guide. So if you have , please sent me. thanks.

**Comment by wakaleo** [comment]
Not really, but you just need chromedriver, phantoms and geckodriver installed and then you run "gradle test" to run the unit tests, "gradle integrationTests" for the integration tests, and "gradle install" to install a snapshot build.

**Comment by ChrisD1990** [comment]
Thanks wakaleo
