### ISSUE TITLE
Cleanup dep tree, especially convergence errors

### ISSUE THREAD

**Issue by jeffjensen** [serenity-bdd/serenity-core#16]
Serenity exposes dependency convergence problems with transitive deps, making it difficult to keep a clean dep tree in client modules.

This gist is an example pom showing the issues.
https://gist.github.com/jeffjensen/729d64c56d5563dc9da2

**Comment by jeffjensen** [comment]
1. In resolving these issues, is your preference to exclude the problematic ones or declare the problematic ones at the latest version?  In reviewing existing build, I only notice exclusions.

2. If preferring declare, which scope is your preference (e.g. I'm wondering if provided)?

**Comment by wakaleo** [comment]
I generally both exclude them and declare the one I want, or let the
preferred library declare the one it needs. Either option would be fine.

Regarding scope, I guess that would depend on the dependency, e.g. can you
be sure that it will be provided, and with a compatible version?

On 20 January 2015 at 01:33, jeffjensen <notifications@github.com> wrote:

>
>    1.
>
>    In resolving these issues, is your preference to exclude the
>    problematic ones or declare the problematic ones at the latest version? In
>    reviewing existing build, I only notice exclusions.
>    2.
>
>    If preferring declare, which scope is your preference (e.g. I'm
>    wondering if provided)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/16#issuecomment-70501196>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by jeffjensen** [comment]
Using Serenity 1.0.25, all the dep convergence problems are gone but recent commit added javassist, so this one now exists:

Dependency convergence error for javassist:javassist:3.9.0.GA paths to dependency are:
+-x:y-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:core:1.0.25
    +-javassist:javassist:3.9.0.GA
and
+-x:y-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:serenity-cucumber:1.0.7
    +-org.reflections:reflections:0.9.8
      +-javassist:javassist:3.12.1.GA

**Comment by wakaleo** [comment]
Should be fixed in 1.0.37

**Comment by franciscodominguez** [comment]
@wakaleo 
sounds good. looking forward to the newer versions!

**Comment by wakaleo** [comment]
It should be all good in 1.0.37

On 3 March 2015 at 16:08, Francisco Dominguez <notifications@github.com>
wrote:

> @wakaleo <https://github.com/wakaleo>
> sounds good. looking forward to the newer versions!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/16#issuecomment-76888083>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by jeffjensen** [comment]
Still issues with 1.0.38:

[WARNING]
Dependency convergence error for commons-codec:commons-codec:1.9 paths to dependency are:
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:core:1.0.38
    +-commons-codec:commons-codec:1.9
and
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:core:1.0.38
    +-org.apache.httpcomponents:httpclient:4.3.6
      +-commons-codec:commons-codec:1.6
and
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:serenity-junit:1.0.38
    +-commons-codec:commons-codec:1.9
and
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:serenity-report-resources:1.0.38
    +-commons-codec:commons-codec:1.9
and
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:serenity-spring:1.0.38
    +-commons-codec:commons-codec:1.9


[WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.apache.httpcomponents:httpclient:4.3.6 paths to dependency are:
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:core:1.0.38
    +-org.apache.httpcomponents:httpclient:4.3.6 (managed) <-- org.apache.httpcomponents:httpclient:4.4
]


[WARNING] Rule 5: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for commons-codec:commons-codec:1.9 paths to dependency are:
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:core:1.0.38
    +-commons-codec:commons-codec:1.9
and
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:core:1.0.38
    +-org.apache.httpcomponents:httpclient:4.3.6
      +-commons-codec:commons-codec:1.6
and
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:serenity-junit:1.0.38
    +-commons-codec:commons-codec:1.9
and
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:serenity-report-resources:1.0.38
    +-commons-codec:commons-codec:1.9
and
+-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
  +-net.serenity-bdd:serenity-spring:1.0.38
    +-commons-codec:commons-codec:1.9
]

**Comment by wakaleo** [comment]
This looks like it's being overridden from somewhere else, I'm not seeing
org.apache.httpcomponents:httpclient:4.3.6 anywhere at all on the current
dependency tree:

$gradle -q dependencyInsight --configuration testCompile --dependency
httpclient
Publishing core:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-report-resources:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-ant-task:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-gradle-plugin:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-junit:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing
serenity-sample-alternative-resources:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-spring:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-test-utils:net.serenity-bdd:1.0.39-SNAPSHOT
org.apache.httpcomponents:httpclient:4.4
\--- project :core
     +--- testCompile
     \--- project :serenity-spring
          \--- testCompile

(*) - dependencies omitted (listed previously)

$gradle -q dependencyInsight --configuration testCompile --dependency
commons-codec
Publishing core:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-report-resources:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-ant-task:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-gradle-plugin:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-junit:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing
serenity-sample-alternative-resources:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-spring:net.serenity-bdd:1.0.39-SNAPSHOT
Publishing serenity-test-utils:net.serenity-bdd:1.0.39-SNAPSHOT
commons-codec:commons-codec:1.9
+--- project :core
|    +--- testCompile
|    \--- project :serenity-spring
|         \--- testCompile
+--- testCompile
+--- project :serenity-report-resources
|    \--- project :core (*)
+--- project :serenity-spring (*)
+--- project :serenity-test-utils
|    \--- testCompile
\--- org.apache.httpcomponents:httpclient:4.4
     \--- project :core (*)

(*) - dependencies omitted (listed previously)



On 14 March 2015 at 04:26, jeffjensen <notifications@github.com> wrote:

> Still issues with 1.0.38:
>
> [WARNING]
> Dependency convergence error for commons-codec:commons-codec:1.9 paths to
> dependency are:
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:core:1.0.38
> +-commons-codec:commons-codec:1.9
> and
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:core:1.0.38
> +-org.apache.httpcomponents:httpclient:4.3.6
> +-commons-codec:commons-codec:1.6
> and
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:serenity-junit:1.0.38
> +-commons-codec:commons-codec:1.9
> and
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:serenity-report-resources:1.0.38
> +-commons-codec:commons-codec:1.9
> and
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:serenity-spring:1.0.38
> +-commons-codec:commons-codec:1.9
>
> [WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps
> failed with message:
> Failed while enforcing RequireUpperBoundDeps. The error(s) are [
> Require upper bound dependencies error for
> org.apache.httpcomponents:httpclient:4.3.6 paths to dependency are:
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:core:1.0.38
> +-org.apache.httpcomponents:httpclient:4.3.6 (managed) <--
> org.apache.httpcomponents:httpclient:4.4
> ]
>
> [WARNING] Rule 5: org.apache.maven.plugins.enforcer.DependencyConvergence
> failed with message:
> Failed while enforcing releasability the error(s) are [
> Dependency convergence error for commons-codec:commons-codec:1.9 paths to
> dependency are:
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:core:1.0.38
> +-commons-codec:commons-codec:1.9
> and
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:core:1.0.38
> +-org.apache.httpcomponents:httpclient:4.3.6
> +-commons-codec:commons-codec:1.6
> and
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:serenity-junit:1.0.38
> +-commons-codec:commons-codec:1.9
> and
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:serenity-report-resources:1.0.38
> +-commons-codec:commons-codec:1.9
> and
> +-my-group-name:my-module-name-at:1.0.0-SNAPSHOT
> +-net.serenity-bdd:serenity-spring:1.0.38
> +-commons-codec:commons-codec:1.9
> ]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/16#issuecomment-79159857>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by jeffjensen** [comment]
Yes, thank you for pointing that out - I looked into it and Spring Boot is managing httpclient to version 4.3.6.  I overrode that to 4.4 and now it is clean for us.  Finally onto 38!  Thank you very much John!
