### ISSUE TITLE
How to run my serenity feature, providing command line options(login credentials) to the program ?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1600]
My serenity project feature is working perfect, by running maven project by using
`mvn clean verify`

But our leadership is against keeping login credentials(userId, password) in the feature file or any external properties file. Only supplying them in the command line like 
`mvn exec:java -Dexec.mainClass="com.module.test.Main" -Dexec.args="arg0 arg1 arg2"  
`
But in Serenity, there is no Main.java file with main() method. Then 

**how do I invoke my serenity feature file to run using Maven with the provided 2 arguments ?**

Your suggestions are highly appreciated,

**Comment by ricardorlg** [comment]
Just pass them as properties then you can use EnvironmentVariables to get the values.

**Comment by PrasadNutalapati** [comment]
You mean the properties with in the pom.xml file ? Or any other way ?
As I said, my leadership is not willing to leave the credentials in any file or codebase or any such thing,
except the command line options when invoking the program.

Or if I misunderstood you, will you please elaborate ?

**Comment by ricardorlg** [comment]
You can run tests with mvn clean verify - Dusername=username - Dpassword=pasword and then in code just read those properties using it system class or EnvironmentVariables serenity class

**Comment by PrasadNutalapati** [comment]
Awesome Ricardo ! Appreciate your answer.
I went to see in the 2.0.40 API at , I found a mention of `net.thucydides.core.util.EnvironmentVariables`, but there is no such class in that package `net.thucydides.core.util`
What/ Why is that missing ?

**Comment by ricardorlg** [comment]
https://github.com/serenity-bdd/the-serenity-book/blob/master/modules/ROOT/examples/serenity-screenplay-rest/src/test/java/examples/screenplay/rest/WhenManagingUsers.java

**Comment by ricardorlg** [comment]
Please try to ask this questions in rocket chat. Github is for reporting bugs.

**Comment by PrasadNutalapati** [comment]
Ricardo;
Our company is a financial institution.(That is why so much restrictions around credentials). They don't allow 'chat', 'messenger' category webpages to loaded. They blocked it. Damn it !!
BTW, 
It is a class 'WhenManagingUsers' which uses EnvironmentVariables. And EnvironmentVariables class is an anonymous inner class having several methods to be implemented.
I will have to sit and do think, what I can do. I don't know whether some idea would come or not.

**Comment by ricardorlg** [comment]
You don't have to implement anything just import the class and declare a field of type EnvironmentVariables. Serenity will inject it. Or just use System.gettProperty

**Comment by PrasadNutalapati** [comment]
Sure. Let me give a try and let you know.
Greatly appreciate the idea and help.

**Comment by PrasadNutalapati** [comment]
Thanks Ricardo;
I have done like this `mvn clean verify -Dusername='pnutala' - Dpasscode='xxxxxxxx',` 
the error message I got is 
`[ERROR] Unknown lifecycle phase "-". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. ->`.

If I understood the message correctly, I should be using a plugin with a goal. Which plugin it could be ? 
`maven-surefire-plugin??
`
`maven-failsafe-plugin ??
`
What would be the goal ?

**Comment by ricardorlg** [comment]
the problem is that you put an space in the password variable. It should be 
mvn clean verify -Dusername='pnutala' -Dpasscode='xxxxxxxx'

**Comment by PrasadNutalapati** [comment]
How dumb of me !
I am indebted to you man !
Kudos to you !

**Comment by PrasadNutalapati** [comment]
BTW, in our present command
`mvn clean verify -Dusername='pnutala' -Dpasscode='xxxxxxxx'`
are we using which plugin ? I am guessing that it is 'surefire' one. Right ?
Do you advice any good text book on Maven, I need to gain some good funda on it.
Thanks for your advice.

**Comment by wakaleo** [comment]
"mvn clean verify" will run both surefire and failsafe, so it will depend on your pom.xml configuration.  For books on Maven, see https://www.sonatype.com/ebooks
