### ISSUE TITLE
Awaitility cannot call Serenity Steps / Tasks

### ISSUE THREAD

**Issue by gkushang** [serenity-bdd/serenity-core#1601]
I use Awaitility to poll my REST tasks. But when I call the Task inside the **Callable** interface, I get `java.lang.NullPointerException` at 

```
java.lang.NullPointerException
	at net.thucydides.core.steps.StepEventBus.updateOverallResults(StepEventBus.java:706)
```

The Serenity Task works fine if called without the  **Callable** interface. It seems like if Serenity Task is called through **Callable** interface, it couldn't figure out the `baseStepListener` in the `StepEventBus` class.

My sample code is below,

```

    private int someTask()
    {
        when( Fred ).attemptsTo(WaitUntil.the(SomePage.SUB_TITLE, WebElementStateMatchers.isCurrentlyVisible()));
        //rest of the code goes below//
        return 0;
    }

    @Test
    public void awaitTest() 
    {
        await().atMost( 300, TimeUnit.SECONDS )
                        .pollInterval( 3, TimeUnit.SECONDS )
                        .until( () -> someTask() > 1);
    }
 ```

**Comment by wakaleo** [comment]
Awaitility runs the task in a separate thread, without knowledge of the Serenity context, so this won't work. I will have a look at extending the existing WaitFor tasks for this purpose.

**Comment by gkushang** [comment]
@wakaleo do you have any workaround?

**Comment by justinhinze** [comment]
@gkushang - You may try

`
Awaitility.await().pollInSameThread()...
`

**Comment by wakaleo** [comment]
Thanks @justinhinze, I wasn’t aware of that feature.
