### ISSUE TITLE
Issue in setting up from serenity.properties

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1602]
I'm setting chrome driver as below in serenity properties .Its executing well in local system but if i execute in jenkins with same configuration im getting the below error .
webdriver.chrome.driver=./libs/chromedriver.exe

Error :Caused by: java.lang.IllegalStateException: The driver is not executable

**Comment by wakaleo** [comment]
It means the driver is not executable in your CI environment.

**Comment by JeffGaly** [comment]
but same driver was working fine when i call out from code .

**Comment by wakaleo** [comment]
What environment  is Jenkins on? Using a relative path may be problematic as it will be from the working directory where the Jenkins build is running. Or if it is a different OS.

**Comment by JeffGaly** [comment]
Its windows and its a diffrent OS comparing to my local execution .

**Comment by wakaleo** [comment]
If it's a different OS then the same binary may not work. Try the approach described in https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html.
