### ISSUE TITLE
Using Interface throws NullPointerException

### ISSUE THREAD

**Issue by sebastianciocan** [serenity-bdd/serenity-core#1606]
Hi,
I get NullPointerException when I use interface.

**Interface class.**
public interface HomeInterface {
    void clickTest();
}
**Java Page Class**
public class AndroidHomePage extends AbstractPage implements HomeInterface {
    @FindBy(id="element")
    private WebElementFacade searchBar;

    public void clickTest() {
        searchBar.waitUntilClickable();
        searchBar.click();
    }
**Step Class**
public class HomeSteps extends ScenarioSteps {
    private HomeInterface homePage;
    public HomeSteps(){
        if(UtilTools.getSerenityPropertiesValues("appium.deviceName").contentEquals("Android")){
            homePage = new AndroidHomePage();
        }
        else {
            homePage = new iOSHomePage();
        }
    }

    @Step
    public void clickSearchBar(){
        homePage.clickTest();

    }

The crash happens at 
        searchBar.waitUntilClickable();

**Comment by wakaleo** [comment]
You can't create page objects directly using the new command: if you want to create them dynamically, create them using `Instrumented.instanceOf(AndroidHomePage.class)`

**Comment by sebastianciocan** [comment]
> You can't create page objects directly using the new command: if you want to create them dynamically, create them using `Instrumented.instanceOf(AndroidHomePage.class)`

I receive the following now:
net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for HomeSteps:java.lang.ClassCastException-->net.serenitybdd.core.steps.Instrumented$InstrumentedBuilder cannot be cast to HomeInterface

**Comment by wakaleo** [comment]
Sorry, should be:
`Instrumented.instanceOf(AndroidHomePage.class).newInstance();`

**Comment by sebastianciocan** [comment]
> Sorry, should be:
> `Instrumented.instanceOf(AndroidHomePage.class).newInstance();`

It works now,
Thank you very much!
