### ISSUE TITLE
How can I have two serenity.properties files dedicated for two feature files respectively ?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1607]
I have two feature files having each several scenarios. Both the feature file implementations share some common Java methods, so they both have to be included inside a single project. But for some purpose, their serenity.properties files need to be different.

Is there a possibility to markedly assign these serenity.properties files individually for each feature file implementation ?

**Comment by wakaleo** [comment]
No, this is not supported.

**Comment by PrasadNutalapati** [comment]
John;
I can understand. As the two different serenity.properties files in a same project is illogical.
But I want to express, why I was trying to do that.
For my first feature, I am using the default cucumber/Serenity setting which is that the browser session will be terminated for each scenario.
But for my second feature, I want to use the Serenity config parameter(in serenity.properties file at the top of the project along side pom.xml) which allows the browser session  to be available for the entire length of the feature like...
`#serenity.restart.browser.for.each=FEATURE // other options FEATURE, STORY, SCENARIO and EXAMPLE`

Is there any other work around for this to be achieved?

**Comment by botlasai** [comment]
can i delegate appium (want to run mobile apk file)and webdriver(wanted to run chrome browser bases testing)  in same serenity.properties file? Please help
