### ISSUE TITLE
Is there an approach for waiting for a process to complete for 5 minutes

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1608]
I am automating using selenium Java, and an action called 'preview' will submit an extract(financial data) process and it will enter a stage called 'previewing'. It normally takes 2-5 minutes of time to complete the 'previewing' process and the stage changes to 'draft'. 

Explicit wait as per this answer is one method.[https://stackoverflow.com/questions/34390541/wait-for-at-least-5-minutes-for-element-to-appear](url)

I don't think implicitwait as per Serenity may not be suitable for my case.
**webdriver.timeouts.implicitlywait=5000**

**Is there a better approach ? Does Serenity offer anything over and above Selenium ?**

**Comment by wakaleo** [comment]
If you are waiting for something to happen in the UI, use withTimeoutOf() - https://serenity-bdd.github.io/theserenitybook/latest/page-objects.html#_explicit_timeouts

**Comment by PrasadNutalapati** [comment]
Dear John;
Awesome.  Only thing I am worried about is that the wait time is not 5 sec, or 20 sec, it can go upto 5 MINUTES !!!! I doubt whether that is supported. Or may be I need to write a while do loop for this.

I will try that and let you know.

**Comment by wakaleo** [comment]
Why would that not be supported?

**Comment by wakaleo** [comment]
Closed, presumed answered.
