### ISSUE TITLE
Appium TouchAction not working

### ISSUE THREAD

**Issue by TudorMoldovanu** [serenity-bdd/serenity-core#1609]
Hello,

I am using Serenity+Appium+JUnit for Android automation. When attempting to do a swipe in a page that extends PageObject, no exception is thrown, but the swipe is not executed. The same method worked as expected for a colleague working on a different project. 

public void swipeDown()throws Exception {
        getScreenSize();
        new TouchAction(getProxiedDriver()).press(PointOption.point((screenWidth / 2), (screenHeight - 1)))
                .waitAction().moveTo(PointOption.point((screenWidth / 2), (screenHeight / 3)))
                .release().perform();
    }

My environment:
Serenity: 2.0.30
Junit: 4.12
Appium: 7.0

**Comment by wakaleo** [comment]
What do you mean by "worked as expected for a colleague working on a different project."?

**Comment by wakaleo** [comment]
I won't be able to help with this, but if you dig into the code and find anything, I'm happy to review a PR.

**Comment by TudorMoldovanu** [comment]
The output of System.out.println(getProxiedDriver().getClass()) is class io.appium.java_client.android.AndroidDriver.

**Comment by TudorMoldovanu** [comment]
Found the problem. The starting point of the swipe was a pair of coordinates that cannot be swiped. Solved by choosing another coordinates.
