### ISSUE TITLE
How should we use narrative.txt file when there are more than one feature file got implemented in the same project?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1612]
When I have one feature file, I used the narrative file to list the description and back ground about that feature, in the narrative.txt file. Now I need to add one more feature file in to the same project. How do I modify the narrative.txt file? Just append the narration of the second feature, after the narrative of the feature one ?

Is there any possibility of named narrative files connected to each feature files ? Or multiple narrative.txt files ?

BTW, another question, is it a good idea to include more than one feature file in a single project ?

**Comment by wakaleo** [comment]
The narrative (or readme.md) file in a directory relates to all the features in the directory, not just one. If you want text related to a specific a feature file, put it in the feature file itself. There are typically many feature files per project, one for each feature of the application.

**Comment by PrasadNutalapati** [comment]
OK. Got it.
I will enhance the narravite.txt and readme.md files and put additional comments in feature file(s) itself.

Thanks John !
