### ISSUE TITLE
After i upgrade the serentity from thucydides, when i run my test case, then it have some warnning information, 

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#1615]
Here have some warnning information, i don't undersytand how to fix these, please help.

> my serentity version  is 2.0.17
> selenium version is 3.13.0
> Chrome is 72

17919 [pool-1-thread-1] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: DemoUIMultipleInstall demo suite
-------------------------------------------------------------------(com/microfocus/cdf/suites/demo/freshinstall/ui/DemoUIMultipleInstall.story;DemoUIMultipleInstall demo suite)
Scenario: DemoUIMultipleInstall demo suite
**19143 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19180 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19182 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19184 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19185 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19186 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19188 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19191 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19193 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19306 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19310 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19312 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19314 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19318 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19321 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19323 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19325 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19327 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19328 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19330 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19331 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19333 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19334 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19336 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19337 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19340 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19342 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19349 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19350 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19355 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19358 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19367 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19369 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.
19375 [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.timeout, please use the serenity.* format instead.**
Mar 11, 2019 10:43:04 AM org.openqa.selenium.remote.DesiredCapabilities chrome
**INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`**
Mar 11, 2019 10:43:26 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

**Comment by wakaleo** [comment]
“Legacy property format detected for thucydides.timeout, please use the serenity. format instead.”

**Comment by ChrisD1990** [comment]
thanks , below the information is my chrome and selenium version is low？
**INFO: Using new ChromeOptions() is preferred to DesiredCapabilities.chrome()**

**Comment by wakaleo** [comment]
You can ignore that message.

**Comment by ChrisD1990** [comment]
ok, thanks for quickly reply.
