### ISSUE TITLE
Serenity Batch execution doesn't work

### ISSUE THREAD

**Issue by KrishnaPulluri1** [serenity-bdd/serenity-core#1621]
Hi Team,
I'm trying to run serenity batches in my local machine by passing the VM arguments from maven command. Could you please advise if there is any sample project to refer and make it run ?

**Comment by wakaleo** [comment]
The Serenity Batch feature is documented here: https://serenity-bdd.github.io/theserenitybook/latest/serenity-parallel.html. I don't know of any sample projects currently, as Serenity batches are an advanced feature used to distribute tests across multiple machines, and you need a grid of machines (e.g. using Jenkins nodes or Docker instances) to do it effectively.

**Comment by wakaleo** [comment]
Closing, presumed answered
