### ISSUE TITLE
How to run maven serenity tests from command prompt for headless browser testing ?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1623]
Hi;
I am using the following command to run my Serenity test cases using firefox browser, passing user credentials. It is working perfectly.

`mvn clean verify -Dwebdriver.driver=firefox -DuserId='xxxx' -Dpasscode='xxxxxxx'`

Now I need to integrate with Jenkins which is running on a **Redhat Linux machine**, which has no GUI. It had been just now only got installed with firefox browser. I had provided geckodriver binary in my code itself. The above command is invoking the browser, but may be because of OS with out GUI, it is not completing the tests and giving in the console the following message: **_"timeout waiting for a browser"_**.

The solution, I think is to run the browser tests in **_head-less mode. How to do that ?_**

**Comment by PrasadNutalapati** [comment]
I saw some thing regarding configuring headless testing using firefox at 
[ Johns Serenity BDD book](https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html#_configuring_firefox). But it is talking about JSON configuration options in the serenity.conf file. Where as I am using serenity.properties and I can't give path to profile, as it is running in Jenkins which is on a corporate Redhat Linux box.

**Comment by PrasadNutalapati** [comment]
I added the following to the serenity.properties file.
```
webdriver.driver=firefox
gecko.firefox.options = {"args": ["-headless"]}
```
It ran well, but gave some weblocator errors like one or two **button as stale or not attached to the DOM**.
Without **headless** option, it ran perfectly with out any errors. Why headless is causing weblocator errors to come up ?

**Comment by wakaleo** [comment]
Your configuration is correct. However running in headless mode sometimes highlights issues in your tests that don't appear in your browser, so it is most likely a problem that can be fixed by refactoring your test.

**Comment by PrasadNutalapati** [comment]
Thank you very much John !
Is running Chrome in headless mode is also same ? As I read some where, the headless driver is built in the Chrome Web Driver since version 59. Just providing the ChromeDriver binary as part of the project code should be enough to run the Serenity testing in with Chrome headless mode. Right ?
OR
Should we add any additional configuration in serenity.properties file ?

Some one else where advised me to install XVFB (XVFB STANDS FOR: X VIRTUAL FRAME BUFFER.) to be able to run headless mode tests.

Our preference is to run Chrome in headless mode rather than Firefox. Just to make it known.

Please advice.
Thanks a million.

**Comment by wakaleo** [comment]
Just add `headless.mode = true` to your serenity config file

**Comment by wakaleo** [comment]
Closing as answered

**Comment by marek2209** [comment]
> Just add `headless.mode = true` to your serenity config file

that param does not work for me

**Comment by eitzenbe** [comment]
FWIW this does the trick, alas not via config file ;)
export MOZ_HEADLESS=1
