### ISSUE TITLE
FontAwesome consumes massive disk space and artifact upload time

### ISSUE THREAD

**Issue by davidvc** [serenity-bdd/serenity-core#1626]
The total size of FontAwesome's resources are 16MB

```
DVC-Work-Laptop:serenity dvancouvering$ du -sh fontawesome-free-5.3.1-web/
 16M	fontawesome-free-5.3.1-web/
```

This results in a massive upload to our artifact repo in CircleCI every time we run integration tests (for us it's each time we submit a pull request).  This costs us time (3 minutes just to upload the artifact) and money (we pay for disk space usage).

I doubt Serenity is using all of those resources in FontAwesome.  Can we pare it down to what Serenity actually needs?  Take a look at https://blog.webjeda.com/optimize-fontawesome/

**Comment by wakaleo** [comment]
Fixed/improved in 2.0.42
