### ISSUE TITLE
Generated test report contians a 'Stories' tag type with class names populating as tag names

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1627]
Hello,

In the aggregated test report, I am seeing a peculiar behaviour in some projects where even though it wasn't explicitly declared, there is a test type 'Stories' appearing with the name of the test class appearing as test names.

For instance:

**Stories**
API Call Type
Insert Deal API
Retrieve Deal API

In the test suite there are test classes called `APICallType.java`, `InsertDealAPI.java`, `RetrieveDealAPI.java`. 

I've double checked that these classes do not have a `@WithTag("stories:RetrieveDealAPI")`.  

Any idea why this might be happening?

**Comment by wakaleo** [comment]
By default Serenity treats test cases as stories for its requirements hierarchy, so this is normal behaviour.

**Comment by timothyjmtan** [comment]
Thanks!
