### ISSUE TITLE
 net.serenitybdd.core.exceptions.SerenityManagedException

### ISSUE THREAD

**Issue by adityagupta2712** [serenity-bdd/serenity-core#1628]
Hello,
i am facing this issue while running gradle integrationTest aggregate on linux cli server (centos 7).
can someone help, i am new to automation testing.

com.project.dashboard.automation.SerenityRunner > Verify Add Custom Dashboard Menu.Add custom dashboard page is displayed FAILED
    net.serenitybdd.core.exceptions.SerenityManagedException
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable

**Comment by wakaleo** [comment]
That's a Cucumber error, but without more information it's hard to say more.

**Comment by adityagupta2712** [comment]
now i am getting this  webdriver error .
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :chromeIntegrationTest

com.project.group.dashboard.automation.SerenityRunner > As a user Add new element and details.Verify 'Add New Element' button is visible FAILED
    net.thucydides.core.webdriver.DriverConfigurationError
        Caused by: net.thucydides.core.webdriver.DriverConfigurationError
            Caused by: org.openqa.selenium.WebDriverException
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable

com.project.group.dashboard.automation.SerenityRunner > As a user Add new element and details.Verify 'Add New Element' page is displayed FAILED
    net.thucydides.core.webdriver.DriverConfigurationError
        Caused by: net.thucydides.core.webdriver.DriverConfigurationError
            Caused by: org.openqa.selenium.WebDriverException
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable

com.project.group.dashboard.automation.SerenityRunner > As a user Add new element and details.Verify 'Element Type' drop down is visible FAILED
    net.thucydides.core.webdriver.DriverConfigurationError
        Caused by: net.thucydides.core.webdriver.DriverConfigurationError
            Caused by: org.openqa.selenium.WebDriverException
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable

com.project.group.dashboard.automation.SerenityRunner > As a user Add new element and details.Verify the 'Title' field FAILED
    net.thucydides.core.webdriver.DriverConfigurationError
        Caused by: net.thucydides.core.webdriver.DriverConfigurationError
            Caused by: org.openqa.selenium.WebDriverException
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable
    cucumber.runtime.junit.UndefinedThrowable

**Comment by wakaleo** [comment]
It looks like some sort of driver issue. Do the tests run locally?

**Comment by adityagupta2712** [comment]
i haven't tried it on windows i have a centos 7 server cli only so i am running these test cases there only

**Comment by wakaleo** [comment]
You should probably make sure the tears work locally first.

**Comment by adityagupta2712** [comment]
when i am running it on windows 10 on intellij it it giving me this error..

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:

Build file 'E:\Eclipse\eclipse-jee-oxygen-1a-win32-x86_64\eclipse\Newproject\project-dashboard-automation\build.gradle' line: 31

* What went wrong:

Plugin [id: 'com.energizedwork.webdriver-binaries', version: '1.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)

- Plugin Repositories (could not resolve plugin artifact 'com.energizedwork.webdriver-binaries:com.energizedwork.webdriver-binaries.gradle.plugin:1.4')

  Searched in the following repositories:

    Gradle Central Plugin Repository

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

**Comment by adityagupta2712** [comment]
and when i am running it using intellij on windows 10 

Plugin [id: 'com.energizedwork.webdriver-binaries', version: '1.4'] was not found in any of the following sources:


 


- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)

- Plugin Repositories (could not resolve plugin artifact 'com.energizedwork.webdriver-binaries:com.energizedwork.webdriver-binaries.gradle.plugin:1.4')

  Searched in the following repositories:

    Gradle Central Plugin Repository

**Comment by wakaleo** [comment]
These are not Serenity issues. If you would like some help setting up your project and environments, you may want to look at our commercial support packages (see https://johnfergusonsmart.com/serenity-bdd-mentoring/) or ask for community help at https://serenity.rocket.chat or in the Gradle forums.
