### ISSUE TITLE
Weird Weblocator issue when running in headless mode

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1629]
Hello;
I am trying to run our Serenity feature testing with multiple scenarios, in headless mode (before running it in our RedHat Jenkins server, as there is no GUI available on RedHat box).
It is 100% success with 4 scenarios in  normal GUI mode, either with Chrome or Firefox (gecko driver). I run the tests from CLI normally like..

`mvn clean verify -DuserId='xxxx' -Dpasscode='xxxx'`

Per recommendation from Serenity author(Mr. John) and various documentation, I made these entries in serenity.properties file to run as headless mode.

```
## Chrome Browser Headless Testing

webdriver.driver=chrome

headless.mode = true



## Firefox Browser Headless Testing

#webdriver.driver=firefox

#gecko.firefox.options = {"args": ["-headless"]}
```

Unfortunately, one single web locator is unable to be found. Giving this error message.

**[ERROR] Errors:**

**[ERROR]   Expected condition failed: waiting for ExtractExecutionHistoryPage.back2SearchAnchor to be present (tried for 10 second(s) with 100 milliseconds interval)**

back2SearchAnchor is a html link, which is located by an xpath 

```
   @FindBy(xpath = "//a[contains(text(),'Back to Search')]")

    private WebElementFacade back2SearchAnchor;
```

Serenity author(Mr.John) mentioned that it is some times possible that headless mode brings out some issues which were erstwhile not there.

This link has NO problem being located and clicked on during regular GUI mode testing. Even 10 sec. of explicit wait period is also not working, as you can see in the error message.

Both the browsers, in headless mode are having the same problem.

I could NOT figure out what is the issue. Does any one faced this type of issue ? Any idea how to overcome this ?

Is it that XVFB a better and cleaner option as of now ?

**Comment by PrasadNutalapati** [comment]
Beautiful !!
I find John to be more than close by, than even my work colleagues. Especially in getting help !
Thanks a lot John !

**Comment by PrasadNutalapati** [comment]
Little feedback.
After replacing the @findBy annotated method of finding web locator to Serenity approach, it worked perfectly. But when ran multiple times, it also started throwing 
`[ERROR]   Expected condition failed: waiting for By.linkText: Back to Search to be present (tried for 10 second(s) with 100 milliseconds interval)`
What gives ??

**Comment by wakaleo** [comment]
Maybe check the screenshots to see if the link is visible when the test looks for it.

**Comment by PrasadNutalapati** [comment]
My apologies for reporting prematurely!
What a find !
It is none of Serenity's or Selenium's problem. It is due to one of our Server service not responding or being down.
**Now thanks to John, that I realized we can use Serenity's screenshots as a debug tool too !!**

**Comment by wakaleo** [comment]
Thanks for the feedback Prasad.
