### ISSUE TITLE
EDGE support - Add webdriver.edge.driver into the serenity bundle

### ISSUE THREAD

**Issue by vabtan** [serenity-bdd/serenity-core#163]
Hi, 
EDGE browser has got it's webdriver library up and running -  https://msdn.microsoft.com/en-us/library/mt188085(v=vs.85).aspx /  selenium implementation: https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/edge/package-frame.html
Could you please add EDGE as a browser option in serenity and bundle it?

regards,
alex funduianu

**Comment by YamStranger** [comment]
Hello @vabtan 

Thanks for this issue:

Support of Microsoft Edge was added in v1.1.29-rc.3

**Comment by purushothamn31** [comment]
Hi YamStranger, is it possible to share the edge capabilities how to write in serenity.conf or serenity.properties file.
