### ISSUE TITLE
Is it enough to mention which browser you want to run the tests with in serenity.properties file ?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1630]
Is it enough to mention which browser you want to run the tests with in serenity.properties file ?
Like...
## Chrome Browser Testing
#webdriver.driver=chrome
#headless.mode = true
```
drivers.windows.webdriver.chrome.driver = src/test/resources/webdriver/windows/chromedriver.exe
drivers.mac.webdriver.chrome.driver = src/test/resources/webdriver/mac/chromedriver
drivers.linux.webdriver.chrome.driver = src/test/resources/webdriver/linux/chromedriver
```

## Firefox Browser Testing
```
webdriver.driver=firefox
gecko.firefox.options = {"args": ["-headless"]}
drivers.mac.webdriver.gecko.driver = src/test/resources/webdriver/mac/geckodriver
drivers.linux.webdriver.firefox.driver = src/test/resources/webdriver/linux/geckodriver
```
and invoke the test using command line like...
``mvn clean verify -DuserId='xxx' -Dpasscode='xxx'``

OR SHOULD I MENTION ALSO..

``mvn clean verify -Dwebdriver.driver=browser -DuserId='xxx' -Dpasscode='xxx'`
`

Will Serenity infer it from properties file alone ?
Because when I don't give any browser in command prompt, and mention only firefox in properties file, it is looking for ChromeDriver and failing, whose path  is properly given in properties file already.
**Which option takes priority or which overrides which ?**
**I agree these are silly little questions !!**

**Comment by PrasadNutalapati** [comment]
Some more additions.
Even when I give complete config in serenity.properties as like...
## Chrome Browser Headless Testing
```
webdriver.driver=chrome
headless.mode = true
#drivers.windows.webdriver.chrome.driver = src/test/resources/webdriver/windows/chromedriver.exe
drivers.mac.webdriver.chrome.driver = src/test/resources/webdriver/mac/chromedriver
```
and invoke the tests like...
`mvn clean verify -DuserId='xxxx' -Dpasscode='xxx'`
with out any information like browser to be used and headless or gui based testing.

Once the test starts running empty chrome browser is popping up and sitting idle. **This should not happen. Right ?**
With this browser popup, the Redhat linux with no GUI, is erroring out.
It looks like there is only one way out. That is XVFB.
Please advice.

**Comment by wakaleo** [comment]
System properties on the command line always take priority. If the browser opens but is blanck, it might be an issue with the version of chrome and chromedriver
