### ISSUE TITLE
Custom driver is not getting invoked

### ISSUE THREAD

**Issue by kumarsahusujit7** [serenity-bdd/serenity-core#1634]
I am using serenity with cucumber. With custom driver, the driver class is never called by serenity.

Below are the properties added to serenity property.
_webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.driver.utils.MyChromeDriver_

Below is my driver class

public class MyChromeDriver implements DriverSource {

    @Override
    public WebDriver newDriver() {
        System.out.println("Inside my driver");
        System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+ File.separator + "chromedriver.exe");
        ChromeOptions chromeOptions = new ChromeOptions();
        Map<String, Object> prefs = new HashMap<String, Object>();
        prefs.put("download.default_directory",/my/fileDir);
        chromeOptions.setExperimentalOption("prefs", prefs);
        return  new ChromeDriver(chromeOptions);
    }

    @Override
    public boolean takesScreenshots() {
        return true;
    }
}

**Comment by wakaleo** [comment]
This works fine; there must be a configuration issue elsewhere in your project

**Comment by kumarsahusujit7** [comment]
Found the issue, as I was running by maven, I have to add these below properties in pom.xml as well.
With below properties in pom.xml as well as in serenity.properties works fine. 
<properties>
		<webdriver.driver>provided</webdriver.driver>
		<webdriver.provided.type>mydriver</webdriver.provided.type>
	    <webdriver.provided.mydriver>com.driver.utils.MyChromeDriver</webdriver.provided.mydriver>
</properties>
