### ISSUE TITLE
Do we need to have the Browser installed on GUI less RedHat Linux m/c when we are running headless tests using XVFB?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1636]
Since we are facing problems with running headless Serenity tests using the installed Firefox browser on a Jenkins Server running on RedHat Linux machine, we installed XVFB to run the  tests.#1633

Our preferred browser to test is with Chrome, not Firefox. But Chrome is not available for RedHat Linux (Jenkins) Server.

Question, is do we need to have the Chrome browser installed on the Linux machine in order to run headless tests using XVFB ?

**Comment by wakaleo** [comment]
Only if you want to run your tests with Chrome.

**Comment by PrasadNutalapati** [comment]
Thanks John ! 
Little clarity needed.
Yes, we want to run with Chrome browser only. But We don't have Chrome browser installation made available by RedHat on their Linux box where Jenkins has been running.

**Comment by wakaleo** [comment]
You can't run chrome without the browser being installed, even in headless mode.
