### ISSUE TITLE
Is it possible to show all tests/stories on 'overall test results' page in Serenity 2

### ISSUE THREAD

**Issue by eriklumbela** [serenity-bdd/serenity-core#1637]
In the Serenity reports from Serenity version 1, all tests were shown on the 'Overall Test Results' page (index.html)

Is it possible to show all tests/stories in Serenity 2 (2.0.41) on the 'Overall Tests Results' page?

**Comment by wakaleo** [comment]
The full list of tests appears in the Test Results tab on the home page.

**Comment by eriklumbela** [comment]
Thanks for your fast reply.

Is it then an option to open index.html on the 'Test Results' tab instead of  'Overall Tests Results'?

**Comment by wakaleo** [comment]
Not currently.

**Comment by eriklumbela** [comment]
Thanks.. Too bad...

Where would be the right place to post a feature request?

**Comment by wakaleo** [comment]
Here, though a PR will be more effective.

**Comment by eriklumbela** [comment]
Thanks
