### ISSUE TITLE
How is 'Total Duration' in the Serenity Result Report derived?

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1640]
Hello,

I am running tests on AWS infrastructure and am trying to estimate the potential costs I will be billed for it.

In the index.html report, I've a test run that shows a Total Duration of 94,690 seconds, but my actual test-run was really only about 2.5 hours long as I was doing 50 concurrent runs at the same time.

May I check what is the calculation logic for Total Duration please?

**Comment by wakaleo** [comment]
The total duration is the sum of the durations of the individual tests.

**Comment by timothyjmtan** [comment]
Thank you!
