### ISSUE TITLE
are serenity-bdd support docker?

### ISSUE THREAD

**Issue by tremkonzah** [serenity-bdd/serenity-core#1642]
I have been looking to leverage docker for serenity bdd test, can't find the steps in serenity bdd book

1. are serenity support docker
2. can i run serenity bdd script inside a docker?
3. where i can find a guide for it?
4. if i package all deps and script to jar file, can i run it through `java -cp` command line?

many thanks

**Comment by wakaleo** [comment]
This should be documented in the user manual, but running Serenity tests on a docker instance is identical to running normal Selenium/WebDriver tests in Java using docker, for which there are many tutorials.

**Comment by tremkonzah** [comment]
Thanks @wakaleo 

I'm trying to do this with starter repo `https://github.com/serenity-bdd/serenity-cucumber4-starter` and leverage `selenium/hub` and `selenium/node-chrome`. 
However i can't figure it out how i can setup serenity.conf for remote driver.

I have read https://johnfergusonsmart.com/getting-started-with-serenity-bdd-and-cucumber-4/, and driver belong to the project directory
```
drivers {
  windows {
    webdriver.chrome.driver = "src/test/resources/webdriver/windows/chromedriver.exe"
    webdriver.gecko.driver = "src/test/resources/webdriver/windows/geckodriver.exe"
  }
  mac {
    webdriver.chrome.driver = "src/test/resources/webdriver/mac/chromedriver"
    webdriver.gecko.driver = "src/test/resources/webdriver/mac/geckodriver"
  }
  linux {
    webdriver.chrome.driver = "src/test/resources/webdriver/linux/chromedriver"
    webdriver.gecko.driver = "src/test/resources/webdriver/linux/geckodriver"
  }
}
```



Should i remove above section from serenity.conf? And add following properties inside `serenity.properties`?
```
webdriver.remote.url
webdriver.remote.driver
webdriver.remote.os
```


would be possible to configure remove url and remote driver on serenity.conf?

**Comment by wakaleo** [comment]
Yes, you could put this in serenity.conf:
```
webdriver {
  remote { 
    url = ... 
    driver = ... 
    url = ...
  }
}
```

**Comment by wakaleo** [comment]
Yes, you can configure the remote webdriver setup in the usual way.

**Comment by tremkonzah** [comment]
Thanks @wakaleo 

Is it possible to have both file configured?
e.g serenity.conf configured with local path webdriver for local testing,
and serenity.properties configured with remote webdriver configuration.

Which one will have higher priority when i run `mvn clean verify`?

or any possibility whether to use serenity.conf or serenity.properties through mvn command?
