### ISSUE TITLE
@Step-like annotation used to record soft asserts

### ISSUE THREAD

**Issue by shreyasarjun** [serenity-bdd/serenity-core#1645]
@Step("Validate testcase 1")
	public void validate_TC1 () 
      {

	Assert.assertEquals(4,5);	

	}
	
	@Step("Validate testcase 2")
	public void Validate_TC2()
	{
	    Assert.assertEquals("TESTING","TESTING");
	  
	}
	
	@Step("Validate testcase 3)
	public void Validate_TC3()
	{

	    Assert.assertEquals("SERENITY","SERENITY");
	}

In the above example, If testcase 1 failed then testcase 2 and 3 is not executing.
So I need to execute testcase 2 and testcase 3 also even if tescase1 failed.
How to achieve this in serenity by using @Step annotation.
But if we use @Test annotation then there is no issue But it will not capture in test reports.
That's why I want to achieve this by using @Step annotation only.
Could you please help on this.

**Comment by wakaleo** [comment]
That's how the @Step annotation is intended to work - it is meant for sequences of actions, not soft asserts. However I will look into adding a different annotation or option to allow assertion-style steps in a future release.
