### ISSUE TITLE
Where to mention Email address for generating serenity emailable report ?

### ISSUE THREAD

**Issue by shreyasarjun** [serenity-bdd/serenity-core#1648]
I have referred below link 
https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html

I have done setup for serenity report dependence and configuration.
Still I am not understanding where to mention email address and how to receive the serenity emailable report .
Could you please explain step by step complete configuration setup for summary report generated by Serenity to email.
The above link not helped me to setup the complete configuration.

**Comment by wakaleo** [comment]
You need to use your CI server to send the actual emails; Serenity does not send the emails for you.

**Comment by shreyasarjun** [comment]
@wakaleo Thanks for your update.  I have used below commands to run the application
clean verify serenity:aggregate reports -Dserenity.reports=email
Its running successfully. But before CI configuration settings, It should be generate email body summary report  right. Where Can I find out that ?

**Comment by wakaleo** [comment]
The email summary is generated in a file called serenity-summary.html

**Comment by shreyasarjun** [comment]
What is the Jenkinsfile descriptive script for attaching this serenity-summary.html file to email body itself in POST stage ?

**Comment by wakaleo** [comment]
That is probably a question for the Jenkins communities.

**Comment by shreyasarjun** [comment]
When I am running in local system, I am able to generate email-able report & getting log as follows
[INFO] ADDITIONAL REPORTS: [email]
[INFO] GENERATING EMAIL REPORT

But when I am running in jenkins & I am not able to generate email-able report, getting log as follows
[INFO] ADDITIONAL REPORTS: [email]
[WARNING] No report found on classpath with name email

Same code is running in both platform.

Sorry If its not issue with serenity.

**Comment by santfirax** [comment]
i am having the same problem, no report found on classpath with name email, Aldo there is no serenity-summary.html file, i am using serenity emails 2.0.50

**Comment by wakaleo** [comment]
See [the documentation](https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html) for details on how to set this up. The message "No report found on classpath with name email" would indicate that Jenkins is using a different pom.xml.

**Comment by santfirax** [comment]
i am using gradle and i did the configuration on build.gradle, but summary.html file should be generate even if i am not using Jenkins or any other CI server? o we can just use this feature with a CI server?

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html#_setting_up_gradle.

**Comment by SameerPersistent** [comment]
Is there any solution to this issue. Followed serenity guide(https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html), to setup emailable reports using maven. When I run tests(mvn clean verify) manually I can see serenity-summary.html file generated under target/site/serenity. But when tests are executed through Jenkins using same maven command I don't see serenity-summary.html file generated, though I see below in Job logs:

[INFO] ADDITIONAL REPORTS: [email]
[INFO] GENERATING EMAIL REPORT

Have tried with serenity-emailer 2.0.48 and 2.0.80 versions.

Any pointers would be helpful.

**Comment by wakaleo** [comment]
Are there any errors in the logs? There is no reason the behaviour on Jenkins should be different to the behaviour locally.

**Comment by SameerPersistent** [comment]
I don't see any specific failures related to Emailable Report Generation. I just see above two lines in the logs related to this task.

**Comment by SameerPersistent** [comment]
So looks like emailable report serenity-summary.html gets generated in directory from where tests are executed, and not in the default reports directory. Is this configurable or is there any plan to fix this.

**Comment by wakaleo** [comment]
I will add it to the backlog. If it is important to you or your company, please consider proposing a Pull Request or raising a support ticket (see https://johnfergusonsmart.com/serenity-bdd-mentoring/#serenity-support) so that we can prioritise it.

**Comment by SameerPersistent** [comment]
If possible will like to propose a Pull Requests. Is there 'How-To' to get started on this.

**Comment by PrateekAgarwal1908** [comment]
Any update ?
I want to send an email that contains the Serenity automation execution report (index.html) 

2 questions - 
Where should I put the configurations like email, password, SMTP details?
Where should I call this file as I am using JBehave (not TestNG or JUnit so cannot use any annotation)

I am not using any CI/CD tool.

**Comment by wakaleo** [comment]
Serenity does not support that feature, and there are no plans to add it at this stage.

**Comment by PrateekAgarwal1908** [comment]
So what is the option to get reports in email?

**Comment by wakaleo** [comment]
Use a CI server.

**Comment by PrateekAgarwal1908** [comment]
Current we are not using any CI server (No Jenkins/Teamcity, Circle CI, GoCD etc)
It's just a Maven project which uses Serenity and for unit testing framework which I am using is JBehave. 

So is there any option which will send automation execution report (Placed in target) via email

**Comment by wakaleo** [comment]
No. You can write your own though if you like.

**Comment by PrateekAgarwal1908** [comment]
How, can you please share the code or suggest where should I do ?

**Comment by wakaleo** [comment]
There is no code for this, you would need to research it yourself. Or just use a CI server, that's what they are for.

**Comment by globalworming** [comment]
https://www.tecmint.com/send-email-attachment-from-linux-commandline/

you might want to sent just the summary report though. even zipped full report gets too big when you enable screenshots
