### ISSUE TITLE
[2.0.27] Screenshot capturing wrong window in acceptance report

### ISSUE THREAD

**Issue by thomastan1234** [serenity-bdd/serenity-core#1649]
Screenshots in Acceptance Report shows duplicated images.
The issue starts when another window is opened. The screenshots are supposed to be taken at the new window however it is showing the previous window.

**Comment by wakaleo** [comment]
I’m not sure if this can be supported - Serenity is just calling Selenium to take screenshots, and if Selenium doesn’t switch windows when screenshots are taken, Serenity has no way of recording them.

**Comment by wakaleo** [comment]
To confirm, you need to navigate to the new window with Selenium to have screenshots.
