### ISSUE TITLE
Error in cast information in report when using SerenityParameterizedRunner

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1650]
Executing some rest tests using screenplay and Junit, I found that with the latest version if I use SerenityParameterizedRunner then in the report the Cast information is not shown. If I run the tests using SerenityRunner then the Cast information is shown as expected.

**Comment by wakaleo** [comment]
This probably needs some major changes to the SerenityParameterizedRunner because of the threading model.
