### ISSUE TITLE
Failed to generate report for Test Summary Report - java.util.concurrent.ExecutionException: java.lang.IllegalStateException: userStory must not be null

### ISSUE THREAD

**Issue by YuliaPrysiazhniuk** [serenity-bdd/serenity-core#1651]
Failed to generate Index.html file. Issue started reproducing few days ago without clear reason (no Serenity version updates were made, no local code has been committed that may have impact on this issue).
Issue could be reproduced with large set of testcases execution, but can not be reproduced when small set of tests has been executed. 
Tests are running on Jenkins via Selenium_grid (chrome browser).
Serenity version: 
<serenity.version>2.0.11</serenity.version>
<serenity.jbehave.version>1.44.0</serenity.jbehave.version>

[report_generating_failure.txt](https://github.com/serenity-bdd/serenity-core/files/3059580/report_generating_failure.txt)

**Comment by wakaleo** [comment]
Hmmm, this could be data-related. Have the tests changed around that time?

**Comment by YuliaPrysiazhniuk** [comment]
No, only minor changes in source code. But issue started reproducing when we got high rate of failures related to user login issues, increasing number of result files in output folder. Could this potentially be reason for report generation failure?
Note: there are no space issues or Jenkins server, where test artifacts are located.

**Comment by YuliaPrysiazhniuk** [comment]
I no longer can reproduce report generation error after application login issue has been resolved.
