### ISSUE TITLE
Serenity report dashboard 2.0 issue

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1652]
Im using serenity 2.0 version to get a new dashboard.
1. I'm not getting capabilities and features tab in the dashboard.
2.Functional overview gives duplication of features as well as folder name.
eg:**src/test/resources/features/netbaking /customer_netbanking.feature** is my feature file and my feature title is **Netbanking** hence it shows both customer netbanking and Netbanking information's in functional overview.
3.Under requirement tab ,im not getting the description of the readme.md file

**Comment by wakaleo** [comment]
Can you provide a sample project to reproduce this issue?

**Comment by wakaleo** [comment]
Closed for lack of activity.
