### ISSUE TITLE
Screenplay eventually task converts timeout to milliseconds which is already in milliseconds as per the documentation

### ISSUE THREAD

**Issue by anoopsivarajan** [serenity-bdd/serenity-core#1653]
Hi wakaleo,

As per the system.prop documention in the below link the serenity.timeout property should be in milliseconds.

https://github.com/serenity-bdd/serenity-documentation/blob/master/src/asciidoc/system-props.adoc

For instance, if I set the serenity.timeout  to 20000 the time out is 20 seconds as expected for the tests using the page object model. If I run my screenplay tests and if any test fails with eventually task it waits for more than 20 seconds.

` 
 public EventualConsequence(Consequence<T> consequenceThatMightTakeSomeTime) {
      this(consequenceThatMightTakeSomeTime, (long)(ConfiguredEnvironment.getConfiguration().getElementTimeout() * 1000));
   }
`

Is that expected or is there a different timeout setting for screenplay?

Regards

Anoop Sivarajan

**Comment by wakaleo** [comment]
Hi Anoop,

I suspect there is indeed an inconsistancy here. If you are in the code and would like to investigate and propose a PR, I'd be happy to integrate a fix to make the units more consistent.

**Comment by anoopsivarajan** [comment]
Thanks wakaleo. I will come up with a PR asap.

**Comment by wakaleo** [comment]
You are correct; `serenity.timeout` should indeed be in seconds. I've updated the code accordingly.

**Comment by anoopsivarajan** [comment]
Thanks wakaleo.  I have created a pull request, please review and close if that change is not required.

**Comment by wakaleo** [comment]
Should be fixed now.
