### ISSUE TITLE
webdriver.timeouts.implicitlywait does not seems to be working

### ISSUE THREAD

**Issue by asuvorkov** [serenity-bdd/serenity-core#1654]
I am trying to increase `implicitlywait` value for all my tests like this:

`webdriver.timeouts.implicitlywait = 20000`

By default this value is set to _2000(ms)_. It seems that changing `webdriver.timeouts.implicitlywait` property doesn't change timeout at all. I have tried also `setImplicitTimeout(20, SECONDS);` and it does, what I am expecting, but I want to set this value to all my tests.

I am using `Serenity 2.0.41`.

A sample code to reproduce the issue:

```
package tests;

import net.thucydides.core.webdriver.WebDriverFacade;
import net.serenitybdd.junit.runners.SerenityRunner;
import net.thucydides.core.annotations.Managed;
import net.thucydides.core.annotations.Steps;
import org.junit.Test;
import org.junit.runner.RunWith;
import steps.SampleSteps;

@RunWith(SerenityRunner.class)
public class SampleTest {

    @Managed
    WebDriverFacade driver;

    @Steps
    SampleSteps sampleSteps;

    @Test
    public void SampleTest() {
        driver.get("http://thucydides.info/docs/serenity-staging/");

        sampleSteps.clickOnNotExistingElement();
    }
}
```
----------------------------------------------------------------------

```
package steps;

import net.thucydides.core.annotations.Step;
import net.thucydides.core.steps.ScenarioSteps;
import pages.SamplePage;

public class SampleSteps extends ScenarioSteps {

    private SamplePage samplePage() {
        return getPages().currentPageAt(SamplePage.class);
    }

    @Step
    public void clickOnNotExistingElement() {
        samplePage().clickOnNotExistingElement();
    }
}
```

----------------------------------------------------------------

```
package pages;

import net.serenitybdd.core.pages.PageObject;
import net.serenitybdd.core.pages.WebElementFacade;
import org.openqa.selenium.support.FindBy;
import static java.time.temporal.ChronoUnit.SECONDS;

public class SamplePage extends PageObject {

    @FindBy(id = "not_an_element") private WebElementFacade notExistingElement;

    public void clickOnNotExistingElement() {
        setImplicitTimeout(20, SECONDS);
        notExistingElement.click();
    }
}
```

**_PS:_** I am using a boilerplate from [here](https://github.com/hypery2k/serenity_sample)

**Comment by wakaleo** [comment]
You can use `setWaitForTimeout()` instead of `setImplicitTimeout()`, or use something like:
```
withTimeoutOf(20, SECONDS).find("does-not-exist");
```

**Comment by asuvorkov** [comment]
@wakaleo thank you for the response, John. Yes I can use, but what if I want to set it globally for every test?  A property `webdriver.timeouts.implicitlywait = 20000` would be an elegant solution, if it would work.

**Comment by wakaleo** [comment]
Have you tried `webdriver.wait.for.timeouts = 20000` ?

**Comment by asuvorkov** [comment]
This doesn't add to timeout as well

**Comment by wakaleo** [comment]
You will need to use the Serenity @FindBy annotation, not the Selenium one, I think

**Comment by wakaleo** [comment]
Closing, presume answered
