### ISSUE TITLE
How can I set browsermob proxy as capabilities to chrome driver?

### ISSUE THREAD

**Issue by jitin03** [serenity-bdd/serenity-core#1656]
Using setup inside @Before tag
` public void setup() {
        ClasspathFixtureProviderService classpathFixtureProviderService = new ClasspathFixtureProviderService();
        List<FixtureService> fixtureServices = classpathFixtureProviderService.getFixtureServices();
        for (FixtureService fixtureService : fixtureServices) {
            if (fixtureService instanceof BrowserMobFixtureService) {
                service = (BrowserMobFixtureService) fixtureService;
                service.setup();
                proxy = service.getProxyServer();
            }
        }
    }`
And then I want to add proxy to chrome driver..usually we can achieve this with below statement:
`Proxy seleniumProxy  = ClientUtil.createSeleniumProxy(proxy );

ChromeOptions options = new ChromeOptions();
options.addArguments("--ignore-certificate-errors");
options.setCapability(CapabilityType.PROXY, seleniumProxy);`

Please help !!
Thanks in advance

**Comment by wakaleo** [comment]
You might be able to use a custom driver; or have a look at `ChromeDriverCapabilities` and `ChromeDriverProvider`, and the `serenity-browsermob-plugin` and see if you can build a PR to add this capability.

**Comment by jitin03** [comment]
@wakaleo , Now am doing this way. But still har file is empty
` public void setup() {
        ClasspathFixtureProviderService classpathFixtureProviderService = new ClasspathFixtureProviderService();
        List<FixtureService> fixtureServices = classpathFixtureProviderService.getFixtureServices();
        for (FixtureService fixtureService : fixtureServices) {
            if (fixtureService instanceof BrowserMobFixtureService) {
                service = (BrowserMobFixtureService) fixtureService;
                service.setup();
                proxy = service.getProxyServer();


                DesiredCapabilities cap = DesiredCapabilities.chrome();
                cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
                cap.setCapability(CapabilityType.SUPPORTS_JAVASCRIPT, true);

                service.addCapabilitiesTo(cap);
                ChromeOptions options = new ChromeOptions();
                options.merge(cap);
            }
        }
    }`

**Comment by wakaleo** [comment]
Where are you using the ChromeOptions object? Just creating the object will have no effect, it needs to be used when the ChromeDriver instance is created.

**Comment by jitin03** [comment]
@wakaleo , Not using ChromeOptions, driver is initiated from serenity.properties file only as "webdriver.driver=chrome".
Appreciated if you let me know the way as you mentioned above!

**Comment by wakaleo** [comment]
The simplest way would be to write a custom driver provider

**Comment by jitin03** [comment]
@wakaleo, Please provide any reference link. For writing custom driver

**Comment by wakaleo** [comment]
https://github.com/serenity-bdd/serenity-documentation/blob/master/src/asciidoc/advanced-webdriver.adoc

**Comment by jitin03** [comment]
@wakaleo , Now How can I use the capabilities from Customdriver class
`
     DesiredCapabilities capabilities;

    @Override
    public WebDriver newDriver() {
        try {
            System.setProperty("webdriver.chrome.driver","webdrivers/chromedriver.exe");
            ChromeOptions options = new ChromeOptions();
            capabilities = new DesiredCapabilities();
            capabilities.setCapability(ChromeOptions.CAPABILITY, options);
            return new ChromeDriver(options);
        } catch (Exception e) {
            throw new Error(e);
        }
    }

    @Override
    public boolean takesScreenshots() {
        return true;
    }`
Where  BrowserMobFixtureService service lies at ServiceHook at @before tag
`  public void setup() {
        ClasspathFixtureProviderService classpathFixtureProviderService = new ClasspathFixtureProviderService();
        List<FixtureService> fixtureServices = classpathFixtureProviderService.getFixtureServices();

        for (FixtureService fixtureService : fixtureServices) {

            if (fixtureService instanceof BrowserMobFixtureService) {
                service = (BrowserMobFixtureService) fixtureService;
                service.setup();
                proxy = service.getProxyServer();
                service.addCapabilitiesTo(capabilities);
            }
        }
    }`

What is your thought to resolve this issue

**Comment by wakaleo** [comment]
You shouldn't need to activate the BrowserMobFixtureService manually; if it is on the classpath, it will be activated automatically. The driver will be created later, when you first call it in your code.

**Comment by jitin03** [comment]
Is there any file should be placed at classpath for running BMP?...I am not aware about it...Can you elaborate about this?

**Comment by jitindoriya07** [comment]
@wakaleo  What is the meaning of `You shouldn't need to activate the BrowserMobFixtureService manually; if it is on the classpath`?
