### ISSUE TITLE
Aggregation of multiple test results not working propperly

### ISSUE THREAD

**Issue by SchnuckySchuster** [serenity-bdd/serenity-core#1657]
Hi John,

I'm running version 2.0.41
I attempt to aggregate tests results as described here:

https://johnfergusonsmart.com/running-tests-different-environments-browsers-serenity-bdd/  chapter "Aggregating test results"

I'm doing it this way:
- Run my first test suite with
   - "-Dserenity.outputDirectory=[a comon directory]"
   - no aggregation step
- Run my second test suite with
   - "-Dserenity.outputDirectory=[a comon directory]"
   - with aggregation step

I expect to see a fully aggregated test result.

What I see is:
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/3406054/56133785-9668f880-5f8d-11e9-9339-b80c36ad53cc.png">

The total number of tests plus the status of the two tests are ok.
But the drill down results are not correct.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3406054/56133933-d039ff00-5f8d-11e9-8ea1-3f8335a42dc3.png">

Here I see only one test result which is the result of the test suite that ran second.
Also I see only the business components of the second test suite.

Is there anything I can do to circumvent this issue short of merging the two test suites, which I do not want to do?

**Comment by miles-mason** [comment]
Are the tests in each suite the same or different? If they're the same, you'll need to set the context e.g. `-Dcontext=chrome` so that the results will be shown next to each other. Otherwise they'll simply be overwritten by the next test run.

**Comment by SchnuckySchuster** [comment]
They are not the same.
I have tests on an API (Serenity Rest Assured) in one suite and tests on the associated GUI (Serenity Selenium) in the other one.
I will try out wether it makes a difference using -Dcontext=API and -Dcontext=GUI

**Comment by SchnuckySchuster** [comment]
It made no difference

**Comment by wakaleo** [comment]
Are the projects in different test suites/project structures. For the aggregation to work,  you  need to have the tests in the same test suite, identified by tags.

**Comment by SchnuckySchuster** [comment]
I have two destinct repositories. I want to run the tests individually. I want to write the test results of both test suites in a common directory and then want to aggregate the results.
It works partially as I see an aggregated test result page but I can not drill down to the individual tests.
I can not move the test in to one repository.
If what I want is not meant to be working, I'm fine with that.
In this case, do I close this issue, or do you do it?

**Comment by wakaleo** [comment]
Yeah, at the minute the aggregate feature needs to work with the same project structure, so it can't merge requirements directories from different projects.
