### ISSUE TITLE
Problem with running tests in chrome since v 2.0.44

### ISSUE THREAD

**Issue by AlexChernookov** [serenity-bdd/serenity-core#1658]
Hi,
Upgrade serenity version from 2.0.43 to 2.0.45 and noticed that tests in chrome are not running 

In serenity.property I have

webdriver.driver=chrome
webdriver.chrome.driver=C:\\tools\\chromedriver.exe

There is an stacktrace
Apr 16, 2019 8:20:16 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: false, browserName: chrome, chrome.switches: --disable-infobars; --disab..., goog:chromeOptions: {args: [--disable-infobars, --disable-extensions, --enable-automation, --test-type], extensions: []}, platform: ANY, version: }
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - STEP ERROR: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver

The same issue is for 2.0.44.

If switch back to 2.0.43 everything is working.
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
chromedriver https://chromedriver.storage.googleapis.com/index.html?path=73.0.3683.68/

**Comment by wakaleo** [comment]
This seems to be Windows-specific (I can't reproduce it on my Mac) - I will take a look when I can, but if you can take a look at the ChromeDriverProvider to see what might be missing, it would help.

**Comment by AlexChernookov** [comment]
Hi John, yep it's Windows.
Looks like problem is in 'DriverService' class for method "findExecutable"
lite 63 String defaultPath = (new ExecutableFinder()).find(exeName) returns null 
but if put 'chromedriver.exe' into the project folder it's start working

**Comment by wakaleo** [comment]
Could you try with 2.0.46?

**Comment by AlexChernookov** [comment]
Checked it on 2.0.46 and 2.0.47 it works fine. Thanks for the quick fix
