### ISSUE TITLE
Serenity integration with a webdrivermanager

### ISSUE THREAD

**Issue by t-hua** [serenity-bdd/serenity-core#1659]
Hi @wakaleo 

Found an old issue posted back in 2016 asking a similar question about webdrivermanager integration with Serenity:
https://github.com/serenity-bdd/serenity-core/issues/616

Wondering if there's been any features similar to this added to Serenity? Will be very useful to have a clean solution without having to download/store driver exes in the directories.

**Comment by wakaleo** [comment]
No. It's a non trivial piece of work to make a generally usable solution; you are welcome to propose a PR.

**Comment by lax1089** [comment]
@wakaleo Agreed, I am exploring this now and it is non-trivial for sure.. will open PR if I have some success.
