### ISSUE TITLE
Not able to debug Serenity with Jbehave code in ecclipse

### ISSUE THREAD

**Issue by dan0935** [serenity-bdd/serenity-core#1660]
I am trying to debug by code(written in JAVA) by applying breakpoint in my code but when I run in debug mode ecclipse doesn't stop at breakpoint and it runs as normal run . Please help me with this

I tried with cleaning project/restarting ecclipse/changing workspace but no luck.

In Goals I am using : 
clean verify -Dmetafilter="+scenariotag" -Dglobal.properties.file="propertyfilename"

**Comment by wakaleo** [comment]
This is an Ecilpse/maven question; it is not related to Serenity as such. Try asking on https://serenity.rocket.chat or on StackOverflow.

**Comment by wakaleo** [comment]
Closing as unrelated to Serenity specifically
