### ISSUE TITLE
Could not instantiate driver when run tests on selenium node when using webdriver.remote.driver

### ISSUE THREAD

**Issue by AlexChernookov** [serenity-bdd/serenity-core#1661]
Hi,  
Was able to reproduce issue on 2.0.47
when run tests on CI with command "mvn clean -Dtest=HelthCheckTest -Dwebdriver.remote.url=http://localhost:4444/wd/hub -Dwebdriver.remote.driver=chrome -Dwebdriver.driver=chrome test" 
 Apr 18, 2019 7:31:22 AM org.openqa.selenium.remote.DesiredCapabilities chrome
 INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - STEP ERROR: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
It doesn't work for Chrome and Firefox drivers

After downgrade to 2.0.43 everything is working. Think the issue could be related to https://github.com/serenity-bdd/serenity-core/issues/1658

**Comment by wakaleo** [comment]
I can't reproduce this using a Zalenium server - could you dig into the code to see if you can find any more details?

**Comment by wakaleo** [comment]
Also, the URL mentioned seems odd: "http://localhos:4444/wd/hub"

**Comment by AlexChernookov** [comment]
it's just typo when I hide the real name :) ok will try to look

**Comment by AlexChernookov** [comment]
The issue is happed in class ChromeDriverCapabilities in method updateChromeBinaryIfSpecified
        File executable = DriverServiceExecutable.called("chromedriver").withSystemProperty(ThucydidesSystemProperty.WEBDRIVER_CHROME_DRIVER.getPropertyName()).usingEnvironmentVariables(this.environmentVariables).reportMissingBinary().downloadableFrom("https://sites.google.com/a/chromium.org/chromedriver/downloads").asAFile();
after executing it null is assignet to variable 'executable'
and in 'if' it's trying to check 'execuatable.exists()' and it's caused NullPointerException 

The same is in class FirefoxDriverCapabilities

**Comment by wakaleo** [comment]
Hmmm, could you propose a PR to fix?
