### ISSUE TITLE
Which version of JUnit works with serenity-core 2.0.0+ ?

### ISSUE THREAD

**Issue by qaschevychelov** [serenity-bdd/serenity-core#1662]
I've updated serenity-core to the latest version (i need 2.0.0+). And my JUnit runner has broken. When i click 'play' button in intellij idea, nothing happens. 
I downloaded starter project with Serenity from https://github.com/serenity-bdd/serenity-junit-starter. And it's not working too.
Can someone tell me, which version of JUnit should i use?
Previously i used following versions:
        <serenity.version>1.9.20</serenity.version>
        <serenity.cucumber.version>1.9.8</serenity.cucumber.version>
        <serenity.rest.assured.version>1.9.20</serenity.rest.assured.version>
Now i want to use versions:
        <serenity.version>2.0.47</serenity.version>
        <serenity.cucumber.version>1.9.36</serenity.cucumber.version>
        <serenity.rest.assured.version>2.0.47</serenity.rest.assured.version>
The version of JUnit is 4.12

**Comment by wakaleo** [comment]
Sound's like an IntelliJ configuration issue - those versions should work.

**Comment by qaschevychelov** [comment]
I'm going to try to update intelliJ. I will comment after that

**Comment by qaschevychelov** [comment]
Now it's working. Thanks a lot!!
