### ISSUE TITLE
Getting Error as Unknown lifecycle phase "reports"

### ISSUE THREAD

**Issue by shreyasarjun** [serenity-bdd/serenity-core#1664]
I am executing my application with following maven commands
clean verify serenity:aggregate reports -Dserenity.reports=email

Because I need serenity email-able report 

Application executed successfully but getting following error 

Unknown lifecycle phase "reports". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

My POM.xml as follows

<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>

I am using serenity version as: 2.0.39

Because of this issue, maven run is failed. Could you please help me to resolve this issue.

Also Serenity email-able report not generated.

**Comment by wakaleo** [comment]
You need to run “mvn serenity:reports”

**Comment by kajols-optimus** [comment]
After successful execution(mvn clean verify), serenity cucumber reports are empty.
mvn serenity:reports is also generating empty serenity reports. Pls help
