### ISSUE TITLE
Fix import in WebElementFacade class

### ISSUE THREAD

**Issue by nikitaratkevich** [serenity-bdd/serenity-core#1665]
I didn't update code and faced the next problem: import org.openqa.selenium.interactions.internal.Locatable;
import org.openqa.selenium.internal.WrapsElement;

I found the cause of problem

Remove internal for the next imports:
import org.openqa.selenium.interactions.internal.Locatable;
import org.openqa.selenium.internal.WrapsElement;

It's in WebElementFacade class.
Maybe issue is reproducible in other classes.

**Comment by wakaleo** [comment]
I'm not sure what to do with this.

**Comment by nikitaratkevich** [comment]
Could you please answer in https://serenity-bdd.rocket.chat/channel/general
I'll add details

**Comment by wakaleo** [comment]
Continuing conversation on RocketChat. This is not a Serenity issue.

**Comment by nikitaratkevich** [comment]
According to the investigation. It can be JetBrains bug.

Workaround to use exclude:

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.13-beta-1'
    testCompile group: 'org.slf4j', name: 'slf4j-simple', version: '1.8.0-beta2'
    testCompile group: 'org.assertj', name: 'assertj-core', version: '3.11.1'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version: '3.141.59'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.141.59'
    compile group: 'org.seleniumhq.selenium', name: 'htmlunit-driver', version: '2.33.1'
    compile group: 'org.seleniumhq.selenium', name: 'jetty-repacked', version: '9.4.12.v20180830'
}

dependencies {
    compile ('net.serenity-bdd:serenity-junit:2.0.19') {
        exclude group: 'org.seleniumhq.selenium'
    }
}

dependencies {
    compile ('net.serenity-bdd:serenity-core:2.0.19') {
        exclude group: 'org.seleniumhq.selenium'
    }
}
