### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/internal/WrapsElement

### ISSUE THREAD

**Issue by pankaj-sukale** [serenity-bdd/serenity-core#1666]
We are facing following issue with latest version of Serenity.

**Serenity version we are using** 
compile "net.serenity-bdd:serenity-gradle-plugin:2.0.48" 
compile "net.serenity-bdd:serenity-spring:2.0.48" 
compile "net.serenity-bdd:serenity-core:2.0.48" 
compile "net.serenity-bdd:serenity-cucumber:1.9.37'" 
compile "net.serenity-bdd:serenity-rest-assured:2.0.48" 
compile "net.serenity-bdd:serenity-jira-plugin:1.12.0" 
compile "net.serenity-bdd:serenity-jira-requirements-provider:1.12.0"

We see issue with introducing selenium latest version i.e. 4.0.0-alpha-1 in Serenity

**Solution to fix above issue: Force selenium old version**

configurations.all {
        resolutionStrategy { 
            force 'org.seleniumhq.selenium:selenium-java:3.141.59'
      }
    }

**Error:**

java.lang.NoClassDefFoundError: org/openqa/selenium/internal/WrapsElement at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(Unknown Source) at java.security.SecureClassLoader.defineClass(Unknown Source) at java.net.URLClassLoader.defineClass(Unknown Source) at java.net.URLClassLoader.access$100(Unknown Source) at java.net.URLClassLoader$1.run(Unknown Source) at java.net.URLClassLoader$1.run(Unknown Source) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(Unknown Source) at java.security.SecureClassLoader.defineClass(Unknown Source) at java.net.URLClassLoader.defineClass(Unknown Source) at java.net.URLClassLoader.access$100(Unknown Source) at java.net.URLClassLoader$1.run(Unknown Source) at java.net.URLClassLoader$1.run(Unknown Source) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) at java.lang.Class.getDeclaredMethods0(Native Method) at java.lang.Class.privateGetDeclaredMethods(Unknown Source) at java.lang.Class.getDeclaredMethods(Unknown Source) at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:766) at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:683) at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378) at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:181) at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:661) at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:617) at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:603) at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:932) at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852) at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291) at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222) at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:938) at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:47) at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60) at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133) at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106) at com.google.inject.Guice.createInjector(Guice.java:87) at com.google.inject.Guice.createInjector(Guice.java:69) at com.google.inject.Guice.createInjector(Guice.java:59) at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:24) at net.serenitybdd.core.di.WebDriverInjectors.getInjector(WebDriverInjectors.java:10) at net.thucydides.core.webdriver.WebDriverFactory.<init>(WebDriverFactory.java:55) at net.thucydides.core.webdriver.WebDriverFactory.<init>(WebDriverFactory.java:49) at net.thucydides.core.webdriver.WebdriverProxyFactory.<init>(WebdriverProxyFactory.java:31) at net.thucydides.core.webdriver.WebdriverProxyFactory.getFactory(WebdriverProxyFactory.java:37) at net.thucydides.core.steps.BaseStepListener.<init>(BaseStepListener.java:235) at net.thucydides.core.steps.BaseStepListener.<init>(BaseStepListener.java:231) at net.thucydides.core.steps.Listeners$BaseStepListenerBuilder.withOutputDirectory(Listeners.java:37) at net.serenitybdd.core.SerenityListeners.<init>(SerenityListeners.java:30) at cucumber.runtime.formatter.SerenityReporter.initialiseThucydidesListenersFor(SerenityReporter.java:111) at cucumber.runtime.formatter.SerenityReporter.lambda$handleTestSourceRead$8(SerenityReporter.java:161) at java.util.Optional.ifPresent(Unknown Source) at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:156) at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:115) at cucumber.runner.EventBus.send(EventBus.java:28) at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132) at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315) at cucumber.api.junit.Cucumber.<init>(Cucumber.java:81) at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:54) at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) at java.lang.reflect.Constructor.newInstance(Unknown Source) at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104) at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26) at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33) at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84) at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70) at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.WrapsElement at java.net.URLClassLoader.findClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) ... 83 more

**Comment by wakaleo** [comment]
This might be fixed/worked-around in the next release - the issue seems to be an open-ended transitive dependency (possibly WebDriverNG) on Selenium, meaning that Gradle ignores the declared Selenium dependencies.

**Comment by wakaleo** [comment]
Could you try with 2.0.50?

**Comment by wakaleo** [comment]
Closed for lack of activity.
