### ISSUE TITLE
Screenshot description hides top part of screenshot

### ISSUE THREAD

**Issue by kutzi** [serenity-bdd/serenity-core#1667]
Something which has been bugging me for a long time:
the description of the screenshot (i.e. the step definition) in the BDD report overlays the top part of the screenshot and so often hides the most important part of it - i.e. where the error actually is.

Can this be adapted so that the text doesn't overlay the screenshot?

**Comment by wakaleo** [comment]
Could you give a screenshot illustrating this?

**Comment by kutzi** [comment]
Sure
![Screenshot from 2019-05-03 15-37-22](https://user-images.githubusercontent.com/175061/57141028-83418f80-6db9-11e9-9f94-e4f34976b7d9.png)

**Comment by wakaleo** [comment]
Have a look at the CSS stylesheets and see if you can propose an improvement.

**Comment by kutzi** [comment]
A frontend colleague of me suggested:
`padding-top: 40px;`

Put this to .nivo-main-image in nivo-slider.css and it should be fine

**Comment by wakaleo** [comment]
Could you see if it works for your report, and if so add it in a PR?

**Comment by kutzi** [comment]
Yes, I tried it in Chrome and Firefox developer console and it looks fine

**Comment by wakaleo** [comment]
Fixed
