### ISSUE TITLE
The response is not stored in serenity session while using .request(Method method) method instead of .get/.post/.put etc. 

### ISSUE THREAD

**Issue by kasiablk** [serenity-bdd/serenity-core#1674]
Hi,

when I use normal requests like:
` SerenityRest.given().......post(url); `
I am able to retrieve the response from different places in the same serenity session (for example in different class: 
`SerenityRest.then());`
but when I am using:
` SerenityRest.given().......request(Method.POST, someUrl); `
the request is sent properly, however the response is not stored inside **SerenityRest** session.

While trying to retrieve the same from different class (SerenityRest.then()) I am getting NullPointerException.

Best Regards,
Kasia

**Comment by kasiablk** [comment]
Hi, any update here?

**Comment by wakaleo** [comment]
Should work with 2.0.50

**Comment by kasiablk** [comment]
Hi,

no, unfortunately SerenityRest.then(); still throws NullPointerException with 2.0.50.

BR,
Kasia

**Comment by wakaleo** [comment]
Can you dig into the code from your side and propose a PR ?
