### ISSUE TITLE
Question : Parallel execution of mobile apps using Serenity JBehave

### ISSUE THREAD

**Issue by rajeshwaran88** [serenity-bdd/serenity-core#1675]
Question : Parallel execution of mobile apps using Serenity JBehave

Is there any means to setup parallel execution in Serenity JBehave. We are planning to implement in such a way the entire pack runs with one user on iOS devices and a different user in Android device. 

We have around 15 story files and a total of 100 odd scenarios. They run fine when we do separate runs on devices. I am not sure if JUnit runner class will help. serenity batch also I read as splitting the cases which I dont want to happen. 

Any suggestion to achieve this?

**Comment by wakaleo** [comment]
I would run them in parallel jobs on Jenkins (for example)

**Comment by rajeshwaran88** [comment]
Will give a try and get back to you @wakaleo

**Comment by Abhishek21sharma** [comment]
hey @wakaleo ,I know it's pretty old thread now but  I'm too trying to run the similar setup, that is running feature 1 on device 1 , feature 2 on device 2 to fasten the test time. 
Tried the above approach using Jenkins - Created two stages(for example) to execute mvn on device 1 and device 2 resp and combined them back together using 'parallel'(in the pipeline). this setup looks ok for now.
Now problem with this approach, we can control the parallel count as for each parallel we need to add another stage first + we would be needing that many agents. 
I was wondering if we've any other appropriate approach  ? how about serenity batch concept, I would've try that but I don't know how does it control different capabilities(basically device details in them) for different batches etc ?
