### ISSUE TITLE
Empty line printed in console when grabbing screenshot

### ISSUE THREAD

**Issue by Azer249** [serenity-bdd/serenity-core#1676]
https://github.com/serenity-bdd/serenity-core/blob/9dc3657224d2b7741860660fa5dc19d8388896d3/serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java#L869-L871

Not sure if this is intentional, but it looks like the BaseStepListener.grabScreenshots(..) method is just printing an empty line for no reason. It caused a bit of confusion when executing tests as it wasn't initially clear where this blank line was coming from.

**Comment by wakaleo** [comment]
Yep, that shouldn't be there. I'll remove it for the next release (or you can provide a PR if you prefer to get the credit).

**Comment by Azer249** [comment]
No worries about the credit, go ahead and make the change 👍 

Thanks!

**Comment by wakaleo** [comment]
Fixed in 2.0.49
