### ISSUE TITLE
.waitingForNoLongerThan() does not work in conjunction with .orComplaintWith()

### ISSUE THREAD

**Issue by globalworming** [serenity-bdd/serenity-core#1677]
I've got two problems and two solutions that don't work together.

I need to wait for an element to be there which is easily done by `actor.attemptsTo(WaitUntil.the(<target>, <Matcher>).forNoMoreThan(3).seconds())`

And when dealing with flakes i want to throw custom exceptions which is done by using `actor.should(seeThat(<element>, <matcher>).orComplainWith(MyCustomException.class))`

Now I have to wait until an element is present (which takes 30 seconds) and complain otherwise. I tried to copy the code from the [WaitUntilBuilder][1] but I can't set the wait time. It's always 5 seconds.

What I have and what I thought should work

    import net.serenitybdd.junit.runners.SerenityRunner;
    import net.serenitybdd.screenplay.Actor;
    import net.serenitybdd.screenplay.abilities.BrowseTheWeb;
    import net.serenitybdd.screenplay.actions.Open;
    import net.serenitybdd.screenplay.matchers.WebElementStateMatchers;
    import net.serenitybdd.screenplay.questions.WebElementQuestion;
    import net.thucydides.core.annotations.Managed;
    import org.junit.Test;
    import org.junit.runner.RunWith;
    import org.openqa.selenium.WebDriver;
    
    import static net.serenitybdd.screenplay.EventualConsequence.eventually;
    import static net.serenitybdd.screenplay.GivenWhenThen.givenThat;
    import static net.serenitybdd.screenplay.GivenWhenThen.seeThat;
    
    @RunWith(SerenityRunner.class)
    public class DelayedComplaintTest {
    
      @Managed
      WebDriver driver;
    
      Actor actor = new Actor("timer tester");
    
      @Test
      public void testEggTimer() {
        givenThat(actor).can(BrowseTheWeb.with(driver));
        actor.attemptsTo(Open.url("https://e.ggtimer.com/30"));
    
        actor.should(seeThat(
            WebElementQuestion.the("#progressText"),
            WebElementStateMatchers.containsText("seconds")));
        // fine
    
        actor.should(eventually(seeThat(
            WebElementQuestion.the("#progressText"),
            WebElementStateMatchers.containsText("Time Expired!"))
        ).waitingForNoLongerThan(30).seconds());
        // fine
      }
    
      @Test
      public void testEggTimerAndComplain() {
        givenThat(actor).can(BrowseTheWeb.with(driver));
        actor.attemptsTo(Open.url("https://e.ggtimer.com/30"));
    
        actor.should(eventually(seeThat(
            WebElementQuestion.the("#progressText"),
            WebElementStateMatchers.containsText("Time Expired!")))
            .waitingForNoLongerThan(30).seconds()
            .orComplainWith(AssertionError.class));
        // failed after 5 seconds
      }
    }

I see the problem in `orComplaintWith`. [It builds a consequence but does not take the original timeout but the systems default timeout.][2] Could this be an improvement? I am not sure about the implications, but basically taking the timeout of the consequenceThatMightTakeSomeTime if set, and if not the system default..

  [1]: https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/waits/WaitUntilBuilder.java

  [2]: https://github.com/serenity-bdd/serenity-core/blob/fad2c4611827fc5ea2a010a4fcac04e9b703474a/serenity-screenplay/src/main/java/net/serenitybdd/screenplay/EventualConsequence.java#L31

**Comment by wakaleo** [comment]
Sounds like an oversight - could you dig into the code and see if you can propose a PR?

**Comment by globalworming** [comment]
> it's gonna be an easy job

i will try :)

**Comment by miles-mason** [comment]
This seems to still be broken. Seen here with an EventualConsequence with 100 second timeout:
![orComplainWith](https://user-images.githubusercontent.com/42948872/61753884-1c0a0900-ae05-11e9-941b-c7ad265770ad.png)

Using Serenity 2.0.59

**Comment by globalworming** [comment]
could you please share the code you where using?

**Comment by miles-mason** [comment]
```java
        theActorInTheSpotlight().should(eventually(seeThat(
            TheDashboard.visibility(), is(true)))
            .waitingForNoLongerThan(100).seconds()
            .orComplainWith(DashboardNotVisible.class));
```
This step was always working before I added the `orComplainWith` line and it's working again now that I removed it.

**Comment by globalworming** [comment]
i just tried out my example with the version 2.0.60 and everything is working as expected. Please try following test on your maschine and tell me if they go green

```

import net.serenitybdd.junit.runners.SerenityRunner;
import net.serenitybdd.screenplay.Actor;
import net.serenitybdd.screenplay.abilities.BrowseTheWeb;
import net.serenitybdd.screenplay.actions.Open;
import net.serenitybdd.screenplay.matchers.WebElementStateMatchers;
import net.serenitybdd.screenplay.questions.WebElementQuestion;
import net.thucydides.core.annotations.Managed;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.WebDriver;

import static net.serenitybdd.screenplay.EventualConsequence.eventually;
import static net.serenitybdd.screenplay.GivenWhenThen.givenThat;
import static net.serenitybdd.screenplay.GivenWhenThen.seeThat;

@RunWith(SerenityRunner.class)
public class DelayedComplaintTest {

  @Managed
  WebDriver driver;

  Actor actor = new Actor("timer tester");

  @Test
  public void testEggTimer() {
    givenThat(actor).can(BrowseTheWeb.with(driver));
    actor.attemptsTo(Open.url("https://e.ggtimer.com/30"));

    actor.should(seeThat(
        WebElementQuestion.the("#progressText"),
        WebElementStateMatchers.containsText("seconds")));
    // fine

    actor.should(eventually(seeThat(
        WebElementQuestion.the("#progressText"),
        WebElementStateMatchers.containsText("Time Expired!"))
    ).waitingForNoLongerThan(30).seconds());
    // fine
  }

  @Test
  public void testEggTimerAndComplain() {
    givenThat(actor).can(BrowseTheWeb.with(driver));
    actor.attemptsTo(Open.url("https://e.ggtimer.com/100"));

    actor.should(eventually(seeThat(
        WebElementQuestion.the("#progressText"),
        WebElementStateMatchers.containsText("Time Expired!")))
        .waitingForNoLongerThan(100).seconds()
        .orComplainWith(AssertionError.class));
    // fine
  }
}
```

**Comment by miles-mason** [comment]
The problem is when the exception you pass in inherits from something other than `AssertionError`. Then when your exception is thrown you end up in this branch: https://github.com/serenity-bdd/serenity-core/blob/6bbff52e627733815aa0e68cc7f6678860798add/serenity-screenplay/src/main/java/net/serenitybdd/screenplay/EventualConsequence.java#L61 rather than this one: https://github.com/serenity-bdd/serenity-core/blob/6bbff52e627733815aa0e68cc7f6678860798add/serenity-screenplay/src/main/java/net/serenitybdd/screenplay/EventualConsequence.java#L53

My problem went away once I inherit from {{AssertionError}}. The problem is that the signature of {{orComplainWith()}} makes it clear that you can inherit from {{Error}}.
