### ISSUE TITLE
Serenity Cucumber global hook option 

### ISSUE THREAD

**Issue by vaibhav2701** [serenity-bdd/serenity-core#1681]
Hi,

We have setup a new BDD project with serenity + cucumber combination and are in the process of figuring things out. One of our requirements is to have a data setup mechanism which will run before any feature is executed. So basically first data setup will run and then all feature files. The data setup is common for all feature files so needs to be run just once.

In jbehave+ serenity combo we used to have @BeforeStories. Can't see it in cucumber. What are our options to achieve this? Any help would be appreciated. Thanks.

**Comment by wakaleo** [comment]
Cucumber doesn't have a BeforeStories equivalent. I would usually just use a synchronised lazy loading mechanism in a @Before method.

**Comment by vaibhav2701** [comment]
synchronized lazy loading? Can you give an example or point to one if its not too much to ask for :)
