### ISSUE TITLE
Error Executing FreeMarker template

### ISSUE THREAD

**Issue by vky26** [serenity-bdd/serenity-core#1682]
Hey Guys,
I'm facing this issue, where during bulk runs(more than 80+ test scenarios). I do get JAVA Heap space error and FTL stack trace ("~" means nesting-related) and reports don't render properly.  
I have added the screenshot of the error. 

Note: If a single scenario gets executed, there is no error observed. reports get generated properly. 

Serenity Details: 
  <serenity.version>2.0.4</serenity.version>
 <serenity.jbehave.version>1.42.0</serenity.jbehave.version>

POM: 
```
<plugin>
 <groupId>org.apache.maven.plugins</groupId>
 <artifactId>maven-surefire-plugin</artifactId>
 <version>2.22.0</version>
  <configuration>
   <argLine>-Xmx2048m</argLine>
     <skip>true</skip>
  </configuration>
</plugin>
```

For JAVA Heap Space: added `<argLine>` in surefire-plugin above. It didn't help. 
           

![FTL Error1](https://user-images.githubusercontent.com/30401839/58013981-b4c39600-7aef-11e9-9939-40312cfe4039.png)
![Out Of Memory Error2](https://user-images.githubusercontent.com/30401839/58013982-b55c2c80-7aef-11e9-9b6a-fe6c16f87ef3.png)

Please share your thoughts on this as this almost make our bulk runs go in vain.  
Any pointers would be appreciated, @wakaleo Thanks.

**Comment by wakaleo** [comment]
80 is only a small number of tests for Serenity (test suites with 10 times that number at common), so I doubt it is the Serenity reporting as such. If it is the tests themselves, you will need to find the correct Maven configuration to allow more memory; I’m not sure what that would be though

**Comment by vky26** [comment]
Thanks for the clarification @wakaleo for it got nothing to do with the serenity. Will try to find other configs for JAVA Heap space.
