### ISSUE TITLE
How to use log object to add custom logs at Step level?

### ISSUE THREAD

**Issue by jitindoriya07** [serenity-bdd/serenity-core#1683]
@wakaleo Please provide your feedback

**Comment by wakaleo** [comment]
I am not sure to understand what you are trying to do.

**Comment by abalmukund** [comment]
Is it possible to send custom logs statements like " Verifying actual value with expected value, val1, val2" along with cucumber steps in serenity results? Its similar like when we create logger for every step and action. Can we pass those logger in serenity results?
