### ISSUE TITLE
@Default url with value as a key get not resolved with parametrized named @NamedUrl 

### ISSUE THREAD

**Issue by andriyyarish** [serenity-bdd/serenity-core#1686]
@DefaultUrl("page:administration.page")
@NamedUrls(
    {
        @NamedUrl(name = "for.participant", url = "/participant/{1}/users")
    }
)
public class UsersPage extends AbstractClhPage {

Actual result:
net.serenitybdd.core.environment.UndefinedEnvironmentVariableException: Environment 'administration.page/participant/BNPP/users' property undefined for environment 'dev'

Expected result:
@DefaultUrl("page:administration.page") should be resolved first and after that @Named relative url should be appended

**Comment by wakaleo** [comment]
Could you propose a PR?
