### ISSUE TITLE
Aggregate Task reporting invalid json on 2.0.49

### ISSUE THREAD

**Issue by miles-mason** [serenity-bdd/serenity-core#1688]
Testing 2.0.49 today using both serenity-screenplay and serenity-cucumber, when running the aggregate task I get the following error on all scenarios:

`This file was not a valid JSON Serenity test report: scenario_name.json
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 8524 path $.testSteps[10].reportData`

Aggregate works with the same scenarios on 2.0.40

Column 8524 refers to the `reportData` section, which looks like:
`"reportData": [
    {
        "title": "CANSERVER__20190527001310.txt",
          "path": "downloadable/downloadable-4e0c172c-57b9-4ef7-9ff9-62b5f070811d-CANSERVER__20190527001310.txt",
          "isEvidence": false,
          "id": "report-data-0244914c-f72c-4920-87a3-729ae7ecd29e"
        }
      ],`

**Comment by miles-mason** [comment]
I can confirm that if there are no attached files aggregate completes, so the problem is confined to the `reportData` section.

**Comment by wakaleo** [comment]
I won’t be able to look into this for a week or two, but I don’t think it’s related to 2.0.49 a probably due to an earlier change. See if you can isolate the exact version change, and possibly propose a PR

**Comment by wakaleo** [comment]
The Json format has changed since 2.0.40 - have you trieddoing a clean build?

**Comment by miles-mason** [comment]
Yes the error is seen on a clean build too. I believe this is happening as a result of 2fd034866d6a87b75d5b6d2a36a9d81ae5d206b1

**Comment by miles-mason** [comment]
This was due to me updating the Serenity version but not the Serenity Gradle Plugin version.
