### ISSUE TITLE
Some assets missing from aggregate report in 2.0.49

### ISSUE THREAD

**Issue by miles-mason** [serenity-bdd/serenity-core#1689]
The summary pie chart and all of the assets for result types were missing from aggregate reports generated in 2.0.49.

![no_result_assets](https://user-images.githubusercontent.com/42948872/58393823-7fd9b500-8094-11e9-85f7-a30657d9a703.png)

**Comment by wakaleo** [comment]
Probably related to #1688

**Comment by miles-mason** [comment]
@wakaleo I don't believe it is, because #1688 is solely to do with `reportData` and in this case we weren't recording any report data and the aggregate generation was successful, except for this issue.
