### ISSUE TITLE
A GivenStories is not working as precondition to entire story 

### ISSUE THREAD

**Issue by klokovas** [serenity-bdd/serenity-core#169]
In [JBehave tutorials!](http://jbehave.org/reference/stable/given-stories.html) there is information that GivenStories can be used as precondition to entire story but in my case scenarios are pending.

I have a story:
```
Story name

Narrative:
any text

GivenStories: stories/demo.story#{id1:firstScenario}
Lifecycle:
After:
Outcome: ANY
Given any step

Scenario: test scenario
....
```

If I put GivenStories before scenarios they are pending.
If I put GivenStories to scenario level it works good.
```
Scenario: test scenario
GivenStories: stories/demo.story#{id1:firstScenario}
Given .......
```

**Comment by wakaleo** [comment]
Moved this issue to https://github.com/serenity-bdd/serenity-jbehave/issues/83
