### ISSUE TITLE
which actor evaluates the then?

### ISSUE THREAD

**Issue by globalworming** [serenity-bdd/serenity-core#1692]
Enhancement request:

When testing multi user applications, the BDD report does not make clear who is testing what. Look at this chat example

```
Dana enters chat room
Bob enters chat room
Dana posts a chat message with content "hello"
Then .chat-messages should be an element containing 'hello'
Then .chat-messages should be an element containing 'hello'
```
These two `then`s are Dana and Bob checking the message list, but you can not say who. When testing with multiple actors it would be better to have the actor in there.. something like

`for Dana then .chat-messages should be an element containing 'hello'`
`for Bob then .chat-messages should be an element containing 'hello'`

If you support this idea, you could point me in the general direction of the classes involved and i could maybe create a pull request.

**Comment by globalworming** [comment]
`because()` seems to replace all the normal `then` part, which is... not very helpful.
`@Subject` looks better, but the wildcard does not work, my texts look like `Then the .chat-messages of {0} should be an element containing "hello"`, the wildcard is not resolved -.-

Even if `@Subject` would work, it does not feel very DRY. Same as `@Step`. Having to write a description when the classname is decent in most of my cases feels like duplication. 
Having a decent default for the `then` display would be nicer than writing them manually in the `@Subject`.

**Comment by globalworming** [comment]
that's what i meant, you can change the output pretty good, but in most cases you are duplication the classname if you do. 
I'd like to have the ability to set something like "serenity.use.actor.names.in.then=true" so i don't have to repeat myself :)

**Comment by wakaleo** [comment]
This would be a good idea, I will look into it.

**Comment by globalworming** [comment]
nice, will try it out as soon as it's on maven central

**Comment by globalworming** [comment]
Dana enters chat room
    Bob enters chat room
    Bob posts a message saying "Hello!"
    For Dana: Then chat messages should be a collection containing a string containing 'Bob\nHello!'

looks good :+1:
