### ISSUE TITLE
How to run tests with steps from external package?

### ISSUE THREAD

**Issue by eriklumbela** [serenity-bdd/serenity-core#1693]
### How can I have serenity run tests with steps that are in an external test-library package?

Situation as follows:

- _I have a maven built java project with multiple modules (one of the modules is specific for my regression-tests) for a specific microservice_
- _In this project I also have a dependency on a test-library (external package) in which I have more general test-code, which can be used by multiple microservices_

And: 

- _I have some (Serenity) Steps that are specific for the microservice itself (located in the microservice's regression-test module)_
- _I have some (Serenity) Steps that are more general in nature and can/should be used by multiple microservices (located in the external test-library)_

If I run my tests with Steps that are located in the external test-package, all steps are marked as 'PENDING'
so: How can I have serenity run tests with steps that are in the external test-library package?

**Comment by wakaleo** [comment]
Do you have a sample project setup to reproduce this?

**Comment by eriklumbela** [comment]
Hi,

Thank you for quick follow up, here my somewhat late follow up:
I can sort of

**Comment by eriklumbela** [comment]
I could reproduce the problem. and doing so I found out that the problem was not with serenity, but with my maven configuration... The external test library was in the test sources root, which is not packed in the jar by default and thus could my steps not be found and went Pending 

(BTW: I resolved this by using the maven source plugin)
`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`
