### ISSUE TITLE
Request method PATCH instead of HEAD

### ISSUE THREAD

**Issue by zbiros** [serenity-bdd/serenity-core#1694]
I'm writing tests using "serenity-screenplay-rest"
after sending step:
`actor.attemptsTo(Head.to("/path/{id}").with(request -> request.header("Authorization", "Bearer " + token).log().all()));`

in console I get:
`Request method:	PATCH`

Please check line 22 in net.serenitybdd.screenplay.rest.interactions.Head class
`this.rest().patch(CallAnApi.as(actor).resolve(this.resource), new Object[0]);`
should be `head` not `patch`

There is also typo in 20 line - `@Step("{0} executes a PUT on the resource #resource")`

Please verify other classes:
- Options - `patch` instead of `options` + typo PUT
- Patch - `options` instead of `patch` + typo PUT
- Delete - typo PUT

**Comment by wakaleo** [comment]
Could you propose a R?

**Comment by zbiros** [comment]
I'm sorry, i was using some old version 1.9.31 and request methods are already fixed in:
https://github.com/serenity-bdd/serenity-core/commit/07c842eb827fab4d07c93992fe961fed49504df9#diff-e600acc900a9a288aa4114832832f390

Only `PUT` typos can be changed.
