### ISSUE TITLE
How to not skip entire scenario when step fails?

### ISSUE THREAD

**Issue by qaschevychelov** [serenity-bdd/serenity-core#1696]
Hi all! I have a cucumber scenario. For instance
"When i open home page
Then i see site logo
When i choose menu item 'about'
Then i see label1
And i see label2 
etc..."
The test fails on "Then i see site logo".
How to not skip all scenario?
I want the test to mark this step as failed and run further. Is there way to do it?

**Comment by wakaleo** [comment]
A BDD scenario should really only test one thing, which is why subsequent steps are skipped. What you are describing here should probably be two separate scenarios. If you want to do multiple checks on the same page, you can use AssertJ soft asserts.

**Comment by qaschevychelov** [comment]
Thanks a lot!
