### ISSUE TITLE
Serenity Report generating error @LOADED REQUIREMENTS steps..

### ISSUE THREAD

**Issue by chirag2104** [serenity-bdd/serenity-core#1698]
Hi,
Recently I have updated all the latest maven dependency in my project. I was using serenity v1.5.0 which was working fine but since I upgraded to 2.0.50 I am getting some error during report generate.

![image](https://user-images.githubusercontent.com/32411499/59065732-4fb8c000-88a5-11e9-8a9c-2855092a8c6e.png)

My POM structure is as per below. Please help me to resolve the issue. Thanks in advance.

 <properties>
        <lombok.version>1.16.10</lombok.version>
        <cucumber.version>4.2.0</cucumber.version>
        <cucumber.version>1.2.5</cucumber.version>
        <serenity.version>2.0.50</serenity.version>
        <serenity.maven.version>2.0.50</serenity.maven.version>
        <serenity-cucumber.version>1.9.38</serenity-cucumber.version>
        <failsafe.version>2.19.1</failsafe.version>
        <jsonpath.version>2.9.0</jsonpath.version>
        <hamcrest.version>1.3</hamcrest.version>
        <jackson.version>2.9.1</jackson.version>
        <jackson.databind.version>2.8.8</jackson.databind.version>
        <maven.compiler.version>3.6.0</maven.compiler.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity-cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-path</artifactId>
            <version>${jsonpath.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>${hamcrest.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-mapper-asl</artifactId>
            <version>1.9.13</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.databind.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.14.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>26.0-jre</version>
        </dependency>

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>15.0</version>
        </dependency>
        <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>12.2.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.12</version>
        </dependency>
        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
            <version>3.3</version>
        </dependency>
        <dependency>
            <groupId>com.pojosontheweb</groupId>
            <artifactId>monte-repack</artifactId>
            <version>1.0</version>
        </dependency>
        
        
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.9</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.5</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.5</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <rerunFailingTestsCount>3</rerunFailingTestsCount>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
                <executions>
                    <execution>
                        <phase>integration-test</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <includes>
                        <include>**/test/java/com/tungsten/test/stepdefs/RunTests.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>2.0.50</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>2.5.2</version>
                <executions>
                    <execution>
                        <id>install-jar-lib-1</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <groupId>com.oracle</groupId>
                            <artifactId>ojdbc8</artifactId>
                            <version>12.2.0.1</version>
                            <packaging>jar</packaging>
                            <file>${basedir}/dependencies/ojdbc8.jar</file>
                            <generatePom>false</generatePom>
                        </configuration>
                        <phase>validate</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by wakaleo** [comment]
What errors are you seeing precisely?

**Comment by chirag2104** [comment]
Hi John,

I am not getting any error apart from attached screenshot.

In working POM dependency I am getting below message at the end of test run.

Console log:

[image: image.png]

And serenity report with nice pie-chart.

[image: image.png]


But with latest version I am getting below console log and part of
pie-chart report.

Console log:
[image: image.png]

Pie-Chart:
[image: image.png]

Its looks like some part of the report are not generated correctly and
because of that console log is different between two version.

Thanks
Regards
Chirag.

**Comment by wakaleo** [comment]
That's not an error, its a normal log message.

**Comment by chirag2104** [comment]
Thanks John,
Do you have latest version report image? So I can compare and make sure everything is working fine in html report.

Thanks
Regards
Chirag.

**Comment by wakaleo** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/55986/59099943-7fef7580-891c-11e9-8bf1-9244e657620a.png">

**Comment by chirag2104** [comment]
Thanks for the quick reply.

Closing this issue now.
