### ISSUE TITLE
[Instructions] As a tester I would like to know where can I configure my webdriver

### ISSUE THREAD

**Issue by gheeno** [serenity-bdd/serenity-core#1699]
**Description:**
As a test developer using serenityBDD, JBehave, Selenium - I would like to know where I can add or edit the webdrivers and or its version.

**Issue Found:*
`net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver`

**Steps**
1. Using IntelliJ I created a new Project.
2. created a mvn archetype `net.serenity.bdd` `serenity-jbehave-archetype` `1.8.4`  FROM `https://mvnrepository.com/artifact/net.serenity-bdd/serenity-jbehave-archetype`
3. changed Serenity Core and Jbehave Version to 2.0.50 and 1.46.0 respectively.
4. Ran `AcceptanceTestSuite.Java`

**Results**
Error 
`net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver`

```
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.0.50</serenity.version>
        <serenity.jbehave.version>1.46.0</serenity.jbehave.version>
        <webdriver.driver>firefox</webdriver.driver>
    </properties>
```

```
net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
```

**Comment by wakaleo** [comment]
The latest version of serenity-jbehave works best with serenity-core 2.0.44. Higher versions are not currently supported. To use the latest version of serenity-core, we recommend using Cucumber rather that JBehave.

**Comment by gheeno** [comment]
@wakaleo unfortunately due to the company's pre-test suite they are "reliant" on JBehave. 
So moving forward - any ChromeDriver/FirefoxDriver update is updated by the Serenity team via `serenity-core` builds?

How do I change the default driver? or even select what driver to use?
Thanks a bunch.

**Comment by wakaleo** [comment]
Use the webdriver.driver property, as described in the docs

**Comment by wakaleo** [comment]
Closed due to lack of activity.
