### ISSUE TITLE
Serenity + Appium sample project somewhere?

### ISSUE THREAD

**Issue by mihaiserdean** [serenity-bdd/serenity-core#170]
Hello,

My long searches on the internet did not reveal a working sample project with Serenity and Appium on Native app (Emulator or RealDevice). @wakaleo do you have one (Android and/or iOS)?

Cheers,
Mihai Serdean

**Comment by mihaiserdean** [comment]
@wakaleo 

I would appreciate any sample project or some links on how to.
We've tried and we get null pointer exceptions on @Steps
If we pass the Webdriver as a parameter then it doesn't throw the exception but the screenshots are not taken for the Steps.

**Comment by selvavaithi** [comment]
hi guys,
Any update on this question im also searching for a sample project that has Appium+serenity.

Thanks in advance.

**Comment by hypery2k** [comment]
you can use this sample project (https://github.com/hypery2k/serenity_sample), install appium `(sudo) npm install -g appium --chromedriver_version="2.16"`, start appium `appium` and then:
* `./gradlew test aggregate -Dappium.hub=http://127.0.0.1:4723/wd/hub -Dwebdriver.driver=appium -Dappium.platformName=Android -Dappium.browserName=Browser -Dappium.deviceName="0123456789ABCDEF"`
* `./gradlew test -Dappium.hub=http://127.0.0.1:4723/wd/hub -Dwebdriver.driver=appium -Dappium.platformName=iOS -Dappium.browserName=Safari -Dappium.deviceName="iPhone 5" `

**Comment by pisarenco92** [comment]
Hi,
@hypery2k How can I use:
   @AndroidFindBy(id = " ")
   @IOSFindBy(xpath = " ") 
   MobileElement element;
with Appium+Serenity?

Thanks.

**Comment by hypery2k** [comment]
you can just add them to the page objects and import the appium annotations

**Comment by pisarenco92** [comment]
@hypery2k  
I tried but with no success,  is throwing exception.
Here is my code:

import java.util.concurrent.TimeUnit;
import org.junit.Assert;
import org.openqa.selenium.WebElement;
import io.appium.java_client.MobileElement;
import io.appium.java_client.pagefactory.AndroidFindBy;
import net.serenitybdd.core.pages.PageObject;

public class CountryPage extends PageObject{
	
   public static final String appNameId = "com.robot.android.debug:id/";
   @AndroidFindBy(id = appNameId + "language_english_text_view")
    public MobileElement english1;
	
    @AndroidFindBy(id = appNameId + "continue_button")
    public MobileElement continueButton;
    	    
	    public void loaded() {	
	    	setImplicitTimeout(6, TimeUnit.SECONDS);
	    	Assert.assertTrue("Element is not displayed", continueButton.isDisplayed());
	        Assert.assertTrue("Element is not displayed", english1.isDisplayed());
	    }	
}

import net.thucydides.core.annotations.Step;
import pages.CountryPage;

public class CountrySteps {
	
	CountryPage countryPage;
	
	@Step
	public void loaded() {
		countryPage.loaded();
	}
}

import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.WebDriver;
import net.serenitybdd.junit.runners.SerenityRunner;
import net.thucydides.core.annotations.Managed;
import net.thucydides.core.annotations.Steps;
import steps.CountrySteps;

@RunWith(SerenityRunner.class)
public class CountryTest {
    @Managed(driver = "appium")
    public WebDriver driver;
	
	@Steps
	CountrySteps countrySteps;
	
	@Test
	public void test() {
		countrySteps.loaded();
	}
}

EXCEPTION:
Failed to instantiate page of type class pages.CountryPage (java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field pages.CountryPage.english1 to com.sun.proxy.$Proxy16)

I changed MobileElement with WebElement and is throwing: Element not found.

If I use @FindBy WebElement is working.

Any suggestions?

Thanks.

**Comment by mihaiserdean** [comment]
In order for @AndroidFindBy and @iOSFindBy to work you need to do this:

public class BasePage extends PageObject {

    public BasePage(WebDriver driver) {
        super(driver);
        injectAnnotatedFieldsInto(driver, this);
    }

    public void injectAnnotatedFieldsInto(WebDriver driver, Object page) {
        PageFactory.initElements(new AppiumFieldDecorator(driver,
                new TimeOutDuration(5, TimeUnit.SECONDS)), page);
    }

**Comment by pisarenco92** [comment]
thanks @mihaiserdean .
I tried: PageFactory.initElements(new AppiumFieldDecorator(driver,new TimeOutDuration(5, TimeUnit.SECONDS)), page) and I found that is working fine with release of 1.1.22-rc.11 but with new releases is throwing exception: Element not found.

**Comment by Moustakas42** [comment]
Has anyone found a workaround for using Appium-specific actions (taps, swipes, etc)?

**Comment by cliviu** [comment]
hi @hypery2k , in your CountryPage define english1 as WebElement. In the Page Object(CountryPage) , before accessing any of the  Android/iOSFindBy, make sure that the PageFactory elements are initialized. Calling initializePageFactoryElements() before accessing any of the annotated fields should make sure that  the  "com.sun.proxy.$Proxy" Exception will never come.

`private boolean pageFactoryInitialized = false;

private void initializePageFactoryElements(){
    if(!pageFactoryInitialized) {
        PageFactory.initElements(new AppiumFieldDecorator(getWebDriver(),
                      this.getImplicitWaitTimeout().in(TimeUnit.SECONDS), TimeUnit.SECONDS), this);
        pageFactoryInitialized = true;
    }
}`
This is only a workaround, I will try to find a way to get this integrated in serenity. Let me know if it helps you further.

**Comment by hypery2k** [comment]
@wakaleo: Can we add this somehow directly to Core? Would be nice to handle it by Serenity directly

**Comment by cliviu** [comment]
@hypery2k : Have you tried it ? Was the workaround  ok for your test case ?

**Comment by wakaleo** [comment]
Closing this as questions are now answered on StackOverflow with the #serenitybdd tag.

**Comment by cliviu** [comment]
The problem occurs when running with java 8. With java 7 it should be ok.
