### ISSUE TITLE
PageUrl Configuration not being updated

### ISSUE THREAD

**Issue by Azer249** [serenity-bdd/serenity-core#1701]
Previously I could use getConfiguration().setDefaultBaseUrl(baseUrl); to set the base URL of the application programatically, then after that if i called a paramatised open on a page object with a named URL, the base URL would be appended so the overall url would be _baseURL + namedUrl_.

However, after updating to 2.0.49 it seems the configuration that is on the PageUrls object, does not match that returned by the ConfiguredEnvironment.getConfiguration() if the configuration has been updated.

Is this a intended design or are there any changes anyone is aware of that could have broke this?

Here is an example where the configuration returned by the ConfiguredEnvironment.getConfiguration() call is different to the one on the PageUrls object: 
![image](https://user-images.githubusercontent.com/17050928/59250245-9fd5b080-8c1e-11e9-8c42-f97945e81caf.png)

**Comment by wakaleo** [comment]
Configuration is generally considered immutable, so this is probably normal behaviour.

**Comment by Azer249** [comment]
Ah - was unsure if this was a change in behaviour as the configurations are always in sync in version 2.0.47

**Comment by wakaleo** [comment]
I don't think there was any intentional change in that behaviour between 2.0.47 and 2.0.48: you could have a look at the code changes to see if there is anything obvious.

**Comment by Azer249** [comment]
Yeah I had a quick gander at the commit history for release 2.0.49, and couldn't see anything obvious either. I'll have another debug today and see if I can find anything.

**Comment by Azer249** [comment]
So an update, 

I think the issue is coming from the change made to the constructor in PageUrls in this commit:

https://github.com/serenity-bdd/serenity-core/commit/581c65b04bf54ac23021a65d0ca79b694aa20524#diff-12461af7707e9a165a82b695b52b7728

The configuration that is being passed to the constructor is now being created withEnvironment variables, which instead of editing the configuration object, makes a copy of it passes that to the main constructor. That means every PageUrls object is being created with a different copy of the configuration. Previously every PageUrls object would instead have a reference to the same object as it would just pass ConfiguredEnvironment.getConfiguration().

Even if the Configuration object is supposed to be immutable, it seems strange to me that the configuration returned by getConfiguration is now not returning the same object that is contained within the PageUrls objects. 

Im not sure if this is a bug/or the intended design. However, if it's the intended design does this kind of implicitly render the getConfiguration().setXX methods useless?

**Comment by wakaleo** [comment]
It could be an easy fix. Could you provide a sample project to illustrate this issue?

**Comment by Azer249** [comment]
@wakaleo 

Here is a Sample project i whipped up quickly, there's some JavaDoc in the WhenUpdatingConfiguration test file that should help with the explanation. You'll need to flick between version 2.0.48 + 2.0.49 to see the difference. 

https://github.com/Azer249/SerenityIssue-1701

**Comment by Azer249** [comment]
Hey @wakaleo, did you manage to take a look at this - I know you mentioned it on Rocket Chat too.

**Comment by wakaleo** [comment]
The change you suggested has been implemented in 2.0.50+, but I haven't checked if it works yet.

**Comment by Azer249** [comment]
@wakaleo  I just gave it a shot on 2.0.55 and it still seems to be an issue. 

On this line: 

https://github.com/serenity-bdd/serenity-core/blob/b50f2d3ca2018c6a58c760718f94a97a1fb2f2c4/serenity-core/src/main/java/net/serenitybdd/core/pages/PageUrls.java#L47

The pageUrls object is still being constructed with a copy of the Configuration thanks to the .withEnvironmentVariables() call. 

https://github.com/serenity-bdd/serenity-core/blob/b50f2d3ca2018c6a58c760718f94a97a1fb2f2c4/serenity-model/src/main/java/net/thucydides/core/configuration/SystemPropertiesConfiguration.java#L80

In version 2.0.48 this .withEnvironmentVariables call was not there hence why the Configuration object was the same throughout all pageUrl objects.

**Comment by wakaleo** [comment]
Can you try out a fix and do a PR if it works?

**Comment by Azer249** [comment]
Sure thing.

**Comment by Azer249** [comment]
@wakaleo I have opened a pull request :D
