### ISSUE TITLE
proxy in serenity.properties is used with Custom Webdriver

### ISSUE THREAD

**Issue by Rajkumar2636** [serenity-bdd/serenity-core#1703]
I have used custom remote Webdriver in my code which needs proxy to launch and test the applications. Below is the code snippet that I have given in serenity.properties for all kind of drivers that I am returning.

serenity.proxy.http=**.**.**.** [example]
serenity.proxy.http_port=**

But the above proxy is not invoked by any web driver, alternate what I did I had to force the proxy for all drivers like this below,But this should not be right option, Correct?

Proxy proxy = new Proxy();
proxy.setHttpProxy("myhttpproxy:3337");
options.setCapability("proxy", proxy);c

Can I know why proxy in serenity.prop config is not invoked to the driver? Does config applicable to only serenity drivers?

**Comment by wakaleo** [comment]
If you use a custom driver you are entirely responsible for setting it up. Serenity has no control over custom drivers, so none of the Serenity configuration options will apply unless you include them explicitly in your custom driver code.

**Comment by Rajkumar2636** [comment]
Thanks for confirming on this.
