### ISSUE TITLE
print Console log in txt file for reference 

### ISSUE THREAD

**Issue by mahesht36** [serenity-bdd/serenity-core#1706]
i want to print the console log in txt file for the refrance.

which include the serenity log as well as the println statements.below is the details

serenity.properties
===========
serenity.outputDirectory=/Output/Reports
serenity.logging=NORMAL

dependency
=========
compile group: 'ch.qos.logback', name: 'logback-core', version: '1.2.3'
compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.6.1'

**Comment by wakaleo** [comment]
https://www.slf4j.org/manual.html

**Comment by mahesht36** [comment]
its printing on console ,i am doing this but what ever printing on the console should also print in the text file.same as console.

**Comment by wakaleo** [comment]
This is more of an SLF4J question. Take a look at https://examples.javacodegeeks.com/core-java/logback-file-appender-example/ or ask on the SLF4J channels.

**Comment by chauhaidang** [comment]
@mahesht36 This is my approach in your case. Yes we use slf4j api to log out everything. Here is my example:
- In your test file: 

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@RunWith(SerenityRunner.class)
public class WhenSearchingByKeywordInDuckDuckGo {
    //Sample of using slf4j to log out message, then logback will take all this log because we binded root logger for it
    static final Logger logger = LoggerFactory.getLogger(WhenSearchingByKeywordInDuckDuckGo.class);

    @Steps
    DuckDuckGoSearcher user;

    @Managed()
    WebDriver driver;

    @Test
    public void should_see_relevant_search_results(){

        user.is_on_the_duckduckgo_homepage();
        logger.info("HAHAHAAHAHAHAHA");

        user.searches_by_keyword_for("tiki");

        user.should_see_only_results_containing("tiki2");
    }

In your logback-test.xml

<configuration>
    <property name = "LOG_DIRECTORY" value = "target/log"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>
                %d{HH:mm:ss.SSS} [LUCY] %-5level %logger{36} - %msg%n
            </pattern>
        </encoder>
    </appender>
    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
        <file>${LOG_DIRECTORY}/serenity.log</file>
        <append>false</append>
        <immediateFlush>true</immediateFlush>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [LUCY] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <logger name="root" level="DEBUG"/>
    <logger name="net.serenitybdd" level="INFO"/>
    <logger name="net.thucydides" level="INFO"/>

    <root level="DEBUG">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="FILE"/>
    </root>

</configuration>

**Comment by wakaleo** [comment]
Closing, presume answered.
