### ISSUE TITLE
Getting File Not Found issue in Serenity Report

### ISSUE THREAD

**Issue by bishnudas1129** [serenity-bdd/serenity-core#1708]
Hi,

I have integrated Serenity with Cucumber . After running Tests, successfully getting the  Serenity report, but in report when I click on Feature name getting "File not found " error . can u please check this issue. I have attached screenshots and also steps to reproduce the same issue below. Thank you in Advanced.

Steps to reproduce the issue : 
step 1: Run the Attached project using maven successfully.
step 2 : Now open the index file for reporting (refer to this location : \SerenityCucumberPro\target\site\serenity\index.html).
step 3 : When u r in Report Home page, switch to "Test Results" tab
Step 4 : Then click on Feature link "Verifying for Home Page".
Step 5 : Now we get the Error as "File not found".

In Every execution when i click above mentioned feature name link, i get File not found Error. Please let me know what is the mistake. 
Thank you.

Bishnu
[SerenityCucumberPro.zip](https://github.com/serenity-bdd/serenity-core/files/3293843/SerenityCucumberPro.zip)

**Comment by wakaleo** [comment]
You need to use the same version number for serenity-core and serenity-maven-plugin - see https://github.com/serenity-bdd/serenity-core/blob/master/README.md#what-is-the-latest-stable-version-i-should-use

**Comment by bishnudas1129** [comment]
I have made the changes informed by u. But still i getting the Error as "File not found" on click on feature name.
Please check the project which i have attached with this message.

[SerenityCucumberPro.zip](https://github.com/serenity-bdd/serenity-core/files/3296229/SerenityCucumberPro.zip)

**Comment by wakaleo** [comment]
Make sure you run with "mvn clean verify".

**Comment by bishnudas1129** [comment]
I have checked by running with "mvn clean verify" as well. Still i am getting "File not found Error " on click on feature name link under "Test Result" tab. Please refer attached screenshot or else please run the attached mini project.

Attached Documents : 
[SerenityCucumberPro.zip](https://github.com/serenity-bdd/serenity-core/files/3296541/SerenityCucumberPro.zip)
<img width="946" alt="Screenshot_1" src="https://user-images.githubusercontent.com/51870654/59600209-35d97180-911e-11e9-9698-d071bdcd823d.png">

**Comment by wakaleo** [comment]
See above - place your feature files in `src/test/resources/features`, not in `src/test/resources/pro/features`

**Comment by bishnudas1129** [comment]
Now i have placed feature file under "src/test/resources/features" as u said. Now i see some more components in report UI, But when i switch to "Test Results " tab and click on highlighted link , i get File not found error again, please refer screenshot with updated project : 

Attched docs :  
<img width="708" alt="Screenshot_2" src="https://user-images.githubusercontent.com/51870654/59602097-8b644d00-9123-11e9-857a-7b5e2f761469.png">
<img width="904" alt="Screenshot_3" src="https://user-images.githubusercontent.com/51870654/59602098-8b644d00-9123-11e9-9bc2-92119ae23a10.png">
[SerenityCucumberPro.zip](https://github.com/serenity-bdd/serenity-core/files/3296800/SerenityCucumberPro.zip)

**Comment by wakaleo** [comment]
I am unable to reproduce this when I run "man clean verify" with the project you supplied.

**Comment by bishnudas1129** [comment]
Once you successfully run the project using "mvn clean verify" command then go through below mentioned location from your local system : 

\SerenityCucumberPro\target\site\serenity\index.html

Now once report page is loaded then click on "Test Result" Tab, refer below screenshot : 
![image](https://user-images.githubusercontent.com/51870654/59704583-1f184500-921a-11e9-919a-4a3767c2ebf6.png)

Then Click on feature name, refer below screenshot : 
![image](https://user-images.githubusercontent.com/51870654/59704751-8635f980-921a-11e9-8715-5c3e204b9610.png)

Now notice that you will be getting File not found Error with blank page, refer below screenshot
![image](https://user-images.githubusercontent.com/51870654/59704938-ed53ae00-921a-11e9-8667-15a10311021a.png)

With the same project attached in  last message.

**Comment by wakaleo** [comment]
It seems to be Windows-specific, which will make it very hard to troubleshoot (I don't use Windows).

**Comment by bishnudas1129** [comment]
After lot of research I have found the answer , it works fine now.

**Comment by wakaleo** [comment]
Great to hear - what did you find?

**Comment by bishnudas1129** [comment]
I have created a folder under "src/test/resources/features/" location then i placed my feature file there. Now in report when i click feature link from report(which was redirecting to File not found issue) , i see it successfully navigate to its parent. i.e its navigate to below screen :
![image](https://user-images.githubusercontent.com/51870654/59868534-bca47d80-93ae-11e9-830c-e87687f9f130.png)

**Comment by bishnudas1129** [comment]
Thank you for support.
