### ISSUE TITLE
Facing difficulty of running tests on chrome headless browser inside CI pipeline using docker

### ISSUE THREAD

**Issue by HGill1** [serenity-bdd/serenity-core#1709]
I am new to dockers and learning while implementing and running serenityBDD tests in CI pipeline and not able to understand the tests are working fine on my local machine but failed to run tests when check-in my code.

My serenity.conf file is 

webdriver {
  driver = chrome
  use.driver.service.pool = false
}
headless.mode = true

#
# Chrome options can be defined using the chrome.switches property
#
chrome.switches="""--start-maximized;--test-type;--no-sandbox;--ignore-certificate-errors;
                   --disable-popup-blocking;--disable-default-apps;--disable-extensions-file-access-check;
                   --disable-infobars,--disable-gpu"""
#
# Define drivers for different platforms. Serenity will automatically pick the correct driver for the current platform
#
drivers {
  windows {
    webdriver.chrome.driver = "src/test/resources/webdriver/windows/chromedriver.exe"
    webdriver.gecko.driver = "src/test/resources/webdriver/windows/geckodriver.exe"
  }
  mac {
    webdriver.chrome.driver = "src/test/resources/webdriver/mac/chromedriver"
    webdriver.gecko.driver = "src/test/resources/webdriver/mac/geckodriver"
  }
  linux {
    webdriver.chrome.driver = "src/test/resources/webdriver/linux/chromedriver"
    webdriver.gecko.driver = "src/test/resources/webdriver/linux/geckodriver"
  }
}

My Dockerfile contains the below code to run tests using run_test file. Docker image is getting created successfully.

RUN set -eux; \
    gradle clean compileJava compileTestJava; \
    rm -rf /tmp/*; \
    chmod +x ${RUNNER_DIR}/bin/run_tests;

Below is my .gitlab-ci.yml I am running selenium/node-chrome service.

stages: 
  - build
  - push
  - run

image: docker:1.12.5

services:
  - docker:1.12.5-dind
  - selenium/node-chrome

Run Tests:
  stage: run
  image: $GCP_REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHA
  variables:
    ENVIRONMENT: dev
  script:
    - run_default_tests

 Seems like there is no issue with all the three stages but while running tests I am getting below error. As per my above serenity.conf file all folder and files are as per the folder structure and tests run fine on my local machine.

org.openqa.selenium.os.OsProcess checkForError
    SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/my_project/src/test/resources/webdriver/linux/chromedriver" (in directory "."): error=2, No such file or directory)
    [Test worker] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 

When I run the same tests by changing the firefox browser then I am getting a different error.

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

        Caused by:
        net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX
        Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
        System info: host: 'runner-3pemtvfr-project-703-concurrent-068lrs', ip: '10.204.0.150', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.65+', java.version: '1.8.0_212'
        Driver info: driver.version: ProvideNewDriver). See below for more details.

            Caused by:
            org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX
            Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
            System info: host: 'runner-3pemtvfr-project-703-concurrent-068lrs', ip: '10.204.0.150', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.65+', java.version: '1.8.0_212'
            Driver info: driver.version: ProvideNewDriver

Again tests running fine on local with firefox browser. Do I need to install firefox or chrome? is it what I need to do using my docker image or its the problem with my image is not able to communicate with the container firefox or chrome is installed. Don't know how I can do that.

**Comment by wakaleo** [comment]
"Cannot run program "/my_project/src/test/resources/webdriver/linux/chromedriver" (in directory "."): error=2, No such file or directory" seems to indicate that the driver file is not present or accessible from within Docker.

**Comment by HGill1** [comment]
Hi Wakaleo, File is there but and I am getting a different error with firefox

**Comment by wakaleo** [comment]
For Firefox, it looks like Firefox itself is not installed in the Docker container: "Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX".

**Comment by HGill1** [comment]
So when I  am doing this

services:
  - docker:1.12.5-dind
  - selenium/node-firefox
  - selenium/node-chrome

Is it not installing firefox? Dont know if my question is correct.

**Comment by wakaleo** [comment]
That would be more a question for the Docker community I think.
