### ISSUE TITLE
Reports - json and html missing while running by an example (line filter)

### ISSUE THREAD

**Issue by sricharanya** [serenity-bdd/serenity-core#1711]
With the following setup:
OS: Debian Linux AMD64
serenityCoreVersion = '2.0.49'
serenityCucumberVersion = '1.9.23'
junitVersion='4.12'
Gradle version: 4.8.1

While running serenity tests by a specific example (line number filter) as follows:

`./gradlew test -Dcucumber.options="classpath:features/some.feature:21"`

the console output logs reports that the tests have passed but the target/serenity/ folder does not contains the .json, .html or the <junit>.xml files.
Strangely this is happening only on a Linux system and not on the Windows PC.
While placing debug breakpoints, I observed that during the "finishExample" call, the baseStepListeners list becomes empty.

Please find attached some screenshots.
![Screenshot from 2019-06-12 17-24-11](https://user-images.githubusercontent.com/46148202/59582439-e8e1a500-90f5-11e9-9cf1-8b6cb99a6d46.png)
![Screenshot from 2019-06-12 17-23-49](https://user-images.githubusercontent.com/46148202/59582440-e8e1a500-90f5-11e9-9541-b63a6198ad1f.png)

Please note that, I did try to reproduce this using `serenity-cucumber-starter` github project but not reproducible.

**Comment by wakaleo** [comment]
I can't reproduce this on a Mac either. It might be a project-specific issue. Can you provide a sample project?

**Comment by sricharanya** [comment]
We could not get a trimmed down version of our project working or reproduce the issue with cucumber starter project. The json and html reports are generated but aggregation failed. 

But here is the observation from one of the developers:
Examples from same scenario created json and html files with **same scenario name.**
This caused issues while uploading files and while generating aggregate reports.
Tried commenting serenity.compress.filenames property, html and json files had same id.
Need to find a solution for this problem.

**Comment by wakaleo** [comment]
It is generally a good idea to avoid duplicated scenario names; could you give me an example of duplicated scenario names you are seeing?

**Comment by wakaleo** [comment]
If this is urgent you can always raise a support ticket or sign up for a support contract - that would allow us to prioritise the issue.
