### ISSUE TITLE
Zalenium opening incorrect browser, opening firefox instead of chrome.

### ISSUE THREAD

**Issue by paulballardboil** [serenity-bdd/serenity-core#1712]
Issue: After launch automation suite to run in Docker, its opening incorrect browser and then times out.

The suite runs fine locally just not through docker.

After launch Zalenium/Grid in Docker and then launching the automation suite using commands:

Docker:
docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -e WAIT_FOR_AVAILABLE_NODES=false --privileged dosel/zalenium start --desiredContainers 1

Suite execution:
mvn verify serenity:aggregate verify -Dtest=RegressionTestSuite -f pom.xml -Dwebdriver.remote.url=http://localhost:4444/wd/hub

The suite is set up in Serenity Properties
webdriver.driver = remote
webdriver.remote.url = "http://localhost:4444/wd/hub"
webdriver.remote.driver = chrome
webdriver.driver= chrome
webdriver.chrome.driver=src/test/resources/drivers/chromedriver75Version.exe
serenity.driver.capabilities= nativeEvents:false;marionette:false;
chrome_preferences.disable-dev-shm-usage;=// overcome limited resource problems
chrome_preferences.no-sandbox;=// Bypass OS security model
chrome_preferences.download.default_directory=/my/download/directory
chrome_preferences.profile_default_content_settings.popups=0
chrome_preferences.pdfjs.disabled=true
chrome.preferences.shm.devdisabled=true
chrome.capabilities.acceptSslCerts = true
chrome.capabilities.handlesAlerts = true
chrome.preference.headless = true
chrome.preferences.disable-gpu = true
chrome.preferences.disable-notifications = true

But when it starts running the automation suite logs show that its got confused between ChromeDriver and firefox and I cant work out how or why.

Jun 17, 2019 3:30:29 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Jun 17, 2019 3:31:16 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
[INFO] 2019-06-17 15:32:21,964 - STEP ERROR: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
[INFO] 2019-06-17 15:32:21,971 - STEP ERROR: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Timed out waiting 45 seconds for **Firefox** to start.
Build info: version: '3.141.59', revision: '82b03c358b', time: '2019-04-30T22:04:50'

It has tried to create a session
Docker log:
16:33:20.021 [http://172.17.0.3:40003] INFO  org.openqa.grid.internal.TestSlot - Trying to create a new session on test slot {server:CONFIG_UUID=2a77144d-baac-4ba2-856b-9d526d7f41b6, seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, version=75.0.3770.80, platform=LINUX, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=chrome, zal:resolution=1920x1080, maxInstances=1, platformName=LINUX}
16:33:20.022 [Matcher thread] INFO  d.z.e.z.registry.ZaleniumRegistry - Test session with internal key 28e9734e-2526-4fbf-9dcb-49fd8378a903 assigned to remote (http://172.17.0.3:40003) after 8 seconds (8626 ms).
16:34:05.845 [http://172.17.0.3:40003] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - Session 28e9734e-2526-4fbf-9dcb-49fd8378a903 completed. Node should shutdown soon...
16:34:22.357 [Thread-19] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.3:40004

But then watching the recording in the Zalenium dashboard its opened a firefox browser.

**Comment by wakaleo** [comment]
Are you using the zalenium plugin for Serenity?

**Comment by paulballardboil** [comment]
Docker set up was done as per https://serenity-bdd.github.io/theserenitybook/latest/serenity-grid.html

**Comment by wakaleo** [comment]
OK, it's probably a bug in the Zalenium setup (in the [BeforeAZaleniumScenario](https://github.com/serenity-bdd/serenity-core/blob/848f7b6fb1f9c2fa7c5723aa72b2cf0f00d6bced/serenity-zalenium/src/main/java/net/serenitybdd/zalenium/BeforeAZaleniumScenario.java) class. The Zalenium integration is pretty experimental, so if you are using it on a real project, the fastest way to get a fix would be to play round with the class yourself and see what Capability options it needs. If you copy the class into your own project structure (and remove the dependency on serenity-zalenium) you should be able to experiment with changing the code pretty easily.
