### ISSUE TITLE
Could not instantiate class org.openqa.selenium.chrome.ChromeDriver

### ISSUE THREAD

**Issue by gheeno** [serenity-bdd/serenity-core#1713]
**Error thrown :** 

> [pool-1-thread-1] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [--enable-automation, --test-type], extensions: []}, platform: ANY, version: }
> Given the user is on the Wikionary home page (FAILED)
> (net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class `org.openqa.selenium.chrome.ChromeDriver)
> 
> net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver

**Chrome Version :** Version 75.0.3770.90 (Official Build) (64-bit)
**OS : Windows 10**

**POM Properties**

> `    <properties>
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <serenity.version>2.0.52</serenity.version>
>         <serenity.jbehave.version>1.46.0</serenity.jbehave.version>
>         <webdriver.driver>chrome</webdriver.driver>
>     </properties>`

**Oracle:** 
With the same configuration - same properties and chrome installed, I cannot reproduce this issue on my Mac.

Commands Used: 
1. `mvn clean verify`
2. ran `AcceptanceTestSuite.class`

**Comment by wakaleo** [comment]
Is your chomedriver binary up to date?

**Comment by gheeno** [comment]
> Is your chomedriver binary up to date?

Thanks for the reply. Just updated it today - still the same results.

`Done. ChromeDriver binary available at C:\WINDOWS\system32\node_modules\chromedriver\lib\chromedriver\chromedriver.exe`

`+ chromedriver@75.0.0`

**Comment by gheeno** [comment]
Also not sure if this matters but I tried using ChromeDriver's sample test to check if the driver is working - and it was working without hardcoding the `path\to\the\chromedriver.exe` using a maven package called `WebDriverManager`

`package simpletest;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class chromedriver {
    @BeforeClass
    public static void setupClass() {
        WebDriverManager.chromedriver().setup();
    }

    @Test
    public void testGoogleSearch() throws InterruptedException {
        // Optional, if not specified, WebDriver will search your path for chromedriver.
        //System.setProperty("webdriver.chrome.driver", "/path/to/chromedriver");

        WebDriver driver = new ChromeDriver();
        driver.get("http://www.google.com/xhtml");
        Thread.sleep(5000);  // Let the user actually see something!
        WebElement searchBox = driver.findElement(By.name("q"));
        searchBox.sendKeys("ChromeDriver");
        searchBox.submit();
        Thread.sleep(5000);  // Let the user actually see something!
        driver.quit();
    }
}
`

Maybe my pathing is incorrect for Serenity?

Here are the binary paths that I have : 
Node.JS = C:\WINDOWS\system32\node_modules\chromedriver
Choco = C:\ProgramData\chocolatey\lib\chromedriver\tools
Environment Path has both $NodeJS'sFullPath%\bin and Choco's full path
