### ISSUE TITLE
Running Serenity BDD tests with cucumber tags also triggers execution of non-cucumber serenity tests

### ISSUE THREAD

**Issue by TagiraNara** [serenity-bdd/serenity-core#1714]
Good afternoon, 
I have a project where there are two types of tests stored at the same time: 
1. Some test classes are run with SerenityParametrizedRunner.class
2. Others are serenity + cucumber bundle, so they are run with CucumberWithSerenityRunnes.class

In general, I use maven profiles to execute different test suits, but sometimes to be more flexible I want to execute only tests with some tags (usually cucumber tags).  So I execute:

mvn clean verify -Dcucumber.options="--tags @_some-desired-tag_"

The thing is, that although tests in a class with SerenityParametziedRuner obviously don't have this cucumber tag, they are executed unless you provide also -Dtags="_any-not-applicable-junit-tag_", which will then force Serenity to skip them. 
This behavior is quite unpredictable and unexpected. When I provide any tags, I expect that only those tests which have it will be executed. 

Do I miss something here? Is there a way to avoid this behavior (except the one I've mentioned above)?

**Comment by wakaleo** [comment]
This is the expected behaviour when you mix JUnit tests with Cucumber runners. The `cucumber.options` parameter is used exclusively by Cucumber to filter the tests, so JUnit will simply ignore it. The workaround is to use the tagging strategy you describe.

**Comment by TagiraNara** [comment]
hi @wakaleo , thank you for your fast reply, just like I thought, except that it is actually an expected behavior - for me it was not...
