### ISSUE TITLE
Long links spill out of the visible frame 

### ISSUE THREAD

**Issue by bady2bro** [serenity-bdd/serenity-core#1716]
**If we have a very long continuous string of characters in the report, like a request url that failed, it will spill out of the visible frame.**
Depending on the length, the person analyzing the report will have to scroll horizontally to scan the entire string but will never have access to the whole/overview in the serenity report.
**_As an example think of the following type of error message:_**
"1) Request with bad responses were found on page: Page One
 Bad request: 
NetworkEvent:
	 Request: **http://site.under.test:xxxx/query?param1=1324654983655&param2=sql%2Fexample%2Fone&param3=value4&param4=value4&param5=value5&param6=value%2F0%2F6&.....&paramN=valueN**
	 Response: 500 Server Error"
in which the request is displayed on a single line, even if it doesn't fit in the visible frame of the report

**Comment by wakaleo** [comment]
Happy to consider a PR to fix the presentation
