### ISSUE TITLE
how to create the executable jar file for cucumber project

### ISSUE THREAD

**Issue by mahesht36** [serenity-bdd/serenity-core#1717]
Hi,
i want to create the executable jar file for my project as like we do for other java project.
i am using intellij IDE.
by using cucumber & serenity-gradle i had created by automation scripts.
do not have the main(String []args) method.
kindly suggest.
Thanks

**Comment by wakaleo** [comment]
This is non-trivial - you can do it by tweaking the Gradle file and writing your own test runners that run from a main method, but it is a fair bit of non-trivial work. It isn't in our backlog for the moment.
