### ISSUE TITLE
Screenshot at last step of each scenario

### ISSUE THREAD

**Issue by Rajkumar2636** [serenity-bdd/serenity-core#1721]
Hi,

We are using serenity with Junit, as of now we are taking screenshots for each steps in scenario, but we would like to have screenshot for failure and last step of each scenario.

Can you please help me to implement this in my framework.

**Comment by wakaleo** [comment]
See http://thucydides.info/docs/serenity-staging/#_managing_screenshots

**Comment by wakaleo** [comment]
Presume answered.
