### ISSUE TITLE
Using a Chrome executable in a non-standard location

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#1723]
How do I specify a non-standard chrome executable?

I tried something like `chrome.binary=/usr/bin/google-chrome-beta`, but that is ignored.

According to [chrome docs](http://chromedriver.chromium.org/capabilities), you can use something like:
```
ChromeOptions options = new ChromeOptions();
options.setBinary("/usr/bin/google-chrome-beta");
```
but how do I get access to the ChromeOptions from Serenity?

Note: I am running this on a Jenkins machine where I do not have admin access.

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html

**Comment by SiKing** [comment]
I read through that, specifically https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html#_configuring_chrome

I noticed the sections that describe using `chrome.switches` and using `chrome_preferences`. Neither of these methods can set the chrome binary! Just so there is no confusion: I have no problem setting the Chrome driver binary; my problem is with setting the Chrome **browser** binary.

The documentation seems to suggest that in Serenity it is not possible to create your own instance of `new ChromeOptions()` and pass that to a `@Managed WebDriver driver`.
Or did I miss something? If yes, how would I accomplish this?

**Comment by SiKing** [comment]
It looks like there was a discussion specifically about this, here: https://groups.google.com/forum/#!topic/thucydides-users/aepwEiTv0b0
But that discussion did not have an answer either. :(

**Comment by SiKing** [comment]
I found the solution! Unfortunately I am behind a firewall and I cannot get Gradle (I only have Maven) ... so I cannot submit a merge request.

In serenity-core:net.serenitybdd.core.webdriver.driverproviders.ChromeDriverCapabilities#ChromeOptions():51, you need something like:

```
if(WEBDRIVER_CHROME_BINARY.isDefinedIn(environmentVariables))
    options.setBinary(WEBDRIVER_CHROME_BINARY.getPropertyValue());
```

**Comment by SiKing** [comment]
https://github.com/serenity-bdd/serenity-core/pull/1724
