### ISSUE TITLE
BrowserOn does not work, yes open url

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#1728]
Using Open.url it's working, but not the browserOn for the same url...

Example:

public class OpenApplication {

    public static Performable theHomePage() {
        return Task.where("that Xavier is logged in with",
                Open.url("http://10.120.187.110")
                //Open.browserOn().the(StartPage.class)
        );
    }
}

@DefaultUrl("http://10.120.187.110")
public class StartPage extends PageObject {
}

@Given("^that user is logged in with$")
    public void thatUserIsLoggedIn(Map<String,String> userData) throws Throwable {
        theActorCalled("Xavier").attemptsTo(OpenApplication.theHomePage());
...

The commented code of Open.browserOn does not work. I'm using Serenity with cucumber 4.

**Comment by wakaleo** [comment]
Have you defined a webdriver.base.url in your properties file?

**Comment by xescuder** [comment]
Yes, my serenity.conf is using remote url as:

webdriver {
  driver = remote
  remote.url = "http://localhost:4444/wd/hub"
  remote.driver = chrome
}

**Comment by wakaleo** [comment]
Do you have the webdriver.base.url defined anywhere?

**Comment by xescuder** [comment]
No, it's not defined anywhere

**Comment by wakaleo** [comment]
What url is opening?

**Comment by xescuder** [comment]
It's opening localhost

**Comment by xescuder** [comment]
Sorry, I think I've found the point. I am using in serenity.conf:

environments {
...
  default {
    webdriver.base.url = "http://10.120.187.110"
  }

...
}

Thanks for your support, it made me think about what else what's happening. Besides this, maybe it's an issue? (DefaultUrl should take precedence if it's an string?)

**Comment by wakaleo** [comment]
The expected behaviour (currently) is that the environment default value (if defined) overrides the @DefaultUrl value (which is mainly for isolated testing) (see http://thucydides.info/docs/serenity-staging/#_opening_the_page).

**Comment by xescuder** [comment]
Great, thanks!
