### ISSUE TITLE
Gherkin steps are missing from the Junit XML reports. 

### ISSUE THREAD

**Issue by dipakbachhav** [serenity-bdd/serenity-core#1729]
Gherkin steps are missing from the Junit XML reports.

**Comment by wakaleo** [comment]
Serenity generates JUnit XML reports for the executed features and scenarios. A feature maps to a test suite, and a scenario to a test case. The JUnit XML format doesn't support any additional layers (https://www.ibm.com/support/knowledgecenter/en/SSUFAU_1.0.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html)

**Comment by dipakbachhav** [comment]
But what about gherkin steps like given.. when ..then.. those are missing from the junit test report.

**Comment by wakaleo** [comment]
They cannot be reported in the JUnit reports because JUnit does not support nested elements inside a test element.
