### ISSUE TITLE
Scenario is not displayed as Pending in Serenity reports

### ISSUE THREAD

**Issue by VictoriiaKakhniy** [serenity-bdd/serenity-core#1731]
serenity-core - 2.0.41
serenity-cucumber - 1.9.31
![image](https://user-images.githubusercontent.com/36822449/60525662-7f69b500-9cf7-11e9-9849-d4d7aa6e8d65.png)
![image](https://user-images.githubusercontent.com/36822449/60525714-93151b80-9cf7-11e9-8aa1-6cf2097aa231.png)

**Comment by wakaleo** [comment]
That doesn't appear to be a pending scenario. But try with the latest version (see 
https://github.com/serenity-bdd/serenity-core#what-is-the-latest-stable-version-i-should-use)

**Comment by VictoriiaKakhniy** [comment]
Thank you for quick answer. With previous versions feature was displayed as pending 
![image](https://user-images.githubusercontent.com/36822449/60528020-281a1380-9cfc-11e9-8aa1-b21275791bbd.png), but not on pie chart. When I used latest versions,  
![image](https://user-images.githubusercontent.com/36822449/60528161-82b36f80-9cfc-11e9-81d0-fbee6ecdb7fc.png) it is not displayed as pending at all. 
![image](https://user-images.githubusercontent.com/36822449/60528303-d4f49080-9cfc-11e9-8bdf-9df45968ae0c.png)

**Comment by wakaleo** [comment]
That doesn't look right. Can you provide a sample project?

**Comment by wakaleo** [comment]
Why do you expect it to be pending?

**Comment by VictoriiaKakhniy** [comment]
I tried to make Scenario pending in such way it was described here in serenity documentation. 
![image](https://user-images.githubusercontent.com/36822449/60584018-c659b800-9d94-11e9-9015-85e5b0c7aab3.png), because making this way didn't work for me 
![image](https://user-images.githubusercontent.com/36822449/60584080-eab59480-9d94-11e9-87d3-3dd48ef86cd4.png). But after specifying @pending tag in -Dcucumber.options it worked (mvn clean verify serenity:aggregate -Psequential-run -Dcucumber.options="--tags @smoke,@regr
ession,@pending"
).
![image](https://user-images.githubusercontent.com/36822449/60584234-5bf54780-9d95-11e9-8ed6-4dd8b542e614.png)
Issue may be closed.
Thank you for help.
