### ISSUE TITLE
Could add getter for notepad in Actor class

### ISSUE THREAD

**Issue by kedziorm** [serenity-bdd/serenity-core#1732]
Actor class contains

`private Map<String, Object> notepad`

that is used to `remember` and `recall` Object under specific key.

However it seems there's no possibility to get whole map of the remembered notepad.

Could you please add a getNotepad method?

**Comment by wakaleo** [comment]
That could be useful. What is your use case? ie would the map be read only or modifiable? (The second case might be problematic)

**Comment by kedziorm** [comment]
Thank you.

I need a read only (notepadkey) map. I am implementing a method that will recall remembered value from actor *or* throw an Exception if actor does not recall particular key.

**Comment by wakaleo** [comment]
Fixed in 2.0.57
