### ISSUE TITLE
Shared tag not working between Tasks

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#1733]
Shared tag is not working between Tasks. Example:

1. ReferenceData class:

public class ReferenceTestData {
    protected Locale userLocale;

    public ReferenceTestData() {}
    public ReferenceTestData(Locale userLocale) {
        this.userLocale = userLocale;
    }
}

2. Task where reference data is created (Spring also used to inject DSL and DAOs, ...)

@ContextConfiguration
@SpringBootTest(classes = {TestConfig.class, BddApplication.class})
@ActiveProfiles("test")
public class PrepareReferenceTestData implements Task {
    @Shared
    ReferenceTestData referenceTestData;

    @Autowired
    TestConfigDAO testConfigDAO;

    public PrepareReferenceTestData() {
    }

    public PrepareReferenceTestData(String username) {
        this.username = username;
    }

    public static Performable inTheTestEnvironment(String username) {
        return instrumented(PrepareReferenceTestData.class, username);
    }

    @Override
    public <T extends Actor> void performAs(T actor) {
        ...
        referenceTestData = new ReferenceTestData(testConfigDAO.getUserLocale(username));
    }
}

3. The task called after previous task

public class Logon implements Task {
    @Shared
    ReferenceTestData referenceTestData;

    LogonPage logonPage;
    private LogonInfo logonInfo;
    public Logon() {
    }
    public Logon(LogonInfo logonInfo) {
        this.logonInfo = logonInfo;
    }
    @Step("{0} opens the application")
    public <T extends Actor> void performAs(T actor) {
         ...
   }

The attribute with Shared annotation is empty, has not the same content created in first task.

4. The steps are:
 
theActorInTheSpotlight().wasAbleTo(
                PrepareReferenceTestData.inTheTestEnvironment(loginInfo.getUsername()),
                Logon.withUserAndPassword(loginInfo));
    }

Debugging code the two are different instances:
com.roche.infinity.model.ReferenceTestData$$EnhancerByCGLIB$$281b52a0@45b96e4c
and the other has another identifer.

Using serenity release: 2.0.56

**Comment by wakaleo** [comment]
I don’t recall the @shared annotation, where does it come from?

**Comment by xescuder** [comment]
Sharing instances using the @Shared annotation: https://serenity-bdd.github.io/theserenitybook/latest/step-libraries.html

**Comment by xescuder** [comment]
I've debugged the code, but I don't see where the first instance is propagated to be shared.

**Comment by xescuder** [comment]
Sorry, John, but I'm blocked with this problem, and I can't progress in our project. Thanks!

**Comment by globalworming** [comment]
did you try to use the solution in https://johnfergusonsmart.com/sharing-state-steps-serenity-bdd/ ?
`Serenity.setSessionVariable("User Name").to("Jane");`

**Comment by xescuder** [comment]
Yes, setSessionVariable works, but the Shared annotation is a little more elegant, as you can define as a property in tasks or interactions, and not Steps or block code needs to be created.

**Comment by wakaleo** [comment]
It's a bug due to creating a task using new instead of Instrumented.instanceOf(). Looking into it now.

**Comment by xescuder** [comment]
Great. Thanks

**Comment by xescuder** [comment]
I''ve updated to new version, but it's not working

**Comment by wakaleo** [comment]
2.0.59?

**Comment by xescuder** [comment]
Yes, 2.0.59

**Comment by wakaleo** [comment]
I can't reproduce this issue for 2.0.59 - can you provide a sample project?

**Comment by xescuder** [comment]
It's very difficult to give a sample project, as it has many dependencies with infrastructure services, and screens are generated from a server propietary product (with licenses). The code that doesn't work is specifically the code added at first comment. 

If I can give you more information about how to reproduce it please don't hesitate to tell me (maybe I can debug some lines with your indications).
