### ISSUE TITLE
How to perform mouseover on UIInteractionSteps class

### ISSUE THREAD

**Issue by tremkonzah** [serenity-bdd/serenity-core#1734]
I don't see mouseover or focuse to web element on UIInteractionSteps?
is it possible to perform mouseover with serenity cucumber?

**Comment by wakaleo** [comment]
The UIInteractionSteps has all the methods of the PageObject class, so you can use a similar approach, eg withAction()...

**Comment by wakaleo** [comment]
Presume answered.
