### ISSUE TITLE
SerenityBDD and JBehave multiple parameterized tables.

### ISSUE THREAD

**Issue by gheeno** [serenity-bdd/serenity-core#1735]
Can JBehave support multiple example table for a single Story?

The issue is - I have been writing tests with one single table, and some scenarios require a lot of data - which in turn I am finding myself creating a long table.

`! -- CURRENT

GIVEN $user1 logs in
WHEN user fills <name> , <address> , <etc1> , <etc2>
THEN user can see <dataHere> , and <someDataThere>

Example:
|name|address|etc1|etc2|dataHere|someDataThere| ... so on and so forth.
|john|canada|etcData|etcData|hereData|thereData| .... so on and so forth

! -- What's in my head

GIVEN $user1 logs in
WHEN user fills <name> , <address> , <etc1> , <etc2>
THEN user can see <dataHere> , and <someDataThere>

Example:
|name|address|etc1|etc2|dataHere|someDataThere| 
|john|canada|etcData|etcData|hereData|thereData|

Example2:
|extraData1|extraData2|extraData3|extraDat4a|extraData5|extraData6| 
|value1|value1|value1|value1|value1|value1|`

**Comment by wakaleo** [comment]
This is possible with Cucumber but not with JBehave

**Comment by wakaleo** [comment]
Answering, presumed answered.
