### ISSUE TITLE
Serenity Execute on multiple environment

### ISSUE THREAD

**Issue by sahutarun** [serenity-bdd/serenity-core#1736]
Hi,

I am trying to achieve multi environment execution. I have serenity.properties and serenity.config file. I have different urls kept for diff env.
[senenityconfig.txt](https://github.com/serenity-bdd/serenity-core/files/3369828/senenityconfig.txt)

I am executing the below command:
mvn verify -Denvironment=staging

My method that pick the url is:
public void open_Home_page(String locale)throws Exception{
		EnvironmentVariables environmentVariables = null;
		String url =  EnvironmentSpecificConfiguration.from(environmentVariables)
                .getProperty("webdriver.base.url");
		getDriver().get(url);
		maximizeBrowser();
	}

But it is not working. Can someone please help me to address this issue.

**Comment by wakaleo** [comment]
The environment variables field should be a field of the Page Object class, not inside the method.

**Comment by sahutarun** [comment]
Kept the environment variables field at class level now it says Environment 'webdriver.base.url' property undefined for environment 'null'

public class Base extends PageObject {

	Logger log = Logger.getLogger(Base.class);

	Login login;
	
	Hooks hooks;
	
	EnvironmentVariables environmentVariables = null;

	@FindBy(how = How.XPATH, using = "//p[@id='__bric_access_button_text']")
	public WebElementFacade acceptCookieAlert;

	public void open_Home_page(String locale)throws Exception{
		String url =  EnvironmentSpecificConfiguration.from(environmentVariables)
                .getProperty("webdriver.base.url");
		getDriver().get(url);
		maximizeBrowser();
	}

**Comment by wakaleo** [comment]
Don't set it to null.

**Comment by sahutarun** [comment]
Hi,

I set the env field to not null now it gives ```
Tests in error:
  No environment configuration found for environment 'prod'
```
though i have prod set in config 

environments {
    localhost {
        webdriver.base.url = "http://localhost:8080/"
    }
    staging {
        webdriver.base.url = "http://staging.devatlant.com"
    }
    prod {
        webdriver.base.url = "http://my.super.production.com"
    }
}

I am running the mvn command as mvn verify -Denvironment=prod

I as there anything I am missing?

**Comment by wakaleo** [comment]
Where is your configuration file and what is it called?

**Comment by sahutarun** [comment]
Config file is under below path src\test\resources\senenity.config

it is named as senenity.config

The project also has serenity.properties which contains stuff other than webdriver.base.url

**Comment by wakaleo** [comment]
It should be `serenity.conf`

**Comment by sahutarun** [comment]
Thanks John i was able to run. Thank you so much.

**Comment by Chelinadevi** [comment]
environments {
    default {
       	security.base.url = "---------"
		device.base.url = "-----------"
		site.base.url = "---------------"
   			 }
    dev{
       	security.base.url = "---------"
		device.base.url = "-----------"
		site.base.url = "---------------"
   			 }
}


I have my serenity.conf file as mentioned above(security reasons the url is shown as -------), I have cucumber features around 20 feature files. When using:

private static EnvironmentVariables env_var;

@Before("@Security")
	public static void setup_SecurityURL() 
		RestAssured.baseURI = EnvironmentSpecificConfiguration.from(env_var).getProperty("security.base.url")
				.toString();
	}

	@Before("@Device")
	public static void setup_DeviceURL() {
		RestAssured.baseURI = EnvironmentSpecificConfiguration.from(env_var).getProperty("device.base.url").toString();
	}

	@Before("@Site")
	public static void setup_SiteURL() {
		RestAssured.baseURI = EnvironmentSpecificConfiguration.from(env_var).getProperty("site.base.url").toString();
	}

The specified Hooks are defined in Hooks.java. I am surprised to see the very first scenario from feature is not executed and failing. the other scenarios are passed in all features. I made sure by interchanging 2 scenarios...whatever the 1st scenario is failing. 

The maven cmd i used is : clean verify -Denvironment=dev serenity:aggregate

Pls help me resolve the issue

**Comment by szanelato** [comment]
@Chelinadevi in my case I'm using that declarations and @Before method in the beginning of my test class:

```
  private String endpointBaseUrl;
  private EnvironmentVariables environmentVariables;

    @Before
    public void configureBaseUrl() {
        endpointBaseUrl = EnvironmentSpecificConfiguration.from(environmentVariables)
                .getProperty("my.base.url");
    }
```
I think it can solve your issue.

**Comment by Juanduarhuge** [comment]
Hello. I have the same issue. Here my code:

Try to get the property in Hooks class:

```
public class Hooks {
	private EnvironmentVariables environmentVariables;
	@Before("@accountExists")
	public void beforeScenario() throws IOException
	{
		//for token authentication probably
		String webserviceEndpoint =  EnvironmentSpecificConfiguration.from(environmentVariables)
				.getProperty("endpoint");

	}
}
```
serenity.conf located in src/main/resources

```
environments {

    dev {
        endpoint = "https://testestetest/dev"
    }
    prod {
        endpoint = "http://mywebservice.myapp.myorg.com"
    }
}

```

I have this issue to run mvn clean verify -Denvironment=dev

[ERROR] Do login without existing email and phone #4(Validating Login and Signup APIs)  Time elapsed: 0.014 s  <<< ERROR!
net.serenitybdd.core.environment.UndefinedEnvironmentVariableException: Environment 'endpoint' property undefined for environment 'dev'

try to get the property in another class. The error is that the webserviceEndpoint String is null...

Can you help me, please?

**Comment by nyjoshi** [comment]
Has anyone figured out a way to access more than URLs from serenity.conf? I have been trying to access ID passwords for different env's but keep on getting the null pointer exception. I can access different URLs but not the ID's.
