### ISSUE TITLE
The test reports don't fully generate when using example parameter in the title of the Scenario outline

### ISSUE THREAD

**Issue by bady2bro** [serenity-bdd/serenity-core#1737]
The issue is almost identical to issue:
"Cannot make Serenity report display examples values in Scenario outlines titles" #1188

In addition, the serenity report is partially generated, not allowing drill down into the example steps, just the overview.

Also any fail in the result of the test is not associated with the scenario example.
![SerenityReport](https://user-images.githubusercontent.com/52037336/60969025-2b7a5400-a327-11e9-93fc-4bed255b9c52.png)

        <serenity.core.version>2.0.52</serenity.core.version>
        <serenity.cucumber.version>1.9.39</serenity.cucumber.version>
        <serenity.rest.version>2.0.52</serenity.rest.version>
        <failsafe.include.pattern>**/*Suite.java</failsafe.include.pattern>
        
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.core.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-emailer</artifactId>
                        <version>${serenity.core.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <reports>email</reports>
                </configuration>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by wakaleo** [comment]
Try with 2.0.56

**Comment by bady2bro** [comment]
> Try with 2.0.57

The versions for serenity-plugin and serenity-core packages are out of sync? core is 2.0.58 and plugin jumped from 2.0.56 to 2.0.59

**Comment by wakaleo** [comment]
Should 2.0.59

**Comment by bady2bro** [comment]
> Should be 2.0.59

core still 2.0.58 and serenity-maven-plugin 2.0.59:
![image](https://user-images.githubusercontent.com/52037336/61064105-d2cfb780-a409-11e9-89b9-0ba4c54bfb02.png)
 
![image](https://user-images.githubusercontent.com/52037336/61064175-f09d1c80-a409-11e9-80d8-0078040863b2.png)

how is the sync done?

**Comment by bady2bro** [comment]
> Try with 2.0.57

Update on this suggestion
The issue is still present on the 2.0.60 version of serenity-bdd/serenity-core

**Comment by wakaleo** [comment]
I don’t understand your use case; you will need to provide a sample project. Or better still, dig into the table rendering code and see what needs fixing.

**Comment by bady2bro** [comment]
It is the standard use case of a Scenario Outline with examples and the example variable used in the Title.
In the Serenity report, the title has an empty string in the place of the variable value. 
NOTE the two ' symbols side by side in the highlighted title of the attached photo. They mark the location of the example table variable.
Also NOTE most likely this is also the cause for table issue because the titles are identical if the example is missing so the matching is broken.

**Comment by wakaleo** [comment]
Hmmm, this looks very hard to implement. Have a look at the https://github.com/serenity-bdd/serenity-core/blob/9c44c7df438603f95226e70927569613996ddccc/serenity-reports/src/main/java/net/thucydides/core/reports/html/Formatter.java class if you would like to have a go.

**Comment by senpay** [comment]
@wakaleo Hello! I may have a look. Just to check if I understand the issue properly - when example variable is used in Title it gets replaced with the empty string, but the expectation is that it is stays intact?

**Comment by bady2bro** [comment]
> @wakaleo Hello! I may have a look. Just to check if I understand the issue properly - when example variable is used in Title it gets replaced with the empty string, but the expectation is that it is stays intact?

It looks good. 
One thing though, I would't say "intact". I would expect the example variable to be replaced with the actual value of the current example  or at least the variable itself.

**Comment by senpay** [comment]
@bady2bro Oh, I see. Can you also please share example scenario?

**Comment by bady2bro** [comment]
I don't have access to the original scenario at the moment but using the photo in the original post:

Scenario Outline: Navigates to specific section in the UI and checks all '<filterType>' filters
   Given navigates somewhere
   Then check that all '<filterType>' work as expected
Example:
|filterType|
|text|
|dropdown|
|dateTime|

**Comment by bady2bro** [comment]
note that it has a weirder behavior when the test fails
