### ISSUE TITLE
Serenity (Selenium) waits explanation

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#1738]
From [Serenity documentation](https://github.com/serenity-bdd/serenity-documentation/blob/master/src/asciidoc/system-props.adoc) I see there are essentially three ways to control timeouts in Serenity:

1. webdriver.timeouts.implicitlywait=X
 How long webdriver waits for elements to appear by default, in milliseconds.

2. webdriver.wait.for.timeout=Y
 How long webdriver waits by default when you use a fluent waiting method, in milliseconds.

3. serenity.timeout=Z
 How long should the driver wait for elements not immediately visible, in milliseconds.

I am pretty sure that the first two are what Selenium refers to as "implicit" and "explicit" waits, and the [Selenium documentation](https://www.seleniumhq.org/docs/04_webdriver_advanced.jsp) specifically says:
> Do not mix implicit and explicit waits! Doing so can cause unpredictable wait times.

Am I correct?

Could you please give some more explanation of what the third one controls/does? Does it _collide_ in some undesirable way with either of the other two?

**Comment by wakaleo** [comment]
More or less:

* `webdriver.timeouts.implicitlywait` is used for most implicit waits 
* `webdriver.wait.for.timeout` is the default timeout used in the Serenity wait() methods, if an explicit timeout isn't specified.
* `serenity.timeout` is only used for fairly advanced configurations, and will be deprecated soon.

Explicit waits are waits that are done programmatically: see https://serenity-bdd.github.io/theserenitybook/latest/page-objects.html#_working_with_asynchronous_pages.

**Comment by SiKing** [comment]
Awrite. Thanx.

**Comment by gauravkhuraana** [comment]
Can you please update the link for waits.. and confirm if the third option is removed.. As we have added all 3 and sometimes i see.. it does not wait for 20 seconds though we have defined all 3 of them.

If some examples can also be added for the waits, that can really help

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/docs/guide/page_objects#implicit-waits

**Comment by rockk51** [comment]
@wakaleo can we achieve this using serenity.conf for recent serenity versions, I have below in my serenity.conf but it always times out after 2 seconds
webdriver{
    driver = chrome

  capabilities {
  browserName = "chrome"
      acceptInsecureCerts = true
      "goog:chromeOptions" {
        args = ["remote-allow-origins=*", "test-type", "ignore-certificate-errors", "--window-size=1980,1080"
          "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", "disable-popup-blocking"]
                            }
                }
    timeouts {
      script = 60000
      pageLoad = 6000
      implicit = 45000
              }

        }
