### ISSUE TITLE
Jenkins updating all issues status in Jira cloud

### ISSUE THREAD

**Issue by syedafirdaus** [serenity-bdd/serenity-core#1739]
I have integrated Jenkins with Jira. And presently Jenkins job is updating all issues which are in "In Progress" . But I need to update specific issues related to commits in github. Commit message contains Jira ticket, And I need to update only those issues. Please advise

**Comment by wakaleo** [comment]
How is this related to Serenity BDD?

**Comment by syedafirdaus** [comment]
Ooops sorry, I did not intend to create under this
