### ISSUE TITLE
The first test does not run 

### ISSUE THREAD

**Issue by Adalid07** [serenity-bdd/serenity-core#1740]
Hello,

I'm a new in serenity bdd, I have created a new project in https://github.com/Adalid07/serenitbdd.git  following your video, i opened with idea IDE  then i did some changes in pom xml like version to 2.0.60  and to run the basic test with chrome browser 

Please take a look the console error :

C:\Users\hp\Desktop\serenity\tutorial1>mvn clean verify
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< net.serenitybdd.tutorials:tutorial1 >-----------------
[INFO] Building Serenity project with JUnit and WebDriver 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tutorial1 ---
[INFO] Deleting C:\Users\hp\Desktop\serenity\tutorial1\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tutorial1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\hp\Desktop\serenity\tutorial1\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ tutorial1 ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tutorial1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ tutorial1 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to C:\Users\hp\Desktop\serenity\tutorial1\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ tutorial1 ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ tutorial1 ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: C:\Users\hp\Desktop\serenity\tutorial1\target\tutorial1-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ tutorial1 ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.serenitybdd.tutorials.features.search.SearchByKeywordStory
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   /
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|

 News and tutorials at http://www.serenity-bdd.info
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport
 Learn Serenity BDD online at http://serenity-dojo.com
-------------------------------------------------------------------------------------

[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Search by keyword story
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/

TEST STARTED: search_results_should_show_the_search_term_in_the_title
-------------------------------------------------------------------
[main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
Jul 16, 2019 8:35:55 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: false, browserName: chrome
, goog:chromeOptions: {args: [--enable-automation, --test-type], extensions: []}, platform: ANY, version: }
Starting ChromeDriver 76.0.3809.25 (a0c95f440512e06df1c9c206f2d79cc20be18bb1-refs/branch-heads/3809@{#271}) on port 1223
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[main] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: net.serenitybdd.tutorials.featu
res
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener -
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/
          \_\

TEST FAILED WITH ERROR: Search results should show the search term in the title
---------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Anna opens the Google search page
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
[pool-2-thread-1] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: net.serenitybdd.tuto
rials.features
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.087 sec <<< FAILURE! - in net.serenitybdd.tutorials.features.search.SearchByKeywordStory
search_results_should_show_the_search_term_in_the_title(net.serenitybdd.tutorials.features.search.SearchByKeywordStory)  Time elapsed: 3.254 sec  <<< ERROR!
net.thucydides.core.webdriver.DriverConfigurationError:
Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (session not created: This version of ChromeDriver only suppo
rts Chrome version 76
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ADALID', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: ProvideNewDriver
remote stacktrace: Backtrace:
        Ordinal0 [0x00447B13+1473299]
        Ordinal0 [0x003CAC61+961633]
        Ordinal0 [0x003541A3+475555]
        Ordinal0 [0x002EF365+62309]
        Ordinal0 [0x002EBC77+48247]
        Ordinal0 [0x00308FD9+167897]
        Ordinal0 [0x00308BAD+166829]
        Ordinal0 [0x003072BB+160443]
        Ordinal0 [0x002F0AE6+68326]
        Ordinal0 [0x002F1A80+72320]
        Ordinal0 [0x002F1A19+72217]
        Ordinal0 [0x003E4A27+1067559]
        GetHandleVerifier [0x004E66F5+506677]
        GetHandleVerifier [0x004E6490+506064]
        GetHandleVerifier [0x004ED038+533624]
        GetHandleVerifier [0x004E6ECA+508682]
        Ordinal0 [0x003DC116+1032470]
        Ordinal0 [0x003DBF8F+1032079]
        Ordinal0 [0x003E693B+1075515]
        Ordinal0 [0x003E6AA3+1075875]
        Ordinal0 [0x003E5A55+1071701]
        BaseThreadInitThunk [0x742F8494+36]
        RtlAreBitsSet [0x773341C8+136]
        RtlAreBitsSet [0x77334198+88]
). See below for more details.
        at net.serenitybdd.tutorials.features.search.SearchByKeywordStory.search_results_should_show_the_search_term_in_the_title(SearchByKeywordStory.java:41)

Results :

Tests in error:
  SearchByKeywordStory.search_results_should_show_the_search_term_in_the_title:41  DriverConfiguration

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent! The file encoding for reports output files should be
 provided by the POM property ${project.reporting.outputEncoding}.
[INFO]
[INFO] --- serenity-maven-plugin:2.0.60:aggregate (serenity-reports) @ tutorial1 ---
[INFO] current_project.base.dir: C:\Users\hp\Desktop\serenity\tutorial1
[INFO] Generating test results for 1 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.PackageRequirementsTagProvider@589dfa6f, net.thucydides.core.requirements.File
SystemRequirementsTagProvider@6f8667bb]
[INFO] Loading requirements from package requirements at: net.serenitybdd.tutorials.features
[INFO] LOADED REQUIREMENTS:
REQUIREMENTS:
    - feature : Search {id: Search, displayName: 'Search', path: , parent: 'null'}
        - story : Search by keyword story {id: Search by keyword story, displayName: 'Search by keyword story', path: search, parent: 'Search'}

[INFO] 2 requirements loaded after 578 ms
[INFO] 2 related requirements found after 582 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 657 ms
[INFO] Configured report threads: 40
[INFO] Test results for 1 tests generated in 1.7 secs
[INFO]
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ tutorial1 ---
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent! The file encoding for reports output files should be
 provided by the POM property ${project.reporting.outputEncoding}.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.969 s
[INFO] Finished at: 2019-07-16T20:36:05-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project tutorial1: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\hp\Desktop\serenity\tutorial1\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wakaleo** [comment]
“This version of ChromeDriver only suppo
rts Chrome version 76”.

You need to make sure the chromedriver binary version matches your chrome version.

**Comment by Adalid07** [comment]
Thanks now is working chromedriver was the problem
