### ISSUE TITLE
Multiple CSV files issue

### ISSUE THREAD

**Issue by jayachandrikagadwal** [serenity-bdd/serenity-core#1741]
Hi,
Regarding using multiple csv files in @UseTestDataFrom annotation, It is picking up the data from the csv files only if we have same headers in all the files.
It picks the data only from the first csv file if I have different headers becoz of this method in net.thucydides.core.steps.stepdata.CSVTestDataSource.java

private String[] getTitleRow() {
        return getDataRows().get(0);
    }
Is it possible to do something about this?

**Comment by wakaleo** [comment]
If there are multiple CSV files they must have the same headers. If you would like to propose a pull request to make this more flexible, I'd be happy to review.

**Comment by matthewrwetzel** [comment]
What is the process for proposing a pull request?
