### ISSUE TITLE
How to publishHTML reports always even on fail using declarative pipeline

### ISSUE THREAD

**Issue by ArthiIR** [serenity-bdd/serenity-core#1742]
I have the below declarative pipeline in my Jenkinsfile for the publishHTML

    stage('Compile-ExecuteTests-GenerateReport'){
      agent {node 'Automation'}       
        steps{
           echo "Running the smoke tests"
           sh 'mvn clean verify -Denv="test" -Dtags="smokeTest" serenity:aggregate'

       publishHTML target: [
        allowMissing: false,
        alwaysLinkToLastBuild: false,
        keepAll: true,
        reportName : 'Serenity Report',
        reportDir:   'target/site/serenity',
        reportFiles: 'index.html'
      ]
    }       
      } 
this publishes the report when the tests pass but when the tests fails report does not get published. In the declarative pipeline is there a way to publish report always even on fail or pass?

thanks!

**Comment by wakaleo** [comment]
Probably more a question for https://serenity-bdd.rocket.chat or the Jenkins community.

**Comment by ArthiIR** [comment]
@wakaleo thank you will start with the Jenkins community.

**Comment by Mo0rBy** [comment]
@ArthiIR Did you find a solution to this problem? I know the details of the problem quite well, but I am unable to find a solution.
