### ISSUE TITLE
Serenity report results not updating Jira ticket.

### ISSUE THREAD

**Issue by vr3frankie** [serenity-bdd/serenity-core#1743]
Please can someone help? 
I am running tests in Intellij and producing Serenity reports which have a1 ways links to JIRA but the results are not updating in the JIRA ticket comments. I have tried all sorts. screenshot of
<img width="687" alt="Screenshot 2019-07-20 at 22 44 29" src="https://user-images.githubusercontent.com/51550624/61584463-f9939980-ab3f-11e9-8bc7-d6dc62b856f4.png">

**Comment by wakaleo** [comment]
For general help, https://serenity-bdd.rocket.chat is a better forum. From the information provided, it is hard to answer your question - what versions are you using? Are you seeing any error messages? What version of JIRA are you using?

**Comment by vr3frankie** [comment]
I don't know any version of JIRA other than the dependency, which I have detailed below from my pom file. 
<dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-jira-plugin</artifactId>
                <version>1.12.0</version>
            </dependency>
there are no error messages and a report is produced with a link to the JIRA ticket, I just can't get the results to populate the comments section. I'm very new to Intellij and Serenity, so please excuse my ignorance.
<img width="886" alt="Screenshot 2019-07-20 at 23 00 54" src="https://user-images.githubusercontent.com/51550624/61584591-47110600-ab42-11e9-9ffa-886835225049.png">
