### ISSUE TITLE
Serenity with Cucumber right lifecycle

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#1745]
Using Serenity with Cucumber, and debugging I've seen this order of execution:

- First all methods of plain classes with Before annotation  are executed
- Then all methods on Stepdefs with Before annotation are executed
- If you've defined a fixture service class in META-INF/services/net.thucydides.core.fixtureservices.FixtureService, then his setup method is called
- Finally, the method "apply" of any class that implements BeforeAWebdriverScenario, is called. 

The last two are used to add capabilities to browser and driver. I suggest or think personally that "Before" annotation, as it's used from steps definitions, is something that needs to be executed after driver has already configured, not before. 

For example, if we want to do the login for all our scenarios (Before), and a logoff when scenario is finished (After), we need to start with an already configured driver and capabilities. 

Thanks in advance.

**Comment by wakaleo** [comment]
Most of this is handled by the Cucumber lifecycle code, so I’m not sure how much control the Serenity codebase can have on it.

**Comment by wakaleo** [comment]
We can't modify the order of the Cucumber step execution. However, if you invoke a step that uses WebDriver at any point, the creation methods will be called. E.g.
```
    @Before
    public void prepareTests() {
        setTheStage(new OnlineCast());
        OnStage.aNewActor().attemptsTo(
                Open.browserOn().the(TodoReactHomePage.class)
        );
    }
```
