### ISSUE TITLE
How to keep Serenity Variable Session ?

### ISSUE THREAD

**Issue by vuthelinh** [serenity-bdd/serenity-core#1748]
Dear John.
I know that serenity will be reset each test. I am using serenity Junit with page object but in some cases, I want to share data to other class with 
`Serenity.setSessionVariable("Email").to("serenity_reply@gmail.com");`
and call it in others class
`Serenity.sessionVariableCalled("Email").toString();`

but if I use it in others test the session will be reset. How to keep the session?

Do we have any configuration to change mode: Keep or not keep session ?

Thanks

**Comment by wakaleo** [comment]
Try:
```
serenity.maintain.session = true
```

**Comment by wakaleo** [comment]
General solution implemented in 2.0.63
