### ISSUE TITLE
Serenity-junit - cannot add tags to current parameterized test

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#1749]
**Dependencies**
serenity-junit 2.0.62
Windows 10
Java 11
Gradle 5.5

Having `serenity-junit` test it is possible to inject new tags to current test using `addTagsToCurrentTest` method of event bus:
```java
@RunWith(SerenityRunner.class)
public class NonParameterizedTest  {

    @Before
    public void before() {
        TestTag tag = TestTag.withName("login").andType("stage");
        StepEventBus.getEventBus().addTagsToCurrentTest(newArrayList(tag));
    }

    @Test
    public void testLogin() {
        Assert.assertTrue("login failed!", true);
    }
}
```
I see that tag further in generated JSON output, and also in HTML report
<details><summary>in HTML report</summary>
<p>

![image](https://user-images.githubusercontent.com/6312221/62059978-f9288c00-b22c-11e9-80c9-4b995e4c18c6.png)

Also this tag appears in `Functional Coverage Overview` on main page if set serenity property `report.tagtypes=stage`:

![image](https://user-images.githubusercontent.com/6312221/62060717-4fe29580-b22e-11e9-97e2-41483ed21101.png)

</p>
</details>

**However**, exactly same approach with usage of `addTagsToCurrentTest` does not work if test is parameterized (i.e. uses `SerenityParameterizedRunner.class` runner):
```java
@RunWith(SerenityParameterizedRunner.class)
public class ParameterizedTest {

    private final String paymentType;

    public ParameterizedTest(String paymentType) {
        this.paymentType = paymentType;
    }

    @TestData(columnNames = "payment type")
    public static Collection<Object[]> testData() {
        return asList(new Object[][]{{"CASH"}, {"CREDIT CARD"}, {"VOUCHER"}});
    }

    @Before
    public void before() {
        TestTag tag = TestTag.withName("checkout").andType("stage");
        StepEventBus.getEventBus().addTagsToCurrentTest(newArrayList(tag));
    }

    @Test
    public void testCheckout() {
        System.out.println("use payment type: " + paymentType);
        Assert.assertTrue("checkout failed!", true);
    }
}
```
Tag does not appear in HTML report neither in  JSON output

<details><summary>in HTML report</summary>
<p>

![image](https://user-images.githubusercontent.com/6312221/62060292-87047700-b22d-11e9-907d-343806951a20.png)

</p>
</details>

**Comment by wakaleo** [comment]
You would need to step into the event bus logic, but from memory it may not be running on the same thread, which would make updating the current test from any given code tricky.

**Comment by scormaq** [comment]
Thanks for fast response.
I also naively tried to run parameterized test with `@Concurrent(threads="1")`, but no luck 🙂 

_(Actually, it is possible to add tag using `@WithTag("stage:checkout")`. But my final goal is to make such tags appear in `Functional Coverage Overview` via injecting tags in runtime. I will keep update issue if I have more details)_
