### ISSUE TITLE
Ensure Syntax shows string expectations failures additionally wrapped in <>  or ()

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1751]
When test failure occurs, the html report shows a string expectation quoted but additionally wrapped in chevrons <> or brackets ():

```
Expecting message with text value that is equal to: <"Thank you for NOT telling us about this change."> But got...........................................: <"Thank you for telling us about this change."> 
```

Additionally, in the _More Details_ section, the expectations are instead enclosed in brackets which is a little confusing for people used to the normal type of failure reporting:

```
Expecting message with text value that is equal to: ('Thank you for NOT telling us about this change.')But got...........................................: ('Thank you for telling us about this change.')
````

Here is a screenshot of the above:

![image](https://user-images.githubusercontent.com/626941/62129754-655bcc00-b2cf-11e9-944d-c2560c2cb074.png)

**Comment by wakaleo** [comment]
I think I tried at length to make this consistent but eventually failed and gave up. Feel free to have a go.
