### ISSUE TITLE
Ensure not displayed assertion fails with NoSuchElementException

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1753]
If using the following syntax is used:

```
Ensure.that(<target>).not().isDisplayed()); 
```

then the assertion fails with `NoSuchElementException`. However the following syntax does not throw an exception:

```
seeThat(the(<target>), isNotVisible()));
```

**Comment by wakaleo** [comment]
I don't think that is fixable - the isDisplayed() will always be called before the not(), and so the exception will be thrown before the not() is processed.

**Comment by nbarrett** [comment]
I've tested on 2.0.68 and `Ensure.that(target).isNotDisplayed()` works great so closing 👍. Thanks for the fix!
