### ISSUE TITLE
Chrome capabilities not passed from 2.0.61

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#1757]
I've defined in serenity.properties:

chrome.capabilities.enableVNC = true
chrome.capabilities.enableVideo = true
chrome.capabilities.acceptSslCerts = true

These capabilities are passed correctly until serenity build 2.0.60, but not from 2.0.61. Maybe this is broken after chrome.extension has been included (that I've checked it works in 2.0.62)

**Comment by xescuder** [comment]
Neither it's working using a BeforeAWebdriverScenario implementation. It works until 2.0.60, not after.

**Comment by wakaleo** [comment]
Have you tried with 2.0.66?

**Comment by xescuder** [comment]
In 2.0.66 BeforeAWebdriverScenario is called, but the capabilites passed from serenity.properties don't work.

**Comment by wakaleo** [comment]
Possibly fixed in 2.0.67

**Comment by xescuder** [comment]
Yes, now working in 2.0.67. Thanks!
