### ISSUE TITLE
Able to using PageObject in Screenplay ?

### ISSUE THREAD

**Issue by vuthelinh** [serenity-bdd/serenity-core#1758]
```

public class ClickByUsingPageObject extends PageObject implements Interaction {

    private Target target;
    
    public ClickByUsingPageObject(Target target) {
        this.target = target;
    }

    @Override
    public <T extends Actor> void performAs(T actor) {
              WebElementFacade elementFacade = target.resolveFor(actor);
              withTimeoutOf(Duration.ofSeconds(5)).waitFor(elementFacade).click();

    }    
}
```

Hi John

We can integrate PageOject with Screenplay with this way ?

**Comment by wakaleo** [comment]
You would normally use the actor's BrowseTheWeb ability rather than extending the PageObject class, e.g. https://github.com/serenity-bdd/serenity-core/blob/e36bef50536d22b9473373055ef8313833b2c8be/serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/JSClickOnTarget.java
