### ISSUE TITLE
Error with expandable behavior 

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1759]
#1718 adds the feature of having expandable steps in nested steps, but it looks like it assign the same id for all the steps, so when I try to expand one substep it applies the action to the first one, which causes That I'm not able to see other nested steps or even worst the exceptions that happen on assertions. 

C.C @wakaleo

**Comment by jasonex7** [comment]
I have the same issue. I'm working with Serenity 2.0.65 with Serenity JBehave 1.46.0

**Comment by wakaleo** [comment]
Please take a look at the default.ftl template and see if you can propose a PR that fixes the issue.

**Comment by ricardorlg** [comment]
@wakaleo I found that one of the reasons that cause that the expandables doesn't work in the report is when for example I have a Task that inside call other tasks, and I use the Step annotation to define the description If I change Step to StepGroup everything works in the Reports.

So for me, thins is a workaround, I will close the bug if it is ok for u John.

**Comment by wakaleo** [comment]
This is weird because @StepGroup hasn't been needed for a very long time (in the code it is synonymous with @Step), so I'm a bit confused as to what is causing this.

**Comment by ricardorlg** [comment]
I think it's related to the fact that the PR that adds the expandable, uses the fact that a step is a TestGroup, So when he receives a task this one is marked just as a step, and if inside there are other tasks Serenity doesn't know what to do.  

I will make an example project just to be sure about this.

**Comment by wakaleo** [comment]
The isAGroup() method in the template just checks whether a step has children (it is not related to @StepGroup, which is effectively deprecated).

**Comment by ricardorlg** [comment]
Yes u are right, I test the StepGrop in another project and the bug appears, I will try to check in the project that it's working what could be the reason.

**Comment by ricardorlg** [comment]
More info, AFter a lot of tests, I found that in my case this Bug happens if u have steps that repeat in same scenario.

**Comment by ShaunyPrawn** [comment]
When I originally implemented the change I used a variable to keep track of the substep count (for use as the ID). From what I can tell, the ftl variable isn't scoped specifically to the macro, so when we have multiple levels of nesting across multiple steps the substep count goes out-of-whack.

I've managed to replicate the issue locally and I believe I've fixed the issue. I've committed the changes to my fork in the branch "collapsible_nested_steps" (https://github.com/ShaunyPrawn/serenity-core/tree/collapsible_nested_steps)

@ricardorlg if you get chance, could you give your tests a run against my fork and let me know if this fixes your issue please? If it fixes your issue I'll get a PR raised.

Cheers

**Comment by ricardorlg** [comment]
@ShaunyPrawn sorry for the late reply I have been busy, can u just give me the steps to build ur fork so I can try to test it.

**Comment by nbarrett** [comment]
Hello @ShaunyPrawn - good news - I've built collapsible_nested_steps branch locally and I can't see anything wrong with the expansion now, whereas I was having lots of trouble before:

![image](https://user-images.githubusercontent.com/626941/63033838-30936b80-beb0-11e9-8c8f-cde986a9bb5d.png)


If you could raise a PR for this and get merged before 2.0.70 gets cut that would be awesome please! Thanks very much for this feature - I can now close #1004 :-)

**Comment by ricardorlg** [comment]
@ShaunyPrawn It works to me too, I think the best is to merge it so we can have more feedback

**Comment by ShaunyPrawn** [comment]
Cheers for verifying this and thanks for raising the pull request :smile:
Apologies if the issue has caused any disruptions.

**Comment by JeffGaly** [comment]
@ShaunyPrawn  is this issue fixed?
