### ISSUE TITLE
How can I merge Serenity Reports?

### ISSUE THREAD

**Issue by johnlozanog** [serenity-bdd/serenity-core#1762]
I'm trying to merge Serenity Reports created from different slaves with different contexts:
I execute the next commands:

mvn clean verify -Dmetafilter="+Filter1" -Dwebdriver.remote.driver="chrome" -Dcurrent.environment="Latest" -Dinjected.tags="Env:Latest"

mvn clean verify -Dmetafilter="+Filter1" -Dwebdriver.remote.driver="chrome" -Dcurrent.environment="Stage" -Dinjected.tags="Env:Stage"

I merged the contents of the target/site/serenity into the main project.

I executed the command "mvn serenity:aggregate".

When I open the index page for the report generated by Serenity I only see one of the tags: Latest or Stage but I don't know how to merge the reports to can see both of them.

<img width="1094" alt="Screen Shot 2019-08-06 at 1 11 21 PM" src="https://user-images.githubusercontent.com/53834344/62565117-c04f6f00-b84b-11e9-919d-94abc7486b45.png">

Do you have any suggestion about it?

**Comment by wakaleo** [comment]
You will need to use test contexts for this: https://johnfergusonsmart.com/running-tests-different-environments-browsers-serenity-bdd/

**Comment by johnlozanog** [comment]
Thank you @wakaleo ! 
I didn't think that Context was required.
