### ISSUE TITLE
Serenity report marks a scenario with ignored step as passed 

### ISSUE THREAD

**Issue by shailysingh** [serenity-bdd/serenity-core#1765]
In case of cucumber.runtime.AmbiguousStepDefinitionsException, the overall scenario is being reported as PASSED even though the impacted step is displayed as IGNORED with a small message below the ignored step - Then validation message prohibiting delete action is displayed. (screenshot attached)

Shouldn't this scenario be displayed as PENDING? 

The scenario being displayed as PASSED confuses the testers, since PENDING/FAILED/BROKEN scenarios get quicker attention. PASSING scenarios are left untouched unless there is a need to change them. 

Versions:
java.version: '1.8.0_212'
<serenity.version>2.0.24</serenity.version>
 browserVersion: 76.0.3809.87
chromedriverVersion: 76.0.3809.68
platform: LINUX 
We are using Zalenium containers to run our tests

<img width="436" alt="ignored step but successful scenario" src="https://user-images.githubusercontent.com/27859706/62630280-ea2d9200-b92e-11e9-9945-179adcd6bf90.PNG">

**Comment by wakaleo** [comment]
I have never encountered this case - generally an ambiguous step will crash the build. But I'm happy to review a PR if you would like to propose a fix.

**Comment by shailysingh** [comment]
@wakaleo  Now when I think of it, you are right. I have seen the build crash in the past because of ambiguous step. Not sure if this is already an open issue with Cucumber. I will check there first.
