### ISSUE TITLE
 ((Locatable)eleESC).getCoordinates()  deprecated after migrated to latest version of serenity core

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1770]
Im utilizing the below version of serenity .After upgrading it is throwing error as locatable deprecated .

 compile 'net.serenity-bdd:serenity-gradle-plugin:2.0.48'
  compile 'net.serenity-bdd:serenity-core:2.0.48'

![image](https://user-images.githubusercontent.com/32665795/62857501-6c1a1400-bcbd-11e9-86f6-0445c1a6ba45.png)

I have upddate to this as well still the error .
 compile "org.seleniumhq.selenium:selenium-java:3.9.1"
 compile  "org.seleniumhq.selenium:selenium-api:3.9.1"

**Comment by wakaleo** [comment]
You are using an old version of selenium which is not compatible with the latest version of Serenity. Remove the selenium dependency and let Serenity determine the Selenium version to use.

**Comment by JeffGaly** [comment]
@wakaleo  i removed the selenium version as well and tried still it throws the same error .

**Comment by wakaleo** [comment]
Then maybe there is another dependency pulling in an old Selenium library. Check your dependency tree, or force the Selenium version to 3.141.59.

**Comment by JeffGaly** [comment]
After updating to 3.141.59 it throws error in locatable
![image](https://user-images.githubusercontent.com/32665795/62859714-8951e100-bcc3-11e9-87ce-2844819312e9.png)

**Comment by wakaleo** [comment]
It looks like the Selenium API has changed, and the Locatable interface has moved - but you should be able to use the getCoordinates() method directly without casting.

**Comment by wakaleo** [comment]
Possibly fixed in 2.0.69
