### ISSUE TITLE
[Inquiry] How are screenshots cleaned up?

### ISSUE THREAD

**Issue by gheeno** [serenity-bdd/serenity-core#1772]
Serenity is hooked to Jenkins now and is working as expected. I do see the "full screen" screenshots - which is amazing. 

How do I maintain the screenshots being saved? 
* I was thinking in the lines of "retain screenshot for 5 days" and then delete them. 

If no configuration exists - any tips and advice that I can do to clean up the screenshots saved? ( our server is limited space )

**Comment by wakaleo** [comment]
This is more a question for https://serenity-bdd.rocket.chat, and also a Jenkins/CI question. The real question is, how long do you need them for? Most teams keep only the last few builds, but some builds (such as releases) may need to be kept for audit and traceability purposes.

**Comment by gheeno** [comment]
> This is more a question for https://serenity-bdd.rocket.chat, and also a Jenkins/CI question. The real question is, how long do you need them for? Most teams keep only the last few builds, but some builds (such as releases) may need to be kept for audit and traceability purposes.

Thank you I have been looking for a forum and group for Serenity thank you for sharing the link.

To answer your questions - no specific requirements but I think a couple of days is enough - maybe even 3 days since our tests run over the weekend as well. 

Major release builds - we create reports on them anyway so we actually save important screenshots so I wouldn't worry about that yet.

**Comment by wakaleo** [comment]
I will close this issue so that the conversation can continue on RocketChat.
