### ISSUE TITLE
Steps marked as pending, after reorganising testrunners

### ISSUE THREAD

**Issue by eriklumbela** [serenity-bdd/serenity-core#1774]
**background**
I have the following Serenity JBehave project layout: (in the testrunners directory are my classes extending SerenityStory)

```
src
|-- test
    |-- java
        |-- com.company.team
            |-- definitionsteps
            |-- usersteps
            |-- testrunners
    |-- resources
        |-- stories
            |-- epic1
            |-- epic2
```
**problem**
Once I try to reorganise my testrunners into subfolders, so that it reflects `resources/stories/{epics}` all my steps are marked as `PENDING`. 
In the documentation I read that:

> Serenity will run any JBehave stories that it finds in the default directory location. By convention, it will look for a stories folder on your classpath, so ‘src/test/resources/stories’ is a good place to put your story files.

So I guessed reorganising shouldn't resolve into `PENDING` steps.
*What do I need to configure to prevent this from happening?*

**reproduce**
```
src
|-- test
    |-- java
        |-- com.company.team
            |-- definitionsteps
            |-- usersteps
            |-- testrunners
                |-- epic1
                |-- epic2
    |-- resources
        |-- stories
            |-- epic1
            |-- epic2
```

**Comment by eriklumbela** [comment]
@wakaleo Have you got any suggestions how to solve this?

**Comment by wakaleo** [comment]
Not really. It sounds like a project configuration issue of some kind - maybe the JBehave runners aren't finding the step definition methods.

**Comment by eriklumbela** [comment]
Thanks for your fast reply. Too bad. Does this also mean, this is supposed to work out of the box. 
_(Then I guess, I have to to go over the `pom.xml` and figure out what's wrong)_

**Comment by wakaleo** [comment]
Looking at your project structure, you may need the test runner classes to be in the top level package for the default paths to work.
