### ISSUE TITLE
Is the Ensure API extensible without modifying serenity itself?

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1776]
I'm beginning to try and introduce the Ensure API to my client project but I'm facing a challenge in how to move from the `should()` pattern for two reasons:

### Passing my domain-specific questions to Ensure

I've been experimenting with the various `Ensure` constructors and have found `thatTheAnswersTo(question: Question<Collection<A>>)`, however this only seems to want to take a `Collection<A>` question and no lower level implementations (e.g. `List<String>`, or better still `List<ToDoList>`). For instance I tried to start simple and add a unit test into `net.serenitybdd.screenplay.ensure.WhenUsingFluentAssertionsInJava` but hit up against this:  

![image](https://user-images.githubusercontent.com/626941/62961208-3af02f80-bdf4-11e9-93c0-86f4189fcef5.png)

I did start adding this into `Ensure`:

```
fun <A> thatTheAnswersToSet(description: String, question: Question<Set<A>>) =
        CollectionEnsure(KnowableSetAnswer(question, description), description)

fun <A> thatTheAnswersToSet(question: Question<Set<A>>) = thatTheAnswersToSet(question.subject, question)
```

But for obvious reasons, want to be able to do this in my own project rather than modifying serenity 😄 

### Using my domain-specific matchers with Ensure
The `should()` API  takes a `Consequence` which can be constructed with any `Question` and `Matcher` of the same type, which provides a nicely composable patten for a library user, but how do we enjoy this composability with `Ensure`?

**Comment by wakaleo** [comment]
This is where my knowledge of Kotlin and generics started to reach its current limits :-). Extensibility would be nice, but I’m not too sure how it would work just yet. Best would be to have a play and see what would work for the type of assertions you want to add, then to see how we can make it pluggable.

**Comment by ricardorlg** [comment]
One way is to use extension methods of kotlin, just to add custom things, but related with extending the ensure to use any type on questions like should, is more difficult due to the non unchecked types in kotlin

**Comment by nbarrett** [comment]
I think I should have clarified that my project is several million lines of Java and not likely to change  in the near future project, so we need to be able to compose new stuff into the API using java....
