### ISSUE TITLE
It cannot run step for story when i use junit to test

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#1782]
Hi,
 when i run story with junit , then not run all step for the story, i don't know why? here is output message:

**Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=false,verboseFiltering=false,storyTimeouts=5000000,threads=1,failOnStoryTimeout=false]
15528 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - [36m

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat      
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
 Learn Serenity BDD online at http://serenity-dojo.com                               
-------------------------------------------------------------------------------------
[0m

(BeforeStories)

(AfterStories)

Generating reports view to 'C:\Core\201911\automation\cda-automation-test\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 0 stories (of which 0 pending) containing 0 scenarios (of which 0 pending)**

**Comment by wakaleo** [comment]
This looks like a usage question rather than a bug; maybe you would get a more useful response on https://serenity-bdd.rocket.chat

**Comment by ChrisD1990** [comment]
i re-import the automation project and fixed maven issue, now it can work.
