### ISSUE TITLE
Using any version of serenity-bdd after after 2.0.43 types double characters in IE11

### ISSUE THREAD

**Issue by matthewrwetzel** [serenity-bdd/serenity-core#1785]
I am testing an IE application.   I am successfully have SerenityBDD enter text into text fields with version 2.0.43.  However, using any higher version results in issues either loading the driver or types  double characters in text fields.  

2.0.43                      type("star")    results in the value "star"
higher versions       type("star")    results in "ssttaarr"

I am using the 32 bit version of IDEDriverServer.exe version 3.9 from https://selenium-release.storage.googleapis.com/index.html?path=3.9/    

Tried the 64 bit IDEDriverServer and the tests have issues instantiating that.

Thanks

**Comment by wakaleo** [comment]
I doubt that is related to Serenity - more likely an IEDriver or Selenium version issue.

**Comment by matthewrwetzel** [comment]
Can I load in a different version of Selenium?

**Comment by wakaleo** [comment]
The Serenity code is bound to the Selenium API, so this may be risky.

**Comment by wakaleo** [comment]
Closing this as it appears to be a Selenium/IE Driver issue (https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4446)
