### ISSUE TITLE
Set MIME types when loading .css

### ISSUE THREAD

**Issue by jonfreedman** [serenity-bdd/serenity-core#1786]
I am seeing several errors in Chrome when rendering Serenity reports due to incorrect MIME types, the include tags should be updated to add `type="text/css"`
e.g.
```html
<link rel="stylesheet" type="text/css" href="fontawesome-free-5.3.1-web/css/all.css">
<link rel="stylesheet" type="text/css" href="fontawesome-free-5.3.1-web/css/v4-shims.css">
```
See https://www.w3schools.com/TAgs/att_link_type.asp

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by jonfreedman** [comment]
If you can point me at the site generator I'll have a look, I tried searching but GitHub matches all the example html files...

**Comment by wakaleo** [comment]
It would be in the freemarker templates (https://github.com/serenity-bdd/serenity-core/tree/master/serenity-report-resources/src/main/resources/freemarker or https://github.com/serenity-bdd/serenity-core/tree/master/serenity-report-resources/src/main/resources/freemarker/libraries)
