### ISSUE TITLE
Serenity 2.0.70 : WebElementFacadeImpl class implementation of clear method does not work on Mac OS

### ISSUE THREAD

**Issue by DragonGowda** [serenity-bdd/serenity-core#1788]
We have been using type method as below.
$(strEmail).type(Emailid);
type method logic has a clear method which uses Control+Delete which works only in Windows but when the the same scripts is executed on MAC OS we see failure.

public void clear() {

        if (driverIsDisabled()) { return;}

        if (!isMobileDriver()) {
            getElement().sendKeys(Keys.chord**(Keys.CONTROL, "a"), Keys.DELETE);**
        }
        getElement().clear();
    }

**Comment by wakaleo** [comment]
Well spotted. Could you propose a PR that copes with both OSes?
