### ISSUE TITLE
2.0.70: Chrome experimental options for excludeSwitches not working when provided in serenity.properties

### ISSUE THREAD

**Issue by DragonGowda** [serenity-bdd/serenity-core#1789]
I am using below details in serenity.properties file
chrome_experimental_options.excludeSwitches="[enable-automation]"
chrome_experimental_options.useAutomationExtension=false

However, driver is not instantiating with below error.
Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (invalid argument: entry 0 of 'firstMatch' is invalid

**Comment by wakaleo** [comment]
Could you share the full stack trace?

**Comment by DragonGowda** [comment]
@wakaleo , please find below the stack trace
[pool-2-thread-1] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (invalid argument: entry 0 of 'firstMatch' is invalid

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:902)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:803)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:791)
	at com.wipro.dias.steps.VFHomeSteps.givenTheUserIsOnHomepage(VFHomeSteps.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:790)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:349)
...

**Comment by wakaleo** [comment]
Do you have anything after the ...? There should be some "Thrown By" stack traces as well.

**Comment by AlexChernookov** [comment]
Have a similar issue Aug 29, 2019 10:19:29 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [--enable-automation, --test-type], excludeSwitches: "[enable-automation]", extensions: [], useAutomationExtension: false}, loggingPrefs: org.openqa.selenium.logging..., platform: ANY, version: }
Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 32198
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - STEP ERROR: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - STARTING STEP As user: aaaa
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - IGNORING STEP

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse excludeSwitches
from invalid argument: must be a list
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MACHINE123', ip: '192.168.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: driver.version: ProvideNewDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00DB7C93+1473683]
	Ordinal0 [0x00D3ADB1+961969]
	Ordinal0 [0x00CC42E3+475875]
	Ordinal0 [0x00C58415+33813]
	Ordinal0 [0x00C59EA4+40612]
	Ordinal0 [0x00C57655+30293]
	Ordinal0 [0x00C59EA4+40612]
	Ordinal0 [0x00C55561+21857]
	Ordinal0 [0x00C788E8+166120]
	Ordinal0 [0x00C78DFA+167418]
	Ordinal0 [0x00C78D1D+167197]
	Ordinal0 [0x00C7742B+160811]
	Ordinal0 [0x00C60AE6+68326]
	Ordinal0 [0x00C61BF0+72688]
	Ordinal0 [0x00C61B89+72585]
	Ordinal0 [0x00D54B77+1067895]
	GetHandleVerifier [0x00E56875+506677]
	GetHandleVerifier [0x00E56610+506064]
	GetHandleVerifier [0x00E5D1B8+533624]
	GetHandleVerifier [0x00E5704A+508682]
	Ordinal0 [0x00D4C266+1032806]
	Ordinal0 [0x00D4C0DF+1032415]
	Ordinal0 [0x00D56A8B+1075851]
	Ordinal0 [0x00D56BF3+1076211]
	Ordinal0 [0x00D55BA5+1072037]
	BaseThreadInitThunk [0x775D0419+25]
	RtlGetAppContainerNamedObjectPath [0x77D9662D+237]
	RtlGetAppContainerNamedObjectPath [0x77D965FD+189]
). See below for more details.

	at ...pages.LoginPage.prepareDriver(LoginPage.java:44)
	at ...pages.LoginPage.openAnUrl(LoginPage.java:63)
	at ...pages.LoginPage.openBackdoorPage(LoginPage.java:71)
	at ...steps.LoginSteps.go_to_login_page(LoginSteps.java:12)
	at ...webtests.BackdoorLoginWebTests.should_not_login_as_unknown_user(BackdoorLoginWebTests.java:25)


[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: should not login as unknown user
---------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Go to backdoor login page
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate class org.openqa.selenium.chrome.ChromeDriver

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Process finished with exit code -1

**Comment by AlexChernookov** [comment]
private WebDriverFacade prepareDriver() {
        WebDriverFacade driver = (WebDriverFacade) this.getDriver();
        WebDriverFacade.Window window = driver.manage().window();
        window.setPosition(new Point(0, 0));
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        if (screenSize.getWidth() < 1920 & screenSize.getHeight() < 1080) {
            window.maximize();
        } else {
            Dimension dim = new Dimension(1920, 1080);
            window.setSize(dim);
        }
        WebDriverFacade.Timeouts timeouts = driver.manage().timeouts();
        timeouts.implicitlyWait(1, TimeUnit.SECONDS);
        timeouts.pageLoadTimeout(60, TimeUnit.SECONDS);
        timeouts.setScriptTimeout(30, TimeUnit.SECONDS);
        this.setDriver(driver);
        return driver;
    }

**Comment by purushothamn31** [comment]
https://github.com/purushothamn31/how-to-disable-the-infobar-Chrome-is-controlled-by-test-software-in-serenity.property-file/issues/1

please give the solution to above issue
