### ISSUE TITLE
Long Jbehave story tags breaking serenity report - Overall Test Results

### ISSUE THREAD

**Issue by kirangeorgeb** [serenity-bdd/serenity-core#1790]
We had Tags generated from Jbehave Story files. As the tags were long, the whole page formatting broke. Do not find Capabilties, Features and Stories section in Home.

version 2.0.70

<img width="1432" alt="Screen Shot 2019-08-27 at 2 41 57 AM" src="https://user-images.githubusercontent.com/54578142/63760615-7ec34a00-c874-11e9-8ab9-2572dbb6d3a7.png">
<img width="1440" alt="Screen Shot 2019-08-27 at 2 41 27 AM" src="https://user-images.githubusercontent.com/54578142/63760614-7e2ab380-c874-11e9-82b5-43be771ae196.png">

**Comment by wakaleo** [comment]
Could you show the top of the Tags section?

**Comment by wakaleo** [comment]
You can use the `dashboard.excluded.tag.list` to prevent story tags from appearing on the dashboard. That said, user story names in a BDD context are intended to be fairly short and concise (like chapter or section headings), not long phrases. These look more like scenarios or acceptance criteria. So you may want to review your story naming/sliding approach.
