### ISSUE TITLE
How to run serenity-junit tests in parallel with surefire-maven plugin.

### ISSUE THREAD

**Issue by AndriiChorniak** [serenity-bdd/serenity-core#1792]
Now I am running tests with fork parameter by classes. Is there any way to run tests by methods without fork?

**Comment by AndriiChorniak** [comment]
Hi John, 
Could you help me with my question?

**Comment by wakaleo** [comment]
I don’t have any specific answer; getting the surefire options right is a bit tricky. Best option is to experiment and see what works and what doesn’t. Serenity uses a thread-local model for its messaging; running classes in parallel should be fairly safe.

**Comment by AndriiChorniak** [comment]
I am experimenting. It seems like only with fork parameter serenity works in parallel. But parallel by method could be more effective.
Are you going to use JUnit 5?

**Comment by wakaleo** [comment]
We will upgrade to JUnit 5 soon. Parallel methods are not possible for technical reasons.
