### ISSUE TITLE
How to generate Serenity email report in output directory reports folder ?

### ISSUE THREAD

**Issue by swetha890** [serenity-bdd/serenity-core#1793]
Hi There, 
i am using serenity and maven versions 2.0.41.
i am trying to generate emailable serenity summary reports along with index.html in single unique folder, to achieve this i have added "build-helper-maven-plugin" artifact for timestamp and using it to append to reports folder name
My POM looks like this
```
		<plugin>
    <groupId>net.serenity-bdd.maven.plugins</groupId>
    <artifactId>serenity-maven-plugin</artifactId>
    <version>${serenity.maven.version}</version>
    <dependencies>
        <dependency> 
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-emailer</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>1.7.0</version>
		</dependency>
    </dependencies>
    <configuration>
        <tags>${tags}</tags>
        <reports>email</reports> 
    </configuration>
    <executions>
        <execution>
            <id>serenity-reports</id>
            <phase>post-integration-test</phase>
         <goals>
            <goal>aggregate</goal>
            </goals>  
            <configuration>
					<outputDirectory>./reports/${current.time}-${xx}-${xx}</outputDirectory>
				</configuration>                      
        </execution>        
    </executions>
    
</plugin> 
```
With this i am not able to generate serenity-summary.html inside reports folder....it always get generated inside target/site/serenity/ .....so i tried below
 https://dzone.com/articles/configuring-different-output-directories-with-sere  
However with this my reports override after each build which is not helpful .
Is there a way to generate serenity-summary.html inside reports folder (folder name appended with time stamp to avoid overriding ) else is there a way to set output directory in serenity properties and append timestamp to the folder (unique index.html and summery.html)
Thanks in advance.

**Comment by wakaleo** [comment]
It looks like the output directory configured in the serenity-maven-plugin (in the `SerenityAggregatorMojo` class) is not being passed to the email reporter (`net.serenitybdd.reports.email.EmailReporter`), so at the moment this is not supported. Maybe have a look at the code and see if you can propose a PR to inject the report output directory and/or other parameters.

**Comment by swetha890** [comment]
Hi Wakaleo,
i have created pull request for properties and POM files, please let me know if that helps or do i need to import entire project.
Thanks in advance.

**Comment by wakaleo** [comment]
I’m not sure what you mean?

**Comment by swetha890** [comment]
Sorry i sent you my current files , i do not know where to begin with! i would appreciate
if you provide tips/suggestions on where to get started.

**Comment by swetha890** [comment]
I have used maven-copy-resources plugin to copy my summary.html into reports folder path and it worked out as expected!! 
Thanks😊
