### ISSUE TITLE
Documentation wrong / misleading for serenity.config

### ISSUE THREAD

**Issue by Schoaf** [serenity-bdd/serenity-core#1795]
https://serenity-bdd.github.io/theserenitybook/latest/environment-specific-config.html

Documentation does not mention, that "webdriver.base.url" is mandatory. otherwise you get a
`net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for SharedAaxSteps:Environment 'webdriver.base.url' property undefined for environment 'null'`

but when you set the "webdriver.base.url" it will substitude other urls you try to use in @DefaultUrl()

by using trial and error I found out that you can set "webdriver.base.url" to "". Then nothing gets replaced and you can use the urls specified in the serenity.conf

**Comment by AvA0808** [comment]
I had an issue where I removed "default { }" from the environments section. Lost a lot of time to figure out that even though you add other environments. Default has to be there.

**Comment by wakaleo** [comment]
What version of Serenity are you using. The `webdriver.base.url` is not mandatory. If you don't define it, the @DefaultUrl url will be used. The default section is not mandatory either - it is just a convenient fallback mechanism. If no matching environment is found, the @DefaultUrl url will be used.

**Comment by Schoaf** [comment]
Using serenity-maven 2.0.70

**Comment by wakaleo** [comment]
I can’t reproduce the behaviour you are describing.
