### ISSUE TITLE
Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver

### ISSUE THREAD

**Issue by skumar1122** [serenity-bdd/serenity-core#1796]
Hello,

I am using Serenity-BDD with Appium for mobile web testing and I wanted to run tests from maven verify(I guess this is the way we do in serenity). I am getting error when I am running tests on real devices(ANDROID and iOS devices) from` maven verify`. It works fine when you start normally. 
It complaints with this command - `mvn clean verify -PSMOKE_DEV -Dappium.platformName=ios`.
It launches Safari couple of times and crashes it straight away. It opens third time and It gives me some errors in console.

I am curious to know is this because of using appium with serenity. As, Serenity-BDD works fine for me for desktop tests even from maven verify including parallel tests. 

I have attached my console logs here, Please let me know if I am missing anything?

Console logs -https://gist.github.com/skumar1122/cfd145611cdf24fb96daf008f46ccd58
pom.xml settings - https://gist.github.com/skumar1122/3aeffbc06927e1e1750fb540dcb5ba1d

Many Thanks in Advance.

**Comment by wakaleo** [comment]
"Could not instantiate the custom webdriver provider of type mydriver" means an error occurred during the creation of your custom driver, or it could not find the custom driver class.

**Comment by skumar1122** [comment]
Thanks John for reply.
My #serenity properties
##appium driver
webdriver.driver=provided
webdriver.provided.type=mydriver
webdriver.provided.mydriver=drivers.Appium1Driver
serenity.driver.capabilities=mydriver

It works when you run normal but yeah its throwing error with `mvn verify`. my serenity properties are correct isn't ?

**Comment by skumar1122** [comment]
Thanks @wakaleo for reply.
My local properties modified as below,

#serenity properties
##appium driver
webdriver.driver=provided
webdriver.provided.type=mydriver
webdriver.provided.mydriver=drivers.Appium1Driver
serenity.driver.capabilities=mydriver

It works when I run normally as JUnit test but its throwing error when I run using mvn verify to run using profiles for parallel testing.

Does serenity supports this ? please let me know.

Thanks

**Comment by wakaleo** [comment]
Serenity supports parallel tests using Maven (surefire or failsafe), but I'm not sure about Appium - it may depend on your custom driver implementation.

**Comment by skumar1122** [comment]
Hi @wakaleo Just to add an update,

I fixed my tests, If we are running tests from profile using appium, I think we cannot use `<parallel>all</parallel>` option in pom.xml. I am not sure If there is a way to run this to open multiple browsers on mobile but as far I think we can only open sequentially(for one test we can open one browser).

Thanks
Shiva
