### ISSUE TITLE
Repetitive assertions while using orComplainWith on an EventualConsequence

### ISSUE THREAD

**Issue by sricharanya** [serenity-bdd/serenity-core#1799]
While using an EventualConsequence as follows:
```
theActorInTheSpotlight().should(eventually(seeThat(
            TheDashboard.visibility(), is(true)))
            .waitingForNoLongerThan(20).seconds()
            .orComplainWith(DashboardNotVisible.class));
    }
```

the consequence is asserting and writing debug logs for every lap of the 20 second timer. Is it possible to assert(complain) only when the entire timeout is elapsed?

This will be very much helpful for especially for logging. Even asserts that don't eventually cause a failure are getting a full stack dump logged every time they a test the assert. It get difficult to read the log file.

**Comment by wakaleo** [comment]
Sounds like a good improvement. Maybe take a look at the code and see if you can propose a PR (it should be a fairly easy change I think).

**Comment by patrickvkb** [comment]
Indeed, having also an assert when then entire timeout is elapsed would be useful.   Be it only to be able to see appearing in the Serenity test reporting that something did not happen within the foreseen timeout.
