### ISSUE TITLE
Centralize dependency version declarations

### ISSUE THREAD

**Issue by jeffjensen** [serenity-bdd/serenity-core#18]
Various modules have differing versions and therefore conflicts.  Yes, gradle will resolve them, but it presents convergence problems and unknown potential problems.

Perhaps move all dependency versions to top build config and inherit them as possible or use properties.

**Comment by YamStranger** [comment]
Hi @jeffjensen. Thanks for this issue. Now it already fixed, all lib version configuration under [build.gradle](https://github.com/serenity-bdd/serenity-core/blob/master/build.gradle#L26). Can you close this issue?
