### ISSUE TITLE
Values of Examples of Scenario oultine is displayed as Null

### ISSUE THREAD

**Issue by hariharanravichandran** [serenity-bdd/serenity-core#1803]
Serenity Core Version: 1.8.1
Serenity Cucumber Version: 1.6.5
![image](https://user-images.githubusercontent.com/22173640/64608805-13878500-d3e9-11e9-8ea4-8729b8a1ae75.png)

Serenity Core Version: 2.0.56
Serenity Cucumber Version: 1.9.40
![image](https://user-images.githubusercontent.com/22173640/64608856-2ef29000-d3e9-11e9-9653-6c1eb2f6b33a.png)

**Comment by wakaleo** [comment]
This appears to work correctly with serenity-core 2.0.70 and serenity-cucumber 1.9.45 or 2.0.21:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/55986/64614810-39089480-d3d1-11e9-835e-02e373932521.png">

**Comment by hariharanravichandran** [comment]
Hi @wakaleo , Issue is resolved in the version mentioned(serenity-core 1.0.70). But, the issue is still reproducible when we execute our tests in Jenkins.

**Comment by hariharanravichandran** [comment]
This issue happens when we execute multiple features with scenario outline. When we execute a single feature with Scenario outline,  Report is generating correctly

**Comment by totovelo10** [comment]
@Hi @wakaleo is the issue is solved?
Like @hariharanravichandran the issue appears when tests are executed on jenkins.
pom.xml extract : 

<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>2.0.70</serenity.version>
		<serenity.maven.version>2.0.70</serenity.maven.version>
		<serenity.cucumber.version>1.0.21</serenity.cucumber.version>
		<cucumber.version>4.2.0</cucumber.version>
		<webdriver.driver>firefox</webdriver.driver>
	</properties>

<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber4</artifactId>
			<version>${serenity.cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>

**Comment by wakaleo** [comment]
Running on Jenkins should make no difference unless you are running it with a different pom file on Jenkins. I have never been able to reproduce it, but I suspect it is an issue of incorrect dependency versions.

**Comment by totovelo10** [comment]
Thank you.
Can you tell me what combination between serenity and cucumber do you recommend ?

**Comment by wakaleo** [comment]
https://github.com/serenity-bdd/serenity-core#what-is-the-latest-stable-version-i-should-use

**Comment by hariharanravichandran** [comment]
I am getting the following Error when I tried to run the test with following changes:
Serenity-core : 2.0.69
serenity-maven-plugin : 2.0.69
serenity-cucumber4 : 1.0.18
Error Message: 
The following artifacts could not be resolved: net.serenity-bdd:serenity-screenplay:jar:2.0.59, net.serenity-bdd:serenity-screenplay-webdriver:jar:2.0.59: Could not find artifact net.serenity-bdd:serenity-screenplay:jar:2.0.59

**Comment by wakaleo** [comment]
Use the latest recommended versions

**Comment by hariharanravichandran** [comment]
This is the latest combination mentioned in https://github.com/serenity-bdd/serenity-core#what-is-the-latest-stable-version-i-should-use for Cucumber 4

**Comment by totovelo10** [comment]
@hariharanravichandran why do you have 2.0.59 in the log it is not should be 2.0.69?

**Comment by hariharanravichandran** [comment]
In Serenity Cucumber4 version 1.0.18, 2.0.59 is used as dependency

**Comment by totovelo10** [comment]
Look at the table 
![serenity_combination](https://user-images.githubusercontent.com/13166452/67865621-dce80400-fb27-11e9-9da3-9cae15afc235.PNG)

**Comment by totovelo10** [comment]
@wakaleo I change the dependencies following the latest stable version table, but i still have the Example null issue when tests were executed in jenkins
here part of my pom.xml


![p1](https://user-images.githubusercontent.com/13166452/67933980-33584f80-fbc7-11e9-8f01-28c364e6a2b3.PNG)

![p2](https://user-images.githubusercontent.com/13166452/67933977-33584f80-fbc7-11e9-8dc8-22437b2f33d6.PNG)

**Comment by wakaleo** [comment]
Try with 2.0.81 and 1.0.25

**Comment by totovelo10** [comment]
@wakaleo 1.0.25 for which dependence?

**Comment by wakaleo** [comment]
Serenity-cucumber

**Comment by totovelo10** [comment]
My pom.xml contains the serenity-cucumber4 dependency and its last version on maven repository is 1.0.21
https://mvnrepository.com/artifact/net.serenity-bdd/serenity-cucumber4
serenity-cucumber has not a 1.0.25 version
https://mvnrepository.com/artifact/net.serenity-bdd/serenity-cucumber

**Comment by wakaleo** [comment]
Sorry, I meant 1.0.21

**Comment by totovelo10** [comment]
I tried combination 2.0.81 and 1.0.21 and i still have the same issue.
In addition the Most Frequent Failures links are broken

**Comment by wakaleo** [comment]
Did you also update the serenity-maven-plugin version?

**Comment by totovelo10** [comment]
Yes I did. Here what i have in pom xml 
![pomproperties](https://user-images.githubusercontent.com/13166452/68282260-a3f4e580-0079-11ea-95ff-8fd8f4e664e6.PNG)
And later in the pom...
![pomplugin](https://user-images.githubusercontent.com/13166452/68282265-a7886c80-0079-11ea-9eab-84b292a2e62e.PNG)

**Comment by wakaleo** [comment]
Can you provide a sample project?

**Comment by totovelo10** [comment]
No I can't.  I work in a private company project I don't have the rights

**Comment by wakaleo** [comment]
The pom file won’t be helpful - it’s most likely related to your tests. In that case maybe consider raising a support ticket (https://johnfergusonsmart.com/serenity-bdd-mentoring/) so that we can look at the code directly.

**Comment by totovelo10** [comment]
How could this be related to my tests while the issue **only** when the serenity-report is generated by Jenkins?

**Comment by wakaleo** [comment]
It may also be related to your Jenkins config.

**Comment by totovelo10** [comment]
Which Jenkins config part could have an impact on Serenity report?

**Comment by totovelo10** [comment]
@hariharanravichandran have resolve the issue?

**Comment by wakaleo** [comment]
If the reports are generated successfully locally, but not on Jenkins, the only explanation is that there is something different about the way Serenity is being executed on Jenkins. I couldn't really say more without seeing the Jenkins config.

**Comment by hariharanravichandran** [comment]
@totovelo10 Issue is still existing. I am using Zalenium docker on Jenkins. 
@wakaleo  if the issue is with our project, then the Scenario outline should displayed as NULL for the below combination of Serenity Jars:
Serenity Core Version: 1.8.1
Serenity Cucumber Version: 1.6.5
https://github.com/serenity-bdd/serenity-core/issues/1802

**Comment by totovelo10** [comment]
Thanks @hariharanravichandran you suggested an idea 
I had add in my maven command **-Dcucumber.options='--tags ~@ignore'** in order to skip "totally" the tests tagges as @ignore.
I delete this argument and the issue disappeared
ps: @wakaleo  is there a way to not display @ignore tests in the reports?

**Comment by MaheshDani** [comment]
@wakaleo I am using following versions 
        <serenity.version>2.2.2</serenity.version>
        <serenity-cucumber.version>2.2.2</serenity-cucumber.version>
        <cucumber-junit.version>5.6.0</cucumber-junit.version>
        <junit.version>4.12</junit.version>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber5</artifactId>
            <version>${serenity-cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber-junit.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java8</artifactId>
            <version>${cucumber-junit.version}</version>
        </dependency>

Running following Runner file 


package cts.parallel.runners;

import org.junit.runner.RunWith;
import io.cucumber.junit.CucumberOptions;
//import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        strict = false,
        features = {"classpath:features/ui/UISample.feature:22"},
        plugin = {"pretty"},
        monochrome = true,
        glue = {"uk.gov.ho.domain.component.ui.steps"}
)

public class TestSuiteSec001 {
}
 mvn clean -Ptests verify -Dit.test=TestSuiteSec001 -Dcontext=TestSuiteSec001 -DskipCheckstyle=true;
we are still seeing Example: null

![image](https://user-images.githubusercontent.com/64141903/83307799-5c909b00-a1fd-11ea-9978-48e9f52dd392.png)

**Comment by wakaleo** [comment]
Can you provide a sample project to reproduce the issue?

**Comment by MaheshDani** [comment]
sure.. let me prepare one sample project..

**Comment by ricardorlg-aval** [comment]
@MaheshDani just to know, are u using the examples in the scenario name?

**Comment by MaheshDani** [comment]
@ricardorlg-aval 
There is one feature file scenario where scenario outline description uses one of the column from example. and there is another feature file which doesn't. and we are seeing example as null in both the cases.

**Comment by ricardorlg-aval** [comment]
@MaheshDani just to see something, can u remove the column from example in the scenario description and run again

**Comment by MaheshDani** [comment]
@ricardorlg-aval  just tried that it did not resolve the problem. Still seeing Example: null

**Comment by MaheshDani** [comment]
@wakaleo created sample project here
https://github.com/MaheshDani/sample-serenity-project
hope that helps

**Comment by MaheshDani** [comment]
@wakaleo so example description value and table is populated properly when I run full feature file with multiple example like this 
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        tags = {""},
        plugin = {"pretty"},
        features = "classpath:features/ui/spamuitests.feature",
        glue = {"sample.project.domain.component.ui.steps"}
)
public class TestSuiteUi  {

}

but is not populated as soon as I specify :16 line number for scenario outline example like this below.

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        tags = {""},
        plugin = {"pretty"},
        features = "classpath:features/ui/spamuitests.feature:16",
        glue = {"sample.project.domain.component.ui.steps"}
)
public class TestSuiteUi  {

}

**Comment by wakaleo** [comment]
I don't think this is currently supported - thoughts @cliviu ?

**Comment by cliviu** [comment]
That's right, is not supported

**Comment by MaheshDani** [comment]
@wakaleo @cliviu the fact that it is allowing us to run individual scenario outline example by specifying line number means it is supporting it.. it's just not able to output in json file against example node.

**Comment by wakaleo** [comment]
@cliviu means that it is not supported by the Serenity reports.

**Comment by wakaleo** [comment]
@cliviu means that it is not supported by the Serenity reports.

**Comment by cliviu** [comment]
That's correct @wakaleo , is not supported by the Serenity reports.

**Comment by ricardorlg-aval** [comment]
By the way, I found something with the linefilters if I remove it the reports now display correctly, I report the issue in cucumber repo if u want to see it @wakaleo  or @cliviu

**Comment by wakaleo** [comment]
@ricardorlg-aval yes, please do.

**Comment by ricardorlg-aval** [comment]
@wakaleo I make the PR, https://github.com/serenity-bdd/serenity-cucumber5/pull/12 let me know what do u think.
