### ISSUE TITLE
class file for io.appium.java_client.FindsByIosUIAutomation not found

### ISSUE THREAD

**Issue by qaschevychelov** [serenity-bdd/serenity-core#1805]
Hi! I've moved to java-client 7.2.0 and get an erorr
![image](https://user-images.githubusercontent.com/44509715/64673969-4593f800-d478-11e9-850a-20a617337cfd.png)
My capabilities are
        DesiredCapabilities cap = new DesiredCapabilities();
        cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
        cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);
        cap.setCapability(MobileCapabilityType.UDID, udid);
        cap.setCapability(MobileCapabilityType.DEVICE_NAME, udid);
        cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.1");
        cap.setCapability(MobileCapabilityType.APP, System.getProperty("appium.app"));
        cap.setCapability(MobileCapabilityType.NO_RESET, "true");
        cap.setCapability(MobileCapabilityType.FULL_RESET, "false");
        cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "30000");

What did i do wrong?

**Comment by wakaleo** [comment]
Does it work with java-client 7.0.0?

**Comment by qaschevychelov** [comment]
It only work with java-client 6.1.0
i use the following versions:
serenity-core 1.9.20
serenity-cucumber 1.9.8
serenity-rest-assured 1.9.20

**Comment by wakaleo** [comment]
The version needs to be aligned with the version of serenity. For serenity-core 2.0.70 the supported java-client is 7.0.0

**Comment by qaschevychelov** [comment]
Yes, it works. But there is no Setting.ALLOW_INVISIBLE_ELEMENTS in java-client 7.0.0. 
I'm experimenting with Setting.ALLOW_INVISIBLE_ELEMENTS. What versions should i use in order to switch this settings?

**Comment by wakaleo** [comment]
You would have to check the Appium docs for that, they change the API quite a bit. If the option isn't there it may no longer be supported by Appium.

**Comment by qaschevychelov** [comment]
Thanks!
