### ISSUE TITLE
unable to run serenity -cucumber tests due to selenium error

### ISSUE THREAD

**Issue by nishh24** [serenity-bdd/serenity-core#1807]
getting the error 

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/thucydides/core/webdriver/capabilities/SaucelabsRemoteDriverCapabilities.getCapabilities(Lorg/openqa/selenium/remote/DesiredCapabilities;)Lorg/openqa/selenium/remote/DesiredCapabilities; @2: invokespecial
  Reason:
    Type 'org/openqa/selenium/remote/DesiredCapabilities' (current frame, stack[1]) is not assignable to 'org/openqa/selenium/MutableCapabilities'

**Comment by wakaleo** [comment]
The cucumber dependencies should be the ones defined in https://github.com/serenity-bdd/serenity-core/#what-is-the-latest-stable-version-i-should-use. However, this error looks more like a Selenium compatibility error - make sure you are using the Selenium versions defined in https://github.com/serenity-bdd/serenity-core/#what-is-the-latest-stable-version-i-should-use.

**Comment by wakaleo** [comment]
Closing, presume answered.
