### ISSUE TITLE
new HtmlAggregateStoryReporter() doesn't work on linux

### ISSUE THREAD

**Issue by talipkorkmaz** [serenity-bdd/serenity-core#1811]
Hi ,
I'm executing serenity:aggregate goal on windows machine and everything is ok.
But in ubuntu via vagrant, maven serenity plugin cant finish its job whatever it is waiting for.
I debugged the serenity-maven-plugin and find that 

**new HtmlAggregateStoryReporter(projectKey);** in **getReporter()** method line waits infinitely.

Any idea?

**Comment by wakaleo** [comment]
Maybe some sort of JVM configuration issue? The line in question does no processing, so it is hard to say.

**Comment by wakaleo** [comment]
I can confirm that in the general case the aggregate function does work correctly on Ubuntu; I haven't tried recently with Vagrant though.
