### ISSUE TITLE
Serenity 2.0.52: Integrated Test execution using maven-failsafe-plugin with AcceptanceTestSuite.java does not generate Context browser symbols in Serenity Reports

### ISSUE THREAD

**Issue by raghuram-venugopal** [serenity-bdd/serenity-core#1813]
Steps to reproduce:
1. Create an AcceptanceTestSuite.java(Multiple files for multithreaded execution) which extends Serenity Stories with below statement.
**SerenitySystemProperties.getProperties().setValue(ThucydidesSystemProperty.CONTEXT, "Edge");**
2. Run test using maven commands without -Dcontext as this is already mentioned programatically in step 1

Expected:
Serenity reports should display scenarios with browser symbols.

Actual:
Even though multiple browsers are opened and executed respectively, reports does not display different browser icons.

**NOTE:** When running the suite using Junit runner we are able to get reports with browser symbols but this happens only with Maven goals execution only. Sample Maven command to execute is as below.
mvn verify -Dmetafilter="RegressionSuite"  -Dwebdriver.base.url="https;//www.walmart.com"

**Comment by mesthaharishs** [comment]
Hello,

I'm facing same issue, serenity generated reports are not displaying browser symbols.
Please check and provide a quick fix to it or let me know the other options?

**Comment by wakaleo** [comment]
System properties are immutable, you can’t modify them on the fly in this way

**Comment by DragonGowda** [comment]
@wakaleo , Thanks for the confirmation. Please could you suggest if there is any other workaround for displaying different browser symbols in reports for multi threaded execution ?
