### ISSUE TITLE
Matcher being called twice in serenity screenplay

### ISSUE THREAD

**Issue by ngocvo3103** [serenity-bdd/serenity-core#1815]
Hi guys,

While doing some research to apply the screenplay pattern in my team, I found the matcher is being called twice. this poses performance risk in our automation test execution. Could you guys please have a look at it?

Detailed as below:

1. I'm extending TypeSafeDiagnosingMatcher to do the validations, haven't tried other matchers, but I have a feeling that they'll all have the same issue.
2. Matcher is being called twice:
  2.1. The first time this matcher is called, the hamcrest.Description was initialized as org.hamcrest.Description$NullDescription
  2.2. The second time this matcher is called, the hamcrest.Description was initialized as org.hamcrest.StringDescription
3. Serenity version: 2.0.71

Full code: [BugReproduceTest.java.zip](https://github.com/serenity-bdd/serenity-core/files/3619904/BugReproduceTest.java.zip)

Console output:
<img width="758" alt="Screen Shot 2019-09-17 at 2 49 51 PM" src="https://user-images.githubusercontent.com/31998023/65022038-72557d00-d95a-11e9-97b9-aafcbdd64008.png">

**Comment by wakaleo** [comment]
This is not related to Serenity or Screenplay. It is due to the Hamcrest  implementation  of the TypeSafeDiagnosingMatcher class, which calls the matchesSafely() method twice: once in the assertThat() method, then a second time in the describeMismatch() method, as can be seen in the implementation of the assertThat() method:
```
    public static <T> void assertThat(String reason, T actual, Matcher<? super T> matcher) {
        if (!matcher.matches(actual)) {
            Description description = new StringDescription();
            description.appendText(reason)
                       .appendText("\nExpected: ")
                       .appendDescriptionOf(matcher)
                       .appendText("\n     but: ");
            matcher.describeMismatch(actual, description);
            
            throw new AssertionError(description.toString());
        }
    }
```
and
```
    public final void describeMismatch(Object item, Description mismatchDescription) {
      if (item == null || !expectedType.isInstance(item)) {
        super.describeMismatch(item, mismatchDescription);
      } else {
        matchesSafely((T) item, mismatchDescription);
      }
    }
```

You don't get this behaviour if you extend the `BaseMatcher` class instead of the `TypeSafeDiagnosingMatcher` class.

**Comment by ngocvo3103** [comment]
Got it! Thank you for your swift response.
