### ISSUE TITLE
Mouse hover is not working on headless browser

### ISSUE THREAD

**Issue by jagdev041215** [serenity-bdd/serenity-core#1816]
1.Mouse hover is not working in headless browser , give element not found exception.

2. Does Sikuli works on headless browser?

**Comment by wakaleo** [comment]
This sounds like a WebDriver issue, not a Serenity one. Do you have a reason to think this is due to something in the Serenity code?

**Comment by jagdev041215** [comment]
okay , i found the reason we have set the dimension 
chrome.switches=--headless
serenity.browser.width=1400
serenity.browser.height=800
and due to this dimension set ,element was not visible on page.

**Comment by jagdev041215** [comment]
Does sikuli works on headless??

**Comment by wakaleo** [comment]
You should probably ask the sikuli community.

**Comment by wakaleo** [comment]
Closing, presume answered
