### ISSUE TITLE
Requirements are not automatically mapped in reports using version 2.0.56 onwards with cucumber 4.

### ISSUE THREAD

**Issue by kreigy1310garg** [serenity-bdd/serenity-core#1817]
Hi Team,
I am using serenity bdd with cucumber 4 for testing microservices.

My directory structure is src/test/resources/features then one.feature,second.feature.

When I use serenity 2.0.48 and serenity-cucumber4 1.0.12 then my requirements are automatically mapped with features but no support of @manual-last-tested , then I migrated to 2.0.67 with serenity-cucumber4 1.0.21  because this is supported after 2.0.56. 

Now my requirements overview is coming as blank. 

I also tried with 2.0.56 with 1.0.12 but still it is blank.

I tried to use serenity properties for requirements.dir,requirements.basedir but still my requirement overview is blank.

My build.gradle

/*
 * This build file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.3/userguide/java_library_plugin.html
 */

// Apply the java-library plugin to add support for Java Library

group 'sdc-service-test'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:${SerenityCoreVersion}")
    }
}

apply plugin: 'java'
apply plugin: 'net.serenity-bdd.aggregator'

configurations.all {
    resolutionStrategy {
        force "io.cucumber:cucumber-core:${cucumberVersion}"
    }
    
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile "net.serenity-bdd:serenity-rest-assured:${SerenityCoreVersion}"
    compile "net.serenity-bdd:serenity-cucumber4:${SerenityCucumberVersion}"
    compile "org.assertj:assertj-core:${assertJVersion}"
   compile "ch.qos.logback:logback-classic:${logVersion}"
    compile "net.serenity-bdd:serenity-core:${SerenityCoreVersion}"
    compile "com.googlecode.json-simple:json-simple:${gsonVersion}"
    compile "org.skyscreamer:jsonassert:${jsonAssertVersion}"
    compile  "mysql:mysql-connector-java:${mysqlVerison}"
    compile "io.cucumber:cucumber-junit:${cucumberVersion}"
     compile "io.cucumber:cucumber-core:${cucumberVersion}"
     compile "org.json:json:${jsonVersion}"

}

test {
    testLogging.showStandardStreams = true
}
gradle.startParameter.continueOnFailure = false

test.finalizedBy(aggregate)

gradle.properties

SerenityCoreVersion = 2.0.67
SerenityScreenPlayCoreVersion = 2.0.67
SerenityCucumberVersion = 1.0.21
junitVersion=4.12
assertJVersion=3.12.2
slf4jVersion=1.7.7
gsonVersion=1.1
jsonAssertVersion = 1.5.0
mysqlVerison = 8.0.11
logVersion = 0.9.26
cucumberVersion=4.2.0
jsonVersion = 20180813

![2 0 67_requirements](https://user-images.githubusercontent.com/49478697/65151525-e61f8480-da43-11e9-8387-d5b4a208786f.jpg)
![2 0 48_requirements](https://user-images.githubusercontent.com/49478697/65151526-e6b81b00-da43-11e9-95c2-07cd2627791b.jpg)

I attached screenshots for both version reports. I didn't do any change in structure only upgraded the version.

**Comment by wakaleo** [comment]
I can't reproduce this; can you provide a sample project?

**Comment by zzoubian** [comment]
> I can't reproduce this; can you provide a sample project?

This issue was reproducible using the serenity-cucumber4-starter project:
https://github.com/serenity-bdd/serenity-cucumber4-starter

The issue occurs in versions after 2.0.48.  I was using Java 1.8, and tried different versions of Gradle: 3.4, 4.2, 5.6.

2.0.48:
![2019-10-03 09_48_19-Requirements_2 0 48](https://user-images.githubusercontent.com/35345489/66134858-01070280-e5c7-11e9-882e-6e2a6265aa0f.png)

2.0.49:
![2019-10-03 09_48_19-Requirements_2 0 49](https://user-images.githubusercontent.com/35345489/66134875-095f3d80-e5c7-11e9-9cde-2aca06feec0a.png)

2.0.56:
![2019-10-03 09_48_19-Requirements_2 0 56](https://user-images.githubusercontent.com/35345489/66134885-0e23f180-e5c7-11e9-95b1-17659449e0a6.png)

2.0.70:
![2019-10-03 09_48_19-Requirements_2 0 70](https://user-images.githubusercontent.com/35345489/66134908-154aff80-e5c7-11e9-8749-e3f310c4c214.png)

**Comment by wakaleo** [comment]
Still can't reproduce this with Gradle or Maven. and haven't come across it on Windows, Linux or MacOS. 

![](https://user-images.githubusercontent.com/35345489/66134858-01070280-e5c7-11e9-882e-6e2a6265aa0f.png)

**Comment by zzoubian** [comment]
> Still can't reproduce this with Gradle or Maven. and haven't come across it on Windows, Linux or MacOS.
> 
> ![](https://user-images.githubusercontent.com/35345489/66134858-01070280-e5c7-11e9-882e-6e2a6265aa0f.png)

It stops working in 2.0.49+.  It works with 2.0.48.  Are you able to reproduce using 2.0.49?

**Comment by wakaleo** [comment]
No, I can't reproduce this issue for 2.0.49 either.

**Comment by kreigy1310garg** [comment]
Thanks wakaleo for your efforts. I tried everything to find the root cause but still facing the same issue. I don't know why you are not able to reproduce the same. I am able to reproduce it with the starter project as well. But I don't know it is happening.

**Comment by kreigy1310garg** [comment]
@wakaleo could you please try using serenity rest assured instead of serenity core ?

**Comment by wakaleo** [comment]
I have lots of projects using serenity-rest-assured; I don't see this behaviour with them either.

**Comment by kreigy1310garg** [comment]
@wakaleo could you please share any standard grade having serenity rest assured with cucumber4 so that I would be able to find out the root cause.

**Comment by kreigy1310garg** [comment]
@wakaleo Invited you in my project SDC as collaborator. Please look into the project and check why requirements are not mapped as structure and everything is fine.


Please don't share the repo further ... Thanks for your efforts.

**Comment by zzoubian** [comment]
I did a little bit more digging around, and it appears it only affects Windows machines.  On our Mac it worked fine.

It appears the default requirements directory is set to "src/test.features" in FileSystemRequirementsTagProvider,  Inside the method 
 FileSystemRequirementsTagProvider.capabilitiesAndStoriesIn(), the call rootDirectory.exists() returns null on Windows.

When we override this value with the system property, "serenity.requirements.dir" to src/test/resources/features in serenity.properties.  The requirements get created, and the report generates properly.

**Comment by kreigy1310garg** [comment]
@zzoubian  could you please let me know with which version you are able to override the properties as I am unable to override the same using serenity.requirements.dir=src/test/resources/features in serenity properties with serenity 2.0.67 and higher version on windows. Could you please tell me with which version you are able to override the path.

**Comment by eventsequor** [comment]
Greetings
You can see that when running only a test scenario, for example with the command
mvn clean verify -Dtags = "@ annotation", 
no information is generated in the requirements overview. It is only generated when the whole package where the runners are defined is run

**Comment by gurgl** [comment]
This needs to be fixed

**Comment by wakaleo** [comment]
> This needs to be fixed

What needs to be fixed? If you want to filter by tags, you can use the standard Cucumber options, e.g.
```
mvn clean verify -Dcucumber.filter.tags="@mytag"
```
