### ISSUE TITLE
Ensure not reporting question subject for boolean assert

### ISSUE THREAD

**Issue by ssmuthukumaran** [serenity-bdd/serenity-core#1818]
Using serenity ensure module for asserting, passing in a question in 
Ensure.that(Question that returns boolean).isEqualto(true)
report prints result like 
![image](https://user-images.githubusercontent.com/26349289/65212647-268c0a80-daf7-11e9-9842-90aa109efff9.png)
it will be good if we could print subject of the question we are passing in.
For questions returning boolean values, subject of question is not printed in report.

**Comment by wakaleo** [comment]
This will be fixed in 2.0.72
