### ISSUE TITLE
@AndroidFindBy and @iOSXCUITFindBy no longer working in Serenity version 2.*.*

### ISSUE THREAD

**Issue by Jaskaran-Kalsi** [serenity-bdd/serenity-core#1820]
Getting Errors while using serenity with appium.
Both @AndroidFindBy and @iOSXCUITFindBy are not working as expected while using PageObject.
@FindBy works perfectly.
This feature should have worked directly out of the box.
Had to define BasePage class to get a work around by using PageFactory.initElements. and had to use WebElement insead of WebElementFacade. Which results in not being able to use functions defined with WebElementFacade. Which will make maintains of scripts really more complex.
WebElementFacade has so many features and being not able to use them.

public BasePage(final WebDriver driver) {
        super(driver, page -> {
            PageFactory.initElements(new AppiumFieldDecorator( ((WebDriverFacade) page.getDriver()).getProxiedDriver(), page.getImplicitWaitTimeout()), page);
            return true;
        });
    }

defining page class as
public class SelectRegionPage extends BasePage {

    @AndroidFindBy(id = "idOfTheElement")
    @iOSXCUITFindBy (id = "idOfTheElement")
    @FindBy(id = "idOfTheElement")
    private WebElement regionSelectionTitle;

    public SelectRegionPage(WebDriver driver) {
        super(driver);
    }
}

Not able to use PageObject directly like
public class SelectRegionPage extends PageObject {

    @AndroidFindBy(id = "idOfTheElement")
    @iOSXCUITFindBy (id = "idOfTheElement")
    @FindBy(id = "idOfTheElement")
    private WebElementFacade regionSelectionTitle;
}

when used like this only @FindBy works. other elements @AndroidFindBy and @iOSXCUITFindBy  don't sent there id value to appium, instead they send elements name i,e. id=regionSelectionTitle for finding the element.
Ends up failing.
Can this be fixed or is there some settings i am missing.
Really want use WebElementFacade instead of WebElemet.

Using Cucumber for features.
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features="src/test/resources/features", glue = "com.corusent.steps")
public class SignInTestSuite {
    @Managed(uniqueSession = true)
    public AppiumDriver<MobileElement> driver;
}
Appium error log
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/ffe236fe-2499-4890-8b3a-5e9a4aef9b6c/element] with body: {"strategy":"id","selector":"regionSelectionTitle","context":"","multiple":false}
[WD Proxy] Got an unexpected response: {"sessionId":"ffe236fe-2499-4890-8b3a-5e9a4aef9b6c","status":7,"value":"An element could not be located on the page using the given search parameters."}
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
Thanks alot

**Comment by wakaleo** [comment]
This is working as expected: these classes were removed from Appium in java-client version 7.2.0, (which is used in Serenity 2.0.71 onwards), and are therefore no longer supported in Serenity. To use the latest version of Appium I imagine you will need to update the code to use whatever Appium suggests as a replacement. Otherwise you will need to use Serenity version 2.0.69 (see https://github.com/serenity-bdd/serenity-core/blob/master/README.md#serenity-with-junit). 

Note that the AndroidFindBy has not changed in Serenity so this should still work unless there is an issue with the appium libraries.

If you think this is due to something in the Serenity code, please feel free to dig in and submit a pull request - the Appium logic in Serenity is entirely community-driven.

**Comment by Jaskaran-Kalsi** [comment]
Thank for quick response,
I did tryed older version even 2.0.69. same behavior.
will try it with an older version of appium.
This was my initail thought that i should not have to define base class just to use PageFactory.initElements(). this should be handled by PageObject if required. as running test on appium is part of serenity and no extra settings should be required.

**Comment by wakaleo** [comment]
As I said, Appium support in Serenity has always been community-driven, so PRs are welcome.
