### ISSUE TITLE
Serenity 2.0.71 - It is not possible to pass list in serenity.properties for chrome_experimental_options

### ISSUE THREAD

**Issue by jacquecosta** [serenity-bdd/serenity-core#1821]
Inform a value of a list in serenity.properties, the property is not beign identified by serenity.

Example of property:
```
chrome_experimental_options.excludeSwitches=[enable-automation]
chrome_experimental_options.useAutomationExtension=false
```

Error returned:

`Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (invalid argument: entry 0 of 'firstMatch' is invalid from invalid argument: cannot parse capability: goog:chromeOptions from invalid argument: cannot parse excludeSwitches from invalid argument: must be a list`

**Comment by wakaleo** [comment]
I still can't reproduce this in 2.0.71. Can you provide a sample project?

**Comment by jacquecosta** [comment]
I created a new project to test it, but, this one can only shows the message of "chrome is being controlled by automated software" still appear when chromeDriver starts.

I will take a look in my actual project to identify why I am still getting `invalid argument: must be a list`, by the way configuring the property on serenity.properties seems to not work.

[serenitytestbug.zip](https://github.com/serenity-bdd/serenity-core/files/3632271/serenitytestbug.zip)

**Comment by wakaleo** [comment]
Can you post the code that works with a custom driver?

**Comment by jacquecosta** [comment]
```
options.setExperimentalOption("excludeSwitches", Arrays.asList("enable-automation"));
options.setExperimentalOption("useAutomationExtension", false);
```

**Comment by wakaleo** [comment]
Try adding the following:
```
use.chrome.automation.options = false
```

**Comment by jacquecosta** [comment]
Using this properties:

```
#chrome_experimental_options.excludeSwitches=[enable-automation]
chrome_experimental_options.useAutomationExtension=false
chrome.switches=--enable-automation --safebrowsing-disable-download-protection --disable-infobars --auto-ssl-client-auth --allow-running-insecure-content --allow-unchecked-dangerous-downloads  --safebrowsing-disable-extension-blacklist --disable-extensions --disable-popup-blocking --lang=pt-BR
use.chrome.automation.options=false
```

Still getting the same result.

**Comment by wakaleo** [comment]
Here is what I have found to work:

In the properties file:
```
use.chrome.automation.options = false
chrome_experimental_options.excludeSwitches=[enable-automation]
```

In serenity.conf:
```
use.chrome.automation.options = false
chrome_experimental_options {
    excludeSwitches="[enable-automation]"
    useAutomationExtension=false
}
```

**Comment by jacquecosta** [comment]
Well,

I don't know why, but, for me still appearing the message of running by automated test.

I tried with:
```
use.chrome.automation.options = false
chrome_experimental_options.excludeSwitches=[enable-automation]
chrome_experimental_options.useAutomationExtension=false
chrome.switches=--enable-automation --safebrowsing-disable-download-protection --disable-infobars --auto-ssl-client-auth --allow-running-insecure-content --allow-unchecked-dangerous-downloads  --safebrowsing-disable-extension-blacklist --disable-extensions --disable-popup-blocking --lang=pt-BR
```

```
use.chrome.automation.options=false
chrome_experimental_options.excludeSwitches=[enable-automation]
chrome.switches=--enable-automation --safebrowsing-disable-download-protection --disable-infobars --auto-ssl-client-auth --allow-running-insecure-content --allow-unchecked-dangerous-downloads  --safebrowsing-disable-extension-blacklist --disable-extensions --disable-popup-blocking --lang=pt-BR
```


I am using [ChromeDriver v77](https://chromedriver.storage.googleapis.com/index.html?path=77.0.3865.40/)

**Comment by AlexChernookov** [comment]
@jacquecosta there is a new serenity version 2.0.73 was released several days ago and looks like the issue was fixed.
Can you try to reproduce it with these params:  
chrome_experimental_options.useAutomationExtension=false
chrome_experimental_options.excludeSwitches=[enable-automation]

**Comment by sparmboy** [comment]
The issue with the properties file being like this 

`use.chrome.automation.options = false
chrome_experimental_options.excludeSwitches=[enable-automation]`

is that it expects the `excludeSwitches` property to be a list, but it isn't parsed as one.

I will raise a pull request if thats helpful?

**Comment by sparmboy** [comment]
Have rased [PR1862](https://github.com/serenity-bdd/serenity-core/pull/1862)

**Comment by MohammedWaasim** [comment]
Hi @wakaleo , @sparmboy I tried with the suggested serenity properties changes, in the above thread and still see the Chrome Bar at the top of the browser launched. please let me know if there is any update on this issue. I would be happy to incorporate it in my framework

**Comment by Shubham-Saxena63** [comment]
Hi @MohammedWaasim, you can try with chrome_experimental_options.excludeSwitches=enable-automation (without square brackets). It should work. Just make sure your chrome driver is updated one.

**Comment by MohammedWaasim** [comment]
> Hi @MohammedWaasim, you can try with chrome_experimental_options.excludeSwitches=enable-automation (without square brackets). It should work. Just make sure your chrome driver is updated one.

Yes this works :), thanks a lot
