### ISSUE TITLE
Reporting manual scenario outline result is wrong

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#1822]
**Environment**
Serenity-core 2.0.70
serenity-cucumber4 1.0.21
Java 11
windows 10

**Summary**
Scenario outline, tagged with manual result, not reported correctly in HTML report - some examples stay manual instead of passed/failed

**Feature file example**
```
Feature: testing manual outline result

  @manual:failed
  Scenario Outline: Test login under different permissions

    Given logged as <user>
    Then get a result <expected>

    Examples:
      | user  | expected      |
      | admin | Logged in     |
      | user  | Logged in     |
      | guest | Access denied |
```

**Expected result**
Running only given feature, expect to have 100% failed tests in pie chart on main page.

**Actual result**
![index](https://user-images.githubusercontent.com/6312221/65325126-afb64680-dbb6-11e9-9499-b48e0695175c.png)

**Comment by wakaleo** [comment]
could you take a look and propose a PR?

**Comment by scormaq** [comment]
Do you have any ideas where to look for root of issue (projects/classes)?

I don't have spare time right now, might took it next month.

**Comment by wakaleo** [comment]
Have you tried with:
```
@manual
@manual-result:failed
```
?
(see https://serenity-bdd.github.io/theserenitybook/latest/manual-tests.html)

**Comment by scormaq** [comment]
>Have you tried with:
>
>@manual
>@manual-result:failed
Same effect with these tags, still reproduced.
BTW results from `@manual:failed` tags is fetched somehow, as you can see from **Tags** section. And it works as intended with regular (non-outline) scenarios.

**Comment by wakaleo** [comment]
Maybe start looking in the `TaggedScenario` class in the serenity-cucumber4 (and serenity-cucumber) project.

**Comment by wakaleo** [comment]
Are you trying to run the tests in parallel?

**Comment by scormaq** [comment]
@wakaleo no. Here is sample project (1 feature file containing 1 scenario outline; built with gradle 5 and java 11): [sample.zip](https://github.com/serenity-bdd/serenity-core/files/3696702/sample.zip)

Invoke `gradle test aggregate` and check report generated.

**Comment by SandeepDarsan** [comment]
Hi @scormaq ,

Is this working for you? Manual tagged scenario outlines are always displayed as passed in the pie chart for me.

**Comment by scormaq** [comment]
Hi @SandeepDarsan,
as I can see, this issue was fixed in latest versions, here what I used:
```
        serenity_version = '2.1.4'
        serenity_cucumber4_version = '2.1.2'
        cucumber_version = '4.8.0'
```
Running feature file from example in my original post now reports as next:
![image](https://user-images.githubusercontent.com/6312221/74248008-9fcb0a80-4cef-11ea-885b-7a0443fd1830.png)

Make sure you using latest versions
