### ISSUE TITLE
Email-able reports are not matching with Index.html

### ISSUE THREAD

**Issue by swetha890** [serenity-bdd/serenity-core#1823]
Hello wakaleo,
i am using following versions for serenity in my current project and implemented additional html reports with plugin serenity-emailer. However the generated serenity-summary.html is not matching with index.html ? could this be version issue!!? if not what could be the possible solution to fix this!
<serenity.version>1.9.45</serenity.version>
		<serenity.maven.version>1.9.45</serenity.maven.version>
		<serenity.cucumber.version>1.9.12</serenity.cucumber.version>	

Thanks in advance,
:)

**Comment by wakaleo** [comment]
See https://github.com/serenity-bdd/serenity-core/#what-is-the-latest-stable-version-i-should-use for recommended versions. What do you mean by "is not matching with index.html"? (see also https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html)

**Comment by swetha890** [comment]
Not matching i am referring to was 
for example For one Test ABC my index.html showing 82% pass however for the same Test email report shows 76% as pass... it seems to qualify the failures differently between reports.

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces the issue?

**Comment by swetha890** [comment]
![image](https://user-images.githubusercontent.com/54693884/65475604-ffa24100-de34-11e9-9672-034f75330988.png)

![image](https://user-images.githubusercontent.com/54693884/65475616-07fa7c00-de35-11e9-9c25-f900dea846cb.png)

**Comment by swetha890** [comment]
![image](https://user-images.githubusercontent.com/54693884/65475657-2b252b80-de35-11e9-915e-a8997511151a.png)
![image](https://user-images.githubusercontent.com/54693884/65475665-2fe9df80-de35-11e9-8da9-aa4aae887416.png)

**Comment by wakaleo** [comment]
Have you tried with a more recent version of Serenity?

**Comment by swetha890** [comment]
Trying it now...

**Comment by swetha890** [comment]
I tried  following versions..
<serenity.version>2.0.48</serenity.version>
		<serenity.maven.version>2.0.48</serenity.maven.version>
		<serenity.cucumber.version>1.9.37</serenity.cucumber.version>
The index.htm is now  matching with emailable reports however i can see 6 folders created in c/project/reports folder. Is there a way to handle this ? because this takes lot of space and could lean to performance issues in long term. 
Thanks in advance,
swetha.

**Comment by swetha890** [comment]
![image](https://user-images.githubusercontent.com/54693884/65477687-eea8fe00-de3b-11e9-9adf-e399e2511c80.png)

i would expected only single folder first one. with unique name.

**Comment by scormaq** [comment]
@swetha890 what are these folders, how exactly do you get them created? It looks like output of your own project, not from serenity...

**Comment by wakaleo** [comment]
I don't think this is a Serenity issue - more related to your project build script or CI job. Feel free to reopen if this is not the case.
