### ISSUE TITLE
How to read csv file value row wise for each different test.

### ISSUE THREAD

**Issue by AmanKan** [serenity-bdd/serenity-core#1825]
Hi,

I am working on serenity rest framework where I have to pass data to different test. I am using csv file , and using SerenityParameterizedRunner.class to get the data. But the problem is- single test is running on all data from csv . I want to have each row data to be provided to each different test.
How can I do it. Please help

**Comment by wakaleo** [comment]
That’s not how the JUnit 4 parameterized tests work; maybe use soft asserts?

Since this is a question not a defect, https://serenity-bdd.rocket.chat would be a better forum.
