### ISSUE TITLE
Documentation for current tasks, actions and abilities

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1826]
Hello,

When we have new hires in our team, the most common question is if there is a place where they can grab a list of the available tasks and actions that Serenity provides by default? It's a situation where they don't know what is available for them to use.
Thanks!

**Comment by wakaleo** [comment]
The most up-to-date docs are on https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html.
