### ISSUE TITLE
file rename issue in serenity 2.0

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1827]
Unable to rename the file names in report in serenity 2.0 with below configuration .

serenity.compress.screenshots=false

**Comment by wakaleo** [comment]
What problem are you trying to solve?

**Comment by JeffGaly** [comment]
I wish to rename the file names in report folder with proper scenario or
feature names.

**Comment by wakaleo** [comment]
This isn't supported, and would be hard to do. Screenshot filenames are hashes of the screenshot contents, so changing their names would break a lot of things.

**Comment by JeffGaly** [comment]
Ok john . Thanks .
