### ISSUE TITLE
Multiple places of configuration of destination for serenity reports produce issues

### ISSUE THREAD

**Issue by YamStranger** [serenity-bdd/serenity-core#183]
Problem:
  Now we have some amount of places to configure serenity properties, they are used in priority (some overrides others) - "final output directory"(serenity-core module). This issue about outputDirectory property - destination of generating aggregation reports in gradle,mnv,ant. We already have several issues (#130, #63, serenity-bdd/serenity-maven-plugin#11) and they have same root cause. 
  In current Serenity version during  executing tests all reports stored directly into "final output directory". After that aggregation task executed to aggregate reports from outputDirectory. In some cases this "final output dirrectory" can be different from outputDirectory - because this configuration in plugins loaded only from systemProperties or serenity.properties file. As result, if this directories are different - we will face an error during aggregation. 
  We have code to load all this properties in same way in serenity-core, but  it is hard reuse it in plugins, because of adding additional dependencies for executing these plugins.  

Solution:
It seems that we can make generating all reports in default directory (targe/serenity/site) during executing tests, and running aggregation task there too. Make "moving" reports to outputDirrectory part of aggregation task, as result - it can be simply implemented in all plugins without any additional dependencies. Also update sources of outputDirrectory property - only  in serenety.properties and system variable - by tag "serenity.output.directory".

**Comment by YamStranger** [comment]
Lets make this using some properties file in reports with target output dir. During tests such file created, and in mvn,ant,gradle - this property file is readed, and move target directory to another place

**Comment by olharuban** [comment]
When this bug is expected to be fixed?

**Comment by YamStranger** [comment]
Hello @olharuban. 

For now we have fix only for gradle (#130 issue). 

Other will be fixed soon, this issue first in queue )

**Comment by olharuban** [comment]
Does this update fix this bug [Aggregate report problems in multimodule Maven build] (https://github.com/serenity-bdd/serenity-maven-plugin/issues/11)?

**Comment by YamStranger** [comment]
Hello @olharuban 
no, it does not fix it.

**Comment by olharuban** [comment]
Looking forward for new fix

Thank you!

**Comment by johndeverall** [comment]
I had something similar in our project which is a multi module maven project where output was appearing in two locations as *I think* is described here. I am currently using a **work around** so I thought I should share it and perhaps help some people.

I specify **two serenity.properties files**. In the folder containing my parent pom, I specify a serenity.properties file like so: 

`serenity.outputDirectory=acceptance_report`

In the module with my serenity tests, I also specify a serenity.properties file, but specifying the parent folder

`serenity.outputDirectory=../acceptance_report`

All my output appears under the root folder in the `acceptance_report` folder. I'm using `1.1.22-rc.11`.

**Comment by YamStranger** [comment]
This issue closed and checked against demo projects

**Comment by WorldofAzeem** [comment]
when we run test second time results in report directory is getting overridden, is there a built in way to avoid overwriting the results? 
.\gradlew.bat test aggregate

**Comment by wakaleo** [comment]
Not really; that's not the way test results work.
