### ISSUE TITLE
cannot access org.openqa.selenium.interactions.Locatable

### ISSUE THREAD

**Issue by kishor32** [serenity-bdd/serenity-core#1830]
<serenity-core.version>2.0.70</serenity-core.version>
<serenity-jbehave.version>1.46.0</serenity-jbehave.version>
<serenity-junit.version>2.0.70</serenity-junit.version>

Getting error :
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project:  Compilation failure
 cannot access org.openqa.selenium.interactions.Locatable while running tests . 
Looks like serenity -core dependency issue

**Comment by wakaleo** [comment]
That could be a selenium version conflict - try doing a dependency analysis on your pom file.

**Comment by kishor32** [comment]
@wakaleo I ma not using any selenium dependency explicitly . Serenity should pull the latest I believe.

**Comment by wakaleo** [comment]
You should do a dependency analysis to see what conflicts you are getting

**Comment by kishor32** [comment]
@wakaleo   org.seleniumhq.selenium:selenium-api:jar:3.8.0:  and org.seleniumhq.selenium:selenium-java:jar:3.9.1: this two I can see after dependency analysis .

**Comment by wakaleo** [comment]
You need to organise your dependencies to make sure they are using the selenium version compatible with Serenity (3.14.159)

**Comment by kishor32** [comment]
@wakaleo  is Selenium 3.14.159  compatible with  Serenity 2.0.70 ?

**Comment by wakaleo** [comment]
https://github.com/serenity-bdd/serenity-core/blob/master/README.md#what-is-the-latest-stable-version-i-should-use

**Comment by kishor32** [comment]
@wakaleo   Hi , after updating  dependencies based on the above read me , I got below error :

java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.<init>(Ljava/lang/Object;Ljava/time/Clock;Lorg/openqa/selenium/support/ui/Sleeper;)V)

**Comment by wakaleo** [comment]
These are project-related dependency conflicts - that one looks like you (or one of your libraries) is still pulling in an incorrect version of Selenium.

**Comment by kishor32** [comment]
yes. got it . need to explicitly defined all selenium  dependencies to latest. Also need to clean up .m2 . 

Thanks @wakaleo  for your time . Really appreciate .

**Comment by wakaleo** [comment]
Good to hear. Can you close this issue if the problem has been resolved?
