### ISSUE TITLE
Cannot pass Appium properties to Sauce Labs since 2.0.74

### ISSUE THREAD

**Issue by justinhinze** [serenity-bdd/serenity-core#1831]
Passing Appium properties to Sauce Labs at runtime like `-Dappium.commandTimeout=180`, `-Dappium.deviceOrientation=portrait`, `-Dappium.build="Build Name"`, etc. does not work as of version 2.0.74. Appears to be related to https://github.com/serenity-bdd/serenity-core/pull/1824 .

> 10:42:44.719 [main] WARN  n.t.c.w.appium.AppiumConfiguration - build capability is not discovered in the list of supported by w3c or Appium. If it is required then it should be listed in {@link ThucydidesSystemProperty#APPIUM_ADDITIONAL_CAPABILITIES}
10:42:44.719 [main] WARN  n.t.c.w.appium.AppiumConfiguration - commandTimeout capability is not discovered in the list of supported by w3c or Appium. If it is required then it should be listed in {@link ThucydidesSystemProperty#APPIUM_ADDITIONAL_CAPABILITIES}
10:42:44.719 [main] WARN  n.t.c.w.appium.AppiumConfiguration - deviceOrientation capability is not discovered in the list of supported by w3c or Appium. If it is required then it should be listed in {@link ThucydidesSystemProperty#APPIUM_ADDITIONAL_CAPABILITIES}
10:42:44.719 [main] WARN  n.t.c.w.appium.AppiumConfiguration - loggingPrefs capability is not discovered in the list of supported by w3c or Appium. If it is required then it should be listed in {@link ThucydidesSystemProperty#APPIUM_ADDITIONAL_CAPABILITIES}
10:42:44.720 [main] WARN  n.t.c.w.appium.AppiumConfiguration - name capability is not discovered in the list of supported by w3c or Appium. If it is required then it should be listed in {@link ThucydidesSystemProperty#APPIUM_ADDITIONAL_CAPABILITIES}

**Comment by wakaleo** [comment]
Maybe ask @a-en? Appium support is community-driven as I have no way of testing the Appium integration.

**Comment by a-en** [comment]
@justinhinze, could you try to put appium.additional.caps? (like `appium.additional.caps=commandTimeout, deviceOrientation, build`)

**Comment by justinhinze** [comment]
Hey @a-en - same errors plus 

> 11:17:47.349 [main] WARN  n.t.c.w.appium.AppiumConfiguration - additional.capabilities capability is not discovered in the list of supported by w3c or Appium. If it is required then it should be listed in {@link ThucydidesSystemProperty#APPIUM_ADDITIONAL_CAPABILITIES}

**Comment by a-en** [comment]
@justinhinze , not `capabilities`, just `caps` (`appium.additional.caps`)

**Comment by justinhinze** [comment]
@a-en - Still seeing a warning but it _appears_ to be accepting my capabilities

> 11:23:17.976 [main] WARN  n.t.c.w.appium.AppiumConfiguration - additional.caps capability is not discovered in the list of supported by w3c or Appium. If it is required then it should be listed in {@link ThucydidesSystemProperty#APPIUM_ADDITIONAL_CAPABILITIES}
11:23:17.976 [main] INFO  n.t.c.w.appium.AppiumConfiguration - appium: prefix added to capability build
11:23:17.976 [main] INFO  n.t.c.w.appium.AppiumConfiguration - appium: prefix added to capability commandTimeout
11:23:17.976 [main] INFO  n.t.c.w.appium.AppiumConfiguration - appium: prefix added to capability deviceOrientation
11:23:17.976 [main] INFO  n.t.c.w.appium.AppiumConfiguration - appium: prefix added to capability loggingPrefs
11:23:17.976 [main] INFO  n.t.c.w.appium.AppiumConfiguration - appium: prefix added to capability name
11:23:17.976 [main] INFO  n.t.c.w.appium.AppiumConfiguration - appium: prefix added to capability url

However, when they get to Sauce Labs they are in the desiredCapabilities as _appium:[property]_ instead of just _[property]_ so it doesn't understand them.

`{
  "desiredCapabilities": {
    "deviceName": "iPhone XS",
    "appium:build": "build-test12",
    "url": "",
    "automationName": "XCUITest",
    "noReset": "false",
    "appium:loggingPrefs": {},
    "appium:commandTimeout": "360",
    "appium:name": "Login as new user",
    "appium:deviceOrientation": "portrait",
    "newCommandTimeout": "4000",
    "platformVersion": "12.2",
    "fullReset": "true",
    "platformName": "iOS"
  }
}`

**Comment by a-en** [comment]
@justinhinze, couple of things to mention:
- are you sure about names of capabilities you are trying to pass? I mean, you have `deviceOrientation` but according to [official list](http://appium.io/docs/en/writing-running-appium/caps/), it should be `orientation`
- some of those which you are referring to (`build`, `commandTimeout` (should it be `commandTimeoutS`?), `name`) seems to be specific of SauceLab's desired caps, so you could provide them without appium prefix (`-Dbuild=build-test12`, `-Dname="Login as new user"`)
- I'm not quite sure why you've included `loggingPrefs` in `appium.additional.caps` -- you can skip it unless you really need it to be passed

Please give it a try and let me know

**Comment by justinhinze** [comment]
@a-en - Yes, some of the capabilities are only for Sauce Labs and may not be part of the W3C standard. These are not new capabilities we are trying, these are the capabilities and command line arguments we have been using for some time. Passing in a property like `-Dbuild=build-test12` or `-Dname="Login as new user"` will not find its way to the desiredCapabilities. 

Can we disable this feature by default and add a property to enable it? Maybe something like `appium.w3c.strict=true` ?

**Comment by a-en** [comment]
@justinhinze right, you still have to prefix them with `appium` to be included in desired capabilities.

Well, I'm not big fan of adding lots of props (especially without proper documentation for them), but in this case I don't see other option so far to support Sauce Labs specifics. 

Will come up with PR to control state of added functionality.

**Comment by justinhinze** [comment]
Thanks @a-en . We're depending on the behavior of Appium properties described here https://serenity-bdd.github.io/theserenitybook/latest/remote.html

> All properties which are starting with appium in serenity.properties will be forwarded to appium driver. e.g. setting appium.automationName = XCUITest in serenity.properties will have as end effect setting the property automationName = XCUITest in appium driver capabilities.

**Comment by a-en** [comment]
@justinhinze you could try with 2.0.77 version? I've disabled filtering/processing desired capabilities while creating Appium session by default (this functionality state is now controlled by `appium.process.desired.capabilities`)

**Comment by justinhinze** [comment]
Looks good. Capabilities are being passed to Sauce Labs. Thanks again @a-en .

**Comment by justinhinze** [comment]
Looks good. Capabilities are being passed to Sauce Labs. Thanks again @a-en .
