### ISSUE TITLE
serenity.extension.packages property not working with webdriver.driver=provided

### ISSUE THREAD

**Issue by Jaskaran-Kalsi** [serenity-bdd/serenity-core#1832]
serenity.extension.packages=<package for AfterAWebDriverScenario  and BeforeAWebDriverScenario >
Both classes are not executed while using webdriver.driver=provided.
I am providing my own driver but need AfterAWebDriverSenario to fire after a WebDriver Scenario completes.
Am I missing some settings. or does it work with only remote driver.
Thanks .

**Comment by wakaleo** [comment]
What behavior are you expecting? AfterAWebdriverScenario is designed to be used with standard drivers, not custom ones
