### ISSUE TITLE
Test with ignored steps is marked as passed

### ISSUE THREAD

**Issue by annholt** [serenity-bdd/serenity-core#1834]
We are using Serenity version 2.0.52 with Cucumber.

If an assume statement is used in the very first step, then everything works exactly as expected.  However if there are any passing steps before the ignored step then the overall result of the test is passed.

As far as I can tell from the documentation this is not expected behavior and I can't find any indication that it's been reported before.

**Comment by wakaleo** [comment]
The typical use of an assume statement is as a gateway at the start of the test, so I’m not sure how Serenity would handle this case. What is your use case?

**Comment by annholt** [comment]
In this case, we are trying to test the create feature for something called a network element

Given the user is logged on
And the user navigates to the correct page
And network element named X doesn't exist

When user adds network element named X

Then user sees network element named X in display

For each of the Given, And statements there is an assume to make sure that those things are true.  If any one of them is not then it doesn't make sense to continue.
