### ISSUE TITLE
Automatic-Module-Name entry within the MANIFEST.MF (Java 9 and above)

### ISSUE THREAD

**Issue by kedziorm** [serenity-bdd/serenity-core#1835]
I cannot find any information about plans for modularizing Serenity.
If Serenity will be not modular, could you be so kind and add:

`Automatic-Module-Name:` <module name> entry to the library's MANIFEST.MF

According to:
http://branchandbound.net/blog/java/2017/12/automatic-module-name/
it is highly recommended.

Currently, when I compile my project under JDK 11, I am receiving a warning that it is not possible to extract automatic module name from the JAR file for Serenity. Then, build fails, because it is not possible to find and use serenity.core module

**Comment by wakaleo** [comment]
No plans at the moment, but PRs are welcome.
