### ISSUE TITLE
Bug using rerun cucumber plugin

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1836]
When using the rerun plugin in cucumber with serenity, after a failed scenario, the rerun file is generated in the correct way, but when running the failed scenarios using
 ``` kotlin
@RunWith(CucumberWithSerenity::class)
@CucumberOptions(
        plugin = ["pretty", "rerun:target/rerun.txt"],
        glue = ["com.example.features.steps"],
        features = ["@target/rerun.txt"])
class FailedScenariosTestRunner
 ```
Serenity is not able to run specific scenarios, instead it will run the complete feature of a failling scenario, this is because in the CucumberWithSerenity class the runtimeOptions is obtained using "@target/rerun.txt" as features path, so it can't get the specific line filters.

**Comment by wakaleo** [comment]
Is there something the Serenity Cucumber runner should do but doesn’t?

**Comment by ricardorlg** [comment]
It should open the rerun file and send the content as the features path or use the features path that cucumber calculates and use them when calculate the filters.

**Comment by wakaleo** [comment]
Shouldn’t Cucumber be doing that? The rerun file is a Cucumber feature, not a Serenity one.

**Comment by ricardorlg** [comment]
Cucumber returns the correct feature path but serenity is the one that calculates the filter using the original runtime options without parsing the features path

**Comment by wakaleo** [comment]
I am not familiar with this Cucumber feature. Can you propose a PR?

**Comment by ricardorlg** [comment]
Sure.

**Comment by ricardorlg** [comment]
I found the problem, It's cucumber thing u can't have the rerun plugin installed twice on the same path. this can be close.
