### ISSUE TITLE
NoSuchElementException on try to find list of elements with only one visible

### ISSUE THREAD

**Issue by SergiiTrybushnyi** [serenity-bdd/serenity-core#1837]
Hello,
I am facing issue when I am trying to get list of WebElementFacades with css/xpath locator.

This variant works perfectly and it finds one element, but it is not visible
> @FindBy(css = "div[role='tabpanel'] .btn.btn-primary")
> private WebElementFacade button;

But I need to find visible element from collection and the code is

> @FindBy(css = "div[role='tabpanel'] .btn.btn-primary")
>  private List</WebElementFacade/> button;

And I get 

> [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - STEP ERROR: org.openqa.selenium.NoSuchElementException: Timed out after 10 seconds. List elements not visible

In my case I want to find collection of elements, find visible with filtering and click it, from error it seems that all the elements should be visible? Is it possible to get collection of existing elements in DOM regardless their visibility?

Thank you in advance.

**Comment by wakaleo** [comment]
@FindBy for collections tends to be unreliable in Selenium with dynamic applications. Use dynamic lookups (e.g. findAll()) instead.

**Comment by SergiiTrybushnyi** [comment]
> @findby for collections tends to be unreliable in Selenium with dynamic applications. Use dynamic lookups (e.g. findAll()) instead.

thank you for the reply, sounds weird, but it is as it is :)
