### ISSUE TITLE
EnvironmentStrategy.ENVIRONMENT_CONFIGURED_BUT_NOT_NAMED not considered in getPropertyValue() 

### ISSUE THREAD

**Issue by pmmdre** [serenity-bdd/serenity-core#1839]
Since the commit 
https://github.com/serenity-bdd/serenity-core/commit/a3aea843dd9359e356455563257dba928f209d9b#diff-d0425b78c014044fd0d91fcb936fa297 
the behavior of environments configurations changed.

**Situation:** 
When running Serenity tests locally, the "-Denvironment=xxx" paramter is set to conveniently use the environments configured in serenity.conf File.
When tests are run by Jenkins, the environment parameters are set by System property via the command line script. In this case, no "-Denvironment=xxx" parameter will be used.

Currently, it does not seem to be possible to combine those two approaches.

**Reason:**
In the Jenkins case, the EnvironmentStrategy resolves to ENVIRONMENT_CONFIGURED_BUT_NOT_NAMED (which is correct). But the method 
```
public String getPropertyValue(String propertyName) {

        switch (environmentStrategy) {
            case USE_NORMAL_PROPERTIES:
                return contextlessProperty.apply(propertyName);

            case USE_DEFAULT_PROPERTIES:
                return defaultProperty.apply(propertyName);

            case ENVIRONMENT_CONFIGURED_AND_NAMED:
                return propertyForADefinedEnvironment.apply(propertyName);
        }

        return null;
    }
```
always returns null when using this EnvironmentStrategy.

**Solution:**
Adding a new case path to getPropertyValue would resolve the issue:
```
case ENVIRONMENT_CONFIGURED_BUT_NOT_NAMED:
                return contextlessProperty.apply(propertyName);
```

**Comment by wakaleo** [comment]
Makes sense, could you prppose a PR?

**Comment by pmmdre** [comment]
I'll happily provide a PR for this if the behavior is as desired.

**Comment by pmmdre** [comment]
Will do. Thanks for the quick reply
