### ISSUE TITLE
Patch request is not supported by Serenity

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#184]
I have noticed that REST-assured PATCH requests are not logged in serenity report. Here is the example:

    rest()
                .contentType("application/json; charset=utf-8")
                .header(getAuthHeader())
                .body(json)
                .patch(System.getProperty("backend.url") + "/api/shipments/{shipmentId}", shipmentId);

**Comment by YamStranger** [comment]
Hello @dsmt! Thanks for this issue. 

Fix for this issue should be available under [v1.1.22-rc.10](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.22-rc.10) release. 

Please check it, now post operations should be in serenity reports:
 
![image](https://cloud.githubusercontent.com/assets/1667699/11424607/2efe5f1e-9457-11e5-8c51-5f7ed98ff134.png)

Thanks a lot!!

**Comment by dsmt** [comment]
Nice work, thanks!
