### ISSUE TITLE
How to handle admin login popup?

### ISSUE THREAD

**Issue by ritesh8040** [serenity-bdd/serenity-core#1842]
I am not able hand admin popup in serenity.

https://stackoverflow.com/questions/44940815/how-to-set-proxy-authentication-in-seleniumwebdriver-for-chrome-browser

**Comment by wakaleo** [comment]
This is more a Selenium usage question than a Serenity defect - could you ask it on https://serenity-bdd.rocket.chat?

**Comment by Chankami** [comment]
@ritesh8040 I'm also facing the same issue 
Did you find a solution? 
Thanks

**Comment by globalworming** [comment]
there is an accepted answer https://stackoverflow.com/a/45464519/1359903

**Comment by Chankami** [comment]
Thanks @globalworming
