### ISSUE TITLE
How to get chrome console log when click the button On uI page?

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#1843]
HI,

I have a question, when i run my story use serenity, some page always failed and told me the element not disable, maybe the return is slow from background, so i want to output console log (F12 debug model) , but i google the question, it told me with **browser.get_log**, but i don't know how to use on the test framework. Do you know how to output console log by serenity?

**Comment by wakaleo** [comment]
"browser.get_log" is not Java. Try `getDriver().manage().logs()`

**Comment by ChrisD1990** [comment]
thanks, i will try
