### ISSUE TITLE
DesiredCapabilities and ChromeOptions is not working in serenity BDD framework

### ISSUE THREAD

**Issue by Ravina020495** [serenity-bdd/serenity-core#1845]
Hi Team, 

We are trying to automate proxy setting of chrome using  DesiredCapabilities and ChromeOptions
but the code in working in normal Selemium framework but code is not working in Serenity frame work it is not working as accepted. Can you please look into the code and help us resolving the problem.

PFB Code which is working in Selenium framework:

package proxy;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.Select;

public class proxy 
{
public static void main (String arg[]) throws IOException, InterruptedException  
{
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\anurita.sharma\\Downloads\\chromedriver.exe");
    ChromeOptions options = new ChromeOptions();

    options.addExtensions(new File("C:\\Users\\anurita.sharma\\Downloads\\extension_3_0_7_1.crx"));

    DesiredCapabilities capabilities = new DesiredCapabilities();

    capabilities.setCapability(ChromeOptions.CAPABILITY, options);

    options.merge(capabilities);

    ChromeDriver driver = new ChromeDriver(options);

    driver.manage().deleteAllCookies();

    System.out.println("testing");

    driver.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);

    Thread.sleep(3000);

           String parentWindowHandle = driver.getWindowHandle();

           System.out.println("Parent window's handle -> " + parentWindowHandle);

    Set<String> allWindowHandles = driver.getWindowHandles();

    int i=0;

    for(String handle : allWindowHandles)

    {

    System.out.println("Window handle - > " + handle);

    driver.switchTo().window(handle);

    if (!handle.equals(parentWindowHandle))

    {

    System.out.println("closing  - > " + handle);

    driver.close();

    i++;

    if(i==2)

    {

           break;

    }

    }

    }

    driver.switchTo().window(parentWindowHandle);

    System.out.println("closing  - > " + parentWindowHandle);

     

    driver.navigate().to("https://www.google.co.in/");

    Thread.sleep(3000);

    driver.navigate().to("chrome-extension://gcknhkkoolaabfmlnjonogaaifnjlfnp/options.html#tabProxies");

    driver.findElement(By.xpath(".//button[@id='addNewProxy']")).click();

    driver.findElement(By.xpath(".//input[@id='proxyHost']")).sendKeys("127.0.0.1");

    driver.findElement(By.xpath(".//input[@id='proxyPort']")).sendKeys("8080");

    driver.findElement(By.xpath(".//button[@type='button']")).click();

    Select dropdown = new Select(driver.findElement(By.id("proxyModeGlobal"))); 

    dropdown.selectByVisibleText("Use proxy 127.0.0.1:08080 for all URLs");
	
	}
}

PFB Code with some changes which is not working in Serenity BDD:

	System.setProperty("webdriver.chrome.driver", "C:\\Users\\anurita.sharma\\Downloads\\chromedriver.exe");
    ChromeOptions options = new ChromeOptions();

    options.addExtensions(new File("C:\\Users\\anurita.sharma\\Downloads\\extension_3_0_7_1.crx"));

    DesiredCapabilities capabilities = new DesiredCapabilities();

    capabilities.setCapability(ChromeOptions.CAPABILITY, options);

   // options.merge(capabilities);
    ChromeDriver driver = (ChromeDriver) getDriver();
    driver = new ChromeDriver(capabilities);

    driver.manage().deleteAllCookies();

    System.out.println("testing");

    driver.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);

    Thread.sleep(3000);

           String parentWindowHandle = driver.getWindowHandle();

           System.out.println("Parent window's handle -> " + parentWindowHandle);

    java.util.Set<String> allWindowHandles = driver.getWindowHandles();

    int i=0;

    for(String handle : allWindowHandles)

    {

    System.out.println("Window handle - > " + handle);

    driver.switchTo().window(handle);

    if (!handle.equals(parentWindowHandle))

    {

    System.out.println("closing  - > " + handle);

    driver.close();

    i++;

    if(i==2)

    {

           break;

    }

    }

    }

    driver.switchTo().window(parentWindowHandle);

    System.out.println("closing  - > " + parentWindowHandle);

     

    driver.navigate().to("https://www.google.co.in/");

    Thread.sleep(3000);

    driver.navigate().to("chrome-extension://gcknhkkoolaabfmlnjonogaaifnjlfnp/options.html#tabProxies");

    driver.findElement(By.xpath(".//button[@id='addNewProxy']")).click();

    driver.findElement(By.xpath(".//input[@id='proxyHost']")).sendKeys("127.0.0.1");

    driver.findElement(By.xpath(".//input[@id='proxyPort']")).sendKeys("8080");

    driver.findElement(By.xpath(".//button[@type='button']")).click();

   //WebElementFacade dropdown = findBy(dropdownelement)); 
  //Select dropdown = new Select(dropdownelement);
    
  // dropdown.selectByVisibleText("Use proxy 127.0.0.1:08080 for all URLs proxyModeGlobal");
    //dropdownelement.selectByValue("33700130");
    Common.waitForElement(dropdownelement);
  // Use proxy 127.0.0.1:08080 for all URLs proxyModeGlobal
    dropdownelement.selectByVisibleText("Use proxy Default for all URLs");
	
	
*******************************************************************************************************

Please let me know if you need more information.

Looking forward for the response.

Regards,
Ravina Ingole

**Comment by wakaleo** [comment]
Have you tried using the BeforeAWebdriverScenario interface? https://serenity-bdd.github.io/theserenitybook/latest/extending-webdriver.html

**Comment by thaile19** [comment]
> Have you tried using the BeforeAWebdriverScenario interface? https://serenity-bdd.github.io/theserenitybook/latest/extending-webdriver.html

I have tried but it still doesn't work. Pls help me check:


`public class MyCapabilityEnhancer implements BeforeAWebdriverScenario {
    @Override
    public DesiredCapabilities apply(EnvironmentVariables environmentVariables, SupportedWebDriver driver, TestOutcome testOutcome, DesiredCapabilities capabilities) {

//        DesiredCapabilities cap = DesiredCapabilities.chrome();
        LoggingPreferences logPrefs = new LoggingPreferences();
        logPrefs.enable(LogType.PERFORMANCE, Level.ALL);
        capabilities.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);

        Map<String, Object> perfLogPrefs = new HashMap<String, Object>();
        perfLogPrefs.put("traceCategories", "browser,devtools.timeline,devtools");
        perfLogPrefs.put("enableNetwork", true);
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("perfLoggingPrefs", perfLogPrefs);
        capabilities.setCapability(ChromeOptions.CAPABILITY, options);

        return capabilities;
    }
}`

In serenity.conf:
`serenity {
  extension.packages=com.mytest.auto.testextension
}`

- Using:
`LogEntries log =  getDriver().manage().logs().get(LogType.PERFORMANCE);`
logs() returns null

**Comment by tiwari90** [comment]
@brianle19 
I am facing the same issue, by any chance have you resolved this issue?

**Comment by wakaleo** [comment]
Fixed in 3.2.0
