### ISSUE TITLE
iOS locator strategies need to be added in WebElementFacade FindBy strategies

### ISSUE THREAD

**Issue by hbanafal** [serenity-bdd/serenity-core#1846]
**Problem :** 
1. When running iOS Appium tests, PageFactory element using iOSClassChain and iOSNSPredicate string as locator strategy throwing this exception 
[main] WARN net.thucydides.core.pages.Pages - Failed to instantiate page of type class pages.locators.PageLocators ({})
java.lang.IllegalArgumentException: @$Proxy28: one of [uiAutomator, accessibility, className, id, tagName, name, xpath, css, linkText, partialLinkText, jQuery, scUsing] should be filled

2. Also When searching for List of Elements in PageFactory using iOSXCUITFindBy annotation throwing null pointer exception.

**Reason**
1. iOSClassChain and iOSNSPredicate locator strategies are missing from Valid Strategies enum in SmartAnnotation class.
2. iOSXCUITFindBy is missing in LEGAL_ANNOTATIONS in SmartFieldDecorator class. 

**Solution**
1. Added iOS Locator strategies in WebElementFacade FindBy locator strategies. 
       ```
BYIOSCLASSCHAIN("iOSClassChain") {
            @Override
            org.openqa.selenium.By getBy(Annotation annotation) {
                return MobileBy.iOSClassChain(getValue(annotation, this));
            }
        },
        BYIOSNSPREDICATE("iOSNsPredicate") {
            @Override
            org.openqa.selenium.By getBy(Annotation annotation) {
                return MobileBy.iOSNsPredicateString(getValue(annotation, this));
            }
        },
```
2. Added iOSXCUITFindBy and other valid annotations in SmartFieldDecorator. 

```
private final static List<Class<? extends Annotation>> LEGAL_ANNOTATIONS = Arrays.asList(FindBy.class,
            net.thucydides.core.annotations.findby.FindBy.class, org.openqa.selenium.support.FindBy.class,
            FindBys.class, FindAll.class, AndroidFindBy.class, AndroidFindBys.class, AndroidFindAll.class,
            iOSXCUITFindBy.class, iOSXCUITFindBys.class, iOSXCUITFindAll.class);
```

**Comment by wakaleo** [comment]
This will be available in the next release
