### ISSUE TITLE
How to extend WebElementFacade?

### ISSUE THREAD

**Issue by DayGitH** [serenity-bdd/serenity-core#1848]
Is there documentation on how to extend WebElementFacade Interface?

I'm trying to extend WebElementFacade to add frequently used functionality/patterns to it, for convenience.

I found this guide on how to extend WebElement, but not sure how to apply this to WebElementFacade:
http://elisarver.com/2012/12/09/wrapping-webelement-1/

**Comment by wakaleo** [comment]
You can use a similar wrapping strategy to the one described in the article.
