### ISSUE TITLE
Performable cannot be defined as lambda

### ISSUE THREAD

**Issue by feliksik** [serenity-bdd/serenity-core#1850]
net.serenitybdd.screenplay.Performable is defined as: 

```
@FunctionalInterface
public interface Performable extends SkipNested {
    <T extends Actor> void performAs(T var1);
}
```

Now Performable must be defined as: 

```

    private Performable actionIsPerformed(int userId) {
        return new Performable() {
            @Override
            public void performAs(Actor actor) {
                // action
            }
        };
    }
```

This is very clumsy!

If generic argument of Performable would be defined as follows: 

```
    @FunctionalInterface
    public interface Performable<T extends Actor> extends SkipNested {
        void performAs(T var1);
    }
```

We could have a nice lambda: 

```
    private Performable2<Actor> actionIsPerformed(int userId) {
        return (Actor actor) -> {
            // action
        };
    }
```

Is there a reason this is not the case?

**Comment by wakaleo** [comment]
Yes, basically a pure lambda implementation would make reporting the steps problematic.

**Comment by feliksik** [comment]
Hmmm I do not know what's going on in the background with reflection etc., and what the boundaries are, but I can make it work for the compiler with this helper method `cleanPerformable`: 

```
   private Performable<Actor> actionIsPerformed(int userId) {
        return cleanPerformable( actor -> { /* action */ }); // look, just a lambda!
    }
    private static <T extends Actor> Performable cleanPerformable(Consumer<Actor> consumer) 
    {
        return consumer::accept;
    }
```

Obviously, this is just a trick, and maybe it's even a completely wrong way of using Serenity/Performable, as I have also seen the use of Task (which is a sub-interface)... 

But does this now break something in the reporting? (I don't get this)

**Comment by wakaleo** [comment]
If you want the performable to appear as a step in the reports, it needs a @Title annotation or to implement a getTitle() (from memory).

**Comment by feliksik** [comment]
Ah I get it know. Thanks, I guess this can be closed.
