### ISSUE TITLE
SerenityBDD Gradle Project - Custom driver code is not detected by the framework

### ISSUE THREAD

**Issue by mraphael2101** [serenity-bdd/serenity-core#1851]
Hi everyone, has anyone working with SerenityBDD created their own custom driver to run remotely on a device farm, in particular SauceLabs? 

I have created the below Java class in a Serenity/Gradle project, and have added several new properties to the Serenity.properties file to detect this new class. However, the code is not executed. 

Do you have any suggestions please on why that might be the case? 

The unit tests are running successfully on the mobile device emulators on the cloud. However, I am trying to run the tests with the applied configuration on a BDD level, and not at a unit testing level. 

Many thanks for any help that you can give.  

```
public class SauceLabsSerenityDriver implements DriverSource {
    @Override
    public WebDriver newDriver() {

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.0");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, MobileBrowserType.CHROME);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");

        try
        {
            return new RemoteWebDriver(
                    new URL("https://mytoken@ondemand.eu-central-1.saucelabs.com:443/wd/hub"),
                    capabilities);
        } catch (MalformedURLException ex) {
            System.out.println(ex);
            return null;
        }
    }

    @Override
    public boolean takesScreenshots() {
        return false;
    }
}
```

The Serenity.properties file contains the below settings:
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.myproject.SauceLabsSerenityDriver
saucelabs.driver.capabilities = mydriver

**Comment by TheTestLynx** [comment]
Hi @mraphael, I think the saucelabs bit in the serenity properties file might be wrong, check https://saucelabs.com/resources/webinars/one-test-to-rule-them-all-conquer-android-and-ios-with-one-script for more information 
I hope it helps :)

**Comment by mraphael2101** [comment]
Hi @TheTestLynx, Thanks for the suggestion. Coincidentally, I have already watched this video and it did not help me. To clarify, I am trying to run Cucumber tests on Mobile Device emulators. The tests will run on the mobile's web browser and are not native apps.

**Comment by TheTestLynx** [comment]
@mraphael2101 what if you remove the line with automation name? You probably don't need it since you are defining browser. Also this line: 'saucelabs.driver.capabilities = mydriver', does not seem right to me, there is an example on minute 25 approx on that video, but it might be a bit outdated

**Comment by anujtiwari24** [comment]
First thing that needs to be checked after you get this error:
Is your script generating any logs on Appium or not. Check the appium window.
 -> If not then this means your custom driver file is not read by the code. Go to serenity.properties and check the reference to the custom driver. It may be incorrect. Check these properties:
#Custom Driver properties.
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.drivers.AppCenterIOSDriver
thucydides.driver.capabilities = mydriver
also check that you have not written any other webdriver.driver property in the properties file.

 ->If Yes, then this means you custom driver is being read by the code but there is some issue in the Capabilities. Check the capabilities carefully and make sure the values are written in the same way as expected. you may check for the casing of the values too.

**Comment by mraphael2101** [comment]
Ok, thanks for the tip. I will check and get back to you.

**Comment by mraphael2101** [comment]
Hi, you can close the ticket as its now working.
All I did was remove the @Override annotation, and ensure that only the below properties were present in serenity.properties and it worked
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.myproject.SauceLabsSerenityDriver
thucydides.driver.capabilities = mydriver
