### ISSUE TITLE
extending PageObject class and having @Step in same class generates reports with no steps

### ISSUE THREAD

**Issue by lgermani** [serenity-bdd/serenity-core#1852]
So basically I'm running tests with JUnitRunner and when I extend PageObject and have @Step in the same class the report is not showing the steps:

![image](https://user-images.githubusercontent.com/1315828/67384051-b9094900-f590-11e9-8275-334512a4723e.png)

`@Slf4j
public class BasicAuthSteps extends PageObject {

    @Step("log in as admin")
    public void logsInAsAdmin() {
        $(LoginPage.LOGIN_TEXTFIELD).type("admin");
        $(LoginPage.PWD_TEXTFIELD).type("admin");
        $(LoginPage.OK_BTN).click();

        logLoggedUserAndRole();
        verifyIfUserIsLoggedInWithAdminRole();
    }
    public void logLoggedUserAndRole(){
        log.info("User: '{}' logged in with Role '{}'",
                $(HeaderPage.USER_NAME).getText(),
                $(HeaderPage.USER_ROLE).getText());
    }
    @Step("Verify if user is logged in with Admin Role")
    public void verifyIfUserIsLoggedInWithAdminRole(){
        assertThat($(HeaderPage.USER_ROLE).getText()).contains(UserRolesEnum.ADMIN.value());
    }
}`

If I try this:
`@Slf4j
public class SerenitySteps {//extends PageObject {

    @Step("step1")
    public void step1() {
        log.info("step1");
    }

    @Step("step2")
    public void step2() {
        log.info("step2");
    }

    @Step("step3")
    public void step3() {
        log.info("step3");
    }
}`

It works, but if you just un-comment the "extends PageObject {" the report does not generate the Steps.

**Comment by wakaleo** [comment]
You can’t have @Step methods in your Page Objects. This is by design, as business logic inside page objects breaks several SOLID principles.

**Comment by lgermani** [comment]
Thanks for the quick reply @wakaleo ,  at 1st I was using "UIInteractionSteps" so that got me thinking that I could do it. It's there a goal for using "UIInteractionSteps" instead of "PageObject"?

**Comment by wakaleo** [comment]
Yes, UIInteractionSteps are intended to model UI-centric interactions with lean Page Objects (Page Objects that contain only locators and no business methods).

**Comment by lgermani** [comment]
Closing the issue.
