### ISSUE TITLE
Error with Custom Cast and Skipped Tests

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1856]
I have implemented my own cast, 
```kotlin
class CustomCast(environmentVariables: EnvironmentVariables, private val testEnvironment: TestEnvironment = TestEnvironment(environmentVariables)) : Cast() {

    override fun actorNamed(actorName: String, vararg abilities: Ability): Actor {
        ..... //some logic that returns an actor that can use Appium and call Rest API
        }
   
}
```
I have a cucumber scenario marked with the tag `@wip`  one of its steps it's already implemented, when serenity starts It runs the steps that are implemented, which tries to get the actor, which gives me some errors on console about the driver, at the en the test is marked as Skipped in report but in console is marked as failed, In fact, serenity tells me  that the test is an error instead of skip. The most problematic thing Its that it executes the logic to get the actor, should serenity ignore all steps inside a scenario that is marked as `@wip` or `@ignore`?

**Comment by wakaleo** [comment]
I think (from memory) the problem is that Serenity has limited (i.e. no) control over the execution of step definition logic, so can't prevent Cucumber from executing this code.

**Comment by ricardorlg** [comment]
Ok, I understand, I find another way to fix the problem so I will close the bug.
