### ISSUE TITLE
Remove runtime dependency on Junit(4)

### ISSUE THREAD

**Issue by amohrig** [serenity-bdd/serenity-core#1858]
When working on [#1039](https://github.com/serenity-bdd/serenity-core/issues/1039) (together with @fabianlinz and others) we found that there are runtime dependencies on Junit 4 in both the serenity-model and serenity-core sub-module of serenity-core. We think it would be beneficial if these could be removed and users can opt-in to use either Junit 4 or Junit 5 (or something else).

Removing the transitive dependency on Junit 4 would be a breaking change, I suppose. But it should at least be possible to exclude this dependency when adding a dependency to serenity-core and still being able to run tests (with another testrunner). We are of course thinking of our [serenity-junit5 module](https://github.com/fabianlinz/serenity-junit5) .

I have started to work on it in [my fork of serenity-core](https://github.com/amohrig/serenity-core), and the functionality is basically there. I still need to test it thoroughly (manually), and maybe add some (automated) tests as well.

I will create a pull-request once this is complete. Thoughts and feedback are already welcome, though!

**Comment by wakaleo** [comment]
Sounds like a good idea - happy to review/comment on your fork/PR as well.

**Comment by fabianlinz** [comment]
While updating [serenity-junit5](https://github.com/fabianlinz/serenity-junit5) we noticed that there is an implicit dependency to JUnit4 in [`net.thucydides.core.annotations.TestAnnotations#isIgnored` ](https://github.com/serenity-bdd/serenity-core/blob/f8ef5b90b1c6ef04bd876a6a59fd996bcc2bb228/serenity-model/src/main/java/net/thucydides/core/annotations/TestAnnotations.java#L48) which checks if a method has an annotation with the name "Ignore".  This allows to skip step methods by using the JUnit4 annotation `@Ignore`. The corresponding Junit5 annotation`@Disabled` is not detected. 

Detection should be moved to a new method in [JUnitAdapter](https://github.com/serenity-bdd/serenity-core/blob/b12bfa47c343eddccff4d759e9a7090f92e76279/serenity-model/src/main/java/net/thucydides/core/util/JUnitAdapter.java#L37).

**Comment by fabianlinz** [comment]
Another small one:
`net.thucydides.core.requirements.annotations.ClassInfoAnnotations#containsTest`only considers public methods to determine if a class contains test. 
This is a valid assumption for JUnit4. But in JUnit5 tests are typically not declared as public.

see also https://github.com/fabianlinz/serenity-junit5/issues/10

**Comment by wakaleo** [comment]
Fixed in 2.1.x
