### ISSUE TITLE
Default access level for String pluralize(Object word, int count)  Inflector.java#L114 causing build failure

### ISSUE THREAD

**Issue by AnshumanGo** [serenity-bdd/serenity-core#1866]
Default access level for  https://github.com/serenity-bdd/serenity-core/blob/b12bfa47c343eddccff4d759e9a7090f92e76279/serenity-model/src/main/java/net/thucydides/core/util/Inflector.java#L114

is causing code break in

https://github.com/serenity-bdd/serenity-demos/blob/master/cucumber-webtests/src/test/java/net/thucydides/showcase/cucumber/steps/SearchScenarioSteps.java#L47

**Comment by AnshumanGo** [comment]
Issue in example 
https://github.com/serenity-bdd/serenity-demos/blob/master/cucumber-webtests/src/test/java/net/thucydides/showcase/cucumber/steps/SearchScenarioSteps.java#L47

can be resolved as 


private String pluralized(int count, String word) {
        if (word == null) return null;
        if (count == 1 || count == -1) {
            return word.toString();
        }
        return Inflector.getInstance().pluralize(word);

    }

**Comment by wakaleo** [comment]
How is this causing the build to break?

**Comment by AnshumanGo** [comment]
@wakaleo 


`> Task :checkOutcomes
Checking serenity results for null in directory /Users/serenity-demos/cucumber-webtests/target/site/serenity

> Task :compileTestJava FAILED
/Users/serenity-demos/cucumber-webtests/src/test/java/net/thucydides/showcase/cucumber/steps/SearchScenarioSteps.java:48: 

error: pluralize(Object,int) is not public in Inflector; cannot be accessed from outside package
        return Inflector.getInstance().pluralize(word,count);
                                      ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

`

**Comment by wakaleo** [comment]
Thanks. Could you propose a PR to make the method public?

**Comment by AnshumanGo** [comment]
Ok

**Comment by AnshumanGo** [comment]
@wakaleo Done

https://github.com/serenity-bdd/serenity-core/pull/1867
