### ISSUE TITLE
SerenityBDD setting download path via System.getProperty("user.dir") is not working

### ISSUE THREAD

**Issue by Rashmik24** [serenity-bdd/serenity-core#1869]

**Comment by Rashmik24** [comment]
I am trying to set download path after a click is done on object, on my local set work with passing the value in Serenity.properties file "chrome_preferences.download.default_directory = my local setup complete path" . Passing absolute  path does not work.
When running the test case, I can not hard code the path, I need to pass the path through "System.getProperty("user.dir")" and append path to it. 
How can I achieve this in Serenity, passing the dynamic path to chrome-capabilities file to set default download location.

Kindly help me with this as I am stuck.

**Comment by wakaleo** [comment]
This is not supported at the moment.

**Comment by wakaleo** [comment]
Have you tried:
```
chrome_preferences.download.default_directory=${user.dir}/my/download/path
```

**Comment by Rashmik24** [comment]
It worked, thank you.
