### ISSUE TITLE
Hi, Can you please say how take screenshot of app desktop? I need include hours of windows in my evidence. I am use screenplay version 2.0.84 with cucumber.

### ISSUE THREAD

**Issue by Candyguerrero17** [serenity-bdd/serenity-core#1873]

**Comment by wakaleo** [comment]
This isn’t supported by Selenium. If you can find a Java library to do it you could attach the file as evidence in your test.

**Comment by wakaleo** [comment]
You can use the Robot or Frame classes for this: See https://stackoverflow.com/questions/58305/is-there-a-way-to-take-a-screenshot-using-java-and-save-it-to-some-sort-of-image

Then record the file as evidence in your test report: https://johnfergusonsmart.com/embedding-custom-data-in-serenity-reports/

**Comment by wakaleo** [comment]
Closing presumed answered
