### ISSUE TITLE
no procedure to register a custom listener 

### ISSUE THREAD

**Issue by karthiksml** [serenity-bdd/serenity-core#1874]
Hi, I am using serenity with junit for rest api automation. I need a way by which I have to run the setup only once before any test method starts. It is achievable if we use RunListener in junit4. however I couldn't find a way to implement this in serenity. can someone share any documents to follow or please explain. it will be really helpful.

I had gone through https://schenkweb.nl/2017/07/11/serenity-bdd-register-a-custom-listener/ this link but it didn't workout.

**Comment by hollandjake** [comment]
This would be a really useful feature
