### ISSUE TITLE
Serenity with Cucumber support for JUnit 5.

### ISSUE THREAD

**Issue by vedshankar14** [serenity-bdd/serenity-core#1877]
Hi,
I am using serenity with cucumber in our project and we are planning to upgrade Junit 4.2 to JUnit 5. So, I wanted to check when serenity with cucumber will start supporting JUnit 5.

Regards,
Ved

**Comment by wakaleo** [comment]
This is an open source project. It will be ready when it is ready. You can run JUnit 4 tests in JUnit 5 using the vintage engine if I recall correctly.

**Comment by vedshankar14** [comment]
Ok. Thanks for the info.
