### ISSUE TITLE
Is there any properties to display Test Environment details, i.e. Browser type, browser version, application url etc in Serenity Standard Report's Summary page?

### ISSUE THREAD

**Issue by susnigdha1** [serenity-bdd/serenity-core#1878]
Is there any properties to display Test Environment details, i.e. Browser type, browser version, application url etc in Serenity Standard Report's Summary page? Is there any plan to provide support for these things in future?

**Comment by wakaleo** [comment]
You can see a lot of this in the Info icon at the top of the screen:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/55986/69350900-4c0dcf80-0c72-11ea-872d-3ec9d52cdf17.png">
