### ISSUE TITLE
Coverage progress bar is vertical-align: top

### ISSUE THREAD

**Issue by nu75h311** [serenity-bdd/serenity-core#1879]
When generating the report, whenever there is a table with the coverage progress bar column (except for the main index page), the progress bar is aligned to top.

Reproduce:

1. Generate the report from the serenity-cucumber4-screenplay archetype project.
2. Open the report and navigate to the Capabilities tab.

Used serenity-core version 2.0.88

**Comment by wakaleo** [comment]
Can you propose a PR or a fix to the CSS stylesheet?

**Comment by nu75h311** [comment]
Yeah, I'll take a look.
