### ISSUE TITLE
Serenity reports do not show steps executed via GPars

### ISSUE THREAD

**Issue by pards** [serenity-bdd/serenity-core#1882]
The Serenity HTML report (target/site/serenity/index.html) does not show the steps that are executed in parallel using the Groovy parallels library, [GPars](http://www.gpars.org/webapp/guide/index.html).

```Groovy
import static groovyx.gpars.GParsPool.withPool

@RunWith(SerenityRunner.class)
class ParallelTest {
    @Steps
    ApiSteps apiSteps

    @Test
    void parallelTest() {
        withPool {
            def accountSummary = apiSteps.&accountSummary.asyncFun()
            def customerProfile = apiSteps.&customerProfile.asyncFun()
            accountSummary()
            customerProfile()
        }
    }
}
```
The steps are executed correctly but are omitted from the report.

Moving the parallel block `withPool` into its own `@Step` inside `ApiSteps` gets it onto the report but the component steps (`accountSummary`, `customerProfile`) do not show up so the critical details about the REST call are lost.

**Comment by wakaleo** [comment]
I don’t think this will be possible - the step listeners are associated with the main execution thread be so if stuff happens in other threads there is no way for it to be detected.
