### ISSUE TITLE
@Manual test does not work correctly

### ISSUE THREAD

**Issue by bokivaol** [serenity-bdd/serenity-core#1883]
Hi,

I wanted to use annotations for manual tests `@Manual(result = TestResult.SUCCESS)` or any other test result possibility but it is not shown correctly in report. Tests are always under Failed no matter if they are marked as Success ....
Then I used your class and same thing happened
[SampleManualScenario](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-junit/src/test/java/net/thucydides/samples/SampleManualScenario.java).

I run this tests using Gradle and JUnit, not using Cucumber.

Error which I receive is:
`java.lang.AssertionError`

![Screenshot_2](https://user-images.githubusercontent.com/9623813/69812043-bcc36780-11ef-11ea-9133-495283afed03.png)

**Comment by wakaleo** [comment]
Does your manual test contain any code?

**Comment by bokivaol** [comment]
No. At the end I used your sample class (SampleManualScenario) and tried it and the same thing happened.
There are no code in manual tests.

**Comment by wakaleo** [comment]
I don’t recall if this feature is finished for JUnit to be honest - it is mainly for Cucumber. You may want to dig into the code.

**Comment by bokivaol** [comment]
Thank you.
