### ISSUE TITLE
Question: is there a reason for the report to be limited to ~1024px width?

### ISSUE THREAD

**Issue by nu75h311** [serenity-bdd/serenity-core#1887]
I could really benefit from extra real estate, specially when the test results table show features/stories along with the scenario names.  

CURRENT:
![current](https://user-images.githubusercontent.com/18273538/70060304-8d8f6a80-15e2-11ea-981c-ded688a06745.JPG)

PROPOSAL:
![proposal](https://user-images.githubusercontent.com/18273538/70060312-93854b80-15e2-11ea-94af-727a25e53b54.JPG)

**Comment by wakaleo** [comment]
If you would like to have a go at restyling the CSS and freemarker templates. I would be happy to review.

**Comment by nu75h311** [comment]
Aye, captain!
