### ISSUE TITLE
@manual-last-tested tag does not work as expected

### ISSUE THREAD

**Issue by jakimcho** [serenity-bdd/serenity-core#1889]
Hello

I have several cucumber scenarios annotated with `@manual-last-tested:sprint-15 @manual-result:passed` and when run my project with `current.target.version=sprint-16` property set in the `serenity.properties` file, the result report still mark those test cases as passed.

### Steps
1. Mark some cucumber scenarios with tags:
```
  @manual @todo
  @manual-result:passed
  @manual-last-tested:sprint-15
  Scenarion: Some Manual scenario
.......
```
2. Set `current.target.version=sprint-16` in `serenity.properties`
3. Run the automation:
```
mvn verify -Dcucumber.options="--tags @manual"
```

### Expected
I should see the scenario in the report marked as pending, with a note indicating that a new manual test is required:
![image](https://user-images.githubusercontent.com/6280772/70129100-d26cdd00-1686-11ea-8681-16ab4daf7b6a.png)

### Actual
I see the scenario as passed in the report:
![image](https://user-images.githubusercontent.com/6280772/70129003-a94c4c80-1686-11ea-99fc-dd9f99922bda.png)

### Env
maven:
```
<serenity.version>2.0.88</serenity.version>
<serenity.cucumber.version>1.9.45</serenity.cucumber.version>
```

**Comment by wakaleo** [comment]
I can't reproduce this with the configuration you describe - can you provide a sample project?

**Comment by jakimcho** [comment]
Hello
I will close this issue as currently, I cannot reproduce it either.
Sorry for the disturbances.
