### ISSUE TITLE
Given story has failed but build has finished successfully

### ISSUE THREAD

**Issue by klokovas** [serenity-bdd/serenity-core#189]
I have some story:
```
GivenStories: stories/demo.story
Scenario: test scenario
Given....
When...
Then...
```

`demo.story` fails and main story skipps but build finishes successfully.
As far as I understand build should finish with an error too.
![givenstoryfailed](https://cloud.githubusercontent.com/assets/8973021/11217526/d171a820-8d61-11e5-9693-8dfd9d54784b.png)

**Comment by klokovas** [comment]
+ The same happens when web driver (in my case `appium driver`) couldn't be initiated during test. 
Should I create another issue for this case?

**Comment by wakaleo** [comment]
Hi Klokiv,

Yes, please create a different issue for this.

Thanks

John

**Comment by wakaleo** [comment]
Moved to https://github.com/serenity-bdd/serenity-jbehave/issues/84
