### ISSUE TITLE
Serenity BDD project with both JUnit and Cucumber tests unable to use maven tag invoker

### ISSUE THREAD

**Issue by admathe** [serenity-bdd/serenity-core#1893]
Our team is trying to add both Cucumber feature file tests with CucumberWithSerenity.class junit runners as well as JUnit style tests using just SerenityRunner.class or SerenityParaterizedRunner.class. When I try to run our tests via the maven invoker with tags, however, it is not running our cucumber tests; it's only running the tagged junit tests. From what I've read in the documentation and posts online, it should work like this:
mvn clean verify -Dtags="application" -Dcucumber.options="--tags @other_application"

Note: I downloaded the cucumber starter project, added one junit test with the application tag and added @other_application tag to the sample search_by_keyword.feature and ran the above maven and I got the same results (it only ran the junit and did not run the cucumber)

**Comment by wakaleo** [comment]
Are you mixing JUnit tests and cucumber scenarios in the same test suite?

**Comment by admathe** [comment]
Yes, we are.

Had a minor brainstorm and realized that I can probably make this work with 2 poms: one pom.xml where surefire plugin includes *Cucumber.java and then another pom_junit.xml that includes When*.java junit tests then run each separately and aggregate at the end, like this:
mvn clean verify -Dcucumber.options="--tags @other_application"
mvn -f pom_junit.xml verify -Dtags="application" serenity:aggregate
I'd rather run them together if possible (tracking multiple poms not ideal), but I'll do what I have to do to make this project work haha :).

**Comment by wakaleo** [comment]
The tagging systems for Cucumber and JUnit are totally different, so it is tricky to mix them both.

**Comment by admathe** [comment]
hmm, i see.  But they "should" work.  There are a number of examples in the documentation/training materials that show them together, like this section about filtering reports:
https://serenity-bdd.github.io/theserenitybook/latest/filtering-reports.html

**Comment by wakaleo** [comment]
This should be fixed in 2.1.0
