### ISSUE TITLE
Is the any possibility print link to report in console aggregated by gradle?

### ISSUE THREAD

**Issue by stalexmr** [serenity-bdd/serenity-core#1899]
Hello,

Is the any possibility print clickable link to report in console aggregated by gradle:

Modify this:
> Task :aggregate
Generating Serenity Reports for myservice to directory /Users/user/repos/gateway/myservice/target/site/serenity

To this:
> Task :aggregate
Generating Serenity Reports for myservice to directory  file://Users/user/repos/gateway/myservice/target/site/serenity/index.html

**Comment by wakaleo** [comment]
Implemented in the latest versions
