### ISSUE TITLE
The "serenity.take.screenshots=FOR_FAILURES" configuration is not respected

### ISSUE THREAD

**Issue by bady2bro** [serenity-bdd/serenity-core#1901]
Serenity version: 2.0.81
Serenity Cucumber version: 1.0.21
Cucumber version: 4.2.0

We have a serenity.properties file that contains this setting "serenity.take.screenshots=FOR_FAILURES" and the tests should use this.

But, as seen in the attached photo, there are screenshots for all UI interactions.

Is there something that overwrites this setting?

Note that I removed all Serenity.takeScreenshot() calls from the code and it still takes every screenshot.
Also, we didn't use any "@Screenshots" tags

![SerenityReportScreenshots](https://user-images.githubusercontent.com/52037336/71095077-b011ae00-21b4-11ea-8fa3-13158099a37e.png)

**Comment by wakaleo** [comment]
I can't reproduce it: `serenity.take.screenshots=FOR_FAILURES` should work from either `serenity.properties` or `serenity.conf`. Are you sure it isn't being overridden somewhere else?

**Comment by bady2bro** [comment]
> I can't reproduce it: `serenity.take.screenshots=FOR_FAILURES` should work from either `serenity.properties` or `serenity.conf`. Are you sure it isn't being overridden somewhere else?

Does a "serenity.conf" file override the "serenity.properties" configuration from the parent directory?
Because I had a conf file which didn't specify the serenity.take.screenshot property, in a directory on the same project but lower hierarchically, and when I removed it, the screenshots worked as intended.
