### ISSUE TITLE
chatty logging from BaseStepListener

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#1902]
I just upgraded to version 1.9.49. When running my tests I see new logs like:

```
[WARN] BaseStepListener - stepStarted: net.thucydides.core.steps.ExecutedStepDescription@6ba7383d
[WARN] BaseStepListener - stepFinished: current outcome: ...
```

I normally have logs from 3rd parties turned to default=warn, but the above makes my logs very chatty.
Why is this a warning? Warning generally suggests something the end-user should pay attention to and possibly fix.
Can this be turned down to just info?

**Comment by wakaleo** [comment]
This will be fixed in the next release
