### ISSUE TITLE
Unable to integrate Sauce labs with Serenity for web automation

### ISSUE THREAD

**Issue by copavan** [serenity-bdd/serenity-core#1904]
I am trying to run Serenity tests on Sauce labs, but getting the following error - Caused by: java.lang.NullPointerException at net.thucydides.core.webdriver.capabilities.SetAppropriateSaucelabsPlatformVersion.from(SetAppropriateSaucelabsPlatformVersion.java:49)at net.thucydides.core.webdriver.capabilities.SaucelabsRemoteDriverCapabilities.configureTargetPlatform(SaucelabsRemoteDriverCapabilities.java:77)at net.thucydides.core.webdriver.capabilities.SaucelabsRemoteDriverCapabilities.getCapabilities(SaucelabsRemoteDriverCapabilities.java:43)at net.serenitybdd.core.webdriver.driverproviders.SaucelabsDriverBuilder.findSaucelabsCapabilities(SaucelabsDriverBuilder.java:48)at net.serenitybdd.core.webdriver.driverproviders.SaucelabsDriverBuilder.buildWithOptions(SaucelabsDriverBuilder.java:33)at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:44)at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:125)
	... 79 more

Here is my serenity.properties file.
----------------------------------------
saucelabs.url=http://username:accesskey@ondemand.saucelabs.com:80/wd/hub
saucelabs.target.platformName=Windows 10
saucelabs.driver.version=78.0
saucelabs.test.name=Sauce Labs Serenity
webdriver.driver=chrome

Could someone please help me with resolving this issue. What am i missing ?

**Comment by copavan** [comment]
saucelabs.url=http://<<username>>:<<accesskey>>@ondemand.saucelabs.com:80/wd/hub

**Comment by alexanderkranga** [comment]
If this is still an issue, can you try something like this:
```
webdriver.driver=chrome
saucelabs.target.platform=Windows 10
saucelabs.driver.version=latest
saucelabs.user.id=<your_username>
saucelabs.access.key=<your_access_key>
saucelabs.url=http://username_accesskey@ondemand.saucelabs.com:80/wd/hub
```
