### ISSUE TITLE
Plans to upgrade to serenity-core to Selenium 4

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1905]
Hello,

Now that from ChromeDriver v75 onwards, the w3c option is set to true by default.

Selenium 4 is the first version that properly complies with w3c standards. Is updating to Selenium 4 part of the roadmap for serenity-core anytime soon?

https://medium.com/@juanba48/selenium-4-is-now-w3c-compliant-what-does-this-mean-ceb44de2d29b

Thanks!

**Comment by wakaleo** [comment]
When it comes out of alpha, but feel free to have a play if you would like to help out and see what changes will be needed

**Comment by SumantaSarathiChakraborty** [comment]
I tried updating the Selenium version explicitly but getting the following error:class file for org.openqa.selenium.internal.WrapsElement not found

I will check further and post if I find anything. Anyone else tried/faced this issue already?

**Comment by wakaleo** [comment]
There are major, deep API changes in Selenium 4; you cannot simply update the version. You need to wait until the Selenium 4 version is stable and integrated into Serenity, or have a look at the Serenity code base and see what updates need doing to make it work.
