### ISSUE TITLE
[Upgraded 2.0.52]  java.lang.NoSuchMethodError: org.springframework.util.Assert.notNull

### ISSUE THREAD

**Issue by jayzsuarez** [serenity-bdd/serenity-core#1908]
@wakaleo 

I upgraded version of serenity from 1.8.21 to 2.0.52 and JBehave from 1.33.0 to 1.46.0 then I got the error of  java.lang.NoSuchMethodError: org.springframework.util.Assert.notNull.

Actual command to run test was mvn clean verify -Dtest.suite=test_story -Ptest_profile then under test_story package I have class file same story name. The actual runner file extends SerenityStory

+Package test_story
a. Runner Class
public class LogInTest extends SerenityStory {
}

b. LogInTest.story

POM configuration:
```
	<plugin>
		<artifactId>maven-failsafe-plugin</artifactId>
			<version>2.18</version>
			<configuration>
		<includes>
			<include>**/${test.suite}/*.java</include>
		</includes>
		</configuration>
			<executions>
				<execution>
					<goals>
						<goal>integration-test</goal>
						<goal>verify</goal>
					</goals>
				</execution>
			</executions>
	</plugin>
```

**Comment by wakaleo** [comment]
That looks like a spring dependency conflict. Do a dependency analysis and check your versions of Spring.

**Comment by jayzsuarez** [comment]
@wakaleo  working on analysis of all dependencies.

**Comment by wakaleo** [comment]
Did you manage to resolve this issue?

**Comment by jayzsuarez** [comment]
@wakaleo It is already resolved. Fix was related to the version of Spring dependencies v4.xx and Serenity core version uses v5.xx. Updated the Spring dependencies and able to use latest version for Serenity-Jbheave. Thanks a lot!
