### ISSUE TITLE
Serenity 2.0.90 - logs are cluttered with WARN level test/steps execution

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#1909]
In serenity 2.0.90 there are huge amount of logging test/step execution with WARN level. This makes console output hardly readable, even on INFO level.

Seems simply merging commit dc1ef2ec45b2ea81dd296cee1988fb1861818dd6 can fix it.

**Comment by wakaleo** [comment]
Correct , this is fixed in the upcoming release (you can check with a snapshot build now to be sure though)

**Comment by scormaq** [comment]
Fixed in 2.0.91
