### ISSUE TITLE
How to get the line number of where the scenario's got stopped from the feature files [eg:- scenario.getLine() instead of scenario.GetLines()]

### ISSUE THREAD

**Issue by adityabhargav** [serenity-bdd/serenity-core#1913]

**Comment by wakaleo** [comment]
Probably more a Cucumber question than a Serenity one - all Serenity has available is the Cucumber classes.

**Comment by adityabhargav** [comment]
Thankx for reply @wakaleo , i will forward the query to cucumber BDD...
