### ISSUE TITLE
Junit: don't see any option to expand the cucumber steps under the scenario

### ISSUE THREAD

**Issue by onlybiju** [serenity-bdd/serenity-core#1914]
Hi Team,
I recently upgraded all of our serenity libs, earlier I was able to expand scenarios under junit ->Feature->Cucumber Scenarios. However when I upgraded it to latest version I don't see that option now. Not sure where is the issue or if there is any settings in STS to get it working. Appriciate your help here.
Gradle dependencies
dependencies {
compile group: 'com.jayway.jsonpath', name: 'json-path', version: '2.4.0'	
    compile group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
    compile group: 'io.swagger', name: 'swagger-models', version: '1.5.24'
	testCompile group: 'org.skyscreamer', name: 'jsonassert', version: '1.5.0'
	compile group: 'com.github.fslev', name: 'json-compare', version: '1.1.0'
	testCompile group: 'net.serenity-bdd', name: 'serenity-spring', version: '2.0.90'
    testCompile 'net.serenity-bdd:serenity-core:2.0.90'
    testCompile 'net.serenity-bdd:serenity-junit:2.0.90' 
    testCompile 'net.serenity-bdd:serenity-cucumber:1.9.49'
    testCompile 'net.serenity-bdd:serenity-screenplay:2.0.90'
    testCompile 'net.serenity-bdd:serenity-rest-assured:2.0.90'
    testCompile 'net.serenity-bdd:serenity-reports:2.0.90'
	testCompile 'junit:junit:4.12'
    testCompile "org.codehaus.groovy:groovy-all:2.4.7"
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('org.jsoup:jsoup:1.10.2')
    compile "org.jsoup:jsoup:1.10.2"
    compile "org.apache.poi:poi:3.12"
    compile "org.apache.poi:poi-ooxml:3.12"
    compile "org.apache.poi:poi-ooxml-schemas:3.12"
    compile "dom4j:dom4j:1.6"
    compile "org.apache.xmlbeans:xmlbeans:2.3.0"
    compile 'org.json:json:20160212'
    compile 'com.fasterxml.jackson.core:jackson-core:2.2.2'
	compile 'com.fasterxml.jackson.core:jackson-databind:2.2.2'
	compile 'com.fasterxml.jackson.core:jackson-annotations:2.2.2'
	compile group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jdk8', version: '2.10.0'	
	compile fileTree(dir: 'libs', include: '*.jar')
	compile group: 'jline', name: 'jline', version: '2.11'  
}

Junit console  
![image](https://user-images.githubusercontent.com/19915208/72191188-0eead180-33c7-11ea-8712-944f1d93d4eb.png)

Cucumber Scenario  
![image](https://user-images.githubusercontent.com/19915208/72191007-997f0100-33c6-11ea-9e72-bcddc309ed3f.png)

I don't see any option to expand the scenario to see my cucumber steps that is Given, When, Then statements.

**Comment by wakaleo** [comment]
I don’t know anything about how Eclipse renders the Cucumber test results; there is no special Serenity code for this.
