### ISSUE TITLE
the property serenity.outputDirectory do not use the environment specific configuration

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1916]
When I set the serenity.outputDirectory inside an environment-specific configuration in the serenity.conf file serenity is still using the default path.
 for example: 
  android {
    appium.platformName = android
    appium.automationName = uiautomator2
    appium.showChromedriverLog=true
    serenity.outputDirectory  = target/site/reports/android
    report.subtitle="Android App"
  }

**Comment by ricardorlg** [comment]
this also applies for report.customfields property

**Comment by wakaleo** [comment]
That’s not supported at the moment
