### ISSUE TITLE
When i am creating an serenity maven project using mvn archetype: generate -dfilter=serernity its not able to configure POM.xml correctly 

### ISSUE THREAD

**Issue by vaseemhussain** [serenity-bdd/serenity-core#1917]
The problem is it is downloading maven-fail-safe-plugin dependency from http://jcenter.bintray.com/org/apache/maven/plugins/maven-failsafe-plugin/2.22.1/maven-failsafe-plugin-2.22.1.pom.

As in the POM.xml the site address is given is http://jcenter.bintray.com which is getting me an error 
like this 
Authorization failed for http://jcenter.bintray.com/org/apache/maven/plugins/maven-failsafe-plugin/2.22.1/maven-failsafe-plugin-2.22.1.pom 403 Forbidden

I try to change the address by updating it to Https, it works as it downloads all the necessary dependencies but it breaks the Maven project.

Please help.

**Comment by wakaleo** [comment]
403 forbidden sounds like a local network issue of some kind

**Comment by wakaleo** [comment]
I can confirm this is not a Serenity issue - you need to make sure maven can access the public repos (or your local artifactory or nexus).

**Comment by ricardorlg-aval** [comment]
the problem is that Jcenter is https only since Jan 13, make sure that u change Jcenter repository to use Https.

**Comment by phamhiepst** [comment]
same here

**Comment by wakaleo** [comment]
Change the bintray urls in the pom.xml to https. This will be fixed in the next release.

**Comment by vaseem78652** [comment]
I have tried but updating bintray url to https in pom.xml is not helping as the pom.xml file would still show error
