### ISSUE TITLE
Zalenium Has Wrong Status Indicators

### ISSUE THREAD

**Issue by newsn31** [serenity-bdd/serenity-core#1919]
The cookies added to the zalenium cookes indicate the wrong status, I don't think I've ever saw a failure check mark as indicated in the zalenium legend

![screenshot-localhost_4444-2020 01](https://user-images.githubusercontent.com/10625800/72656101-fbeb7a80-394d-11ea-9c6b-9401c70ce7d4.png)

**Comment by wakaleo** [comment]
The code looks correct and follows the Zalenium docs as far as I can tell (https://opensource.zalando.com/zalenium/). Can you provide a sample project!
