### ISSUE TITLE
Missing pie chart in serenity aggregate report

### ISSUE THREAD

**Issue by mansiKulkarni39** [serenity-bdd/serenity-core#1920]
Hi,
In serenity aggregate report, pie chart is missing. I have attached screenshot of the report also pom.xml is attached.

Version used,
<serenity.version>2.0.91</serenity.version>
<serenity.maven.version>2.0.90</serenity.maven.version>
<serenity.cucumber.version>1.9.50</serenity.cucumber.version> 

[pom.docs.docx](https://github.com/serenity-bdd/serenity-core/files/4085452/pom.docs.docx)

![image](https://user-images.githubusercontent.com/58168600/72715381-57667400-3bab-11ea-99f8-9e44f9125a91.png)

**Comment by wakaleo** [comment]
Make sure the maven plugin version is the same as the core version.

**Comment by mansiKulkarni39** [comment]
Even both are same it is not displaying pie chart. Tried many things.

**Comment by wakaleo** [comment]
Did you run a clean build? Are there any error messages?

**Comment by mansiKulkarni39** [comment]
Yes, executed by clean build.

**Comment by mansiKulkarni39** [comment]
One of the warning is 
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!.

**Comment by wakaleo** [comment]
I can’t reproduce this - can you provide a sample project?

**Comment by mansiKulkarni39** [comment]
I just deleted test report folder (Which I created under src/test/resources) and again created with same name(testReports) in same location(src/test/resources) and then executed build. So now it is giving me pie chart.

![image](https://user-images.githubusercontent.com/58168600/72790528-be019580-3c70-11ea-8c37-7a3026d4d919.png)

**Comment by wakaleo** [comment]
Have you modified the default output directory?

**Comment by mansiKulkarni39** [comment]
Yes. I created in src/test/resources/testReports which path mentioned in serenity.properties.

**Comment by wakaleo** [comment]
You shouldn't use directories in the src folders for output, it can mess up your version control and build process.

**Comment by mansiKulkarni39** [comment]
Ok.
I will revert. Thanks for your quick response.
