### ISSUE TITLE
@RunWith(SerenityParameterizedRunner.class) test driver doesn't re-start a new session

### ISSUE THREAD

**Issue by phamhiepst** [serenity-bdd/serenity-core#1921]
I'm using:
<serenity.version>2.0.91</serenity.version>

My Test has 5 data test

        @RunWith(SerenityParameterizedRunner.class)
        @Managed
	WebDriver driver;
	@After
	public void tearDown() {
		// do nothing
	}

I expected after each test, the driver will close and start from the beginning automatically, but it does not. The same code did worked well as expected with serenity 2.0.82

**Comment by phamhiepst** [comment]
@wakaleo the issue happens from 2.0.84 version

**Comment by wakaleo** [comment]
Could would provide a small sample test to demonstrate the issue?

**Comment by wakaleo** [comment]
Thanks for spotting this, it will be fixed in the next release.

**Comment by phamhiepst** [comment]
@wakaleo the issue was fixed in 2.1.0
