### ISSUE TITLE
Cucumber - Serenity - HTTP Proxy - Not working

### ISSUE THREAD

**Issue by verhagen** [serenity-bdd/serenity-core#193]
When combining Cucumber with Serenity, the `serenity.proxy.http` are not picked up, once the browser (firefox) is started.

File `serenity.properties`

    serenity.proxy.http = localhost
    serenity.proxy.http_port = 8083

__WARNING__
In case _only_ Serenity is used, it does work
In case _only_ Cucumber is used, without Serenity it also does work (setting the http proxy, through Cucumber)

**Comment by YamStranger** [comment]
Hello @verhagen. 

Thanks a lot for provided fix, it looks good! 

I will check it as soon as possible.

**Comment by eskape** [comment]
Ehm...@YamStranger ... You are welcome.

**Comment by verhagen** [comment]
Nice work @eskape Thx!!!
