### ISSUE TITLE
Serenity passing a Question as True when it should not

### ISSUE THREAD

**Issue by TheGlobalist** [serenity-bdd/serenity-core#1931]
I'm trying to implement some BDD on a Java 8 project.
These are the dependencies that I'm using with Maven for having all Serenity-related plugins:

`
    
    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-core</artifactId>
        <version>2.1.0</version>
    </dependency>

    
    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-cucumber</artifactId>
        <version>1.9.48</version>
    </dependency>

    
    <dependency>
        <groupId>org.hamcrest</groupId>
        <artifactId>hamcrest</artifactId>
        <version>2.2</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-screenplay</artifactId>
        <version>2.1.0</version>
    </dependency>

    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-screenplay-webdriver</artifactId>
        <version>2.1.0</version>
    </dependency>

    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-junit</artifactId>
        <version>2.1.0</version>
        <scope>test</scope>
    </dependency>`

When I try to run this snippet of step

`   @And("the user click on the (.*) button")
    public void clickOnSubmitButton(String submitButton) {
    
	    Actor actor = theActorInTheSpotlight();
	    
	    BrowseTheWeb.as(actor).getDriver().findElement(By.xpath(constantsService.getXpathsMap().get(submitButton))).click();
		final Integer possibileVariazioneFlusso = Serenity.sessionVariableCalled("numero_visite_prima");
		if (possibileVariazioneFlusso != null) {
			final String source = BrowseTheWeb.as(actor).getDriver().getPageSource().toLowerCase();
			actor.should(seeThat("Prova",CanIHave.pageSource(), containsString("MUSE")));
			//boolean prova = BrowseTheWeb.as(actor).getDriver().getPageSource().toLowerCase().contains("internal server error");
			//Assert.assertFalse("L'utente salva la visita ispettiva", prova);
		}
		try {
			Thread.sleep(3000);
		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }`

No matter what question do I put inside the actor.should(seeThat()), Serenity would just either skip it or mark it as true even though it shouldn't be.
In this specific case, I'm trying to assert that at the given page (which just only shows "Internal Server Error") the source contains the string "MUSE". While I'm expecting this to fail, this actually passes.

The content of the CanIHave question is...

`
import net.serenitybdd.screenplay.Actor;
import net.serenitybdd.screenplay.Question;
import net.serenitybdd.screenplay.abilities.BrowseTheWeb;
public class CanIHave implements Question<String> {

    @Override
    public String answeredBy(Actor actor) {
        return BrowseTheWeb.as(actor).getDriver().getPageSource().toLowerCase();
    }

    public static Question<String> pageSource() {
        return new CanIHave();
    }
}
`

I've tried even the latest releases on Maven but nothing worked... what am I missing?

**Comment by globalworming** [comment]
are you sure about the 

    	final Integer possibileVariazioneFlusso = Serenity.sessionVariableCalled("numero_visite_prima");
	if (possibileVariazioneFlusso != null) {

part? if your question is skipped it may be because `possibileVariazioneFlusso` is `null`? When using actors, i would recomment using `actor.remembers` and `actor.recalls` instead of `sessionVariable`

**Comment by TheGlobalist** [comment]
> are you sure about the
> 
> ```
> final Integer possibileVariazioneFlusso = Serenity.sessionVariableCalled("numero_visite_prima")
> if (possibileVariazioneFlusso != null) {
> ```
> 
> part? if your question is skipped it may be because `possibileVariazioneFlusso` is `null`? When using actors, i would recomment using `actor.remembers` and `actor.recalls` instead of `sessionVariable`

Yes, this part isn't skipped in the debug process

**Comment by globalworming** [comment]
and the `final String source` is filled also with lowercase page source?

**Comment by TheGlobalist** [comment]
> and the `final String source` is filled also with lowercase page source?

Yes!
The debugger reaches that part and also reaches `pageSource()` static method of the `CanIHave` class but, after that, the answeredBy() is not triggered

**Comment by TheGlobalist** [comment]
Now with the following configuration on Maven

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>


<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <cucumber.version>1.2.5</cucumber.version>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
</properties>



<dependencies>

    

    
    <dependency>
        <groupId>org.sql2o</groupId>
        <artifactId>sql2o</artifactId>
        <version>1.6.0</version>
    </dependency>

    
    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-cucumber</artifactId>
        <version>1.9.48</version>
    </dependency>


    
    <dependency>
        <groupId>org.hamcrest</groupId>
        <artifactId>hamcrest</artifactId>
        <version>2.2</version>
        <scope>test</scope>
    </dependency>


    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-screenplay</artifactId>
        <version>2.1.0</version>
    </dependency>

    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-screenplay-webdriver</artifactId>
        <version>2.1.0</version>
    </dependency>

    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-junit</artifactId>
        <version>2.1.0</version>
        <scope>test</scope>
    </dependency>`

    <dependency>
        <groupId>com.oracle</groupId>
        <artifactId>ojdbc</artifactId>
        <version>7</version>
        <scope>system</scope>
        <systemPath>${project.basedir}/libs/ojdbc7.jar</systemPath>
    </dependency>

    
    <dependency>
        <groupId>com.googlecode.json-simple</groupId>
        <artifactId>json-simple</artifactId>
        <version>1.1.1</version>
    </dependency>


    



    
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-chrome-driver</artifactId>
        <version>3.141.59</version>
    </dependency>

    


    

    
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-firefox-driver</artifactId>
        <version>3.6.0</version>
    </dependency>

    
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-ie-driver</artifactId>
        <version>3.6.0</version>
    </dependency>

</dependencies>


</project>`
I am getting the following error

````
Test ignored.

java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at net.thucydides.core.steps.BaseStepListener.getCurrentStep(BaseStepListener.java:662)
	at net.thucydides.core.steps.BaseStepListener.updateExampleLineNumber(BaseStepListener.java:240)
	at net.thucydides.core.steps.StepEventBus.updateExampleLineNumber(StepEventBus.java:245)
	at cucumber.runtime.formatter.SerenityReporter.lambda$handleTestStepStarted$9(SerenityReporter.java:314)
	at java.util.Optional.ifPresent(Optional.java:159)
	at cucumber.runtime.formatter.SerenityReporter.handleTestStepStarted(SerenityReporter.java:313)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$3(SerenityReporter.java:129)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.api.TestStep.run(TestStep.java:79)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)`
```

Essentially, the previously mentioned method `clickOnSubmitButton(String submitButton) ` is not even reached. The program reads until the step before that

**Comment by TheGlobalist** [comment]
From what I saw in the debugger, it almost looks like that what he should analyze is the following.
Given the seeThat() content as 

`seeThat("SUPER TEST!",CanIHave.pageSource(source), equalTo(false))
`
He evaluates a Step Description which is something like "Then SUPER TEST is equal to false"

Should I try to remove the subject and have just 

`seeThat(CanIHave.pageSource(source), equalTo(false))
`
this would become "Then can i have is equal to false"

**Comment by globalworming** [comment]
this seems unrelated to the "anweredBy is not called" problen :)

**Comment by TheGlobalist** [comment]
> this seems unrelated to the "anweredBy is not called" problen :)

Why?
From what I’ve seen, this happens during the process in which, theoretically the answeredBy() method should be called

**Comment by globalworming** [comment]
it just seems weird to me how changes to the step description have any impact on `answeredBy` being called or not. 

https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay/src/main/java/net/serenitybdd/screenplay/QuestionConsequence.java#L47 is where `answeredBy` should be called. When you debug, is this code reached? if not, is `evaluateFor` reached?

**Comment by globalworming** [comment]
maybe create a small example project where i could reproduce the issue?

**Comment by TheGlobalist** [comment]
> it just seems weird to me how changes to the step description have any impact on `answeredBy` being called or not.
> 
> https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay/src/main/java/net/serenitybdd/screenplay/QuestionConsequence.java#L47 is where `answeredBy` should be called and this seems independant of the `subject` (though i am not sure if the `injectScenarioStepsInto` does anything weird). When you debug, is this code reached? if not, is `evaluateFor` reached?

I'm almost sure that I never got there with the debugging... I'll try to upload the project somewhere in the next days!

**Comment by TheGlobalist** [comment]
> maybe create a small example project where i could reproduce the issue?

I've uploaded the project here https://github.com/giulioP24/automationtesting

**Comment by globalworming** [comment]
... when i check out the CanIUse class it says `Class 'CanIHave' is never used`
what test should focus in the "small example project"?

**Comment by TheGlobalist** [comment]
Correct, because we had to remove it so that we could make the test work with Asserts.
Its usage is linked to the VisitaIspettivaCreazione.feature, step 

`    And the user click on the Salva_Ispettiva button
`

Essentially, we made the actor remember a variable that could indicate that he had compiled the form and, then, in the next step, he recalls the variable to see whether he needs to seeThat an error has occurred

**Comment by globalworming** [comment]
could you please boil the problem down to a minimal test which can be run easily. currently `mvn clean test` does nothing, running the `CucumberMain` results in "can't find browser because not windows" -.-
```
     java.lang.IllegalStateException: The driver executable does not exist: /home/wormi/Downloads/automationtesting-master/C:\Driver\chromedriver.exe
```

**Comment by TheGlobalist** [comment]
> Correct, because we had to remove it so that we could make the test work with Asserts.
> Its usage is linked to the VisitaIspettivaCreazione.feature, step
> 
> ` And the user click on the Salva_Ispettiva button`
> 
> Essentially, we made the actor remember a variable that could indicate that he had compiled the form and, then, in the next step, he recalls the variable to see whether he needs to seeThat an error has occurred



> could you please boil the problem down to a minimal test which can be run easily. currently `mvn clean test` does nothing, running the `CucumberMain` results in "can't find browser because not windows" -.-
> 
> ```
>      java.lang.IllegalStateException: The driver executable does not exist: /home/wormi/Downloads/automationtesting-master/C:\Driver\chromedriver.exe
> ```

Sorry, you're right!
Maybe the best option that I have is to adapt the program to read the driver in a certain folder of your system (like, /autom/drivers) as the problem I'm experiencing not always happen: some questions are correctly triggered, some no

**Comment by globalworming** [comment]
even then 
```
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - I/O-Fehler: The Network Adapter could not establish the connection

```

sorry, can't reproduce the issue with this project

**Comment by TheGlobalist** [comment]
> even then
> 
> ```
> org.sql2o.Sql2oException: Could not acquire a connection from DataSource - I/O-Fehler: The Network Adapter could not establish the connection
> ```
> 
> sorry, can't reproduce the issue with this project

Updated. Now should work :)
