### ISSUE TITLE
Is it possible to create fullpage screenshot instead of viewport of the specified area ?

### ISSUE THREAD

**Issue by daniilmatafonov** [serenity-bdd/serenity-core#1934]
I have configured `serenity.take.screenshots` property in `serenity.properties` file to set the frequency of taken screenshots. For my reports I expected to see a fullpage image. How can i configure it?

**Comment by wakaleo** [comment]
Not with Selenium

**Comment by globalworming** [comment]
oh, but it is, have a look at https://github.com/pazone/ashot
but it wont integrate very well with serenity 
you can create scrolling screenshots and add them as evidence

**Comment by daniilmatafonov** [comment]
@wakaleo ,
I found a conversation about using full size screenshots in Thucydides. Please, could you tell me if it's possible to add such functionality in the latest versions of Serenity Framework ?

**Comment by wakaleo** [comment]
Not currently.

**Comment by daniilmatafonov** [comment]
Ok. Is it possible to accept a pull request for this functionality in the future ?

**Comment by wakaleo** [comment]
Absolutely - it’s probably not a hard thing to do and the screenshot logic is quite localised.

**Comment by daniilmatafonov** [comment]
Hello, @wakaleo!

Please, check my PR when you have time.
https://github.com/serenity-bdd/serenity-core/pull/1975

**Comment by wakaleo** [comment]
Thanks! I will take a look tomorrow

**Comment by daniilmatafonov** [comment]
@wakaleo,
I'll close this issue because pr have been already merged.
