### ISSUE TITLE
Running Serenity Screenplay tests from CLI

### ISSUE THREAD

**Issue by TheGlobalist** [serenity-bdd/serenity-core#1937]
Having a project defined by the following main, is there a way to make it start from CLI by specifying the tests it should run?

```
`import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features = "src/test/resources/features/NuovoClienteCreazione.feature", format = {"pretty", "html:target/Destination"})
public class
CucumberMain {
}
`
```

**Comment by gizdolok** [comment]
I guess that can be achieved using cucumber tags

**Comment by TheGlobalist** [comment]
> I guess that can be achieved using cucumber tags

What's the difference between the two approaches? Ie, if I want to execute specific tests, would it be possible? Or should I dynamically add a special "execution" tag created by myself dynamically for executing?

**Comment by wakaleo** [comment]
You can run a specific JUnit test runner using the failsafe properties on the command line, but not a specific feature file or scenario. People generally use tags for this.

**Comment by TheGlobalist** [comment]
I've tried to issue the following command

mvn test -Dcucumber.filter.tags="@prova"

But the result was still the same: no tests executed, even though I've inserted it in a few .feature files

**Comment by wakaleo** [comment]
To filter with tags you need to use the cucumber.options parameter, eg

mvn verify -Dcucumber.options=“—tags @prova”

**Comment by TheGlobalist** [comment]
> To filter with tags you need to use the cucumber.options parameter, eg
> 
> mvn verify -Dcucumber.options=“—tags @prova”

This happens 
If I issue with just one -, the result is still the same
![Cattura](https://user-images.githubusercontent.com/19427963/73661833-0ec6b480-469b-11ea-9b23-8b9344e693ad.JPG)

**Comment by wakaleo** [comment]
Are you sure your surefire or failsafe plugins are configured correctly to run the runner class?

**Comment by TheGlobalist** [comment]
> Are you sure your surefire or failsafe plugins are configured correctly to run the runner class?

This is what I have right now
```

<configuration>
        <includes>
            <include>/steps/**/*Steps.java</include>
        </includes>
    </configuration>
```

**Comment by wakaleo** [comment]
You need to configure the maven-failsage-plugin to run your CucumberMain class - see http://maven.apache.org/surefire/maven-failsafe-plugin/

**Comment by TheGlobalist** [comment]
> You need to configure the maven-failsage-plugin to run your CucumberMain class - see http://maven.apache.org/surefire/maven-failsafe-plugin/

Thank you, I honestly didn't know about this!
Configuring Failsage made everything work.
Thank you so much!
