### ISSUE TITLE
@Screenshot annotation not working properly when trying to disable screenshots

### ISSUE THREAD

**Issue by djpasch** [serenity-bdd/serenity-core#1939]
Hi,

I used the serenity-cucumber4-starter project.
When i try to disable screenshots for a specific step it is still taking a screenshot.

Here's a snapshot of the code how i tried to disable screenshots:
    @Given("^(?:.*) is on the DuckDuckGo home page")
    @Screenshots(disabled = true)
    public void i_am_on_the_DuckDuckGo_home_page() {

It will only disable the screenshots for the sub steps.

Reason for doing this is, i want to extend my test using "SerenityRest" for some steps. As this is making an API call, it doesn not require a screenshot taken from the webdriver.

I'm using Gradle ("gradlew clean test -Pdriver=chrome")

Any suggestions, to what i'm doing wrong?

Kind regards,
Patrick

**Comment by wakaleo** [comment]
Serenity didn’t have much control over the Cucumber steps, so this annotation can only work for sub-steps.

**Comment by djpasch** [comment]
Hi Wakaleo,

Thanks for the quick response.

When i change the serentiy.properties for example by setting serenity.take.screenshots=FOR_FAILURES
or
serenity.take.screenshots=DISABLED
it does influence the way screenshots are taken, not only for the serenity Steps, but also for cucumber steps.

So somehow it should be possible...

**Comment by wakaleo** [comment]
Happy to consider a PR if you can find a way, but currently it is not possible to process annotations on the cucumber-annotated methods.

**Comment by djpasch** [comment]
I think something is going wrong when processing annotations.
Using for example "@BlurScreenshots(BlurLevel.HEAVY)" will only work for the first step.
Other steps using the same annotation are not blurred.

**Comment by wakaleo** [comment]
Maybe dig into the code and see what it is doing

**Comment by djpasch** [comment]
Sorry, but i don't know where to start digging. I was hoping you could help out.

**Comment by wakaleo** [comment]
I just took another look, and I can confirm that disabling screenshots on Cucumber (or JBehave) annotations will not be possible with the current Cucumber architecture.

**Comment by wakaleo** [comment]
I think this works in 2.2.9 - could you check?

**Comment by djpasch** [comment]
I tried to retest it, but I'm using serenity in combination with cucumber. As per my understanding that version is not yet compatible?

**Comment by wakaleo** [comment]
Disabling screenshots now works for Serenity with Cucumber.

**Comment by krishnapemmaraju** [comment]
@wakaleo -  I see screenshots are not capturing for each step and I see screenshots are getting duplicated for each step. Is there any way we can stop this
