### ISSUE TITLE
Strange symbols in console output broken failsafe/surefire xml reports

### ISSUE THREAD

**Issue by dip56** [serenity-bdd/serenity-core#194]
reproduced in serenity version 1.1.22-rc.7

output from xml:
```
<system-err>
...
18:19:15 ERROR Serenity - &amp#;[91m
...
--------------------------------------------------------------------------&amp#;[0m
...
</system-err>
```

error while parsing xml:
```
org.dom4j.DocumentException: Error on line 91 of document file:///tmp/test/target/failsafe-reports/TEST-test.Simple_Test.xml : The reference to entity "amp" must end with the ';' delimiter. Nested exception: The reference to entity "amp" must end with the ';' delimiter.
```

**Comment by YamStranger** [comment]
Hello @dip56.

Thanks for reporting this issue.

Do you run this build in windows?

**Comment by dip56** [comment]
Hi @YamStranger,

No, this build on linux ubuntu with locale ru_RU.UTF-8.
It works fine on version 1.1.22-rc.4

**Comment by YamStranger** [comment]
@dip56 Please post full stack trace. I downloaded xml with dom4j  and can not reproduce this issue. May be in stack trace I find lib that so angry for xmls.

**Comment by YamStranger** [comment]
@dip56 Also can you explain how you get this error. I mean workflow. Thanks!!

**Comment by dip56** [comment]
Hello @YamStranger,

I reproduced this bug in 1.1.22-rc.7. Yes, you were right. Problem caused by switch on colors in console log with maven failsafe plugin version 2.15

You can try run this project: https://github.com/dip56/serenity-custom-driver.git

```
mvn clean integration-test serenity:aggregate -Dit.test=net.thucydides.showcase.junit.features.cart.AddItemsToCartTest -Dwebdriver.driver=chrome
```
after that you should see report:
```
target/failsafe-reports/TEST-net.thucydides.showcase.junit.features.cart.AddItemsToCartTest.xml
```
w3c xml validating error:
```
XML Parsing Error: not well-formed
Location: http://www.w3schools.com/xml/xml_validator.asp
Line Number 81, Column 49:
[main] INFO net.serenitybdd.core.Serenity - &amp#;[96m
------------------------------------------------^
```

P.S. about error in dom4j library, this stack trace from jenkins junit reporter plugin =)

P.S.S. by the way in version 1.1.22-rc.8, I can't see console log information about steps with the same project settings:( only test started and test passed/failed...

**Comment by YamStranger** [comment]
@dip56 Thanks for provided example, it was very helpful. 

Yes, in rc.7 additional colors brake some xml parsing things. 
That's why they was turned off in rc.8 by default - and this issue will not reproduced for rc.8.

I thinks that this issue fixed, if you agree with me - please close it. 

About 
 > P.S.S. by the way in version 1.1.22-rc.8, I can't see console log information about steps with the same project settings:( only test started and test passed/failed...

if it is so critical for you and you need this info, and can not get all necessary info from reports - please create additional issue of it, and for sure we will help you )

Thanks!!!

**Comment by dip56** [comment]
> I thinks that this issue fixed, if you agree with me - please close it. 
ok. I agree, but if you will return this feature with colors in console, I need to create a new issue? =)

**Comment by YamStranger** [comment]
@dip56 Thanks. 

Now we have additional property for enabling these colors. And by default they turned off. 

You can reopen this issue, if same problem will return
