### ISSUE TITLE
Serenity didn't generate detailed reports with steps. Please help.

### ISSUE THREAD

**Issue by vaseemhussain** [serenity-bdd/serenity-core#1941]
![Capture](https://user-images.githubusercontent.com/59791193/73674249-1fe0e700-46d6-11ea-8ecb-9936d58cf423.PNG)

**Comment by wakaleo** [comment]
I can't do anything with this.

**Comment by wakaleo** [comment]
Unless you can provide a sample project or more details of what you are trying to do, I will have to close this issue.

**Comment by wakaleo** [comment]
Could you share the code of the test that generated this?
