### ISSUE TITLE
Chrome Mobile Emulation With Serenity

### ISSUE THREAD

**Issue by Dushyant0902** [serenity-bdd/serenity-core#1942]
I wanted to run the test in the mobile mode present in the chome web browser, it is called as mobile emulation. I have refered this link and using selenium java i have managed to do it. https://chromedriver.chromium.org/mobile-emulation
I need to do the same with Serenity.
Can anybody tell me what needs to be done ?

public class ChromeEmulation implements DriverSource {
	@Override
	public WebDriver newDriver() {
		Map<String, Object> deviceMetrics = new HashMap<>();
		deviceMetrics.put("width", 360);
		deviceMetrics.put("height", 640);
		deviceMetrics.put("pixelRatio", 3.0);

		Map<String, Object> mobileEmulation = new HashMap<>();
		mobileEmulation.put("deviceMetrics", deviceMetrics);
		mobileEmulation.put("userAgent", "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19");

		ChromeOptions chromeOptions = new ChromeOptions();
		chromeOptions.setExperimentalOption("mobileEmulation", mobileEmulation);
		System.setProperty("webdriver.chrome.driver", "./resources/chromedriver_76.exe");
		WebDriver d = new ChromeDriver(chromeOptions);
		return d;
	}
	
	@Override
	public boolean takesScreenshots() {
		return true;
	}

and properties added are - 
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.xyz.abcdweb.utility.ChromeEmulation
thucydides.driver.capabilities = mydriver

From searching the post I found the above implementation, but didnt worked, not sure why ? can you help ?e

**Comment by globalworming** [comment]
looks about right to me, like http://thucydides.info/docs/serenity-staging/#_custom_webdriver_implementations

what exactly is the error you are getting?

**Comment by Dushyant0902** [comment]
I have a test class where I am doing - 

public class SecureWebTest extends SerenityStories {
	public static WebDriver driver;

now what I am thinking is this driver will be set automatically using the newDriver method which is override.  This class will have all the @Steps and @Given, @When statements

and when I run the error is java.lang.NullPointerException.

It seems to me that the overrided method newDriver is not executing, I have added one comment to print on console, but it is not ruuning.

**Comment by wakaleo** [comment]
@Dushyant0902 the WebDriver field should never be static; in fact if you are using Serenity Action Classes or Page Objects, you should never need to declare a WebDriver instance anywhere.

Have you considered moving to Cucumber? There won't be much further development done for JBehave integration in Serenity/

**Comment by Dushyant0902** [comment]
@wakaleo thank you for taking out time and answering the questions. I will make the changes in my code. I will also try cucumber with serenity.

**Comment by globalworming** [comment]
can you try 
```
@Managed
public Webdriver driver
```

**Comment by Dushyant0902** [comment]
I tried that. seems to be working.

**Comment by globalworming** [comment]
xD :+1:
