### ISSUE TITLE
Serenity-JBehave report generation failed with java.nio.file.InvalidPathException: Illegal char <:> at index 2

### ISSUE THREAD

**Issue by YevgenShem** [serenity-bdd/serenity-core#1944]
On Windows, starting from serenity-core 2.1.2:  when generating Serenity report - the following error occurs:
_Failed to run story stories/consult_dictionary/LookupADefinition.story
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/SerenityBdd.issues/ReportGenerationIssue/serenity-jbehave/target/test-classes/stories_

How to reproduce:
1) generate Serenity-JBehave project using maven archetype
$ mvn archetype:generate -B -DarchetypeGroupId=net.serenity-bdd -DarchetypeArtifactId=serenity-jbehave-archetype -DarchetypeVersion=2.0.81 -DgroupId=org.test -DartifactId=serenity-jbehave
2) download chromedriver.exe from https://chromedriver.chromium.org/downloads and copy it into root dir
3) set in serenity.properties: "webdriver.driver=chrome"
4) in pom.xml, set "<serenity.version>2.1.4</serenity.version>"
5) run tests
$ mvn clean verify
6) look into console log

Please find the full console log attached
[maven_2.1.4.log](https://github.com/serenity-bdd/serenity-core/files/4154531/maven_2.1.4.log)

**Comment by wakaleo** [comment]
This appears to be Windows-specific so I can't reproduce it locally, but there is a possible fix in https://github.com/serenity-bdd/serenity-core/commit/64ba15c896efa7af5e4961212d04edcf96342fd5

**Comment by wakaleo** [comment]
Could you confirm if this works in version 2.1.6?

**Comment by YevgenShem** [comment]
Confirmed that it works on version 2.1.6, thank John!
