### ISSUE TITLE
Serenity report: non-web Steps have screenshots taken from previous web Steps

### ISSUE THREAD

**Issue by YevgenShem** [serenity-bdd/serenity-core#1946]
When a JBehave Scenario contains both web and non-web Steps - in the Serenity report, the non-web Steps obtained screenshots from the previos web-Step. Is it posible somehow to disable this screenshot attaching to non-web Steps? The "@Screenshots(disabled=true)" annotation does not help.

How to reproduce:

1) generate Serenity-JBehave project using maven archetype
_mvn archetype:generate -B -DarchetypeGroupId=net.serenity-bdd -DarchetypeArtifactId=serenity-jbehave-archetype -DarchetypeVersion=2.0.81 -DgroupId=org.test -DartifactId=serenity-jbehave_
2) download chromedriver.exe from https://chromedriver.chromium.org/downloads and copy it into root dir
3) set in serenity.properties: "webdriver.driver=chrome"
4) add to a Scenario several non-web steps (as it shown on attached screenshot)
5) run tests
_mvn clean verify_
6) open the generated Serenity report and go to the updated Scenario

As you can see, only the first non-web Step does not have attached screenshot; all the next non-UI steps have screenshots.

![AddingNonWebSteps](https://user-images.githubusercontent.com/22942682/73778598-246bd500-4794-11ea-9794-c685e77f0fe8.png)
![report](https://user-images.githubusercontent.com/22942682/73778608-26ce2f00-4794-11ea-8c2e-b7d48e0798dc.png)

**Comment by wakaleo** [comment]
This isn’t possible with JBehave.

**Comment by YevgenShem** [comment]
Thanks for the clarification.
