### ISSUE TITLE
PageObject instantiation question

### ISSUE THREAD

**Issue by bady2bro** [serenity-bdd/serenity-core#1949]
Hi,

So I have @Steps classes that have PageObject fields and as I understand they are instantiated at the same time as the @Steps classes.
The issue is that:
1. I have to add a proxy I create to the webdriver to catch network requests.
2. I have have access to the proxy after the test is over to parse the responses

Questions or solutions I though of:

1. Does anyone know if there is a way to override the driver of all the already instantiated PageObjects  at the same time?
2. Or is there a way to configure serenity properties so that I can create a BrowserMobProxy and have access to it afterwards? If yes, please give example or documentation, I lost days looking into this
3. Or is there a way to indicate that a method(class) should be run before serenity instantiates the @Steps

**Comment by wakaleo** [comment]
Have a look at the code in the serenity-browsermob-plugin module. You might be able to use or adapt this.

**Comment by bady2bro** [comment]
Do you mean the code here?
https://github.com/serenity-bdd/serenity-core/blob/master/serenity-browsermob-plugin/src/test/groovy/net/thucydides/browsermob/fixtureservices/WhenUsingABrowsermobService.groovy

**Comment by wakaleo** [comment]
Yes, the whole module on fact

**Comment by bady2bro** [comment]
I also looked at those and while I sort of get how it works, locally there, I don't know how to integrate it in the serenity driver instantiation, or if I should do it even.
For example:
When should I use the "BrowserMobFixtureService" class and it's methods so it will be attached to the webdriver that is created by the serenity framework based on the serenity.properties file?
https://github.com/serenity-bdd/serenity-core/blob/master/serenity-browsermob-plugin/src/main/java/net/thucydides/browsermob/fixtureservices/BrowserMobFixtureService.java

**Comment by wakaleo** [comment]
If you use the BrowserMobFixtureService class you shouldn't need to create your own driver instance.
