### ISSUE TITLE
Steps are not shown in reports when nested step classes are instantiated using custom constructors

### ISSUE THREAD

**Issue by alexanderkranga** [serenity-bdd/serenity-core#1952]
Hi,

Here is a sample test class to reproduce this issue:
```
@RunWith(SerenityRunner.class)
public class SampleTest {

    @Steps
    private CustomSteps customSteps;

    @Test
    public void ctaTest() {
        customSteps.openSite();
        customSteps.getNestedSteps().doSomething();
    }
}
```
The `CustomSteps` class:

```
public class CustomSteps {

    @Steps
    private NestedSteps nestedSteps;

    public CustomSteps() {
        this.nestedSteps = new NestedSteps("custom param");
    }

    @Step("Open serenity site")
    public void openSite() {
        getDriver().get("http://thucydides.info/docs/serenity-staging/");
    }

    public NestedSteps getNestedSteps() {
        return nestedSteps;
    }
}
```
And `NestedSteps` class:

```
public class NestedSteps {

    private String customParam;

    public NestedSteps() {}

    public NestedSteps(String customParam) {
        this.customParam = customParam;
    }

    @Step("This step is not shown in report")
    public void doSomething() {
        Assert.assertTrue("Some assertion", true);
    }

}
```

When running this simple test using configuration above, the only step that is being shown in report is `openSite()`, whereas `doSomething()` step from `NestedSteps` class is not.
When removing this constructor:
```
public CustomSteps() {
    this.nestedSteps = new NestedSteps("custom param");
}
```
all two steps are shown correctly.

I know that Serenity should instantiate step classes by itself, but in my case I need to configure steps based on our project requirements. Looks like Serenity is not looking at step methods in already instantiated classes when generating reports. Can someone please take a look at this or let me know how can I achieve required behavior?

I am using `2.0.82` version of Serenity

**Comment by wakaleo** [comment]
This is expected behaviour. If you want to instantiate your own Step classes, you need to use the `Instrumented` class, e.g. `Instrumented.instanceOf(NestedSteps.class).withProperties("custom param")`

**Comment by alexanderkranga** [comment]
Thanks for your quick reply, I was able to fix it!
