### ISSUE TITLE
Serenity Restart Browser Not As Expected

### ISSUE THREAD

**Issue by billyjulius** [serenity-bdd/serenity-core#1954]
Hi, I'm currently have 2 separate `.feature`, and in `serenity.properties` I already set `serenity.restart.for.each = feature` as per in https://serenity-bdd.github.io/theserenitybook/latest/cucumber.html. 

Let's say : 
```
file1.feature --- Scenario A
file2.feature --- Scenario B, Scenario C
```

But when I run `mvn verify`, 

1. scenario A run - finish - close browser
2. scenario B run - finish - close browser
3. scenario C run - finish - close browser

As far I understand, the expected result should be:
1. scenario A run - finish - close browser
2. scenario B run - finish - browser not closed
3. scenario C run - finish - close browser

When scenario B run finished, it should not closing the browser because I set it to restart browser for each FEATURE, as scenario B and scenario C is within same `.feature` file it should using same browser meaning after scenario B finish it won't closing the browser

Is this bug? Or maybe I'm misunderstood this behaviour?

```
<serenity.core.version>2.1.4</serenity.core.version>
<serenity.cucumber4.version>2.1.2</serenity.cucumber4.version>
<cucumber.version>4.8.0</cucumber.version>
```

Edit:
I also tried with `serenity.restart.browser.for.each=feature` and the result: 
1. scenario A run - finish - browser not closed
2. scenario B run - finish - browser not closed
3. scenario C run - finish - browser not closed
As it should be closed when scenario A run finished

**Comment by wakaleo** [comment]
No, this generally works well. Could you provide a sample project?

**Comment by billyjulius** [comment]
Thanks for the reply,

Here is my sample project with same case above
[learning-serenity.zip](https://github.com/serenity-bdd/serenity-core/files/4191923/learning-serenity.zip)

**Comment by billyjulius** [comment]
Hello @wakaleo, is there any updates regarding this issue?

**Comment by wakaleo** [comment]
It's on the backlog - if it is important for your work and you need a quick response, you can opt for one of our commercial support packages (see https://johnfergusonsmart.com/serenity-bdd-mentoring/#support).
