### ISSUE TITLE
Handle Select Certificate popup 

### ISSUE THREAD

**Issue by Krithikmano** [serenity-bdd/serenity-core#1955]
When I open the application URL using chrome, i am getting the below certificate pop up.  How to handle this pop up. Is any specific attribute needs to be added  in "chrome.switches"
![certificate Popup](https://user-images.githubusercontent.com/28629290/74597059-074dc680-501e-11ea-8712-76a920bd354f.jpg)

**Comment by wakaleo** [comment]
I'm not aware of any chrome options for this. See https://github.com/SeleniumHQ/selenium/issues/5408 and https://github.com/puppeteer/puppeteer/issues/540 for some possible approaches.
