### ISSUE TITLE
Having @Managed WebDriver causes double RemoteWebDriver

### ISSUE THREAD

**Issue by jvsanten** [serenity-bdd/serenity-core#1957]
When using @Managed to (for example) maximize the browser window one browser gets opened and maximized by the @Managed WebDriver, while another gets opened with the actual page in it, but this only happens when using a RemoteWebDriver.

I've attached a zip file with a small project which reproduces the issue. The issue seems to be around starting from serenity 2.0.49 (have run the example project with various versions, 2.0.48 and before seems fine, 2.0.49 and up shows the issue.)

(Only getting around to reporting now because @Managed isn't used very often and the main 'problem' is extra selenium-grid instances being claimed, not really a big issue unless our grid is at full capacity.)

The properties I'm using to test (with chromedriver started manually from the commandline):

> webdriver.driver=remote
> webdriver.remote.driver=chrome
> webdriver.remote.url=http://localhost:9515

I've also used:
> webdriver.driver=chrome
> webdriver.remote.url=http://localhost:9515

I've managed to chase things down a bit to SerenityWebdriverManager and WebdriverInstances but can't find the root of the problem in order to propose a fix.

With both sets of properties the WebDriver  controlled by @Managed ends up in the WebdriverInstances driverMap with the key "remote:driver". The one used by the PageObject has either "remote" or "chrome" as its key, depending on the value of webdriver.driver in properties.

[serenity-double-browser-test.zip](https://github.com/serenity-bdd/serenity-core/files/4213249/serenity-double-browser-test.zip)

**Comment by wakaleo** [comment]
Have you tried with the latest versions

**Comment by jvsanten** [comment]
> Have you tried with the latest versions

The example project is using 2.1.6 - I specified the 2.0.49 because that's the first one I saw the failure on while working back (should probably have specified newest as well as first).

**Comment by wakaleo** [comment]
Ok, thanks for the sample project

**Comment by jvsanten** [comment]
Managed to get some more debugging done. The "remote:driver" name seems to come from RequestedDrivers line 45. I've tried just taking out the first "if" in the requestedDriverFor method, which does fix my problem, but seems a bit too 'blunt instrument' to be the actual fix.

![image](https://user-images.githubusercontent.com/22679938/74829557-935b3900-5311-11ea-88a8-68bd1fe2fc10.png)

**Comment by wakaleo** [comment]
Could you see if this is fixed in 2.2.9?

**Comment by jvsanten** [comment]
> Could you see if this is fixed in 2.2.9?

It's fixed, many thanks!
