### ISSUE TITLE
hub capability is not discovered in the list of supported by w3c or Appium

### ISSUE THREAD

**Issue by dagiguevara** [serenity-bdd/serenity-core#1959]
I faced this issue before, but for some reason after the last release I'm getting the issue again

**Comment by a-en** [comment]
@dagiguevara , is that just a warning in logs or something is not working as expected? That message was introduced in scope of [this issue](https://github.com/serenity-bdd/serenity-core/issues/1812).
Processing additional capabilities is disabled by default, so I wonder what issue you are facing and what is the impact.
