### ISSUE TITLE
File Upload issue

### ISSUE THREAD

**Issue by mansiKulkarni39** [serenity-bdd/serenity-core#1960]
Hi,
I am using **upload(fileName).to(uploadFileButton)** to upload the file. Also I am passing fileName as "src\\test\\resources\\TestUpload\\HeroListToUpload.csv" and correct element of uploadFileButton(verified by using onclick, it is opening window's pop up).
But I am getting "net.thucydides.core.pages.components.FileToUploadCouldNotBeFoundException: File not found: /Users/abc/eclipse-workspace/OProject/Open/src\test\resources\TestUpload\HeroListToUpload.csv"

I have tried many things but it is not working. 

Below are versions I used in pom.xml
<serenity.version>2.0.90</serenity.version>
<serenity.maven.version>2.0.90</serenity.maven.version>
<serenity.cucumber.version>1.9.50</serenity.cucumber.version>

Please let me know.
**Note**: I haven't use screenplay in my project so for consistency not using it for upload file too.

**Comment by wakaleo** [comment]
`FileToUploadCouldNotBeFoundException` means what it says: it can't find a file with that path. Try with forward-slashes "/" and make sure the file does inded exist.

**Comment by mansiKulkarni39** [comment]
Even after changing to "/" it is not working, it is giving error as "org.openqa.selenium.ElementNotInteractableException: element not interactable". But I am able to do just click on same element which I used for upload.

**Comment by wakaleo** [comment]
That's a Selenium issue - the element is not interactable. Your locator might not be locating the element you think it is.
