### ISSUE TITLE
Serenity takes screenshot for rest steps

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1963]
I have some tasks that are only rest calls in my tests, I set up the ScreenShot annotation to be disabled on those tasks but I still get the screenshot in the report, could u guide me where in code can I see in order to make a fix.

**Comment by wakaleo** [comment]
Sure, let me track it down. Are you using Screenplay or just step libraries?

**Comment by ricardorlg** [comment]
screenplay

**Comment by wakaleo** [comment]
From memory it’s analysing the stack trace that makes this tricky - I’ll check

**Comment by wakaleo** [comment]
The place to start would be the `ScreenshotPermission` class. Also see then`shouldTakeScreenshot()` method in `BaseStepListener` and the `Photographer` class.

**Comment by ricardorlg** [comment]
You are a monster, I will test it, but again u are the best.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by wakaleo** [comment]
Please experiment with it - I've done some tests on the most common use cases, and it seems to work OK, but it could do with some in-depth exploratory testing. Have a look at the committed code to see how it works - it basically traverses the stack trace looking for `performAs()` methods and figures that the associated object must be a performable, so looks at those objects for annotations and interfaces.

**Comment by ricardorlg** [comment]
Yeah I will test it a lot as far as I can see It just validates at the end of the tree of the performance. I will try it and let u know.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by wakaleo** [comment]
It should climb the tree (that’s the intent at least)
