### ISSUE TITLE
Serenity version 2.1.6 doesn't capture failed count in report

### ISSUE THREAD

**Issue by shbtechno** [serenity-bdd/serenity-core#1964]
Hi,
I am using serenity version 2.1.6, I see the logs have Failure count for one of the failed scenario, but the failure count in report is 0 and test covering is 100% passed with all tests counted as passed.

**Comment by wakaleo** [comment]
I can’t reproduce this - can you provide a sample project and an example of the output you are seeing?

**Comment by shbtechno** [comment]
An example of the output. 100% coverage passed though having test failures, same is there for summary report. I am not able reproduce the issue in a fresh new project and couldn't find the difference in projects

<img width="916" alt="image2" src="https://user-images.githubusercontent.com/60326006/75100745-ec54f680-55c9-11ea-8377-4946602046a3.png">

<img width="919" alt="image3" src="https://user-images.githubusercontent.com/60326006/75100742-dd6e4400-55c9-11ea-9298-76560dc21917.png">

**Comment by wakaleo** [comment]
So you are saying you cannot reproduce the issue?

**Comment by wakaleo** [comment]
Could you see if this happens with version 2.1.7?

**Comment by shbtechno** [comment]
> So you are saying you cannot reproduce the issue?

I did tried with new version 2.1.7 as well, the strange thing is it works perfectly fine in one workspace which I created newly, but the workspace where I upgraded the serenity version to latest I started facing this issue.

**Comment by wakaleo** [comment]
Without a project that reproduces the issue it sound's like a project or environment-specific issue. Happy to provide more project-specific support at part of one of our support packages if required (https://johnfergusonsmart.com/serenity-bdd-mentoring/#support)

**Comment by nambikaas** [comment]
Able to fix this issue when used Serenity version 2.1.7... also the failing count were not part of the report because one of my steplibrary class were instantiated instead of just declaring which caused response validator library class/particular step to be not part of the serenity report ,which also made my report too look 100% passed inspite of the failures 
. Eg : instead of declaring step library like below @Steps
	Validator validator; , i had previously instantiated it as @Steps
	Validator validator = new Validator(); <which is fine with some serenity versions but inlatest version this is not acceptable & class doesnt get part of serenity reports,thats why failing count was not counted>

**Comment by wakaleo** [comment]
Thanks for your feedback @nambikaas
