### ISSUE TITLE
How do we manage test data based on environment

### ISSUE THREAD

**Issue by shbtechno** [serenity-bdd/serenity-core#1965]
Hi,

I am trying to use serenity.conf to locate the test directory based on the environment, and when using  @UseTestDataFrom("$DATADIR/xyz.csv") annotation I am getting error no file found at "$DATADIR/xyz.csv".

 How do we manage the test data based on the different environment like the base urls are managed using serenity.conf

**Comment by wakaleo** [comment]
You can use the variables HOME, USERDIR, APPDATA and DATADIR. DATADIR is defined in the Serenity property `serenity.data.dir`. Environment-specific variables (using serenity.data.dir in an environment-specific block) will be supported in an upcoming release.

**Comment by shbtechno** [comment]
Thanks for your response, do we have an example  for the usage of these variables to refer and implement please.

**Comment by shbtechno** [comment]
I have tried using this new feature but was unsuccesful, can you assist here

https://github.com/serenity-bdd/serenity-core/commit/f60ce51cb44fe9fc72fd419891eed3337b54c58f#commitcomment-37454871

**Comment by dianacarmen** [comment]
I have the same issue, I can't wait Serenity to support this.
