### ISSUE TITLE
How to use Cucumber with ParameterizedRunner class in Serenity rest assured

### ISSUE THREAD

**Issue by nambikaas** [serenity-bdd/serenity-core#1967]

**Comment by wakaleo** [comment]
They are two separate runners; for parameterised tests in Cucumber you would use example tables

**Comment by nambikaas** [comment]
can we use SerenityParametrizedRunner class with Cucumber BDD ..is there
any example available for that?

**Comment by wakaleo** [comment]
No, this is not possible.

**Comment by shbtechno** [comment]
I also have the same query : how do we externalise test data in cucumber rather than using in examples/tables in feature file?

**Comment by wakaleo** [comment]
Cucumber does not support externalised data tables by design (Cucumber is not a test scripting tool)
