### ISSUE TITLE
Inkonsistent rendering of readme.md in HTML report

### ISSUE THREAD

**Issue by laberning** [serenity-bdd/serenity-core#1968]
I'm currently trying to add a markdown-description to the overview "Requirements" page of the HTML-report.

I noticed that the markdown is rendered differently depending on the directory:

src/test/resources/features/somefeature/readme.md:
- everything looks as expected

src/test/resources/features/readme.md:
- UTF-8 encoding is ignored (i.e. öäü characters are broken)
- Markdown-tables are rendered differently without borders and spacing

**Comment by wakaleo** [comment]
Could you provide a simple sample project?

**Comment by wakaleo** [comment]
Could you try with 2.1.7? I couldn't reproduce the issue with UTF-8 encoding though.

**Comment by laberning** [comment]
Thanks for digging into this. I placed a sample project to reproduce the issue here: 
https://github.com/laberning/serenity-core-issue-1968

Interestingly the issue with the corrupted letters only happens when running maven on a windows machine. If I run the same sample project on mac all letters look good.

Unfortunately I could not find the specified version 2.1.7, do you have a link on that one so I can try it?

**Comment by wakaleo** [comment]
Appears to work in 2.1.7:
```
        <serenity.version>2.1.7</serenity.version>
        <serenity.maven.version>2.1.7</serenity.maven.version>
        <serenity.cucumber4.version>2.1.2</serenity.cucumber4.version>
```

![image](https://user-images.githubusercontent.com/55986/75117515-f9292700-5669-11ea-86f4-6c4ff1100d26.png)

**Comment by laberning** [comment]
Thanks for the new version, the markdown-tables now work in both sections.

However it seems that the encoding problem on the "Requirements"-page still exists. For me that only happens on Windows 10 and if I store that one markdown file with ISO encoding, then everything looks good. Somehow it seems that the markdown renderer does not pick up the file encoding for that particular file and falls back to a system default encoding.

Just noticed another difference: The "Requirements"-page renders the title "A table" while that one is missing on the "Capabilities"-page.

![requirements_page](https://user-images.githubusercontent.com/151194/75136230-4a75fc80-56e4-11ea-81eb-2b6f1c9b1d93.png)
![capabilities_page](https://user-images.githubusercontent.com/151194/75136229-49dd6600-56e4-11ea-86b3-d04d957b0bc0.png)

**Comment by wakaleo** [comment]
You will probably need to play with the freemarker templates on your side to fix this as I am unable to reproduce it here (I don't use Windows).

**Comment by laberning** [comment]
Totally understood. My guess is, that the encoding problem happens while loading the files.

Most Narrative Pages are loaded here with a file encoding declared.

https://github.com/serenity-bdd/serenity-core/blob/21eb2417f7ec31a102bc20ff6fb596f649838d7c/serenity-model/src/main/java/net/thucydides/core/requirements/model/LoadedNarrative.java#L18

But the overview-page is loaded here:

https://github.com/serenity-bdd/serenity-core/blob/21eb2417f7ec31a102bc20ff6fb596f649838d7c/serenity-model/src/main/java/net/thucydides/core/requirements/model/OverviewReader.java#L21

The Conversion to string does not set an encoding, so it falls back to the default character encoding of the VM (ISO-8859 on windows). A fast fix could be to set the file encoding while initializing the string `new String(..., "UTF-8");`
