### ISSUE TITLE
Adding extra test results into the aggregated report

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#1973]
Hi, 

Assuming I have executed a single test-case individually, and have copied out the results comprising the following files:
1) SERENITY-JUNIT-123abc.xml
2) 123abc_screenshots.html
3) 123abc.html
4) Along with the entire collection of .png screenshots for that test-case

If I were to paste these files into another target/site/serenity directory which has already executed other test-cases, and then run a `mvn serenity:aggregate`, I am expecting to see this newly added test-case as an entry in the newly aggregated report. However, I am unable to do so.

Am I missing any files which I need to add as well?

**Comment by wakaleo** [comment]
What version are you using? We haven't used XML to store test results for quite some time. It's the JSON files you will need (as well as screenshots etc) for the aggregation. The HTML ones are not needed, and the JUNIT ones are only useful for Jenkins reporting.

**Comment by timothyjmtan** [comment]
A really old version of 1.9.36 :-) We'll be upgrading to version 2+ in the near future...
Got it, thanks!!
