### ISSUE TITLE
Serenity Assertions not accepting links <a> tag

### ISSUE THREAD

**Issue by DilipKumar1412** [serenity-bdd/serenity-core#1977]
Hi @wakaleo,

I want to display hyperlink in the Assertion message, but it is displaying anchor tag as string in the HTML report.

![image](https://user-images.githubusercontent.com/61414460/75654549-f93aaf80-5c85-11ea-9119-b0e86bdff74c.png)

Expected result should be Screenshot : [2020-03-02T_12_45_58_612Z.png](/)

Is there any workaround to achieve this?

Thanks

**Comment by wakaleo** [comment]
Not currently.
