### ISSUE TITLE
Show test ignore reason in HTML report?

### ISSUE THREAD

**Issue by alexanderkranga** [serenity-bdd/serenity-core#1979]
Hi,

I have some tests marked as ignored with reason using `@Ignored("Reason")`. Is there a way to show the `Reason` in serenity html report? Currently, ignored tests are just grayed out, but would be nice to see the reason in report.

Thanks!

**Comment by wakaleo** [comment]
Yeah, this isn’t supported yet, but it would be nice.

**Comment by alexanderkranga** [comment]
Can this be considered as a feature for some future release? This would definitely help to bring awareness to ignored tests.

**Comment by wakaleo** [comment]
Sure, and you can even propose a Pull Request if you want to see it implemented sooner rather than later!
