### ISSUE TITLE
Cannot generate index.html automatically

### ISSUE THREAD

**Issue by rvolokhov** [serenity-bdd/serenity-core#1980]
Hello!
Serenity report cant be generated automatically. The only way for me to generate it is to execute maven goal manually. I have the goal in pom.xml but it doesnt work. The project that I work on is very simple, I downloaded it in order to learn Serenity.

"aggregate" goal has already been in the project, so I think it worked for the person who created it. Also, Ive read similar issues and didnt find solution.

Here is the pom.xml:
`<dependencies>
    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-screenplay-rest</artifactId>
      <version>${serenity.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-junit</artifactId>
      <version>${serenity.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  
    <build>
      <plugins>
          <plugin>
              <groupId>net.serenity-bdd.maven.plugins</groupId>
              <artifactId>serenity-maven-plugin</artifactId>
              <version>${serenity.version}</version>
              <executions>
                  <execution>
                      <id>serenity-reports</id>
                      <phase>post-integration-test</phase>
                      <goals>
                          <goal>aggregate</goal>
                      </goals>
                  </execution>
              </executions>
              <dependencies>
                  <dependency>
                      <groupId>net.serenity-bdd</groupId>
                      <artifactId>serenity-core</artifactId>
                      <version>${serenity.version}</version>
                  </dependency>
              </dependencies>
          </plugin>
        <plugin>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>2.20</version>
          <executions>
              <execution>
                  <goals>
                      <goal>integration-test</goal>
                       <goal>verify</goal>
                  </goals>
              </execution>
          </executions>
        </plugin>
      </plugins>
    </build>`

Also, /target/site/serenity folder is being generating, and a lot of files in it, but there's no index.html
Any help is appreciated, thanks!

**Comment by wakaleo** [comment]
The index.html file is not generated when you run individual tests; only when you run the aggregate goal. Does the index.html file get generated when you run the aggregate goal or mvn verify?

**Comment by rvolokhov** [comment]
Yes, when I run aggregate goal it get generated. I'd like to get the same but automatically. Is there any way to do this?
Ps. Sorry, can't paste pom.xml properly...

**Comment by wakaleo** [comment]
No, this is normal behaviour - if you want the result of an individual test, just look for the most recent html file in the target/site/serenity directory.

**Comment by rvolokhov** [comment]
Yeah, but I have to do it manually, I mean to write this command "mvn serenity:aggregate" everytime I need report. Is there possibility to build report automatically everytime after I run my tests?

**Comment by wakaleo** [comment]
No

**Comment by rvolokhov** [comment]
Got it. Thanks for the answers!
