### ISSUE TITLE
Serenity Cucumber, Saving List of Strings into variables in Step Definitions.

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-core#1981]
Hi,

We are currently setting up a new BDD framework with Serenity and Cucumber and one of the requirements is that you can save Lists of Strings in a variable declared in a Step Definition. 

For example:
in StepDefclass: @**Then**("Save List of Id's into $listOfID"); (using the $ of Jbehave as an example only)
in feature file: **Then** Save List of Id's into **LIST_OF_ID** ("LIST_OF_ID" being the variable that receives the list)
**and use the saved list like this**
**Then** Verify is if **LIST_OF_ID** is complete.

What are our options to achieve this? Any help would be appreciated. Thanks.

**Comment by wakaleo** [comment]
In Cucumber lists are represented as a table with a single column (or you could just pass a string and convert it yourself).

**Comment by edricklacbayo** [comment]
Hi Mr. Ferguson, Thank for answering. I'll read more about Cucumber Lists as a single table. Can you recommend me some links so I can read them? Thank you.
