### ISSUE TITLE
@Screenshots annotation doesn't work for @Step method

### ISSUE THREAD

**Issue by daniilmatafonov** [serenity-bdd/serenity-core#1982]
I can't use annotation @Screenshots for @Step methods with value **disabled** to override logic of creating screenshots in my UI test.

In my steps class I have written the following step method.

`@Step("Turn back on previous page. Skin: {0}")
@Screenshots(disabled = true)
public void turnBackOnPreviousPage(String skin){
       onPreLivePage().turnOnPreviousPage();
}`

But in logs I see that screenshot have been taken. I use Serenity Framework with version 2.1.8.

**DEBUG [main] (StepInterceptor.java:438) - STARTING STEP: PreLivePageStoryTest.topLeaguesCoupons - Turn back on previous page. Skin: {0}
 INFO [main] (CommonPage.java:67) - waiting for timeout: 10
DEBUG [main] (StackTraceAnalyser.java:37) - Couldn't find class during Stack analysis: org.apache.maven.surefire.junit4.JUnit4Provider
DEBUG [main] (StackTraceAnalyser.java:37) - Couldn't find class during Stack analysis: org.apache.maven.surefire.junit4.JUnit4Provider
DEBUG [main] (StackTraceAnalyser.java:37) - Couldn't find class during Stack analysis: org.apache.maven.surefire.junit4.JUnit4Provider
DEBUG [main] (StackTraceAnalyser.java:37) - Couldn't find class during Stack analysis: org.apache.maven.surefire.junit4.JUnit4Provider
DEBUG [main] (StackTraceAnalyser.java:37) - Couldn't find class during Stack analysis: org.apache.maven.surefire.junit4.JUnit4Provider
DEBUG [main] (StackTraceAnalyser.java:37) - Couldn't find class during Stack analysis: org.apache.maven.surefire.junit4.JUnit4Provider
DEBUG [main] (Darkroom.java:99) - Send negative for processing for target\site\serenity\31ad32de6e1e4e5148fb817fea5a896c1b792e59e67247798fc4d819da94de5d.png
DEBUG [main] (StepInterceptor.java:442) - STEP DONE: Turn back on previous page. Skin: {0}**

How it can be fixed ?

**Comment by wakaleo** [comment]
Does the screenshot appear in the reports? The Darkroom operates on a different thread so may not correspond to the step mentioned.

**Comment by daniilmatafonov** [comment]
@wakaleo,
Yes, the screenshot is saved on the file system and displayed in the report.

![image](https://user-images.githubusercontent.com/4964768/76147297-e5d77c00-60ab-11ea-92f3-c251625b68a2.png)

**Comment by ricardorlg-aval** [comment]
@wakaleo It looks like the problem is due to StackTraceAnalyser not able to load step methods because from stacktrace they comes with netBuddy process, I think the best option is to add a logic in the methodOverride method to also check the current step if it has the `@Step` annotation. If u want I can take this.

**Comment by wakaleo** [comment]
Sound's like a plan, thanks Ricardo
