### ISSUE TITLE
Serenity Core Issue with InputStream?

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-core#1983]
I am setting up a new Framework which uses v.1.9.50 of Serenity Cucumer and v.2.0.91 of Serenity and Serenity Maven. I having a problem with FileInputStream not getting the Path of the File.
![image](https://user-images.githubusercontent.com/28752767/76061114-d11cba80-5fbd-11ea-8ee2-76805db774ed.png)
Code:
![image](https://user-images.githubusercontent.com/28752767/76061174-ea256b80-5fbd-11ea-9c4a-6351059ddae3.png)

But in our Jbehave Serenity Framework which uses v.1.8.21 of Serenity. The code works well

Is it because of version compatibility issues?

**Comment by wakaleo** [comment]
It looks like either a version conflict or a problem with your maven repository (corrupted files?)

**Comment by wakaleo** [comment]
Closed for lack of activity.
