### ISSUE TITLE
Possible incompatibility ChromeDriver/Selenium - Could not instantiate class org.openqa.selenium.chrome.ChromeDriver

### ISSUE THREAD

**Issue by andreea-s07** [serenity-bdd/serenity-core#1984]
I am using Serenity version 2.1.4 with Cucumber 4.8.0.
Last week I updated ChromeDriver version to 80.0.3987.106 and the tests executed successfully.
Everytime I tried executing tests in the past few days, I received the error net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver.

I have already tried updating dependencies versions and the behavior remained unchanged. Also, other colleagues are experiencing the same issue.

**Comment by wakaleo** [comment]
You need to update the chromedriver binary

**Comment by andreea-speriatu** [comment]
I updated it again today - same results.

**Comment by wakaleo** [comment]
This is unrelated to the Serenity code or the selenium version (do not change these). Make sure the chromedriver binary is compatible with the Chrome version (each version needs a different binary).

**Comment by andreea-s07** [comment]
ChromeDriver binary and Chrome browser have the same version - 80.0.3987.106.

**Comment by wakaleo** [comment]
What is the exact error message and log output?

**Comment by andreea-s07** [comment]
For another colleague using Ubuntu everything is working fine. It seems like a Windows issue.

[DriverConfigurationError.txt](https://github.com/serenity-bdd/serenity-core/files/4298385/DriverConfigurationError.txt)

**Comment by wakaleo** [comment]
That looks like a chromedriver error; you should ask the chromedriver team (there is nothing the Serenity or WebDriver code can do at this level).

**Comment by andreea-s07** [comment]
I was thinking that it might be something from Serenity since a project without Serenity works fine.

**Comment by wakaleo** [comment]
I can't reproduce it but feel free to dig into the Serenity code and see if you can see anything that could be done differently.

**Comment by wakaleo** [comment]
Closed for lack of activity.

**Comment by krishnapemmaraju** [comment]
@wakaleo - I am running serenity scripts from linux and it failing with below error

Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

But same this is working fine in windows 
could you please help

**Comment by JoseMariaSardoR** [comment]
> For another colleague using Ubuntu everything is working fine. It seems like a Windows issue.
> 
> [DriverConfigurationError.txt](https://github.com/serenity-bdd/serenity-core/files/4298385/DriverConfigurationError.txt)

Hi @andreea-s07  i would like ask you how did you solve the issue because i'm having the same problem and i can´t figure it out!! thanks in advance!!

**Comment by andreea-s07** [comment]
> > For another colleague using Ubuntu everything is working fine. It seems like a Windows issue.
> > [DriverConfigurationError.txt](https://github.com/serenity-bdd/serenity-core/files/4298385/DriverConfigurationError.txt)
> 
> Hi @andreea-s07 i would like ask you how did you solve the issue because i'm having the same problem and i can´t figure it out!! thanks in advance!!

Hi! If I remember correctly, it was a matter of incompability between Chrome, chromedriver and Serenity versions. Unfortunately, I am no longer doing automation testing, so I don’t have a recent matrix of compatibility… :(
