### ISSUE TITLE
Serenity generating incorrect report used latest version 2.1.8. 

### ISSUE THREAD

**Issue by shbtechno** [serenity-bdd/serenity-core#1985]
Hi Team,
I am getting report as 100% pass even though there are test failures, the coverage is 100% pass in all sections epic,feature,story, etc though test is failed.

I have managed to recreate the issue for test coverage showing 100% pass even though there are failures. 

Kindly please help to get this resolved,

Following information and observations:
1. To recreate run only specific test using mvn verify -Denvironment="dev" -Dtags="ms:weather"
**2. Failure in test coverage is 100% pass**
![image](https://user-images.githubusercontent.com/60326006/76152862-833aac00-60bc-11ea-82a2-2c20088c59b6.png)
![image](https://user-images.githubusercontent.com/60326006/76152869-964d7c00-60bc-11ea-8135-2e49c0cd0f47.png)

Sample project attached for the same.
[SerenityBDDTest (2).zip](https://github.com/serenity-bdd/serenity-core/files/4302555/SerenityBDDTest.2.zip)

**Comment by wakaleo** [comment]
Thanks for reproducing this issue. I won't be able to look at it any time soon, but it looks like the test result summary page is not correctly interpreting the test outcome produced by the Parameterised tests. I'm not sure why, but the datatable element in the attached file is showing as successful, whereas it should be failed. So if you want to take a closer look, you could start with the `net.thucydides.core.model.DataTable` class and see how it is being updated during the test execution.

[04cd21fa8e99bacc1071538fe145c8c6afe11cd79101cc870f84272c1184aa4f.json.txt](https://github.com/serenity-bdd/serenity-core/files/4302572/04cd21fa8e99bacc1071538fe145c8c6afe11cd79101cc870f84272c1184aa4f.json.txt)
l

**Comment by shbtechno** [comment]
@wakaleo  Yes, I tried with simple SerenityRunner rather than parameterised it works fine with test results as expected, couldn't find the exact issue. Also noted this issue is specific to only SerenityRest/Restassured testing, the ui testing with parameterisation is working fine with regards to reporting.
Is there any previous version I should move back so it can help me to move forward at the moment?

**Comment by shbtechno** [comment]
Hi Team @wakaleo 

Can you please assist with this issue.. Appreciate your help here

**Comment by wakaleo** [comment]
Have you tried with the latest Cucumber 4 version?

**Comment by shbtechno** [comment]
Hi,
I am not using cucumber as more interested to use serenityparameterized to externalise test data in csv.

**Comment by shbtechno** [comment]
Hi Team @wakaleo ,
I tried to reproducing the issue using the serenity junit starter provided, followed below steps
1. Upgraded to latest serenity version 2.2.0
2. Added RestAssured test for passed and failed in same sample test file

I am getting same incorrect report issues where failed tests with serenityRest are being counted in passed count.
Second thing I tried using only RestAssured rather than SerenityRest, the test counts are coming correct for failed as well but when clicked on failed count from summary report page, it doesn't show any data for failed test.

Can you please assist with this fix or guide me if something is done wrong here, as this is becoming a hurdle for me to portray to the customer to opt for serenity framework.
Appreciate your help

[serenity-junit-starter-master.zip](https://github.com/serenity-bdd/serenity-core/files/4399738/serenity-junit-starter-master.zip)

**Comment by wakaleo** [comment]
This is a defect with the parameterized tests - not sure when I will get a chance to investigate though/

**Comment by pgsysemsinc** [comment]
Serenity 3.1.1 report is not showing correctly.

![image](https://user-images.githubusercontent.com/59636954/153911362-c0c8a5e8-bb84-431e-afad-d33e289e0717.png)


test percentage is showing > 100
