### ISSUE TITLE
Unable to access the WebElementFacade element with Android driver

### ISSUE THREAD

**Issue by suryabandam** [serenity-bdd/serenity-core#1987]
Getting the below error while accessing the WebElementFacade element with Android Driver.

java.lang.ClassCastException: io.appium.java_client.android.AndroidElement cannot be cast to net.serenitybdd.core.pages.WebElementFacade

**Comment by wakaleo** [comment]
Use WebElement instead

**Comment by suryabandam** [comment]
Hi Wakalo, We are using Serenity framework and WebElementFacade for desktop web application, wanted to use the same for mobile web automation.  
And it is working fine when I use WebElement. 
Kindly suggest, if is there any chance to use WebElementFacade.

Thank you in advance :)

**Comment by wakaleo** [comment]
They aren’t supported currently, but might be in the future. Serenity’s Appium integration is largely community-driven.

**Comment by suryabandam** [comment]
Thank you @wakaleo.
