### ISSUE TITLE
Not able to use isDisabled() assertion

### ISSUE THREAD

**Issue by Manishrn** [serenity-bdd/serenity-core#1988]
Hi 
I am trying to check that perticular  webelement is disabled or not .
I can see that  Ensure.that(target, isVisible())  and Ensure.that(target, isEnabled())  is there, however  
not able to find isDisabled() .
is there something that I am missing ? @wakaleo @jan-molak

**Comment by wakaleo** [comment]
Try `isNotEnabled()`

**Comment by Manishrn** [comment]
Hi ,
I shows "can not find name 'isNotEnabled'".
I did not see any declaration isNotEnabled in below image.
![image](https://user-images.githubusercontent.com/24430750/76331096-ae1f3d00-6314-11ea-822a-4a53eb099d94.png)

**Comment by wakaleo** [comment]
For serenity/js questions you will need to raise the issue in https://github.com/serenity-js/serenity-js/issues

**Comment by Manishrn** [comment]
@wakaleo Thank you .

**Comment by jan-molak** [comment]
This question was answered at serenity-js/serenity-js#496
