### ISSUE TITLE
Parallel execution for mobile application 

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1991]
Hi I can execute my chrome browsers in parallel with the help of gradle function maxParallelForks.How can i achieve the same for mobile app execution in parallel with gradle .
how can i trigger to device at a time ?

**Comment by wakaleo** [comment]
This is a question rather than a defect, so it would be better to ask it on Gitter (there are a lot of Appium users there, and I think the answer is non-trivial).
