### ISSUE TITLE
Unable to run JUnit tests after Serenity v2.1.0 upgrade

### ISSUE THREAD

**Issue by JoseCIG** [serenity-bdd/serenity-core#1992]
Hello I recently upgraded serenity from v2.0.10 to v2.1.8 and noticed that now when I try to run tests with multiple tags (for example: `mvn clean verify -Dtags="p0, p1"`) I get this error:
![image](https://user-images.githubusercontent.com/39282076/76344490-e98f1c80-62be-11ea-80be-ed38ead9bbf3.png)

After some some digging I found that this issue seems to be related to the tagging changes in https://github.com/serenity-bdd/serenity-core/commit/7bd03babfcf32bbe5fbbeb064887bffdd99d90cb#diff-2a448288ea753810f81dccb1fb0cef02 which went in on the v2.1.0 release. I have not seen anyone else using JUnit report this issue so im wondering if perhaps this is on my end. Any ideas?

**Comment by wakaleo** [comment]
You need to use cucumber tag expressions, eg “p0 or p1”

**Comment by JoseCIG** [comment]
I see thank you!
