### ISSUE TITLE
((AndroidDriver<?>) driver).pressKey(new KeyEvent(AndroidKey.CAMERA)) is not capturing photo from opened camera

### ISSUE THREAD

**Issue by mansiKulkarni39** [serenity-bdd/serenity-core#1993]
@query,
how to click on capture button of camera. As my camera is opening camera after click on native app locator button. But after that I need to click on capture button, but I am unable to do that. 
I have tried ((AndroidDriver<?>) driver).pressKey(new KeyEvent(AndroidKey.CAMERA)). But it is not capturing. Please help me on that?
**automating Native android app.**

**Comment by wakaleo** [comment]
This sound's like an Appium question, not a Serenity one.

**Comment by wakaleo** [comment]
Closing as not directly related to Serenity code. Please feel free to reopen if a change in the Serenity code is required.
