### ISSUE TITLE
Switching to new tab

### ISSUE THREAD

**Issue by marek2209** [serenity-bdd/serenity-core#1995]
Hi, 

Is it possible to create new tab using serenity and do some work on it?

I would like to do some stuff on page A then open page B do some stuff on it and after that close it and back again to page A.

i wanted to use @DefaultUrl annotation but once i do Class.open() then Page B always 'ovveride' tab with Page A....

Maybe im using wrong approach for such action and there is some better solution for it.

**Comment by marek2209** [comment]
well i just used 
ForgotPasswordPage forgotPasswordPage = this.switchToPage(ForgotPasswordPage.class);
forgotPasswordPage.open();
 
:)

**Comment by wakaleo** [comment]
That would be the simplest approach - @DefaultUrl isn't really meant for switching pages
