### ISSUE TITLE
Incorrect number value of "retries (unstable test)" tag in Serenity report

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#1997]
When Serenity-JUnit test is executed with property `test.retry.count`, test is retried successfully, but number of retries is reported incorrectly in generated HTML report.

Example:
Flaky test was executed with `test.retry.count=10`. It failed 3 times and passed at 4th time, so number of retries = 3:
![image](https://user-images.githubusercontent.com/6312221/76515973-390e4d80-6463-11ea-852f-114900a8f8b5.png)

However, on HTML page in generated report, tag `Retries` shown as `7` (3 expected)
![image](https://user-images.githubusercontent.com/6312221/76516016-59d6a300-6463-11ea-8296-4550603474af.png)

**Comment by wakaleo** [comment]
I think this is normal behavior - there are only 7 tests, even if one was run several times.

**Comment by wakaleo** [comment]
Could you propose a PR?

**Comment by scormaq** [comment]
Unfortunately I don't have time available in nearest future, but I suppose it should be pretty simple fix 🙂

**Comment by scormaq** [comment]
Works fine within serenity-core 2.1.13
