### ISSUE TITLE
Add alias to RestInteraction for Groovy users

### ISSUE THREAD

**Issue by drkstr101** [serenity-bdd/serenity-core#2003]
Hello,

I have a minor feature request if it's not to much trouble. I could even submit a pull request if desired.

The problem comes down to the `RestInteraction with(RestQueryFunction restConfiguration)` method. Groovy adds a default `with` method to every object, which accepts a Groovy Closure as an argument. So if I do something like this: `Get.resource("/users/{id}").with({ request -> request.pathParam("id", 1) })`, Groovy will see that I am attempting to pass a Closure and match the default `with` method rather than the intended one.

In order to do this in Groovy, I had to create my own class which extends `RestInteraction` like so:

```groovy
abstract class ApiInteraction extends RestInteraction {

    ApiInteraction withRequest(RestQueryFunction restConfiguration) {
        super.with(restConfiguration)
        return this
    }

    ApiInteraction withRequest(List<RestQueryFunction> restConfigurations) {
        super.with(restConfigurations)
        return this
    }
}
```

Then create my own `Post`, `Get`, etc. which extend from this class. Adding a simple alias to these methods will make it a lot more usable for Groovy users.

Cheers and thanks for your time!

**Comment by wakaleo** [comment]
Good idea - I'd be happy for you to propose a PR (it will get done faster that way)

**Comment by drkstr101** [comment]
Awesome! I will have it done by the end of the day.

**Comment by drkstr101** [comment]
https://github.com/serenity-bdd/serenity-core/pull/2004

Cheers, and thank you!

**Comment by drkstr101** [comment]
Fixed in PR
