### ISSUE TITLE
Take screenshot from Custom Listener

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#2005]
I am trying to take a screenshot from custom listener (for integrating with Allure), but from custom listener I can't reach web driver.

Custom Listener should give access to driver, as it gives access for example to EnvironmentProperties.

**Comment by wakaleo** [comment]
What sort of custom listener are you using?

**Comment by xescuder** [comment]
I'm implementing StepListener. I've also tried to use JUnit4 RunListener.

**Comment by wakaleo** [comment]
StepListeners aren't really designed for that.
