### ISSUE TITLE
Presence of comments in JBehave scenarios make test scenario execution status as ‘ignored/skipped’

### ISSUE THREAD

**Issue by YuliaPrysiazhniuk** [serenity-bdd/serenity-core#2006]
Steps to reproduce:
1. Created a sample project using latest available Serenity JBehave Archetype (v 2.0.91) which is based on <serenity.version>2.0.48.
2. Add comments in any of sample test scenarios and run the test. Test status will be passed.
3. Update Serenity version to the latest one - 2.1.13. Run the same testcase. Result: test status will be ‘ignored/skipped’.

**Comment by wakaleo** [comment]
Comments are not supported in JBehave scenarios. I would recommend moving to Cucumber as JBehave is no longer actively supported

**Comment by wakaleo** [comment]
I don't think anything has changed in the Serenity code for this, so maybe a JBehave issue.

**Comment by pdevaraj714** [comment]
Reviving this thread, I am also facing a similar issue with the presence of comments making the final results of tests to become ignored, even if every step in the jbehave story is passed.

Please find the versions of serenity and dependencies used below(maven build tool):
<serenity.version>3.1.15</serenity.version>
<serenity.maven.version>3.1.15</serenity.maven.version>
<serenity.jbehave.version>1.46.0</serenity.jbehave.version>

<java.version>1.8</java.version>
<junit.version>4.12</junit.version>

<maven-surefire-plugin.version>3.0.0-M5</maven-surefire-plugin.version>
<maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
<maven-shade-plugin.version>3.2.4</maven-shade-plugin.version>

**Comment by wakaleo** [comment]
It might be a problem parsing the JBehave story file when the requirements module in Serenity reads it. We don't really actively support JBehave specifically these days for the more recent versions of Serenity, but if you want to have a look at the code, please feel free to have a look at `net.thucydides.core.requirements.model.LoadedNarrative`

**Comment by pdevaraj714** [comment]
Hi John, thanks for the reply. Does that mean we will have to revert back to previous version of serenity to maintain jbehave support? The previous version that we were using was serenity 2.0.53. Please also find a screenshot of how the report looks like for reference. Thanks.
![image](https://user-images.githubusercontent.com/54423098/147791411-e32adef1-36af-4935-8496-8d5fd7dddd8e.png)

**Comment by wakaleo** [comment]
I suspect comments in JBehave stories may always have caused problems.

**Comment by wakaleo** [comment]
Closing as JBehave is not specifically supported in Serenity 3.x.
