### ISSUE TITLE
[Serenity JUnit] Сomma separated list of tags doesn't execute any test

### ISSUE THREAD

**Issue by yavgel** [serenity-bdd/serenity-core#2007]
Latest `<serenity.version>2.1.13</serenity.version>`

- as per doc -> http://thucydides.info/docs/serenity-staging/#_running_scenarios_by_tags

```
With JUnit tests, this can be achieved by providing a single tag or a comma separated list of tags from command line. If provided, only classes and/or methods with tags in this list will be executed.

mvn clean verify -Dtags="release:sprint-2"
or
mvn clean verify -Dtags="feature:Reporting, release:sprint-2"
```

Current results:
![image](https://user-images.githubusercontent.com/8123409/77532293-e38b6500-6e94-11ea-9f43-936298c818a9.png)

![image](https://user-images.githubusercontent.com/8123409/77532414-1d5c6b80-6e95-11ea-9301-7b183a672fc9.png)

Trying to run them with next command: 
`mvn clean verify -Dtags="wasabi:api_positive,jazo:api_positive"`

0 tests executed:
![image](https://user-images.githubusercontent.com/8123409/77532565-66acbb00-6e95-11ea-947a-eda479169a2a.png)

Please advice, thank you a lot!

**Comment by wakaleo** [comment]
That documentation is the old version, referring to cucumber 1.x. In the current versions you need to use cucumber tag expressions (see https://cucumber.io/docs/cucumber/api/ and https://github.com/cucumber/cucumber/blob/master/tag-expressions/README.md)

**Comment by wakaleo** [comment]
The answer given is still the right one.

**Comment by yavgel** [comment]
Hello @wakaleo - could you please give me an example of the test class with @RunWith(SerenityRunner.class) runner and Junit tests using the cucumber tag expressions you've mentioned above. As per the docs you gave -  I am a bit confused about how to use it in my Serenity Junit tests and how to run them in a command line.

Thank you a lot in advance!

**Comment by yavgel** [comment]
> The answer given is still the right one.

sorry, you are right - will close it, but please help me to figure out the comment above.

**Comment by yavgel** [comment]
Dear @wakaleo the issue above was about Serenity with **JUnit** but not Cucumber, so the question is still relevant for me, how can I use a comma-separated list of tags to run my Junit tests? Thank you a lot in advance!

**Comment by yavgel** [comment]
> Have you tried with the cucumber tags notation?

Doesn’t work for me: 
![image](https://user-images.githubusercontent.com/8123409/89306320-fe09f200-d66f-11ea-99fb-51b3b2c24871.png)

`mvn clean verify -Dcucumber.options="--tags=@EMAIL_LIVE_MESSAGE"`

**Comment by wakaleo** [comment]
`mvn verify -Dtags="@EMAIL_LIVE_MESSAGE"`

**Comment by yavgel** [comment]
Unfortunately still nothing executed:

![image](https://user-images.githubusercontent.com/8123409/89307299-352cd300-d671-11ea-98d5-15d77fa0c1d4.png)

**Comment by yavgel** [comment]
> `mvn verify -Dtags="@EMAIL_LIVE_MESSAGE"`

Unfortunately still nothing executed:

![image](https://user-images.githubusercontent.com/8123409/89307299-352cd300-d671-11ea-98d5-15d77fa0c1d4.png)

**Comment by wakaleo** [comment]
![image](https://user-images.githubusercontent.com/55986/89308438-27c01a80-d66a-11ea-8646-39cb3936d3b4.png)

``` mvn verify -Dtags="@quick"```

**Comment by yavgel** [comment]
> ![image](https://user-images.githubusercontent.com/55986/89308438-27c01a80-d66a-11ea-8646-39cb3936d3b4.png)
> 
> ` mvn verify -Dtags="@quick"`

one works perfectly as in your example, but two or more...
`mvn clean verify -Dtags="@EMAIL_LIVE_ORDER, @EMAIL_LIVE_MESSAGE"` - DO NOT WORK

**Comment by yavgel** [comment]
Just tried like this -> `mvn clean verify -Dtags="@EMAIL_LIVE_ORDER or @EMAIL_LIVE_MESSAGE"`
and it works fine for me now, as per the article you gave me, so I need not use comma but specific cucumber logical words instead.

**Comment by yavgel** [comment]
BTW:  @wakaleo  - it works also without the `@` symbol near the tag name(s), for example:
`-Dtags="UI_FEAT or API_LIVE or API_FEAT or JAZO_API and not EMAIL_LIVE_ORDER and not EMAIL_LIVE_MESSAGE"`
