### ISSUE TITLE
Filter requirements in serenity report while using serenity with cucumber 

### ISSUE THREAD

**Issue by shankar4a1** [serenity-bdd/serenity-core#2009]
Hi ,
I am new to serenity BDD framework.
Currently,I observed that all requirements under "src/test/resources/features" are getting displayed under "Requirements " tab in generated serenity report .Can we filter the requirement to be shown in the report to just to show the current release requirements if specific release tags are used for features/scenarios .As business is interested to look at only current release requirement and and corresponding statistics. Please suggest/guide if this is already available in serenity. Currently am using below versions

 serenity.version>2.0.48
 serenity.maven.version>2.0.48
 serenity.cucumber.version>1.0.12
 cucumber.version>4.2.0.

Thank you.

**Comment by wakaleo** [comment]
Use the latest versions (2.2.0) and the Cucumber filter options, the reports will be filtered automatically.

**Comment by shankar4a1** [comment]
Hi @wakaleo ,
Thank you for the input.

I have set up project by following step by step as mentioned in the below project 

 https://github.com/serenity-bdd/serenity-cucumber-starter 

serenity.version>2.2.0
serenity.maven.version>2.2.0
serenity.cucumber.version>2.2.0
cucumber.version>5.5.0

Currently am using maven run configuration as below

clean verify -Ddriver=chrome -Dcucumber.filter.tags=@smoke

But in Requirements tab it is still showing all  feature files irrespective of tag i.e smoke

In Over all Test results ,Under functional coverage report is showing only feature files which is marked with "@smoke" tag after using below option.

report.tagtypes=feature

Requirement is to only show current release requirements in "Requirements Tab"

Please suggest if am not using filter options correctly. . Thank you for your time and suggestion in advance.

**Comment by wakaleo** [comment]
Try running:
```
mvn clean verify -Dcucumber.options="--tags @smoke"
```

**Comment by wakaleo** [comment]
Try running:
```
mvn clean verify -Dcucumber.options="--tags @smoke"
```

**Comment by shankar4a1** [comment]
I have tried running with suggested command.
mvn clean verify -Ddriver=chrome "-Dcucumber.options=--tags @smoke"

After running,I am unable to view ny requirements listed in "Requirements " and "features" tab.

However ,In Over all Test results functional coverage report is showing only feature files which is marked with "@smoke" tag as i used below option.
report.tagtypes=feature

**Comment by wakaleo** [comment]
Make sure you respect the position of the quotes in the command

**Comment by shankar4a1** [comment]
Apologies ..I have tried with below command as well  

mvn clean verify -Dcucumber.options="-- tags @smoke"

Both below commands  yielede same results i.e.  unable to view any requirements listed in "Requirements " and "features" tab.


mvn clean verify -Dcucumber.options="--tags @smoke"       and 

mvn clean verify -Ddriver=chrome "-Dcucumber.options=--tags @smoke"

**Comment by wakaleo** [comment]
Can you provide a  sample project?

**Comment by shankar4a1** [comment]
Can you please suggest me how to add a project here .I am unable to see any link to attach zip files here

**Comment by shankar4a1** [comment]
Hi @wakaleo ,,
Please find sample project below.
[https://github.com/shankar4a1/SampleProject1](url)

**Comment by wakaleo** [comment]
![image](https://user-images.githubusercontent.com/55986/77889164-5ade4180-7265-11ea-9d4d-461e4c24cc2b.png)

**Comment by shankar4a1** [comment]
Could you please check once .changed from private to public.

 [https://github.com/shankar4a1/SampleProject1](url)

**Comment by wakaleo** [comment]
Your scenario outline has no title.

**Comment by shankar4a1** [comment]
I updated scenario outline  .but curious to know how does it matter as scenarios is not marked with @smoke tag .

**Comment by wakaleo** [comment]
It's not legal Gherkin syntax, so Serenity will be unable to generate the reports.

**Comment by shankar4a1** [comment]
Sure Thank you. However I have tried after updating scenario outline as well but no luck.
Please let me know once you get a chance to look into the project and suggest.

**Comment by wakaleo** [comment]
The tests run normally - they are marked as pending as there are no step definitions.
![image](https://user-images.githubusercontent.com/55986/77927234-f7710580-729e-11ea-90d6-4cfff05cd3c8.png)

If you need further help I'd be happy to set up some project-specific support sessions (see https://johnfergusonsmart.com/serenity-bdd-mentoring/)

**Comment by shankar4a1** [comment]
Yes as no steps are implemented it will be in pending status. and that is irrelevant to problem statement. Apologies if i made you  understand in-correctly 

Below is my problem statement :
To Show only filtered requirements under "Requirements " tab 

Example:
 if all scenarios in one release , are marked with tag specific version like @release4 , Serenity report should show only the features/scenarios corresponding to current release tag under "Requirements " tab. 

As per current implementation in serenity, it shows all scenarios/features irrespective of tags .

If there are 4 directories (release1,release2 ,release3 and release4)  under src/test/resources/feature directory, 25 feature files in each directory.i.e. on total 100 feature files .

If i am executing scenarios with @release4 tag, Requirements tab should only display release 4.  25 features files but not 100 feature files. hope this clarifies .

**Comment by shankar4a1** [comment]
Can you please let em know how many features are under Requirements tab after executing sample project.

**Comment by wakaleo** [comment]
Filtering by tags also works normally for the sample project. If you need more project-specific help, please refer to the link above.

**Comment by shankar4a1** [comment]
Normal filter tagging is not working and it is not filtering requirements  as I already tried. Anyways Thank you for the input and time..

**Comment by wakaleo** [comment]
It works for the project that you provided, although I had to add extra features and tags (since there was only one feature). As I said, if you need project specific help, that would fall under the commercial support category.
