### ISSUE TITLE
Edge driver, always returns an error and automation fails.

### ISSUE THREAD

**Issue by xMagiciaNx** [serenity-bdd/serenity-core#2010]
Everytime when I try to set the driver to 'edge' the test fails with error:

`net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.edge.EdgeDriver`

In any case, is edge currently supported by serenity?
Thank you in advance.

**Comment by wakaleo** [comment]
Serenity supports any driver that Selenium supports, and works fine with Edge on BrowserStack and SauceLabs, so I would suggest looking more closely at the exact error message to find the cause of the problem.
