### ISSUE TITLE
Gradle - how to pass cucumber tag value using -Dcucumber.options 

### ISSUE THREAD

**Issue by Krithikmano** [serenity-bdd/serenity-core#2012]
Please provide the details how to pass cucumber tag running using gradle.

when i try to run the below command via command prompt, it is not accepting "cucumberOptions'

.gradlew runTest -PcucumberOptions="--tags @end2end"

**Comment by wakaleo** [comment]
This is a Gradle question, so would be best asked in the Gradle forums.

**Comment by ssmuthukumaran** [comment]
.gradlew runTest -Dcucumber.options="--tags '@End2End' "
Am using like this.

**Comment by Krithikmano** [comment]
@ssmuthukumaran  i tried but it is showing the message as Task '.options=--tags' not found in root project. Did you add anything in build.gradle.
