### ISSUE TITLE
Aggregating TestOutcomes in-memory without generating any physical files 

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#2014]
Hello!

I have this task:

1. Download and consolidate a bunch of zip files containing individual serenity test results.
2. Open these zip files, and create TestOutcomes from the entire set of files
3. Use the `HtmlAggregateStoryReporter` to generate the aggregated report.

From reading the documentation my general workflow will be as such:

```
    String outputDirectory = ... // has to be a file directory

    TestOutcomes outcomes =  
    TestOutcomeLoader.loadTestOutcomes().inFormat(OutcomeFormat.XML).from(outputDirectory);

    HtmlAggregateStoryReporter reporter = new HtmlAggregateStoryReporter(...);

    reporter.generateReportsFromTestResultsIn(outcomes); // returns void
```

The catch is, **I am supposed to do these in-memory, without creating physical files**.

Based on what I'm reading, there are two potential blockers I will face:

1. `TestOutcomeLoader` only allows loading from a file directory, and does not accept InputStreams.
2. `HtmlAggregateStoryReporter` returns void, and so even if I manage to aggregate the outcomes, I am not able to access them anywhere?

Are these observations correct, and if so are there any potential solutions to this?

http://thucydides.info/docs/apidocs/net/thucydides/core/model/TestOutcome.html
http://thucydides.info/docs/apidocs/net/thucydides/core/reports/html/HtmlAggregateStoryReporter.html#generateReportsForTestResultsIn(net.thucydides.core.reports.TestOutcomes)

**Comment by wakaleo** [comment]
This would require some big architectural changes - Serenity assumes it is running in a build directory with access to the source code (feature files), so I'm not sure how this could work with the current code.

**Comment by timothyjmtan** [comment]
Yes you're absolutely right, I don't see how this can be done in a few lines of code change -- in that case, let me revisit my solutioning. Thanks for the quick reply!
