### ISSUE TITLE
Serenity gradle report doesn't show tabs on Win10

### ISSUE THREAD

**Issue by pbaeck** [serenity-bdd/serenity-core#2018]
Environment:

Windows 10
Java 8
Gradle 5.6
Serenity versions:
net.serenity-bdd:serenity-screenplay:2.0.52
net.serenity-bdd:serenity-cucumber4:1.0.21
net.serenity-bdd:serenity-gradle-plugin:2.0.52

Problem:
When I execute the serenity report locally I can't see the tabs:
 Themes
 Stakeholders
 Capabilities
 Features
And the tab Requirements doesn't show any tests.
On detail view of a test I can see the tabs but when I click on them I get a 404 error.
When we execute the same project on Jenkins (Linux) server the report is generated correctly.

Do I have to configure something special for windows?

**Comment by wakaleo** [comment]
Have you tried with a more recent version?

**Comment by pbaeck** [comment]
Thank you for the quick answer.
After upgrading the version: net.serenity-bdd:serenity-gradle-plugin to 2.2.0 the report was generated correctly.

A big thank you for the help!
