### ISSUE TITLE
Javadoc says SERENITY_JQUERY_INTEGRATION is disabled by default, though PageObject defaults to true

### ISSUE THREAD

**Issue by tschmidt01** [serenity-bdd/serenity-core#2019]
PageObject:
```
private Boolean jqueryIntegrationIsActivated() {
    return THUCYDIDES_JQUERY_INTEGRATION.booleanFrom(environmentVariables, true);
}
```

ThucydidesSystemProperty:
```
/**
* Enable JQuery integration.
* If set to true, JQuery will be injected into any page that does not already have it.
* This option is deactivated by default, as it can slow down page loading.
*/
SERENITY_JQUERY_INTEGRATION,
```

**Comment by wakaleo** [comment]
Well spotted - does this option impact your tests in any way?

**Comment by tschmidt01** [comment]
It actually does. We're getting a `JavascriptException: jQuery is not defined` testing against an app which redirects to login.microsoftonline.com in `PageObject.open()`. I'll try to do a sample project showcasing the error tomorrow. 

I'll further can do a pull request for updating JavaDoc or default value for `SERENITY_JQUERY_INTEGRATION`, if you want :)

**Comment by wakaleo** [comment]
Sure, please do so you get some credit for the find!
