### ISSUE TITLE
Warning: Loading deprecated ObjectFactory from runtime via reflection: cucumber.runtime.SerenityObjectFactory

### ISSUE THREAD

**Issue by mayank-kapoor** [serenity-bdd/serenity-core#2027]
Warning in Cucumber 4 for deprecated ObjectFactory from runtime cucumber.runtime.SerenityObjectFactory

@wakaleo Does this exist in cucumber 5 with serenity also ?

I can see this has been fixed in cucumber jvm : [here](https://github.com/cucumber/cucumber-jvm/commit/bd8d2b590945492777a1433338999a4e3106945e)

**Comment by wakaleo** [comment]
Have you tried?

**Comment by mayank-kapoor** [comment]
Haven't started with cucumber5 yet, will check and get back

**Comment by testifyqa** [comment]
Any updates on this? I am seeing the same thing when running my tests in parallel via gradle

**Comment by wakaleo** [comment]
Are you running with serenity-cucumber5?

**Comment by testifyqa** [comment]
i was on serenity-cucumber4 but updating now to 5 and see what happens

**Comment by testifyqa** [comment]
Updating to serenity-cucumber5 fixed it for me. Thanks. This issue can probably be closed :)

**Comment by wakaleo** [comment]
Thanks for the update!
