### ISSUE TITLE
Cannot resolve plugin net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.1

### ISSUE THREAD

**Issue by yavgel** [serenity-bdd/serenity-core#2028]
![image](https://user-images.githubusercontent.com/8123409/79335356-2c798b00-7f22-11ea-89b0-3eb4e0026fe9.png)

**Comment by wakaleo** [comment]
See https://search.maven.org/artifact/net.serenity-bdd.maven.plugins/serenity-maven-plugin/2.2.1/maven-plugin

**Comment by yavgel** [comment]
I can see that it is there, but for some reason, I cannot fetch it :( , 
even with `mvn dependency:purge-local-repository clean` command

**Comment by yavgel** [comment]
Idea, File > Invalidate caches helped
