### ISSUE TITLE
Hide Rest Interactions

### ISSUE THREAD

**Issue by ricardorlg-aval** [serenity-bdd/serenity-core#2029]
I would like to know if is possible to hide rest interaction, when using Rest Screenplay implementation.

Currently in my E2E I have to make some rest calls, But I don't want to display all the Get,Post... interactions, I make a SilentRestInteraction, that implements the IsSilent mark, but the interactions are still added in the report.

**Comment by wakaleo** [comment]
Any chance you could provide a sample project for this?

**Comment by globalworming** [comment]
see my test branch https://github.com/globalworming/serenity-screenplay-rest-example/blob/test-perform-silent/src/test/kotlin/com/example/testcases/jsonplaceholder/PostsIT.kt

Compare using it without `IsSilent`:
![image](https://user-images.githubusercontent.com/2108984/92489253-e0402780-f1ef-11ea-8e36-276554ae80f2.png)

To using it with `IsSilent`:
![image](https://user-images.githubusercontent.com/2108984/92489331-f3eb8e00-f1ef-11ea-907e-ecbb078e3ec5.png)


It seems the step and consequence is properly hidden, the `Get` is reported

**Comment by globalworming** [comment]
` if (isNestedInSilentTask()) {  
                performSilently(task);`
looks fine, i guess the additional info (url and query) are added somewhere else

**Comment by ricardorlg-aval** [comment]
yes I know, but I see the same request for other people in the past, the problem is that the RestDecorator is the one that adds the record to the report, I will try a fix ASAP.
