### ISSUE TITLE
@Issue does not create a link if alphabetic prefix is not provided

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#203]
In order to link Serenity tests with Testrail cases I did the following:
- added in **serenity.properties** link to my issue tracker 

```
# Testrail
serenity.issue.tracker.url = https://myprojeсt.testrail.net/index.php?/cases/view/{0}
```
- set case index for the test

```
@Test
@Issue("934")
public void shouldRespondWithOkStatusIfVersionPlatformSupported() {
    ...
}
```

After execution I could see case index in Serenity log, but it did not have a link. After investigating I have found out that without alphabetical prefix and the dash the link won't be created.

**Comment by wakaleo** [comment]
The convention is to prefix numerical issue numbers with #, so @Issue("#934") rather than @Issue("934")

**Comment by YamStranger** [comment]
New pattern for Issue names will be introduces in future versions.
