### ISSUE TITLE
All iteration results are not showing if using list1.parallelStream in Report

### ISSUE THREAD

**Issue by Krithikmano** [serenity-bdd/serenity-core#2035]
Just assume that i passing different values in the GET endpoint and verifying the results. I stored all possible values in the List and passing each value for each iteration. 

But in the report it is showing only the last iteration details when i use the forEach.parallelStream(). Remaining iterations are not displaying

Ex: https://localhost.com/accountSearch=<passValueFromList>

list1.parallelStream() 
            .forEach( 
                s -> { getAccountSearch(s)                    
                }); 
    } 
} 

Note: 
1.AccountSerach method will contain all endpoint information.
2. Passing value from List instead of 123

**Comment by wakaleo** [comment]
Can you provide a sample project?
