### ISSUE TITLE
Date parameter 2020-01-01T00:00:00.000Z is displaying with special charters in Report

### ISSUE THREAD

**Issue by Krithikmano** [serenity-bdd/serenity-core#2036]
if i run the below endpoint and serenity report is showing date value is differently

https:/localhost.com/transactions?startTime=2020-01-01T00:00:00.000Z

report is displaying like this https:/localhost.com/transactions?startTime=2020-01-01T00%3A00%3A00.00z

**Comment by wakaleo** [comment]
Can you provide a sample project and screenshot of the issue?
