### ISSUE TITLE
SerenityRest should not take screenshot 

### ISSUE THREAD

**Issue by turturie** [serenity-bdd/serenity-core#2039]
When SerenityRest request is made, if the browser was previously initialised, wrongly take screenshoots.

It's legitimate the have steps that are using both browser and SereityRest instances but screenshot should only be taken at browser steps. 
Currently, after a browser steps, all the following steps, even the SerenityRest, are taking screenshots slowing down the execution while taking useless screenshots.

Thanks,
Martino

**Comment by wakaleo** [comment]
Unfortunately this is pretty much impossible to do in a general case with Cucumber.

**Comment by wakaleo** [comment]
The next release will support the `@Screenshots` annotation for step definition methods, e.g.
```
    @Given("^(?:.*) is on the DuckDuckGo home page")
    @Screenshots(disabled = true)
    public void i_am_on_the_DuckDuckGo_home_page() {
        navigateTo.theDuckDuckGoHomePage();
    }
```

**Comment by turturie** [comment]
Thanks for taking care of this!

**Comment by ricardorlg-aval** [comment]
You can also use DisableScreenshots interface.
