### ISSUE TITLE
get the error message (stack trace) in jBehave listener methods

### ISSUE THREAD

**Issue by gitrak** [serenity-bdd/serenity-core#2045]
how can i get hold of error message of failed scenarios in listener methods. I am using Serentiy BDD with jBehave

@AfterScenario(uponType=ScenarioType.ANY,uponOutcome=AfterScenario.Outcome.FAILURE)
    public void afterEachFailScenario() throws InterruptedException, IOException, AWTException, ClassNotFoundException, SQLException{
       //want to get the error message here so that i can save it in database
    }

**Comment by wakaleo** [comment]
You might be able to use this:
```
StepEventBus.getEventBus().getBaseStepListener().latestTestOutcome().get().getTestFailureCause()
```

**Comment by gitrak** [comment]
Thanks alot ....it is working
