### ISSUE TITLE
Serenity overwrite the report every time new runner executed

### ISSUE THREAD

**Issue by MaheshDani** [serenity-bdd/serenity-core#2046]
Hello I am facing this unique issue where in I have 3 runners generated as below

Runner 1

cat ./parallel/runners/TestSuiteUi0070.java
package parallel.runners;

import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import ....hooks.BrowserStackHooks;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        strict = false,
        features = {"/app/Function/src/test/resources/features/ui/spamuitests.feature:14"},
        plugin = {"json:/app/Function/target/cucumber-parallel/7.json"},
        monochrome = true,
                glue = {"...domain.component.ui.steps", "...hooks"})

public class TestSuiteUi0070 extends BrowserStackHooks {

}

Runner 2
cat ./parallel/runners/TestSuiteUi0071.java
package parallel.runners;

import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import ....hooks.BrowserStackHooks;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        strict = false,
        features = {"/app/Function/src/test/resources/features/ui/spamuitests.feature:14"},
        plugin = {"json:/app/Function/target/cucumber-parallel/7.json"},
        monochrome = true,
                glue = {"....domain.component.ui.steps", "....hooks"})

public class TestSuiteUi0071 extends BrowserStackHooks {

}

Runner 3
cat ./parallel/runners/TestSuiteUi0072.java
package cts.parallel.runners;

import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import ....hooks.BrowserStackHooks;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        strict = false,
        features = {"/app/Function/src/test/resources/features/ui/spamuitests.feature:14"},
        plugin = {"json:/app/Function/target/cucumber-parallel/7.json"},
        monochrome = true,
                glue = {"....domain.component.ui.steps", "....hooks"})

public class TestSuiteUi0072 extends BrowserStackHooks {

}

when these runner are executed using mvn verify command... and serenity aggregate goal is executed after that.. I see summary as only 1 test was run .. 

upon investigation it was seen only instead of 3 different json report as expected there as only one json report generated .

. -name "*.json" | egrep -v "report-template|chartist|fontawesome|nivo-slider"
./Function/target/site/reports/serenity/9a0840e97546a49f86f0b20b93bcd792210f4c2ef8b200be07c11c1e32217f3b.json
./Function/target/cucumber-parallel/7.json

any idea why serenity is not generating  unique report files for each runner execution?

version I am using are 
        <serenity.version>2.0.9</serenity.version>
        <serenity-cucumber.version>1.9.18</serenity-cucumber.version>
        <maven-failsafe-plugin.version>2.22.0</maven-failsafe-plugin.version>
        <maven-surefire-plugin.version>2.22.0</maven-surefire-plugin.version>
        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
        <surefire-junit.version>2.22.0</surefire-junit.version>

**Comment by wakaleo** [comment]
You are running four parallel tests that run the same feature file four times in parallel?

**Comment by MaheshDani** [comment]
@wakaleo  no, at the moment I  am achieving serial run of each runner one after the other.

**Comment by wakaleo** [comment]
Scenario reports are for scenarios, they are not dependent on the test runners, so if you run the same scenario several times, you will only get one report.

**Comment by MaheshDani** [comment]
oh! my requirement is to run same scenario for given number of time one after the other and expect all runs for that scenario reported in aggregate... how do I achieve that?

**Comment by wakaleo** [comment]
You can't do that with Cucumber.

**Comment by MaheshDani** [comment]
is there no way to rename reports generated before next runner test trigger?

**Comment by wakaleo** [comment]
No, scenarios are unique within the report. Cucumber is a living documentation tool, not a test scripting tool, so not designed for this sort of thing.

**Comment by MaheshDani** [comment]
Thanks @wakaleo
