### ISSUE TITLE
[SEVERE]: Timed out receiving message from renderer

### ISSUE THREAD

**Issue by jayzsuarez** [serenity-bdd/serenity-core#2047]
@wakaleo Hi,

Chromedriver and Google were set initially to v81 but we encountered a warning "[SEVERE]: Timed out receiving message from renderer:". Then I tried to downgrade to v79 and v80 but still the same.

Serenity version details:

               <serenity.version>1.8.21</serenity.version>
		<serenity.maven.version>1.8.21</serenity.maven.version>
		<serenity.jbehave.version>1.33.0</serenity.jbehave.version>

Is this expected  behavior?

**Comment by wakaleo** [comment]
That’s a chrome driver message, it’s not related to Serenity.

**Comment by jayzsuarez** [comment]
@wakaleo thank you, no side effects in the serenity.
