### ISSUE TITLE
Serenity - net.thucydides.core.steps.ConsoleLoggingListener - TEST PENDING

### ISSUE THREAD

**Issue by ar0a** [serenity-bdd/serenity-core#2048]
Hi folks,

I've created a super simple test using Serenity + BDD + Maven

I have my feature file pointing to my corresponding stepDefinition method. For some reason, when I try to compile this and obtain this:

Any ideas about how I can fix this?:

***

This is my very simple feature file:
-------------------------------------
```
Feature: User Access to the Agents Web

Scenario: As a user I want to do login in the web
Given I navigate to the login page

```

This is my very simple login step definition class:
------------------------------------------------------
```
public class Login_stepDef {
@Steps
UserSteps user;

@Given("^I navigate to the login page$")
public void I_navigate_to_the_login_page() {
user.navigateToLoginPage();
}
}
```

I copied and pasted the autogenerated step to avoid misspellings but still not working.

My feature file detects my step but when I run the test, the listener says it does not found the step:

1822 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - TEST PENDING
    [33mGiven [0m[33mI navigate to the login page[0m                       [90m# null[0m
1828 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
          __  _____ _____ ____ _____   ____  _____ _   _ ____ ___ _   _  ____ 
 _       / / |_   _| ____/ ___|_   _| |  _ \| ____| \ | |  _ \_ _| \ | |/ ___|
(_)____ / /    | | |  _| \___ \ | |   | |_) |  _| |  \| | | | | ||  \| | |  _ 
 |_____/ /     | | | |___ ___) || |   |  __/| |___| |\  | |_| | || |\  | |_| |
(_)   /_/      |_| |_____|____/ |_|   |_|   |_____|_| \_|____/___|_| \_|\____|

You can implement missing steps with the snippets below:

```
@Given("^I navigate to the login page$")

public void i_navigate_to_the_login_page() {

    // Write code here that turns the phrase above into concrete actions

    throw new PendingException();

}
```

[Prueba.zip](https://github.com/serenity-bdd/serenity-core/files/4530623/Prueba.zip)

Thanks a lot in advance

**Comment by wakaleo** [comment]
Your feature file is in the wrong place - have a look at https://github.com/serenity-bdd/serenity-cucumber-starter to see the proper directory structure and conventions.

**Comment by ar0a** [comment]
Thanks a lot...
I'm still having the same issue
[Prueba_v2.zip](https://github.com/serenity-bdd/serenity-core/files/4531030/Prueba_v2.zip)

**Comment by ar0a** [comment]
> Your feature file is in the wrong place - have a look at https://github.com/serenity-bdd/serenity-cucumber-starter to see the proper directory structure and conventions.

Thanks a lot...
I'm still having the same issue
[Prueba_v2.zip](https://github.com/serenity-bdd/serenity-core/files/4531030/Prueba_v2.zip)
