### ISSUE TITLE
Serenity index.html is empty after configuring single page html report

### ISSUE THREAD

**Issue by amungrey** [serenity-bdd/serenity-core#2050]
Here is my Pom.xml snippet
```     
<plugin>
    <groupId>net.serenity-bdd.maven.plugins</groupId>
    <artifactId>serenity-maven-plugin</artifactId>
    <version>${serenity.version}</version>
    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-single-page-report</artifactId>
            <version>2.1.11</version>
        </dependency>
    </dependencies>
    <configuration>
        <tags>{tags}</tags>
        <reports>single-page-html</reports>
    </configuration>
    <executions>
        <execution>
            <id>serenity-reports</id>
            <phase>post-integration-test</phase>
            <goals>
                <goal>aggregate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
When i run mvn clean verify, 

[INFO] SERENITY REPORTS
[INFO]   - Full Report: file:///Users/amungrey/Projects/Ventana/store-test-suite/target/site/serenity/index.html
[INFO]   - Single Page HTML Summary: file:///Users/amungrey/Projects/Ventana/store-test-suite/target/site/serenity/serenity-summary.html
[INFO] 

Single Page HTML Summary: file:///Users/amungrey/Projects/Ventana/store-test-suite/target/site/serenity/serenity-summary.html looks great 

However, 
 Full Report: file:///Users/amungrey/Projects/Ventana/store-test-suite/target/site/serenity/index.html is empty.

I want to have both, one for jenkins and one for email. Please help

**Comment by wakaleo** [comment]
Could you format your question so that it is possible to read the pom.xml file? The single page HTML plugin has no effect on the main report.

**Comment by globalworming** [comment]
huh, seems like i can edit the post by @amungrey 
edited formatting

**Comment by wakaleo** [comment]
Are there any error messages in the log? Generating the single page HTML report has no effect on the main report.
