### ISSUE TITLE
[Question] Is there any way to wait for XHR calls to complete?

### ISSUE THREAD

**Issue by ramkumar-yoganathan** [serenity-bdd/serenity-core#2054]
Is there any way to wait until all the xhr calls to complete in the page? This is for sales force lightning web. I believe this could be achieved using chrome network event listener. 

**Reference:**
[chrome-devtools-java-client](https://github.com/kklisura/chrome-devtools-java-client)

Thanks

**Comment by wakaleo** [comment]
There is nothing built-in to Serenity to do this.

**Comment by ramkumar-yoganathan** [comment]
Could you please check and expose a method for this?

**Comment by wakaleo** [comment]
If you have a working project with this issue you are probably best placed to experiment - I would recommend creating a custom driver or a custom version of the ChromeDriverProvider class to see if you can get the library doing what you need.
