### ISSUE TITLE
Serenity report issue while using version compatible with Cucumber4

### ISSUE THREAD

**Issue by sfarhan25** [serenity-bdd/serenity-core#2056]
Hi,

I am using the following versions and the test runs are working as expected.
        <serenity.version>2.1.10</serenity.version>
        <serenity.cucumber.version>2.1.2</serenity.cucumber.version>
        <cucumber.version>4.8.0</cucumber.version>

But facing an issue with the Serenity reports when I am trying to run using the following CucucmberOptions.
(For instance I want to run 2 scenarios namely `@tag1` and `@tag2`)

- `-Dcucumber.options="--tags @tag1,@tag2 --strict"` : This following command is not generating the serenity report at all. The report states 0 scenarios.

- `-Dcucumber.options="--tags '@tag1 or @tag2' --strict"` : This following command fails the build with the following error - 
[ERROR] Unknown lifecycle phase "or". You must specify a valid lifecycle phase or a goal in the format

This is all on the LINUX based machines.

Could you please help me with the same ? (As to what I am doing incorrectly here, or I am missing any syntax)

**Comment by wakaleo** [comment]
Try using version 2.2.0 (and Cucumber version 5.5.0) with -Dcucumber.filter.tags="@tag1 or @tag2"

**Comment by sfarhan25** [comment]
@wakaleo Hi John,

I have some framework dependencies and hence restricted to use Cucumber 4.8, hence any suggestions please ?

**Comment by wakaleo** [comment]
Then cucumber.options should work with `mvn verify -Dcucumber.options="--tags '@tag1 or @tag2'"

**Comment by sfarhan25** [comment]
Unfortunately thats resulting in mvn build error with the following:
`Unknown lifecycle phase "or". You must specify a valid lifecycle phase or a goal in the format`

This is on Linux agents - based on TeamCity.

**Comment by wakaleo** [comment]
That would indicate that you have an unclosed quote somewhere. You can also try `mvn verify -Dcucumber.options='--tags "@tag1 or @tag2"'`

**Comment by sfarhan25** [comment]
😞 tried exactly as you have defined - 
`-D"cucumber.options='--tags "@tag1 or @tag2"'`

Getting this error now:
`Unknown lifecycle phase "@tag1 or @tag2"'`

**Comment by wakaleo** [comment]
That is a Maven error, so there is most likely an issue with the quotes in your command line. The syntax seems correct and corresponds to what I use routinely on Mac and Linux machines

**Comment by sfarhan25** [comment]
You are right, as it works as expected on my mac locally.
Seems to be an issue with TeamCity as to how it decodes this command line arguments.

**Comment by wakaleo** [comment]
I would suggest trying to upgrade so you can use the filters option parameter instead

**Comment by sfarhan25** [comment]
Thanks for you inputs and suggestions John.
Appreciate your quick responses 👍

**Comment by sfarhan25** [comment]
Hi John @wakaleo ,

Finally got it working for Cucumber 4.8 with the following (on TEAMCITY specifically is an issue):
`"-Dcucumber.options=--tags '@tag1 or @tag2'"` (_also should be placed as the last argument in build params_)

Just fyr if in future somebody raises this sort of an issue.
