### ISSUE TITLE
How can I define no-proxy property?

### ISSUE THREAD

**Issue by szanelato** [serenity-bdd/serenity-core#2058]
@wakaleo I'm using serenity to test my intranet project in CI using Jenkins/Docker. The Jenkins and my containers can resolve the hosts from intranet, but I have one dependency in internet, and I'm facing with problem to access.  I'm used to do this passing in the execution something like this:

Supose that "proxy.aws.intranet.company.domain"  is my proxy address

-Dproxy=proxy.aws.intranet.company.domain 
-Dproxy-bypass=company.domain.com,*.company.domain.com

How can I do the same configuration using serenity for chrome and firefox?

Best regards.

**Comment by wakaleo** [comment]
https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html#_configuring_proxy_settings

**Comment by silviozanelato19** [comment]
Sorry @wakaleo , but it wasn't clear to me. How can I define proxy bypass?

**Comment by JeffGaly** [comment]
@wakaleo  John we are looking for the same set of proxy to configure from serenity .Can you help on this .

**Comment by wakaleo** [comment]
This is driver specific I think - the Serenity options are set up to work for Firefox, but chrome (for example) has it's own options.

**Comment by JeffGaly** [comment]
@wakaleo can you share the chrome options?

**Comment by silviozanelato19** [comment]
@JeffGaly @wakaleo I managed this situation using this argument at my gradle command. In this case to execute my project inside a isolated docker container:

`-Dserenity.proxy.http=proxy.provider.intranet.company.domain:80`

It work fine at firefox and chrome.

**Comment by wakaleo** [comment]
Those properties should work (see https://github.com/serenity-bdd/serenity-core/blob/cac909b0e65c910a7f96198546625262889ccd50/serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java#L608) - could you confirm if you are still having issues with version 3.2.0?

**Comment by jpramirezlo** [comment]
Thank you very much for your collaboration, it worked for me:

serenity.proxy.http = 127.0.0.1:8080
serenity.proxy.sslProxy = 127.0.0.1:8080
