### ISSUE TITLE
Query about missing INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1 from console output since version 2.1.7

### ISSUE THREAD

**Issue by adeellis** [serenity-bdd/serenity-core#2061]
Hi,

Since version 2.1.7 the console output seems to be missing the cumulative "TEST NUMBER" information. Is there a reason why this nice feature has been removed?

Example excerpt from console output using version 2.1.6 shown below: 

TEST STARTED: scenario_007
-------------------------------------------------------------------
16:31:18.881 [main] INFO  - TEST NUMBER: 96     <--- this is what I am referring to which has disappeared from version 2.1.7 onwards

Thanks
Ade

**Comment by wakaleo** [comment]
We removed that a few versions back because it can be misleading with parallel processing.

**Comment by adeellis** [comment]
Ah thanks for thre speedy response. From my [selfish] perspective it would have been nice if it could have picked up a config item which stated that it were running in parallel mode and suppressed this TEST NUMBER rather than removing it for all. But thanks for the quick response. :)
