### ISSUE TITLE
how to convert WebElement to WebElementFacade

### ISSUE THREAD

**Issue by gitrak** [serenity-bdd/serenity-core#2062]
how to convert WebElement to WebElementFacade

**Comment by wakaleo** [comment]
This can't be done; you need to retrieve the object as a WebElementFacade initially. What problem are you trying to solve?

**Comment by gitrak** [comment]
I was working on a utility function which takes a xpath string, make WebElementFacade with it and then create a logic to find whether that element is present or not, enabled or not, visible or not...
So all in all, i need is a way to make WebElementFacade with string without annotation

**Comment by wakaleo** [comment]
If you have an XPath expression you can just the `find()` method in the `PageObject` or `UIInteractionSteps` class for this.

**Comment by gitrak** [comment]
Thanks alot!

**Comment by gokulkuppan** [comment]
Use "element" method in page class that takes webelement as input and returns webelementFacade
