### ISSUE TITLE
Issue when using css selector with findBy and $ methods in serenity bdd 2.2.2

### ISSUE THREAD

**Issue by so-cs** [serenity-bdd/serenity-core#2063]
It seems there is an issue in detecting a css selector when using the findBy() or $() in locating an element.
Following code works fine:

```
WebElementFacade link = find(By.cssSelector("a[href='/test']"));
link.click(); 
```
Following pieces of code do not work anymore:

```
WebElementFacade link = findBy("a[href='/test']");
link.click();
```

```
WebElementFacade link = $("a[href='/test']");
link.click();
```

So it seems that using the shorter versions FindBy() and $(), where an xpath or css selector is expected, does not work anymore due to it expecting only an xpath, as per the error. It either does not recognize the css selector or it doesn't check for one. If I am missing something in calling the functions please let me know. So far was not able to find anything useful on the web. Thanks in advance. 

Error is following:

**[main] ERROR  -     Expected enabled element was not enabled

net.thucydides.core.webdriver.exceptions.ElementShouldBeEnabledException: Expected enabled element was not enabled
	at com.gettingstarted.tests.LocatorExamplesTest.tc3(LocatorExamplesTest.java:30)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for By.xpath: a[href='/test'] to be enabled (tried for 10 second(s) with 100 milliseconds interval)
	at com.gettingstarted.tests.LocatorExamplesTest.tc3(LocatorExamplesTest.java:30)
Caused by: org.openqa.selenium.NoSuchElementException: 
no such element: Unable to locate element: {"method":"xpath","selector":"a[href='/test']"}**

**Comment by wakaleo** [comment]
This is a case where the css is also valid xpath, and it is therefore treated as XPath. It is not possible to distinguish the XPath from the CSS in this case.  You need to use the “css:” prefix or the long form selector in these cases.

**Comment by globalworming** [comment]
My goto workaround `body a[... ]`

**Comment by so-cs** [comment]
> This is a case where the css is also valid xpath, and it is therefore treated as XPath. It is not possible to distinguish the XPath from the CSS in this case. You need to use the “css:” prefix or the long form selector in these cases.

Thanks for your reply. I was also thinking of a prefix maybe, but used "cssselector:", obviously didn't work.

But why are you saying that it is not possible to distinguish between them, isn't an xpath supposed to start with "//"? Or is that prefix intentionally left out from validation?

Anyway, thank you again for helping me out. Issue can be closed on my part.

**Comment by wakaleo** [comment]
XPath doesn't have to start with "//" (see https://www.w3schools.com/xml/xpath_syntax.asp), and there is no way (that I could find) to verify the syntax of a CSS expression, otherwise CSS would have been the default option.
