### ISSUE TITLE
is there a @after hook for every story line that is executed in serenity/jbehave

### ISSUE THREAD

**Issue by gitrak** [serenity-bdd/serenity-core#2068]
Scenario: New Connection
Meta:@NewConnection
Given Login with 'username' and 'password'
Given Create a new Account
And Create a order

what i needed was that after each story line executed, for ex ( Login with 'username' and 'password' ), 
i need to capture the story line as text in some sort of @after hook(which invoked after each story line is executed)

**Comment by wakaleo** [comment]
What problem are you trying to solve? Do you need to use JBehave? In Cucumber, you could use `AfterStep` for this.

**Comment by gitrak** [comment]
yes i am using serenity with jbehave...i want to store every story line in local DB  as the get successfully passed. this way i can look back in DB and check till which story line it got successfully passed.

**Comment by wakaleo** [comment]
if you are using the info after the tests, it might be easier just to use the JSON files generated by Serenity, which contain this information in great detail.

**Comment by gitrak** [comment]
actuallly i wanted to capture the story line string as they get executed and store it in local DB. but JSON should be getting geneated after the completion of test

**Comment by wakaleo** [comment]
There is no such hook in JBehave, though there is one in Cucumber.

**Comment by gitrak** [comment]
ok thanks wakaleo...please can you let me know the path of json which serenity creates
