### ISSUE TITLE
java.lang.ClassCastException: net.serenitybdd.core.pages.WebElementFacadeImpl cannot be cast to org.openqa.selenium.interactions.internal.Locatable

### ISSUE THREAD

**Issue by cvarshn-cloud** [serenity-bdd/serenity-core#2069]
java.lang.ClassCastException: net.serenitybdd.core.pages.WebElementFacadeImpl cannot be cast to org.openqa.selenium.interactions.internal.Locatable

getting this error for serenity version 2.2.1 and 2.2.2

I am using below method
public Actions mouseHover(WebElementFacade element) {
		Actions action = new Actions(getDriver());
		action.moveToElement(element).build().perform();
		return action;
	}

Mouse hover not working in serenity latest versions 2.x.x
_Originally posted by @cvarshn-cloud in https://github.com/serenity-bdd/serenity-core/issues/1012#issuecomment-623175410_

**Comment by wakaleo** [comment]
I can't reproduce this - can you provide a more detailed stack trace and/or a sample project reproducing the issue?

**Comment by cvarshn-cloud** [comment]
java.lang.ClassCastException: net.serenitybdd.core.pages.WebElementFacadeImpl cannot be cast to org.openqa.selenium.interactions.internal.Locatable
	at org.openqa.selenium.interactions.Actions.moveToElement(Actions.java:387)

this is the only stacktrace which is generated

**Comment by wakaleo** [comment]
`org.openqa.selenium.interactions.internal.Locatable` is a deprecated class in Selenium - what version of Selenium are you using?

**Comment by cvarshn-cloud** [comment]
I am not using any selenium dependency in my POM file. Is it required with serenity to add selenium dependencies?

**Comment by wakaleo** [comment]
Maybe do a dependency analysis - the Locatable class mentioned in the error is no longer used in Selenium (I checked the source code for that class)

**Comment by cvarshn-cloud** [comment]
I have updated dependencies to latest versions also added selenium dependencies as well but still same issue

**Comment by wakaleo** [comment]
Can you do a dependency analysis? The line referred to in the stack trace does not exist in Selenium 3.14.159.

**Comment by cvarshn-cloud** [comment]
I have added <dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.0.0-alpha-3</version>
		</dependency>
as well still not working for WebelementFacade element type.

**Comment by wakaleo** [comment]
Serenity is not compatible with selenium 4.0.0-alpha

**Comment by cvarshn-cloud** [comment]
This I have tried explicitly but I am not using selenium related dependencies in my POM

**Comment by cvarshn-cloud** [comment]
<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency>

		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20170516</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.8.0-alpha2</version>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.10.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.10.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>29.0-jre</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.1-901.jdbc4</version>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>datatable</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.galenframework</groupId>
			<artifactId>galen-java-support</artifactId>
			<version>2.3.7</version>
		</dependency>
		<dependency>
			<groupId>com.jcraft</groupId>
			<artifactId>jsch</artifactId>
			<version>0.1.50</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>4.6.0</version>
		</dependency>
		<dependency>
			<groupId>com.github.temyers</groupId>
			<artifactId>cucumber-jvm-parallel-plugin</artifactId>
			<version>5.0.0</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>gherkin</artifactId>
			<version>5.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
			<version>4.3.10.RELEASE</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay-webdriver</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber5</artifactId>
			<version>${serenity.cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>datatable-dependencies</artifactId>
			<version>1.1.14</version>
			<scope>test</scope>
		</dependency>

**Comment by cvarshn-cloud** [comment]
this is my dependency list

**Comment by wakaleo** [comment]
Can you do a maven dependency analysis and copy the results here?

**Comment by cvarshn-cloud** [comment]
i am using serenity 2.2.2

**Comment by cvarshn-cloud** [comment]
> Can you do a maven dependency analysis and copy the results here?

Any specific command for this?

**Comment by wakaleo** [comment]
`mvn dependency:tree -Dverbose`

**Comment by cvarshn-cloud** [comment]
[INFO] com.gl.odigo:regression-suite:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.1.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.1.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.3.RELEASE:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- org.springframework:spring-core:jar:5.1.5.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.1.5.RELEASE:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.23:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.1.3.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.1.3.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.1.3.RELEASE:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:test
[INFO] |  +- org.assertj:assertj-core:jar:3.11.1:test
[INFO] |  +- org.mockito:mockito-core:jar:2.23.4:compile
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.1.5.RELEASE:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.6.2:test
[INFO] +- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] +- org.json:json:jar:20170516:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.8.0-alpha2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  \- log4j:log4j:jar:1.2.17:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.10.0:test
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.10.0:test
[INFO] +- com.google.guava:guava:jar:29.0-jre:test
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:test
[INFO] |  +- org.checkerframework:checker-qual:jar:2.11.1:test
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:test
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:1.3:test
[INFO] +- org.apache.commons:commons-lang3:jar:3.8.1:test
[INFO] +- postgresql:postgresql:jar:9.1-901.jdbc4:compile
[INFO] +- io.cucumber:cucumber-core:jar:5.5.0:compile
[INFO] |  +- io.cucumber:cucumber-gherkin:jar:5.5.0:compile
[INFO] |  +- io.cucumber:cucumber-gherkin-vintage:jar:5.5.0:compile
[INFO] |  +- io.cucumber:tag-expressions:jar:2.0.4:compile
[INFO] |  +- io.cucumber:cucumber-expressions:jar:8.3.1:compile
[INFO] |  +- io.cucumber:cucumber-plugin:jar:5.5.0:compile
[INFO] |  +- io.cucumber:docstring:jar:5.5.0:compile
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.0:compile
[INFO] +- io.cucumber:cucumber-java:jar:5.5.0:compile
[INFO] +- io.cucumber:cucumber-junit:jar:5.5.0:test
[INFO] +- io.cucumber:datatable:jar:3.0.0:compile
[INFO] +- com.galenframework:galen-java-support:jar:2.3.7:compile
[INFO] |  +- com.galenframework:galen-rainbow4j:jar:2.3.7:compile
[INFO] |  \- com.galenframework:galen-core:jar:2.3.7:compile
[INFO] |     +- org.slf4j:slf4j-simple:jar:1.7.25:compile
[INFO] |     +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |     +- org.mozilla:rhino:jar:1.7.7.2:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.9.8:compile
[INFO] +- com.jcraft:jsch:jar:0.1.50:test
[INFO] +- net.masterthought:cucumber-reporting:jar:4.6.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.8:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |  |  \- commons-lang:commons-lang:jar:2.4:compile
[INFO] |  +- velocity-tools:velocity-tools:jar:1.4:compile
[INFO] |  +- joda-time:joda-time:jar:2.10.1:compile
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.1.1:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.11.3:compile
[INFO] |  +- com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:jar:20190325.1:compile
[INFO] |  \- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] +- com.github.temyers:cucumber-jvm-parallel-plugin:jar:5.0.0:compile
[INFO] |  \- org.projectlombok:lombok:jar:1.18.6:compile
[INFO] +- io.cucumber:gherkin:jar:5.1.0:compile
[INFO] |  \- io.cucumber:gherkin-jvm-deps:jar:1.0.4:compile
[INFO] +- org.springframework:spring-web:jar:4.3.10.RELEASE:test
[INFO] |  +- org.springframework:spring-aop:jar:5.1.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.1.5.RELEASE:compile
[INFO] |  \- org.springframework:spring-context:jar:5.1.5.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.1.5.RELEASE:compile
[INFO] +- net.serenity-bdd:serenity-core:jar:2.2.2:compile
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.9.10:compile
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.9.10:compile
[INFO] |  +- com.google.inject:guice:jar:4.2.2:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.ow2.asm:asm:jar:7.2:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.11:compile
[INFO] |  +- org.objenesis:objenesis:jar:3.0.1:compile
[INFO] |  +- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- io.vavr:vavr:jar:0.9.0:compile
[INFO] |  |  \- io.vavr:vavr-match:jar:0.9.0:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  +- com.sun.xml.bind:jaxb-core:jar:2.3.0.1:compile
[INFO] |  +- com.sun.xml.bind:jaxb-impl:jar:2.3.0.1:compile
[INFO] |  +- javax.activation:activation:jar:1.1.1:compile
[INFO] |  +- net.serenity-bdd:serenity-report-resources:jar:2.2.2:compile
[INFO] |  +- net.serenity-bdd:serenity-model:jar:2.2.2:compile
[INFO] |  |  +- commons-net:commons-net:jar:3.6:compile
[INFO] |  |  +- org.apache.commons:commons-text:jar:1.6:compile
[INFO] |  |  \- es.nitaur.markdown:txtmark:jar:0.16:compile
[INFO] |  +- net.serenity-bdd:serenity-reports:jar:2.2.2:compile
[INFO] |  |  \- net.serenity-bdd:serenity-stats:jar:2.2.2:compile
[INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.2.71:compile
[INFO] |  |        +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.2.71:compile
[INFO] |  |        \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-server:jar:3.141.59:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.14.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.14.0:compile
[INFO] |  |  +- com.beust:jcommander:jar:1.72:compile
[INFO] |  |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  +- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:jetty-repacked:jar:9.4.12.v20180830:compile
[INFO] |  |  +- com.squareup.okhttp3:okhttp:jar:3.11.0:compile
[INFO] |  |  +- com.squareup.okio:okio:jar:1.14.0:compile
[INFO] |  |  \- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:3.14.0:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-support:jar:3.14.0:compile
[INFO] |  +- com.paulhammant:ngwebdriver:jar:1.1.4:compile
[INFO] |  +- com.assertthat:selenium-shutterbug:jar:0.9.3:compile
[INFO] |  |  \- com.github.zafarkhaja:java-semver:jar:0.9.0:compile
[INFO] |  +- com.codeborne:phantomjsdriver:jar:1.4.4:compile
[INFO] |  +- org.seleniumhq.selenium:htmlunit-driver:jar:2.33.0:compile
[INFO] |  +- io.appium:java-client:jar:7.3.0:compile
[INFO] |  |  +- commons-validator:commons-validator:jar:1.6:compile
[INFO] |  |  |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  |  |  \- commons-digester:commons-digester:jar:1.8.1:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.2:compile
[INFO] |  +- org.springframework:spring-context-support:jar:5.1.5.RELEASE:compile
[INFO] |  +- org.codehaus.groovy:groovy:jar:2.5.6:compile
[INFO] |  +- net.sf.opencsv:opencsv:jar:2.0:compile
[INFO] |  +- commons-beanutils:commons-beanutils-core:jar:1.8.3:compile
[INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.9:compile
[INFO] |  |  +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  |  \- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- org.freemarker:freemarker:jar:2.3.28:compile
[INFO] |  +- net.sourceforge.jexcelapi:jxl:jar:2.6.12:compile
[INFO] |  +- net.sourceforge.htmlunit:htmlunit:jar:2.33:compile
[INFO] |  |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.33:compile
[INFO] |  |  +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.33:compile
[INFO] |  |  |  \- xerces:xercesImpl:jar:2.12.0:compile
[INFO] |  |  +- net.sourceforge.htmlunit:htmlunit-cssparser:jar:1.2.0:compile
[INFO] |  |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.4.14.v20181114:compile
[INFO] |  |     +- org.eclipse.jetty:jetty-client:jar:9.4.14.v20181114:compile
[INFO] |  |     |  \- org.eclipse.jetty:jetty-http:jar:9.4.14.v20181114:compile
[INFO] |  |     +- org.eclipse.jetty:jetty-xml:jar:9.4.14.v20181114:compile
[INFO] |  |     +- org.eclipse.jetty:jetty-util:jar:9.4.14.v20181114:compile
[INFO] |  |     +- org.eclipse.jetty:jetty-io:jar:9.4.14.v20181114:compile
[INFO] |  |     \- org.eclipse.jetty.websocket:websocket-common:jar:9.4.14.v20181114:compile
[INFO] |  |        \- org.eclipse.jetty.websocket:websocket-api:jar:9.4.14.v20181114:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.7:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.7:compile
[INFO] |  +- org.fluentlenium:fluentlenium-core:jar:0.10.2:compile
[INFO] |  +- com.jhlabs:filters:jar:2.0.235:compile
[INFO] |  +- org.asciidoctor:asciidoctorj:jar:1.5.6:compile
[INFO] |  |  \- org.jruby:jruby-complete:jar:1.7.26:runtime
[INFO] |  +- org.imgscalr:imgscalr-lib:jar:4.2:compile
[INFO] |  +- javax.el:javax.el-api:jar:2.2.4:compile
[INFO] |  +- org.glassfish.web:javax.el:jar:2.2.4:compile
[INFO] |  +- xalan:xalan:jar:2.7.2:compile
[INFO] |  +- xalan:serializer:jar:2.7.2:compile
[INFO] |  +- org.awaitility:awaitility:jar:4.0.1:compile
[INFO] |  |  \- org.hamcrest:hamcrest:jar:2.1:compile
[INFO] |  +- com.typesafe:config:jar:1.3.1:compile
[INFO] |  +- com.google.jimfs:jimfs:jar:1.1:compile
[INFO] |  \- com.vladsch.flexmark:flexmark-all:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-abbreviation:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-admonition:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-anchorlink:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-aside:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-attributes:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-autolink:jar:0.34.30:compile
[INFO] |     |  \- org.nibor.autolink:autolink:jar:0.6.0:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-definition:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-emoji:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-enumerated-reference:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-escaped-character:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-footnotes:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-issues:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-tables:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-tasklist:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-users:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gitlab:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-jekyll-front-matter:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-jekyll-tag:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-media-tags:jar:0.34.30:compile
[INFO] |     |  \- com.vladsch.flexmark:flexmark-test-util:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-ins:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-xwiki-macros:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-superscript:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-tables:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-toc:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-typographic:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-yaml-front-matter:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-youtube-embedded:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-formatter:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-html-parser:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-jira-converter:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-pdf-converter:jar:0.34.30:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-core:jar:0.0.1-RC13:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-pdfbox:jar:0.0.1-RC13:compile
[INFO] |     |  |  +- org.apache.pdfbox:pdfbox:jar:2.0.8:compile
[INFO] |     |  |  |  \- org.apache.pdfbox:fontbox:jar:2.0.8:compile
[INFO] |     |  |  +- org.apache.pdfbox:xmpbox:jar:2.0.8:compile
[INFO] |     |  |  \- de.rototor.pdfbox:graphics2d:jar:0.12:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-rtl-support:jar:0.0.1-RC13:compile
[INFO] |     |  |  \- com.ibm.icu:icu4j:jar:59.1:compile
[INFO] |     |  \- com.openhtmltopdf:openhtmltopdf-jsoup-dom-converter:jar:0.0.1-RC13:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-profile-pegdown:jar:0.34.30:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-util:jar:0.34.30:compile
[INFO] |     \- com.vladsch.flexmark:flexmark-youtrack-converter:jar:0.34.30:compile
[INFO] +- net.serenity-bdd:serenity-junit:jar:2.2.2:compile
[INFO] +- net.serenity-bdd:serenity-screenplay:jar:2.2.2:compile
[INFO] +- net.serenity-bdd:serenity-screenplay-webdriver:jar:2.2.2:compile
[INFO] +- net.serenity-bdd:serenity-cucumber5:jar:2.2.0:compile
[INFO] |  +- io.cucumber:datatable-matchers:jar:3.3.0:compile
[INFO] |  \- org.apache.commons:commons-csv:jar:1.5:compile
[INFO] +- net.serenity-bdd:serenity-rest-assured:jar:2.2.2:compile
[INFO] |  +- io.rest-assured:rest-assured:jar:3.1.1:compile
[INFO] |  |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:compile
[INFO] |  |  +- io.rest-assured:json-path:jar:3.1.1:compile
[INFO] |  |  |  \- io.rest-assured:rest-assured-common:jar:3.1.1:compile
[INFO] |  |  \- io.rest-assured:xml-path:jar:3.1.1:compile
[INFO] |  +- org.codehaus.groovy:groovy-xml:jar:2.5.6:compile
[INFO] |  \- org.codehaus.groovy:groovy-json:jar:2.5.6:compile
[INFO] +- junit:junit:jar:4.12:compile
[INFO] +- org.hamcrest:hamcrest-all:jar:1.3:compile
[INFO] \- io.cucumber:datatable-dependencies:jar:1.1.14:test

**Comment by wakaleo** [comment]
The `selenium-java` dependency is wrong (should be 3.141.59)

**Comment by cvarshn-cloud** [comment]
+- org.seleniumhq.selenium:selenium-java:jar:3.14.0:compile I haven't added any dependency for selenium how to update this to new version.

**Comment by wakaleo** [comment]
It should be automatic, there must be another dependency in your project overriding it.

**Comment by cvarshn-cloud** [comment]
ok

**Comment by wakaleo** [comment]
When you run `mvn dependency:tree -Dverbose` (with the verbose option) Maven will show you the conflicts

**Comment by cvarshn-cloud** [comment]
[INFO] Verbose not supported since maven-dependency-plugin 3.0

**Comment by cvarshn-cloud** [comment]
Issue resolved by updating spring boot parent version
