### ISSUE TITLE
"issue tracker url" can't create an url in cucumber feature

### ISSUE THREAD

**Issue by kzokv** [serenity-bdd/serenity-core#2070]
Hi, I have below maven dependancies for my project 

```
serenity-core: 2.1.7
serenity-cucumber4: 2.1.2
```

Currently I'm facing an issue that ```serenity.issue.tracker.url``` (my serenity.properties locates under root level path of project) isn't creating a clickable URL for cucumber feature and scenario in Serenity-BDD report by using @issue:<issueId> as expected written in this document: https://github.com/serenity-bdd/serenity-documentation/blob/master/src/asciidoc/serenity-issues.adoc

```
//my feature file
@issue:dummy-id111
Feature: Test sign-up
  As a new Test user
  I want to be able to sign up with Facebook account
  so that I can use fancy TestApp services

  For example:
  {Examples} Sign in Test
```

Here's what I'm seeing:
![image](https://user-images.githubusercontent.com/18299695/80943385-a6ae7880-8e19-11ea-8c2b-b3fc0cbb94cf.png)

Same issue occurs at scenario level.

However, I couldn't find any related information about ```serenity.issue.tracker.url``` in serenity handbook - https://serenity-bdd.github.io/theserenitybook/latest/

Would you please let me know if this feature is obsolete or it's an issue with the version I'm currently using? Thank you.

**Comment by wakaleo** [comment]
What value did you set for `serenity.issue.tracker.url`?

**Comment by kzokv** [comment]
Hi, we are using notion so I set the value to below:
```
serenity.issue.tracker.url = https://www.notion.so/<our-custom-project>/{0}
```

**Comment by globalworming** [comment]
see http://thucydides.info/docs/serenity-staging/#_integrating_with_jira

shouldnt it be `@issue:#dummy-id111` ?

**Comment by kzokv** [comment]
Hi,
As far as I understand, http://thucydides.info/docs/serenity-staging/#_integrating_with_jira is for JIRA integration, but what I need is to integrate with notion and 
```
serenity.issue.tracker.url
``` 
should be the one to use.

**Comment by kzokv** [comment]
Hi, any updates on this topic?

**Comment by wakaleo** [comment]
Try:
```
@issue:DUMMY-id111
Feature: Test sign-up
  As a new Test user
  I want to be able to sign up with Facebook account
  so that I can use fancy TestApp services

  For example:
  {Examples} Sign in Test
```

**Comment by kzokv** [comment]
Great, it works now. Thank you.
