### ISSUE TITLE
SerenityRest not reporting Request Params in HTML Report

### ISSUE THREAD

**Issue by SengCheong** [serenity-bdd/serenity-core#2076]
Hi,

I am unable to view the request body when issuing a rest-assured request with SerenityRest.

<img width="1388" alt="Screen Shot 2020-05-09 at 10 23 05 AM" src="https://user-images.githubusercontent.com/31485862/81461557-57809300-91df-11ea-9f24-98e87f16d9ce.png">

This is in contrast to the screenshot present in this tutorial book:
https://serenity-bdd.github.io/theserenitybook/0.1.0/serenity-rest.html

I performed an initial analysis, and discovered that: https://github.com/serenity-bdd/serenity-core/blob/fcbcb27f4eacdc2e757de8c3cac2dc3f8ff017c0/serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestReportingHelper.java#L44-L62
does not record the request body or params e.g. when using .formParams().

I tried setting a custom RestReportingHelper that adds .withParameters() to the rest query, but there was no change in the generated report.

My dependencies are:
- serenity-jbehave:1.4.6
- serenity-core: 2.2.1
- serenity-rest-assured:2.2.1
- serenity-junit: 2.2.1

Upgrading the dependencies to 2.2.4 did not fix the issue

**Comment by wakaleo** [comment]
Could you propose a PR?

**Comment by SengCheong** [comment]
Sorry Wakaleo, I have been busy and I did not had the time into looking for a possible solution. From my understanding, it seems that the problem might also extend all the way into the way the HTML report is generated, especially regarding the HTMLAcceptanceTestReporter.java class

I do not have the time currently to investigate how the HTMLAcceptanceTestReporter works at the moment, so I highly suggest you tag this issue as a bug currently. I will see if i am avaliable to propose a PR
