### ISSUE TITLE
[Question] How do I report assertions using ensure for junit-web which is not a bdd style?

### ISSUE THREAD

**Issue by ramkumar-yoganathan** [serenity-bdd/serenity-core#2078]
I have created a project as similar like https://github.com/serenity-bdd/serenity-junit-starter. I have used as given below to report the assertions.

`Ensure.that(ElementLocated.by(By.id(USERNAME))).isDisplayed();`

I am not able to see the report with assertions. Could you please help me on this?

**Comment by wakaleo** [comment]
The Ensure class only works with Screenplay - there is no equivalent functionality in normal non-Screenplay code. You can use AssertJ but it will not report the assertions unless they fail.
