### ISSUE TITLE
serenity-reports show duplicate features?

### ISSUE THREAD

**Issue by jesusop** [serenity-bdd/serenity-core#2079]
Hi, 
1. The report shows duplicate features:
![1](https://user-images.githubusercontent.com/59234405/81742705-2b2a7800-9466-11ea-8ab3-8a6da18d7ceb.PNG)

2. My Structure:
![2](https://user-images.githubusercontent.com/59234405/81742754-37163a00-9466-11ea-8a9d-66ea54a9754e.PNG)

4. Content:
![4](https://user-images.githubusercontent.com/59234405/81742940-780e4e80-9466-11ea-93ae-3aa205f6c369.PNG)

3. Version:
![3](https://user-images.githubusercontent.com/59234405/81742769-3c738480-9466-11ea-88b2-123665983f41.PNG)

**Comment by wakaleo** [comment]
This is a known issue: the workaround is to place your features in a subdirectory under the features directory.

**Comment by jesusop** [comment]
it works, thnks u
