### ISSUE TITLE
Not able to add customfields such as application version, user etc. in serenity single page html report

### ISSUE THREAD

**Issue by kreigy1310garg** [serenity-bdd/serenity-core#2081]
Not able to add customfields such as application version, user etc. in serenity single page html report.

I am using following version 
SerenityCoreVersion = 2.1.5
SerenityScreenPlayCoreVersion = 2.1.5
SerenityCucumberVersion = 1.9.50

This is my build.gradle

repositories {
    mavenCentral()
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:${SerenityCoreVersion}")
        classpath("net.serenity-bdd:serenity-single-page-report:${SerenityCoreVersion}")
        classpath("net.serenity-bdd:serenity-json-summary-report:${SerenityCoreVersion}")   
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'net.serenity-bdd.aggregator'

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {

    testCompile "net.serenity-bdd:serenity-junit:${SerenityCoreVersion}"
    testCompile "net.serenity-bdd:serenity-rest-assured:${SerenityCoreVersion}"
    testCompile "net.serenity-bdd:serenity-cucumber:${SerenityCucumberVersion}"
    testCompile "org.assertj:assertj-core:${assertJVersion}"
    testCompile "ch.qos.logback:logback-classic:${logVersion}"
    testCompile "net.serenity-bdd:serenity-core:${SerenityCoreVersion}"
    testCompile "com.googlecode.json-simple:json-simple:${gsonVersion}"
    testCompile "org.skyscreamer:jsonassert:${jsonAssertVersion}"
    testCompile  "mysql:mysql-connector-java:${mysqlVerison}"
}

serenity {
    reports = ["single-page-html","json-summary"]
}

test {
    testLogging.showStandardStreams = true
    }
gradle.startParameter.continueOnFailure = true

test.finalizedBy(aggregate)

Serenity.properties 
report.customfields.ApplicationVersion = 1.2.3
report.customfields.environment = staging

I am able to generate the reports but not able to add the customfields . Working with windows10, openjdk 11.

could you please look into the same ?

#Request : Could you please let me know how to generate serenity reports folder with date and time using gradle. I am able to generate it using maven -surfire plugin in maven but not getting a way to the same gradle. If you have any solution for the same.

**Comment by wakaleo** [comment]
I can't reproduce this - try with the latest version of Serenity.

**Comment by wakaleo** [comment]
![image](https://user-images.githubusercontent.com/55986/81828582-da805100-9531-11ea-83c6-938b21a914c9.png)
