### ISSUE TITLE
Serenity report is too heavy

### ISSUE THREAD

**Issue by qaschevychelov** [serenity-bdd/serenity-core#2082]
I'm running 600 test cases. Is it normal that serenity report weighs about 2.1Gb?
What can i do to decrease serenity report weight?

**Comment by wakaleo** [comment]
Probably. You can reduce the size by taking fewer screenshots.

**Comment by qaschevychelov** [comment]
I use the following versions
        <serenity.version>1.9.20</serenity.version>
        <serenity.cucumber.version>1.9.8</serenity.cucumber.version>
        <serenity.rest.assured.version>1.9.20</serenity.rest.assured.version>
I take screenshots on failures. Average failure rate is <= 5% (~30 failures)

**Comment by wakaleo** [comment]
If you only take screenshots on failures then there is not a lot to do. Try with a more recent version, we optimised the report generation somewhat in Serenity 2.x

**Comment by qaschevychelov** [comment]
I'm trying to update serenity a little bit later. Will comment here

**Comment by qaschevychelov** [comment]
I was trying to update serenity-core to 2.2.5, but i stumbled upon with compatibility issues. CucumberOptions annotation is not found.
What versions can i use?

**Comment by wakaleo** [comment]
The package has probably changed

**Comment by qaschevychelov** [comment]
It used to be cucumber.api.CucumberOptions
In 2.2.5 version it is io.cucumber... 
But i can't find any package with this annotation in io.cucumber.

**Comment by wakaleo** [comment]
```
import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        features = "src/test/resources/features"
)
public class FullTestSuite {}
```
