### ISSUE TITLE
[Question] How do I convert the Question<String> for further sanitization?

### ISSUE THREAD

**Issue by ramkumar-yoganathan** [serenity-bdd/serenity-core#2084]
I have a Question class as defined.

```
 public static Question<String> defaultLocation()
    {
        return actor -> Value.of(CreatePage.CREATE).viewedBy(actor).asString();
    }
```
The issue is defaultLocation comes with few escape charcters such as newline. When I use the asString value, the validation fails in test level.

How do I convert the Question<String> in to String then remove the escape characters and Send it back to test for validation.

Thanks,
Ram

**Comment by wakaleo** [comment]
Just do whatever manipulation you need to do in the Question lambda itself, e.g.

```
    public static Question<String> defaultLocationInUpperCase()
    {
        return actor -> Value.of(TodoList.CLEAR_COMPLETED).viewedBy(actor).asString().toUpperCase();
    }
    
```

**Comment by ramkumar-yoganathan** [comment]
Thanks
