### ISSUE TITLE
NPE in SerenityRest.lastResponse()

### ISSUE THREAD

**Issue by globalworming** [serenity-bdd/serenity-core#2089]
serenity v2.2.7

i tried to use the `SessionFilter` but somehow I get weird null pointer exceptions. Am I missing something? Please see
```
package com.test;

import io.restassured.filter.session.SessionFilter;
import io.restassured.specification.RequestSpecification;
import net.serenitybdd.junit.runners.SerenityRunner;
import net.serenitybdd.screenplay.Actor;
import net.serenitybdd.screenplay.rest.abilities.CallAnApi;
import net.serenitybdd.screenplay.rest.interactions.Get;
import org.junit.Test;
import org.junit.runner.RunWith;

import static net.serenitybdd.screenplay.rest.questions.ResponseConsequence.seeThatResponse;

@RunWith(SerenityRunner.class)
public class SessionFilterTest {

  Actor actor = Actor.named("actor").whoCan(CallAnApi.at("https://graphql.contentful.com/content/v1/spaces/f8bqpb154z8p/environments/master"));

  @Test
  public void throwsNPE() {
    actor.attemptsTo(Get.resource("/").with(request -> request.filter(new SessionFilter())));
    actor.should(seeThatResponse("bad request", response -> response.statusCode(304)));

  }

  @Test
  public void alsoThrowsNPE() {
    actor.attemptsTo(Get.resource("/").with(request -> {
      request.param("k", "v");
      return request.filter(new SessionFilter());
    }));
    actor.should(seeThatResponse("bad request", response -> response.statusCode(304)));

  }

  @Test
  public void works() {
    actor.attemptsTo(Get.resource("/").with(request -> {
      request.filter(new SessionFilter());
      return request.param("k", "v");
    }));
    actor.should(seeThatResponse(response -> response.statusCode(401)));

  }

  @Test
  public void alsoNPE() {
    actor.attemptsTo(Get.resource("/").with((RequestSpecification request) -> request.filter(new SessionFilter()).param("k", "v")));
    actor.should(seeThatResponse(response -> response.statusCode(401)));
  }
}

```
when it works,  it also sends the correct parameters and remembers the session from the setCookie header :shrug:

**Comment by wakaleo** [comment]
Not really - you might have to dig into the stack trace to see what is going on.

**Comment by globalworming** [comment]
Meh, I'd rather not, that looks pretty deep :) but i guess i have no choice

**Comment by wakaleo** [comment]
@cliviu might be able to help, I think he did some work on that area of the code base not too long ago.

**Comment by wakaleo** [comment]
@cliviu might be able to help, I think he did some work on that area of the code base not too long ago.

**Comment by globalworming** [comment]
this is gonna be another headache inducing thing, isn't it..
when debugging, i can the the lastResponse is set.... but null when I check it later with SerenityRest -.-
![image](https://user-images.githubusercontent.com/2108984/82370793-62c29280-9a19-11ea-835a-5b7565f43698.png)
![image](https://user-images.githubusercontent.com/2108984/82370815-6eae5480-9a19-11ea-9db9-2c2c7474db53.png)

so i googled @cliviu and he lives like 45 minutes away, I could just go meet him (maintaining distance) :)
