### ISSUE TITLE
jbehave / stories with comments are marked as PENDING

### ISSUE THREAD

**Issue by patrykost** [serenity-bdd/serenity-core#2090]
When there is a comment in .story file then all steps are not running and marked as PENDING.
i.e. : "!-- POSITIVE"

**Comment by wakaleo** [comment]
That's a JBehave issue, not a Serenity issue. I'm not sure comments are supported in JBehave.

**Comment by patrykost** [comment]
Hi @wakaleo,
I see it different, since it works with serenity 2.0.81, but not in higher versions - I've tried with 2.2.5 too.
Could you check it please?

**Comment by wakaleo** [comment]
JBehave integration isn't actively supported in newer versions (we recommend using Cucumber).

**Comment by patrykost** [comment]
I know jbehave is not actively supported, but what about bug fixing ? ;)

**Comment by wakaleo** [comment]
The simplest option is either to dig into the code itself or to raise a commercial support ticket (if you are interested in that option I can send you a link with details).

**Comment by patrykost** [comment]
I would rather dig into code or better say bye to jbehave and hello to cucumber :)

**Comment by wakaleo** [comment]
Cucumber is a better long-term bet I would say.
