### ISSUE TITLE
Element visible in devtools, but seen as not visible by serenity

### ISSUE THREAD

**Issue by ioanaDinescu** [serenity-bdd/serenity-core#2091]
Hello,

I have a column with checkboxes such as the one bellow
![image](https://user-images.githubusercontent.com/28264061/82255581-8e804280-995d-11ea-99d6-e34cdb2a3198.png)

When I try to click on one  of them accessing it with xpath, serenity throws an element not visible exception.
I need to mention that:
1) Path is correct, checked in devtools with both xpath and jquery. I also checked visibility with jquery and is true.
2) The div-parent of input/label is seen as visible by serenity.
3) Presence.of(#checkbox) returns true, but Visibility.of(#checkbox) returns false.
4) WaitUntil(#checkbox, isVisisble()) throws net.serenitybdd.core.exceptions.SerenityManagedException: 
Expected: an element that is visible
     but: no matching element found by xpath:

**Comment by wakaleo** [comment]
Serenity is reporting what Selenium tells it - "no matching element found by xpath". Could be an issue with frames? I would put a breakpoint and see what WebDriver can actually find.

**Comment by ioanaDinescu** [comment]
No, the table is outside any frame. Also tried with debug and everything seems fine from webdriver POV too. 
Shouldn't it normally return "no matching element found by xpath" when asked for its presence as well?

**Comment by wakaleo** [comment]
So "#checkbox" is, according to Selenium, in the DOM but not rendered (or covered by something else). What do you mean "everything seems fine from webdriver POV"?

**Comment by ioanaDinescu** [comment]
I could see/ check it in devtools, but as soon as it tries to do any action on it immediately throws not visible error.

Usually when it is covered by something else it says that another element receives the click. Also Selenium sees if #checkbox state changes from checked to unchecked...

**Comment by wakaleo** [comment]
What makes you think this is a Serenity issue?

**Comment by ioanaDinescu** [comment]
This is what I'm trying to find out if its a Serenity (or Selenium issue) regarding checkboxes in table or something else.

**Comment by wakaleo** [comment]
Serenity mostly just wraps Selenium - sometimes it adds some extra wait logic and checks (which can sometimes have an effect). The way to check is to look up a WebElement using getDriver() and see if that behaves differently.

**Comment by ioanaDinescu** [comment]
Ok. I'll look furter into it. Thank you for your time. :)
