### ISSUE TITLE
chrome.switches="--lang=en-us" is  not updating my webpage language

### ISSUE THREAD

**Issue by gopal3008** [serenity-bdd/serenity-core#2098]
I am working on a retail website and the native language is some European country . I want to change it to English. I am using chrome.switches like below

but nothing happens.

chrome.switches="--lang=en-us;--incognito;--start-maximized"
Even though browser opens in incognito mode but the language is not getting changed

**Comment by gopal3008** [comment]
Is it enough to just mention below changes in serenity.conf or do we have to tell my script specifically to change the language. If yes then how can we do that.
chrome.switches="--lang=en-us;--incognito;--start-maximized"

**Comment by wakaleo** [comment]
The chrome.switches options should be sufficient.

**Comment by gopal3008** [comment]
I have done the same in my serenity.conf file
chrome.switches="--lang=en-us"
Its not working page is still opening in native language.

**Comment by globalworming** [comment]
check https://browserspy.dk/language.php with different languages and ensure it changes something

**Comment by gopal3008** [comment]
tried to do but sadly it didn't work. Any other suggestion.

**Comment by wakaleo** [comment]
Could be a driver issue. Does it work in plain selenium?

**Comment by globalworming** [comment]
the `--lang` option did nothing for me.. setting `intl.accept_languages` did though
https://stackoverflow.com/a/50602007/1359903

**Comment by globalworming** [comment]
setting `chrome_preferences.intl.accept_languages=ja-jp` in the serenity.properties did work

**Comment by gopal3008** [comment]
I will try this.

**Comment by globalworming** [comment]
any luck @gopal3008 ?
