### ISSUE TITLE
Could not change the report project title through setting property "serenity.project.name".

### ISSUE THREAD

**Issue by ldy810** [serenity-bdd/serenity-core#2100]
Hi,
     I clone the project  "serenity-junit-starter-master", then try to change the "serenity.project.name" value in "Serenity.properties". but doesn't work on the generated report. I try the latest version, and "2.2.0", '2.0.91'.

**Comment by wakaleo** [comment]
I can't reproduce this. Are you sure the file is called `serenity.properties` (in lower case) and is at the root of your project?

**Comment by ldy810** [comment]
Yes, I am sure, could you tell me the senerity-core  version what you try?

**Comment by wakaleo** [comment]
2.2.8

![image](https://user-images.githubusercontent.com/55986/82532275-e921c600-9b38-11ea-89d6-45d2b7272cbc.png)

```mvn clean verify```

![image](https://user-images.githubusercontent.com/55986/82532329-08205800-9b39-11ea-813a-ce333763f797.png)

**Comment by ldy810** [comment]
It is so weird, I run many times and use the gradle refresh the project. it is ok now. Thanks a lot!

**Comment by ldy810** [comment]
Hi,
    I found the reason, could not update the report title,  when I run the test one time, and jvm not shut down, then change the  property, re-run it. the system will start a new jvm. and the report title should not changed. but the title of the test result page for each test details was updated.
![image](https://user-images.githubusercontent.com/6262632/82624625-a4b82800-9c15-11ea-9382-ee50c8531524.png)
![image](https://user-images.githubusercontent.com/6262632/82624703-cfa27c00-9c15-11ea-93e7-be39b6a7ed09.png)

**Comment by ldy810** [comment]
when I end the two jvm processes, then rerun, the report title is ok, can be changed normally,  So maybe set these report parameters as global variables. once the test finished, it will  be cleared automatically by jvm.

**Comment by wakaleo** [comment]
The test title should be considered static for a project - it's not intended to change for different tests, if that is what you are trying to do. The reports for individual tests are generated when they are run, and the pages for the overviews are generated during the aggregate phase, so if you change the property between the runs, you will get different titles.

**Comment by ldy810** [comment]
Yes, I agree with you, But I want to  add some  additional information to report title, it is not necessary.
