### ISSUE TITLE
NullPointerException at PageObject.open and browser is not invoked

### ISSUE THREAD

**Issue by ahuja-ankur** [serenity-bdd/serenity-core#2103]
When I try to run the same code with serenity-core 2.2.7 version, it does not runs fine and the browser does not get invoked.
I debugged the PageObject.Class file, the pageutils value is coming blank for my page class.
The error I got is - 
java.lang.NullPointerException
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:803)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:792)
	at com.<myproject>.pages.LoginPage.openURL(LoginPage.java:43)

LoginPage code is :

42    public void openURL() {
43        open();
44        getDriver().manage().window().maximize();
45    }

When I try to run the same code with serenity-core 1.9.31 version, it runs fine and the browser gets invoked fine without any issue.

Any idea what is missing here?

**Comment by wakaleo** [comment]
Can you provide a sample project?

**Comment by ahuja-ankur** [comment]
sorry cant share the code base, client code.

**Comment by wakaleo** [comment]
Can you produce a sample project starting with one of the starter projects that reproduces the issue?

**Comment by ahuja-ankur** [comment]
yupp....will share soon.

**Comment by ahuja-ankur** [comment]
Here is the sample code. please take a look https://github.com/ahuja-ankur/sample-Proj.git

**Comment by ahuja-ankur** [comment]
Nevermind, I found the issue and this is resolved now.

**Comment by chrisbrinkmann** [comment]
> Nevermind, I found the issue and this is resolved now.

What was the solution? I am having the same issue.
