### ISSUE TITLE
using Serenity with junit @beforeclass method

### ISSUE THREAD

**Issue by erdelyizsolt** [serenity-bdd/serenity-core#2107]
I tried to use Serenity framework with junit. For my testsuite i need to iniate some steps before all testsuite, not for every tests in class, so i tried it with junit @BeforeClass annotation. It seems it need to be a static method, and for this i can not use serenity steps for that. with a @Before method, what is not a mandatory to be static works flawless. There is any workaround or usecase for that with Serenity?
here is my test class code:
`@RunWith(SerenityRunner.class)
public class Login_Test extends TestBase {

    @Managed(driver = "chrome", uniqueSession = true)
  static  WebDriver driver;

    @Steps
    static
    NewSystemFormHuPage form;

    @Steps
    static
    NewSystemActions newsystem;

    @BeforeClass
    public static void init(){
        form.openForm();
        newsystem.init();
    }

    @Before
    public void everyMethodInit(){
        System.out.println("minden method elott");
    }

    @Test
    @Title("ez meg a valid login")
    public void validLogin() {
        System.out.println("valid login");
    }

    @Test
    @Title("ez itt invalid login")
    public void invalidLogin(){
        System.out.println("invalid login");
    }

    @Test
    @Title("a forgot pass szovege")
    public void forgotPassword(){
        System.out.println("forgot password");
    }

    @AfterClass
    public static void tearDown(){
        System.out.println("takaritas");
    }
}
`
i got a nullpointerexception in the init() method. Any suggestion?

**Comment by wakaleo** [comment]
Static methods won't work for this, and would fail if you need to run the tests in parallel. A more flexible approach would be to use a threadsafe flag and a lazy strategy (e.g. a method that performs the required set up only if it has not already been done).
