### ISSUE TITLE
Error executing EdgeDriver with Serenity

### ISSUE THREAD

**Issue by mvillmow89** [serenity-bdd/serenity-core#2108]
I am receiving the following error when I set the "webdriver.edge.driver" property in either the serenity.conf and serenity.properties file:

`"net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.edge.EdgeDriver (The path to the driver executable must be set by the webdriver.edge.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/MicrosoftWebDriver. The latest version can be downloaded from http://go.microsoft.com/fwlink/?LinkId=619687). See below for more details."`

serenity.conf:
```
drivers {
  windows {
    webdriver.chrome.driver = src/test/resources/drivers/windows/chromedriver.exe
    webdriver.gecko.driver = src/test/resources/drivers/windows/geckodriver.exe
    webdriver.edge.driver = src/test/resources/drivers/windows/msedgedriver.exe
    webdriver.ie.driver = src/test/resources/drivers/windows/IEDriverServer.exe
    phantomjs.binary.path = src/test/resources/drivers/windows/phantomjs.exe
  }
  mac {
    webdriver.chrome.driver = src/test/resources/drivers/mac/chromedriver
    webdriver.gecko.driver = src/test/resources/drivers/mac/geckodriver
	phantomjs.binary.path = src/test/resources/drivers/mac/phantomjs
  }
  linux {
    webdriver.chrome.driver = src/test/resources/drivers/linux/chromedriver
    webdriver.gecko.driver = src/test/resources/drivers/linux/geckodriver
  }
}

```
serenity.properties:
```
webdriver.driver=edge
#firefox, chrome,iexplorer,phantomjs,htmlunit,edge
webdriver.edge.driver = resources/drivers/windows/msedgedriver.exe

```
(also changed to drivers.windows.webdriver.edge.driver = resources/drivers/windows/msedgedriver.exe)

serenity-core version - 2.2.5 (although I have tested mutliple previous versions as well)
Edge version: 83.0.478.37 (Official build) (64-bit)

Other browser drivers work - Chrome, IE, firefox
I have downloaded the correct driver version for my browser. I have also tested my Edge/Edge Driver configuration in a selenium project that does not use serenitybdd and it works.

When I set the System.setProperty value to configure the edge driver, the driver works as expected. 
System.setProperty("webdriver.edge.driver", "src/test/resources/drivers/windows/msedgedriver.exe");"
It is only when I try to configure using the serenity properties/conf files that the edge driver does not instantiate. 

Let me know if you need any further information.

**Comment by globalworming** [comment]
in general it is recommended to create a minimal example git repo (maybe based on the junit-starter project) to reproduce the problem. the minimal test i think is "when having webdriver.edge.driver set in properties or conf, when I start a test, the property is set and points to the right location"

**Comment by mvillmow89** [comment]
@globalworming - no problem, I will create a minimal example. Thank you.

**Comment by n0n0t** [comment]
hi,
im havign same issue, any update on this?

**Comment by wakaleo** [comment]
Put a breakpoint in the EdgeDriverProvider and see what it is doing, in particular compared with the InternetExplorerDriverProvider class.

**Comment by n0n0t** [comment]
@wakaleo i checked both, Edge is using depreceated constructor to create EdgeDriver
`	  @Deprecated
	  public EdgeDriver(Capabilities capabilities) {
	    this(EdgeDriverService.createDefaultService(), capabilities);
	  }` 
but internet explorer si using
`	  @Deprecated
	  public EdgeDriver(Capabilities capabilities) {
	    this(EdgeDriverService.createDefaultService(), capabilities);
	  }`

could this be the issue? im new to serenity

**Comment by wakaleo** [comment]
Maybe add an equivalent for Edge, do a local build, and see if it works?

**Comment by n0n0t** [comment]
im having an issue with local build,
Build file 'C:\IdeaProjects\serenity-core\build.gradle' line: 21

Plugin [id: 'org.ajoberstar.release-opinion', version: '1.7.2'] was not found in any of the following sources:

**Comment by n0n0t** [comment]
I've tried both approaches, the problem still persist, any other ideas?

**Comment by wakaleo** [comment]
I would think that adding an equivalent of the updateIEDriverBinaryIfSpecified() should do the trick.

**Comment by n0n0t** [comment]
ive added:
`    private void updateEdgeDriverBinaryIfSpecified() {

        File executable = DriverServiceExecutable.called("EdgeDriver.exe")
                .withSystemProperty(WEBDRIVER_EDGE_DRIVER.getPropertyName())
                .usingEnvironmentVariables(environmentVariables)
                .reportMissingBinary()
                .downloadableFrom("https://github.com/SeleniumHQ/selenium/wiki/EdgeDriver")
                .asAFile();

        if (executable != null && executable.exists()) {
            System.setProperty("webdriver.edge.driver", executable.getAbsolutePath());
        }
    }`

**Comment by n0n0t** [comment]
any update on this, or anything else where should I look?

**Comment by wakaleo** [comment]
Does this change work for you? I don’t use Windows so IE support is mostly community driven.

**Comment by n0n0t** [comment]
it doesn't work, is there anybody else who could help me with it, or got it working?

**Comment by kiranAdiga** [comment]
@wakaleo  @n0n0t  @globalworming  is this working fine now ?

**Comment by mrjcohen** [comment]
I dont think so. I just tried using the latest version (2.4.4) and am getting the same error message.

**Comment by wakaleo** [comment]
Have a look at the code and raise a PR - I don't think that property is supported

**Comment by kiranAdiga** [comment]
@wakaleo @mrjcohen  Thanks for the response
