### ISSUE TITLE
Serenity summary file alignment is not correct

### ISSUE THREAD

**Issue by ahuja-ankur** [serenity-bdd/serenity-core#2109]
Hi,

When I used Email-ext plugin to send the serenity-summary.html to my gmail box. It is distorted. The same project is https://github.com/ahuja-ankur/sample-Proj.git

Please help.

![image](https://user-images.githubusercontent.com/65816172/83182033-5938d900-a143-11ea-9646-5e392255021f.png)

**Comment by wakaleo** [comment]
Does it work when you display the report locally?

**Comment by ahuja-ankur** [comment]
yes, when I open the file in browser normally, it works fine.

**Comment by wakaleo** [comment]
Have you tried sending the original report as an html document to your gmail client?

**Comment by wakaleo** [comment]
HTML rendering is notoriously unreliable in email clients, so it could be an issue with the rendering (which will be hard to fix, as fixing the rendering for one client will break it for another, or may not be possible at all).

**Comment by ahuja-ankur** [comment]
> Have you tried sending the original report as an html document to your gmail client?

I am sending as HTML only.

**Comment by wakaleo** [comment]
The other possibility is that the email-ext plugin modifies the html (that would seem unlikely but worth checking)

**Comment by ahuja-ankur** [comment]
> HTML rendering is notoriously unreliable in email clients, so it could be an issue with the rendering (which will be hard to fix, as fixing the rendering for one client will break it for another, or may not be possible at all).

It is working fine for old versions of serenity.

**Comment by wakaleo** [comment]
If you can figure out a modification of the HTML that would render correctly, I can have a look at the template to see if it is possible.

**Comment by globalworming** [comment]
if you could precisely state the version where it breaks, we could check the commits for what may be the culprit

**Comment by ahuja-ankur** [comment]
> If you can figure out a modification of the HTML that would render correctly, I can have a look at the template to see if it is possible.

I can say it is working fine for serenity-emailer version 1.9.45 but not for 2.2.5... Probably this could help you in comparing.

**Comment by ahuja-ankur** [comment]
> if you could precisely state the version where it breaks, we could check the commits for what may be the culprit

Working fine in 1.9.45 but not in 2.2.5

**Comment by ahuja-ankur** [comment]
> that's not very precise :)

After 1.9.45, I checked at 2.0.40. There also it is broken... I am not able to go below this version because then I have to lower down all my dependencies

**Comment by wakaleo** [comment]
If you can identify an exact version change we can see what has changed.

**Comment by ahuja-ankur** [comment]
> If you can identify an exact version change we can see what has changed.

Would it be possible for you to compare the two versions I provided, because ultimately the fix would be on top of latest version.

**Comment by ahuja-ankur** [comment]
for serenity-single-page-report, it is issue from first version for me... earlier I was using serenity-emailer 1.9.45

**Comment by wakaleo** [comment]
It’s just the artifact name that changed, the code should be similar. See if you can isolate the exact change

**Comment by ahuja-ankur** [comment]
ok, let me try quickly

**Comment by ahuja-ankur** [comment]
> It’s just the artifact name that changed, the code should be similar. See if you can isolate the exact change

It is 1.9.45 and 2.0.0

**Comment by wakaleo** [comment]
There are about 50 releases between 1.9.45 and 2.0.0

**Comment by ahuja-ankur** [comment]
> that's not very precise :)

It is exact 2.0.4 and 2.0.5 version where the format has changed. I hope it helps.

**Comment by ahuja-ankur** [comment]
> There are about 50 releases between 1.9.45 and 2.0.0

It is exact 2.0.4 and 2.0.5 version where the format has changed. I hope it helps.

**Comment by wakaleo** [comment]
That does help. I don’t know when I will be able to look at it, though - if you can look at the differences in GitHub and propose a PR it will be quicker

**Comment by ahuja-ankur** [comment]
> That does help. I don’t know when I will be able to look at it, though - if you can look at the differences in GitHub and propose a PR it will be quicker

can you please help in confirming exactly where to look at. I am new to this.

**Comment by globalworming** [comment]
with you IDE it should be easy to check out a the branches tagged v2.0.4 and v2.0.5 and compare them (at least my IntelliJ does this pretty good). changes in the emailable html report are most important i guess

**Comment by ahuja-ankur** [comment]
I am not able to find the emailable report, can you help me with that?

**Comment by ahuja-ankur** [comment]
I tried to push my branch to create pull request but it is giving me permission denied...
Please help..

**Comment by wakaleo** [comment]
You’ll need to raise a Pull Request

**Comment by ahuja-ankur** [comment]
> You’ll need to raise a Pull Request

how, when I cannot push my branch. I created the branch locally but when pushing it is giving me error - 
![image](https://user-images.githubusercontent.com/65816172/83262675-090d5580-a1db-11ea-8c33-473555ec1c84.png)

**Comment by wakaleo** [comment]
See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

You need to fork the repository, make and test your change locally, then propose a Pull Request against the main repo

**Comment by ahuja-ankur** [comment]
Raised PR https://github.com/serenity-bdd/serenity-core/pull/2112. Please take a look.

**Comment by ahuja-ankur** [comment]
@wakaleo  Thanks for merging the PR, it looks like it will be part of 2.2.9, so when 2..29 is expected to be rolled out? because I would like to get this soon.

**Comment by ahuja-ankur** [comment]
Raised PR https://github.com/serenity-bdd/serenity-core/pull/2113 for minor modifications. Please merge.

**Comment by ahuja-ankur** [comment]
@wakaleo @globalworming  Is it possible to generate 2.2.9 release? I need the latest fix urgently.

**Comment by wakaleo** [comment]
There will be a new release early next week.

**Comment by ahuja-ankur** [comment]
Issue not occurring in 2.2.9. Fix is good. Closing this thread.
