### ISSUE TITLE
journey pattern for tests with rest assured

### ISSUE THREAD

**Issue by bassmake** [serenity-bdd/serenity-core#211]
I see that there exists `browse-the-web` library that implements journey pattern for testing with web-driver. Is it possible, and also do you think it is a good idea to use journey pattern for tests with rest-assured?

**Comment by wakaleo** [comment]
The https://github.com/serenity-bdd/serenity-journey-demo project demonstrates how to use the browse-the-web library to use the Journey pattern with WebDriver. Yes, excellent idea to use the journey pattern with rest-assured - there isn't an explicit module for this yet, though, so you would just implement the Rest-Assured calls in the tasks. The serenity-rest-assured module (https://github.com/serenity-bdd/serenity-core/tree/master/serenity-rest-assured) provides general support for Rest-Assured, which you can use in the Journey pattern tasks.

**Comment by bassmake** [comment]
thanks,
I will try to implements something simple with rest-assured and journey pattern and share it on github.

**Comment by vahidg** [comment]
@wakaleo is there any kind of documentation available for serenity-rest-assured module?

**Comment by bassmake** [comment]
@vahidg there is really nothing special. All that is need is rest-assured functionality and

    net.serenitybdd.rest.SerenityRest

provides some glue code between Serenity and rest-assured

**Comment by vahidg** [comment]
@bassmake thanks for the quick reply. I haven't used rest-assured though it looks very straightforward. What I was mainly wondering was how the `given().param("key1", "value1").param("key2", "value2").when().post("/somewhere").then().body(containsString("OK"));` syntax of rest-assured fits in with the separated `Step` methods of a `ScenarioSteps` class, or should one simply store the intermediate states in a field?

**Comment by bassmake** [comment]
I use `getCurrentSession()` for managing state between step definitions (Given, When, Then) and Steps are stateless. So method implementing step has params.

**Comment by YamStranger** [comment]
Hello @bassmake did you find answer to you question? 

If yes, and you feel that this question already answered and you have no question with the same topic - please close this issue. 

Thanks a lot!

**Comment by bassmake** [comment]
Hi,
this can be closed as a question, but I think there should be created an improvement for creating journey pattern for rest-assured tests.

**Comment by YamStranger** [comment]
@bassmake As for me such code looks like journey pattern:
```
rest().body(text).post("url").then().body(containsString("OK"))
```

And it can be done with current implementation )

What you mean under improvement, can you write some example?

**Comment by bassmake** [comment]
I though there should be some `Ability` implementation for rest-assured like now there is `BrowseTheWeb` ability

**Comment by wakaleo** [comment]
Yes, proper Rest integration with the Journey pattern will involve an
Ability.

On 3 December 2015 at 19:08, Miroslav Matejovsky <notifications@github.com>
wrote:

> I though there should be some Ability implementation for rest-assured
> like now there is BrowseTheWeb ability
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/211#issuecomment-161546263>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by tremkonzah** [comment]
Hi @YamStranger  @wakaleo 
any plan to support this in serenitybdd 1.5?

thanks

**Comment by wakaleo** [comment]
Yes, at some point.

**Comment by cklasicki** [comment]
Hi, any news about this feature? To test REST API as an Ability?

**Comment by wakaleo** [comment]
It’s been implemented for a while in serenity-screenplay-restassured
