### ISSUE TITLE
not able to reset the data once testscript got failed.

### ISSUE THREAD

**Issue by Manish123chandel** [serenity-bdd/serenity-core#2110]
I have written test script.
Scenario:

-  Login the browser page and browser for one test tab and update the data of given tab(whole column).
-  Want to reset  the data(via running same Test script with different value) with original value after running the Test Script. 

I tried these things via put all the reset code logic under@After annotation method, but it executes that code but doesn't perform action(what ever logic written i.e open the browser and reset the values)

is there any way to do perform **teardown** action, after performing the testscript.

**Comment by wakaleo** [comment]
What version of Serenity are you using?

**Comment by Manish123chandel** [comment]
Serenity version 1.9.36 version

**Comment by Manish123chandel** [comment]
One of my motive which i tries that I tried to create new Actor name "DestroyActor" which will extend the Actor.and want to override the attemptTo method but could not do.

So my expectation is that , Can we find any way to run the teardown script?

**Comment by wakaleo** [comment]
Try with a more recent version - you should be able to do anything you need to in the @After method

**Comment by wakaleo** [comment]
Also, the Actor class is not designed to be extended by inheritance - if you want the actor to perform specific setup and teardown activities, you might be able to use Facts instead (see https://github.com/serenity-bdd/serenity-core/blob/add76d98de591feb4cdb7751b09540dbf4b2a023/serenity-screenplay/src/test/java/net/serenitybdd/screenplay/facts/WhenDeclaringFactsAboutActors.java).

**Comment by Manish123chandel** [comment]
Yeah I tried with Fact also,but our requirement is to perform the action in teadown.
like in teardown 
 code `deskUser.attemptTo(StartWith.ABCloginpage(),Login.as(deskBean))`

`StartWith implements Task{

public void performsAs(T actor){
actor.attemptTo(// Some task) // line 10
}

}`

When it comes line 10 So it skipped all the thing

**Comment by wakaleo** [comment]
Are you using the latest version?

**Comment by Manish123chandel** [comment]
No, my project using 1.9.36.3 version only, We can't move to latest version suddenly.

**Comment by wakaleo** [comment]
I can't help you if you aren't using the latest version.

**Comment by Manish123chandel** [comment]
Okay, Thanks.
