### ISSUE TITLE
Serenity-Browserstack integration fails to launch multiple browsers for custom driver if environment property is used at runtime

### ISSUE THREAD

**Issue by adeshmukh-mms** [serenity-bdd/serenity-core#2117]
Hi,

I used SerenityBDD Cucumber5 Latest framework with BrowserStack integration. The repo example is 
https://github.com/browserstack/serenity-browserstack

However if I pass environment property at runtime to maven using -Denvironemnt=qa Browserstack only uses chrome on multiple threads for test execution.

If environment is defined at property level or not passed at all then all different browsers are getting launched properly.

Working command with different browsers
``` clean compile verify -Dbrowserstack.user=<usrname> -Dbrowserstack.key=<key> -Dcucumber.filter.tags="@Cycle=FAQ" serenity:aggregate -P parallel   ```

Non working command for multiple browsers
``` clean compile verify -Denvironemnt=Prod -Dbrowserstack.user=<usrname> -Dbrowserstack.key=<key> -Dcucumber.filter.tags="@Cycle=FAQ" serenity:aggregate -P parallel  ```

Kindly assist

**Comment by wakaleo** [comment]
That code is written and maintained by Browserstack; please ask them for assistance with it. It uses a custom driver and custom properties which are not standard Serenity. 

See https://serenity-bdd.github.io/theserenitybook/latest/remote.html#_running_serenity_tests_on_browserstack for the documentation on working with Browserstack in Serenity.

**Comment by adeshmukh-mms** [comment]
Thanks a lot for the clarification. I will raise it with browserstack. You may close the issue.
