### ISSUE TITLE
REST Query button not generated when `.auth().basic(username, password)` is used for request

### ISSUE THREAD

**Issue by bassmake** [serenity-bdd/serenity-core#212]
When using rest-assured for testing rest services `REST query` button is generated on the report. However, when `.auth().basic(username, password)` is used, this button is no longer visible.

**Comment by YamStranger** [comment]
Thanks for this Issue @bassmake!

Yes, we have such bug, you can use workaround for it as introduced in #185. 

We will fix it soon.

**Comment by bassmake** [comment]
The workaround does not work for me, because I am not using `.log().all()` at all.
This issue may be related, but it does not depend on `.log().all()`

**Comment by YamStranger** [comment]
Hello @bassmake!

This issue should be fixed under [1.1.22-rc.11](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.22-rc.11), please check it. 

If you feel that this issue already fixed and cant be reproduced - please close this issue. 

Thanks a lot!!
