### ISSUE TITLE
Empty report when running tests with multiple tags

### ISSUE THREAD

**Issue by tmouryc** [serenity-bdd/serenity-core#2122]
I'm using the JUnit with screenplay and hit the issue with the empty report when the aggregation is run in a post-integration-test phase. After looking into debug logs and some experimenting, the problem occurs when I invoke tests by using multiple tags. When I do that, the aggregation part shows good overall numbers in the console but says 0 tests at the same time.

```
[INFO] --- serenity-maven-plugin:2.2.8:aggregate (serenity-reports) @ serenity-junit-starter ---
[INFO] Test results for 0 tests generated in 1.4 secs in directory: file:/C:/Users/tmour/IdeaProjects/serenity-junit-starter/target/site/serenity/
[INFO] -----------------------------------------
[INFO]  SERENITY TESTS : SUCCESS
[INFO] -----------------------------------------
[INFO] | Tests executed         | 1
[INFO] | Tests passed           | 1
[INFO] | Tests failed           | 0
```

It can be quickly reproduced by adding tags in the serenity-junit-starter project. I added the following tags to the test:     @WithTags({@WithTag("Layer:API"), @WithTag("Area:Test")})
And then run test using:
```
mvn clean verify -Dtags="@Layer:API" -> works fine
mvn clean verify -Dtags="@Layer:API and @Area:Test" -> produce empty report as shown above
```

**Comment by wakaleo** [comment]
@cliviu Thoughts?

**Comment by wakaleo** [comment]
Could you try with 2.2.9?

**Comment by tmouryc** [comment]
It works with 2.2.9.

Btw I tried it also with latest 2.2.10 and aggregation has some issues (although the report seems to be generated). Probably different issue (is it known? do you want to resolve it here? do you want me to file a separate bug?)
> [INFO] --- serenity-maven-plugin:2.2.10:aggregate (serenity-reports) @ serenity-junit-starter ---
> Jul 07, 2020 9:37:18 AM freemarker.log._JULLoggerFactory$JULLogger error
> SEVERE: Error executing FreeMarker template
> FreeMarker template error:
> The following has evaluated to null or missing:
==> formatter.renderHeader  [in template "freemarker/home.ftl" at line 137, column 58]
> ...
> and some stacktrace follows

**Comment by wakaleo** [comment]
There's very little change between 2.2.9 and 2.2.10 - what issues are you seeing?

**Comment by tmouryc** [comment]
When I run with 2.2.10 a see following logs: https://drive.google.com/file/d/19Jo3aNfjc8fddO-hCYUKk-IANnUzi7tZ/view?usp=sharing

**Comment by wakaleo** [comment]
That looks like a bug; not sure what it would be caused by. Maybe have a look at the latest changes and see if anything migh be related?

**Comment by Dvoreth** [comment]
I started having the same issue that @tmouryc mentions after upgrading from 2.2.8 to 2.2.11.

**Comment by wakaleo** [comment]
Try with 2.2.12

**Comment by Dvoreth** [comment]
Fixed in 2.2.12. Thank you!

**Comment by cliviu** [comment]
@Dvoreth , can you please close the issue  ?

**Comment by Dvoreth** [comment]
@cliviu I think only @tmouryc can? They created the original issue.

**Comment by tmouryc** [comment]
All looks fine in 2.2.12. Thank you
