### ISSUE TITLE
Serenity report is empty

### ISSUE THREAD

**Issue by nhhphuong** [serenity-bdd/serenity-core#2125]
Hello,

I'm written a simple project using Serenity, Selenium, and Maven run parallel. It's run fine but no data display in the Serenity report (I meant case passed/failed,...).
I've put code into GitHub, please take a look and help me fix it.
https://github.com/nhhphuong/serenityparallelmaven

(mvn clean verify)

Thanks so much,

**Comment by globalworming** [comment]
You need to tell serenity where your requirements are, see https://github.com/serenity-bdd/serenity-junit-starter/blob/master/serenity.properties

**Comment by nhhphuong** [comment]
Thanks so much for a quick response,

I've updated code as you said, it still does not update the test cases passed/failed into Serenity report. I've checked in code into Git. Please guide me on how to fix this issue.

**Comment by globalworming** [comment]
Why don't you just import the junit starter project?

**Comment by nhhphuong** [comment]
About "junit starter project", I've tried and the Serenity report will be generated in the parallel mode without using feature files. If I using the feature files, the Serenity report was generated in sequence mode. In case I run in parallel mode, the Serenity report displays no data.

**Comment by globalworming** [comment]
parallel cucumber is a different beast... did you try https://johnfergusonsmart.com/running-parallel-tests-serenity-bdd-cucumber/ ?

**Comment by nhhphuong** [comment]
I've tried in multiple ways but it does not successfully, I think this is a limitation of the Serenity. I will close this thread and thank you so much for your support.
