### ISSUE TITLE
Custom report generation failure

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#2126]
Hello Team,

Currently im phasng issue in utilizing the custom reporting option available in serenity .
https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html

classpath ("net.serenity-bdd:serenity-single-page-report:2.2.8"

serenity {
	reports = ["single-page-html"]
}

Error :

* What went wrong:
Execution failed for task ':reports'.
> No signature of method: net.serenitybdd.reports.email.SinglePageHtmlReporter.generateReportFrom() is applicable for argument types: (sun.nio.fs.WindowsPath) values: 
  Possible solutions: generateReport()

**Comment by wakaleo** [comment]
I can't reproduce this - maybe check your dependencies for conflicts (the `generateReportFrom()` method doesn't exist in the current versions)

**Comment by JeffGaly** [comment]
@wakaleo Thanks John.
