### ISSUE TITLE
[Restassured.module.jsv] is not included into serenitybdd.rest

### ISSUE THREAD

**Issue by yavgel** [serenity-bdd/serenity-core#2132]
Hello @wakaleo  - it is not a BUG, it is more like a question!
why 
`io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchemaInClasspath;` 

is not included in `serenitybdd.rest` package?

Due to this reason, I need to put it as a separate direct dependency in my tests:

![image](https://user-images.githubusercontent.com/8123409/84799325-69363100-affc-11ea-8e90-098ce5fb2272.png)

Thank you a lot in advance! 👍

**Comment by wakaleo** [comment]
Because it's not a Serenity class: https://www.javadoc.io/static/io.rest-assured/json-schema-validator/3.0.0/index.html?io/restassured/module/jsv/JsonSchemaValidator.html.

**Comment by yavgel** [comment]
> Because it's not a Serenity class: https://www.javadoc.io/static/io.rest-assured/json-schema-validator/3.0.0/index.html?io/restassured/module/jsv/JsonSchemaValidator.html.

@wakaleo  do you have a plan to include it in the future? thank you, will close this ticket

**Comment by wakaleo** [comment]
No, because then I would need to maintain it ;-)
