### ISSUE TITLE
How to run tests on multiple tabs of 1 browser

### ISSUE THREAD

**Issue by happy1610** [serenity-bdd/serenity-core#2133]
Dear, 

I am using Serenity Screenplay.
I want to take advantage of using same cookies on browser, avoid re-login for each case,
so I would like to run testcases on multiple tabs of 1 browser for same account login.
No result when I search on Google. Please help.
Thank so much.

Linh

**Comment by happy1610** [comment]
@wakaleo can you help me? thanks so much

**Comment by sudhir-kunchakuri** [comment]
Even i am also looking for the same help..
My Requirement is : 
I have 10 scenarios in one feature file
Now i used to run all 10 scenarios by using required tag

restart.browser.for.each = never
With this configuration in serenity.conf file , all the 10 scenarios would run one after the other in the same browser instance and would close the browser after execution of 10 scenarios 

//restart.browser.for.each = never
If i comment this line then each scenario would get execute and close thee browser and for next scenario execution again browser will open and do the same.

Now my ask is I want to execute my scenarios one after the other in tabs of same browser window.
like 
Browser will open and scenario 1 will get execute 
Once scenario 1 execution is completed then scenario 2 should get execute in new tab of same window
Once scenario 2 execution is completed then scenario 3 should get execute in new tab of same window
.
.
Once Scenario 10 execution is completed then all the opened tabs should get close ..

So please let me know how can it be achieved. 
@wakaleo @globalworming

**Comment by wakaleo** [comment]
This isn't supported.
