### ISSUE TITLE
When using the rerun of failed scenario outline example are not showing passed example details

### ISSUE THREAD

**Issue by vvramanan** [serenity-bdd/serenity-core#2136]
When i used the below mvn command  for execution and below code is my feature file rerun is done successfully, With reports not showing for earlier pass cases

**Issue :** : When example test case 1 fails and test case 2 passed, Test case 1 retry and pass
In the report 
\target\site\serenity\index.html
### We are unable to see details of first run pass test case 2 in tab **Overall Test Results**

`mvn clean verify -Dcucumber.options="--tags @testRun" -Dfailsafe.rerunFailingTestsCount=2`

My Test is in the following format
`Feature: Sample Test

    Scenario Outline: Scenario Outline name
        Given Test start <Header 1>
        When test pre condition <Header 2>
        And Steps added
        Then validate result <Header 3>

        Examples:
            | testcase   | Header 2 | Header 3 |
            | testcase_1 | Value 2  | Value 3  |
            | testcase_1 | Value 5  | Value 6  |`

**Comment by wakaleo** [comment]
Only the latest results are shown at the moment.
