### ISSUE TITLE
It's not possible to replace configuration via system properties

### ISSUE THREAD

**Issue by renatomefi** [serenity-bdd/serenity-core#2137]
Given the following `serenity.conf`:
```conf
webdriver {
  driver = remote
  remote {
    driver = chrome
    url = "http://localhost:4444/wd/hub"
  }
}
```
More setup information:
- Gradle 6.4
- Serenity 2.2.9
- Serenity Cucumber 2.2.5
- Cucumber 5.7.0

When I run the test suite via gradle:
`./gradlew -Dwebdriver.driver=chrome`
I'd expect to have my local driver running, but instead it still runs via the remote driver

Another attempt was to remove the URL, but maybe that's another problem that if it comes empty from the system properties it does seem the replace the final configuration:
`./gradlew -Dwebdriver.driver=chrome -Dwebdriver.remote.url=""`

My intention is to have sane defaults and allow CI or users to influence it via system properties.

Is there a way to achieve this with Serenity?

Thank you!

**Comment by wakaleo** [comment]
Have you tried using `./gradlew -Pwebdriver.driver=chrome`

**Comment by jacquecosta** [comment]
@wakaleo 

I am with the same doubt, but in my case I am using Maven. 

At the moment I am testing Appium + Serenity and the behavior that I am experiencing is:

Given the following `serenity.conf`:

```
environments {
  default{
    context = android
    appium.platformName = Android
    appium.app = appPath
    appium.automationName = UiAutomator2
    appium.deviceName = emulator-5554
  }
}

```
If I run:

`mvn verify -Dappium.platformName=ios -Dappium.avd="iPhone 8" .....`

Then the information provided are ignored and the execution stills considering the `default` on `serenity.conf` file.

I tried with `mvn verify -Penvironment=default` but a provile with this name doesn't exists, any idea?

My info:

Serenity Version = 2.0.90
Serenity Cucumber = 1.9.50
