### ISSUE TITLE
remote driver is timing out in few milliseconds on grid setup

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#214]
Hi John,

This is broken with latest version of framework 1.1.22-rc.10 and earlier version 1.1.14 was working fine

getting timeout in milliseconds error

[pool-1-thread-4] WARN net.thucydides.core.webdriver.WebDriverFacade - Error while quitting the driver (Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'e11f2d0540e4', ip: '172.17.0.37', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.10-boot2docker', java.version: '1.8.0_45-internal'
Driver info: driver.version: unknown
Command duration or timeout: 14 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'Vikrams-MBP.fritz.box', ip: '192.168.178.33', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.glYiPN}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.71, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=1baac730-6efc-49e1-ace4-4d45379de06d, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 1baac730-6efc-49e1-ace4-4d45379de06d)

Please look into it

Thanks & REgards,
Vikram

**Comment by vikramvi** [comment]
webdriver.wait.for.timeout = 8000
webdriver.timeouts.implicitlywait = 10000
serenity.timeout = 8000
serenity.take.screenshots=FOR_FAILURES
serenity.timeout = 10000
max.retries = 0
serenity.logging = VERBOSE
serenity.verbose.steps = true

Does remoteWebDriver doesn't take above values ?

Thanks,
Vikram

**Comment by wakaleo** [comment]
Try modifying the Selenium version to see if it is a Selenium issue.

On 3 December 2015 at 00:58, vikramvi <notifications@github.com> wrote:

> webdriver.wait.for.timeout = 8000
> webdriver.timeouts.implicitlywait = 10000
> serenity.timeout = 8000
> serenity.take.screenshots=FOR_FAILURES
> serenity.timeout = 10000
> max.retries = 0
> serenity.logging = VERBOSE
> serenity.verbose.steps = true
>
> Does remoteWebDriver doesn't take above values ?
>
> Thanks,
> Vikram
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/214#issuecomment-161301301>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by vikramvi** [comment]
Hi John,

I'm using latest version of Selenium 2.48.2.

It was working perfectly with serenity version 1.1.14 , so I think there is a regression

can you please look if something changed wrt RemoteWebDriver ?

And just to confirm RemoteWebDriver doesn't have to mention values separately right ?

Thanks & Regards,
Vikram

**Comment by vikramvi** [comment]
Hi John,

This issue is not there with serenity.version 1.1.21 but observed with 1.1.22-rc.10

Can you please relook if some major change underwent ?

Thanks again.

Regards,
Vikram

**Comment by vikramvi** [comment]
@YamStranger With docker 2.52.0 + 1.1.26-rc.1  this issue is resolved.

Off late grid is having its own regression issues.  refer to https://github.com/SeleniumHQ/selenium/issues/1565

Closing this ticket for now.

**Comment by YamStranger** [comment]
Thanks @vikramvi !!!
