### ISSUE TITLE
how to use existing chrome profile using serentiy BDD with JBehave

### ISSUE THREAD

**Issue by gitrak** [serenity-bdd/serenity-core#2144]
Hi, 
Is there a way in serenity to use existing Chrome Profile using serentity BDD.

without serenity just as we do using below code:
            ChromeDriver driver = null;
            ChromeOptions chOption = new ChromeOptions();
            chOption.addArguments("user-data-dir=C:/Users/abcuser/AppData/Local/Google/Chrome/User Data");
            chOption.addArguments("--start-maximized");

**Comment by globalworming** [comment]
does https://serenity-bdd.github.io/theserenitybook/latest/extending-webdriver.html help?

**Comment by gitrak** [comment]
serentiy version i am using(1.4) has no such class/interface as indicated in provided article.
is there another way around this?

**Comment by globalworming** [comment]
argh, sorry, wrong link

https://serenity-bdd.github.io/theserenitybook/latest/advanced-webdriver.html

in the serenity.properties you can set the custom driver and use the code you posted exactly. I hope this is available in v1.4
If not you may need to upgrade..

**Comment by gitrak** [comment]
Thanks @globalworming 
Is there a way of doing this using serenity.properties file

**Comment by globalworming** [comment]
huh? from the documentation:

> Custom WebDriver implementations
>
> You can add your own custom WebDriver provider by implementing the DriverSource interface. First, you need to set up the following system properties (e.g. in your _serenity.properties file_):
