### ISSUE TITLE
Are you planning to upgrade rest-assured library from 3.3.0 to latest (4.3.0)? 

### ISSUE THREAD

**Issue by venkat675** [serenity-bdd/serenity-core#2145]
There are lot of updates in rest assured library, are you planing to upgrade?

**Comment by wakaleo** [comment]
At some point, yes. Are you able to assist?

**Comment by globalworming** [comment]
hmm.. i would disagree with `a lot of updates`

relevant for serenity-rest seems only
* added ability to blacklist headers
* Made it possible to specify a multi-expectation body with arguments

or is there anything else you are especially looking forward to @venkat675 ?
