### ISSUE TITLE
Error with cucumber in other languages 

### ISSUE THREAD

**Issue by ricardorlg-aval** [serenity-bdd/serenity-core#2146]
Hi, I`m working on migrating my current project from serenity 2.1.x to the last version, for that I make the changes to support cucumber 5, but now I see that given that my project is in spanish, and some of the features has names different from the features file name, then I see in the report multiples features that are not correct.

for example, if I have a feature file called test_feature.feature and in the gherkin I calle the feature as Feature example in spanish, in the report I see two results one for file name and the other for the Gherkin name.

Also I have some readme.md files inside some capabilities folder in my structure, for example I have a readme inside features/capabilityTest/readme, If this file has a name different from the parent directory then I see a new feature in the report.

**Comment by wakaleo** [comment]
I suspect this might be a more general issue related to the way the features are tagged.

**Comment by ricardorlg-aval** [comment]
@wakaleo after debugging, I think the problem is related to the fact that Serenity delegates to the Cucumber Gherkin lexer the task to transform the feature files, and this one assume a UTF-8 encoding, when the feature uses a different one, in older versiones, Serenity uses the Cucumber FeatureParser instead of the Gherkin one, I will make some tests changing the Gherkin to the FeatureParser to see if this fix the bug.

If u want u can assign this to me.

**Comment by wakaleo** [comment]
Thanks!

**Comment by ricardorlg-aval** [comment]
@wakaleo The fix only affects features files, I found that if a capability folder has Spanish accents then the features are still duplicated, any idea where should I start to debug in order to fix this.

**Comment by wakaleo** [comment]
That's odd - the capability folder names would go into the requirements paths, so it could be an issue that happens when the requirements tree is built (maybe the accents are being normalised or transformed when they are read?)

**Comment by ricardorlg-aval** [comment]
well, I was doing a lot of debugging trying to understand how works the requirements tree build, what I see is that the URI used for the features with an accent is not decoded, so sometimes I see that the name is printed with the accent but the path was encoded, I´m still lost, so, for now, I will just remove the accents, or maybe is possible to make a filter by name before sending the requirements to the report?

**Comment by ricardorlg-aval** [comment]
@wakaleo I found the problem, is in Serenity Cucumber 6 when loading the features is using URI, so if the parent folder has special characters the path of the feature as URI will be encoded, which causes that the reporter finds special tags like feature:encoded_path/feature_name. So, if instead of using the URI toString call, I use URLDecoder to standard UTF-8, I get no more duplicates.

I will make the PR with the fix in the cucumber6 repo.
