### ISSUE TITLE
how to change default template in serenity single page report

### ISSUE THREAD

**Issue by emaninder** [serenity-bdd/serenity-core#2151]
Serenity-single-page-report is using a default template when summary page html is generated.

`DEFAULT_TEMPLATE = "templates/email/serenity-summary-report-inlined.html"`

how can i switch to use other email templates in resources folder.

**Comment by wakaleo** [comment]
This is the only template currently supported.

**Comment by emaninder** [comment]
@wakaleo  thank you.
