### ISSUE TITLE
Serenity is skipping many of the tests when running it in parallel

### ISSUE THREAD

**Issue by davi-romero** [serenity-bdd/serenity-core#2153]
I have a total of 405 tests. They are all executed fine when running it on a single machine. However, when trying to run it in parallel, it seems the number of tests is not being properly allocated.

So, for example, executing it using 3 slaves:

```
mvn  integration-test -Dwebdriver.remote.url=http://selenium-hub.project.svc.cluster.local:4444/wd/hub \
                      -Dwebdriver.remote.driver=chrome                 \
                      -Dwebdriver.driver=chrome                         \
                      -Dserenity.batch.size=3 \
                      -Dserenity.batch.number=<"from 1 to 3"> \
                      -Dserenity.batch.strategy=DIVIDE_BY_TEST_COUNT        \ 
                      -Dserenity.take.screenshots=FOR_EACH_ACTION
```

After triggered maven, as according to the sample above, the tests have been allocated as follows:

```
Slave 1: 106
Slave 2:  96
Slave 3: 103
  Total: 305
```

It is like it is counting 4 machines instead of 3. Or like there is some max test count set per slave.

Another interesting behaviour is that even if I set the batch.number higher than the batch.size, serenity will still allocate some tests to be run. Is there any way I could visualize how the tests are allocated per thread when running it in parallel?

I'm running those tests using Jenkins, hosted in an Openshift environment.

**Comment by wakaleo** [comment]
A question for @nbarrett

**Comment by nbarrett** [comment]
Some thoughts, suggestions @daniilmatafonov. 
* Don't set the `serenity.batch.number` > `serenity.batch.count` I don't believe there is any validation on doing that. It will just not work properly. 
* Are all of your tests Junit tests or are there some cucumber ones in there as well? I'm not sure what the effect would be of batching if there was a combination of the two.
* What happens if you choose serenity.batch.strategy=DIVIDE_EQUALLY?

**Comment by davi-romero** [comment]
@nbarrett Many thanks for your answer.

- Ok. I will not do it.

- They are all Junit tests.

- It is behaving in the same way for both DIVIDE_BY_TEST_COUNT or DIVIDE_EQUALLY. Meaning it is not executing all the tests, no matter the algorithm we are using for splitting.

- Actually you are right about it. The tests have been executed in parallel among separated slave machines. I've used the word "thread" incorrectly in this context. At the end of the test execution, as mentioned in your last comment, I'm aggregating the results by calling "mvn serenity:aggregate". 

- I've added the suggested configuration (e.g. runOrder). It helped as some tests that were previously not being executed, now were added to the test list. However, the number of tests is still the same. 

I've found a workaround by scaling it up for running the tests in 4 machines, instead of 3. However, I cannot trust it, given the number of tests will increase in the future, being nicer, if the tests were equally distributed among the machines, instead. As well, it looks like some tests are still not being executed.

Is there anything else I could do for raising the logs, in a way I could see how the tests are divided per machine? Or any other tip you could give that could help in the investigation?

**Comment by davi-romero** [comment]
Fixed it by upgrading the selenium node version (3.141.59-titanium) and increasing its max session numbers (i.e. 5 chrome sessions per pod).
