### ISSUE TITLE
Serenity manual tests are reported as ignored when excluded from the. tags

### ISSUE THREAD

**Issue by pnakhat** [serenity-bdd/serenity-core#2154]
I am trying to use @manual tags in my tests and the issue is, when tests are not excluded from cucumber runner the report is generated ok, however cucumber attempts to execute it. However, when tests are excluded - serenity reports them as ignored not under manual tests.

**Comment by wakaleo** [comment]
Do your manual tests have an implementation then?

**Comment by pnakhat** [comment]
No they don't. Hence cucumber complains
