### ISSUE TITLE
Get Error Object Details when Test is Failed/Error

### ISSUE THREAD

**Issue by jayzsuarez** [serenity-bdd/serenity-core#2155]
Hi @wakaleo,

Is there a proper way to get error object/entities details as shown in the Serenity Report in preparation to customize reporting?

Example below: Error message for the specific test was "No such element exception"

![image](https://user-images.githubusercontent.com/41811725/86908831-be6fe900-c149-11ea-845c-545ed4202689.png)

**Comment by globalworming** [comment]
What do you mean by "customize reporting"?

**Comment by jayzsuarez** [comment]
For the custom reporting, I need to get the actual error details from the serenity report and pass the details in the our custom report.

e.g
```java
|Test Case Id | Test Title| Expected Status| Actual Result| Actual Error|
|Test-001|      Demo Test| Displayed|       Not Displayed| No Such Element Exception|


```

I need to get it pass it in our test management tool.

**Comment by jayzsuarez** [comment]
Can we get also the actual screenshot from the serenity?
