### ISSUE TITLE
Error during the execution 

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#2156]
getting the error

java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
net/thucydides/core/webdriver/capabilities/SaucelabsRemoteDriverCapabilities.getCapabilities(Lorg/openqa/selenium/remote/DesiredCapabilities;)Lorg/openqa/selenium/remote/DesiredCapabilities; @2: invokespecial
Reason:
Type 'org/openqa/selenium/remote/DesiredCapabilities' (current frame, stack[1]) is not assignable to 'org/openqa/selenium/MutableCapabilities'

Using the serenity version of 2.2.9 with cucumber5

**Comment by wakaleo** [comment]
Can you provide a sample project?

**Comment by JeffGaly** [comment]
@wakaleo I cannot share the sample as well.Any suggestion from your end ?

**Comment by wakaleo** [comment]
Have you tried debugging the SaucelabsRemoteDriverCapabilities class? I'm not too familiar with that code.

**Comment by JeffGaly** [comment]
@wakaleo Even im not familar with that code but Im no where calling or referring the saucelab .

**Comment by wakaleo** [comment]
Interesting! I'd put a breakpoint and see where it is being called then.

**Comment by JeffGaly** [comment]
@wakaleo  Error throws before the initialization .

**Comment by wakaleo** [comment]
I can't reproduce it here so I presume it is something specific in your project. If you put a breakpoint in the code and run the test suite it should still stop there, even if it is happening during the initialization.

**Comment by JeffGaly** [comment]
@wakaleo  i will try this from my end John.

**Comment by JeffGaly** [comment]
@wakaleo I tried debugging the code .

It fails in WebDriverFactory class ,upon calling the saucelabcapabilities. but when i run with other project it goes to the capabilities and initiate the listener.

Both the project has same configuration .

public WebDriverFactory(EnvironmentVariables environmentVariables,
                            FixtureProviderService fixtureProviderService) {
        this.environmentVariables = environmentVariables;
        this.fixtureProviderService = fixtureProviderService;
        this.sauceRemoteDriverCapabilities = new SaucelabsRemoteDriverCapabilities(environmentVariables);
        this.timeoutStack = new TimeoutStack();
        this.closeBrowser = WebDriverInjectors.getInjector().getInstance(CloseBrowser.class);
    }

**Comment by JeffGaly** [comment]
@wakaleo  also received this error in junit 

<terminated>org.eclipse.jdt.internal.junit.runner.RemoteTestRunner at localhost

**Comment by JeffGaly** [comment]
@wakaleo Upon updating the JUNIT ,its working now.Thanks a lot .

**Comment by rudranilwowinc** [comment]
@JeffGaly Can you please specifically let us know what changes need to be done in POM file , I have tried to used latest junit 4.13 but the issue still persists
