### ISSUE TITLE
is there a way to model JUnit's Assume in Screenplay pattern?

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#2157]
Something like `actor.should(seeThat(actual, expected))` is essentially a JUnit Assert.

Is there a way to model JUnit's Assume? That is: if the actual does not match the expected, the test is marked as Ignored, not Failed.

I thought `net.serenitybdd.screenplay.GivenWhenThen.seeIf()` might be it, but I am sure if this is the correct way forward. I am not able to find any examples of using `seeIf()`.

**Comment by wakaleo** [comment]
No, but it would be a good idea.

**Comment by globalworming** [comment]
There is something you can use already, http://thucydides.info/docs/articles/semantic-exceptions.html

```
actor.should(eventually(seeThat(actual, expected)).complainingWith(FailingAssumption.class))
```

while `class FailingAssumption extends TestCompromisedException`

**Comment by globalworming** [comment]
also.. shouldn't it be easy to write an interaction like `actor.attemptsTo(TestAssumption(actual, expected))` ?

**Comment by ricardorlg-aval** [comment]
Other option that I use, is the Facts, u can make a Fact about something and in case it doesn’t  satisfy the rule, throw a compromised exception or use the Junit assume inside the setUp method of the fact.

**Comment by SiKing** [comment]
> There is something you can use already, http://thucydides.info/docs/articles/semantic-exceptions.html
> ...
> while `class FailingAssumption extends TestCompromisedException`

This seemed like the easiest solution, but I get:
```
The method orComplainWith(Class<? extends Error>) in the type Consequence<WebElementState> is not applicable for the arguments (Class<FailingAssumption>)
```

I also tried `extends org.junit.AssumptionViolatedException` but that gave me the same error.

**Comment by SiKing** [comment]
> Other option that I use, is the Facts, u can make a Fact about something and in case it doesn’t satisfy the rule, throw a compromised exception or use the Junit assume inside the setUp method of the fact.

@ricardorlg-aval I have never used `Fact` and I am having a hard time finding any examples of this. Could you provide some more details?

**Comment by globalworming** [comment]
Correction on my example:

```
import net.serenitybdd.core.exceptions.CausesCompromisedTestFailure;

public class CompromisedTest extends AssertionError implements CausesCompromisedTestFailure{

  public CompromisedTest(Object detailMessage) {
    super(detailMessage);
  }

  public CompromisedTest(String message, Throwable cause) {
    super(message, cause);
  }
}

```
And then do `class AssumptionFailed extends CompromisedTest`

**Comment by SiKing** [comment]
That builds, but the test gets marked as Failed. I need it marked as Skipped.

I ended up doing something like: `Assume.assumeThat(valueOf(target).answeredBy(actor), containsOnlyText("text"));`, which is one refactor away from your `TestAssumption(actual, expected)` suggestion.
