### ISSUE TITLE
browserstack+serenity+appium: isCurrentlyVisible(), isCurrentlyEnabled() throw a WebDriverException with "browserstack.use_w3c", "true"

### ISSUE THREAD

**Issue by arhanechka** [serenity-bdd/serenity-core#2160]
Hi. We use w3c actions in framework. Trying to connect with browserstack, put browserstack.use_w3c to true to have a possibility use actions. But then in any methods isCurrentlyVisible(), isCurrentlyEnabled() got an exception org.openqa.selenium.WebDriverException: The following error occurred: Returned value cannot be converted to WebElement: {error=no such element, message=An element could not be located on the page using the given search parameters., stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.
We do not have such problem locally. How can we fix it?

**Comment by arhanechka** [comment]
Hi. We use w3c actions in framework. Trying to connect with browserstack, put browserstack.use_w3c to true to have a possibility use actions. But then in any methods isCurrentlyVisible(), isCurrentlyEnabled() got an exception org.openqa.selenium.WebDriverException: The following error occurred: Returned value cannot be converted to WebElement: {error=no such element, message=An element could not be located on the page using the given search parameters., stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.
We do not have such problem locally. How can we fix it?

**Comment by wakaleo** [comment]
I would put a breakpoint and try to figure out what is going on in the code, and propose a PR if you find anything interesting.

**Comment by gokulkuppan** [comment]
I'm also facing same issue with Selenium+TestNg+Browserstack
if I run the scripts in debug mode then there are no issues.

**Comment by wakaleo** [comment]
TestNG? Serenity doesn't support TestNG.

**Comment by wakaleo** [comment]
Couldn't reproduce this with version 3.2.0

**Comment by gokulkuppan** [comment]
> TestNG? Serenity doesn't support TestNG.

not serenity! SELENIUM with TestNG & BrowserStack.

**Comment by wakaleo** [comment]
Ok, in that case I'll close this issue as it is unrelated to Serenity.
