### ISSUE TITLE
Individual scenario gets passed however in bulk run , it fails

### ISSUE THREAD

**Issue by push2212** [serenity-bdd/serenity-core#2161]
Hello ,

Whenever I run scenarios in bulk , 40 + at once , there are failures in the scenarios which run successfully if I run them individually.

All the sync methods are in place and working.

Please suggest if I am missing anything or to improve my approach.

**Comment by wakaleo** [comment]
There is probably a dependency between some of your tests.

**Comment by push2212** [comment]
There ia no dependency as such , they wouldn't have tun individually then . 

What can I do to have a complete passed result ?

**Comment by push2212** [comment]
There is no dependency as such , the scenarios wouldn't have passed individually then .
What shall I do to have a complete passed status ?

**Comment by wakaleo** [comment]
Do the tests pass when you restart the browser for each test?

**Comment by push2212** [comment]
It was the dependency that were causing the failures .Thanks 
By the way does restart never help to execute faster ?
