### ISSUE TITLE
Question: Is it possible to use DefaultFieldDecorator to decorate WebElementFacade

### ISSUE THREAD

**Issue by Jazzyekim** [serenity-bdd/serenity-core#2163]
We have some dropdown lists on the page which are implemented as two separate elements - a "button" that triggers the dropdown and list with items itself. I want to wrap them using a DefaultFieldDecorator and work as with one element. Is it possible to use decorators with WebElementFacade? Is there any example of such approach?

**Comment by wakaleo** [comment]
Anything you can do with a WebElement you can also do with a WebElementFacade.

**Comment by Jazzyekim** [comment]
I have some difficulties with decorating WebElementFacade.  I have a page 
```
public class ConnectFrame extends PageObject {

    @FindBy(id = "directDebit_bic")
    public WebElementFacade txtBic;

    @FindBy(id = "select2-brandTypeSelect-container")
    public ComboElement ddlPaymentMethod;   //ComboElement -  my custom webelement
...
    public ConnectFrame(final WebDriver driver) {
        super(driver, pageObject -> {
            PageFactory.initElements(
                    new FrameFieldDecorator(
                            driver), pageObject);
            return true;
        });
    }
```

and here is the decorator that I am using:
```
public class FrameFieldDecorator extends DefaultFieldDecorator {
    public FrameFieldDecorator(final SearchContext searchContext) {
        super(new DefaultElementLocatorFactory(searchContext));
    }

    @Override
    public Object decorate(ClassLoader loader, Field field) {
        Class<?> decoratableClass = decoratableClass(field);
        if (decoratableClass != null) {
            ElementLocator locator = factory.createLocator(field);
            if (locator == null) {
                return null;
            }
            return createElement(loader, locator, decoratableClass, getFrameId(field));
        }
        return super.decorate(loader, field);
    }
```

 After WebElementFacade is checked whether it is a decoratable it is passed to super.decorate(loader, field); where it fails with error 
```
net.thucydides.core.pages.Pages - Failed to instantiate page of type class com.fd.ipg.pages.connect.ConnectFrame ({})
java.lang.IllegalArgumentException: Can not set net.serenitybdd.core.pages.WebElementFacade field com.fd.ipg.pages.connect.ConnectFrame.txtBic to com.sun.proxy.$Proxy40
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
Failed to instantiate page (java.lang.IllegalArgumentException: Can not set net.serenitybdd.core.pages.WebElementFacade field com.fd.ipg.pages.connect.ConnectFrame.txtBic to com.sun.proxy.$Proxy40)
	at net.thucydides.core.pages.Pages.thisPageObjectLooksDodgy(Pages.java:296)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:220)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:91)
```
This decorator works perfectly fine with WebElement, but not with WebElementFacade.
@wakaleo could you please help me with that?

**Comment by globalworming** [comment]
I still struggle to see why you need that. Admittedly I don't use page objects anymore so maybe I am missing something crucial here, though if you would state what problem you are trying to solve, we might come up with easier solutions.

**Comment by Jazzyekim** [comment]
I have dropdown list on the page that is implemented as two separate webelements: a button and a list with items.

```
@FindBy(id = "select2-brandTypeSelect-container")
    public WebElementFacade ddlPaymentMethod; // a button that open the list with items
 
@FindBy(xpath = "//ul[@id='select2-brandTypeSelect-results']//li[contains(@id, 'MASTERCARD')]")
    public WebElementFacade pmntMasterCard;  // one of the items in the list
```

I want to create a custom webelement that would wrap all those elements and hide all those details. So I could use something like dropdown.select("MASTERCARD");
I had an idea that I could use decorator for that since I used this approach on my previous non-serenitybdd projects. Maybe it is not a good idea, maybe it is not the way serenitybdd should be used. I don't know..i am still studying and exploring.

**Comment by Jazzyekim** [comment]
Even if not to take into account the task i am trying to solve my question is - what is the proper way to use decorator mechanism with WebElementFacade?

**Comment by wakaleo** [comment]
As @globalworming mentioned, most of the core Serenity developers don't use Page Objects anymore so this sort of requirement isn't very common. I would model that as a task. I would just have a method or object that modelled the two interactions together.
