### ISSUE TITLE
Serenity upgrade from 1.2.2 to latest 2.2.x

### ISSUE THREAD

**Issue by nshiveg** [serenity-bdd/serenity-core#2165]
Hi John and team,

Can we upgrade serenity core and other components(serenity-cucumber and serenity rest assured) to the latest 2.2.x
Is it possible? or it is not feasible. I have attached my POM here. 

By the way you people are really doing wonders. It is really good to see the way things are shaped in serenity. We in Nokia completely into the serenity. 

[pom.zip](https://github.com/serenity-bdd/serenity-core/files/4916831/pom.zip)

**Comment by wakaleo** [comment]
Hard to say from just the pom - a lot of the underlying libraries (such as Cucumber and rest assured) have had lots of breaking changes since version 1.2.2, so you will probably need to change your code as well.

**Comment by nshiveg** [comment]
Hi John,

Thanks a lot for your response. 
Code change is fine for us. But upgrade is supported is it?
There will not be any change in the cucumber feature file writing?, I mean what we had written in 1.1.23 serenity cucumber we don't need to change them correct. Since we have 5000 cases changing that would be really difficult.

**Comment by wakaleo** [comment]
Between Cucumber 1 and Cucumber 5+ there are many many API changes so your glue code will need to be updated fairly extensively.
