### ISSUE TITLE
Timeouts issue- implicit.wait is doubled

### ISSUE THREAD

**Issue by zuzeac** [serenity-bdd/serenity-core#2167]
Hi, 
I'm are using the following timeouts config in serenity.conf:
```
webdriver {
  driver = chrome
  timeouts {
    implicitlywait = 10000
  }
}
```

While trying to wait for an element, I observed that driver will wait the implicitwait X2, meaning 20000ms

`WaitUntil.the(target, isVisible())` will wait for 20000ms in this case. Should wait for only 10000ms as it is configured?
I'm assuming there is a bug somewhere in the timeouts or I didn't get it how to use it :)

**Comment by wakaleo** [comment]
Can you dig into the code to see?

**Comment by zuzeac** [comment]
I've tried digging, but didn't manage to identify where could the issue be.
To reproduce it you can just wait for an element which is not present in the page. `WaitUntil.the(addATargetWhichIsNotInThePage, isVisible())`

Forgot to mention the library version
` <serenity.version>2.2.8</serenity.version>
        <serenity.maven.version>2.2.8</serenity.maven.version>`
