### ISSUE TITLE
Is there any method to realize soft assertion between steps?

### ISSUE THREAD

**Issue by micropan111** [serenity-bdd/serenity-core#2170]
For example:

  Scenario: A Test Scenario
    When test step1
    And test step2
    And test step3

If test step1 is failed, I want to continue run step2 and 3.
So I try to turn on soft assertion by: StepEventBus.getEventBus().softAssertsActive();
    @Before
    public void initTest() {
        StepEventBus.getEventBus().enableSoftAsserts();
    }
But seems this is not worked, step2 and 3 are skipped after step1 failed

**Comment by wakaleo** [comment]
Soft asserts work within a step IIFC, not across steps.

**Comment by micropan111** [comment]
Thank you, my testsuit run with "CucumberWithSerenity", If I need to let step2 continue running regardless step1 pass or fail, is there any other solution?

**Comment by wakaleo** [comment]
No, that's not currently supported.
