### ISSUE TITLE
Is there any ways to compare 2 values after using Question in Screenplay?

### ISSUE THREAD

**Issue by lucas-nguyen-17** [serenity-bdd/serenity-core#2171]
I need to compare 2 values from 2 different elements using Question in Screenplay, but I cannot find any ways to do that.
`actor.should(seeThat(actual, expected))` defines: `actual` is Question and `expected` is Matcher.

I hope something like this:
`String value2 = Anwser.theQuestion(Question2);`
`actor.should(seeThat(Question1, is(value2)))`
Please let me know if you have any suggestions? Thanks in advance.

**Comment by globalworming** [comment]
Thats pretty easy actually. Just store the answer like `string value1 = actor.asksFor(question1)`

**Comment by lucas-nguyen-17** [comment]
@globalworming Thank you so much. I got it
