### ISSUE TITLE
Since version 2.2.2 Android & iPhone Environment Contexts Get Overwritten

### ISSUE THREAD

**Issue by gizdolok** [serenity-bdd/serenity-core#2172]
I use serenity-bdd with cucumber5 for mobile applications.

I run my tests for different platforms separately using commands

`mvn verify -Dcontext=android -Dinjected.tags='os:android'`
`mvn verify -Dcontext=iphone -Dinjected.tags='os:iphone'`

After these runs, I open the reports, and I get on Test Results tab all the scenarios identified by the icon of the corresponding mobile platform.

Problem is, this works perfectly up until Serenity version 2.2.2

Since then, I always get that the **last test run overwrites** the **previous** one.

Just tried with version 2.2.12 and result is the same.

Here is an illustration of what I get after running 2 tests: one for android and one for iphone:

<img width="253" alt="Screenshot 2020-07-16 at 22 01 59" src="https://user-images.githubusercontent.com/2281516/87717018-0200cd80-c7b0-11ea-8ad6-c14f50f642f6.png">                           <img width="255" alt="Screenshot 2020-07-16 at 21 40 32" src="https://user-images.githubusercontent.com/2281516/87715040-037cc680-c7ad-11ea-9e2d-7d9f0edbb344.png">

Tried to do `mvn serenity:aggregate` in between test runs and afterwards but doesn't help.

**Comment by FranciscoSanQA** [comment]
Hi @gizdolok , 
I'm experiencing  the  same problem in my tests. 
I open a issue https://github.com/serenity-bdd/serenity-core/issues/2129. 
I  create  a support ticket,  using the email that give me this link https://johnfergusonsmart.com/serenity-bdd-mentoring/ .
I think this is the way to report the issue .
@wakaleo sending the email is t he  correct  way to create a support  ticket?.
Shall we see the ticket in the dashboard   Serenity BDD Maintenance and Enhancements?
Thank

**Comment by gizdolok** [comment]
thanks @FranciscoSanQA 
Hopefully it gets fixed on some coming version
