### ISSUE TITLE
cucumber.steps.AuthenticationTokenSteps - this class doesn't have an empty or a page enabled constructor"

### ISSUE THREAD

**Issue by jainamit1712** [serenity-bdd/serenity-core#2173]
<properties>
		<serenity.version>1.9.12</serenity.version>
		<serenity.cucumber.version>1.9.5</serenity.cucumber.version>
		<serenity.maven.version>1.9.12</serenity.maven.version>
	</properties>

<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
		</dependency>
		
<dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-picocontainer</artifactId>
    <version>1.0.25</version>
</dependency>

I tried to implement very simple class to retrieve token and want to share across different scenarios 

public class AuthenticationTokenSteps {
	
	TestContextAPI testContext;
	
	public AuthenticationTokenSteps(TestContextAPI testContext) {
		this.testContext = testContext;
	}
	
	@Steps
	SerenityCommonMethodsSteps cmnMethod;
	
	
	@Given("user calls (.+) with (.+) http request")
	public void user_calls_with_http_request(String string, String string2) throws Exception {
		
	 testContext. AccessToken= cmnMethod.getAccessToken();
	
	  
	}

}

This is my contextclass

public class TestContextAPI {

	protected RequestSpecification req_spec=null;
    protected Response resp=null;
    protected String AccessToken = null;
  
    
}

I dont know why it is complaining  this class doesn't have an empty or a page enabled constructor. i have specified the constructor.

Please suggest how can i achieve this.

**Comment by jainamit1712** [comment]
These are the dependency i am using

<properties>
		<serenity.version>1.9.12</serenity.version>
		<serenity.cucumber.version>1.9.5</serenity.cucumber.version>
		<serenity.maven.version>1.9.12</serenity.maven.version>
	</properties>


<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
		</dependency>
		
<dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-picocontainer</artifactId>
    <version>1.0.25</version>
</dependency>

**Comment by wakaleo** [comment]
I'm not clear what you are trying to do?

**Comment by jainamit1712** [comment]
I want to share AccessToken value across all my step definition class using pico-container

Please refer below two classes TestContextApI(responsible to share accessToken value) and AuthenticationTokenSteps(called step) 

In the below example cmnMethod.getAccessToken(); returns me accessToken which i am storing in textcontext.accessToken so that i can share the value across different stepdefs. 

In order to achieve this i have created constructor below AuthenticationTokenSteps  and passed TextContextAPI class.

When i run the test it complaint this class doesn't have an empty or a page enabled constructor", but if you see in my AuthenticationTokenSteps class i have defined the constructor.




public class TestContextAPI {
protected String accessToken = null;
}
-----------------------------------------------------------------------------------------------------------
public class AuthenticationTokenSteps {

TestContextAPI testContext;

public AuthenticationTokenSteps(TestContextAPI testContext) {
	this.testContext = testContext;
}

@Steps
SerenityCommonMethodsSteps cmnMethod;


@Given("user calls (.+) with (.+) http request")
public void user_calls_with_http_request(String string, String string2) throws Exception {
	
 testContext. AccessToken= cmnMethod.getAccessToken();      ------this method retuns me accessToken
}






1. testContext. accessToken= cmnMethod.getAccessToken();-- -- this method returns me accessToken
2.

**Comment by jainamit1712** [comment]
I am able to achieve this with cucumber by implementing same logic but i am trying to do with serenity-bdd it is complaining "this class doesn't have an empty or a page enabled constructor"
