### ISSUE TITLE
chrome.switches changing value of --use-file-for-fake-video-capture

### ISSUE THREAD

**Issue by edgardosilverio** [serenity-bdd/serenity-core#2174]
My test is to check the take photo functionality of the page. 
I'm using and added --use-file-for-fake-video-capture=${user.dir}/src/test/resources/templates/takephoto.y4m to chrome.switches and it works pretty well. The question is, can i change the file value in chrome.switches? My other test requires me to take different photo to check the validity of photo taken. I tried setting a new value of chrome.switches using environmentVariables.setProperty("chrome.switches", newValue), it only changes the value of chrome.switches (as per checking in logs) but it didnt take effect.

**Comment by globalworming** [comment]
No sure if you can change the value on a running driver on the fly... try closing the current driver, then setting the system property, then starting the driver again.

**Comment by globalworming** [comment]
>  My other test requires me to take different photo to check the validity of photo taken

do you compare screenshots or videos?

**Comment by edgardosilverio** [comment]
> > My other test requires me to take different photo to check the validity of photo taken
> 
> do you compare screenshots or videos?

i'm taking photo using the video (y4m) loaded. so im changing it to blurry one if my test requires me to take invalid picture.
