### ISSUE TITLE
unable to publish index.html in azure devops pipeline

### ISSUE THREAD

**Issue by heerqa** [serenity-bdd/serenity-core#2177]
hi @wakaleo 
Hope you are doing well!!

Serenity run generates index.html report, which publish well in Jenkins. However, now many teams are moving to Azure devops.

I am able to run the serenity tests in the pipeline, but cannot publish HTML reports, since it need only Junit , xml format.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml

If you need, I can share my sample azure pipeline running the serenity tests using dockers .

Please let me know if we have any solution to publish results in azure devops pipeline.

**Comment by wakaleo** [comment]
Serenity also generates JUnit-compatible xml reports, thought they are not as rich as the actual Serenity reports. I would suggest publishing the reports to a static website when you run the builds.

**Comment by globalworming** [comment]
> How can we publish HTML reports(Generated on Agent machine) in Azure Release Pipeline or Test Plans?

https://stackoverflow.com/a/59470123/1359903
