### ISSUE TITLE
It seems that during using HTMLunit take screenshot always failing. 

### ISSUE THREAD

**Issue by YamStranger** [serenity-bdd/serenity-core#218]
HTMLUnit  cant not take screenshots, and serenity fails with it (default behaving - take screenshots if it is webtest)

https://code.google.com/p/selenium/issues/detail?id=1361

**Comment by wakaleo** [comment]
HTMLUnit has never been able to take screenshots, and Serenity normally copes with that correctly. Is this a new issue?

**Comment by YamStranger** [comment]
Now I working on jbehave, and here we use html unit. All stories with it fails because of exception, that HTML unit can not take screenshots. I created test that now fails (and with @Ignored for now) in serenity-core, and will push it soon
