### ISSUE TITLE
jQuery is not defined when open page

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2182]
Hello,
I'm using the following libraries:
```
ext {
    junitVersion = '4.13'
    slf4jVersion = '1.7.30'
    assertJVersion = '3.16.1'
    serenityVersion = '2.2.10'
}

dependencies {
    testImplementation "junit:junit:${junitVersion}"
    testImplementation "org.slf4j:slf4j-simple:$slf4jVersion"
    testImplementation "org.assertj:assertj-core:${assertJVersion}"
    testImplementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-junit:${serenityVersion}"
}
```
When running our serenity test suite via Bamboo build sometimes the error "jQuery is not defined" is reported when using the method _open()_ from _PageObject_ class. Code snippet below:
```
14    @Given("The user is on the IDP login page.")
15    public boolean isOnLoginPage() {
16        loginPage.open();
17        return loginPage.isAtLoginPage();
18    }

```
Error trace below:
```
org.openqa.selenium.JavascriptException: org.openqa.selenium.JavascriptException: ReferenceError: jQuery is not defined
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'agent-bart-01', ip: '172.16.35.150', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-148-generic', java.version: '11.0.4'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 75.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200403170909, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 1372, moz:profile: /tmp/rust_mozprofilenRlP1f, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.4.0-148-generic, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 4bf9ede3-ddc7-4173-98e5-9f9...}
Session ID: 4bf9ede3-ddc7-4173-98e5-9f90e0c34d79
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'agent-bart-01', ip: '172.16.35.150', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-148-generic', java.version: '11.0.4'
Driver info: driver.version: unknown
org.openqa.selenium.JavascriptException: ReferenceError: jQuery is not defined
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'agent-bart-01', ip: '172.16.35.150', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-148-generic', java.version: '11.0.4'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 75.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200403170909, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 1372, moz:profile: /tmp/rust_mozprofilenRlP1f, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.4.0-148-generic, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 4bf9ede3-ddc7-4173-98e5-9f9...}
Session ID: 4bf9ede3-ddc7-4173-98e5-9f90e0c34d79
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'agent-bart-01', ip: '172.16.35.150', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-148-generic', java.version: '11.0.4'
Driver info: driver.version: unknown
	at steps.common.LoginSteps.isOnLoginPage(LoginSteps.java:16)
	at tests.notary.NotarySearchTest.login(NotarySearchTest.java:38)
```
I was trying to work around the above issue by using of _serenity.jquery.integration = true_ option but this did not help.

Please, advice some work around or a solution.
Thanks and best regards, André

**Comment by wakaleo** [comment]
What is your LoginSteps class doing?

**Comment by aybartsch** [comment]
Hi John, I have already pasted the lines of interested (14-18) in the 1st code block above. The LoginSteps class is just calling the open() method provided by Serenity's PageObject class. Means, the error is thrown somewhere within the Serenity framework.

**Comment by wakaleo** [comment]
Do you have a stack trace? There is not enough to go on here.

**Comment by aybartsch** [comment]
Unfortunately, not. Selenium is not really verbose here. Maybe you could advise me how to gather more debug info from Serenity resp. Selenium framework and I would try to reproduce the error. (The error just happens randomly.)

**Comment by wakaleo** [comment]
The message "jQuery is not defined" is not from Serenity, so I'm not sure where this is happening.

**Comment by aybartsch** [comment]
Probably worth to know: When calling the base url defined in _serenity.comf_ our system is performing numerous re-directs and opens an external login page. We assume some time critical thing here i.e. this external login page is not always loading the jQuery library in time. But this is just our guess and we would need more detailed info. Thus, could you please give me some advice how to continue with debugging?

**Comment by globalworming** [comment]
> this external login page is not always loading the jQuery library in time

is that's a possible explanation, maybe try reproducing the error without serenity just by navigating to the page, doing a few things, invoking jQuery with the javascript executor? let the test run a few times to see if there is any flakieness there..

can you share the login page? maybe a look at the chrome debugging tools by us could help?

**Comment by aybartsch** [comment]
Unfortunately, the login page is not reachable from the outside and restricted, too. But I'm gonna try to follow your proposal for stress testing the page. Thank you!

**Comment by aybartsch** [comment]
Although I'm using the open() method out of the Serenity framework could it be possible that a jQuery selector defined in _LoginPage_ class and displayed below may cause the issue? I mean when I'm trying to navigate to the login page where I try later on to find an element via jQuery but jQuery library is still missing then I should face _jQuery is not defined_. Right?
`
@FindBy(jquery = "span.pnidp-error-msg:contains('Ungültige Zugangsdaten.')")
private WebElementFacade divErrorMessage;
`

**Comment by wakaleo** [comment]
If you are using findBy(jquery) I imagine that you need JQuery to be present on the page already.

**Comment by aybartsch** [comment]
@wakaleo Thanks for your answer. But does the open() method in _BasePage_ class not already doing some jQuery stuff under the hood:

`
    private void open(final OpenMode openMode) {
        String startingUrl = updateUrlWithBaseUrlIfDefined(getPageUrls().getStartingUrl());
        openPageAtUrl(startingUrl);
        checkUrlPatterns(openMode);
        initializePage();
    }
`

I mean Javascript support of the driver class is checked and even added if required.

**Comment by aybartsch** [comment]
@wakaleo @globalworming Seems that removing the findBy(jQuery) from our _LoginPage_ class could solve the issue. Gonna close the ticket. Thanks you both!

**Comment by aybartsch** [comment]
@wakaleo FYI: The removal of findBy(jQuery) could not solve this issue but the setting "serenity.jquery.integration = false" could.

**Comment by wakaleo** [comment]
Thanks for the update
