### ISSUE TITLE
CSV report for the serenity will not be having the scenario outline example count

### ISSUE THREAD

**Issue by nshiveg** [serenity-bdd/serenity-core#2185]
Hi John,

Can we have scenario outline count to be included in the CSV report please. Our Nokia management ask for this many times why there is count mismatch. Rather we need to manually go and update the count in the excel.

To explain with an example, when the below get executed. Then in the CSV report there will be one scenario and count as 1. Where as in the serenity report there will be 3. 

 @manual
  Scenario Outline: Searching for a term
    Given Sergey is on the DuckDuckGo home page
    When he searches for <TEST>
    Then all the result titles should contain the word "Cucumber"

    Examples: 
      | TEST |
      |    1 |
      |    2 |

Can serenity be fixed with this please.I had raised this concern 3 years back also.
We took the new serenity, the issue is still there :)

Thanks a lot, as I mention always serenity people have made the automation life easy. You are people are awesome

**Comment by globalworming** [comment]
@nshiveg I have some trouble understanding the issue. The best way to describe your request is to create an example project.
Could you quickly set up a minimal project that we can run and then point us to the values you need changes for. Maybe create a `expected-summary.csv`?

**Comment by nshiveg** [comment]
Hi @globalworming ,

![image](https://user-images.githubusercontent.com/20845350/88926581-d1329500-d293-11ea-8dba-ae969d17271e.png)

The above image shows manual counting as 2. In the CSV we have only 1. The question is can we have count lable in the report xls

Actual excel is what serenity is allowed to download from the report. Expected excel is what we wanted.

[actual.xlsx](https://github.com/serenity-bdd/serenity-core/files/5001400/actual.xlsx)
[Expected.xlsx](https://github.com/serenity-bdd/serenity-core/files/5001401/Expected.xlsx)

**Comment by wakaleo** [comment]
The CSVReporter is the class you want to look it.
