### ISSUE TITLE
Using "new FirefoxOptions()" is preferred to "DesiredCapabilities.firefox()"

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2187]
Hello,
I'm using Serenity version 2.2.12 and I'm always facing the below STANDARD_ERROR in our build log:

```
tests.common.LoginTest > shouldNotBeAbleToLogin STANDARD_ERROR
build	31-Jul-2020 10:12:33	    Jul 31, 2020 10:12:33 AM org.openqa.selenium.remote.DesiredCapabilities firefox
build	31-Jul-2020 10:12:33	    INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
build	31-Jul-2020 10:12:40	    Jul 31, 2020 10:12:40 AM org.openqa.selenium.remote.ProtocolHandshake createSession
build	31-Jul-2020 10:12:40	    INFO: Detected dialect: W3C
```

I having set "driver.capabilities = mydriver" in _serenity.conf_ which is most probably causing the above warning. How could I set the FirefoxOptions() instead of capabilities to get rid off the above message?

Thanks and best regards, André

**Comment by globalworming** [comment]
In your custom DriverSource you just need to create the firefox driver differently.

does this help? https://stackoverflow.com/a/57042225/1359903

> FirefoxOptions options = new FirefoxOptions();
> options.setBinary("C:\\Program Files\\Mozilla Firefox\\firefox.exe");
> WebDriver driver =  new FirefoxDriver(options);

**Comment by aybartsch** [comment]
Thanks, @globalworming. I came across the same solution but I was hoping you could provide something similar like "serenity.driver.options = new FirefoxOptions()". Since, I would like to avoid a custom driver setup but prefer to use Serenity config instead.

**Comment by aybartsch** [comment]
@globalworming Would it be possible to set the options via _serenity.conf_?

**Comment by wakaleo** [comment]
You can always propose a PR to change the Serenity code.

**Comment by aybartsch** [comment]
@wakaleo I know I could but I guess my dev skills are not sufficient enough to enhance the Serenity framework by myself. Sorry.

**Comment by aybartsch** [comment]
@wakaleo May I issue a change request to support FirefoxOptions() for future versions?

**Comment by ArvindDangi007** [comment]
I am still facing this "INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`" on Serenity BDD. Could you please help. @aybartsch @wakaleo
