### ISSUE TITLE
Saucelabs not working with macOS

### ISSUE THREAD

**Issue by xMagiciaNx** [serenity-bdd/serenity-core#2193]
I am trying to run remote tests on saucelabs with safari and macos.
The command i sent is:

`mvn verify -Dsaucelabs.target.platform="macOS 10.15" -Dwebdriver.driver=safari -Dsaucelabs.driver.version=13.1  -Dsaucelabs.url=http://***** -Dsaucelabs.access.key=***** -Dsaucelabs.user.id=**** -Dwebdriver.remote.os=MACOS -Dcontext=safari`

When running it i get:

`Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.remote.RemoteWebDriver (macos 10.15). See below for more details.`

Any suggestion? Am I doing something wrong? Ty.

**Comment by wakaleo** [comment]
Most likely Saucelabs is not happy with the options you are passing it.

**Comment by xMagiciaNx** [comment]
Ty wakaleo for the quick answer, this one runs, but I don't see what am i doing wrong here.

`mvn verify -Dsaucelabs.target.platform="Windows 10" -Dwebdriver.driver=firefox -Dsaucelabs.driver.version=70 -Dsaucelabs.url=http://**** -Dsaucelabs.access.key=**** -Dsaucelabs.user.id=*** -Dwebdriver.remote.os=WINDOWS -Dcontext=firefox`

**Comment by wakaleo** [comment]
Can you get other combinations to work? I’ve found that some combinations don’t work with Saicelabs. (Serenity is just passing the fields to Saucebabs and reporting the error)

**Comment by xMagiciaNx** [comment]
`mvn verify -Dsaucelabs.target.platform="macOS 10.13" -Dwebdriver.driver=safari -Dsaucelabs.driver.version=13 -Dsaucelabs.url=*** -Dsaucelabs.access.key=**** -Dsaucelabs.user.id=*** -Dwebdriver.remote.os=MACOS -Dcontext=safari  
`

Yes this one works :) 
So it seems something happening to the saucdelabs, nice to know 👍

**Comment by wakaleo** [comment]
Closing as it appears to be a saucelabs config question.
