### ISSUE TITLE
Debugger extremely slow when jQuery integration is set to false

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2194]
Hello,
to solve #2182 I have finally set _jquery.integration = false_ in the serenity config file. Unfortunately, this setting is slowing down the debugger extremely. When evaluating expressions e.g. _getDriver()_ at a break point it takes approx. one minute to get the response. It seems that there is a kind of timeout when not having jQuery integration (injection) active. As soon as the option is set to true the evaluation is performed without any delay. Please, correct this wrong behaviour.
Thanks and best regards, André

**Comment by wakaleo** [comment]
This is the only place this option is used: 

https://github.com/serenity-bdd/serenity-core/blob/d4e7539f523c4df78feb737216206dd4e330aadc/serenity-core/src/main/java/net/serenitybdd/core/pages/PageObject.java#L1207

Turning the option off _reduces_ the number of interactions with the browser. The only reason it might delay is if your tests depend on JQuery (for example if you use JQuery locators) and these locators time out when you don't have JQuery on your pages. So I don't think the delays are related to the Serenity code.

**Comment by aybartsch** [comment]
Thanks for your instant answer, @wakaleo.

Indeed, I'm using some jQuery selectors but all our pages are having jQuery library imported. Apart from that when there is an issue with jQuery I would expect an exception thrown but no wait. I was just trying to evaluate the webdriver by typing  _getDriver()_ or to get an element by css selector _getDriver().findElementBy()_ in the debugger session.

But now it becomes totally strange: In order to get some more details for you I have switched off the jQuery integration again and the issue was not happening anymore. I cannot understand the reason why but for now the issue is solved at least on my IDE. Maybe, there was something in the IDE cache which was causing this remarkable delay...

**Comment by aybartsch** [comment]
Seems that the problem was more caused by IntelliJ Idea than by Serenity framework. Going to close this ticket.
