### ISSUE TITLE
Serenity report at scenario level details is taking to file not found html page

### ISSUE THREAD

**Issue by sheerintaj** [serenity-bdd/serenity-core#2195]
Hi John,

I am trying to configure multi-browser and multi-environment testing in serenity BDD with cucumber. I am good with all setup, also got the aggregate report. But when i try to navigate from test results tab to scenario level step details I get html file not found message.

https://johnfergusonsmart.com/running-tests-different-environments-browsers-serenity-bdd/

When i checked the reports i see the html file for that particular scenario is generated, but from index links its taking me to the HTML file which is not at all generated.

I am using the below version of serenity ,JUnit & Cucumber.

serenity -Core : 2.2.9
serenity-junit :2.2.9
Serenity-cucumber5:2.2.0

Thanks in advance!

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces the issue?

**Comment by sheerintaj** [comment]
I have no sample project in my personal machine. Could you please guide me with configurations that need to be checked to resolve this issue.
