### ISSUE TITLE
While executing a runner file I see the console errors, but test gets passed.

### ISSUE THREAD

**Issue by shivajibharpure** [serenity-bdd/serenity-core#2197]
1992 [main] ERROR net.thucydides.core.model.TestOutcome - Tag provider net.thucydides.core.requirements.FileSystemRequirementsTagProvider@784c3487 failure
cucumber.runtime.CucumberException: gherkin.ParserException$CompositeParserException: Parser errors:
(21:5): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'And	user clicks on "Menu Bar" on menu to test page visibility'
.
.
.
.
.	at gherkin.Parser.addError(Parser.java:152)
	at gherkin.Parser.matchTokenAt_9(Parser.java:1068)
	at gherkin.Parser.matchToken(Parser.java:364)
	at gherkin.Parser.parse(Parser.java:137)
	at gherkin.Parser.parse(Parser.java:118)
	at gherkin.Parser.parse(Parser.java:114)
	at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:56)
	... 78 more

1 Scenarios (1 passed)
5 Steps (5 passed)
0m49.225s

Process finished with exit code 0

**Comment by wakaleo** [comment]
There’s an error in your feature file:

Parser errors:
(21:5): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'And user clicks on "Menu Bar" on menu to test page visibility'

**Comment by shivajibharpure** [comment]
Feature file is simple and clean, shown below. 
Error at "got 'And user clicks on "Menu Bar" on menu to test page visibility'" doesn't contain this step in current feature file.

Feature: Demo Test Scenarios

  Scenario: 1 Login test
    Given the user is navigate to loginpage
    And user enters username as "SuperUser" password as "SuperUserPassword" and station name as "StationName"
    And user clicks on "SignInButton" on login page
    And user clicks on "RLink" on common page
    And user finds test data from db to be used
      | dbColumn|  value |
      | channel |    NA   |

**Comment by wakaleo** [comment]
Cucumber is complaining about the feature file containing the text “And user clicks on "Menu Bar" on menu to test page visibility'
