### ISSUE TITLE
serenity:check doesn’t work with cucumber tags notation

### ISSUE THREAD

**Issue by yavgel** [serenity-bdd/serenity-core#2198]
- run your tests with next command format:
`mvn clean verify -Dtags="UI_FEAT or API_LIVE or API_FEAT or JAZO_API and not EMAIL_LIVE_ORDER and not EMAIL_LIVE_MESSAGE" serenity:check`

**Current results:**
`serenity:check` command shows SUCCESS although there are test errors and failures

![1](https://user-images.githubusercontent.com/8123409/89807793-71f93e00-db39-11ea-82b3-77e92723d2c1.png)

Tried without cucumber tags notation - ALL GOOD, no issues:
`mvn clean verify serenity:check` 

![2](https://user-images.githubusercontent.com/8123409/89807895-935a2a00-db39-11ea-833b-84a7aeb88cf0.png)

PARTIALLY RELATED to: https://github.com/serenity-bdd/serenity-core/issues/2007

TESTED ON: Linux (from GitHub Actions CI)

**Comment by wakaleo** [comment]
serenity:check does not support filtering - use mvn clean verify for that

**Comment by yavgel** [comment]
> serenity:check does not support filtering - use mvn clean verify for that

thank you @wakaleo , yeah it is unfortunate for me to be honest, I really need to have this capability.
@wakaleo  - do you have a plan in future to implement it?

**Comment by wakaleo** [comment]
Not at this stage.
