### ISSUE TITLE
Steps annotated with @And are not reported

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2200]
Hello,
I'm using the below setup:
```
    junitVersion = '4.13'
    slf4jVersion = '1.7.30'
    assertJVersion = '3.16.1'
    serenityVersion = '2.2.12'
    jacksonVersion = '2.11.1'
```
When annotating my test steps "io.cucumber.java.en.And" the corresponding text is not printed to console. Moreover, no reporting i.e. no screenshots have been created. Please, have a look to this issue.

Thanks and best regards, André

**Comment by wakaleo** [comment]
I can't reproduce this using  - @cliviu ?

**Comment by aybartsch** [comment]
@wakaleo This issue was caused by a wrong combination of junit and cucumber. Meanwhile, I could fix this issue by myself. Thanks for your support.
