### ISSUE TITLE
Uninitialised WebDriverFacade

### ISSUE THREAD

**Issue by raniswap** [serenity-bdd/serenity-core#2201]
I am getting Uninitialised WebDriverFacade when try get the webdriver instance using getDriver() method.

im using below properties in my property file.

webdriver.base.url=https://www.localhost.com/
webdriver.timeouts.implicitlywait=5000
webdriver.wait.for.timeout=10000
serenity.browser.maximized=true
serenity.take.screenshots=FOR_EACH_ACTION
webdriver.driver=chrome
webdriver.chrome.driver=src/test/resources/drivers/chromedriver.exe
chrome_preferences.profile.default_content_setting_values.notifications=2

this is my pom jar versions.
<serenity.version>2.2.12</serenity.version>
<serenity.maven.version>2.2.12</serenity.maven.version>
<serenity.cucumber.version>2.2.5</serenity.cucumber.version>
<serenity.restassured.version>2.2.12</serenity.restassured.version>

<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.3.2.RELEASE</version>

**Comment by raniswap** [comment]
getDriver() i can see driver is initialized.
@Managed()
WebDriver driver; when i inspect driver here it gives null value

**Comment by wakaleo** [comment]
What does your code look like?

**Comment by raniswap** [comment]
Im trying to access getDriver() from page step class

@Configuration
public class ThreadLocalConf {

	@Bean("threadLocal")
	public ThreadLocal<HashMap<String, Object>> threadLocal() {
		HashMap<String, Object> hm = new HashMap<>();

		ThreadLocal<HashMap<String, Object>> tl = new ThreadLocal();
		tl.set(hm);

		return tl;
	}

}


@ContextConfiguration(classes = { ThreadLocalConf.class })
public class PageObjectHelper extends PageObject {

	@Autowired
	ThreadLocal<HashMap<String, Object>> threadLocal;

	public WebDriver getDriverInstance() {

		WebDriver driver = getWebDriverInstance();
		return driver;
	}

	public WebDriver getWebDriverInstance() {
		if (threadLocal.get().get("chromedriver") == null) {
			return getDriver();
		} else {
			return (WebDriver) threadLocal.get().get("chromedriver");
		}

	}

}

public class CustomDriver implements DriverSource {

	@Override
	public WebDriver newDriver() {
		System.setProperty("webdriver.driver", "chrome");
		System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver.exe");

		ChromeOptions chromeOptions = new ChromeOptions();
		// chromeOptions.addArguments("--headless");
		chromeOptions.addArguments("--no-sandbox");
		chromeOptions.addArguments("--disable-dev-shm-usage");
		chromeOptions.addArguments("--window-size=1920,1080");
		// chromeOptions.addArguments("--log-level=3");
		chromeOptions.addArguments("--start-maximized");
		WebDriver driver = new ChromeDriver(chromeOptions);
		return driver;

	}

	@Override
	public boolean takesScreenshots() {
		// TODO Auto-generated method stub
		return true;
	}

}

**Comment by wakaleo** [comment]
Looks like you are trying to mix Spring dependency injection with Serenity dependency injection - that won't work. What problem are you trying to solve? This seems very complicated code.

**Comment by raniswap** [comment]
in my automation i have two sets of scenarios, some tests need chromedriver and some need appium driver. 
i thought i can achieve this by overriding DriverSource interface.
Can you please suggest how can solve this

**Comment by raniswap** [comment]
serenity property file used:
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.walmart.classic.utility.CustomDriver
thucydides.driver.capabilities = mydriver
serenity.project.name = End to End Automation
serenity.use.unique.browser = false
serenity.browser,height = 1200
serenity.browser,width = 1500
serenity.dry.run=false
serenity.restart.browser.for.each = never

#serenity.test.root=net.thucydides.showcase.cucumber.junit

# How long does Serenity wait for elements that are not present on the screen to load
webdriver.timeouts.implicitlywait = 60000
webdriver.wait.for.timeout = 60000
serenity.take.screenshots=AFTER_EACH_STEP
serenity.report.show.manual.tests=false
serenity.reports.show.step.details=true
serenity.take.screenshots.for.interactions=AFTER_EACH_STEP

#android testing
appium.platformName=Android

**Comment by raniswap** [comment]
serenity property file used:
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.walmart.classic.utility.CustomDriver
thucydides.driver.capabilities = mydriver
serenity.project.name = End to End Automation
serenity.use.unique.browser = false
serenity.browser,height = 1200
serenity.browser,width = 1500
serenity.dry.run=false
serenity.restart.browser.for.each = never

webdriver.timeouts.implicitlywait = 60000
webdriver.wait.for.timeout = 60000
serenity.take.screenshots=AFTER_EACH_STEP
serenity.report.show.manual.tests=false
serenity.reports.show.step.details=true
serenity.take.screenshots.for.interactions=AFTER_EACH_STEP

#android testing
appium.platformName=Android

**Comment by raniswap** [comment]
serenity property file used:
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.test.classic.utility.CustomDriver
thucydides.driver.capabilities = mydriver
serenity.project.name = End to End Automation
serenity.use.unique.browser = false
serenity.browser,height = 1200
serenity.browser,width = 1500
serenity.dry.run=false
serenity.restart.browser.for.each = never

webdriver.timeouts.implicitlywait = 60000
webdriver.wait.for.timeout = 60000
serenity.take.screenshots=AFTER_EACH_STEP
serenity.report.show.manual.tests=false
serenity.reports.show.step.details=true
serenity.take.screenshots.for.interactions=AFTER_EACH_STEP

#android testing
appium.platformName=Android

**Comment by wakaleo** [comment]
It looks like you are trying to have classes that are managed by both Spring and Serenity. Separate these concepts and it should work.

**Comment by raniswap** [comment]
you have any sample project which i can refer.

Regards

**Comment by raniswap** [comment]
Thank you .. i separated both the logic, now it's working fine.

**Comment by LinhTH91** [comment]
Sorry, I got issue Uninitialised WebDriverFacade when run feature file. I used anotation @Steps for LoginStep class so I think WebDriver must be initial but in real is not. Sorry if my question is not suitable. 
```
---------------------------------------------------------------

Feature: Add new item to TODO list

  Scenario: I want to login system
    Given Open URL
    Then Login screen is displayed
---------------------------------------------------------------

import net.serenitybdd.core.pages.PageObject;
import net.thucydides.core.annotations.DefaultUrl;

@DefaultUrl("https://www.google.com.vn/")
public class LoginPage extends PageObject {
}
---------------------------------------------------------------

import net.thucydides.core.annotations.Step;
import net.thucydides.core.steps.ScenarioSteps;
import page.LoginPage;

public class LoginStep extends ScenarioSteps {
    LoginPage loginPage;
    @Step
    public void openWeb() {
        loginPage.open();
    }
}
------------------------------------------------------------

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import net.thucydides.core.annotations.Steps;
import step.LoginStep;

public class LoginMapper {
    **@Steps**
    LoginStep loginStep;
    @Given("Open URL")
    public void open_url() {
        loginStep.openWeb();
    }
    @Then("Login screen is displayed")
    public void login_screen_is_displayed() {
        System.out.println("a");
    }
}

```
