### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.NullPointerException: No BaseStepListener has been registered : Throwing this exception under Java's Callable interface call() method with Serenity

### ISSUE THREAD

**Issue by nitin1989** [serenity-bdd/serenity-core#2203]
Hi ,
I am getting below exception on using Callable interface call() method implemetation with Serenity.

java.util.concurrent.ExecutionException: java.lang.NullPointerException: No BaseStepListener has been registered
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.serenity.test.cucumberStepDefinitions.api.EmployeeGlue.i_hit_API_n_times_with_body_data_as(EmployeeGlue.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)

Below is the code I am using inside Callable interface's call() method:

 @Override
    public String call() throws Exception 
    {
        Response res=null;
        StringBuilder sb = new StringBuilder();
        res=employee.createNewEmployee(url,payload); // Calling to POST API to create employees
        JsonPath jsonpath = res.jsonPath();
        String name = jsonpath.get("name");
        sb.append("API Response : ").append(res.asString()).append('\n');
	sb.append("Name : ").append(name).append('\n');
	**Serenity.recordReportData().withTitle("Employee Creation : ").andContents(sb.toString());**  // Exception thrown here.
	return name;
 
    }

Exception is getting thrown in above code when logging content in Serenity report(Line of code highlighted above in bold)

**Comment by wakaleo** [comment]
You are using Serenity in a separate thread - that won’t work.

**Comment by nitin1989** [comment]
Why is this so?

**Comment by wakaleo** [comment]
The Serenity reporter is thread local and tied to a particular thread.

**Comment by nitin1989** [comment]
Ok. Is there any workaround for logging the content in Serenity report, since its not even logging the API request and response in Serenity report on using SerenityRest class within Callable implementation.

**Comment by wakaleo** [comment]
You would need to look at the code to figure out a way to do this.
