### ISSUE TITLE
javascript error: jQuery is not defined

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#2205]
About 2% of my tests fail with:
```
org.openqa.selenium.JavascriptException: javascript error: jQuery is not defined
  (Session info: headless chrome=85.0.4183.69)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '...', ip: '...', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.6.1.el7.x86_64', java.version: '1.8.0_242'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 85.0.4183.69, chrome: {chromedriverVersion: 85.0.4183.38 (9047dbc2c693f..., userDataDir: /tmp/.com.google.Chrome.rnwS7l}, goog:chromeOptions: {debuggerAddress: localhost:39911}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 4788d3c664ffd156cd1a5aba7f2f56f8
```

There is no additional stacktrace info!

My tests do not use any jQuery at all.

Through some creative logging and debugging, I have been able to determine this is happening when the browser is first started. I have a `Task` something like:
```
@Step("{0} launches Application")
@Override
public <T extends Actor> void performAs(T actor) {

	actor.wasAbleTo(Open.browserOn().the(applicationLandingPage));

	// more code for logging in
}


@DefaultUrl("https://...")
public class ApplicationLandingPage extends PageObject {
	// empty
}
```

Some other possibly relevant information:

- using latest Google-Chrome-Beta with matching chromedriver
- using latest Serenity
- running tests in parallel or sequential makes no difference
- the same test does not fail twice in a row

I am at a loss as to what to try or how to track down this problem. Any advice is appreciated.

**Comment by srilakshmishankar** [comment]
I face this error as well when I try to do page.open() and I agree with all details mentioned above. It fails so randomly and out of ideas to how to fix this.

**Comment by wakaleo** [comment]
Have you tried setting `serenity.jquery.integration` to false?

**Comment by srilakshmishankar** [comment]
> Have you tried setting `serenity.jquery.integration` to false?

Thanks for the reply, I will try this and update. Where can I find info about this configuration? I did not find anything on this anywhere.

**Comment by SiKing** [comment]
@srilakshmishankar There is little bit of documentation on that switch here https://github.com/serenity-bdd/serenity-core/blob/master/serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java#L681

We had discovered some code in our application that interacted with this injected jQuery in an undesirable way.
I had also opened this same bug with chromedriver here https://bugs.chromium.org/p/chromedriver/issues/detail?id=3581 if you are interested in some additional information.

From my point of view, this bug can be closed.
