### ISSUE TITLE
How to download HAR file using serenity for chrome browser

### ISSUE THREAD

**Issue by dinezbabu** [serenity-bdd/serenity-core#2209]

**Comment by dinezbabu** [comment]
Without using browserMob
Similar to
props.setProperty("devtools.netmonitor.enabled", "true");
        props.setProperty("devtools.netmonitor.har.compress", "true");
        props.setProperty ("devtools.netmonitor.har.defaultFileName", "Autoexport_%y%m%d_%H%M%S");
        props.setProperty("devtools.netmonitor.har.defaultLogDir", FilePath.OUTPUT_DIRECTORY);
        props.setProperty("devtools.netmonitor.har.enableAutoExportToFile", "true");
        props.setProperty("devtools.netmonitor.har.forceExport", "true");
        props.setProperty("devtools.netmonitor.har.includeResponseBodies", "false");
        props.setProperty("devtools.netmonitor.har.jsonp", "false");
        props.setProperty("devtools.netmonitor.har.jsonpCallback", "false");
        props.setProperty("devtools.netmonitor.har.pageLoadedTimeout", "2500");
        props.setProperty("devtools.toolbox.selectedTool","netmonitor");
        props.setProperty("devtools.netmonitor.har.forceExport","true");

**Comment by wakaleo** [comment]
Do you know the chromedriver options you need?
