### ISSUE TITLE
Serenity does not recognise JUnit TestRules

### ISSUE THREAD

**Issue by johndeverall** [serenity-bdd/serenity-core#221]
Serenity does not seem to recognise JUnit Test Rules. It does however recognise JUnit TestClass Rules. 

I have provided an [example happy case](https://github.com/johndeverall/testcases/tree/master/JUnitTestRulesInSerenity/SpringMethodRuleHappyCase) and [example failure case](https://github.com/johndeverall/testcases/tree/master/JUnitTestRulesInSerenity/SpringMethodRuleFailure).

@wakaleo - these examples are mostly demo code you wrote. Is this a bug in Serenity or are you able to quickly point out what I'm doing wrong from these test cases? Also @ScottDennison I see you wrote some TestRule code back in Juneish? I can't seem to get your Rules to work either. You might have an idea about this? 

This issue also relates to [this stackoverflow question](http://stackoverflow.com/questions/31492691/how-do-i-specify-test-runner-in-serenity-tests/34121652#34121652).

**Comment by ScottDennison** [comment]
@johndeverall
I've had a super quick look at the code you provide and I can't see anything wrong.
I'm unfortunately don't have time for an in-depth look (I'm just off to bed and I have a busy week ahead)

Does it not recognize all JUnit Test rules, or specifically those directly related to spring (both SpringMethodRule or SpringIntegrationMethodRule)?
<i><sub><sup>(By the way, thank for indirectly letting me know about SpringMethodRule and SpringClassRule which I didn't know about before - they didn't exist when I wrote SpringIntegrationMethodRule and SpringIntegrationClassRule)</sup></sub></i>

If it does recognize those, but not the spring ones, it might be worth trying to temporarily downgrade the version of spring in the projects to the same version serenity currently uses in its CI tests, and try again to see if they suddenly work. Behind the scenes, both my rules and the new spring rules eventually call code in various classes provided by spring in the package org.springframework.test.context.junit4.statements.* - If there is a bug in the code in this package, then it would cause problems with both my rules and spring's rules.

**Comment by johndeverall** [comment]
@ScottDennison good luck getting all your changes in before the moratorium. Thank you for the insight. The failure case test case code I posted is not recognising any rules, including your rules, any rules I write myself, or the spring rules. 

I'll try your tips and let you know how I get on.

**Comment by johndeverall** [comment]
To me this seems like a bug in Cucumber philosophy but could potentially be worked around with cucumber-junit if /cucumber/cucumber-jvm#393 is anything to go by. Time to try JBehave :+1:

**Comment by johndeverall** [comment]
Relocated this issue as it is a serenity-cucumber issue, not a serenity-core issue.
