### ISSUE TITLE
Question: How to Auto linking of the zephyr test case and JIRA story issue.

### ISSUE THREAD

**Issue by Manish123chandel** [serenity-bdd/serenity-core#2210]
Hi @wakaleo ,

Please help me to complete this requirement and suggest me any doc if existing, I tried lot of docs but couldn't get.
Requirement:
There is a testcase script annotated with @Issue(#ABC-114). We want to create link automatically in its corresponding Story jira ticket. means it should link this issue to it's Story ticket jira automatically.
As we know , we can do linking manually through the "Link" click on jira and can add any Jira ticket to link any issue/Story.
We are thinking to do it automatically when we run the Zypher testscript(or can say Normal script in serenity) annotated with @Issue tag.
Can you please tell me ? It is doable?

Thanks, waiting for your reply.

**Comment by globalworming** [comment]
there seems to be an API for that https://getzephyr.docs.apiary.io/#reference/testcaseresource/adds-issue-link/add's-issue-link

i believe, if you want to do anything after a serenity test (suite) executed, you would need some kind of processor that finds the generated test reports, finds the issue links and then loops over them to call the zephyr api.

maybe check how the serenity report aggregator does it and https://serenity-bdd.github.io/theserenitybook/latest/importing-test-outcomes.html

**Comment by Manish123chandel** [comment]
I'm closing the issue I got the alternate way to do this.


Thanks for your help
