### ISSUE TITLE
JUnit SerenityRunner.class became unavailable after serenity core v2.2.13 update

### ISSUE THREAD

**Issue by yavgel** [serenity-bdd/serenity-core#2211]
![image](https://user-images.githubusercontent.com/8123409/91029046-9277cc80-e5fe-11ea-9078-02fc6b7c4eb8.png)

**Comment by wakaleo** [comment]
It's still there, so this looks like an IDE issue:

![image](https://user-images.githubusercontent.com/55986/91030590-50975800-e5f7-11ea-94b5-875c308ee3c1.png)
