### ISSUE TITLE
Serenity reports shows 0 results (using Cucumber latest)

### ISSUE THREAD

**Issue by klaksh** [serenity-bdd/serenity-core#2212]
We are using the latest Cucumber version and trying to get reports using Sereniyty.
Used command: mvn serenity:aggregate

pom.xml file dependency versions:

		<commons.io>2.7</commons.io>
		<guice.version>4.2.3</guice.version>
		<selenium.java.version>3.141.59</selenium.java.version>
		<cucumber.java.version>6.4.0</cucumber.java.version>
		<cucumber.junit.version>6.4.0</cucumber.junit.version>
		<cucumber.core.version>6.4.0</cucumber.core.version>
		<cucumber.testng.version>6.4.0</cucumber.testng.version>
		<junit.version>4.13</junit.version>
		<cucumber.jvm.deps>1.0.6</cucumber.jvm.deps>
		<cucumber.java8.version>6.4.0</cucumber.java8.version>
		<log4j.version>1.2.17</log4j.version>
		<phantomjsdriver.version>1.4.4</phantomjsdriver.version>
		<serenity.version>2.2.1</serenity.version>
		<serenity.cucumber.version>2.2.0</serenity.cucumber.version>
		<serenity.maven.plugin.version>2.2.1</serenity.maven.plugin.version>
		<maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
		<json.smart.version>2.3</json.smart.version>
		<json.flattener.version>0.7.1</json.flattener.version>
		<json.version>20200518</json.version>
		<serenity.cucumber4.version>2.1.2</serenity.cucumber4.version>
		<cucumber.junit.version.old>4.2.0</cucumber.junit.version.old>
		<json.simple.version>1.1.1</json.simple.version>
		<hawk.core.version>1.2.3</hawk.core.version>
		<testng.version>7.3.0</testng.version>
		<jackson.mapper.asl.version>1.9.13</jackson.mapper.asl.version>
		<gson.version>2.8.6</gson.version>
		<log4j.version>1.2.17</log4j.version>
		<java.version>1.8</java.version>
		<slf4j.version>1.6.1</slf4j.version>
		<maven.failsafe.plugin.version>3.0.0-M5</maven.failsafe.plugin.version>

and <build> section of the pom.xml file:
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>${maven.failsafe.plugin.version}</version>
				<configuration>
					<includes>
						<include>**/*.java</include>
					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.plugin.version}</version>
				<executions>
                <execution>
                    <phase>test-compile</phase>
                    <goals>
                        <goal>testCompile</goal>
                    </goals>
                </execution>
            </executions>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.plugin.version}</version>
				<configuration>
                <tags>${tags}</tags>
            </configuration>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

When run the command mvn serenity:aggregate:
![image](https://user-images.githubusercontent.com/55970987/91303991-6e66e780-e7c6-11ea-8b68-5e37b844334d.png)

The index.html report shows the feature file / scenario title however results shows 0.

The project structure is:
src/test/java/features (had tried by keeping under src/test/resources, but didn't work)
src/test/java/stepDefinitions

Runner file:
import org.junit.runner.RunWith;
import io.cucumber.junit.*;
import net.serenitybdd.cucumber.CucumberWithSerenity;

@RunWith(CucumberWithSerenity.class)                    
@CucumberOptions(
        features= {"src/test/java/features/"},         
        glue = {"src.test.java.stepDefinitions."},
        tags = "@core",
        plugin = {"pretty","html:target/html-report",
        		"json:target/cucumber.json"}
       
        )              

public class RunnerFile {
	
	

}

Complete pom.xml file:

	<properties>

		<commons.io>2.7</commons.io>
		<guice.version>4.2.3</guice.version>
		<selenium.java.version>3.141.59</selenium.java.version>
		<cucumber.java.version>6.4.0</cucumber.java.version>
		<cucumber.junit.version>6.4.0</cucumber.junit.version>
		<cucumber.core.version>6.4.0</cucumber.core.version>
		<cucumber.testng.version>6.4.0</cucumber.testng.version>
		<junit.version>4.13</junit.version>
		<cucumber.jvm.deps>1.0.6</cucumber.jvm.deps>
		<cucumber.java8.version>6.4.0</cucumber.java8.version>
		<log4j.version>1.2.17</log4j.version>
		<phantomjsdriver.version>1.4.4</phantomjsdriver.version>
		<serenity.version>2.2.1</serenity.version>
		<serenity.cucumber.version>2.2.0</serenity.cucumber.version>
		<serenity.maven.plugin.version>2.2.1</serenity.maven.plugin.version>
		<maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
		<json.smart.version>2.3</json.smart.version>
		<json.flattener.version>0.7.1</json.flattener.version>
		<json.version>20200518</json.version>
		<serenity.cucumber4.version>2.1.2</serenity.cucumber4.version>
		<cucumber.junit.version.old>4.2.0</cucumber.junit.version.old>
		<json.simple.version>1.1.1</json.simple.version>
		<hawk.core.version>1.2.3</hawk.core.version>
		<testng.version>7.3.0</testng.version>
		<jackson.mapper.asl.version>1.9.13</jackson.mapper.asl.version>
		<gson.version>2.8.6</gson.version>
		<log4j.version>1.2.17</log4j.version>
		<java.version>1.8</java.version>
		<slf4j.version>1.6.1</slf4j.version>
		<maven.failsafe.plugin.version>3.0.0-M5</maven.failsafe.plugin.version>

	</properties>

	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${selenium.java.version}</version>
		</dependency>

		<dependency>
			<groupId>net.minidev</groupId>
			<artifactId>json-smart</artifactId>
			<version>${json.smart.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.wnameless</groupId>
			<artifactId>json-flattener</artifactId>
			<version>${json.flattener.version}</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>${json.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber4</artifactId>
			<version>${serenity.cucumber4.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.java.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.junit.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>${cucumber.core.version}</version>
		</dependency>

		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>${json.simple.version}</version>
		</dependency>
		<dependency>
			<groupId>com.wealdtech.hawk</groupId>
			<artifactId>hawk-core</artifactId>
			<version>${hawk.core.version}</version>
		</dependency>

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-mapper-asl</artifactId>
			<version>1.9.13</version>
		</dependency>

		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>${gson.version}</version>
		</dependency>

		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>${log4j.version}</version>
		</dependency>

<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
 
 
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>${maven.failsafe.plugin.version}</version>
				<configuration>
					<includes>
						<include>**/*.java</include>
					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.plugin.version}</version>
				<executions>
                <execution>
                    <phase>test-compile</phase>
                    <goals>
                        <goal>testCompile</goal>
                    </goals>
                </execution>
            </executions>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.plugin.version}</version>
				<configuration>
                <tags>${tags}</tags>
            </configuration>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

Please guide how to overcome this issue, tried by going through multiple articles on the internet, but coudn't resolve the issue on my own.

**Comment by wakaleo** [comment]
Like it says on the box, serenity-cucumber4 is compatible with Cucumber 4. Cucumber versions are not backward compatible, and Cucumber 6 is not yet supported.

**Comment by klaksh** [comment]
Changing versions to 4.0.0 for below dependencies:
<cucumber.java.version>4.0.0</cucumber.java.version>
		<cucumber.junit.version>4.0.0</cucumber.junit.version>
		<cucumber.core.version>4.0.0</cucumber.core.version>
		<cucumber.testng.version>4.0.0</cucumber.testng.version>


Will changing above versions would be sufficient to get serenity reports, or Do I need to update other dependencies too?
Please suggest.

**Comment by klaksh** [comment]
I guess need to update this as well

<dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-cucumber4</artifactId>
    <version>1.0.4</version>
</dependency>

**Comment by klaksh** [comment]
Able to integrate and get Serenity reports by following: https://www.youtube.com/watch?v=VNjrE3BXAAg
Had to change versions to older version as given below:
<serenity.version>2.0.81</serenity.version>
		<serenity.cucumber.version>1.9.45</serenity.cucumber.version>
		<serenity.maven.plugin.version>2.0.81</serenity.maven.plugin.version>

Thanks for the support and guidance.
