### ISSUE TITLE
Serenity Screenshots methods can be overwriting?

### ISSUE THREAD

**Issue by juferz** [serenity-bdd/serenity-core#2214]
Hello everyone

I want to do some changes in Serenity framework to take screenshots using Winnium (desktop automation) and not Selenium. I want to know if is possible to do some changes on framework and if the answer is Yes
What is the method or function to change that? because I am reading and in serenity book it talks about the properties capabilities. this link ---> https://serenity-bdd.github.io/theserenitybook/latest/screenshot.html
but it does not specified what method is the properties calling to take the screenshots and build the living documentation.
I clone the repo but i cant found it. 

It will be helpfull if anyone can tell me what methods use Serenity to take screenshots and create the living documentation to overwrite it and test if its works.

Thanks a lot.

**Comment by wakaleo** [comment]
Have a look at the Photographer class and the PhotoSession class.
