### ISSUE TITLE
Serenity reports not getting generated.

### ISSUE THREAD

**Issue by MJavedAli** [serenity-bdd/serenity-core#2216]
I am using serenity cli-jar v2.1.10- serenity-js v2.2.2 - On failed scenarios I am getting the below errors. 

E/launcher - Error: VError: a BeforeAll hook errored, process exiting: core-libraries\support\cucumber\cucumber.hooks.ts:20: timeout: Timed out receiving message from renderer: -0.002
17:16:21   (Session info: chrome=80.0.3987.132)
17:16:21   (Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Windows NT 10.0.14393 x86_64)
17:16:21     at E:\jenkins\workspace\GD-QA-AUTOMATION\ws\node_modules\cucumber\lib\runtime\index.js:60:15
17:16:21 [11:46:21] E/launcher - Process exited with error code 100
17:16:21 npm ERR! code ELIFECYCLE
17:16:21 npm ERR! errno 100

-------------------------------------------------------------------------------------------
17:16:26 > GD-QA-Automation@2.0.0 report E:\jenkins\workspace\GD-QA-AUTOMATION\ws
17:16:26 > serenity-bdd run --cacheDir ./lib/serenity-cli --features target/site/serenity --destination execution-results/serenity
17:16:26 
17:16:27 Spawning: E:/jenkins/workspace/GD-QA-AUTOMATION/tools/win_64/jdk-1.8.0_161-b12/bin/java.exe -DLOG_LEVEL=warn -Dlogback.configurationFile=E:\jenkins\workspace\GD-QA-AUTOMATION\ws\node_modules\@serenity-js\serenity-bdd\resources\logback.config.xml -jar lib/serenity-cli/serenity-cli-2.1.10-all.jar --features target/site/serenity --destination execution-results/serenity --source target/site/serenity --project ws
17:16:28 -------------------------------
17:16:28 SERENITY COMMAND LINE INTERFACE
17:16:28 -------------------------------
17:16:28 Loading test outcomes from target\site\serenity
17:16:28 Writing aggregated report to execution-results\serenity
17:16:28 
17:16:32 11:46:31.841 [main] ERROR n.thucydides.core.reports.CopyFiles - Error during copying files to the target directory
17:16:32 java.nio.file.NoSuchFileException: E:\jenkins\workspace\GD-QA-AUTOMATION\ws\target\site\serenity
17:16:32 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
17:16:32 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
17:16:32 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
17:16:32 	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
17:16:32 	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
17:16:32 	at java.nio.file.Files.newDirectoryStream(Files.java:457)
17:16:32 	at net.thucydides.core.reports.CopyFiles.filesToCopyBetween(CopyFiles.java:69)
17:16:32 	at net.thucydides.core.reports.CopyFiles.to(CopyFiles.java:40)
17:16:32 	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.copyScreenshotsFrom(HtmlAggregateStoryReporter.java:144)
17:16:32 	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:125)
17:16:32 	at net.serenitybdd.cli.reporters.CLIAggregateReportGenerator.generateReportsFrom(CLIAggregateReportGenerator.java:66)
17:16:32 	at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
17:16:32 	at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
17:16:32 	at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
17:16:32 Exception in thread "main" net.thucydides.core.reports.ReportLoadingFailedError: Can not load reports for some reason
17:16:32 	at net.thucydides.core.reports.TestOutcomeLoader.loadFrom(TestOutcomeLoader.java:78)
17:16:32 	at net.thucydides.core.reports.TestOutcomeLoader$TestOutcomeLoaderBuilder.from(TestOutcomeLoader.java:138)
17:16:32 	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.loadTestOutcomesFrom(HtmlAggregateStoryReporter.java:243)
17:16:32 	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:129)
17:16:32 	at net.serenitybdd.cli.reporters.CLIAggregateReportGenerator.generateReportsFrom(CLIAggregateReportGenerator.java:66)
17:16:32 	at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
17:16:32 	at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
17:16:32 	at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
17:16:32 Caused by: java.io.IOException: Could not find directory target\site\serenity
17:16:32 	at net.thucydides.core.reports.TestOutcomeLoader.getAllOutcomeFilesFrom(TestOutcomeLoader.java:119)
17:16:32 	at net.thucydides.core.reports.TestOutcomeLoader.loadFrom(TestOutcomeLoader.java:63)
17:16:32 	... 7 more
17:16:32 I'm terribly sorry, but something didn't go according to plan.
17:16:32 The following process exited with 1: E:/jenkins/workspace/GD-QA-AUTOMATION/tools/win_64/jdk-1.8.0_161-b12/bin/java.exe -DLOG_LEVEL=warn -Dlogback.configurationFile=E:\jenkins\workspace\GD-QA-AUTOMATION\ws\node_modules\@serenity-js\serenity-bdd\resources\logback.config.xml -jar lib/serenity-cli/serenity-cli-2.1.10-all.jar --features target/site/serenity --destination execution-results/serenity --source target/site/serenity --project ws

**Comment by wakaleo** [comment]
Probably more appropriate to post this in the serenity-js issues.

**Comment by MJavedAli** [comment]
> Probably more appropriate to post this in the serenity-js issues.

Raised it here [issue-648]( https://github.com/serenity-js/serenity-js/issues/648)
