### ISSUE TITLE
Pom.xml build part is not taking consideration while run project

### ISSUE THREAD

**Issue by ebbesandslevin** [serenity-bdd/serenity-core#2219]
hi guys,

I use serenity since 1.5 years and today I had my first issue, which I could't find any answer:

I have a new pom.xml dependency in my project, which points to our local Artifactory for an internal tool. If I run the code from IntelliJ then everything works as expected.
But if I run the project with the 'mvn clean verify' command, then the build doesn't run any tests: it says 0 tests have been found, build success.
I use tags which are added as cucumber options for maven-failsafe-plugin and it runs the Runner.java file.
Here is the code:

```
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <cucumber.options>${cucumber.options}</cucumber.options>
                    </systemPropertyVariables>
                    <includes>
                        <include>testrunners.TestRunner</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
             ...
```

I also use a local settings.xml for the Artifactory authentication and for proxy, also it is available in the pom.xml like this:

```
  <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>artifactory</id>
            <name>artifactory</name>
            <url>URL_OF_ARTIFACTORY/</url>
  </repository>
```

Looks like the command doesn't take into consideration the build part of my pom.xml, but it is just a guess.

Of course if I remove the local code dependency from the pom.xml everything works as expected.

Do you have any guess to help me?

Thank you!

Sandor

**Comment by wakaleo** [comment]
that would be related to your maven-failsafe-configuration - make sure it is set up to run all of your tests.

**Comment by ebbesandslevin** [comment]
Could you please help me with that?

I think the plugin is actually setuped well: the only case if it is not running any test when I put my dependency for the Artifactory code in the dependencies part.
If I remove the dependency everything works as expected.
I am not sure that it is an issue with the plugin :(

Here is my failsafe config again:
`      <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <cucumber.options>${cucumber.options}</cucumber.options>
                    </systemPropertyVariables>
                    <includes>
                        <include>testrunners.TestRunner</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
      `

**Comment by ebbesandslevin** [comment]
hi guys, any news on the topic? :)

**Comment by wakaleo** [comment]
I can't see anything that jumps out - maybe an artifactory or repo issue?

**Comment by ebbesandslevin** [comment]
I do not think if it any of them: if I run the tests from IntelliJ using JUnit command, then the tests ran without any problem
The problem is only in case I try to run them with the 'mvn clean verify' command

**Comment by wakaleo** [comment]
Then the problem is something to do with your Maven configuration. As it's not a Serenity issue, it would be more appropriate to ask the question on https://gitter.im/serenity-bdd/serenity-core

**Comment by ebbesandslevin** [comment]
ok thx write to that forum

**Comment by ebbesandslevin** [comment]
Issue can be close: the problem was that the local dependency included an other version of junit, so I had to exclude it in pom.xml
