### ISSUE TITLE
Screenshots and steps missing from report when extending net.serenitybdd.core.pages.PageObject

### ISSUE THREAD

**Issue by nsraghu** [serenity-bdd/serenity-core#2222]
Using serenity version 2.2.8
I have a test which executes perfectly fine and generates reports with steps and screenshots for every action. I want to use Pageobject capabilities so I extend existing class with "net.serenitybdd.core.pages.PageObject". After this the test executes fine, but report does not have steps information and screenshots captured.
I have tried using, screenshot annotation, "@ Screenshots(forEachAction=true)" and setting "serenity.take.screenshots = FOR_EACH_ACTION" in serenity.properties file. Neither of them work.
At this point if I remove the "extends" keyword, report has all the steps and screenshot info.

What additional step am I missing here?

**Comment by wakaleo** [comment]
Extending the PageObject class is pretty standard behaviour - could you share your code?
