### ISSUE TITLE
How to get the current running browser name from serenity 

### ISSUE THREAD

**Issue by Chankami** [serenity-bdd/serenity-core#2225]
Hi
I need to get the current running browser name. Can you pls explain to me how to get that.
My requirement is to get the current running environment and browser.
I'm using the below code to get the current running environment.
   String environmentUrl = EnvironmentSpecificConfiguration.from(environmentVariables)
                .getProperty("webdriver.base.url");

Thanks

**Comment by globalworming** [comment]
why?

> The nature of WebDriver is that you, the tester, are doing the driving - not the browser. Don't try to detect things.

https://stackoverflow.com/a/35258154/1359903

**Comment by Chankami** [comment]
@globalworming  Let me explain my requirement
We have 3 different test environments and running in different browsers.
For some environments, we have authentication Popup. 
We are handling that pop using the extensions.(chrome, firefox)
In our code, we need to get the currently running environment and browser to handle those extensions.

In order to achieve this, I need to get the current browser name, can you pls help

**Comment by Chankami** [comment]
Also when I'm trying to get browser name from Capabilities getting below error.
 
 Capabilities capabilities= ((RemoteWebDriver) driver).getCapabilities();
  String browser= capabilities.getBrowserName().

 **net.thucydides.core.webdriver.WebDriverFacade cannot be cast to org.openqa.selenium.remote.RemoteWebDriver**

**Comment by globalworming** [comment]
check out net.serenitybdd.core.webdriver.RemoteDriver to get the remote driver

`RemoteDriver.of(BrowseTheWeb.as(actor).getDriver())`

nevertheless.. when necessary, i pass some environment to the actor in `@Before` steps. Like `actor.remember("stage", "uat") .... ("browser", "firefox")`. Later, `if (actor.recall("broswer").equals("firefox) && actor.recall("stage").equals("uat")) { handleAuthPopup() }`

**Comment by globalworming** [comment]
i assume the :+1: means i can close for now :)

**Comment by Chankami** [comment]
Hi @globalworming 
Thanks for your help.
In our project, we are not using the screenplay but was able to get the browser name from RemoteDriver thanks to your suggestion.
`String browser = RemoteDriver.of(getDriver()).getCapabilities().getBrowserName();`
