### ISSUE TITLE
rest assured dynamic payload to request body

### ISSUE THREAD

**Issue by globalworming** [serenity-bdd/serenity-core#2226]
Hi,

I am working on serenity rest assured.

I need to put the dynamic payload to request body. Could you please assist
me on this. Or can you please share repository where I can refer a similar
code.

Thank you

_Originally posted by @Chelinadevi in https://github.com/serenity-bdd/serenity-core/issues/1570#issuecomment-690592842_

**Comment by wakaleo** [comment]
See https://github.com/serenity-bdd/bdd-trader

**Comment by globalworming** [comment]
you could just put a string containing json into the body https://github.com/globalworming/serenity-screenplay-rest-example/blob/bf1b8e768d8d72da6579a662fb995a1bd0664237/src/test/kotlin/com/example/testcases/jsonplaceholder/PostsIT.kt#L77

**Comment by globalworming** [comment]
wow, bdd-trader is an awesome example of bdd

@Chelinadevi see https://github.com/serenity-bdd/bdd-trader/blob/ef389a9798353cac91cf245d8b311d4a6a9f114a/src/test/java/net/bddtrader/acceptancetests/tasks/PlaceOrder.java#L47
