### ISSUE TITLE
Question: Capability Enhancer for a provided driver

### ISSUE THREAD

**Issue by thePantz** [serenity-bdd/serenity-core#2227]
Hello,

I've noticed that Capability Enhancers (extending BeforeAWebDriverScenario) are not called if using a provided driver.
Is this intentional? I have a need to get EnvironmentVariables and TestOutcome to add capabilities to my provided driver.
what is the recommended way to achieve this?

**Comment by wakaleo** [comment]
Capacity Enhancers are designed to enhance normal drivers - if you use a custom driver, you do everything yourself.

**Comment by thePantz** [comment]
I'm was able to get environment variables, but not the TestOutcome this way... I'm guessing this is because the driver is instantiated before it's injected into the test.  is there any other way to achieve this? 

I looked into providing these options after the fact using `ThucydidesWebDriverSupport.getWebdriverManager().withOptions()` but it looks like `ProvidedDriverProvider` doesn't pass these along to `driverSource.newDriver()`

I'm considering just using an unmanaged driver but I will lose much of the driver management configuration that serenity has built in. :(

**Comment by thePantz** [comment]
Found a workaround, I'm setting an environment variable with the test outcome info I need. Before my driver is instantiated, my provided driver reads this as any other property
