### ISSUE TITLE
StackTraceAnalyser class "getMethod" calls "callingClass.getSuperclass"(Line 36), and passes to extractMethod. But its not necessary that there be superclass(Inner nested single interface lambda implementation). Leads to Nullpointer

### ISSUE THREAD

**Issue by naveenchandra91** [serenity-bdd/serenity-core#2229]
StackTraceAnalyser class "getMethod" calls callingClass.getSuperclass, and passes it to extractMethod. But its not necessary that there be superclass. Leads to Nullpointer. Especially when the call is from Junit 5 execution engine I am getting Nullpointer for "ExecutableInvoker" class which has a inner interface single method implementation for "ReflectiveInterceptorCall" which does not have a super class. Leading to Nullpointer exception in "extractMethod" because callingClass is passed as null.

![image](https://user-images.githubusercontent.com/20183760/93184241-a1632200-f759-11ea-80b7-06d8c249039d.png)
![image](https://user-images.githubusercontent.com/20183760/93184301-afb13e00-f759-11ea-90bf-27b889ed779a.png)
![image](https://user-images.githubusercontent.com/20183760/93184335-bc359680-f759-11ea-9406-ccba8100c174.png)
![image](https://user-images.githubusercontent.com/20183760/93184393-d2435700-f759-11ea-8bd1-dbf1f4437e82.png)
![image](https://user-images.githubusercontent.com/20183760/93184466-e7b88100-f759-11ea-8d6a-afaf1ff4f83e.png)
![image](https://user-images.githubusercontent.com/20183760/93184504-f3a44300-f759-11ea-9afe-a7701a2bc246.png)
![image](https://user-images.githubusercontent.com/20183760/93184661-24847800-f75a-11ea-97c2-d5025a1308d0.png)
![image](https://user-images.githubusercontent.com/20183760/93184718-336b2a80-f75a-11ea-98dd-b02361979561.png)
![image](https://user-images.githubusercontent.com/20183760/93184740-3c5bfc00-f75a-11ea-880c-0eb5e12c1485.png)

**Comment by wakaleo** [comment]
Can you propose a PR to fix?

**Comment by naveenchandra91** [comment]
@wakaleo Sure. Should i just handle the "null" returned in "callingClass.getSuperclass" or should i pass the ReflectiveInterceptorCall reference too to the extractMethod? I am not sure whether we need to dig in to these classes as these are core Junit5 classes and no logical need to in this usecase. However if there is some nested single method lambda interface defined in a class where a "screenshot" annotation is applied then we ideally should(I am not sure whether thats a valid use case)

**Comment by wakaleo** [comment]
I would just handle the null by ignoring it, as this code is to detect annotations in the test code itself, not in JUnit code.

**Comment by naveenchandra91** [comment]
Thanks @wakaleo . Will raise PR to handle this

**Comment by fabianlinz** [comment]
Had the same issue: StackTraceAnalyser runs into a `NullPointerException` for stacktrace element `org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)` because `org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall` is a inner interface and does not have a superclass. (`StackTraceAnalyser#36`)

**Comment by fabianlinz** [comment]
#2295 was release with [v2.3.9](https://github.com/serenity-bdd/serenity-core/releases/tag/v2.3.9)

**Comment by naveenchandra91** [comment]
This is working as expected now. Hence closing this issue. Thank you @fabianlinz and @wakaleo
