### ISSUE TITLE
Sometime WhenRunningADataDrivenTestScenario fails without any reason

### ISSUE THREAD

**Issue by YamStranger** [serenity-bdd/serenity-core#223]
Sometime WhenRunningADataDrivenTestScenario fails without any reason: 
Last fail: 
Note: Recompile with -Xlint:deprecation for details.
Note: /var/snap-ci/repo/serenity-junit/src/test/java/net/serenitybdd/junit/runners/integration/WhenRunningADataDrivenTestScenario.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:serenity-junit:compileTestGroovy
:serenity-junit:processTestResources
:serenity-junit:testClasses
:serenity-junit:integrationTests

net.serenitybdd.junit.runners.integration.WhenRunningADataDrivenTestScenario > a_separate_html_report_should_be_generated_from_each_scenario FAILED
    java.lang.AssertionError: 
    Expected: is <2>
         but: was <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.junit.runners.integration.WhenRunningADataDrivenTestScenario.a_separate_html_report_should_be_generated_from_each_scenario(WhenRunningADataDrivenTestScenario.java:760)

94 tests completed, 1 failed, 1 skipped
:serenity-junit:integrationTests FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':serenity-junit:integrationTests'.
> There were failing tests. See the report at: file:///var/snap-ci/repo/serenity-junit/build/reports/integration-tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9 mins 53.624 secs
Command ./gradlew integrationTests failed with status 1. Took 9 minutes 54 seconds.

**Comment by wakaleo** [comment]
Possibly a concurrency issue related to running the tests in parallel. Would be good to get to the bottom of it.

**Comment by YamStranger** [comment]
It should be fixed, please revert this fix, if something gone wrong in future. Thanks
