### ISSUE TITLE
[Question] How to get Test outcome of current scenario?

### ISSUE THREAD

**Issue by Jacobvu84** [serenity-bdd/serenity-core#2237]
Hi
I am using screenplay with Junit.

I want to get test outcome of current scenario (outCome by thread) such as test name, steps, test result...
so that I can provide the test outcome information to some rest api.

Example

```
public class SearchByKeywordStory {
   .....
    @Test
    public void search_results_should_show_the_search_term_in_the_title() {

        givenThat(anna).wasAbleTo(openTheApplication);

        when(anna).attemptsTo(Search.forTheTerm("BDD In Action"));

        then(anna).should(eventually(seeThat(TheWebPage.title(), containsString("BDD In Action"))));

    }
```

I expect get test outcome are:

currentTestOutcome.getStoryName(); // return Search By Keyword Story
currentTestOutcome.getSceanrioNames(); // [0] search results should show the search term in the title
currentTestOutcome.getTestSteps(); // [0] open The Application, [1] Search for The Term "BDD In Action"....
currentTestOutcome.getStates();// Pass, fail....

Which class in the core, I should learn ?

Thanks in advance,

**Comment by ricardorlg-aval** [comment]
take a look to https://serenity-bdd.github.io/theserenitybook/latest/extending-webdriver.html#_the_afterawebdriverscenario_interface

**Comment by Jacobvu84** [comment]
@ricardorlg-aval Thanks. I forget it.
