### ISSUE TITLE
Extend Search Filter to all sections of the Serenity report 

### ISSUE THREAD

**Issue by yotageo** [serenity-bdd/serenity-core#2240]
Hello, 

**Current Behaviour**:  The Search Filter is only available in the "Tests" and "Features" Section of the Serenity report. 

**Problem**: User cannot use search filter in other Sections of the Serenity report - for example Requirements, Themes, Capabilities, etc. 

**Suggested Behaviour**: Extend search filter to all sections of the Serenity report.  This enhancement would improve a lot the usability of the report. 

**Examples**: Screenshots attached below. 

Search Filter in "Tests" and associated Data properties in Serenity source
![SearchFilter_TestSection](https://user-images.githubusercontent.com/71768614/94016962-19ab9200-fdaf-11ea-95b8-9c18e245cbf3.jpg)
![SearchFilter_TestSection_SerenitySource](https://user-images.githubusercontent.com/71768614/94016971-1dd7af80-fdaf-11ea-9ca7-d9e6816a6b28.jpg)

Data properties of other sections (eg. Capabilities, Themes etc.( in Serenity source
![DataProperties_OtherSections_SerenitySource](https://user-images.githubusercontent.com/71768614/94016990-2334fa00-fdaf-11ea-8d7c-189849a97929.jpg)

**Comment by wakaleo** [comment]
Do you have an idea of how to implement this capability?
