### ISSUE TITLE
New Click Interaction doesn't report the target name

### ISSUE THREAD

**Issue by ricardorlg-aval** [serenity-bdd/serenity-core#2243]
The new Click interaction appears in the reports like, **actor clicks on #target**, this happens because the name field is not found in AnnotatedStepDescription process to get the step name, I was looking into the problem and found that due to Bytebuddy the getName method, has an unknown name.

This problem, opens the discussion to see if is possible to provide to the Performables a way to setUp the task name, like the getSubject in Question, some folks use serenity in other languages different than English and it will be nice if is possible to override the step names for the built-in Interactions.

One idea would be to add a default getDescriptionName to the Performable interface and then by reflection get the result of the method, the problem with this is that ExecutedStepDescription doesn't know the current instance of the test.

@wakaleo any ideas, in order to achieve this.

**Comment by wakaleo** [comment]
I presume this happens when you click on anything other than a target?

**Comment by ricardorlg-aval** [comment]
this happens on ClickOnTarget because is the only one that uses the ClickOnClickable performAs implementation.

**Comment by ricardorlg-aval** [comment]
I can make the fix for this concrete case, but the idea behind this issue is to discuss if is possible to add the option to change Interactions names.

**Comment by ricardorlg-aval** [comment]
@wakaleo I was thinking about this, and after checking the code I assume is a big change to allow override task names, so for the moment, I will focus this issue in just fixing the ClickOnTarget.
