### ISSUE TITLE
German cucumber annotations have not been reported

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2248]
Hi there,
I was trying to use the german cucumber annotations "@Gegenbensei", "@Wenn" und "@Dann" but the steps annotated this way have neither been logged nor reported. I have set "feature.file.language = de" in serenity configuration. Is there anything I missed to configure?
Regards, André

PS: There is a small typo in serenity documentation: "feature.file,language = en" Guess the comma should be a point instead.

**Comment by ricardorlg-aval** [comment]
Do u have a sample, to try to reproduce this, also, which Serenity version are u using.

**Comment by cliviu** [comment]
do you have `# language: de` as the first line of the feature file  ?

**Comment by aybartsch** [comment]
I'm not sure what a feature file is but I'm using the cucumber annotation in my step files which are extending ScenarioSteps class. For example:
- @When("the user is doing something") --> logged and reported
- @Wenn("the user is doing something") --> neither logged nor reported
At present I have just set the value "feature.file.language = de" in the "serenity.conf" file. Nothing more. To be complete: I'm using serenity version 2.2.12.

**Comment by aybartsch** [comment]
@cliviu I had a closer look to the reference manual and now I'm knowing what a feature file is. But I'm not using such kind of feature files. Instead I'm using old-school java classes with jUnit test methods in there. These test methods are calling steps defined in separate step classes which are annotated with @When and @Then. Everything is working well as long as I'm using the english cucumber annotations.

**Comment by wakaleo** [comment]
Using the Cucumber annotations in that way is not supported.

**Comment by aybartsch** [comment]
@wakaleo Thanks for your answer. In your reference manual [http://thucydides.info/docs/serenity-staging/#_step_definitions](url) you are proposing such kind of an implementation.

**Comment by wakaleo** [comment]
That's not how Cucumber works. @Given, @When and @Then is only designed to work in conjunction with a feature file.

**Comment by aybartsch** [comment]
Now, I'm having your point. Thanks again, @wakaleo.
