### ISSUE TITLE
HTML Report - User Click action step incorrect in 2.3.4 . Works fine in 2.3.2

### ISSUE THREAD

**Issue by anoopk1981** [serenity-bdd/serenity-core#2249]
There is a problem with a step in report for the User click event for version 2.3.4. Here are the details

For the step

``
     user.attemptsTo(
                Click.on(LoginPage.SIGNIN_BUTTON)
        );
``

   in which SIGNIN_BUTTON is defined as 

``
       public static Target SIGNIN_BUTTON = Target.the("Signin").located(By.xpath("//button[text()='Sign In']"));
``

 The HTML report step is shown as 

``
      User clicks on #name 
``

   which is incorrect. 

This is working fine in version 2.3.2 . It seems that some one have hard coded the word "#name" and forgot to remove it.

**Comment by ricardorlg-aval** [comment]
this is fixed in the next version
