### ISSUE TITLE
Full page screenshots in serenity report

### ISSUE THREAD

**Issue by moolisrujana** [serenity-bdd/serenity-core#2252]
Hello Everyone

I want to know if it is possible to take full-page screenshots in the serenity report as current functionality can only take screenshots in the viewport.
And if the answer is yes, what are the changes that I must do at the framework level.
if the answer is no, is there any alternate way that I can take a screenshot for full-page and can attach in the serenity report?

it will be helpful if anyone can tell me what methods use Serenity to take screenshots and create the living documentation to overwrite it and test if it works.

Note: The browsers in which I want full screenshot is chrome, safari, and firefox
Thanks a lot.

**Comment by globalworming** [comment]
i usually did recommend the AShot library, but checking #1934 again...
there was a PR #1975 , check it out. and if you get it to work, please notify me how you did it :) I can then add a paragraph in the documentation https://serenity-bdd.github.io/theserenitybook/latest/screenshot.html

Or - @daniilmatafonov - can you describe how it's supposed to work?

**Comment by globalworming** [comment]
as far as i can see you have to set ThucydidesSystemProperty.SERENITY_FULL_PAGE_SCREENSHOT_STRATEGY to true?
you could maybe do that by adding `serenity.full.page.screenshot.strategy=true` to your `serenity.properties?`

**Comment by moolisrujana** [comment]
@globalworming Thank you for the quick response. I really appreciate it.
I will check by adding serenity.full.page.screenshot.strategy=true to my serenity.properties and will let you know if it works in my case.

**Comment by daniilmatafonov** [comment]
@globalworming , thank you for your answer!
Full page screenshot support is enabled by adding a property **serenity.full.page.screenshot.strategy=true**.
I'll create a separate pull request to change the documentation for this functionality in the near future. Unfortunately, I wasn't able to respond quickly.

**Comment by daniilmatafonov** [comment]
[PR](https://github.com/serenity-bdd/the-serenity-book/pull/47) for Serenity Book.

**Comment by globalworming** [comment]
nice

**Comment by preetimohan** [comment]
Is it possible to set the screenshot property at a specific serenity step rather than as a global parameter?

**Comment by globalworming** [comment]
currently not

**Comment by prat23k** [comment]
When I provide following property its not including the browser url

serenity.full.page.screenshot.strategy=true
