### ISSUE TITLE
HTML Report are not aligned (right and left margins) in 2.3.2 version

### ISSUE THREAD

**Issue by brianle19** [serenity-bdd/serenity-core#2257]
I'm using serenity version 2.3.2 and see that HTML report in /target/site/serenity/index.html are not aligned compared to lower version. Is this a new feature or a bug?

![1](https://user-images.githubusercontent.com/21083736/95288905-b2540e80-0893-11eb-9281-626089a0ecd8.png)

*****Lower version
![2](https://user-images.githubusercontent.com/21083736/95288918-bd0ea380-0893-11eb-931d-066ec538c899.png)

**Comment by wakaleo** [comment]
This is intentional.
