### ISSUE TITLE
How to make serenity parallel with fork works when running test that have scenario outline with parameter on the title?

### ISSUE THREAD

**Issue by shirokuma-ds** [serenity-bdd/serenity-core#2261]
Hi, so I follow the documentation on [Serenity Parallel Batches](https://serenity-bdd.github.io/theserenitybook/latest/serenity-parallel-batches.html) and testing it out on [Serenity Cucumber 5 Starter](https://github.com/serenity-bdd/serenity-cucumber5-starter) project. Trying it out, I am able to make it run parallelly when I have 2 features, one with 2 Scenario and the other feature have Scenario Outline with 2 examples.

But when I add a parameter on the Scenario Outline title, then It's unable to run the feature with the scenario outline and only running the other feature with 2 scenario. I check the log and it seems there is a mismatch when counting the scenarios that will be run
`21:28:25.522 [main] INFO  i.c.junit.CucumberSerenityRunner - Running slice 1 of 1 using fork 2 of 2 from feature paths [file:/D:/Automation%20Projects/Experiments/serenity-cucumber5-starter/src/test/res
ources/features/]
21:28:25.566 [main] INFO  i.c.junit.CucumberSerenityRunner - Running slice 1 of 1 using fork 1 of 2 from feature paths [file:/D:/Automation%20Projects/Experiments/serenity-cucumber5-starter/src/test/res
ources/features/]
21:28:25.788 [main] INFO  i.c.junit.CucumberSerenityRunner - 2 scenario(s) included for 'Search by keyword' in file:///D:/Automation%20Projects/Experiments/serenity-cucumber5-starter/src/test/resources/
features/search_by_keyword.feature
21:28:25.814 [main] INFO  i.c.junit.CucumberSerenityRunner - Filtered out all 2 scenarios for feature 'Defining Meaning'
21:28:25.816 [main] WARN  i.c.junit.CucumberSerenityRunner - There is a mismatch between the number of scenarios included in this test run (0) and the expected number of scenarios loaded (1). This sugge
sts that the scenario filtering is not working correctly or feature file(s) of an unexpected structure are being run
21:28:25.789 [main] INFO  i.c.junit.CucumberSerenityRunner - Included scenario 'Searching for a term(Search by keyword)'
21:28:25.816 [main] INFO  i.c.junit.CucumberSerenityRunner - Running 0 of 2 features`

Here is the 2 features
Feature 1 (this one run)
![image](https://user-images.githubusercontent.com/59801616/95474651-8fb71800-09af-11eb-9eda-af28d716fdd4.png)
Feature 2 (this one not able to run when I add \<term\> parameter on the title)
![image](https://user-images.githubusercontent.com/59801616/95474730-ad847d00-09af-11eb-9ed8-4976bb7687da.png)

I am running it using this command:
`mvn clean verify -Dcucumber.options="--tags @Sanity" -Dserenity.batch.count=1 -Dserenity.batch.number=1 -P useTheForks` 

Why there is a mismatch? Is it because when I add the \<term\> parameter it count this as 2 different scenario, thus unable to divide this correctly? 
And how do I solve this?
Thanks.

**Comment by wakaleo** [comment]
@nbarrett will this work with Cucumber 6?

**Comment by nbarrett** [comment]
Hi @wakaleo - I haven't personally used this version of Cucumber or a version of Serenity that supports that version yet so can't really advise. I'd probably start diagnosing the [unit tests in the latest version of the product](https://github.com/serenity-bdd/serenity-cucumber6/blob/master/src/test/java/net/serenitybdd/cucumber/suiteslicing/CucumberScenarioLoaderTest.java) which all seem to still be there from the 2.x version of serenity so that looks promising.

**Comment by shirokuma-ds** [comment]
hi @wakaleo, I updated the serenity version to the following
```
<serenity.version>2.3.5</serenity.version>
<serenity.maven.version>2.3.4</serenity.maven.version>
<serenity.cucumber.version>2.3.4</serenity.cucumber.version>
```
and also change serenity-cucumber5 to serenity-cucumber6
```
<dependency>
         <groupId>net.serenity-bdd</groupId>
         <artifactId>serenity-cucumber6</artifactId>
         <version>${serenity.cucumber.version}</version>
         <scope>test</scope>
</dependency>
```
but unfortunately it's still producing the same log:
```
12:22:18.043 [pool-1-thread-1] INFO  i.c.core.plugin.SerenityReporter - Running feature from file:///D:/Automation%20Projects/Experiments/serenity-cucumber5-starter/src/test/resources/features/defining_
meaning.feature
12:22:17.986 [main] INFO  i.c.junit.CucumberSerenityRunner - Filtered out all 2 scenarios for feature 'Defining Meaning'
12:22:17.989 [main] WARN  i.c.junit.CucumberSerenityRunner - There is a mismatch between the number of scenarios included in this test run (0) and the expected number of scenarios loaded (1). This sugge
sts that the scenario filtering is not working correctly or feature file(s) of an unexpected structure are being run
12:22:18.043 [pool-1-thread-1] WARN  i.c.core.plugin.SerenityReporter - Feature from file:///D:/Automation%20Projects/Experiments/serenity-cucumber5-starter/src/test/resources/features/defining_meaning.
feature is not under the 'features' directory. Requirements report will not be correctly generated!
12:22:17.989 [main] INFO  i.c.junit.CucumberSerenityRunner - Running 0 of 2 features
```

**Comment by keshrey** [comment]
Hi @shirokuma-ds , Did you find any solution for this problem ?

**Comment by shirokuma-ds** [comment]
Hi @keshrey, unfortunately no, and I haven't tried this again on Serenity 3. Currently, I handle my parallel using Jenkinsfile script instead.
