### ISSUE TITLE
Running feature file directly from IntelliJ then NoStageException happens in @After with serenity core 2.3.4

### ISSUE THREAD

**Issue by brianle19** [serenity-bdd/serenity-core#2262]
I'm running .feature file from IntelliJ and got the error as below. Furthermore, I'm NOT using SerenityScreenPlay pattern in my project and it doesn't happen when running test in command line. Please guide me how to fix it.

![1](https://user-images.githubusercontent.com/21083736/95535509-d38f3900-0a12-11eb-89c9-383547196d12.png)

```
Step failed
net.serenitybdd.screenplay.actors.NoStageException: No stage available - it looks like you haven't called the setTheStage() method before calling this one.
	at net.serenitybdd.screenplay.actors.OnStage.lambda$stage$0(OnStage.java:70)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at net.serenitybdd.screenplay.actors.OnStage.stage(OnStage.java:70)
	at net.serenitybdd.screenplay.actors.OnStage.drawTheCurtain(OnStage.java:74)
	at net.serenitybdd.cucumber.actors.StageDirector.endTheAct(StageDirector.java:9)
```

![1](https://user-images.githubusercontent.com/21083736/95535590-1224f380-0a13-11eb-9318-80c62ae8aae1.png)

**Comment by ricardorlg-aval** [comment]
Just remove net.serenitybdd.cucumber.actors from. The glue part in the run configuration.

**Comment by brianle19** [comment]
> Just remove net.serenitybdd.cucumber.actors from the glue part in the run configuration.

Thanks a lot
