### ISSUE TITLE
can the test framwork support browsermob proxy ?

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#2270]
HI

  Now i have a question, we need record all api and export all api response log when click button on ui page, i found the browsermob-proxy, so i want to know , we support the proxy? and i test with my test code, it always prompt me  **org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'CNDONGCH04', ip: '10.5.41.118', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at com.microfocus.cdf.common.TestPageBase.startproxy(TestPageBase.java:102) seeion**

Below is my code:

	public void startproxy(String url) {
		BrowserMobProxy proxy = new BrowserMobProxyServer();
		int port = 8750;
		proxy.start(port);
		// get the Selenium proxy object
//		RemoteWebDriver rDriver = (RemoteWebDriver) ((WebDriverFacade) getDriver()).getProxiedDriver();
//		String browser = rDriver.getCapabilities().getBrowserName().toLowerCase();
		 String browser = "chrome";
		// Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
		Proxy seleniumProxy = ClientUtil.createSeleniumProxy(new InetSocketAddress("******", port));
		// String ipAddress = new
		// NetworkUtils().getIp4NonLoopbackAddressOfThisMachine().getHostAddress();
		// port = proxy.getPort();
		// seleniumProxy.setHttpProxy(ipAddress + ":" + port);

		if (browser.equalsIgnoreCase("chrome")) {
			DesiredCapabilities chromeCapabilities = DesiredCapabilities.chrome();
			chromeCapabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
			String chromeBinary = System.getProperty(" ");
			if (chromeBinary == null || chromeBinary.equals("")) {
				String os = System.getProperty("os.name").toLowerCase().substring(0, 3);
				chromeBinary = "C:\\Automation\\SeleniumGrid\\chromedriver" + ".exe";
				System.setProperty("webdriver.chrome.driver", chromeBinary);
				ChromeOptions options = new ChromeOptions();
				options.addArguments("--start-maximized");
			}
			proxy.enableHarCaptureTypes(CaptureType.getAllContentCaptureTypes());
			//driver = new RemoteWebDriver(chromeCapabilities);
			try {
				driver = new RemoteWebDriver(new URL("http://******:4444/wd/hub"), chromeCapabilities);
			} catch (MalformedURLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			System.out.println("Using default browser as firefox");
			DesiredCapabilities capabilities = DesiredCapabilities.firefox();
			capabilities.setCapability("marionette", true);
			driver = new FirefoxDriver(capabilities);
		}
		try {
//			String getSession = driver.toString().substring(driver.toString().indexOf("(") + 1,
//					driver.toString().indexOf(")"));
//			Map<String, String> getIP = Pub
//					.get("http://******:4444/grid/api/testsession?session=" + getSession);
//			Gson gson = new Gson();
//			Map<String, Object> map = new HashMap<String, Object>();
//			map = gson.fromJson(getIP.get("Response"), map.getClass());
//			String proxyId = (String) map.get("proxyId");
//			System.out.println("the ip of server running on:" + proxyId);
			proxy.newHar("swtestacademy");
			driver.get(url);
			try {
				Thread.sleep(10000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
			Har har = proxy.getHar();
			File harFile = new File("academy.har");
			har.writeTo(harFile);
		} catch (IOException ioe) {
			ioe.printStackTrace();
		}
		// driver.quit();
		// proxy.stop();
	}

>

**Comment by Jacobvu84** [comment]
https://github.com/serenity-bdd/serenity-core/issues/100

**Comment by ChrisD1990** [comment]
Thanks, @Jacobvu84 I will look
