### ISSUE TITLE
containsOnlyText - semantic change and NullPointerException

### ISSUE THREAD

**Issue by martintanler** [serenity-bdd/serenity-core#2275]
` @Override
    public boolean containsOnlyText(final String value) {
        if (driverIsDisabled()) {
            return false;
        }

        WebElement element = getElement();

        if (element == null)
            return false;

        String text = element.getText();
        if (text.isEmpty()) {
            // https://github.com/serenity-bdd/serenity-core/issues/2134
            // maybe it's an input element?
            text = element.getAttribute("value");
        }
        return text.equals(value);
    }`

When text.isEmpty() is true and element.getAttribute("value") is null then text = null. Hence, text.equals(value) throws a NullPointerException.

That issue was encountered using Chrome and serenity version 2.3.6.

Furthermore I wouldn't have excepcted containsOnlyText the check the attribute value. The semantic change implemented in  https://github.com/serenity-bdd/serenity-core/issues/2134 should be reverted in my opinion. There is a method WebElementFacadeImpl.getTextValue(). In my opinion it would be better to add another mehtod containsOnlyTextValue which is implemented as follows:

`public boolean containsOnlyTextValue(String valueOrText) {
		return getTextValue().equals(valueOrText);
	}`

**Comment by globalworming** [comment]
In my opinion the getText returning  textContent or value attribute is totally fine. as a user you just want to get the text you are seeing, you don't really care if the visible text is actually from a value attribute.

You are right with the nullpointerexception though...
