### ISSUE TITLE
How to accumulate properties

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2279]
Hello,

since we are planning to deploy our Serenity tests to customers we have to separate our company properties from the customer properties. Is it possible to apply more than one "serenity.properties" file i.e. to accumulate properties? If so, how we can achieve this? Currently, we have the below project structure which is not working:

/project-root/config/serenity.properties --> Environment properties (visible to company only)
/project-root/e2e/src/test/ressources/serenity.properties --> Base properties (visible to customer)

Thanks and best regards,
André

**Comment by wakaleo** [comment]
This isn't supported at the moment.

**Comment by globalworming** [comment]
What do you mean by "visible"? If the properties are used, they are accessible by the user.

You could set your company properties through your systems environment variables.

**Comment by aybartsch** [comment]
@globalworming Visible means that property files of the root folders won't be shipped to our customers. Regarding your proposal: Actually we are applying the main properties for Serenity via system properties and the environment specific properties via common "serenity.properties". But this solution looks ugly to me and I would prefer a better solution which supports cascading of "serenity.properties" by default.

**Comment by aybartsch** [comment]
Because accumulating of properties is not supported so far I have defined my properties outside of the e2e test package. But when trying to run the tests via gradle build tool Serenity is always telling me that the drivers cannot be found. But the path mentioned in the error message is existing though. Below is our project structure:

(/Users/abartsch/IdeaProjects/)nvz-clean/config/serenity.properties
(/Users/abartsch/IdeaProjects/)nvz-clean/e2e/src/test/java/tests/serenity/common/admin/PasswordTest.java
(/Users/abartsch/IdeaProjects/)nvz-clean/e2e/src/test/resources/drivers/geckodriver_0.27.0_linux64

**Serenity-Config**
```
drivers {
    win {
        webdriver.gecko.driver = "e2e\\src\\test\\resources\\drivers\\geckodriver_0.27.0_win64.exe"
        webdriver.chrome.driver = "e2e\\src\\test\\resources\\drivers\\chromedriver_win32.exe"
    }
    mac {
        webdriver.gecko.driver = "e2e/src/test/resources/drivers/geckodriver_0.27.0_mac64"
        webdriver.chrome.driver = "e2e/src/test/resources/drivers/chromedriver_mac64"
    }
    linux {
        webdriver.gecko.driver = "e2e/src/test/resources/drivers/geckodriver_0.27.0_linux64"
        webdriver.chrome.driver = "e2e/src/test/resources/drivers/chromedriver_linux64"
    }
}
```
**Gradle Command**
```
nvz-clean % ./gradlew e2e:test --tests "tests.serenity.common.admin.PasswordTest" -Dproperties="../config/serenity/serenity.conf" -Denvironment=local-dev -Dcucumber.filter.tags="@Customer"
```
**Error Message**
```
Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (The driver executable does not exist: /Users/abartsch/IdeaProjects/nvz-clean/"e2e/src/test/resources/drivers/geckodriver_0.27.0_linux64").
```
Could you please tell me what is wrong?

**Comment by aybartsch** [comment]
@wakaleo For any reason IntelliJ and Gradle cannot deal with the above serenity config. Thus, I have changed the properties file as below:
```
drivers.win.webdriver.gecko.driver = e2e/src/test/resources/drivers/geckodriver_0.27.0_win64.exe
drivers.win.webdriver.chrome.driver = e2e/src/test/resources/drivers/chromedriver_win32.exe
drivers.mac.webdriver.gecko.driver = e2e/src/test/resources/drivers/geckodriver_0.27.0_mac64
drivers.mac.webdriver.chrome.driver = e2e/src/test/resources/drivers/chromedriver_mac64
drivers.linux.webdriver.gecko.driver = e2e/src/test/resources/drivers/geckodriver_0.27.0_linux64
drivers.linux.webdriver.chrome.driver = e2e/src/test/resources/drivers/chromedriver_linux64
```
The above kind of setting is working but I have no clue why. Going to close this issue.
