### ISSUE TITLE
Transient issue with goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.3.6:aggregate (serenity-reports)

### ISSUE THREAD

**Issue by yavgel** [serenity-bdd/serenity-core#2280]
at GitHub Actions I run my tests with next command:
run: `mvn clean verify -Denvironment=live -Dtags="EMAIL_LIVE" serenity:check`

and 2 builds from ~50 are failing with the next error (although all the tests were PASSED successfully):

![image](https://user-images.githubusercontent.com/8123409/97416576-e6f13e00-1906-11eb-9b90-7be827a7aaa9.png)

```
Error:  Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.3.6:aggregate (serenity-reports) on project automation: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.3.6:aggregate failed: Plugin net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.3.6 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-core:jar:3.5.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/3.5.0/maven-core-3.5.0.jar: Connection timed out (Read failed) -> [Help 1]
```

@wakaleo  - do you have any idea why it's happening? Thank you a lot in advance!

**Comment by globalworming** [comment]
that's seems to be related to github, maven and maybe azure? see https://github.com/actions/virtual-environments/issues/1499

that's nothing we can help with. I'd recommend getting in contact with the github support
