### ISSUE TITLE
ElementLocatorFactorySelector appiumConfig does not use provided EnvironmentVariables

### ISSUE THREAD

**Issue by thePantz** [serenity-bdd/serenity-core#2281]
Hello,

I've noticed that `ElementLocatorFactorySelector` contains an instance of `AppiumConfiguration` that does not use the provided `EnvironmentVariables` instance. Instead it gets them via Injectors.

```
public ElementLocatorFactorySelector(int timeoutInSeconds, EnvironmentVariables environmentVariables) {
    this.timeoutInSeconds = timeoutInSeconds;
    this.environmentVariables = environmentVariables.copy();
    appiumConfiguration = AppiumConfiguration.from(Injectors.getInjector().getProvider(EnvironmentVariables.class).get());
}
```

I propose we change it to:
`appiumConfiguration = AppiumConfiguration.from(environmentVariables);`

This is causing issues in my project where I'm dynamically loading the device configs I need for a particular driver. Essentially it boils down to something like this:

```
WebDriver driver = ThucydidesWebDriverSupport.getWebdriverManager()
                                  .withProperty("appium.platformName", "Android")
                                  .withProperty("appium.browserName", "chrome")
                                  ....
                                 .getDriver("appium");

actor.can(BrowseTheWeb.with(driver));
```
The above code will throw an error because appium.platformName is not present in the EnvironmentVariables before they were dynamically updated.

**Comment by wakaleo** [comment]
Sound's reasonable, can you propose a PR?

**Comment by thePantz** [comment]
Will do!
