### ISSUE TITLE
How to add header using proxy

### ISSUE THREAD

**Issue by michal-wasiukiewicz** [serenity-bdd/serenity-core#2284]
How to setup browser proxy that will be adding specified header to http request when running gui tests?
@wakaleo can you help?

**Comment by michal-wasiukiewicz** [comment]
@wakaleo  can you help?

**Comment by wakaleo** [comment]
I think it is browser-dependent - e.g. with chrome options for chrome. I haven't done it myself.

**Comment by michal-wasiukiewicz** [comment]
I've been trying code as below. 
The custom headers are added to proxy objects
`INFO: service headers: {TEST=TEST2}`
However, when the browser starts headers are not added to requests

I've been tying this code
`public class BackgroundSteps {
  private BrowserMobFixtureService service;
  private BrowserMobProxy proxy;

  @Before
  public void setup() {

    service = new BrowserMobFixtureService();
    service.setup();
    service.getProxyServer().addHeader("TEST", "TEST2");
    log.info("service headers: " + service.getProxyServer().getAllHeaders());
    proxy = new BrowserMobProxyServer();
    proxy.setTrustAllServers(true);
    proxy.addHeader("test","new header");
    log.info("headers: " + proxy.getAllHeaders());
    proxy.start();

    Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);

    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
    service.addCapabilitiesTo(DesiredCapabilities.chrome().merge(capabilities));
    service.addCapabilitiesTo(DesiredCapabilities.chrome());
    log.info("============ Scenario begins here ============");
  }`
