### ISSUE TITLE
Use Awaitility in serenity Rest Screenplay Pattern

### ISSUE THREAD

**Issue by s1apped** [serenity-bdd/serenity-core#2286]
Hi,

I'm looking into possibility of using Awaitility  together with Rest Screenplay Pattern. Wondering if it's possible, are there any examples or maybe serenity provides some mechanism to to wait until async action is finished?

Thanks!

**Comment by globalworming** [comment]
You can just wrap your checks with 'eventually' to do the same thing. Or are there functions in Awaitility you are missing in serenity?

**Comment by s1apped** [comment]
I'm wondering how to handle Task and Ensure.  

```
    @Override
    @Step("{0} finds file with name: #name")
    public <T extends Actor> void performAs(T actor) {
        actor.attemptsTo(
                Get.from(format("/someFiles/%s", name))
                        .with(request -> request
                                .headers(Map.of("Authorization", "Bearer " + actor.recall(entryNamed(ACCESS_TOKEN)))
                        .then(Ensure.that("File is returned", response -> response.statusCode(200))));
    }
```

**Comment by wakaleo** [comment]
I use Awaitility with Rest all the time - the trick is to make sure that you run Awaitility in the same thread.

**Comment by s1apped** [comment]
my first idea was to wrap everything with 
`   with().pollInSameThread().await().atMost(2, TimeUnit.MINUTES).untilAsserted(() ->`
but still `STEP FAILURE: java.lang.AssertionError: 1 expectation failed.` so clearly missing something. 
@wakaleo  would you mind sharing some example?

**Comment by wakaleo** [comment]
They are all in client code bases so I would need to check tomorrow, but I also use pollInSameThread() which seems to work fine.

**Comment by s1apped** [comment]
when I replaced Ensure with `assertThat(lastResponse().getStatusCode()).isEqualTo(200);` it seems to be working but then have problem with report because it reports step multiple times
![image](https://user-images.githubusercontent.com/32245059/97847113-5c865100-1cef-11eb-8ee7-66ee57c835f3.png)

**Comment by wakaleo** [comment]
If you don't want it appearing in the report when poling then use plain RestAssured for that step and not SerenityRest.

**Comment by eva-pareja** [comment]
Hello,

I have to test an soap api. It is a callback and I don´t know how to manage the response with  Awaitility together with Rest Screenplay Pattern. @wakaleo  If you can give me some example , i will really appreciate it.
