### ISSUE TITLE
Driver is not closed between tests when using Cast + Junit

### ISSUE THREAD

**Issue by thePantz** [serenity-bdd/serenity-core#2289]
Hello,

I'm trying to use a `Cast` within a JUnit test. But I've noticed that drivers are not being closed between tests. This is not an issue when I use Cucumber... For example:

```
@RunWith(SerenityRunner.class)
public class WhenRunningSomeTests{
    Actor customer;

    @Before
    public void setup() {
        OnStage.setTheStage(new OnlineCast());
        customer = OnStage.theActorCalled("customer");
    }

    @After
    public void teardown() {
        OnStage.drawTheCurtain();
    }

    @Test
    public void test1() {
      //....
    }

    @Test
    public void test2() {
        //....
    }
}
```

if I were to run the above test class. The test1 would run as expected, test2 would start using test1s WebDriver. Is this an issue with how `SerenityRunner` is implemented vs `CucumberSerenityRunner`?

**Comment by thePantz** [comment]
I think this happens because a StepListener is never created when using `OnlineCast`. Therefore the drivers are not closed during the TestFinished event

**Comment by thePantz** [comment]
Upon further investigation I think this is the issue. In Serenity we have this: 
```
private void buildAndConfigureListeners() {
        this.initStepEventBus();
        if (this.webtestsAreSupported()) {
            ThucydidesWebDriverSupport.initialize(this.requestedDriver);
            WebDriver driver = ThucydidesWebDriverSupport.getWebdriverManager().getWebdriver();
            this.initPagesObjectUsing(driver);
            this.setStepListener(this.initListenersUsing(this.getPages()));
            this.initStepFactoryUsing(this.getPages());
        } else {
            this.setStepListener(this.initListeners());
            this.initStepFactory();
        }

    }
```

`webTestSupported` checks for the existence of a `@Managed` tag. Then the StepListener would be added to the driver type specified in the tag.

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by thePantz** [comment]
I will try to take a look this weekend. I'm assuming we would want an approach closer to the Cucumber implementation? At first glance it looks like `io.cucumber.core.plugin.SerenityReporter` is a good place to start looking

**Comment by thePantz** [comment]
@wakaleo I finally had a chance to look into this a little further. I propose we introduce a new annotation to mark the test as a WebTest.
Something like:

```
@WebTest
@RunWith(SerenityRunner.class)
public class WhenRunningSomeTests{
    Actor customer;

    @Before
    public void setup() {
        OnStage.setTheStage(new OnlineCast());
        customer = OnStage.theActorCalled("customer");
    }
```

Then we can modify `webtestsAreSupported` to check if the `@WebTest` annotation exists

**Comment by wakaleo** [comment]
I like the idea, very elegant.

**Comment by thePantz** [comment]
I'll get started on a PR!

**Comment by thePantz** [comment]
With the introduction of the `@CastMember` and the JUnit 5 implementation, this is no longer needed
