### ISSUE TITLE
Issue while using HtmlUnitDriver with latest version of Serenity

### ISSUE THREAD

**Issue by RJ05** [serenity-bdd/serenity-core#229]
I am using following version of Serenity:-
 
serenity.version:1.1.21
serenity.cucumber.version:1.1.2

I am trying use, HtmlUnitDriver, for extracting some information from a URL.

Serenity is throwing following error:-
java.lang.IllegalArgumentException: Cannot locate declared field class org.apache.http.impl.client.HttpClientBuilder.sslContext

It works perfectly fine when we use an older(following) version of Serenity:-
serenity.version:1.1.14
serenity.cucumber.version:1.1.1

**Comment by YamStranger** [comment]
Hello @RJ05, thanks for this issue!!!

It depends on #218

**Comment by RJ05** [comment]
Hello @YamStranger, Thanks for the reply, But I think, #218 is a little different Issue.

I think this issue deals with HttpComponents 4.5 support. Kindly see, if you could find some way out. 

First step my test is doing is accepting an SSL Certificate and I thinks that is where it is throwing the Exception.

**Comment by YamStranger** [comment]
@RJ05, #218 issue about general problem with execution steps with htmlunit, because of default "take screenshots feature". You issue can be different, but it will be hard to close it before #218. 

Please, to speed up closing this issue - provide some example. 

Thanks a lot!!!

**Comment by RJ05** [comment]
@YamStranger 

Example:- I am trying to implement a very fundamental thing.
 
WebDriver driver = new HtmlUnitDriver();
 driver.get(URL);

HtmlUnitDriver by default try to accept the SSL Certificate, and code throws java.lang.IllegalArgumentException: Cannot locate declared field class org.apache.http.impl.client.HttpClientBuilder.sslContext .

This Code works perfectly fine, when I run it with Selenium Standalone latest build.

**Comment by RJ05** [comment]
i.e. Selenium Standalone 2.48.2

**Comment by YamStranger** [comment]
looks like some lib version problems. Please port you build config

**Comment by RJ05** [comment]
PFB my pom.xml

 <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.21</serenity.version> --Serenity Version
        <serenity.cucumber.version>1.1.2</serenity.cucumber.version> --Serenity Cucumber Version
        <webdriver.driver>chrome</webdriver.driver>--driver
    </properties>



    <reporting>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>3.0.2</version>
                <configuration>
                    <xmlOutput>true</xmlOutput>
                    <xmlOutputDirectory>target/site</xmlOutputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20151123</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/unittest/*.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/binding/*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by wakaleo** [comment]
This is due to a bug in HTMLUnit - on line 951 or 2.19 (and 944) of version 2.18 of the HttpWebConnection, the name of the "sslContext" field does match the case in the targeted HTTPClientBuilder, where it is "sslcontext":

            final SSLContext sslcontext = (SSLContext) FieldUtils.readDeclaredField(builder, "sslContext", true);
