### ISSUE TITLE
NoSuchElementException when using FindBy

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2290]
Hello, when using FindBy with WebElementFacade I'm not able to click on an element from a list of elements but when using webdriver method directly it's working as expected:
### Not working example
```
    @FindBy(css = "nt-edit-buttons[ng-model='officeIntCtrl.ngModel'] > button[ng-click='btnCtrl.save()']")
    private List<WebElementFacade> buttonsSaveSpecialNotaryData;
    buttonsSaveSpecialNotaryData.get(1).waitUntilClickable.click() // NoSuchElementException thrown
```

### Working example
```
getDriver().findElements(By.cssSelector("nt-edit-buttons[ng-model='officeIntCtrl.ngModel'] > button[ng-click='btnCtrl.save()']")).get(1).click()
```

It seems to me that Serenity cannot click on the second element because the first one is not visible.

**Comment by wakaleo** [comment]
Does it work with a normal @FindBy and list of WebElements?

**Comment by aybartsch** [comment]
Sorry, but what do you mean with "normal @findby"?

**Comment by wakaleo** [comment]
org.openqa.selenium.support.FindBy

**Comment by aybartsch** [comment]
It's not working too:
```
    @org.openqa.selenium.support.FindBy(css = "nt-edit-buttons[ng-model='officeIntCtrl.ngModel'] > button[ng-click='btnCtrl.save()']")
    private List<WebElementFacade> buttonsSaveSpecialNotaryData;
    buttonsSaveSpecialNotaryData.get(1).waitUntilClickable.click() // NoSuchElementException thrown
```

**Comment by wakaleo** [comment]
Why don't you just fetch the list dynamically? @FindBy on collections tends to be unreliable.

**Comment by aybartsch** [comment]
Could you please provide an example how to fetch the list dynamically the Serenity way?

**Comment by wakaleo** [comment]
```
$$("nt-edit-buttons[ng-model='officeIntCtrl.ngModel'] > button[ng-click='btnCtrl.save()']")).get(1).click()
```

**Comment by aybartsch** [comment]
Okay, that's what you have meant. I was already using same syntax with Geb selenium wrapper in the past. Thanks again, John.

**Comment by aybartsch** [comment]
FYI: The dynamic approach is causing an InvalidSelectorException: _Given xpath expression "nt-edit-buttons[ng-model='officeIntCtrl.ngModel'] > button[ng-click='btnCtrl.save()']" is invalid: TypeError: Document.evaluate: Result type mismatch_

**Comment by wakaleo** [comment]
It accepts XPath or CSS, but if it is ambiguous, prefix it with "css:"
