### ISSUE TITLE
When use SpringIntegrationSerenityRunner.class, I didn't get screenshots in my report

### ISSUE THREAD

**Issue by upaul23** [serenity-bdd/serenity-core#2291]
When I use SerenityRunner.class it's all right

In my serenity.properties
serenity.take.screenshots = FOR_FAILURES

In my POM:
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.3.4</serenity.version> 
        <serenity.maven.version>2.3.4</serenity.maven.version>
        <threadCounts>8</threadCounts>
        <tags></tags>
        <retryCount>0</retryCount>
        <maven.failsafe.version>3.0.0-M4</maven.failsafe.version>
    </properties>

<dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>5.0.4.RELEASE</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <version>5.0.4.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>5.0.4.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>5.0.4.RELEASE</version>
        </dependency>

**Comment by upaul23** [comment]
@wakaleo answer me please

**Comment by wakaleo** [comment]
You shouldn't need SpringIntegrationSerenityRunner at all.

**Comment by upaul23** [comment]
> You shouldn't need SpringIntegrationSerenityRunner at all.

Do you mean, that i can initialized spring context without this ruuner?

**Comment by wakaleo** [comment]
Yep.

**Comment by globalworming** [comment]
see also https://serenity-bdd.github.io/theserenitybook/latest/spring.html
