### ISSUE TITLE
Failed to get named parameters value without delimiters Jbehave examples table

### ISSUE THREAD

**Issue by pradeep1429** [serenity-bdd/serenity-core#2292]
We are using Serenity with Jbehave for out automation stories, and we have recently upgraded our version to Serenity(2.2.1) and jbejave(1.46.0). Jbehave-core updated from 4.1.3 to 4.4. After the update i am facing an issue with examples table. it is forcing to use delimiter for the step table provided which is taken from story Examples. This worked previously and got expected values into table

```
Given modal should contains the next content:
{transformer=FROM_LANDSCAPE}
| modalTitle       | expectedTitle1      |
| modalFooterTitle | expectedFooterTitle | 
Examples:
{transformer=FROM_LANDSCAPE}
| expectedTitle1      | this is first expected title |
| expectedFooterTitle | This is expected footer text |
```
Now i have to use delimiter to get my expected content into table as below

```
Given 'Transit product' modal should contains the next content:
{transformer=FROM_LANDSCAPE}
| modalTitle       | <expectedTitle1>      |
| modalFooterTitle | <expectedFooterTitle> |
Examples:
{transformer=FROM_LANDSCAPE}
| expectedTitle1      | this is first expected title |
| expectedFooterTitle | This is expected footer text |
```
Also tried with configuration steps like `ParameterControls().useDelimiterNamedParameters(false)` but didn't worked. We have already implemented thousands of stories and it is hard to replace storied with delimiters. is there any work around to solve my problem?

**Comment by wakaleo** [comment]
JBehave is not actively supported, but feel free to propose a PR

**Comment by wakaleo** [comment]
Please place this issue in https://github.com/serenity-bdd/serenity-jbehave if it is related to the Serenity code base or raise it with the JBehave team.

**Comment by pradeep1429** [comment]
Hi Wakaleo,
Thanks for reply. I too believe its a issue with jbehave. i will create issue in serenity-jabehave.
