### ISSUE TITLE
How to get total steps of silent Task/interaction in TestOutcome ?

### ISSUE THREAD

**Issue by Jacobvu84** [serenity-bdd/serenity-core#2294]
Hi all

I am using serenity screenplay. 

pls help me find solution for this question?

Thanks

**Comment by wakaleo** [comment]
The purpose of a silent task is for it NOT to appear in the test outcomes. The solution is to not use a SilentTask.

What problem are you trying to solve?

**Comment by Jacobvu84** [comment]
Thanks John for reply quickly.

I am trying to update the steps status to testFlo. The testFlo provides an API for this: [change_steps_status](https://deviniti.com/support/server/testflo-79/latest/rest-api/change_steps_status.json)

It requires `"rowIndex"` so I need to get total of steps in TestOutcome.

```
int totalsSteps= testOutcome.getTestSteps().size();
```

but it seems to be is incorrect because I see on the log the error message: 

```
net.rcarz.jiraclient.RestException: 400 : {"error":"Row index '7' does not exists, max index is '5'"}
```

and I think that `totalsSteps` counts silent steps in there.

**Comment by wakaleo** [comment]
Why do you want to update the step status?

**Comment by Jacobvu84** [comment]
This is my code
```
	public static void theStepsStatus(JiraBase jira, Issue issue, TestOutcome testOutcome) {
		
		int totalsSteps= testOutcome.getTestSteps().size();
		
		LOGGER.info("testOutcome.getTestSteps(): "+totalsSteps);
		
		 for(int i = 0; i < totalsSteps; i++) {
			 
				JSONObject stepRow = new JSONObject()
						.element("issueId", issue.getId())
						.element("rowIndex",i)
						.element("status", status(testOutcome.getTestSteps().get(i).getResult().name()));
				
				try {
					
					jira.getJiraClient().getRestClient().put("/rest/tms/latest/steps/status", stepRow);
					
				} catch (RestException | IOException | URISyntaxException e) {
					e.printStackTrace();
				}
		}
	}
	
```

**Comment by Jacobvu84** [comment]
Why do you want to update the step status?

=>> That is different story John. I don't want but team leader want. I have no choice.
