### ISSUE TITLE
How to implement hooks when using CucumberWithSerenity

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2296]
Hi there,

I have transformed my Serenity tests from JUnit to Cucumber. Thus, the test logic has been moved from test to step classes which are linked to feature files accordingly.

My test classes are extending a BaseTest class which is having "Before" and "After" hooks. Unfortunately, the hooks in the BaseTest class are never called. But the hooks in the step classes are called:

**LoginTest.java**
```
@CucumberOptions(
        features = "classpath:/features/common/login/Login.feature",
        glue = {"steps.common.login"})
public class LoginTest extends BaseTest {
}
```

**BaseTest.java**
```
@RunWith(CucumberWithSerenity.class)
public abstract class BaseTest {
    @Before
    public void setup() {
        // Never called...
    }

    @After
    public void cleanup() {
        // Never called...
    }
}
```

**LoginSteps.java**
```
public class LoginSteps extends BaseSteps {
    @Before
    public void setup() {
        // Always called...
    }

    @After
    public void cleanup() {
        // Always called...
    }

}
```

Is there a way to get the hooks in the BaseTest class running? Since, Cucumber is not supporting "BeforeClass" and "AfterClass" hooks it would be nice to get the hooks running, too.

**Comment by globalworming** [comment]
you do need to call `super.setup()` in your LoginSteps.java `@Before`, do you do that?

**Comment by aybartsch** [comment]
I need to call the setup() method of my BaseTest.java which is not linked to LoginSteps.java calls. I think, that super.setup() in my LoginSteps.java would call the method in my BaseSteps.java but not in BaseTest.java.

LoginSteps --> BaseSteps
LoginTest --> BaseTest (Here, I'd like to call the setup() method.)

**Comment by globalworming** [comment]
oh, i misread that xD ignore my unqualified interruption

**Comment by aybartsch** [comment]
@globalworming No problem. But can you confirm that BaseTest is more or less an empty template when running cucumber tests and thus, ignored by test runners?

**Comment by globalworming** [comment]
don't know. documentation seems limited to `@before` in steps classes and i cant seem to find a `@BeforeScenario` or something like that.

Did you defining a `@before` in the `LoginTest`? If your assumption is true, this wouldn't be called either, right?

**Comment by aybartsch** [comment]
Yes, I did but everything I define in LoginTest is ignored. I guess because the CucumberWithSerenity runner is used.

**Comment by globalworming** [comment]
I don't really want to dig into the source code there so let me maybe ask: what does need to be done before a feature runs? maybe you can do it another way?

**Comment by aybartsch** [comment]
In the "Before" hook I'd like to read some serenity properties and log them plus optionally configure the driver. In the "After" hook I'd like to read the browser logs and log them in case of SEVERE errors have been found. Unfortunately, when all steps are passed the driver object is null and cannot be accessed anymore.

**Comment by globalworming** [comment]
that should be fine with what's described in https://serenity-bdd.github.io/theserenitybook/latest/cucumber-before-and-after.html right? setting up a cast is setting up the driver. and after is driver dependent as well

**Comment by aybartsch** [comment]
How to setup a cast?

**Comment by globalworming** [comment]
https://github.com/serenity-bdd/serenity-cucumber-starter/blob/07c4700d44cc58d716e4551010a5edb5b2735861/src/test/java/starter/stepdefinitions/SearchStepDefinitions.java

**Comment by aybartsch** [comment]
@globalworming Okay, I'm new to cast but I will give it a try. Thanks so far!

**Comment by globalworming** [comment]
:+1: 
I'll close for now.
