### ISSUE TITLE
Feature is not under features directory warning

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2297]
Hi there, I'm always getting the below warning:
```
WARN io.cucumber.core.plugin.SerenityReporter - Feature from classpath:features/substitution/edit/SubstitutionEditAndSign.feature is not under the 'features' directory. Requirements report will not be correctly generated!
```
I don't really understand why this warning is displayed since my structure is as below:
```
e2e/src/test/java/steps/substitution/edit/SubstitutionEditAndSignSteps.java
e2e/src/test/java/tests/serenity/substitution/edit/SubstitutionEditAndSignTest.java
e2e/src/test/resources/features/substitution/edit/SubstitutionEditAndSign.feature
```
 Could you please tell me what is wrong in my structure?

**Comment by wakaleo** [comment]
Are the requirements reported correctly?

**Comment by aybartsch** [comment]
Not really i.e. the "Specifications" tab in the "Requirement" section is empty just the "Test Results" tab contains data.

**Comment by wakaleo** [comment]
Are you using Maven or gradle?

**Comment by aybartsch** [comment]
I'm using Gradle.

**Comment by aybartsch** [comment]
Update: Today, I have updated Serenity and Cucumber versions to 2.3.6. In addition, I have applied scenario outlines to my feature files. Because of one or both of these internal changes the requirement tab is now showing the feature tree. Nevertheless, the error is still displayed.

**Comment by wakaleo** [comment]
It’s a warning so it may not be significant if the requirements tree is being generated. It could be because the features are in a module

**Comment by aybartsch** [comment]
Thanks, for the explanation. Going to close this issue.

**Comment by aybartsch** [comment]
The serenity report of our bamboo build is again lacking of the requirements again. Surprisingly, in the bottom line serenity version "Serenity BDD version 2.2.12" is depicted. I don't know why the requirements were available in the report when running in IDE but not when running on Bamboo build agent. Seems that error message cannot be neglected. Do you have further advices?

**Comment by wakaleo** [comment]
I do recall a JVM-related bug in gradle that make it impossible to determine the correct working directory in some environments. Without seeing your project and environment it might be hard to reproduce the issue though

**Comment by aybartsch** [comment]
Okay, I will further try to find the reason for this issue. Thanks for you answer.

**Comment by aybartsch** [comment]
@wakaleo I'm sorry, but I need your help further. You were writing that one possible reason could be that the tests are located in a module. I guess you are referring to the package "e2e". I see that Bamboo is running the tests in the below module folder. At least Bamboo is telling me that the below is the working directory:
```
/opt/bamboo-agent-home/xml-data/build-dir/BM-NEM-ETDS/e2e
```
Our feature files are located in:
```
/opt/bamboo-agent-home/xml-data/build-dir/BM-NEM-ETDS/e2e/src/test/resources/features
```
Our step files are located in:
```
/opt/bamboo-agent-home/xml-data/build-dir/BM-NEM-ETDS/e2e/src/test/java/steps
```
Looks good to me... but in the Bamboo serenity report the "Requirement" tab is empty and furthermore the tabs for "Themes", "Capabilities", and "Features" are missing completely. Do you have further hints for me?

**Comment by wakaleo** [comment]
is `e2e` a project in its own right or a module of a multi-module project?

**Comment by aybartsch** [comment]
e2e is a module inside of a multi-module project.

**Comment by wakaleo** [comment]
I think that can be an issue in some cases.

**Comment by cliviu** [comment]
> The serenity report of our bamboo build is again lacking of the requirements. Surprisingly, in the bottom line serenity version "Serenity BDD version 2.2.12" is depicted. I don't know why the requirements were available in the report when running in IDE but not when running on Bamboo build agent. Seems that error message cannot be neglected. Do you have further advices?

Somehow the version 2.2.12 of Serenity is used.

**Comment by aybartsch** [comment]
@cliviu In the project just the serenity version 2.3.6 can be found in external libraries. I guess that the version depicted in the report is misleading.

**Comment by wakaleo** [comment]
The version on the report reflects the version of Serenity used to generate the report, so it is an indicator that something odd is going on. Maybe check the version of the Serenity gradle plugin.

**Comment by aybartsch** [comment]
@wakaleo Your assumption was right! The old plugin was defined in gradle build file because it was not linked to serenity version variable I used throughout the file. After correcting the same the error has been gone. Thanks and have a nice weekend. :-)
