### ISSUE TITLE
Cannot run JUnit tests using multiple tags

### ISSUE THREAD

**Issue by alexanderkranga** [serenity-bdd/serenity-core#2299]
Hi,

I have two JUnit tests in one class that have multiple tags that specify the platform that I want to use and browser:

```
    @Test
    @WithTagValuesOf({"platform:desktop", "browser:chrome"})
    public void firstTest() {
         // test here
    }

    @Test
    @WithTagValuesOf({"platform:mobile", "browser:chrome"})
    public void secondTest() {
        // test here
    }

```
I need to run test on desktop and in chrome, so according to [documentation](https://serenity-bdd.github.io/theserenitybook/latest/filtering-reports.html#_running_scenarios_by_tags), I run it with this parameter:
`-Dtags=platform:desktop,browser:chrome`. But no tests are executed. It only works when I provide one tag, for example:
`-Dtags=platform:desktop`

Can someone please help me with this?

I am using 2.2.8 version of Serenity

Thank you,
Alex

**Comment by cliviu** [comment]
hi, see this issue https://github.com/serenity-bdd/serenity-core/issues/2273 , you should define the tags like `-Dtags=platform:desktop  or browser:chrome`
