### ISSUE TITLE
Scenario outline variable not resolved in report

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2300]
Hi there, I have applied a scenario outline with examples to my feature files. I've applied a variable to the scenario outline title:
```
Scenario outline: The scenario outline is using a <variable> within the title.
...
Examples:
| variable |
| value    |
```
When I'm running the scenario in IntelliJ Idea the variable is replaced in the runner tab correctly. But in the report the scenario outline is written w/o resolving the variable. Because IntelliJ is replacing the variable I'd think that the report could do the same but maybe this is no error but a feature.

**Comment by wakaleo** [comment]
This isn’t supported at the moment.

**Comment by aybartsch** [comment]
Thanks. Is this feature scheduled already?

**Comment by wakaleo** [comment]
There are no plans for this feature at the moment (it is non-trivial if I recall correctly) - happy to review a PR though.
