### ISSUE TITLE
@AfterScenario is not displaying input tag value

### ISSUE THREAD

**Issue by CrazyMunda** [serenity-bdd/serenity-core#2305]
Hi All,
          I am trying to write some specific step based on given tags for scenario . But my After scenario is not picking the tags and i am not sure what i am missing here. I am using **Serenity and JBehave**

in my story file i am using 
**META:@test**

and in my step definitions i am using
`@AfterScenario
    public void AfterScenario( **@ Named**("test") String Testname) // **but testname is always coming empty**
    {        
        {

        }
    }`

Am i missing anything here. Thanks for the help.

**Comment by wakaleo** [comment]
This looks more like a JBehave question, so probably better to ask the JBehave community. In general Cucumber is the recommended tool for Serenity for new projects.

**Comment by CrazyMunda** [comment]
ok, will add is there . Is there any advantage cucumber over jbehave . Sorry I am new to this automation things.
