### ISSUE TITLE
Unable to run Serenity in Azure Dev Pipeline 

### ISSUE THREAD

**Issue by lgovalles** [serenity-bdd/serenity-core#2308]
Hi community

I try to run Serenity in the pipeline of azure but it gives the error "net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver"

![image](https://user-images.githubusercontent.com/54162651/99923431-bc2ab780-2d03-11eb-84c8-9ad38043e927.png)

This is my serenity.conf file 

![image](https://user-images.githubusercontent.com/54162651/99923474-ebd9bf80-2d03-11eb-8cc5-0087a4ba4634.png)

I run it with Gradle 
![image](https://user-images.githubusercontent.com/54162651/99923527-1c215e00-2d04-11eb-88a2-78d630527704.png)

**Comment by globalworming** [comment]
you have to make sure chrome is installed. only the driver isn't enough

**Comment by lgovalles** [comment]
@globalworming Thank you for reply 

The project working fine on my local machine, but when I try to run it from azure tfs give me that error

**Comment by lgovalles** [comment]
Solved.
I Implemented BrowserStack 
https://www.browserstack.com/docs/automate/selenium/getting-started/java/serenity
