### ISSUE TITLE
Serenity Types the letter 'a' twice when using WebElementFacade::type(String)

### ISSUE THREAD

**Issue by admapere** [serenity-bdd/serenity-core#2311]
EDIT: I found these possibly related issues #2038 and #1788, seems like it was already known. I'll leave to maintainers to decide what to do.

When using the WebElementFacade method, type(String), the letter 'a' is typed twice into the input field. This happens in all browsers, but is most notable in Internet Explorer (probably because of how slow it is).

I looked deeper into this issue, and I believe it has to do with changes made to `net.serenitybdd.core.pages.ClearContents` by commit number `89858954eee6364e1e80e83e865f12ecbba8bf72`. Here is a gif demonstrating what is happening:

![bug_demo](https://user-images.githubusercontent.com/38545169/100028196-6239f880-2dbc-11eb-901d-4907b79bc344.gif)

The demonstration code just does what the ClearContents.ofElement(WebElement elem) method does.

**Comment by wakaleo** [comment]
Looks like there is no general solution for this problem, other than removing the clearing behaviour of the type() method.

**Comment by wakaleo** [comment]
What version are you using?
