### ISSUE TITLE
How log the string messages in serenity reports

### ISSUE THREAD

**Issue by ChakravarthiS** [serenity-bdd/serenity-core#2317]
Hi ,

I have query on serenity reports. Please help me.

I am capturing strings from UI like 
String accountNumber = WebElement.getText();

I want to log this String value in Serenity reports under steps like
"The account number displayed as '1231515215'".

Please help me to log the custom messages in Serenity reports.

**Comment by globalworming** [comment]
You can do this using the Serenity.recordReportData() method
