### ISSUE TITLE
Screenplay interaction for checking/unchecking checkboxes

### ISSUE THREAD

**Issue by thePantz** [serenity-bdd/serenity-core#2319]
Hello,

Is there an interaction that allows the actor to set the state of a checkbox? I've looked around and haven't been able to find it.
Of course I can use `Click`, but I often need to evaluate the current state of the checkbox before clicking to ensure it's in the desired state.

If nothing exist, something like `actor.attemptsTo(CheckCheckbox.of(FORGOT_PASSWORD))` would work. I can submit a PR if you're interested

```
public class CheckCheckbox implements Interaction {

    public final Target target

    public CheckCheckbox(Target target) { this.target = target; }

    @Override
    public <T extends Actor> void performAs(T actor) {
        boolean isSelected = actor.asksFor(SelectedStatus.of(target).asABoolean());
        if(!isSelected) actor.attemptsTo(Click.on(target)) ;
    }

}

```

I would also include the `UncheckCheckbox` counterpart of course

**Comment by thePantz** [comment]
or should I be using [Checkbox](https://github.com/serenity-bdd/serenity-core/blob/f8ef5b90b1c6ef04bd876a6a59fd996bcc2bb228/serenity-core/src/main/java/net/thucydides/core/webelements/Checkbox.java)

**Comment by wakaleo** [comment]
A PR for a Screenplay Action to do this would be most welcome - Checkbox is a convenience class, I think the code you propose is fine as is.
