### ISSUE TITLE
Missing as(Type) and as(TypeRef) in ResponseDecorated

### ISSUE THREAD

**Issue by tlinkowski** [serenity-bdd/serenity-core#2321]
[ResponseDecorated](https://github.com/serenity-bdd/serenity-core/blob/17ccd8713bb322be7f73761b979afcb7152e5e8f/serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/ResponseDecorated.java#L61-L74) misses [as(TypeRef)](https://github.com/rest-assured/rest-assured/blob/947118ba17ecdaca6c76661b76fd65773ba39b30/rest-assured/src/main/java/io/restassured/response/ResponseBodyExtractionOptions.java#L62-L67) and [as(Type)](https://github.com/rest-assured/rest-assured/blob/947118ba17ecdaca6c76661b76fd65773ba39b30/rest-assured/src/main/java/io/restassured/response/ResponseBodyExtractionOptions.java#L69-L98) overloads (these calls are not forwarded to [core](https://github.com/serenity-bdd/serenity-core/blob/17ccd8713bb322be7f73761b979afcb7152e5e8f/serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/ResponseDecorated.java#L30)) which causes an error when these methods are called on an instance of `ResponseDecorated` class.

**Comment by wakaleo** [comment]
Could you raise a PR for this?

**Comment by tlinkowski** [comment]
Sure.
