### ISSUE TITLE
Using header markdown on first line in readme causes breadcrumbs line to display large title

### ISSUE THREAD

**Issue by eitzenbe** [serenity-bdd/serenity-core#2322]
when adding a readme.md with first line being

`#End Points`

the breadcrumb line gets displayed as 

![Screenshot_20201201_092646](https://user-images.githubusercontent.com/5560776/100715463-85b20400-33b7-11eb-9ba8-616829956440.png)

Also in the table on the page the corresponding entry has the "#" shown

![Screenshot_20201201_092957](https://user-images.githubusercontent.com/5560776/100715647-c873dc00-33b7-11eb-978e-e47be8838e4e.png)

OS: Windows 10
Versions:
    <version.serenity.core>2.1.7</version.serenity.core>
    <version.serenity.maven.plugin>2.1.7</version.serenity.maven.plugin>
    <version.serenity.cucumber.4>2.1.2</version.serenity.cucumber.4>
    <version.cucumber>4.8.0</version.cucumber>

Is this a known bug?

**Comment by wakaleo** [comment]
Could you propose a PR to fix this?

**Comment by eitzenbe** [comment]
pfuuh sorry but really really busy currently with the company project and with xmas around the corner  I would think not this year :(

Sorry

**Comment by ricardorlg-aval** [comment]
@wakaleo assign this to me.
