### ISSUE TITLE
Possibility of injecting a custom ConsoleLoggingListener.class

### ISSUE THREAD

**Issue by timothyjmtan** [serenity-bdd/serenity-core#2324]
Hello,

I would like to extend the `ConsoleLoggingListener` class and override it with custom handling for the `logFailureCause` method:

https://github.com/serenity-bdd/serenity-core/blob/master/serenity-model/src/main/java/net/thucydides/core/logging/ConsoleLoggingListener.java#L250

I noticed that even after extending this class, I would have to handle the below where it is being utilised:

**ThucydidesModule.java**
https://github.com/serenity-bdd/serenity-core/blob/602d65a1fc44e35a3a6a2ec422a14dc3eefc2a50/serenity-model/src/main/java/net/thucydides/core/guice/ThucydidesModule.java#L62

Is there an easy way to inject my own custom ConsoleLoggingListener into this class?

**Comment by wakaleo** [comment]
Hmmm. "Easy". I'm not too sure.
