### ISSUE TITLE
Csv file is update during time and used that Csv file for parameterized that for other test method. But updated Csv file value is not taken. It is taking old values

### ISSUE THREAD

**Issue by Umamaheswari1311** [serenity-bdd/serenity-core#2327]
Example:
1. Start execution
2. From application to Hash map (Data stored) 
 3.Hashmap to Csv file
4.use that Csv file for serenity parameterization
5.it won't pick the Run time stored value in Csv file

**Comment by wakaleo** [comment]
You would need to dig into the code but I doubt this is supported - test data is generally considered to be immutable once loaded.

**Comment by Umamaheswari1311** [comment]
Anyway is there to  achieve my scenerios

**Comment by wakaleo** [comment]
Don’t use the same file - create a new one.
