### ISSUE TITLE
Feature Request: Control width of serenity report

### ISSUE THREAD

**Issue by erikgk** [serenity-bdd/serenity-core#233]
The width / max-width of the html report is currently fixed to 1025px. Is it possible to introduce a serenity.properties property to make this a bit higher. We have longer Test and Feature titles which don't fit in the current small 1025px wide report.

**Comment by geertpeeters** [comment]
We have the same issue, especially when adding images that are referenced in overview.md files.

**Comment by wakaleo** [comment]
That would require a major UI redesign which isn't on the horizon at this stage.
