### ISSUE TITLE
[serenity-junit][SerenityRunner] Wrong reference to WebDriver in steps when tests executed in parallel

### ISSUE THREAD

**Issue by a-en** [serenity-bdd/serenity-core#2330]
While running tests in parallel with the help of Surefire plugin, I’ve noticed issue in test scenarios. In case of referring to WebDriver (or WebDriverFacade) from `ScenarioSteps.getDriver()`, it points to **same** object for **all** of the tests, that are executed in parallel. At the same time field, which is annotation with `@Managed` and driver provided to PageObjects contain correct reference – separate for all of the tests. It means that if there is no calls to `getDriver()` method from ScenarioSteps (or any of children), everything works fine. 

After investigation, I came to the conclusion that source of the issues is code in `SerenityRunner`. In the implementation of `methodInvoker` method, objects are initialized for every test. These created objects (PagesObject and StepFactory in particular) are assigned to the fields of `SerenityRunner`. However, this method is not thread-safe. Let’s say we have 2 tests running in parallel – first one creates `PagesObject` and `StepFactory`, puts references to appropriate fields – but second one replaces them immediately.  As result, steps are initialized with the same `StepFactory` object, which contains reference to WebDriver/WebDriverFacade (via Pages). PageObjects are initialized with `PageFactory` and driver for them is provided via request to `Serenity.getWebdriverManager().getWebdriver()`, so they have correct reference.

I see 2 possible solutions to fix this:
-	make `methodInvoker` synchronized, so it becomes thread-safe;
-	make `PagesObject` field thread-local and remove `stepFactory` field at all. References to this field could be replaced with `StepFactory.getFactory()` method, which returns thread-local object.

I have tested 2nd option for some time and it seems to be working fine. @wakaleo,  I’m ready to create PR based on the recommended option.

**Comment by wakaleo** [comment]
Well spotted, a PR would be most welcome.

**Comment by a-en** [comment]
Any prefs in regards of provided options to address this issue?

**Comment by wakaleo** [comment]
I also prefer the second option.

**Comment by berkaykirmizioglu** [comment]
Hi @a-en we are stuck on parallelism problem. Which version should we use to do this ?

Do you have any example repository share with ? 
Thanks

**Comment by wakaleo** [comment]
@berkaykirmizioglu This was merged in December so should be available in version 2.3.11 or 2.3.12

**Comment by emrebaygul** [comment]
When I upgrade the version to 2.3.12, setpdef. The methods in the class are not defined in the feature file. What can I do ? @wakaleo

**Comment by emrebaygul** [comment]
When I upgrade the version to 2.3.12, setpdef. The methods in the class are not defined in the feature file. 
Can you share the version information like in the picture below ? @wakaleo 
<img width="676" alt="Screen Shot 2021-01-12 at 15 09 29" src="https://user-images.githubusercontent.com/47067363/104313003-75c62d80-54e8-11eb-8722-0c3227c3d003.png">
