### ISSUE TITLE
Serenity 2.3.4 - 2.3.9 using older version of hamcrest - 1.3

### ISSUE THREAD

**Issue by mi-akram** [serenity-bdd/serenity-core#2332]
Hi I have just recently upgraded my project dependencies to use Serenity versions 2.3.4 however, my project still seems to be using older versions of hamcrest -  1.3. 

I have built a dependency tree and see that the parents:
net.serenity-bdd:serenity-junit:2.3.4 - is using  org.hamcrest:hamcrest-core:1.3
net.serenity-bdd:serenity-rest-assured:2.3.4 > io.rest-assured:rest-assured:3.3.0 is using org.hamcrest:hamcrest-core:1.3

However
net.serenity-bdd:serenity-cucumber6:2.3.4 - is using io.cucumber:datatable-matchers:3.4.0 > org.hamcrest:hamcrest:2.2

Is there any reason why Serenity versions 2.3.X are using older versions of hamcrest and are they any suggestions on how I can pulling using the latest version 2.2. I suspect there could some conflicts with both of them pulled together with the package names being the same.

As a result when I am trying to use the 'containsStringIgnoringCase' matcher, it is unable to resolve.

Versions of Serenity that I am using:

    testCompile group: 'net.serenity-bdd', name: 'serenity-core', version: '2.3.4'
    testCompile group: 'net.serenity-bdd', name: 'serenity-junit', version: '2.3.4'
    testCompile group: 'net.serenity-bdd', name: 'serenity-rest-assured', version: '2.3.4'
    testCompile group: 'net.serenity-bdd', name: 'serenity-cucumber6', version: '2.3.4'

Any help would be most appreciated.

**Comment by mi-akram** [comment]
[
[projectDependencies.docx](https://github.com/serenity-bdd/serenity-core/files/5652948/projectDependencies.docx)

](url)

**Comment by SiKing** [comment]
Can you just specify in your project (Maven, Gradle, ???) to use org.hamcrest:hamcrest:2.2?
