### ISSUE TITLE
Problems opening Serenity in Eclipse

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#2335]
I am trying to import Serenity into Eclipse. (All the MRs I submitted so far, I created in vi :p )
Here is what I have so far:

1. fresh install of latest Eclipse: 2020-09 "for Java developers"
2. git clone serenity
3. run `./gradlew eclipse`
4. import the entire project into Eclipse as existing project

I end up with 2-dozen errors similar to:
```
One or more cycles were detected in the build path of project 'serenity-screenplay-webdriver'. The paths towards the cycle and cycle are:
serenity-screenplay-webdriver->{serenity-core-serenity-core, serenity-reports, serenity-stats, serenity-model, serenity-test-utils}
```

Any recommendations how to fix this?

**Comment by wakaleo** [comment]
The latest versions use Maven; maybe you will have more luck importing as a maven project?

**Comment by SiKing** [comment]
When I found out about the switch to Maven (here  #2404) that was the first thing I tried: import everything as a Maven project. But that ends with the same problem.

FYI: If I try to build the project from command line `mvn clean install`, it builds fine for me.
