### ISSUE TITLE
stop test on first failure

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#2339]
In Serenity Screenplay, is there a way to stop a test on first failure?

```
@Test
public void should_be_able_to_add_a_todo_item() {

    givenThat(james).wasAbleTo(OpenTheApplication.onTheHomePage());

    when(james).attemptsTo(AddATodoItem.called("Buy some milk"));

    then(james).should(seeThat(theDisplayedItems, hasItem("Get some milk")));

    System.out.println("DO NOT WANT TO SEE THIS!");
}
```

In the above example, if any of the steps fail for whatever reason I do not want that the last line executed. However, I still see it.

**Comment by globalworming** [comment]
Put the last line in a silent performable, then it too will be skipped

**Comment by SiKing** [comment]
My actual use-case is a little more involved. I have one test in a class that is critical - it must pass. If it fails, the rest of the tests in that class do not need to run. Something like this:

```
@RunWith(SerenityRunner.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class CRUDTest {

    private static boolean pass = true;

    @Before
    public void setUp() throws Exception {
	Assume.assumeTrue(pass);
    }

    // this test is critical!
    @Test
    public void test1_create_something() {
	pass = false;

	// Serenity test steps...

	// if anything above fails, this must not get executed
	pass = true;
    }

    @Test
    public void test2_read_something() {
	// Serenity test steps...
    }

    @Test
    public void test3_update_something() {
	// Serenity test steps...
    }

    @Test
    public void test4_delete_something() {
	// Serenity test steps...
    }
}
```

**Comment by globalworming** [comment]
You can do that with junit rules... TestWatcher or something like that. I have an example somewhere, will look for it later

**Comment by globalworming** [comment]
Though the easier option would be to have every test set up their own test data. Why are you doing it in such a way?

**Comment by SiKing** [comment]
> Though the easier option would be to have every test set up their own test data. Why are you doing it in such a way?

Lets say the test is: In the github issue tracker, can you CRUD a new bug?

test1_create_something could be something like:

1. navigate to this project
2. log in as a user
3. click on New Issue
4. .....
5. .....

test2_read_something could be something like:

1. navigate to this project
2. log in as a different user
3. find the issue from previous step
4. ....
5. ....

**Comment by SiKing** [comment]
> You can do that with junit rules... TestWatcher or something like that. I have an example somewhere, will look for it later

There are some ideas in this [SO question](https://stackoverflow.com/q/10036894/3124333). Using an Assume was just the easiest to implement ... if the test stops on first failed step.

**Comment by globalworming** [comment]
found my example... in general, you want your tests to be independent. so i would structure the test like

```
authorized = new Actor("authorized")
anonymous = new Actor("unauthorized")
issue = null

@Before
fun setup() {
  authorized.attemptsTo(CreateIssue())
  issue = authorized.asksFor(LatestIssueCreated())
}

@Test
fun read() {
  anonymous.attemptsTo(EnsureTheyCanReadIssue(issue))
}

@Test
fun update() {
  authorized.attemptsTo(Update(issue))
  anonymous.attemptsTo(EnsureTheyCanSeeUpdate(issue))
}

```
this makes sure, you still get info about "does deletion work" even if "update" might fail. I had a case where there was a hard limit on the "create" part, so I had to do a similar workaround

```
@RunWith(SerenityRunner.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class HealthTest extends TestBase {

    private static List<String> notSuccessful = new ArrayList<>();

    @Rule
    public TestWatcher watchman = new TestWatcher() {
        @Override
        protected void failed(Throwable e, Description description) {
            notSuccessful.add(description.getMethodName());
        }

        @Override
        protected void skipped(AssumptionViolatedException e, Description description) {
            notSuccessful.add(description.getMethodName());
        }
    };

   
    @Test
    public void A_test() {
      }

    @Test
    public void B_test() {
        Assume.assumeThat("dependencies not failing", notSuccessful, not(hasItem("A_test")));
    }

}

```

you can set hard dependencies with method names (i had multiple things in one class) or you could just set a boolean instead of a list

**Comment by globalworming** [comment]
i'll close this. it's not really serenity related and there are things in junit/surefire which can be used. :+1: ?
