### ISSUE TITLE
Image Capture in Serenity Reports. SeeTest, Cucumber JVM and Serenity.

### ISSUE THREAD

**Issue by RJ05** [serenity-bdd/serenity-core#234]
Hi, I am trying to Integrate SeeTest with Cucumber JVM and Serenity with Serenity Reporting for Mobile Browser Automation. But I am not able to capture the Screenshots in Serenity Reports. is there any way out?

**Comment by wakaleo** [comment]
I am not familiar with SeeTest. You might be able to create a provided driver to wrap the SeeTest capabilities.

Closing this as questions are now answered on StackOverflow with the #serenitybdd tag.
