### ISSUE TITLE
How to configure Serenity+Appium+Browserstack

### ISSUE THREAD

**Issue by 10kMonkeys** [serenity-bdd/serenity-core#2340]
Hi there! I need to run my Java+Appium+Serenity tests on Browsestack with AppiumDriver. I found brilliant way for my web automation framework and configured it using RemoteWebDriver(see below, please). But this way doesn't work for my mobile automation framework, because I see exceptions in attempt to cast RemoteWebDriver to AppiumDriver for swiping and other mobile actions.

**pom**
**Using dependency:**
            **groupId:** net.serenity-bdd
            **artifactId:** serenity-browserstack
            **version**: ${serenity.version}

**serenity.properties:**
browserstack.user=username1
browserstack.key=key1
browserstack.server=hub-cloud.browserstack.com
webdriver.driver=remote
webdriver.remote.url=https://username1:key1@hub-cloud.browserstack.com/wd/hub
browserstack.device=iPhone 11
browserstack.realMobile=true
browserstack.video=true

Could you help me to find solution for my mobile automation framework to use serenity+appium+browserstack, please? I tried both way to use webdriver.driver=appium, instead webdriver.driver=remote in serenity.properties or implement my custom driver (see below, please). No one way works for me. I need to use AppiumDriver configured in serenity.properties or in custom driver class. Thank you in advance!

**serenity.properties:**
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.arteza.mobile.driverInstance **<--- WRONG**
webdriver.provided.mydriver = com.arteza.mobile.driverInstance.DriverInstance **<--- CORRECT**
serenity.driver.capabilities = mydriver

**Custom driver**
public class DriverInstance implements DriverSource {

    @Override
    public WebDriver newDriver() {
        DesiredCapabilities caps = new DesiredCapabilities();
        URL url = null;

        caps.setCapability("os_version", "13");
        caps.setCapability("device", "iPhone 11");
        caps.setCapability("realMobile", "false");
        caps.setCapability("browserstack.appium_version", "1.18.0");
        caps.setCapability("browserstack.local", "false");

        try {
            url = new URL("https://username1:key1@hub-cloud.browserstack.com/wd/hub");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        AppiumDriver driver = new AppiumDriver(url, caps);

        return driver;
    }

    @Override
    public boolean takesScreenshots() {
        return false;
    }
}

I have got ignored test with the following exceptions in attempt to use the code above:

[main] WARN net.thucydides.core.pages.Pages - Failed to instantiate page of type class com.arteza.mobile.pages.accountPages.ShippingAddressPage ({})
java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type com.arteza.mobile.driverInstance

net.thucydides.core.pages.WrongPageError: The page object class com.arteza.mobile.pages.accountPages.ShippingAddressPage looks dodgy:
Failed to instantiate page (java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type com.arteza.mobile.driverInstance)

**Comment by 10kMonkeys** [comment]
Sorry, guys. My bad with serenity.properties of Custom Driver. Initial post updated. Hope this topic will help anybody to configure both web and mobile framework for browserstack. Closed.

**Comment by mnajibb-ralali** [comment]
hi @10kMonkeys , can you share the pom on this one? i have issues when combine appium with browserstack on serenity version 2 above. thanks in advance

**Comment by 10kMonkeys** [comment]
Hi @mnajibb-ralali , sure. Couldn't upload xml, see txt in attachments, please.

[pom.txt](https://github.com/serenity-bdd/serenity-core/files/5995741/pom.txt)
