### ISSUE TITLE
can you share how to set up the developer environment? 

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#2342]
hi Developer,
       i want to develop and learn the sernity with Inteliij IDE, can you share how to set up the developer environment? i cannot find any document about setup environment ?

Thanks
Chris

**Comment by globalworming** [comment]
this should be pretty easy. in intelliJ you pick "new project from version control" and then enter the git url. IntelliJ should tell you to either set up a gradle or maven project. 

I usually just import it as a maven project.. there are enough tutorials available online.
https://www.jetbrains.com/help/idea/maven-support.html#maven_import_project_start

If you need further help, send me a DM on https://gitter.im/serenity-bdd/serenity-core or LinkedIn and I'll have a look

**Comment by ChrisD1990** [comment]
thanks @globalworming
