### ISSUE TITLE
 gradle -Denvironment = localhost clean test does not work in gradle - it always takes the default value of the serenity.conf

### ISSUE THREAD

**Issue by santiagogf26** [serenity-bdd/serenity-core#2343]
this is the serenity.conf file

environments {
    default{
        webdriver.base.url = "http://my.super.production.com"
    }
    localhost {
        webdriver.base.url = "http://localhost:8080/"
    }
    staging {
        webdriver.base.url = "http://staging.devatlant.com"
    }
}

**Comment by wakaleo** [comment]
This is a Gradle question - you need to pass your environment variables to the Gradle test task, since it runs in a separate JVM (see for example https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html)
