### ISSUE TITLE
Can't run the test and get report 

### ISSUE THREAD

**Issue by MohamedAliFatnassi** [serenity-bdd/serenity-core#2344]
Hello everyone !
I have this as output after running the test:
Scanning for projects...
[INFO] 
[INFO] --------------< AmazonMavenProjects:AmazonMavenProjects >---------------
[INFO] Building AmazonMavenProjects 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ AmazonMavenProjects ---
[INFO] Deleting /Users/mohamedalifatnassi/eclipse-workspace/AmazonMavenProjects/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ AmazonMavenProjects ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ AmazonMavenProjects ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ AmazonMavenProjects ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ AmazonMavenProjects ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/mohamedalifatnassi/eclipse-workspace/AmazonMavenProjects/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.18:test (default-test) @ AmazonMavenProjects ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ AmazonMavenProjects ---
[INFO] Building jar: /Users/mohamedalifatnassi/eclipse-workspace/AmazonMavenProjects/target/AmazonMavenProjects-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18:integration-test (default) @ AmazonMavenProjects ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- serenity-maven-plugin:2.0.69:aggregate (serenity-reports) @ AmazonMavenProjects ---
[INFO] current_project.base.dir: /Users/mohamedalifatnassi/eclipse-workspace/AmazonMavenProjects
[INFO] Generating test results for 0 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.PackageRequirementsTagProvider@349f3ff7, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@3c9f4376, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@5f3f57ff]
[INFO] Loading requirements from package requirements at: net.serenitybdd.samples.junit.features
[INFO] LOADED REQUIREMENTS:
NO REQUIREMENTS FOUND
[INFO] 0 requirements loaded after 470 ms
[INFO] 0 related requirements found after 471 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 524 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 1.8 secs
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18:verify (default) @ AmazonMavenProjects ---
[INFO] Failsafe report directory: /Users/mohamedalifatnassi/eclipse-workspace/AmazonMavenProjects/target/failsafe-reports
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --------------< AmazonMavenProjects:AmazonMavenProjects >---------------
[INFO] Building AmazonMavenProjects 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- serenity-maven-plugin:2.0.69:aggregate (default-cli) @ AmazonMavenProjects ---
[INFO] current_project.base.dir: /Users/mohamedalifatnassi/eclipse-workspace/AmazonMavenProjects
[INFO] Generating test results for 0 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.PackageRequirementsTagProvider@349f3ff7, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@3c9f4376, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@5f3f57ff]
[INFO] LOADED REQUIREMENTS:
NO REQUIREMENTS FOUND
[INFO] 0 requirements loaded after 3 ms
[INFO] 0 related requirements found after 4 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 5 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 28 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.231 s
[INFO] Finished at: 2020-12-27T18:45:59-05:00
[INFO] ------------------------------------------------------------------------
There is no test run !!

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>AmazonMavenProjects</groupId>
	<artifactId>AmazonMavenProjects</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>2.0.69	</serenity.version> 
		<serenity.maven.version>2.0.69</serenity.maven.version>
		<serenity.cucumber.version>1.9.21</serenity.cucumber.version> 
	</properties>

	
	<repositories>
		<repository>
			<id>serenity</id>
			<name>bintray</name>
			<url>http://dl.bintray.com/serenity/maven</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>serenity</id>
			<name>bintray-plugins</name>
			<url>http://dl.bintray.com/serenity/maven</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>1.8.6</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.5.4</version>
		</dependency>
		

		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>1.7.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jira-plugin</artifactId>
			<version>1.8.0</version>
		</dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.18</version>
				<configuration>
					<includes>
						<include>**/AmazonMavenProjects/**/*.java</include>
						<include>**/AmazonMavenProjects/*.java</include>
					</includes>
					<argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>

Please help !!

**Comment by globalworming** [comment]
```
<artifactId>maven-failsafe-plugin</artifactId>
			<version>2.18</version>
			<configuration>
				<includes>
					<include>**/AmazonMavenProjects/**/*.java</include>
					<include>**/AmazonMavenProjects/*.java</include>
```
i guess your includes are wrong and not picking up the tests
and maybe your `serenity.test.root` in your properties file is wrong?

**Comment by MohamedAliFatnassi** [comment]
Thank you for your help!
Which name should i put (the project name or package name?) Can you provide the syntax of serenity.test.root should i put.
Sorry am new with serenity.
Thank you very much!

**Comment by globalworming** [comment]
I would suggest you try to run https://github.com/serenity-bdd/serenity-cucumber-starter and then change the starter project to fit your needs

**Comment by MohamedAliFatnassi** [comment]
> I would suggest you try to run https://github.com/serenity-bdd/serenity-cucumber-starter and then change the starter project to fit your needs

**Comment by MohamedAliFatnassi** [comment]
> > I would suggest you try to run https://github.com/serenity-bdd/serenity-cucumber-starter and then change the starter project to fit your needs

You mean the pom file?

**Comment by MohamedAliFatnassi** [comment]
> ```
> 
> <artifactId>maven-failsafe-plugin</artifactId>
> 
> 			<version>2.18</version>
> 
> 			<configuration>
> 
> 				<includes>
> 
> 					<include>**/AmazonMavenProjects/**/*.java</include>
> 
> 					<include>**/AmazonMavenProjects/*.java</include>
> 
> ```
> 
> i guess your includes are wrong and not picking up the tests
> 
> and maybe your `serenity.test.root` in your properties file is wrong?

Yes it is !! The mistake is in the includes ! Thank you very much 😊

**Comment by globalworming** [comment]
:+1:
