### ISSUE TITLE
Maven compilation error while running serenity project ( Package doesn't exist error)

### ISSUE THREAD

**Issue by SankarChanna2020** [serenity-bdd/serenity-core#2345]
Hi while running serenity maven project I am getting package not found errors.
I tried all basic maven trouble shooting techniques but still unable to resolve this issue.

console output.

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building CarDekhoFramework 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ CarDekhoFramework ---
[INFO] Deleting C:\Users\91830\Serenity\CarDekhoFramework\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ CarDekhoFramework ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ CarDekhoFramework ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\91830\Serenity\CarDekhoFramework\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[5,27] package org.openqa.selenium does not exist
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[6,27] package org.openqa.selenium does not exist
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[7,27] package org.openqa.selenium does not exist
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[10,34] package net.serenitybdd.core.pages does not exist
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[11,34] package net.serenitybdd.core.pages does not exist
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[13,31] cannot find symbol
  symbol: class PageObject
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[20,16] cannot find symbol
  symbol:   class WebElementFacade
  location: class base.BasePage
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[37,21] cannot find symbol
  symbol:   class WebElementFacade
  location: class base.BasePage
[ERROR] /C:/Users/91830/Serenity/CarDekhoFramework/src/main/java/base/BasePage.java:[55,17] cannot find symbol
  symbol:   class By
  location: class base.BasePage

pom file:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" <xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.cardekho</groupId>
  <artifactId>CarDekhoFramework</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
		<serenity.version>2.0.81</serenity.version>
		<serenity.maven.version>2.0.81</serenity.maven.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<encoding>UTF-8</encoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
		    <groupId>org.apache.poi</groupId>
		    <artifactId>poi</artifactId>
		    <version>3.17</version>
		</dependency>
		
		<dependency>
		    <groupId>org.apache.poi</groupId>
		    <artifactId>poi-ooxml</artifactId>
		    <version>3.17</version>
		</dependency>	
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.1</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.22.1</version>
				<configuration>
					<includes>
						<include>**/testcases/**/*.java</include>
						<include>**/testcases/*.java</include>

					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>	
</project>

**Comment by ricardorlg-aval** [comment]
according to ur pom u have serenity-core with test scope, but u are using related things in `main` package, remove the test scope and try again.

**Comment by SankarChanna2020** [comment]
Yeah Thank you @ricardorlg-aval 

That worked  👍

**Comment by soumyamavens** [comment]
Hi while running Java with Maven Project  in Github using Actions I am getting package not found errors.
please help me if anyone knows this.
Pom file is given below
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>Hello</groupId>
  <artifactId>Helloworld</artifactId>
  <version>0.0.1-SNAPSHOT</version>
 

  <name>Helloworld</name>
  
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
  </properties>

  <dependencies>
   <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi</artifactId>
    <version>5.0.0</version>
   </dependency>

<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>5.0.0</version>
</dependency>

<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.8.0</version>
</dependency>

<dependency>
    <groupId>poi</groupId>
    <artifactId>poi-scratchpad</artifactId>
    <version>3.1-FINAL</version>
</dependency>

<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>openxml4j</artifactId>
    <version>1.0-beta</version>
</dependency>
<dependency>
  <groupId>org.testng</groupId>
  <artifactId>testng</artifactId>
  <version>6.8</version>
  <scope>compile</scope>
</dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.6.0</version>
</dependency>
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.0.0</version>
    
</dependency>



<dependency>
    <groupId>ru.yandex.qatools.ashot</groupId>
    <artifactId>ashot</artifactId>
    <version>1.5.4</version>
</dependency>

 
  </dependencies>
  
  

  <build>
  
    <pluginManagement>
      <plugins>
        
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
      
    </pluginManagement>
  </build>
</project>
