### ISSUE TITLE
Not able to update JIRA comments or status

### ISSUE THREAD

**Issue by rishabh2212** [serenity-bdd/serenity-core#2347]
Here is the POM.xml:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>MyRestFrameWork</groupId>
  <artifactId>MyRestFrameWorkBDDSerenity</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Sample Serenity BDD project using Cucumber</name>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.0.91</serenity.version>
        <serenity.maven.version>2.0.91</serenity.maven.version>
       <serenity.cucumber.version>2.1.2</serenity.cucumber.version> 
        <cucumber.version>4.8.0</cucumber.version>
        <logback.version>1.2.3</logback.version>
        <encoding>UTF-8</encoding>
        <tags></tags>
        <parallel.tests>4</parallel.tests>
    </properties>
    <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
        
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.7</version>
    </dependency>
    <dependency>
        <groupId>org.codehaus.groovy</groupId>
        <artifactId>groovy-all</artifactId>
        <version>1.8.6</version>
    </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay-rest</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber4</artifactId>
            <version>${serenity.cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.6.2</version>
            <scope>test</scope>
        </dependency>
       <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.lalyos</groupId>
            <artifactId>jfiglet</artifactId>
            <version>0.0.3</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
		  <groupId>net.serenity-bdd</groupId>
		  <artifactId>serenity-jira-requirements-provider</artifactId>
		  <version>1.12.0</version>
		</dependency>
 
		<dependency>
		  <groupId>net.serenity-bdd</groupId>
		  <artifactId>serenity-jira-plugin</artifactId>
		  <version>1.12.0</version>
		</dependency>
	
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/Test*.java</include>
                        <include>**/*TestSuite.java</include>
                        <include>**/When*.java</include>
                        <include>**/*Tests.java</include>
                         <include>**/*Tests*.java</include>
                    </includes>
                    <systemPropertyVariables>
                        <webdriver.base.url>${webdriver.base.url}</webdriver.base.url>
                    </systemPropertyVariables>
                    <parallel>classes</parallel>
                    <threadCount>${parallel.tests}</threadCount>
                    <forkCount>${parallel.tests}</forkCount>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <configuration>
                  <tags>${tags}</tags>
                </configuration>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
            <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
            <executions>
                <execution>
                    <id>serenity-reports</id>
                    <phase>post-integration-test</phase>
                    <goals>
                        <goal>aggregate</goal>
                    </goals>
                </execution>
            </executions>
            <dependencies>
              <dependency>
		  <groupId>net.serenity-bdd</groupId>
		  <artifactId>serenity-jira-requirements-provider</artifactId>
		  <version>1.12.0</version>
		</dependency>
 
		<dependency>
		  <groupId>net.serenity-bdd</groupId>
		  <artifactId>serenity-jira-plugin</artifactId>
		  <version>1.12.0</version>
		</dependency>
            </dependencies>
        </plugin>
        </plugins>
    </build>
    
</project>

Below is the Serenity.properties file:

jira.url=https://xxxxx.atlassian.net
jira.project=XXX
jira.username=rishabh.puri@xxxxxx.com
jira.password=APITOKEN
serenity.requirement.types=story,epic
serenity.public.url=file:///C:/Users/rishabh.puri/Downloads/MyRestFrameWorkBDDSerenity/MyRestFrameWorkBDDSerenity/target/site/serenity
serenity.release.types=milestone, release, version
webdriver.timeouts.implicitlywait = 10000
serenity.jira.workflow=my-workflow.groovy
serenity.jira.workflow.active=true

Feature file:
@issue:XXX-5
Feature: To verify API automation with Rest Assured
Scenario: To verify tha membeship API- Get method
Given I want to execute memberships endpoints
When I submit the GET request
Then I should get 200 Success Status Code

  Scenario Outline: Title of your scenario outline
    Given I want to write a step with <key>
    When I check for the <value> in step
    Then I verify the <status> in step

    Examples: 
      | name  | value | status  |
      | name1 |     xxxxxxxx | success |

The results of this test case from Junit are passed still not able to post any thing on JIRA using a 2 way integration. 
Also there are NO traces in logs like "net.serenitybdd.plugins.jira.JiraUpdater - Updating JIRA issue: *****"

I can see logs like  net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider - 5 child requirements loaded but not anything related to updating.

PLEASE HELP!

Please help as this is really frustrating.

**Comment by wakaleo** [comment]
Two-way JIRA integration is currently not supported, as the JIRA APIs have changed.

**Comment by rishabh2212** [comment]
Thanks a lot for your prompt reply :)

Any update if this feature will be available in future or not?

**Comment by wakaleo** [comment]
Probably, but I don't have a timeline just yet.

**Comment by rishabh2212** [comment]
Ok, will wait for further notice.
We can close this ticket till then.

**Comment by rishabh2212** [comment]
@wakaleo Does this also affect the Requirements loader because I cant see the Requirements in the Reports??

**Comment by rishabh2212** [comment]
??

**Comment by wakaleo** [comment]
Yes, this will affect the Requirements section too.

**Comment by rishabh2212** [comment]
Thanks a lot @wakaleo But we definitely look forward for these fixes in upcoming releases :)
