### ISSUE TITLE
can we support selenium-4.0.0-alpha-7?

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#2351]
Hi Developers,

                  can we support selenium-4.0.0-alpha-7 for serenity? 
 I found the selenium-4.0.0-alpha-7 support Chrome DevTools, https://applitools.com/blog/selenium-4-chrome-devtools/ 
So I want to update the selenium from 3.141.59 to 4.0.0.alpha7 version, 
but I cannot sure our serenity framework supports the version, so if you know, can you tell me? thanks.

**Comment by wakaleo** [comment]
Serenity will probably need major changes to support selenium 4.0.0 so probably not.

**Comment by ChrisD1990** [comment]
thanks for your replay
