### ISSUE TITLE
Fail :: TestOutcomes outcomes = TestOutcomeLoader.loadTestOutcomes().inFormat(format)

### ISSUE THREAD

**Issue by viniciusmorais** [serenity-bdd/serenity-core#2354]
This code line doesn't work in Serenity version 2.3.10

TestOutcomes outcomes = TestOutcomeLoader.loadTestOutcomes().inFormat(format)

**Comment by wakaleo** [comment]
Could you be more precise?

**Comment by viniciusmorais** [comment]
I'm trying to do like the documentation : https://serenity-bdd.github.io/theserenitybook/latest/importing-test-outcomes.html

But I have a erro: TestOutcome cannot be resolved to a type.

This comand TestOutcomeLoader.loadTestOutcomes().inFormat(format) return TestOutcomeLoaderBuilder, not a TestOutcomes.

**Comment by wakaleo** [comment]
Use JSON instead of XML - XML output is deprecated.

**Comment by viniciusmorais** [comment]
I'm using JSON...

	@After
	public void testOutcomes() {
		OutcomeFormat format = OutcomeFormat.JSON;
		TestOutcome outcomesBuilder = TestOutcomeLoader.loadTestOutcomes().inFormat(format);	
	}

**Comment by wakaleo** [comment]
You need to say where you are loading the reports from, e.g.
```
TestOutcomes testOutcomes = TestOutcomeLoader.loadTestOutcomes().inFormat(OutcomeFormat.JSON).from(someDirectory));
```
