### ISSUE TITLE
Appium (Safari) - fails to take screenshot when system popup warning is displayed

### ISSUE THREAD

**Issue by thePantz** [serenity-bdd/serenity-core#2355]
There is a quirk in mobile safari when it detects javascript that is trying to open a new page, a warning will be displayed.
![image](https://user-images.githubusercontent.com/5605700/103952741-85b7c900-5106-11eb-9353-d40f2a7b82a4.png)

So say I click on a 'New' button that opens a new tab. Under the hood, the webdriver will call the onClick event on this button via javascript which safari will detect as something potentially dangerous so the warning is displayed. However, after I've clicked on this button Serenity will take a screenshot which throws an error:

> 16:25:22.035 [main] WARN  n.s.core.photography.PhotoSession - Failed to take screenshot
> java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
> 	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:304) ~[selenium-remote-driver-3.141.59.jar:na]
> 	at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshot(Browser.java:88) ~[selenium-shutterbug-0.9.3.jar:na]
> 	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:107) ~[selenium-shutterbug-0.9.3.jar:na]
> 	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:72) ~[selenium-shutterbug-0.9.3.jar:na]
> 	at net.serenitybdd.core.photography.PhotoSession.takeScreenshot(PhotoSession.java:63) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.serenitybdd.core.photography.PhotoSessionBooking.andSaveToDirectory(PhotoSessionBooking.java:40) [serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.BaseStepListener.screenshotFrom(BaseStepListener.java:971) [serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.BaseStepListener.lambda$grabScreenshots$6(BaseStepListener.java:962) [serenity-core-2.3.4.jar:2.3.4]
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_242-release]
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_242-release]
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_242-release]
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_242-release]
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_242-release]
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_242-release]
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_242-release]
> 	at net.thucydides.core.steps.BaseStepListener.grabScreenshots(BaseStepListener.java:964) [serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:862) [serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.BaseStepListener.takeEndOfStepScreenshotFor(BaseStepListener.java:843) [serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.BaseStepListener.stepFinished(BaseStepListener.java:714) [serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.StepEventBus.stepFinished(StepEventBus.java:407) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.StepInterceptor.notifyStepFinishedFor(StepInterceptor.java:503) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:473) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:445) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:201) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:188) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:76) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51) ~[serenity-core-2.3.4.jar:2.3.4]
> 	at net.serenitybdd.screenplay.actions.ClickOnTarget$ByteBuddy$wnEAqDW8.performAs(Unknown Source) ~[na:2.3.4]
> 	at net.serenitybdd.screenplay.Actor.performTask(Actor.java:248) ~[serenity-screenplay-2.3.4.jar:2.3.4]
> 	at net.serenitybdd.screenplay.Actor.perform(Actor.java:229) ~[serenity-screenplay-2.3.4.jar:2.3.4]
> 	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:175) ~[serenity-screenplay-2.3.4.jar:2.3.4]

If I disable all screenshots I'm able to handle this dialog and proceed.
My theory is that because the driver will be in a different [context ](https://appium.io/docs/en/writing-running-appium/web/hybrid/index.html#entering-the-web-view-context)when this popup gets displayed the Screenshot command returns an instance of com.google.common.collect.Maps$TransformedEntriesMap.

I think the simplest way to resolve this would be to disable screenshots for this click. I would prefer not to disable it for all actions though. Is there currently a way to disable screenshots for a click in screenplay?

**Comment by ricardorlg-aval** [comment]
U can make ur own interaction that wraps the Click Interaction, and mark that one with DisableScreenshots (implement the interface)

**Comment by thePantz** [comment]
Thanks @ricardorlg-aval that works for my needs :)
