### ISSUE TITLE
StepListener Method Not Called

### ISSUE THREAD

**Issue by billyjulius** [serenity-bdd/serenity-core#2357]
Hello

I found sometimes method in StepListener is not called, testFinished() specifically. 
I found it only happen when:
- Using Scenario data tables (I'm using Cucumber)
- One or more scenario data result in test failed

For example, I have this data tables:
```
Examples:
      | TagEndpoint       |   TagCondition.        |  TagValidate           |
      | getMerchant       |   withoutParamMid      |   unauthorized         |
      | getMerchant       |   withoutParamMidValue |   unauthorized         |
      | getMerchant       |   invalidTokenValue    |   unauthorized         |
      | getMerchant       |   withoutTokenValue    |   unauthorized         |
```
Lets say, the 2nd data will result in test failed. What will happen is:
- Data 1 finish result in test passed & testFinished() is called
- Data 2 finish result in test failed & testFinished() is called
- Data 3 finish result in test passed/failed & testFinished() is not called
- Data 4 finish result in test passed/failed & testFinished() is not called

As long as data result in test passed, testFinished() will always called every scenario data finished executed.
If scenario data result in failed, all the next scenario data will not called the method after its finished.

What I expect is, as it name implies, testFinished() is called after every scenario finished (either passed or failed).

Version used
```
serenity-core 2.1.4
serenity-cucumber4 2.1.2
cucumber-core 4.8.0
```

**Comment by wakaleo** [comment]
The Cucumber API doesn't invoke all of the events as it should. Have you tried with the latest versions?

**Comment by billyjulius** [comment]
Thank you for the response. After updating to latest version, the issue is solved!
