### ISSUE TITLE
How can I call HtmlAggregateStoryReporter programmatically to get achieve the mvn serenity:aggregrate command

### ISSUE THREAD

**Issue by LayMui** [serenity-bdd/serenity-core#2358]
I am running the serenity using java command (not maven)
however, the artefact has the missing index.html

I create a file with the code snippet
package demo.report;

import net.thucydides.core.Thucydides;
import net.thucydides.core.reports.html.HtmlAggregateStoryReporter;

import java.io.File;
import java.io.IOException;

import io.cucumber.plugin.ConcurrentEventListener;
import io.cucumber.plugin.event.EventHandler;
import io.cucumber.plugin.event.EventPublisher;
import io.cucumber.plugin.event.TestRunFinished;
import io.cucumber.plugin.event.TestRunStarted;

public class Initialization implements ConcurrentEventListener {
        private EventHandler<TestRunStarted> setup = event -> {
           //  System.out.println("setup!!");
        };
        
        private EventHandler<TestRunFinished> teardown = event -> {
            File sourceDirectory = new File("target/site/serenity/");
            HtmlAggregateStoryReporter reporter = new HtmlAggregateStoryReporter(Thucydides.getDefaultProjectKey());
            reporter.setOutputDirectory(sourceDirectory);
            try {
                reporter.generateReportsForTestResultsFrom(sourceDirectory);
            }
            catch (IOException e)
            {
                System.out.println("generateReportsForTestResultsFrom exception ");
                e.printStackTrace();
            }
        };
        
        @Override
        public void setEventPublisher(EventPublisher publisher) {
            publisher.registerHandlerFor(TestRunStarted.class, setup);
            publisher.registerHandlerFor(TestRunFinished.class, teardown);
        }

}

and in my Cucumber test runner:
package demo;

import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        plugin = {"pretty", "demo.report.Initialization"},
        features = "classpath:features",
        strict = true,
        snippets = CucumberOptions.SnippetType.CAMELCASE
)
public class CucumberTestSuite {

}

in the java command
- java -Dcucumber.plugin=classpath:demo.report -Dcucumber.filter.tags=@app -Dcucumber.features=classpath:features -Dcucumber.glue=classpath:demo.stepdefinitions -Dwebdriver.driver=appium -Dappium.screenshots.dir=$DEVICEFARM_SCREENSHOT_PATH -Dappium.autoAcceptAlerts=true -Dappium.platformName=$DEVICEFARM_DEVICE_PLATFORM_NAME -Dappium.app=$DEVICEFARM_APP_PATH org.testng.TestNG -junit -testjar *-tests.jar -d $DEVICEFARM_LOG_DIR/test-output -verbose 10

but artefact didn't generate any serenity report, that is the target/site/serenity is not even generated

is there a system system properties that I can set to achieve mvn serenity:aggregrate?

**Comment by wakaleo** [comment]
It's doable but you would need to look at the internal Serenity APIs to find a way. Why don't you just use maven or gradle?

**Comment by GianniGiglio** [comment]
@LayMui 

Here is what I use:

private static ResultChecker generateHtmlStoryReports() throws IOException {
        HtmlAggregateStoryReporter htmlAggregateStoryReporter = new HtmlAggregateStoryReporter("dgc");
        htmlAggregateStoryReporter.setSourceDirectory(new File("build/site/report"));
        htmlAggregateStoryReporter.setOutputDirectory(new File("build/site/report"));
        htmlAggregateStoryReporter.generateReportsForTestResultsFrom(new File("build/site/report"));
        return new ResultChecker(htmlAggregateStoryReporter.getOutputDirectory());
    }
