### ISSUE TITLE
Browser is not started maximzed in latest version of serenity

### ISSUE THREAD

**Issue by ibrahimkhaleel** [serenity-bdd/serenity-core#2359]
Hi @wakaleo,

I have upgraded my serenity pom to the latest version as shown below and noticed browser maximize is not working during execution. 

![image](https://user-images.githubusercontent.com/25445287/104315837-786a5800-54d3-11eb-963d-d87d6c3c6840.png)

I have also set the serenity.conf as per below:
chrome.switches = """--start-maximized;--test-type;--no-sandbox;--ignore-certificate-errors;
                   --disable-popup-blocking;--disable-default-apps;--disable-extensions-file-access-check;
                   --disable-infobars,--disable-gpu"""

I also notice execution logs as below and notice above switches are added in run:
![image](https://user-images.githubusercontent.com/25445287/104316409-54f3dd00-54d4-11eb-80e9-adbe3707abd0.png)

Please assist me if I am missing anything here.

Addition to the above query, could you also please clarify the if we set webdriver to autodownload = true in serenity.conf will work regular page object model or it is a specific feature for Screenplay 

Thank you so much in advance. 

Best regards, Ibrahim Khaleel S M

**Comment by ibrahimkhaleel** [comment]
I found the solution myself to my second query here related to webdriver autodowload. I can run this option enabled for my existing page object model framework.

**Comment by ibrahimkhaleel** [comment]
To add further for browser maximise issue I am able to maximise the browser only when I set the **serenity.browser.maximized=true** in _**serenity.properties**_ 

I wonder why it is not working from _**serenity.conf**_ file for chrome browser.

**Comment by wakaleo** [comment]
Using chrome.switches is the recommended approach. There is no difference between `serenity.browser.maximized=true` in `serenity.properties` and `serenity.conf`, assuming you have used the correct HOCON format in `serenity.conf`. There is no difference in the code. The feature however uses `driver.manage().window().maximize();`, which may not be supported by Chrome.

**Comment by ibrahimkhaleel** [comment]
Thank you @wakaleo for your time to respond on this. I tried keeping switches in both conf and property files of serenity and still, Chrome browser maximize did not work. But I do have mention serenity.browser.maximized=true in serentiy.properties and it is working with Chrome. I could not have a chance to test this latest serenity version with other browsers yet. Could you please assist me to investigate the issue with **_chrome.switches_** because I do need these options when I run the test from CI/CD in headless mode.

Also, apologise if I am jumping to another question from my issue description regarding **autodownload**, could you please confirm if this feature works with other browsers like Firefox, Safari and Edge?  I am currently successfully using it for chrome but could not find it is working with Firefox. Could you also please confirm this?
