### ISSUE TITLE
Setting serenity.console.headings=normal still showing ascii but in a less arty way

### ISSUE THREAD

**Issue by mcm1988** [serenity-bdd/serenity-core#2360]
Serenity Version 2.3.4

I'm trying to set serenity.console.headings=normal so that it's easy to do a CTRL+F in jenkins console to search for "test failed" etc.
but setting it to normal no longer makes it "normal" like i would expect

it now shows like:

[Screenshot here](https://imgur.com/a/SHp1JUc)

 
 This is not normal, but also not the same as ASCII
 
 How do I get normal back?

**Comment by mcm1988** [comment]
[Screenshot here](https://imgur.com/a/SHp1JUc)

**Comment by wakaleo** [comment]
These are the only options available - there was never a "normal" for the console messages.

**Comment by globalworming** [comment]
there was.. 2.0.7 shows normal as
```
----------------
- TEST STARTED -
----------------
TEST STARTED: whenPosting
```

really would prefer having that again :)

**Comment by wakaleo** [comment]
The class to look at is ConsoleHeading (https://github.com/serenity-bdd/serenity-core/blob/4caee3e9ee15874dd90815dccd14b9c0e5d9198c/serenity-model/src/main/java/net/thucydides/core/logging/ConsoleHeading.java)
