### ISSUE TITLE
Modify displayed html report steps

### ISSUE THREAD

**Issue by susacapuntas** [serenity-bdd/serenity-core#2363]
Hello,

I would like to modify the report steps by masking some of the parameters which contain sensitive data such as passwords etc, but I can't find where the steps written in my code "match" with the html report to change the value before creating it.

Could you shed some light about it?

Thanks

**Comment by globalworming** [comment]
depends on what you use. when doing screenplay, you instrument your class and use the step annotation to display whatever. example: https://github.com/globalworming/serenity-junit-screenplay-starter/blob/0858d36a05c0dc9167cb9da4f4518ed0643dd68d/src/test/java/com/example/screenplay/action/UploadNewPost.java

so you can change the step annotation to show something different, but you need to mark this class as IsSilent or something like that to stop included actions from reporting.

**Comment by susacapuntas** [comment]
sorry I wasn't clear enough. 
i'm not using screenplay, I'm just making API requests so there is no browser interaction

**Comment by globalworming** [comment]
screenplay isn't just for browsers, it's also for API and to be used with cucumber
for cucumber with step libraries it should be pretty similar https://serenity-bdd.github.io/theserenitybook/latest/cucumber.html#_using_serenity_step_libraries_in_cucumber_step_definitions there is a Step annotation that can be used.

**Comment by globalworming** [comment]
If you need more specific help, please create a minimal example project and attach a screenshot of what message you would like to change

**Comment by susacapuntas** [comment]
Hi again!

Thanks for your response. Sorry for not understanding you the first time, I'm a newbie with serenity 😞 
This is a piece from my code. As you can see, I'm already using the Step annotation and I know how to change the "content" of the step, but what I want is to change the Step "title", masking it.

```
public class GenericStepDefinitions {

	@Steps
	APIResource apiResource;

        private void clientLogin(String user, String password, String country, String passKey, String type){
                 //Client login code
        }

	@Given("I log in as the service user {string} with password {string}")
	public void iLogInAsTheServiceUserWithPassword(String user, String password) {
		//Some more code 
	}
}
```

What I want is to mask the parameter "inttest1_ar" with "*********" or some other symbol.

![example](https://user-images.githubusercontent.com/4288261/104609867-c7ef8600-5683-11eb-8646-ec5d651c5c1c.png)


Something like this:

![example](https://user-images.githubusercontent.com/4288261/104611175-1f422600-5685-11eb-949d-2761d53dcd4b.png)


Is it possible?

Thank you so much for your time.

**Comment by globalworming** [comment]
Not sure if that's possible. But also not necessary i think. Just remove the parameters and provide the password in another way, hard coded in the class or from environment variables. It's recommended to not be so specific in your scenarios  https://cucumber.io/docs/bdd/better-gherkin/

**Comment by susacapuntas** [comment]
You are right, it is not a best practice to have users and passwords in the steps but it's something I already inherited and I have to work with it for now (this change is in the project's backlog and environment variables probably will be used).

I was just wondering if what I wanted was possible but guess it is not. I will just change the step content.

Thanks again a lot.
