### ISSUE TITLE
Organise assets (test evidence) in subdirectories

### ISSUE THREAD

**Issue by patrickvkb** [serenity-bdd/serenity-core#2364]
For now only test evidence present in the root of the `resources/images` is copied in to the `target/site/serenity/assets` directory when the aggregated report is created.
Is there a means to have also test evidence that is organised in subdirectories of the `resources/images` recursively copied to the `target/site/serenity/assets` directory during the aggregate report creation.

**Comment by wakaleo** [comment]
Have you tried?

**Comment by patrickvkb** [comment]
Just tried again while adding a new directory with one picture in it.  The new directory as such is created in the`assets`directory but its content is not copied:
![subdirectory-in-images](https://user-images.githubusercontent.com/43884721/104730994-5246f100-573b-11eb-82aa-ab16d0ff9091.png)

**Comment by patrickvkb** [comment]
This may also be important:
```
serenityVersion = "2.0.84"
serenityCucumber4Version = "1.0.21"
cucumberVersion = "4.2.0"
```
