### ISSUE TITLE
WebElementFacadeStub does not automatically fail assertions on "shouldBe..." method family 

### ISSUE THREAD

**Issue by hccummins** [serenity-bdd/serenity-core#2365]
I noticed that `WebElementFacadeStub`'s implementation of the test methods that begin with "should", i.e. `shouldBePresent()`,
`shouldBeVisible()`, `shouldBeCurrentlyVisible()`, etc. are all No-Ops. This has tripped me up some in some instances; as I wrote some wrapper methods to return `WebElementFacadeImpl` if an element is present and stub if not. Here's a simple example  snippet to illustrate:

`WebElementFacade elem = (!getDriver().findElements(<some_locator>).isEmpty())`
         `  ? $(getDriver().findElement(<some_locator>))` 
         `  : new WebElementFacadeStub();`
`elem.shouldBeCurrentlyVisible(); // want polymorphic behavior; pass if the element is visible, fail if not OR if its a stub`

This is based on the assumption that `WebElementFacadeStub` should represent a missing or empty Web Element, which reduces the need to check null references, deal with `NoSuchElementException`'s when we can tolerate missing elements, etc. Therefore it is my suggestion to implement these methods (defined in `net.serenitybdd.core.pages.WebElementState`) in `WebElementFacadeStub` to automatically throw an Assertion Failure; unless, I am misunderstanding the intended purpose of this class. Any insights or suggestions welcome. 

Version: `net.serenity-bdd:serenity-core:2.0.54`

**Comment by wakaleo** [comment]
The intention of the WebElementFacadeStub is to do nothing as best it can after a previous step has failed, so that the test can finish as quickly as possible without causing confusion by throwing other errors. It is not intended to be used in test code directly.

**Comment by hccummins** [comment]
> The intention of the WebElementFacadeStub is to do nothing as best it can after a previous step has failed, so that the test can finish as quickly as possible without causing confusion by throwing other errors. It is not intended to be used in test code directly.

Thanks for the clarification. To model a missing WebElement as is my intention, it seems as though one could instead use 
`WebElementFacadeImpl.wrapWebElement(getDriver(), null, <configured_Implicit_Timeout>, <configured_explicit_Timeout>);`
