### ISSUE TITLE
Performable interface too complicated?

### ISSUE THREAD

**Issue by globalworming** [serenity-bdd/serenity-core#2366]
implementing a performable creates a 

```
@Override
public <T extends Actor> void performAs(T t) {}
```
is there a reason we can't just change the performable to

```
void performAs(Actor actor);
``` 
instead of 
```
<T extends Actor> void performAs(T actor);
``` 
so it looks a bit nicer implementing the interface?

**Comment by wakaleo** [comment]
It would break a lot of code.

**Comment by globalworming** [comment]
so.. i could try? and fail terribly? :)
