### ISSUE TITLE
Question:How to ignore certificat errors on IE using Serenity WebDriver

### ISSUE THREAD

**Issue by RomanIshchenko** [serenity-bdd/serenity-core#237]
Does not help
serenity.driver.capabilities="ie.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS:true;browserstack.debug:false;single-window:true;ie.ensureCleanSession:true;SECURE_SSL:false;ACCEPT_SSL_CERTS:true;--ignore-ssl-errors:true

**Comment by wakaleo** [comment]
You should probably post this on the Serenity user group (https://groups.google.com/forum/#!forum/thucydides-users), where more people will have had experience using IE.

**Comment by RomanIshchenko** [comment]
Thanks a lot for link I sorted out my problem

homePage.openAt(url);
		if("Certificate Error: Navigation Blocked".equals(getDriver().getTitle())) {
			getDriver().navigate().to("javascript:document.getElementById('overridelink').click()");
		}

**Comment by RomanIshchenko** [comment]
sorted out
