### ISSUE TITLE
How to get the text from a particular xpath and how to store that in a string using Serenity

### ISSUE THREAD

**Issue by sudhir-kunchakuri** [serenity-bdd/serenity-core#2371]
I want to fetch the text from an xpath and then store it in a string.

Scenario: 
After entering all inputs and submitting , a new code will get generated on web page and which looks like Customercode: IN02732114(number will dynamic).

Now i want to fetch this code and store it in a string and later I want to use this string in other steps to search the data with this code.

i have used below different snippets to get the text from the xpath.

public static Question<String> customer_code_value() { return actor -> Text.of(CustomerCreatePage.CUSTOMER_CODE_TEXT).viewedBy(actor).asString().substring(15, 26); }

String code= customer_code_value(); // trying to store the value in String code

but customer_code_value() method returns in Question and cant store in String.

Need some help on how to get the text and store it in string in Serenity. 
Please help me ...

**Comment by globalworming** [comment]
In your test you would call

```
String customerCode = actor.asksFor(new CustomerCodeValue());

```
with the question being
```
public class CustomerCodeValue extends Question<String> {

  String answeredBy(Actor actor) {
    return actor.asksFor(Text.of(CustomerCreatePage.CUSTOMER_CODE_TEXT).asString()).substring(15, 26);
  }
}
```

**Comment by sudhir-kunchakuri** [comment]
Thanks for your reply.
But Question<String> is an interface so it should be implements rather than extends right.

as of now i have put as like this.

public class CustomerCodeValue implements Question<String> 

but i am getting some error in the below code snippet.

![image](https://user-images.githubusercontent.com/70365103/105492342-d241fd80-5cdd-11eb-98ce-a60292be43ba.png)

Can you please help me to get it resolved.

@globalworming

**Comment by globalworming** [comment]
what version of serenity are you using? it compiles with the latest version. of cause with `implements` instead of `extends` :)

**Comment by sudhir-kunchakuri** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/70365103/105494014-2948d200-5ce0-11eb-83de-daf3c07f2409.png)

i think it should be asAString() instead of asString() and i have put as asAString() and executed but at compilation i am getting error.


![image](https://user-images.githubusercontent.com/70365103/105494309-978d9480-5ce0-11eb-82ff-08b74c86a476.png)

**Comment by globalworming** [comment]
:shrug: no clue how to use that. it's also not recommended to have different versions of everything...
I would suggest you use the lastest version of serenity. if you dont want that, 2.2.11 has the missing `asString`

**Comment by sudhir-kunchakuri** [comment]
as you said i have updated the most of the dependencies to the latest version.
![image](https://user-images.githubusercontent.com/70365103/105513346-31ad0700-5cf8-11eb-85cf-44b8f7ef9cf4.png)

now when i executed one of my passed scenario to just check the basic build then i am getting this error.
![image](https://user-images.githubusercontent.com/70365103/105513714-a7b16e00-5cf8-11eb-8c7e-636102cb9f0f.png)


Below is my Runner Class: 

![image](https://user-images.githubusercontent.com/70365103/105513515-6a4ce080-5cf8-11eb-8c35-5eff7565bc0c.png)

Can you please help me to get it resolved.. as i am beginner and started to learn so asking help for the issues i am facing..

**Comment by globalworming** [comment]
latest version would need `implementation 'net.serenity-bddserenity-cucumber6:2.3.12'`

**Comment by sudhir-kunchakuri** [comment]
now i am getting this below error after execution:
![image](https://user-images.githubusercontent.com/70365103/105524026-1e546880-5d05-11eb-87cd-d1b345cbed15.png)


and my current chrome browser version is: Version 88.0.4324.104 (Official Build) (64-bit)
i have downloaded ChromeDriver version of below and uploaded in my project 
![image](https://user-images.githubusercontent.com/70365103/105523769-d5041900-5d04-11eb-8abe-27161ca51b9c.png)

and ran again now and still getting the same error and even restarted my system and tried but still getting same error.

![image](https://user-images.githubusercontent.com/70365103/105524014-1bf20e80-5d05-11eb-8e52-1dd70f30790a.png)


can you please help me again here..

**Comment by globalworming** [comment]
you may need to set `webdriver.autodownload=false` in your serenity.properties

**Comment by sudhir-kunchakuri** [comment]
i have added it and it got worked...
Even i am able to get text and store it in string and it also got worked...
Thank u Than u Thank u So much @globalworming for your continuous help.... 
Cheersss broo

**Comment by globalworming** [comment]
:+1:

**Comment by sudhir-kunchakuri** [comment]
@globalworming 
i have one doubt, right now inorder to store one field i have created one class..
Now if i want to store multiple other fields, should i need to create each class for each field?
or is there any way to create only one common class and capture the data for multiple fields and use them where ever i want..?

**Comment by globalworming** [comment]
check out the [WebElementQuestion](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/questions/WebElementQuestion.java) and see if you can get what you need from there
