### ISSUE TITLE
assumeThat with Cucumber fails Step and Report instead of Ignore

### ISSUE THREAD

**Issue by ChrisVanBael** [serenity-bdd/serenity-core#2379]
In my preconditions I'm trying to use assumeThat so that my tests don't fail, but are ignored. 
This is discussed in: https://serenity-bdd.github.io/theserenitybook/latest/junit-skipping.html
However, is this also applicable when using Cucumber? In the report the step and tests are marked as failed.
I'm using Serenity-BDD 2.3.6 with Cucumber 6.6.0 and for the assumeThat I do an import of "import static org.junit.Assume.assumeThat;"

Another user also seems to have this issue:
https://gitter.im/serenity-bdd/serenity-core?at=6017b8554f7d1b68e522a72f

**Comment by globalworming** [comment]
Just tried it with the cucumber starter project... and it works :shrug: 

```
 Given Sergey is researching things on the internet # starter.stepdefinitions.SearchStepDefinitions.researchingThings(net.serenitybdd.screenplay.Actor)
      org.junit.AssumptionViolatedException: got: <true>, expected: is <false>
```

and the report shows the test as ignored. can you provide a minimal example where it does not work?

**Comment by ChrisVanBael** [comment]
It seems to be working now for me, have no idea why. I only bumped Serenity from 2.3.6 to 2.3.12. And then I put it back to 2.3.6 to test and the failed assumption still puts the step and scenario to ignored.  So I don't have a clue anymore.

What I still don't like however, is that the report just puts the step and scenario to ignored without providing the assumption that failed. I've added a workaround in my code to report the failed assumption like this:
```
    @Given("the following processes are running:")
    public void verifyRunningProcesses(List<String> processes) {
        processes.forEach(process -> {
            Boolean status = processTasks.verifyProcessRunning(process);
            Serenity.recordReportData()
                    .withTitle("Is process '" + process + "' running? " + status.toString().toUpperCase())
                    .andContents(status.toString());
            assumeThat(" is process " + process + " running?", status, is(true));
        });
    }
```
It would make my code more clear if the failed assumption was put into the report by default.

**Comment by wakaleo** [comment]
@ChrisVanBael That would make a great enhancement to the framework if you want to have a go at proposing a pull request.

**Comment by ChrisVanBael** [comment]
Any suggestions where to start hunting for the behavior?

**Comment by ricardorlg-aval** [comment]
you can play with the exceptions too, for example instead of using AssumeThat, make the validation, if fails throws a specific exception with the details, and in ur serenity.conf add the serenity.skipped.on=your.exception, serenity will mark the tests as ignored and in the details of the test, you will find the details of the exceptions with screenshots and other information.

**Comment by globalworming** [comment]
nice, #1208

@ChrisVanBael are you fine with this solution? can you confirm it works? I'll update https://serenity-bdd.github.io/theserenitybook/latest/serenity-system-properties.html then

**Comment by ChrisVanBael** [comment]
I haven't tried the suggestion above.
Did some digging in the code and noticed in serenity-cucumber6 in SerenityReporter.java the recordStepResult method.
It's called through some other methods by an EventHandler on TestStepFinished, I assume from Cucumber itself.
What I see is that a step with a failed assumption gets status SKIPPED and then stepIgnored is called.
For status FAILED, there is a method failed(String stepTitle, Throwable cause) which funnily checks isAssumptionFailure.
I find that a bit odd, did Cucumber previously return FAILED instead of SKIPPPED for a failed assumption?

I think the solution may be to a similar method ignored
```
    private void failed(String stepTitle, Throwable cause) {
        if (!errorOrFailureRecordedForStep(stepTitle, cause)) {
            if (!isEmpty(stepTitle)) {
                getContext().stepEventBus().updateCurrentStepTitle(stepTitle);
            }
            Throwable rootCause = new RootCauseAnalyzer(cause).getRootCause().toException();
            if (isAssumptionFailure(rootCause)) {
                getContext().stepEventBus().assumptionViolated(rootCause.getMessage());
            } else {
                getContext().stepEventBus().stepIgnored();
            }
        }
    }
```
and call this in recordStepResult on line 803. What do you think?

**Comment by ChrisVanBael** [comment]
Finally got around to look into this. 
Suggestion https://github.com/serenity-bdd/serenity-core/issues/2379#issuecomment-772617560 didn't work for me: no information was added to the report.
I have adapted the code in serenity-cucumber6 as mentioned above and that does seem to add the assumeThat message to the report. Tried to make a PR for that, but could not push my code.
Here is the Git patch:
`
---
 .../cucumber/core/plugin/SerenityReporter.java | 18 ++++++++++++++++--
 1 file changed, 16 insertions(+), 2 deletions(-)

diff --git a/src/main/java/io/cucumber/core/plugin/SerenityReporter.java b/src/main/java/io/cucumber/core/plugin/SerenityReporter.java
index 261867c..8b0dbec 100644
--- a/src/main/java/io/cucumber/core/plugin/SerenityReporter.java
+++ b/src/main/java/io/cucumber/core/plugin/SerenityReporter.java
@@ -8,7 +8,7 @@ import io.cucumber.messages.Messages.GherkinDocument.Feature.TableRow;
 import io.cucumber.messages.Messages.GherkinDocument.Feature.TableRow.TableCell;
 import io.cucumber.messages.Messages.GherkinDocument.Feature.Scenario.Examples;
 import io.cucumber.messages.Messages.GherkinDocument.Feature.Tag;
-import io.cucumber.messages.Messages.GherkinDocument.Feature.Step;;
+import io.cucumber.messages.Messages.GherkinDocument.Feature.Step;
 import io.cucumber.plugin.ConcurrentEventListener;
 import io.cucumber.plugin.Plugin;
 import io.cucumber.plugin.event.*;
@@ -805,7 +805,7 @@ public class SerenityReporter implements Plugin, ConcurrentEventListener {
         } else if (Status.FAILED.equals(result.getStatus())) {
             failed(stepTitleFrom(currentStep, currentTestStep), result.getError());
         } else if (Status.SKIPPED.equals(result.getStatus())) {
-            getContext().stepEventBus().stepIgnored();
+            skipped(stepTitleFrom(currentStep, currentTestStep), result.getError());
         } else if (Status.PENDING.equals(result.getStatus())) {
             getContext().stepEventBus().stepPending();
         } else if (Status.UNDEFINED.equals(result.getStatus())) {
@@ -864,6 +864,20 @@ public class SerenityReporter implements Plugin, ConcurrentEventListener {
         }
     }
 
+    private void skipped(String stepTitle, Throwable cause) {
+        if (!errorOrFailureRecordedForStep(stepTitle, cause)) {
+            if (!isEmpty(stepTitle)) {
+                getContext().stepEventBus().updateCurrentStepTitle(stepTitle);
+            }
+            Throwable rootCause = new RootCauseAnalyzer(cause).getRootCause().toException();
+            if (isAssumptionFailure(rootCause)) {
+                getContext().stepEventBus().assumptionViolated(rootCause.getMessage());
+            } else {
+                getContext().stepEventBus().stepIgnored();
+            }
+        }
+    }
+
     private String currentStepTitle() {
         return getContext().stepEventBus().getCurrentStep().isPresent()
                 ? getContext().stepEventBus().getCurrentStep().get().getDescription() : "";
-- 
`

**Comment by globalworming** [comment]
I'll have look later 👀
