### ISSUE TITLE
serenity.take.screenshots=DISABLED throw IllegalArgumentException

### ISSUE THREAD

**Issue by RomanIshchenko** [serenity-bdd/serenity-core#238]
http://thucydides.info/docs/serenity-staging/#_managing_screenshots
serenity.take.screenshots can be set to configure how often the screenshots are taken
DISABLED
Doesn’t save screenshots for any steps.

java.lang.IllegalArgumentException: No enum constant net.thucydides.core.model.TakeScreenshots.DISABLED
serenity.version>1.1.21

**Comment by RomanIshchenko** [comment]
<serenity.version>1.1.21</serenity.version>

**Comment by YamStranger** [comment]
Hello @RomanIshchenko. Thanks for this issue. 

Disabled introduced by this pull request #191 to fix this issue:  #188. This level was introduced from [1.1.22-rc.5](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.22-rc.5)

Please try to use last version that available. 

If you feel that this issue already fixed - please close this issue.

**Comment by RomanIshchenko** [comment]
Hi @YamStranger the bug has been fixed. Thank you
