### ISSUE TITLE
Unable to initialize Chrome driver with serenity version 2.3.12

### ISSUE THREAD

**Issue by sumit-global** [serenity-bdd/serenity-core#2380]
@wakaleo Getting "net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (**Trailing char < > at index 4: true** ). See below for more details.
**Caused by: java.nio.file.InvalidPathException: Trailing char < > at index 4: true** " trying to initialize chromedriver.

Note:

Kept chromedriver.exe into project root folder
passed below value in serenity.properties file
driver=chrome
drivers.windows.webdriver.chrome.driver=chromedriver.exe
Using serenity-cucumber6
Getting "Uninitialised WebDriverFacade" value for driver.
ChromeBrowser version: 88.0.4324.104
ChormeDriver version: 88.0.4324.96
Please let me know in-case of any other additional information required

**Comment by wakaleo** [comment]
Can you provide a project to reproduce this issue?
