### ISSUE TITLE
Screenplay - Reading/Sending Emails

### ISSUE THREAD

**Issue by thePantz** [serenity-bdd/serenity-core#2382]
Hello,

I need the ability to read emails using screenplay. My application sends emails to various users and I need to verify they've been sent, their content is correct, parse information out of them, etc. Unless I'm mistaken, this is unsupported at this time.

I'm planning on implementing the following but I'd like some feedback. I'd gladly submit a PR if this would be helpful for others.

### AccessInbox (Ability)

- accepts credentials, mail server name, etc.
- Manages mailbox connection for a given actor
- `as(actor)` - checks if actor has ability, returns instance of `AccessInbox`
- `getConnection()` - get the mailbox connection (using Java Mail)

### SearchTermBuilder

- Builds search criteria to find email(s)
- `areFrom()`, `areTo()`, `haveSubject()`, `areSentAfter()`, etc.
- `build()` returns a [SearchTerm](https://docs.oracle.com/javaee/7/api/javax/mail/search/SearchTerm.html)

### MatchingEmails (Question)

- accepts `SearchTermBuilder` (calls `build()`) in the constructor to get SearchTerm)
- Gets email connection using `AccessInbox` ability, searches for emails matching the provided `SearchTerm`
- returns a collection of [Message](https://docs.oracle.com/javaee/7/api/javax/mail/Message.html)

So it would end up looking something like this:

```
actor.can(AccessInbox.withCredentials(user, pass, mailServer));

Message[] messages =
actor.asksFor(MatchingEmails.that(SearchTermBuilder.areFrom("abc123@test.com").haveSubject("Test"))
```

I'm not sure if I like users having direct access to the `Message` object. However, I want to leave flexibility. There's a bunch of complexity around parsing the mail content if say it contains html the user may want to parse it through the DOM. 

Any thoughts?

**Comment by globalworming** [comment]
capturing mails is a pretty common requirement I think, so I think it may be useful to have. check out https://github.com/mailosaur/mailosaur-java , there may be something worth stealing there in terms of how the API could look like.

But in my personal use.. I only needed 
`actor should eventually see a mail with subject $subject arrived`
`message = actor asks for latest mail to $actorEmail with subject $subject`
and obviously
`message.getLinks().findFirst(link -> isConfirmationUrl(link))` :)
