### ISSUE TITLE
Automatic-Module-Name uses invalid identifier '-' in Manifests for serenity

### ISSUE THREAD

**Issue by naveenchandra91** [serenity-bdd/serenity-core#2384]
Automatic-Module-Name uses invalid identifier '-' in Manifests for serenity. Hence we get the following errors when we try to import :

Automatic-Module-Name: serenity-core: Invalid module name: 'serenity-core' is not a Java identifier. Hence while creating jars the '-' should be replaced with '.' and then added to manifest.

**Comment by naveenchandra91** [comment]
This issue relates to issue number #1835 . I will be a raising a PR to fix this.

**Comment by wakaleo** [comment]
We are relooking at the build process as we are migrating away from JCenter - this change will be considered as part of this migration.

**Comment by naveenchandra91** [comment]
@wakaleo: Can you please let me know an approximate time required for that.. I will have to plan my tasks in my org according to that..

**Comment by wakaleo** [comment]
It's open source, so not really, no - it will be ready when it's ready.

**Comment by naveenchandra91** [comment]
@wakaleo : Okay I understand.. Thank you.. Please let me know if I could do something to help you with the process.

**Comment by wakaleo** [comment]
Do you use Gradle or Maven?

**Comment by naveenchandra91** [comment]
@wakaleo : We use Gradle

**Comment by wakaleo** [comment]
Should be fixed in 2.3.31
