### ISSUE TITLE
How to see the status of each scenario as pass or fail in the console itself rather than waiting for the report.

### ISSUE THREAD

**Issue by sudhir-kunchakuri** [serenity-bdd/serenity-core#2386]
Background : In One Feature file there are 10 scenarios and now i am running those scenarios with the help of tag.
When i execute it sometimes some scenarios get failed and i can know only the failed scenarios once the report got generated.
Now my question is, is there any way to see the status of each scenario as pass or fail in the console itself rather than waiting for the report.

Please let me know inorder to acheive it what code i have to add in any config file or add any dependency or someother thing..

**Comment by globalworming** [comment]
try https://serenity-bdd.github.io/theserenitybook/latest/serenity-system-properties.html#_serenity_logging in your serenity.properties

`serenity.logging=VERBOSE`

**Comment by sudhir-kunchakuri** [comment]
I have mentioned like this in my Serenity Config file
![image](https://user-images.githubusercontent.com/70365103/107735860-b4891680-6d26-11eb-8506-b56013355949.png)

Now i have ran the scripts with one tag which runs two scenarios and i cant see any execution status of the scenario in console.
Can you let me know what need to be done more..

------- Below is the Console log -------

11:32:30: Executing tasks 'clean build -Denvironment=sit -Dtags="Facility-Search-By-Reference"'...

> Task :clearReports
> Task :clean
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :jar
> Task :assemble
> Task :compileTestJava
> Task :processTestResources
> Task :testClasses
> Task :test
Picked up JAVA_TOOL_OPTIONS: -agentpath:"C:\windows\system32\Aternity\Java\JavaHookLoader.dll"="C:\ProgramData\Aternity\hooks" -agentpath:"C:\WINDOWS\system32\Aternity\Java\JavaHookLoader.dll"="C:\ProgramData\Aternity\hooks"

> Task :aggregate
Generating Serenity Reports for mdm-cmd-automation to directory file:///C:/Users/sudhir/Automation%20New%20Sudhir/mdm-cmd-automation/target/site/serenity/

> Task :checkOutcomes
Checking serenity results for mdm-cmd-automation in directory C:\Users\sudhir\Automation New Sudhir\mdm-cmd-automation\target\site\serenity

> Task :check
> Task :build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 30s
9 actionable tasks: 9 executed
11:34:00: Tasks execution finished 'clean build -Denvironment=sit -Dtags="Facility-Search-By-Reference"'.

**Comment by wakaleo** [comment]
This might be a gradle question - you need to configure gradle to print the output of the test task to the console, which it doesn't do natively I think.

**Comment by sudhir-kunchakuri** [comment]
I have added this in my build.gradle file

![image](https://user-images.githubusercontent.com/70365103/108087120-20f47480-709d-11eb-907b-6cbd49863c10.png)

I can see the output like this in my console:

![image](https://user-images.githubusercontent.com/70365103/108087266-484b4180-709d-11eb-92a7-9cb4d20ab079.png)

I feel i have got my answer with the above implementation but again just want to know is it the right way of implementing it or else please do let me know the correct way..
