### ISSUE TITLE
NullPointerException when waiting until page has been loaded

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2389]
Hi there,

As many others I'm using the below code snippet to check for a page is loaded completely:
```
    public boolean waitForPageToBeLoaded() {
        WebDriverWait wait = new WebDriverWait(getDriver(), getWaitingTime());

        ExpectedCondition<Boolean> javascriptHasLoaded = driver -> {
            return ((JavascriptExecutor) driver).executeScript("return document.readyState").equals("complete");
        };

        ExpectedCondition<Boolean> jQueryHasLoaded = driver -> {
            return ((JavascriptExecutor) driver).executeScript("return typeof jQuery !== 'undefined'").equals(true);
        };

        return wait.until(javascriptHasLoaded) && wait.until(jQueryHasLoaded); // --> NullPointerException
    }
```

When running my tests in parallel saying up to 3 instances  I'm sometimes facing a NullPointerException at "org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)":
```
V value = isTrue.apply(input); // input --> WebDriverFacade
```

I'd like to know the reason for the NullPointerException. Moreover, could you please suggest the Serenity way to replace the above Selenium snippet?

Thanks and best regards,
André

**Comment by globalworming** [comment]
No clue about the null pointer but

why are you waiting? why do you wait for jQuery? I would recommend waiting for specific dom states with the `WaitUntil` class. Invoking the JS executor seems suspicious. 
But if you really need that,  using the screenplay pattern i would create something like

```
actor.attemptsTo(new WaitUntilPageIsLoaded() );

class WaitUntilPageIsLoaded implements Performable {
  @Override
  public <T extends Actor> void performAs(T actor) {
    actor.should(eventually(seeThat(new DocumentReadyState(), is("complete"))));
    actor.should(eventually(seeThat(new JQueryHasLoaded(), is(true))));
  }
}
```
but in general, the app should know if it's ready to be acted upon. if there are things that need loading, the DOM should reflect that so you can wait for something in the DOM instead.

**Comment by aybartsch** [comment]
@globalworming Thanks for your answer. To explain: I'm waiting for jQuery library since I'm using jQuery selectors on an external login page where sometimes jQuery was not yet loaded while using selectors.

May I ask you to explain your statement "but in general, the app should know if it's ready to be acted upon." in more detail?

**Comment by globalworming** [comment]
You can't really know from the outside if your system under test is ready to be tested. Only the system knows and has to tell you in a simple way. In general, when you do selenium based test automation and something feels hacky, like a workaround or just can't be done easily like thousands of other people are doing it, there may be an underlying testability issue that should be addressed. 
For a concrete example: if "jQuery loaded" is a hard requirement, i could imagine putting a "loading" class on the body tag and after jQuery is ready, change "loading" to "loading-done" through jQuery :) then your "wait for jQuery ready" can be expressed `WaitUntil.the("body.loading-done", isPresent())`
But you were saying it's in external page, so I assume you can't influence the pages source code? :)

**Comment by aybartsch** [comment]
@globalworming Thanks again for your answer and ideas. And yes, the page causing the jQuery issues is not under our control. In fact the application under test was written 10 years ago and testability was not in focus of the development.

I decided to get rid of the waitForPageLoaded() method and instead I'm using Serenity methods to wait for elements to become available.

But there is still one issue with the $ selector which I'm going to address separately. Thanks and best regards, André
