### ISSUE TITLE
Serenity forces the InternetExplorer browser to twitch during the run (does not reproducible with other browsers)

### ISSUE THREAD

**Issue by RomanIshchenko** [serenity-bdd/serenity-core#239]
Serenity forces the InternetExplorer browser to twitch during the run
Tried with IE 11
Serenity properties: 
serenity.driver.capabilities="INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS:true;SUPPORTS_JAVASCRIPT:true;
serenity.take.screenshots=FOR_EACH_ACTION

Note:
I'm sure that it is serenity because if you define
serenity.take.screenshots=FOR_FAILURES - twitch does not reproducible.
serenity.version>1.1.21
Tried with Win 8 and Win Server 2008 R2 - the same.

**Comment by YamStranger** [comment]
Hello @RomanIshchenko.

Please try to use last version of serenity bdd. 

Thanks a lot!

**Comment by RomanIshchenko** [comment]
Still reproducible with serenity >> 1.1.22-rc.5

**Comment by wakaleo** [comment]
It does sound like an IE issue related to taking screenshots. Serenity takes lots of screenshots. Most browsers handle this just fine, but there may be an issue with the way IE responds when a screenshot is taken.

**Comment by RomanIshchenko** [comment]
Will be good if somebody can check it with IE 10  to be sure that it is 11 specific

**Comment by wakaleo** [comment]
This appears to be IE related, so there is not a lot we can do on the Serenity side.
