### ISSUE TITLE
$ selector is causing StaleElementReferenceException

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2391]
Hi there,

in another post @wakaleo was suggesting me to use the $ selector to detect elements instead of using FindBy annotation. I was doing so and everything works well with Firefox driver. Now, I'm also using Chrome driver for testing and I'm facing the well-known StaleElementReferenceException when using $ selectors:
```
$("//label[contains(@class, 'job-description')]").click();
$("//a[contains(@ng-click, 'jobQueueCtrl.showDetails(job)')]").click();
```
When clicking on the link which becomes visible after clicking on the label I'm often getting StaleElementReferenceException. But I'm facing this exception also on other places when using $ selector with Chrome driver.

One workaround is to catch this exception and retry to click. The other workaround is to use the driver methods to find the element directly.

I'd like to understand why the usage of the $ selector with Chrome driver is causing this nasty StaleElementReferenceException. Every idea is highly appreciated.

Thanks and best regards, André

PS: I'm using Serenity 2.3.12 and run up to 3 tests in parallel in docker container.

**Comment by wakaleo** [comment]
It's not the $() selector - that's just a shorthand for the Webdriver findBy() method. It means the state of your page is changing when you try to perform the click. You need to figure out how to wait until the DOM is stable before interacting with it.

**Comment by aybartsch** [comment]
@wakaleo Thanks for your answer. I have had a method which was checking the document readyState:
```
    public boolean waitForPageToBeLoaded() {
        WebDriverWait wait = new WebDriverWait(getDriver(), getWaitingTime());
        ExpectedCondition<Boolean> javascriptHasLoaded = driver -> {
            return ((JavascriptExecutor) driver).executeScript("return document.readyState").equals("complete");
        };
        return wait.until(javascriptHasLoaded);
    }
```
Would you suggest to use the above method for checking the DOM state?

**Comment by aybartsch** [comment]
@wakaleo Aside of the above method for checking the DOM state what could I do better? I'm getting the element and clicking on it immediately after. I guess when the element reference becomes stale in milliseconds there is no other solution than to catch the exception and to try again. Would you confirm?

Finally, I guess using waitUntilClickable() would not help in this situation at all.
