### ISSUE TITLE
How to use BeforeAWebdriverScenario  with Provided DriverSource 

### ISSUE THREAD

**Issue by dicksonprof** [serenity-bdd/serenity-core#2392]
We are using Provided to custom our own RemoteWebDriver.
I dont see a way the enhanced capabilities is passed to the DriverSource.

How can we use BeforeAWebdriverScenario hook with Provided?

**Comment by wakaleo** [comment]
If you use a Provided driver you are entirely responsible for creating and configuring the driver in your own code.
