### ISSUE TITLE
How to connect appium with perfecto using serenity

### ISSUE THREAD

**Issue by komireddy407** [serenity-bdd/serenity-core#2399]
Hi @wakaleo @vikramvi @ptillemans @jeffjensen  
I'm trying to setup appium + serenity with perfecto but I'm unable to connect to Perfecto

webdriver.driver= appium
appium.hub = http://0.0.0.0:4723/wd/hub
appium.automationName = uiautomator2
appium.platformName = Android
appium.platformVersion = 10
appium.deviceName  = emulator-5554
appium.app = shop.apk
appium.noReset = true
appium.newCommandTimeout = 1000

Followed https://serenity-bdd.github.io/theserenitybook/latest/remote.html but I can see BrowserStack and sacuelabs
Can you share a sample repo that appium with perfecto using serenity

Thanks in Advance

**Comment by komireddy407** [comment]
Followed https://serenity-bdd.github.io/theserenitybook/latest/remote.html but i can see browserstack and sacuelabs
Can you share a sample repo that appium with perfecto using serenity
Thanks in Advance

**Comment by wakaleo** [comment]
Maybe ask the Perfecto support folks?

**Comment by komireddy407** [comment]
Ok @wakaleo , I'll check with the Perfecto team.
Thank you for your support.

**Comment by madhusudhan-patha** [comment]
@komireddy407 Did you check with them and got any info?

**Comment by komireddy407** [comment]
added securityToken in capabilities and working fine

**Comment by s9g0** [comment]
@komireddy407  - Can you help me with connecting appium to Perfecto. Here is the serenity.properties files looks like 

_webdriver.driver=appium
appium.hub=https://xxxxxxx.perfectomobile.com/nexperience/perfectomobile/wd/hub
appium.automationName = uiautomator2
appium.platformName=Android
appium.platformVersion=10.0
appium.app=com.safety.app
appium.noReset = true_
 
in addition, i've created a capability enhancer extending BeforeAWebdriverScenario

_public class PerfectoCapabilityEnhancer implements BeforeAWebdriverScenario {
	public DesiredCapabilities apply(EnvironmentVariables environmentVariables, SupportedWebDriver driver,
			TestOutcome testOutcome, DesiredCapabilities capabilities) {
		
		capabilities.setCapability("appium:chromeOptions", ImmutableMap.of("w3c", false));
		capabilities.setCapability("location", "US East");
		String token = "sxxffddasd";
		capabilities.setCapability("securityToken", token);
		
		return null;
	}
}_

But my remote session isn't launching. Appreciate any help or if u can share a template project on github..

**Comment by komireddy407** [comment]
Hi Srinivas,

Looks good, try this

return capabilities;

**Comment by s9g0** [comment]
@komireddy407 - No, the app isn't launching after returning capabilities from Enhances.
Also, I've added _appium.deviceName=335854323645123448_ [exact device Android ID where the app is already installed]

By any chance, you've any template project available anywhere in Git or somewhere that i can refer to?
Appreciate your support

**Comment by NataliaPineda18** [comment]
Hola!

Me pueden ayudar por favor a conectar perfecto con appium usando serenity BDD
