### ISSUE TITLE
Report is not generated correctly (since 1.0.29)

### ISSUE THREAD

**Issue by awallat** [serenity-bdd/serenity-core#24]
While in 1.0.28 the report was generated fine, there occured errors in the following versions up to 1.0.31. Several warnings and exception of the type are shown:
> [WARNING] this file was not a valid JSON Serenity test report: 3e1acda910a5b01fa30ba70eca08dd97c60cf196a938c046d09530ffa77d22b8.json
> java.lang.ClassNotFoundException: de.wemove.testing.junit.webmapClient.layer.External

I'm using jUnit tests. I saw that in 1.0.28 when generating a report the following output appeared in the beginning:
> Feb 16, 2015 5:43:23 PM org.hibernate.validator.internal.util.Version <clinit>
> INFO: HV000001: Hibernate Validator 5.1.1.Final

which does not in the other versions.

When switching back to the old version and generating the report (from the 1.0.31 test run) it also seems, that there are some tests missing and warnings of the following type appeared:
> [WARNING] this file was not a valid JSON Thucydides test report: 3fe441dc52bc84292010b8886cf1fd291cbc74aef13683de6d9130c715940425.json
>Invalid UTF-8 middle byte 0x6e
 at [Source: java.io.BufferedInputStream@5d51e129; line: 1, column: 1470] (through reference chain: net.thucydides.core.model.TestOutcome["testSteps"]->java.util.ArrayList[4]->net.thucydides.core.model.TestStep["description"])

**Comment by wakaleo** [comment]
Hi Andre,

Could you send me some of the json files indicated in the exceptions? I
think I've fixed this but want to be sure.

Thanks

John.

On 17 February 2015 at 03:59, André Wallat <notifications@github.com> wrote:

> While in 1.0.28 the report was generated fine, there occured errors in the
> following versions up to 1.0.31. Several warnings and exception of the type
> are shown:
>
> [WARNING] this file was not a valid JSON Serenity test report:
> 3e1acda910a5b01fa30ba70eca08dd97c60cf196a938c046d09530ffa77d22b8.json
> java.lang.ClassNotFoundException:
> de.wemove.testing.junit.webmapClient.layer.External
>
> I'm using jUnit tests. I saw that in 1.0.28 when generating a report the
> following output appeared in the beginning:
>
> Feb 16, 2015 5:43:23 PM org.hibernate.validator.internal.util.Version
> INFO: HV000001: Hibernate Validator 5.1.1.Final
>
> which does not in the other versions.
>
> When switching back to the old version and generating the report (from the
> 1.0.31 test run) it also seems, that there are some tests missing and
> warnings of the following type appeared:
>
> [WARNING] this file was not a valid JSON Thucydides test report:
> 3fe441dc52bc84292010b8886cf1fd291cbc74aef13683de6d9130c715940425.json
> Invalid UTF-8 middle byte 0x6e
> at Source: java.io.BufferedInputStream@5d51e12
> <https://github.com/java.io.BufferedInputStream/serenity-core/commit/5d51e129>;
> line: 1, column: 1470
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/24>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by awallat** [comment]
I put some of the problematic json files here:
https://www.dropbox.com/sh/sc9kbefr7e5gkzx/AAB2Tjy0OTzm38qrkpyTHnC6a?dl=0

**Comment by awallat** [comment]
Looks good in 1.0.35

**Comment by PratapSingh09** [comment]
Report for scenario outline is not appering under serenity index.html file though I can see it is running under console.
Getting below error:
[WARNING] this file was not a valid JSON Serenity test report: 5886ad7d04be3ebbe448bd1fabd784696523876d0f4e0bbc4d00efe069492efb.json
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4127 path $.dataTable.currentRow
used below version:
serenity.version 1.1.24
serenity.cucumber.version: 1.1.3
serenity.maven.version: 1.1.17

written scenario outline in below formate:
Given I open the application
When I enter details as username "", password "" and title "<title>"
Then able to see the homepage

Examples:

| username | password | title |

| Rob | xyz1 | title1 |

| Bob | xyz1 | title2 |

Please help me to resove this issue

**Comment by wakaleo** [comment]
Try using the latest versions of all libraries.

**Comment by PratapSingh09** [comment]
Thanks for you replying... :)

But still after changing the version to below
serenity.version 1.2.3-rc.7
serenity.cucumber.version: 1.1.9
serenity.maven.version: 1.2.3-rc.7

I am only ale to see Scenario name under index.html if I am clicking to see Gherkin step like (Given/When/Then) It is throwing below error:

Your file was not found

It may have been moved or deleted.
ERR_FILE_NOT_FOUND

**Comment by wakaleo** [comment]
Make sure _all_ of your dependencies are updated. The latest cucumber version is 1.1.23

**Comment by PratapSingh09** [comment]
Hi After updating it to latest cucumber version I am not getting any scenario details under index.html.
Getting  No data available 

please find below pom.xml I m using:

<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.2.3-rc.7</serenity.version>
        <java.version>1.7</java.version>
        <serenity.cucumber.version>1.1.23</serenity.cucumber.version>
        <serenity.maven.version>1.2.3-rc.7</serenity.maven.version>
       
        <surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
        <rest-assured.plugin.version>2.4.1</rest-assured.plugin.version>
        <resource.directory>src/test/resources</resource.directory>
        
        <spring-framework.version>4.1.5.RELEASE</spring-framework.version>
        <spring.boot.version>1.2.4.RELEASE</spring.boot.version>
        
        <log4j.version>1.2.17</log4j.version>

        
        <junit.version>4.12</junit.version>
        <slf4j.version>1.6.1</slf4j.version>
        <maven.test.failure.ignore>true</maven.test.failure.ignore>
    </properties>
    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey.contribs</groupId>
            <artifactId>jersey-multipart</artifactId>
            <version>1.8</version>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-client</artifactId>
            <version>1.17.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.3.6</version>
        </dependency>
        <dependency>
            <groupId>eu.medsea.mimeutil</groupId>
            <artifactId>mime-util</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>com.owlike</groupId>
            <artifactId>genson</artifactId>
            <version>0.98</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>smtp</artifactId>
            <version>1.4.7</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.5.1</version>
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>mail</artifactId>
            <version>1.4.7</version>
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>javax.mail-api</artifactId>
            <version>1.5.1</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20090211</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-requirements-provider</artifactId>
            <version>1.1.2-rc.1</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>1.1.2-rc.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.4.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>3.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>1.1.36</version>
        </dependency>

        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring-framework.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-spring</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
            <version>${spring.boot.version}</version>
        </dependency>
        
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>${spring-framework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.8</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.8</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-path</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path-assert</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.5.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.6.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlbeans</groupId>
            <artifactId>xmlbeans</artifactId>
            <version>2.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.6.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>1.23</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty</artifactId>
            <version>3.5.7.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>1.23</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18</version>
                <configuration>
                    <includes>
                        <include>**/test/**/*.java</include>
                        <include>**/features/**/*.java</include>
                    </includes>
                    <systemProperties>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                    </systemProperties>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-requirements-provider</artifactId>
                        <version>1.1.2-rc.1</version>
                    </dependency>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-plugin</artifactId>
                        <version>1.1.2-rc.1</version>
                    </dependency>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>

**Comment by PratapSingh09** [comment]
with below properties:

<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.2.3-rc.7</serenity.version>
        <java.version>1.7</java.version>
        <serenity.cucumber.version>1.1.23</serenity.cucumber.version>
        <serenity.maven.version>1.2.3-rc.7</serenity.maven.version>
       
        <surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
        <rest-assured.plugin.version>2.4.1</rest-assured.plugin.version>
        <resource.directory>src/test/resources</resource.directory>
        
        <spring-framework.version>4.1.5.RELEASE</spring-framework.version>
        <spring.boot.version>1.2.4.RELEASE</spring.boot.version>
        
        <log4j.version>1.2.17</log4j.version>

        
        <junit.version>4.12</junit.version>
        <slf4j.version>1.6.1</slf4j.version>
        <maven.test.failure.ignore>true</maven.test.failure.ignore>
    </properties>

**Comment by PratapSingh09** [comment]
with above properties

**Comment by wakaleo** [comment]
You still have a dependency on serenity-core 1.1.36 in your pom.xml file.

**Comment by PratapSingh09** [comment]
If I have commented this dependency as I have already used this as this under dependency with version 1.2.3-rc.7 then I am getting below error

java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.listFilesAndDirs(Ljava/io/File;Lorg/apache/commons/io/filefilter/IOFile
Filter;Lorg/apache/commons/io/filefilter/IOFileFilter;)Ljava/util/Collection;

![image](https://cloud.githubusercontent.com/assets/17722170/24046350/8de0533c-0b22-11e7-9cd9-2f078cd628b9.png)
 with above report

**Comment by PratapSingh09** [comment]
now I am using below pom.xml


<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.2.3-rc.7</serenity.version>
        <java.version>1.7</java.version>
        <serenity.cucumber.version>1.1.3</serenity.cucumber.version>
        <serenity.maven.version>1.2.3-rc.7</serenity.maven.version>
      
        <surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
        <rest-assured.plugin.version>2.4.1</rest-assured.plugin.version>
        <resource.directory>src/test/resources</resource.directory>
        
        <spring-framework.version>4.1.5.RELEASE</spring-framework.version>
        <spring.boot.version>1.2.4.RELEASE</spring.boot.version>
        
        <log4j.version>1.2.17</log4j.version>

        
        <junit.version>4.12</junit.version>
        <slf4j.version>1.6.1</slf4j.version>
        <maven.test.failure.ignore>true</maven.test.failure.ignore>
    </properties>
    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey.contribs</groupId>
            <artifactId>jersey-multipart</artifactId>
            <version>1.8</version>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-client</artifactId>
            <version>1.17.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.3.6</version>
        </dependency>
        <dependency>
            <groupId>eu.medsea.mimeutil</groupId>
            <artifactId>mime-util</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>com.owlike</groupId>
            <artifactId>genson</artifactId>
            <version>0.98</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>smtp</artifactId>
            <version>1.4.7</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.5.1</version>
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>mail</artifactId>
            <version>1.4.7</version>
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>javax.mail-api</artifactId>
            <version>1.5.1</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20090211</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-requirements-provider</artifactId>
            <version>1.1.2-rc.1</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>1.1.2-rc.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.4.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>3.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>
        

        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring-framework.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-spring</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
            <version>${spring.boot.version}</version>
        </dependency>
        
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>${spring-framework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.8</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.8</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-path</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path-assert</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.5.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.6.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlbeans</groupId>
            <artifactId>xmlbeans</artifactId>
            <version>2.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.6.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>1.23</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty</artifactId>
            <version>3.5.7.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>1.23</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18</version>
                <configuration>
                    <includes>
                        <include>**/test/**/*.java</include>
                        <include>**/features/**/*.java</include>
                    </includes>
                    <systemProperties>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                    </systemProperties>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-requirements-provider</artifactId>
                        <version>1.1.2-rc.1</version>
                    </dependency>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-plugin</artifactId>
                        <version>1.1.2-rc.1</version>
                    </dependency>
                   
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
        <resources>
        
        <resource>

        <directory>src/test/resources/properties/${application.properties}</directory>

        <filtering>true</filtering>
        </resource>
        </resources>

**Comment by PratapSingh09** [comment]
with property below:

<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.2.3-rc.7</serenity.version>
        <java.version>1.7</java.version>
        <serenity.cucumber.version>1.1.3</serenity.cucumber.version>
        <serenity.maven.version>1.2.3-rc.7</serenity.maven.version>
      
        <surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
        <rest-assured.plugin.version>2.4.1</rest-assured.plugin.version>
        <resource.directory>src/test/resources</resource.directory>
        
        <spring-framework.version>4.1.5.RELEASE</spring-framework.version>
        <spring.boot.version>1.2.4.RELEASE</spring.boot.version>
        
        <log4j.version>1.2.17</log4j.version>

        
        <junit.version>4.12</junit.version>
        <slf4j.version>1.6.1</slf4j.version>
        <maven.test.failure.ignore>true</maven.test.failure.ignore>
    </properties>

**Comment by PratapSingh09** [comment]
with property below

<serenity.version>1.2.3-rc.7</serenity.version>
        <java.version>1.7</java.version>
        <serenity.cucumber.version>1.1.3</serenity.cucumber.version>
        <serenity.maven.version>1.2.3-rc.7</serenity.maven.version>
      
        <surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
        <rest-assured.plugin.version>2.4.1</rest-assured.plugin.version>
        <resource.directory>src/test/resources</resource.directory>
        
        <spring-framework.version>4.1.5.RELEASE</spring-framework.version>
        <spring.boot.version>1.2.4.RELEASE</spring.boot.version>
        
        <log4j.version>1.2.17</log4j.version>

        
        <junit.version>4.12</junit.version>
        <slf4j.version>1.6.1</slf4j.version>
        <maven.test.failure.ignore>true</maven.test.failure.ignore>

**Comment by wakaleo** [comment]
Make sure you have the latest versions for all the serenity dependencies.

**Comment by PratapSingh09** [comment]
ok let me do that: :+1:

**Comment by PratapSingh09** [comment]
I will update and let you know

**Comment by wakaleo** [comment]
You have an incorrectly formatted feature file - one of the scenarioa doesn’t have a name:

“A scenario with no name was found for: verify-that-we-can-find-brazil-country-using-the-code-br”

**Comment by ychaudhari** [comment]
Thanks @wakaleo! 
1. After adding the scenario name in feature file, I was able to get scenario name in home/summary page table. however, detailed steps page was showing 'page not found' error.
2. Removing 'output.formats=json' from serenity.properties file did the trick for me. Now I see summary as well as detailed steps in the report!

**Comment by ARadauer** [comment]
In my case this error was caused by a missing name after the Scenario Outline in my feature files.
```
 Scenario Outline: 
    Given I ...
```

The solution was
```
Scenario Outline: This is my Scenario
    Given I ...
```
