### ISSUE TITLE
Rest Query json format

### ISSUE THREAD

**Issue by anka12gft** [serenity-bdd/serenity-core#240]
Hi,
In the Overall Test Results screen, when clicking on Rest Query of a Step, a pop-up with the response data is shown (Status, Response Body). The response body is a json structure but it is not formatted.

![screenshot_restqueryjson](https://cloud.githubusercontent.com/assets/16487935/12049825/e3003afa-aeec-11e5-9e64-ac3e540762d7.jpg)

Would it be possible to format it?
Regards

**Comment by YamStranger** [comment]
Hi @anka12gft. 

Thanks for this issue!!

I will mark you issue as enmeshment, yes it is possible and we will do it during next update of reports.

**Comment by YamStranger** [comment]
depends on #355

**Comment by YamStranger** [comment]
Hello @anka12gft 
You issue is fixed and can be checked in serenity-core 1.1.31. 
![after1](https://cloud.githubusercontent.com/assets/1667699/14664977/60372cd4-06d8-11e6-8618-d4f22b5a2b0b.png)

please close this ticket

Thanks a lot!
