### ISSUE TITLE
Serenity with JUnit is not creating requirement description using readme.md files

### ISSUE THREAD

**Issue by datnq102** [serenity-bdd/serenity-core#2401]
I am trying to add requirement description using readme.md files but it doesn't work. Only the annotation @Narrative is working. Is readme.md not supported for Serenity with JUnit? or what do I need to do to make it work?
Thanks!

**Comment by globalworming** [comment]
the `.md` files are for cucumber based projects. `@Narrative` and `package.info` is for plain junit https://serenity-bdd.github.io/theserenitybook/latest/junit-requirements.html
