### ISSUE TITLE
org.junit is gone from serenity-junit

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#2404]
In version 2.3.26 I get compile errors:
package org.junit does not exist

Looks like the junit package disappeared from the pom.xml of serenity-junit.

What is the plan going forward? Am I now expected to bring it in explicitly for my project?

**Comment by wakaleo** [comment]
Hmmm, it should be a transitive dependency of serenity-junit, but you will be using JUnit classes directly, so you probably should include it as a dependency in its own right in your project.

**Comment by wakaleo** [comment]
We switched from gradle to maven, so the dependencies might be a bit different

**Comment by SiKing** [comment]
I have been using Maven since 4ever.

**Comment by wakaleo** [comment]
So the summary is: you'll need to include the junit dependency in your project directly.

**Comment by SiKing** [comment]
I'm curious: Why the switch from Gradle to Maven? Seems like most projects go the other way.

**Comment by SiKing** [comment]
For anybody that finds this bug, the last version that works "the old way" and brings in all transitive dependencies (there is way more than just junit) is version 2.3.12.

Version 2.3.13 is missing serenity-maven-plugin. And after that the project changed to the new way?
