### ISSUE TITLE
Task blindly swallows Exception

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#2405]
I have a `net.serenitybdd.screenplay.Task`. In the `performAs()` method I call `java.util.concurrent.ThreadLocalRandom.current().nextInt()`. I accidentally called it with 0, as in `ThreadLocalRandom.current().nextInt(0);`. This should have thrown `java.lang.IllegalArgumentException`.

I was expecting the test to terminate at this point with this error. However, the test continued, and in my case got stuck in an endless loop.

I have since discovered that I have other Tasks where I am expecting that an Exception would terminate the task and fail the test. However this is not happening.

It appears as if a Task swallows any Exception and just continues with execution. Is this a bug, or am I just using this wrong?

**Comment by wakaleo** [comment]
Sounds like a bug.

**Comment by wakaleo** [comment]
I can't reproduce this, could you provide a sample project?

**Comment by SiKing** [comment]
I was trying to create a (unit) test that shows this, and then I wanted to look if I could fix it. Unfortunately I am blocked by #2335 Any chance you could help me with that @wakaleo ?

**Comment by SiKing** [comment]
I had some time today to look into this. I cannot reproduce it anymore either. :(
