### ISSUE TITLE
net.serenitybdd.core.pages.WebElementFacade.type() method not working

### ISSUE THREAD

**Issue by sumit-global** [serenity-bdd/serenity-core#2406]
**serenity.version: 2.3.10
serenity.cucumber.version: 2.3.10
driver= safari
saucelabs.target.platform=macOS 10.13
saucelabs.browser.version=12**

method **type()** is entering blank value instead of actual String passed when running suite on **Safari** browser on sauce lab, unable to check on safari browser when running locally.

workaround: use sendKeys() instead of type() method for safari browser.

Please let us know in-case of any additional information required.

**Comment by wakaleo** [comment]
I have no idea with what to do with this - have you asked the Saucelabs folks? I would use the work-around in the meantime.

**Comment by sumit-global** [comment]
Thanks @wakaleo for your quick response.

I think issue is here with type() method which is available in WebElementFacade class not sure saucelab folks will play any role here.

Regards,
Sumit

**Comment by wakaleo** [comment]
I would recommend just using sendKeys().
