### ISSUE TITLE
Chrome 88 disable third party cookies preference problem

### ISSUE THREAD

**Issue by ebbesandslevin** [serenity-bdd/serenity-core#2407]
hi guys,

I use Serenity with Chrome 88 and I would like to set the parameter 'Disable third party cookies' as false, see screenshot attachment: 
![image](https://user-images.githubusercontent.com/47423361/110911423-fc459280-8312-11eb-8584-fc01cf21ebf3.png)

I know that this chrome feature was changed in version 84.
I tried to set the following parameter to false (also to true): 'chrome_preferences.profile.block_third_party_cookies', but it didn't made any changes. Also this one: 'chrome_preferences.profile.default_content_setting_values.cookies', but also not helped.
The parameters are taking into consideration by serenity, because the log shows me that this/these preferences are in use.

I am not sure that this is a serenity issue, can could you please take a look and help me figure it out how I can set this parameter in the code?

Thank you!

Sandor

**Comment by wakaleo** [comment]
Sound's like a Chrome issue.

**Comment by ebbesandslevin** [comment]
Could you please send me a forum where I can ask for it?

**Comment by wakaleo** [comment]
https://chromedriver.chromium.org

**Comment by ebbesandslevin** [comment]
issue resolved by using this parameter: 
chrome_preferences.profile.cookie_controls_mode=0
