### ISSUE TITLE
Feature tab in Serenity BDD Report for JBehave case

### ISSUE THREAD

**Issue by Paco-lo** [serenity-bdd/serenity-core#241]
I am using JBehave, then .story files. As said in BDD in Action book (5.5.1) I would like to change 'Stories' tab in the report to 'Features' in order to avoid confusions with User Stories agile terminology, but it seems the only tab not configurable (at least I don't know how to do it).

Also the order of the tabs would be good to be configurable to follow a left to the right detail order (instead alphabetical order).

Thank you very much.

![bddreport](https://cloud.githubusercontent.com/assets/16477791/12054569/ff70a1b0-af24-11e5-8478-f3582b021441.png)

**Comment by YamStranger** [comment]
Hello @Paco-lo 

Thanks for your issue.

So you would like add possibility to configure:
1) tab names
2) positions of tabs

I will mark this issue as enhancement. 

Thanks a lot!
