### ISSUE TITLE
aggregate gradle task no longer finds any tests in 2.3.11

### ISSUE THREAD

**Issue by hertzsprung** [serenity-bdd/serenity-core#2413]
My gradle build with `net.serenity-bdd:serenity-gradle-plugin:2.3.10` produced an aggregate report successfully, but not with 2.3.11 or above.
I can see that test results are written to `target/site/serenity` successfully, but they are not being picked up during aggregation.

Let me know if you need more information and I'll do my best to help :slightly_smiling_face:

**Comment by wakaleo** [comment]
Could you produce a sample project?

**Comment by hertzsprung** [comment]
Here's a minimal sample project.
[serenity-core-2413.tar.gz](https://github.com/serenity-bdd/serenity-core/files/6220661/serenity-core-2413.tar.gz)
