### ISSUE TITLE
Serenity is not marking compromised tests based on defined custom Exceptions

### ISSUE THREAD

**Issue by NSnietol** [serenity-bdd/serenity-core#2414]
Hello,

I am currently using serenity (core) version  2.1.0 I have some custom Exceptions created and added those as part of serenity properties file as follow:

`serenity.compromised.on=projectname.utils.MyTestException`

It seems serenity doesn't recognize them, I tried with Java Exceptions such as RunTimeException, SQLException and so and it worked properly.

I came across some suggestions and although I added the project as a dependency to Serenity aggregate stage, I'm not seeing the test marked as `compromised  `.

When I see the report I get this message `UnrecognisedException`.

REPORT

![image](https://user-images.githubusercontent.com/12100190/111372967-5757ec00-8669-11eb-94dc-ff4de707a8b2.png)

POM REFERENCE
```
		<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>${project.groupId}</groupId>
						<artifactId>${project.artifactId}</artifactId>
						<scope>system</scope>
						<version>${project.version}</version>
						<systemPath>${project.basedir}/target/${project.artifactId}-1.0-SNAPSHOT.jar</systemPath>
					</dependency>
				</dependencies>
			</plugin>
```

Thanks you 😃

**Comment by globalworming** [comment]
what works good for me is creating a base error that is marked "compromised"

```
import net.serenitybdd.core.exceptions.CausesCompromisedTestFailure;

public class CompromisedTestError extends AssertionError implements CausesCompromisedTestFailure{

  public CompromisedTestError(Object detailMessage) {
    super(detailMessage);
  }

  public CompromisedTestError(String message, Throwable cause) {
    super(message, cause);
  }
}
```

and extending from that and throwing the meaningful errors

```
public class ThirdPartyAuthError extends CompromisedTestError {


    public ThirdPartyAuthError(Object detailMessage) {
        super(detailMessage);
    }

    public ThirdPartyAuthError(String message, Throwable cause) {
        super(message, cause);
    }
}
```

```
then(actor).should(eventually(seeThat(
                WebElementQuestion.the(CurrentPage.statusMessageError),
                WebElementStateMatchers.isNotPresent()))
                .orComplainWith(ThirdPartyAuthError.class, message));
```

**Comment by NSnietol** [comment]
Hi @globalworming, I got it over by creating my owned Exceptions that extended from TestCompromisedException

**Comment by aspenboy** [comment]
@NSnietol @globalworming but shouldn't this work also for "regular" exceptions, like for example `java.sql.SQLException`?

**Comment by NSnietol** [comment]
@aspenboy  well to be honest I didn't notice it, I was getting and the failure marked with red color. Although I could cope it by using this class net.serenitybdd.core.exceptions.TestCompromisedException, I created my owned exceptions based on that one and it marked the tests as compromised even without using the Serenity property file.
