### ISSUE TITLE
Share variables between steps using rest screenplay and cucumber

### ISSUE THREAD

**Issue by s1apped** [serenity-bdd/serenity-core#2415]
Hi.

What is the recommended way of sharing variables and state between steps using rest screenplay and cucumber?
@Steps, notepad?
Unfortunately haven't been able to find much on rest screenplay + cucumber 

Thanks!

**Comment by globalworming** [comment]
Yeah, actor.remember and actor.recall is usually the way to go.
With serenity rest, actors always remember the last response and there are specific questions to get the latest response.
Actor.askFor(LastResponse.received()) if i recall correctly.
