### ISSUE TITLE
How to learn to code in the screen play pattern fast?

### ISSUE THREAD

**Issue by SchnuckySchuster** [serenity-bdd/serenity-core#2417]
Hallo community,

this might be a stupid question, nevertheless:

For years I intend to learn to use the screen play pattern. I never got the hang of it so far.
Now I try again. I watch the you tube videos and I read the tutorials.
I can understand what I see and read.
In fact it feels beautiful, natural, inspiring, ... .

I just don't know how to get from reading something like this 

`then(anna).should(eventually(seeThat(TheWebPage.title(), containsString("BDD In Action"))));`

to being able to write it my self.

How many people actually use the screen play pattern and if you happen to be one, how did you get there? 
I started with the API documentation. My problem there is that I don't see much documentation there apart from the bare bone java doc.
But diving in to the API spec I learn that `should(...)` needs a consequence, but how to know what methods of what objects return what types of consequences?

I think I could try to get my hands on as much example code I can find and from there try to figure out things via trial and error.

The problem is I'm a consultant and I need to show my customer why it would be good for him to use the screen play pattern.
Currently I see lots of reasons why the screen play pattern is nice.
On the other hand if it takes lots of time to learn how to use this pattern because there is not much in terms of a detailed "how to transition from steps and pages to screen play" I see no business case. 

What I've found so far are teasers that make appetite to use the screen play pattern.
What do I miss?

May be I'm just not a good enough java developer and for the good java developers the whereabouts of the screen play pattern is so obvious that there is no need for the kind of documentation I'm looking for.

On the other hand people who write automated tests are no expert developers, otherwise they would be developers not testers.

So am I to assume that the old "steps and pages" way to use Serenity is meant to be used by testers and the screen play pattern is meant to be used for real java developers? 

I'd love to get the hang of the screen play pattern.
Help is much appreciated.

**Comment by wakaleo** [comment]
@SchnuckySchuster I've worked with lots of testers who have mastered the art of Screenplay. If you want to reach out to me directly (on LinkedIn or via https://serenitydojo.as.me/clarity-call) I'd be happy to give you some insight.

**Comment by SchnuckySchuster** [comment]
Hi John,

do you have Serenity BDD Dojo videos available as a self paced course available in a udemy style? 
I did a training with Mumshad Mannambeth <https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiioen3i9bvAhXID2MBHTdyCYgQFjABegQIBBAD&url=https%3A%2F%2Fwww.udemy.com%2Fuser%2Fmumshad-mannambeth%2F&usg=AOvVaw2JPk8VYybw-b7wfzcwpCP8> from https://kodekloud.com/courses <https://kodekloud.com/courses>  which I really liked.

The package had a reasonable price which I do not remember.
I did book a years worth of access to one course.
There were lots of videos available.
There was a discord channel for asking questions.

I’d like to book your course, but I think I do not want to spend 600€ per month as I don’t know when I will have time to study. I might have lots of time one month and no time the next month.
Also being able to slow down, skip, fast forward … content works well for me plus I would like to pause and apply what I have seen.  

Gerhard


Mit besten Grüßen,
Gerhard Schuster

Festnetz: 08637/986157
Mobil:      0179/1006330

**Comment by aspenboy** [comment]
@SchnuckySchuster I've been using serenity for almost 3 years now, and also trying to apply screenplay pattern where applicable. `Questions` and `Consequences` are a bit confusing at first. Right now I'm trying to stick to `Ensure` library, which is not perfect - but usually does the trick. To be honest - screenplay pattern looks nice, but it's a bit overrated. It's not easy to get into it and might actually lead to overengineering. As the documentation is not very detailed - you can try to study the questions implemented in serenity and try to apply similar approach in your case.

If you have more specific example then maybe we can think about the approach?

**Comment by SchnuckySchuster** [comment]
@aspenboy Thanks for your response! 
I want to use ScreenPlay in my current project. I have coded my tests via Page and Steps so far.
Somehow my test suites ended up quite messy and tests where not easy to maintain.
I put high hopes on the ScreenPlay pattern. It feels so elegant.
But I have no experience how good the test suite will end up and whether maintanance will be an issue or not.
I also think that the documentation or the lack there of is a big drawback.

Once I have some experiance and given I have time I would like to contribute to the documentation.
ScreenPlay looks nice to read but I got through lots of pain reprogramming my brain to be able to think in ScreenPlay.  

I think I got the hang of it.

**Comment by globalworming** [comment]
i have a some example projects on github you can look up https://github.com/globalworming?tab=repositories&q=serenity 

you can also meet me https://calendly.com/aw_calendly1/coffee and I'll show you around a browser automation project I did for an insurance company if that helps.

Regarding "how to get there".. i feel its pretty easy when you already have the requirements in a way that also mentions given/when/then style who does what why. In the mentioned project I subversively asked questions while grooming to get the requirements in a state where this is the case.
