### ISSUE TITLE
Formatting error when there is slash in feature name

### ISSUE THREAD

**Issue by malekadrar** [serenity-bdd/serenity-core#2420]
Hello,
First of all, thank you very much for this beautiful tool which I'm starting to use to generate my BDD reports and live documentation.

I've a little issue which seems to be a bug. Suppose we've the following cucumber feature such as its name has a slash 

    Feature: The division A/B

      Scenario Outline: Natural numbers division 
          Given the numbers <x> and <y>
          When we divide x by y
          Then the <division> should be
  
          Examples:
              | x | y | division |
              | 1 | 1 | 1        |
              | 0 | 1 | 0        |

So, when we run the tests and have a look at the home page of the Serenity reports, we notice that:

in the Summary tab, the name of the feature is truncated: the string before the backslash is omitted. In our case, only "B" is displayed. Whereas Serenity behave properly in the others sections. For instance in the tab "Test Results", all the feature name of our example (The division A/B) is displayed.

Thanks in advance

Feel Free to contact me for any other precision.

Regards,
Malek

**Comment by wakaleo** [comment]
I can't reproduce this in version 2.4.0

**Comment by malekadrar** [comment]
Hello,

I'll upgrade to 2.4.0. Thanks.

Regards
