### ISSUE TITLE
Not able to download driver on http adress with standard serenity configuration

### ISSUE THREAD

**Issue by romain85** [serenity-bdd/serenity-core#2425]
Hello,

we try to configure webdriver with http adress (in internal repository) and it doesn't work.
This protocole doesn't seem to be supported. is it possible to add it ?

we are on serenity bdd version 2.3.10

Thanks

**Comment by wakaleo** [comment]
Do you mean using WebDriverManager?

**Comment by romain85** [comment]
not at all, we tried to put directly an HTTP address on driver.windows.webdriver.chrome.driver configuration.
it's probably not the good way to achieve the webdriver management ?

thanks

**Comment by wakaleo** [comment]
Oh, gotcha. Yeah, that's not supported at all at the moment.

**Comment by romain85** [comment]
ok, what's the good way to manage the driver ? (using Webdriver Manager ?)

thanks

**Comment by nicolashenrylbp** [comment]
Hello, 
Do we have to configure the webdrivermanager (adding a webdrivermanager.properties file?)
Is there a way to configure it using serenity.conf file?
Thanks

**Comment by wakaleo** [comment]
See https://github.com/bonigarcia/webdrivermanager#configuration
