### ISSUE TITLE
Attachment upload for ALM tool question

### ISSUE THREAD

**Issue by ebbesandslevin** [serenity-bdd/serenity-core#2426]
Hi,

I got a task to get Serenity screenshots for the current scenario or the HTML report for the current scenario with the screenshots attached and send them to our ALM tool with POST request to its API.
Is there a way to do such a thing in Serenity? Maybe is there an example code somewhere?
The POST part is no problem, the problematic part is to reach the html or the jpg files to attach them, which I do not know how to do in my java code.

I found an open issue here, where you told to get the json file and get the data from it, but I do not know if it can solve my problem.

Thank you for your answer!
Sandor

**Comment by wakaleo** [comment]
There is no such feature at the moment, but you could write one yourself by processing the JSON test outcomes and calling your REST API.

**Comment by ebbesandslevin** [comment]
ok thank you

**Comment by ebbesandslevin** [comment]
sorry one more question:
is there a way to generate the json/html/jpg files for a scenario after its run, and not after all the scenarios run? 
I mean for me now they are generated in post-integration-test phase (all of them together as I understand) and I am not sure if it is possible to run any action after this step in java.
Or do you know any way how to reach the json files before the post-integration-phase or after?

Sandor

**Comment by wakaleo** [comment]
The JSON files are generated after each scenario is completed.

**Comment by ebbesandslevin** [comment]
one more question:
what to do if the tests running in parallel? I mean how to make sure that the json file in the folder is the latest and it belongs to the last running test? 
I mean: it is an easy way to verify that which json file belongs to the latest executed scenario?

**Comment by wakaleo** [comment]
Each scenario generates a different outcome file, so unless you are running the same scenario in parallel, it shouldn't be an issue.

**Comment by ebbesandslevin** [comment]
understood, thx

**Comment by ebbesandslevin** [comment]
hi again :)

As I understood (maybe missunderstood) that after each scenario run a new json file is generated with png screenshots as a report to folder target/site/serenity.

For me it worked different: it was ok with only 1 scenario.
But if I ran 2 (or 5) scenarios then the json files were generated only after the last scenario (the 2nd or the 5th) was running. 

Is it possible to setup serenity to generate the json files and screenshots after each scenario run separate?

If not then is it an easy way to know (beside opening all of them 1 by 1) which json belongs to which scenario?

In my script after each scenario I was looking for the last json which was generated and checked its contain, but if I run 2 (or more) scenarios then the json is not found in the folder.

Sandor

**Comment by wakaleo** [comment]
Are they Cucumber scenarios?

**Comment by ebbesandslevin** [comment]
Yes

**Comment by wakaleo** [comment]
The results will get generated when the scenarios executed by the cucumber runner class are finished. What problem are you trying to solve?

**Comment by ebbesandslevin** [comment]
The problem I would like to resolve is the following:

I would like to report to our ALM tool based on the serenity report with
the screenshots as attachment.
As I know the only way to get the screenshost is the json file which
belongs to the cucumber scenario.
My problem is to build a logic in java to know which json file belongs to
which scenario.

Right now I did a solution which finds the latest generated json file after
each scenario, but that one fails because all the jsons are generated after
the last scenario run

**Comment by globalworming** [comment]
just let them run all and then run whatever you want on the testoutcomes? https://serenity-bdd.github.io/theserenitybook/latest/importing-test-outcomes.html

**Comment by ebbesandslevin** [comment]
Looks good: thank you!

Is it possible to get the screenshots as well with this logic?

**Comment by globalworming** [comment]
Didn't look at the model, but it should contain the screenshots as far as i remember

**Comment by ebbesandslevin** [comment]
Ok thank you: I will try it out today or on monday

Have a nice weekend

**Comment by ebbesandslevin** [comment]
Good morning!

Which file should I open in folder to get the results in folder 'target/site/serenity'?
See attachment ![image](https://user-images.githubusercontent.com/47423361/115200985-197d3600-a0f5-11eb-96ef-5e9142213c47.png)

**Comment by ebbesandslevin** [comment]
Also in the model I cannot find the screenshots (which is the whole point to get the results for me), could you please help me with that?

**Comment by wakaleo** [comment]
The test outcomes are the json files in target/site/serenity. Screenshots are also here.

**Comment by ebbesandslevin** [comment]
ok thz: actually I already created a model for the results already, but I will use your model instead: found the screenshot list in it eventually

One more question:
When is the moment when the json files are generated?
is the @AfterClass annotation a good approach for that? I mean if put my script to get the screenshots in an afterclass annotation then is is sure that till that time all the jsons are generated?

**Comment by wakaleo** [comment]
@Afterclass might work. Report generation happens when the JUnit test runner finishes, which is not exactly the same thing as the before/after annotations

**Comment by ebbesandslevin** [comment]
Maybe do you have a better solution when to check the report results?
Actually from me this was a guess that afterclass could work...

**Comment by globalworming** [comment]
your safest best would be after the whole run. so basically in the post-verify phase.. similar to this maybe https://stackoverflow.com/a/52559004/1359903

**Comment by ebbesandslevin** [comment]
it worked with @AfterClass: thanks for the help guys

I close the ticket
