### ISSUE TITLE
To Enable Disable Serenity REST request/response data reported in Serenity report 

### ISSUE THREAD

**Issue by MaheshDani** [serenity-bdd/serenity-core#2428]
To Enable Disable Serenity REST request/response data reported in Serenity report.

Please could you guide us on how we can enable disable through configuration, whether given REST request/response/headers data should be reported in serenity report or not.

Some of REST generate huge amount of rest data that make serenity report too big to handle with limited memory. hence request for this option.

**Comment by wakaleo** [comment]
If you don't want the request to be reported, use RestAssured.* instead of SerenityRest.*

**Comment by MaheshDani** [comment]
@wakaleo 
Is there no way to disable reporting data in serenity report only when there is validation failure or something like that?

**Comment by wakaleo** [comment]
No, that isn't supported.

**Comment by MaheshDani** [comment]
oh.. ok.. Thanks for your answer on above query.

**Comment by ricardorlg-aval** [comment]
You can also use this:

``` kotlin         
 Get.resource(PATH).with { request ->
                request
                    .contentType(ContentType.JSON)
            }.withNoReporting()```

the withNoReporting will ignore the query in the report.

**Comment by MaheshDani** [comment]
@ricardorlg-aval 
I can't fine any `.withNoReporting()` in serenityREST. 
what library package is that?
