### ISSUE TITLE
Some html report page not generated when using serenity.compress.filenames = false in serenity.properties

### ISSUE THREAD

**Issue by IntJiang** [serenity-bdd/serenity-core#2429]
Version:
`    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <serenity.version>2.3.12</serenity.version>
        <serenity.maven.version>2.3.6</serenity.maven.version>
        <serenity.cucumber.version>2.3.12</serenity.cucumber.version>
        <webdriver.driver>chrome</webdriver.driver>
    </properties>`

Scenario: (Workspaces_Users_A006)Verify that non-account admin user with WSS_Read+Edit+Delete_UserGroups and WSS_Read+Edit_Policies rule can perform proper actions on 'Users>User Groups'

I'm running serenity with maven clean verify, aggregate plugin has been included in our pom.xml.

For some reason, if the Scenario name above is inclued in feature file, the index.html file will generate, but all Scenarios detailed html files will be missing.

And the amazing thing is, if I replace all "+" with "-" or "_" in that Scenario name, this issue will not occur.

But if the Scenario name is "WSS_Read+Edit+Delete_UserGroups" or "a+b", this issue will not occur.

Also I want to know more detailes of the naming rules in generating the html file for Scenario when using serenity.compress.filenames = false. For example, "(" will be translated to "_opr" and ")" is "_cpr". We want to map the html files with our Scenario names. 

Thanks in advance : )

**Comment by wakaleo** [comment]
The best is to use scenario names using plain natural language without special characters. But to answer your question, setting `serenity.compress.filenames` to false is known to cause issues when there are special characters in the scenario name (and in general on Windows), so should only be used for troubleshooting.

**Comment by IntJiang** [comment]
So is there any workaround to map scenario names to the unreadable html report files? Such as "e8df890104cfad772c33a8bab17df9a06ffe6ff7eb65d462f1f2aa7f1183e504.html"

**Comment by wakaleo** [comment]
In version 2.4.4, set `serenity.logging` to `verbose`.

**Comment by IntJiang** [comment]
Sorry, I'm not clear what the version "2.4.4" means. I didn't saw this version in the Release Notes of serenity-core. Could you please help to provide more info?

**Comment by IntJiang** [comment]
Update: I found the work around:
https://serenity-bdd.github.io/theserenitybook/latest/importing-test-outcomes.html
We can get the name of report html file with `outcome.getReportName()`
