### ISSUE TITLE
upgrade typesafe config to newer version

### ISSUE THREAD

**Issue by bassmake** [serenity-bdd/serenity-core#243]
`ConfigBeanFactory` was added in 1.3.0. https://github.com/typesafehub/config#configbeanfactory

it will be nice to have it be default.

**Comment by YamStranger** [comment]
Hello @bassmake. 

Thanks for this issue!!! 
Version updated, if you feel that you request applied - please close this issue. 

Thanks

**Comment by YamStranger** [comment]
Hello @bassmake. 

Unfortunately I need reopen this ticket. 

It seems that 1.3.0 can be used only for java 8 [as described there](https://github.com/typesafehub/config#supports-java-8-and-later), so we can not use it for now (a lot of projects are used java 7).

I will revert this update, and we will use 1.2.1, until it will be possible to use 1.3.0 with java 7 or we decide stop support of older versions of java.

**Comment by wakaleo** [comment]
Unfortunately we can't force Java 8 on users as much as we would like to ;-)

**Comment by wakaleo** [comment]
Current version is 1.3.1
