### ISSUE TITLE
Need an advice on the error - net.serenitybdd.core.exceptions.SerenityManagedException

### ISSUE THREAD

**Issue by LalithaRajesh06** [serenity-bdd/serenity-core#2430]
![image](https://user-images.githubusercontent.com/82463816/114584598-c03b7f80-9c7a-11eb-84b1-d910054816f1.png)

![image](https://user-images.githubusercontent.com/82463816/114587730-d7c83780-9c7d-11eb-90bf-206e63ce204a.png)

Hi Team, 

My name is Lalitha and I am a QA Automation Engineer . I have upgraded my pom.xml file recently to use maven-failsafe-plugin instead of temyers/cucumber-jvm-parallel-plugin. After I upgraded it, I started getting the following error mentioned below. For a sanity check, I had tested the same code in the lower version (to the previous version before I moved my changes), it was running successfully. I could not figure anything exactly more on this error.  

Error details:
17:06:37.209 [main] INFO   - STEP ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: Receiver class net.serenitybdd.rest.decorators.ResponseSpecificationDecorated$ByteBuddy$d1qolyPM does not define or inherit an implementation of the resolved method abstract body(Ljava/lang/String;Lorg/hamcrest/Matcher;[Ljava/lang/Object;)Lio/restassured/specification/ResponseSpecification; of interface io.restassured.specification.ResponseSpecification.

The steps I had taken to resolve:
1) Tried adding byteBuddy dependency
2) my current serenity version is 2.3.12. Tried changing that to 2.4.1 as well. I suspected that there would be a version mismatch between serenity and hamcrest. However, it did not work even after I used the recent serenity version.. 
3) I deleted the java package folder(com)  inside the repositories under .m2 folder. Then tried to maven clean install. 

However all these steps did not provide any effect.

Please can some one help me on this issue. Any help on this would really be appreciated.
Thank you,
Lalitha Rajesh

**Comment by wakaleo** [comment]
Looks like a version conflict with an incompatible version of rest assured.

**Comment by LalithaRajesh06** [comment]
Thanks John. I have few doubts on the version conflict. 

My previous serenity version was 2.2.9. Now, I have upgraded to 2.3.12. On looking into the above error, we have a java library called bytebuddy. I understand that bytebuddy will automatically get some reflections of the code like providing an implementation for interfaces or abstract methods automatically. So, while we are using 2.2.9, it was able to use those decorations I believe. However after upgrading to 2.3.12, for some reason, it is not able to do the io.restassured related abstract methods. 

![image](https://user-images.githubusercontent.com/82463816/114744224-5dfb8100-9d45-11eb-9d13-0fe54e33d3cc.png)

Internally on the code, this is the place where I see the serenityManagedException error.

On my perspective When this except() is being called, the serenity BDD rest assured internally calls io.resassured response specifications only. Hence it is not able to get the classes that it is looking for. 

When we take a closer look on   https://javadoc.io/doc/io.rest-assured/rest-assured/3.0.5/io/restassured/specification/ResponseSpecification.html#expect-- , it returns a response specification. Similarly, when we take a look at https://javadoc.io/doc/net.serenity-bdd/serenity-rest-assured/2.0.71/net/serenitybdd/rest/SerenityRest.html#expect--  the except method is providing the io.restassured.specification.ResponseSpecification. When this method is not built by bytebuddy, then it is not able to get that responseSpecification properly. 

Hence if this assumption is correct, I tried to add the dependency like below.
<dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>xml-path</artifactId>
            <version>3.0.2</version>
        </dependency>

However, I still get the same error. 

Please can you advice on this  further.

**Comment by wakaleo** [comment]
It's a dependency conflict with your version of rest-assured. Remove the dependencies on rest-assured in your pom.xml.

**Comment by LalithaRajesh06** [comment]
Hi John, 

Thanks for your message. I did not have that dependency earlier. I just added it now to understand if that makes any difference. 
Any how having that dependency/ not having that dependency results in the same error.

**Comment by wakaleo** [comment]
Try doing a dependency analysis to find out where the dependency conflict is, and adding a version compatible with the latest version of Serenity (e.g. 4.3.3)
