### ISSUE TITLE
unable to customize requirement  types using cucumber with serenity

### ISSUE THREAD

**Issue by GianniGiglio** [serenity-bdd/serenity-core#2435]
Using property:
serenity.requirements.types=capability,stories
I would expect the report to show tabs capability stories however the report keeps displaying: 
Themes, epics and features

Added a test project
[serenity-cucumber-threaded.zip](https://github.com/serenity-bdd/serenity-core/files/6344773/serenity-cucumber-threaded.zip)

**Comment by wakaleo** [comment]
Did you try with `serenity.requirement.types`?

**Comment by GianniGiglio** [comment]
Hi,

Just tested same result serenity.requirement.types or serenity.requirements.types
