### ISSUE TITLE
Serinity downloading all user stories from Jira even if we run single user story from Jira

### ISSUE THREAD

**Issue by konavenkatesh** [serenity-bdd/serenity-core#2436]
Hi Sir,

We have done Jira integration with my serinity-jbehave framework, and observed that all user stories were downloading and printing on console even if I ran single user story, because of that Execution time is increasing, is there any way to disable downloading stories from jira and displaying on console ?

**Comment by wakaleo** [comment]
Why do you think this is related to the JIRA integration?

**Comment by konavenkatesh** [comment]
thank you sir for your reply, i am thinking that JiraStoryLoader is loading all user stories from Jira and printing all scenarios on Console. 
Please find the below example:

I have 5 User stories in my JIRA and each user story having 10 scenarios each.
Out of 5 User Stories, i want to run Story#2, so provided tag as 'Sample_Test' for the all scenarios in the Story#2. And i ran the Maven project with command as 'clean verify -Dmetafilter=groovy:Sample_Test'.

Then i could see that all User stories are downloading from JIRA and printing in Console (i mean all 50 scenarios are printed on Console), because of this my execution time got increased, is there any way to stop printing all scenarios on Console.

Just because of this my Org is not interested in Serenity, But i am very much interested in Serenity. Please help me on this.

Thank you
Venkatesh

**Comment by wakaleo** [comment]
That's a fairly old library that we no longer support because of performance issues with JIRA and changing JIRA APIs, but feel free to look at the code and see if you can improve it for your purposes. Generally JIRA structures are not clean enough for requirements documentation, since JIRA is a ticket tracking system, not a requirements specification tool.

**Comment by konavenkatesh** [comment]
Hi Sir,

Can i have link for new library as we don't have permission to share code. And we are using below classes to connect and load JIRA User Stories:
JIRAStoryLoader , 
JIRAStoryPathFinder 
thucydidesConfiguration
JiraStepDocReporter
JiraStoryReporter.

Thanks in advance.
Regards
Venkatesh

**Comment by wakaleo** [comment]
There is no new library but you are free to contribute one.
