### ISSUE TITLE
Question on restarting the browser and clearing cookies

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-core#2443]
Could you please clarify what is the difference between:
- `@Managed(uniqueSession = true)` - "You can also get Serenity to open the browser at the start of the tests, and leave it open until all of the tests in this test case have been executed, using the uniqueSession parameter."
- and `serenity.restart.browser.for.each = story` - "Indicate when a browser should be restarted during a test run. Can be one of: example, scenario, story, feature, never."

I would also like to know: When the browser is restarted, what happens to local storage and cookies. If I use `@Managed(clearCookies = Never)` in combination with `serenity.restart.browser.for.each = story`, do cookies persist between each story?

**Comment by wakaleo** [comment]
These annotations have a long history - best to dig into the code and see how they work exactly.

**Comment by wieben** [comment]
For those using `serenity-cucumber` running multiple tests on a single browser instance, a combination of 
`serenity.restart.browser.for.each=never` and tagging tests with `@singlebrowser` prevent the `SerenityReporter.handleTestCaseStarted` method from restarting the browser, in version 3.1.5

**Comment by wakaleo** [comment]
Closed for lack of activity.
