### ISSUE TITLE
Can i incorporate Reporting ability of serenity into an existing project which has its own dependencies already junit with POM?

### ISSUE THREAD

**Issue by Ramaa99** [serenity-bdd/serenity-core#2445]
@wakaleo ,Hello Sir,Can i incorporate Reporting ability of serenity into an existing project which has its own dependencies already.
I'm using Cucumber /Junit /Java with Page object Model , all the Page objects(web elements/xpaths) in one .Java file and Page related Step definition methods in one Java file.
Please advice.
Thanks much for your time!!

**Comment by wakaleo** [comment]
You would need to switch to the Serenity cucumber runner and let Serenity manage your WebDriver instances - that would be a start.
