### ISSUE TITLE
Warning message while executing test

### ISSUE THREAD

**Issue by skhandekar1** [serenity-bdd/serenity-core#2446]
I am new to Serenity BDD and getting the following warning message. How do I get rid of them?

[pool-5-thread-1] WARN net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: Method net/serenitybdd/plugins/jira/requirements/JIRARequirementsProvider.getParentRequirementOf(Lnet/thucydides/core/model/TestOutcome;)Ljava/util/Optional; is abstract
java.lang.AbstractMethodError: Method net/serenitybdd/plugins/jira/requirements/JIRARequirementsProvider.getParentRequirementOf(Lnet/thucydides/core/model/TestOutcome;)Ljava/util/Optional; is abstract
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java)
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementFor(BaseRequirementsService.java:48)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:171)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by skhandekar1** [comment]
Any help at all? This is really driving me crazy!

**Comment by wakaleo** [comment]
It might be fixed in the latest version, but it's just a warning - if your requirements reports are generating, you can ignore it.

**Comment by skhandekar1** [comment]
Thank you.   Is there any way to turn off this warning? I work in a medical device industry and might not be easily able to download the new version as each test tool need to undergo a strict evaluation for FDA. So can I take care of the problem in the current version by setting any properties in the serenity.properties file?

My serenity.properties file looks as follows:


webdriver.driver = appium

appium.platformName = Android

appium.platformVersion = 10.0

#Replace deviceName and udid with your S6 Tablet's Serial Number
appium.deviceName = R52N20ALVDN
appium.udid = R52N20ALVDN


appium.hub = http://127.0.0.1:4723/wd/hub
#appium.url = http://127.0.0.1:4443/wd/hub

#appium.systemPort = 8205

appium.appPackage = Nalu.CP.Android

appium.automationName = uiautomator2

#appium.appActivity = md5943e8bc44609f7ff612d6ac75f507b3d.ActivityLicenseBrowse
#appium.appActivity = md581ec75973e0b97f2dfd0a5656e9f1c4d.ActivityLicenseBrowse
appium.appActivity = crc6429e3927486beccbc.ActivityLicenseBrowse

#appium.app =  D:\\Nalu.CP.Android_763.apk

appium.noReset = true

#appium.dontStopAppOnReset = true

appium.resetKeyboard = true

appium.unicodeKeyboard = true

appium.browserName =
#The above capability is needed to run the test...

appium.newCommandTimeout = 5000

appium.skipDeviceInitialization = true

appium.skipServerInstallation = true

#Skips unlock during session creation
appium.skipUnlock = false	

appium.noSign = true

#appium.dontStopAppOnReset = true

appium.ignoreUnimportantViews = true

appium.disableAndroidWatchers = true

appium.disableWindowAnimation = true

serenity.project.name = CP Automation Report <br/> <h5> Device: Samsung Galaxy Tab S6 <br/> <h5/>

#serenity.take.screenshots = DISABLED
serenity.take.screenshots = AFTER_EACH_STEP

serenity.console.headings = normal

serenity.requirement.types = feature, story

step.creation.strategy = legacy

**Comment by skhandekar1** [comment]
It gets really difficult to view a clean log on the screen. Having to search through the logs is really cumbersome. My serenity version is 2.2.0

**Comment by cliviu** [comment]
can you post your pom also please ?

**Comment by skhandekar1** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.nalumed.mobapp</groupId>
	<artifactId>nalu-med-mob-app</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>2.2.0</serenity.version>
		<serenity.maven.version>2.2.0</serenity.maven.version>
	</properties>

	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>https://jcenter.bintray.com</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>https://jcenter.bintray.com</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.141.59</version>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jira-requirements-provider</artifactId>
			<version>1.8.0</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.25</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.9.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.11.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.11.0</version>
		</dependency>

		<dependency>
			<groupId>ru.yandex.qatools.ashot</groupId>
			<artifactId>ashot</artifactId>
			<version>1.5.3</version>
		</dependency>

		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>7.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>5.2</version>
		</dependency>
	</dependencies>

	<build>

		<plugins>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<id>current-time</id>
						<phase>validate</phase>
						<goals>
							<goal>timestamp-property</goal>
						</goals>
						<configuration>
							<name>current.time</name>
							<pattern>dd-MM-yyyy_HH-mm-ss</pattern>
							<timeZone>IST</timeZone>
						</configuration>
					</execution>
				</executions>
			</plugin>

			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<verbose>true</verbose>
					<fork>true</fork>
					<executable>${JAVA_HOME}\bin\javac</executable>
				</configuration>
			</plugin>
			
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.21.0</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.21.0</version>
				<configuration>
					<includes>
						<include>**/*.java</include>
					</includes>
					<argLine>-Xmx512m</argLine>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
						<configuration>
							<outputDirectory>./Outputs/SerenityReports/CP Test Automation Report-${current.time}</outputDirectory>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-jira-requirements-provider</artifactId>
						<version>1.8.0</version>
					</dependency>
				</dependencies>
			</plugin>

		</plugins>

	</build>
</project>

**Comment by cliviu** [comment]
do you need serenity-jira-requirements-provider ?

**Comment by skhandekar1** [comment]
Thank you! That solved it. One more question before I close this issue. I want to use the WebDriverListener (that i had used in the past with Selenium) with webdriverFacade. I have looked everywhere for the answer to this question but haven't been able to find anything. Can you help? Do I raise a separate issue for this?
