### ISSUE TITLE
Unable to use Webdriver eventListeners with WebDriverFacade 

### ISSUE THREAD

**Issue by skhandekar1** [serenity-bdd/serenity-core#2447]
I am currently declaring all my android elements as webElementFacade as I want to use the added functionality of wait for element to appear before action is taken etc. The problem is I am not able to use the WebDriver provided EventListeners so that I can log all actions that are taken on any elements without having to create a separate basePage file from which all my page classes inherit to get common log messages. Any way to achieve this in Serenity?

**Comment by globalworming** [comment]
I can't really follow you.. I am assuming you have the serenity provided driver instance somewhere available at the start of your test and want to register some event listeners..  would `getProxiedDriver()` help to get the driver you are looking for?
https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFacade.java#L100

**Comment by skhandekar1** [comment]
So I have my test as follows:

```
package com.mobapp.pages;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.apache.poi.ss.usermodel.Sheet;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.nalumed.mobapp.commonfunctions.BasePage;
import com.nalumed.mobapp.commonfunctions.FileIO;

import lombok.Getter;
import net.serenitybdd.core.annotations.findby.By;
import net.serenitybdd.core.pages.PageObject;
import net.serenitybdd.core.pages.WebElementFacade;

/*
 * This page defines page objects and methods to interact with Login page
 * Please make sure to use the BasePage methods for WebElement interactions
 */

@Getter
public class LoginPage extends BasePage{
	
	private static final Logger log = LoggerFactory.getLogger(LoginPage.class);

	
	FileIO fileIO = new FileIO();
	Sheet sheet;
	String fileName = "./src/test/resources/testData/LoginPageData.xlsx";
	
	// Page Object Initialization
	
	@FindBy(id="btnLogin1")
	private WebElementFacade loginButton;

	@FindBy(id="btnForgotPasscode")
	private WebElementFacade forgetPasscodeButton;

	@FindBy(id="txtPasscode")
	private WebElementFacade inputPasscodeField;

	@FindBy(id="txtClinicName")
	private WebElementFacade clinicLogo;

	@FindBy(id="txtWelcometo")
	private WebElementFacade welcomeLabel;

	@FindBy(id="txtLeapstim")
	private WebElementFacade applicationLabel;

	@FindBy(id="txtPasscodeTitle")
	private WebElementFacade passcodeLabel;

	@FindBy(id="txtPasscodeMessage")
	private WebElementFacade passcodeMessage;

	@FindBy(id="btnAppVersion")
	private WebElementFacade appVersion;
	
	
	
	//Methods
	
	public void setPasscode(String passcode) {
		inputPasscodeField.type(passcode);
		log.info("Clicked on " + inputPasscodeField.toString());
	}	
	
	public void clickOnLoginButton() {
		loginButton.click(); 
		log.info("Clicked on " + loginButton.toString());
	}
}
```

All elements are declared as WebElementFacade. Now I don't want logging messages in individual page classes for every element action. So normally when I don't use serenity, I am adding the WebDriverListener and register the eventListener in my class.

https://www.softwaretestinghelp.com/webdriver-listeners-in-selenium/

How can the same be achieved when I use webdriverfacade instead of webdriver? Right now since I am not sure how to do that I am using a base class where all the log messages exist. But I would rather have the WebDriverFacade do the logging for me, by me implementing the webdriverListener class:

BasePage class:

package com.mobapp.commonfunctions;

/*
 * This class mentions all the common methods that will be inherited
 * by the rest of the page classes. Repetitive code like logging for every 
 * element action will be added to this file
 */
public class BasePage extends PageObject{
	
	private static final Logger log = LoggerFactory.getLogger(BasePage.class);
    
    //Commonly used webElementFacade methods
	
	public void clickBtn(WebElementFacade btnName) {
		log.info("About to click " + btnName + " button");
		btnName.click();
		log.info("Successfully clicked on " + btnName + " button.");		
	}
	
	public void clickLink(WebElementFacade linkName) {
		log.info("About to click " + linkName + " link");
		linkName.click();
		log.info("Successfully clicked on " + linkName + " link");		
	}
	
	public void typeText(WebElementFacade txtBoxName, String text) {
		log.info("About to type into " + txtBoxName + " text box" + " the text '" + text + "'");
		abc();
		txtBoxName.type(text);
		log.info("Successfully typed into " + txtBoxName + " the text '" + text + "'");
	}
}

**Comment by globalworming** [comment]
check out https://serenity-bdd.github.io/theserenitybook/latest/advanced-webdriver.html and wrap your driver with the EventFiringWebDriver from the link you shared

**Comment by skhandekar1** [comment]
> I can't really follow you.. I am assuming you have the serenity provided driver instance somewhere available at the start of your test and want to register some event listeners.. would `getProxiedDriver()` help to get the driver you are looking for?
> https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFacade.java#L100
> so.. get the serenity driver, get the proxied driver, cast to the specific driver you need

I am able to do this just fine in the test class:

	@Test
	public void test() throws InterruptedException{
		AndroidDriver<AndroidElement> androidDriver = (AndroidDriver<AndroidElement>) ((WebDriverFacade) appiumDriver).getProxiedDriver();
		EventFiringWebDriver eventDriver = new EventFiringWebDriver(appiumDriver);

		EventHandler handler = new EventHandler();
		eventDriver.register(handler);
		
		eventDriver.findElement(By.id("txtPasscode")).sendKeys("147258");
		eventDriver.findElement(By.id("btnLogin")).click();
		Thread.sleep(2000);
	}

But I am not sure how to send the eventDriver to @Managed tag using custom driver. I don't want to have to add this code to all my test classes. I am following POM and want the eventHandler driver to directly come through @Managed. So basically instead of saying 

@Managed
WebDriver appiumDriver

I want to say
@Managed
EventDriver appiumDriver 

and get the driver with eventhandler already attached. 

Just not sure how to use customDriver class for this. This is what i tried, but it fails:

`
public class MyEventDriver implements DriverSource {

	@Override
	public WebDriver newDriver() {
		System.out.println("Here");
		DesiredCapabilities capabilities = DesiredCapabilities.android();
		WebDriver appiumDriver = new AndroidDriver(capabilities);
		AndroidDriver<AndroidElement>  driver = (AndroidDriver<AndroidElement>) ((WebDriverFacade) appiumDriver).getProxiedDriver();
		EventFiringWebDriver eventDriver = new EventFiringWebDriver(driver);

		EventHandler handler = new EventHandler();
		eventDriver.register(handler);
		return eventDriver;
	}
`

My serenity properties file have to be changed too, though i just am not understanding how. This is what I tried:

webdriver.driver = provided
webdriver.provided.type=mydriver
webdriver.provided.mydriver=com.nalumed.mobapp.commonfunctions.MyEventDriver;
thucydides.driver.capabilities = mydriver

I just followed what was given in https://serenity-bdd.github.io/theserenitybook/latest/extending-webdriver.html for the above. where am I going wrong? i get error saying

could not instantiate the custom webdriver provider of type androiddriver;

**Comment by skhandekar1** [comment]
Not an issue
