### ISSUE TITLE
Summary chart renders little red line (for failures, even there are no)

### ISSUE THREAD

**Issue by punkratz312** [serenity-bdd/serenity-core#2449]
There is a little red line that indicated the error cases. In my case i only have working ✅ or pending scenarios, so there should no red anything be displayed imho the chart. Im sure its just a small adjustment to fix this ✅ ✅ .

thanks

![image](https://user-images.githubusercontent.com/8830888/117278795-5cfbd200-ae61-11eb-9c8d-1c9371f96a50.png)

![image](https://user-images.githubusercontent.com/8830888/117278401-08f0ed80-ae61-11eb-861d-d9baeefd96aa.png)

**Comment by wakaleo** [comment]
It should but it doesn't. I can't fix this, I think it is an issue with the underlying JS library.
