### ISSUE TITLE
Is it possible to remove html tags from the log?

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#245]
If you use `serenity.logging = VERBOSE` there will be HTML tags in Serenity log. Is it possible to remove them from the log?

![](http://take.ms/x7LjD)

**Comment by wakaleo** [comment]
What HTML tags do you mean?

**Comment by dsmt** [comment]
Hi, John. 
I can't reproduce this issue, It seems to be fixed in one of the previous commits.

**Comment by wakaleo** [comment]
Thanks for the update.
