### ISSUE TITLE
How to register webdriver/actor for current running test?

### ISSUE THREAD

**Issue by MHamzaY-E** [serenity-bdd/serenity-core#2450]
I am creating actors during the runtime during a junit test. For these actors screenshots do not appear in the report. From what I have found is that I got to use 

```
@Managed
WebDriver driver;
```

inside the test class. As the serenity runner initializes and uses this driver to get screenshots. But I do not know how many actors will be created during runtime. So I am creating actors in the code without predefining them in the main test class. 

How can I register drivers of the dynamically created actors ? I have tried this 

`ThucydidesWebDriverSupport.getWebdriverManager().registerDriver(BrowseTheWeb.as(actor).getDriver());`

as the code inside the registerDriver method kinda suggests that it registers the driver to current test.

 ```
 @Override
    public void registerDriver(WebDriver driver) {
        if (driver != null) {
            inThisTestThread().registerDriverCalled(nameOf(driver)).forDriver(driver);
            inThisTestThread().setCurrentDriverTo(driver);
        }
    }
```

But it did not work. So how can I pass the webdriver/actors to current test so it can take the screenshots.

**Comment by globalworming** [comment]
Just out of curiosity, why don't you know how many actors you need?

I am pretty sure you problem disappears when you get your actors from a `new OnlineCast() `

**Comment by wakaleo** [comment]
As @globalworming says, try using an `OnlineCast`

**Comment by MHamza-Y** [comment]
> As @globalworming says, try using an `OnlineCast`

I tried this before using managed driver,

```
OnStage.setTheStage(new OnlineCast());
Actor actor = OnStage.theActorCalled("James");
```

I declared this inside a junit rule called `SetTheStage` . In the test I am calling this and some other rules.

```
public SetTheStage stage = new SetTheStage("James");

public LoginToXXXXX login = new LoginToXXXXX();

public NavigationRule navigationRule = new NavigationRule(XXXXXpage.class);

@Rule
public TestRule chain = RuleChain.outerRule(stage).around(login).around(navigationRule);
```

Inside my test script

`givenThat(theActorInTheSpotlight()).wasAbleTo(...);`

The code works fine but no screenshots are recorded in the report with `OnlineCast`

**Comment by MHamza-Y** [comment]
> Just out of curiosity, why don't you know how many actors you need?
> 
> I am pretty sure you problem disappears when you get your actors from a `new OnlineCast() `

My script creates n instances of something. Each Instance have its own IP. I have to open each IP address in the browser and verify something.

**Comment by wakaleo** [comment]
@Rules are going to be outside of the Serenity/Screenplay lifecycle I suspect (they will depend on the JUnit runner). Why not just put this logic in  a @Before method?

**Comment by MHamza-Y** [comment]
> @rules are going to be outside of the Serenity/Screenplay lifecycle I suspect (they will depend on the JUnit runner). Why not just put this logic in a @before method?

This way I can make many reusable rules and chain them up. The advantage would be flexibility. Instead of making separate base classes for each small group of tests with slight setup variations.

**Comment by wakaleo** [comment]
Rules are managed outside the Serenity lifecycle so there is no guarantee that they will work this way.
