### ISSUE TITLE
can't run serenity appium without .apk file

### ISSUE THREAD

**Issue by datnq102** [serenity-bdd/serenity-core#2452]
I get this error: 
"Caused by: net.thucydides.core.webdriver.ThucydidesConfigurationException: The browser under test or path to the app needs to be provided in the appium.app or appium.browserName property."

Here is the appium properties in serenity.conf file:
android {
    ####### Android CAPS ######
    appium.automationName = uiautomator2
    appium.platformName = Android
    appium.platformVersion = 9
    appium.deviceName = randomName
    appium.app = ""
    appium.appPackage = com.example.qa
    appium.appActivity = .MainActivity
    appium.autoGrantPermissions = true
  }

I have tried with appium.app = "", appium.app = , and remove appium.app as well, but still getting an error which says that the path to the app needs to be specified in appium.app.

**Comment by wakaleo** [comment]
"The browser under test or path to the app needs to be provided in the appium.app or appium.browserName property."

**Comment by datnq102** [comment]
Hi @wakaleo, so the answer is that we cannot run Serenity with Appium without the app file, right?

**Comment by wakaleo** [comment]
You need either the appium.app property or the appium.browserName property

**Comment by datnq102** [comment]
I know, it's in the error message. But I just want a confirmation because Appium itself can work fine without the app file if the app is already installed. 
Do you have any plan for Serenity to support running app without app file?

**Comment by wakaleo** [comment]
Appium support is largely community driven. Have you tried just providing the appium.browserName property?

**Comment by datnq102** [comment]
The appium.browserName property is only used for running tests on mobile browsers like Chrome or Safari and not for other apps.

**Comment by wakaleo** [comment]
If you know how to do what you want in Appium, why don't you have a look at the Appium Serenity integration and see if you can come up with a PR?

**Comment by oleg-rd** [comment]
@datnq102, you could give it a try with the next release, which will have https://github.com/serenity-bdd/serenity-core/pull/1156 merged. I think it should address the issue you are seeing, and it should be possible to start a new session without app or browserName props.

**Comment by Jacobvu84** [comment]
@datnq102 It is depended on your configuration. If appium.noReset = true then no need appium.app property.

if appium.noReset = false that means we need to re-install app so the appium will look for the app.apk. otherwises it will launch app only, no need to re-install

I guest

**Comment by datnq102** [comment]
> @datnq102, you could give it a try with the next release, which will have #1156 merged. I think it should address the issue you are seeing, and it should be possible to start a new session without app or browserName props.

Thanks @oleg-rd. I have just tried with latest version - 2.5.0 and it's working.
