### ISSUE TITLE
Incorrect step definition directory path issue Intellij

### ISSUE THREAD

**Issue by Manasr1** [serenity-bdd/serenity-core#2460]
Hi everyone, i try setting up serenity project in Intellij when I try to create a step definition from the feature file(Alt + Enter) i get an error as 'incorrect step definition directory path'  also when i run the runner file I get an error(undefined step reference) -- please help to resolve this issue-runners java class file                                                                                                                                              @RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        plugin = {"pretty", "junit:build/test-results/test/TEST-cucumber.xml"},
        features = {"classpath:features"},
        glue = {"classpath:org.rsi.webservices.steps"},
        dryRun = true,
        snippets = CucumberOptions.SnippetType.CAMELCASE)

My directory structure-
![image](https://user-images.githubusercontent.com/31305121/118644577-94706400-b7fb-11eb-87d3-530bacc8614d.png)

**Comment by wakaleo** [comment]
try glue="org.rsi.webservices.steps"

**Comment by Manasr1** [comment]
Thanks for your response, the issue got resolved, I just updated the IntelliJ IDE. Now my feature file step started linking with the step definition java class.
