### ISSUE TITLE
Reporting in a specific format

### ISSUE THREAD

**Issue by skhandekar1** [serenity-bdd/serenity-core#2466]
I work for a company where  we are required to submit our test results to the FDA. Currently in addition to the serenity reports we are separately writing to an Excel file to create a report that we can submit to FDA. The problem with this approach is that we have a lot of excess code in our testcases (high-level testcases) doing the writing which makes the test look very messy. I want to know if there is a better way to do this using Serenity Reports. The ResultCSV excel file we currently generate for fda submission looks as follows:

![image](https://user-images.githubusercontent.com/82490680/119564072-32fd4780-bd5d-11eb-922d-dabc8fa5794b.png)

I see a results.csv file in the serenity reports folder, but it only contains information for each @Title in the testcase. We have testcases where one test has a number of smaller testcases, the reason being that the tests are so small that we do not want to close and open the app for each testcase. Basically our code is as follows:

```
	@Title("Amplitude increases according to step size")
	@Test
	public void amplitudeUpdatesForOR()
	{		
			log.info("User logins into CP application and creates OR session for the searched patient");
			Section05.setUp();
			
		try {	
				log.info("User will increase and decrease Amplitude according to selected step size");
				Section05.TP397_ID27_ID32();
								
				log.info("User will check the maximum and minimum limit for an Amplitude");
				Section05.TP397_ID11_ID10();
				
				log.info("User will check values are readjustable or not when try to set Amplitude greater than maximum limit by tapping on up arrow");
				Section05.TP397_ID133();
				
				log.info("User will check values are readjustable or not when try to set Amplitude less than minimum limit by tapping on down arrow");
				Section05.TP397_ID134();
				
				log.info("User will check the minimum limit for an Amplitude by entering zero");
				Section05.TP397_ID11();
				
				log.info("User will check stimulation is enabled for valid amplitude value");
				Section05.TP397_ID20();
}
```

The result.csv from serenity Reports folder looks as follows;

![image](https://user-images.githubusercontent.com/82490680/119567947-cfc1e400-bd61-11eb-853a-378f98820723.png)

Is there any way to log the results of each test separately as well as send the result for each? Basically we need the columns to look as the one shown in the first image because that is the way it needs to be submitted to the FDA. Thank you

**Comment by wakaleo** [comment]
Possibly. I would need to understand exactly the format you would need, but I think a custom report should achieve this more easily. Reach out to me directly and we can see.

**Comment by skhandekar1** [comment]
How do I reach out to you directly?

**Comment by skhandekar1** [comment]
Hi, I am really interested in talking with you to see if there is a solution for my problem above. It will greatly reduce all the extra effort in creating a new report. Could you let me know how i can reach you? Thank you
