### ISSUE TITLE
Take Screenshot after a WaitUntil.the(target)

### ISSUE THREAD

**Issue by davidsotelo1505** [serenity-bdd/serenity-core#2467]
Hello community, the problem that I am presenting is that when I perform a waituntil in a step if this function fails because the element does not find it, then it does not take a screenshot to view it in the serenity report. I appreciate if anyone knows how to solve this.
![image](https://user-images.githubusercontent.com/44252132/119577513-67362f80-bd80-11eb-82a9-00f100fea65e.png)

**Comment by globalworming** [comment]
What serenity version are you using? What did you set as screenshot property in your serenity.properties?

**Comment by antuking** [comment]
I'm facing the same issue and here are my configuration and version of Serenity:
> serenity.take.screenshots=FOR_FAILURES

> <serenity.maven.version>2.0.69</serenity.maven.version>

**Comment by globalworming** [comment]
that's probably because Wait throws an AssertionError and no Exception, that's probably hard to change

but you can [take a screenshot whenever you like](https://serenity-bdd.github.io/theserenitybook/latest/screenshot.html#_taking_screenshots_at_any_arbitrary_point_during_a_step) i think

**Comment by antuking** [comment]
@globalworming how to manage the screenshot directory or where does this stuff store? I tried to use this but I can't see any update then.

**Comment by globalworming** [comment]
screenshots are stored in the `target/site/serenity` folder

**Comment by antuking** [comment]
@globalworming , I tried to this stuff and don't see any screenshot anymore with `FOR_FAILURES` config value
![image](https://user-images.githubusercontent.com/19822174/178942665-0d57c4e8-d969-43d1-a471-7ebbf813ad52.png)

**Comment by antuking** [comment]
They are the same @globalworming . No screenshot so far 😢 
![image](https://user-images.githubusercontent.com/19822174/178972823-ce8cc5d0-e227-4280-b4df-dd77fb5d4347.png)
![Screen Shot 2022-07-14 at 18 32 00](https://user-images.githubusercontent.com/19822174/178973381-62585b8c-636b-442a-aabd-45eeb7156f02.png)

**Comment by globalworming** [comment]
are you doing it before the failure? and in a step? it works for me https://github.com/globalworming/serenity-junit-screenplay-starter/commit/939e19e20d03b46fd1f5c50f990b258585db36ac#diff-360833b92bed2311002847ba5c7d96ba0970c7018daddc92b48e4571e133120c
![image](https://user-images.githubusercontent.com/2108984/179048812-5d2a14e7-de56-4818-947b-8ffff55fa0da.png)

**Comment by antuking** [comment]
I still don't see any screenshot into target folder @globalworming . I re-use your `takeScreenShot` Task, but this one doesn't affect after Wait throws AssertError Exception.
![image](https://user-images.githubusercontent.com/19822174/179151483-fac41883-3264-4f21-8882-7b5c4f0603d5.png)
Have any issue with my serenity version? It's too old 🤔

**Comment by globalworming** [comment]
you'd have to do it before the Failure
if a step results in a failure, all further steps are skipped.

**Comment by globalworming** [comment]
unfortunately, after the step fails, the webdriver is marked as suspended, so you cannot easily use it to take screenshot after catching the Error

a workaround may be to not use wait but increase implicit wait temporarily `BrowseTheWeb.as(actor).getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);`

**Comment by antuking** [comment]
@globalworming , hmm I think I should implement a new takeScreenShot method as new approachment. Seems that here is limitation of the built-in serenity library.

**Comment by wakaleo** [comment]
I had a look into this - there was an issue with SilentTasks like WaitUntil disabling screenshots. Screenshots will be enabled in SilentTasks for failures or errors in the next release.
