### ISSUE TITLE
Is there a PageElement class, rather than PageObject?

### ISSUE THREAD

**Issue by john-caleb-phillips** [serenity-bdd/serenity-core#2469]
I am currently working with Serenity using ```PageObject``` and ```ScenarioSteps``` files, not the Screenplay pattern.

In my project I have several reusable elements are appear on various pages.  There are the obvious header, footer, and sidebar objects that lots of sites have, but also a few others that are specific to my project.  I am unsure what class these reusable page elements should inherit from.  I don't want to have them inherit from ```ScenarioSteps```, since they contain no steps.  I also do not want them to inherit from ```PageObject```, since it contains many methods that do not apply to these elements.  Methods such as ```open()``` and ```callWhenPageOpensMethods()``` come to mind.

Is there a class that these reusable elements can inherit from that is lighter than the PageObject class, but semantically different from the ScenarioSteps class?

**Comment by wakaleo** [comment]
Not currently, but it is a good idea and I had in mind adding a class like this in a future version.
