### ISSUE TITLE
multiple csv file used as test data  issue

### ISSUE THREAD

**Issue by tonhauser** [serenity-bdd/serenity-core#247]
Hello guys, 

 I try to use multiple csv files as input data for my test using @UseTestDataFrom annotation. 
 I have issues using it and when checking the code, method 
net.serenitybdd.junit.runners.DataDrivenAnnotations.findTestDataSource()

which is responsible for reading actual files 
returns first path retrieved by file splitter and never gets other ones

thanks a lot for a great product
kind regards
juraj

**Comment by wakaleo** [comment]
This will be fixed in 1.1.32

**Comment by wakaleo** [comment]
Fixed in 1.1.33.

**Comment by pankajshinde1679** [comment]
Guys any help on this reading multiple files through @UseTestDataFrom annotation. I am also facing the same issue.

**Comment by wakaleo** [comment]
There is not enough information to help you; you would need to include the classes you are loading to and the format of the CSV files.

**Comment by pankajshinde1679** [comment]
Thanks John,

The issue got resolved. Only I have to update was the pom.xml file. I updated in with latest version and issue got resolved.
