### ISSUE TITLE
Serenity compatibility with aws farm device

### ISSUE THREAD

**Issue by davidsotelo1505** [serenity-bdd/serenity-core#2473]
Hi, I'm trying to set up a Serenity-Screenplay project on aws farm devices but I can't get it. I do not know if it is because it is not compatible with this framework. 
I appreciate your help

**Comment by ricardorlg-aval** [comment]
I have made a maven and Gradle plugin that allows running serenity-appium tests in device farm, the plugin will create a project, schedule, and wait for run execution then it will download the serenity reports, and the AWS session video.

let me know if u want to use it.

**Comment by davidsotelo1505** [comment]
If I wanted to use it, I would appreciate it very much

**Comment by Jacobvu84** [comment]
@ricardorlg-aval Pls share it with me too. I am looking the solution for this

**Comment by AchalGit7** [comment]
@ricardorlg Please share the plugin. I want to use it too. kind of stuck in serenity AWS
 integration. Thanks in advance

**Comment by ricardorlg** [comment]
Hi all. sure I'm working on the documentation for the plugins, which will be ready today, 

these are the links.  
https://github.com/ricardorlg/aws-device-farm-tractor-maven-plugin
https://github.com/ricardorlg/aws-device-farm-tractor-gradle-plugin

**Comment by prajusg** [comment]
@ricardorlg Could you please share the steps to use the plugin?
