### ISSUE TITLE
Environment details and Driver capabilities don't appear in Serenity Report (serenity.version 2.4.24)

### ISSUE THREAD

**Issue by datgjan** [serenity-bdd/serenity-core#2479]
Hi all,

I'm using serenity version 2.4.24, environment details and Driver capabilities don't appear in Serenity Report
![screencapture-localhost-63342-iboard-ui-automation-target-site-serenity-index-html-2021-06-04-10_53_50](https://user-images.githubusercontent.com/45711231/120743541-69884e80-c523-11eb-877f-afa3131cbb7a.png)

I tried with serenity version 2.4.0, I got  "Failed to generate report for Requirements report capabilities.html in serenity" error message

**Comment by wakaleo** [comment]
Where are you expecting to see these details?

**Comment by datgjan** [comment]
I saw the environment details and Driver capabilities in the Serenity Report when using the old previous version,  you can see them here https://github.com/serenity-bdd/serenity-core/issues/1878. I have tried many ways and researched thoroughly but still can't solve this problem, can you help me?

**Comment by wakaleo** [comment]
Click on the Info icon in the top right corner of the scree n

**Comment by datgjan** [comment]
Many thanks for your support!
