### ISSUE TITLE
No such element after context switch in app hybrid 

### ISSUE THREAD

**Issue by davidsotelo1505** [serenity-bdd/serenity-core#2484]
Hi guys,

I have been having problems when performing automation in a hybrid application, because when I perform the context switch it does not find any element, I send an appium trace to see if you can help me solve it.

here I make the context change
![image](https://user-images.githubusercontent.com/44252132/121398481-06c7f600-c91b-11eb-9bd0-9a63aae19211.png)

after making the change it does not find the element
![image](https://user-images.githubusercontent.com/44252132/121398585-219a6a80-c91b-11eb-986f-b5c2f3fe08ec.png)

**Comment by Jacobvu84** [comment]
Can you give sample code ?

**Comment by ricardorlg** [comment]
why u make a switching context? if ur app is hybrid u can tell appium to assume web context by default,.
