### ISSUE TITLE
serenity-mobile-screenplay: driver is initiated twice

### ISSUE THREAD

**Issue by zuzeac** [serenity-bdd/serenity-core#2485]
Hello, 
I'm trying to build a testing framework based on serenity-mobile-screenplay. Configured everything like in the project. But for some reasons the driver is initiated twice. 
First app will open, then will close and open again.  
The problem: appium has 2 sessions, the 1st one is trying to do things (clicks and so on) but it will fail because the app opened is from the second session.
I'm thinking maybe someone encounter this already and have a solution
Here is the appium log: https://gist.github.com/zuzeac/d61fd71ca5d7824cfab3e2a11cfa8dd7

**Comment by wakaleo** [comment]
Maybe ask this question on Gitter as well, as there are a lot of Appium users there.

**Comment by Jacobvu84** [comment]
@zuzeac are using junit or cucumber ?

**Comment by zuzeac** [comment]
i'm using in runner CucumberWithSerenity.class.
and 
<serenity.version>2.4.34
<serenity.cucumber.version>2.4.34
 <serenity.maven.version>2.4.34

**Comment by Jacobvu84** [comment]
@zuzeac Sorry, my mistake.

if your code is

```
@Managed    
public WebDriver hisMobileDevice;    	

@Before 	
public void jacobCanBrowseTheMobileApp() { OnStage.setTheStage(new OnlineCast()); 	}

@Test    
public void when_launch_application() {  
            givenThat(jacob).can(BrowseTheWeb.with(hisMobileDevice));    	    	 
            givenThat(jacob).attemptsTo(Click.on(ADD_BUTTON));
    }
```

Pls remove this line

```
givenThat(jacob).can(BrowseTheWeb.with(hisMobileDevice));    	
```

It should be

```
@Managed    
public WebDriver hisMobileDevice;    	

@Before 	
public void jacobCanBrowseTheMobileApp() { OnStage.setTheStage(new OnlineCast()); 	}

@Test    
public void when_launch_application() {  	    	 
            givenThat(jacob).attemptsTo(Click.on(ADD_BUTTON));
    }
```

**Comment by Jacobvu84** [comment]
@zuzeac Pls check and close issue

**Comment by zuzeac** [comment]
Thanks @Jacobvu84 that did the trick. Using cucumber is not needed to do  theActorCalled("jacob").can(BrowseTheWeb.with(mobileDevice));
