### ISSUE TITLE
RestReportingHelper is referring to unknown method blacklistedHeaders()

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2488]
Hi there,

I've started implementing a new serenity project for REST API testing from scratch. I'm using serenity version 2.3.12 with the below packages:
```
    testImplementation "net.serenity-bdd:serenity-core:$serenityVersion"
    testImplementation "net.serenity-bdd:serenity-junit:$serenityVersion"
    testImplementation "net.serenity-bdd:serenity-cucumber6:$serenityVersion"
    testImplementation "net.serenity-bdd:serenity-rest-assured:$serenityVersion"
```
When running the test I'm always facing this exception:
```
java.lang.NoSuchMethodError: 'java.util.Set io.restassured.config.LogConfig.blacklistedHeaders()'
	at net.serenitybdd.rest.utils.RestReportingHelper.registerCall(RestReportingHelper.java:69)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.reportQuery(RequestSpecificationDecorated.java:292)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:284)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.get(RequestSpecificationDecorated.java:67)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.get(RequestSpecificationDecorated.java:38)
```
Having a look to the corresponding class _RestReportingHelper_ I can see that the method _blacklistedHeaders()_ cannot be resolved in _LogConfig_ class. This method is not available in rest-assured version 3.1.1 which was coming with serenity 2.3.12. There seems to be a version conflict. The same issue applies to latest serenity version 2.4.34.

Please, help to solve this issue.

Best regards, André

**Comment by wakaleo** [comment]
Looks like a version conflict. Serenity 2.4.x uses a more recent version of RestAssured, so just let it pull in the dependency itself.

**Comment by aybartsch** [comment]
Thanks for your quick answer, John. We have already check the gradle dependencies and we've found a conflict but we've no clue what other plugin or package is responsible for that:

```
\--- net.serenity-bdd:serenity-rest-assured:2.3.12
...
      +--- io.rest-assured:rest-assured:4.3.2 -> 3.1.1
      ...
      +--- io.rest-assured:json-path:3.1.1
     |    |    \--- io.rest-assured:rest-assured-common:3.1.1
     |    \--- io.rest-assured:xml-path:3.1.1
     |         +--- io.rest-assured:rest-assured-common:3.1.1
```
I guess we have to force the rest-assured version in gradle which is not really cool...

**Comment by wakaleo** [comment]
serenity-rest-assured has a dependency on rest-assured 4.x 

You should be able to see where your project is getting rest-assured 3.x from (maybe another library?)

**Comment by aybartsch** [comment]
So far, I was not able to find the library which is requesting the older rest-assured version. Maybe, you could give me hint how to gather this info.

One remark: When using "io.cucumber.core.cli.Main" for the cucumber java runner configuration the newer version is applied and the test is passing. But when using "net.serenitybdd.cucumber.cli.Main" serenity is using the old library.

**Comment by wakaleo** [comment]
net.serenitybdd.cucumber.cli.Main hasn't been supported for a while now, as the IntelliJ APIs have changed.

**Comment by aybartsch** [comment]
Thanks for this update. I will continue searching for the library causing the version conflict...

**Comment by onlybiju** [comment]
Hi @wakaleo,
Looks like Serenity -rest-assured is downloading io.rest-assured 3.3.0, I tried to exclude it but have no success
+- **net.serenity-bdd:serenity-rest-assured:jar:2.4.4**:compile
|  |  +- **io.rest-assured:rest-assured:jar:3.3.0:compile**
|  |  |  +- org.hamcrest:hamcrest-library:jar:2.2:compile
|  |  |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:compile
|  |  |  +- io.rest-assured:json-path:jar:3.3.0:compile

**Comment by wakaleo** [comment]
@onlybiju Serenity needs the version that it needs, and this will vary depending on the version of Serenity you are using. Don't try to override the version or you will get version conflicts. If you want to use a more recent version of Rest Assured, use a more recent version of Serenity.

**Comment by onlybiju** [comment]
Thank you very much @wakaleo , I updated to latest version of serenity 3.0.5 and I am not getting the NoSuchMethodError exception anymore
