### ISSUE TITLE
Illegal char <*> at index 2: (.*)[\/\\]?src[\/\\]test[\/\\]resources[\/\\]serenity.conf

### ISSUE THREAD

**Issue by vovik815** [serenity-bdd/serenity-core#2490]
**Serenity version:** 2.4.20
Error message happends only on Windows (Win 10). Only Linux everything is good.

```
1) [Guice/ErrorInCustomProvider]: InvalidPathException: Illegal char <*> at index 2: (.*)[\/\\]?src[\/\\]test[\/\\]resources[\/\\]serenity.conf
  at ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:77)
  while locating EnvironmentVariables

Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 2: (.*)[\/\\]?src[\/\\]test[\/\\]resources[\/\\]serenity.conf
```

**Comment by wakaleo** [comment]
What is in your serenity.conf file?

**Comment by vovik815** [comment]
`
environments {
  default {
      base.url = "http://localhost:8080"
  }
  dev {
    base.url = "http://dev.env.com"
  }
  sandbox {
	base.url = "http://sandbox.env.com"
  }  
}
`

**Comment by wakaleo** [comment]
Have you tried with the latest version?

**Comment by vovik815** [comment]
Thank you for suggestion. Upgraded to the newest version - 2.4.32. The issue is not reproduced. The ticket can be closed.
