### ISSUE TITLE
Typing mistake

### ISSUE THREAD

**Issue by quyennt44** [serenity-bdd/serenity-core#2491]
I found a typing mistake here. It should be "appeared", right?:
![image (2)](https://user-images.githubusercontent.com/43987470/122702739-39a6ae00-d27a-11eb-81e9-4c8e05fb6bf5.png)

**Comment by globalworming** [comment]
i am pretty sure this is not coming from the serenity source code

**Comment by quyennt44** [comment]
I found out that it's generated from method name. Sorry.
