### ISSUE TITLE
Logging doesn't pick up JavascriptExecutor command.

### ISSUE THREAD

**Issue by sebastiangrigore** [serenity-bdd/serenity-core#2492]
Hello,
I'm trying to pick up the number of DataLayer elements from a page and then loop through them and check their contents.
Using Serenity 2.3.6 with Java. My code:

      `JavascriptExecutor js = (JavascriptExecutor) getDriver();
        js.executeScript("console.clear()");
        js.executeScript("console.log(window.dataLayer.length)");

        LoggingPreferences logPrefs = new LoggingPreferences();
        logPrefs.enable(LogType.BROWSER, Level.ALL);
        DesiredCapabilities desiredCapabilities = DesiredCapabilities.chrome();
        desiredCapabilities.setCapability("goog:loggingPrefs", logPrefs);
        LogEntries log = getDriver().manage().logs().get(LogType.BROWSER);

        String consoleLog = log.getAll().toString();
        String temp = consoleLog.substring(consoleLog.length() - 3);
        String end = temp.substring(0, temp.length() - 1);
        int dataLayerEntries = Integer.parseInt(end);'

     
        The problem is that the logging doesn't pick up the js.executeScript stuff and still returns the console log before the clearing. I've tried adding to serenity.conf and serenity.properties the following 2 pieces of code respectively:

        `webdriver {
    logprefs {
        driver = ALL
        browser = ALL
    }
}'

`chrome.switches=--enable-logging,--v=2,--no-sandbox,--log-level=0
chrome.capabilities.loggingPrefs={"driver":"ALL","browser":"ALL"}`

Any ideas, suggestions?

**Comment by wakaleo** [comment]
Are you expecting Serenity or Selenium to perform this logging?

**Comment by wakaleo** [comment]
Have a look at the AddLoggingPreferences class and see what it is doing differently to the code you would expect.
