### ISSUE TITLE
Can we use serenity-core to test a React Application

### ISSUE THREAD

**Issue by zrieq** [serenity-bdd/serenity-core#2494]
I am not sure if this is the right place to ask this question but please help us to get the answer or guide us where to go.

We have built a test suite with over 3000 test scenarios using serenity-core, serenity-rest-assured and serenity-jbehave, that does almost all of our end-to-end testing for our application, and obviously, **all is written in java.**

Our application right now is using Angular 1.x in the FE (which is dead) and we are planning to do a full re-write for the FE and use ReactJS.

**Our concern is around the effort we have put in building the test suite, is there a way to not lose our test suite? is there a way to interact with the new react application by replacing the PageObject class with something else that can handle react components? or is there any other solution that can help to interact properly with the React Dom instead of the HTML dom ?**

We are looking to re-write only the part related to deal with the page and leave everything as is if possible.

**Comment by wakaleo** [comment]
There's no reason why you can't test a React application with Selenium (and hense Serenity BDD). But you might also want to use Javascript unit tests for the React components themselves (https://reactjs.org/docs/testing.html), to make your test suite faster.
