### ISSUE TITLE
Serenity Run using Cucumber Tags - Serenity Run Console indicates tests for ALL TAGS executed even when Single TAG is executed (Serenity Reports as expected) 

### ISSUE THREAD

**Issue by TarahMo** [serenity-bdd/serenity-core#2496]
Hi John @wakaleo 

Creating the issue here (under serenity-core). I have also shared the project GIT URL in my comment below.

**Problem description:**

I am noticing a strange behavior during build run-time within Serenity Console Run when running Serenity Tests using Cucumber Tags.

I have 6 Scenarios in the Feature File each with different Tags. When I run the project using Maven run configuration for a specific TAG e.g. for "GETSERVICES" TAG (for the highlighted scenario in the attached files), observations highlighted under 1) & 2) below.

1) When the build execution starts - I find it ambiguous looking at the Serenity Run Console as it indicates 6 TESTS Executed & 6 TESTS Passed. I have used log().all() in the REST Assured code which is logging the request & response and I can see ALL 6 API's have been executed.

2) Build is successful (Process finished with exit code 0 & BUILD SUCCESS) and when I look at "Serenity Summary Emailable Report" & "Index.HTML Report" -> as expected, I see ONLY 1 TEST (based on the TAG provided) executed & PASSED.

Therefore I am confused why Serenity Run Console indicates 6 TESTS Executed & 6 TESTS Passed & it actually does and I see GET & POST responses for ALL 6 API's in the console logs.

I have attached a few screen prints for the following files & have attached the Full Console Log as well.

Please can you advise what may be the reason for the above behavior?

Attached screen prints & logs for the following:

i) Serenity Run - Console Logs
ii) Serenity Run Logs
iii) Feature File
iv) Serenity Runner File
v) Maven Run Configuration
vi) Index.html Report
vii) serenity-summary.html (Serenity Summary Emailable Report)
viii) POM.XML Maven Failsafe Plugin
ix) POM.XML (full)

![Feature File](https://user-images.githubusercontent.com/85223433/123294076-258cd600-d532-11eb-9318-17e840a28184.JPG)

![Serenity Runner File](https://user-images.githubusercontent.com/85223433/123294117-2d4c7a80-d532-11eb-96ba-99eb7591f5ac.JPG)

[Serenity Run - Console Logs.txt](https://github.com/serenity-bdd/serenity-rest-starter/files/6710558/Serenity.Run.-.Console.Logs.txt)

[POM XML.txt](https://github.com/serenity-bdd/serenity-rest-starter/files/6710682/POM.XML.txt)

![Serenity Run Logs](https://user-images.githubusercontent.com/85223433/123294183-3d645a00-d532-11eb-9097-75085cd12648.JPG)

![Serenity Summary Emailable Report](https://user-images.githubusercontent.com/85223433/123296856-a2b94a80-d534-11eb-8fff-7ae86cb419a2.JPG)

![Index HTML Report](https://user-images.githubusercontent.com/85223433/123296898-ad73df80-d534-11eb-86cb-61be37b107c6.JPG)

![Maven Run Configuration](https://user-images.githubusercontent.com/85223433/123297270-0f344980-d535-11eb-8600-40385a473c68.JPG)

![POM XML Maven Failsafe Plugin](https://user-images.githubusercontent.com/85223433/123294293-5836ce80-d532-11eb-977b-6e2ef6b3216f.JPG)

**Comment by TarahMo** [comment]
@wakaleo - Creating the issue here (under serenity-core) as you advised. 

GIT Project Clone URL (My Project): https://github.com/TarahMo/Cucumber-with-Serenity-Maven-Project-.git

Please can you verify if this is reproducible at your end.

Many thanks for your continuous support.

**Comment by globalworming** [comment]
Checked out your project, ran with `mvn clean verify -Dcucumber.options="--tags=@GETSERVICES" -Dtags=GETSERVICES`
seems to work like https://serenity-bdd.github.io/theserenitybook/latest/filtering-reports.html#_excluding_unrelated_requirements states, ran 1 test, report contains 1 test

**Comment by TarahMo** [comment]
Thank you Andreas. Using the maven run configuration (additional tag details -Dtags=GETSERVICES) has resolved the issue & excluded tests with other tags. Happy to close this issue.
