### ISSUE TITLE
'serenity.browser.maximized' doesnt maximize the browser in headless mode

### ISSUE THREAD

**Issue by gorakshasabnis** [serenity-bdd/serenity-core#2499]
Hi,

i am using 'serenity.browser.maximized = true' to maximize the browser. However, when I set 'headless.mode = true' in serenity.conf then my test cases are failing; since browser opens in small window and not maximizing it. This us causing few of the pannels on the webpage to stay collapsed due to small window size. If headless mode is false then 1st browser opens in small window and then maximizes.
Can you please help ?

Regards,
Goraksha

**Comment by wakaleo** [comment]
I don't think you can maximise a browser in headless mode in Selenium - maybe try setting the window dimensions explicitly

**Comment by gorakshasabnis** [comment]
Setting dimensions explicitly worked for headless. thanks
