### ISSUE TITLE
aggregate + gradle daemon issue

### ISSUE THREAD

**Issue by eraether** [serenity-bdd/serenity-core#250]
How to reproduce:
gradle clean test aggregate --daemon
This will print multiple java.nio.file.NoSuchFileException: target\site\serenity but will succeed.
Rerun gradle clean test aggregate --daemon
This will print 'Could not find directory ...target\site\serenity' and fail the build.

Why is this happening?
After running the first gradle clean test aggregate --daemon, process explorer reports that the newly created gradle daemon is keeping a lock on the 'target\site\serenity' file handle.

Why is this an issue?
All eclipse+gradle integrations I've encountered use a gradle daemon, so running the clean test aggregate tasks more than once leads to eclipse being unable to generate a serenity report.

**Comment by YamStranger** [comment]
Hello @eraether. Please add to ticket your serenity.properties, and if it is possible try to build some of [these](https://github.com/serenity-bdd/serenity-demos) project and add full stack trance. 

Thanks!!!

**Comment by YamStranger** [comment]
This issue fixed by #252 pull request, now it build executed with `./gradlew clean test aggregate` all work fine. Tested against serenity-test-project.
