### ISSUE TITLE
Asynchronous generating reporting serenity before finishing main method running tests

### ISSUE THREAD

**Issue by Neray92** [serenity-bdd/serenity-core#2500]
Hello,

I'm facing an issue I'm trying to run my test from My cucumberTestSuite

`package starter;

import io.cucumber.core.options.CommandlineOptionsParser;
import io.cucumber.core.options.RuntimeOptions;
import io.cucumber.core.resource.ClassLoaders;
import io.cucumber.core.runtime.Runtime;
import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import net.serenitybdd.cucumber.CucumberWithSerenityRuntime;
import net.serenitybdd.cucumber.cli.Main;
import net.thucydides.core.reports.html.HtmlAggregateStoryReporter;
import org.junit.AfterClass;
import org.junit.runner.RunWith;

import java.io.File;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        plugin = {"pretty"},
        features = "src/main/resources/features"
)
public class CucumberTestSuite {

     public static void main(String[] args) throws Throwable {

         Main.main(new String[]{"src/main/resources/features", "-g", "starter"});

         HtmlAggregateStoryReporter reporter = new HtmlAggregateStoryReporter("toto");
         File sourceDirectory = new File("/Users/rchougar001/Downloads/automation_tw/target/site/serenity");
         File outputDirectory = new File("/Users/rchougar001/Downloads/automation_tw/target/site/serenity");
         reporter.setSourceDirectory(sourceDirectory);
         reporter.setOutputDirectory(outputDirectory);
         reporter.generateReportsForTestResultsFrom(reporter.getSourceDirectory());
     }

}
`

My tests are running but my reporting is empty after searching the issue it seems like the  generating of the report is asynchronous to the running of the tests.

If someone know how to let the test finish and run the reporting generation

**Comment by wakaleo** [comment]
Why do you have a main() method in your test suite? What problem are you trying to solve?

**Comment by Neray92** [comment]
Hi @wakaleo thank's for your quick reply
I  have to put my test suit in a CI CD Chain and it will run into a container like an application 
 My  docker entry point must launch the application through a main, as we do with a "classic" java application

**Comment by wakaleo** [comment]
Reports are generated asynchronously in a separate thread. I'm not sure how you would make this work - it's not a very common scenario; the Serenity tests expect to be run using a build tool like Maven or Gradle.
