### ISSUE TITLE
How take screenshot with serenity bdd and playwright together

### ISSUE THREAD

**Issue by alexihrndz** [serenity-bdd/serenity-core#2502]
Hello, please help me... I trying build a project with Serenity Screenplay without Selenium

I use interactions of playwright (net.serenitybdd.screenplay.playwright.interactions), but i can´t take screenshots into tasks with commons properties like:

serenity.take.screenshot = BEFORE_AND_AFTER_EACH_STEP

Here I leave the code for if you can take a look at it

https://github.com/alexihrndz/PruebasPlaywright.git

**Comment by wakaleo** [comment]
serenity-screenplay-playwrite is an experimental library that is still work-in-progress. The screenshot component has not yet been implemented.

**Comment by pogodins** [comment]
Screenshots for Playwright will be working after #2652.
@wakaleo can we than say that this issue is fixed?

**Comment by wakaleo** [comment]
Fixed in 3.2.0

**Comment by mabdulkadar** [comment]
Hi @pogodins  - I am not using screenplay in my project. Using version 3.7.1. Can you please help me to get screenshot in the report. My last blocker is, screenshot missing.

**Comment by madhvirangaswamy** [comment]
Serenity supports screenshots inside the report index.html but when i'm using playwright it doesn't contain any screenshots generated for each steps even though serenity-screenplay-playwrite  is used
