### ISSUE TITLE
stepStarted() log formatting

### ISSUE THREAD

**Issue by AshirovaK** [serenity-bdd/serenity-core#2503]
https://github.com/serenity-bdd/serenity-core/blob/fe4acd62cd8893557f01f76170046ac9f21c7483/serenity-model/src/main/java/net/thucydides/core/logging/ConsoleLoggingListener.java#L280-L282

Since serenity-core 4.2.22 version stepStarted() method starts using System.out.println() instead getLogger().
Can you please return using of getLogger() for stepStarted()?

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by AshirovaK** [comment]
> Can you propose a PR?

I cant push 
```
remote:` Permission to serenity-bdd/serenity-core.git denied to AshirovaK.
fatal: unable to access 'https://github.com/serenity-bdd/serenity-core.git/': The requested URL returned error: 403
```

**Comment by wakaleo** [comment]
You need to raise a pull request: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
