### ISSUE TITLE
Chrome failed to start while running my test in docker container

### ISSUE THREAD

**Issue by Neray92** [serenity-bdd/serenity-core#2506]
Hi
I'm trying to run my test suite by a dockerfile.
I'm able to launch my test suite by using `mvn clean verify` but I'm facing an issue, all my test fails with this log:

7006.335][SEVERE]: bind() failed: Cannot assign requested address (99)

Here is my dockerfile 

`FROM openjdk:11-jdk

RUN apt-get update && apt-get install -y libnss3-tools libxcb1 chromium maven

COPY ./src automation_tw/src

COPY ./target/test-classes automation_tw/target/test-classes

COPY ./target/lib   ~/.m2/repository

COPY ./serenity.properties automation_tw/

COPY ./pom.xml automation_tw/

ENTRYPOINT ["mvn","verify"]`

And here is my serenity.conf 

`webdriver {
  driver = chrome
  autodownload = true
  automatic.driver.download = true
  webdriver.chrome.driver = "src/test/drivers/mac/chromedriver"
  webdriver.remote.driver= chrome
  webdriver.remote.url= "http://localhost:4444/wd/hub"
  webdriver.remote.os=LINUX
  timeouts {
    implicitlywait = 10000
        fluentwait = 10000
  }
}
drivers {
  windows {
    webdriver.chrome.driver = src/test/drivers/windows/chromedriver.exe
  }
  mac {
    webdriver.chrome.driver = src/test/drivers/mac/chromedriver
  }
  linux {
    webdriver.chrome.driver = src/test/drivers/linux/chromedriver
  }
}
headless.mode = true

serenity {
    serenity.console.colors = true
    take.screenshots = FOR_FAILURES
}

}
chrome.switches = """--start-maximized;--test-type;--no-sandbox;--ignore-certificate-errors;--verbose;
                   --disable-popup-blocking;--disable-dev-shm-usage;--whitelisted-ips;--disable-default-apps;--disable-extensions-file-access-check;
                   ;--disable-infobars,--disable-gpu"""
`

I've added some chrome properties like --whitelisted-ips or disable-dev-shm-usage because some of them have worked for somebody who faced the same issue but noting for me.

Thank's for reply if someone have faced the same issue

**Comment by wakaleo** [comment]
"bind() failed: Cannot assign requested address (99)" looks like a Docker-related issue, have you asked the Docker community?

**Comment by globalworming** [comment]
I am confused.. Are you sure it's using the chromedriver executable and not the configured selenium grid url?

**Comment by Neray92** [comment]
> I am confused.. Are you sure it's using the chromedriver executable and not the configured selenium grid url?

He is using the webdriver which is downloaded

14:10:11.785 [pool-2-thread-1] INFO  i.c.core.plugin.SerenityReporter - Running feature from file:///automation_tw/src/test/resources/features/features/LoginAs.feature
14:10:11.790 [pool-2-thread-1] INFO  n.s.c.w.d.ChromeDriverProvider - Using automatically driver download
14:10:11.951 [pool-2-thread-1] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.cache/selenium/chromedriver/linux64/91.0.4472.101/chromedriver
14:10:12.086 [pool-2-thread-1] INFO  n.s.c.w.d.ProvideNewDriver - Instantiating driver
14:10:12.086 [pool-2-thread-1] INFO  n.s.c.w.d.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: false, browserName: chrome, chrome.switches: --start-maximized;--test-ty..., goog:chromeOptions: {args: [--start-maximized, --test-type, --no-sandbox, --ignore-certificate-errors, --verbose;\n, --disable-popup-blocking, --disable-dev-shm-usage, --whitelisted-ips, --disable-default-apps, --disable-extensions-file-a..., --disable-infobars, --disable-gpu, --headless], extensions: []}, loggingPrefs: org.openqa.selenium.logging...}
Starting ChromeDriver 91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}) on port 2168
Only local connections are allowed.

**Comment by globalworming** [comment]
This is all a bit confusing. I would suggest running a selenium grid and not bother with browsers and drivers. See https://github.com/SeleniumHQ/docker-selenium#quick-start
