### ISSUE TITLE
Tests with Serenity version 2.4.44 run significantly slower than with 2.4.4

### ISSUE THREAD

**Issue by SchnuckySchuster** [serenity-bdd/serenity-core#2507]
I test a page that is quite long. 

When running the tests with version 2.4.44 each page gets visibly scrolled down in several increments every time something is done on that page. The scrolling is quite slow.

The configuration that shows this behaviour is
- Serenity version **2.4.44**  plus  **serenity.full.page.screenshot.strategy = true**

Following configuration does **not** show this behaviour
- Serenity version 2.2.44  plus  serenity.full.page.screenshot.strategy = false
- Serenity version 2.2.4    plus  serenity.full.page.screenshot.strategy = true or false

**Comment by wakaleo** [comment]
Hmmm, that doesn't sound like something that Serenity would do explicitly, but we switched to using shutterbug a while back (don't recall when). Try with `serenity.screenshot.strategy=VIEWPORT`.

**Comment by SchnuckySchuster** [comment]
With the setting serenity.screenshot.strategy=VIEWPORT the screenshot only shows a small part of the page.
It looks like the setting VIEWPORT is equivalent to false

I'd like to see the entire page in the screenshot.

For the time being I will downgrade to 2.4.4 as I don't need anything from 2.4.44

Later on I could use the following work arround
- while developing the tests I don't make the full page screenshots and the tests run fast
- when running at night in the pipeline I use the headless mode and there it might not hurt when the scrolling occurs

**Comment by wakaleo** [comment]
Did you get full screenshots in 2.4.4 (ie. before we integrated with shutterbug?). The idea of introducing shutterbug was to add support for full screenshots on all browsers.

**Comment by SchnuckySchuster** [comment]
I do get full screenshots in **2.4.4** with the setting **serenity.full.page.screenshot.strategy = true**

**Comment by wakaleo** [comment]
Can you see if 2.4.4 is using shutterbug?

**Comment by SchnuckySchuster** [comment]
Sure, how do I do that?

**Comment by wakaleo** [comment]
The change in versions is from shutterbug 0.9.5 to 1.5, where they changed the implementation of the scrolling logic. Scrolling to get the full picture seems to be always slow; try setting serenity.screenshot.strategy to one of these values:
  - VIEWPORT: capture visible part of the viewport only
  - FULL: full page screenshot using devtools
  - FULL_SCROLL: full page screenshot using scroll & stitch method
  - VERTICAL_SCROLL:vertical scroll page screenshot using scroll & stitch method
  - HORIZONTAL_SCROLL: horizontal scroll page screenshot using scroll & stitch method

**Comment by wakaleo** [comment]
I might have a fix that changes the default behaviour for `serenity.full.page.screenshot.strategy = true` - could you try with `serenity.screenshot.strategy = FULL` ?

**Comment by SchnuckySchuster** [comment]
Using the parameter FULL the page does not scroll on Firefox but the screenshot does not show the full page either, only the viewport.

I think that most people test on Chrome, Firefox and Safari.
I can not speak for Safari but Chrome and Firefox are better of with shutterbug 0.9.5

**Comment by wakaleo** [comment]
OK, looks like shutterbug > 0.9.5 is a bit rubbish. I'll retrograde to the previous version

**Comment by wakaleo** [comment]
Before I do that, could you confirm that the performance degradation happens in the next version after 2.4.4?

**Comment by SchnuckySchuster** [comment]
I assume that the next working version after 2.4.4 is 2.4.42 (2.2.41 artefacts could no be downloaded)
I can say the the degradation happens in version 2.4.42.

**Comment by wakaleo** [comment]
The version after 2.4.4 is 2.4.5, then it goes to 2.4.15

**Comment by wakaleo** [comment]
![image](https://user-images.githubusercontent.com/55986/125051961-62f97380-e09b-11eb-8ef2-464d528e8843.png)

**Comment by SchnuckySchuster** [comment]
Ups, seem that I did not understand how version numbers work
With version 2.4.5 aggregate does not work
<img width="831" alt="image" src="https://user-images.githubusercontent.com/3406054/125053388-54b05500-e0a5-11eb-8958-ee3278ad5466.png">

**Comment by wakaleo** [comment]
And with 2.4.15?

**Comment by SchnuckySchuster** [comment]
same thing.
I use following settings
<img width="662" alt="image" src="https://user-images.githubusercontent.com/3406054/125053740-c12b5400-e0a5-11eb-96ca-1640693436f6.png">
Is that correct?
It seems like there is no serenity.cucumber.version=2.4.15
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/3406054/125053984-fdf74b00-e0a5-11eb-97da-b3990f327744.png">

**Comment by SchnuckySchuster** [comment]
The test are coded using ScreenPlay

**Comment by SchnuckySchuster** [comment]
Version 2.4.21 works fine. Aggreagate creates a report and the scrolling problem is visible.

**Comment by wakaleo** [comment]
So it is the shutterbug upgrade that caused the issue.

**Comment by SchnuckySchuster** [comment]
I need to correct my self.
With versions 2.4.5, 2.4.15, 2.4.20 my tests do not run because of:
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/3406054/125055137-321f3b80-e0a7-11eb-99c5-807ecf7586d9.png">

The tests run wit version 2.4.21

**Comment by wakaleo** [comment]
I need to know the earliest version where you see the performance issue.

**Comment by SchnuckySchuster** [comment]
The earliest version where I see the problem is 2.4.21 
as 2.4.5, 2.4.15 and 2.4.20 do crash with the message above and i can not say whether there is the problem or not.
With 2..4.5, 2.4.15 and 2.4.20 the browser does not open at all

**Comment by wakaleo** [comment]
Try with 2.4.48: see https://serenity-bdd.github.io/theserenitybook/2.4.48/web-testing-in-serenity.html#_taking_screenshots

**Comment by SchnuckySchuster** [comment]
With this setting in the pom.xml
<img width="693" alt="image" src="https://user-images.githubusercontent.com/3406054/125239857-903b6100-e2e9-11eb-8b6d-a25f25a271a6.png">

I get following error
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/3406054/125239934-aba66c00-e2e9-11eb-9458-78d6b0a6a42b.png">

When setting the version
<img width="454" alt="image" src="https://user-images.githubusercontent.com/3406054/125240006-ca0c6780-e2e9-11eb-9496-c21b84b8343a.png">

I get following error
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/3406054/125240088-ed371700-e2e9-11eb-9644-acd981517a7e.png">

I'm behind a proxy but downloading things usually works

**Comment by wakaleo** [comment]
You'll need version 2.4.48 for all of these

**Comment by SchnuckySchuster** [comment]
Thank you for your patience with me.
When using the version number 2.4.48
there is no difference in the way the screenshots are taken between

shutterbug.scrollstrategy=WHOLE_PAGE
and 
shutterbug.scrollstrategy=WHOLE_PAGE_SCROLL_AND_STITCH
and 
shutterbug.scrollstrategy=VIEW_PORT

all do scroll painfully slow, all take the full screenshot

What is your standard setting for
serenity.screenshooter = shutterbug
Even when I have no shutterbug.scrollstrategy=... setting in my conf file at all it does scroll painfully slow and takes the whole page as picture.

I copied and pasted the settings from the manual, so I doubt that I made a typo.

**Comment by SchnuckySchuster** [comment]
> You'll need version 2.4.48 for all of these

You could mention the version field in the manual as you do it in other cases
<img width="889" alt="image" src="https://user-images.githubusercontent.com/3406054/125280427-52543200-e315-11eb-9fa9-7106872cdee4.png">

**Comment by wakaleo** [comment]
I can't reproduce this at all - can you dig into the code to try to identify what the cause of the issue is, and propose a PR? I refactored the screenshot logic to make this easier to do.

**Comment by wakaleo** [comment]
Also, please feel free to propose improvements to the docs as PRs as well.

**Comment by wakaleo** [comment]
Note that serenity does not handle the scrolling - that is 100% shutterbug. Try with different screenshot implementations (including the basic webdriver one) and/or implement your own to see what changes improve things. The serenity-screenshot library uses the old shutterbug library, so should be identical to the older version of Serenity.

**Comment by SchnuckySchuster** [comment]
Ok, thanks. I will create a simple example that I can share.
Who knows what mistake I made.
I hope to find time this week. Can you leave this issue open until then?

**Comment by SchnuckySchuster** [comment]
John, you can close this bug. I will raise another one when I find the time to public a project for bug reproduction
