### ISSUE TITLE
Serenity chromedriver capabilities are not working with BeforeAWebdriverScenario, but working with chrome.switches.

### ISSUE THREAD

**Issue by tiwari90** [serenity-bdd/serenity-core#2513]
created a sample repo with the same issue.
https://github.com/tiwari90/SerenityCapabilityIssue.git

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by tiwari90** [comment]
@wakaleo Is this a known issue?

**Comment by wakaleo** [comment]
No. I'd recommend putting a breakpoint and seeing what the code is doing behind the scenes.

**Comment by tiwari90** [comment]
I tried and observed that Serenity is reading and setting all the capabilities in the background, also printing it on the console as well, during execution. But still, it's not applying.

**Comment by wakaleo** [comment]
Have a look at the ChromeDriverProvider class - that is where the new ChromeDriver instance is created.

**Comment by tiwari90** [comment]
WebDriver newDriver = ProvideNewDriver.withConfiguration(environmentVariables,
                enhancedCapabilities,
                driverServicePool,
                DriverServicePool::newDriver,
                (pool, capabilities) -> new ChromeDriver(enhancedChromeOptions)
        );

Below is the value passed for **enhancedChromeOptions** variable:

Capabilities {acceptInsecureCerts: false, acceptSslCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-gpu, --start-maximized, use-fake-device-for-media-s..., use-fake-ui-for-media-stream], extensions: [], prefs: {download.default_directory: C:\Users\Ashish\git\qa-te..., download.prompt_for_download: false, plugins.always_open_pdf_externally: true, plugins.plugins_disabled: [Adobe Flash Player], profile.default_content_settings.popups: 0}}, loggingPrefs: org.openqa.selenium.logging..., platform: ANY, version: }

I personally don't see any issue with this.
Can you please have a look once?

**Comment by wakaleo** [comment]
If you can update your sample project so that it runs in all environments (no tests currently run when you run mvn verify) and reproduces the issue, it will be easier for folk to pick it up and see if anything is amiss.

**Comment by tiwari90** [comment]
Done,
Added sample test class in pom.xml

**Comment by wakaleo** [comment]
Your sample project only works on Windows.

**Comment by tiwari90** [comment]
Added driver for Linux and Mac as well

**Comment by tiwari90** [comment]
@wakaleo did you get a chance to look into it?

**Comment by wakaleo** [comment]
Is it urgent? Is it something you need for your work?

**Comment by tiwari90** [comment]
not that urgent, as chrome.switches, are already there as a workaround.

**Comment by tiwari90** [comment]
In addition to the above issue, I have observed one more scenario breaking, which can be related to this issue.
If we are using comma-separated arguments for chrome.switches, it's not working.

Example:
If I use chrome.switches=start-maximized, it works fine browser open maximized.
But
If I use chrome.switches=start-maximized,use-fake-device-for-media-stream,use-fake-ui-for-media-stream, it didn't work as expected. None arguments applied for chrome, not even start-maximized.

**Comment by tiwari90** [comment]
@wakaleo Did you get a chance to look into it?

**Comment by wakaleo** [comment]
No

**Comment by ravibabu1408** [comment]
Hi all, Currently i am running serenity bdd tests with browser stack, looks like the tests are running on browserstack but not being taking browser capabilities, can anyone please help me whats the wrong here?
capabilities {
    browserName = "Firefox"
    #
    # Any BrowserStack-specific options go in the 'bstack:options' section
    #
    "bstack:options" {
      os = "Windows"
      osVersion = "11"
      browserVersion = "107.0"
      local = false
      resolution = "1920x1200"
      #seleniumVersion = "4.6.0"
      video = true
      idleTimeout = 300
      buildName= "browserstack-build-1"
      #browserstack.networkLogs=true
      #browserstack.consoleLogs=errors
      debug= true
      consoleLogs=errors
    }
