### ISSUE TITLE
How to use spring-data-jpa together with Serenity BDD?

### ISSUE THREAD

**Issue by kedziorm** [serenity-bdd/serenity-core#2515]
I want to use spring-data-jpa to obtain test data directly from the database. 

How can I find which version of `spring-data-jpa` is compatible with the latest Serenity BDD? 
I see that serenity core contains project `serenity-spring`, but I can't find any table with compatible version.

**Comment by globalworming** [comment]
What did you try? Last time i tried https://serenity-bdd.github.io/theserenitybook/latest/spring.html it was just working as expected. I can share a few example github repositories if you like? Never used jpa in them but.. it should just work allright

**Comment by kedziorm** [comment]
I am using in my code JPA repositories to query objects from database, like:

```
public interface AccountRepository extends JpaRepository<Account, Long> { … }
```

(example copied from https://spring.io/blog/2011/02/10/getting-started-with-spring-data-jpa)

When I execute my code with latest Spring Data JPA and latest Serenity BDD, 
it throws ClassCastException: class com.sun.proxy.$Proxy90 cannot be cast to class javax.persistence.EntityManagerFactory
