### ISSUE TITLE
clarify how to report selenium actions

### ISSUE THREAD

**Issue by sparkoasis** [serenity-bdd/serenity-core#2516]
Hi

Type: clarification

Please, clarify how to ensure that selenium actions (click, enter text, however, etc) are getting written explictly to the report or at least to the console.

Context project: screenplay todomvc example project

serenity.properties
serenity.reports.show.step.details=true
serenity.verbose.steps=true
serenity.full.page.screenshot.strategy=WHOLE_PAGE
serenity.verbose.screenshots=true
serenity.logging=VERBOSE
verbose.reporting=true
serenity.verbose.reporting=true

At this moment above settings do not ensure that selenium actions are logged (similarly to the technical actions the rest project starter does).

Thank you!

**Comment by wakaleo** [comment]
You need to use the Screebplay pattern to get this level of reporting.

**Comment by sparkoasis** [comment]
Thank you for your prompt reply in weekend. ❤️ 

Just in case, the project i have mentioned is this one - https://github.com/serenity-bdd/screenplay-pattern-todomvc
and the command i use to start it is:
`mvn clean verify ` 

Really i was assuming it's already based on screenplay pattern. :)

I'll re-check if the screenplay pattern is really used in the above project and get back with confirmation.

> You need to use the Screenplay pattern to get this level of reporting.

**Comment by sparkoasis** [comment]
> Thank you for your prompt reply in weekend. ❤️
> 
> Just in case, the project i have mentioned is this one - https://github.com/serenity-bdd/screenplay-pattern-todomvc
> and the command i use to start it is:
> `mvn clean verify `
> 
> Really i was assuming it's already based on screenplay pattern. :)
> 
> I'll re-check if the screenplay pattern is really used in the above project and get back with confirmation.
> 
> > You need to use the Screenplay pattern to get this level of reporting.

steps to reproduce:
1. checkout 'https://github.com/serenity-bdd/screenplay-pattern-todomvc' project with changeid - 45c26b3
2. execute using screenplay pattern parameter:

`mvn clean verify -Pscreenplay`
3. check the report & console logs for technical evidence from the Selenium webfacade

Expected result: selenium click, actions with locators are included in the report or/and console

Actual result: no tech evidence

below are the screenshots:
![image](https://user-images.githubusercontent.com/81381189/126910113-cfed0236-9357-40aa-af52-f645b0e6990f.png)

**Comment by wakaleo** [comment]
Not all of the tests run with Screenplay - the ones that do will document the tasks down to the UI Interactions:
![image](https://user-images.githubusercontent.com/55986/126910599-17e7968b-851c-410c-8574-6888a2aca9f4.png)

For Screenplay tasks, you don't need to do anything special, but `serenity.logging=verbose` will also write the task hierarchy to the console:
![image](https://user-images.githubusercontent.com/55986/126910701-dbe73c58-4243-4c87-b3e1-90810317bba0.png)

(Make sure you are using version 2.4.51 for the console output)
