### ISSUE TITLE
Needs to log Console Log At Info Level

### ISSUE THREAD

**Issue by TalatiShirish** [serenity-bdd/serenity-core#2519]
Hi Team,

I would like to log browser console log at info level.
So far I have used 
List<LogEntry> logs=getDriver().manage.logs().get(LogType.BROWSER).getAll();

But this only gets the log at WARNING and SEVER level logs.

Any document link or demo of the project or tips please.

I can see in the browser console logs ,,
![image](https://user-images.githubusercontent.com/18418921/127145495-8a0a59e3-734d-4bc5-8f2f-9a3bb70a44fb.png)
 but not able to captrue by the above steps.

**Comment by globalworming** [comment]
i some time ago had something like 

```java
private void waitAssertAndPrintErrorLogs() {
    new CurrentPage().waitFor(5).seconds();
    List<LogEntry> logEntries = new SevereConsoleLogs().answeredBy(newUser);
    then(newUser).should("there should be no error logs in the console" ,
        eventually(seeThat(actor -> logEntries, List::isEmpty)).orComplainWith(
            AssertionError.class, "severe logs:\n" + logEntries.stream()
            .map(entry -> entry.toString() + "\n")
            .collect(Collectors.joining())
    ));
  }
```
with

```java
public class SevereConsoleLogs extends QuestionWithDefaultSubject<List<LogEntry>> {
  @Override
  public List<LogEntry> answeredBy(Actor actor) {
    if (BrowseTheWeb.as(actor).getDriver().manage().logs().getAvailableLogTypes() == null) {
      // means a previous step by the actor already failed
      return Collections.emptyList();
    }

    return BrowseTheWeb.as(actor).getDriver().manage().logs().get(LogType.BROWSER).getAll().stream()
            .filter(e -> e.getLevel().equals(Level.SEVERE)).collect(Collectors.toList());
  }
}
```

changing that `Level.SEVERE` to `Level.INFO` should work. Maybe check https://stackoverflow.com/a/25431419/1359903 regarding setting up the driver

**Comment by TalatiShirish** [comment]
Hi, Thanks for reply. I did try that but still I am only getting the SEVERE and WARNING LEVEL logs only.
