### ISSUE TITLE
Problems bumping serenity version to 2.5.5

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2525]
Hi there,

today, I'd like to update our serenity testing project to version 2.5.5. Unfortunately, the serenity-cucumber6 plugin is just available upto version 2.4.51. Will this plugin be available for version 2.5.5 soon or do I have to install another one?

To get a better inside I was searching for a release note of the present versions but could not find any. Could you please provide a link to release notes or changelog?

Thanks and best regards, André

**Comment by wakaleo** [comment]
serenity-cucumber6 is a separate project on a separate lifecycle: while we try to keep them in sync it is not always the case and subject to best efforts. The best place to find the latest fully released versions is here: https://github.com/serenity-bdd/serenity-core#serenity-with-junit. The best place for the changelog is in the commit history.

**Comment by aybartsch** [comment]
Thanks, John.

Would you suggest to update to serenity 2.5.5 and combine with serenity-cucumber6 2.4.51?

**Comment by wakaleo** [comment]
Best to wait till I add the versions to the reader after I have tested them.

**Comment by aybartsch** [comment]
Meanwhile, I was running the above combination and it's working well. Moreover, it seems that the serenity version 2.5.5 is remarkable faster than 2.3.12 I have used before.

Thanks for your ongoing support. :)
