### ISSUE TITLE
Unable to capture browser url in serenity report

### ISSUE THREAD

**Issue by prat23k** [serenity-bdd/serenity-core#2532]
When I provide following property its not including the browser url, can anyone correct me if I am using wrong property

serenity.full.page.screenshot.strategy=true

Thanks

**Comment by globalworming** [comment]
This takes a screenshot of the browsers viewport, not the whole window with url bar. You can log the url with Serenity.recordReportData()...

**Comment by prat23k** [comment]
Thank you so much, so do I need to update to each and every step to print url or is there any better way for the global change rather than changing each and every step

**Comment by prat23k** [comment]
thank you so much its working
