### ISSUE TITLE
Issue while invoking serenity test at VM(RDC)(Browser Chrome, firefox, IE not getting launched)

### ISSUE THREAD

**Issue by ajaykumardhaka** [serenity-bdd/serenity-core#2533]
Hi,
i am running a basic www.google.com launch test. however my browser is not getting launched. Same code is working fine at local machine. And it's not working on VM(RDC). All proxy setting is fine for chrome, gradle. I tried with almost all serenity versions old and new. Still getting issue.
Attaching error logs. Could you please look and give a reply. Also i tried with chrome binary which is compatible to my chrome browser version 92.
This is the github URL of project which i am trying.
**https://github.com/naveenanimation20/SerenityWithWebDriverJunit**
[error logs.txt](https://github.com/serenity-bdd/serenity-core/files/7015959/error.logs.txt)

**Comment by wakaleo** [comment]
Try using the latest version of Serenity and removing the driver configurations.

**Comment by ajaykumardhaka** [comment]
Hi John,
Thanks for the response. I just tried with all serenity latest version ie 2.5.8. the issue is still same. 
The main thing here is that browser is getting launched at local system. Issue is at VM (RDC). Also when I use Normal selenium bdd, then browser launches successfully. This looks like serenity issue. Could you please check and confirm. I am trying from last 2 days. And issue is same from very 1st day.

**Comment by wakaleo** [comment]
Commit your latest code and I might be able to take a look when I get back from holidays

**Comment by ajaykumardhaka** [comment]
Hi John.
The below is github URL of project which i tried on VM. Also could you please check error log file once which i shared. As per my research, it's looks like some HTTP client 5 related issue. 
**https://github.com/naveenanimation20/SerenityWithWebDriverJunit**
[error logs.txt](https://github.com/serenity-bdd/serenity-core/files/7022485/error.logs.txt)

**Comment by wakaleo** [comment]
Try removing the references to the driver binaries in the serenity.Conf file and updating to the latest version of Serenity. I see no binaries in your repo so I don't know how this could work on a build server.

**Comment by ajaykumardhaka** [comment]
Hi John. I have used latest version of serenity that is 2.5.8 and also used latest driver binaries that is version 92 for chrome. This GitHub is having old serenity version but I am using latest one. And I am trying to run on RDC machine locally not remotely. Also please check my error log file which u shared in last comment.

**Comment by ajaykumardhaka** [comment]
I would request you please check the error log file which j shared. I hope you will able to find the root cause.

**Comment by wakaleo** [comment]
If the browser is not launching, it's usually a driver issue or a driver configuration issue, especially if the tests run locally. Like I said, try dropping the driver configuration sections and using the automated driver download feature of Serenity. Otherwise, it could be a configuration issue on the machine you are running the tests on.

**Comment by wakaleo** [comment]
I can't read the log file on my phone.

**Comment by ajaykumardhaka** [comment]
I tried after dropping driver configuration section as well. But issue still exist. 
Please let me know how can I show you the logs.
![Uploading IMG_20210820_204435.jpg…]()

**Comment by ajaykumardhaka** [comment]
I have again shared an image of error.if you can see that. Or let me know how can I share the logs

**Comment by ajaykumardhaka** [comment]
I am really excited to use the serenity. As this framework has lot of inbuilt features. Please once look into this issue. It will be a great help for me.
Thanks

**Comment by wakaleo** [comment]
It's not related to Serenity, it looks like the machine you are running the tests on can't access the network addresses it needs to:

https://chromedriver.storage.googleapis.com:443

**Comment by wakaleo** [comment]
So it looks like a configuration issue with your RDC

**Comment by wakaleo** [comment]
Try setting the webdri er.autodownload property to false.

**Comment by ajaykumardhaka** [comment]
Hey John...thanks thanks a big thanks to you .yes this worked for me .I set the autodownload to false .and that worked. I really appreciate for your time

**Comment by ajaykumardhaka** [comment]
Salute you John for your valuable time🙏
