### ISSUE TITLE
Serenity Encoding properties not used when building index.html file

### ISSUE THREAD

**Issue by dwursteisen** [serenity-bdd/serenity-core#254]
This a an issue when using serenity with the maven plugins.
But The issue is in the serenity-core module used by the maven plugin.

![issue](https://github.com/dwursteisen/serenity-bug-report/raw/encoding-reporting-fix/screenshot.PNG)

Related to https://github.com/serenity-bdd/serenity-maven-plugin/issues/16

**Comment by YamStranger** [comment]
Hello @dwursteisen. Thanks for this issue!

It seems that this issue about execution tests in not standard encoding.  Executing them in UTF-8 will help you avoid some problems. 

However all string should be encoded to report-default encoding (json-reports to system-dependent, html-reports to UTF-8). I think that generation HTML reports not in UTF-8 format it is bad idea, as well as json reports. Do you have some business case where you should use HTML reports with not UTF-8 format?

**Comment by YamStranger** [comment]
copy one comment 

>Our feature file is in UTF-8. If serenity use the default system encoding, Serenity won't ever be able to render the name of the feature. And, because the link is generated from the name, cliking on the name lead to a file not found.

**Comment by YamStranger** [comment]
Updated, fix will be available in next release
