### ISSUE TITLE
Mismatch between number of scenarios when running parallel tests with tag filter

### ISSUE THREAD

**Issue by KurumiXenar** [serenity-bdd/serenity-core#2548]
Hi, I'm using intellij with maven on this personal test project. I am using serenity-cucumber-6 for the tests scenarios.

When I try to run the tests in parallel with a batch count of 2 and applying a tag filter, serenity tells me this:
**There is a mismatch between the number of scenarios included in this test run ({}) and the expected number of scenarios loaded ({}). This suggests that the scenario filtering is not working correctly or feature file(s) of an unexpected structure are being run"**

I have tried using the mvn clean verify with flags method:
**mvn clean verify -Dmode="parallel" -Dserenity.batch.count=2 -Dserenity.batch.number=2 -Dcucumber.filter.tags=@1234**

And I have tried using the run/debug configurator to execute the runner directly as well:
**-ea -Dmode="parallel" -Dserenity.batch.count=2 -Dserenity.batch.number=2 -Dcucumber.filter.tags=@test1234**

I have tried changing the batch number and batch count to no avail as well.
Is there a possible fix for this or am I doing something wrong? Thank you.

**Comment by wakaleo** [comment]
@nbarrett might be able to cast more light, but are you trying to run your tests in parallel on a single machine using the batch configuration?

**Comment by KurumiXenar** [comment]
Hi thanks for the reply,
Yes currently I am testing parallel on a single machine using the batch configuration.

I also need to mention that this problem occurs only when I make use of Scenario Outlines. When using tags with individual scenarios instead, the parallel tests run fine in a the same batch configuration.

**Comment by wakaleo** [comment]
I don't think running scenario outlines in parallel would work.

**Comment by KurumiXenar** [comment]
I understand. Will this feature be a possible implementation in future? Or is it logically difficult/impossible? Thank you.
