### ISSUE TITLE
Slowness using 1.1.17-rc.3

### ISSUE THREAD

**Issue by dwursteisen** [serenity-bdd/serenity-core#255]
We noticed a slowness using the 1.1.17-rc version. We still have it with newest version of serenity. (last version tried : 1.1.22-rc.15)

We notice that this bug is introduced by this commit : https://github.com/serenity-bdd/serenity-core/commit/93f8e34a2747219c6756abf3d475a9f4ef5566ab (which is kind weird) or from both https://github.com/serenity-bdd/serenity-core/commit/93f8e34a2747219c6756abf3d475a9f4ef5566ab and https://github.com/serenity-bdd/serenity-core/commit/4d6e9bc104b4a2773d7d29cea766f82653b1f2db

related to a google group discution : https://groups.google.com/forum/#!topic/thucydides-users/OfB3ryoHjbg

**Comment by YamStranger** [comment]
Hello @dwursteisen, thanks for this issue. 

It can be an result of additional synchronization during copying files in HtmlResourceCopier.java, during report generation. 

It was done because of some issues and problems during report generation, using several threads.

**Comment by dwursteisen** [comment]
Thanks for your quick reply.


I just try. But a dependency is compiled with java 8. And we're running our project using java 7

    java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigFactory : Unsupported major.minor version 52.0

**Comment by dwursteisen** [comment]
Hello

we just try the 1.1.25-rc.2. With our first run, we still got the slowness. I will retry, but I don't think this new version solve our issue :S

**Comment by YamStranger** [comment]
Hello @dwursteisen Thanks, for this test

Unfortunately your issue still not fixed. 

Ticket will be updated, as soon as some fixes will be provided.

**Comment by dwursteisen** [comment]
With latest version : build duration : 22min
```
03/02/2016 05:02:34 [INFO ] | AbstractConnector.java         | 307 | Stopped ServerConnector@333b3ad7{HTTP/1.1,[http/1.1]}{0.0.0.0:9716}
03/02/2016 05:02:48 [INFO ] | ConsoleLoggingListener.java    | 232 | 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
```

the same project with a custom build of the 1.1.22 serenity version (without commits that I suspect to be the issue) : build duration : 10min

```
03/02/2016 03:44:03 [INFO ] | AbstractConnector.java         | 307 | Stopped ServerConnector@2950e3d7{HTTP/1.1,[http/1.1]}{0.0.0.0:9272}
03/02/2016 03:44:03 [INFO ] | ConsoleLoggingListener.java    | 222 | Test Suite Started: suite name
03/02/2016 03:44:03 [INFO ] | ConsoleLoggingListener.java    | 232 | 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
```


So I confirm (again :P) that the slowness is still here.
I just added some logs that clearly show that the slowness is between the end and the start of a new test suite.

**Comment by wakaleo** [comment]
Thanks to your references to the specific commits, the error was actually quite easy to find. This should be fixed in the next release.
