### ISSUE TITLE
Soft asserts disabled in scenario outline example after failure in previous example

### ISSUE THREAD

**Issue by luisbarretoglobant** [serenity-bdd/serenity-core#2552]
I have a scenario outline with multiple examples. The last step of the scenario is a soft assertion with several validations. In the execution of the first example, theActorInTheSpotlight.should(seeThat(....), seeThat(....)) perform all asserts as expected but in the following examples it performs only the first assertion as if soft assertions were disabled after the failure in the first example. As a workaround (after following the code in consequence check within the actor) I manually enabled back soft assertions by calling         
         StepEventBus.getEventBus().enableSoftAsserts();
before performing the soft asserts part as in
         theActorInTheSpotlight().should(seeThat(1....), seeThat(2....), ...);

It is working like a charm now but I think it is something to be fixed.

Hope this helps...

**Comment by wakaleo** [comment]
Could you check with 3.0.5?

**Comment by luisbarretoglobant** [comment]
Checked in 3.0.5... It is working fine there.
