### ISSUE TITLE
What is the best approach to handle Serenity BDD scenarios that requires longer execution time / longer waits?

### ISSUE THREAD

**Issue by kedziorm** [serenity-bdd/serenity-core#2553]
In my set of tests, I have only few of them that are failing, because of the timeout.
I could fix them, by increasing:

- implicitlywait 
- fluentwait 

values in ```serenity.properties```.

However, this way will influence all of the tests, not only those that are causing issues.
What is the most elegant / best approach way to handle this situation? Is there any special annotation that I could apply to tests that are executing longer?

**Comment by wakaleo** [comment]
Implicit waits should be used with moderation, as it will slow down all negative checks (eg checking if a field is not visible). The best is to use low values in the configuration file and fluent waits for specific conditions in your code.

**Comment by juand212** [comment]
you can also use the target utility if it is the case 
waitingForNoMoreThan(Duration.ofSeconds(10)) 
when you do not need to wait all the time configured by default.

**Comment by wakaleo** [comment]
Closing presumed answered.
