### ISSUE TITLE
 Blank reports when running mnv clean verify (index.html)

### ISSUE THREAD

**Issue by victorgallegosGIT** [serenity-bdd/serenity-core#2557]
hello I have a problem that when executing mvn clean verify it throws me the blank reports

![image](https://user-images.githubusercontent.com/85090062/133831848-31af1e11-61cc-4608-b88b-8e90f13e6e23.png)

![image](https://user-images.githubusercontent.com/85090062/133832321-0211613b-96bb-4306-9387-5fd54b6ec364.png)

![image](https://user-images.githubusercontent.com/85090062/133832451-3a075575-9815-43d3-84af-0a0f488ed849.png)
![image](https://user-images.githubusercontent.com/85090062/133832453-c64ee3a3-0bfd-49a2-a713-c51d496041d4.png)

I leave my POM

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.serenitybdd.starter</groupId>
    <artifactId>serenity-junit-starter</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Sample Serenity BDD project using JUnit</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.3.2</serenity.version>
        <serenity.maven.version>2.3.2</serenity.maven.version>
        <serenity.cucumber.version>2.3.2</serenity.cucumber.version>
        <encoding>UTF-8</encoding>
        <tags></tags>
        <parallel.tests>4</parallel.tests>
        <webdriver.base.url></webdriver.base.url>
    </properties>

    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray-plugins</name>
            <url>http://jcenter.bintray.com</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.0.13</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay-webdriver</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber6</artifactId>
            <version>2.3.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.6.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-ensure</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <includes>
                        <include>**/Runner.java</include>
                        <include>**/*Test.java</include>
                        <include>**/Test*.java</include>
                        <include>**/*TestSuite.java</include>
                        <include>**/When*.java</include>
                    </includes>
                    <systemPropertyVariables>
                        <webdriver.base.url>${webdriver.base.url}</webdriver.base.url>
                    </systemPropertyVariables>
                    <parallel>classes</parallel>
                    <threadCount>${parallel.tests}</threadCount>
                    <forkCount>${parallel.tests}</forkCount>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <configuration>
                    <tags>${tags}</tags>
                </configuration>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by wakaleo** [comment]
Do your tests match the naming convention in the maven-failsafe-plugin?
```
                <includes>
                    <include>**/Runner.java</include>
                    <include>**/*Test.java</include>
                    <include>**/Test*.java</include>
                    <include>**/*TestSuite.java</include>
                    <include>**/When*.java</include>
                </includes>
```

They don't have to but the maven-failsafe-plugin needs to be configured appropriately if they are not.

**Comment by victorgallegosGIT** [comment]
Here is my project, excuse me but I'm new to this in advance, thank you very much for helping me

![image](https://user-images.githubusercontent.com/85090062/133834487-f69c8587-a3fd-450c-a413-0ed44c7347c1.png)

![image](https://user-images.githubusercontent.com/85090062/133834540-15926060-1494-4fff-9fa2-4da5efe66df8.png)

![image](https://user-images.githubusercontent.com/85090062/133834716-d908b230-bf40-4339-88c0-59c7a3d3ecf5.png)

![image](https://user-images.githubusercontent.com/85090062/133834772-610078e7-1c77-4c47-a837-f5c7904ac4f7.png)
![image](https://user-images.githubusercontent.com/85090062/133834825-ee78ebeb-8247-43e2-a69f-b87a67adc546.png)

**Comment by victorgallegosGIT** [comment]
@wakaleo Good afternoon, please how can I configure maven-failsafe-plugin to get the Report

**Comment by victorgallegosGIT** [comment]
![image](https://user-images.githubusercontent.com/85090062/135905681-3baae0f1-64d4-45ee-8636-c9bbac4fd82d.png)

**Comment by wakaleo** [comment]
See https://maven.apache.org/surefire/maven-failsafe-plugin/ and https://serenity-bdd.github.io/theserenitybook/latest/maven.html

**Comment by wakaleo** [comment]
Closing presumed answered.
