### ISSUE TITLE
what bugs are solved if i upgrade Serenity BDD

### ISSUE THREAD

**Issue by skhandekar1** [serenity-bdd/serenity-core#2558]
We are currently using serenity bdd version 2.0.0. We are a medical device company and need a good enough reason with proper Tool Test documentation to switch versions. I have been assigned the task of figuring out the reason why we should move to the latest version of Serenity BDD. Need help with understanding what bug fixes or updates are included in version 2.6.0 from version 2.2.0. Thank you

**Comment by globalworming** [comment]
hard to say, you'd have to go through the merged pull request I guess, there are some notes but not a lot

https://github.com/serenity-bdd/serenity-core/blob/master/docs/release-notes/2.3.2.md
https://github.com/serenity-bdd/serenity-core/blob/master/docs/release-notes/2.6.0.md

**Comment by wakaleo** [comment]
This is an open source project run by volunteers, so you will not find the level of release documentation that you would expect from a vendor of commercial tools. If you need this level of documentation and information and you find Serenity BDD helpful for your development, maybe you should consider opting for a support contract?

**Comment by wakaleo** [comment]
Closed due to lack of activity.
