### ISSUE TITLE
Serenity Runner does a lot of things behind the scenes

### ISSUE THREAD

**Issue by skhandekar1** [serenity-bdd/serenity-core#2559]
When we have a number of java class test files, each class with a different @withTag, and we want to run a single class using the tags (say in case that class tests failed for some reason), then I find that the Serenity runner still executed all the rest of the class files (atleast the @BeforeClass functions that were present in the classes). So basically things are happening behind the scenes while using serenity runner that we are not aware of. I wonder how many more such things are happening under the hood of Serenity Runner. My question is, is there any documentation on how serenity runner works?

**Comment by wakaleo** [comment]
Nope. But you can write some if you like.
