### ISSUE TITLE
Issues while running multiple CucumberWithSerenity runners in parallel

### ISSUE THREAD

**Issue by pogodins** [serenity-bdd/serenity-core#2565]
Since Cucumber with Junit can run only feature files in parallel I was looking for a solution to generate test runners for every scenario.
Test runners generation intself works fine with https://github.com/temyers/cucumber-jvm-parallel-plugin.

However, in case of multiple runners being executed in parallel, I'm getting issues with Serenity, namely:
- "No BaseStepListener has been registered" error when executing runners in parallel which are pointing to different feature files.
![image](https://user-images.githubusercontent.com/15627778/135514655-b74aa05e-b074-4efe-93a9-3128c814366c.png)
Code can be found here: https://github.com/pogodins/serenity-cucumber-starter/tree/ParallelRunnersDifferentFeatures
- Broken Serenity report when executing runners in parallel from the same feature file
![Same feature](https://user-images.githubusercontent.com/15627778/135514914-8dc9cc51-2fe5-40d9-b02d-751e7cee7583.PNG)
Code example: https://github.com/pogodins/serenity-cucumber-starter/tree/ParallelRunnersSameFeature

@wakaleo could you please check if I configured properly test execution?
If I did it right, it would be really helpful to fix these issues as a lot of people would benefit from running scenarios in parallel.

When I'm able to execute multiple runners in parallel, I could write an insrtuction on how to generate runners and configure Serenity.

**Comment by wakaleo** [comment]
https://github.com/temyers/cucumber-jvm-parallel-plugin is no longer supported. 

I've written up how to run Cucumber features in parallel in https://johnfergusonsmart.com/parallel-test-execution-with-cucumber-and-serenity-bdd/ - parallel scenario execution isn't supported.

**Comment by pogodins** [comment]
Hi @wakaleo, thanks for your feedback!
My issue is not about cucumber plugin itself, and I know how to run feature files in parallel.

The problem for me is that Serenity doesn't work with parallel CucumberWithSerenity runners as I showed in my example project.
In example projects I created runners pointing to different scenarios manually (without any plugin).
What I expect is that manually created runners can be executed in parallel on the same machine.

Could you please suggest if I misconfigured my code or how we can fix Serenity to execute Cucumber runners in parallel?

**Comment by wakaleo** [comment]
This seems to work fine in 3.2.0 - please reopen if the issue still occurs for you.

**Comment by pogodins** [comment]
The behavior is still the same for multiple runners with Serenity 3.2.0. Repository with example code is updated by me now.
@wakaleo could you please share the configuration which worked for you?

**Comment by wakaleo** [comment]
> The behavior is still the same for multiple runners with Serenity 3.2.0. Repository with example code is updated by me now. @wakaleo could you please share the configuration which worked for you?

See  https://github.com/serenity-dojo/swaglabs-serenity-cucumber.git for an example of multiple Cucumber runners running in parallel with Serenity 3.2.0
