### ISSUE TITLE
No capability displayed in the serenity report

### ISSUE THREAD

**Issue by juand212** [serenity-bdd/serenity-core#2566]
Since I have a package called "login" and I have a test class called "Login"

![image](https://user-images.githubusercontent.com/47909113/135533711-6120d91e-058d-40a1-9112-57799d5e2028.png)

when you have the same test name with the capability, the report does not show the tested capability

![image](https://user-images.githubusercontent.com/47909113/135533839-daf8603e-8970-4308-b725-83a1bbb03406.png)

@wakaleo, Is there a reason for this problem?

**Comment by juand212** [comment]
good afternoon, a more specific example

https://github.com/juand212/IssueSerenityReportPoc

the report does not show the general capabilities and the "login" capability is lost

![image](https://user-images.githubusercontent.com/47909113/135683167-400cb2ff-d2bb-4cdc-9a2f-5673c5c374b2.png)
![image](https://user-images.githubusercontent.com/47909113/135683345-f6c76405-4bee-417b-bdba-3fddb02e53a8.png)

I would appreciate your help to be able to solve this problem or verify perhaps that it is necessary, greetings
@wakaleo

**Comment by juand212** [comment]
Shouldn't the report show the same for the two archetypes?

**Comment by wakaleo** [comment]
Should be fixed in 3.2.0
