### ISSUE TITLE
How to Generate PDF report

### ISSUE THREAD

**Issue by nilimajagtap** [serenity-bdd/serenity-core#257]
As i select multiple entries through Check box then it should generates PDF file for that selected entries.Please help me how to do this?
Thanks in Advance

**Comment by YamStranger** [comment]
Hello @nilimajagtap. 

I don't understand how you are trying to generate pdf reports, can you add some details. 

In current version only json, csv, html reports can be generated.

**Comment by YamStranger** [comment]
It seems that this issue already fixed or answer founded somehow.
