### ISSUE TITLE
edge browser is not launching 

### ISSUE THREAD

**Issue by brunofelix1711** [serenity-bdd/serenity-core#2572]
i am using edge driver version Version: 94.0.992.47: x86 and i gave the details in serenityedge.properties 

# Executing locally
#Options: ("chrome","firefox","iexplorer","Edge")
webdriver.driver = Edge
#Edge.switches = --start-maximized

#Web driver paths
webdriver.edge.driver = xx\\xx\\xx\\xx\\msedgedriver.exe

But i am getting a below error 

[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {browserName: MicrosoftEdge, loggingPrefs: org.openqa.selenium.logging...}

**Comment by wakaleo** [comment]
Just remove the webdriver path information and Serenity with use WebDriverManager to download and configure the right version of the driver.

Where did you read that you could use a serenitychrome file? I don't recall implementing that anywhere...

**Comment by brunofelix1711** [comment]
EnvironmentVariables environmentVariables = SystemEnvironmentVariables.createEnvironmentVariables();
 String executionPlatform=environmentVariables.getProperty("execution.platform");
String userAgent = (String) ((JavascriptExecutor) this.getDriver()).executeScript("return navigator.userAgent;");

execution.platform- this i have defined in property file like chrome.properties , firefox.proprties , safari.properties

**Comment by brunofelix1711** [comment]
my edge properties file look like below

#Properties file for local executions using standard webdrivers.
#MANDATORY FOR COMPATIBILITY BETWEEN EXECUTIONS PLATFORMS
#Options: ("selenoid","browserstack","localwebdrivers")
te.execution.platform=localwebdrivers

# Executing locally
#Options: ("chrome","firefox","iexplorer","Edge")
webdriver.driver = Edge
#Edge.switches = --start-maximized

#Web driver paths
#webdriver.edge.driver = xxxx\\xx\\edgedriver_win32\\msedgedriver.exe

**Comment by brunofelix1711** [comment]
i executed like below in prpperties file


#Properties file for local executions using standard webdrivers.
#MANDATORY FOR COMPATIBILITY BETWEEN EXECUTIONS PLATFORMS
#Options: ("selenoid","browserstack","localwebdrivers")
te.execution.platform=localwebdrivers

# Executing locally
#Options: ("chrome","firefox","iexplorer","Edge")
webdriver.driver = Edge
#Edge.switches = --start-maximized

#Web driver paths
#webdriver.edge.driver = \\msedgedriver.exe

webdriver.autodownload = true

getting the same error 

main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {browserName: MicrosoftEdge, loggingPrefs: org.openqa.selenium.logging...}

**Comment by wakaleo** [comment]
If you think there is an issue in the Serenity code, dig into the ProvideNewDriver and EdgeDriverProvider classes and propose a PR.

**Comment by brunofelix1711** [comment]
now able to run the edge browser from prop file , thanks wakaleo
