### ISSUE TITLE
Execution on chrome browser failing after chrome 95 upgrade >> net.serenitybdd.core.exceptions.SerenityManagedException: The following error occured: mouseMoveTo

### ISSUE THREAD

**Issue by copavan** [serenity-bdd/serenity-core#2589]
net.serenitybdd.core.exceptions.SerenityManagedException: The following error occured: mouseMoveTo
Build info: version: '3.5.2'
chrome browser version: 95.0.4638.54
chrome driver version: 95.0.4638.17

**Comment by wakaleo** [comment]
Closing as this appears to be a driver issue unrelated to Serenity.
