### ISSUE TITLE
how to achieve @BeforeAll in Serenity Cucumber.

### ISSUE THREAD

**Issue by sandlok** [serenity-bdd/serenity-core#2599]
Hi Team,
I have api test scenarios around 200, which needs token as header. currently using serenity cucumber framework generating token for every scenario using tag with before hook. This is resulting in 200 tokens being generated. I want to generate one token and use for all my scenarios since token has 24 hours valid time to use. Please let me know how to achieve this problem statement

**Comment by wakaleo** [comment]
Cucumber doesn't currently support hooks of that type, though I think it might in Cucumber 7.

**Comment by sandeepraina-lenze** [comment]
You can Background in your cucumber feature file which will execute generate token code before every scenario. I also had the same issue and could resolve it through this design. Cucumber 6 documentation gives more insight about this

**Comment by SandeepReddyLokasani** [comment]
@wakaleo I have integrated my current project with cucumber 7 to achieve BeforeAll annotation. However its when i am trying to run with junit 5, it's not executing. it says 0 test cases to executed. Below is the pom file

<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <packaging>jar</packaging>

  
  
     <properties>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            <serenity.core.version>2.5.8</serenity.core.version>
            <serenity.cucumber6.version>${serenity.core.version}</serenity.cucumber6.version>
            <serenity-rest-assured.version>${serenity.core.version}</serenity-rest-assured.version>
            <serenity-maven-plugin.version>${serenity.core.version}</serenity-maven-plugin.version>
            <serenity-jira-plugin.version>1.12.0</serenity-jira-plugin.version>
            <groovy-all.version>3.0.8</groovy-all.version>
            <slf4j-simple.version>1.7.9</slf4j-simple.version>
            <assertj-core.version>3.20.2</assertj-core.version>
            <commons-net.version>3.3</commons-net.version>
            <aspectj.version>1.9.7</aspectj.version>
            <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
            <maven-failsafe-plugin.version>2.22.1</maven-failsafe-plugin.version>
            <maven-surefire-plugin.version>2.22.1</maven-surefire-plugin.version>
            <json-unit.version>2.27.0</json-unit.version>
            <parallel.tests>1</parallel.tests> 
            <junit.version>5.6.0</junit.version>
			<junit.jupiter.version>${junit.version}</junit.jupiter.version>
			<junit.vintage.version>${junit.version}</junit.vintage.version>
			<junit.platform.version>1.6.0</junit.platform.version>
          </properties>
   		 <repositories>
       	 <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray</name>
            <url>https://jcenter.bintray.com</url>
       	 </repository>
  	 	 </repositories>
   		 <pluginRepositories>
       	 <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray-plugins</name>
            <url>https://jcenter.bintray.com</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>0.15</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.9</version>
        </dependency>
        <dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20180813</version>
</dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.9</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>2.9.9</version>
        </dependency>
       	 <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.10</version>
            <scope>provided</scope>
        </dependency>

 		 <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.0.13</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.core.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        
        
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber6</artifactId>
            <version>${serenity.cucumber6.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.6.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.fge</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.2.6</version>
        </dependency>
        <dependency>
   				 <groupId>io.cucumber</groupId>
  				  <artifactId>cucumber-java</artifactId>
   				 <version>7.0.0</version>
  				  <scope>test</scope>
		</dependency>
		<dependency>
    			<groupId>io.cucumber</groupId>
    			<artifactId>cucumber-java8</artifactId>
   				 <version>7.0.0</version>
    			<scope>test</scope>
			</dependency>
			<dependency>
   				 <groupId>io.cucumber</groupId>
  				  <artifactId>cucumber-junit</artifactId>
   				 <version>7.0.0</version>
   				 <scope>test</scope>
			</dependency>
			<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-api</artifactId>
    <version>${junit.jupiter.version}</version>
</dependency>
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <version>${junit.jupiter.version}</version>
</dependency>
<dependency>
    <groupId>org.junit.vintage</groupId>
    <artifactId>junit-vintage-engine</artifactId>
    <version>${junit.vintage.version}</version>
</dependency>
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-engine</artifactId>
    <version>${junit.platform.version}</version>
</dependency>
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-launcher</artifactId>
    <version>${junit.platform.version}</version>
</dependency>
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-runner</artifactId>
    <version>${junit.platform.version}</version>
</dependency>

<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-console-standalone</artifactId>
    <version>${junit.platform.version}</version>
    <scope>test</scope>
</dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                     <testFailureIgnore>true</testFailureIgnore>
                    <skip>false</skip>
                </configuration>
            </plugin> 
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <includes>
                        <include>**/*TestSuite.java</include>
                    </includes>
                 	   
                	    
                 	  
       				  
                    <systemPropertyVariables>
                    <report>true</report>
                    <environment>{environment}</environment>
                    </systemPropertyVariables>
          	   </configuration> 
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.core.version}</version>
                 <configuration>
            				 <tags>${tags}</tags>
            				  <reports>single-page-html</reports> 
        		</configuration>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                         <configuration>
                           <outputDirectory>/Users/pfmacsandeep/AutomationResults_Baas/TestResults_11_19_three_staging</outputDirectory>
                 	 </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>


Junit runner class

import net.serenitybdd.cucumber.CucumberWithSerenity;


import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.cucumber.junit.CucumberOptions;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    plugin = {"pretty"},

    	features = {
    			"src/test/resources/features"
    			},.
    glue= "org.StepDefinitions"
   // tags = "smoke"
)
public class CucumberTestSuite {
	private static final Logger logger = LoggerFactory.getLogger(CucumberTestSuite.class);

	@BeforeClass
	public static void initializationPersonId()
	{
		logger.error("In bbb class");
	}
	@AfterClass
	public static void savingCSVfile() {
		logger.error("In after class");
		
	}
	
}

**Comment by wakaleo** [comment]
You are trying to use JUnit annotations with a Cucumber test, which won't work. Use Cucumber 7 @BeforeAll along with Serenity 3.2.0.
