### ISSUE TITLE
Serenity result.csv giving file not found exception

### ISSUE THREAD

**Issue by SandeepReddyLokasani** [serenity-bdd/serenity-core#2601]
Hi Team,
import net.serenitybdd.cucumber.CucumberWithSerenity;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.slf4j.LoggerFactory;
import com.google.common.io.Files;
import io.cucumber.junit.CucumberOptions;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    plugin = {"pretty"},
    features = {"src/test/resources/features/"},
    glue= "StepDefinitions",
    tags = "smoke"
)
public class CucumberTestSuite {
	private static final Logger logger = LoggerFactory.getLogger(CucumberTestSuite.class);

	@BeforeClass
	public static void initializationPersonId()
	{
		logger.error("In bbb class");
	}
	@AfterClass
	public static void savingCSVfile() {
		try {
			Thread.sleep(5000);
		
		logger.error("In after class");
		Date d = new Date();
		logger.error(d.toString());
		long filename = d.getTime();
		Path src = Paths.get("{Project_dir}/target/site/serenity/results.csv")
		
			Files.copy(src.toFile(), dest.toFile());
		} 
		
		catch (IOException e) {
			logger.error("Saving csv file :",e);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
}
After executing the test i am want to save results.csv into one of my local directory. But this is giving me below error

22:04:21.717 [pool-1-thread-1] ERROR o.p.B.CucumberTestSuite - In after class
22:04:21.723 [pool-1-thread-1] ERROR o.p.B.CucumberTestSuite - Sat Nov 06 22:04:21 PDT 2021
22:04:21.742 [pool-1-thread-1] ERROR o.p.B.CucumberTestSuite - Saving csv file :
java.io.FileNotFoundException: 
{project_dir}/target/site/serenity/results.csv (No such file or directory)

**Comment by wakaleo** [comment]
Test outputs are generated in a parallel thread, independent of the test lifecycle, and may not have been completed when the @AfterClass method is invoked. If you want to process test output files, it should really be part of your build process, not your test code.

**Comment by SandeepReddyLokasani** [comment]
@wakaleo how to save my results.csv through build process.

**Comment by SandeepReddyLokasani** [comment]
@wakaleo thanks, I could able to set the results via build process.
