### ISSUE TITLE
Integration plans of Selenium 4

### ISSUE THREAD

**Issue by sandeepraina-lenze** [serenity-bdd/serenity-core#2602]
Hi,

There is a major release of selenium 4 which compiles with W3C standards which is integrated with major web-browsers. Along with this change selenium 4 comes with lots of upgrades and feature additions.

I want to know is there any plan to integrate selenium 4 with serenity. I understand since this is a major upgrade and can break some legacy functionalities. But still looking forward for this integration.

Thanks and Regards,
Sandeep Raina

**Comment by wakaleo** [comment]
Serenity 3.0.6 will integrate with Selenium 4, and should be available within the next few days. As you mention it does introduce breaking changes, and has dropped support for HTMLUnit and PhantomJS.

**Comment by sandeepraina-lenze** [comment]
Thank you John for your reply looking forward for this build version

**Comment by sandeepraina-lenze** [comment]
Serenity Core v3.1.0 integrates Selenium 4 hence closing this issue
