### ISSUE TITLE
I cannot launch app without app path in serenity.properties

### ISSUE THREAD

**Issue by ThanhTra1** [serenity-bdd/serenity-core#2604]
I already installed my app  and i don't have the app.apk.
I tried to set app path in serenity.properties like this **_appium.app =_** 
( follow https://github.com/serenity-bdd/serenity-core/issues/1154) 
It work until yesterday.
But now, it is not work anymore.

_appium.automationName=uiautomator2
appium.platformName = Android
appium.platformVersion = 9.0
appium.deviceName  = randomName
appium.app =
appium.appActivity = com.google.android.finsky.activities.MainActivity
appium.appPackage = com.android.vending
appium.hub = http://localhost:4723/wd/hub
appium.browserName=Browser
webdriver.driver=appium_

**Comment by wakaleo** [comment]
If it worked yesterday maybe see what has changed since yesterday?

**Comment by ThanhTra1** [comment]
Thanks for the reply.
I've checked and I haven't changed anything about the serenity.properties file setting.

**Comment by wakaleo** [comment]
Have you changed the version of Serenity?

**Comment by ThanhTra1** [comment]
no, i use version 2.5.8

**Comment by wakaleo** [comment]
So what has changed since yesterday? If you have not changed Serenity version or configuration, that would suggest the problem comes from somewhere else. I would advise asking on the Serenity Gitter channel (http://gitter.im/serenity-bdd/serenity-core), as Appium support is largely community-driven.

**Comment by ThanhTra1** [comment]
Thanks. I will ask on the Serenity Gitter channel.
