### ISSUE TITLE
When step for Scenario's with @ignore and @test tag run and throws error

### ISSUE THREAD

**Issue by sumit-global** [serenity-bdd/serenity-core#2605]
Hi John,

I found weird behavior after upgraded to "2.3.10", I have 2 scenarios as below:

```
@test @ignore
Scenario 1: Test
Given I open web browser--> This will open browser using openUrl(''xyz.com")
When I verified some links on home page--> Wait for links to verified
Then All links should shown on page--> Do assertions
```
```
@test
Scenario 2: Test another
Given I open web browser--> This will open browser using openUrl(''xyz.com")
When I verified some links on home page--> Wait for links to verified
Then Check for user logged in--> This part isn't implemented yet
```

I am running -Dcucumber.filter.tags="@test" tag, scenario 1 runs fine but for scenario 2 it **ignore** Given step but always run When step, as browser isn't launched hence wait for link and throw exception and marked build failed.

Could you please help here?

**Comment by wakaleo** [comment]
Cucumber tags do not affect scenario execution unless you include them in a Cucumber filter, so you would need to use a filter like "@test and not @ignore".
