### ISSUE TITLE
GridEditorBase e item eklemek

### ISSUE THREAD

**Issue by neonemivar** [serenity-bdd/serenity-core#261]
Aşağıda yer alan kod yapısı grid içerisine item ları ekliyor ancak grid i refresh edemiyorum, konu ile ilgili yardım edebilirseniz sevinirim,

	public class QuestionOptionEditor : GridEditorBase<QuestionOptionRow>
	{
		public QuestionOptionEditor(jQueryObject container)
			: base(container)
		{ }
			
		protected override List<ToolButton> GetButtons()
		{
			List<ToolButton> buttons = base.GetButtons();
			buttons.Add(new ToolButton
			{
				Title = Q.Text("Generate Options"),
				CssClass = "generate-options-button",
				OnClick = delegate
				{
						this.Items.Add(new QuestionOptionRow { OptionText = "YEŞİL", SortOrder = 10, IsActive = true });
						this.Items.Add(new QuestionOptionRow { OptionText = "SARI", SortOrder = 20, IsActive = true });
						this.Items.Add(new QuestionOptionRow { OptionText = "KIRMIZI", SortOrder = 30, IsActive = true });
						this.Refresh();
				}
			});
			return buttons;
		}
	}

**Comment by YamStranger** [comment]
Hello @neonemivar. 

Please use English for issue description

Thanks a lot!!!

**Comment by neonemivar** [comment]
Hello YamStranger,

Problem, added items in ToolButton.OnClick, so does not UI refresh.

**Comment by YamStranger** [comment]
Hello @neonemivar. 

It seems that this issue pushed to wrong project - it is not about [Serenity BDD](http://thucydides.info/docs/serenity-staging/#_building_serenity_projects_in_maven). 

If I am wright - please close this issue, or add some additional details. 

Thanks

**Comment by neonemivar** [comment]
I'm sorry for mistakes
