### ISSUE TITLE
Unable to run multiple tags at same time

### ISSUE THREAD

**Issue by deepthi-ravindra** [serenity-bdd/serenity-core#2610]
I have tried the following :
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        features = {"classpath:parallel/features/[CUCABLE:FEATURE].feature"},
        dryRun = false,
        tags = "@tag1 and @tag2",
        monochrome = false,
        glue = "stepdefs")

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        features = {"classpath:parallel/features/[CUCABLE:FEATURE].feature"},
        dryRun = false,
        tags = "(@tag1 and @tag2)",
        monochrome = false,
        glue = "stepdefs")

I need to combine 2 tags and run some scenarios. How is it possible with Serenity? I use Junit.

**Comment by deepthi-ravindra** [comment]
I have already tried this : mvn clean verify -P PROFILENAME -Dbrowser=chrome -Denvironment=s1 -Dtags="s1 and vm02"

**Comment by deepthi-ravindra** [comment]
Yes doesn't work.

I need to concat 2 in the sense,  i need to run tests which has both tags..
so need to use 'and'.

Cheers

**Comment by wakaleo** [comment]
`mvn clean verify -Dcucumber.filter.tags="@tag1 and @tag2"`

**Comment by rakeshhp** [comment]
@wakaleo cucumber filter tags just doesn't work at all even on giving a single tag in the maven goal 
mvn clean verify -Dcucumber.filter.tags="@tags" and have tried all other variations as well
It's becomes important to filter tests in run time having larger suite and have been unable to do so.

**Comment by wakaleo** [comment]
@rakeshhp what version are you using? I ran the command I mentioned against Serenity 3.0.5 without any issues.

**Comment by deepthi-ravindra** [comment]
This didn't work as well John..

**Comment by rakeshhp** [comment]
@wakaleo using serenity 2.5.8

**Comment by wakaleo** [comment]
2.5.8 should be fine, but try with 3.0.5 (and make sure you are using the correct version of Cucumber).

**Comment by rakeshhp** [comment]
@wakaleo as per the site for cucumber 6  serenity 2.5.8 is stable version

**Comment by wakaleo** [comment]
Nevertheless...

**Comment by rakeshhp** [comment]
@wakaleo I tried with 3.0.5  version with cucumber.filter.tags zero tests were executed.
As @deepthi-ravindra mentioned only way I could execute is mentioning tag  in the cucumber runner file and that too it does not take multiple tags .

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces the issue? I can't reproduce this behaviour - have you ever seen it working with your current tags?

**Comment by wakaleo** [comment]
The correct way to do this with Serenity 3.1.15 is:
```mvn clean verify -Dcucumber.filter.tags="@tag1 and @tag2"```

**Comment by Nekobravo** [comment]
> The correct way to do this with Serenity 3.1.15 is: `mvn clean verify -Dcucumber.filter.tags="@tag1 and @tag2"`
I'm using cucumber 7 and I can't run 2 scenarios, can you help me
![image](https://user-images.githubusercontent.com/23462665/166395444-d007a5e0-bba0-493e-8624-4406f885a0ea.png)
