### ISSUE TITLE
How to run @BeforeAll(Cucumber7) using our current serenity version

### ISSUE THREAD

**Issue by sandlok** [serenity-bdd/serenity-core#2611]
Hi Team,
Cucumber 7 has introduced @BeforeAll and @AfterAll annotations. However when running the individual feature file its working with current v2.5.8 version serenity. However when executing through cucumberserenity runner class its not working. Can some please advise me on this.

**Comment by wakaleo** [comment]
Serenity only supports Cucumber 6 at the moment. The quickest solution is to update the code to support Cucumber 7 and propose a pull request.

**Comment by wakaleo** [comment]
Cucumber 7 works with Serenity 3.1.15

**Comment by sandlok** [comment]
Thanks Wakaleo
