### ISSUE TITLE
DevTools usage

### ISSUE THREAD

**Issue by jirikralik** [serenity-bdd/serenity-core#2616]
Hello guys, 

serenity finally supports Selenium 4 (thank you John!). I would like to use the DevTools for our project. Do I assume correctly, it is not currently possible since the webdriver is managed by serenity and we are not able to get ChromeDriver instance to call getDevTools? Thank you!

Jiri

**Comment by wakaleo** [comment]
In any PageObject or UIInteractionSteps class, you can call `getDevTools()`. And in Screenplay, you can do something like this:
```
         actor.attemptsTo(
             WithDevTools.perform(
                 devTools -> devTools.createSession()
             )
         );
```

**Comment by jirikralik** [comment]
omg, this is even better than I expected

**Comment by xixiWj** [comment]
hi ,  Is there a guide for devTools send? 
```
devTools.send(new Command<>())
```
Parameter description of the Command class

**Comment by xixiWj** [comment]
@wakaleo @jirikralik 
hi , Is there a guide for devTools send?

devTools.send(new Command<>())
Parameter description of the Command class

**Comment by wakaleo** [comment]
There is probably something in the Selenium documentation .
