### ISSUE TITLE
A way to run only tagged classes without running before method of non tagging classes.

### ISSUE THREAD

**Issue by jeewanthajtk** [serenity-bdd/serenity-core#2619]
Hi,
I am facing below issue. Could you please help me on resolving this if there is any posibility.

Issue:
I have two test class as A and B. Both classes has a before method. Then I have tagged tests in class A. Then I run that tag to run all tests in class A. But as I saw the before method in class B also run. 

Can we run the before method if that class has matching tag only?

Thanks

**Comment by wakaleo** [comment]
That is dependent on the JUnit lifecycle, so Serenity has no control over that in JUnit. You could check using the Serenity StepEventBus to see what tags are currently active on the current test.

**Comment by jeewanthajtk** [comment]
Thank You.
