### ISSUE TITLE
serenity-bdd-screenplay-webdriver missing abilities package when import from maven/gradle

### ISSUE THREAD

**Issue by cuongld2** [serenity-bdd/serenity-core#2624]
[Scenario]
I want to use the BrowserTheWeb function but when import library from maven for serenity-screenplay-webdriver I don't see the abilities/BrowserTheWeb class in the downloaded library.

<img width="302" alt="browse-the-web" src="https://user-images.githubusercontent.com/42601985/144739865-4206c1e6-5b5e-40fd-b308-148b632010f7.PNG">

**Comment by wakaleo** [comment]
![image](https://user-images.githubusercontent.com/55986/144740492-ddd1398e-c5e1-4091-b905-85e13840e653.png)

**Comment by cuongld2** [comment]
Ah I see.
I need to import serenity-screenplay-webdriver .
Thank you!
