### ISSUE TITLE
Serenity.conf ignoring firefox.preferences

### ISSUE THREAD

**Issue by despellhtb** [serenity-bdd/serenity-core#2626]
I am adding firefox.preferences = "browser.helperApps.neverAsk.saveToDisk=text/plain" in serenity.conf and serenity seems to ignore the setting. 

This has been working for years until I bumped serenity to the latest version => 3.1.5

ATM I revert back to version => 2.3.2 and everything seems working again.

Please have a look, the base suspect is changing versions, for anything else just ask me for more feedback.

**Comment by wakaleo** [comment]
Have a look at the code in the and see if you can see anything - the FirefoxDriverCapabilities class is the place you'll want to look. Could be related to Selenium 4. If you fix a fix, raise a PR and I will take a look.

**Comment by despellhtb** [comment]
I downgraded the serenity core version and this is working now. If I can reproduce this in the feature I will let you know!

**Comment by KroneckerDeIta** [comment]
It's working for me in 3.2.5, but not in 3.3.0. So problem happened between those two releases, but 3.2.5 is after the release OP mentioned there was an issue so was fixed and not working again.

**Comment by wakaleo** [comment]
In the latest versions all the options are configured via W3C properties - see https://serenity-bdd.github.io/docs/guide/driver_config#configuring-firefox

**Comment by KroneckerDeIta** [comment]
Thanks, assumed was a bug. Works fine.

**Comment by madduci** [comment]
Can i set properties per OS? Example: the Path to download files is strictly system-dependent (windows paths vs. linux paths)

**Comment by despellhtb** [comment]
Of course you can. 
Do not make use of wasted "if" of course, you can do this:

`import java.io.File;
Path filePath = Paths.get(System.getProperty("user.dir") + File.separator + "src" + File.separator + "test" + File.separator + "resources" + File.separator + "example.txt");

`

**Comment by madduci** [comment]
I didn't want to set it by code, but leave as an option in `serenity.conf`` and I've made it possible by setting

```
"browser.download.dir": ${user.dir}${file.separator}MyDir
```
