### ISSUE TITLE
webdriver.autodownload = true not working behind proxy

### ISSUE THREAD

**Issue by balajioct8** [serenity-bdd/serenity-core#2631]
[DEBUG] 2021-12-08 23:35:26,194 [main] (WebDriverManager.java:586)- The driver version for Chrome 96 is unknown ... trying with latest
[DEBUG] 2021-12-08 23:35:26,198 [main] (InternalHttpClient.java:172)- ex-00000003: preparing request execution
[DEBUG] 2021-12-08 23:35:26,198 [main] (RequestAddCookies.java:114)- Cookie spec selected: strict
[DEBUG] 2021-12-08 23:35:26,199 [main] (RequestAuthCache.java:76)- Auth cache not set in the context
[DEBUG] 2021-12-08 23:35:26,199 [main] (ProtocolExec.java:158)- ex-00000003: target auth state: UNCHALLENGED
[DEBUG] 2021-12-08 23:35:26,199 [main] (ProtocolExec.java:164)- ex-00000003: proxy auth state: UNCHALLENGED
[DEBUG] 2021-12-08 23:35:26,199 [main] (ConnectExec.java:116)- ex-00000003: acquiring connection with route {s}->https://chromedriver.storage.googleapis.com:443
[DEBUG] 2021-12-08 23:35:26,199 [main] (InternalExecRuntime.java:101)- ex-00000003: acquiring endpoint (3 MINUTES)

can you make it work behind proxy by something like this

https://stackoverflow.com/questions/45733761/webdriver-manager-not-working-behind-proxy

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by wakaleo** [comment]
The simplest way to customise the WebDriverManager behaviour is to use the `WebDriverManagerEnhancer`https://github.com/serenity-bdd/serenity-core/blob/bd32881ee6ffef3a8bfa0a949864a94e9cbfbded/serenity-core/src/main/java/net/serenitybdd/core/webdriver/enhancers/WebDriverManagerEnhancer.java interface:

**Comment by wakaleo** [comment]
Closed for lack of activity
