### ISSUE TITLE
Report is missing Features Graph

### ISSUE THREAD

**Issue by OussamaAutomation** [serenity-bdd/serenity-core#2641]
Hello I am trying to update to the new Serenity version, 3.1.1
everything is working correctly but still just one issue that the report is missing the features chart.

![report missing chart](https://user-images.githubusercontent.com/46843077/146389546-312c8aa5-1545-444c-a342-1eb9f7856555.png)

Thanks in advance.

**Comment by OussamaAutomation** [comment]
this is my pom: 

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<serenity.version>3.1.1</serenity.version>
		<serenity.cucumber.version>3.1.1</serenity.cucumber.version>
		<serenity.maven.version>3.1.1</serenity.maven.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>com.google.inject</groupId>
			<artifactId>guice</artifactId>
			<version>5.0.1</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.7</version>
				<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.2.6</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
			<version>1.2.6</version>
		</dependency>

		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.19.0</version>
		</dependency>
		<dependency>
			<groupId>com.adp.qa</groupId>
			<artifactId>qa-autopilot-commons</artifactId>
			<version>9.0.0</version>
			<exclusions>
				<exclusion>
					<groupId>commons-codec</groupId>
					<artifactId>commons-codec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-collections</groupId>
					<artifactId>commons-collections</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>jetty-util</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpmime</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-simple</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.mashape.unirest</groupId>
			<artifactId>unirest-java</artifactId>
			<version>1.4.9</version>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jira-plugin</artifactId>
			<version>1.12.0</version>
		</dependency>
		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>3.8</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-launcher</artifactId>
			<version>1.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<version>5.8.1</version>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M5</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>3.0.0-M5</version>
				<configuration>
					<includes>
						<include>**/*.java</include>
					</includes>
					<reuseForks>true</reuseForks>
					<argLine>-Xmx1024m</argLine>
					<parallel>classes</parallel>
					<threadCount>7</threadCount>
					<perCoreThreadCount>false</perCoreThreadCount>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>

					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by wakaleo** [comment]
Can you try with 3.1.5?

**Comment by OussamaAutomation** [comment]
I tried but still the same problem. i was thinking that using both logback and log4j cause so i removed log4j but still the same problem.

**Comment by wakaleo** [comment]
It is probably related to jchart (nothing to do with Java). Check the javascript console for error messages in your browser. Which browser are you using? Can you provide a project that reproduces the issue?

**Comment by OussamaAutomation** [comment]
i am using chrome version 88. But when i clone the serenity-cucumber-starter and run it then the report is displayed correctly with all charts.
![full report](https://user-images.githubusercontent.com/46843077/146411162-897dc453-2305-424a-9ed3-88fc5c033e4d.png)


 this is the console error :
![2021-12-16_17-30-56](https://user-images.githubusercontent.com/46843077/146410879-076722a0-19dc-4958-aba7-98fcbce85069.png)

**Comment by wakaleo** [comment]
It looks like some kind of Javascript issue related to ChartJS, possibly related to something in the test data that JSChart doesn't like. Can you provide a project that reproduces the issue? Try starting with the starter project and adding scenarios gradually until you can reproduce the issue.

**Comment by OussamaAutomation** [comment]
Hello 
Finaly I found that the issue was with the feature title : it was containing ' because the title is in french. Once i removed it  then the graph is displayed correctly.
<img width="430" alt="error" src="https://user-images.githubusercontent.com/46843077/146644277-21920aaf-ed23-4c22-971b-95419b98bbd7.png">

Thanks for your support.
