### ISSUE TITLE
View full report url update

### ISSUE THREAD

**Issue by yunwu-cn** [serenity-bdd/serenity-core#2645]
https://github.com/serenity-bdd/serenity-core/blob/aa299f861940450310f663d043097e518428e691/serenity-single-page-report/src/main/resources/templates/email/serenity-summary-report-inlined.html#L1089

This link is pointing to the folder/directory, instead of the exact path to  index.html. can we have the link as report.link + "/index.html" instead ?

**Comment by wakaleo** [comment]
The report value is determined by the `serenity.report.url` property (it has no default value). You can set it to anything you want.

**Comment by yunwu-cn** [comment]
Yes, that value is determined by this property `serenity.report.url`

However, if we have the full url let's say `serenity.report.url = http://example.com/index.html`, it will then cause the other links on the summary page invalid. 
For example, the failed scenario link will be `http://example.com/index.html/some-failed-scenario.html` instead of the correct `http://example.com/some-failed-scenario.html`, so that's why the `serenity.report.url` will need to be the directory name.
Reference code 
https://github.com/serenity-bdd/serenity-core/blob/aa299f861940450310f663d043097e518428e691/serenity-single-page-report/src/main/resources/templates/email/serenity-summary-report-inlined.html#L1298
and
https://github.com/serenity-bdd/serenity-core/blob/aa299f861940450310f663d043097e518428e691/serenity-single-page-report/src/main/resources/templates/email/serenity-summary-report-inlined.html#L1357

That's why I think the full report home page should follow the same pattern like
` th:href="${#strings.concat(report.link,'/index.html')}">View full report</a> `

I can create a quick PR if this makes sense to you.

**Comment by wakaleo** [comment]
Ok, I see now. Yes, please do propose a PR
