### ISSUE TITLE
Not able to see the pie chart in serenity report 3.1.5

### ISSUE THREAD

**Issue by robintyagi12** [serenity-bdd/serenity-core#2653]
Hi Team,

I was using serenity version 2.2.13 and there is wrong time issue in the reports when executing test cases parallelly. So I want to move to 3.1.5 and updated the following dependencies to 3.1.5 and not seeing the pie chart when executing on local system (no jenkins)

serenity-single-page-report and serenity-maven-plugin to 3.1.5

And rest following dependencies are of 2.2.13 version -

serenity-core, serenity-junit, >serenity-screenplay, serenity-screenplay-webdriver, serenity-cucumber5, 

and Junit version is - 4.13.2

Please guide me, what shall be wrong here, even on local execution (no jenkins), pie chart is not coming, could be it bcz of mismatch of serenity versions, please guide ?

<img width="947" alt="Serenity_Report_3 1 5_02" src="https://user-images.githubusercontent.com/14859746/147326735-d5add6c4-a6f4-4c81-a89f-bc381cc58bd0.png">
<img width="947" alt="Serenity_Report_3 1 5_01" src="https://user-images.githubusercontent.com/14859746/147326737-9f75c95a-94bc-4cb6-baa3-3cc46f5cd58f.png">

**Comment by globalworming** [comment]
Do you open it from e.g. your IDE as "htto://localhost.." or from your file system as "file://..."?

**Comment by wakaleo** [comment]
Don't mix serenity versions, as it will cause errors. Make sure all the version numbers are the same.

**Comment by robintyagi12** [comment]
> 
First I moved to target/site folder and then opened index.html

**Comment by wakaleo** [comment]
Make sure all the Serenity version numbers are the same for all libraries.

**Comment by robintyagi12** [comment]
Hi @wakaleo and @globalworming - I have updated all the serenity dependencies to 3.1.5 and test case is executing successfully but there is no test case related information with in the serenity report. I am running locally on windows 10.

We are using maven-failsafe-plugin to run the test which are in the format - **/*IT.java

Please suggest what could be the issue here.

![Serenity_Reports_3 1 5](https://user-images.githubusercontent.com/14859746/147750886-a5c002ec-fccc-4443-8d94-56a10e145e4e.png)

**Comment by wakaleo** [comment]
Make all the versions 3.1.15, and drop the Cucumber dependencies. Also check for dependency conflicts: https://maven.apache.org/plugins-archives/maven-dependency-plugin-2.8/examples/resolving-conflicts-using-the-dependency-tree.html

**Comment by robintyagi12** [comment]
Hi @wakaleo, 

After removing cucumber unwanted dependencies, when I try to run test, facing below error - do you have some idea about this? 

<img width="960" alt="SS_02" src="https://user-images.githubusercontent.com/14859746/147826491-0b14d6ab-9db7-4544-8d50-59a6a3a57f9f.png">

<img width="960" alt="SS_01" src="https://user-images.githubusercontent.com/14859746/147826490-58893f26-4c14-4814-a223-c61650611d9e.png">

**Comment by wakaleo** [comment]
NoClassDefFound is always a dependency conflict issue, so there must be some remaining conflicts.

**Comment by wakaleo** [comment]
Closing presumed fixed

**Comment by prashantrbs** [comment]
I fixed this by downgrading serenityCoreVersion = '3.1.1' to '3.0.5'

**Comment by wakaleo** [comment]
> I fixed this by downgrading serenityCoreVersion = '3.1.1' to '3.0.5'

That's not really a sustainable solution, though, is it? Could you see if it works with 3.2.0, and make sure that all of the serenity dependencies match (there is a mix of many versions in the script shown here which will not work).
