### ISSUE TITLE
What is different to task and interaction on Serenity BDD Screenplay?

### ISSUE THREAD

**Issue by kemalkagankural** [serenity-bdd/serenity-core#2654]

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/theserenitybook/latest/serenity-screenplay.html#_high_level_tasks_rely_on_other_lower_level_tasks_or_actions

**Comment by kemalkagankural** [comment]
Thanks Mr. Smart. I will read tihis documentation.

**Comment by kemalkagankural** [comment]
I have a question about Target. If there is more than one target in the target section, how can I get one of them? 
Also ı want to swipe left to right android device screen  with use appium. How can ı do this and can ı use withaction via actor?

**Comment by wakaleo** [comment]
Github issues are intended for defects or change requests - Gitter (https://gitter.im/serenity-bdd/serenity-core) is a better place for this kind of question.

**Comment by kemalkagankural** [comment]
Sorry,I dont know this. I will Gitter.
