### ISSUE TITLE
Timestamp in individual Scenario's report is +1 year. It is ok in overall report

### ISSUE THREAD

**Issue by ankush2704** [serenity-bdd/serenity-core#2655]
![image](https://user-images.githubusercontent.com/19248898/147449554-bdc686f2-1e4e-4fdd-a4b2-899ad0385a05.png)

This time is incorrect with serenity version 2.2.13
Observing since 26th Dec 2021. Was working fine till 25th Dec

**Comment by wakaleo** [comment]
Can't reproduce this with 3.1.15, but this is unlikely to be related to Serenity - Serenity just reads the system date, so it may be related to the date on the server you are running the tests on.

**Comment by ankush2704** [comment]
In case of wrong system date. Timestamp at home page of report should be incorrect too.
Where as time stamp at home page is OK but time stamp at individual scenario is wrong.
![image](https://user-images.githubusercontent.com/19248898/147454145-b63c3161-d4f1-471c-9af9-57bb48d5ce39.png)

**Comment by wakaleo** [comment]
No idea, maybe you have some old files in your target directory.

**Comment by ankush2704** [comment]
should not be the case because I tried to run it on linux containers as well as my local windows machine every time with fresh clone so chances of conflict with residual are slim :(

**Comment by wakaleo** [comment]
Have you tried with the latest version?

**Comment by ankush2704** [comment]
I tried but for I need to change cucumber and Junit versions too. A bit long process.
Are you sure that data formatter is no where dd-MM-YYYY instead of dd-MM-yyyy?

**Comment by wakaleo** [comment]
```
protected static final String TIMESTAMP_FORMAT = "dd-MM-YYYY HH:mm:ss";
```

Update to 3.1.15 and see if you still get the issue.

**Comment by wakaleo** [comment]
Possibly, I will check.
