### ISSUE TITLE
Setting 'threadCount ' can not take effect

### ISSUE THREAD

**Issue by carl-pki** [serenity-bdd/serenity-core#2658]
I set threadCount to 2, the story cannot be executed at the same time
![image](https://user-images.githubusercontent.com/85552832/148046591-74afbe1c-144b-4bad-bfcc-cddb08791791.png)

**Comment by wakaleo** [comment]
That would be a JBehave question, which would be either in the serenity-jbehave module (https://github.com/serenity-bdd/serenity-jbehave) or in the JBehave project itself. We are no longer maintaining JBehave integration but you are welcome to look yourself and propose a PR (or request a change as part of a commercial support package).

**Comment by wakaleo** [comment]
Closed as not related to serenity-core
