### ISSUE TITLE
[question] - how to throw more meaningful exception instead of Serenity UnrecognisedException when casting a response

### ISSUE THREAD

**Issue by kedziorm** [serenity-bdd/serenity-core#2659]
When I receive a response from REST, I am trying to cast it:

```
response.extract().as(MyDtoClass.class)
```

When there's any issue with casting, for example one of the fields changed its type, Serenity UnrecognisedException is thrown and displayed in the report.

How can I handle it - give more information in the report / provide better exception?
As I could see, method ```as``` in 
https://javadoc.io/doc/io.rest-assured/rest-assured/3.0.0/io/restassured/response/ResponseBodyExtractionOptions.html#as-java.lang.Class-

does not declare any exception.

**Comment by globalworming** [comment]
probably just wrap it in a try-catch block, catching the UnrecognisedException and then  `throw new YourCustomException(message, e)`

**Comment by wakaleo** [comment]
If the error is unrecognised, and RestAssured is not giving any extra information, then your own custom exception would be the best option (assuming you know something RestAssured doesn't)

**Comment by wakaleo** [comment]
Closing presumed answered
