### ISSUE TITLE
Serenity Rest - Blacklisted Request headers not masked in the console logs and report

### ISSUE THREAD

**Issue by m-aster22** [serenity-bdd/serenity-core#2660]
I'm trying to mask the API key passed in the Request header for security purposes.

When I use rest-assured's method, the request header is blacklisted in the console logs but the REST query isn't published in the Serenity report.
```
    given()
        .config(
            RestAssuredConfig.config()
                .logConfig(LogConfig.logConfig().blacklistHeader("x-api-key")))
        .baseUri("https://my-api-base-uri.com")
        .header("x-api-key", "my-api-key-value")
        .log()
        .all();
```

Console log output:
```
    Request method:	GET
    Request URI:	https://my-api-base-uri.com
    Proxy:		<none>
    Request params:	<none>
    Query params:	<none>
    Form params:	<none>
    Path params:	customer_no=001
    Headers:		x-api-key=[ BLACKLISTED ]
    			Accept=*/*
    Cookies:		<none>
    Multiparts:		<none>
    Body:		<none>
    HTTP/1.1 200 OK
```

When I use SerenityRest, the blacklisted header value is still published in both the console logs and the report.
```
    SerenityRest.given()
        .config(
            RestAssuredConfig.config()
                .logConfig(LogConfig.logConfig().blacklistHeader("x-api-key")))
        .baseUri("https://my-api-base-uri.com")
        .header("api-key", "my-api-key-value")
        .log()
        .all();
```

Console log output:
```
    Request method:	GET
    Request URI:	https://my-api-base-uri.com
    Proxy:		<none>
    Request params:	<none>
    Query params:	<none>
    Form params:	<none>
    Path params:	customer_no=001
    Headers:		x-api-key=my-api-key-value
    			Accept=*/*
    Cookies:		<none>
    Multiparts:		<none>
    Body:		<none>
    HTTP/1.1 200 OK
```
![image](https://user-images.githubusercontent.com/28387803/148454001-28d0b909-8400-4121-8624-4f82bd6392df.png)

serenityCoreVersion: 2.3.12
serenityRestAssuredVersion: 2.3.12
rest-assured version: 4.3.2

**Comment by wakaleo** [comment]
I'm not familiar with the `blacklistHeader()` method, but from a quick look at the Serenity code, you would need to refactor the `registerCall()` method in the `net.serenitybdd.rest.utils.RestReportingHelper` class, and do some pre-processing on the headers before creating the `RestQuery` object. If you do a pull request I am happy to review.
