### ISSUE TITLE
Automatic driver download in serenity framework

### ISSUE THREAD

**Issue by Tanvitha** [serenity-bdd/serenity-core#2661]
Hi, 
With the latest git checkins on serenity junit framework i can see the driver is downloading automatically, but not with the old serenity frameworks.
what I can do to my existing framework to download the driver automatically?
Please suggest

**Comment by wakaleo** [comment]
You will need to upgrade to the latest version of Serenity.

**Comment by Tanvitha** [comment]
Hi, Thanks for such a quick reply, 
But i have both the framework side by side, and i downgraded the serenity version of new framework to  '2.4.34' which i am using in my old framework, but still the driver is downloaded automatically.

i observed that the new framework is making a call to webdriver manager API, not sure.
Please suggest

**Comment by Tanvitha** [comment]
And i tried upgrading the serenity version to 3.1.1, and the driver is downloading automatically
Thanks for the suggestion :)
