### ISSUE TITLE
needing help with opening the browser incognito mode with Serenity framework

### ISSUE THREAD

**Issue by bayrambinbir** [serenity-bdd/serenity-core#2665]
below snippet does not open chrome in incognito mode

chrome.switches = """--start-maximized;--test-type;--no-sandbox;--ignore-certificate-errors;
                   --disable-popup-blocking;--window-size=1920,1080;--disable-default-apps;--disable-extensions-file-access-check;
                   --incognito;--disable-download-notification;--disable-infobars,--disable-gpu"""

**Comment by wakaleo** [comment]
Does it work in plain Selenium? If the chrom switches do not do what you want, you probably should ask the Chrome community.

**Comment by wakaleo** [comment]
Closed presumed resolved.
