### ISSUE TITLE
Nexus IQ - Vulnerability reported in serenity-core. Related to DataTables . Please include fixes from DataTables.net

### ISSUE THREAD

**Issue by Dineshtj** [serenity-bdd/serenity-core#2667]
We use Nexus for repository management. Nexus IQ  flagged a critical security vulnerability (CVSS score > 9) in serenity-core and this resulted in all versions of serenity-core being quarantined. This causes the jenkins job to fail following a maven build failure. The issue seems to be existing in the js file. https://github.com/serenity-bdd/serenity-core/blob/master/serenity-report-resources/src/main/resources/report-resources/datatables/1.10.20/DataTables-1.10.20/js/jquery.dataTables.js 

This code is vulnerable to prototype pollution. Please see - https://github.com/advisories/GHSA-m7j4-fhg6-xf5v

DataTables have already provided a fix for the issue - https://github.com/DataTables/Dist-DataTables/commit/e2e19eac7e5a6f140d7eefca5c7deba165b357eb

But it seems that serenity-core  is still using an older version of the file.

Is it possible to update serenity-bdd to use a version of the jquery.dataTables.js that has a fix for the prototype pollution issue?

**Comment by wakaleo** [comment]
These files are no longer used in the code. They will be removed from the next release.

**Comment by deepnap** [comment]
@wakaleo Thanks for the update!

**Comment by Dineshtj** [comment]
@wakaleo Thanks for the update. We will wait for the next release
