### ISSUE TITLE
BeforeAWebdriverScenario with Firefox is not being called

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#2670]
I am using serenity.extension.packages and I've implemented a BeforeAWebdriverScenario to add some capabilities.

I am debugging the code and when I use chrome the method is executed, but with firefox NOT.

Version of serenity used: 3.1.5

```
public class CapabilityEnhancer implements BeforeAWebdriverScenario {
    @Override
    public DesiredCapabilities apply(EnvironmentVariables environmentVariables, SupportedWebDriver driver, TestOutcome testOutcome, DesiredCapabilities capabilities) {
        if (driver == SupportedWebDriver.FIREFOX) {
            String firefoxExtensionPath = EnvironmentSpecificConfiguration.from(environmentVariables)
                    .getProperty("firefox.plugin");

            if (isNotEmpty(firefoxExtensionPath)) {
                FirefoxProfile profile = new FirefoxProfile();
                profile.addExtension(new File(firefoxExtensionPath));
                capabilities.setCapability(FirefoxDriver.Capability.PROFILE, profile);
            }
        }

        if (driver == SupportedWebDriver.CHROME) {
            String chromeExtensionPath = EnvironmentSpecificConfiguration.from(environmentVariables)
                    .getProperty("chrome.plugin");

            if (isNotEmpty(chromeExtensionPath)) {
                URL dirUrl = ClassLoader.getSystemResource(chromeExtensionPath);

                ChromeOptions options = new ChromeOptions();

                try {
                    options.addExtensions(new File(dirUrl.toURI()));
                    capabilities.setCapability(ChromeOptions.CAPABILITY, options);
                } catch (URISyntaxException e) {
                    e.printStackTrace();
                }
            }
        }

        return capabilities;
    }
}

```

**Comment by wakaleo** [comment]
Possibly fixed in 3.1.16

**Comment by xescuder** [comment]
With the new version, it forces to implement apply and isActivated. What's the expected content of apply?

**Comment by xescuder** [comment]
Thanks! Now it works!

**Comment by xescuder** [comment]
I checked only that code enters in there, but I've not seen that now Firefox gives Forbidden:You don't have permission to access this resource, for any url.

I've removed the extension packages and checked that it happens anyway...

**Comment by xescuder** [comment]
With this new version I've realized (without extension Capability), that any url gives Forbidden permission. I've tested in Chrome and Firefox.

**Comment by wakaleo** [comment]
Do you have the stack trace?

**Comment by xescuder** [comment]
Everything seems OK. I am testing an internal application with VPN, with 3.1.15 the error does not happen. 

Starting ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}) on port 60855
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1643285818.873][WARNING]: FromSockAddr failed on netmask
ChromeDriver was started successfully.

**Comment by wakaleo** [comment]
I'm not sure I follow - are you seeing an error in 3.1.16 that wasn't in 3.1.15?

**Comment by xescuder** [comment]
No, I am saying that the Forbiden error doesn't happen with 3.1.15 version, only with 3.1.16.

**Comment by wakaleo** [comment]
Before 3.1.16, the BeforeAWebdriverScenario classes were not invoked. Do you have a stack trace or some indicator of somewhere in the Serenity code that might be causing a Forbidden error, or is it coming from your BeforeAWebdriverScenario class which is now being called?

**Comment by xescuder** [comment]
Nope. 

I've commented at serenity conf: #extension.packages = com.roche.infinity.actions. I've checked that BeforeAWebdriverScenario it not being called. 

The stack trace doesn't say anything. The browser is opened but everything gives Forbidden error on browser.

**Comment by wakaleo** [comment]
Put a breakpoint in the FirefoxDriverProvider and see what it is doing. I've never seen that behaviour before.

**Comment by xescuder** [comment]
It's failing at Chrome as well

**Comment by xescuder** [comment]
I don't see why is failing at 3.1.16 but not with previous versions

**Comment by wakaleo** [comment]
Nothing has changed in the browser initialisation in chrome between 3.1.15 and 3.1.16 if I recall correctly. Have a look at the change logs to see if there is anything obvious - the changes in 3.1.16 are mostly driven by this ticket.

**Comment by xescuder** [comment]
I think I've found what has changed in some way. 

Let me try to explain. We've used the next configuration for the last 2 years (first with properties, now with a hconf format)

1. At serenity.conf we have: 
webdriver.base.url = "http://10.120.187.181"
start.page = "#{webdriver.base.url}/Infinity"

2. The start page:

```
@DefaultUrl("page:start.page")
public class StartPage extends PageObject {
    ```

Our server does not allow to visit the page without adding the suffix Infinity. If you try to the forbidden message is shown from the server.

I've debugged the code and it seems that before executing the page, is trying to visit the url from webdriver.base.url. 

So I think that maybe before it didn't check the base url, and the navigation was only controlled by steps with page objects urls.

**Comment by xescuder** [comment]
One final comment or question. Now the BeforeWebdriverScenario apply method has redefined the parameter driver from class WebDriver to class SupportedWebDriver, and it seems this new one is not an instance of driver, so I can't call for example driver.installExtension.

How can I get the driver from BeforeAWebdriverScenario?

I've look at AfterAWebdriverScenario and the parameter class is WebDriver, but not at BeforeAWebdriverScenario.

Thanks a lot!

**Comment by wakaleo** [comment]
When BeforeAWebdriverScenario is invoked, the driver has not yet been created. In the next version you will be able to use the CustomDriverEnhancer class to do this.

**Comment by xescuder** [comment]
Great! Thanks.

**Comment by xescuder** [comment]
I've replicated the code that worked some versions ago. It's being executed to install an extension, but the extension doesn't work.

    ```
@Override
    public MutableCapabilities apply(EnvironmentVariables environmentVariables, SupportedWebDriver supportedWebDriver, TestOutcome testOutcome, MutableCapabilities mutableCapabilities) {
        if (supportedWebDriver != SupportedWebDriver.CHROME) {
            return mutableCapabilities;
        }

        String chromeExtensionPath = EnvironmentSpecificConfiguration.from(environmentVariables)
                .getProperty("chrome.plugin");

        if (StringUtils.isNotEmpty(chromeExtensionPath)) {
            URL dirUrl = ClassLoader.getSystemResource(chromeExtensionPath);

            ChromeOptions options = new ChromeOptions();

            try {
                options.addExtensions(new File(dirUrl.toURI()));
                mutableCapabilities.setCapability(ChromeOptions.CAPABILITY, options);
            } catch (URISyntaxException e) {
                e.printStackTrace();
            }
        }

        return mutableCapabilities;
    }
```
