### ISSUE TITLE
Shadow Root throws UnsupportedOperationException

### ISSUE THREAD

**Issue by PraveenHudgi1** [serenity-bdd/serenity-core#2672]
Please refer below bug for issue description.

https://github.com/SeleniumHQ/selenium/issues/10269

**Comment by wakaleo** [comment]
Can you provide a sample project?

**Comment by PraveenHudgi1** [comment]
Sorry , I did not get you .

Are you asking to share the project which we are using ?

**Comment by wakaleo** [comment]
Yes, can you provide a sample project that reproduces this issue?

**Comment by PraveenHudgi1** [comment]
Sorry , I cant provide you a sample project , Its work project , I cant share it .

Please follow below steps to reproduce by using serenity.

Steps to reproduce:

1.Create an account with uipath cloud community application from this link https://cloud.uipath.com and login into application.
2.Left side panel  have shadow element.
3.Click on apps or Action Center from the left side panel.
3.Getting an error when I am trying to click one of the option which is present at left side panel.

I am getting error when script is executing 2nd  line.

1.WebElement shadowHost = find(By.xpath("//portal-nav"));
2.SearchContext shadowRoot = shadowHost.getShadowRoot();

Error:java.lang.UnsupportedOperationException: getShadowRoot

Serinity 3.1.15(Selenium version 4.1.1)
Chrome browser:97
Windows 10
Java:8 update 251

**Comment by wakaleo** [comment]
If you can't provide a sample project to reproduce the issue it is unlikely that someone will pick up the issue to try to resolve it (unless it comes up as a support request from a commercial client). Have you tried looking into the code yourself?

**Comment by wakaleo** [comment]
Try with 3.2.0 - the Shadowdom logic has had some refactoring. Otherwise, step into the Serenity code to see what it is doing.

**Comment by wakaleo** [comment]
You can access Shadow Dom elements using the `ByShadow` locator: https://javadoc.io/doc/net.serenity-bdd/serenity-core/latest/index.html

**Comment by MilvenCossa** [comment]
I have the following error when i try to access a shadowdom element  "java.lang.UnsupportedOperationException: getShadowRoot".



Line of code that returns error: SearchContext element = getDriver().findElement(By.tagName("search-entity")).getShadowRoot();
Browser: Microsoft Edge  99.0.1150.36 
Selenium: 4.1.2
VaadinTestBench: 23.0.0
