### ISSUE TITLE
Create WebDriver with different ChromeOption by test

### ISSUE THREAD

**Issue by vayaszsolt** [serenity-bdd/serenity-core#2675]
I am using the serenity to manage the WebDriver download and creation. Right now I am using the chrome driver.

I need to extend a test in order to open the browser with different IP addresses because the application has different behavior by ip address's country.

I need to specify the '--proxy-server' ChromeOption before the WebDriver is created. This value will be different by test. Is there a before web driver hook in Serenity? So I can specify in a programmatic way the ChromeOption before the driver is created.

**Comment by globalworming** [comment]
Does this help? https://serenity-bdd.github.io/theserenitybook/latest/advanced-webdriver.html

**Comment by vayaszsolt** [comment]
@globalworming Does the custom webdriver will download the chrom drvier with the exact version in serenity.conf. 
So my concern is: Will I lose some serenity configuration related to the WebDriver creation if I will use a Custom one that will create the ChromeDriver? 
I mean the following serenity configuration:
- Chrome driver to be downloaded
- The ChromeDriver configuration can be specified in a mixed: serenitry.conf and programmatically?

**Comment by wakaleo** [comment]
If you create a custom driver you are entirely responsible for its configuration.

**Comment by wakaleo** [comment]
Closing presumed answered.
