### ISSUE TITLE
User-defined title for Step is broken if method parameter contains comma character

### ISSUE THREAD

**Issue by ovenal** [serenity-bdd/serenity-core#268]
It's possible to specify user-defined title for Step-method. The problem appears when the parameter contains comma character which is used inside Serenity to separate parameters in their text representation:
![commaislost](https://cloud.githubusercontent.com/assets/3194707/12455077/800dd97a-bf9a-11e5-997a-2e6cfb7d56bd.png)

Version: 1.1.21

**Comment by YamStranger** [comment]
Hello @ovenal. 

Thanks for this issue!

**Comment by YamStranger** [comment]
Hello @ovenal 
Thanks for fix for this issue, it is now available  under serenity-core:1.1.25-rc.3. 

If all works fine - please close this issue. 

Thanks a lot!!!

**Comment by YamStranger** [comment]
It seems that all fixed properly, so we can close this issue
