### ISSUE TITLE
I have a question is there any simple way in serenity that can handle browser notifications

### ISSUE THREAD

**Issue by prashantrbs** [serenity-bdd/serenity-core#2680]
In selenium we have like 

ChromeOptions options = new ChromeOptions();
options.addArguments("--disable-notifications");
System.setProperty("webdriver.chrome.driver","path/to/driver/exe");
WebDriver driver =new ChromeDriver(options);

Is there any easy way in the serenity that can achieve above in easies way?

**Comment by globalworming** [comment]
Probably you want chrome switches in your serenity.properties file? https://johnfergusonsmart.com/configuring-chromedriver-easily-with-serenity-bdd/

**Comment by prashantrbs** [comment]
Awesome it saved lot of rework. Thanks
