### ISSUE TITLE
selectByVisibleText deprecated - Documentation update 

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#2682]
Hi. I was using selectByVisibleText from WebElementFacade. I see is deprecated but the code doesn't say what needs to be used instead. 

I've checked documentation and is still explaining selectByVisibleText. What's the new way to do it?

Thanks!

**Comment by wakaleo** [comment]
No idea, I'm not sure why they are deprecated. Might be an error.

**Comment by wakaleo** [comment]
Fixed in 3.2.0
