### ISSUE TITLE
include @Step from Serenity in @AfterStep Hooks of Cucumber

### ISSUE THREAD

**Issue by adrianmw9** [serenity-bdd/serenity-core#2685]
When using Cucumber Hooks with @ AfterStep annotation for example, the sub-steps defined through Serenity with @ Step annotation are considered into the @ AfterStep of course. Is there a way to include them?

**Comment by wakaleo** [comment]
Include them in what?

**Comment by adrianmw9** [comment]
thanks for the reply, let's assume you have a Feature file with a @ Given step and within the @ Given step there is a call to a method that has @ Step annotation from Serenity that is shown in the report as a sub-step of the cucumber step.
If I have a @ AfterStep defined in the Hooks class printing something, the @ AfterStep hook will print it only after the execution of the Cucumber Step in the feature file, I want to have it printed also for the method that has @ Step annotation from Serenity. Similar to what the Serenity property does with FOR_EACH_ACTION. 
If that's not clear let me know
Thanks

**Comment by wakaleo** [comment]
I don't think this is possible at the moment, because the @AfterStep method is executed outside of the test execution.
