### ISSUE TITLE
serenity-junit5 depends on junit4 classes

### ISSUE THREAD

**Issue by zeners** [serenity-bdd/serenity-core#2686]
the artifact net.serenity-bdd:serenity-junit5:3.1.20.jar contains the classes
* [PendingTestException](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-junit5/src/main/java/net/serenitybdd/junit5/PendingTestException.java)
* [SkippedTestException](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-junit5/src/main/java/net/serenitybdd/junit5/SkippedTestException.java)

which both extends the junit4 class org.junit.AssumptionViolatedException instead of org.opentest4j.TestAbortedException, like the org.junit.jupiter.api.Assumptions#throwTestAbortException use on assumption violation.

**Comment by wakaleo** [comment]
Well spotted. Can you propose a PR?

**Comment by zeners** [comment]
yes .. will take a moment ...

**Comment by zeners** [comment]
and done

**Comment by zeners** [comment]
is there any chance to get rid of 
`import static org.junit.Assert.assertTrue;`
in [PredicateConsequence](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay/src/main/java/net/serenitybdd/screenplay/PredicateConsequence.java)?

**Comment by wakaleo** [comment]
Why do you want to get rid of it?

**Comment by zeners** [comment]
it's the last dependency to junit4 in our use-case

currently i excluded junit4 (with own Assert.assertTrue, forwading to junit5 Assertions.assertTrue) to ensure all Tests are of junit5 and developers are not irritated in choosing the 'correct' `@Test` annotation.

**Comment by zeners** [comment]
in the meantime done by 56cb636636557e8f3a573eb2bff1394b3aacb3f8
great thanks
