### ISSUE TITLE
@BeforeAll Tag is not triggering while running from terminal(serenity version 3.1.20)

### ISSUE THREAD

**Issue by sandlok** [serenity-bdd/serenity-core#2688]
Hi All,
I am using latest serenity version with Cucumber 7 to use BeforeAll tag. This Tag is running fine when executing the test scenarios from feature file. However when executing the scenarios from terminal(mvn clean install) the @BeforeAll tag is not working. Please advise.

My Pom file
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>ExampleAutomation</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

 
     <properties>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            <serenity.core.version>3.1.20</serenity.core.version>
            <serenity.cucumber6.version>${serenity.core.version}</serenity.cucumber6.version>
            <serenity-rest-assured.version>${serenity.core.version}</serenity-rest-assured.version>
            <serenity-maven-plugin.version>${serenity.core.version}</serenity-maven-plugin.version>
            <serenity-jira-plugin.version>1.12.0</serenity-jira-plugin.version>
            <groovy-all.version>3.0.8</groovy-all.version>
            <slf4j-simple.version>1.7.9</slf4j-simple.version>
            <assertj-core.version>3.20.2</assertj-core.version>
            <commons-net.version>3.3</commons-net.version>
            <aspectj.version>1.9.7</aspectj.version>
            <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
            <json-unit.version>2.27.0</json-unit.version>
            <parallel.tests>3</parallel.tests> 
            <junit.version>5.6.0</junit.version>
			<junit.jupiter.version>${junit.version}</junit.jupiter.version>
			<junit.vintage.version>${junit.version}</junit.vintage.version>
			<junit.platform.version>1.6.0</junit.platform.version>
          </properties>
   		 <repositories>
       	 <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray</name>
            <url>https://jcenter.bintray.com</url>
       	 </repository>
  	 	 </repositories>
   		 <pluginRepositories>
       	 <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray-plugins</name>
            <url>https://jcenter.bintray.com</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>0.15</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.9</version>
        </dependency>
        <dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20180813</version>
		</dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.9</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>2.9.9</version>
        </dependency>
       	 <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.10</version>
            <scope>provided</scope>
        </dependency>

 		 <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.0.13</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.core.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
         <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.core.version}</version>
            <scope>test</scope>
        </dependency>
        
       <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.core.version}</version>
            <scope>test</scope>
        </dependency> 
      			  <dependency>
   			 <groupId>org.junit.jupiter</groupId>
    		<artifactId>junit-jupiter-api</artifactId>
   			 <version>5.8.2</version>
   			 <scope>test</scope>
				</dependency>
        
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.6.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.fge</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.2.6</version>
        </dependency>
        <dependency>
    			<groupId>io.cucumber</groupId>
    			<artifactId>cucumber-java8</artifactId>
   				 <version>7.0.0</version>
    			<scope>test</scope>
			</dependency>
			<dependency>
   				 <groupId>io.cucumber</groupId>
  				  <artifactId>cucumber-junit</artifactId>
   				 <version>7.0.0</version>
   				 <scope>test</scope>
			</dependency>
       
   			 </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                     <testFailureIgnore>true</testFailureIgnore>
                    <skip>false</skip>
                     <includes>
                        <include>CucumberTestSuite.java</include>
                    </includes>
                </configuration>
            </plugin> 
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <includes>
                        <include>**/*TestSuite.java</include>
                    </includes>
                 	 <threadCount>${parallel.tests}</threadCount> 
                	  <forkCount>${parallel.tests}</forkCount>
                 	  <parallel>methods</parallel>   
       				<useUnlimitedThreads>true</useUnlimitedThreads>  
                    <systemPropertyVariables>
                    <report>true</report>
                    <environment>{environment}</environment>
                    </systemPropertyVariables>
          	   </configuration> 
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.core.version}</version>
                 <configuration>
            				 <tags>${tags}</tags>
            				  <reports>single-page-html</reports> 
        		</configuration>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                         <configuration>
                     
                 	 </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by wakaleo** [comment]
You can't run Serenity tests directly from the feature file. Looks like your pom.xml has some dependency conflicts - resolve these and see if the problem persists.

**Comment by sandlok** [comment]
@wakaleo I have tried again with resolving conflicts in Pom. Still @BeforeAll code is not triggering from terminal(mvn clean install)

**Comment by wakaleo** [comment]
It looks like BeforeAll and AfterAll are not supported by versions of Cucumber 7 before 7.2.1. This will be included in the standard Serenity dependencies in versions 3.2.0 onwards.

**Comment by jakimcho** [comment]
Hi @wakaleo I'm also experiencing the same Problem. the hooks @BeforeAll and @AfterAll are not executed when run with serenity and cucumber 7
I have created a simple project that logs messages on defferent cucumber Hooks: https://github.com/jakimcho/SerenityCucumber7
There are three branches and only the one with Cucumber 7.1.0 without serenity,  logs messages from the @BeforeAll and @AfterAll hooks.

**Comment by wakaleo** [comment]
See my previous comment.

**Comment by jakimcho** [comment]
I saw it. Just wanted to point out that my plain cucumber project uses a cucumber version before 7.2.1 and the hooks work as expected.

**Comment by wakaleo** [comment]
@jakimcho OK, thanks. I knew this was introduced in 7.2.1 or earlier, but didn't know the precise version.

**Comment by sandlok** [comment]
@wakaleo when is the new serenity release planned(3.2.0)

**Comment by wakaleo** [comment]
> @wakaleo when is the new serenity release planned(3.2.0)

When it is ready.

**Comment by sandlok** [comment]
> > @wakaleo when is the new serenity release planned(3.2.0)
> 
> When it is ready.

Ok.Thanks
