### ISSUE TITLE
Editor Issue While build the application? 

### ISSUE THREAD

**Issue by nilimajagtap** [serenity-bdd/serenity-core#269]
Error:1	The type 'System.ComponentModel.DisplayNameAttribute' exists in both 'd:\Workspace\KLMS\packages\Serenity.Script.1.9.1\lib\net2\Serenity.Script.UI.dll' and 'c:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll'	D:\Workspace\KLMS\Serene\Serene.Script\Northwind\Note\HtmlBasicContentEditor.cs	7	14	Serene.Script

Error:2	The type or namespace name 'DisplayName' could not be found (are you missing a using directive or an assembly reference?)	D:\Workspace\KLMS\Serene\Serene.Script\Northwind\Note\HtmlBasicContentEditor.cs	7	14	Serene.Script

**Comment by wakaleo** [comment]
Hi,

I think this issue is not in the right repository - Serenity BDD does not support .NET at this stage.
