### ISSUE TITLE
Does Serenity 2.0.0 supports multiple tag?

### ISSUE THREAD

**Issue by Manish123chandel** [serenity-bdd/serenity-core#2691]
Hi @wakaleo , @ptillemans , @jeffjensen 

I am trying to execute the test cases and i have tagged testcases with multiple names.

I ran following command to execute the testcases as below

 `mvn -U Verify -Dtags="TagName1,TagName2"`

but I can see it is not able to filter any testcase and not executing any tests.

Although I am able to execute test case with one tag like below

`mvn -U verify -Dtags="TagName"`

I am using Serenity 2.0.0 version for our project.

Please let me know your thoughts? whether multitags has been removed in 2.0.0 upgrade as earlier in 1.9.* version it was supported.

**Comment by arustamov** [comment]
Hi @Manish123chandel,
Let me share my experience as I'm here posting in another thread.
**tags** shortcut version never worked for me for any expression that is more complex than just a single tag reference. So if you run through Cucumber suggest using -Dcucumber.filter.tags version where Cucumber tag expressions supported in full

**Comment by Manish123chandel** [comment]
hi @arustamov ,
Thanks for commenting your thoughts.
I think we are not using running through cucumber so we cant use this -Dcucumber.filter.tags.
**Should i assume that this doesn't support multiple tags?**

Please let me know your thoughts?

**Comment by wakaleo** [comment]
Serenity 2.0.0 is quite old, and from memory only Cucumber tag expressions are supported. In the latest version you can also use JUnit 5 tags (https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-filter-tags).

**Comment by Manish123chandel** [comment]
Okay thanks @wakaleo . SO conclusion is version 2.0.0 doesnot support the multiple tags.
