### ISSUE TITLE
Browser Is Not Restarting On Each Feature

### ISSUE THREAD

**Issue by bliu13** [serenity-bdd/serenity-core#2692]
I used the [serenity-cucumber-starter](https://github.com/serenity-bdd/serenity-cucumber-starter) to create the tests and I wanted to try to reuse the same browser for each feature file. I tried setting `serenity.restart.browser.for.each = feature` in the `serenity.conf` file, but for some reason the Serenity no longer restarts the browser anymore for the entirety of the test run.
This is how I structured the feature files:
```
test\resources\features\one.feature
test\resources\features\two.feature
```
I have been using Screenplay, but I don't know if that made a difference.

**Comment by wakaleo** [comment]
This seems to be a bug. As a workaround you can use the @singlebrowser annotation in the feature file to run all the scenarios in a single feature.

**Comment by wakaleo** [comment]
To confirm, this feature is not supported in Cucumber and will be removed in an upcoming release.

**Comment by bliu13** [comment]
I realized that the original post was not much to go off of so I am including a [gist](https://gist.github.com/bliu13/5dfb41577ad418ebe22366d7fc8f23cf) of the changes I made to the starter template.

I only added the necessary configuration and I duplicated the sample scenario in each file and in two files.
I am not sure if the configuration is working as intended, but the test output appeared to be the example same with or without the configuration. It looked like the browser is being restarted on every scenario.

**Comment by bliu13** [comment]
Is there any additional information that I could look up about @singlebrowser? I tested out the annotation and this is what I have done:
```
@singlebrowser
Feature: Feature_File_1
  Scenario: User searches for results
    Given the User navigated to the home page
    And the User is already logged in
    When the User types information on the search bar
    Then the User should see the results

@singlebrowser
Feature: Feature_File_2
  Scenario: User logs in on app and logs out
    Given the User navigated to the home page
    And the User is not logged in
    When the User clicks on the sign in button
    Then the User should see login page
    When the User enters credentials
    And the User clicks on the Sign In button
    Then the User should see the home page
    When the User clicks on the log out button
    Then the User should see the log out page

  Scenario: User will log in automatically if not logged in
    Given the User navigated to the home page
    And the User is already logged in
    Then the User should see the home page
    And the User should see the logout button
```
I was experiencing some weird issues. I was expecting Serenity to use a different browser for each feature file, but it looked like Serenity used the same browser for all feature files. The reason why I was trying to reuse the same browser was because I wanted to reuse the same login session for multiple tests.

There were also other behaviors I observed where if we had something like this:
```
Feature: Feature_File_1
  Scenario: File_1_Scenario_1
    ...
  Scenario: File_1_Scenario_2
  ...

Feature: Feature_File_2
  @singlebrowser
  Scenario: File2_Scenario_1
    ...

  @singlebrowser
  Scenario: File2_Scenario_2
    ...

Feature: Feature_File_3
  Scenario: File3_Scenario_1
    ...

  Scenario: File3_Scenario_2
    ...
```
The snippet above was interesting where Feature_File_1 would restart the browser for each scenario, but the annotation would affect Feature_File_2 and Feature_File_3 even though Feature_File_3 did not have the @singlebrowser annotation. The second observation is that it seemed like the browser is reused in for each scenario in Feature_File_2.

**Comment by wakaleo** [comment]
@singlebrowser is designed to use a single browser for the whole feature file, something we can do in JUnit. However I don't think @singlebrowser will work in all cases either, because Cucumber does not have an event that is triggered at the end of a feature.  The default behaviour (with no annotations) is a new browser for each scenario.
