### ISSUE TITLE
Missing Report-Pages when serenity.test.root is not set

### ISSUE THREAD

**Issue by zeners** [serenity-bdd/serenity-core#2698]
without serenity.test.root property set, the generated report missed `Features` and `Stories` pages

steps to reproduce:
* clone https://github.com/serenity-bdd/serenity-junit-starter.git
* disable `test.root = starter`in line 13 in `src/test/resources/serenity.conf`
* run `mvn clean verify`
* the generated report has no Stories or Features "tab" and the links to Story `Wikipedia/When Searching For Terms   1 ` and Feature `When searching for terms` going to not generated files

**Comment by wakaleo** [comment]
That is expected behavior - in JUnit, you must define the `serenity.test.root` property in order to generate the requirements reporting. What problem are you trying to solve?

**Comment by zeners** [comment]
thanks, it was suspicious to see links without content - in the past we don't set this property and at least with 2.4.34 the Feature pages has been generated
