### ISSUE TITLE
Skipping of "Steps" after failure takes too long

### ISSUE THREAD

**Issue by awallat** [serenity-bdd/serenity-core#27]
When a test has an error/failure at some point, then all following steps will still be called (probably for the report generation). The problem is that this takes much longer than before in Thucydides. Some steps need 10s to be skipped.

Here's a screenshot from a report:

![screenshot 2015-02-20 11 15 14](https://cloud.githubusercontent.com/assets/5612346/6284626/7ca53ed6-b8f2-11e4-8a79-03491f25ebff.png)

**Comment by wakaleo** [comment]
What version of serenity are you using?

**Comment by awallat** [comment]
I am using 1.0.28 (waiting for 1.0.32+ to be available from Maven)

**Comment by wakaleo** [comment]
You can try with 1.0.34 which is undergoing testing on bintray at the moment.

**Comment by wakaleo** [comment]
Fixed in 1.0.35

**Comment by awallat** [comment]
I tried version 1.0.35 and the skipped tests (which take s screenshot) still take 10s. This also happens with Chrome.

**Comment by wakaleo** [comment]
Hi Andre,

I'm not seeing this behaviour - could you put a sample project on Github
that reproduces it?

Thanks

John.

On 3 March 2015 at 22:11, André Wallat <notifications@github.com> wrote:

> I tried version 1.0.35 and the skipped tests (which take s screenshot)
> still take 10s. This also happens with Chrome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/27#issuecomment-76926938>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________
