### ISSUE TITLE
 Serenity.setSessionVariable scope for hooks(@BeforeAll)

### ISSUE THREAD

**Issue by sandlok** [serenity-bdd/serenity-core#2704]
Hi @wakaleo 
Thanks for code fix for @BeforeAll and @AfterAll hookup(3.2.0 version). However I have a use-case where in need to setup 
something like this.
@BeforeAll
Serenity.setSessionVariable("token_id").to(accessToken);
The above "token_id" I want to retrieve it in Scenario
Serenity.getCurrentSession().get("token_id")-------This is giving null pointer exception. How to resolve this one

**Comment by wakaleo** [comment]
Session data is cleared before each session by default. If you want to preserve session data between sessions, you need to set the `serenity.maintain.session` property to `true` (see https://github.com/serenity-bdd/serenity-core/blob/cf153613df2b2c4ff2a8b6cc680748f1158e087b/serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java#L1354).

**Comment by wakaleo** [comment]
Looks like it is behaving as expected. If you are running parallel tests, each parallel thread has it's own session. @BeforeAll methods are called in a different thread, and don't have access to the sessions used by the parallel tests. If you need to run your tests in parallel, you can either use a static variable or use a @Before method to run at the start of each scenario.

**Comment by sandlok** [comment]
Got it Thanks
