### ISSUE TITLE
BeforeAWebdriverScenario not being called? - Serenity 3.1.20

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#2705]
Hi. After upgrading to 3.1.20, I am debugging my extensions and it seems they are not being called.

serenity.conf:
```
serenity {
  extension.packages = com.infinity.fixtures
```

class:
```
package com.infinity.fixtures;

public class BrowserExtensionEnhancer implements BeforeAWebdriverScenario {
    @Override
    public MutableCapabilities apply(EnvironmentVariables environmentVariables, SupportedWebDriver supportedWebDriver, TestOutcome testOutcome, MutableCapabilities mutableCapabilities) {
```

Thanks a lot.

**Comment by wakaleo** [comment]
Could you try with 3.2.0, it seems to work fine with that version.

**Comment by xescuder** [comment]
I've upgrade to 3.2.0 but it seems is not being called.

**Comment by wakaleo** [comment]
Put a breakpoint in the `PreScenarioFixtures` class to see why it is not loading the classes for your project.

**Comment by xescuder** [comment]
PreScenarioFixtures neither is being called :(

**Comment by wakaleo** [comment]
Sound's like you mght have a version conflict - check that all of the Serenity libraries are using the same version.

**Comment by xescuder** [comment]
Maybe, but I am checking it and it seems all are using the same version:

![dependencies](https://user-images.githubusercontent.com/1093095/153593718-eb99d3cd-eb3f-47cb-bc0e-41cd30f3fb75.png)

**Comment by wakaleo** [comment]
I can't reproduce the issue - can you produce a sample project that reproduces this behaviour? What driver are you using?

**Comment by xescuder** [comment]
Using Chrome:

```
webdriver {
    driver=chrome
    # Implicit Waits are used to ensure that Serenity does not fail a test if a web element is not immediately
    # present on the page when you first try to use it.
    # Fluent Waits make Serenity wait for an element that is already present on the page to become visible or
    # enabled, before interacting with it
    timeouts {
      implicitlywait = 5000
      fluentwait = 10000
    }
}
```

**Comment by wakaleo** [comment]
It should work fine; I suspect a project-specific issue of some kind, which I can't troubleshoot without seeing your project. Put a breakpoint in the newInstance() method of the ChromeDriverProvider class and step through the code - it should call your custom classes in the enhancedCapabilitiesConfiguredIn() method. Step into that method and see what it does.

**Comment by xescuder** [comment]
Sorry, but I've already debugged and I don't see any code where is calling the extensions. I've not seen any code to do it (see below):

```
    private MutableCapabilities enhancedCapabilitiesConfiguredIn(EnvironmentVariables environmentVariables, String options) {
        MutableCapabilities capabilities = this.chromeDriverCapabilitiesDefinedIn(environmentVariables, options).getCapabilities();
        CapabilityEnhancer enhancer = new CapabilityEnhancer(environmentVariables, this.fixtureProviderService);
        return enhancer.enhanced(capabilities, SupportedWebDriver.CHROME);
    }

    private ChromeDriverCapabilities chromeDriverCapabilitiesDefinedIn(EnvironmentVariables environmentVariables, String options) {
        return new ChromeDriverCapabilities(environmentVariables, options);
    }
}



   public MutableCapabilities enhanced(MutableCapabilities capabilities, SupportedWebDriver driver) {
        CapabilitySet capabilitySet = new CapabilitySet(this.environmentVariables);
        this.addExtraCapabilities(capabilities, capabilitySet);
        if (ThucydidesSystemProperty.ACCEPT_INSECURE_CERTIFICATES.booleanFrom(this.environmentVariables, false) && capabilities instanceof DesiredCapabilities) {
            ((DesiredCapabilities)capabilities).acceptInsecureCerts();
        }

        this.addCapabilitiesFromFixtureServicesTo(capabilities);
        AddEnvironmentSpecifiedDriverCapabilities.from(this.environmentVariables).forDriver(driver).to(capabilities);
        if (StepEventBus.getEventBus() != null && StepEventBus.getEventBus().isBaseStepListenerRegistered()) {
            Optional<TestOutcome> currentTestOutcome = StepEventBus.getEventBus().getBaseStepListener().latestTestOutcome();
            if (currentTestOutcome != null && currentTestOutcome.isPresent()) {
                AddCustomDriverCapabilities.from(this.environmentVariables).withTestDetails(driver, (TestOutcome)currentTestOutcome.get()).to(capabilities);
            }
        }

        if (driver.isW3CCompliant()) {
            capabilities = capabilities.merge(W3CCapabilities.definedIn(this.environmentVariables).withPrefix("webdriver"));
        }

        return capabilities;
    }

```

**Comment by xescuder** [comment]
I only see this reference to the extensions package in the debugging, but it's expecting my class implements CustomChromeOptions, not BeforeAWebdriverScenario

![capture](https://user-images.githubusercontent.com/1093095/153603344-e4aa6dc1-16f2-4e1a-a139-a34cc357121a.png)

**Comment by wakaleo** [comment]
That's the wrong class - this is where you should be looking:

ChromeDriverProvider.java
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/55986/153605344-cfb99540-8c1f-4b9f-8c1b-83a9805c9756.png">

CapabilitiesEnhancer.java
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/55986/153605394-9e544eb4-3232-4924-a5cc-c7bfa4a7a089.png">

AddCustomDriverCapabilities.java
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/55986/153605551-52bb81ad-9804-4798-bf9c-464760d0483f.png">

PreScenarioFixtures.java
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/55986/153605625-2150bbeb-94ac-4462-bfdb-947bc5eb1b0b.png">

**Comment by xescuder** [comment]
I've seen the problem it that it doesn't enter in the code because the next condition is false (no base step listener is registered).

```
if (StepEventBus.getEventBus() != null && StepEventBus.getEventBus().isBaseStepListenerRegistered()) {
            Optional<TestOutcome> currentTestOutcome = StepEventBus.getEventBus()

```      

I don't see why...

**Comment by xescuder** [comment]
This happens because I am debugging from feature. It works if I debug from TestRunner.

**Comment by wakaleo** [comment]
You can't run a Serenity test directly from the feature, you need to run it through a test runner.

**Comment by xescuder** [comment]
Well, except for the BeforeAWebDriver, everything else was working executing/debugging directly from the feature.

**Comment by wakaleo** [comment]
It will work partially but the classes will not be all configured, so it won't work the way you expect.

**Comment by xescuder** [comment]
Thanks!

**Comment by AlexanderGamarra** [comment]
HI @xescuder, I have troubles to call BeforeAWebdriverScenario.

This is my code:

************ serenity.properties ************

webdriver.driver = chrome
serenity.extension.packages=net.serenitybdd.browserstack.BeforeABrowserStackScenario


*********** BeforeABrowserStackScenario ***********

        @Override
    public MutableCapabilities apply(EnvironmentVariables environmentVariables,
                                     SupportedWebDriver driver,
                                     TestOutcome testOutcome,
                                     MutableCapabilities capabilities) {

        if (driver == SupportedWebDriver.CHROME) {
            String chromeExtensionPath = "src/test/resources/extension/prc1/prc1.crx";

            if (isNotEmpty(chromeExtensionPath)) {
                URL dirUrl = ClassLoader.getSystemResource(chromeExtensionPath);

                ChromeOptions options = new ChromeOptions();

                try {
                    options.addExtensions(new File(dirUrl.toURI()));
                    capabilities.setCapability(ChromeOptions.CAPABILITY, options);
                } catch (URISyntaxException e) {
                    e.printStackTrace();
                }
            }
        }

        return capabilities;

    }



My serenity conf don't recognize my class that implements Before Webdriver Scenario.
Please if u can help me let me know.

I'm using serenit-bdd 3.2.0

**Comment by xescuder** [comment]
Hi. I finally solved using FixtureService. This is my code using chrome and firefox extensions:

`import net.thucydides.core.fixtureservices.FixtureException;
import net.thucydides.core.fixtureservices.FixtureService;
import net.thucydides.core.util.PathProcessor;
import org.openqa.selenium.MutableCapabilities;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;

import java.io.File;

public class BrowserFixtureService  implements FixtureService {
    private static final String CHROME_EXTENSION = "classpath:plugins/chrome-extension.crx";
    private static final String FIREFOX_EXTENSION = "classpath:plugins/firefox-extension.xpi";

    private static final String DOM_DISABLE_WINDOW_MOVE_RESIZE = "dom.disable_window_move_resize";

    @Override
    public void addCapabilitiesTo(MutableCapabilities capabilities) {
        if (capabilities.getBrowserName().equals("chrome")) {
            ChromeOptions options = new ChromeOptions();

            PathProcessor pathProcessor = new PathProcessor();
            String extensionPath = pathProcessor.normalize(CHROME_EXTENSION);
            options.addExtensions(new File(extensionPath));
            capabilities.setCapability(ChromeOptions.CAPABILITY, options);
        }

        if (capabilities.getBrowserName().equals("firefox")) {
            FirefoxOptions options = new FirefoxOptions();
            options.setProfile(buildFirefoxProfile());
            capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, options);

        }
    }

    private FirefoxProfile buildFirefoxProfile() {
        PathProcessor pathProcessor = new PathProcessor();
        String extensionPath = pathProcessor.normalize(FIREFOX_EXTENSION);

        FirefoxProfile profile = new FirefoxProfile();
        profile.addExtension(new File(extensionPath));
        return profile;
    }
}
`
