### ISSUE TITLE
Getting driverConfigurationException for remotedriver with cause NO BaseStepListener has been registered when use @beforeClass annotation

### ISSUE THREAD

**Issue by remyanekkuth** [serenity-bdd/serenity-core#2708]
In my framework, I have cucumber tests also junit test. Cucumber test runs with @Runwith(cucumberwithSerenity.class) . I gave parameterised test that runs with @RunWith(SerenityParameterizedRunner.class). All my test cases were working. 

As part of my enhancement, I added a new method which contains info that needs to be printed or returned before each class . So I used @BeforeClass annotation. 

Surprisingly, after that my test failing with couldn’t instantiate chrome remote driver and caused by is “No baseListener registered”. 
My jUnit test cases is working fine though. 

When I remove @BeforeClass my test is working fine. Is there is any work around to make this work. 

Please help

**Comment by wakaleo** [comment]
This is normal behaviour. The Webdriver instances are created as part of the test lifecycle, and are not available in @BeforeClass or @BeforeAll methods.

**Comment by remyanekkuth** [comment]
@wakaleo Oh ok. Then why jUnit test cases are passing when I’m giving @BeforeClass. Only the classes which has RunWith CucumberWithSerenity and data driven tests are failing. The map that I’m returning, I can still see it in console but right after that I am getting error for cucumber and datadriven tests. 

I am trying to return a map which includes from where the test triggered, session id, browser name etc. 
I need this info printed only once not in test level. Is there any work around to return this if annotations won’t work.

**Comment by wakaleo** [comment]
There will be a different browser session for each test, or each feature, or each execution thread, and sometimes multiple browsers per test, so having the browser name/session id captured only once doesn't make much sense in the context of a Serenity test suite. In each test you can see this sort of details in the Info page, e.g

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/55986/154293694-6d922e2a-18cd-4c07-86ee-711668f99df5.png">

**Comment by remyanekkuth** [comment]
The requirement for me is, if test is triggered from Jenkins I have to return the key and value for that, along with nodeId, sessionId, etc. if running from IDE , I will return MANUAL as a value for source. Along with that, I will return the browserName and all in console . 

having each @Test returns these info doesn’t have a value added, since we are mentioning the browser, version etc in Jenkins or as part of run configuration. We are running test with grid, so sessionId  and nodeId will also be for that entire session. 

eg: 
SourceName: JENKINS
Browser: chrome 
Version: 96.xx
SessionID: 1234

Is there a way to print it once.

**Comment by wakaleo** [comment]
No. As I said, the Session ID will be different for each browser instance, and therefore for each test. If you just want to log this information once, as part of your Jenkins build, do it as part of your Jenkins build job, not as part of the Serenity tests.

**Comment by wakaleo** [comment]
No problem. In that case can we close this issue or is there something else you wanted to clarify?

**Comment by remyanekkuth** [comment]
> No problem. In that case can we close this issue or is there something else you wanted to clarify?

No . I’m good. Thanks again
