### ISSUE TITLE
java: package net.serenitybdd.junit.runners does not exist

### ISSUE THREAD

**Issue by anshubhatt09** [serenity-bdd/serenity-core#2710]
Hi 
I am new to serenity and following the online training material from Dojo website. I have followed step by all instrcutions but it is throwing this error 

java: package net.serenitybdd.junit.runners does not exist

here it the code snippet 

**********************************************************************************

package serenityswag.authentication;

import net.serenitybdd.junit.runners.SerenityRunner;
import net.thucydides.core.annotations.Managed;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.WebDriver;

@RunWith(SerenityRunner.class)
public class WhenLoginOn {

    @Managed
    WebDriver driver;

**Comment by wakaleo** [comment]
Make sure you have the serenity-junit dependency in your project dependencies, e.g. 
```
<dependency>
  <groupId>net.serenity-bdd</groupId>
  <artifactId>serenity-junit</artifactId>
  <version>3.2.0</version>
</dependency>
```

**Comment by anshubhatt09** [comment]
it worked thanks. I have cloned the project as per video instructions. 
where do we get such missing dependencies?

**Comment by wakaleo** [comment]
No problem. The best way is to look at the starter projects, e.g. https://github.com/serenity-bdd/serenity-junit-starter

**Comment by Laxmankere** [comment]
Same issue i also got,
