### ISSUE TITLE
Ensure is not auto filled and is not part of the list when I try to use it. If I use it I get and error with Cannot resolve symbol 'Ensure'.

### ISSUE THREAD

**Issue by sakhedingi** [serenity-bdd/serenity-core#2714]
Ensure is not auto filled and is not part of the list when I try to use it. If I use it I get and error with Cannot resolve symbol 'Ensure'. I am still new and learning serenity bdd with screenplay pattern. Could you please assist?
<img width="468" alt="2022-02-18_18h27_40" src="https://user-images.githubusercontent.com/46962472/154722877-555e1c06-b415-498a-9616-6f327ff8ed68.png">

<img width="454" alt="2022-02-18_18h28_15" src="https://user-images.githubusercontent.com/46962472/154722992-71cdda64-b0e1-40bb-84e6-cf1f6030af9a.png">

**Comment by sakhedingi** [comment]
Hi @wakaleo, thanks for the feedback. But seems like it is there in my pom.xml file...
<img width="437" alt="image" src="https://user-images.githubusercontent.com/46962472/154732039-1111964d-922e-43ca-a3eb-2262c2cd605f.png">
<img width="303" alt="2022-02-18_19h25_21" src="https://user-images.githubusercontent.com/46962472/154732168-0a94faeb-605a-4d0c-a700-2129b85d5401.png">

**Comment by wakaleo** [comment]
Try importing the class directly:
```
import net.serenitybdd.screenplay.ensure.Ensure;
```

Your IDE caches may need updating as well.

**Comment by sakhedingi** [comment]
I tried but still not recognized. Let me try to update my IDE.
<img width="644" alt="image" src="https://user-images.githubusercontent.com/46962472/154733800-b17b8d6a-53fa-4679-ae40-76c3696fac8e.png">

**Comment by sakhedingi** [comment]
Resolved. I had to update my IDE to the lates version 2021. Thanks @wakaleo .
