### ISSUE TITLE
How to update project to serenity 3.2.0 with junit 5 and cucumber

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2720]
Hi there,

I'd like to update our serenity cucumber test project to the lastest serenity version 3.2.0 and switch to junit 5, too. Before, we were having the below setup applied:
```
    testImplementation "net.serenity-bdd:serenity-core:2.5.8"
    testImplementation "net.serenity-bdd:serenity-junit:2.5.8"
    testImplementation "net.serenity-bdd:serenity-cucumber6:2.5.8"
    testImplementation "net.serenity-bdd:serenity-rest-assured:2.5.8"
    testImplementation "org.junit.vintage:junit-vintage-engine:5.7.2"
```
I was already trying with this setup:
```
    testImplementation "net.serenity-bdd:serenity-core:3.2.0"
    testImplementation "net.serenity-bdd:serenity-junit:3.2.0"
    testImplementation "net.serenity-bdd:serenity-junit5:3.2.0"
    testImplementation "net.serenity-bdd:serenity-cucumber:3.2.0"
    testImplementation "net.serenity-bdd:serenity-rest-assured:3.2.0"
    testImplementation "org.junit.vintage:junit-vintage-engine:5.7.2"
```
I'm aware that "serenity-junit" and "junit-vintage-engine" should not be included but excluding them causes our tests to fail at present. Our tests are currently annotated the old way:
```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        features = "classpath:/features/common/login/Login.feature",
        glue = {"steps.common.login"})
public class LoginTest extends BaseTest {
}
```
When running the above test the browser session is not closed after the scenario is finished. The @SingleBrowser annotation is not working with our setup.

Please, provide a correct dependency stack for serenity 3.2.0 with cucumber and junit 5. Please, tell us how to adapt the above test case to run with junit 5.

Thank you and best regards,
André.

**Comment by aybartsch** [comment]
Update: Changing the property from "serenity.use.unique.browser" to "serenity.use.single.browser" could solve the single browser problem.

**Comment by nitinjain0512** [comment]
With serenity 3.2 .. I ma facing problem on opening the browser.. did u face the issue? Can u share your open broswer function and pom.xml file.

**Comment by wakaleo** [comment]
> With serenity 3.2 .. I ma facing problem on opening the browser.. did u face the issue? Can u share your open broswer function and pom.xml file.

Are you sure you are not running the tests in headless mode?

**Comment by nitinjain0512** [comment]
Yes. not running in headless mode..

**Comment by aybartsch** [comment]
@nitinjain0512 I'm not facing any problems when open the browser and I'm using gradle as build tool. (Thus, no pom.xml is available.)

**Comment by aybartsch** [comment]
@wakaleo Hi John. Could you please provide a working dependency stack for serenity 3.2.0 running with cucumber and junit 5?

**Comment by wakaleo** [comment]
Do you mean running Cucumber via JUnit 5?

**Comment by aybartsch** [comment]
I think yes. I'd like to migrate my initial stack to support latest serenity version plus cucumber plus junit5:
```
    testImplementation "net.serenity-bdd:serenity-core:2.5.8"
    testImplementation "net.serenity-bdd:serenity-junit:2.5.8"
    testImplementation "net.serenity-bdd:serenity-cucumber6:2.5.8"
    testImplementation "net.serenity-bdd:serenity-rest-assured:2.5.8"
    testImplementation "org.junit.vintage:junit-vintage-engine:5.7.2"
```

**Comment by wakaleo** [comment]
If you are using JUnit 5, you need to run Serenity with Cucumber in the vintage mode, as there is no JUnit 5 runner implemented yet.

**Comment by aybartsch** [comment]
Is the below stack expected to work?
```
testImplementation "net.serenity-bdd:serenity-core:3.2.0"
testImplementation "net.serenity-bdd:serenity-junit:3.2.0"
testImplementation "net.serenity-bdd:serenity-junit5:3.2.0"
testImplementation "net.serenity-bdd:serenity-cucumber:3.2.0"
testImplementation "net.serenity-bdd:serenity-rest-assured:3.2.0"
testImplementation "org.junit.vintage:junit-vintage-engine:5.7.2"
```

**Comment by wakaleo** [comment]
Here is an example of Cucumber and Serenity running with JUnit 5: https://github.com/serenity-bdd/serenity-cucumber-starter

**Comment by wakaleo** [comment]
> @wakaleo Thanks, John. Is there a plan to provide a replacement for "CucumberWithSerenity" runner?

At some stage maybe: do you have a compelling reason why the vintage mode is not sufficient?

**Comment by aybartsch** [comment]
I just wanted to get rid of junit4 in our project including serenity tests. As far as I understand the vintage mode of junit5 is kind of a bridge to junit4. Thus, I cannot drop out junit4 completely.

**Comment by wakaleo** [comment]
Changing to JUnit 5 is lot of work, and there are other higher priority tasks that will come first - if it is important for you, you can always consider getting your company to sponsor the work to make it go faster of course.

**Comment by aybartsch** [comment]
Thanks for the offer. I will talk to my head of about this idea.
