### ISSUE TITLE
Not able to find implementation of relative locators (selenium 4) with Target 

### ISSUE THREAD

**Issue by ag-gggp** [serenity-bdd/serenity-core#2736]
I've been trying to implement the latest serenity bdd **3.2.0** (having selenium 4) in the current project. 
What I've found is that we can use some serenity methods like 👇  to create a target using Selenium 4.

`Target ele = Button.withLabel("Button1");`

But if I want to use the relative locators provided in selenium 4 like above, below, near, etc, then I don't see any binding available in serenity core.

Can anyone please suggest how can we use the relative locators like above, near, below, etc with serenity screenplay Java?

**Comment by wakaleo** [comment]
Relative locators are `By` locators, so you can use them wherever you would use a normal `By` locator, e.g.
```
Button.located(RelativeLocator.with(By.tagName("input")).above(By.id("titlebar")))
```

**Comment by ag-gggp** [comment]
Thanks a lot, @wakaleo. It worked. We're good to close this question.
