### ISSUE TITLE
QUESTION: Issue with /target/site/serenity/requirements/*-package-requirements.json after serenity v2.5.10 not populating with data from multi-execution maven builds

### ISSUE THREAD

**Issue by adeellis** [serenity-bdd/serenity-core#2737]
I am currently running version 2.1.6 and wanted to upgrade to a later version to take advantage of performance improvements. I am running a junit test setup with the serenity.test.root defined as per the documentation so that the features and stories tabs display properly on the report. This has worked well for me for a number of years with my project. It has 4 separate <execution> blocks to segregate different types of test which cannot run in the same execution (e.g. some tests have to run in sequence as they need sole use of the database, whereas several hundred tests are happy to run in parallel, hence have their own execution block where maven spins up extra forks). Hope this makes sense!

At version 2.1.6 and up to version 2.5.10, this json file under /target/site/serenity/requirements/ is fully populated with all of my test package names, features and stories and therefore the features and stories tabs work correctly on the Serenity HTML report.  All versions after 2.5.10 have only one entry in this JSON file (which I guessed is driving the report features and stories tab - apologies if I am way off here!) and is missing 99% of my features and stories. Is this a known issue or a change on purpose?

**Comment by wakaleo** [comment]
Can you provide a sample project reproducing your setup?

**Comment by adeellis** [comment]
I can do but it will be over the weekend as I'll need to create a dummy one and ensure this dummy one suffers the same fate. Thanks for the speedy reply!

**Comment by adeellis** [comment]
Hi John, I seem unable to recreate this issue on a clean dummy project using v3.1.1 with multiple execution blocks. The features and stories are all displayed as expected on the report. Please close this issue as the real fault lies inside our project somewhere, possibly a transient dependency causing a conflict or some such. I'll have to hunt for it myself.
Thanks
Ade Ellis

**Comment by adeellis** [comment]
Hi John
I am re-opening this issue after further investigation. It turns out that any test which extends my test base class will not show up in the Requirements json file in /site/serenity/requirements/ folder and thus will be omitted from the following report pages, "Requirements, Features, Stories". I have attached my sample project which run 3 tests in 3 separate execution blocks. The 3rd test will not show as a story or feature in the feature tab because it extends TestBase. If you remove the 'extends TestBase' from TestStory3 class and run 'mvn clean install', all 3 features and stories appear on the report as expected. Can you please try recreating this and let me know if you can recreate it?

[serenityissue2.zip](https://github.com/serenity-bdd/serenity-core/files/8186797/serenityissue2.zip)

**Comment by wakaleo** [comment]
Interesting. I will try to have a look when I can, though I don't think it will be any time soon. I'm not sure why a base class would make any different (I never use them myself for tests, so haven't come across this).

**Comment by adeellis** [comment]
OK thanks, but I'm not a Java developer so wouldn't really know what I was looking for.

**Comment by adeellis** [comment]
After yet further investigation and help from a developer, this has been traced to having TestBase outside of the scope of serenity.test.root. It seems that after v2.5.10, should you wish to make use of a base test class which other tests extend, then this base class this must be located underneath serenity.test.root
