### ISSUE TITLE
Validation like seeThat/Ensure is not waiting for action to complete {serenity version - 3.2.0}

### ISSUE THREAD

**Issue by ag-gggp** [serenity-bdd/serenity-core#2738]
I'm implementing the serenity latest version - **3.2.0** with cucumber. Earlier it was working fine for all sorts of validations like seeThat/Ensure. However, with the recent change to 3.2.0, the above validation calls are failing as they're not waiting for the action to complete. 

`seeThat(WebElementQuestion.the({target-locators}), isCurrentlyVisible())`

Like in my case, when I click on Continue/Submit button, the user is navigated to a new page. But the call itself is failing before coming to the landing page. The implicit wait is above 10 seconds, and the page is loading in 4 seconds.

If I revert to the old versions, like 2.5.7 it works fine.

Please suggest.

@wakaleo

**Comment by wakaleo** [comment]
That sounds like the intended behavior. `isCurrentlyVisible()` should not wait (thats what the "currently" means). Try with isVisible()

**Comment by ag-gggp** [comment]
@wakaleo 

I've tried with isVisible too, but the same behavior. Not waiting for the action to complete.

`seeThat(the({target-element}), isVisible())`

**Comment by wakaleo** [comment]
What makes you think it is not waiting? In version 3.2.0, `isVisible()` will use the `webdriver.wait.for.timeout` property to determine how long it will wait, with a default of 5 seconds. If you have any doubts, put a breakpoint in the `IsVisibleMatcher` to understand how the code works under the hood.

**Comment by ag-gggp** [comment]
Working fine, no more an issue. Happy to close it.  😄
