### ISSUE TITLE
thucydides.jira.workflow doesn't work on 1.1.1

### ISSUE THREAD

**Issue by Dmitriy84** [serenity-bdd/serenity-core#274]
pom.xml

```
...
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/*TestSuite.java</include>
                        <include>**/Test*.java</include>
                        <include>**/When*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>1.1.24</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-requirements-provider</artifactId>
                        <version>1.1.1</version>
                    </dependency>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-plugin</artifactId>
                        <version>1.1.1</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```

workflow.groovy is in src\test\resources
serenity.properties

```
thucydides.jira.workflow.active = true
thucydides.jira.workflow = workflow.groovy
```

workflow.groovy

```
when 'Open', {
    'success' should: 'Resolve Issue'
}

when 'Open', {
    'success' should: 'Resolve'
}

when 'Open', {
    'failure' should: 'Resolve'
}

when 'Reopened', {
    'success' should: 'Resolve Issue'
}

when 'Resolved', {
    'failure' should: 'Reopen Issue'
}

when 'In Progress', {
    'success' should: ['Stop Progress','Resolve Issue']
}

when 'CLOSED', {
    'failure' should: 'Reopen'
}

when 'CLOSED', {
    'success' should: 'Reopen'
}
```

**Comment by Dmitriy84** [comment]
![jira_issue](https://cloud.githubusercontent.com/assets/12140576/12582370/63a2c976-c445-11e5-8689-9ee7b46786f6.png)

**Comment by Dmitriy84** [comment]
Test results:

Reports view generated with 1 stories (of which 1 pending) containing 3 scenarios (of which 1 pending)
Failures in reports view: 1 scenarios failed

**Comment by Dmitriy84** [comment]
Issue: Jira issue statuses cannot be updated with default and defined workflow (*.groovy file)

**Comment by cliviu** [comment]
hi @Dmitriy84 . Your configuration file should be named **serenity.properties** and not **serenity.property** . Or it was a typo ?

**Comment by Dmitriy84** [comment]
Yep typo... corrected it

**Comment by cliviu** [comment]
hi @Dmitriy84, is the  *workflow.groovy* for sure in classpath ?

**Comment by cliviu** [comment]
can you post some log files , some more details ? The workflow should work, I'm not sure what can be wrong.

**Comment by Dmitriy84** [comment]
I can find it here ...\target\test-classes\workflow.groovy

```
INFO  net.serenitybdd.plugins.jira.JiraListener: Updating JIRA issue: NP-794
INFO  net.serenitybdd.plugins.jira.JiraListener: JIRA server: Connection to JIRA instance at https://****.com/jira with user ****
INFO  net.serenitybdd.plugins.jira.JiraListener: Updating comments for issue NP-794
INFO  net.serenitybdd.plugins.jira.JiraListener: WIKI Rendering activated: true
INFO  net.serenitybdd.plugins.jira.JiraListener: Updating status for issue NP-794 with test result ERROR
INFO  net.serenitybdd.plugins.jira.JiraListener: Issue NP-794 currently has status 'Closed'
INFO  net.serenitybdd.plugins.jira.JiraListener: Found transitions [] for issue NP-794
INFO  net.thucydides.core.reports.ReportService: Reporting formats: [JSON, XML, HTML]
```

Is it enough?

**Comment by Dmitriy84** [comment]
I've found issue.
 ```
when '**Closed**', {
    'success' should: 'Reopen'
}
```

Fixed my case. But I think we should use case insensitive approach for statuses.

**Comment by cliviu** [comment]
Ok, great that you have found it :-)

**Comment by YamStranger** [comment]
Thanks @Dmitriy84 
Will mask this issue as enhancement request

**Comment by amitAutoS** [comment]
@Dmitriy84 Hello ! Do you mind sharing your pom please. The JIRA issue status is getting updated for me but issue is it is getting updated twice! DOn't get it why?

31623 [main] INFO net.serenitybdd.plugins.jira.JiraListener - Updating JIRA issue: DIG-6
31623 [main] INFO net.serenitybdd.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at https://***.atlassian.net with user ***
31624 [main] INFO net.serenitybdd.plugins.jira.JiraListener - Updating comments for issue DIG-6
31624 [main] INFO net.serenitybdd.plugins.jira.JiraListener - WIKI Rendering activated: true
34864 [main] INFO net.serenitybdd.plugins.jira.JiraListener - Updating status for issue DIG-6 with test result SUCCESS
37592 [main] INFO net.serenitybdd.plugins.jira.JiraListener - Issue DIG-6 currently has status 'In Test'
37598 [main] INFO net.serenitybdd.plugins.jira.JiraListener - Found transitions [Ready For UAT] for issue DIG-6
41653 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Updating JIRA issue: DIG-6
41653 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at https://***.atlassian.net with user ***
41653 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Updating comments for issue DIG-6
41653 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - WIKI Rendering activated: true
45489 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Updating status for issue DIG-6 with test result SUCCESS
46922 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Issue DIG-6 currently has status 'Ready For UAT'
46922 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Found transitions [In UAT, Done] for issue DIG-6

**Comment by DashkevichBy** [comment]
@Dmitriy84
The same result as in previous comment. The issue is being updated twice. I've tried 1.1.1, 1.1.2-rc.1, 1.1.3-rc.1 and 1.1.3-rc.2 versions of serenity-jira-plugin but result is still the same. Does anybody know why it works like this? 
43298 [main] INFO net.serenitybdd.plugins.jira.JiraUpdater - Updating JIRA issue: BANK-1
43298 [main] INFO net.serenitybdd.plugins.jira.JiraUpdater - JIRA server: Connection to JIRA instance at http://localhost:8080/ with user jiraUser
43298 [main] INFO net.serenitybdd.plugins.jira.JiraUpdater - Updating comments for issue BANK-1
43298 [main] INFO net.serenitybdd.plugins.jira.JiraUpdater - WIKI Rendering activated: true
44546 [main] INFO net.serenitybdd.plugins.jira.JiraUpdater - Updating status for issue BANK-1 with test result SUCCESS
44671 [main] INFO net.serenitybdd.plugins.jira.JiraUpdater - Issue BANK-1 currently has status 'Open'
44671 [main] INFO net.serenitybdd.plugins.jira.JiraUpdater - Found transitions [Move to Done] for issue BANK-1
44874 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraUpdater - Updating JIRA issue: BANK-1
44874 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraUpdater - JIRA server: Connection to JIRA instance at http://localhost:8080/ with user webdrivertest04
44874 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraUpdater - Updating comments for issue BANK-1
44874 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraUpdater - WIKI Rendering activated: true
45045 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraUpdater - Updating status for issue BANK-1 with test result SUCCESS
45092 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraUpdater - Issue BANK-1 currently has status 'Done'
45092 [pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraUpdater - Found transitions [Close] for issue BANK-1
