### ISSUE TITLE
[Serenity Screenplay-Junit with Appium] ScreenshotException shows after clicking on Button

### ISSUE THREAD

**Issue by ldt0589** [serenity-bdd/serenity-core#2757]
I'm using:
```
Serenity-core 3.2
Serenity Screenplay 3.2
Junit 5
```

My code:
```
        String xpath = "//android.widget.ImageView[@content-desc="nLike"]/android.view.View";
        Target target = Target.the("button Like").located(By.xpath(xpath));
        WaitUntil.the(xpath, isClickable());
        actor.attemptsTo(Click.on(target));
```
In Serenity.conf:
```
serenity {
	test.root = starter
	compress.filenames = false
	take.screenshots = FOR_EACH_ACTION
}
```
I always get the ScreenShot Exception after clicking Like button successfully (actor.attemptsTo(Click.on(target))). 
Please help to resolve this issue.
```
org.openqa.selenium.remote.ScreenshotException: Screen shot has been taken

```

**Comment by wakaleo** [comment]
This is a Selenium error of some kind. #b906de8eb56561d78112c4ec23ce8d5040e6e569 includes a work-around to catch and report this error as a warning message.

**Comment by ldt0589** [comment]
> message

I see latest version is 3.2.1.
So could you tell the way to workaround for this issue?

**Comment by wakaleo** [comment]
Disable the screenshots or wait for version 3.2.2

**Comment by ldt0589** [comment]
> Disable the screenshots or wait for version 3.2.2. Or figure out why Selenium/Appium is reporting an error.

An application's popup will display right after clicking the Button. Cannot capture xpath of element this time (this xpath could be captured before popup shows).
I'm not sure the reason of ScreenshotException. But when set serenity.take.screenshot property is Disabled then everything is OK without Screenshot

**Comment by wakaleo** [comment]
> > Disable the screenshots or wait for version 3.2.2. Or figure out why Selenium/Appium is reporting an error.
> 
> An application's popup will display right after clicking the Button. Button is hidden and cannot capture xpath of button element this time (this xpath could be captured before popup shows). I'm not sure the reason of ScreenshotException. But when set serenity.take.screenshot property is Disabled then everything is OK without Screenshot

It might be an Appium driver bug then?

**Comment by ldt0589** [comment]
> > > Disable the screenshots or wait for version 3.2.2. Or figure out why Selenium/Appium is reporting an error.
> > 
> > 
> > An application's popup will display right after clicking the Button. Button is hidden and cannot capture xpath of button element this time (this xpath could be captured before popup shows). I'm not sure the reason of ScreenshotException. But when set serenity.take.screenshot property is Disabled then everything is OK without Screenshot
> 
> It might be an Appium driver bug then?

I'm not sure but i didn't see this issue before

**Comment by ricardorlg** [comment]
this one was hard, I was also facing the same problem, the error happens because since Serenity supports in the screenplay the method `protected PageObject currentPageVisibleTo(Actor actor)`, the implementation is adding drivers that are already added in the driversMap, when a new test starts It tries to take a screenshot using the unclosed driver because is assuming driver is still there, the fix was to change how we handle the logic to get a driver given its name and avoid having duplicated drivers in driversMap.

@wakaleo let me know what u think, PR is coming
