### ISSUE TITLE
Report size is massive due to multiple CSV files. noway to turn these off 

### ISSUE THREAD

**Issue by pankaj-huma** [serenity-bdd/serenity-core#2759]
If you run multiple tests report size goes into GBs, looking into the report folder I see multiple CSV files which is the underlying reason.

Any way to turn off ?
<img width="997" alt="Screenshot 2022-03-29 at 11 01 57" src="https://user-images.githubusercontent.com/98319955/160587326-35be8354-7ea5-44c5-9ac3-91ddac5d1705.png">

**Comment by wakaleo** [comment]
Try setting `serenity.generate.csv.reports` to false.

**Comment by wakaleo** [comment]
Closing presumed answered
