### ISSUE TITLE
Some browserstack capabilities are not working

### ISSUE THREAD

**Issue by Mike-Last** [serenity-bdd/serenity-core#276]
Whilst browserstack.url, browserstack.project, browserstack.local and browserstack.build capabilities all work fine, several others like browserstack.os do not have any effect.

I did some digging and could see the parameters are being processed to remove the browserstack prefix and passed to org.openqa.selenium.remote.RemoteWebDriver as DesiredCapabilities.  The original values including the prefix are also passed though and for whatever reason the RemoteWebDriver initialises with default os, browser, version etc..  Maybe due to the fact that it is getting passed a large number of unrecognisable capabilities?

I have overcome the issue by using a custom WebDriver the provides a RemoteWebDriver with the capabilities of my choosing.

**Comment by YamStranger** [comment]
Hello @Mike-Last!

Thanks for this issue!

It will be great if you will add some short example, how you pass parameters. Thanks a lot!

**Comment by Mike-Last** [comment]
Hi @YamStranger ,

I guess this is typical but I cannot reproduce the issue.  It all works fine, which is odd as I spent hours trying to get round it when it did not work.  I will continue to play and re-open if I come across it in a reproducible way.

FYI I was using a combination of systemPropertyVariables in maven-failsafe-plugin and serenity.properties file.  If I get some free time I will dig out one of the old revisions.

Sorry for wasting your time.

Mike

**Comment by Mike-Last** [comment]
Hi @YamStranger 

ok so I have now worked out the issue, the properties do not seem to support multiple periods.

Does not apply the right os version or browser version:
`<systemPropertyVariables>
						<browserstack.url>${my.browserstack.url}</browserstack.url>
						<browserstack.project>PROOF PROJECT</browserstack.project>
						<browserstack.build>PROOF BUILD</browserstack.build>
						<browserstack.url>${my.browserstack.url}</browserstack.url>
						<browserstack.os>Windows</browserstack.os>
						<browserstack.os.version>7</browserstack.os.version>
						<browserstack.browser>IE</browserstack.browser>
						<browserstack.browser.version>11</browserstack.browser.version>
					</systemPropertyVariables>`

Does apply the right os version and browser version:
<systemPropertyVariables>
						<browserstack.url>${my.browserstack.url}</browserstack.url>
						<browserstack.project>PROOF PROJECT</browserstack.project>
						<browserstack.build>PROOF BUILD</browserstack.build>
						<browserstack.url>${my.browserstack.url}</browserstack.url>
						<browserstack.os>Windows</browserstack.os>
						<browserstack.os_version>7</browserstack.os_version>
						<browserstack.browser>IE</browserstack.browser>
						<browserstack.browser_version>11</browserstack.browser_version>
					</systemPropertyVariables>

**Comment by ovenal** [comment]
Also faced with this problem. 
It seems that BrowserStack has changed the name of parameters to specify OS and browser version, previously "." character was used as a delimiter, now it's been changed to "_" character. As the result the tests are executed on some default setup, here's an example:
![browserstackdiffversions](https://cloud.githubusercontent.com/assets/3194707/12753124/59c4fd3c-c9ce-11e5-8a9c-966ff13be74e.png)

I fixed locally in the way similar to provided above by @Mike-Last, but it would be nice to have a fix in Serenity too.

**Comment by YamStranger** [comment]
@ovenal thanks for this description and provided solution!!
@Mike-Last it seems that this issue solved, please check it and if so - close this issue.

**Comment by Mike-Last** [comment]
Thanks!
