### ISSUE TITLE
Bootstrap 3.3.0 vulnerabilities in Serenity Report Resources

### ISSUE THREAD

**Issue by arturmalinowski** [serenity-bdd/serenity-core#2767]
Hi,

I have noticed that Serenity Report Resources comes with Bootstrap 3.3.0. There has been a number of vulnerabilities identified in older versions of bootstrap:

https://snyk.io/vuln/npm:bootstrap

Would it be possible to get bootstrap updated?

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by wakaleo** [comment]
Fixed in 3.2.4
