### ISSUE TITLE
Error ClassLoader when use CustomReporter 

### ISSUE THREAD

**Issue by carl-pki** [serenity-bdd/serenity-core#2786]
1、 definition custom reporter
![image](https://user-images.githubusercontent.com/85552832/164254491-a9902c0d-9266-40e9-8eeb-54bf504a30e9.png)
2、"ClassNotFound " show when use current ClassLoader
![47999ba09d2153fb0de2ea1517dc937](https://user-images.githubusercontent.com/85552832/164254685-dc25e2d7-6102-439c-9293-db54ceab29f0.png)
3、not error massage show when use updated ClassLoader
![image](https://user-images.githubusercontent.com/85552832/164260776-cc12ce88-0b32-45fd-ab1a-e63e4b598cbb.png)

![92c4b524a7759489e95c20bdc593a8f](https://user-images.githubusercontent.com/85552832/164254704-0db609d7-149b-4631-889a-e5ad2ed95e2b.png)

**Comment by carl-pki** [comment]
do you think i should rewtite the maven plugin?
why do not use updated classloader?

**Comment by xescuder** [comment]
Hi @carl-pki. Have you solved it? I need the same ;D

**Comment by carl-pki** [comment]
@xescuder yes, I solved it. I download source code and rewrite reportFrom method in class of SerenityAggregatorMojo. Then serenity can finds custom reporter class by serenity.properties, next I rebuild the plugin and upload to CI server. you can  at will add comments If you need other information.
``` java
    private Optional<UserStoryTestReporter> reportFrom(String key) {
        String reportClass = environmentVariables.getProperty(key);
        try {
            return Optional.of((UserStoryTestReporter) Class.forName(reportClass, true, Thread.currentThread().getContextClassLoader()).newInstance());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException e) {
            e.printStackTrace();
        }
        return Optional.empty();
    }
```

 serenity.properties

``` config 

serenity.custom.reporters.CustomReporter = com.test.report.TestMyCustomReporter


```

**Comment by xescuder** [comment]
Please, could you give me advise on how to compile the plugin? I don't know what plugin and why.

**Comment by carl-pki** [comment]
first you need know that you current used serenity version, next download source code the version same as you used, next open the serenity-maven-plugin project, finally rewrite  reportFrom method and build the plugin following below steps in picture:
![image](https://user-images.githubusercontent.com/85552832/187947452-dfe4c4be-3d1d-4a0a-944b-20ee07f2790d.png)



next copy below folder to your maven repository on your CI server same path.
![image](https://user-images.githubusercontent.com/85552832/187947978-2c9c0370-d6cb-49d0-ba40-d8a3b0f82852.png)


next you can definition a custom report class and indicate it in your serenity config file.


``` java

public class TestMyCustomReporter  extends HtmlReporter implements UserStoryTestReporter {

    Logger LOGGER = LoggerFactory.getLogger(TestMyCustomReporter.class);
    /*
     * @Parameter(property = "thucydides.project.key", defaultValue = "default")
     * public String projectKey;
     **/

    public File getOutputDirectory() {
        String absolutePath = ConfiguredEnvironment.getConfiguration().getOutputDirectory().getParentFile().getAbsolutePath();
        File tempOutputDirectory = new File(String.valueOf(Paths.get(absolutePath, "temp")));
        if (!tempOutputDirectory.exists()) {
            tempOutputDirectory.mkdir();
        }
        LOGGER.info("Output path is {}", absolutePath);
        return tempOutputDirectory;
    }

    private TestOutcomes loadTestOutcomesFrom(File sourceDirectory) throws IOException {
        return TestOutcomeLoader.loadTestOutcomes().inFormat(new FormatConfiguration(Injectors.getInjector().getProvider(EnvironmentVariables.class).get()).getPreferredFormat()).from(sourceDirectory);
    }


    public TestOutcomes generateReportsForTestResultsFrom(File sourceDirectory) throws IOException {
        EnvironmentVariables environmentVariables = Injectors.getInjector().getProvider(EnvironmentVariables.class).get();
        FreemarkerContext context = new FreemarkerContext(environmentVariables, new DefaultRequirements().getRequirementsService(),Injectors.getInjector().getInstance(IssueTracking.class), "");
        TestOutcomes allTestOutcomes = this.loadTestOutcomesFrom(sourceDirectory);
        Map<String, Object> buildContext = context.getBuildContext(allTestOutcomes, new ReportNameProvider(), true);
        try {
            LOGGER.info("ready generate custom report.");
            buildContext.put("requirementTypes", new ArrayList<>());
            Map<String, String> custom = new HashMap<>();
            String customFieldsPrefix = "serenity.custom.fields.";
            long count = environmentVariables.getKeys().stream().filter(k -> k.startsWith(customFieldsPrefix)).map(k -> custom.put(k.substring(customFieldsPrefix.length()), environmentVariables.getProperty(k))).count();
            buildContext.put("customFieldsMap", custom);
            LOGGER.info("custom fields count: {}", count);
            Configuration configuration = new Configuration(Configuration.VERSION_2_3_30);
            configuration.setClassForTemplateLoading(this.getClass(), "/");
            Template template = configuration.getTemplate("freemarker/index.ftl");
            String customReport = String.valueOf(Paths.get(this.getOutputDirectory().getAbsolutePath(), "test.html"));
            try (FileWriter writer = new FileWriter(customReport)) {
                template.process(buildContext, writer);
                LOGGER.info("SERENITY REPORTS");
                LOGGER.info("  - Custom Report: {}", Paths.get(customReport).toUri());
            }
        } catch (Exception e) {
            LOGGER.info("generate custom report fail !!", e);
        }
        return allTestOutcomes;
    }


}

```

If you want use the TestMyCustomReporter class, you need copy below resource in picture  :

![image](https://user-images.githubusercontent.com/85552832/187950158-63aa5159-26cc-4dd4-968b-e98ff668e013.png)


If you don't overwrite the reportFrom method then serenity plugin cann't find your custom report class, unless that 
' Make sure your custom report class is on the maven plugin path (which is not the same as your project dependencies).'


I'd be happy if I could help you, If you have any question please add comments.

**Comment by carl-pki** [comment]
@wakaleo Next version, Can we rewrite reportFrom method in class of SerenityAggregatorMojo? If we can do that, I will commit a Pull Request.

```
    private Optional<UserStoryTestReporter> reportFrom(String key) {
        String reportClass = environmentVariables.getProperty(key);
        try {
            return Optional.of((UserStoryTestReporter) Class.forName(reportClass, true, Thread.currentThread().getContextClassLoader()).newInstance());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException e) {
            e.printStackTrace();
        }
        return Optional.empty();
    }
```

**Comment by wakaleo** [comment]
Yes, please propose a PR and I will include it in the next release

**Comment by carl-pki** [comment]
@wakaleo When I commit the code after creating the branch I have the following problem: 
``` text

ERROR: Permission to serenity-bdd/serenity-core.git denied to carl-pki.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

```

Can you help me? If you need more information you can add comments.

**Comment by wakaleo** [comment]
You can't commit directly to the repo, you need to fork the repo and create a pull request
