### ISSUE TITLE
Question: How user proxy mobile element to invoke by InvocationHandler to close random popup on screenplay?

### ISSUE THREAD

**Issue by antuking** [serenity-bdd/serenity-core#2793]
I'm facing the issue from random popup on mobile automation testing. I read some articles about proxy design pattern and want to apply this to close the random popup via InvocationHandler. Could you guys please help me how to do this on screenplay? Thanks in advance.

**Comment by antuking** [comment]
@wakaleo @globalworming Do you guys have any suggestions?

**Comment by wakaleo** [comment]
No, I've never used that class.

**Comment by antuking** [comment]
@wakaleo How to invoke to screenplay performable/Consequence to define a dynamic method as above question?

**Comment by antuking** [comment]
Close this ticket for finding the solution
