### ISSUE TITLE
[Question]All tests are skipped when a webdriver error occurs

### ISSUE THREAD

**Issue by JonathanOrtegon-L** [serenity-bdd/serenity-core#2797]
Versions

serenity-core 3.2.4, serenity-maven-plugin 3.2.4, Selenium version 4.1.3, Appium client version 8.0.0, serenity-cucumber 3.2.4 y  Cucumber 7.2.3

In a regression execution it is happening that certain errors completely break the execution and tests are being skipped to be executed.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/77115977/165382928-1f6dd9df-4fbf-45f8-81d4-5c7f7995d171.png">
<img width="605" alt="image" src="https://user-images.githubusercontent.com/77115977/165383622-08d258d4-c733-458b-8577-9ea08fce1f5e.png">

The tests that did not start are not shown in the report and the test that caused the failure is not shown in the report either:

**Log in which a test fails using chromeDriver Headless:**

Log en el que falla un test usando chromeDriver Headless:
 org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of By.xpath: //body//div[1]/h1 (tried for 10 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87)

​  (Session info: headless chrome=100.0.4896.75)

**Next Scenario->**

The following test tries to use the ChromeDriver Headless, throws the following error and stops the execution completely (This test does not appear in the report, nor the following ones):

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: 'JonaPC.local', ip: 'fe80:0:0:0:1005:326d:54b1:ae52%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.6.4', java.version: '11.0.12'
Driver info: org.openqa.selenium.chrome.ChromeDriver

It should be noted that a migration is being carried out from serenity core 2.3.33 to the latest version 3.2.3, in the old version this problem does not occur, if a test fails due to the error of not finding an element, the next one continues without problems

**Dependency tree:**

+- net.serenity-bdd:serenity-core:jar:3.2.4:compile
[INFO] |  +- net.serenity-bdd:serenity-model:jar:3.2.4:compile
[INFO] |  |  +- org.apache.commons:commons-text:jar:1.9:compile
[INFO] |  |  +- commons-net:commons-net:jar:3.8.0:compile
[INFO] |  |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.11.0:compile
[INFO] |  |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  |  +- com.google.inject:guice:jar:5.1.0:compile
[INFO] |  |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  +- org.jsoup:jsoup:jar:1.14.3:compile
[INFO] |  |  +- com.thoughtworks.xstream:xstream:jar:1.4.19:compile
[INFO] |  |  |  \- io.github.x-stream:mxparser:jar:1.2.2:compile
[INFO] |  |  |     \- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  |  +- io.cucumber:cucumber-java:jar:7.2.3:compile
[INFO] |  |  +- com.typesafe:config:jar:1.4.2:compile
[INFO] |  |  +- org.imgscalr:imgscalr-lib:jar:4.2:compile
[INFO] |  |  +- org.freemarker:freemarker:jar:2.3.31:compile
[INFO] |  |  +- io.github.classgraph:classgraph:jar:4.8.138:compile
[INFO] |  |  +- net.sourceforge.jexcelapi:jxl:jar:2.6.12:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.12.8:compile
[INFO] |  |  \- net.bytebuddy:byte-buddy-agent:jar:1.12.8:compile
[INFO] |  +- net.serenity-bdd:serenity-report-resources:jar:3.2.4:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.9.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- commons-io:commons-io:jar:2.11.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:4.1.3:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v85:jar:4.1.3:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v97:jar:4.1.3:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v98:jar:4.1.3:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v99:jar:4.1.3:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:4.1.3:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:4.1.3:compile
[INFO] |  |  |  +- com.beust:jcommander:jar:1.82:compile
[INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.75.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-codec:jar:4.1.75.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-handler:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-classes-epoll:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-classes-kqueue:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-native-epoll:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-native-kqueue:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.75.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-resolver:jar:4.1.75.Final:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-api:jar:1.12.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-context:jar:1.12.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-exporter-logging:jar:1.12.0:compile
[INFO] |  |  |  |  +- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.12.0-alpha:compile
[INFO] |  |  |  |  \- io.opentelemetry:opentelemetry-sdk-logs:jar:1.12.0-alpha:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.12.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:jar:1.12.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:jar:1.12.0-alpha:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-trace:jar:1.12.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk:jar:1.12.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-semconv:jar:1.12.0-alpha:compile
[INFO] |  |  |  +- io.ous:jtoml:jar:2.0.0:compile
[INFO] |  |  |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  |  +- org.asynchttpclient:async-http-client:jar:2.12.3:compile
[INFO] |  |  |  |  +- org.asynchttpclient:async-http-client-netty-utils:jar:2.12.3:compile
[INFO] |  |  |  |  +- io.netty:netty-codec-socks:jar:4.1.60.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-handler-proxy:jar:4.1.60.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.60.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.60.Final:compile
[INFO] |  |  |  |  +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  |  |  \- com.typesafe.netty:netty-reactive-streams:jar:2.0.4:compile
[INFO] |  |  |  \- org.seleniumhq.selenium:selenium-http:jar:4.1.3:compile
[INFO] |  |  |     \- dev.failsafe:failsafe:jar:3.2.3:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-safari-driver:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-support:jar:4.1.3:compile
[INFO] |  |  +- com.google.auto.service:auto-service-annotations:jar:1.0.1:compile
[INFO] |  |  +- com.google.auto.service:auto-service:jar:1.0.1:compile
[INFO] |  |  |  \- com.google.auto:auto-common:jar:1.2:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-json:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:4.1.3:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-chromium-driver:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:4.1.3:compile
[INFO] |  +- io.appium:java-client:jar:8.0.0:compile
[INFO] |  |  +- commons-validator:commons-validator:jar:1.7:runtime
[INFO] |  |  |  \- commons-digester:commons-digester:jar:2.1:runtime
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.8:runtime
[INFO] |  +- org.apache.groovy:groovy:jar:4.0.1:compile
[INFO] |  +- net.sf.opencsv:opencsv:jar:2.0:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- org.fluentlenium:fluentlenium-core:jar:0.10.2:compile
[INFO] |  +- io.github.bonigarcia:webdrivermanager:jar:5.1.0:compile
[INFO] |  |  +- com.github.docker-java:docker-java:jar:3.2.13:compile
[INFO] |  |  |  +- com.github.docker-java:docker-java-core:jar:3.2.13:compile
[INFO] |  |  |  |  +- com.github.docker-java:docker-java-api:jar:3.2.13:compile
[INFO] |  |  |  |  +- org.apache.commons:commons-compress:jar:1.21:compile
[INFO] |  |  |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
[INFO] |  |  |  |     \- org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
[INFO] |  |  |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile
[INFO] |  |  +- com.github.docker-java:docker-java-transport-httpclient5:jar:3.2.13:compile
[INFO] |  |  |  +- com.github.docker-java:docker-java-transport:jar:3.2.13:compile
[INFO] |  |  |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.0.3:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents.core5:httpcore5:jar:5.0.2:compile
[INFO] |  |  |  \- net.java.dev.jna:jna:jar:5.8.0:compile
[INFO] |  |  \- org.brotli:dec:jar:0.1.2:compile
[INFO] |  +- com.jhlabs:filters:jar:2.0.235:compile
[INFO] |  +- com.paulhammant:ngwebdriver:jar:1.1.6:compile
[INFO] |  +- joda-time:joda-time:jar:2.8.2:compile
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:compile
[INFO] |  +- com.google.jimfs:jimfs:jar:1.2:compile
[INFO] |  +- org.mockito:mockito-core:jar:3.3.3:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.22.0:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  +- com.sun.xml.bind:jaxb-core:jar:2.3.0.1:compile
[INFO] |  +- com.sun.xml.bind:jaxb-impl:jar:2.3.3:compile
[INFO] |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- com.sun.activation:jakarta.activation:jar:1.2.2:compile
[INFO] |  \- javax.activation:activation:jar:1.1.1:compile
[INFO] +- net.serenity-bdd:serenity-screenplay:jar:3.2.4:compile
[INFO] +- net.serenity-bdd:serenity-screenplay-webdriver:jar:3.2.4:compile
[INFO] +- net.serenity-bdd:serenity-cucumber:jar:3.2.4:compile
[INFO] |  +- io.cucumber:cucumber-core:jar:7.2.3:compile
[INFO] |  |  +- io.cucumber:cucumber-gherkin:jar:7.2.3:compile
[INFO] |  |  +- io.cucumber:cucumber-gherkin-messages:jar:7.2.3:compile
[INFO] |  |  +- io.cucumber:messages:jar:17.1.1:compile
[INFO] |  |  +- io.cucumber:tag-expressions:jar:4.1.0:compile
[INFO] |  |  +- io.cucumber:cucumber-expressions:jar:15.0.1:compile
[INFO] |  |  +- io.cucumber:datatable:jar:7.2.3:compile
[INFO] |  |  +- io.cucumber:cucumber-plugin:jar:7.2.3:compile
[INFO] |  |  +- io.cucumber:docstring:jar:7.2.3:compile
[INFO] |  |  +- io.cucumber:html-formatter:jar:17.0.0:compile
[INFO] |  |  \- io.cucumber:ci-environment:jar:8.1.0:compile
[INFO] |  +- io.cucumber:cucumber-junit:jar:7.2.3:compile
[INFO] |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:compile
[INFO] |  \- org.apache.commons:commons-csv:jar:1.5:compile
[INFO] +- net.serenity-bdd:serenity-ensure:jar:3.2.4:compile
[INFO] |  +- net.serenity-bdd:serenity-junit:jar:3.2.4:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.0:compile
[INFO] |     +- org.jetbrains:annotations:jar:13.0:compile
[INFO] |     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.6.0:compile
[INFO] +- net.serenity-bdd:serenity-rest-assured:jar:3.2.4:compile
[INFO] |  +- io.rest-assured:rest-assured:jar:5.0.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpmime:jar:4.5.13:compile
[INFO] |  |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:compile
[INFO] |  |  +- io.rest-assured:json-path:jar:5.0.1:compile
[INFO] |  |  |  \- io.rest-assured:rest-assured-common:jar:5.0.1:compile
[INFO] |  |  \- io.rest-assured:xml-path:jar:5.0.1:compile
[INFO] |  +- org.apache.groovy:groovy-json:jar:4.0.1:compile
[INFO] |  +- org.apache.groovy:groovy-xml:jar:4.0.1:compile
[INFO] |  \- org.opentest4j:opentest4j:jar:1.2.0:compile
[INFO] +- net.serenity-bdd:serenity-screenplay-rest:jar:3.2.4:compile
[INFO] +- net.serenity-bdd.maven.plugins:serenity-maven-plugin:jar:3.2.4:compile
[INFO] |  +- org.apache.maven:maven-core:jar:3.6.3:compile
[INFO] |  |  +- org.apache.maven:maven-model:jar:3.6.3:compile
[INFO] |  |  +- org.apache.maven:maven-settings:jar:3.6.3:compile
[INFO] |  |  +- org.apache.maven:maven-settings-builder:jar:3.6.3:compile
[INFO] |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.25:compile
[INFO] |  |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
[INFO] |  |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] |  |  +- org.apache.maven:maven-builder-support:jar:3.6.3:compile
[INFO] |  |  +- org.apache.maven:maven-repository-metadata:jar:3.6.3:compile
[INFO] |  |  +- org.apache.maven:maven-artifact:jar:3.6.3:compile
[INFO] |  |  +- org.apache.maven:maven-model-builder:jar:3.6.3:compile
[INFO] |  |  +- org.apache.maven:maven-resolver-provider:jar:3.6.3:compile
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.4.1:compile
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.4.1:compile
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.4.1:compile
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.4.1:compile
[INFO] |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.2.1:compile
[INFO] |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.4:compile
[INFO] |  |  |  \- javax.enterprise:cdi-api:jar:1.0:compile
[INFO] |  |  |     \- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] |  |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.4:compile
[INFO] |  |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-component-annotations:jar:2.1.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.2.1:compile
[INFO] |  +- org.apache.maven:maven-plugin-api:jar:3.6.3:compile
[INFO] |  +- org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile
[INFO] |  |  \- org.apache.maven.doxia:doxia-sink-api:jar:1.0:compile
[INFO] |  \- org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.5:compile
[INFO] +- net.serenity-bdd:serenity-reports:jar:3.2.4:compile
[INFO] |  +- net.serenity-bdd:serenity-stats:jar:3.2.4:compile
[INFO] |  +- net.serenity-bdd:serenity-reports-configuration:jar:3.2.4:compile
[INFO] |  +- com.vladsch.flexmark:flexmark-all:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-abbreviation:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-admonition:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-anchorlink:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-aside:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-attributes:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-autolink:jar:0.34.30:compile
[INFO] |  |  |  \- org.nibor.autolink:autolink:jar:0.6.0:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-definition:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-emoji:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-enumerated-reference:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-escaped-character:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-footnotes:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-gfm-issues:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-gfm-tables:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-gfm-tasklist:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-gfm-users:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-gitlab:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-jekyll-front-matter:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-jekyll-tag:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-media-tags:jar:0.34.30:compile
[INFO] |  |  |  \- com.vladsch.flexmark:flexmark-test-util:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-ins:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-xwiki-macros:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-superscript:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-tables:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-toc:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-typographic:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-yaml-front-matter:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-ext-youtube-embedded:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-formatter:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-html-parser:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-jira-converter:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-pdf-converter:jar:0.34.30:compile
[INFO] |  |  |  +- com.openhtmltopdf:openhtmltopdf-core:jar:0.0.1-RC13:compile
[INFO] |  |  |  +- com.openhtmltopdf:openhtmltopdf-pdfbox:jar:0.0.1-RC13:compile
[INFO] |  |  |  |  +- org.apache.pdfbox:xmpbox:jar:2.0.8:compile
[INFO] |  |  |  |  \- de.rototor.pdfbox:graphics2d:jar:0.12:compile
[INFO] |  |  |  +- com.openhtmltopdf:openhtmltopdf-rtl-support:jar:0.0.1-RC13:compile
[INFO] |  |  |  |  \- com.ibm.icu:icu4j:jar:59.1:compile
[INFO] |  |  |  \- com.openhtmltopdf:openhtmltopdf-jsoup-dom-converter:jar:0.0.1-RC13:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-profile-pegdown:jar:0.34.30:compile
[INFO] |  |  +- com.vladsch.flexmark:flexmark-util:jar:0.34.30:compile
[INFO] |  |  \- com.vladsch.flexmark:flexmark-youtrack-converter:jar:0.34.30:compile
[INFO] |  \- es.nitaur.markdown:txtmark:jar:0.16:compile
[INFO] +- junit:junit:jar:4.13.1:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:2.2:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.7:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO] +- org.aeonbits.owner:owner-java8:jar:1.0.9:compile
[INFO] |  \- org.aeonbits.owner:owner:jar:1.0.9:compile
[INFO] +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.0.4:compile
[INFO] +- io.rest-assured:json-schema-validator:jar:4.5.1:compile
[INFO] |  \- com.github.java-json-tools:json-schema-validator:jar:2.2.14:compile
[INFO] |     +- com.github.java-json-tools:jackson-coreutils-equivalence:jar:1.0:compile
[INFO] |     |  \- com.github.java-json-tools:jackson-coreutils:jar:2.0:compile
[INFO] |     |     \- com.github.java-json-tools:msg-simple:jar:1.2:compile
[INFO] |     |        \- com.github.java-json-tools:btf:jar:1.3:compile
[INFO] |     +- com.github.java-json-tools:json-schema-core:jar:1.2.14:compile
[INFO] |     |  +- com.github.java-json-tools:uri-template:jar:0.10:compile
[INFO] |     |  \- org.mozilla:rhino:jar:1.7.7.2:compile
[INFO] |     +- com.sun.mail:mailapi:jar:1.6.2:compile
[INFO] |     +- com.googlecode.libphonenumber:libphonenumber:jar:8.11.1:compile
[INFO] |     +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |     \- net.sf.jopt-simple:jopt-simple:jar:5.0.4:compile
[INFO] +- com.github.mifmif:generex:jar:1.0.2:compile
[INFO] |  \- dk.brics.automaton:automaton:jar:1.11-8:compile
[INFO] +- com.github.javafaker:javafaker:jar:1.0.1:compile
[INFO] |  \- org.yaml:snakeyaml:jar:android:1.23:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.10:provided
[INFO] +- com.amazonaws:aws-java-sdk-sqs:jar:1.11.683:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.683:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.10.3:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.683:compile
[INFO] +- com.amazonaws:aws-java-sdk-dynamodb:jar:1.11.683:compile
[INFO] +- com.github.mailslurp:mailslurp-client-java:jar:5.1.0:compile
[INFO] |  +- org.threeten:threetenbp:jar:1.3.5:compile
[INFO] |  +- com.squareup.okhttp:okhttp:jar:2.7.5:compile
[INFO] |  |  \- com.squareup.okio:okio:jar:1.6.0:compile
[INFO] |  +- io.gsonfire:gson-fire:jar:1.8.0:compile
[INFO] |  +- org.apache.oltu.oauth2:org.apache.oltu.oauth2.client:jar:1.0.1:compile
[INFO] |  |  \- org.apache.oltu.oauth2:org.apache.oltu.oauth2.common:jar:1.0.1:compile
[INFO] |  |     \- org.json:json:jar:20140107:compile
[INFO] |  +- com.squareup.okhttp:logging-interceptor:jar:2.7.5:compile
[INFO] |  \- io.swagger:swagger-annotations:jar:1.5.17:compile
[INFO] +- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- org.apache.pdfbox:pdfbox:jar:2.0.8:compile
[INFO] |  \- org.apache.pdfbox:fontbox:jar:2.0.8:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.6:compile
[INFO] |  \- org.apache.httpcomponents:httpcore:jar:4.4.10:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.3:compile
[INFO] +- org.awaitility:awaitility:jar:3.0.0:compile
[INFO] |  +- org.hamcrest:hamcrest-library:jar:2.2:compile
[INFO] |  \- org.objenesis:objenesis:jar:2.5.1:compile
[INFO] +- org.awaitility:awaitility-proxy:jar:3.0.0:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.11.683:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-kms:jar:1.11.683:compile
[INFO] +- com.amazonaws:aws-java-sdk-ssm:jar:1.11.683:compile
[INFO] +- com.univocity:univocity-parsers:jar:2.8.4:compile

**Comment by wakaleo** [comment]
Sounds like a JVM crash - can you reproduce it in a sample project?

**Comment by JonathanOrtegon-L** [comment]
Hello, we have already solved it by removing an old dependency of the report generator
