### ISSUE TITLE
CucumberScenarioLoader parsing Tags incorrectly in 3.2.4

### ISSUE THREAD

**Issue by arturmalinowski** [serenity-bdd/serenity-core#2799]
Hi,

I've noticed that the current implementation for the method `tagsFor` in `CucumberScenarioLoader` returns a set of strings that look like this:
- `io.cucumber.messages.types.Tag@3f9f71ff[location=io.cucumber.messages.types.Location@fabb651[line=3,column=1],name=@SomeTag,id=b9753153-a140-4de1-9c93-b9f5ebe268ec]`

Further down the line, that set is used to see if it contains an individual tag (`@SomeTag`) in `CucumberSuiteSlicer`. `TagParser` is calling `evaluate` to achieve that. Unfortunately it only calls `contains` method on the set, and because it's such a massive String instead of the actual tag name, we always return false. 

I did a bit of digging and I can see that the implementation of `tagsFor` has changed in this commit `9165181b1e01f1e64c0977b57c87732ebdf1520d`
 
I think a solution is to revert back to what it was originally (with a minor change):

`FluentIterable.concat(feature.getTags(), scenarioTags(scenarioDefinition)).stream().map(Tag::getName).collect(toSet())`

Let me know please!

**Comment by wakaleo** [comment]
Can you give it a go, and if it works raise a PR?

**Comment by arturmalinowski** [comment]
Created https://github.com/serenity-bdd/serenity-core/pull/2800

I did more testing and it turns out this isnt fully broken - it works fine in features where examples are used.

To see the problem, run the added test without my change.

**Comment by wakaleo** [comment]
Pretty sure this is fixed.
