### ISSUE TITLE
@WithTag, @WithTags, @Tag and @Tags do not work in Serenity Core 3.2.x

### ISSUE THREAD

**Issue by anhphan-cwvn** [serenity-bdd/serenity-core#2801]
I am using SerenityBDD-Screenplay with Junit 5.

In Serenity BDD version 2.0.x, @WithTag still works, but after upgrading to Serenity version 3.2.0, it does not work anymore.

When using: `mvn verify -Dtags="value-of-WithTag"` it executes all scripts

Which annotation do we need to use?

**Comment by cliviu** [comment]
hi, just use the   @Tag JUnit5 native annotation

**Comment by anhphan-cwvn** [comment]
@cliviu I tried to use `@Tag` JUnit5 from `import org.junit.jupiter.api.Tag;`

However, it still doesn't work!

**Comment by cliviu** [comment]
at which level are you using the annotations ? Can you post a short example?

**Comment by anhphan-cwvn** [comment]
@cliviu This is my code:
```
import net.serenitybdd.junit5.SerenityJUnit5Extension;
import net.serenitybdd.screenplay.abilities.BrowseTheWeb;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static net.serenitybdd.screenplay.GivenWhenThen.*;
import static org.hamcrest.CoreMatchers.is;

@ExtendWith(SerenityJUnit5Extension.class)
@Tag("AAAA")
public class CameraHostTests extends Common {

    @Test
    @Title("Test 01")
    public void test01() {
         System.out.println("test 1");
    }

    @Test
    @Title("Test 03")
    public void test03() {
         System.out.println("test 3");
    }
}
```

**Comment by cliviu** [comment]
can you try please to use directly this documentation: https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-filter-tags

**Comment by cliviu** [comment]
actually `mvn verify -Dtags="AAAA"` has to work. I have just tested it with serenity 3.2.4

**Comment by anhphan-cwvn** [comment]
Solved!
`mvn verify -Dgroups="AAAA"`

**Comment by tibioneh** [comment]
This is still not working if running tests via gradle. Does anyone have a solution?

**Comment by johnysv** [comment]
> Solved! `mvn verify -Dgroups="AAAA"`

@anhphan-cwvn How to specify tags in in -Dgroups to pick test which has either one of the tags. The way we use -Dtags=@AAA or @BBB in junit4??

**Comment by AndreasScharfCPB** [comment]
-Dgroups works with Junit5 and @Tag

Thanks!
