### ISSUE TITLE
[Serenity 3.2.4][Junit5]: Json file not containing data based on custom display name generator 

### ISSUE THREAD

**Issue by bachhavdipak** [serenity-bdd/serenity-core#2804]
JSON file generated under target/site/serenity not containing data based on the Junit 5 custom display name generator. 

Please find the repo to reproduce issue: https://github.com/bachhavdipak/serenityJunit5/blob/main/src/test/java/starter/wikipedia/When_Searching_For_Terms.java

`{"name":"**search_by_single_keyword**","id":"**starter.wikipedia.When_Searching_For_Terms:search_by_single_keyword**","testCaseName":"starter.wikipedia.When_Searching_For_Terms","testSteps":[{"number":1,"description":"Navigate to the home page","duration":11470,"startTime":"2022-04-29T16:13:55.613+01:00[Europe/London]","screenshots":[{"screenshot":"d766ead5fa01902c43be6987673597ff3933826d50b64c72d7bbd153ebd0b126.png","timeStamp":1651245247083,"screenshotName":"d766ead5fa01902c43be6987673597ff3933826d50b64c72d7bbd153ebd0b126.png"}],"result":"SUCCESS","precondition":false,"level":0},{"number":2,"description":"Search by keyword \u0027Everest\u0027","duration":3247,"startTime":"2022-04-29T16:14:07.091+01:00[Europe/London]","screenshots":[{"screenshot":"597b79a182df41a4c47e54e1b2e766985064982352a407925041c61c53d69d28.png","timeStamp":1651245250338,"screenshotName":"597b79a182df41a4c47e54e1b2e766985064982352a407925041c61c53d69d28.png"}],"result":"SUCCESS","precondition":false,"level":0},{"number":3,"description":"The first heading should be \u0027Mount Everest\u0027","duration":1466,"startTime":"2022-04-29T16:14:10.380+01:00[Europe/London]","screenshots":[{"screenshot":"ad257c4fb289f56e4535629912587c88d9ad275b9c90ec2182936e0578cf5941.png","timeStamp":1651245250928,"screenshotName":"ad257c4fb289f56e4535629912587c88d9ad275b9c90ec2182936e0578cf5941.png"}],"result":"SUCCESS","precondition":false,"level":0}],"userStory":{"id":"starter.wikipedia.When_Searching_For_Terms","storyName":"When searching for terms","displayName":"When searching for terms","storyClassName":"starter.wikipedia.When_Searching_For_Terms","path":"wikipedia","type":"story"},"featureTag":{"name":"Wikipedia/When searching for terms","type":"story","displayName":"Wikipedia/When searching for terms"},"title":"Search by single keyword","tags":[{"name":"Wikipedia/When searching for terms","type":"story","displayName":"When searching for terms"},{"name":"Wikipedia","type":"feature","displayName":"Wikipedia"}],"startTime":"2022-04-29T16:13:54.262+01:00[Europe/London]","duration":18408,"projectKey":"","driver":"","isManualTestingUpToDate":false,"manual":false,"testSource":"JUnit5","order":0,"result":"SUCCESS"}
`

![image](https://user-images.githubusercontent.com/77110618/165999045-345c728f-c926-4228-a259-115d516eec24.png)

Code:

```
import Framework.Annotations.Common.MyTest;
import net.serenitybdd.core.Serenity;
import net.serenitybdd.junit5.SerenityJUnit5Extension;
import net.thucydides.core.annotations.Managed;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.WebDriver;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(SerenityJUnit5Extension.class)
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class When_Searching_For_Terms {

    /**
     * Define the webdriver instance to be used for these tests
     */
    @Managed(driver = "chrome", options = "")
    WebDriver driver;

    /**
     * Navigation actions. This is a UIInteraction class so it will be instantiated automatically by Serenity.
     */
    NavigateActions navigate;

    /**
     * Actions related to searches. This is a UIInteraction class so it will be instantiated automatically by Serenity.
     */
    SearchActions search;

    /**
     * A page object representing a Wikipedia article that is currently appearing in the browser.
     * Page Objects are automatically initialised by Serenity.
     */
    DisplayedArticle displayedArticle;

    @MyTest
    void search_by_single_keyword() {

        navigate.toTheHomePage();

        search.searchBy("Everest");
        Serenity.reportThat("The first heading should be 'Mount Everest'",
                () -> assertThat(displayedArticle.getFirstHeading()).isEqualTo("Mount Everest")
        );
        driver.close();
    }
```
```
import org.apiguardian.api.API;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;
import java.lang.annotation.*;
import static org.apiguardian.api.API.Status.STABLE;

@Target({ ElementType.ANNOTATION_TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@API(status = STABLE, since = "5.0")
@Inherited
@Test
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
public @interface MyTest {

}

```

**Comment by wakaleo** [comment]
I don't think custom name generators are currently supported.

**Comment by bachhavdipak** [comment]
@wakaleo: When do we expect changes?

**Comment by wakaleo** [comment]
When someone decides to contribute and raise a pull request.

**Comment by bachhavdipak** [comment]
@wakaleo  : I am looking into it and trying to identify root cause of this issue but looks like serenity is not stable and after clonining repo into local m/c so many existing issue found. Currently blocked due https://github.com/serenity-bdd/serenity-core/issues/3111

**Comment by bachhavdipak** [comment]
I am using windows machine and java version "1.8.0_281"
```
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
```

**Comment by bachhavdipak** [comment]
@wakaleo @globalworming : I am able to resolve this issue and planinning to push chnages in my own branch but facing issue while pushinh changes 

![image](https://user-images.githubusercontent.com/77110618/233054842-083cf182-05a5-41e0-8df7-8e4e9256eacd.png)

I have also tried same using SSH

![image](https://user-images.githubusercontent.com/77110618/233055138-a0744a8e-399a-4058-a0fd-723c49c2dba6.png)

**Comment by bachhavdipak** [comment]
@wakaleo : I have raised pull request for this issue: https://github.com/serenity-bdd/serenity-core/pull/3118.
