### ISSUE TITLE
[Serenity 3.2.4] Hide tags from the tags section of the report

### ISSUE THREAD

**Issue by Pigeon-Barry** [serenity-bdd/serenity-core#2818]
Hello,

I have question that I could not find in the documentation.

In essence I want to run the full report (including all tags) with the report showing all the exectured tests

However, I want to hide some tags from the tags section to avoid cluttering up the report.

For instance I have a test suite with 4000+ tests each with a unique @Issue associated to it. As such there are 4000+ @ISSUE:Issue-0000 tags in this section (with unique pages/charts associated to them) which I do not require.

Appoligies if this is already implemented

**Comment by wakaleo** [comment]
Use `serenity.report.exclude.tags`: see https://serenity-bdd.github.io/docs/reporting/the_serenity_reports
