### ISSUE TITLE
Test report showing PASSED when there are test failures and errors - serenity 3.2.4

### ISSUE THREAD

**Issue by deepthi-ravindra** [serenity-bdd/serenity-core#2819]
When there is 1 failure or even 1 error in report, test report is green , but error/failure does show up when report is opened and also in console as:
SERENITY TESTS: ERROR
[INFO] -----------------------------------------
[INFO] | Test cases executed    | 7
[INFO] | Tests executed         | 7
[INFO] | Tests passed           | 6
[INFO] | Tests failed           | 0
[INFO] | Tests with errors      | 1
[INFO] | Tests compromised      | 0
[INFO] | Tests aborted          | 0
[INFO] | Tests pending          | 0
[INFO] | Tests ignored/skipped  | 0
[INFO] ------------------------ | --------------
[INFO] | Total Duration         | 20m 37s
[INFO] | Fastest test took      | 1m 21s
[INFO] | Slowest test took      | 4m 43s
[INFO] --------------------------------------
The error/failure is  1) net.thucydides.core.webdriver.exceptions.ElementShouldBePresentException 2)java.lang.IllegalStateException: Unexpected value
But the failed test has not been re-run as flake. Shows as following after flakes are run, which are very confusing.

[WARNING] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Flakes: 2

This can lead to missed bugs. Please suggest.
Report plugins in pom:
  <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <configuration>
                    <reports>single-page-html</reports>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-single-page-report</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by wakaleo** [comment]
I can't reproduce this in 3.3.2
