### ISSUE TITLE
Please update core to include 2.50.1

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#282]
current core version has 2.48.2 please update to 2.50.1

This has got fix for Grid TIMEOUT issue

**Comment by wakaleo** [comment]
The next version will use 2.50.1.

**Comment by vikramvi** [comment]
Thanks John for quick reply , will check this in new release and close later.

**Comment by YamStranger** [comment]
Version upgraded, so it ready to be included in next release.

**Comment by wakaleo** [comment]
This should be done in 1.1.25-rc.4

**Comment by vikramvi** [comment]
closing as this is done
