### ISSUE TITLE
[Serenity 3.2.4] When the scenario name contains <title> charts do not generate

### ISSUE THREAD

**Issue by Pigeon-Barry** [serenity-bdd/serenity-core#2823]
When running the report with scenario names that contain <title> or any HTMLtext this causes the report to fail to generate tables

For instance we use the following

Scenario: Some Prefix - <title>
Given I run Step 1
When I run Step 2
Then I run Step 3 with <data>

Examples:
|title| data|
|typical|typical|
|max|max|

**Comment by wakaleo** [comment]
Can't reproduce in 3.3.2
