### ISSUE TITLE
Please update the version of cucumber jvm(the problem with Extra newlines appended to the console)

### ISSUE THREAD

**Issue by rustemsam** [serenity-bdd/serenity-core#2834]
Hi!
We faced with issue when Extra newlines appended to the console.
As I understand it's related to this issue:
https://github.com/gradle/gradle/issues/20599 
and this one: 
https://github.com/cucumber/cucumber-jvm/issues/2481

I saw that cucumber introduced the new version of cucumver-jvm:
https://github.com/cucumber/cucumber-jvm/blob/main/CHANGELOG.md
Which fixing this issue:
[7.3.3](https://github.com/cucumber/cucumber-jvm/compare/v7.3.2-RC1...v7.3.3) (2022-04-30)
Fixed
[Core] Pretty print plugin performance issues; incorrect DataTable format in Gradle console (https://github.com/cucumber/cucumber-jvm/pull/2541 Scott Davis)

Is it possible to update the version of cucumber:
  <cucumber.version>7.2.3</cucumber.version> 
from 7.2.3 to 7.3.3 , please?

**Comment by wakaleo** [comment]
We will do this eventually. There are lots of API changes in this version change, which mean lots of changes in the Serenity code.

**Comment by rustemsam** [comment]
@wakaleo , thanks for the information! Do you know maybe when will be the release including this updating ?

**Comment by rustemsam** [comment]
@wakaleo , you closed the bug. But I see that the version is still the same. Is there any reason for reason? 
Could you kindly reply?

**Comment by wakaleo** [comment]
The latest version of Serenity uses Cucumber 7.4.1
