### ISSUE TITLE
Is step library always needed for every step?

### ISSUE THREAD

**Issue by softwaredev999** [serenity-bdd/serenity-core#2839]
Hello,

Serenity + Maven + Cucumber project. 

I am checking to see il step library is required to have for every step.

1. Feature file has one line like this:
  
`  When i click on the close button
`  
2. Step definition:
  
```
@When("i click on the close button")
public void i_click_on_the_login_button() {
	Steps.clickCloseAlert();
}
```

3. Step library:

	
```
@Step("close")
public void clickCloseAlert() {
	HomePage.clickCloseAlert();
}
```
	

4. page class
```
public class HomePage extends BasePage{
	
	
private By close = By.className("close");

@Step("Click close")
public void clickCloseAlert() {
	click(close);
}
}
```

What If I click login button in this order 1, 2, 4 without using step library. It works just fine. 

Is it a good practice to use step library for some steps and do not use it for some steps? If you could clarify the purpose of step library, that would be great. Thank you!

**Comment by wakaleo** [comment]
Step libraries are used to add a layer of abstraction and group interactions into reusable tasks. Since your Gherkin step is quite low level, you could interact directly with a page object here.
