### ISSUE TITLE
Basic Authentication with Selenium 4 / SerenityBDD

### ISSUE THREAD

**Issue by Xvier** [serenity-bdd/serenity-core#2845]
I got a question/problem and I'm looking for help.
There is a new feature in Selenium 4 to enable basic auth from the start of your project.

```java
Webdriver driver = new Chromedriver();
((HasAuthentication) driver).register(UsernameAndPassword.of("username", "pass"));
```
and then you can navigate with your driver.

For our project we are using Cucumber + SerenityBDD and i tried to implement something similiar.

```java
  var driver = getDriver();
  ((HasAuthentication) driver).register(UsernameAndPassword.of("username", "pass"));
````

But the then i get an Error

`
starter.CucumberTestSuite > Loggin in for the first time.The user will log in for the first time and see his worklist FAILED
    java.lang.ClassCastException: class net.thucydides.core.webdriver.DevToolsWebDriverFacade cannot be cast to class org.openqa.selenium.HasAuthentication (net.thucydides.core.webdriver.DevToolsWebDriverFacade and org.openqa.selenium.HasAuthentication are in unnamed module of loader 'app')
        at starter.stepdefs.TestSteps.opens_the_app(TestSteps.java:35)
`

Do you have an working example how to implement this with SerenityBDD

**Comment by wakaleo** [comment]
I'll add native support for this in the next release.

**Comment by Xvier** [comment]
Thank you very much

**Comment by OlhaVasylets** [comment]
> I'll add native support for this in the next release.

Any updates retarding that?

**Comment by wakaleo** [comment]
This was released a few releases back.
