### ISSUE TITLE
Is there a known issue related to `restart.browser.for.each = scenario`

### ISSUE THREAD

**Issue by mrpet88** [serenity-bdd/serenity-core#2851]
We are trying to update to serenity 3.2.4 from 2.5.4 and we noticed that browser is not restarting after each scenario like it does on serenity 2.5.4. Is there a known issue related?

A bit difficult to provide code. But this is some sample from serenity.conf if it helps:

```
serenity {
  take.screenshots = FOR_FAILURES
  console.colors = true
  use.unique.browser = true
  browser.maximized = true
  restart.browser.for.each = scenario
}
```

**Comment by sandeepraina-lenze** [comment]
If you are using **@singlebrowser** tag in your feature file then **restart.browser.for.each** property will be overridden. On the other hand if I remember correctly by default web driver restarts after every scenario but again remove **@singlebrowser** from the feature file

**Comment by mrpet88** [comment]
Thanks for your reply! 
No, we are not using **@singlebrowser**, and true, it was restarting after every scenario in the 2.5.4. But that's not the case for the 3.2.4.

**Comment by sandeepraina-lenze** [comment]
I think this is potential issue in the framework then or may be a change in the usage of this property. Serenity v3 is major update which integrates Selenium 4 and Cucumber v6 and v7. I also understood there are some changes with the hook mechanism of Cucumber after Cucumber v4. I have handled this by introducing a **@reset** tag for every first scenario of the feature file and then adding the following code in a common java class

```
@Before(value="@reset", order=1)
    public void restartBrowser() {

        if (Serenity.getWebdriverManager().getCurrentDriver() != null) {
            Serenity.getWebdriverManager().getCurrentDriver().close();
            Serenity.getWebdriverManager().getCurrentDriver().quit();
        }
    }
```

@debug
Feature: AmazonLogin
  I want to log inside the Amazon webpage through different login credentials

  ```
@reset
  Scenario Outline: Successful Login with Valid Credentials
    Given User is on page '<pageaddress>'
    When User Navigate to LogIn Page
    And User enters '<username>' and '<password>'
    Then Message displayed Login Successfully

    Examples: 
      |	pageaddress							| username   | password |
      |	https://www.amazon.com/	| testuser_1 | Test@153 |
      |	https://www.amazon.com/	| testuser_2 | Test@153 |
```

**Comment by aybartsch** [comment]
I can confirm this issue using Serenity 3.2.5 but the work around could solve the problem.

**Comment by wakaleo** [comment]
`use.unique.browser = true` and `restart.browser.each.scenario = true` are contradictory - you are telling Serenity to keep the browser open for all the scenarios in the feature _and_ to restart the browser for each scenario. Use one or the other (or nothing at all if you just want the browser to restart for each scenario).

**Comment by aybartsch** [comment]
You are right. It's a typo! The correct setup is:
```
use.unique.browser = false
restart.browser.each.scenario = true
```
