### ISSUE TITLE
newDriver function don't recognize my driver.

### ISSUE THREAD

**Issue by AlexanderGamarra** [serenity-bdd/serenity-core#2855]
Hi, I have troubles to execute scenarios:

This is my serenity.properties
![image](https://user-images.githubusercontent.com/33327109/175349157-e36e4969-0dbc-497c-bf0d-c0879cb225a4.png)

This is my class that implements DriverSource
![image](https://user-images.githubusercontent.com/33327109/175349455-27f86502-139e-4d46-aac3-a99ee7f41e31.png)

Error Detail: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property.

I realized that if i specify where is the driver, it works!
![image](https://user-images.githubusercontent.com/33327109/175349889-b78fdb64-9f57-4dfd-ae98-58969b349a3d.png)

But, that's not right. Because, that configuration are in my serenity.conf file
![image](https://user-images.githubusercontent.com/33327109/175350103-fc7e847b-d7e6-4f08-94b7-715e577d47cf.png)

**Comment by wakaleo** [comment]
This is normal behavior: Custom drivers do not use the serenity properties files.
