### ISSUE TITLE
StepEventBus.getEventBus.enableSoftAssert() is not working for cucumber test

### ISSUE THREAD

**Issue by remyanekkuth** [serenity-bdd/serenity-core#2858]
@wakaleo 
I have a cucumber test in which we want to validate some negative scenarios but with enableSoftAssert() and didableSoftAssert(). Expectation is even though one step fails the test will continue, but actual is the first assertion fails, the test failed and skipped rest of the lines. 

We have same scenarios written in jUnit and enableSoftAssert() and disableSoftAssert() working as expected. 

We are using serenity-cucumber 6 : version 2.3.10 

Need some help on how to make this work for cucumber tests.

**Comment by wakaleo** [comment]
Soft assertions across steps are not supported.

**Comment by remyanekkuth** [comment]
@wakaleo is it only with the version. How can I use soft assert in cucumber in this case. Please provide some guidelines

**Comment by wakaleo** [comment]
Closing presumed answered
