### ISSUE TITLE
1.1.25-rc.4 java.lang.NullPointerException in logIfVerbose

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#286]
java.lang.NullPointerException
	at net.serenitybdd.core.pages.WebElementFacadeImpl.logIfVerbose(WebElementFacadeImpl.java:978)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.logClick(WebElementFacadeImpl.java:973)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.click(WebElementFacadeImpl.java:967)

Found this bug with latest version.

Any pointers for me to add unit test case for this kind of scenario ?

Thanks & Regards,
Vikram

**Comment by vikramvi** [comment]
Please see if this is side affect of fix in https://github.com/serenity-bdd/serenity-core/issues/281

**Comment by wakaleo** [comment]
This should be fixed in 1.1.25-rc.5

**Comment by vikramvi** [comment]
@YamStranger can you please give some pointers; on how and where can I add unit test case for this scenario ?

**Comment by wakaleo** [comment]
Could you check with there latest version?

**Comment by vikramvi** [comment]
@wakaleo I tried to use 1.1.25-rc.5 but it seems to be broken.

The next release 1.1.25-rc.6 is not yet showing in search.maven.org

**Comment by YamStranger** [comment]
Hello @vikramvi 
I think you can add your test in this class - https://github.com/serenity-bdd/serenity-core/blob/dc6c68e81a9031efb416658a0d355c48819aed4c/serenity-core/src/test/groovy/net/serenitybdd/core/pages/WhenManipulatingWebElements.groovy. I will move it if best place will be found

As I understand about @wakaleo request - you already checked it with rc.5 and this exception rise up. 

Please add some short example how I can check it and full stack trace. 

Thanks a lot!!!

**Comment by vikramvi** [comment]
@YamStranger  Please refer to https://github.com/vikramvi/serenity-journey-demo-debug/commit/7eaa6f025c0016f4228c0dfff541403ef37d7263

I couldn't check the fix in 1.1.25-rc.5 , as it seems to be broken.

Also thanks for pointer , will try to add a test case covering this scenario

**Comment by wakaleo** [comment]
It should be all fixed in 1.1.25-rc.6 - if you point your repos to jcenter you should be able to get this version.

**Comment by YamStranger** [comment]
Hello @vikramvi. I checked your repo, and it seems that you catch null pointer because of some build config issues. 

I updated serentyc-core to last at current time (1.1.25) and also updated serenity-jbehave/serenity-cucumber to latests. It seems that last one action was most important. 

I created pull request to help you find it fast: https://github.com/vikramvi/serenity-journey-demo-debug/pull/1

As result of this update
```
mvn clean verify
```
executed successfully
![screenshot from 2016-02-06 14-34-43](https://cloud.githubusercontent.com/assets/1667699/12866712/afa540a8-cce0-11e5-89e9-ad89c61fb588.png)

@vikramvi please close this issue, if your problem solved

Thanks a lot!!!

**Comment by vikramvi** [comment]
@YamStranger @wakaleo sorry for delay updating this ticket , as I'm still struck with an open issue

When I'm changing <serenity.version>1.1.25-rc.6</serenity.version> Getting error Missing artifact , as this is not yet present in Maven Central.

How to get this from JCenter ? I mean how to tell pom.xml to download from JCenter rather than Maven Central ?

Thanks

**Comment by YamStranger** [comment]
Hello @vikramvi. It seems that you can add configuration as here : 
[serenity-demos/junit-webtests/pom.xml](https://github.com/serenity-bdd/serenity-demos/blob/d0c685b08bf2a3fa9f1220e855ec8b3065ed2bf6/junit-webtests/pom.xml)
or 
[serenity-demos//cucumber-webtests/pom.xml](https://github.com/serenity-bdd/serenity-demos/blob/a51523960484637bf2543185a7084efe43db99e4/cucumber-webtests/pom.xml)

Something like this: 

```
    <repositories>
      <repository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
      </repository>
    </repositories>
    <pluginRepositories>
      <pluginRepository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray-plugins</name>
        <url>http://jcenter.bintray.com</url>
      </pluginRepository>
    </pluginRepositories>
```

or 
```
    <repositories>
        <repository>
            <id>serenity</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/serenity/maven</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>serenity</id>
            <name>bintray-plugins</name>
            <url>http://dl.bintray.com/serenity/maven</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by vikramvi** [comment]
@YamStranger Thanks a ton for quick info , I have solved the JCenter issue.

But something wrong with latest releases , couldn't get browser launched checked with 1.1.25 and 1.1.26-rc.1.

Let me check this in a public project and update back to you in some time.

**Comment by vikramvi** [comment]
verified fixed.

The funny part I need to find solution now; is that my local project can't run / debug single junit test case with latest versions anymore. 

It's only working with mvn clean verify commands.

Thanks for help @YamStranger

**Comment by YamStranger** [comment]
@vikramvi you are welcome
