### ISSUE TITLE
Test cases are not getting triggered using surefire plugin

### ISSUE THREAD

**Issue by guptadeepak0687** [serenity-bdd/serenity-core#2865]
I am trying to run the test cases using mvn test command, but it seems not working getting some JUnit errors, same piece is working using mvn verify command.
Can anyone help me.

**Comment by wakaleo** [comment]
What errors are you getting?

**Comment by guptadeepak0687** [comment]
Cucumber-Junit and Serenity-Junit  version is 5.6.0

**Comment by guptadeepak0687** [comment]
Did anyone one get a chance to look into this?
Any suggestions would help me alot.

**Comment by guptadeepak0687** [comment]
anyone suggestion for me

**Comment by wakaleo** [comment]
Try looking at the https://github.com/serenity-bdd/serenity-junit-starter for a working configuration.

**Comment by wakaleo** [comment]
Closing presumed resolved.
