### ISSUE TITLE
False positive report in serenity 3.2.5

### ISSUE THREAD

**Issue by deepthi-ravindra** [serenity-bdd/serenity-core#2871]
Although couple of tests has failed in a pack of 94 tests.. the build passed and serenity console showing no failures/errors but in the repot, there were 2 errors.
Parallel execution being done by cucable plugin.

Is this a known issue?
Serenity version - 3.2.5
<img width="622" alt="Screenshot 2022-07-19 at 10 14 42" src="https://user-images.githubusercontent.com/32193521/179714398-e7967b12-4142-4da7-a221-809b481c1f9b.png">

**Comment by wakaleo** [comment]
Cucable with Serenity isn't supported. It might work running features in parallel, but it won't work with scenarios if you use scenario outlines.

**Comment by deepthi-ravindra** [comment]
We have got it working with running scenarios in parallel with scenario outline.. it's just the false reporting.. do you think it could be surefire or failsafe?

**Comment by wakaleo** [comment]
The tests will run, but the reporting will not work.

**Comment by wakaleo** [comment]
Closing as not supported - parallel execution will be available with Cucumber parallel execution integration
