### ISSUE TITLE
Upgrading from 2.4.4 to 3.2.4 and facing an exception with NoClassDefFoundError

### ISSUE THREAD

**Issue by tanakala2645** [serenity-bdd/serenity-core#2872]
dependencies {
    implementation group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: '2.12.3'
    implementation group: 'com.github.invictum', name: 'serenity-reportportal-integration', version: '1.5.6'
    implementation group: 'com.google.guava', name: 'guava', version: '30.1.1-jre'
    implementation group: 'io.rest-assured', name: 'json-schema-validator', version: '5.0.1'
    implementation group: 'org.apache.commons', name: 'commons-collections4', version: '4.4'
    implementation group: 'org.json', name: 'json', version: '20210307'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '2.41.0'
    implementation group: 'org.yaml', name: 'snakeyaml', version: '1.28'
    implementation group: 'commons-validator', name: 'commons-validator', version: '1.7'
    implementation group: 'com.github.fge', name: 'json-schema-validator', version: '2.2.6'
    implementation group: 'com.github.fge', name: 'json-schema-core', version: '1.2.5'
    implementation group: 'com.github.fge', name: 'uri-template', version: '0.9'
    implementation group: 'com.github.fge', name: 'jackson-coreutils', version: '1.8'
    implementation group: 'org.ehcache', name: 'jcache', version: '1.0.0'
    implementation group: 'net.serenity-bdd.maven.plugins', name: 'serenity-maven-plugin', version: '3.2.4'

    implementation 'ch.qos.logback:logback-classic:1.2.3'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.10.0'
    implementation 'com.epam.reportportal:agent-java-cucumber6:5.0.5'
    implementation 'com.epam.reportportal:logger-java-logback:5.0.3'
    implementation 'commons-configuration:commons-configuration:1.10'
    implementation 'io.rest-assured:rest-assured:5.0.1'
    implementation 'io.rest-assured:json-path:5.0.1'
    implementation 'org.testng:testng:7.4.0'
    implementation 'org.slf4j:slf4j-api:1.7.5'
    implementation 'org.springframework:spring-web:3.0.2.RELEASE'
    implementation 'net.serenity-bdd:serenity-core:3.2.4'
    implementation 'net.serenity-bdd:serenity-cucumber:3.2.4'
    implementation 'net.serenity-bdd:serenity-screenplay-webdriver:3.2.4'
    implementation 'net.serenity-bdd:serenity-saucelabs:3.2.4'
    implementation 'net.serenity-bdd:serenity-rest-assured:3.2.4'

//    testImplementation 'io.cucumber:cucumber-core:7.2.3'
//    testImplementation 'io.cucumber:cucumber-java:7.2.3'
//    testImplementation 'io.cucumber:cucumber-junit:7.2.3'
    testImplementation 'junit:junit:4.13.1'
    testImplementation 'org.assertj:assertj-core:3.8.0'
    testImplementation 'org.slf4j:slf4j-api:1.7.5'
    testImplementation 'net.serenity-bdd:serenity-ensure:3.2.4'
}

While running API tests facing below exception:
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: io/cucumber/messages/Messages$GherkinDocument$Builder
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.cucumber.core.runtime.Runtime.runFeatures(Runtime.java:117)
	at io.cucumber.core.runtime.Runtime.lambda$run$0(Runtime.java:82)
	at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:80)
	at io.cucumber.core.cli.Main.run(Main.java:87)
	at io.cucumber.core.cli.Main.main(Main.java:30)

**Comment by tanakala2645** [comment]
Test Runner

import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        tags="@Functional",
        features = "src/test/resources/features/api",
        glue={"com.fiserv.stepdefs", "com.fiserv.support.stepdefmethods"})
public class RunCucumberTest {
}

**Comment by wakaleo** [comment]
NoClassDefFoundError is a dependency conflict - do a dependency analysis on your project and you should find the issue.

**Comment by wakaleo** [comment]
Closing presume resolved.
