### ISSUE TITLE
GC overhead limit exceeded when running a test suite 

### ISSUE THREAD

**Issue by ikallala** [serenity-bdd/serenity-core#2873]
After upgrade serenity from 3.1.10 to 3.2.5 , **error java.lang.OutOfMemoryError: GC overhead limit exceeded** appears despite I already set **<argLine>-Xmx1024m</argLine>** in maven-failsafe-plugin configuration 
PS: it works well with 3.1.10

**Comment by 1109471432** [comment]
I had the same problem at Serenity-bdd 3.2, I analysis dump file. I think this is a Memory Leak problem.
![d8a2ebc758de3efb81535740e3be119](https://user-images.githubusercontent.com/52598902/186922503-55a49226-5a78-4eab-a1e7-c7efc987d1cb.png)
![7e5b04c3abfaeef33e9575ff9a6dd0b](https://user-images.githubusercontent.com/52598902/186922519-c46905f3-1813-491b-86f5-12f6eb6098da.png)
Please contact me if you need more information.

**Comment by ikallala** [comment]
@1109471432 Thanks for responding to my issue
How can I fix this problem ?

**Comment by 1109471432** [comment]
The error code exists only in version(3.1.20),version(3.2.0) The error code is as follows:
![image](https://user-images.githubusercontent.com/52598902/186946494-4dd65f51-4d8f-4068-92ef-f92e450116c4.png)
the error code add at 1/27/2022 and remove at 6/19/2022, You can user other version serenity-bdd. 

Please contact me if you need more information.

**Comment by 1109471432** [comment]
The above remarks are all my speculations, please correct me if there is anything wrong, thank you.

**Comment by ikallala** [comment]
this issue is no more reproduced with the version 3.3.2
