### ISSUE TITLE
Prepare a "next chapter" button at the end of each page of The Serenity BDD Book

### ISSUE THREAD

**Issue by monsoma** [serenity-bdd/serenity-core#2874]
Great tool, and great book for learning Serenity BDD. It's a bit cumbersome after finishing one chapter of the book to move to the next one: Scroll to the top, find the actual selected chapter in the TOC, select the next one. Please prepare a "next chapter" button on the end of the page to support continous reading.

**Comment by globalworming** [comment]
justto make sure... could you post a link to the book? :smiley:

**Comment by monsoma** [comment]
Yeah, that's correct!

**Comment by wakaleo** [comment]
This is implemented in the new docs: https://serenity-bdd.github.io
