### ISSUE TITLE
Getting error Plugin with id 'net.serenity-bdd.aggregator' not found.

### ISSUE THREAD

**Issue by bachhavdipak** [serenity-bdd/serenity-core#2876]
I am using the below serenity version but while compiling the project getting the Plugin with id 'net.serenity-bdd.aggregator' not found. I am trying to apply plugin: 'net.serenity-bdd.aggregator'. It works fine with the old version `3.2.4` 

```
serenityCoreVersion = 3.3.0
serenityGradlePlugin = 3.3.0
```

**Comment by wakaleo** [comment]
Is this with Gradle?

**Comment by bachhavdipak** [comment]
Sorted

**Comment by bachhavdipak** [comment]
Yes I am using Gradle

**Comment by wakaleo** [comment]
This one? https://plugins.gradle.org/plugin/net.serenity-bdd.serenity-gradle-plugin

**Comment by bachhavdipak** [comment]
No, I am facing issue with **apply plugin: 'net.serenity-bdd.aggregator'**

**Comment by wakaleo** [comment]
Try using the plugin as defined in the link above.

**Comment by bachhavdipak** [comment]
No , it's not working

**Comment by wakaleo** [comment]
Have a look at https://github.com/serenity-dojo/swaglabs-serenity-cucumber for a working example of a Gradle build. I don't recall anyone proposing a pull request for the display name generator - was there something that led you to believe this would be in the next release?

**Comment by souwa** [comment]
hi @bachhavdipak,

> No, I am facing issue with apply plugin: 'net.serenity-bdd.aggregator'

please try to apply the serentiy gradle plugin instead. That worked for me:

`apply plugin: "net.serenity-bdd.serenity-gradle-plugin"`

**Comment by bachhavdipak** [comment]
@souwa : I have tried that but still getting an empty serenity report.

![image](https://user-images.githubusercontent.com/77110618/182845704-c2b4ddcb-4183-4136-9f85-b9313fd59ae7.png)

**Comment by wakaleo** [comment]
That would mean that your tests are not being executed

**Comment by bachhavdipak** [comment]
The test is executed @wakaleo and fails due to the `ElementNotInteractableException` 

```
 13:37:30.788 [ForkJoinPool-1-worker-1] INFO  d.e.u.s.eCommStepDefinitions - Destroy the web driver instance

e comm functional tests > Sample Test case  FAILED
    org.openqa.selenium.ElementNotInteractableException: Timed out after 20 seconds. Element not available
    Build info: version: '4.3.0', revision: 'a4995e2c09*'
    System info: host: 'UKC-DSEV023991', ip: '10.4.12.58', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
    Driver info: driver.version: unknown
```

**Comment by wakaleo** [comment]
Try starting with one of the starter projects - I don't know what the issue is here.

**Comment by bachhavdipak** [comment]
In my case, I need to delete the target/serenity folder from my local disk. Now its working fine Thanks @wakaleo

**Comment by aniket00197** [comment]
@wakaleo I am also facing the same issue which @bachhavdipak  mentioned above. 
 - Test Root: starter
      - Requirements base directory: null

**Comment by wakaleo** [comment]
It's a known Gradle issue - I don't have a solution at this stage, but PRs are more than welcome - it's something to do with the way Gradle defines root directories.

**Comment by HanselCream** [comment]
Hello I am having an Issue with gradle. I am using JDK 18 and Gradle 7.6

This is showing an error
* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'net.serenity-bdd.serenity-gradle-plugin', version: '7.6'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'net.serenity-bdd.serenity-gradle-plugin:net.serenity-bdd.serenity-gradle-plugin.gradle.plugin:7.6')

This is my build.gradle
```
plugins {
    id "net.serenity-bdd.serenity-gradle-plugin" version "7.6"
    id 'java'
    id 'eclipse'
    id 'idea'
}

defaultTasks 'clean','test','aggregate'

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

ext {
    slf4jVersion = '1.7.7'
    serenityCoreVersion = '3.5.1'
    junitVersion = '5.8.2'
    assertJVersion = '3.22.0'
    logbackVersion = '1.2.10'
}

dependencies {
    testImplementation "net.serenity-bdd:serenity-core:7.6",
            "net.serenity-bdd:serenity-junit5:7.6",
            "net.serenity-bdd:serenity-screenplay:7.6",
            "net.serenity-bdd:serenity-ensure:7.6",
            "net.serenity-bdd:serenity-screenplay-webdriver:7.6",
            "org.junit.jupiter:junit-jupiter-api:5.8.2",
            "org.assertj:assertj-core:3.22.0",
            "ch.qos.logback:logback-classic:1.2.10"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.8.2"
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

gradle.startParameter.continueOnFailure = true

test.finalizedBy(aggregate)

```

What is wrong? I am using Intellij

**Comment by ferlot70** [comment]
@HanselCream got the same failure, but the problem was the plugin version. I fixed it by updating to the latest https://plugins.gradle.org/plugin/net.serenity-bdd.serenity-gradle-plugin
