### ISSUE TITLE
Unnecessarily forced to write step defs for @manual tagged scenarios

### ISSUE THREAD

**Issue by vivganes** [serenity-bdd/serenity-core#2877]
I am facing issues running serenity-bdd with cucumber-jvm. Possibly a bug in serenity system.

**Version:** 3.3.0

I have a scenario marked as `@manual` in the feature file

```
Feature: Subtracting Numbers

  @manual
  Scenario: Subtracting two numbers
    Given a is 2
    And b is 1
    When I subtract b from a
    Then the difference should be 1
```

**Expected:** serenity should not force me to write step definitions for this scenario as it is tagged as manual.

**Actual:**  I get the following error when I run the serenity

```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.539 s <<< FAILURE! - in org.example.acceptancetests.AcceptanceTestSuite
[ERROR] Subtracting Numbers.Subtracting two numbers  Time elapsed: 0.109 s  <<< ERROR!
io.cucumber.junit.UndefinedStepException:
The step "I subtract b from a" is undefined. You can implement it using the snippet(s) below:

@When("I subtract b from a")
public void i_subtract_b_from_a() {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}


Some other steps were also undefined:

@Then("the difference should be {int}")
public void the_difference_should_be(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}


[INFO] 
[INFO] Results:
[INFO]

[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

When I implement empty step definitions for the manual scenarios, the build passes.  This is a behavior that would force unused step defs for manual test cases

**Comment by wakaleo** [comment]
That's just how Cucumber works - it's not related to Serenity.

**Comment by vivganes** [comment]
Do you mean this is a bug in Cucumber?

I would like to generate a report with both manual and automated tests, without writing dummy step definitions.

Right now, it is not possible for me to determine the success or failure of tests from the Maven build's exit code

**Comment by wakaleo** [comment]
It's not a bug, it's a documented feature: it's just the way Cucumber (as of Cucumber 4 IIRC) works. If you want to include manual tests, you need to exclude them from the test execution, e.g

```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        plugin = {"pretty"},
        features = "src/test/resources/features",
        tags="not @manual"
)
public class CucumberTestSuite {}
```

They will still appear in the requirements reports, but not in the test execution counts.

**Comment by vivganes** [comment]
Thanks this is exactly what I was looking for.  I am closing this issue
