### ISSUE TITLE
Test executes so slower than call through Postman on Macbook Pro M1

### ISSUE THREAD

**Issue by minhldhe130866** [serenity-bdd/serenity-core#2880]
Im testing restAPI, with the same body and url, I called via Postman (0.5 sec) so much faster than call by code (more than 1mins)
<img width="231" alt="image" src="https://user-images.githubusercontent.com/55751453/182194325-b540bd39-44b8-4e7e-ac2e-d59ff494e04e.png">
<img width="508" alt="image" src="https://user-images.githubusercontent.com/55751453/182194521-12a0acb2-9383-48e9-9a93-086677b75b58.png">
I need all help :((

**Comment by wakaleo** [comment]
What version of Serenity are you using? Are you using plain RestAssured, or just SerenityRest? Is this for every test, or just the first test (what is the total time if you add more tests).

**Comment by minhldhe130866** [comment]
> What version of Serenity are you using? Are you using plain RestAssured, or just SerenityRest? Is this for every test, or just the first test (what is the total time if you add more tests).

Im doing use 2.4.34 ver and SerenityRest. It happened on every my testcase :(

**Comment by wakaleo** [comment]
Have you tried with a more recent version?

**Comment by minhldhe130866** [comment]
> Have you tried with a more recent version?

I'll try

**Comment by minhldhe130866** [comment]
It doesn't work for me :((( I tried to use 3.3.0 ver :(

**Comment by wakaleo** [comment]
There is a startup time due to the code instrumentation in RestAssured. After that, the tests should run at normal speed. I can't reproduce any performance issues other than a few seconds delay on startup. Can you provide a sample project that reproduces this issue?

**Comment by wakaleo** [comment]
Closed for lack of activity

**Comment by minhldhe130866** [comment]
sorry, I can provide source code example because of my company's privacy. help meeee @wakaleo

**Comment by minhldhe130866** [comment]
Is there any ways for me to log every step program running ?

**Comment by minhldhe130866** [comment]
I check service log, I recieved nothing after SerenityRest.given() was called. I don't know why. As normal, it must have sth in log such as body request.
