### ISSUE TITLE
Text box values are not cleared for Calendar type

### ISSUE THREAD

**Issue by senthilkumar-gopi** [serenity-bdd/serenity-core#2884]
We have a calendar input box and input the value using Enter.theValue() method. We will update the value which will automatically clear the field and send new values. This was working well up to the Serenity Version 3.1.20. But after that it is not working. It is not clearing the field properly. Please check and fix.

**Comment by wakaleo** [comment]
This was changed back due to inconsistent behaviour with some of the drivers on different OSs, which caused defects in some cases. Changing it back would reintroduce these bugs, so I don't think we'll be doing that soon.

**Comment by senthilkumar-gopi** [comment]
Even if I use click, clear and then send values as a workaround, still the field is not getting cleared. I need to figure out whether selenium commands works here.

**Comment by wakaleo** [comment]
That would probably be a selenium driver issue. Try with pure selenium or debug into the code to see what it is doing.

**Comment by senthilkumar-gopi** [comment]
It's not a Selenium issue. If the Task method is executed with only Enter method, then it is clearing the Calendar input text box properly. If the Task method contains sequence of steps along with Enter method, then only it is failing by not clearing the Calendar input text box.

My understanding based on this issue is that Clear method when executed as a single statement inside a Task is working fine, But when executed with a sequence of steps inside a Task is not clearing properly. This is only for Calendar as input text box.

**Prerequisite** : Calendar input text box prepopulated during create. We need to update the Calendar input text box.

As stated above this was working well in Serenity Version 3.1.20. But fails after that new versions.

**======
SUCCESS:
======**
    public static Performable dummy1() {
        return Task.where("Open Deal Summary Page", Enter.theValue("8/13/22").into(TXT_DOD_OPINION_DATE));
    }
(or)
    theActorInTheSpotlight().attemptsTo(Enter.theValue("8/13/22").into(TXT_DOD_OPINION_DATE));
(or)
    public static Performable dummy2() {
        return Task.where("Open Deal Summary Page", Clear.field(InitializationPage.TXT_DOD_OPINION_DATE));
    }

**===
FAIL:
===**
    public static Performable dummy() {
        return Task.where("enter details",
                Click.on(DD_HEADER_USEOFFUNDS),
                Enter.theValue("8/13/22").into(TXT_DOD_OPINION_DATE)
        );
    }

(or)

public static Performable dummy2() {
        return Task.where("enter details",
                Click.on(InitializationPage.DD_HEADER_USEOFFUNDS),
                Clear.field(InitializationPage.TXT_DOD_OPINION_DATE)
        );
    }

**Comment by wakaleo** [comment]
Have a look at the code to see if you can propose a change.

**Comment by sandeepraina-lenze** [comment]
We had a similar problem but Serenity provides a functionality that can universally help you in clearing contents consistently _ClearContents.ofElement()_ under **net.serenitybdd.core.pages.ClearContents** class library

**Comment by senthilkumar-gopi** [comment]
Thanks @sandeepraina-lenze . Using this command, I created a separate task to clear the values. But getting one more error related to the issue which occurs when executing sequence of steps inside a task.

Here I pass the start time and end time as 05:25 and 05:35. But the values are not inputted properly for minutes. Rather it is inputted as "00". I think since clear is not working properly, this error is occurring. After calling the workaround task method which clears the field, able to set the correct values. [These are calendar fields. We can increase or decrease time using keyboard functions as well]

public static Performable setStartEndTime(String startTime, String endTime) {
        String startHour = startTime.split(":")[0];
        String startMin = startTime.split(":")[1];
        String endHour = endTime.split(":")[0];
        String endMin = endTime.split(":")[1];
        return Task.where("Enter the StartTime "+startTime+ ", EndTime "+endTime,
                WaitUntil.the(AuditPage.TXT_START_DATE, WebElementStateMatchers.isEnabled()),
                Enter.theValue(startHour).into(AuditPage.TXT_START_HOUR),
                **Enter.theValue(startMin).into(AuditPage.TXT_START_MIN),**
                Enter.theValue(endHour).into(AuditPage.TXT_END_HOUR),
                **Enter.theValue(endMin).into(AuditPage.TXT_END_MIN)**
        );
 }

**Comment by wakaleo** [comment]
@senthilkumar-gopi The behaviour you are describing comes from a driver bug which we have no control over, and which is why the Serenity code was changed initially. There is nothing more we can do at the Serenity level in a general case, but you can try to write a specific task to clear the component for your particular case.

**Comment by senthilkumar-gopi** [comment]
Am able to use the workaround by creating a separate task with ClearContents.ofElement(target.resolveFor(theActorInTheSpotlight())).

**Comment by senthilkumar-gopi** [comment]
Again have one more issue related to this subject. I think real root cause of this issue might be executing sequence of steps inside the task. I clear a mandatory field and check whether the save button is disabled. This is working fine with Serenity Version 3.1.20. All problems stated above is after the version Serenity Version 3.1.20. But now the Clear field is empty the text box input field. But Save button still remains enabled.

**Workaround**: Again I used the separate task which I mentioned above. It clears the field as well as the Save button seems to be disabled and works as usual.

**Comment by wakaleo** [comment]
The change made after 3.1.2.0 is not reversable as it is a workaround for a chromedriver bug/inconsistency, so I think writing your own task is the best solution to this problem.

**Comment by wakaleo** [comment]
Closing presumed answered (and with workaround)
