### ISSUE TITLE
CSS codes generated in the serenity report

### ISSUE THREAD

**Issue by bhatprateeksha1991** [serenity-bdd/serenity-core#2889]
Hi, We are using serenity core 3.1.0, cucumber 6.10.2 and the generated report has CSS codes displayed at the bottom. Please advise.

![image](https://user-images.githubusercontent.com/111409702/185035303-0cdfa39c-f517-4b61-bf7e-9ead50b636fa.png)

![image](https://user-images.githubusercontent.com/111409702/185035080-5ef28d63-e9ef-4c92-8001-1cc7fd300a73.png)

![image](https://user-images.githubusercontent.com/111409702/185035548-37cc5826-03fa-42e8-9499-1cab8ebba191.png)

**Comment by wakaleo** [comment]
Try with the latest recommended versions.

**Comment by wakaleo** [comment]
Closing presumed resolved.
