### ISSUE TITLE
Soft assert failures in the @After tag are not included in the report

### ISSUE THREAD

**Issue by george89ro** [serenity-bdd/serenity-core#2890]
I'm running some tests using Cucumber (7.2.3) with Serenity (3.3.1).
I'm using soft assertions (AssertJ 3.22.0) and all the checks are being done in a step with @After tag.
The actual feature file doesn't contain a step where the assertions are being performed as they are done after each test through the @After tag.

The problem is that even if there is a failure, Serenity will show the report as passed. In maven I can clearly see that there is a failure.
The expectation here is that the last step in the flow will be marked as failed.
Running through Junit also fails the test correctly.

This worked fine in an older version of serenity (2.3.4), i.e. the last step in the test was marked as failed in the serenity report.

Serenity report sample (index.html):
![serenity](https://user-images.githubusercontent.com/17336423/185109361-7fcc1bd7-9eef-425b-bfc6-e726891cdf4b.jpg)

Maven console:
![Maven](https://user-images.githubusercontent.com/17336423/185109435-df3c0aed-0fce-4613-90e3-808dd450b44d.jpg)

**Comment by wakaleo** [comment]
I can't reproduce this behaviour - do you have a sample product where it occurs?

**Comment by george89ro** [comment]
@wakaleo - I created a repo and sent you the invite. Thanks!

**Comment by wakaleo** [comment]
The @ContextConfiguration annotation in the steps library is confusing the Cucumber runner, so it is not activating the right code in the @After. You need to have a separate class that interacts with the Spring code, and instantiate it using the TestContextManager class.

**Comment by george89ro** [comment]
Thanks!

This adds additional classes for me and won't allow me to properly use Spring tags as I would like.
I'll try to see if I can figure something out
