### ISSUE TITLE
Cannot allow an Actor to call from 2 API's

### ISSUE THREAD

**Issue by Mo0rBy** [serenity-bdd/serenity-core#2891]
I'm using Serenity Screenplay + Cucumber in my test framework. I understand what an Actor is and what Abilities are and that Actor's can be setup to be allowed to perform certain actions (like calling an API).

In my Cucumber feature file, I have 2 `Given` steps, both stating that the Actor can CallAnApi at 2 different endpoints:

`Given` User can call an API at service A
`And` User can call an API at service B (Note that this step is performed immediately after the 1st Given step)

Both of these steps are written like this:
```
    @Given("{actor} has access to <ServiceName>")
    public void actor_has_access_to_service(Actor actor) {
        actor.can(CallAnApi.at(<ServiceBaseUri>));
    }
```
I ran the tests and found that my POST request was being sent to ServiceB, not serviceA, despite the fact that I explicitly define the BaseUri for service A in my POST request:
```
    File jsonPayload = new File(<FilePathToExampleJsonPayload>);
    String serviceA_Baseurl = <BaseUrlHere>;
    actor.attemptsTo(
        Post.to(<APIEndpoint>)
                .with(request -> request
                    .baseUri(serviceA_Baseurl)
                    .body(jsonPayload))
    );
```
Now my guess is that the 2nd `Given` statement, in which Serenity is told the Actor can perform an API call to service B, overwrites the 1st `Given` statement that states that the Actor can call an API at service A. Is there a way to _ADD_ abilities to an Actor that already exists without overwriting the Actor's current abilities?

I noticed that in a single `actor.can(<Abilities>)`, you can only define a single API that the Actor can call. Is there no way for an Actor to have the ability to call more than 1 API?

**Comment by globalworming** [comment]
yeah, call an api is using rest assured. an actor can only have one of these and rest assured is meant to use a single api url.
you could use different actors for different services..
or you switch the base url on the fly. i vaguely remember something about the RestAssured config that made this possible but i cannot find it again.

i found https://medium.com/naukri-engineering/handle-multiple-base-uri-to-achieve-end-to-end-api-testing-using-rest-assured-1200a5217404 maybe that helps?

**Comment by Mo0rBy** [comment]
@globalworming, thank you for your suggestion, had a quick look at that article and it looks like something I'd be able to use. For my own curiosity, do you know why explicitly stating the baseUri for SerenityRest doesn't affect the baseUri that is used? There's the method I used above where the I set the `.baseUri()` for the `RequestQueryFunction` and there's another method I tried in which I had 1 line like: `SerenityRest.rest().baseUri(<baseUri>)`. This also didn't affect the baseUri called.

**Comment by globalworming** [comment]
as far as i remember the rest assured configuration is set once and cannot be overridden, but I don't know specifics. i can recommend setting debug breakpoints and checking yourself

**Comment by Mo0rBy** [comment]
The main point to the solution in the article given by @globalworming is using the `RequestSpecBuilder` class to build the request specification. I've implemented it in a simpler way (just hard coding, nothing to do with getting data from YAML's, I already have a way of pulling in baseUrl's for different envs) and it still calls the API at the last baseUri defined in that last `Given actor.can(CallAnApi.at(<BaseUrl>))`. This brings me back to believing that the Actor can only ever call the API that it is "allowed" to communicate with and this can only ever be set to 1 baseUri. This is definitely something that Serenity could improve on by allowing Actors to have a list/array of baseUri's that they have been allowed to call.

For now, I'm going to have to change my Given steps so that I don't set any abilities for the Actor, and hope that I can do it this way.

Is it possible for me to look into this issue deeper and propose a change to the Serenity codebase?
