### ISSUE TITLE
Serenity restassured- Issues in builder class()

### ISSUE THREAD

**Issue by Vijay2871** [serenity-bdd/serenity-core#2898]
When building the api post request Builder class is not working
```
@Getter
@Setter
@Jacksonized
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)

public class SFCCGuestAuth {

    @JsonProperty("type")
    private String type;

}

   public static SFCCGuestAuth requestSFCCGuestAuth() {
        return SFCCGuestAuth.builder().type("guest").build();
    }
```    

> error: cannot find symbol
        return SFCCGuestAuth.builder().type("guest").build();

**Comment by wakaleo** [comment]
I don't think this is related to the Serenity code - it looks like Lombok is not working for some reason.

**Comment by Vijay2871** [comment]
> I don't think this is related to the Serenity code - it looks like Lombok is not working for some reason.
added and issue resolved
dependencies {
     compileOnly 'org.projectlombok:lombok:1.18.8'
     annotationProcessor 'org.projectlombok:lombok:1.18.8'
     ...
 }
