### ISSUE TITLE
How to use builder pattern in Serenity BDD-issues at point builder()

### ISSUE THREAD

**Issue by Vijay2871** [serenity-bdd/serenity-core#2899]
![image](https://user-images.githubusercontent.com/54226136/186306261-8dfdb86d-289d-4b43-9553-f68d83c9e002.png)

**Comment by globalworming** [comment]
what issue do you have exactly?
lombock annotations are pretty much independent from serenity (unless interference in the compile phase somehow)

**Comment by Vijay2871** [comment]
> what issue do you have exactly? lombock annotations are pretty much independent from serenity (unless interference in the compile phase somehow)

For serialising the request body i need to use the builer pattern and throwing an error

**Comment by globalworming** [comment]
and what error might that be?

**Comment by Vijay2871** [comment]
> and what error might that be?

![image](https://user-images.githubusercontent.com/54226136/186382646-eac21a16-52d5-4de6-b568-1f6ff9b616e6.png)


error: cannot find symbol
        return SFCCGuestAuth.builder().type("guest").build();
                            ^
  symbol:   method builder()
  location: class SFCCGuestAuth

**Comment by globalworming** [comment]
this has nothing to do with serenity but is more a general java and maybe lombock related question. please ask in a java or lombock forum 

also please check [some advice](https://opensource.com/life/16/10/how-ask-technical-questions) on [how to ask](https://stackoverflow.com/help/how-to-ask) questions

**Comment by Vijay2871** [comment]
> this has nothing to do with serenity but is more a general java and maybe lombock related question. please ask in a java or lombok forum
> 
> also please check [some advice](https://opensource.com/life/16/10/how-ask-technical-questions) on [how to ask](https://stackoverflow.com/help/how-to-ask) questions

I have replicate the code which I did for Cucumber and it was working fine, but same code I put in Serenity bdd framework it's not working

**Comment by wakaleo** [comment]
It might be a dependency conflict. It's a compilation error, not a runtime error, so it looks like an issue with the build setup.

**Comment by Vijay2871** [comment]
> It might be a dependency conflict. It's a compilation error, not a runtime error, so it looks like an issue with the build setup.

build.gradle looks like:
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:3.3.2"
        classpath "net.serenity-bdd:serenity-single-page-report:3.3.2"
    }
}

plugins {
    id "net.serenity-bdd.serenity-gradle-plugin" version "3.3.2"
    id 'java'
    id 'eclipse'
    id 'idea'
}

defaultTasks 'clean', 'test', 'aggregate'

repositories {
    mavenCentral()
}

sourceCompatibility = 11
targetCompatibility = 11

ext {
    serenityCoreVersion = '3.3.2'
    serenityCucumberVersion = '3.3.2'
    junitVersion = '5.9.0'
    assertJVersion = '3.23.1'
    hamcrest = '2.2'
    slf4japi = ':1.6.1'
    lombok = '1.18.24'
}

dependencies {

    implementation 'org.projectlombok:lombok:1.18.24'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.3'
    implementation 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    implementation 'net.serenity-bdd:serenity-rest-assured:3.3.2'


    testImplementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-junit5:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-rest-assured:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-cucumber:${serenityCucumberVersion}",
            "org.junit.jupiter:junit-jupiter-api:${junitVersion}",
            "org.junit.jupiter:junit-jupiter-engine:${junitVersion}",
            "org.assertj:assertj-core:${assertJVersion}",
            "org.hamcrest:hamcrest-library:${hamcrest}",
            'io.rest-assured:rest-assured:5.1.1'


}


test {
    useJUnitPlatform()
    enableAssertions = true
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

serenity {
    reports = ["single-page-html"]

    //testRoot = "starter"
}

gradle.startParameter.continueOnFailure = true
test.finalizedBy(aggregate)
