### ISSUE TITLE
Serenity not compatible with Firefox version 36.0

### ISSUE THREAD

**Issue by Xenguard** [serenity-bdd/serenity-core#29]
Just tested the project build with Mozilla Firefox version 36 today (2015-02-25).
Test failure results in an issue creating a new Firefox instance.

`org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
, setting schema version preference to 16`
...
`ERROR n.t.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver`

`net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver`

*Workaround:* Use Firefox 35.x Portable and set the `webdriver.firefox.bin` system property to the `firefox.exe` file path.

**Comment by wakaleo** [comment]
Thanks for pointing this out. I'll close it here as it is not technically a Serenity issue, but rather a known Selenium/Firefox issue (https://code.google.com/p/selenium/issues/detail?id=8399).

**Comment by alex-okrushko** [comment]
@wakaleo John, can you please update [the documentation here for serenity](http://thucydides.info/docs/serenity-staging/#_building_serenity_projects_in_gradle) to user newer version (that uses selenium with this bug solved)? 1.0.21 is not good. 
Took me some time to figure out what's wrong.

**Comment by BrahmendraJayaraju** [comment]
i am able to launch firefox 89.0.1 version firefox  but its not entering url  showing below warning.please help me which version is compatible for firefox   . Driver info: driver.version: FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Timed out waiting 45 seconds for Firefox to start.

**Comment by wakaleo** [comment]
Make sure your drivers are up to date or set webdriver.autodownload to true

**Comment by BrahmendraJayaraju** [comment]
i am not able to launch edge browser  please help me 
webdriver.driver=edge
webdriver.edge.driver=/src/test/resources/pm/drivers/msedgedriver.exe

System.setProperty("webdriver.driver", "edge");

**Comment by BrahmendraJayaraju** [comment]
i am not able to launch edge browser  please help me 
webdriver.driver=edge
webdriver.edge.driver=/src/test/resources/pm/drivers/msedgedriver.exe

System.setProperty("webdriver.driver", "edge");

**Comment by BrahmendraJayaraju** [comment]
It worked thanks a lot
