### ISSUE TITLE
Unexpected behavior: test mocks return value after exception is thrown

### ISSUE THREAD

**Issue by jpcastberg** [serenity-bdd/serenity-core#2900]
While running a test, a step may throw an exception. It seems that the exception is caught by Serenity, then the test moves forward. That step may have a return value. Following the exception, that return value is mocked by Mockito. If I try to use that return value, I get an exception, as the value is mocked instead of being the actual expected value.

The issue here is that I never actually see the exception that initially happened in console output or in the report file - only the error thrown as a result of trying to use the mocked value, making debugging a real pain.

My expected behavior is that as soon as an exception is thrown in a step, the test will fail and the stack trace for that exception would be printed.

I did see that there is a static method `Serenity.throwExceptionsImmediately()` that enables my expected behavior, which is cool, but would I have to add this to all my tests in a BeforeAll block? Could I add a property to serenity.conf to enable it all the time, or is there a reason I wouldn't want to do that?

Here is a code example that reproduces this behavior:
Steps: https://gist.github.com/jpcastberg/6d0f1f25d026a18f80e34fe1d9baee3f
Test: https://gist.github.com/jpcastberg/15285df37a232ba6c4a6bd814c564383

I am running Serenity version 3.3.2 on Java 17.

**Comment by wakaleo** [comment]
This is normal behaviour - Serenity continues the steps but returns stubs in order to generate the reports. The static method is the way to get this behaviour - there isn't a corresponding Serenity property.
