### ISSUE TITLE
Listeners are not called - Only called if forkCount=0

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#2909]
If I execute mvn verify of my project (based on last release and pom.xml of Cucumber Starter), none of my custom listeners are called.

But if I execute:
mvn verify -DforkCount=0 then my custom listeners are called.

**Comment by wakaleo** [comment]
Check the code how the listeners are read and cached - there might be some thread-local stuff going on.

**Comment by xescuder** [comment]
It worked in previous versions of Serenity. Which part of the code should I check?

**Comment by xescuder** [comment]
I've also tried with the SampleStepListener, not working

**Comment by wakaleo** [comment]
You'll need to look in the code to see how those clases are being loaded.

**Comment by xescuder** [comment]
Hi, @wakaleo. I think we've found a solution. If we add useModulePath false to failsafe plugin it works.

`<plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <useModulePath>false</useModulePath>
`
