### ISSUE TITLE
How to exchange session data between step classes

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2912]
Hi there,

I'm having a cucumber feature file, a test case linked with feature file and step classes, and further step classes. I'd like to exchange serenity session variable between the step classes.

StepClass1:
```
Object object1 = new Object(); // Pseudo code

@Before
public void setup() {
   Serenity.setSessionVariable("object1").to(object1);
}
```

StepClass2:
```
Object object2 ; // Pseudo code

@Before
public void setup() {
   if (Serenity.sessionVariableCalled("object1") != null) {
      object2 = Serenity.sessionVariableCalled("object1");
   }
}
```

Unfortunately, the session variable "object1" is null when called in StepClass2. How can I solve this problem? And how can I control the order of step classes setups called?

I'm using serenity version 3.2.5.

Thanks and regards, André

**Comment by aybartsch** [comment]
I found out that "serenity.maintain.session" needs to be set to true. Does this imply the session variable is known in other running tests, too? And my second question still remains: How can I control the order of step classes setups called?

**Comment by aybartsch** [comment]
It seems that the order I'm defining the "glue" in the test case is defining the order the step classes setups are called. Can you confirm my assumption?

**Comment by wakaleo** [comment]
You can also use the @Step(shared=true) annotation to inject shared objects between steps. Milage may vary if you run things in parallel though.

**Comment by aybartsch** [comment]
Thanks for the hint.
