### ISSUE TITLE
steps and screenshots not added in the serenity report after the successful test execution

### ISSUE THREAD

**Issue by Manasr1** [serenity-bdd/serenity-core#2913]
- Running test on chrome browser Version 105.0.5195.102 (Official Build) (64-bit) ,( i have not fire fox browser on my machine supported by serenity by default)
- Did not add chrome binary 
- in the serenity.properties , i have added _webdriver.driver=chrome_
-         <serenity.version>3.3.2</serenity.version>
        <serenity.maven.version>3.3.2</serenity.maven.version>

- added @steps annotation in the test class
- Test runs successfully
Issues -
Test passes but the console shows 'java.net.SocketException: Connection reset'
There is no screenshot and step added by default

![image](https://user-images.githubusercontent.com/31305121/188313231-d774e999-f522-42a0-ba02-52a8ddf9b8a6.png)
![image](https://user-images.githubusercontent.com/31305121/188313284-65fa8e91-2a09-420f-87d6-52c709be3bfc.png)
![image](https://user-images.githubusercontent.com/31305121/188313304-545da885-ed2d-4c1d-9946-b82481f4aa68.png)
![image](https://user-images.githubusercontent.com/31305121/188313425-f780c796-835d-44f9-9a8d-31659b16c728.png)

**Comment by wakaleo** [comment]
Are the screenshots enabled?

**Comment by Manasr1** [comment]
No, screenshots has not be enabled in the serenity.conf/serenity.properties file. But I was following your Udemy serenity-junit-starter course and in that course i did not see anywhere you enabled the screenshots. also @step was coming bydefault in the serenity report just by adding @steps annotation in the test class. But in my serenity report i did not see @step and snapshot are getting addded

**Comment by wakaleo** [comment]
The starter project setup may have changed since the course was recorded - by default screenshots are disabled, but you can enable them by uncommenting the `serenity.take.screenshots` option in `serenity.conf`
