### ISSUE TITLE
Report generation is not linking all the pages very well

### ISSUE THREAD

**Issue by andryi777** [serenity-bdd/serenity-core#2914]
Hi, please your help

I am working with serenity.version=3.3.2 and with io.appium-javaclient 8.1.1 for some mobile testing but when I finish my test and execute the command mvn:serenity:aggregate, the report is generated but without linking the test steps or test screenshots.

![image](https://user-images.githubusercontent.com/21963698/188395213-1fe76099-f17c-4062-a562-0e7b4550e2ed.png)

nevertheless, there are two pages with the steps and their screenshots but with a autogenerated name

![image](https://user-images.githubusercontent.com/21963698/188394953-89df1405-a2d6-487b-9636-8255049c786c.png)

here are my properties and dependencies of my POM.xml
```
	<properties>
		<serenity.version>3.3.2</serenity.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<encoding>UTF-8</encoding>
		<tags></tags>
		<parallel.tests>5</parallel.tests>
		<webdriver.base.url></webdriver.base.url>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
```

And these dependencies:

```
<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-ensure</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>8.1.1</version>
		</dependency>

```

**Comment by wakaleo** [comment]
Looks like you have a mix of compressed and uncompressed filenames - make sure `serenity.compress.filenames` is set to false and run `mvn clean verify`.

**Comment by andryi777** [comment]
Yes, as i am using a serenity.properties and android.properties, in the second one I not putted that line:
`serenity.compress.filenames=false`

So, now I added it works very well with all the pages linked (steps and screenshots), thank you @wakaleo !!
