### ISSUE TITLE
AcceptanceTestFullReporter not available in release 3.1.1

### ISSUE THREAD

**Issue by xescuder** [serenity-bdd/serenity-core#2915]
Hi. 

We've used for several years a customized class that extends **net.thucydides.core.reports.AcceptanceTestFullReporter** to add some values in generated XUnit file from custom annotations in our tests. The generated files are synchronized with HP ALM (also for regulatory purposes). 

The reporter class was easily defined in a META-INF/net.thucydides.core.reports.AcceptanceTestFullReporter file.

We've migrated to new versions of Serenity and it doesn't work anymore. It seems the class AcceptanceTestFullReporter is not available anymore, so we're stuck. We've seen the existence of class **ExtendTestOutcomeAdaptorReporter** that it seems very similar, but we don't find how to configure to use it with a custom class.

Thanks in advance.

**Comment by xescuder** [comment]
To be studied

**Comment by xescuder** [comment]
Hi, @wakaleo. I closed the issue some minutes ago, but it's a mistake. 
Have you any advise, clue or example? Thanks a lot.

**Comment by wakaleo** [comment]
The `AcceptanceTestFullReporter` interface and the corresponding class loader code hasn't changed in over 4 years - maybe have a look at the `ReportService` class to see what is happening.

**Comment by xescuder** [comment]
Thanks @wakaleo. Weird behaviour that also happened with another issue I opened related with step listeners. When I debug from IDE IntelliJ it works, but execution from Maven does not work, the code is not executed.

I've checked libraries and dependencies and everything seems correct. Do you know what is happening? (I've struggling several days with the other issue as well and I'm not able to see the problem).

Thanks a lot.

**Comment by wakaleo** [comment]
Hmmm, not sure. If it works in IntelliJ but not in Maven, it could be some kind of class loader issue perhaps?

**Comment by xescuder** [comment]
Hi, @wakaleo. Thanks for the suggestion to look at ReportService. I've found where it fails:

```
public static List<AcceptanceTestFullReporter> getDefaultFullReporters() {
       ...
        while (reporterImplementations.hasNext()) {
            AcceptanceTestFullReporter reporter = reporterImplementations.next();

``` 

At next if throws an exception of java.util.NoSuchElementException, with this stack trace: 

```
0 = {StackTraceElement@5661} "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
1 = {StackTraceElement@5662} "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
2 = {StackTraceElement@5663} "java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
3 = {StackTraceElement@5664} "java.base/java.lang.reflect.Method.invoke(Method.java:566)"
4 = {StackTraceElement@5665} "io.cucumber.java.Invoker.doInvoke(Invoker.java:66)"
5 = {StackTraceElement@5666} "io.cucumber.java.Invoker.invoke(Invoker.java:24)"
6 = {StackTraceElement@5667} "io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)"
7 = {StackTraceElement@5668} "io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:64)"
8 = {StackTraceElement@5669} "io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)"
9 = {StackTraceElement@5670} "io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)"
10 = {StackTraceElement@5671} "io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)"
11 = {StackTraceElement@5672} "io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)"
12 = {StackTraceElement@5673} "io.cucumber.core.runner.TestStep.run(TestStep.java:57)"

```
I've checked that target **test-classes** has the class. So I don't know what's happening.

**Comment by xescuder** [comment]
Solved with useModulePath set to false in failsafe plugin
