### ISSUE TITLE
Screenshots in the report are not centered

### ISSUE THREAD

**Issue by andryi777** [serenity-bdd/serenity-core#2919]
Hi

I am running a web automation test, with the serenity version 3.3.2 and the screenshot are not align to the center, maybe it could be good if it has a some space to the sides

![report_v3 3 2](https://user-images.githubusercontent.com/21963698/189545318-b1a36587-f970-4d04-844b-7d1ee5260418.png)

**Comment by wakaleo** [comment]
Unfortunately the JA control used by the screenshot carousel requires a fixed size, so short of rewriting that completely with a different component there's not a lot we can do.

**Comment by andryi777** [comment]
oh I see, in that case, would you recommend me what older version can I use to get the centered images?

**Comment by wakaleo** [comment]
This havent changed in quite a while...

**Comment by andryi777** [comment]
well , no problem , thanks @wakaleo
