### ISSUE TITLE
Screenshots appearing in report on failures even when disabled in serenity properties

### ISSUE THREAD

**Issue by derekjmoo** [serenity-bdd/serenity-core#2926]
Screenshots are still appearing in the report for failures even when they are disabled in the serenity properties file

serenity.properties file>
serenity.take.screenshots=DISABLED

This is occuring on versions 3.3.0 and above

This also has implications for the workaround for the issue below
https://github.com/serenity-bdd/serenity-core/issues/2878

**Comment by ametlan-wyn** [comment]
I can confirm that I am also observing same issue

**Comment by wakaleo** [comment]
Should be fixed in the next release

**Comment by suadhika** [comment]
Any update on this ticket? Which release should fix this issue?

**Comment by wakaleo** [comment]
It was fixed a while back - just use the latest release.

**Comment by suadhika** [comment]
No, I still get the same error with 3.4.3 and above.

**Comment by suadhika** [comment]
Ok I haven’t tried 3.6.23 and with 3.4.3 also I am not getting the screenshot. My question itself was wrong. But by disabling the screenshots I wanted the report in Jenkins when tests fail ,which is supposed to be the workaround for #2878 . So this one (#2926) is fine. Probably I should comment on #2878
