### ISSUE TITLE
Java Lang String error while using SendKeys

### ISSUE THREAD

**Issue by GaneshUma** [serenity-bdd/serenity-core#2927]
Hi Team,

I am a newbie for SerenityBDD while trying to use the sendKeys method I am getting an error as ' cannot resolve method ' sendKeys(java.lang.String)'. Could you please share your thoughts to resolve my issue?

![mySystemIssue](https://user-images.githubusercontent.com/32485186/190837794-926aa661-7356-4118-8373-79b50763e5b5.jpg)

PFA., snapshot for the same.

Thanks,
Ganesh

**Comment by lucas-nguyen-17** [comment]
I think it's problem of your IDE. It cannot resolve `String` or `Override` as well.
