### ISSUE TITLE
Screenplay interactions do not work on Mobile App

### ISSUE THREAD

**Issue by cacevedod** [serenity-bdd/serenity-core#2929]
I have a mobile automation project where the error is replicated: [devco seed](https://github.com/Devcognitio/serenitybdd_mobile_seed/tree/feature/actualizacion)

We updated to the latest version of serenityBDD (3.4.4) and updated the automation by removing some deprecated classes.

when we execute, it interacts with the first text field of the app and at the end it shows the following exception in Appium:

`[HTTP] --> GET /wd/hub/session/7eeac6d4-896e-4765-8019-5377017212e1/window
[HTTP] {}
[AndroidUiautomator2Driver@b95e (7eeac6d4)] Driver proxy active, passing request on via HTTP proxy
[debug] [AndroidUiautomator2Driver@b95e (7eeac6d4)] Matched '/wd/hub/session/7eeac6d4-896e-4765-8019-5377017212e1/window' to command name 'getWindowHandle'
[debug] [AndroidUiautomator2Driver@b95e (7eeac6d4)] Did not know how to rewrite the original URL '/wd/hub/session/7eeac6d4-896e-4765-8019-5377017212e1/window' for W3C protocol
[debug] [AndroidUiautomator2Driver@b95e (7eeac6d4)] Proxying [GET /wd/hub/session/7eeac6d4-896e-4765-8019-5377017212e1/window] to [GET http://127.0.0.1:8200/session/6649f164-4c99-43b1-9f09-7b0f57b37ed2/window] with no body
[AndroidUiautomator2Driver@b95e (7eeac6d4)] Got response with status 404: {"sessionId":null,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":"io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler...
[debug] [W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- GET /wd/hub/session/7eeac6d4-896e-4765-8019-5377017212e1/window 404 7 ms - 3529
[HTTP]
[HTTP] --> GET /wd/hub/session/7eeac6d4-896e-4765-8019-5377017212e1/window`

The interactions we use are:
` Enter.theValue("standard_user").into(TXT_USERNAME),
   Enter.theValue("secret_sauce").into(TXT_PASSWORD),
    Click.on(BTN_LOGIN)`

The Target are using:
`AppiumBy.accessibilityId`

We are testing with Appium 2.0.0-beta.44, An emulated Android Device and in Mac OS X version 10.16.

**Comment by wakaleo** [comment]
I'm not sure what to do about this - feel free to propose a PR if you have a solution.

**Comment by Rangiferus** [comment]
What happens when you add `Click.on(TXT_USERNAME)` before `Enter.theValue("xxx").into(TXT_USERNAME)`?

**Comment by cacevedod** [comment]
With the new versions of the libraries the error was corrected, I was not able to determine what the error was but it is no longer replicated.
