### ISSUE TITLE
How to change the name of the report?

### ISSUE THREAD

**Issue by nbauskar** [serenity-bdd/serenity-core#2940]
Hello,

I want the report name should contain the main of the feature which is been executed and not the time stamp. Please help

**Comment by arustamov** [comment]
serenity.project.name in serenity.conf is what you are looking for?

**Comment by nbauskar** [comment]
@arustamov I want to change the name of the report which gets saved in the project folder after execution of tests. Can we customize the report name?

**Comment by arustamov** [comment]
@nbauskar then as far as I understand it is **serenity.outputDirectory**

**Comment by wakaleo** [comment]
You can set the `serenity.compress.filenames` property to false. But this may cause problems with the maximum allowed filename lengths on Windows.

**Comment by wakaleo** [comment]
Closing presumed answered.
