### ISSUE TITLE
Question::How to access the values of the environment variables defined in Serenity.Conf for Junit Test?

### ISSUE THREAD

**Issue by CodeScratchDig** [serenity-bdd/serenity-core#2941]
environments {
default {
webdriver.base.url = "https://duckduckgo.com/"
}
dev {
webdriver.base.url = "https://duckduckgo.com/dev"
}
staging {
webdriver.base.url = "https://duckduckgo.com/staging"
}
prod {
webdriver.base.url = "https://duckduckgo.com/prod"
}
}

How can i specify the env during Junit Test unlike passing in env parameter in Mvn command.
I don't want to use default url but want to be able to specify the env.

**Comment by arustamov** [comment]
In serenity.conf set environment = dev/staging/prod (whatever you believe should be the default)
Running with maven then -Denvrionment to provide env for the run

**Comment by wakaleo** [comment]
Closing presumed answered.
