### ISSUE TITLE
How to ADD more characters to a text field input without clearing the input that is already there?

### ISSUE THREAD

**Issue by Mo0rBy** [serenity-bdd/serenity-core#2942]
I am trying to test a "Character validation" feature for a text input. The requirement is that no more than 1000 characters are allowed in the text box, when it is at the upper limit of 1000, the User should not be able to input anymore character into the field.

I am randomly generating a string of 1000 characters, asserting that my "0 characters remaining" message is shown, and then I want to assert that no more characters can be added to the input. To do this, I want to ADD 1 more character to the end of text that is in the input field, then assert that it is not there (User typed the character, but it has not been allowed into the input). My random string is letters only, so I am adding a "1" and then asserting that the "1" is not there.

My issue is that whenever I try and input something. The field get's completely cleared. Is there anyway to ADD this extra character to what is already in the input field, without having to input all 1000 characters again + the "1" character?

**Comment by wakaleo** [comment]
Use the sendKeys() function.

**Comment by Mo0rBy** [comment]
SendKeys() still clears the previous value. Let me try it again and check

**Comment by Mo0rBy** [comment]
Yes, I'm correct, using sendKeys() still clears the value that was previously entered into the text field. I've tried `Enter()` and `SendKeys()`. Found `Press()` on the Javascript documentation, but I don't believe that is available within the Java libraries.

**Comment by wakaleo** [comment]
SendKeys uses the Selenium sendKeys() command, which shouldn't clear the field first (unless you are using a very old version of Serenity).

**Comment by Mo0rBy** [comment]
Apologies @wakaleo , I had an extra rogue line that was clearing it, you are correct, SendKeys() is the one. Thank you!
