### ISSUE TITLE
Serenity Global Hook

### ISSUE THREAD

**Issue by peterwkc85** [serenity-bdd/serenity-core#2945]
Dear All, I had tried to implement cucumber hook using @Before and @After in a separate class but this class does not called by the serenityrunner. 

How to implement serenity hook?

public class Hooks {

public DAOManager daoManager;
public MFAManager mfaManager;
public UICompareManager uiCompareManager;
public CryptoManager cryptoManager;
public SpringInitManager springInitManager;
public CaptchaManager captchaManager;
public PropertiesManager propertiesManager;
public BrokenLinkChecker brokenLinkChecker;

private MyMailer emailer;

@Before
public void setup() {
daoManager = new DAOManager();
mfaManager = new MFAManager();
uiCompareManager = new UICompareManager();
cryptoManager = CryptoManager.getInstance(System.getProperty("user.dir") + "\\credential\\salt.txt");
springInitManager = new SpringInitManager();
captchaManager = new CaptchaManager();
propertiesManager = PropertiesManager.createInstance();
brokenLinkChecker = new BrokenLinkChecker();

emailer = new MyMailer();

}

@After
public void tearDown() {
emailer.sendEmail();
}

}

Please help. Thanks.

**Comment by peterwkc85** [comment]
Please help me.

**Comment by peterwkc85** [comment]
Anyone please help me.

**Comment by wakaleo** [comment]
See https://cucumber.io/docs/cucumber/api/?lang=java.

**Comment by peterwkc85** [comment]
I had checked the documentation but it doesn't have Global Hooks implemented for Cucumber-jvm. 

This website did highlighted all the solution. 
https://metamorphant.de/blog/posts/2020-03-10-beforeall-afterall-cucumber-jvm-junit/

**Comment by arustamov** [comment]
What is your runner class? Does it have @RunWith(CucumberWithSerenity.class) assigned?

**Comment by wakaleo** [comment]
BeforeAll and AfterAll methods need to be static. Something like this should work fine:
```
    @BeforeAll
    public static void runBeforeAnyTests() {
        System.out.println("BEFORE ALL");
    }
```

**Comment by peterwkc85** [comment]
It works after some move the GlobalHooks to glue folder. Thanks John
