### ISSUE TITLE
Could not instantiate new WebDriver instance if ONLY 'webdriver.capabilities.browserName' set and neither legacy 'webdriver.remote.driver' nor 'webdriver.driver' properties

### ISSUE THREAD

**Issue by arustamov** [serenity-bdd/serenity-core#2947]
So with the following config:
webdriver.capabilities.browserName - set
webdriver.remote.driver - NOT set
webdriver.driver - NOT set

Caused by: net.thucydides.core.webdriver.DriverConfigurationError:
Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Remote driver not specified - you need to specify the name of the remote driver either in the webdriver.capabilities.browserName or in the legacy webdriver.remote.driver or webdriver.driver properties.). See below for more details.

**Comment by wakaleo** [comment]
This is expected behavior - you need to define the driver at least using the webdriver.driver property.

**Comment by arustamov** [comment]
Then the error message looks misleading, doesn't it?

public static final String MISSING_REMOTE_DRIVER_PROPERTY = "Remote driver not specified - you need to specify the name of the remote driver either in the webdriver.capabilities.browserName or in the legacy webdriver.remote.driver or webdriver.driver properties.";

**Comment by wakaleo** [comment]
Fixed: https://github.com/serenity-bdd/serenity-core/commit/87af1b14f88d0b35857e699eee97ae934b6a6b55
