### ISSUE TITLE
not restarting chrome browser for each scenario-serenity

### ISSUE THREAD

**Issue by Vijay2871** [serenity-bdd/serenity-core#2951]
My Feature file looks like
![image](https://user-images.githubusercontent.com/54226136/197105293-ca494145-4b2d-4360-a4dc-aefb84a462b3.png)
This is not restarting for each scenario but works fine when i comment individually
In my serenity conf

![image](https://user-images.githubusercontent.com/54226136/197105407-82aae587-a37d-4816-87f9-fa44a0902f6b.png)

**Comment by wakaleo** [comment]
There is only one scenario in the image.
