### ISSUE TITLE
With @ExtendWith(SerenityJUnit5Extension.class)  and  @CsvFileSource -> produce Exception java.io.FileNotFoundException:

### ISSUE THREAD

**Issue by wilux** [serenity-bdd/serenity-core#2956]
**POM**     
   <serenity.version>3.3.4</serenity.version>
        <junit5.version>5.8.2</junit5.version>

**Code Example:** 

@ExtendWith(SerenityJUnit5Extension.class)
class UnitTest {

    @ParameterizedTest
    @CsvFileSource(resources = "/data/invalidUsers.csv")
    void loginWithValidUsers(String user, String pass) {
        System.out.println("User: " + user);
        System.out.println("Pass: " + pass);

        Serenity.reportThat("Test",
                () -> assertThat(user.equals(user))
        );
    }

}

**Log:**

Using @ExtendWith(SerenityJUnit5Extension.class)

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
12:35:26.315 [main] ERROR n.s.j.d.JUnit5CSVTestDataSource - Could not read test data file from \data\invalidUsers.csv
java.io.FileNotFoundException: Could not load test data from \data\invalidUsers.csv

**The file exist and it is get ok, the test passed on even the throw exception.  Why log de exception?**

[INFO] Running onlinebanking.tests.UnitTest
User: fakeUser1
Pass: 123456
User: fakeUser2
Pass: 123%456
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.107 s - in onlinebanking.tests.UnitTest
[INFO] 
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- serenity-maven-plugin:3.3.4:aggregate (serenity-reports) @ serenity-junit-starter ---
[INFO] Test results for 2 tests generated in 3.3 secs in directory: file:/C:/Users/nesto/IdeaProjects/onlineBanking_SerenityBDD/target/site/serenity/
[INFO] -----------------------------------------
[invalidUsers.csv](https://github.com/serenity-bdd/serenity-core/files/9853056/invalidUsers.csv)

Same example without using @ExtendWith(SerenityJUnit5Extension.class) No Exceptions error log!

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running onlinebanking.tests.UnitWithOutTest
User: fakeUser1
Pass: 123456
User: fakeUser2
Pass: 123%456
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.08 s - in onlinebanking.tests.UnitWithOutTest
[INFO] 
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO]

**Example without SerenityJUnit5Extension**
![WithoOutSerenityJUnit5Extension](https://user-images.githubusercontent.com/850505/197573304-2015d3b4-b0c7-42cb-b230-6fbdc363f65c.png)

**Example with SerenityJUnit5Extension**
![WithSerenityJUnit5Extension](https://user-images.githubusercontent.com/850505/197573309-15ca3611-acf6-4d01-bb84-66e6bf64890e.png)

**Comment by wakaleo** [comment]
This might be Windows-specific - I can't reproduce it at all.

**Comment by wilux** [comment]
Oh!, i see. The problem is with "resource" option, because if i try with "file" option and the complete path not exception found. But is posible that this might be Windows-specific. Thank you anyway. 
![image](https://user-images.githubusercontent.com/850505/199025626-22b96979-aad7-4e29-aece-aa756bb56cc7.png)

**Comment by ndagnhat** [comment]
> Oh!, i see. The problem is with "resource" option, because if i try with "file" option and the complete path not exception found. But is posible that this might be Windows-specific. Thank you anyway. ![image](https://user-images.githubusercontent.com/850505/199025626-22b96979-aad7-4e29-aece-aa756bb56cc7.png)

But datatest not show in serenity report 
![image](https://user-images.githubusercontent.com/65029229/211259689-7780d570-4bd9-48d9-9161-60c466f00fb5.png)
