### ISSUE TITLE
can not throw same exception multiple time when using serenity cucumber

### ISSUE THREAD

**Issue by ntthaibk** [serenity-bdd/serenity-core#2958]
I'm using serenity cucumber, I'm trying to implement a retry based on exception method. which look like this.
```
int retry = 10;
while(true){
try{
var events = getLogEvent();
}catch(TestContextException e){
 retry--;
continue;
}

if(!events.isEmpty()) break;
}


getLogEvent(){
log = getLog();
if(log.isEmpty){
throw new TestContextException("ABC);
}
return log;
}

```
when trying outside cucumber, it successfully throw exception multiple time, but when running from feature file using serenity cucumber, then it just can throw exception one time and get into infinity loop, by debugging, I saw that the first run it throw TestContextException Successfully, but in consecutive run, it move to invokeMethodAndNotifyFailures in DryRunMethodRunner class
I'm using Serenity bdd 3.3.2, anyone have any idea about this? thanks

**Comment by wakaleo** [comment]
Sound's like you should be using soft asserts for this. Once Serenity sees an exception, it will abort test execution and run the subsequent steps in dry-run mode.
