### ISSUE TITLE
Can I add Reporting ability of Serenity into an existing project which has its own dependencies already?

### ISSUE THREAD

**Issue by cbaquero-ar** [serenity-bdd/serenity-core#2961]
I'm working with an existinng framework that already has it base page objects and test base classes, and I want to use Serenity for reporting. Is this possible? The project is using TestNG but I plan to move to Cucumber. 
Thanks

**Comment by wakaleo** [comment]
If you are migrating from TestNG already it would probably be easier simply to rewrite the tests using Serenity - Serenity has it's own way of managing the WebDriver lifecycle events that won't work if you try to use your own page objects. You also lose the option of using a more modern pattern such as Screenplay.

**Comment by cbaquero-ar** [comment]
I see, is there any official documentation to follow on using Serenity with Page Objects pattern? I'm  not sure we can migrate _also_ to Screenplay pattern right now...

**Comment by wakaleo** [comment]
The official documentation is on https://serenity-bdd.github.io/.

**Comment by cbaquero-ar** [comment]
Sorry, I already read the documentation for Page Objects, I have to revisit. I was looking for a way to avoid migrating all my tests, but I will definitely reconsider. Thanks!

**Comment by cbaquero-ar** [comment]
I have tried for a couple of days now to extend PageObject class, but even when I see the serenity bdd core package contains it, is not being found by the compiler. Not sure if it's an issue with IntelliJ or the core library, I can't make it work at all.

**Comment by cbaquero-ar** [comment]
Is there any way to create and maintain my PageObject extending classes on `src/main/java` folder? Currently I was only able to extend PageObject class having my child classes under `src/test/java`

**Comment by wakaleo** [comment]
> Is there any way to create and maintain my PageObject extending classes on `src/main/java` folder? Currently I was only able to extend PageObject class having my child classes under `src/test/java`

You can place your page object classes anywhere you want, as long as you have the Maven dependencies in the right scope.

**Comment by cbaquero-ar** [comment]
Oh, I see! I was struggling with that witout noticing until an hour ago. Thanks!

**Comment by cbaquero-ar** [comment]
Is it possible to integrate Serenity with other Test Tracking tools than Jira? Thanks!

**Comment by cbaquero-ar** [comment]
I'm trying to use PageFactory within a PageObject extending class, but I get a NullPointerException when trying to access a WebElementFacade. Is there any example with PageObjets that you can refer with the complete code of a working PageObject child class? 
Here is mine:
`package pageobjects;

import exceptions.InvalidCredentialsLoginException;
import javafx.util.Duration;
import net.serenitybdd.core.annotations.findby.FindBy;
import net.serenitybdd.core.pages.PageObject;
import net.serenitybdd.core.pages.WebElementFacade;
import net.thucydides.core.annotations.At;
import net.thucydides.core.annotations.DefaultUrl;
import net.thucydides.core.annotations.WhenPageOpens;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.support.PageFactory;

import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalUnit;
import java.util.concurrent.TimeUnit;

@DefaultUrl("http://automation.sgh-os.10.125.125.74.nip.io/auth/login")
@At(urls={"#HOST/auth/login"})
public class LoginPage extends PageObject {

    @FindBy(xpath = ".//input[@formcontrolname='username']")
    public WebElementFacade user;
    @FindBy(xpath = ".//input[@formcontrolname='password']")
    private WebElementFacade password;
    @FindBy(xpath = ".//*[@translate='auth.login.form.SUBMIT']")
    private WebElementFacade loginButton;

    @FindBy(xpath = "//p[contains(@class,'ng-star-inserted')]")
    private WebElementFacade errorMessage;

    public LoginPage() {
        super();
        open();
    }

    @WhenPageOpens
    public void waitUntilPageLoads() {
        setWaitForTimeout(30000);
        user.waitUntilVisible();
        element(password).waitUntilVisible();
        element(loginButton).waitUntilVisible();
    }
}
`
