### ISSUE TITLE
Problem with EnhanceCapabilitiesWithFixtures

### ISSUE THREAD

**Issue by luanqauto** [serenity-bdd/serenity-core#2962]
serenity.version 3.3.10
I want to add capabilities by implemented FixtureService. However
- in "ChromeDriverProvider" class, at line "EnhanceCapabilitiesWithFixtures.using(fixtureProviderService).into(enhancedOptions)" > enhancedOptions cannot get options that I added by implemented FixtureService.
- by debugging, I see some problems in methods
    public <T extends MutableCapabilities> T into(MutableCapabilities options) {
        applyFixturesTo(options); 
        return (T) options; // --> **this return the original options (empty options), not the options after executed by "applyFixturesTo(options)"**
    }

    private void applyFixturesTo(MutableCapabilities options) {
        fixtureProviderService.getFixtureServices().forEach(
                fixtureService -> fixtureService.addCapabilitiesTo(options)
        );
    }
![image](https://user-images.githubusercontent.com/71999858/199655660-51946e7b-df9b-4c86-93ff-11dd146a2bf9.png)

**>> So the method "applyFixturesTo(MutableCapabilities options)" should return the options that were implemented by "FixtureService"**

**Comment by wakaleo** [comment]
Thanks for spotting this. Could you make the change locally and test with a snapshot build, and if it works to your satisfaction propose a PR?

**Comment by wakaleo** [comment]
I took a look at the code - applyFixturesTo doesn't return a value, it just acts on the options passed to it, so this part of the code behaves as expected.
