### ISSUE TITLE
 Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.4.2:aggregate failed: Collection contains no element matching the predicate.

### ISSUE THREAD

**Issue by Cvarshney-clgx** [serenity-bdd/serenity-core#2973]
Hi, when I upgraded the serenity plugin to 3.4.2 I was not able to reproduce it. So it seems like it is fixed in that version.

_Originally posted by @MartinxCieslar in https://github.com/serenity-bdd/serenity-core/issues/2968#issuecomment-1314095193_

**Comment by Cvarshney-clgx** [comment]
@wakaleo Getting this error "Collection contains no element matching the predicate. " for serenity 3.4.X versions Collection contains no element matching the predicate. while running aggregare goal.

**Comment by wakaleo** [comment]
Is this reproducible?

**Comment by Cvarshney-clgx** [comment]
> Is this reproducible?

Yes

**Comment by baskarcsb** [comment]
Here is the sample project and the reproducible logs available @ https://github.com/baskarcsb/Sample3.4.2/actions/runs/3552105419/jobs/5966795514

**Comment by 07himanshu** [comment]
Hi All, 

i am also seeing similar issue after upgrading serenity to 3.4.2

**Comment by wakaleo** [comment]
This was fixed in 3.4.3

**Comment by chanduguthikonda** [comment]
@wakaleo 
We are using gradle and I see that the latest serenity-gradle-plugin version is 3.4.2 and I'm still able to reproduce the issue  "Execution failed for task ':aggregate'. > Collection contains no element matching the predicate".
Is it going to be fixed for gradle plugin any time soon?

**Comment by pgupta26** [comment]
@wakaleo - As you mentioned it is fixed in version 3.4.3, can you let me know from where I can download this version as am not able to see this version on gradle plugins page 0 https://plugins.gradle.org/plugin/net.serenity-bdd.serenity-gradle-plugin

**Comment by wakaleo** [comment]
Use 3.5.0 or higher.
