### ISSUE TITLE
Serenity tests are not fully recognized and reports are not generated when multiple @ExtendWith annotations are set for a class

### ISSUE THREAD

**Issue by ovolynets** [serenity-bdd/serenity-core#2982]
While debugging a problem with generating test reports, it looks like I found a bug when a serenity test class has more than one `@ExtendWith()` annotation. Here is an example of such usage:
```java
@ExtendWith(SerenityJUnit5Extension.class)
@ExtendWith(DataProviderExtension.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class MySerenityIT {
    @Test
    public void myTestShouldSucceed() {
        ...
    }
}

```

The issue is in [this code](https://github.com/serenity-bdd/serenity-core/blob/main/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityTestExecutionListener.java#L549-L554):
```java
static boolean isSerenityTestClass(Class<?> testClass) {
        return classNestStructure(testClass).stream()
                .filter(clazz -> clazz.getAnnotation(ExtendWith.class) != null)
                .map(clazz -> clazz.getAnnotation(ExtendWith.class))
                .anyMatch(annotation -> Arrays.asList(annotation.value()).contains(SerenityJUnit5Extension.class));
    }
```

which identifies a serenity test by having `@ExtendWith` annotation with `SerenityJUnit5Extension` value. The problem is in the usage of multiple `@ExtendWith` annotation by junit5.

According to [their documentation](https://github.com/junit-team/junit5/blob/main/junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtendWith.java#L43), it should be possible to combine multiple annotations. However, they are grouped under a different, `@Extensions`, annotation, see [this part](https://github.com/junit-team/junit5/blob/main/junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtendWith.java#L93), and the filter in `isSerenityTestClass()` returns false in this case, although `@ExtendWith(SerenityJUnit5Extension.class)` is there. It should, in this case, also check if `@Extensions` annotation is present and has one of its values for `SerenityJUnit5Extension.class`, among possible others.

As a result of this behaviour, there are no serenity test reports generated. This might be related to the issue reported in #2689, although it seems there is not enough data to make conclusions for that issue.

If someone could confirm that this behaviour is indeed not intended and/or is as a bug, I could try to provide a fix.

**Comment by wakaleo** [comment]
It's definitely not intentional - please do see if you can see anything.

**Comment by ovolynets** [comment]
We can mark this issue as duplicate of https://github.com/serenity-bdd/serenity-core/issues/3117 which was fixed in the meantime. Thanks @hinnerkoetting for providing the fix
