### ISSUE TITLE
ExceptionInInitializerError: Exception com.google.inject.internal.cglib.core.$CodeGenerationException:

### ISSUE THREAD

**Issue by nicholaswkc34** [serenity-bdd/serenity-core#2983]
Dear All, I tried to code serenity version 3.3.4, maven 3.8.1 and java 13/19, suddenly the code cannot be run anymore. 
I treid different version of Java like java 13, java 17 18 19 but none of this works. The maven version is the latest from intellij IDE. 

The complete exception log is here.

java.lang.ExceptionInInitializerError: Exception com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2d1ef81a [in thread "main"]

I had run out of idea to solve it. Please help me. Thanks in advance

**Comment by nicholaswkc34** [comment]
Dear all, i solved the problem by deleteing the .idea folder and rerun it. It works. There is another problem arise which is no browser was open when it running, it just display some test result to the console.

**Comment by wakaleo** [comment]
Thanks for the feedback Nicholas.
