### ISSUE TITLE
Can't open chrome with extension after upgrade to 3.4.1

### ISSUE THREAD

**Issue by OussamaAutomation** [serenity-bdd/serenity-core#2985]
Hello,

i was using Serenity 3.1.10 and i was using this option in the serenity.properties to install extension on chrome: 
chrome.extension=C:/Projects/chrome-modheader/modheader.crx

But after upgrade serenity to 3.4.1  chrome is opened without installing the extension.

Any idea on how to solve this issue ?

Thanks.

**Comment by wakaleo** [comment]
This property is no longer supported: use the W3C properties instead (see https://serenity-bdd.github.io/docs/guide/driver_config#configuring-chrome)

**Comment by OussamaAutomation** [comment]
> This property is no longer supported: use the W3C properties instead (see https://serenity-bdd.github.io/docs/guide/driver_config#configuring-chrome)

Okay thank you
