### ISSUE TITLE
Handling driver instance for mobile testing

### ISSUE THREAD

**Issue by aadhi00** [serenity-bdd/serenity-core#2988]
I am in the process of scaling the automated tests to run on saucelabs. I am able to run the tests independently without any issues. However, to optimise the tests a little bit more I want to make use of keeping the session open in between scenarios, so that the app doesn't get installed and uninstalled every time. 

In order to achieve this, I need to be able to control the driver instance of the appiumdriver. But I am unable to do that.

The current way of running tests
1. Install app and create a session
2. Run the first test
3. End the session
4. Install app and create a new session
5. Run the second test
6. End the session

What I want to achieve is
1. Install app and create a session
2. Run the test
3. Restart the app
4. Run the next test
5. End the session

**Comment by Rangiferus** [comment]
I've been successful to achieve the desired behavior using this code:
In @Before hook:
`
        if (!FIRST_SCENARIO) {
            try {
                log.info("Re-launching the app");
                if (MobileDevice.isAndroid()) {
                    ((AndroidDriver) RemoteDriver.of(getDriver())).activateApp("your.app");
                } else {
                    ((IOSDriver) RemoteDriver.of(getDriver())).activateApp("your.app");
                }
            } catch (Exception e) {
                // do nothing, it's the beginning of test suite, driver not yet initialized
                log.info("ignored exception");
            }
        }
`

In @After hook:
`
            if (MobileDevice.isAndroid()) {
                ((AndroidDriver) RemoteDriver.of(getDriver())).terminateApp("your.app");
            } else {
                ((IOSDriver) RemoteDriver.of(getDriver())).terminateApp("your.app");
            }
`

**Comment by aadhi00** [comment]
for me the driver actually becomes null before entering the @after. which version are you using?

**Comment by Rangiferus** [comment]
You need to set serenity.restart.browser.for.each to never or otherwise your driver is destroyed after each scenario.
I'm using Serenity 3.4.3 but it doesn't matter.

**Comment by aadhi00** [comment]
That helped. Thanks.
