### ISSUE TITLE
ThucydidesWebDriverSupport.getSessionId() return null

### ISSUE THREAD

**Issue by marek5050** [serenity-bdd/serenity-core#299]
Hello,
I've been trying to get Serenity reports to recognize that I'm using Saucelabs. For some reason when I execute **mvn verify** it generates the reports but the TestOutcome objects have sessionsid's set to null. Even thought if I cast the webdriver properly during debugging it provides me with a SessionId. From my understanding it breaks down at the **updateSessionIdIfKnown** method of **BaseStepListener.java**  
When I set a breakpoint within  **updateSessionIdIfKnown** and execute 
((RemoteWebDriver)((WebDriverFacade) getDriver()).getProxiedDriver()).getSessionId()
 returns the correct sessionId

![screenshot not being set](https://cloud.githubusercontent.com/assets/6081895/12877294/c4c16e16-cdd6-11e5-95c5-e2f8fa4d59ac.PNG)

However the current:
SessionId sessionId = ThucydidesWebDriverSupport.getSessionId(); 
returns a null. 
![sessionid_not_being_set_2](https://cloud.githubusercontent.com/assets/6081895/12877295/c746a6ce-cdd6-11e5-9367-19b37d110898.png)

Later on when I do mvn serenity:aggregate the build-info.html has the SessionId in it and SessionId is also available in the context["build"] during aggregation.  

Here's the repo to reproduce:
https://github.com/marek5050/selenium-serenity-jbehave-base/tree/SessionIdNull

Expectation:
If the SessionId is not set then the image functionality in default.ftp doesn't work. 
```
<#if (testOutcome.videoLink)??>
         <a href="${relativeLink!}${testOutcome.videoLink}"><img class="story-outcome-icon"
                  src="images/video.png" width="25"
                  height="25" alt="Video"/></a>
</#if>
```

**Comment by YamStranger** [comment]
Hello @marek5050 Thanks for your issue!!!

Yes it is a bug, will fix it soon.

**Comment by YamStranger** [comment]
@marek5050 please check it in next release (or with source code of current release). It should be fixed

Thanks for helping us making serenity bdd better!!!

Also, if you feel that this issue solved - please close this ticket.

**Comment by marek5050** [comment]
Thank you for the quick response!
