### ISSUE TITLE
Switching back to the parent frame automatically

### ISSUE THREAD

**Issue by MHabiib** [serenity-bdd/serenity-core#2990]
Hi, i found an issue
so example i have 2 steps
step 1 switch to frame we called frameX
step 2 get element from  frameX
and will throw error element not attracable

this because serenity try to take a screenshot from step1 so it will back to parent frame
and when step 2 executed it will throw error becaues its not on frameX anymore

**Comment by wakaleo** [comment]
Well spotted. Can you propose a fix?

**Comment by wakaleo** [comment]
Have a look at the WebDriverPhotoLens class. It switches back to the window identified by driver.getWindowHandle(). If this is not the current frame, and you have a way of identifying the current frame, then this is where you would need to change the code.

**Comment by MHabiib** [comment]
hi @wakaleo , for now, I'm still not found any way to identify the current frame, what if I add flagging on that line, so the user can decide to check on alert or not?

**Comment by MHabiib** [comment]
working on it, will test best possible way to solve this @wakaleo

**Comment by MHabiib** [comment]
dropped the pr @wakaleo, kindly please check that

**Comment by MHabiib** [comment]
hi, @wakaleo is there any ETA to release the new version of the serenity?

**Comment by MHabiib** [comment]
hi, @wakaleo is there any ETA to release the new version?

**Comment by wakaleo** [comment]
Probably early Jan

**Comment by wakaleo** [comment]
This should be in versions 3.5.2 and 3.6.0
