### ISSUE TITLE
webdriver.timeouts.implictlywait works rather than webdriver.capabilities.timeouts.implicit

### ISSUE THREAD

**Issue by edudelta** [serenity-bdd/serenity-core#2993]
Are there difference between **webdriver.timeouts.implictlywait** and **webdriver.capabilities.timeouts.implicit**?
For both 3.4.2 and 3.4.3 with **webdriver.capabilities.timeouts.implicit** (according W3C capabilities as here https://serenity-bdd.github.io/docs/guide/driver_config#configuring-timeouts) as 0sec I'm facing errors like
```
org.openqa.selenium.ElementNotInteractableException: Timed out after 2 seconds. Element not available
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6.2', java.version: '18.0.2.1'
Driver info: driver.version: unknown
```
however when I define **webdriver.timeouts.implictlywait** (according https://serenity-bdd.github.io/docs/guide/page_objects#implicit-waits) It's failing by 0sec as expected.

**Comment by wakaleo** [comment]
The timeouts in webdriver.capabilities are being passed directly to the driver, so the driver is interpreting them, not Serenity. Maybe have a look in the Serenity code to see if the implicit timeouts aren't being overridden somewhere later on.

**Comment by edudelta** [comment]
There is no other place overriding timeout. Looks like **webdriver.capabilities.timeouts.implicit** does not change implicit timeout as **webdriver.timeouts.implictlywait** does.

**Comment by edudelta** [comment]
Yes, this is the situation. When I define webdriver.capabilities.timeouts.implicit I don't see implicit timeout working as expected.
