### ISSUE TITLE
by default set to acceptInsecureCerts: false even though provided in configuration on serenity 3.4.2 ,3.4.3 and 3.5.0

### ISSUE THREAD

**Issue by sankar067** [serenity-bdd/serenity-core#2994]
serenity.conf

webdriver {
  capabilities {
    acceptInsecureCerts = true
  }
}

[pool-2-thread-1] INFO net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider - Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}

In debug mode, it was updated (ChromeDriverProvider.class) after execution of below line 
ChromeOptions chromeOptions = W3CCapabilities.definedIn(environmentVariables).withPrefix("webdriver.capabilities").chromeOptions();

next line it default set to false again

ChromeOptions enhancedOptions = (ChromeOptions)ConfigureChromiumOptions.from(environmentVariables).into(chromeOptions); 

Update with properties serenity.driver.capabilities=ACCEPT_INSECURE_CERTIFICATES:true still default set to false

**Comment by wakaleo** [comment]
Thanks for locating the source of the issue. Can you provide a fix in a PR?

**Comment by wakaleo** [comment]
Should be fixed in the next release.

**Comment by sankar067** [comment]
Thanks @wakaleo
