### ISSUE TITLE
SearchingOnGoogleStory.java need to be updated from ThucydidesRunner to SerenityRunner

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#30]
import net.thucydides.junit.runners.ThucydidesRunner; 

to 

import net.serenitybdd.junit.runners.SerenityRunner;

also
@RunWith(SerenityRunner.class) from @RunWith(ThucydidesRunner.class)

Thanks & Regards,
Vikram

**Comment by wakaleo** [comment]
This class is not part of serenity-core - could you make a pull request on the corresponding repo?
