### ISSUE TITLE
Getting  RemoteWebDriver cannot be cast to io.appium.java_client.AppiumDriver error 

### ISSUE THREAD

**Issue by Ramesh1103** [serenity-bdd/serenity-core#3005]
With  serenity version 3.4.2 i am getting .RemoteWebDriver cannot be cast to io.appium.java_client.AppiumDriver error while reading android properties from Serenity.conf , and when I am trying to retrieve getDriver() i am getting **Driver :Uninitialised WebDriverFacade**

Sample config file 
environments{
 android  {
       webdriver{
            driver = "remote"
              remote{
       		  url="http://localhost:4723/wd/hub"
       		  driver = "appium"
       }
       capabilities {
       app= "App path"
       appPackage="Package Path"
       platformName="Android"
       platformVersion="7.1.1"
       deviceName="emulator-5554"  
       autoGrantPermissions= true
       	}
       }
    }
}

Run command : mvn clean verify -D environment=android 

Earlier with serenity 3.1.5 I am maintained serenity.conf as below and able to run mobile tests successful 
android {
       webdriver.driver = "remote"
       webdriver.remote.driver="appium"
       webdriver.remote.url="http://localhost:4723/wd/hub"
       appium.app="$Path to apk"
	appium.appPackage="path to package"
       appium.platformName="Android"
       appium.platformVersion="7.1.1"
       appium.deviceName="emulator-5554"  
    } 
    
 can this issue is a configuration issue ?

**Comment by wakaleo** [comment]
Possibly. For Appium issues, the best is to dive into the code and see what is going on - it is very much community supported via community pull requests.

**Comment by Ramesh1103** [comment]
@wakaleo   i tried the problem its unable retrieve getDriver() hence not able to type cast to appium driver as below 
AppiumDriver appiumDriver = ((AppiumDriver) ((WebDriverFacade) getDriver()).getProxiedDriver());

getDriver is unable to recognize driver as **remote**  from config file.

**Comment by ricardorlg-yml** [comment]
try this:

```
environments{
android{
  webdriver.driver = appium
    appium.platformName = "Android"
    appium.automationName = "UiAutomator2"
    appium.app = "path to apk"
    appium.autoGrantPermissions = true
    appium.allowTestPackages = true
    appium.newCommandTimeout = 0
    appium.unicodeKeyboard = true
    appium.resetKeyboard = true
    appium.deviceName= emulator-5554
}
}
```

**Comment by Ramesh1103** [comment]
Thanks @ricardorlg-yml ,
Now i am able to run tests .

**Comment by sumit-global** [comment]
@Ramesh1103 could you please help with your serentiy.conf file with sensitive information as masked? It will be great help
