### ISSUE TITLE
The size of report folder increases when upgrade to 3.5.1

### ISSUE THREAD

**Issue by ikallala** [serenity-bdd/serenity-core#3012]
There is a big difference in the size of report folder between the 3.2.5 version and 3.5.1 .
In a test suite which contains 1800 scenarios, the size increases from 3 go to 22 go. 

This is a simple project to reproduce the issue https://github.com/ikallala/SampleSerenityTest/tree/master (in this example the size passed from 12.3 mo to 16.5 mo, only 3 scenarios)

This difference in size becomes from generation of new the framed file in 3.5.1 (in screenshot below, the target of the same scenarios with different version )

![image](https://user-images.githubusercontent.com/74077850/212033106-ff7e125a-bf90-4011-8589-96a11f0e45ae.png)

**Comment by wakaleo** [comment]
This looks normal - the reports in 3.5.1 are richer and more complete than in 3.2.5. Can you see any indication of additional files that are not actually part of the reports?

**Comment by ikallala** [comment]
I don't see any files that are not actually part of the reports. but this difference of size causes many problems, the size of a report of a test suite (1800 scenarios) increases from 3go to 22go, that impacts our resources (server on which we execute tests).

**Comment by wakaleo** [comment]
Here are a few things you can do:

- If you don't want the html page source being stored, you can set the `serenity.store.html` property to "never".
- You can also set `serenity.generate.csv.reports` to "false" to reduce the number of files.

But all the HTML files generated are required for the reports to work correctly.

**Comment by ikallala** [comment]
This error appears when I added the property serenity.core.htlm **No enum constant net.serenitybdd.core.photography.StoreHTML.never** (reproduced only with 3.5.1, neither 3.2.5)

**Comment by wakaleo** [comment]
```
serenity.store.html=NEVER
```
