### ISSUE TITLE
Gradle cucumber: pending scenarios makes the build fail

### ISSUE THREAD

**Issue by GianniGiglio** [serenity-bdd/serenity-core#3016]
Hi,

Am using cucumber with serenity and gradle.
Whenever a scenario is not yet implemented the report is generated correctly showing the details of all scenarios including the pending ones. However the gradle task fails the build.

com.collibra.aggregator.smoke.CatalogTestSuite > Datamarket place.Navigate to the datamarket place settings page FAILED
    io.cucumber.junit.UndefinedStepException
    
I would expect the build to pass since those test are not yet implemented but I still want them to be reported.

Is this the expected behavior? 

Thanks for looking into it.

**Comment by wakaleo** [comment]
This is normal Cucumber behaviour - Cucumber will always fail if there are missing step definitions. It's also outside of the scope of Serenity to affect this behaviour.
