### ISSUE TITLE
Aggregate report is not showing untested count properly 

### ISSUE THREAD

**Issue by Prasadsimha** [serenity-bdd/serenity-core#304]
Aggregate report is not showing untested count properly in Requirements Overview section. 
I have 42 epics and it is showing 455 ....

I am using serenity-jira-requirements-provider plugin . 
![report](https://cloud.githubusercontent.com/assets/16546423/12930754/2651b4ac-cf48-11e5-9438-2ebbaca77b2c.png)

And also please advise any way to avoid all the requirements (bugs, tasks) in aggregate report . 

REgards
Prasad Banala

**Comment by YamStranger** [comment]
Hello @Prasadsimha 

Please add some additional details: 
1) Are your tests use some-kind examples? (http://thucydides.info/docs/serenity-staging/#_detailed_description_of_aggregation_reports)

2) Is it possible provide some working example of your project? 

Thanks!

**Comment by YamStranger** [comment]
This bug can not be reproduces without additional details. Will close this issue
