### ISSUE TITLE
Illegal reflective access by net.thucydides.core.steps.StepInterceptor

### ISSUE THREAD

**Issue by ivtu** [serenity-bdd/serenity-core#3045]
Using OpenJDK 17:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.thucydides.core.steps.StepInterceptor (file:/C:/Users/tufegdzi/.m2/repository/net/serenity-bdd/serenity-core/3.6.9/serenity-core-3.6.9.jar) to field java.lang.reflect.Method.root
WARNING: Please consider reporting this to the maintainers of net.thucydides.core.steps.StepInterceptor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by globalworming** [comment]
thanks for reporting
