### ISSUE TITLE
Ensure class is not found in newer version 3.6.12 (gradle)

### ISSUE THREAD

**Issue by cb-duppanapudisurya** [serenity-bdd/serenity-core#3052]
previously I am using testImplementation "net.serenity-bdd:serenity-ensure:3.2.1" but i changed this to 3.6.12. I am facing the error saying cannot find ensure class. But I can able to find this in maven but when I am trying to run using gradle i am facing this issue.

**Comment by wakaleo** [comment]
Do you have the exact error?

**Comment by cb-duppanapudisurya** [comment]
<img width="747" alt="Screenshot 2023-02-14 at 9 55 26 AM" src="https://user-images.githubusercontent.com/98867630/218639479-b61da3e4-6f80-4394-ad06-1657242ca2b9.png">

I am getting this error.

**Comment by wakaleo** [comment]
Looks like an IDE error - the Ensure class is still there. 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/55986/228559169-b18392a0-adf0-4f80-9e88-11ef485abb8e.png">
