### ISSUE TITLE
We need to know how to force the execution of a test to fail by a self-validation of the test.

### ISSUE THREAD

**Issue by davidGFerruelo** [serenity-bdd/serenity-core#3055]
Hi,
We need some information about how we force to break a test in validation for "if" sentence in a "task" something like that:

![image](https://user-images.githubusercontent.com/90895982/219421520-e1082a51-83e9-4a4c-8457-9610039c884a.png)

Thanks for your support.

**Comment by davidGFerruelo** [comment]
Hello, would anyone know how to force this execution to "failed"?

**Comment by wakaleo** [comment]
Just use an assertion for that, e.g.
```
String notification = actor.asksFor(Text.of(RESULT_NOTIFICATION));
assertThat(notification).isIn("repearedReception","repeatedReceptionAlternative");
```

**Comment by davidGFerruelo** [comment]
Ok, perfect with "isIn", ok ok 
Thanks for your support @wakaleo !
