### ISSUE TITLE
Manual tests takes very long time to execute, exactly 1 minute for each

### ISSUE THREAD

**Issue by macken920** [serenity-bdd/serenity-core#3063]
Hi,

My api / frontend tests are as fast as possible, but for some reason when i want to run @manual-result:passed or @manual-result:failed each test takes exactly 1 minute. Can you advise here. Is there any additional options to speed it up? I assume it is waiting for real user to execute test in meantime but not sure.

**Comment by globalworming** [comment]
that shouldn't be the case
can you share a minimal example project that shows this behaviour?

my best guess right now is that your manual tests are invoking setup or teardown methods that maybe do http requests that time out after 60 seconds :shrug:

**Comment by macken920** [comment]
I found the issue. It happens only if part of manual steps is automated. After i remvoed all steps definitions it works very fast.
