### ISSUE TITLE
Logs are not refreshed but prints in bulk

### ISSUE THREAD

**Issue by svjohny** [serenity-bdd/serenity-core#3068]
I am using Serenity 2.4.34. After upgrading to java 17 my serenity report console logs are not behaving correctly. It waits for 20 to 30 mins and then prints the whole log as a bulk. Again repeats.It doesn't print logs for each timeframe

slf4j version 1.7.25

![image](https://user-images.githubusercontent.com/126460640/221756772-e0976825-b81e-4c69-a9dc-f6d8138814b9.png)

**Comment by wakaleo** [comment]
This is presumably related to the slf4j configuration, not Serenity.
