### ISSUE TITLE
No Capabilities report is generated with Serenity version 3.6.12

### ISSUE THREAD

**Issue by malekadrar** [serenity-bdd/serenity-core#3069]
After upgrading Serenity  from 2.3.31 to 3.6.12, only "Overall Test Results", "Requirements", "Themes" and "Features" are generated, but not "**Capabilities**", in the final report.
	
Note: my feature files are always stored in src/test/resources/features directory having always the same structure.

With Serenity 3.6.12
![image](https://user-images.githubusercontent.com/64359976/221813643-fda7e6f6-6b5c-4c8d-95a8-7b37d3254e46.png)

With Serenity 2.3.31
![image](https://user-images.githubusercontent.com/64359976/221814306-6c9669c1-dfe5-4c9b-a5cc-8a6e7aab6fc2.png)

**Comment by wakaleo** [comment]
This will depend on your requirements setup in serenity.conf and the structure of your requirements directory.

**Comment by malekadrar** [comment]
First, I'd like to point out another mismatch with the  [online documentation](https://serenity-bdd.github.io/docs/reference/serenity-properties). The name of this parmeter is:
serenity.**requirement**.types and not serenity.**requirements**.types (there is no **s** for requirements)

I set serenity.requirement.types=theme,capability,feature and here is the structure of my requirements directory:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/64359976/222667263-f0ece331-db58-4adf-8530-017382c7699c.png">

So I'm expecting to get "Date And Time" as theme and "Relative date time" as capability, but I get both under themes.

**Comment by wakaleo** [comment]
Can you provide a sample project? 

Thanks for spoting the typo in the docs - please feel free to raise a PR to fix it.

**Comment by malekadrar** [comment]
Here is a sample which reproduce the problem. I expect to have in the report one theme on "Math operators" and two capabilities for "Addition" and "Division".

[Sample.zip](https://github.com/serenity-bdd/serenity-core/files/10883547/Sample.zip)

**Environment**: 
Visual Studio Code
Windows 11 Professionnel
Java 11.0.10

**Comment by wakaleo** [comment]
Fixed in 3.6.22
