### ISSUE TITLE
Maven clean takes longer time when deleting the serenity reports in target folder

### ISSUE THREAD

**Issue by NandhakumarSubbaiah** [serenity-bdd/serenity-core#3073]
**Serenity cucumber dependency :**
<dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>3.2.1</version>
        </dependency>

**Maven execution plugin:**
<groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>

**Additional Note :**
1.target/site/serenity folder contains 3000+ files
2. When I run with **mvn clean**, It is taking more than 7 minutes to execute. When running with mvn  -T 4 clean, It takes more than 3 minutes to delete the target folder.
3. While deleting the target folder manually, It takes less than 90 seconds.

**Comment by wakaleo** [comment]
Even 90 seconds to delete a folder sounds very slow, but I don't think it's related to Serenity (maven does the actual IO operations when you do man clean). This sounds like an OS or environment issue - do you have an antivirus running?

**Comment by NandhakumarSubbaiah** [comment]
If I delete the serenity folder alone manually  (target/site/serenity), mvn clean takes less than 10 seconds to complete the clean command execution.

**Comment by globalworming** [comment]
TIL: the clean plugin has a [fast mode](https://maven.apache.org/plugins/maven-clean-plugin/clean-mojo.html#fast)

**Comment by wakaleo** [comment]
Closing as unrelated to the Serenity code.
