### ISSUE TITLE
Typo in the documentation.

### ISSUE THREAD

**Issue by malekadrar** [serenity-bdd/serenity-core#3074]
I'd like to point out a mismatch with the [online documentation](https://serenity-bdd.github.io/docs/reference/serenity-properties) about the parameter on the hierarchy of requirement types:

serenity.**requirements**.types doesn't work, I had to use instead   serenity.**requirement**.types (without **s** for requirements)

**Comment by wakaleo** [comment]
Can you propose a PR - you can use the "Edit this page" button at the bottom to propose a fix.

**Comment by malekadrar** [comment]
Well done!
