### ISSUE TITLE
How to solve critical chromedriver 111 issue?

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#3083]
Dear Serenity Devs.

With the update of chrome browser and chrome driver to version 111 a critical communication issue has been started:

```
Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 5117
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Mar 10, 2023 10:16:20 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Invalid Status code=403 text=Forbidden
java.io.IOException: Invalid Status code=403 text=Forbidden
```

According to the thread on [groups.google](https://groups.google.com/g/chromedriver-users/c/xL5-13_qGaA) this issue seems to be caused by selenium itself. The workaround mentioned is to apply the chrome option "--remote-allow-origins=*".

Unfortunately, I cannot apply this switch in "serenity.conf" correctly i.e. the error is still shown. The below was not working:
```
chrome.switches = "--remote-allow-origins=*"
```

Why is the above switch not working as expected? Please, help to solve this critical issue.

Thanks and best regards, André

**Comment by abergmeister** [comment]
I got it working by adding it like this:

`"goog:chromeOptions" {
      args = ["remote-allow-origins=*", ...]
    }`

**Comment by wakaleo** [comment]
Thanks @abergmeister. The `chrome.switches` option is deprecated since Serenity 3.3.0 as using the w3c options is the preferred approach.

**Comment by aybartsch** [comment]
Problem solved! Thanks to both of you.

**Comment by aybartsch** [comment]
Unfortunately, I cannot use firefox driver when defining chrome options anymore.
```
net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.firefox.FirefoxDriver
WebDriver reported the following message: Could not start a new session. Response code 500. Message: Unable to find a matching set of capabilities 
```
How can I define the capabilities for chrome driver only?

**Comment by aybartsch** [comment]
Solved by myself when removing the capability "browserName=chrome".

**Comment by jerrin89** [comment]
> I got it working by adding it to serenity.conf like this:
> 
> `"goog:chromeOptions" { args = ["remote-allow-origins=*", ...] }`

@abergmeister  could you please tell me where i need to put the above??

  local {
    rest.logging = true
    headless.mode = false
    mssql.db.username = "ucase_AutoTest"
    mssql.db.password = "AutoTest1"
    webdriver.base.url = "http://localhost"
    mssql.db.connection = "jdbc:sqlserver://localhost:1433;databaseName=ucase;"
    webdriver {
      driver = chrome
    }
  }

**Comment by globalworming** [comment]
see https://serenity-bdd.github.io/docs/guide/driver_config#configuring-chrome
```
webdriver {
  capabilities {
    browserName = "Chrome"
    browserVersion = "103.0"
    platformName = "Windows 11"
    screenResolution = "1280x1024"

    "goog:chromeOptions" {
      args = [ "window-size=1000,800", "headless" ]
      binary = ${HOME}/path/to/chromedriver
      detach = true
      localState = {
        cart-contents = [1,2,3]
      }
    }
  }
}
```

**Comment by jerrin89** [comment]
@globalworming I have added that but not working for me 
  local {
    rest.logging = true
    headless.mode = false
    mssql.db.username = "ucase_AutoTest"
    mssql.db.password = "AutoTest1"
    webdriver.base.url = "http://localhost"
    mssql.db.connection = "jdbc:sqlserver://localhost:1433;databaseName=ucase;"
    webdriver {
      capabilities {
        ...
        "goog:chromeOptions" {
          args = [ "start-maximized", "headless"]
        }
      }
    }
  }

**Comment by globalworming** [comment]
remove the `...`

**Comment by jerrin89** [comment]
@globalworming removed the dots but still the same 
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: ConfigException$Parse: C:\Repos\BDD New\ucase-bdd\src\test\resources\serenity.conf: 125: unbalanced close brace '}' with no open brace (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
  at ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:71)
  at SystemPropertiesConfiguration.<init>(SystemPropertiesConfiguration.java:67)
      \_ for 1st parameter
  while locating SystemPropertiesConfiguration
  at ThucydidesModule.configure(ThucydidesModule.java:47)
  while locating Configuration

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
ConfigException$Parse:         "com.typesafe.config.ConfigException$Parse"
Configuration:                 "net.thucydides.core.webdriver.Configuration"
SystemPropertiesConfiguration: "net.thucydides.core.configuration.SystemPropertiesConfiguration"
ThucydidesModule:              "net.thucydides.core.guice.ThucydidesModule"
========================
End of classname legend:
========================

**Comment by globalworming** [comment]
`serenity.conf: 125: unbalanced close brace '}' with no open brace`

you messed up the format somewhere

**Comment by SaikatDEV** [comment]
it worked for me!. Thanks
