### ISSUE TITLE
[question]Does serenity report support multi language?

### ISSUE THREAD

**Issue by cww1769** [serenity-bdd/serenity-core#3085]
Can we configure the report to display other language?

**Comment by globalworming** [comment]
no
but you can probably use browser plugins or other means. why do you need that?

**Comment by cww1769** [comment]
Ok. Just want to show the report to someone who cannot speak engllish....

**Comment by globalworming** [comment]
then try for example https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb
