### ISSUE TITLE
HTML source code of screenshot webpages are downloaded

### ISSUE THREAD

**Issue by kenny-la** [serenity-bdd/serenity-core#3095]
In response to [https://github.com/SeleniumHQ/selenium/issues/11750](url) I updated serenity bdd from 3.2.0 to 3.6.7.

However, I noticed that now the VM that I use for running the tests is running out of memory quickly, as the reports now include the HTML source code of the webpages that are being tested.
These are saved as "pagesource[some-number].html" and take up to 4mb each.
This should be defaulted to false, and still happens when setting the option below in the serenity.properties.

serenity.store.html.source=false

**Comment by wakaleo** [comment]
HTML source code is not generated by default, except for test failures.

**Comment by wakaleo** [comment]
What makes you think the page source is related to memory consumption?

**Comment by kenny-la** [comment]
Thank you for the speedy answer!

After updating serenity, the page source files were generated for each and every test regardless of test outcome.
Setting serenity.store.html.source=false wouldn't help, although that should be defaulted to false anyway if I read that correctly.

With 509 test cases this amounted to about 6gb of pagesource[0-9]*.html files which is too much to bear.

**Comment by ikallala** [comment]
I had the same problem and it was fixed by serenity.store.html=NEVER and serenity.generate.csv.reports=false

**Comment by kenny-la** [comment]
Thanks, I tried it but unfortunately it's not working for me.

**Comment by wakaleo** [comment]
What is in your serenity.conf or serenity.properties file? HTML source is not generated by default in the most current versions of Serenity.

**Comment by wakaleo** [comment]
Have you tried with the latest version? Serenity hasn't generated these files by default for some time. 

Also, you talk about running out of memory - do you mean disk space? Because generating files of any kind should not affect the memory, so if you are running out of memory, it's probably a different issue.

**Comment by wakaleo** [comment]
Try:
```
serenity.store.html=NEVER
```

**Comment by kenny-la** [comment]
I just realised my mistake of changing 

serenity.store.html.source=false
to serenity.store.html.source=NEVER
rather than serenity.store.html=NEVER

although I have been given the correct answer yesterday already.
I need to have my glasses fixed.
