### ISSUE TITLE
1.1.26 Legacy property format detected for * displays for non-thucydides properties

### ISSUE THREAD

**Issue by marek5050** [serenity-bdd/serenity-core#310]
Our serenity.properties does not contain any thucydides.* properties yet when executing mvn verify we get dozens of warnings. 

`[pool-3-thread-3] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for saucelabs.access.key, please use the serenity.* format instead. `

![screen shot 2016-02-16 at 8 03 51 pm](https://cloud.githubusercontent.com/assets/6081895/13097642/73adea22-d4e8-11e5-8199-d3fe2cbcf1e8.png)

I've traced this down to legacyValue in legacyPropertyValueIfPresentIn() [ThucydidesSystemProperty.java](https://github.com/serenity-bdd/serenity-core/blob/2322ffbb35e1b22c7a9730c21302e360142a331d/serenity-core/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java#L782), which evaluates to "" and so enters the 
(legacyValue != null) condition.  Maybe this should be extended for legacyValue!=null && legacyValue!=""

![screen shot 2016-02-16 at 7 52 22 pm](https://cloud.githubusercontent.com/assets/6081895/13097655/90174da2-d4e8-11e5-8d96-c7738cd4ac49.png)

**Comment by YamStranger** [comment]
Hello @marek5050 

Yes it should. Will update this line )

Thanks

**Comment by YamStranger** [comment]
It seems that this issue already solved and this issue can be closed
