### ISSUE TITLE
"Exception when processing method annotations java.lang.NoSuchMethodException" for test annotated with @Disabled

### ISSUE THREAD

**Issue by DenysHrytsenko** [serenity-bdd/serenity-core#3103]
https://github.com/serenity-bdd/serenity-junit-starter is used with addition of 1 test to src/test/java/starter/wikipedia/WhenSearchingForTerms.java

    @Disabled
    @Test
    void test () {

    }
    
    
    
    Test is actually skipped and there are 2 tests in terminal(1 completed and 1 skipped):
    
    [WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 6.543 s - in starter.wikipedia.WhenSearchingForTerms

Only completed test is visible in HTML report, @Disabled test is not visible at all in HTML report - serenity-junit-starter/target/site/serenity/index.html

![image](https://user-images.githubusercontent.com/74365747/228350775-80f4c1bc-76b5-4170-9eb5-b75aa79e67a8.png)
![image](https://user-images.githubusercontent.com/74365747/228350864-65183b42-b97b-4d96-af27-b592961eeae6.png)

**Comment by wakaleo** [comment]
Fixed in 3.6.22
