### ISSUE TITLE
chrome.capabilities.acceptInsecureCerts=true not working in serenity 3.6.15 version

### ISSUE THREAD

**Issue by sudheer1437** [serenity-bdd/serenity-core#3106]
Hi,

Previously we used to use serenity 3.1.15 version and chrome.capabilities.acceptInsecureCerts=true in serenity.properties file and it used to work.

`Capabilities:: {acceptInsecureCerts=true, browserName=chrome`

But when we switched to serenity 3.6.15 version, setting in properties file or conf file is not working. meaning chrome capabilities is always defaulting to false.
`Capabilities:: {acceptInsecureCerts=false, browserName=chrome`

Can anyone help me with the solution?

**Comment by wakaleo** [comment]
Use serenity.conf instead (serenity.properties is deprecated).

**Comment by sudheer1437** [comment]
> Use serenity.conf instead (serenity.properties is deprecated).

Thank you John. I did try from serenity.conf too

chrome {
    capabilities {
        acceptSslCerts=true
        handlesAlerts=true
        acceptInsecureCerts=true
    }
}

but no luck..

`{acceptInsecureCerts=false, browserName=chrome, browserVersion=111.0.5563.147, chrome={chromedriverVersion=111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}), userDataDir=C:\Users\BALIVA~1\AppData\Local\Temp\scoped_dir24976_1833903989}, goog:chromeOptions={debuggerAddress=localhost:52725}, networkConnectionEnabled=false, pageLoadStrategy=normal, platformName=WINDOWS, proxy=Proxy(), se:cdp=ws://localhost:52725/devtools/browser/2e2962dd-bf36-4126-90b5-8c93f72e271d, se:cdpVersion=111.0.5563.147, setWindowRect=true, strictFileInteractability=false, timeouts={implicit=0, pageLoad=300000, script=30000}, unhandledPromptBehavior=dismiss and notify, webauthn:extension:credBlob=true, webauthn:extension:largeBlob=true, webauthn:extension:minPinLength=true, webauthn:extension:prf=true, webauthn:virtualAuthenticators=true}`

**Comment by sudheer1437** [comment]
> You will need to use the W3C properties in the webdriver.capabilities section (See https://serenity-bdd.github.io/docs/guide/driver_config), e.g.
> 
> ```
> headless.mode = true
> 
> webdriver {
>   driver = chrome
>   capabilities {
>     browserName = "chrome"
>     acceptInsecureCerts = true
>     "goog:chromeOptions" {
>       args = ["remote-allow-origins=*", "test-type", "ignore-certificate-errors", "--window-size=1000,800"
>         "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", "disable-popup-blocking"]
>     }
>   }
> }
> ```

Thank you John. This worked.
