### ISSUE TITLE
 How do I compare the datetimefield in Serenity Core?

### ISSUE THREAD

**Issue by SebnemSeymen** [serenity-bdd/serenity-core#3112]
I'm trying to write the following code in the repository:

 if ((Authorization.UserDefinition as UserDefinition).IsInRole(1002))
  {
      query.Where( 
          new Criteria(MyRow.Fields.CreatedOn) < new DateTime(MyRow.Fields.CreatedOn).AddDate(7))
          );
  }

authorized person can see only one week after the registration date. After a week, the record will not be listed. We can do this with addDay(7) in #c. But I don't know what is the correct syntax for serenity. I will be glad if you help.

**Comment by wakaleo** [comment]
Is this a question related to Serenity BDD?

**Comment by SebnemSeymen** [comment]
Yes, About Serenity Core

**Comment by wakaleo** [comment]
I'm afraid I don't understand the question. This doesn't look like Serenity BDD test code (it looks like C#, not Java) - are you sure you are referring to Serenity BDD, the Java test automation library?

**Comment by SebnemSeymen** [comment]
My fault, sorry, I should have been more clear. serenity core, c#

**Comment by wakaleo** [comment]
OK, thanks. This is the repository for the Serenity BDD project - Serenity BDD has no relationship with the .NET project called Serenity.
