### ISSUE TITLE
@manual-test-evidence doesnt display png

### ISSUE THREAD

**Issue by TomasoG** [serenity-bdd/serenity-core#3116]
Hi All,

Have the following issue that i need some help with.

I am tagging a scenario with @manual-test-evidence:assets/hi.png
<img width="165" alt="image" src="https://user-images.githubusercontent.com/43374789/232751446-7666e139-1fc4-4709-862b-bf2c376f65e9.png">

Issue is when checking the report and clicking on the evidence tag the screenshot is not displayed.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/43374789/232747287-fe58215e-bdd9-462f-9624-a6dee3792735.png">

After clicking:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/43374789/232747510-4d19726d-9688-4e4b-940c-eb4fcea6b1d8.png">

POM Versions:
        <serenity.version>3.6.12</serenity.version>
        <serenity.maven.version>3.6.12</serenity.maven.version>
        <serenity.cucumber.version>3.6.12</serenity.cucumber.version>
        <mavenfailsafeplugin.version>3.0.0-M5</mavenfailsafeplugin.version>
        <maven.surefire.plugin.version>3.0.0-M5</maven.surefire.plugin.version>
        <maven.compiler.plugin.version>3.10.1</maven.compiler.plugin.version>
        <logback.version>1.4.6</logback.version>

also tried with url link but still no joy :-(

Thanks.

**Comment by TomasoG** [comment]
Working now, it has to do with the @manual-last-tested tag.
If you have it set in properties for example current.target.version = sprint-1
Then set the tag above your scenario as @manual-last-tested:sprint-1

You should click on the evidence tag that is now displayed, not the tag the shows the .png
<img width="216" alt="image" src="https://user-images.githubusercontent.com/43374789/232759410-fd365126-014b-4aa3-bfd6-bf6cabb6aeec.png">


Thanks.

**Comment by wakaleo** [comment]
Thanks for the update Tomaso
