### ISSUE TITLE
Serenity-tests not included in report when using multiple JUnit5 @ExtendWith-annotations

### ISSUE THREAD

**Issue by hinnerkoetting** [serenity-bdd/serenity-core#3117]
When using multiple `@ExtendWith`-annotations for JUnit5 testclasses they will be converted to one `@Extensions`-annotation and this causes Serenity to not recognize them as serenity-tests (`SerenityTestExecutionListener#isSerenityTestClass` does not check for the latter, see
https://github.com/serenity-bdd/serenity-core/blob/8f7d14c6dad47bb58a1585fef5f9d9a44bb963fd/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityTestExecutionListener.java#L552-L557)

*Reproduce with*
What I did was something like this
```
@ExtendWith(SerenityJUnit5Extension.class)
@ExtendWith(ResetSomeCookies.class)
class MyTest {
...
}
```

**Workaround**
With this syntax my test is again recognized as expected.
```
@ExtendWith({SerenityJUnit5Extension.class, ResetSomeCookies.class})
```
**Possible solution**
`isSerenityTestClass` should probably use `getAnnotationsByType` [(JavaDoc)](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/AnnotatedElement.html#getAnnotationsByType-java.lang.Class-) instead of `getAnnotation`.

**Comment by wakaleo** [comment]
Well spotted.
Could you propose a PR?

**Comment by hinnerkoetting** [comment]
Probably yes, might take a day or two.
