### ISSUE TITLE
Serenity ignores several steps during execution

### ISSUE THREAD

**Issue by carlospinaSWO** [serenity-bdd/serenity-core#3121]
Hi, I'm encountering a strange behavior during the execution of some tests and after a thorough inspection I've decided to come here to ask if anyone has any idea of what could be happening.  Thanks in advance for reading this and I apologize for any mistakes with my English or any technical misunderstandings.

I've been working in a project for almost three months now and I have never encountered this issue before.  I'll share the feature with which I'm working and the runner in case I could be missing something in those files.

```
#language:en

Feature: TC_PBI_46070: Clasificado manual
    As an Operator
    I want to perform a manual sort

    @ManualSort
    Scenario Outline: (ORDERS) Clasificado manual
        Given the responsible has registered stock needed for
            | outcome      |
            | regularBatch |
        And the responsible creates a new roadmap for order
        When the responsible assigns a manual sort with
            | pickQuantity   | readPosition   | sortQuantity   |
            | <pickQuantity> | <readPosition> | <sortQuantity> |

        Examples:
            | pickQuantity | readPosition | sortQuantity |
            | true         | true            | true         |
            | true         | true            | false        |
            | true         | false           | true         |

```

And the runner.

```
package name_redacted.runners;

import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    glue = {"name_redacted.stepdefinitions.orders",
        "name_redacted.stepdefinitions.general"},
    features={"src/test/resources/features/orders/manual_sort.feature"},
    snippets= CucumberOptions.SnippetType.CAMELCASE
)
public class ManualSortRunner {
}
```

I've implemented several features with the same structure, even with the same two first steps, several runners identical to the one shown and all worked fine and dandy until now.  When I tried to execute these tests I encountered the following problems:

- The outcome of all tests in the report is _pending_, and the outcome of all steps but the first one is _ignored_.
- The first test always fails, regardless of the values of the parameters passed.  It will take around 2 seconds to execute and do nothing.  I'll attach a screenshot next.  Note that although the outcome of the first steps in which the call to the API is made is _success_, this call is not really made.
![clasificado_manual_2](https://user-images.githubusercontent.com/92158209/233322379-20c37483-743a-48b0-ab2b-d1740d2f6868.PNG)
- The remaining tests are always marked as _passed_ during the execution, but really only the calls to the API and the first step are executed, the remaining ones are ignored and the outcome in the report is indeed _ignored_.
![clasificado_manual_1](https://user-images.githubusercontent.com/92158209/233323067-006bbf13-9475-474b-b8a1-bdc47d4b2805.PNG)

I'm using Serenity BDD version 3.5.0 and Cucumber version 7.10.0.

I've spent several hours and asked some colleagues with experience with Serenity and we found nothing.  As I said, I have never encountered this behavior in the past and I've created several features with the same steps used in this one, so I have no idea of what could be happening now.  I'll provide more information if needed.

Thanks for reading through and I hope to hear from you soon.

**Comment by davidGFerruelo** [comment]
HI, it´s interesting, maybe @wakaleo  have more info about this.

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces this behaviour?

**Comment by carlospinaSWO** [comment]
Upon further inspection we've come across the following.  Apparently the first REST query performed is giving a status code of 0 (which is obviously not an actual HTTP code) with an execution time of 1 ms, so there is something weird happening there for some reason and the query is not really being executed.  As it can be seen in the screenshots of my original comment the remaining REST queries are performed with a reasonable execution time and providing a 204 status code, as it's expected.  Hope this can shine some light on the issue, as we have no clue about what could be the cause of this behavior.
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/92158209/234497010-66aa860c-a4ea-48b8-82d9-e67c7bb8469f.png)

**Comment by wakaleo** [comment]
Could you try with version 3.7.1? It might also be related to the tags.

**Comment by wakaleo** [comment]
Thanks for the feedback Carlo!
