### ISSUE TITLE
Can we associate or link a tag on the feature file to the respective environment mentioned on serenity.conf?

### ISSUE THREAD

**Issue by zgoveas** [serenity-bdd/serenity-core#3122]
I have a feature file:

@Stag Feature: This is just a demo

Scenario: Make sure the account is in online mode Given Adam needs to login to the demo page When he enables online mode Then he sees tests the demo logo

My serenity.conf file:

```
 environments {
 default 
 {
     webdriver.base.url = "https://default.demo.com"
 }
 local 
 {
     webdriver.base.url = "https://local.demo.com"
 }
 dev 
 {
     webdriver.base.url = "http://dev.demo.com"
 }
 staging 
 {
     webdriver.base.url = "https://staging.demo.com"
 }
 }
```
Is there a way to launch the browser with the appropriate URL? Maybe using the @Before tag Or is there another simpler way?

I also understand that we can use command line mvn verify -Denvironment=staging, however is there another way without the use of command line? Mainly when I try to run a single scenario using right-click on a Scenario -> Run 'Scenario: Make sure the account is in online mode'

Tried the below code

```
 Before(value = "@Stag")
 @Given("^I am setting the environment$")
 public void setTheEnvironment()
 {         
    EnvironmentVariables env = SystemEnvironmentVariables.currentEnvironmentVariables();
    String baseUrl = EnvironmentSpecificConfiguration.from(env).getProperty("environments.staging.webdriver.base.url");
    env.setProperty("webdriver.base.url", baseUrl)  
 }
```
The above was not meant to work as I later found out that environment variables are ready only.

There also are potential solutions like create a custom property file like project.properties and use it map using JAVA code. But I just want to avoid the coding and understand if there is a direct way to relate @Stag to environments.staging.webdriver.base.url

**Comment by globalworming** [comment]
with intelliJ you could try maven profiles https://www.jetbrains.com/help/idea/work-with-maven-profiles.html
it might work that you have different profiles that set different `environment` properties and then can toggle them easily for your `Run 'Scenario`

**Comment by Rangiferus** [comment]
Why don't you just add a line at the top of your serenity.conf and modify it depending on what environment you want to execute your tests on in IntelliJ:

```
environment = staging
```

**Comment by zgoveas** [comment]
Thank you for your quick response. We are going to use environment = staging when running our tests from command line
