### ISSUE TITLE
org.openqa.selenium.JavascriptException: javascript error: Cannot read properties of null (reading 'scrollHeight')

### ISSUE THREAD

**Issue by manaspatra** [serenity-bdd/serenity-core#3123]
getting :
org.openqa.selenium.JavascriptException: javascript error: Cannot read properties of null (reading 'scrollHeight') 
---configuration--
 (Session info: headless chrome=108.0.5359.94)
Build info: version: '4.8.2', revision: '826dbfc730'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [c5396473efe38641cd1dcc6b3c82a255, executeScript {script=return Math.max(document.body.scrollHeight, document.body.offsetHeight, document.documentElement.clientHeight, document.documentElement.scrollHeight, document.documentElement.offsetHeight);
, args=[]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.94, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /var/folders/k5/34hxwn_n291...}, goog:chromeOptions: {debuggerAddress: localhost:55140}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: MAC, proxy: Proxy(), se:cdp: ws://localhost:55140/devtoo..., se:cdpVersion: 108.0.5359.94, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}

any pointer for the resolution ?

**Comment by wakaleo** [comment]
That seems to be some code used in the bootstrap library, but that isn't called by Serenity. Do you have more of a stack trace?

**Comment by wakaleo** [comment]
That stacktrace looks like a TestNG test, not a Serenity BDD test?
