### ISSUE TITLE
Cannot find AndroidDrviver class in Selenium after updating project with Thucydides on project with Serenity

### ISSUE THREAD

**Issue by irinaKurganova** [serenity-bdd/serenity-core#314]
Hello!

I wanted to update my old project from Thucydides 0.9.273 version to Serenity 1.1.24 version  ( or 0.49 the first version). But I could not compile my project because I have error:

**java.lang.NoClassDefFoundError: org/openqa/selenium/android/AndroidDriver
	at net.thucydides.core.webdriver.SupportedWebDriver.<clinit>(SupportedWebDriver.java:49)
	at net.thucydides.core.webdriver.SystemPropertiesConfiguration.lookupSupportedDriverTypeFor(SystemPropertiesConfiguration.java:254)	......**

I checked in Maven that in Serenity you use **2.48.2** version selenium.jar.
But Selenium **AndroidDriver.jar** **2.39.0** the last one version.

Is it bug or not?
How can I update and compile my project?

Waiting on answer.
Regards, Irina.

**Comment by wakaleo** [comment]
Selenium-android was retired by the Selenium folk 3 years ago (https://seleniumhq.wordpress.com/2013/12/24/android-and-ios-support) in favour of Appium, and I suspect that the Selenium Android is not compatible with recent versions of Selenium, which means that Serenity also has moved on. I would suspect migrating to Appium, which is supported by Serenity.
