### ISSUE TITLE
SerenityJUnit5Extension does not fail tests annotated with @DisplayName or @DisplayNameGeneration

### ISSUE THREAD

**Issue by moshethebeadle** [serenity-bdd/serenity-core#3141]
If your test method has a `@DisplayName()` annotation, then Serenity will NOT mark the test as failed in case of an assertion error thrown by a @Step-annotated method in a @Steps class.

The reason is due to the discrepancy between these two spots:
- `SerenityJUnit5Extension#afterEach()` method, which [checks only the actual Java Method name](https://github.com/serenity-bdd/serenity-core/blob/main/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityJUnit5Extension.java#L67)
- SerenityTestExecutionListener#testStarted, which [uses the @DisplayName or @DisplayNameGeneration annotations, if available, to generate the test method name](https://github.com/serenity-bdd/serenity-core/blob/main/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityTestExecutionListener.java#L423)

### Sample fix

I have verified that I can fix this by using the following replacement for the `SerenityJUnit5Extension`:

```
@Log4j2
public class TestFailingSerenityJUnit5Extension extends SerenityJUnit5Extension {

  @Override
  public void afterEach(final ExtensionContext context) {
    if (!StepEventBus.getEventBus().isBaseStepListenerRegistered()) {
      log.warn("NO BASE STEP LISTENER FOUND IN THREAD " + Thread.currentThread());
    }
    final TestOutcome outcome = StepEventBus.getEventBus().getBaseStepListener().getCurrentTestOutcome();
    final String methodName = outcome.getQualifiedMethodName();
    context.getTestMethod().ifPresent(
        method -> {
          final String actualMethodName = JUnit5TestMethodAnnotations.forTest(method)
              .getDisplayName()
              .orElse(method.getName());

          // Make sure it's the right test - not sure when this gets called in parallel testing.
          if (actualMethodName.equals(methodName)) {
            // Failing test
            if (outcome.getTestFailureCause() != null) {
              throw outcome.getTestFailureCause().asRuntimeException();
            } else if (outcome.isPending()) {
              throw new PendingTestException(context.getDisplayName());
            } else if (outcome.isSkipped()) {
              throw new SkippedTestException(context.getDisplayName());
            }
          }
        }
    );
  }

}
```

(Note that this has only been tested with `@DisplayName`, not with `@DisplayNameGeneration` and also not with any qualifiers)

### Sample Setup
```
@ExtendWith(SerenityJUnit5Extension.class)
class TestIT {
   @Steps
   StepClass stepClass
   @Test
   @Displayname("blah")
   void test() { 
      stepClass.validateStuff()
  }
}
class StepClass {
   @Step
   validateStuff() {
     throw new AssertionError("...error...")
   }
}
```

**Comment by moshethebeadle** [comment]
I think the core issue is that the `StepListener#testStarted()` function accepts a `String` for the test name, which is flexible but doesn't provide any guarantees as to how it's generated.  It means that if you change how a test name is generated, you have to account for that in all other spots that use that.
It might be better to pass an object that is consistent, such as the java.lang.Method, so that comparisons in other places just work.

Another possibility is, [why are we checking the method name anyway](https://github.com/serenity-bdd/serenity-core/blob/main/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityJUnit5Extension.java#L66)?  The comment linked there suggests concern with parallel testing as the reason for checking the method name.
However, the `StepEventBus` is a `ThreadLocal`, which means it's unique per thread, and therefore each thread should have its own bus, and one thread won't interfere with any other.
So we might consider simply removing the `if`-check on the method name altogether, given that guarantee.

**Comment by moshethebeadle** [comment]
One more possibility:
Factor out the code that generates the test method into a utility (maybe `TestMethodNamingUtility`, or something like that).
Then, call that function from the extension class when trying to figure out the test method name.

**Comment by wakaleo** [comment]
Could you propose a PR?
