### ISSUE TITLE
SerenityRest lastResponse() method returns response from previous response

### ISSUE THREAD

**Issue by Tamas-Demeny** [serenity-bdd/serenity-core#3154]
So basically in some cases my `lastresponse()` method gets stuck with a previous response and won't update to a real 'last' response. 
For example if I execute this request
`SerenityRest.given()
                .accept("*/*")
                .header("X-Api-Key", "api key")
                .when()
                .get("https://randommer.io/api/Finance/Iban/".concat(countryUri)).getBody().as(String.class);`
I get back a random IBAN from the given country. When I make another request after this, and after the second request I call `restAssuredThat(
                lastResponse -> lastResponse.body(containsString(message)));`
The `lastResponse` will contain the first requests IBAN, instead of the second requests body. I have encountered this issue with post requests, when I use `multipart` to upload a file.

**Comment by wakaleo** [comment]
I would advise digging into the code and seeing what is happening. The lastResponse() method uses a ThreadLocal variable, so if you can troubleshoot and propose a PR if you find an issue.

**Comment by Tamas-Demeny** [comment]
So, I was using a `CommonAbstractClass` for my requests, in which I used a `RequestSpecification`, to save common headers and token
`RequestSpecification requestSpecification = SerenityRest.given()
            .contentType("application/json")
            .accept("*/*")
            .header("Connection", "keep-alive");`

When I used a `multiPart` request with it and after that a simple post request, the `lastResponse()` got stuck with the response from the `multiPart`
`SerenityRest.given()
                .header("Authorization", "Bearer " + Serenity.getCurrentSession().get("token"))
                .multiPart(controlName, file, "text/csv")
                .multiPart("json_data", body)
                .post(EnvironmentSpecificConfiguration.from(environmentVariables)
                        .getProperty("my.webservice.endpoint").concat(uri));`
then
`requestSpecification
                .body(body)
                .when().post(EnvironmentSpecificConfiguration.from(environmentVariables)
                        .getProperty("my.webservice.endpoint").concat(uri));`

In the Serenity report I saw the correct response for the second request, but in `lastResponse()` it contained the one from the first call. Haven't encountered this issue with my working stile before.
