### ISSUE TITLE
Junit5 is not recognising failed tests if the test display name is changed using @DisplayNameGeneration

### ISSUE THREAD

**Issue by djhTesting** [serenity-bdd/serenity-core#3162]
Hi, we have an issue where test results are correct in the serenity report, but when viewing junit tests in Azure all tests show as passed regardless of outcome.
It seems to work ok as long as the test display name is the same as the test method name, but as soon as you change the display name using @DisplayNameGeneration the problem occurs.

I think it is the same issue spotted here:
#2920 
...but that has been closed.

I've managed to fix the issue locally by changing SerenityJUnit5Extension.java (https://github.com/serenity-bdd/serenity-core/blob/main/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityJUnit5Extension.java) as below, does this look like the correct fix?
![image](https://github.com/serenity-bdd/serenity-core/assets/37965148/422dfcc9-b037-4a1f-a941-09bc94200953)

**Comment by djhTesting** [comment]
Just been informed this has already been fixed - will repon if necessary

**Comment by djhTesting** [comment]
OK reopening - the other fix mentioned is #3158 which is dealing with a slightly different issue, so maybe the fix above is still required?

**Comment by bachhavdipak** [comment]
|I have verified this issue and its resolved as a part of #3158 PR. I am waiting for author to go through code and accept my PR.

**Comment by wakaleo** [comment]
Can you try with 3.9.0?

**Comment by djhTesting** [comment]
@wakaleo - tried with 3.9.1 and working fine now, thanks.
