### ISSUE TITLE
How to get scenario name before driver instantiation?

### ISSUE THREAD

**Issue by dragos-panzaru-md** [serenity-bdd/serenity-core#3173]
I have a custom driver implementation:
` 

        String scenarioName = StepEventBus.getEventBus().getBaseStepListener().getCurrentTestOutcome().getName();

        String buildName = System.getProperty("buildName");

        try {

            MutableCapabilities caps = new MutableCapabilities();

            caps.setCapability("platformName", "Android");

            caps.setCapability("appium:platformVersion", "9");

            caps.setCapability("appium:newCommandTimeout", 90);

            caps.setCapability("appium:appiumVersion", "1.22.3");

            caps.setCapability("appium:deviceType", "phone");

            caps.setCapability("appium:deviceName", "^Samsung.*");

            caps.setCapability("appium:automationName", "UiAutomator2");

            caps.setCapability("appium:ignoreUnimportantViews", false);

            caps.setCapability("appium:app", "storage:APP_ID");

            MutableCapabilities sauceOptions = new MutableCapabilities();

            sauceOptions.setCapability("build", buildName);

            sauceOptions.setCapability("name", scenarioName);

            sauceOptions.setCapability("tunnelName", "tunnel");

            sauceOptions.setCapability("tunnelOwner", "SAUCE_USERNAME");

            sauceOptions.setCapability("phoneOnly", true);

            caps.setCapability("sauce:options", sauceOptions);

            return new AndroidDriver(new URL(<saucelabs_url>), caps);
      } catch (MalformedURLException e) {

            throw new Error(e);
        }`
The first line worked in serenity 3.2.5 and returned the title of the scenario that is under execution.
Now I am trying to upgrade serenity, cucumber and junit in order to be able to execute scenarios in parallel, not just features.
Currently, with serenity version 3.8.1 the line looks like this `String scenarioName = StepEventBus.getParallelEventBus().getBaseStepListener().getCurrentTestOutcome().getName();`
but the scenario name always returns "Test outcome unavailable"

**Comment by wakaleo** [comment]
In parallel execution, due to the nature of the event messages, this information is not available until the end of the scenario execution.

**Comment by dragos-panzaru-md** [comment]
I understand. But in this case can I get at least the feature name? Otherwise what should I put in the "name" capability so that it makes sense when I look in the Saucelabs Dashboard when checking the test executions?

**Comment by wakaleo** [comment]
The JUnit 5 and Cucumber event logs make this extremely difficult in general. I don't recall if we found a solution - have a look at the current serenity-saucelabs and serenity-browserstack modules to see.

**Comment by dragos-panzaru-md** [comment]
Thank you for the quick responses.

**Comment by dragos-panzaru-md** [comment]
@wakaleo Another thing I noticed is that the code that I have in a @BeforeAll hook is executed before driver instantiation if I use cucumber-junit 7.2.3, but if I upgrade to version 7.12.1 then the driver instantiation is done before the @BeforeAll hook. Is this normal?

**Comment by dragos-panzaru-md** [comment]
Scratch that. After upgrade it was using the @BeforeAll annotation from Junit instead of the one from Cucumber. Not sure why this happened but with the one from Cucumber, then the code in the @BeforeAll method is executed before driver instantiation.
