### ISSUE TITLE
SystemEnvironmentVariables object not retrieving properties on every instance

### ISSUE THREAD

**Issue by a-k-khurana** [serenity-bdd/serenity-core#3181]
When debugging first test I can see SystemEnvironmentVariables retrieving all properties successfuly, but when it runs second test, very few properties are present in SystemEnvironmentVariables object.

Below is my build.gradle

ext {
    slf4jVersion = '1.7.7'
    serenityCoreVersion = '3.8.1'
    serenityCucumberVersion = '3.8.1'
    serenityRestAssuredVersion = '3.8.1'
    junitVersion = '4.12'
    assertJVersion = '3.8.0'
    logbackVersion = '1.2.3'
}

dependencies {
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.11.1'
    testCompile group: 'org.apache.maven.plugins', name: 'maven-failsafe-plugin', version: '3.0.0-M5'
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation group: 'net.serenity-bdd', name: 'serenity-rest-assured', version: '3.8.1'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.10'
    compile 'org.postgresql:postgresql:42.2.5'
    compile group: 'org.postgresql', name: 'postgresql', version: '9.3-1100-jdbc4'
    compile 'com.adyen:adyen-java-api-library:9.0.0'
    implementation group: 'org.json', name: 'json', version: '20210307'
    testImplementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-cucumber:${serenityCucumberVersion}",
            "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}",
            "junit:junit:${junitVersion}",
            "org.assertj:assertj-core:${assertJVersion}"
    testImplementation 'com.auth0:java-jwt:4.0.0'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.10.0-M1'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.0-M1'
    testImplementation 'org.junit.vintage:junit-vintage-engine:5.10.0-M1'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.12.1'
    testImplementation 'org.junit.platform:junit-platform-suite:1.10.0-M1'
}

**Comment by a-k-khurana** [comment]
all good. I've had to write this code to grab hold of SystemEnvironmentVariables and store it for later use.

` EnvironmentVariables environmentVariables1 = new SystemEnvironmentVariables();
        if(fixed == null) {
            Map<String, String> map =  environmentVariables.getProperties().entrySet().stream().collect(Collectors.toMap(
                    e-> (String) e.getKey(),
                    e-> (String) e.getValue()
            ));
            fixed = new EnvVariables();
            fixed.setProperties(map);

        }
        Map<String, String> savedMap = fixed.getProperties().entrySet().stream().collect(Collectors.toMap(
                e -> (String) e.getKey(),
                e -> (String) e.getValue()
        ));
        environmentVariables1.setProperties(savedMap);
        return EnvironmentSpecificConfiguration.from(environmentVariables1)
                .getProperty(propName);`

**Comment by wakaleo** [comment]
Can you try with 3.9.0?

**Comment by wakaleo** [comment]
Fixed in version 3.9.8
