### ISSUE TITLE
Broken serenity index.html

### ISSUE THREAD

**Issue by bachhavdipak** [serenity-bdd/serenity-core#3185]
Getting 404 error after selecting scenario from the index.html with the latest serenity version 3.9.0 

![image](https://github.com/serenity-bdd/serenity-core/assets/77110618/e1499838-617b-4a71-ab81-3b84a13e9764)

![image](https://github.com/serenity-bdd/serenity-core/assets/77110618/37cddc27-bf80-43c7-b317-3dc48c09cbf9)

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces the issue?

**Comment by bachhavdipak** [comment]
@wakaleo : You can try with https://github.com/serenity-bdd/serenity-junit-starter

**Comment by wakaleo** [comment]
I can't reproduce that problem with the repo you mentioned - did you run mvn clean verify with the latest code?

**Comment by bachhavdipak** [comment]
I am using gradle project
