### ISSUE TITLE
Bug: Serenity report is empty when using plugins with junit @ConfigurationParameter

### ISSUE THREAD

**Issue by mrpet88** [serenity-bdd/serenity-core#3189]
Run sample project with `clean test -Dcucumber.filter.tags="@MyTest"` 
When there is at least one plugin imported with junit `@ConfigurationParameter` then the report is empty (check screenshot and `src/test/java/starter/CucumberTestSuite.java` runner)
If the same plugin is referenced through `junit-platform.properties` then report is showing correctly. 

https://github.com/mrpet88/basicProjects/tree/main

Other info:
```
serenityCoreVersion = '3.6.21'
id "net.serenity-bdd.serenity-gradle-plugin" version "3.6.7"
```

![image](https://github.com/serenity-bdd/serenity-core/assets/40420772/9db4aa0f-688e-45e9-b999-fecc6f20b22d)

**Comment by wakaleo** [comment]
@cliviu any idea about this one?

**Comment by cliviu** [comment]
This is strange. @mrpet88 , how are you exactly configuring the plugin junit-platform.properties?

**Comment by mrpet88** [comment]
Hello, not sure what do you mean by "how", but in general the whole junit-platform.properties and serenity-cucumber runner configuration can be found on the attached github repo. More or less the configuration I followed is coming from the instructions:
https://serenity-bdd.github.io/docs/guide/cucumber

**Comment by wakaleo** [comment]
Found it: you need to also include the Serenity plugin - for some reason if you declare plugins in the runner class, JUnit no longer reads them from the properties file, so you need to do this:
```
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "io.cucumber.core.plugin.SerenityReporterParallel,pretty,json:build/test-results/cucumber/frontend/global/results.json,timeline:build/test-results/timeline")
```

**Comment by mrpet88** [comment]
Indeed, never thought to add the SerenityReporterParallel in the runner class. Works now, thanks!

**Comment by wakaleo** [comment]
> <img alt="Screenshot 2023-08-10 at 9 16 49 AM" width="1781" src="https://user-images.githubusercontent.com/136751252/259753807-be62a35e-6a91-41f6-a61b-192de9d00f73.png">
> @wakaleo I Need commercial support, how can i proceed with that

Send me an email at john.smart[at]wakaleo.com and I will send you the details.
