### ISSUE TITLE
Set a list to Session variable and use

### ISSUE THREAD

**Issue by maidinhh** [serenity-bdd/serenity-core#3205]
Hi everyone, I am new in Serenity!
I have a list String called A and I set it to session like this:
List<String> listAtr = helper.findElements(locator);
            Serenity.setSessionVariable("data").to(listAtr);
Then how to get list A and compare with new list called B
(Please give me example)
Thank you so much!

**Comment by maidinhh** [comment]
@wakaleo please help me on this question if you know! thank you so much!

**Comment by Rangiferus** [comment]
@maidinhh This is not the question related to Serenity itself but rather to Java. I understand that you want to compare lists of objects. Why don't you simply search for "finding the differences between two lists in Java"?

tip: When you retrieve the list from your session variable you simply call `(List<XXX>) Serenity.sessionVariableCalled("data")`

**Comment by maidinhh** [comment]
> 

Thank for your support! Now I can handle this problem!
