### ISSUE TITLE
[Serenity - 3.9.8]error: package net.thucydides.core.guice does not exist 

### ISSUE THREAD

**Issue by bachhavdipak** [serenity-bdd/serenity-core#3206]
Getting below issue with the latest serenity core =3.9.7

```
error: package net.thucydides.core.guice does not exist
import net.thucydides.core.guice.Injectors;                                                                                 
                                ^                                                                                           
C:\TestAutomation\Properties.java:8: error: cannot find symbol               
    private static final EnvironmentVariables vars = Injectors.getInjector().getProvider(EnvironmentVariables.class).get();
```

**Comment by bachhavdipak** [comment]
Release note would be helpful so that we can take care of it

**Comment by bachhavdipak** [comment]
@wakaleo  : Any sample example available to deal with latest version?

**Comment by wakaleo** [comment]
The commit logs are fairly well documented. If you would like to help out with the release notes and docs you are more than welcome to help.

**Comment by wakaleo** [comment]
Alternatively if your company is getting value out of Serenity BDD, you can always opt for a commercial support contract, which can give more options for updates and feature/bug fix requests.

**Comment by bachhavdipak** [comment]
@wakaleo : Any sample example available to deal with latest version?

**Comment by GauravTyagi007** [comment]
I am also Facing the Same issue but was not able to find any walk around

**Comment by wakaleo** [comment]
net.thucydides.core.guice.Injectors was an internal Serenity class that is no longer used. See comments above.

**Comment by bachhavdipak** [comment]
@GauravTyagi007  : You can use below code 

`EnvironmentVariables environmentVariables = SystemEnvironmentVariables.createEnvironmentVariables();
environmentVariables.getProperty("property name")`

**Comment by GauravTyagi007** [comment]
Its Displaying the error cannot find symbol

**Comment by wakaleo** [comment]
See https://github.com/serenity-bdd/serenity-core/blob/main/docs/release-notes/4.0.0.md#guice-is-no-longer-used

**Comment by bachhavdipak** [comment]
@GauravTyagi007 :  
```

import net.thucydides.core.environment.SystemEnvironmentVariables;
import net.thucydides.core.util.EnvironmentVariables;

EnvironmentVariables environmentVariables = SystemEnvironmentVariables.createEnvironmentVariables(); 
environmentVariables.getProperty("property name")
```
