### ISSUE TITLE
Exception/assertion messages missing

### ISSUE THREAD

**Issue by sw-sowatec** [serenity-bdd/serenity-core#321]
Hi,
Our software team is using Serenity together with Cucumber to produce nice test reports. But recently we discovered that some failed assertions do not produce any meaningful messages even if we had written one. It simply states "_Assertion error_":
![2016-02-24 14_46_43-3 settlement calculation](https://cloud.githubusercontent.com/assets/17452693/13287116/98e7b53e-db05-11e5-9d71-9f10f48d682f.png)

## Used software versions

 - Serenity-bdd (cucumber) 1.1.3
 - Gradle 2.10
 - Cucumber 1.2.4

## Bug description and reproduction steps

For example a simple UnitTest containing only one line:
`org.junit.Assert.assertTrue("this message should be visible", false);`

Would lead to a report entry:
> Assertion error

With the following stack trace:

> org.junit.Assert.fail(Assert.java :88)
org.junit.Assert.assertTrue(Assert.java :41)
(...)

As you can see, the assertion-message cannot be found anywhere. Instead it _should_ output something like this:
> Assertion error: this message should be visible

## Error source

I think I have found the source of this bug by using the power of debugging.
The error/assert-message gets lost in the class **net.thucydides.core.model.stacktrace.FailureCause** inside the method [**buildThrowable** line 143-157](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/thucydides/core/model/stacktrace/FailureCause.java#L143). 
The assertion in the example (`java.lang.AssertionError`) has a default constructor. Therefore `defaultConstructorFor(failureClass).isPresent()` is returning `true` which creates a new (empty) exception of this type. This resulting exception/assertion has no message anymore.

To fix this bug it is necessary to use the default constructor only as last option or set the message in another way.

Thank you.

**Comment by YamStranger** [comment]
@sw-sowatec thanks for such detailed explanation!!

Will be fixed soon

**Comment by robertzett** [comment]
I've came across this issue as well. In my case Exception messages have been missing when run in Eclipse.
I've created an pull request fixing hopefully this and covering that with some unit tests.

**Comment by YamStranger** [comment]
Hello @robertzett 
This issue should be closed by your updates

If you feel that your issue is solved please close this ticket.

Thanks for your contribution !!!

**Comment by robertzett** [comment]
Looks good for me.
@sw-sowatec could you please verify that this is solved.

**Comment by sw-sowatec** [comment]
Also looks good for me.
Thanks for fixing this issue so fast and a special thanks to @robertzett for your contribution.
