### ISSUE TITLE
Selenium 4.11.x is not working with Serenity 3.9.8

### ISSUE THREAD

**Issue by dkumarra** [serenity-bdd/serenity-core#3212]
Selenium 4.11.x is not working with Serenity 3.9.8. Generated a new jar with the updated code(3.10.0-SNAPSHOT) which is working. Do we have timeline when the new version will be released.

**Comment by wakaleo** [comment]
It's an open source project, the next release will be ready when it's ready.

**Comment by dkumarra** [comment]
Sorry @wakaleo got a bit curious. I can see the latest version is now being released, will check with that. Thank you.

**Comment by wakaleo** [comment]
The next version will be 4.0.0, which includes support for JDK 11+, and so will have a lot of changes - not sure when it will be released though.

**Comment by dkumarra** [comment]
I can see the 3.10.0 and 4.0.0 present in the packages under the tags sections as Jars. But both of them are not present in the Maven central repository. Do we need to download it from someother place

![image](https://github.com/serenity-bdd/serenity-core/assets/37109896/fc8bb872-d510-4806-ae3b-77bb21a7fe0e)

![image](https://github.com/serenity-bdd/serenity-core/assets/37109896/e060ae20-c7d8-48d9-ba12-109652edc9e4)

**Comment by wakaleo** [comment]
They are not released yet - the tags are an error.

**Comment by dkumarra** [comment]
@wakaleo I dnt think this is the right place to ask this but I am not sure where to check about this. 

I can see the GitHub workflows are still in Java8, please let me know if you want me to raise a PR to change it to Java11.

**Comment by dkumarra** [comment]
Just seen you have updated it now.
