### ISSUE TITLE
Bug: logback-classic incompatible with slf4j

### ISSUE THREAD

**Issue by jan-molak** [serenity-bdd/serenity-core#3214]
Hey @wakaleo - it looks like Serenity BDD 3.9.8 and above ship with:
- [SLF4J 2.0.7](https://github.com/serenity-bdd/serenity-core/blob/fef8039a42c3670c112386d1f371d17b89abc9ee/pom.xml#L50)
- [logback-classic 1.2.3](https://github.com/serenity-bdd/serenity-core/blob/8ea5d002159c27928e4c3cf12c36d8bc339bd296/serenity-cli/pom.xml#L91)

This version of logback targets SLF4J 1.7.x or earlier and is incompatible with version 2.0.7, as per the [docs here](https://www.slf4j.org/codes.html#ignoredBindings). It also results in the following error when invoking Serenity BDD CLI:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/jan/Projects/serenity-js/serenity-js/packages/serenity-bdd/cache/serenity-cli-3.9.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

The latest version of logback is [1.4.9](https://mvnrepository.com/artifact/ch.qos.logback/logback-classic); any reason why we shouldn't upgrade to that?

**Comment by wakaleo** [comment]
Fixed in 4.0.0
