### ISSUE TITLE
Serenity.conf is not loading the browser extension 

### ISSUE THREAD

**Issue by asutoshbiswal1995** [serenity-bdd/serenity-core#3218]
My Serenity.conf file is as below:
webdriver {
  driver = chrome
  autodownload = true
  capabilities {
      "goog:chromeOptions" {
          browserName = "chrome"
          acceptInsecureCerts = true
          extensions = [src/test/resources/extensions/EXTENSION-FILENAME.crx]
    }
}
}

[https://serenity-bdd.github.io/docs/guide/driver_config#configuring-chrome-extensions]

**Comment by asutoshbiswal1995** [comment]
Fixed it

**Comment by astor4ever** [comment]
@asutoshbiswal1995 did you find working solution? i have same issue
