### ISSUE TITLE
Reporserenity failed 

### ISSUE THREAD

**Issue by jecardenasri01** [serenity-bdd/serenity-core#3219]
my serenity bdd report is showing the actions as scenarios

![image](https://github.com/serenity-bdd/serenity-core/assets/45072804/47b732df-0ead-4ea1-b72c-2740168e5ccb)
![image](https://github.com/serenity-bdd/serenity-core/assets/45072804/7d0bac9e-0df5-4aaa-9e8f-e75cf025ced6)
![image](https://github.com/serenity-bdd/serenity-core/assets/45072804/54b6952e-01b9-40b5-87e6-be42e3c49e2f)
buildscript {
    ext.serenityCoreVersion = '3.3.0'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:3.4.2")
        classpath "net.serenity-bdd:serenity-single-page-report:$serenityCoreVersion"
    }
}

plugins {
    id "net.serenity-bdd.serenity-gradle-plugin" version "${serenityCoreVersion}"
    id 'java'
    id 'eclipse'
    id 'idea'
}

defaultTasks 'clean','test','aggregate'

group 'co.com.base.gradle'
version '1.0-SNAPSHOT'

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.8.2'
    logbackVersion = '1.2.10'
    lombokVersion = '1.18.22'
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"

    implementation ("net.serenity-bdd:serenity-core:${serenityCoreVersion}")
    implementation "net.serenity-bdd:serenity-junit5:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-cucumber:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-rest-assured:${serenityCoreVersion}"

    implementation "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}"
//    implementation "net.serenity-bdd:serenity-ensure:2.3.5"
    implementation "net.serenity-bdd:serenity-screenplay:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-screenplay-rest:${serenityCoreVersion}"

    implementation "ch.qos.logback:logback-classic:${logbackVersion}"

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

serenity {
    testRoot = "co.com.base.gradle.runners"
    requirementsBaseDir = "src/test/resources/features"
    reports = ["single-page-html"]
}

gradle.startParameter.continueOnFailure = true
test.finalizedBy(aggregate)

**Comment by wakaleo** [comment]
Can you try with version 3.9.8?

**Comment by jecardenasri01** [comment]
* change scenario outlines to Scenario Template

* update serenity screenplay with version 3.9.8

and it worked correctly
___________________________
buil.gradle 
defaultTasks 'clean', 'test', 'aggregate'

repositories {
    mavenCentral()
    mavenLocal()
}

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:3.9.8"
    }
}


apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: "net.serenity-bdd.serenity-gradle-plugin"

sourceCompatibility = 16
targetCompatibility = 16

ext {
    serenity_version = '3.9.7'
    junit_platform_launcher_version="1.9.3"
    cucumber_junit_platform_engine_version="7.2.3"
    junit_platform_suite_version="1.9.3"
    junit_jupiter_engine_version="5.9.3"
    junit_vintage_engine_version="5.9.3"
    logback_classic_version="1.2.10"
    assertj_core_version="3.23.1"
}

dependencies {
    dependencies {
        testImplementation "net.serenity-bdd:serenity-core:${serenity_version}"
        testImplementation "net.serenity-bdd:serenity-cucumber:${serenity_version}"
        testImplementation "net.serenity-bdd:serenity-screenplay:${serenity_version}"
        testImplementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenity_version}"
        testImplementation "net.serenity-bdd:serenity-ensure:${serenity_version}"
        testImplementation "org.junit.platform:junit-platform-launcher:${junit_platform_launcher_version}"
        testImplementation "io.cucumber:cucumber-junit-platform-engine:${cucumber_junit_platform_engine_version}"
        testImplementation "org.junit.platform:junit-platform-suite:${junit_platform_suite_version}"
        testImplementation "org.junit.jupiter:junit-jupiter-engine:${junit_jupiter_engine_version}"
        testImplementation "org.junit.vintage:junit-vintage-engine:${junit_vintage_engine_version}"
        implementation "ch.qos.logback:logback-classic:${logback_classic_version}"
        testImplementation "org.assertj:assertj-core:${assertj_core_version}"
    }
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

gradle.startParameter.continueOnFailure = true

test.finalizedBy(aggregate)

____________________

gradle-wrapper.properties : 

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.2.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

**Comment by jecardenasri01** [comment]
evidence of changes
![image](https://github.com/serenity-bdd/serenity-core/assets/45072804/578cdc88-b340-4ae9-a3ad-cae4095d1610)

**Comment by wakaleo** [comment]
Fixed in 4.0.x
