### ISSUE TITLE
Why chrome.exe doesn't close completely?

### ISSUE THREAD

**Issue by akhabarovIT** [serenity-bdd/serenity-core#3230]
Hello!
I use the code after performing the autotest:
![image](https://github.com/serenity-bdd/serenity-core/assets/69796174/ae234f91-4494-408e-a67c-f4aa937efac4)
and watching the processes in the task manager.

During the execution of the autotest, 7 processes are started chrome.exe, after the end of the run there are 2 of them. Why chrome.exe is it not completely killed?
![image](https://github.com/serenity-bdd/serenity-core/assets/69796174/f5dd28e8-ce20-4a64-84e8-d33955f3759e)

Serenity BDD version 3.9.8 .

**Comment by wakaleo** [comment]
Do not do this. Serenity will close the browsers and drivers automatically. If you do it yourself, you can disrupt the Serenity processes.

**Comment by akhabarovIT** [comment]
> Не делай это. Serenity автоматически закроет браузеры и драйверы. Если вы сделаете это сами, вы можете нарушить процессы Serenity.

Oh, thanks!
And I found how to solve the problem. I started using serenity.conf instead of serenity.properties. All processes chrome.exe closed correctly. I don't understand how this is related and why it helped.

**Comment by wakaleo** [comment]
serenity.properties is deprecated - for W3C capabilities you need to use serenity.conf
