### ISSUE TITLE
4.0.0-beta JavascriptExecutor script is not executed

### ISSUE THREAD

**Issue by vayaszsolt** [serenity-bdd/serenity-core#3231]
Hi,

I switched to use 4.0.0-beta2 since the 3.2.8 version's WebDriver was too old for the current Chrome version. As I understood the current version use the DriverManager provided from Selenium.

After I switched and I resolved the breaking changes I cannot use the JavascriptExecutor with the new driver.

`JavascriptExecutor js = (JavascriptExecutor) driver;`
`String sentence = "window.sessionStorage.setItem(\"" + name + "\"" + ", \"" + value + "\")";`
`js.executeScript(sentence);`

The reason behind this is the "proxiedWebDriver" is null inside the WebDriverFacade class.

What additional configuration do I need to do in order the "proxiedWebDriver" to be initialized?

**Comment by wakaleo** [comment]
Could be a bug. Can you dig into the code and propose a PR?

**Comment by vayaszsolt** [comment]
I will try. Before doing this I am want to be sure I am Injection the WebDriver in the correct way. The above code I use in a StepDefinition class and the WebDriver is injected:

```
    @Managed
    private WebDriver webDriver;
```

Do I inject the driver in the correct way inside the CucumberStepDefinition class?

**Comment by vayaszsolt** [comment]
I above code created a new driver that wasn't created before by Serenity. I remove that WebDriver injection inside the Definition class. I moved to use an internal Serenity class:

`ThucydidesWebDriverSupport.getWebdriverManager().getCurrentDriver()`

This fixed my issue.
