### ISSUE TITLE
Browser is not restarting after a scenario execution

### ISSUE THREAD

**Issue by alberf50** [serenity-bdd/serenity-core#3257]
### What happened?

Hi all,

I have a project run by these Serenity versions of Cucumber & Maven:
`<serenity.version>3.9.0</serenity.version>
        <serenity.maven.version>3.9.0</serenity.maven.version>
        <serenity.cucumber.version>3.9.0</serenity.cucumber.version>`

Also, I have these Serenity settings:

`serenity {
  take.screenshots = FOR_FAILURES
  test.root = src/test/resources/features
  tag.failures = "true"
  linked.tags = "issue"
  use.unique.browser = false
  restart.browser.each.scenario = true
  webdriver.autodownload = false
  headless.mode = false
  browser.maximized = true
  report {
    accessibility = true
  }
}`
However, after the scenarios are executed, **the browser is not being restarted**. Is there any fix available? I think I didn't mess up anything, please If that's the case, tell me :)

Best regards

### What did you expect to happen?

By these Serenity configurations the browser should be closed after every scenario execution, which is not happening at the moment.

### Serenity BDD version

3.9.0

### JDK version

17.0.7_7

### Execution environment

Windows 10 Enterprise

### How to reproduce the bug.

By having an Intellij project run by Serenity and trying to execute all the features by adding these code lines:

`serenity {
  take.screenshots = FOR_FAILURES
  test.root = src/test/resources/features
  tag.failures = "true"
  linked.tags = "issue"
  **use.unique.browser = false**
  **restart.browser.each.scenario = true**
  webdriver.autodownload = false
  headless.mode = false
  browser.maximized = true
  report {
    accessibility = true
  }
}`

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by sandeepraina-lenze** [comment]
Try the following

```
serenity {
  project.name = "Serenity BDD TodoMVC"
  test.root = "net.serenitybdd.demos.todos"
  tag.failures = "true"
  linked.tags = "issue"
  restart.browser.for.each = scenario
  logging = verbose
  compress.filenames=false
  outputDirectory = "reports"
}
```
