### ISSUE TITLE
Tests not sorted by 'Started' column

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#3261]
### What happened?

In serenity full HTML report rows with automated tests not sorted by 'Started' column

https://github.com/serenity-bdd/serenity-core/assets/6312221/da217ae9-b773-41d9-a8ee-b48f124f5e77

### What did you expect to happen?

I expect that tests can be sorted by 'Started' column, so I can figure out which test was first/last, what was test order execution, etc.

### Serenity BDD version

4.0.5

### JDK version

Java 18

### Execution environment

reproduced on Linux and Windows

### How to reproduce the bug.

Run 2+ more tests, preferable each should take 2+ seconds. Then generate report, open it and try to sort automated tests table by 'Started' column.

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by scormaq** [comment]
hi @wakaleo , I checked it on serenity 4.0.12 and sorting still not working.

Also I noticed that on `Functional Coverage Details` table sorting by `Result` not working too.

**Comment by wakaleo** [comment]
@scormaq it seemed to be fixed but apparently not. Can you take a look and propose a PR? It's something to do with the DataTables JQuery component.

**Comment by scormaq** [comment]
@wakaleo my bad, forgot to update plugins. Fixed indeed.
I'm afraid I'm not that familiar with jquery to do fixes for it, sorry.

**Comment by DiepAnh** [comment]
> @wakaleo my bad, forgot to update plugins. Fixed indeed. I'm afraid I'm not that familiar with jquery to do fixes for it, sorry.
I see the same error :((, plz tell me how to update plugins. thanks
