### ISSUE TITLE
results.csv is no longer generated?

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#3264]
### What happened?

I use file `results.csv`, generated after `aggregate` task, for some post-regression analysis. After updating Serenity to latest version 4.0.12 there no longer file `target/site/serenity/results.csv` generated.

### What did you expect to happen?

I expect to have file `results.csv` with test report in CSV format after generating full HTML report. File contains test results per test case

### Serenity BDD version

4.0.12

### JDK version

Java 18

### Execution environment

Windows 10

### How to reproduce the bug.

Having gradle-java project run tests and then execute task `aggregate` to generate full report, then check `target/site/serenity` for file presence.

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
Set the `serenity.generate.csv.reports` property to true.

**Comment by scormaq** [comment]
I rechecked with `serenity.generate.csv.reports = true` in `serenity.properties`, but file is still not generated. Also, comment for this property says that it should be set to `true` by default.

**Comment by wakaleo** [comment]
<img width="1028" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/55986/c0e7b7da-ead9-4e73-90bf-971c7eef4e43">

**Comment by scormaq** [comment]
Interesting, it may be a windows-specific issue. I still can't get it generated on my Windows laptop, but I see it is generated on Linux runner on CI.

**Comment by wakaleo** [comment]
Maybe dig into the code and take a look. All that has changed is the default value for that flag.

**Comment by scormaq** [comment]
Maybe it was some nasty combo of different factor, but I no longer can reproduce it on windows (mentioned property is set explicitly now ), therefore closing this issue

**Comment by wagner-deoliveira** [comment]
Hi. I'm facing the same issue and add the following lines to my serenity.conf file:
```
webdriver {
  driver = "chrome"
  capabilities {
    browserVersion = "117.0"
  	"selenoid:options":{"enableVNC":true}
  	"goog:chromeOptions" {args = ["start-maximized", "window-size=1920,1080", "disable-dev-shm-usage", "remote-allow-origins=*"]}
  }
}

serenity {
	generate.csv.reports = true	
}

```

It doesn't seem to work though. Am I missing something?

**Comment by wagner-deoliveira** [comment]
> Hi. I'm facing the same issue and added the following lines to my serenity.conf file:
> 
> ```
> webdriver {
>   driver = "chrome"
>   capabilities {
>     browserVersion = "117.0"
>   	"selenoid:options":{"enableVNC":true}
>   	"goog:chromeOptions" {args = ["start-maximized", "window-size=1920,1080", "disable-dev-shm-usage", "remote-allow-origins=*"]}
>   }
> }
> 
> serenity {
> 	generate.csv.reports = true	
> }
> ```
> 
> It doesn't seem to work though. Am I missing something?

I've managed to make it work adding it to serenity.properties instead of serenity.conf 👍
