### ISSUE TITLE
Getting NoClassFound error  for net.thucydides.model.util.EnvironmentVariables while updating Serenity 3 to 4 and Java 8 to 11 version

### ISSUE THREAD

**Issue by PritiKumari95** [serenity-bdd/serenity-core#3268]
### What happened?

Getting NoClassFound error  for net.thucydides.model.util.EnvironmentVariables while updating Serenity 3 to 4 and Java 8 to 11 version

### Serenity BDD version

4.0.1

### JDK version

11

### Execution environment

Windows

### How to reproduce the bug.

Create a plugin with all the required dependencies of serenity with version 4.0.1 and Java 11 and consume it in in another project having java 11. 

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
See https://github.com/serenity-bdd/serenity-core/blob/main/docs/release-notes/4.0.1.md

**Comment by PritiKumari95** [comment]
I followed the above document still i keep getting NoClassFound error for net.thucydides.model.util.EnvironmentVariables and org.apache.logging.log4j.Logger error

**Comment by wakaleo** [comment]
NoClassFound means it can't find the class it is expecting, which means your dependencies might be incorrect.

**Comment by PritiKumari95** [comment]
I am using Serenity BDD 4.0.1 for all serenity bdd related dependencies and log4j-slf4j2-impl version 2.20.0. do you suggest any other dependency version than this which would be compatible with java 11.

**Comment by wakaleo** [comment]
Take a look at https://github.com/serenity-bdd/serenity-cucumber-starter and https://github.com/serenity-bdd/serenity-junit-starter.

**Comment by PritiKumari95** [comment]
I tried the above versions, still the issue persist. I have used the dependencies which supports java 11.

**Comment by wakaleo** [comment]
Do a dependency analysis of your project and look for older versions of Serenity or dependency conflicts. If you need more project-specific help you can also ask your project to get a commercial support package (https://www.serenity-dojo.com/home1691753380236)

**Comment by manishbupadhyay** [comment]
Hey @PritiKumari95 have you find any solution to fix this issue? I'm getting the same issue.

**Comment by wakaleo** [comment]
@manishbupadhyay Read the release notes in https://github.com/serenity-bdd/serenity-core/blob/main/docs/release-notes/4.0.1.md

**Comment by PritiKumari95** [comment]
I was able to resolve the above issue, But now i am facing issue with the reports, I am using TstOutcomeLoader in my project but its failing to load the reports since i have updated the serenity version to 4.0.1, one thing i observed that my report folder  doesn't contain all the files which used to get generated with older version of serenity, I a not sure if this can be reason for TstOutcomeLoader failure

**Comment by wakaleo** [comment]
@PritiKumari95 What do you mean by failing?

**Comment by PritiKumari95** [comment]
TestOutcomeLoader method gives error as 'could not load the reports due to some reason', there is no clear reason specified why its failing to load the reports, one of the behavior i could see is that the reports getting generated doesn't have all the folders few files are missing which i could see with serenity 3 like serenity-reports

**Comment by wakaleo** [comment]
I would need to see your project, but it could be you still have old dependencies or plugins that are using or expecting incompatible formats.

**Comment by manishbupadhyay** [comment]
Hey @PritiKumari95 how you've resolved this issue? Can you please let me know the same?

**Comment by PritiKumari95** [comment]
@manishbupadhyay It was issue with the java configuration in my system, even though i updated JDK 11 in environment variable my system was still not referring to java 11. I had to connect my IT support team they resolved this system issue. Please check your java version.
