### ISSUE TITLE
Exception is thrown when setting custom outputDirectory

### ISSUE THREAD

**Issue by lordofthejars** [serenity-bdd/serenity-core#329]
I have configured a custom outputDirectory in `serenity.properties` file using the property `serenity.outputDirectory` to set the output directory to `build/reports/serenity`. But when I run the `test`goal (in Gradle) I get next exception:

```
java.io.FileNotFoundException: build/reports/serenity/requirements/org.starwars.features.json (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at net.thucydides.core.requirements.RequirementPersister.write(RequirementPersister.java:72)
        at net.thucydides.core.requirements.PackageAnnotationBasedTagProvider.persistRequirementsAsJSON(PackageAnnotationBasedTagProvider.java:256)
```

Using SerenityBDD 1.1.26 with Java 8. Maybe I should specify more than one property?

**Comment by YamStranger** [comment]
Hello @lordofthejars 

No, it should work without any additional properties. 

Do you use latest version of serenity-bdd modules and serenity-gradle plugin ?

**Comment by lordofthejars** [comment]
You can see the project here: https://github.com/lordofthejars/starwars/tree/master/acceptance-test

**Comment by YamStranger** [comment]
@lordofthejars I cloned your repo 
updated properties to use some directory, executed `gradle clean test aggregate`: 
![image](https://cloud.githubusercontent.com/assets/1667699/13457860/e7165748-e072-11e5-9b04-2799808aac9a.png)

and 

![image](https://cloud.githubusercontent.com/assets/1667699/13458014/cf4b061c-e073-11e5-96b4-62d70cf5a411.png)


All finished without any error (report generation, not tests :) ). 

![image](https://cloud.githubusercontent.com/assets/1667699/13458040/ea44354c-e073-11e5-8442-002e86536692.png)


It seems that something wrong with that directory, for example it can be removed during test execution... Please try to run build with other directory in your property.

**Comment by lordofthejars** [comment]
Ok I will try it and keep you updated. But then it should be some kind of feature for allowing Serenity to generate reports in standard Gradle directory and not in `target`

**Comment by YamStranger** [comment]
@lordofthejars It seems that it possible ) 
As I posted before, generated reports are in standard gradle directory (after updating serenity properties)

![image](https://cloud.githubusercontent.com/assets/1667699/13458610/e7b27f8e-e076-11e5-8fa3-e71a4e3679cb.png)

Serenity BDD can work with gradle, mvn, ant - and they have different standard build directories witch can not be retrieved during test execution, that is why working directory of module/project is used for generating reports, based on outputDirectory configuration.

**Comment by lordofthejars** [comment]
YesI need to check out what's happening since I am not doing anything strange

**Comment by lordofthejars** [comment]
Don't know why but still the same problem and the strange is that it fails when I run `test` and not aggregating.

**Comment by YamStranger** [comment]
@lordofthejars unfortunately I can not reproduce it.. 

What operation system do you use? What version of gradle?  

I hope it just version conflicts of serenity-modules: please try to use provided below build.gradle with latest versions of libs (journey was renamed to screenplay ):

```
ext{
    serenity_version = "1.1.27"
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.1.27")
    }
}

repositories {
    mavenLocal()
    jcenter()
}


apply plugin: 'java'

apply plugin: "net.serenity-bdd.aggregator"


println "project.serenity.outputDirectory= ${project.serenity.outputDirectory}"

dependencies {
    compile "net.serenity-bdd:serenity-core:$serenity_version"
    compile "net.serenity-bdd:serenity-junit:$serenity_version"
    compile("net.serenity-bdd:serenity-screenplay:$serenity_version")
    compile("net.serenity-bdd:serenity-rest-assured:$serenity_version")
    compile 'org.codehaus.groovy:groovy-all:2.3.10'
    compile 'junit:junit:4.12'
}

test {
    testLogging {
        showStandardStreams = true
    }
    /* Pass all system properties: */
    systemProperties System.getProperties()
}

gradle.startParameter.continueOnFailure = true
```

**Comment by lordofthejars** [comment]
with Gradle 2.10 and 1.1.28 happens too :(

**Comment by YamStranger** [comment]
@lordofthejars did you tried config from my previous comment?

**Comment by lordofthejars** [comment]
@YamStranger Yes I have tried (well to avoid problems I have updated to .28) and still the same, I have changed from journey to screenplay as you mention. You can see the build here: https://github.com/lordofthejars/starwars/blob/master/acceptance-test/build.gradle

I have tried to remove all the build/target files and recreate it again, but no luck.
