### ISSUE TITLE
Scenario report HTML not generated with aggregate with 4.0.15

### ISSUE THREAD

**Issue by rajorshi-ghosh** [serenity-bdd/serenity-core#3291]
### What happened?

I have setup a sample serenity project with RestAssured for calling APIs. Tests ran successfully. There were expected failures. But after running aggregate, inside the index.html report (attached), the scenario (which has the steps) html is not found. Attaching the zipped sample project.
[ApiSerenityTest.zip](https://github.com/serenity-bdd/serenity-core/files/12991232/ApiSerenityTest.zip)

### What did you expect to happen?

The scenario html file should have been generated

### Serenity BDD version

4.0.15

### JDK version

20.0.2

### Execution environment

Running on IntelliJ in MacOS X

### How to reproduce the bug.

Run the test cases in UserDetailsTestCases.java and then run aggegate.
Open serenity report index.html
Go to Test Results.
Click on any of the executed scenarios.
No html file found with the link in index.html

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
Your Gradle plugin version is incorrect, and there are some dependency conflicts in your build script. See https://github.com/serenity-bdd/serenity-junit-starter/blob/master/build.gradle
