### ISSUE TITLE
After upgrading to serenity 4.0.1 the serenity-summary.html report is not getting generated

### ISSUE THREAD

**Issue by manishbupadhyay** [serenity-bdd/serenity-core#3295]
### What happened?

I've upgraded my serenity project from 3.8.1 to 4.0.1 then the index.html report is generated but the serenity-summary.html report is not getting generated.
In console I'm getting below error.

net.thucydides.core.reports.ExtendedReport: net.serenitybdd.reports.email.EmailReporter Unable to get public no-arg constructor: net/thucydides/core/util/EnvironmentVariables: net.thucydides.core.util.EnvironmentVariables -> [1m[Help 1][m
[ERROR] java.util.ServiceConfigurationError: net.thucydides.core.reports.ExtendedReport: net.serenitybdd.reports.email.EmailReporter Unable to get public no-arg constructor: net/thucydides/core/util/EnvironmentVariables: net.thucydides.core.util.EnvironmentVariables

### What did you expect to happen?

serenity-summary.html  report should be generated

### Serenity BDD version

4.0.1

### JDK version

17

### How to reproduce the bug.

Upgrade your project to serenity 4.0.1
run the project
serenity-summary.html report is not getting generated

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
Read the 4.0.1 release notes.

**Comment by manishbupadhyay** [comment]
@wakaleo I've go through the release notes 4.0.1 https://github.com/serenity-bdd/serenity-core/blob/main/docs/release-notes/4.0.1.md and do the same steps but still I'm not able to get the serenity-summary.html report

**Comment by manishbupadhyay** [comment]
@wakaleo I've read the updated release document of 4.0.1 https://github.com/serenity-bdd/serenity-core/blob/main/docs/release-notes/4.0.1.md and update my project but still I'm not able to generate the serenity-summary.html report and in console the same error message. 

net.thucydides.core.reports.ExtendedReport: net.serenitybdd.reports.email.EmailReporter Unable to get public no-arg constructor: net/thucydides/core/util/EnvironmentVariables: net.thucydides.core.util.EnvironmentVariables -> [1m[Help 1][m
[ERROR] java.util.ServiceConfigurationError: net.thucydides.core.reports.ExtendedReport: net.serenitybdd.reports.email.EmailReporter Unable to get public no-arg constructor: net/thucydides/core/util/EnvironmentVariables: net.thucydides.core.util.EnvironmentVariables

**Comment by manishbupadhyay** [comment]
@wakaleo I'm able to fix this issue, now serenity-summary.html report is getting generated.

We're good to close this issue.

**Comment by ArvindDangi007** [comment]
Hi @wakaleo ,

After execution report is not generating, can you  plz help
![image](https://github.com/serenity-bdd/serenity-core/assets/142920618/ac7e4d5e-0d49-4f70-8b4f-21523d662e38)
Report: 
![image](https://github.com/serenity-bdd/serenity-core/assets/142920618/4fb4bfd3-92cf-4f2c-a5b1-0574e048bf50)

**Comment by fericeand** [comment]
here is my build.gradle file
`plugins {
    id "io.freefair.lombok" version "8.6"
    id "net.serenity-bdd.serenity-gradle-plugin" version "4.1.10"
    id "java"
    id "idea"
    id 'checkstyle'
    id 'com.adarshr.test-logger' version '4.0.0'
    id "org.gradle.test-retry" version "1.5.9"
}

group = 'com.fanduel.fgp'
version '0.0.1-SNAPSHOT'

defaultTasks 'clean', 'test', 'aggregate'

repositories {
    mavenCentral()
}

ext {
    slf4jVersion = '2.0.13'
    serenityCoreVersion = '4.1.10'
    serenityCucumberVersion = '4.1.10'
    junitVersion = '5.11.0-M1'
    junitLauncher = '1.11.0-M1'
    assertJVersion = '3.25.3'
    logbackVersion = '1.5.6'
    jacksonVersion = '2.17.0'
    jacksonDataFormatVersion = '2.17.0'
    serenityVersion = '5:4.1.10'
    aws_version = '2.20.103'
}

dependencies {
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:${jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}"
    implementation group: 'org.jboss.aerogear', name: 'aerogear-otp-java', version: '1.0.0'
    implementation "mysql:mysql-connector-java:8.0.32"

    testImplementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay-rest:${serenityCoreVersion}"
    testImplementation "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}"
    testImplementation "org.junit.platform:junit-platform-launcher:${junitLauncher}"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
    testImplementation "org.junit.vintage:junit-vintage-engine:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertJVersion}"
    testImplementation "net.serenity-bdd:serenity-junit${serenityVersion}"
    testImplementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:${jacksonDataFormatVersion}"

    testImplementation platform("software.amazon.awssdk:bom:${aws_version}")
    testImplementation 'software.amazon.awssdk:s3'
    testImplementation 'software.amazon.awssdk:sts'
}

test {
    testlogger {
        theme 'standard-parallel' // task level
    }
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
    def test_suite = System.getenv().get("TEST_FLAG")
    retry {
        maxRetries = 1
        maxFailures = 10
    }
    useJUnitPlatform {
        excludeTags 'org.junit.jupiter.api.Disabled'

        if ((test_suite != null) && (test_suite != "full_suite")) {
            def tags = test_suite.replace(',', ' & ')
            includeTags tags
        }
    }
}

gradle.startParameter.continueOnFailure = true
test.finalizedBy(aggregate)

`

**Comment by fericeand** [comment]
in my case the report is generated, but when clicking on scenario I got the error

<img width="1503" alt="Screenshot 2024-05-20 at 09 01 17" src="https://github.com/serenity-bdd/serenity-core/assets/68053441/20008513-9e89-42f9-aa8a-143642afc507">
<img width="1654" alt="Screenshot 2024-05-20 at 09 01 30" src="https://github.com/serenity-bdd/serenity-core/assets/68053441/dab5e009-96be-40eb-b06a-c2b8175787a9">
<img width="1437" alt="Screenshot 2024-05-20 at 09 01 40" src="https://github.com/serenity-bdd/serenity-core/assets/68053441/08fbe35d-840f-481c-aa5e-f0732413e772">

**Comment by vilasyra59** [comment]
> > [@wakaleo](https://github.com/wakaleo) I'm able to fix this issue, now serenity-summary.html report is getting generated.
> > We're good to close this issue.
> 
> How did you solve this? I have the same issue.

I have the exactly same problem on old project. I'm googling around. I stumble upon threads like this, and I feel morally obliged to leave a reply... even three years after the original post.

A developper comes in begging the community for help, somehow finds the solution, and then juste vanishes into the void without ever updating the ticket with the fix that could help literally everyone else afterward.

Absolutely incredible behavior. Civilization truly peaked.

**Comment by wakaleo** [comment]
`Unable to get public no-arg constructor: net/thucydides/core/util/EnvironmentVariables` or similar is almost certainly a version conflict between the various Serenity libraries - that would be the place to look.
