### ISSUE TITLE
tagging feature doesn't work in serenity from mavne

### ISSUE THREAD

**Issue by Vovanchik** [serenity-bdd/serenity-core#33]
I have TCs grouped by several tags.

When I specifying -Dtags="tag1:tag2" parameter in maven build all tests are skipped. :(

Serenity version: 1.0.35

Works in thucydides 0.9.275.

**Comment by wakaleo** [comment]
JUnit or JBehave?

**Comment by Vovanchik** [comment]
JUnit

*Volodymyr Koval*

**Comment by mikezx6r** [comment]
If you're trying to run tests with a tag of tag1 or tag2,then you need to
separate them by either spaces or commas. Unfortunately I don't recall
which off the top of my head.

The colon allows for tag categorization. You can tag something
'category:tag1', 'category:tag2' and then get grouped under a header
categorys in the report.

What you've put for tags= will attempt to run for tag2 withing category
tag1.

Hth

**Comment by Vovanchik** [comment]
Hi,

Here part of my code with tags.

   @WithTags( {
           @WithTag(type="priority",name="medium"),
           @WithTag(type="component",name="supercomponent"),
           @WithTag(type="environment",name="superenv")

   })

In previous thucydides version from which I migrated to serenity I had
an ability to run TCs using following syntax
-Dtags="environment:superenv"

This is according your comments. But right now it does not work.

6 бер. 2015 13:51, користувач "Mike Wilkes" <notifications@github.com>
написав:

**Comment by mikezx6r** [comment]
I wonder if it's an issue with @WithTag/@WithTags. I've been using `@WithTagValuesOf`, and that's been working for me. 

For your example, it would be 

    @WithTagValuesOf({"priority:medium", "component:supercomponent", "environment:superenv"})

and you should be able to use `-Dtags="environment:superenv"`

**Comment by wakaleo** [comment]
The older @WithTag/@WithTags annotations still seems to work fine - are you
sure you are passing the "tags" environment variable through to
surefire/failsafe? Can you create a sample project that reproduces the
problem?

On 9 March 2015 at 00:58, Mike Wilkes <notifications@github.com> wrote:

> I wonder if it's an issue with @WithTag/@WithTags. I've been using
> @WithTagValuesOf, and that's been working for me.
>
> For your example, it would be
>
> @WithTagValuesOf({"priority:medium", "component:supercomponent", "environment:superenv"})
>
> and you should be able to use -Dtags="environment:superenv"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/33#issuecomment-77750191>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by Vovanchik** [comment]
Hi John,

I'll double check and if it will be still reproducible I send you this test
project.

*Volodymyr Koval*

**Comment by Vovanchik** [comment]
Hi guys,

After some investigation I found root cause of problem.

Problem is not in serenity. Problem in Continuous Integration server which
I used to run TCs.  In my case this is teamcity.

When on teamcity I passed parameter -Dtags="environment:superenv" all tests
were skipped. Teamcity somehow incorrectly interpret *quotes*. Everything
work's ok without quotes:  -Dtags=environment:superenv.

Sorry for misleadin and thank's for quick answers.

Problem resolved.

--
*Volodymyr Koval*

**Comment by mikezx6r** [comment]
Ahhh, yes! Sorry I didn't think of that sooner. I had the same problem, but
with Bamboo. Didn't remember it until you discovered it too.

I suspect TeamCity does the same thing Bamboo does. Wraps the whole command
in quotes.

Putting quotes inside quotes of course 'confuses' the shell, and therefore
you're not running what you think you're running.

Glad you figured it out too.  I'll have to make a stronger mental note
about this one.

Something to add to the manual under 'CI Server configuration/execution'.

**Comment by tomasvalentatelus** [comment]
Hello, I cannot make multiple tags to work.
I'm testing with the starter project.
Added this
`@Test
    @WithTag("tag1")
    public void addingSums() {
    ...
    }
@Test
    @WithTag("tag2")
    public void addingSums2() {
    ...
    }
`

but running 
mvn verify -Dtags="tag1, tag2"
results with
io.cucumber.tagexpressions.TagExpressionException: Tag expression 'tag1, tag2' could not be parsed because of syntax error: expected operator

**Comment by tomasvalentatelus** [comment]
So after reviewing Cucumber docs, I realized the tags should be specified with Cucumber operators.
So the correct command would be
`mvn verify -Dtags="tag1 or tag2"`
Can you please update your documentation here:
https://serenity-bdd.github.io/theserenitybook/latest/filtering-reports.html#_running_scenarios_by_tags

Thanks.

**Comment by globalworming** [comment]
you can just quickly edit it yourself https://github.com/serenity-bdd/the-serenity-book/edit/master/modules/ROOT/pages/filtering-reports.adoc

**Comment by tomasvalentatelus** [comment]
This seems to have already been fixed by commit 250b35750d7e4a867f98a5beb7468a128c935674
How will it propagate to https://serenity-bdd.github.io/theserenitybook/latest/filtering-reports.html#_running_scenarios_by_tags page?
The page does not have latest content.
