### ISSUE TITLE
Tags are missing in serenity report 4.0.15

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#3300]
### What happened?

I have migrated an old serenity project 2.5.8 to the latest release 4.0.15 plus moving test cases from jUnit 4 to 5. The tests are running but the tags defined by "WithTags/WithTag" are missing in the serenity report.

### What did you expect to happen?

The tags defined by "WithTags/WithTag" annotations should be present in the serenity report.

### Serenity BDD version

4.0.15

### JDK version

11.0.21

### Execution environment

OS: macOS Monterey 12.7
Browser: Chrome 118.0.5993.96

### How to reproduce the bug.

1. Run the below test case
```
@ExtendWith(SerenityJUnit5Extension.class)
@WithTags({@WithTag(type = "Test", name = "SomeTest"), @WithTag(type = "Application", name = "SomeApplication")})
public class SmokeTest {

@Test
public void runSmokeTest() {
      // Some test here...
   }
}
```
2. Aggregate the report
3. Open the report and verify tags

Workaround: Using jUnit 5 annotations
```
@Tags({@Tag("Test:SomeTest"), @Tag("Application:SomeApplication")})
```

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
Are you using the JUnit 5 tags?

**Comment by aybartsch** [comment]
I'm currently using the jUnit 5 tags as a workaround but would be prefer to use serenity tags instead.

**Comment by wakaleo** [comment]
The serenity tags are only for JUnit 4 - in JUnit 5 only native JUnit 5 tags are supported

**Comment by aybartsch** [comment]
Okay. Should the annotations not be excluded from serenity-model-4.0.15.jar or marked as depcrecated?

**Comment by wakaleo** [comment]
No, because they are still relevant for JUnit 4 tests.

**Comment by aybartsch** [comment]
Thanks, John!
