### ISSUE TITLE
How to migrate CucumberWithSerenity to use jUnit 5

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#3305]
### What happened?

I'm updating our test project from serenity 3.7.1 to 4.0.15. But I also want to replace jUnit 4 by 5. The current test class implementation is calling the jUnit 4 runner:
```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        features = "classpath:/features/api/health/NvzHealthCheck.feature",
        glue = {"com.westernacher.nvz.e2e.steps.api.health"})
public class NvzHealthCheckTest extends BaseTest {
}
```

I changed dependency "net.serenity-bdd:serenity-cucumber" to "net.serenity-bdd:serenity-cucumber4" which should support jUnit 5 but I cannot find a proper replacement for @RunWith and @CucumberOptions. How should the test class be annotated to support Serenity and Cucumber and jUnit 5.

### What did you expect to happen?

The test case should run with Serenity and Cucumber and jUnit 5.

### Serenity BDD version

4.0.15

### JDK version

11.0.21

### How to reproduce the bug.

n/a

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
The way to run Cucumber in JUnit 5 is totally different, so the @RunWith runners will not work. You need to do something like this:
```
import org.junit.platform.suite.api.ConfigurationParameter;
import org.junit.platform.suite.api.IncludeEngines;
import org.junit.platform.suite.api.SelectClasspathResource;
import org.junit.platform.suite.api.Suite;

import static io.cucumber.junit.platform.engine.Constants.PLUGIN_PROPERTY_NAME;

@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("/features")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME,
                        value = "io.cucumber.core.plugin.SerenityReporterParallel,pretty,timeline:target/test-results/timeline")
public class CucumberTestSuite {
}
```

**Comment by aybartsch** [comment]
Thanks, John. That's indeed totally different compared to previously applied implementation. How I have to define the "glue" between the feature files and the step classes? Do you have a test case instead of test suite example?

**Comment by wakaleo** [comment]
There's a ConfigurationParameter option for the glue code package as well, e.g.

```
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("/features")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME,
        value = "io.cucumber.core.plugin.SerenityReporterParallel,pretty")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "net.serenitybdd.demos.todos.stepdefinitions")
public class CucumberTestSuite {
}
```

**Comment by aybartsch** [comment]
Sounds good! I'm not using test suites but test cases only. May I skip the @Suite annotation?

**Comment by wakaleo** [comment]
No 
<img width="383" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/55986/24b41525-0e16-470c-9b78-645accb63e5a">

**Comment by aybartsch** [comment]
Okay, I will give it a try. Is it correct to move from "net.serenity-bdd:serenity-cucumber" to "net.serenity-bdd:serenity-cucumber4"?

**Comment by wakaleo** [comment]
Yes, that is the correct dependency.

**Comment by aybartsch** [comment]
Unfortunately, IntelliJ cannot resolve the jUnit 5 annotations. I guess my dependency stack does not fit any longer:
```
    testImplementation "net.serenity-bdd:serenity-core:4.0.15"
    testImplementation "net.serenity-bdd:serenity-junit5:4.0.15"
    testImplementation "net.serenity-bdd:serenity-cucumber4:4.0.15"
    testImplementation "net.serenity-bdd:serenity-rest-assured:4.0.15"
    testImplementation "io.github.bonigarcia:webdrivermanager:5.5.3"
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.0"
    testImplementation "org.junit.platform:junit-platform-launcher:1.10.0"
    testImplementation "org.junit.vintage:junit-vintage-engine:5.10.0"
```
Could you please tell me what is wrong here?

**Comment by aybartsch** [comment]
FYI: After adding "testImplementation "org.junit.platform:junit-platform-suite-engine" the annotations could be found.

But IntelliJ still cannot resolve the keys PLUGIN_PROPERTY_NAME and GLUE_PROPERTY_NAME.

**Comment by aybartsch** [comment]
One further dependency was needed "org.junit.platform:junit-platform-engine" to resolve the constants problem above.

**Comment by aybartsch** [comment]
The below dependency stack is working now:
```
    testImplementation "net.serenity-bdd:serenity-core:4.0.15"
    testImplementation "net.serenity-bdd:serenity-junit5:4.0.15"
    testImplementation "net.serenity-bdd:serenity-cucumber:4.0.15"
    testImplementation "net.serenity-bdd:serenity-rest-assured:4.0.15"
    testImplementation "io.github.bonigarcia:webdrivermanager:5.5.3"
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.0"
    testImplementation "org.junit.vintage:junit-vintage-engine:5.10.0"
    testImplementation "org.junit.platform:junit-platform-launcher:1.10.0"
    testImplementation "org.junit.platform:junit-platform-engine:1.10.0"
    testImplementation "org.junit.platform:junit-platform-suite-engine:1.10.0"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:7.14.0"
```

@wakaleo One final issue: The solution to get all tags which you described  in issue [199](https://github.com/serenity-bdd/serenity-cucumber/issues/199) is causing a NullPointerException with the new serenity stack. What is the replacement to get all feature tags?

**Comment by aybartsch** [comment]
I could solve the problem by myself using the scenario object in the before hook:
```
scenario.getSourceTagNames()
```
Many thanks, @wakaleo! Coffee is on the way... ;-)

**Comment by Benski89** [comment]
Hi, 

Can someone help me I have setup my framework to run in parallel. However Im getting a runtime error stating

```
org.junit.platform.commons.JUnitException: Failed to transform configuration parameter with key 'cucumber.plugin' and initial value 'io.cucumber.core.plugin.SerenityReporterParallel,pretty,timeline:target/test-results/timeline'

Caused by: java.lang.IllegalArgumentException: The plugin specification 'io.cucumber.core.plugin.SerenityReporterParallel' has a problem:

Could not load plugin class 'io.cucumber.core.plugin.SerenityReporterParallel'.

This my CucumberTestSuite below

package ho.qat.seo.testrunners;

import org.junit.platform.suite.api.ConfigurationParameter;
import org.junit.platform.suite.api.IncludeEngines;
import org.junit.platform.suite.api.SelectClasspathResource;
import org.junit.platform.suite.api.Suite;

import static io.cucumber.junit.platform.engine.Constants.PLUGIN_PROPERTY_NAME;
import static io.cucumber.junit.platform.engine.Constants.GLUE_PROPERTY_NAME;

@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("/features")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME,
        value = "io.cucumber.core.plugin.SerenityReporterParallel,pretty,timeline:target/test-results/timeline")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "net.serenitybdd.demos.todos.stepdefinitions")
public class CucumberTestSuite {
}

and this below is my junit.platform.properties file 

cucumber.execution.parallel.enabled=true
cucumber.execution.parallel.config.strategy=dynamic
cucumber.execution.parallel.config.fixed.parallelism=3
cucumber.execution.parallel.config.fixed.max-pool-size=3
cucumber.plugin=io.cucumber.core.plugin.SerenityReporterParallel

```
