### ISSUE TITLE
Parallel test execution with Cucumber & JUnit5 gives `TestEngine with ID 'junit-platform-suite' failed to discover tests`

### ISSUE THREAD

**Issue by Mo0rBy** [serenity-bdd/serenity-core#3307]
### What happened?

I have followed the documentation [here](https://serenity-bdd.github.io/docs/tutorials/running_cucumber_scenarios_in_parallel) on setting up JUnit5 in my Cucumber Serenity project to enable parallel testing.

When I run the test suite after making all the modification as stated in the docs, I get an error and none of my tests run:
```
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] TestEngine with ID 'junit-platform-suite' failed to discover tests
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

### What did you expect to happen?

I expected the tests to execute in parallel

### Serenity BDD version

4.0.12

### JDK version

openjdk version "17.0.6" 2023-01-17

### Execution environment

MacOS Ventura 13.6
Chrome v118

### How to reproduce the bug.

Follow the Cucumber Serenity Screenplay docs to setup a Cumber Serenity project > https://serenity-bdd.github.io/docs/tutorials/cucumber-screenplay

Follow the docs to setup JUnit5 and Cucumber for parallel testing > https://serenity-bdd.github.io/docs/tutorials/running_cucumber_scenarios_in_parallel

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by Mo0rBy** [comment]
I've done some more troubleshooting and found that when changing the version of the `junit-bom` dependency to `5.8.2` gives me a successful build, but with 0 tests run:
```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>5.8.2</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

```
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- serenity:4.0.12:aggregate (serenity-reports) @ psdt.automationtesting ---
```

With `junit-bom` at version `5.9.3`, I see the same error as before:
```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>5.9.3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

```
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] TestEngine with ID 'junit-platform-suite' failed to discover tests
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- serenity:4.0.12:aggregate (serenity-reports) @ psdt.automationtesting ---
```

**Comment by wakaleo** [comment]
"TestEngine with ID 'junit-platform-suite' failed to discover tests" is a JUnit 5 error, most likely due to inconsistent jUnit libraries. Make sure you are using the same version of JUnit as the Serenity version you are using.

**Comment by Mo0rBy** [comment]
I've looked at serenity-core on maven repository to list it's dependencies and found that for Serenity v4.0.12 it uses:



junit » junit | 4.13.2
org.junit.jupiter » junit-jupiter-api | 5.10.0

**Comment by Mo0rBy** [comment]
I believe I found my problem and you were correct.
Had the `junit-jupiter-api` package with a different version:
```xml
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.9.1</version>
```

Removed this version definition and it is working. Thanks!
