### ISSUE TITLE
Total Duration  for individual tests are not correct in Serenity report

### ISSUE THREAD

**Issue by johnysv** [serenity-bdd/serenity-core#3315]
### What happened?

I am using SerenityBDD with Junit 5. When Running the test from jenkins, it took 32 mins as mentioned in Total duration. But the individual test time is not correct.

![image](https://github.com/serenity-bdd/serenity-core/assets/41629868/3450d198-d4dd-4327-a657-f1bf2d4f0c00)

The version which I use are

<rest.assured.version>5.3.2</rest.assured.version>
<serenity.version>4.0.15</serenity.version>
<selenium.version>4.14.0</selenium.version>
<artifactId>junit-jupiter-engine</artifactId>
			<version>5.10.0</version>
<artifactId>serenity-junit5</artifactId>
			<version>4.0.15</version>
JDK 17

### What did you expect to happen?

Individual time durations should match the total time duration

### Serenity BDD version

4.0.15

### JDK version

17

### How to reproduce the bug.

Run with the above configurations

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by Tamas-Demeny** [comment]
I have this same issue
![image](https://github.com/serenity-bdd/serenity-core/assets/110590815/3d9d220e-db1f-4b2c-a3af-36df1a49956a)
The total time for the two Scenarios from `Scenario Outline` is not correct and if I run a test which is a `Scenario` in cucumber, then the tests execution time is incorrect

**Comment by wakaleo** [comment]
Test durations are a tricky concept, particularly with Cucumber 7 parallel execution. If it is important to your organisation and you would like it prioritised, the best option would be to look into the commercial support packages.

**Comment by brabenetz** [comment]
FYI:
I maybe had the same problem, but I used serenity 3.9.2: a failed step (because of 30s timeout) only showed a few ms:
![image](https://github.com/serenity-bdd/serenity-core/assets/1237858/19797fb4-343d-43a4-b6d0-4a578f72f655)

After upgrading to the latest version 4.1.14 it works now again:
![image](https://github.com/serenity-bdd/serenity-core/assets/1237858/b90a7f97-e8cc-46a4-aa65-ba7460c55095)

**Comment by wakaleo** [comment]
I think this is fixed in 4.1.14
