### ISSUE TITLE
Error when updating serenity version to 4.0.19

### ISSUE THREAD

**Issue by ravibabu1408** [serenity-bdd/serenity-core#3319]
Below error is displayed while running serenity tests after updating serenity dependency to 4.0.19. and browser is not launched
 <<< ERROR!
net.serenitybdd.model.exceptions.SerenityManagedException: 'javax.net.ssl.SSLContext org.openqa.selenium.remote.http.ClientConfig.sslContext()'

Can anyone please suggest me is there any other dependency needs to be added for this error.?

**Comment by wakaleo** [comment]
Pretty much all the issues like this related to updating to 4.x.x are due to dependency conflicts or old drivers on your path, so the first thing to do is a dependency analysis. This particular error doesn't ring any bells.

**Comment by ravibabu1408** [comment]
Ok sure, thanks @wakaleo

**Comment by wakaleo** [comment]
Closing presumed fixed
