### ISSUE TITLE
Maven compile fails with pronouns specified in serenity.conf

### ISSUE THREAD

**Issue by MaxenceBontePE** [serenity-bdd/serenity-core#3321]
### What happened?

I have specified pronouns as specified in docs in serenity.conf

`screenplay.pronouns=il,elle,ils,elles,son,sa,leur,leurs`

I launched a Maven compile (verify) and got his result:
`[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:4.0.18:aggregate (serenity-reports) on project cucumber-starter: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:4.0.18:aggregate failed: D:\git\depotoffrerecruteur-serenitybdd\src\test\resources\serenity.conf: 25: Key 'elle' may not be followed by token: ',' (if you intended ',' to be part of a key or string value, try enclosing the key or value in double quotes) -> [Help 1]`

### What did you expect to happen?

Compile should have passed this step.

### Serenity BDD version

<serenity.version>4.0.19</serenity.version>

### JDK version

11.0.21

### Execution environment

Windows
Chrome

### How to reproduce the bug.

just need to specify the screenplay.pronouns property as stated and launch mvn (e.g. verify)

**Comment by MaxenceBontePE** [comment]
Seems the docs are incorrect. You can't configure pronouns. I'm pretty sure this used to work in Serenity 3.
@wakaleo why did this feature disappear ? I have to specify my actor's name in every step of my Gherkin scenario, which is weird. Serenity shouldn't make it compulsory to write my scenario in a particular way.

**Comment by wakaleo** [comment]
Try putting the list of pronouns in quotes.

**Comment by MaxenceBontePE** [comment]
Ok it worked.
So this is a part of my serenity.conf file:
```
serenity {
    take.screenshots = AFTER_EACH_STEP
    #FOR_EACH_ACTION: Saves a screenshot at every web element action (like click(), typeAndEnter(), type(), typeAndTab() etc.).
    #BEFORE_AND_AFTER_EACH_STEP: Saves a screenshot before and after every step.
    #AFTER_EACH_STEP: Saves a screenshot after every step
    #FOR_FAILURES: Saves screenshots only for failing steps.
    #DISABLED: Doesn’t save screenshots for any steps.*/
    pronouns = "il,elle,ils,elles,son,sa,leur,leurs"
}
```
