### ISSUE TITLE
How to import system environment variable to serenity.conf file

### ISSUE THREAD

**Issue by ravibabu1408** [serenity-bdd/serenity-core#3323]
Currently i am working on serenity tests integration with browser stack. I want to pass browserstack. user and browserstack.accessKey from system environment variable to serenity.conf file.
so that who ever is working they can use their own user and access key from windows environment variable values
Can anyone please suggest how can pass values to serenity.conf file.

**Comment by wakaleo** [comment]
See the Typesafe Config docs - it is explained in some detail.
