### ISSUE TITLE
Serenity Rest: When api method has @Step annotation, it is not failed on wrong status code

### ISSUE THREAD

**Issue by jurec72** [serenity-bdd/serenity-core#3331]
### What happened?

API request is not failed and next steps continue execution, but in report shows failure.
I found that it is happening only in latest version of Serenity, but in 3.7.1 all worked perfect.
And it is happening when I use annotation on top of method as **@Step**

In the example below assertion is not failed:
```java
//class where we have all assertions for api
public class AssertActions {

public void verifyStatusCode(int statusCode) {
assertThat(getStorage().getLastResponse().statusCode()).isEqualTo(statusCode);
}
}
`
```java
public class ExecutionClass {
    @Shared
    private AssertActions assertActions;


    @Step("get all users from account with feature name: {0}, company: {1}") //if remove this step then all as should be
    public void getAllUsers(String featureName, Companies company) {
        requestActions.sendRequest(BaseUrl.A_API, HttpMethods.GET, UserEndpoints.GET_USERS.getEndpoint());
        assertActions.verifyStatusCode(HttpStatus.SC_OK);//should stop code here, but continue execution
//if use assertion here as 'assertThat(lastResponce.statuscode).isEqualsTo(200) then it is failed, but code above worked in previous version of Serenity 3.7.1, so should be working here as well
    }

}
```

As you can see from report below, it is failed on first step api, but continue execution other steps and showing them as green:
![55551](https://github.com/serenity-bdd/serenity-core/assets/38194479/59a52830-db01-4e65-b362-9d6cb01c4583)

### What did you expect to happen?

Expect: assertion to fail right awai

### Serenity BDD version

4.0.21

### JDK version

jdk-17

### Execution environment

Windows 11
Chrome 119

### How to reproduce the bug.

do not have separate project for this right now

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
Can you create a sample project to reproduce this?

**Comment by jurec72** [comment]
Hi @wakaleo , here is sample project to reproduce this bug - [Sample Project](https://github.com/jurec72/sampleProject/tree/master).
Let me know please if you have any questions!
Thank you!

**Comment by wakaleo** [comment]
Had a quick look - I'm not sure what is wrong, but this seems to work fine with Cucumber 7 and the JUnit 5 Serenity runner. (I haven't seen this issue in older versions either so it could be a project-specific issue of some kind. Your steps are in src/main/java not src/test/java which is odd, but I don't think it should affect anything).

Can you try with the latest version of Cucumber and JUnit 5? Here's an example of your scenario working correctly with JUnit 5 and Cucumber 7:

<img width="1711" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/55986/d9b0bcf8-b386-4e4b-8eba-bed4b1ee1ac0">

**Comment by jurec72** [comment]
I just think that in version 3.7.1 it is working fine with junit4. But in 4.0.21 not working properly! Because setup junit 5 is not easy, so not ready to move there yet! Is Serenity 4.0.21 better support junit5?
Thank you!

**Comment by wakaleo** [comment]
We will only be maintaining and updating JUnit 5 and Cucumber 7.x moving forward, and you need JUnit 5/Cucumber to support parallel execution, so yes, it is recommended to move to the latest version.

**Comment by jurec72** [comment]
Got it, thank you!
