### ISSUE TITLE
Not able to read the values from serenity.conf file

### ISSUE THREAD

**Issue by santhoshkumar-ponnusamy** [serenity-bdd/serenity-core#3335]
After upgrading to latest serenity version 4.0.24, am not able to read the values from serenity.conf file.

We have multiple values in serenity.conf, when i try to read - it says environment variables is null.

Its working fine with 3.X older versions of serenity. Can you please help me in reading the values from serenity.conf file.

![image](https://github.com/serenity-bdd/serenity-core/assets/94733440/20d6a5ab-0833-496b-8cd2-def43979d278)

**Comment by wakaleo** [comment]
We no longer use Guice. See https://github.com/serenity-bdd/serenity-core/blob/main/docs/release-notes/4.0.1.md

**Comment by santhoshkumar-ponnusamy** [comment]
Updated as per latest version comments.
