### ISSUE TITLE
Chromedriver fails to start when used with a proxy since release 4.0.21

### ISSUE THREAD

**Issue by muppet3000** [serenity-bdd/serenity-core#3340]
### What happened?

When maven is executed as follows:
``` mvn -B -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dmaven.repo.local=/opt/mvn_cache -f ./pom.xml  -Dheadless.mode=true clean verify -Dhttp.proxyHost=<PROXY_HOSTNAME> -Dhttp.proxyPort=<PROXY_PORT> -Dhttps.proxyHost=<PROXY_HOSTNAME> -Dhttps.proxyPort=<PROXY_PORT> -Dhttp.nonProxyHosts=<NON_PROXY_LIST_PIPE_SEPARATED_INCLUDING_LOCALHOST>```
Since release 4.0.21 it fails to obey/listen to the `http.nonProxyHosts` argument and attempts to go out via the proxy for localhost calls e.g.
```Caused by: net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.chrome.ChromeDriver
WebDriver reported the following message: Could not start a new session. Unable to parse remote response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2021 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!--
 /*
 * Copyright (C) 1996-2021 The Squid Software Foundation and contributors
 *
 * Squid software is distributed under GPLv2+ license and includes
 * contributions from numerous individuals and organizations.
 * Please see the COPYING and CONTRIBUTORS files for details.
 */

/*
 Stylesheet for Squid Error pages
 Adapted from design by Free CSS Templates
 http://www.freecsstemplates.org/
 Released for free under a Creative Commons Attribution 2.5 License
*/

<LOTS OF REMOVED CONTENT THAT ISN'T RELEVANT>

<p>The following error was encountered while trying to retrieve the URL: <a href="http://localhost:29188/session">http://localhost:29188/session</a></p>
```

Some additional info: we are running inside a docker container ([docker-maven-chrome](https://hub.docker.com/r/markhobson/maven-chrome/)) - the previous 114 release of chromedriver.

Either in the 4.0.21 release some support for the non-proxy list was removed, OR it has never used those values and instead has started looking at `localhost` for something else.

This same issue appears to be present in the latest 4.0.24 release as well which I have attempted to roll-forward to as part of the investigation (this same issue happens with 4.0.24 with 114 chromedriver and also 4.0.24 with 119 chromedriver).

### What did you expect to happen?

The nonProxyHosts values should be observed and adhered to therefore localhost would not attempt to go out via the proxy.

If there is an alternative way to specify the proxy and nonproxy details, please let me know so that I can test that.

### Serenity BDD version

4.0.21, 4.0.24

### JDK version

17

### Execution environment

We are running inside a docker container ([docker-maven-chrome](https://hub.docker.com/r/markhobson/maven-chrome/)) - the previous 114 release of chromedriver (JDK 17).

The same issue happens with the latest version as well.

This all works fine with 4.0.19, then breaks with 4.0.21 as the only change to the codebase.

### How to reproduce the bug.

Run a serenity job using a proxy, with nonProxyHosts including localhost.
Use 4.0.21 or higher of serenity.

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
I don't think this is Serenity related. Does it work in pure Selenium?

**Comment by muppet3000** [comment]
I can get someone to test and report back. Is the suggestion that something that serenity includes when we increase the version causes this?

**Comment by sandeepraina-lenze** [comment]
Can this be the reason of failure [https://github.com/seleniumbase/SeleniumBase/issues/2343](https://github.com/seleniumbase/SeleniumBase/issues/2343)

**Comment by wakaleo** [comment]
Possibly, but Serenity doesn't use that value, so it might be a chrome driver issue.

**Comment by muppet3000** [comment]
For anyone coming to this, I've been running some extensive tests with my team that uses serenity and this does seem to be an issue with the version of Selenium at play and not anything in Serenity itself.
We see this proxy issue when running with Selenium 4.15.0, but we don't with the latest (4.16.1 at the time of writing), therefore I'm hoping that when there is a release of Serenity that includes 4.16.1 of Selenium I can re-test and report back that this is resolved, although, with the holiday season upon us that's now likely to be in the new year.

**Comment by wakaleo** [comment]
Version 4.0.29 of Serenity works with 4.16.1.

**Comment by sandeepraina-lenze** [comment]
I can confirm that latest Serenity version 4.0.29 works perfectly fine and I can launch the Chrome browser without any issue.

**Comment by wakaleo** [comment]
@sandeepraina-lenze can we close this issue?

**Comment by muppet3000** [comment]
Please can we leave it open one more day until I've got my team to test tomorrow?
I originally raised the bug so I was hoping it could stay open at least until I've confirmed my issue is resolved?

**Comment by sandeepraina-lenze** [comment]
> @sandeepraina-lenze can we close this issue?

Technically we can but since I am not the originator so we need to hear from him too

**Comment by muppet3000** [comment]
I can confirm this is now resolved, we also required a few other configuration changes to our chrome options, but overally the bump to 4.0.29 gave us everything we needed.
The other options we added (in case it helps others):
`--remote-debugging-pipe` & `--no-sandbox` as per: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35
