### ISSUE TITLE
Not able to generate the Report & Unwanted run statements printing in console - Latest version of serenity

### ISSUE THREAD

**Issue by santhoshkumar-ponnusamy** [serenity-bdd/serenity-core#3346]
Hi @wakaleo & Team,

After upgrading to latest serenity version, am facing 2 different issues, can you please help me resolve this.

**Issue 1**. Unwanted run status is displaying in console. For example: **Run 88: PASS** and so on.. How to avoid this.?

![image](https://github.com/serenity-bdd/serenity-core/assets/94733440/65945eb3-af93-4c7c-99b3-7b5454bbce65)

**Issue 2**. I am not able to generate the report, getting below error in console. How to resolve this.?

![image](https://github.com/serenity-bdd/serenity-core/assets/94733440/d50a255f-4adf-45a1-b615-278c77539ce2)

**Comment by wakaleo** [comment]
Try running with -e

**Comment by wakaleo** [comment]
The first issue looks like an issue with your tests.

**Comment by santhoshkumar-ponnusamy** [comment]
> Try running with -e

Sorry i didn't understand @wakaleo..

**Comment by wakaleo** [comment]
I don't think the "Run 80: PASS" statements are related to Serenity.

**Comment by santhoshkumar-ponnusamy** [comment]
> I don't think the "Run 80: PASS" statements are related to Serenity.

ok... I will check with other forums... Any update on second issue reported.?

**Comment by wakaleo** [comment]
Run mvn verify -e to see if there is any additional information.

**Comment by santhoshkumar-ponnusamy** [comment]
> Run mvn verify -e to see if there is any additional information.

Executed using above commans, getting below error.. @wakaleo 

![image](https://github.com/serenity-bdd/serenity-core/assets/94733440/4591541c-387a-4478-944e-a36549af9fff)

**Comment by wakaleo** [comment]
That's an error in the report generation but without a detailed stack trace and/or a project that reproduces the issue, it isn't possible to see where the error is coming from.

**Comment by santhoshkumar-ponnusamy** [comment]
Resolved
