### ISSUE TITLE
single line comment with !--  in scenario in serenity 3.3.0 is not working

### ISSUE THREAD

**Issue by Nagaraj-Lagashetty** [serenity-bdd/serenity-core#3348]
### What happened?

single line comment with !-- in scenario in serenity 3.3.0 is making entire scenario as ignored in report. which was not the case in 2.3.0 serenity.
!-- is used to comment th step in feature file.
After updating serenitycore version from 2.3.0 to 3.3.0 behaviour mentioned in section 6.1.3 in below serenity doc is not working as expected. https://serenity-bdd.info/docs/serenity/

### What did you expect to happen?

When any perticular line is commented out usinf !--, Scenario in serenity report should be marked success based on steps performed istead of marking entire as ignored.

### Serenity BDD version

3.3.0

### JDK version

java 17.0.9 2023-10-17 LTS

### Execution environment

os :windows. 
browser: chrome

### How to reproduce the bug.

run any scenario with single line comment mentioned in the scenario.

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
See https://cucumber.io/docs/gherkin/reference/#:~:text=Comments%20are%20only%20permitted%20at,(%20%23%20)%20and%20some%20text.

**Comment by wakaleo** [comment]
Closing as "!--" comments are not supported Gherkin syntax in Cucumber 7.
