### ISSUE TITLE
After adding @Step, Serenity BDD report NOT printing parameterize data into report

### ISSUE THREAD

**Issue by kavimukh** [serenity-bdd/serenity-core#3354]
### What happened?

Scenario Outline reading data from Examples and serenity report not printing actual data into report

### What did you expect to happen?

Serenity BDD report need to print Actual data which is in Scenario Outline Examples

### Serenity BDD version

4.0.14

### JDK version

Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)

### How to reproduce the bug.

This is my feature file
Scenario Outline: Check Page Status and JQuery
Given Page is loaded

Examples:
  | URL | SIZE |
  | https://www.google.com/online/ |

=== StepDefinitions.java
    @Steps
    CommonActions commonActions;

@given("Page {word} is loaded")
public void pageURLIsLoaded(String pageURL) throws MalformedURLException {
System.out.println("Navigating to => "+pageURL);
commonActions.navigateTo(pageURL);
}

===
CommonAction.java
https://github.com/step("Page {word} is loaded")
public void navigateTo(String goToURL) throws MalformedURLException {
System.out.println("platform.contains "+ environmentVariables.getProperty("environment"));
Serenity.setSessionVariable("return_user_flow").to(false);
getDriver().navigate().to(goToURL);
}

In Serenity Report it's not printing URL
Refer to screen capture
<img width="706" alt="Screenshot 2023-12-13 at 5 39 20 AM" src="https://github.com/serenity-bdd/serenity-core/assets/17184142/1f3e4294-f213-4486-a546-7f7453bee9eb">

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
This is a scenario outline, it will show the variable not the value (since in a scenario outline you typically have more than one example).

**Comment by kavimukh** [comment]
Thanks @wakaleo for the update
