### ISSUE TITLE
Getting error while import net.thucydides.core.annotations.Should;

### ISSUE THREAD

**Issue by kavimukh** [serenity-bdd/serenity-core#3355]
### Serenity BDD version

4.0.14

### JDK version

Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)

### How to reproduce the bug.

In my pom.xml file I have
In my pom.xml I already have
<dependency>
<groupId>net.serenity-bdd</groupId>
<artifactId>serenity-core</artifactId>
<version>4.0.14</version>
<scope>test</scope>
</dependency>

When I try to import net.thucydides.core.annotations.Should;
I am getting error message saying Cannot resolve symbol 'Should

@Should
public void myTest() {
    should("Result is correct").beEqual(someValue, expectedValue);
    should("Some element is visible").beTrue(someElement.isVisible());
}

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
There is no such annotation in Serenity. What are you trying to do?

**Comment by kavimukh** [comment]
Thanks @wakaleo for the update. I got this while searching on google and tried to my serenity automation.

**Comment by pentamchettyk** [comment]
@kavimukh  what was the solution you found?
