### ISSUE TITLE
Issues with SerenityParameterizedRunner

### ISSUE THREAD

**Issue by jordanbragg** [serenity-bdd/serenity-core#338]
I am having multiple issues with the SerenityParameterizedRunner. From @YamStranger comment, I am separating items into other tickets, but will leave this ticket with the following issues, which I believe I have a fix for already.

I showed a visual below, but the issues being observed:

1. @Qualifier is not being used in report
2. Scenario text should be the Given,When, Then of the first example.

I provided a github repo to demonstrate this: https://github.com/jordanbragg/serenity-report-test

<img width="779" alt="screen shot 2016-03-03 at 3 53 35 pm" src="https://cloud.githubusercontent.com/assets/6812229/13552585/179dc7f4-e31e-11e5-9c5a-ff819a490db6.png">

**Comment by YamStranger** [comment]
Hello @jordanbragg, thanks for this issue. 

Yes, it will be better if you find time to create separate ticket for each problem - because they will be fixed separately

Thanks!

**Comment by YamStranger** [comment]
@jordanbragg this issue should be fixed in next release.

Thanks!!!
