### ISSUE TITLE
Not getting html report while running test cases directly through runner class using IDE

### ISSUE THREAD

**Issue by PritiKumari95** [serenity-bdd/serenity-core#3383]
### What happened?

Not getting html report while running test cases directly through runner class using IDE

### What did you expect to happen?

html report should be generated with screenshot while running test cases directly through runner class using any IDE like STS,Eclipse etc.

### Serenity BDD version

4.0.30

### JDK version

11

### How to reproduce the bug.

Run the test cases through runner class in spring tool suite and see if you could generate html report

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
This is expected behaviour - the HTML reports are generate when you run mvn serenity:aggregate

**Comment by PritiKumari95** [comment]
Thanks for the information
