### ISSUE TITLE
Reporting failures with mutliple examples result in nested steps

### ISSUE THREAD

**Issue by Johan-Sap** [serenity-bdd/serenity-core#3393]
### What happened?

When I have a Scenario with multiple examples, and one of those (or all worst case) fail the report will show all steps of the next example as steps from the failed example. 

It happens when the assert or failure is nested a bit deeper in the code (not stepdefinitions or stepslib but a step that is called from a method in a stepslib or deeper);
Below is a screenshot of the report which shows the second example to be nested in the first one;

<img width="1423" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/151131559/5d36c650-4094-4813-b84c-50c3c9d7d3d8">

Traced the issue back to this change
https://github.com/serenity-bdd/serenity-core/pull/3369

reverted this change locally and using that snapshot results in the correct behaviour.

### What did you expect to happen?

All examples (regardless of passing or failing) will be shown as separate tests.

Below screenshot is of the report using my snapshot after reverting the code in change 
`https://github.com/Johan-Sap/serenity-core/commit/e2955c8aaf75798b1cb1f66c7b461b6a488f7f46`

<img width="1474" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/151131559/df70960c-c781-4b5b-8b68-b45b5961e08f">

### Serenity BDD version

As of 4.0.31 

### JDK version

20

### Execution environment

MAC
Chrome Browser

### How to reproduce the bug.

Repo:
https://github.com/Johan-Sap/eu_pvh_demo2

Run Command:
clean clearReports test

libs folder contains the snapshot of 4.0.47 in case you want to try that. Gradle should contain 
`testImplementation files('libs/*.jar', 'libs/serenity-core-4.0.47-SNAPSHOT.jar')`

in the depedencies to test the snapshot.

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
This appears to be a persistent problem in the parallel execution logic. Thanks for your investigations. Unfortunately we can't undo that commit as it is where we implement support for parallel execution in Cucumber.

**Comment by Rangiferus** [comment]
I reported a similar effect some time ago in https://github.com/serenity-bdd/serenity-core/issues/3296.
I run Srenity in one thread, no parallelization.

**Comment by wakaleo** [comment]
Fixed in 4.1.0

**Comment by Johan-Sap** [comment]
Perfect, tested it and seems to be working as expected indeed !

**Comment by Rangiferus** [comment]
Now, in 4.1.0 it's even worse. At least in all my cases with multiple examples when some of them fail on assertions specified in subtasks.
But not only. Even in regular scenarios (no examples) I'm getting a report with only one step visible and when it's expanded, then all steps are displayed mixed with log entries defined inside steps (that should be visible only when I expand their tasks) and with entries from @After hook. In some cases even the sequence of entries is totally wrong.

It's hard to reproduce and provide an example project to prove it due to complexity of my project.
cc: @wakaleo, @Johan-Sap

**Comment by wakaleo** [comment]
Maybe dive into the code and see if you can see anything. I wont be able to look at a fix without a sample project to reproduce the issue though.

**Comment by wakaleo** [comment]
It really sounds like there might be some project-specific issues though - we could look at your project directly, but it would have to be part of a commercial support package.
