### ISSUE TITLE
Can not set language and locale capabilities for appium via command line args

### ISSUE THREAD

**Issue by dragos-panzaru-md** [serenity-bdd/serenity-core#3409]
### What happened?

I have a custom driver that looks like this:
`public class SauceLabsAndroidDriver implements DriverSource {

    private static final String URL = "https://" + System.getenv("SAUCE_USERNAME") + ":" +
            System.getenv("SAUCE_ACCESS_KEY") + "@ondemand.eu-central-1.saucelabs.com:443/wd/hub";

    @Override
    public WebDriver newDriver() {
        try {
            MutableCapabilities caps = new MutableCapabilities();
            caps.setCapability("appium:platformVersion", "^(9|1[0-4]).*");
            caps.setCapability("appium:newCommandTimeout", 90);
            caps.setCapability("appium:deviceType", "phone");
            caps.setCapability("appium:deviceName", "^(Samsung|LG).*");
            caps.setCapability("appium:automationName", "UiAutomator2");
            caps.setCapability("appium:ignoreUnimportantViews", false);
            caps.setCapability("appium:app", "storage:" +  System.getenv("APP_ID"));
            MutableCapabilities sauceOptions = new MutableCapabilities();
            sauceOptions.setCapability("appiumVersion", "latest");
            sauceOptions.setCapability("name", "Android Test");
            sauceOptions.setCapability("phoneOnly", true);
            caps.setCapability("sauce:options", sauceOptions);
            return new AndroidDriver(new URL(URL), caps);
        } catch (MalformedURLException e) {
            throw new Error(e);
        }
    }

    @Override
    public boolean takesScreenshots() {
        return true;
    }
}`

When I run my tests via command line with mvn clean verify I want to be able to set the language and locale capabilities.
I tried it like this with no success:
` mvn clean verify "-Dappium.language=de" "-Dappium.locale=de" `

### What did you expect to happen?

My expectation was that the app would run in German when I executed my tests, but the app ran in default English.

### Serenity BDD version

3.9.8

### JDK version

11

### Execution environment

I am running on Android phone via saucelabs, but I also tried locally on emulator, still with no success

### How to reproduce the bug.

Just use the custom driver provided in the description or something like this if running locally on an emulator:
`public class LocalAndroidDriver implements DriverSource {

    private static final String URL = "http://127.0.0.1:4723";

    @Override
    public WebDriver newDriver() {
        try {
            MutableCapabilities caps = new MutableCapabilities();
            caps.setCapability("platformName", "Android");
            caps.setCapability("appium:platformVersion", "9");
            caps.setCapability("appium:newCommandTimeout", 30000);
            caps.setCapability("appium:appiumVersion", "latest");
            caps.setCapability("appium:automationName", "UiAutomator2");
            caps.setCapability("appium:deviceOrientation", "portrait");
            caps.setCapability("appium:enableMultiWindows", true);
            caps.setCapability("appium:deviceName", "emulator-5554");
            caps.setCapability("appium:app", "<apk_location>");
            return new AndroidDriver(new URL(URL), caps);
        } catch (MalformedURLException e) {
            throw new Error(e);
        }
    }

    @Override
    public boolean takesScreenshots() {
        return true;
    }
}`

and then set the custom driver in serenity properties and run the tests with maven:
`mvn clean verify "-Dappium.language=de" "-Dappium.locale=de"`

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
If you are using a custom driver, it will be your responsibility to collect and parse command-line options to the capabilities - Serenity cannot do it for you.

**Comment by dragos-panzaru-md** [comment]
Thank you for the info. Will do as you mentioned.

**Comment by thiagojalmeida** [comment]
Hi, @dragos-panzaru-md 

Could you please share where can I call the custom driver?
Serenity PageObject does not recognize  it and respond calls from @AndroidFinby as  css selector.
