### ISSUE TITLE
ERR_FILE_NOT_FOUND after running Gradle aggregate

### ISSUE THREAD

**Issue by s1apped** [serenity-bdd/serenity-core#3415]
### What happened?

After updating serenity from 4.0.27 to 4.1.3 test report is not aggregated properly (had to update because `@TestTemplate` displayName isn't working properly on 4.0.27)
When accessing scenario results I'm getting ERR_FILE_NOT_FOUND. Looks like aggregation fails to convert json to html because I can find the json with expected name.

### Serenity BDD version

4.1.3

### JDK version

17

### How to reproduce the bug.

` id 'net.serenity-bdd.serenity-gradle-plugin' version '4.1.3'`
![Zrzut ekranu 2024-03-10 o 11 26 38](https://github.com/serenity-bdd/serenity-core/assets/32245059/1a94f97a-3aa3-4d35-bcd8-01db50bbc2c9)

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
Make sure you do a clean build

**Comment by s1apped** [comment]
Tried multiple times.
![image](https://github.com/serenity-bdd/serenity-core/assets/32245059/62d7e6f5-98a9-41b1-b0ce-7a3244518f72)
![image](https://github.com/serenity-bdd/serenity-core/assets/32245059/f7531d46-74d6-43c1-9769-ef64f5dbbc3e)

**Comment by wakaleo** [comment]
It might be something to do with the name of the tests or scenarios - try setting serenity.compress.filenames to false and see if there are any patterns.

**Comment by s1apped** [comment]
Not sure what to look for
before aggregate:
![image](https://github.com/serenity-bdd/serenity-core/assets/32245059/7d2d66ed-b390-428d-93a2-c7237c5affcb)
after:
![image](https://github.com/serenity-bdd/serenity-core/assets/32245059/f9f262e7-538e-42b0-844a-e86549e49a20)
Looks like there is no other way than to debug reports

**Comment by wakaleo** [comment]
<img width="390" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/55986/04969e29-7aee-4229-9e69-a7232372998e">

You should see the html files with the end of the test names:

<img width="736" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/55986/6f429af4-ff99-4838-9e13-0353a12cd376">

Then compare this with the link that doesn't work to see for which test or page the report isn't getting generated.

Also check the console logs for exceptions.

**Comment by s1apped** [comment]
it's every test. initially I thought it's `@TemplateTest` but same behaviour for normal `@Test`. The expected html is missing and it's Scenario page with steps

**Comment by wakaleo** [comment]
OK, I can reproduce it. Seems to be a general problem with the Gradle plugin. Try rolling back the recent pull requests and see when the last version that worked was.

**Comment by s1apped** [comment]
rolling back gradle plugin to 4.0.46 solved the issues. Libs remained with 4.1.3

**Comment by wakaleo** [comment]
If you can identify the change in the plugin code that causes the issue we might be able to fix it. Having different plugin and library versions is not recommended.

**Comment by wakaleo** [comment]
See if 4.1.4-RC1 fixes the issue for you.

**Comment by s1apped** [comment]
works :)

**Comment by wakaleo** [comment]
Cool, I will include this in version 4.1.4

**Comment by khuenguyen-agilityio** [comment]
![Screenshot 2024-03-19 091833](https://github.com/serenity-bdd/serenity-core/assets/140588261/7b0e285b-d1e4-47b9-8351-c51f6b259fd4)
I got this when I open the report. Can anyone help me to solve it.
JDK : 21
Maven : 3.9.6
Serenity BDD : 4.1.0
Many thanks!

**Comment by wakaleo** [comment]
> ![Screenshot 2024-03-19 091833](https://private-user-images.githubusercontent.com/140588261/313894653-7b0e285b-d1e4-47b9-8351-c51f6b259fd4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Mzg2MDksIm5iZiI6MTcxMTQzODMwOSwicGF0aCI6Ii8xNDA1ODgyNjEvMzEzODk0NjUzLTdiMGUyODViLWQxZTQtNDdiOS04MzUxLWM1MWY2YjI1OWZkNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNzMxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Zjg3MWE5Mjk1ZTc0NmNhOWQ0NTA1YWMzZThlOWY1Y2YzOTFhY2I1YjM4MzA3ZmExZTdjY2JlYWRmNTUwOGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2pSyL5NIPlZIsBumjW2ysIdkZvIbflq7CUi5l9N5sgA) I got this when I open the report. Can anyone help me to solve it. JDK : 21 Maven : 3.9.6 Serenity BDD : 4.1.0 Many thanks!

This is unrelated to the original issue. Try doing a full clean build.

**Comment by amir143in** [comment]
Dear Team, 
After the execution an index.html file is generated but while accessing "scenario results" I'm getting ERR_FILE_NOT_FOUND.
Hereby I am attaching my build.gradle file:-

defaultTasks 'clean','test','aggregate'
apply plugin: 'java'
apply plugin: 'net.serenity-bdd.aggregator'

group 'org.automationserenity'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}
tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

sourceSets {
    test {
        resources {
            srcDir 'src/test/resources'
        }
    }
}


buildscript {
    project.ext {
        serenityVersion = '2.3.12'
    }
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath('net.serenity-bdd:serenity-gradle-plugin:' + serenityVersion)
        //classpath "net.serenity-bdd:serenity-gradle-plugin:$serenityVersion"
    }
}

sourceCompatibility = 17
targetCompatibility = 17

ext {
    slf4jVersion = '2.0.13'
    serenityCoreVersion = '4.1.20'
    junitVersion = '4.13.2'
    assertJVersion = '3.26.3'
    logbackVersion = '1.5.6'
    jacksonVersion = '2.17.2'
}

dependencies {
    testImplementation  "net.serenity-bdd:serenity-core:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-junit:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-screenplay:${serenityCoreVersion}",
            "junit:junit:${junitVersion}",
            "org.assertj:assertj-core:${assertJVersion}",
            "ch.qos.logback:logback-classic:${logbackVersion}",
            "org.slf4j:slf4j-api:${slf4jVersion}",
            "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
}

test {
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}
gradle.startParameter.continueOnFailure = true
test.finalizedBy(aggregate)


Please need your help to resolve this issue. I have tried everything possible to get through this issue. Please let me know if any  more files is needed.
