### ISSUE TITLE
reports were not generating when we execute testcases parallelly using serenity bdd junit cucumber

### ISSUE THREAD

**Issue by geetha051993** [serenity-bdd/serenity-core#3428]
can anyone help me,

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.health.bdd</groupId>
	<artifactId>ParallelTests_Serenity_Cucumber_JUnit5_Demo</artifactId>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>4.1.4</serenity.version>
		<serenity.cucumber.version>4.1.4</serenity.cucumber.version>
		<junit.platform.version>1.10.2</junit.platform.version>
		<junit-vintage-engine.version>5.10.2</junit-vintage-engine.version>
		<cucumber.version>7.16.1</cucumber.version>
		<maven.compiler.plugin.version>3.11.0</maven.compiler.plugin.version>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<maven.surefire.plugin.version>3.2.1</maven.surefire.plugin.version>
		<maven.failsafe.plugin.version>3.2.1</maven.failsafe.plugin.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit5</artifactId>
			<version>${serenity.version}</version>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit-platform-engine</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite</artifactId>
			<version>${junit.platform.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.ibm.icu</groupId>
			<artifactId>icu4j</artifactId>
			<version>74.2</version>
		</dependency>

		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<version>${junit-vintage-engine.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.24.2</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
		</dependency>
		

		
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>5.1.1</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.18.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>4.0.0-alpha-2</version>
		</dependency>
		

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-api</artifactId>
			<version>4.18.1</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20180130</version>
		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>4.4.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.4</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>31.0.1-jre</version>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>3.3</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.6.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-csv</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.4</version>
		</dependency>
		
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy</artifactId>
			<version>3.0.19</version>
		</dependency>

		
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>3.0.19</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>json-path</artifactId>

			<version>5.3.2</version>

		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>xml-path</artifactId>

			<version>5.3.2</version>

		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>json-schema-validator</artifactId>

			<version>5.3.2</version>

		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.42</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>6.1.0.jre8</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>7.13.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.17.2</version>
		</dependency>
		
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.10.1</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
		
		
		

		
		<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber7-adapter</artifactId>
			<version>1.14.0</version>
		</dependency>

		
		

		
		
		
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.14</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.24</version>
			<scope>provided</scope>
		</dependency>
		
		
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>3.0.1</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox-io</artifactId>
			<version>3.0.1</version>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-devtools-v120</artifactId>
			<version>4.16.1</version>
		</dependency>

		
		<dependency>
			<groupId>net.sourceforge.tess4j</groupId>
			<artifactId>tess4j</artifactId>
			<version>5.10.0</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>fontbox</artifactId>
			<version>3.0.1</version>
		</dependency>
		

		<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extent-pdf-report</artifactId>
			<version>2.12.0</version>
		</dependency>

		

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire.plugin.version}</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>${maven.failsafe.plugin.version}</version>
				<configuration>
					<includes>
						<include>**/*.java</include>
						<include>**/*Test.java</include>
						<include>**/*TestSuite.java</include>
						<include>**/Test*.java</include>
						<include>**/When*.java</include>
						<include>**/*CucumberTestSuite.java</include>
					</includes>
					<systemPropertyVariables>
						<webdriver.base.url>${webdriver.base.url}</webdriver.base.url>
					</systemPropertyVariables>
					<parallel>methods</parallel>
					
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.plugin.version}</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<configuration>
					<tags>${tags}</tags>
				</configuration>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>3.3.0.603</version>
			</plugin>

			<plugin>
				<groupId>org.codehaus.gmaven</groupId>
				<artifactId>gmaven-plugin</artifactId>
				<version>1.4</version>
			</plugin>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>3.5.1</version>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<Export-Package>
							!io.restassured.path.xml.*,
							!io.restassured.path.json.*,
							!io.restassured.common.*,
							!io.restassured.internal.path.xml.*,
							!io.restassured.internal.path.json.*,
							!io.restassured.internal.common.*,
							io.restassured.*
						</Export-Package>
						<Import-Package>
							groovy.*;version="3.0.19",
							org.codehaus.groovy.*;version="3.0.19",
							*
						</Import-Package>
					</instructions>
				</configuration>
			</plugin>

		</plugins>
	</build>
</project>

**Comment by wakaleo** [comment]
See https://github.com/serenity-bdd/screenplay-pattern-todomvc

**Comment by geetha051993** [comment]
Hi John, we are trying to achieve parallel execution to our existing framework itself since we have already developed 1000 testcases, where we are using serenity bdd cucumber junit with maven . and we were able to execute testcases parallelley(went through one of your video in youtube), but now reports was not generating , and it will generate index.html file where we will be having only scenario name

**Comment by geetha051993** [comment]
@wakaleo i have tried the pom.xml which you have provided but still same issue getting index.html like below
![img](https://github.com/serenity-bdd/serenity-core/assets/157007680/59fa5edf-93c8-4140-89ee-1d19847dfc02)

**Comment by wakaleo** [comment]
This report shows the tests being executed in parallel - what behaviour are you seeing?

**Comment by geetha051993** [comment]
it was executing parallelly but we are expecting the below report format
![new1](https://github.com/serenity-bdd/serenity-core/assets/157007680/0d2d6444-1849-4762-907f-be6d1ef064ff)

**Comment by wakaleo** [comment]
I don't know what that report is. If you look in target/site/serenity/index.html you should find the Serenity BDD reports.

**Comment by geetha051993** [comment]
oh ok, in this target/site/serenity/index.html path we are not getting index.html file

**Comment by wakaleo** [comment]
If the index.html file isn't being generated it could be some project-specific issue. If you can't figure it out we can help you with project-specific issues as part of a commercial support package (https://www.serenitydojo.academy/serenity-bdd-support-packages).

**Comment by geetha051993** [comment]
ok, thank you. one last question i have imported the project from the shared branch and executed there also same issue, i didn't see serenity report

![image](https://github.com/serenity-bdd/serenity-core/assets/157007680/4389bcf3-7f30-4f5a-98a1-c48a4f493b30)

![image](https://github.com/serenity-bdd/serenity-core/assets/157007680/22ce78ab-4fb9-400c-be01-1af2018cea9f)


under test-results index.html was there but not proper which i have shared already

**Comment by wakaleo** [comment]
Did you run "mvn verify" or "mvn serenity:aggregate"? to generate the reports?

**Comment by geetha051993** [comment]
![image](https://github.com/serenity-bdd/serenity-core/assets/157007680/fbf7a433-1de3-47f4-b331-8f6fa3cf0f70)

**Comment by wakaleo** [comment]
You need to run mvn serenity:aggregate to generate the reports

**Comment by geetha051993** [comment]
@wakaleo  Thank you it's worked for me, can we execute same in jenkins as well(parallel execution)

**Comment by wakaleo** [comment]
Yes you can, but on Jenkins just run mvn verify and the reports will be generated automatically.

**Comment by geetha051993** [comment]
@wakaleo Thank you so much

**Comment by geetha051993** [comment]
@wakaleo  :reports were generating in jenkins as well but parallel execution was not happening in jenkins, testcases are executing one by one .

![image](https://github.com/serenity-bdd/serenity-core/assets/157007680/26fc071b-4473-4175-b38b-b7f3286a203d)


do i have to pass any extra parameters

**Comment by wakaleo** [comment]
No, no extra parameters are required. The configuration is done in the junit-platform.properties configuration file.

**Comment by geetha051993** [comment]
![image](https://github.com/serenity-bdd/serenity-core/assets/157007680/6235bd52-975c-4519-a585-46f67c37a4e4)


yes i have done that
