### ISSUE TITLE
serenity report was not coming properly for parallel execution

### ISSUE THREAD

**Issue by geetha051993** [serenity-bdd/serenity-core#3430]
when we are executing testcases parallelly using serenity, serenity report was displaying wrong timings.

![image](https://github.com/serenity-bdd/serenity-core/assets/157007680/72dd05ec-49b2-4e82-9536-c7c38ae16b94)

Thanks in Advance

**Comment by geetha051993** [comment]
can anyone please help me on this issue

Thanks in Advance

**Comment by wakaleo** [comment]
Can you try with 4.1.6 and make sure you run mvn clean verify?

**Comment by geetha051993** [comment]
means serenity-core  version 4.1.6?

**Comment by wakaleo** [comment]
Yes

**Comment by geetha051993** [comment]
but iam seeing latest version is 4.1.4
![image](https://github.com/serenity-bdd/serenity-core/assets/157007680/ed872dd3-1607-4609-9bba-e8405983db2e)

**Comment by wakaleo** [comment]
mvnrepository.com is slow to update. See https://central.sonatype.com/artifact/net.serenity-bdd/serenity-core

**Comment by geetha051993** [comment]
Thank you @wakaleo report was generating , but iam getting this error  [INFO] GENERATING REPORTS FOR: C:\ProgramData\Jenkins\.jenkins\workspace\GeethaP14_WorkItem
21:31:00 java.nio.charset.UnmappableCharacterException: Input length = 1
21:31:00 	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:275)
21:31:00 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
21:31:00 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
21:31:00 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
21:31:00 	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
21:31:00 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
21:31:00 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
21:31:00 	at java.base/java.nio.file.Files.readAllLines(Files.java:3415)
21:31:00 	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:2665)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.readLocaleFromFeatureFile(FileSystemRequirementsTagProvider.java:679)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.loadFromFeatureFile(FileSystemRequirementsTagProvider.java:671)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.readRequirementsFromStoryOrFeatureFile(FileSystemRequirementsTagProvider.java:611)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
21:31:00 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
21:31:00 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
21:31:00 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
21:31:00 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:160)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.readChildrenFrom(FileSystemRequirementsTagProvider.java:822)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.requirementFromDirectoryName(FileSystemRequirementsTagProvider.java:701)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.readRequirementFrom(FileSystemRequirementsTagProvider.java:589)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
21:31:00 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
21:31:00 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
21:31:00 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
21:31:00 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:160)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.readChildrenFrom(FileSystemRequirementsTagProvider.java:822)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.requirementFromDirectoryName(FileSystemRequirementsTagProvider.java:701)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.readRequirementFrom(FileSystemRequirementsTagProvider.java:589)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
21:31:00 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
21:31:00 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
21:31:00 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
21:31:00 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:160)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.readChildrenFrom(FileSystemRequirementsTagProvider.java:822)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.requirementFromDirectoryName(FileSystemRequirementsTagProvider.java:701)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.readRequirementFrom(FileSystemRequirementsTagProvider.java:589)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
21:31:00 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
21:31:00 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
21:31:00 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
21:31:00 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
21:31:00 	at net.thucydides.model.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:160)
21:31:00 	at net.thucydides.model.requirements.RequirementsProvided.asStream(RequirementsProvided.java:30)
21:31:00 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
21:31:00 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
21:31:00 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
21:31:00 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
21:31:00 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
21:31:00 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
21:31:00 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
21:31:00 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
21:31:00 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
21:31:00 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
21:31:00 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
21:31:00 	at net.thucydides.model.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:43)
21:31:00 	at net.thucydides.model.reports.TestOutcomes.withRequirementsTags(TestOutcomes.java:629)
21:31:00 	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.loadTestOutcomesFrom(HtmlAggregateStoryReporter.java:279)
21:31:00 	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
21:31:00 	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:274)
21:31:00 	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:212)
21:31:00 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
21:31:00 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
21:31:00 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
21:31:00 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
21:31:00 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
21:31:00 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
21:31:00 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
21:31:00 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
21:31:00 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
21:31:00 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
21:31:00 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
21:31:00 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
21:31:00 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
21:31:00 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
21:31:00 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:31:00 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
21:31:00 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:31:00 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
21:31:00 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
21:31:00 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
21:31:00 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
21:31:00 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
21:31:00 [INFO] GENERATING REPORTS USING 16 THREADS
21:31:07 [INFO] GENERATING SUMMARY REPORTS...
21:31:08 [INFO] GENERATING REQUIREMENTS REPORTS...
21:31:10 [INFO] GENERATING RESULT REPORTS...
21:31:11 [INFO] GENERATING ERROR REPORTS...
21:31:11 [INFO] Test results for 11 tests generated in 10.9 secs in directory: file:/C:/ProgramData/Jenkins/.jenkins/workspace/GeethaP14_WorkItem/target/site/serenity/
21:31:11 [INFO] ------------------------------------------------
21:31:11 [INFO] | SERENITY TESTS:               | ERROR
21:31:11 [INFO] ------------------------------------------------
21:31:11 [INFO] | Test scenarios executed       | 11
21:31:11 [INFO] | Total Test cases executed     | 11
21:31:11 [INFO] | Tests passed                  | 7
21:31:11 [INFO] | Tests failed                  | 2
21:31:11 [INFO] | Tests with errors             | 2
21:31:11 [INFO] | Tests compromised             | 0
21:31:11 [INFO] | Tests aborted                 | 0
21:31:11 [INFO] | Tests pending                 | 0
21:31:11 [INFO] | Tests ignored/skipped         | 0
21:31:11 [INFO] ------------------------------- | --------------
21:31:11 [INFO] | Total Duration| 1h 32m 50s
21:31:11 [INFO] | Fastest test took| 6m 28s
21:31:11 [INFO] | Slowest test took| 9m 12s
21:31:11 [INFO] ------------------------------------------------
21:31:11 [INFO] 
21:31:11 [INFO] SERENITY REPORTS
21:31:11 [INFO]   - Full Report: file:///C:/ProgramData/Jenkins/.jenkins/workspace/GeethaP14_WorkItem/target/site/serenity/index.html
21:31:11 [INFO] 
21:31:11 [INFO] --- maven-failsafe-plugin:3.2.5:verify (default) @ ParallelTests_Serenity_Cucumber_JUnit5_Demo ---
21:31:11 [INFO] ------------------------------------------------------------------------
21:31:11 [INFO] BUILD FAILURE
21:31:11 [INFO] ------------------------------------------------------------------------
21:31:11 [INFO] Total time:  10:55 min
21:31:11 [INFO] Finished at: 2024-04-03T21:31:11+05:30
21:31:11 [INFO] ------------------------------------------------------------------------
21:31:11 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.2.5:verify (default) on project ParallelTests_Serenity_Cucumber_JUnit5_Demo: 
21:31:11 [ERROR] 
21:31:11 [ERROR] Please refer to C:\ProgramData\Jenkins\.jenkins\workspace\GeethaP14_WorkItem\target\failsafe-reports for the individual test results.
21:31:11 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
21:31:11 [ERROR] -> [Help 1]
21:31:11 [ERROR] 
21:31:11 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
21:31:11 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
21:31:11 [ERROR] 
21:31:11 [ERROR] For more information about the errors and possible solutions, please read the following articles:

**Comment by wakaleo** [comment]
That's just a warning but it means there is something wrong or odd with one of your feature files.

**Comment by geetha051993** [comment]
ok, Thank you @wakaleo , is there a way that we can pass @tags to run parallel execution using serenity

**Comment by wakaleo** [comment]
Yes, please refer to the Cucumber and JUnit 5 documentation for that.

**Comment by geetha051993** [comment]
ok, i will check that Thank you.

**Comment by geetha051993** [comment]
Hi @wakaleo  still total execution time was coming wrongly, can you please help me on this.

![image](https://github.com/serenity-bdd/serenity-core/assets/157007680/d701fff2-1e2b-4a7d-82fc-07db9114d1bf)

Thanks in Advance

**Comment by wakaleo** [comment]
Total execution time is the total time of all tests.
