### ISSUE TITLE
Does Serenity have the possibility to rerun failed tests?

### ISSUE THREAD

**Issue by Darenth** [serenity-bdd/serenity-core#3434]
### What happened?

I'm looking for information does Serenity have the possibility to rerun failed tests in the documentation, and there is no information about that. Does it mean that this feature is not out of the box of Serenity and have to be configured from junit5 or cucumber perspective?

### Serenity BDD version

4.0.29

### JDK version

11

### How to reproduce the bug.

no option I as see

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by globalworming** [comment]
not sure how it works with cucumber.. but with plain junit it should work by configuring the surefire/failsave plugins https://maven.apache.org/surefire/maven-failsafe-plugin/examples/rerun-failing-tests.html

**Comment by globalworming** [comment]
looks like it works just like that with cucumber as well https://github.com/serenity-bdd/serenity-core/issues/2136#issue-642490447

**Comment by Darenth** [comment]
Thanks a lot @globalworming  for your response! I tried #2136  already, Serenity reruns the failed test, but the report contains only the first result (failed). I tried it for versions 4.0.19 and 4.1.6 (the latest). Is this behaviour expected?

**Comment by globalworming** [comment]
yes, see also https://github.com/serenity-bdd/serenity-core/issues/1194
