### ISSUE TITLE
Not able to configure screen height and width for chrome browser in serenity.properties file

### ISSUE THREAD

**Issue by PritiKumari95** [serenity-bdd/serenity-core#3436]
### What happened?

Not able to configure screen height and width for chrome browser in serenity.properties file, we tried to set below configuration but its working for firefox but not chrome
// To maximize
chrome.switches = --start-maximized

// To Resize
serenity.browser.width=981
serenity.browser.height=644

### What did you expect to happen?

Screen height and width shoul be adjusted as per the configuration

### Serenity BDD version

4.0.30

### JDK version

11

### How to reproduce the bug.

try setting below in serenity.properties file
serenity.browser.width=981
serenity.browser.height=644

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
`serenity.properties` is deprecated - use `serenity.conf` instead:

```
serenity {
  browser {
    width = 981
    height = 644
  }
  ...
```

**Comment by PritiKumari95** [comment]
As suggested i tried the above lines of code but we still don't see any changes, below is the code we are using to verify the size.
getDriver().manage().window().getSize()

**Comment by wakaleo** [comment]
Maybe you have some chrome options elsewhere that are overriding the properties? I can confirm that the configuration above works in normal circumstances.

**Comment by PritiKumari95** [comment]
i am usin --start-maximized in chrome options, does this has anything to do with the default size i am getting?

**Comment by wakaleo** [comment]
Yes, that will start the browser in maximized mode, overriding any browser size settings.

**Comment by wakaleo** [comment]
Closing presumed resolved
