### ISSUE TITLE
can't we use static variables for parallel execution in serenity framework

### ISSUE THREAD

**Issue by geetha051993** [serenity-bdd/serenity-core#3442]
when we are using static variables (Maps and list)  and executing test cases parallelly ,since we are using same static variables across all testcases, testcases were failing is there any way that we can handle this.

Thanks in Advance

**Comment by wakaleo** [comment]
Use ThreadLocals.

**Comment by geetha051993** [comment]
Thank you @wakaleo since iam new to this concept is there any particular  document we have to  refer this

**Comment by geetha051993** [comment]
thank you, 
you meant to say threadlocal with serenity session variables right?

**Comment by wakaleo** [comment]
Serenity session variables are thread safe (they use thread locals)

**Comment by geetha051993** [comment]
ok Thank you

**Comment by geetha051993** [comment]
Hi @wakaleo , i have tried Serenity session variables  didn't work for me, i was calling a feature line where i used to retrieve dynamic data and storing it in map using Serenity.setSessionVariable("color").to("dynamicdata");  and then calling the data by using Serenity.sessionVariableCalled("color"); , then after some feature line (we used to do some apllication navigations) then need to retrieve same data using Serenity.sessionVariableCalled("color");  now it's returning null, can you help me to resolve this issue.

Example:
When i capture and store data.
And navigating to some screens
Then i return captured data

Thanks in Advance

**Comment by wakaleo** [comment]
Are you calling these in the same scenario?

**Comment by geetha051993** [comment]
yes

**Comment by geetha051993** [comment]
yes scenario, but calling in different methods

**Comment by wakaleo** [comment]
That should work fine then. Here's an example:
```
    @Given("{actor} has a todo list containing {items}")
    public void that_James_has_an_empty_todo_list(Actor actor, List<String> items) {
        Serenity.setSessionVariable("todoItems").to(items);
        actor.wasAbleTo(Start.withATodoListContaining(items));
    }
    ...
    @Then("his/her todo list should contain {items}")
    public void todo_list_should_contain(List<String> expectedItems) {
        List<String> originalItems = Serenity.sessionVariableCalled("todoItems");
        assertThat(originalItems).isNotEmpty();

        theActorInTheSpotlight().should(seeThat(TheItems.displayed(), equalTo(expectedItems))
                .orComplainWith(MissingTodoItemsException.class, "Missing todos " + expectedItems));
    }
```

**Comment by geetha051993** [comment]
can we call  Serenity.setSessionVariable("todoItems").to(items); and  List<String> originalItems = Serenity.sessionVariableCalled("todoItems"); in page classes like below

A a=new A();
B b=new B();

@Given("{actor} has a todo list containing {items}")
    public void that_James_has_an_empty_todo_list(Actor actor, List<String> items) {
       a.storevalues(actor,items);
    }
    ...
    @Then("his/her todo list should contain {items}")
    public void todo_list_should_contain(List<String> expectedItems) {
        b.retrievevalues(expectedItems));
    }

page classs:

class A(){

public void storevalues(Actor actor, List<String> items){
Serenity.setSessionVariable("todoItems").to(items);
        actor.wasAbleTo(Start.withATodoListContaining(items));


}}

Class B(){

public void retrievevalues(List<String> expectedItems){
List<String> originalItems = Serenity.sessionVariableCalled("todoItems");
        assertThat(originalItems).isNotEmpty();

        theActorInTheSpotlight().should(seeThat(TheItems.displayed(), equalTo(expectedItems))
                .orComplainWith(MissingTodoItemsException.class, "Missing todos " + expectedItems));
}
}

**Comment by wakaleo** [comment]
Yes, it doesn't matter what class the methods are in as long as they are executed in the same thread.

**Comment by geetha051993** [comment]
is there any way we can check that they are executed in the same thread or not.  i am executing two testcases both are using same methods because of that testcases were failing, if i execute single testcase also capture data was not getting displayed. iam using java selenium

**Comment by wakaleo** [comment]
Are you trying to share data between test cases or within a single test case?

**Comment by geetha051993** [comment]
with in a single testcase only. 
actually  10  testcases  steps will be same . only few validations will differ so we are capturing data and storing it in static variables then we are using that data for validations.

Example:

Class A(){

public static Map<String, List<String>> agingDetailsforAppointment = new HashMap<String, List<String>>();

public void  capturedata(){
agingDetailsforAppointment.put("dynamic data");   // this data will change for every testcase

}

}

Class B(){

public void retrievevalues(){

agingDetailsforAppointment.get("id");  // every testcase we are capturing new data and validating here 

}}

same variables but independent testcases, capturing data in same testcase and validating data also in that testcase only

**Comment by wakaleo** [comment]
Either the Serenity session data or native ThreadLocals should work fine for that (I use it all the time) - if it is not, there may be an issue in your test logic.

**Comment by wakaleo** [comment]
Closing presumed answered
