### ISSUE TITLE
JUnit5: StepListener get wrongly SUCCESS when an Exception is thrown in test

### ISSUE THREAD

**Issue by zeners** [serenity-bdd/serenity-core#3443]
### What happened?

[`net.serenitybdd.junit5.SerenityTestExecutionListener#testFinished`](https://github.com/serenity-bdd/serenity-core/blob/main/serenity-junit5/src/main/java/net/serenitybdd/junit5/SerenityTestExecutionListener.java#L361) missed to call `updateResultsUsingTestExecutionResult()` with `TestExecutionResult.Status.FAILED` because `result.isLessSevereThan(TestResult.FAILURE)` has to be negated or flipped.

### What did you expect to happen?

get the correct FAILED result in `net.thucydides.model.steps.StepListener#testFinished(net.thucydides.model.domain.TestOutcome)` if an exception is thrown inside a test, but outside a step

### Serenity BDD version

4.0.12

### JDK version

17

### Execution environment

caused by net.serenity-bdd:serenity-junit5:4.0.12

### How to reproduce the bug.

- create a junit5 test with `throw new RuntimeException("Test-Error");`
- do one of
  - create a net.thucydides.model.steps.StepListener service and try to log result.getResult() inside `void testFinished(TestOutcome result)` 
  - set a breakpoint in SerenityTestExecutionListener#testFinished
  - register `net.thucydides.core.steps.Listeners#getLoggingListener()` (eg with `StepEventBus.getEventBus().registerListener(getLoggingListener())`)
- run the test

test failed, but the Listener got an result SUCCESS

this can be seen
- inside `testFinished(TestOutcome result)` with `result.getResult() == TestResult.SUCCESS`
- that `SerenityTestExecutionListener#testFinished` missed to call `updateResultsUsingTestExecutionResult()`
- that the loggingListener prints `Test Passed`

please note that the method `void testFailed(TestOutcome testOutcome, Throwable cause)` is correctly called

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by wakaleo** [comment]
I would need to check but I believe if a test fails, the test finished listener is not meant to be triggered.

**Comment by wakaleo** [comment]
(Also 4.0.12 is an old version, have you tried with the latest versions)

**Comment by zeners** [comment]
- the test finished is called, if i call the missed routine inside debugger
- the spotted line is unchanged in current master

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by zeners** [comment]
will take some time, my dev environment is outdated

**Comment by zeners** [comment]
i have troubles to reproduce it with current version 4.1.6

**Comment by zeners** [comment]
found:
4.0.12 > `TestResult.SUCCESS.isLessSevereThan(TestResult.FAILURE) `return false
4.1.6 > `TestResult.SUCCESS.isLessSevereThan(TestResult.FAILURE)` return true (correct)

**Comment by zeners** [comment]
duplicate of #3299
