### ISSUE TITLE
jira.url property breaks links to scenario details in reports.

### ISSUE THREAD

**Issue by dmitriy-grablyov** [serenity-bdd/serenity-core#346]
This problem is observed when using serenity-core with serenity-jbehave  and writing BDD stories

First of all there is an issue that reporter tries to mark as ticket number Everything matching jira url pattern.
For example, even if I set jira.project=OR it will parse as ticket key both OR-17 and TC-OR-1721-1 (last one we use just as testcase code which is nothing common with issue tracking).

And the problem comes with the usage of jira.url property
Let's say we have a scenario named "TC-OR-1010-1 Do something" which is linked by issue metatag to ticket OR-1010. In this case in reports the scenario will be described as:
`
<td class="SUCCESS-text sorting_1">
                                <a href="5330538ab89c976e1a23ff87461d24005cac76462763e0d5ca39c58f526edf2b.html" class="ellipsis" title="">
                                    TC-OR-1010-1 Do something (OR-1010, TC-OR-1010-1)
                                </a>
                            </td>
`

Everything here is just a text and this text is clickable since it is whole under a tag

if I specify jira.url parameter - it will try to make every key a link to jira and html goes this way:

`
<td class="SUCCESS-text sorting_1">
                                <a href="214eb7b738ec5c9289c043e797caeb60cf1ae342e0275ee14cbf87230a95afd9.html" class="ellipsis" title="">
                                    </a><a target="_blank" href="https://jira.net/browse/TC-OR-1010-1">TC-OR-1010-1</a> Do something (<a target="_blank" href="https://jira.net/browse/OR-1010">OR-1010</a>, <a target="_blank" href="https://jira.net/browse/TC-OR-1010-1">TC-OR-1010-1</a>)
                            </td>
`

In this case text is no more clickable and scenario details are no more accessible because original a tag is closed immediately without any text I can click on.

To reproduce this issue just create a dummy scenario containing some jira-like key at the beginning of scenario name. Execute this test setting some valid url for jira.url in serenity.properties

**Comment by YamStranger** [comment]
@dmitriy-grablyov 

Thanks for this issue!!
