### ISSUE TITLE
TakeScreenShot is calling wrong implementation. 

### ISSUE THREAD

**Issue by SrivaniChennupati** [serenity-bdd/serenity-core#3464]
### What happened?

Serenity 3 version: 

In StepEventBus of this version when we call `takeScreenshot`,  method call is happening as follows 
```
   public void takeScreenshot() {
        getBaseStepListener().takeScreenshot();
    }
```

Serenity 4 version: 

In StepEventBus of newer version, listener is calling a different method, which is failing to attach any screenshots 
```
public void takeScreenshot() {
        if (!isDryRun()) {
            getBaseStepListener().notifyUIError();
        }
    }
```

### Serenity BDD version

4.1.6

### JDK version

11

### How to reproduce the bug.

1. Whenever I call Serenity.takeScreenshot() at any point in the step level, it is calling takeScreenshot() method but it is checking for the UI errors , not taking the screenshots and not attaching result to TestOutcome Object within the testFinished() method of the BaseTestlistener class ( Which is a custom listener class that implements StepListener) 

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
Fixed in 4.1.12
