### ISSUE TITLE
@FindBy annotation is not being initialized 

### ISSUE THREAD

**Issue by SrivaniChennupati** [serenity-bdd/serenity-core#3466]
from 4.1.8 , @findBy annotation is not getting initialized , Here is an example 

I have `LaunchPage.java` where i have initialized properties `username` and `password`. 

![image](https://github.com/serenity-bdd/serenity-core/assets/63605884/40df0a8e-894d-4933-a3a3-bca171aaf75a)

`LaunchPage.java` is referenced like this from base class as follows 

![image](https://github.com/serenity-bdd/serenity-core/assets/63605884/7351fde0-31ff-490f-ab0e-a6f6cbb7cc27)
 
However when i try to make actions on the property, its getting failed as `username` is getting null reference error and when i see that page during initialization i can see the following variables, and in here username and password are null. 
![image](https://github.com/serenity-bdd/serenity-core/assets/63605884/7c7cf8df-51f4-4e9b-9068-87dfa7044775)

**Comment by wakaleo** [comment]
I would generally advise against using @FindBy, but I'm not sure why it wouldn't get initialised. Have a look in the PageObject class to see if you can see any reason why it might be getting skipped.

**Comment by SrivaniChennupati** [comment]
I tried with By locator Strategy and its working. However for `FindBy`, even if driver is null, framework is getting driver from  serenity , so I don't see any issue there and I will try to debug more and see to pin point the issue 

Thanks for the help @wakaleo

**Comment by wakaleo** [comment]
Closed presumed resolved.

**Comment by Abhishek468** [comment]
@SrivaniChennupati  I've resolved this issue and already raised a PR as well, awaiting to be merged. You can take a look at it to see what changes I've made.https://github.com/serenity-bdd/serenity-core/pull/3625

**Comment by Abhishek468** [comment]
> I tried with By locator Strategy and its working. However for `FindBy`, even if driver is null, framework is getting driver from serenity , so I don't see any issue there and I will try to debug more and see to pin point the issue
> 
> Thanks for the help [@wakaleo](https://github.com/wakaleo)

Another way is to call the super constructor explicit in your page object class.
