### ISSUE TITLE
How to customize the serenity Report with Gradle

### ISSUE THREAD

**Issue by Yeshi2021** [serenity-bdd/serenity-core#3472]
### What's the Problem You're Trying to Solve?

I am looking to achieve on how to customize serenity report using gradle, is there any sample project?
using serenity 3.7...
gradle project

### Proposed Solution

n/a

### Alternative Solutions

n/a

### Implementation Support

- [ ] Contribute the feature myself (with guidance from the Serenity BDD team)
- [ ] Hire the Serenity BDD team for implementation
- [ ] Add it to the Serenity BDD backlog and wait for community contribution

**Comment by wakaleo** [comment]
See https://github.com/serenity-bdd/screenplay-pattern-todomvc.git

**Comment by Yeshi2021** [comment]
@wakaleo thanks for your support and quick response.
