### ISSUE TITLE
ImplicitWait set to 0 after looking for element that doesn't exist in page

### ISSUE THREAD

**Issue by Lingweezy** [serenity-bdd/serenity-core#3477]
### What happened?

Implicit wait set to zero after searching for an element that was not found on the page. 
Serenity code calls net.serenitybdd.core.pages.RenderedPageObjectView.findAllWithOptionalWait(By bySelector, FindAllWaitOptions waitForOptions) which explicitly calls setImplicitTimeout with a value of Zero. 
At the end of the try block there is code to call resetImplicitTimeout but if an exception happens before that the reset is never called. 

### What did you expect to happen?

That the ImplicitWait would remain as specified by the configuration. 

net.serenitybdd.core.pages.RenderedPageObjectView.findAllWithOptionalWait(By bySelector, FindAllWaitOptions waitForOptions) 
It would appear that the code this.pageObject.resetImplicitTimeout(); should be added to a new finally block so that no matter what happens in this method the ImplicitWait value is reset to the value that was defined on entering this method. 

### Serenity BDD version

4.1.0

### JDK version

Java17

### Execution environment

Happens on both Windows and Linux OSes and on both Chrome and Edge

### How to reproduce the bug.

Set the implicitlyWait property to 7000 in the serenity.conf file

try { 
  Target target = Target.the("More...").locatedBy("//button[contains(. , 'More')]");
  Boolean targetVisible = target.isVisibleFor(actor);
} catch (Excepton e) {
  e.printStackTrace();
}

Date start = new Date();
System.out.println("Start Time: " + start);
try {
  actor.attemptsTo(Click.on(target));
} finally {
   Date end = new Date();
   System.out.println("End Time: " + end);
   System.out.println("Duration ms: " + end-start);
}

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment]
Thanks for looking into this. Using a finally block sounds like a good approach - can you propose a PR and see if it works for you locally?

**Comment by Lingweezy** [comment]
Can't replicate the issue anymore, so we can close out this issue. If I can reproduce the issue I'll either reopen this one or raise a new issue.
