### ISSUE TITLE
Can't switch to iframes easy

### ISSUE THREAD

**Issue by chiupakabra** [serenity-bdd/serenity-core#35]
Could't find any easy way to switch to iframe in the page object

**Comment by mikezx6r** [comment]
Try:

    getDriver().switchTo().frame("frame name");

To switch to the main frame again, you can use:
    getDriver().switchTo().defaultContent();

These are Selenium functions, and getDriver() returns the Selenium driver in your PageObject.

**Comment by chiupakabra** [comment]
ok I will try that great thank you Mike

**Comment by Afez89** [comment]
how do i automate check for iframe to access content that i want when the iframe id keeps changing?

**Comment by wakaleo** [comment]
You will need to write custom code for your app to keep track of the iFrames or recheck each time.

**Comment by Afez89** [comment]
@wakaleo 
When i wrote this loop:
while(!searchFieldID.isCurrentlyVisible()) {
		System.out.println("i: "+i);
		i++;
		getDriver().switchTo().frame(i);
		}
sometimes to get the to the element that is in the iframe.
sometimes it works, sometimes does not, then throws error:
  [31mnet.serenitybdd. core.exceptions.SerenityManagedException: no such frame
        (Session info: chrome=63.0.3239.132)

but if i bash into a value like i=2 it works. why is this so?

**Comment by wakaleo** [comment]
This is more a question for https://serenity-bdd.rocket.chat, where more people could give their thoughts.

**Comment by sonet114882** [comment]
Hey john,
i am not able to switch the iframe ..... into my serenity project i have initialize driver.switchto.frame(ID) in my step library. when i run my main test it gives me null point exception . could u please help me out from that...
