### ISSUE TITLE
How to use org.openqa.selenium.support.events.EventFiringWebDriver with Serenity

### ISSUE THREAD

**Issue by gitgrimbo** [serenity-bdd/serenity-core#350]
Hi,

I want to be able to intercept certain WebDriver calls.

The [`org.openqa.selenium.support.events.EventFiringWebDriver`](https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/events/EventFiringWebDriver.html) class seems to be the appropriate class for this.

How can I get Serenity to use this class?

At the moment I have copied the `net.thucydides.core.webdriver.WebdriverInstanceFactory` source code and changed this class to wrap all drivers it creates with `org.openqa.selenium.support.events.EventFiringWebDriver`, but this is just a hack to get my code working and I imagine it wouldn't be the correct way (if such a way exists).

Cheers.

**Comment by YamStranger** [comment]
Hello @gitgrimbo. 

Unfortunately now it cant be done with configuration. 

Will mark this question as Enhansement - it will be great to implement configuration of rappers for managed web-driver instances

Thanks!

**Comment by NSnietol** [comment]
> Unfortunately now it cant be done with configuration.



@YamStranger  could you give us an example? we have to do that
