### ISSUE TITLE
The Build info entry is not clear enough

### ISSUE THREAD

**Issue by 1109471432** [serenity-bdd/serenity-core#3503]
### What's the Problem You're Trying to Solve?

The Build info entry is not clear enough

### Proposed Solution

Add text to build info link.

### Implementation Support

- [X] Contribute the feature myself (with guidance from the Serenity BDD team)
- [ ] Hire the Serenity BDD team for implementation
- [ ] Add it to the Serenity BDD backlog and wait for community contribution

**Comment by kaylezhangzhaoLin** [comment]
@wakaleo  [Can you help me to review this PR?](https://github.com/serenity-bdd/serenity-core/pull/3504). I will close the PR if you consider it terrible.
