### ISSUE TITLE
Test suite with parallel parameterized tests is executed sequentially

### ISSUE THREAD

**Issue by TKolesnikova** [serenity-bdd/serenity-core#351]
I am trying to run parallel parameterized Serenity tests using test suite.
1) I need to run the same test with different parameters simultaneously.

2) And I use test suite for defining the order of the tests. My tests are independent but I need to run them in the specific order (not always the same) to simulate business scenarios.  So Test1() should run with all the parameters concurrently, and Test2() should do the same but it should wait for myTest1() to complete with all parameters before executing.

My test classes look like that:

```
@RunWith(SerenityParameterizedRunner.class)
@Concurrent(threads="2")
public class MyTestClass1 {
    @TestData
    public static Collection<Object[]> testData() {
        return Arrays.asList(new Object[][] {
            {1}, {2}
        });
    }

    private int x;

    public MyTestClass(int x) {
        this.x = x
    }

    @Test
    public void Test1() {
        ...
    }
}
```

And it works fine if I do not use test suite class for running it. Each test is executed for each parameter value and it happens simultaneously.

But if I use test suite for running these tests:

```
@RunWith(Suite.class)
@SuiteClasses({ MyTestClass1.class, MyTestClass2.class })
public class AllTests { }
```

tests are run for each parameter but they are executed one after another (sequentially).

Is it possible to run test suite with parametrized tests that will be run concurrently? If not, then it would be a good feature to implement :)

Thanks!

**Comment by YamStranger** [comment]
@TKolesnikova Thanks for this examples!
