### ISSUE TITLE
Could not initialize class sun.awt.X11.XToolkit - failure with xvbf + chrome setup

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#353]
Hi,

Getting below error  while running test cases on Linux VM + xvbf + Chrome setup ( in docker container )

"[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP Maximize browser window
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STEP ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: Could not initialize class sun.awt.X11.XToolkit
load_WLInboxPage Exception Caughtorg.openqa.selenium.TimeoutException: Timed out after 30 seconds waiting for element to be clickable: By.xpath: //input[@value='Sign In']
Build info: version: '2.50.1', revision: 'd7fc91b29de65b790abb01f3ac5f7ea2191c88a7', time: '2016-01-29 11:11:26'
System info: host: 'wunderlist-qa', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-49-generic', java.version: '1.8.0_74'
Driver info: net.thucydides.core.webdriver.WebDriverFacade	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)	at com.wunderlist.steps.WL_ListFeature_EndUserSteps.load_WLInboxPage(WL_ListFeature_EndUserSteps.java:82)	at com.wunderlist.steps.WL_ListFeature_EndUserSteps$$EnhancerByCGLIB$$98b7b6e2.CGLIB$load_WLInboxPage$0(<generated>)	at com.wunderlist.steps.WL_ListFeature_EndUserSteps$$EnhancerByCGLIB$$98b7b6e2$$FastClassByCGLIB$$5e91e312.invoke(<generated>)	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:348)	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:333)	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:308)	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:130)	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:57)	at com.wunderlist.steps.WL_ListFeature_EndUserSteps$$EnhancerByCGLIB$$98b7b6e2.load_WLInboxPage(<generated>)	at com.wunderlist.storyTest.WL_PreferencesFeatureStoryTest.DeleteAccount(WL_PreferencesFeatureStoryTest.java:70)	at com.wunderlist.storyTest.WL_PreferencesFeatureStoryTest.IsUserLoggedIn(WL_PreferencesFeatureStoryTest.java:61)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:452)	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:54)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:346)	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:246)	at org.junit.runners.Suite.runChild(Suite.java:128)	at org.junit.runners.Suite.runChild(Suite.java:27)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)	at java.util.concurrent.FutureTask.run(FutureTask.java:266)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)	at java.lang.Thread.run(Thread.java:745)[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - FINISHING STEP
"

This works perfectly with Mac + Docker setup though

Please review

Thanks,
Vikram

**Comment by YamStranger** [comment]
Hello @vikramvi 

It seems that something wrong with webdriver configuration, could you try initialize webdirver without serenity BDD (just to be sure that it is possible to run Chrome at all)? 

Something as simple as it possible:
```
WebDriver driver = new ChromeDriver(); 
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS); 
driver.get("http://www.google.com"); 
```

Thanks!

**Comment by vikramvi** [comment]
@YamStranger  

I did below 

export DISPLAY=:99

and re-run test cases , the error has changed to 

"[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP Maximize browser window
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STEP ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: Could not initialize class sun.awt.X11.XToolkit
load_WLInboxPage Exception Caughtorg.openqa.selenium.TimeoutException:"

I think browser.maximize fails for headless chrome browser

**Comment by YamStranger** [comment]
@vikramvi source of this exception is selenium, execution of driver fails during some specific case on your environment. 

Serenity BDD did not use method `maximize` at all. 

Lets think in different direction... 
ChromeDriver can fail itself, did you have a change to check how chromedriver works without serenty bdd?  Something like: 

```
        WebDriver driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.get("http://www.google.com");
        WebElement element = driver.findElement(By.name("q"));
        element.sendKeys("ChromeDriver");
        element.submit();
```

**Comment by vikramvi** [comment]
@YamStranger  I tried above sample code and it is failing with below error

"TEST FAILED WITH ERROR: Google test
---------------------------------------------------------------------
[pool-1-thread-1] ERROR net.serenitybdd.core.Serenity - unknown error: Chrome failed to start: exited abnormally
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 90.084 sec <<< FAILURE! - in net.thucydides.showcase.junit.features.cart.AddItemsToCartTest
google_test(net.thucydides.showcase.junit.features.cart.AddItemsToCartTest)  Time elapsed: 60.151 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: 
unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.19.0-49-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.09 seconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'wunderlist-qa', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-49-generic', java.version: '1.8.0_74'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at net.thucydides.showcase.junit.features.cart.AddItemsToCartTest.google_test(AddItemsToCartTest.java:46)

Running net.thucydides.showcase.junit.features.petstore.AddAPetToThePetStoreTest
"

I have run the test cases in project https://github.com/vikramvi/junit-webtests-parallel-grid-docker-jenkins-debug/tree/master/junit-webtests

Please have a look

**Comment by vikramvi** [comment]
additional note above code works perfectly with Mac + Docker setup but only fails with Linux VM + Docker setup. I'm not getting what may be going wrong

**Comment by YamStranger** [comment]
Hello @vikramvi 

**It is not issue of Serenity BDD**, please close this issue:

I started selenium-grid hub using this command: 
```
java -jar selenium-server-standalone-2.52.0.jar -role hub
```
and selenium grid node with linux and chrome: 
```
java -jar selenium-server-standalone-2.52.0.jar -role webdriver -hub http://localhost:4444/grid/register -browser browserName="chrome",version=ANY,platform=LINUX,maxInstances=5
```
Here is screen shot of my console: 
![grid_console](https://cloud.githubusercontent.com/assets/1667699/13803456/6a688b86-eb4d-11e5-98d5-443912a823eb.png)

and executed tests from your repository based on provided command: 
```
mvn clean verify -Dskip.parallel=false -DskipITs -Dwebdriver.remote.url=http://localhost:4444/wd/hub -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.os=LINUX
```
results as usual are awesome: 

![results](https://cloud.githubusercontent.com/assets/1667699/13803481/9cea30dc-eb4d-11e5-9624-3e5786ccc93b.png)

**make sure** that you machine can run all chrome in parallel (as default behaving for such configuration), in my situation such test "eat" 2+GB of ram. **OR** try use phantomjs instead of chome. 

Thanks

**Comment by vikramvi** [comment]
@YamStranger  Good morning and thanks a ton for your efforts in debugging.

I'm closing as per your clarifications. I'll continue to investigate issue and update this ticket for others benefit.

Regards,
Vikram

**Comment by vikramvi** [comment]
@YamStranger  At last found the root cause , below method was failing only on Linux VM + Docker and working perfectly with Mac + Docker setup

Both has exactly same docker setup and chrome driver version.

Thanks for your patience and help

public void maximizeBrowserWindow(){
		try{
			Toolkit toolkit = Toolkit.getDefaultToolkit();
			
			Dimension screenResolution = new Dimension((int) toolkit.getScreenSize().getWidth(), (int) toolkit.getScreenSize().getHeight());
			
			getDriver().manage().window().setSize(screenResolution);
		}catch(Exception e){
			e.printStackTrace();
		}
	}

**Comment by YamStranger** [comment]
@vikramvi thanks a lot for sharing your experience!!!
