### ISSUE TITLE
NullPointerException in waitThenRetry() logic when the property 'webdriver.creation.retry.count' is set to 0

### ISSUE THREAD

**Issue by aroras25** [serenity-bdd/serenity-core#3556]
### What happened?

**Issue** : Null Pointer Exception is observed when we set the property 'webdriver.creation.retry.count' to 0.

**Error Screenshot** 
![image](https://github.com/user-attachments/assets/253616c3-6cdd-4625-9a57-58fecce38e73)

**Root Cause :** 

**Class File** : net.thucydides.core.webdriver.WebDriverFactory
**Method** : waitThenRetry()

In case of failure in establishing the driver instance, when the code calls the waitThenRetry method for the first time, it passes NULL value for the Exception argument.

While for the successive retries , we pass the exception parameter. 

Hence , we get the null pointer issue only when we set the property to 0. And the issue is not observed if we pass the retry property >0.

Code Snippet : 
![image](https://github.com/user-attachments/assets/4db7752e-9e55-4080-90f2-0ac1aeaa8f20)

### What did you expect to happen?

The logic should not provide null pointer exception. 
When this.quit() method is called, we should pass the exception to report the same

### Serenity BDD version

4.1.14

### JDK version

11

### Execution environment

Windows
Chrome

### How to reproduce the bug.

Set the property 'webdriver.creation.retry.count' to 0. 
Execute the test. 
Null Pointer Exception is observed

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
Can you propose a PR to address this please?

**Comment by wakaleo** [comment]
Fixed in 4.2.6 I believe.
