### ISSUE TITLE
waitForTextToAppear failing - waits for just 44 millliseconds

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#357]
**Serenity Version:**

<serenity.version>1.1.29-rc.1</serenity.version>

**Project to reproduce : **

https://github.com/serenity-bdd/serenity-demos/tree/master/junit-webtests

**Error Log:**

org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=48.0.2564.116)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 44 milliseconds

net.thucydides.showcase.junit.pages.SearchResultsPage.selectListing(SearchResultsPage.java:53)
	at net.thucydides.showcase.junit.steps.serenity.BuyerSteps.selects_listing(BuyerSteps.java:51)
	at net.thucydides.showcase.junit.features.cart.AddItemsToCartTest.add_item_to_cart(AddItemsToCartTest.java:30)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by YamStranger** [comment]
Hello @vikramvi. 
This project contains some fails (and report should contains some errors as well).
If you expect "green report" - you can use this project: https://github.com/serenity-bdd/serenity-test-projects/tree/master/web-todomvc-tests or just exclude some test from those example project. 

In my logs I can't find any "org.openqa.selenium.StaleElementReferenceException", so it is possible that we use different versions of chrome-driver, sereniy-core and so on:
please execute command `mvn dependency:tree >dependency.tree.txt` and attach here output. It seems that some version in pom/gradle was not updated OR *old* version of chome driver is used: https://sites.google.com/a/chromium.org/chromedriver/. 

Here is my updated [pom.txt](https://github.com/serenity-bdd/serenity-core/files/171928/pom.txt), and dependency tree: [dependency.tree.txt](https://github.com/serenity-bdd/serenity-core/files/171921/dependency.tree.txt)

Result of build : 
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:42 min
[INFO] Finished at: 2016-03-14T14:29:22+02:00
[INFO] Final Memory: 40M/648M
```

and report with errors (they are expected):

![before](https://cloud.githubusercontent.com/assets/1667699/13744664/eab5c9f0-e9f1-11e5-8b61-ccccf2b19583.png)

**Comment by vikramvi** [comment]
@YamStranger  please find below output from mvn dependency:tree >dependency.tree.txt attached

I'm modifying failures and submit PR this week

[dependency.tree.txt](https://github.com/serenity-bdd/serenity-core/files/172069/dependency.tree.txt)

**Comment by YamStranger** [comment]
@vikramvi that version of chomedriver do you use?

**Comment by vikramvi** [comment]
@YamStranger  sorry I was on current - 2 version of chrome driver. 

With 2.21 version it works perfectly.

**Comment by vikramvi** [comment]
@YamStranger  can you please clarify couple of queries related to chrome driver

1. How do you get notified when newer version is released ?

2. how to find version of chrome driver from command line ?  Today I checked the download date in file info

**Comment by YamStranger** [comment]
@vikramvi, about your questions: 

>1) How do you get notified when newer version is released ?

I am not notified - when we updating selenium core to latest - I update chromedriver on my pc as well. Its quite often problem when new selenium version does'n work with old chromedirver

_____________

> 2)how to find version of chrome driver from command line ? Today I checked the download date in file info

if chromedirver available in class path then when you execute 
```  chromedriver ```
It will return something like: 
```Starting ChromeDriver (v2.9.248304) on port 9515```
here is version of chrome driver

**Comment by vikramvi** [comment]
Thanks @YamStranger  for this useful tips
