### ISSUE TITLE
@Findby doesn't work for xpath, className, linkText ....

### ISSUE THREAD

**Issue by Vovanchik** [serenity-bdd/serenity-core#36]
Hello,

I am using serenity 1.0.38, JUnit runner and browsers FF/Chrome.

I discovered that @Findby with xpath, className, linkText and may be others doesn't work. Element always has value "undefined", what is really weired.

Works well only with name and id.

As library I am using:
import net.serenitybdd.core.annotations.findby.FindBy;

Previously I used thucydides 0.9.275 where everything works as expected.

What is wrong or I am doing wrong?

Thank you.

**Comment by wakaleo** [comment]
Hi Volodymyr,

@FindBy should work fine with all of those options and more - could you
give me a code snippet that isn't working?

Thanks

John.

On 19 March 2015 at 06:54, Volodymyr Koval <notifications@github.com> wrote:

> Hello,
>
> I am using serenity 1.0.38, JUnit runner and browsers FF/Chrome.
>
> I discovered that @Findby <https://github.com/Findby> with xpath,
> className, linkText and may be others doesn't work. Element always has
> value "undefined", what is really weired.
>
> Works well only with name and id.
>
> As library I am using:
> import net.serenitybdd.core.annotations.findby.FindBy;
>
> Previously I used thucydides 0.9.275 where everything works as expected.
>
> What is wrong or I am doing wrong?
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/36>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by Vovanchik** [comment]
Hello John,

Will prepare small part of the project and send you soon.

Thank's for quick response.

*Volodymyr Koval*

**Comment by Vovanchik** [comment]
Hello John,

After deep investigation of my test framework I discovered difference
between Thucydides and Serenity.

In general what I discovered:
1. During Test execution when element on the page is not found than
PageObject throw exception.
2. After that Execution of Test case continuous. And here is the difference:

   - Thucydides - marks next step as SKIPPED and continue execution until
   first action from PageObject/WebDriver occurs, than throw *exception*
   and go to next step.
   - Serenity - marks next step as SKIPPED and continue execution until
   first action from PageObject/WebDriver occurs, and throw *no exception*
   (debuger show that element undefined) and go to next step.

As result some of my TCs goes to unfinished loop, because I have method
which catch exception, something like this:


@Step
public void removeAllRecords(String item){
    page.openHistory(item);
    page.deleteAllRecords();
}

...

public void deleteAllRecords() {
    HistoryPopup popup = new HistoryPopup(getDriver());
    popup.selectPopup();
    while (popup.deleteRecord()) {
        popup.selectPopup();
    }
}

...

public class ABasePage extends PageObject {

private String deleteLink = "//*[contains(@id,'delete')]";
...
*This method always return true in Serenity if TC fails on previous step.*

public boolean deleteRecord() {
    try {
        element(findBy(deleteLink)).click();
        waitForPageLoaded();
        return true;
    } catch (Exception e) {
        return false;
    }
}
...
}

Everything else work's well. So, to resolve this problem I need to
re-write my method (and similar method), but my question was: is it
something that was re-designed in Serenity?

Thank's for you help.


*Volodymyr Koval*

**Comment by wakaleo** [comment]
Hi Volodymyr,

Yes, this was intentionally redesigned in Serenity for technical reasons. As a general rule, it is probably not a great idea to use a try/catch as part of the expected behaviour of a test - can you use some of the Serenity and Selenium waitFor capabilities to do this?

**Comment by Vovanchik** [comment]
Yes John, I already re-designed major methods in my framework.

Thank's for your answer.

*Volodymyr Koval*
