### ISSUE TITLE
Unable to do Appium Touchaction in Serenity

### ISSUE THREAD

**Issue by selvavaithi** [serenity-bdd/serenity-core#362]
Hi,
Im using Appium+Serernity+JBehave for an Android automation. When trying for 
TouchAction actions = new TouchAction((MobileDriver) getDriver()); in an PageObject class the following error is being shown. 

My Environment is
Serenity-core: 1.1.29-rc.1
Serenity-jbehave: 1.8.0
Win: 8.1 pro
Eclipse: Version: Mars.2 Release (4.5.2)
Appium version: 1.4.16.1 (Ophiuchus)

(java.lang.ClassCastException: net.thucydides.core.webdriver.WebDriverFacade cannot be cast to io.appium.java_client.MobileDriver)

java.lang.ClassCastException: net.thucydides.core.webdriver.WebDriverFacade cannot be cast to io.appium.java_client.MobileDriver
	at com.test.appium.RealBucksAutomation.pageobject.RealbuckPageObject.clickTextBox(MyClassPageObject.java:47)
	at com.test.appium.RealBucksAutomation.model.RealbuckTestStepModules.clickOntextbox(MyClassStepModules.java:17)
	at com.test.appium.RealBucksAutomation.model.RealbuckTestStepModules$$EnhancerByCGLIB$$a9d424f2.CGLIB$clickOntextbox$1(<generated>)
	at com.test.appium.RealBucksAutomation.model.RealbuckTestStepModules$$EnhancerByCGLIB$$a9d424f2$$FastClassByCGLIB$$54e5228d.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:348)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:333)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:308)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:130)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:57)
	at com.test.appium.RealBucksAutomation.model.RealbuckTestStepModules$$EnhancerByCGLIB$$a9d424f2.clickOntextbox(<generated>)
	at com.test.appium.RealBucksAutomation.steps.RealbuckTestSteps.givenIClickOnTheTextBox(MyClassTestSteps.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:599)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:340)

**Comment by YamStranger** [comment]
@selvavaithi thanks, for this issue!

WebDriver facade should be updated to implement MobileDriver as well.

Please try to run something like (I think you will lost some statistics until we will fix this bug):
WebDriver facade = getDriver();
WebDriver driver = ((WebDriverFacade)facade).getDriver();
TouchAction actions = new TouchAction((MobileDriver)driver) ;

**Comment by selvavaithi** [comment]
Hi @YamStranger Sorry when trying your code getting this error

"The method getDriver() is undefined for the type WebDriverFacade"

**Comment by YamStranger** [comment]
@selvavaithi I am talked about method :
https://github.com/serenity-bdd/serenity-core/blob/f6d14d9b92d5f63bc64431cb24494dbfd651cf38/serenity-core/src/main/java/net/thucydides/core/webdriver/WebDriverFacade.java#L101

**Comment by 8saturday8** [comment]
Once more, I tested with default browser in Android. It had the same issue.

**Comment by wakaleo** [comment]
@selvavaithi were you able to get this working?

**Comment by selvavaithi** [comment]
Hi @wakaleo 
Yes now im can able to get this working. Thanks

**Comment by divyaramachandran** [comment]
Can you please let me know how did you get this working? I am running into same problem, Any sample code is appreciated.

**Comment by selvavaithi** [comment]
@divyaramachandran 
This is how i did it.
WebDriver facade = getDriver();
WebDriver driver= ((WebDriverFacade) facade).getProxiedDriver();
TouchAction actions = new TouchAction((MobileDriver)driver) ;

**Comment by divyaramachandran** [comment]
Thank you Selva, but I get a different error  like the below if I use as below


 WebDriver driver =   getDriver();

    WebDriver driver1 = ((WebDriverFacade) driver).getProxiedDriver();

   TouchAction tAction1 = new TouchAction((MobileDriver)driver1) ;

Error in this code :::   tAction1.moveTo(element).release().perform();


java.lang.ClassCastException: com.sun.proxy.$Proxy19 cannot be cast to org.openqa.selenium.remote.RemoteWebElement



While performing actions I get the error


Thanks & regards,

Divya

**Comment by loveshjain** [comment]
@selvavaithi 

I tried your way, but was getting below error : 

Error:- 

Error:org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$6191bd78 cannot be cast to io.appium.java_client.MobileDriver

Please Note : - I am running test on saucelabs.

Could you please provide a solution to it. Many thanks in advance

Thanks,
Lovesh Jain

**Comment by charansethi1** [comment]
Yes I am also getting the same error while running this on sauce labs. it works fine when running it on the simulator on local machine but gives cannot be cast to io.appium.java_client.MobileDriver on Sauce Labs. Please Help

Many Thanks in advance

Charan

**Comment by loveshjain** [comment]
@charansethi1 

Hi Charan,

I have raised a separate issue with @wakaleo and waiting for a perfect solution but meanwhile I was able to resolve the issue with an alternative solution. 

The issue is that when you run the test on saucelabs and give serenity property "Saucelabs.url=something" then the driver is considered as RemoteWebdriver and remotedriver cannot be cast to other driver. So to resolve the issue don't provide Saucelabs.url property and run the test. The only issue you would get is serenity report won't be having your saucelabs job video link because the SaucelabsLinkGenerator.class take saucelabs.url for providing saucelabs video link in serenity report. Therefore you can modify the function with below function to take Saucelab_Access_key : -

 private boolean saucelabsIsNotConfigured() {
        return (ThucydidesSystemProperty.SAUCELABS_ACCESS_KEY.from(environmentVariables) == null);
    }

Also having said that you will encounter 1 issue after this which is when your test case fails, serenity will try to take a screenshot if you have set "serenity.take.screenshots=FOR_FAILURES" or "serenity.take.screenshots=AFTER_EACH_STEP" but since we are not providing saucelabs.url property, it does not consider that as RemoteDriver and does not go to takeScreenShot function of RemoteDriver and because of that your test case will try to do that till saucelabs job time which is by default 30 mins comes to end. I would recommend you to set  "serenity.take.screenshots=DISABLED".

Let me know if in case you face any issue.

Thanks,
Lovesh Jain
+642108258442

**Comment by charansethi1** [comment]
Hi Lovesh

Thanks for the reply. Can you please explain me How and where to use the function you have mentioned

private boolean saucelabsIsNotConfigured() {
return (ThucydidesSystemProperty.SAUCELABS_ACCESS_KEY.from(environmentVariables) == null);
}

How Exactly can we configure Sauce Labs after disabling sauce labs.url serenity property.

Really appreciate your help.

**Comment by loveshjain** [comment]
Hi Charan,

You can still run your appium mobile test cases on saucelabs by giving saucelabs local host path in appium.hub property as below. I have commented out saucelabs.url but provided that url in appium.hub.

Therefore it will consider driver as Android driver and not RemoteDriver.

saucelabs.test.name = Test-Saucelabs-Android
webdriver.driver = appium
appium.hub = http://SaucelabsUsername:SaucelabsAccessKey@localhost:4445/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1
appium.deviceName = Android Emulator
appium.browserName = Browser
appium.deviceType = tablet
appium.deviceOrientation = portrait
appium.hasTouchScreen= true
#saucelabs.url=http://SaucelabsUsername:SaucelabsAccessKey@localhost:4445/wd/hub
saucelabs.access.key=SaucelabsAccessKey
saucelabs.user.id=SaucelabsUsername

With respect to video link in report. The function is in "net.thucydides.core.reports.saucelabs.SaucelabsLinkGenerator"

private boolean saucelabsIsNotConfigured() {
return (ThucydidesSystemProperty.SAUCELABS_URL.from(environmentVariables) == null);
}

Just replace this with 

private boolean saucelabsIsNotConfigured() {
return (ThucydidesSystemProperty.SAUCELABS_ACCESS_KEY.from(environmentVariables) == null);
}

You need to update the jar source.

Thanks,
Lovesh Jain
+642108258442

**Comment by epdittmer** [comment]
Can this be re-opened? Problem still persists today
