### ISSUE TITLE
1.1.29-rc.1 webdriver not restarting after crash.

### ISSUE THREAD

**Issue by dmitriy-grablyov** [serenity-bdd/serenity-core#363]
I'm comparing serenity core 1.1.5 and 1.1.29-rc.1

Let's say I have story1 with scenario11 and scenario12, and story2 with scenario21 and scenario22

execution order is:
 story1 
  scenario11 
  scenario12 
 story2
  scenario21 
  scenario22

When running tests I'm simulating a driver crash just simply by closing browser window. 
With 1.1.5 result gets as follows:
 story1 
  scenario11 - Failure 
  scenario12 - Failure (as driver is managed at a story level) 
 story2
  scenario21 - Success
  scenario22 - Success

With 1.1.29-rc.1 the result is:
 story1 
  scenario11 - Failure 
  scenario12 - failure by logs, ignored in report
 story2
  scenario21 - failure by logs, ignored in report
  scenario22 - failure by logs, ignored in report

So it seems once driver crashed serenity doesn't try to create a new instance.

adding to this, I have configured restart.browser.each.scenario=false for both cases in order to save time on tests execution

**Comment by dmitriy-grablyov** [comment]
I tried to surf the code comparing two versions.
What I found in 1.1.29-rc.1 (and 1.1.26 as well) is that afterStory execution tries to close and quit all drivers, but does not try to clear a proxiedDriver variable in WebDriverFacade.

Please, refer to the method closeAndQuit of WebdriverInstances class.
In 1.1.5 in the method implementation it was the quit() operation for the WebDriverFacade which actually cleared the proxiedDriver variable, currently quit() is called just for the webdriver.

So it turns that in the next stories Serenity still performs consequent calls to WebDriverFacade.getProxiedDriver() where the variable proxiedDriver is not re-initalized.

**Comment by wakaleo** [comment]
Hi Dimitry,

Could you indicate the commit that caused the change that you suspect is causing this problem?

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 21 March 2016 at 4:59:27 PM, dmitriy-grablyov (notifications@github.com) wrote:

I tried to surf the code comparing two versions.
What I found in 1.1.29-rc.1 (and 1.1.26 as well) is that afterStory execution tries to close and quit all drivers, but does not try to clear a proxiedDriver variable in WebDriverFacade.

Please, refer to the method closeAndQuit of WebdriverInstances class.
In 1.1.5 in the method implementation it was the quit() operation for the WebDriverFacade which actually cleared the proxiedDriver variable, currently quit() is called just for the webdriver.

So it turns that in the next stories Serenity still performs consequent calls to WebDriverFacade.getProxiedDriver() where the variable proxiedDriver is not re-initalized.

**Comment by dmitriy-grablyov** [comment]
Ohh, sorry man, I just got stuck in debugging.
I'm trying to debug that after story post action. In 1.1.5 I get such stack of calls when trying catch the point when drivers are closing after story execution:
`
WebDriverFacade.quit() line: 283	
WebdriverInstances.closeAndQuit(WebDriver) line: 66	
WebdriverInstances.closeAllDrivers() line: 92	
ThucydidesWebdriverManager.closeAllCurrentDrivers() line: 82	
ThucydidesWebDriverSupport.closeCurrentDrivers() line: 77	
StepEventBus.testSuiteFinished() line: 464	
SerenityReporter.afterStory(boolean) line: 456
`
in 1.1.26 (1.1.29-rc.1 whatever) I just cannot catch that action. None of my breakpoints work, even at SerenityReporter.afterStory and I start thinking that this branch of code is not even being called.

Possibly this refers to the behavior I described in initial post: If I crash driver at scenario11 of my execution all the rest is just marked as skipped in reports. If so, afterStory could be not even called.

I can proceed digging to the cause of the problem, but I think I'm not able to find it myself.

**Comment by dmitriy-grablyov** [comment]
One more possible reason I can suggest is the problem with getting page source for crashed webdriver.
If something bad occurs with test step serenity wants to log a failure before notifying eventbus about step failure. At StepInterceptor.runTestStep, if step was unsuccessful, catch block tries to invoke logStepFailure method which includes taking a screenshot for current state and also a page source. Screenshot failure is processed correctly, but taking pageSource no. So it turns if step execution failed at taking page source it never gets marked 'finished'.

I think this actually causes all subsequent test scenario skips: afterStory is not invoked because there was no signal that all tests in story are finished and that causes not restarting webdriver instance, but not restarting webdriver instance causes all subsequent scenarios no finishing with appropriate status.

**Comment by YamStranger** [comment]
Hello @dmitriy-grablyov 

Thanks for this issue. 

It reproduced with jBehave. 
Fix will be provided under next release. 
here is screen shots before and after fix for story file with `restart.browser.each.scenario=false` property :
```
Scenario: Record a new todo action for future use
Given I need to buy some milk
When I add the todo action "Buy some milk"
Then "Buy some milk" should be recorded in my todo list

Scenario: New todos should be marked as Active 1
Given I need to buy some milk2
When I add the todo action "Buy some milk2"
Then "Buy some milk2" should be recorded in the "Active" items

Scenario: New todos should be marked as Active 2
Given I need to buy some milk3
When I add the todo action "Buy some milk3"
Then "Buy some milk3" should be recorded in the "Active" items


Scenario: New todos should be marked as Active 3
Given I need to buy some milk4
When I add the todo action "Buy some milk4"
Then "Buy some milk4" should be recorded in the "Active" items


Scenario: New todos should be marked as Active 4
Given I need to buy some milk5
When I add the todo action "Buy some milk5"
Then "Buy some milk5" should be recorded in the "Active" items
```
 (if browser closed manually during `New todos should be marked as Active 1` or `New todos should be marked as Active 4`) 
before:
![before](https://cloud.githubusercontent.com/assets/1667699/13979049/5aacafec-f0de-11e5-902b-83037e27419b.png)

after: 
![after](https://cloud.githubusercontent.com/assets/1667699/13979050/5aad1cac-f0de-11e5-9100-181cd922cda0.png)

**Comment by dmitriy-grablyov** [comment]
Thank you very much guys for paying attention to this issue!

Best Regards,
Dmytro Grablov

**Comment by YamStranger** [comment]
Fix will be available in next serenity-jbehave release

**Comment by YamStranger** [comment]
@dmitriy-grablyov please check fix of this issue in latest jbehave (1.9.0) and serenity core (1.1.29-rc.3)

**Comment by dmitriy-grablyov** [comment]
Just checked with chromedriver on 1.9.0 jbehave and 1.1.29-rc.3 core
Now works as expected, thank you!

**Comment by YamStranger** [comment]
@dmitriy-grablyov Thanks for helping make Serenity BDD better )
