### ISSUE TITLE
HTML report layout issue (1.1.29-rc1)

### ISSUE THREAD

**Issue by jan-molak** [serenity-bdd/serenity-core#365]
Hi there,

As you can see on the screenshot below, it seems like there is a problem with the HTML report generated using Serenity 1.1.29-rc1:

![html-report-issue](https://cloud.githubusercontent.com/assets/1089173/13899887/c8aca4c0-edf0-11e5-9219-64ed8152b5d4.png)

Maybe some missing HTML tag?

The actual HTML report [is available here for your reference](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor-experiments/Serenity/f10d1e79e74a5b8ce2b6f1ea2bc0ff517bdd80d6c38e5b86cdf1a993d70c92b2_screenshots.html#screenshots?screenshot=14).

Please let me know if there's any additional information you'd like me to provide.

Best,
Jan

**Comment by YamStranger** [comment]
Thanks!

**Comment by jan-molak** [comment]
No worries, let me know if I can be of more help with that issue :-)

**Comment by wakaleo** [comment]
Fixed in the next release.
