### ISSUE TITLE
 mvn verify serenity:aggregate no longer run test with the latest version 1.1.28

### ISSUE THREAD

**Issue by monkeyjabs** [serenity-bdd/serenity-core#368]
Hi @YamStranger,

I recently updated my net.serenity-bdd dependencies from 1.1.24 to the latest 1.1.28 and noticed that my mvn command that run my specified test no long run any test at all. 

This command `mvn verify serenity:aggregate -e -DdpsEnvironment=jupiter02 -Dwebdriver.driver=chrome -Dwebdriver.chrome.driver="/Users/csy/Documents/webdriver/chromedriver" -Dit.test=PaywallSmokeTest -Dtags="groups:smoke" ` that works with version 1.1.24 no longer works in 1.1.28. All I see is that the test case started and ends. 

I've tried different version in between and noticed that starting with serenity-core version 1.1.25-rc.5 is what I'm start seeing this issue. Any idea why?

**Comment by YamStranger** [comment]
Hello @monkeyjabs 

Please check that you use latest chrome driver, in [1.1.25-rc.5](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.25-rc.5) selenium was updated to  2.50.1, as result old chrome driver can work not so good as expected... 

Thans!

**Comment by monkeyjabs** [comment]
@YamStranger,

It turned out that the latest version of serenity-bdd required an additional dependencies
`<dependency>
	<groupId>commons-collections</groupId>
	<artifactId>commons-collections</artifactId>
	<version>3.2.2</version>
</dependency>`

It was helpful that I also included the maven-enforcer-plugin to show me what I was missing.

`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <id>enforce</id>
                        <configuration>
                            <rules>
                                <requireUpperBoundDeps/>
                            </rules>
                        </configuration>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

**Comment by YamStranger** [comment]
@monkeyjabs 
Thanks a lot for these instructions!
