### ISSUE TITLE
Free marker error

### ISSUE THREAD

**Issue by ravipallanti** [serenity-bdd/serenity-core#369]
Hi all,

I've been facing the below with an issue for a few days FreeMarker template error:

please see error traced on mvn clean install is below, which looks related. Any ideas?
Appreciate your help.

Mar 25, 2016 2:49:44 AM freemarker.log._JDK14LoggerFactory$JDK14Logger error
25-Mar-2016 02:49:44	SEVERE: Error executing FreeMarker template
25-Mar-2016 02:49:44	FreeMarker template error:
25-Mar-2016 02:49:44	The following has evaluated to null or missing:
25-Mar-2016 02:49:44	==> status_icon  [in template "freemarker/release.ftl" at line 198, column 72]
25-Mar-2016 02:49:44	
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	FTL stack trace ("~" means nesting-related):
25-Mar-2016 02:49:44	        - Failed at: ${status_icon}  [in template "freemarker/release.ftl" at line 198, column 70]
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	
25-Mar-2016 02:49:44	Java stack trace (for programmers):
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
25-Mar-2016 02:49:44	        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:108)
25-Mar-2016 02:49:44	        at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:346)
25-Mar-2016 02:49:44	        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:80)
25-Mar-2016 02:49:44	        at freemarker.core.DollarVariable.accept(DollarVariable.java:40)
25-Mar-2016 02:49:44	        at freemarker.core.Environment.visit(Environment.java:257)
25-Mar-2016 02:49:44	        at freemarker.core.MixedContent.accept(MixedContent.java:57)
25-Mar-2016 02:49:44	        at freemarker.core.Environment.visitByHiddingParent(Environment.java:278)
25-Mar-2016 02:49:44	        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:157)
25-Mar-2016 02:49:44	        at freemarker.core.Environment.visitIteratorBlock(Environment.java:501)
25-Mar-2016 02:49:44	        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
25-Mar-2016 02:49:44	        at freemarker.core.Environment.visit(Environment.java:257)
25-Mar-2016 02:49:44	        at freemarker.core.MixedContent.accept(MixedContent.java:57)
25-Mar-2016 02:49:44	        at freemarker.core.Environment.visit(Environment.java:257)
25-Mar-2016 02:49:44	        at freemarker.core.Environment.process(Environment.java:235)
25-Mar-2016 02:49:44	        at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:36)
25-Mar-2016 02:49:44	        at net.thucydides.core.reports.html.HtmlReporter$Merger.usingContext(HtmlReporter.java:155)
25-Mar-2016 02:49:44	        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportPage(HtmlAggregateStoryReporter.java:522)
25-Mar-2016 02:49:44	        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReleaseDetailsReportsFor(HtmlAggregateStoryReporter.java:335)
25-Mar-2016 02:49:44	        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReleasesReportFor(HtmlAggregateStoryReporter.java:298)
25-Mar-2016 02:49:44	        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:170)
25-Mar-2016 02:49:44	        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:131)
25-Mar-2016 02:49:44	        at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:208)
25-Mar-2016 02:49:44	        at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:149)
25-Mar-2016 02:49:44	        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
25-Mar-2016 02:49:44	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
25-Mar-2016 02:49:44	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
25-Mar-2016 02:49:44	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
25-Mar-2016 02:49:44	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
25-Mar-2016 02:49:44	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
25-Mar-2016 02:49:44	        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
25-Mar-2016 02:49:44	        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
25-Mar-2016 02:49:44	        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
25-Mar-2016 02:49:44	        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
25-Mar-2016 02:49:44	        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
25-Mar-2016 02:49:44	        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
25-Mar-2016 02:49:44	        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
25-Mar-2016 02:49:44	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25-Mar-2016 02:49:44	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
25-Mar-2016 02:49:44	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25-Mar-2016 02:49:44	        at java.lang.reflect.Method.invoke(Method.java:497)
25-Mar-2016 02:49:44	        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
25-Mar-2016 02:49:44	        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
25-Mar-2016 02:49:44	        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
25-Mar-2016 02:49:44	        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
25-Mar-2016 02:49:44	
25-Mar-2016 02:49:44	[ERROR] Syntax error in report template: The following has evaluated to null or missing:
25-Mar-2016 02:49:44	==> status_icon  [in template "freemarker/release.ftl" at line 198, column 72]
25-Mar-2016 02:49:44	
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	FTL stack trace ("~" means nesting-related):
25-Mar-2016 02:49:44	        - Failed at: ${status_icon}  [in template "freemarker/release.ftl" at line 198, column 70]
25-Mar-2016 02:49:44	----
25-Mar-2016 02:49:44	        - Failed at: ${status_icon}  [in template "freemarker/release.ftl" at line 198, column 70]

**Comment by ravipallanti** [comment]
I am using the below versions of serenity
<serenity.version>1.1.26</serenity.version>
        <serenity.cucumber.version>1.1.5</serenity.cucumber.version>
        <serenity.maven.version>1.1.18</serenity.maven.version>

**Comment by wakaleo** [comment]
Have you tried worth 1.1.29-rc.1?

**Comment by ravipallanti** [comment]
Thanks for your quick reply ..
will check and let you know the result

**Comment by YamStranger** [comment]
@ravipallanti if it is possible (if new versions of serenity-core will not help) please attach pom.xml and dependency tree 

THanks

**Comment by YamStranger** [comment]
It seems that this issue already fixed and ticket will be closed.
