### ISSUE TITLE
Has driver support for Microsoft Edge only just been added?

### ISSUE THREAD

**Issue by murrayrj** [serenity-bdd/serenity-core#373]
It looks like the latest commit: https://github.com/serenity-bdd/serenity-core/commit/07762e7942397f757d7191275899352f1829e5b2 has added the necessary edgeDriver to run tests in Microsoft Edge.

I thought Microsoft Edge support was added in v1.1.28?

**Comment by YamStranger** [comment]
Support of Microsoft Edge added only in v1.1.29-rc.3
