### ISSUE TITLE
uniqueInstance-Attribute not working accross multiple step-definitions

### ISSUE THREAD

**Issue by christopherfrieler** [serenity-bdd/serenity-core#374]
I'm currently experiencing the following problem:
I have two classes with step-definitions. Both are using the same step-library, injected into a field annotated with `@Steps`. Although I am setting the uniqueInstance-attribute to `true`, I get two different instances.

The cause seems to be the initialization of the Serenity-class. This initialization is done repeatedly for each step-definition-class. In line 125 of class Serenity there is a new StepFactory instantiated each time. Hence, I am getting a new instance of the step-library, because the existing instance was cached only by the former StepFactory.

A possible solution might be, to create a new StepFactory only if the ThreadLocal is currently empty.
For those facing the same problem, here's my current workaround: I let the instances of the step-library share the value, that I want to access from each instance, through a ThreadLocal.

**Comment by wakaleo** [comment]
Thanks Christopher, we'll take a look at this shortly.

**Comment by cliviu** [comment]
Hi Cristopher ! I think that the name of the "uniqueInstance" attribute is a bit confusing. 

I think that with "unique" is meant that always **different** instances of the fields annotated with @Steps  have to be created. So, by default (meaning uniqueInstance="false") , you should get always the same instance of the field annotated with @Steps.

The problem that I see now is that, as you mentioned, more StepFactory instances are created, making caching of the Steps instances useless. 

Nevertheless, the creation of the StepFactory occurs here 
```java
	at net.thucydides.core.steps.StepFactory.<init>(StepFactory.java:49)
	at net.serenitybdd.junit.runners.SerenityRunner.initStepFactoryUsing(SerenityRunner.java:375)
	at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:527)
```

**Comment by wakaleo** [comment]
Liviu, did you run the tests locally for your change? I'm seeing unit test failures.

**Comment by cliviu** [comment]
Hi Cristopher ! The **uniqueInstance** attribute works only at method level. 
Lets say we have the following scenario
```java
    @Steps
    AuthorizationSteps authorizationSteps;

    @Steps
    AuthorizationSteps authorizationSteps1;

    @Test
    public void testUsingAuthorizationSteps() {
       ...
        authorizationSteps.authorizeWithPhone("123-1");
        authorizationSteps1.authorizeWithPhone("123-1");
    }    
```
In the above mentioned method, the authorizationSteps and authorizationSteps1 will point to the same  
AuthorizationSteps instance.

in case that you add the uniqueInstance attribute , 
```java
    @Steps(uniqueInstance = true)
    AuthorizationSteps authorizationSteps;

    @Steps(uniqueInstance = true)
    AuthorizationSteps authorizationSteps1;

    @Test
    public void testUsingAuthorizationSteps() {

        authorizationSteps.authorizeWithPhone("123-1");
        authorizationSteps1.authorizeWithPhone("123-1");
    }    
```
the **authorizationSteps** and **authorizationSteps1** will be two different AuthorizationSteps instances

Having the same instance of a step library across multiple tests could create side-effects between tests, which is why it would not be a good idea

**Comment by cliviu** [comment]
@john , please close the pull request, it was a bad ideea

**Comment by cliviu** [comment]
@christopherfrieler , would you like to post some sample code of the problem you are trying to solve ?I hope that my above explanation about the scope and the meaning of **uniqueInstance** attribute is clear. 
In case that everything is clear, please close the issue.  Thanks !

**Comment by christopherfrieler** [comment]
Thanks for looking at it. Yes, I misunderstood the uniqueInstance-attribute. It works just the other way around. And yes, you're right, using the same step-instance accross multiple tests is a bad idea, because these tests would no longer be independent.

In my case, I am using serenity with serenity-cucumber and have nested step-libraries like this:

```java
public class BaseSteps {
    private Object stateBetweenSteps;
...
}

public class AdvancedSteps1 {
    @Steps
    private BaseSteps baseSteps;
...
}

public class AdvancedSteps2 {
    @Steps
    private BaseSteps baseSteps;
...
}
```

And somewhere the cucumber-annotated method:
```java
	@Steps
	private AdvancedSteps1 advancedSteps1 ;
	@Steps
	private AdvancedSteps2 advancedSteps2 ;

	@Given("^whatever.$")
	public void whatever() {
		advancedSteps1.firstPartOfWhatever();
		advancedSteps2.secondPartOfWhatever();
	}
```

In this case, I get two different instances of BaseSteps. Hence AdvancedSteps1 and AdvancedSteps2 cannot make use of the state in BaseSteps. Maybe that's all a bad idea. But right now in my situation I need that state between steps, but also want to cut my step-classes into small, reusable building-blocks following the single-responsibility-principle.

**Comment by Invictum** [comment]
Hi @christopherfrieler 
So, as I understand you just want to share some data between steps?

**Comment by christopherfrieler** [comment]
Yes, but want this state between steps as a reuseable feature in my step-library-classes. Maybe the Treadlocal that I use as a workaround is already the best solution, because it should allow to execute tests in parallel threads.

**Comment by YamStranger** [comment]
Hello @christopherfrieler 

it seems that solution was found, please close this ticket

Thanks!!

**Comment by YamStranger** [comment]
@christopherfrieler 
Thanks!!
