### ISSUE TITLE
Merge reports from multiple browser

### ISSUE THREAD

**Issue by hypery2k** [serenity-bdd/serenity-core#376]
If I run my tests per browser I want to merge the single test runs. I saw an [google group post](https://groups.google.com/forum/#!searchin/thucydides-users/multi$20browser/thucydides-users/GSLmjOn2C1E/7DnVToPpBgAJ), but I don't want to reimplement my tests

Any ideas?

**Comment by hypery2k** [comment]
any ideas how to resolve?

**Comment by wakaleo** [comment]
At the moment it would not be possible. We are considering how to implement this as a built-in feature for an upcoming release.

**Comment by wakaleo** [comment]
This can now be done: see https://johnfergusonsmart.com/running-tests-different-environments-browsers-serenity-bdd/

**Comment by tdudhale** [comment]
how to merge reports ran on different machine

**Comment by wakaleo** [comment]
Copy the contents of the target/site/serenity directories onto one machine and run mvn serenity:aggregate

**Comment by mcocosila** [comment]
Hi John,

I merged Serenity reports from two maven modules by copying contents of the target/site/serenity of one module over target/site/serenity directory of the second. Then I ran mvn serenity:aggregate. Requirements, Capabilities and Features tabs show only links referencing target module. Only Overall Test Results tab shows tests from both modules.

Please advise.

Thanks,
mircea

**Comment by wakaleo** [comment]
The requirements hierarchy needs to be the same for both merged projects.

**Comment by mcocosila** [comment]
Thanks for your quick response. I have same number of folder levels in both modules like:
src/test/resources/features/search/find_user.feature

I have following cucumber options in both modules:
@CucumberOptions(
        plugin = {"pretty"},
        features = {"src/test/resources/features"},
        glue = {"abc.stepdefinitions"}

**From console where module1 was built:**
REQUIREMENTS:
    - capability : License {id: License, displayName: 'License', path: license, parent: 'null'}
        - feature : License mock {id: license-mock, displayName: 'License mock', path: license/license_mock.feature, parent: 'License'}
    - capability : Status {id: Status, displayName: 'Status', path: status, parent: 'null'}
        - feature : Check on all unit tests {id: check-on-all-unit-tests, displayName: 'Check on all unit tests', path: status/check_on_api_status.feature, parent: 'Status'}

**From console where report merge happened (module2) after I copied over target/site/serenity of module1:**
REQUIREMENTS:
    - capability : Search {id: Search, displayName: 'Search', path: search, parent: 'null'}
        - feature : Admin finds a User {id: admin-finds-a-user, displayName: 'Admin finds a User', path: search/find_user.feature, parent: 'Search'}

In the Requirements, Capabilities and Features tabs of the merged report I see only the capabilities and features of module2. Overall Test Results shows all tests both for module1 and module2.

Wondering if you spot something in the inputs of the merge report which is not as expected.

**Comment by wakaleo** [comment]
To merge the requirements, the requirements folders need to be identical (not just the same number of levels) - merging different requirements trees is not supported as Serenity needs to read the feature files and their locations to generate the reports.

**Comment by mcocosila** [comment]
Thanks again for your quick response. I still don't understand how report merge works. I ensured same folders are created in both requirements hierarchies. I also created dummy scenarios not to have empty requirements folders in any of the hierarchies. Same behavior as before: in the Requirements, Capabilities and Features tabs of the merged report I see only the capabilities and features of the module where I've run mvn serenity:aggregate.

Any more advise is highly appreciated. Thanks.

**Comment by mcocosila** [comment]
John,

When you say "to merge the requirements, the requirements folders need to be identical" you mean for the folders to also have exactly same feature files in them and also having same scenarios in those feature files?

Please confirm so I'll stop my attempts to merge complementary requirements trees - even when trying to ensure same requirements folders but different feature files in them. Thanks a lot.

**Comment by wakaleo** [comment]
In summary, merging will only currently work if you are merging different sub-sets of tests from the same project. Serenity needs access to the full requirements structure including dirs and feature files.

**Comment by piyushawe25** [comment]
> Copy the contents of the target/site/serenity directories onto one machine and run mvn serenity:aggregate

Hi,
I am confused with it,as i am trying to copy of both report at same place but system ask me to copy and replace index.html as both have index.html file,once i do that n run aggregate it doesn't not generate report...so can you explain me what m i missing n how to to do that..

**Comment by gizdolok** [comment]
I am having the same exact issue.

I trying to follow everything from this tutorial https://johnfergusonsmart.com/running-tests-different-environments-browsers-serenity-bdd/

I don't get step 2 of the _Aggregating test results_ part:

_Copying the contents of the target/site/serenity directories into the target/site/serenity directory of your main project_

I always get system alerts that I'm replacing already existing files.

@wakaleo could you explain in more detail why we need to copy the contents of this path's directories into the root of this path?

**Comment by bdeane96** [comment]
@gizdolok did you find a solution for this?
