### ISSUE TITLE
Appium(Java Android) + Chrome test , setup chromeOption

### ISSUE THREAD

**Issue by 8saturday8** [serenity-bdd/serenity-core#379]
Hi all,
I have a problem when running Serenity with chrome.It always asking saving password pop-up each logging web app.
I investigated and know that Appium server capabilities have an option to solve this : chromeOptions.
But I can not add it to [serenity.properties]. Did I miss something or Serenity  not support yet ?
Thanks,

**My config like that:**
 [serenity.properties]
webdriver.driver=appium
appium.autoWebView = true
appium.automationName=Appium
appium.hub = http://127.0.0.1:4723/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1
appium.deviceName =
appium.noReset = true
appium.browserName = Chrome
appium.chromeOptions.args  = disable-save-password-bubble

**Comment by YamStranger** [comment]
Hello @8saturday8 
Thanks for this issue. 

Based on [manual](http://thucydides.info/docs/serenity-staging/) : 
>
serenity.driver.capabilities
A set of user-defined capabilities to be used to configure the WebDriver driver. Capabilities should be passed in as a space or semi-colon-separated list of key:value pairs, e.g. "build:build-1234; max-duration:300; single-window:true; tags:[tag1,tag2,tag3]"

so you should pass your capability as parameter in command line during execution of test, OR provide them as list of key:value pairs. 
For example if your capability should contains only chromeOptions is should be something like:
```
serenity.driver.capabilities=appium.chromeOptions.args:disable-save-password-bubble
```

**Comment by 8saturday8** [comment]
Thanks @YamStranger 
I tried to change in [serenity.properties] file but no luck.
Maybe this capabilities need a list of setting argument .

I tried something like that as appium capability [manual](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md)

**[serenity.properties] **
```
webdriver.driver=appium
appium.autoWebView = true
appium.automationName=Appium
appium.hub = http://127.0.0.1:4723/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1
appium.deviceName =
appium.noReset = true
appium.browserName = Chrome
appium.chromeOptions={args: ['--disable-popup-blocking']}
```

Seam to be it reconized chromeOptions but not reconized the value that I passed.
Maybe I didn't input the correct value's format . I also tried other value for this as : 
args: ['--disable-popup-blocking'] 
{"args":["--disable-save-password-bubble"]}
....
Then the appium error log: 
`
> info: --> POST /wd/hub/session {"desiredCapabilities":{"hub":"http://127.0.0.1:4723/wd/hub","noReset":"true","platformVersion":"5.1","automationName":"Appium","autoWebView":"true","browserName":"Chrome","chromeOptions":"{args: ['--disable-popup-blocking']}","platformName":"Android","deviceName":""}}
> info: Client User-Agent string: Apache-HttpClient/4.5.2 (Java/1.8.0_66)
> warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.
> warn: Converting cap autoWebView from string to boolean. This might cause unexpected behavior.
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : hub, autoWebView, chromeOptions
> info: Set mode: Proxying straight through to Chromedriver
> info: [debug] Looks like we want chrome on android
> info: [debug] Creating new appium session 01ef6760-2a90-4111-af8e-8d142566b958
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Android\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device emulator-5554
> info: [debug] Setting device id to emulator-5554
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 wait-for-device
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.chrome -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data"}
> info: [debug] dataDir set to: /data
> info: Chromedriver: Changed state to 'starting'
> info: Chromedriver: Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
> info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: Chromedriver: No old chromedrivers seemed to exist
> info: Chromedriver: Spawning chromedriver with: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=9515
> info: Chromedriver: [STDOUT] Starting ChromeDriver 2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a) on port 9515
> Only local connections are allowed.
> info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
> info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1 SP1\"}}}"
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"0":"{","1":"a","2":"r","3":"g","4":"s","5":":","6":" ","7":"[","8":"'","9":"-","10":"-","11":"d","12":"i","13":"s","14":"a","15":"b","16":"l","17":"e","18"...
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"7f1cababdf031e3d606b35ccd709a2c6","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: 0\n  (Driver i...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"0":"{","1":"a","2":"r","3":"g","4":"s","5":":","6":" ","7":"[","8":"'","9":"-","10":"-","11":"d","12":"i","13":"s","14":"a","15":"b","16":"l","17":"e","18"...
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"9e839a540e393d37c787fc4d68fcc8aa","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: 0\n  (Driver i...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"0":"{","1":"a","2":"r","3":"g","4":"s","5":":","6":" ","7":"[","8":"'","9":"-","10":"-","11":"d","12":"i","13":"s","14":"a","15":"b","16":"l","17":"e","18"...
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"ae734151c70caccab8f6756fe65afbab","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: 0\n  (Driver i...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"0":"{","1":"a","2":"r","3":"g","4":"s","5":":","6":" ","7":"[","8":"'","9":"-","10":"-","11":"d","12":"i","13":"s","14":"a","15":"b","16":"l","17":"e","18"...
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"242fba75878a8e87d93ed1973e93a959","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: 0\n  (Driver i...
> error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
> info: Chromedriver: Changed state to 'stopped'
> info: Chromedriver stopped unexpectedly on us, shutting down then calling back up with the on-die callback
> error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: cannot parse capability: chromeOptions
> from unknown error: unrecognized chrome option: 0
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64))
>     at JWProxy.command$ (lib/proxy.js:133:15)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at bound (domain.js:284:14)
>     at GeneratorFunctionPrototype.runBound (domain.js:297:12)
>     at run (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:89:39)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:100:28
>     at flush (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\$.microtask.js:17:13)
>     at process._tickDomainCallback (node.js:381:11)
>  { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: cannot parse capability: chromeOptions
> from unknown error: unrecognized chrome option: 0
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64))]
>   status: 13,
>   value: { message: 'unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: 0\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)' },
>   httpCode: 200 }
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: cannot parse capability: chromeOptions
> from unknown error: unrecognized chrome option: 0
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64))
> info: [debug] Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: cannot parse capability: chromeOptions
> from unknown error: unrecognized chrome option: 0
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64))
>     at JWProxy.command$ (lib/proxy.js:133:15)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at bound (domain.js:284:14)
>     at GeneratorFunctionPrototype.runBound (domain.js:297:12)
>     at run (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:89:39)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:100:28
>     at flush (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\$.microtask.js:17:13)
>     at process._tickDomainCallback (node.js:381:11)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: An unknown server-side error occurred while processing the command. (Original error: unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: 0\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)))","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: 0\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)"},"httpCode":200,"origValue":"An unknown server-side error occurred while processing the command. (Original error: unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: 0\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64))"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 1792.819 ms - 1019 
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 0.93
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] UiAutomator shut down normally
> info: [debug] executing cmd: C:\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop com.android.chrome"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Cleaning up appium session
`

**Comment by 8saturday8** [comment]
Update:
I tried with config:
`appium.chromeOptions={"args": ["--disable-popup-blocking"]}`

When senerity passed to appium , it becomes like that:
`> info: --> POST /wd/hub/session {"desiredCapabilities":{"hub":"http://127.0.0.1:4723/wd/hub","noReset":"true","platformVersion":"5.1","automationName":"Appium","autoWebView":"true","browserName":"Chrome","chromeOptions":"{\"args\": [\"--disable-popup-blocking\"]}","platformName":"Android","deviceName":""}}`

```
> error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: cannot parse capability: chromeOptions
> from unknown error: unrecognized chrome option: 0
```
Anybody know how to remove sign "\" ?

**Comment by YamStranger** [comment]
Hello @8saturday8 

Here is example of code, where capabilities are added to desired capabilities of target driver: 
```
    private DesiredCapabilities addExtraCatabilitiesTo(DesiredCapabilities capabilities) {
        CapabilitySet capabilitySet = new CapabilitySet(environmentVariables);
        Map<String, Object> extraCapabilities = capabilitySet.getCapabilities();
        for(String capabilityName : extraCapabilities.keySet()) {
            capabilities.setCapability(capabilityName, extraCapabilities.get(capabilityName));
        }
        addCapabilitiesFromFixtureServicesTo(capabilities);
        return capabilities;
    }
```
and here is example of code where capabilities are parsed (CAPABILITY_SEPARATOR=";"):
```
    public Map<String,Object> getCapabilities() {
        Map<String,Object> capabilitiesMap = Maps.newHashMap();

        String specifiedCapabilities = THUCYDIDES_DRIVER_CAPABILITIES.from(environmentVariables);
        if (StringUtils.isNotEmpty(specifiedCapabilities)) {
            Iterable<String> capabilityValues = Splitter.on(CAPABILITY_SEPARATOR).trimResults().split(specifiedCapabilities);
            capabilitiesMap = addCapabilityMapValues(capabilityValues);
        }
        return capabilitiesMap;
    }
```
so if you add to your config line
```
serenity.driver.capabilities=capability-name:--disable-popup-blocking
```
it will be passed to browser capability without any additional "\"" 
```
capabilities.setCapability("capability-name","--disable-popup-blocking");
```
but as I see you try to pass command line switches to browser (link)[http://peter.sh/experiments/chromium-command-line-switches/]. 
We have such options ONLY for chrome, using string in format `chrome.switches = --notincognito`, here is code:
```
    private DesiredCapabilities chromeCapabilities() {
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        String chromeSwitches = environmentVariables.getProperty(ThucydidesSystemProperty.CHROME_SWITCHES);
        capabilities.setCapability(ChromeOptions.CAPABILITY, optionsFromSwitches(chromeSwitches));
        capabilities.setCapability("chrome.switches", chromeSwitches);
        return capabilities;
    }
``` 
**BUT**
I think that it can work if you pass your switches to appium using capabilities-passing mechanism as described in beginning of this answer.
```
serenity.driver.capabilities=chromeOptions:[--disable-popup-blocking;--disable-save-password-bubble];chrome.switches:[--disable-popup-blocking;--disable-save-password-bubble]
```

Based on your example: 
>{"desiredCapabilities":{"hub":"http://127.0.0.1:4723/wd/hub","noReset":"true","platformVersion":"5.1","automationName":"Appium","autoWebView":"true","browserName":"Chrome","chromeOptions":"{\"args\": [\"--disable-popup-blocking\"]}","platformName":"Android","deviceName":""}}

did you try next?  
```
appium.chromeOptions={args: [--disable-popup-blocking]}
```

**Comment by 8saturday8** [comment]
Hello @YamStranger 
I see, but the capabilities for chromeOptions need sub argument. 
As I see in appium document, --disable-popup-blocking belong to "args" object
Besides "args" object , chromeOptions also have "extensions", "binary" ...
I also tried but no luck , it still not recognized the value passed to  chromeOptions
appium.chromeOptions={args: [--disable-popup-blocking]}

```
serenity.driver.capabilities=chromeOptions:[--disable-popup-blocking;--disable-save-password-bubble];chrome.switches:[--disable-popup-blocking;--disable-save-password-bubble]
...
```

Same error from appium server like that(seam to be it recognized that capability but can not parse the value):
`> from unknown error: unrecognized chrome option: 0`
I think it need double quote for sub object. I think the example code only parse first level of capabilities. 
I think it will work if the POST to appium have the format like this:

`> info: --> POST /wd/hub/session {"desiredCapabilities":{"hub":"http://127.0.0.1:4723/wd/hub","noReset":"true","platformVersion":"5.1","automationName":"Appium","autoWebView":"true","browserName":"Chrome","chromeOptions":"{"args": ["--disable-popup-blocking"]}","platformName":"Android","deviceName":""}}`

**Comment by YamStranger** [comment]
@8saturday8 Did you try to use appium without serenity? 

To make sure that all passed  capabilities and options are accepted correctly?

**Comment by YamStranger** [comment]
It seems that this issue can be closed and solution was found
