### ISSUE TITLE
Assertion messages are displayed incompletely in report in case of failure.

### ISSUE THREAD

**Issue by alexamber** [serenity-bdd/serenity-core#380]
Hi,

We have updated serenity-bdd core version from 1.1.14 to 1.1.29-rc.3 and now we see incomplete assertion messages in report. In fact if you press "View stack trace" button the message will display fully. Also the message in displayed fully in the tool-tip for scenario on the index page. 
![image](https://cloud.githubusercontent.com/assets/10475651/14490847/f5c92b90-017d-11e6-9b05-218bab6b9dec.png)
First example is for old variant from 1.1.14 version.
Second is for the new one. 

You can see that in the second variant the message is trimmed while on the first one it is displayed fully with ability to scroll and read.

The following assertion libraries are used in the project: org.easytesting/fest-assert-core/2.0M10 and org.assertj/assertj-core/3.3.0

I assume the problem may be in templates used for report generation or in the way test result data is provided to them.
Could you please look at the issue and provide some solution?

Thank you.

**Comment by wakaleo** [comment]
Thanks for raising this issue, it does look like a bug in how certain types of assertions are reported. Do you think you could provide an example of a failing assertion that causes this issue so that we can include it in our unit tests?

**Comment by alexamber** [comment]
Example:
`assertThat(actualCode).as(String.format("RESPONSE ERROR: [%s]", response.getBody())).expectedResponseCode);`
I hope that is what is needed.

**Comment by wakaleo** [comment]
Fix released in version 1.1.32-rc.2
