### ISSUE TITLE
While executing multiple tests, report generation is slow in serenity

### ISSUE THREAD

**Issue by kamalshingala** [serenity-bdd/serenity-core#382]
Hi, I am facing issue with reports being generated very slow (While running a test with for e.g. 10 test scenarios, report generation service aggregates and compiles reports starting from scenario 1 every time i.e scenario1, report generated for scenario 1, scenario 2 execution, report generated for scenario 1 and 2 and so on.. and I am using serenity version 1.1.21. I tried using latest version of serenity 1.1.29-rc.2 as you suggested and it looks to be generating report quickly, however it doesnt show the step started and step done in the output logs.

**Comment by kamalshingala** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>uitest</groupId>
    <artifactId>webtest</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Sample Serenity project using Cucumber and WebDriver</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.21</serenity.version>
        <serenity.cucumber.version>1.1.2</serenity.cucumber.version>
        <webdriver.driver>chrome</webdriver.driver>
    </properties>



    <reporting>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>3.0.2</version>
                <configuration>
                    <xmlOutput>true</xmlOutput>
                    <xmlOutputDirectory>target/site</xmlOutputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20151123</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/unittest/*.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/binding/*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by YamStranger** [comment]
Hello @kamalshingala 
Thanks for this issue. 

If it is possible - please use latest version of serenity if it possible.

Also, it seems that you can change level of log info included in logs to include that you need:

Please search manual by "serenity.logging": http://thucydides.info/docs/serenity-staging/
Thanks!

**Comment by kamalshingala** [comment]
Hello @YamStranger 

Thanks for your reply!

I tried using latest version of serenity, however due to some reason I don't see output logs (in NORMAL logging) it is just showing me logs when error occurs. Can it be because of other plugins not being up to date or anything else? I also tried using the serenity.logging and it is giving me logs when I set it to VERBOSE. 

Thanks!

**Comment by YamStranger** [comment]
Hello @kamalshingala 
Reason should be in some configuration of your project. 
It is great, that 'VERBOSE' helped you. 

Will close this issue.

**Comment by kamalshingala** [comment]
Hi @YamStranger 

I have attached my pom.xml in my first question. I dont understand what is wrong in the project configuration. Appreciate if you can let me know if I have missed anything as NORMAL logging is perfectly working fine when I use 1.1.21 version of serenity. It is not working in NORMAL mode when I go for latest version 1.1.29-rc.2 and I don't want to use VERBOSE as it is logging a lot more information then I need. I tried to investigate myself for NORMAL logging but it did not work. Appreciate if you can help!

Thanks!

**Comment by YamStranger** [comment]
@kamalshingala Sure, will take a look and will update this ticket. Do you have some logging configuration in your project? (log4j, slf4j and so on.)

**Comment by kamalshingala** [comment]
@YamStranger 

Yes. We are using slf4j. Below is the pom.xml snapshot for the same.

<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>

**Comment by YamStranger** [comment]
@kamalshingala, yes it is what I mean - I think that some configuration in your project brake log output.
By default Serenity BDD use info logging level, and by default it is printed to console:
```
    public void testStarted(String description) {
        if (loggingLevelIsAtLeast(LoggingLevel.NORMAL)) {
            getLogger().info(testStartedHeadings() + "\nTEST STARTED: " + description + underline(TEST_STARTED_HEADINGS.get(headingStyle)));
        }
    }
```

**Comment by kamalshingala** [comment]
@YamStranger 

Yes. I am looking to use default logging only, however not sure why it is braking when I use latest version of serenity. Please note apart from change in the version of serenity there is no other change I am doing.

**Comment by YamStranger** [comment]
@kamalshingala please clone repository git@github.com:serenity-bdd/serenity-demos.git 
and navigate to folder cucumber-webtests, and here execute command
```
mvn clean verify
``` 

did you see logs, like:?
```
21589 [main] INFO net.serenitybdd.core.Serenity - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  
```

Also, did you mean under 
>Please note apart from change in the version of serenity there is no other change I am doing.
that you updated all versions, include serenity-cucumber?

**Comment by kamalshingala** [comment]
Hi @YamStranger 

I tried executing the specified repo from github and yes I can see TEST STARTED texts. 

And regarding your second question, I did not update serenity-cucumber plugin. Previously once I had tried using 1.1.5 and 1.1.6 version of serenity just to check if is it version conflict with the serenity or anything else and result was the same no output for NORMAL logging.

**Comment by YamStranger** [comment]
@kamalshingala 
Are you sure that you tests executed at all (as well as aggregated reposts are generated)? 
Please post sample project to github, and add link to this ticket. 

It seems that tests are not executed at all, and it depends on your project configuration. 

Thanks

**Comment by kamalshingala** [comment]
Hi @YamStranger 

Yes! Tests are getting executed and generating reports.

As per your request, I have created a sample project and uploaded it to a repository @ https://github.com/kamalshingala/serenityDemo.git

Please let me know if you need more information!

Thanks,
Kamal Shingala

**Comment by kamalshingala** [comment]
Hi @YamStranger 

Just checking if you got a chance to look at the above comment?

Thanks in advance,
Kamal Shingala

**Comment by YamStranger** [comment]
Hello @kamalshingala 
Yes, I have looked on your project: 

first of all you use old cucumber, and not latest version of serenity, so I updated your pom to: 
(serenity cucumber from 1.1.2 to 1.1.6, serenity core from 1.1.29-rc2 to 1.1.32-rc1, maven plugin to 1.1.31).

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>uitest</groupId>
    <artifactId>webtest</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Sample Serenity project using Cucumber and WebDriver</name>
    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </releases>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray-plugins</name>
            <url>http://jcenter.bintray.com</url>

        </pluginRepository>
        <pluginRepository>
            <id>my-local-repo</id>
            <url>file://${user.home}/.m2/repository/</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>


    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.32-rc.1</serenity.version>
        <serenity.cucumber.version>1.1.6</serenity.cucumber.version>
        <webdriver.driver>chrome</webdriver.driver>
    </properties>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>3.0.2</version>
                <configuration>
                    <xmlOutput>true</xmlOutput>
                    <xmlOutputDirectory>target/site</xmlOutputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20151123</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>1.1.6</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/unittest/*.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/binding/*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>1.1.31</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

I executed your
 tests, and found in logs information about starting of tests and finishing of them: 

[out.txt](https://github.com/serenity-bdd/serenity-core/files/246310/out.txt)

It looks like 
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running githubTest.binding.TestRunner

1 Scenarios ([32m1 passed[0m)
3 Steps ([32m3 passed[0m)
0m9.155s

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.806 sec - in githubTest.binding.TestRunner

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

```

In console you can find info like in more "beautiful way"
```
-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
-------------------------------------------------------------------------------------

[main] INFO net.serenitybdd.core.Serenity - Test Suite Started: Google Feature
[main] INFO net.serenitybdd.core.Serenity - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: google search test
-------------------------------------------------------------------
[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.build.directory : null
[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.reporting.OutputDirectory : null
[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - OutputDirectory : /home/yamstranger/dev/src/serenity/serenity-all/serenity-module-integrations/src/test/resources/projects/serenityDemo/target/site/serenity
Starting ChromeDriver (v2.9.248304) on port 27927
[0.206][WARNING]: PAC support disabled because there is no system implementation
[main] INFO net.serenitybdd.core.Serenity - 
        __    _____ _____ ____ _____   ____   _    ____  ____  _____ ____  
  _     \ \  |_   _| ____/ ___|_   _| |  _ \ / \  / ___|/ ___|| ____|  _ \ 
 (_)_____| |   | | |  _| \___ \ | |   | |_) / _ \ \___ \\___ \|  _| | | | |
  _|_____| |   | | | |___ ___) || |   |  __/ ___ \ ___) |___) | |___| |_| |
 (_)     | |   |_| |_____|____/ |_|   |_| /_/   \_\____/|____/|_____|____/ 
        /_/                                                                

TEST PASSED: google search test
```

**It is correct behaving, and logging works as expect to work**.
To include info about step started step done - please turn on VERBOSE mode, and yes you will see a lot of additional info (because step started - step stop it is out of normal logging - it is detailed logging )

Also, as main issue of this ticket - "report are generated too slow"  - fixed (by using latest version of serenity), I think that this ticket can be closed.

P.S. @kamalshingala if you take a look at code that generate such output to console: 
https://github.com/serenity-bdd/serenity-core/blob/56b027874e67ebb0bda54959356a2725f5ec91c8/serenity-core/src/main/java/net/thucydides/core/steps/ConsoleLoggingListener.java#L215

you will find that we use slf4, so if you need some extended behaving - just update configuration of slf4 to make it work as you want ) 
(and push output from particular classes, or even methods to log file as well)

Thanks!!

**Comment by kamalshingala** [comment]
@YamStranger ,

Thanks for your reply. I just wanted to confirm if the logging is as per the expected behavior.
