### ISSUE TITLE
Serenity generates report before finishing running all steps

### ISSUE THREAD

**Issue by darekzborowski** [serenity-bdd/serenity-core#385]
Hello,

After the upgrade to Serenity 1.1.29-rc3, we've noticed that our report does not get fully generated.
After Serenity is done executing our scenarios and index.html page is created, all "step pages" are missing. (Steps table is populated however with all steps from scenarios)
Clicking on anything in index.html gives us a 404 not found error.

I have also noticed that our last scenario is prematurely interrupted and does not finish executing causing the webdriver to hang. That scenario is marked as "Pending" in the final even though all steps are implemented. 
In the output logs I can see that AfterStories call is performed while our last scenario is still running, killing the execution of last scenario but leaving the driver hanging.
No exceptions are thrown while creating the report.

I can replicate this issue every so often. Running the same test multiple times will eventually generate full report but only if the driver closes before AfterStories.

Thanks for your help

**Comment by darekzborowski** [comment]
#102 After searching through open issues some more, this one seems to have the same root cause.

**Comment by darekzborowski** [comment]
More Details.
The issue seems to be caused by JBehave's Tabular Parameters feature.

If the story has scenario(s) with tabular parameters as part of the grammar the AfterStories is triggered prematurely killing the runner before all steps are done. This issue is also causing the Selenium webdriver to hang since it never gets destroyed. 
While serenity is generating the final report, this log pops up:
"Failed to run batch 
path/to/story/my_story.story: java.util.concurrent.CancellationException"

Running the exact same story file without tab parameter scenario gives us no error in execution.
Hope this helps

**Comment by wakaleo** [comment]
Could you check with serenity-core 1.1.36 and serenity-behave 1.13.0?

**Comment by darekzborowski** [comment]
Found out what the issue was.

Default story timeout value is set to 300 and since I wasn't setting serenity.timeout and story.timeout.in.secs to a higher value, longer tests were executing prematurely.

After setting those 2 configurations to a longer timeout, the issue is now gone.

Thanks for your feedback
