### ISSUE TITLE
Serenity bug with executeScript - : unknown error: $ is not a function

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#393]
@YamStranger  @wakaleo  I am trying to achieve HTML5 drag and drop.

I could able to get it done with simple selenium script , please refer to 
https://github.com/vikramvi/Selenium-Java/commit/a1354ca5854315fded8fc80ba24a4717927d08c7

https://github.com/vikramvi/Selenium-Java

This works perfectly but same code doesn't work with Serenity

https://github.com/vikramvi/serenity-cucumber-wl/commit/f489ece79bfeeaabfda103872cfe3d8df2c5385f

https://github.com/vikramvi/serenity-cucumber-wl

`org.openqa.selenium.WebDriverException: unknown error: $ is not a function
  (Session info: chrome=50.0.2661.86)
 (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds

Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=/var/folders/94/3dpydv3j2t7__4736h1pl0vr0000gn/T/.org.chromium.Chromium.j5W35o}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=50.0.2661.86, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a741033f320e8f40e5fd9c7eeba97231
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at net.thucydides.core.webdriver.WebDriverFacade.executeScript(WebDriverFacade.java:372)
	at com.vikramvi.cucumber.pages.WLC_ListPage.DragAndDrop(WLC_ListPage.java:189)
	at com.vikramvi.cucumber.steps.serenity.WL3CSteps.selectListAndDoTaskDragAndDrop(WL3CSteps.java:84)
`

I think there is bug in framework method which tries to execute javascript.

Kindly have a look and let me know if I can give more info

**Comment by wakaleo** [comment]
It looks like you are just accessing the WebDriver JavaScript execution directly - I could be mistaken, but Serenity doesn’t have much of a role here I think. 'unknown error: $ is not a function’ seems to indicate that JQuery is not present on the page you are manipulating?

Also, a couple of comments on your code:

"getDriver().findElement(By.xpath” can be replaced with $, e.g.

getDriver().findElement(By.xpath("//div[@class='lists-scroll']/ul[@class='lists-collection']/li[contains(@class,'sidebarItem')]["+listCounter+"]//a//span[contains(@class,'title')]")).click();

could be

$("//div[@class='lists-scroll']/ul[@class='lists-collection']/li[contains(@class,'sidebarItem')]["+listCounter+"]//a//span[contains(@class,'title')]").click();

Though I usually avoid using XPath selectors like that, as they are quite brittle and hard to read.

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 26 April 2016 at 2:25:30 PM, Vikram Ingleshwar (notifications@github.com) wrote:

@YamStranger @wakaleo I am trying to achieve HTML5 drag and drop.

I could able to get it done with simple selenium script , please refer to
vikramvi/Selenium-Java@a1354ca

https://github.com/vikramvi/Selenium-Java

This works perfectly but same code doesn't work with Serenity

vikramvi/serenity-cucumber-wl@f489ece

https://github.com/vikramvi/serenity-cucumber-wl

`org.openqa.selenium.WebDriverException: unknown error: $ is not a function
(Session info: chrome=50.0.2661.86)
(Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds

Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=/var/folders/94/3dpydv3j2t7__4736h1pl0vr0000gn/T/.org.chromium.Chromium.j5W35o}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=50.0.2661.86, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a741033f320e8f40e5fd9c7eeba97231
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
at net.thucydides.core.webdriver.WebDriverFacade.executeScript(WebDriverFacade.java:372)
at com.vikramvi.cucumber.pages.WLC_ListPage.DragAndDrop(WLC_ListPage.java:189)
at com.vikramvi.cucumber.steps.serenity.WL3CSteps.selectListAndDoTaskDragAndDrop(WL3CSteps.java:84)
`

I think there is bug in framework method which tries to execute javascript.

Kindly have a look and let me know if I can give more info

**Comment by vikramvi** [comment]
@wakaleo  thanks for quick review but the code which actually not working is in public void DragAndDrop() 

javaScript = javaScript + "$('" + source + "').simulateDragDrop({ dropTarget: '" + target + "'});";

can you please check this method and let me know if I'm doing something wrong , as exact same code is working fine with normal selenium project.

As HTML5 drag and drop involves jQuery , I have to pass identifiers as CSS.

Kindly review again

**Comment by wakaleo** [comment]
So you are trying to perform the Drag-and-Drop in Javascript?

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 26 April 2016 at 2:38:40 PM, Vikram Ingleshwar (notifications@github.com) wrote:

@wakaleo thanks for quick review but the code which actually not working is in public void DragAndDrop()

javaScript = javaScript + "$('" + source + "').simulateDragDrop({ dropTarget: '" + target + "'});";

can you please check this method and let me know if I'm doing something wrong , as exact same code is working fine with normal selenium project.

As HTML5 drag and drop involves jQuery , I have to pass identifiers as CSS.

Kindly review again

**Comment by vikramvi** [comment]
Exactly @wakaleo  as Selenium standard drag and drop method doesn't work with HTML5

**Comment by wakaleo** [comment]
That’s fine, but Serenity does nothing special with Javascript execution other than a convenience method to access the Javascript Executor (which is not being used here) - I’m not sure where the problem could be.

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 26 April 2016 at 2:52:29 PM, Vikram Ingleshwar (notifications@github.com) wrote:

Exactly @wakaleo as Selenium standard drag and drop method doesn't work with HTML5

**Comment by vikramvi** [comment]
`javaScript = javaScript + "$('" + source + "').simulateDragDrop({ dropTarget: '" + target + "'});";
			      ((JavascriptExecutor)webDriver).executeScript(javaScript);`

this is working code with selenium ( without serenity ) , I've mentioned working project in first comment.

It's strange what may be going wrong wrt Serenity + Javascript

**Comment by wakaleo** [comment]
Maybe try running the javascript against the proxied driver? It might be the way the WebDriver instance is configured. But it looks like it can’t find JQuery in the page for some reason.

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 26 April 2016 at 2:56:49 PM, Vikram Ingleshwar (notifications@github.com) wrote:

javaScript = javaScript + "$('" + source + "').simulateDragDrop({ dropTarget: '" + target + "'});";
((JavascriptExecutor)webDriver).executeScript(javaScript);

this is working code with selenium ( without serenity ) , I've mentioned working project in first comment.

It's strange what may be going wrong wrt Serenity + Javascript

**Comment by vikramvi** [comment]
solved this issue by replacing $ with window.jQuery as per https://groups.google.com/forum/#!topic/selenium-users/zJ_egyg_GbA.

closing the false alarm

**Comment by wakaleo** [comment]
Thanks for the update Vikram
