### ISSUE TITLE
Extra entry in report when using JBehave and german story files

### ISSUE THREAD

**Issue by Ruschnik** [serenity-bdd/serenity-core#394]
Hi,

first of all: Serenity is a pretty cool tool. I am just evaluation some tools and I hope we can use it in our project. 

I try to use Serenity with JBehave and german story files. 

My story file starts with 

```
Erzählung:
Als ...
```

The name of the story file is `meine_erzählung.story` (stupid name, only for testing the language support ;-)).

Here is my problem: After the test run there are two links in my serenity report:
 
![image](https://cloud.githubusercontent.com/assets/18681916/14821471/2b902538-0bcb-11e6-8649-7f4ed8b7932b.png)

The link with no name is working the other one is not. 

My work-around is to add the name of the story in the first line of the story file:
```
Erzählung: Meine Erzählung
Als ...
```
This work fine (only one entry!) but the additional text is artificial and I do not want to use it. 

Some remarks to all the things I have done before:

I had to override the configuration like this:
```
	protected Locale locale() {
		return new Locale("de");
	}
	@Override
	public Configuration configuration() {
		Keywords keywords = new LocalizedKeywords(locale());
		Configuration configuration = super.configuration();
		configuration.useKeywords(keywords)
				.useStepCollector(new MarkUnmatchedStepsAsPending(keywords))
				.useStoryParser(new RegexStoryParser(keywords))
				.storyReporterBuilder().withKeywords(keywords);
		return configuration;
	}
``` 
At least this works. But of course the code is ugly. (Maybe it would be better to seperate the configuration and the instantiation of e.g. the SerenityReporter in `SerenityJBehave::defaultConfiguration(...)`. And the method `SerenityStories::configuration()` was probably not designed for changes/ overriding.)
OK. I also set 
> JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

because of the known issue https://github.com/serenity-bdd/serenity-core/issues/254
But there is still this problem with the extra entry in the report. 
Maybe it is caused by `net.thucydides.core.requirements.model::NarrativeReader`. At least the method 
```
    private boolean isMarkup(String line) {
        String normalizedLine = normalizedLine(line);
        return normalizedLine.startsWith("narrative:")
                || normalizedLine.startsWith("givenstory:")
                || normalizedLine.startsWith("background:")
                || normalizedLine.startsWith("meta")
                || normalizedLine.startsWith("@")
                || normalizedLine.startsWith("givenstories:");
    }
```
does not use any localization. 

What do you think?

**Comment by wakaleo** [comment]
Thanks for your detailed analysis. There are some known issues around discordances between the feature file names and the feature names, and this might be related to that problem. We will look into it!

**Comment by YamStranger** [comment]
Issue about discordances between the feature file names and the feature names will be fixed under serenity-bdd/serenity-jbehave/issues/17

**Comment by YamStranger** [comment]
@Ruschnik please take a look to answer of @cliviu under serenity-bdd/serenity-jbehave#17

**Comment by wakaleo** [comment]
Moved to https://github.com/serenity-bdd/serenity-jbehave/issues/86
