### ISSUE TITLE
Skip tag not working when running SerenityStory

### ISSUE THREAD

**Issue by lukateklic** [serenity-bdd/serenity-core#395]
Dear Serenity Support,

When running a JBehave story via a java class that extends SerenityStory, as a junit test, the @skip meta tag is being ignored. When running the same story via maven, with the serenity-aggregate profile, the @skip meta tag works.
This is inconsistent behaviour and we use the @skip meta tag extensively. Can you please investigate?

Sincerely,
Luka

**Comment by YamStranger** [comment]
Hello @lukateklic 
Please add examples, for now I can not understand what you mean.

**Comment by lukateklic** [comment]
Via IntellIJ/JUnit (SKIP DOES NOT WORK):
C:\dev\JDKs\jdk1.8.0_45\bin\java -ea -Dwebdriver.base.url=http://localhost:8080 -Dwebdriver.driver=chrome -Dwebdriver.chrome.driver=C:\<PRIVATE>\chromedriver.exe -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\dev\IntelliJ IDEA 14.1.3\bin" -Dfile.encoding=windows-1252 -classpath "<PRIVATE>" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 <PRIVATE>.AaDebug

Via mvn (SKIP WORKS):
C:\dev\JDKs\jdk1.8.0_45\bin\java "-Dmaven.home=C:\dev\IntelliJ IDEA 14.1.3\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\dev\IntelliJ IDEA 14.1.3\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=7533 "-Didea.launcher.bin.path=C:\dev\IntelliJ IDEA 14.1.3\bin" -Dfile.encoding=windows-1252 -classpath "C:\dev\IntelliJ IDEA 14.1.3\plugins\maven\lib\maven3\boot\plexus-classworlds-2.4.jar;C:\dev\IntelliJ IDEA 14.1.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.1.3 clean verify -Dstory.path=stories/**/*AaDebug*.story -Dwebdriver.base.url=http://localhost:8080 -P serenity-aggregate

JBehave Story (AsDebug.story):
Scenario: Test subscription
Meta:
**@skip**
@issue JIRA-3393
@tags product:subscriptions
Given the following....

**Comment by lukateklic** [comment]
accidentally closed.

**Comment by wakaleo** [comment]
Moved to https://github.com/serenity-bdd/serenity-jbehave/issues/85
