### ISSUE TITLE
serenity.use.unique.browser property not working

### ISSUE THREAD

**Issue by lukateklic** [serenity-bdd/serenity-core#396]
Dear Serenity Support,

We have been facing a performance hit to our automated tests since migrating to Serenity. The doco says to use the property serenity.use.unique.browser, and the Serenity code is still referring to thucydides.use.unique.browser. Neither of them work.
 
Could you please take a look at this and let us know if this is a bug in serenity or if we need to use a different approach?

Sincerely,
Luka

**Comment by YamStranger** [comment]
Hello @lukateklic 
Please close this issue as duplicate to serenity-bdd/serenity-jbehave/issues/72, thanks!

**Comment by YamStranger** [comment]
For better performance try to use phantomjs for example, such tests will be executed much faster

**Comment by lukateklic** [comment]
In theory phantomjs, i.e. headless should work, but in practice, especially with heavy JavaScript/Ajax sites, it's not that easy.

**Comment by lukateklic** [comment]
Will follow serenity-bdd/serenity-jbehave#72 thanks!

**Comment by YamStranger** [comment]
@lukateklic serenity-bdd/serenity-jbehave#72 ticket was updated.

Thanks!!
