### ISSUE TITLE
Serenity BDD 1.1.31 reports not showing "Pending" and "Ignored" tests

### ISSUE THREAD

**Issue by sampathgoud42** [serenity-bdd/serenity-core#397]
Hi,

I have recently updated my serenity version from 1.1.13 to 1.1.31. ( the reporting was fine with 1.1.13)

After upgrading to 1.1.31 I am observing that there's mismatch in html reports to console reports. 

Below is my actual test summary which is printed in maven/CMD console.
`Test run: 62, Failures: 5, Errors: 5, Skipped:2`

Coming to the serenity generated reports, the skipped tests(@Ignore Tests) are are not showing in 1.1.31 serenity html reports and fail test count should be 10 but displaying as 13. (Note: results.csv file is looking fine). Here's the serenity generated test summary.
`Total: 62, Pass: 48(77%), Fail: 13(21%), Pending:0, Ignored:0`

Hope you will better understand with screenshot attached. Thank you!

![ser1 1 31](https://cloud.githubusercontent.com/assets/5715875/14917128/1fb28a18-0e3b-11e6-97af-03d2fc56e877.JPG)

**Comment by YamStranger** [comment]
Hello @sampathgoud42 
Thanks for this issue!

Please add more info: 
Did you use serenity with junit, jbehave, cucumber?
Did you use latest version of serenity libs?  

>serenity html reports and fail test count should be 10 but displaying as 13

Please take a look at new chapter in our documentation: 
http://thucydides.info/docs/serenity-staging/#_detailed_description_of_aggregation_reports

You can see "additional" failed tests if you use examples table (csv file in your example) - and some of them fail.

In cmd you will found info before aggregation, during aggregation in reports added some additional info (I mean statistics include also examples table) - so it can be different.

**Comment by sampathgoud42** [comment]
Hi @YamStranger 

Serenity with Junit
All serenity libraries are updated to latest version i.e.1.1.31

Thanks,

**Comment by YamStranger** [comment]
@sampathgoud42 

I can not reproduce your issue. It seems that you face problem, that can be reproduced only with your build config. 

Here is report for next class:
```
@RunWith(SerenityRunner.class)
@WithTag("smoketest")
public class FilterTodosByStatus {

    @Managed
    WebDriver hisBrowser;

    @Steps AddItems addedSomeItems;
    @Steps DisplayedItems theDisplayedItems;
    @Steps OpenTheApplication openedTheTodoApplication;

    Actor joe = Actor.named("Joe");

    @Before
    public void joe_can_use_a_browser() {
        joe.can(BrowseTheWeb.with(hisBrowser));
        joe.has(openedTheTodoApplication);
    }

    //static int tries = 1;
    @Test
    @Ignore
    public void filter_by_active_tasks() {
        givenThat(joe).has(addedSomeItems.called("Buy the milk", "Buy Petrol"));
        andThat(joe).attemptsTo(CompleteItem.called("Buy the milk"));

        when(joe).attemptsTo(FilterItems.byStatus(Active));

        then(joe).should(seeThat(theDisplayedItems, contains("Buy Petrol")));
        //todo move to external build test
        //assertThat(tries++).isGreaterThanOrEqualTo(3);
    }

    @Test
    public void filter_by_completed_tasks() {
        givenThat(joe).has(addedSomeItems.called("Buy the milk", "Buy Petrol"));
        andThat(joe).attemptsTo(CompleteItem.called("Buy the milk"));

        when(joe).attemptsTo(FilterItems.byStatus(Completed));

        then(joe).should(seeThat(theDisplayedItems, contains("Buy the milk")));
    }

}
```

![before1](https://cloud.githubusercontent.com/assets/1667699/15051377/f40f1712-1300-11e6-9348-310cbf969159.png)

**Comment by YamStranger** [comment]
@sampathgoud42 
Can you give some tips to reproduce you problem? (some sample)
Thanks!

**Comment by wakaleo** [comment]
Hi @sampathgoud42,

We are having trouble reproducing this issue - could you try again with version 1.1.32 (which will be online in the next day or two), and if you are seeing the problem, provide us with a sample project that illustrates the issue?

**Comment by sampathgoud42** [comment]
HI John,

I couldn't share my original project details here. When I tried with sample
project, I am getting expected results and reports. Let me try with 1.1.32
and will update you.

On Mon, May 16, 2016 at 7:45 PM, John Ferguson Smart <
notifications@github.com> wrote:

> Hi @sampathgoud42 <https://github.com/sampathgoud42>,
>
> We are having trouble reproducing this issue - could you try again with
> version 1.1.32 (which will be online in the next day or two), and if you
> are seeing the problem, provide us with a sample project that illustrates
> the issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/397#issuecomment-219435630>
>



-- 
Thank you!

Regards,
S.Sampath

**Comment by YamStranger** [comment]
Hello @sampathgoud42 

Did you find expected results with latest serenity-core? 

Please close this ticket, if you feel that this problem already solved. 

Thanks!

**Comment by sampathgoud42** [comment]
Hello @YamStranger 

Yea, after upgrading to 1.1.36 results are displaying as expected. Thank you for the fix.
