### ISSUE TITLE
Require upper bound dependencies error for org.slf4j:slf4j-api:1.7.7

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#398]
I'm trying to run automation through jenkins and getting error SLF4J: Failed to load class “org.slf4j.impl.StaticLoggerBinder”

After updating to below 
`<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.12</version>
        </dependency>`

with serenity version 1.1.31 getting error

`[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.slf4j:slf4j-api:1.7.7 paths to dependency are:
+-com.microsoft.today:todayWebClientAutomation:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-core:1.1.31
    +-org.slf4j:slf4j-api:1.7.7
and
+-com.microsoft.today:todayWebClientAutomation:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-junit:1.1.31
    +-org.slf4j:slf4j-api:1.7.7
and
+-com.microsoft.today:todayWebClientAutomation:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-rest-assured:1.1.31
    +-org.slf4j:slf4j-api:1.7.7
and
+-com.microsoft.today:todayWebClientAutomation:0.0.1-SNAPSHOT
  +-org.slf4j:slf4j-simple:1.7.12
    +-org.slf4j:slf4j-api:1.7.12
and
+-com.microsoft.today:todayWebClientAutomation:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-core:1.1.31
    +-net.serenity-bdd:serenity-report-resources:1.1.31
      +-org.slf4j:slf4j-api:1.7.7`

**Comment by YamStranger** [comment]
Hello @vikramvi 
You see such error because of different version of libs what are you trying to use. 

It is problem of versions what you use in your pom and check what you have configured, here is link to maven chapter: https://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html

This ticket not about serenity, so I will close this ticket. 

Thanks

**Comment by vikramvi** [comment]
Agree with resolution
