### ISSUE TITLE
running cucumber tests in parallel not working as expected

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#399]
@YamStranger  I'm trying to migrate existing setup to Cucumber but post migration not able to run cucumber tests in parallel.

Is there any unique setting needs to be done for it ?

https://github.com/vikramvi/serenity-cucumber-wl/blob/b0c06eb44f93d2c6d056c430728f23485a144270/pom.xml 

This is what I'm trying , it works in non cucumber scenarios

Thanks in advance.

Regards,
Vikram

**Comment by vikramvi** [comment]
@wakaleo @YamStranger  this looks bug to me , as similar pom.xml is setup is able to run test cases parallel in docker containers but with cucumber setup it's running one after another instead of in paralle

https://github.com/vikramvi/serenity-cucumber-wl/blob/master/pom.xml

Please check if I'm doing something wrong which is related to cucumber ?

**Comment by vikramvi** [comment]
Is it because maven-surefire-plugin can run only junit test cases and not able to run cucumber features files in respective java class files in parallel mode ?

**Comment by wakaleo** [comment]
Yes, surefire cannot run feature files, only test classes that run feature files - it is the test classes that run in parallel.

**Comment by vikramvi** [comment]
In my case surefire is not running test classes in parallel , can you please have a quick look https://github.com/vikramvi/serenity-cucumber-wl and see what may be going wrong ?

**Comment by wakaleo** [comment]
Take a look at https://maven.apache.org/surefire/maven-failsafe-plugin/examples/fork-options-and-parallel-execution.html. Failsafe is a bit buggy for some aspects of parallel execution, but this works for one of my projects

<plugin>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>2.18.1</version>
    <configuration>
        <includes>
            <include>**/cucumber/*.java</include>
        </includes>
        <excludes>
            <exclude>**/*WithFailures.java</exclude>
        </excludes>
        <argLine>-Xmx512m</argLine>
        <parallel>classes</parallel>
        <threadCount>4</threadCount>
        <forkCount>4</forkCount>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
            </goals>
        </execution>
    </executions>
</plugin>

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better

http://johnfergusonsmart.com  | reachme@johnfergusonsmart.com
___________________________________________________


On 4 May 2016 at 2:52:33 PM, Vikram Ingleshwar (notifications@github.com) wrote:

In my case surefire is not running test classes in parallel , can you please have a quick look https://github.com/vikramvi/serenity-cucumber-wl and see what may be going wrong ?

**Comment by vikramvi** [comment]
@wakaleo  Thanks a ton again for quick help , it worked like charm.

Per you if failsafe is buggy , what is rock solid solution or you've any plans to integrate with serenity in future ?

I read about https://opencredo.com/test-automation-concepts-parallel-test-execution/ , will update in this thread

**Comment by wakaleo** [comment]
Closing this as questions are now answered on StackOverflow with the #serenitybdd tag.
