### ISSUE TITLE
Lack of report when test class spring wiring fails

### ISSUE THREAD

**Issue by CobaltChicken** [serenity-bdd/serenity-core#40]
We've found a problem when a Spring Framework based unit test fails to wire (@Autowire not matched by Spring bean). The test class is a @RunWith(SerenityRunner.class). We're running integration tests under gradle.

The wiring failure is only visible on the debug level output of gradle. It doesn't report it as a test failure. When building under Jenkins the build is not stopped by the failure, and the test reports report as clear.

Looking at the stack trace, and the SerenityRunner source the reporting context for the class seems to be closed in the finally clause of the run method, but the exception is just printStackTrace'd and rethrown. Looks like the finally will close the reporting context before anything useful is done with the exception.

**Comment by wakaleo** [comment]
I wasn't able to reproduce this, could you provide a sample project that illustrates the problem?

**Comment by YamStranger** [comment]
Hello @CobaltChicken, thanks for this issue. 

Please provide additional details to close this issue. It will be great if you provide some sample - and we will fix this issue as soon as possible. 

Thanks a lot!
