### ISSUE TITLE
Set timeout for PageObject.open() when application URL is non-responsive

### ISSUE THREAD

**Issue by im-zeeshan** [serenity-bdd/serenity-core#417]
My AUT recently goes into a non-responsive state and later crashes after a particular workflow is performed. We have around 100 test cases, the 47th test case causes this failure.

The issue is during regression run after the 48th test case i.e. application has gone into non-responsive state, whenever `PageObject.open()` method is invoked, it takes forever to timeout as the intended URL or homepage never loads completely. Suppose 'http://localhost:9000' is no longer available, it continues to wait for the page indefinitely. Why doesn't the method throw a timeout exception? 

I tried using:
`homepage.getDriver().manage().timeouts().pageLoadTimeout(3, TimeUnit.SECONDS);`
but it didn't timeout after 3 seconds.

I have specified the following timeout related properties in my `serenity.properties` file:
```
# Execution Timeouts
story.timeout.in.secs=7200
webdriver.timeouts.implicitlywait=1000
webdriver.wait.for.timeout=10000
serenity.timeout=5000
```

**Comment by wakaleo** [comment]
I don't think this is a Serenity issue. In Selenium opening an unavailable page (Driver.get()) will not fail if the URL is not available; it will just load an empty page or an HTML page with an error message, and fail with the usual timeout when you try to access an element. If it can access the URL, but the server is unresponsive, Selenium will wait until the page loads completely, and will block until the page finishes loading. So if the application is non-responsive for some reason, it will wait a long time. Is it possible that it is the application that crashes, and not the test that fails?

**Comment by YamStranger** [comment]
Hello @im-zeeshan 
Please give us some more info based on @wakaleo question to help you solve this problem. 

If you feel that this issue already have been solved - please close this ticket. 

Thanks!

**Comment by im-zeeshan** [comment]
The application back-end is majorly made up of micro-services. On the front-end;
_When_ the homepage service is non-responsive _then_ the application homepage does not load _but_ the service request is still waiting for a response _and_ the test is still waiting for `story.timeout.in.secs` which is currently set to 7200.

I'm not sure if this issue is reproducible outside of my application's test/dev/prod environment. Hence, I'm closing it.

**Comment by im-zeeshan** [comment]
Thanks @wakaleo & @YamStranger for the support.
