### ISSUE TITLE
regression: nested html tables in html reports

### ISSUE THREAD

**Issue by richard-melvin** [serenity-bdd/serenity-core#420]
With v1.1.31 and before, it was possible to include html markup (e.g. tables) in test logs, e.g. as:

```
@Step
public void showPacketContents(String html)
```

With v1.1.34, the contents of the html string seems to get processed by Formatter.formatWithFields which replaces the html markup with `&lt` etc. This doesn't seem to be overridable or configurable.

Could there be some way of indicating a particular argument to a Step method is already html-encoded and so shouldn't be re-encoded?

**Comment by richard-melvin** [comment]
![image](https://cloud.githubusercontent.com/assets/5872490/15540609/425450a2-2280-11e6-8881-281b6e04e116.png)

**Comment by wakaleo** [comment]
Thanks for pointing this out. This change is due to a bug fix where formatted HTML or XML was being incorrectly treated as part of the HTML page, but we will think of some way of allowing both behaviours.

**Comment by richard-melvin** [comment]
I can see there has been some markdown support added, which would work to solve this problem (as markdown is allowed to contain embedded html). However, the new code in Formatter.java seems to:

- render the markdown to html
- escape the html, e.g.  ` &lt;table class=&quot;packets&quot; width=&quot;100%&quot;`

Is that working as intended? Is there any way to customize or override that behavior?

**Comment by wakaleo** [comment]
Have you tried using the enable.markdown property, eg

enable.markdown = story,narrative,step

**Comment by richard-melvin** [comment]
yes, added `enable.markdown = [story,narrative,scenario,step]` to serenity.conf, and confirmed by debugger that it does call the `renderMarkdown` method.

**Comment by wakaleo** [comment]
Most likely a bug then (though you shouldn't have square brackets in the property value).
