### ISSUE TITLE
Aggregated report across several executions

### ISSUE THREAD

**Issue by Invictum** [serenity-bdd/serenity-core#421]
Is there is some way to build aggregated serenity report across several tests run?
I mean report that will show tests stability or something like this.
If no, do you planning to implement something situated?

**Comment by YamStranger** [comment]
Hello @Invictum, thanks for this questions:

>Is there is some way to build aggregated serenity report across several tests run?
I mean report that will show tests stability or something like this.

Now it is not possible

>If no, do you planning to implement something situated?

Will make this request as enhancement, but for now such update quite hard to implement.

**Comment by wakaleo** [comment]
You could use contexts to achieve this: https://johnfergusonsmart.com/running-tests-different-environments-browsers-serenity-bdd/
