### ISSUE TITLE
max.retries is broken in 1.1.33

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#422]

**Comment by wakaleo** [comment]
This feature was removed in 1.1.33 as it is a duplication of JUnit retries (http://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html).

**Comment by dsmt** [comment]
Thanks a lot!

**Comment by carlphilipp** [comment]
Is there anything similar for Gradle ?
