### ISSUE TITLE
Elements searched from FindAll annotation always return null in page object 

### ISSUE THREAD

**Issue by aquadrehz** [serenity-bdd/serenity-core#423]
In page object class I need to get element searched by Selenium annotation.
But **FindAll** always return null.

Example

>        BasePage .java

    @DefaultUrl("https://www.etsy.com/")
	public abstract class BasePage extends PageObject {
     @FindBy(css = "div")	WebElement testFindBy;
	 @FindBys({@FindBy(css = "div"),})	List<WebElement> testFindBys;
	 @FindAll({@FindBy(css = "div"),})	List<WebElement> testFindAll;
	public BasePage displaySize(String categoryName) {
		System.out.println(testFindBy.getText());      //>> Return null   
		System.out.println(testFindBys.size());        //>> Return null
		System.out.println(testFindAll.size());        //>> Return some amount
		return this;
	}

**Comment by YamStranger** [comment]
Hello @aquadrehz 
In this issue you have reported that find all always return null, but in next your issue: #424 you provide some working example (@FindAll({@FindBy(css = ".clear"),})) where all works fine. 

May be we should keep only one issue #424 ?

**Comment by aquadrehz** [comment]
Yes, you can merge this to that issue.
But need to note that **FindBys still work if it found only few element.**
Thank you for your advise

**Comment by wakaleo** [comment]
I just looked at the internals and I may have an idea of what's going on - I will investigate further.

**Comment by wakaleo** [comment]
This is fixed in 1.1.37-rc.2
