### ISSUE TITLE
ReportService.waitForReportGenerationToFinish keeps running forever

### ISSUE THREAD

**Issue by debae** [serenity-bdd/serenity-core#425]
At this moment 1 out of 6 runs with all our testsuites gives a problem due to the ReportService.waitForReportGenerationToFinish which keeps on running forever on our CI server.
So the last thing we can see in the logs is the output "AfterStories"

I noticed there was pull request 148 (https://github.com/serenity-bdd/serenity-core/pull/148) which should resolve this, so we upgraded to 1.1.34 but no solution for us.

We use bamboo and the build was hung, so to analyse this further I installed the build-hung-killer which also gave us the possible to get more info when this happened.

This was the outcome : 

26-May-2016 11:45:24    2016-05-26 11:45:23
26-May-2016 11:45:24    Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.80-b11 mixed mode):
26-May-2016 11:45:24    "pool-2-thread-2" prio=10 tid=0x00007fdb3cae7000 nid=0x2826 runnable [0x00007fdb354e1000]
26-May-2016 11:45:24       java.lang.Thread.State: RUNNABLE
26-May-2016 11:45:24            at java.util.HashMap.put(HashMap.java:494)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.indexChildRequirements(RequirementsServiceImplementation.java:117)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.indexChildRequirements(RequirementsServiceImplementation.java:119)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.indexRequirements(RequirementsServiceImplementation.java:91)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.getRequirements(RequirementsServiceImplementation.java:64)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.getAllRequirements(RequirementsServiceImplementation.java:302)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.getRequirementTypes(RequirementsServiceImplementation.java:237)
26-May-2016 11:45:24            at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:121)
26-May-2016 11:45:24            at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:86)
26-May-2016 11:45:24            at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:213)
26-May-2016 11:45:24            at net.thucydides.core.reports.ReportService.access$100(ReportService.java:26)
26-May-2016 11:45:24            at net.thucydides.core.reports.ReportService$1.run(ReportService.java:148)
26-May-2016 11:45:24            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
26-May-2016 11:45:24            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
26-May-2016 11:45:24            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
26-May-2016 11:45:24            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
26-May-2016 11:45:24            at java.lang.Thread.run(Thread.java:745)
26-May-2016 11:45:24    "pool-2-thread-1" prio=10 tid=0x00007fdb3cae5800 nid=0x2825 runnable [0x00007fdb355e3000]
26-May-2016 11:45:24       java.lang.Thread.State: RUNNABLE
26-May-2016 11:45:24            at java.util.HashMap.put(HashMap.java:496)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.indexChildRequirements(RequirementsServiceImplementation.java:117)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.indexChildRequirements(RequirementsServiceImplementation.java:119)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.indexRequirements(RequirementsServiceImplementation.java:91)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.getRequirements(RequirementsServiceImplementation.java:64)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.getAllRequirements(RequirementsServiceImplementation.java:302)
26-May-2016 11:45:24            at net.thucydides.core.requirements.RequirementsServiceImplementation.getRequirementTypes(RequirementsServiceImplementation.java:237)
26-May-2016 11:45:24            at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:121)
26-May-2016 11:45:24            at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:86)
26-May-2016 11:45:24            at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:213)
26-May-2016 11:45:24            at net.thucydides.core.reports.ReportService.access$100(ReportService.java:26)
26-May-2016 11:45:24            at net.thucydides.core.reports.ReportService$1.run(ReportService.java:148)
26-May-2016 11:45:24            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
26-May-2016 11:45:24            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
26-May-2016 11:45:24            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
26-May-2016 11:45:24            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
26-May-2016 11:45:24            at java.lang.Thread.run(Thread.java:745)
26-May-2016 11:45:24    "Darkroom Processing Line" daemon prio=10 tid=0x00007fdb004ee000 nid=0x27c4 in Object.wait() [0x00007fdb36555000]
26-May-2016 11:45:24       java.lang.Thread.State: WAITING (on object monitor)
26-May-2016 11:45:24            at java.lang.Object.wait(Native Method)
26-May-2016 11:45:24            - waiting on <0x00000000c6a1f618> (a java.util.concurrent.ConcurrentLinkedQueue)
26-May-2016 11:45:24            at java.lang.Object.wait(Object.java:503)
26-May-2016 11:45:24            at net.serenitybdd.core.photography.DarkroomProcessingLine.run(DarkroomProcessingLine.java:58)
26-May-2016 11:45:24            - locked <0x00000000c6a1f618> (a java.util.concurrent.ConcurrentLinkedQueue)
26-May-2016 11:45:24            at java.lang.Thread.run(Thread.java:745)
26-May-2016 11:45:24    "Java2D Disposer" daemon prio=10 tid=0x00007fdaf400b800 nid=0xf41 in Object.wait() [0x00007fdb356ee000]
26-May-2016 11:45:24       java.lang.Thread.State: WAITING (on object monitor)
26-May-2016 11:45:24            at java.lang.Object.wait(Native Method)
26-May-2016 11:45:24            - waiting on <0x00000000c57e8e38> (a java.lang.ref.ReferenceQueue$Lock)
26-May-2016 11:45:24            at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
26-May-2016 11:45:24            - locked <0x00000000c57e8e38> (a java.lang.ref.ReferenceQueue$Lock)
26-May-2016 11:45:24            at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
26-May-2016 11:45:24            at sun.java2d.Disposer.run(Disposer.java:145)
26-May-2016 11:45:24            at java.lang.Thread.run(Thread.java:745)
26-May-2016 11:45:24    "pool-1-thread-1" prio=10 tid=0x00007fdb3ca82000 nid=0xf3f waiting on condition [0x00007fdb36656000]
26-May-2016 11:45:24       java.lang.Thread.State: WAITING (parking)
26-May-2016 11:45:24            at sun.misc.Unsafe.park(Native Method)
26-May-2016 11:45:24            - parking to wait for  <0x00000000c5770108> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
26-May-2016 11:45:24            at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
26-May-2016 11:45:24            at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
26-May-2016 11:45:24            at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
26-May-2016 11:45:24            at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
26-May-2016 11:45:24            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
26-May-2016 11:45:24            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
26-May-2016 11:45:24            at java.lang.Thread.run(Thread.java:745)
26-May-2016 11:45:24    "com.google.inject.internal.util.$Finalizer" daemon prio=10 tid=0x00007fdb3c85b800 nid=0xf3b in Object.wait() [0x00007fdb36b83000]
26-May-2016 11:45:24       java.lang.Thread.State: WAITING (on object monitor)
26-May-2016 11:45:24            at java.lang.Object.wait(Native Method)
26-May-2016 11:45:24            - waiting on <0x00000000c537a8b0> (a java.lang.ref.ReferenceQueue$Lock)
26-May-2016 11:45:24            at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
26-May-2016 11:45:24            - locked <0x00000000c537a8b0> (a java.lang.ref.ReferenceQueue$Lock)
26-May-2016 11:45:24            at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
26-May-2016 11:45:24            at com.google.inject.internal.util.$Finalizer.run(Finalizer.java:114)
26-May-2016 11:45:24    "Service Thread" daemon prio=10 tid=0x00007fdb3c11a000 nid=0xf39 runnable [0x0000000000000000]
26-May-2016 11:45:24       java.lang.Thread.State: RUNNABLE
26-May-2016 11:45:24    "C2 CompilerThread1" daemon prio=10 tid=0x00007fdb3c117800 nid=0xf38 waiting on condition [0x0000000000000000]
26-May-2016 11:45:24       java.lang.Thread.State: RUNNABLE
26-May-2016 11:45:24    "C2 CompilerThread0" daemon prio=10 tid=0x00007fdb3c114800 nid=0xf37 waiting on condition [0x0000000000000000]
26-May-2016 11:45:24       java.lang.Thread.State: RUNNABLE
26-May-2016 11:45:24    "Signal Dispatcher" daemon prio=10 tid=0x00007fdb3c112800 nid=0xf36 waiting on condition [0x0000000000000000]
26-May-2016 11:45:24       java.lang.Thread.State: RUNNABLE
26-May-2016 11:45:24    "Finalizer" daemon prio=10 tid=0x00007fdb3c0f1800 nid=0xf35 in Object.wait() [0x00007fdb4070e000]
26-May-2016 11:45:24       java.lang.Thread.State: WAITING (on object monitor)
26-May-2016 11:45:24            at java.lang.Object.wait(Native Method)
26-May-2016 11:45:24            - waiting on <0x00000000c5238c48> (a java.lang.ref.ReferenceQueue$Lock)
26-May-2016 11:45:24            at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
26-May-2016 11:45:24            - locked <0x00000000c5238c48> (a java.lang.ref.ReferenceQueue$Lock)
26-May-2016 11:45:24            at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
26-May-2016 11:45:24            at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
26-May-2016 11:45:24    "Reference Handler" daemon prio=10 tid=0x00007fdb3c0ef800 nid=0xf34 in Object.wait() [0x00007fdb4080f000]
26-May-2016 11:45:24       java.lang.Thread.State: WAITING (on object monitor)
26-May-2016 11:45:24            at java.lang.Object.wait(Native Method)
26-May-2016 11:45:24            - waiting on <0x00000000c5273160> (a java.lang.ref.Reference$Lock)
26-May-2016 11:45:24            at java.lang.Object.wait(Object.java:503)
26-May-2016 11:45:24            at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
26-May-2016 11:45:24            - locked <0x00000000c5273160> (a java.lang.ref.Reference$Lock)
26-May-2016 11:45:24    "main" prio=10 tid=0x00007fdb3c008800 nid=0xf30 waiting on condition [0x00007fdb4443a000]
26-May-2016 11:45:24       java.lang.Thread.State: WAITING (parking)
26-May-2016 11:45:24            at sun.misc.Unsafe.park(Native Method)
26-May-2016 11:45:24            - parking to wait for  <0x00000000eed3d550> (a java.util.concurrent.FutureTask)
26-May-2016 11:45:24            at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
26-May-2016 11:45:24            at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
26-May-2016 11:45:24            at java.util.concurrent.FutureTask.get(FutureTask.java:187)
**26-May-2016 11:45:24          at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:173)**
26-May-2016 11:45:24            at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:154)
26-May-2016 11:45:24            at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:103)
26-May-2016 11:45:24            at net.serenitybdd.jbehave.SerenityReporter.generateReports(SerenityReporter.java:472)
26-May-2016 11:45:24            - locked <0x00000000c5317040> (a net.serenitybdd.jbehave.SerenityReporter)
26-May-2016 11:45:24            at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:454)
26-May-2016 11:45:24            at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
26-May-2016 11:45:24            at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:121)
26-May-2016 11:45:24            at org.jbehave.core.embedder.StoryRunner.runBeforeOrAfterStories(StoryRunner.java:86)
26-May-2016 11:45:24            at org.jbehave.core.embedder.StoryManager.runBeforeOrAfterStories(StoryManager.java:96)
26-May-2016 11:45:24            at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:91)
26-May-2016 11:45:24            at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:203)
26-May-2016 11:45:24            at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:159)
26-May-2016 11:45:24            at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:234)
26-May-2016 11:45:24            at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:133)
26-May-2016 11:45:24            at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:114)
26-May-2016 11:45:24            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
26-May-2016 11:45:24            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
26-May-2016 11:45:24            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
26-May-2016 11:45:24            at java.lang.reflect.Method.invoke(Method.java:606)
26-May-2016 11:45:24            at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:188)
26-May-2016 11:45:24            at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:166)
26-May-2016 11:45:24            at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
26-May-2016 11:45:24            at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:101)
26-May-2016 11:45:24            at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
26-May-2016 11:45:24    "VM Thread" prio=10 tid=0x00007fdb3c0eb000 nid=0xf33 runnable 
26-May-2016 11:45:24    "GC task thread#0 (ParallelGC)" prio=10 tid=0x00007fdb3c01e800 nid=0xf31 runnable 
26-May-2016 11:45:24    "GC task thread#1 (ParallelGC)" prio=10 tid=0x00007fdb3c020800 nid=0xf32 runnable 
26-May-2016 11:45:24    "VM Periodic Task Thread" prio=10 tid=0x00007fdb3c124800 nid=0xf3a waiting on condition 
26-May-2016 11:45:24    JNI global references: 296
26-May-2016 11:45:24    Heap
26-May-2016 11:45:24     PSYoungGen      total 45568K, used 8563K [0x00000000ec600000, 0x00000000efe00000, 0x0000000100000000)
26-May-2016 11:45:24      eden space 39424K, 13% used [0x00000000ec600000,0x00000000ecb0e970,0x00000000eec80000)
26-May-2016 11:45:24      from space 6144K, 55% used [0x00000000eec80000,0x00000000eefce4f8,0x00000000ef280000)
26-May-2016 11:45:24      to   space 5632K, 0% used [0x00000000ef880000,0x00000000ef880000,0x00000000efe00000)
26-May-2016 11:45:24     ParOldGen       total 74752K, used 64139K [0x00000000c5200000, 0x00000000c9b00000, 0x00000000ec600000)
26-May-2016 11:45:24      object space 74752K, 85% used [0x00000000c5200000,0x00000000c90a2fc8,0x00000000c9b00000)
26-May-2016 11:45:24     PSPermGen       total 46592K, used 35791K [0x00000000c0000000, 0x00000000c2d80000, 0x00000000c5200000)
26-May-2016 11:45:24      object space 46592K, 76% used [0x00000000c0000000,0x00000000c22f3ec0,0x00000000c2d80000)

**Comment by hazmeister** [comment]
I have had problems with this in the past when running on VMs with less than 4GB of RAM.  If this an option for you, I'd certainly investigate increasing it.

**Comment by debae** [comment]
We have elastic instances in bamboo which have 3.75 GB in memory and we only set the max of the JVM to -Xmx1512m -XX:MaxPermSize=768m.
So I will increase those values and try that as a workaround.

**Comment by hazmeister** [comment]
We were at the same RAM limit for the 32bit VMs we were using, so we moved to 64bit versions of Windows.

**Comment by YamStranger** [comment]
Hello @debae 
it seems that this some specific issue for your tests, can you give some example to help us to reproduce this issue?

**Comment by debae** [comment]
@hazmeister I increased the JVM memory settings , but no success.
@YamStranger , the issue does not seem to be related to one test, because it doesn't fail all the time, maybe related to the outcome of some test that's not written correctly or something. But no clue how to determine this. We only see that we have a problem in the AfterStories where the report is generated.

**Comment by YamStranger** [comment]
@debae thanks, it should not be related to JVM memory, but it can be related to making of screenshots, will check it.

Thanks for additional details!!

**Comment by wakaleo** [comment]
Could you check with 1.2.1-rc.6?

**Comment by wakaleo** [comment]
Report generation has been redone in 1.2.2-x. Closing this for now - please reopen if the problem persists.
