### ISSUE TITLE
Project name is not displayed on the main page of test report when it was set within serenity.conf

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#427]
Hello,

I have noticed minor issue when played with serenity-web-todomvc-journey
The project name is not displayed on the main page of test report when it was set within serenity.conf.

![ss1](https://cloud.githubusercontent.com/assets/2085160/15656263/082a566a-26ae-11e6-8a1d-8344f1cbf338.png)

However, the project name is displayed on stories level
![ss2](https://cloud.githubusercontent.com/assets/2085160/15656288/52f134a2-26ae-11e6-926c-7b6508cff29c.png)

 Is there a quick fix to it or other options?

Thanks

**Comment by YamStranger** [comment]
Hello @ilzul 
Will take a look, thanks

**Comment by cliviu** [comment]
hi @ilzul . The solution is to set the property 
`serenity.project.name` = Demo Project using Serenity and Cucumber
in the serenity.properties configuration file. Let me know if this answers your question. 
Thanks ! 
We will adjust soon the serenity-web-todomvc-journey.

**Comment by ilzul** [comment]
Hi @cliviu, 

Yes, when serenity.project.name is set within serenity properties, the project name is properly displayed. But I was planning to use only serenity.conf for all serenity properties, and seems like it doesn't work.

**Comment by cliviu** [comment]
Hi, @ilzul . I will take a look to see what the problem is.

**Comment by wakaleo** [comment]
Unfortunately this is a limitation due to the way Maven works - the Maven Serenity plugin works with a different class path to your normal project, so you need to add a dependency to your own project to the plugin dependencies.

**Comment by ilzul** [comment]
Thanks everyone for the clarifications ! 
Please close this issue.

PS: I have found a workaround for my project, just set the 'serenity.project.name' property within build.gradle:
`tasks.withType(Test) {
def env = Injectors.getInjector().getProvider(EnvironmentVariables.class).get()
env.setProperty("serenity.project.name", "Tested System on: " + env.getProperty("selectedEnv", ""))
}`
And run tests as following: gradlew clean test -DselectedEnv=my_test_environment aggregate
