### ISSUE TITLE
Serenity:check hangs at attempt to fail the build

### ISSUE THREAD

**Issue by agaidaichuk** [serenity-bdd/serenity-core#428]
After upgrade serenity-core to v.1.1.28 or later, we found that "check" functionality hangs once expected exception appeared in the log.
This functionality works fine with v.1.1.26.

**Comment by wakaleo** [comment]
Have you tried with 1.1.34?

**Comment by agaidaichuk** [comment]
Yes.
I've checked all major versions after 1.1.26.
This issue occurs with all of them.

**Comment by YamStranger** [comment]
Hello @agaidaichuk. Thanks for this issue!

Please add some short examples what you mean under "check" functionality.

Thanks!

**Comment by agaidaichuk** [comment]
Hi, @YamStranger .
Check functionality is : Check the test results in the output directory, and fail the build if there are errors or failures. 

You can find the log below:

`D:\Development\my-project>mvn serenity:check`
`[INFO] Scanning for projects...`
`[INFO]`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Building MY Test Framework 1.0-SNAPSHOT`
`[INFO] ------------------------------------------------------------------------`
`[INFO]`
`[INFO] --- serenity-maven-plugin:1.1.34:check (default-cli) @ my-test-framework ---`
`[INFO] Checking Serenity test results`
`[INFO] LOADING LOCAL PROPERTIES FROM D:\Development\my-project\serenity.properties`
`[INFO] LOADING LOCAL PROPERTIES FROM D:\Development\my-project\serenity.properties`
`[INFO] LOADING LOCAL PROPERTIES FROM D:\Development\my-project\serenity.properties`
`[INFO] webdriver.driver=chrome`
`[INFO] serenity.timeout=10`
`[INFO] serenity.take.screenshots=FOR_FAILURES`
`[INFO] serenity.maintain.session=true`
`[INFO] webdriver.timeouts.implicitlywait=5000`
`[INFO] jira.url=https://jira.fglsports.com`
`[INFO] webdriver.wait.for.timeout=30000`
`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time: 1.665 s`
`[INFO] Finished at: 2016-06-01T13:45:27+03:00`
`[INFO] Final Memory: 11M/27M`
`[INFO] ------------------------------------------------------------------------`
`---------------------------------------------------`
`constituent[0]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/aether-api-1.0.2.v20150114.jar`
`constituent[1]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/aether-connector-basic-1.0.2.v20150114.jar`
`constituent[2]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/aether-impl-1.0.2.v20150114.jar`
`constituent[3]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/aether-spi-1.0.2.v20150114.jar`
`constituent[4]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/aether-transport-wagon-1.0.2.v20150114.jar`
`constituent[5]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/aether-util-1.0.2.v20150114.jar`
`constituent[6]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/aopalliance-1.0.jar`
`constituent[7]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/cdi-api-1.0.jar`
`constituent[8]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/commons-cli-1.2.jar`
`constituent[9]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/commons-io-2.2.jar`
`constituent[10]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/commons-lang-2.6.jar`
`constituent[11]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/guava-18.0.jar`
`constituent[12]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/javax.inject-1.jar`
`constituent[13]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/jsoup-1.7.2.jar`
`constituent[14]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/jsr250-api-1.0.jar`
`constituent[15]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-aether-provider-3.3.3.jar`
`constituent[16]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-artifact-3.3.3.jar`
`constituent[17]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-builder-support-3.3.3.jar`
`constituent[18]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-compat-3.3.3.jar`
`constituent[19]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-core-3.3.3.jar`
`constituent[20]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-embedder-3.3.3.jar`
`constituent[21]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-model-3.3.3.jar`
`constituent[22]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-model-builder-3.3.3.jar`
`constituent[23]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-plugin-api-3.3.3.jar`
`constituent[24]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-repository-metadata-3.3.3.jar`
`constituent[25]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-settings-3.3.3.jar`
`constituent[26]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/maven-settings-builder-3.3.3.jar`
`constituent[27]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/org.eclipse.sisu.inject-0.3.0.jar`
`constituent[28]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/org.eclipse.sisu.plexus-0.3.0.jar`
`constituent[29]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/plexus-cipher-1.7.jar`
`constituent[30]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/plexus-component-annotations-1.5.5.jar`
`constituent[31]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/plexus-interpolation-1.21.jar`
`constituent[32]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/plexus-sec-dispatcher-1.3.jar`
`constituent[33]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/plexus-utils-3.0.20.jar`
`constituent[34]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/sisu-guice-3.2.5-no_aop.jar`
`constituent[35]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/slf4j-api-1.7.5.jar`
`constituent[36]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/slf4j-simple-1.7.5.jar`
`constituent[37]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/wagon-file-2.9.jar`
`constituent[38]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/wagon-http-2.9-shaded.jar`
`constituent[39]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/wagon-http-shared-2.9.jar`
`constituent[40]: file:/C:/Apache/apache-maven-3.3.3/bin/../lib/wagon-provider-api-2.9.jar`
`constituent[41]: file:/C:/Apache/apache-maven-3.3.3/bin/../conf/logging/`
`---------------------------------------------------`
`Exception in thread "main" net.thucydides.core.reports.TestOutcomesError: THUCYDIDES TEST FAILURES: ERROR COUNT: 2`
`        at net.thucydides.core.reports.ResultChecker.checkTestResultsIn(ResultChecker.java:32)`
`        at net.thucydides.core.reports.ResultChecker.checkTestResults(ResultChecker.java:24)`
`        at net.serenitybdd.maven.plugins.SerenityCheckMojo.execute(SerenityCheckMojo.java:50)`
`        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)`
`        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)`
`        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)`
`        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)`
`        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)`
`        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)`
`        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)`
`        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)`
`        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)`
`        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)`
`        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)`
`        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)`
`        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)`
`        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)`
`        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`
`        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
`        at java.lang.reflect.Method.invoke(Method.java:498)`
`        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)`
`        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)`
`        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)`
`        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)`

**Comment by wakaleo** [comment]
This looks like a Maven class loader issue. Could you post your pom.xml file?

**Comment by agaidaichuk** [comment]
The dummy project with 1 failed test is attached.

Please try to execute serenity:check maven goal.

[CheckIssue.zip](https://github.com/serenity-bdd/serenity-core/files/306661/CheckIssue.zip)
