### ISSUE TITLE
Integration with the Galenframework

### ISSUE THREAD

**Issue by hypery2k** [serenity-bdd/serenity-core#430]
I really like Serenity and I also like the automatic layout testing with the Galenframework. I would like to see integration with Galenframework in Serenity, especially the report. I think like the Spring integration a Junit rule would be needed. What do you think about integrating Galen in Serenity?

**Comment by RJ05** [comment]
Is there any progress to this Discussion ?

**Comment by wakaleo** [comment]
Galenframework integration is not on our roadmap at this stage but since both are open source projects you are certainly welcome to take a look yourself.

**Comment by hypery2k** [comment]
I could try to make integration steps. Should it be part of serenity afterwards? For just the execution of the tests it's rather easy, but the report integration could be harder

**Comment by wakaleo** [comment]
It could certainly be a serenity module once it is stable. Integrating with Screenplay would probably be the easiest approach (you just write your own interaction classes), but I haven't worked with the GalenFramework.

**Comment by AshrayViswanath** [comment]
We managed to integrate serenity with galen by using the following class


```
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

import org.openqa.selenium.WebDriver;

import com.galenframework.api.Galen;
import com.galenframework.junit.GalenJUnitTestBase;
import com.galenframework.reports.GalenTestInfo;
import com.galenframework.reports.HtmlReportBuilder;
import com.galenframework.reports.TestReport;
import com.galenframework.reports.model.LayoutReport;

public class GalenTest extends GalenJUnitTestBase {
	protected WebDriver driver;
	private static TestReport report;
	private static GalenTestInfo test;
	private static List<GalenTestInfo> tests = new LinkedList<GalenTestInfo>();;

	public GalenTest(WebDriver driver) {
		super();
		this.driver = driver;
	}

	public void test(String path, String name, String description) throws GalenTestFailedException {
		List<String> tags = new ArrayList<String>();
		tags.add("mobile");
			LayoutReport layoutReport = Galen.checkLayout(driver, path, Arrays.asList("mobile"));
			test = GalenTestInfo.fromString(name);
			test.getReport().layout(layoutReport, description);
			tests.add(test);
			new HtmlReportBuilder().build(tests, "target/galen-html-reports");
	}

	@Override
	public TestReport getReport() {
		if (report == null) {
			report = new TestReport();
		}
		return report;
	}

	@Override
	public WebDriver getDriver() {
		return driver;
	}

	@Override
	public void load(final String uri) {
		this.driver = driver;
	}

	@Override
	public WebDriver createDriver() {
		return driver;
	}

}
```

You can use pass the driver to the test method by using this :
`	
	WebDriver driver = (WebDriver )BrowseTheWeb.as(actor).getDriver();
`
