### ISSUE TITLE
Appium tests in Travis CI

### ISSUE THREAD

**Issue by hypery2k** [serenity-bdd/serenity-core#431]
Would be great to have some appium tests within Serenity to ensure that the integration is working.
I've already added some Android test in #415, but would be great to have iOS tests, too. 
To do this, Travis CI needs to be run in an OS X environment. That would also make the Android tests run faster, but would run all the Travis CI build in an OS X environment. 

What do you think about that?

**Comment by YamStranger** [comment]
@hypery2k great idea

Thanks!
