### ISSUE TITLE
waitFor doesn't work.

### ISSUE THREAD

**Issue by foxrafi** [serenity-bdd/serenity-core#432]
Hi,
I upgraded old Thucydides version to serenity-core-1.1.31.jar. 

What I found is that such a function **net.serenitybdd.core.pages.PageObject.waitFor**  does not work as previously. Sample code line:

`waitFor(ExpectedConditions.invisibilityOfElementLocated(deleteButtonBy));`

I had to replace it with this code that fortunately works fine :

`new WebDriverWait(getDriver(), 60).until(ExpectedConditions.invisibilityOfElementLocated(deleteButtonBy));
`
Do you know what has changed and why the first function does not work anymore.

Thank you
foxrafi

**Comment by wakaleo** [comment]
Hi,

I'm unable to reproduce this issue. Could you describe the behaviour that you are seeing in more detail?
