### ISSUE TITLE
[Question] How to display value get from step on report?

### ISSUE THREAD

**Issue by aquadrehz** [serenity-bdd/serenity-core#434]
I get some text from target page and want to display this value on report.

I've use testNG before it use command like Report.log("reportTest")
But, I can't any think like that on Manual.

**Comment by wakaleo** [comment]
There will be a feature like that in a future version. For now just use a custom @Step method and pass the message as a parameter, e.g

@Step
public void log(String message) {}

**Comment by aquadrehz** [comment]
Thank you for fast response.

**Comment by mail2savi** [comment]
Where should the @Step method be added? Should it be in the steps file or the actual implementation code?

**Comment by YamStranger** [comment]
@mail2savi @Step method should be added in @Steps class, you can find some examples in [manual](http://thucydides.info/docs/serenity-staging/#first-steps)

@aquadrehz if you feel that you problem is solved - please close this ticket. 
Thanks!

**Comment by mail2savi** [comment]
@YamStranger - Thanks for your response. 
I have loginsteps.java. loginpage.java and login.feature files. I get the application version in loginpage.java and printing it using logger and I am looking to include this version info in index.html. If i add the @step method in loginsteps.java, Can you please tell me where do I call the method from and pass the version information as a parameter.
Sorry for this lengthy question and going back and forth on this. I have been using serenity recently and also learning about it.
Thanks.

**Comment by YamStranger** [comment]
@mail2savi 
Please take a look at example: 
https://github.com/serenity-bdd/serenity-demos/blob/master/cucumber-webtests/src/test/java/net/thucydides/showcase/cucumber/steps/serenity/BuyerSteps.java

for example method in this Steps class
```
searchByKeyword(String keyword) 
```

after execution in it will be included in report as step of some test where it was executed, and passed parameter (keyword) will be included also.

**Comment by mail2savi** [comment]
Thank you @Yam Stranger.
I just have one last question. How do we pass value for the String keyword?Should it come from feature file or can we fetch it from LoginPage.java(Page object file) and pass it in @Step method. Because we are fetching the application version from UI and logging it in the console in LoginPage.java.
Thank you so much for your time!

**Comment by mail2savi** [comment]
Hi aquadrehz,
Were you able to get the data from UI and print it in the report?
Can you please help me, I have added getAppVersion(String version) method with @Step annotation in LoginSteps.java. But I am not sure where should this method be called from so that I can pass the application version number.
Thanks in advance!!

**Comment by aquadrehz** [comment]
@YamStranger example is good explanation.
They're JUnit file and need to be called from another Cucumber's step definition files.

For more detail I recommend to read more about page object approach or journal approach.

I didn't use the report yet so I can't answer that.

**Comment by aquadrehz** [comment]
I got the answer and work around already so I close this.

**Comment by Vic152** [comment]
Hi Guys, Is this implemented yet?
I would like to be able to log to Serenity report from cucumber.

I tried

**Comment by wakaleo** [comment]
https://johnfergusonsmart.com/embedding-custom-data-in-serenity-reports/

**Comment by Vic152** [comment]
Hey John,

Today I come to you with another question.
I would like to use pytest with pytest-bdd for my testing, BUT I want to
use serenity reporting.

Does serenity support this? I know pytest-bdd can generate cucumber like
JSON is there anyway to show it in serenity?

Kind Regards
Vic
-----------------------------------------------
www.bluegreenblack.com
www.thisfeelsgreat.blogspot.com
https://github.com/Vic152

For sensitive information please use encryption.

Public key available at: http://pgp.mit.edu/
Figerprint: 3D8C 48ED 42BD 4004 D23C  C455 8D80 7FB4 2C4D 7801

**Comment by chnmdey1** [comment]
Hi @wakaleo, I want to embed custom data (variable values) in serenity single page emailable report. 
Do we have any way as we have for living documentation, using Serenity.recordReportData()?

**Comment by wakaleo** [comment]
No, that's not currently supported

**Comment by chnmdey1** [comment]
Thanks @wakaleo for the quick response.
It would be great if we can have a feature like that in future.
The requirement currently, for a particular test case, is to print out in the emailable report, the number of records in the source and destination to compare, irrespective of failure or success.

**Comment by kavimukh** [comment]
@wakaleo 
I have following code
Scenario Outline: Check Page Status and JQuery
    Given Page <URL> is loaded

    Examples:
      | URL | SIZE |
      | https://www.google.com/online/ |

----
   @Given("Page {word} is loaded")
    public void pageURLIsLoaded(String pageURL) throws MalformedURLException {
        System.out.println("Navigating to => "+pageURL);
        commonActions.navigateTo(pageURL);
    }

---
CommonAction.java
    @Step("Page {word} is loaded")
    public void navigateTo(String goToURL) throws MalformedURLException {
        System.out.println("platform.contains "+ environmentVariables.getProperty("environment"));
        Serenity.setSessionVariable("return_user_flow").to(false);
        getDriver().navigate().to(goToURL);
    }

In Serenity Report it's not printing URL
Refer to screen capture
<img width="706" alt="Screenshot 2023-12-12 at 3 52 10 PM" src="https://github.com/serenity-bdd/serenity-core/assets/17184142/d05a7ceb-28a9-4f4f-b8de-74660badcff3">
