### ISSUE TITLE
[Question] How to add custom header in request?

### ISSUE THREAD

**Issue by kittugit** [serenity-bdd/serenity-core#435]
I'm new to Serenity.. using Serenity with JBehave.. Trying to add custom header in request.. 
Have added "net.serenity-bdd:serenity-browsermob-plugin:1.1.26" as dependency..  so it automatically starts browsermob proxy and executes test cases   but I'm not sure where and how to add header?

Tried the following snippet in different places.. but it doesn't work.. Your help would be appreciated..

```
FixtureProviderService fixtureProviderService = Injectors.getInjector().getInstance(FixtureProviderService.class);
		for(FixtureService fixtureService: fixtureProviderService.getFixtureServices()){
	         if(fixtureService instanceof BrowserMobFixtureService ) {
        
        	        BrowserMobFixtureService mob = (BrowserMobFixtureService) fixtureService;
                	BrowserMobProxy proxyServer = mob.getProxyServer();
                
	                proxyServer.addHeader("myheader", "myheadervalue");
                
        	   }
```

**Comment by YamStranger** [comment]
Hello @kittugit 

Thanks for this question, but we can't help you - this functionality out of serenity.  

Also inserting of headers  - not "user possible" operation so it should not be used in tests, may be you have some other way to test what you want.

Based on this issue https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2047#issuecomment-191485796
>Selenium does not provide this capability, as it is not something a user can do. It's
recommended you use a proxy to inject additional headers to the requests generated
by the browser.

you can use some proxy, with serenity bdd it can be done only with firefox: 
http://thucydides.info/docs/serenity-staging/#_providing_your_own_firefox_profile
or by using
```
serenity.proxy.http
serenity.proxy.http_port
serenity.proxy.type
serenity.proxy.user
serenity.proxy.password
```

Please close this ticket if you feel that your question have been answered or you find solution for your issue, thanks!

**Comment by kittugit** [comment]
Hi @YamStranger .. Thanks for your reply..  Will try the options you have specified..   I understand this is not serenity issue.. if i found concrete solution, will update this.. Now i'm closing this question..

**Comment by kittugit** [comment]
I'm able to add request headers using BrowserMobProxy.. 
1) added the following method in net.thucydides.browsermob.fixtureservices.BrowserMobFixtureService

```
private void addRequestHeader(){
    	for(String headerKey: environmentVariables.getKeys()){
    		if(headerKey.startsWith("browser_mob_proxy.header")){
    			String headerName = headerKey.substring("browser_mob_proxy.header".length() + 1);
    			threadLocalproxyServer.get().addHeader(headerName, environmentVariables.getProperty(headerKey, ""));
    		}
    	}
    	
    }
```
2) Called the method from initializeProxy()

```
private void initializeProxy(int port) throws Exception {
        setPort(port);
        addRequestHeader();
        threadLocalproxyServer.get().start(getPort());
    }

3) Added my request headers in serenity.properties as below

browser_mob_proxy.header.name1=value1
browser_mob_proxy.header.name2=value2
```

Thought might be useful for someone.. 

Thanks
