### ISSUE TITLE
New Security Policy in Jenkins breaks reporting

### ISSUE THREAD

**Issue by hazmeister** [serenity-bdd/serenity-core#437]
Jenkins 1.641 / Jenkins 1.625.3 introduces the Content-Security-Policy header to static files served by Jenkins.  This new restrictive header applies the following policies:
`sandbox; default-src 'none'; img-src 'self'; style-src 'self';
`
[Full details here](https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy).

Unsurprisingly, this breaks the display of the Serenity Report when using the [Thucydidies plugin](https://wiki.jenkins-ci.org/display/JENKINS/Thucydides+Plugin), as scripts and CSS used in the report  get blocked.

I appreciate that this plugin is not maintained here, but as the plugin has not seen an update in four years I thought I would raise the issue here where the community is active.

**Comment by wakaleo** [comment]
Unfortunately, this is beyond our control, and happens even when you publish the Serenity reports with the HTMLPublisher plugin. It is not a Serenity issue, but happens with any non-trivial HTML reports. Although we have plans to upgrade the Serenity reports soon, it is doubtful that we will be able to do so without using Javascript or CSS. I would raise this as an issue with the Jenkins team.

**Comment by hazmeister** [comment]
Cheers John,

I've rebuilt the plugin locally with the same patch the cucumber team made on their own reporting plugin.  I've raised it with the Jenkins team and submitted a [PR](https://github.com/jenkinsci/thucydides-plugin/pull/1), so we'll see if its accepted.

If anyone else needs the temporary fix now, you can temporarily grab a copy from the [Jenkins CI server](https://jenkins.ci.cloudbees.com/job/plugins/job/thucydides-plugin/2/net.thucydides.jenkins$thucydides/artifact/net.thucydides.jenkins/thucydides/0.2-SNAPSHOT/thucydides-0.2-SNAPSHOT.hpi).

In order to do a tidier fix for the Jenkins plugin, it would help if the report didn't inline any styles or Javascript.  Bundling the generated javascript and css sources would also help.  I appreciate this is a fair bit of work though.

**Comment by Constantinul** [comment]
Hello,

Any news about this? The temporary fix works, but I'm having trouble convincing my company to allow me to add it to Jenkins, given that it's not official (understandably).
Could you update the version in the Jenkins Plugins repository? It would make a big difference for a lot of people.

Thank you and looking forward to your reply.

**Comment by wakaleo** [comment]
Unfortunately we have no control or involvement in the HTMLPublisher plugin.

**Comment by hazmeister** [comment]
The original maintainer seems to have lost interest in the plugin- which was the main reason the PR remains unmerged. You're more than welcome to audit the changes I made in the pull request which generated the plugin file.

I copied the approach another plugin took, but there's almost certainly a better way of doing it. With some effort I could changed to the plugin maintainer, but you're the first person to ask in a year! I might revisit this or again but I can't make any promises.

**Comment by Constantinul** [comment]
It would be great if this got out, I know a lot of people who are using Serenity BDD and struggling with this Jenkins issue but just didn't think to post here. It was a last resort for me too, given that using the framework altogether could possibly be compromised by this (that would be a shame really).

**Comment by wakaleo** [comment]
As I mentioned, this is not something in our sphere of control; it is really a discussion for the Jenkins developers and contributors.
