### ISSUE TITLE
1.1.36 won't start Appium tests

### ISSUE THREAD

**Issue by Moustakas42** [serenity-bdd/serenity-core#439]
When I start my Appium tests from 1.1.36 nothing reaches Appium. Tests start and fail. Tests used to run under 1.1.31.

**Comment by hypery2k** [comment]
Did you follow the documentation at http://thucydides.info/docs/serenity-staging/#_running_tests_on_appium?

**Comment by Moustakas42** [comment]
I think this section doesn't exist anymore. I'm updating the description to clarify that tests ran fine under 1.1.31, barring a reporting issue.

**Comment by wakaleo** [comment]
Hard to tell what might be happening. Your best bet is to place a breakpoint in the WebdriverInstanceFactory class, in newAppiumDriver(), and see if anything odd is happening.

**Comment by hypery2k** [comment]
Here's the correct link http://thucydides.info/docs/serenity-staging/#_running_tests_on_appium

**Comment by Moustakas42** [comment]
I think it's the same :)

**Comment by hypery2k** [comment]
are you using gradle or maven?

**Comment by Moustakas42** [comment]
Maven.
________________________________

**Comment by Moustakas42** [comment]
Works with Serenity-Cucumber 1.1.9. Closing.
