### ISSUE TITLE
JSON is throwing exception, but  with null message

### ISSUE THREAD

**Issue by ptillemans** [serenity-bdd/serenity-core#44]
with serenity-core 1.0.44 :

$ gradle aggregate
...
:aggregate
Generating Serenity Reports for POS_REPORTS to directory /Users/pti/workspace/POS_REPORTS/target/site/serenity
this file was not a valid JSON Serenity test report: ca619da1feac2ae732e59d2e4590b237c6eb83cbb477f547a9fea10587ff2bed.json
null

BUILD SUCCESSFUL

**Comment by ptillemans** [comment]
[16:45:41] pti:POS_REPORTS git:(master*) $ json_verify <target/site/serenity/ca619da1feac2ae732e59d2e4590b237c6eb83cbb477f547a9fea10587ff2bed.json
JSON is valid

the JSON in question is:

{"name":"","testSteps":[{"number":1,"description":"When I run the \u0027pos_reports/import_future_pos_report_0_1\u0027 job","duration":142,"startTime":1427726183139,"result":"SUCCESS"},{"number":2,"description":"Then I have many rows in table \u0027stg_pos.i_fut_point_of_sales\u0027 in staging schema","duration":1830,"startTime":1427726183281,"result":"SUCCESS"}],"userStory":{"id":"import-distributor-reports","storyName":"Import distributor reports","path":"distributors/distributor_info_import.feature","narrative":"  \nIn order to analyse the performance of distributors\nas a Sales Analyst\nI need to get information about their sales and inventory","type":"feature"},"title":"","description":"","tags":[{"name":"Distributors/Import distributor reports","type":"feature"},{"name":"Distributors","type":"capability"},{"name":"Distributors/Distributor info import","type":"story"},{"name":"Import distributor reports","type":"feature"}],"startTime":1427726182978,"duration":2133,"driver":"firefox","manual":false,"result":"SUCCESS"}

**Comment by wakaleo** [comment]
I've added this JSON file to the unit tests, but it seems to be read correctly. Are you sure the Gradle plugin version in the buildscript dependencies the same as the one in the project dependencies? In the next version there will be a bit more info in the error message, so that might give some clues as well.

**Comment by ptillemans** [comment]
it seems all versions match up 

I redid the tests just to be sure:

[23:09:29] pti:POS_REPORTS git:(master*) $ gradle clean
:clearReports
:clean

BUILD SUCCESSFUL

Total time: 1.475 secs
[23:09:35] pti:POS_REPORTS git:(master*) $ gradle test aggregate
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:processTestResources
:testClasses
:test
:aggregate
Generating Serenity Reports for POS_REPORTS to directory /Users/pti/workspace/POS_REPORTS/target/site/serenity
this file was not a valid JSON Serenity test report: ca619da1feac2ae732e59d2e4590b237c6eb83cbb477f547a9fea10587ff2bed.json
null

BUILD SUCCESSFUL

Total time: 12.978 secs
[23:10:06] pti:POS_REPORTS git:(master*) $ cat build.gradle
apply plugin: 'java'

sourceCompatibility = 1.6
version = '1.0'

repositories {
    mavenCentral()
    jcenter()
}

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.0.44")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'

dependencies {
    testCompile 'net.serenity-bdd:core:1.0.44'
    testCompile 'net.serenity-bdd:serenity-junit:1.0.44'
    testCompile 'net.serenity-bdd:serenity-spring:1.0.44'
    testCompile 'net.serenity-bdd:serenity-cucumber:1.0.14'
    testCompile 'org.springframework:spring-jdbc:3.2.3.RELEASE'
    testCompile 'postgresql:postgresql:9.1-901-1.jdbc4'
    testCompile group: 'junit', name: 'junit', version: '4.11'
    testCompile 'org.slf4j:slf4j-simple:1.7.7'
}%

**Comment by wakaleo** [comment]
Are you still getting these errors with Serenity 1.1.x?

**Comment by ptillemans** [comment]
No, its working fine for me.

On Saturday, 24 October 2015, John Ferguson Smart <notifications@github.com>
wrote:

> Are you still getting these errors with Serenity 1.1.x?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/44#issuecomment-150784016>
> .
>


-- 
Sent from Gmail Mobile
