### ISSUE TITLE
Passed tests marked as skipped

### ISSUE THREAD

**Issue by Moustakas42** [serenity-bdd/serenity-core#441]
Running 1.1.31/Cucumber/Appium (1.1.36 won't play with Appium). Tests pass but are reported as skipped. Attaching POM + props. 
[pom+props.zip](https://github.com/serenity-bdd/serenity-core/files/306493/pom.props.zip)

**Comment by Moustakas42** [comment]
Solved. Let's make a note somewhere that @wip scenarios are always reporter as SKIPPED.

**Comment by YamStranger** [comment]
Thanks!
Created ticket: serenity-documentation/issues/83
