### ISSUE TITLE
Pie-Chart broken with gradle

### ISSUE THREAD

**Issue by hypery2k** [serenity-bdd/serenity-core#443]
With the recent serenity version the report seems somehow broken. If I ran a sample project with maven, it looks good, see https://martinreinhardt-online.de/jenkins/view/Demos/job/serenity_maven_sample/ and the pie chart is showing up, but in gradle the pie chart is missing: https://martinreinhardt-online.de/jenkins/view/Demos/job/serenity_gradle_sample/

Any ideas?

**Comment by wakaleo** [comment]
Thanks for the samples, this has helped us isolate the problem. This is a localisation issue (commas instead of dots in the Javascript). We are working on isolating the cause.

**Comment by wakaleo** [comment]
This should be fixed in the next release.
