### ISSUE TITLE
Serenity + RestAssured Integration: parameters values are always serialized as Arrays

### ISSUE THREAD

**Issue by viktor-klymenko** [serenity-bdd/serenity-core#444]
Serenity + Rest Assured Integration: parameters values are always serialized as Arrays. 
Example:

```
import static net.serenitybdd.rest.SerenityRest.*;
...
given()
                .param("param", "asasas")
                .log().all()
                .post("server.php");
...
```

Expected result:
**Request params: param="asasas"**

Actual result:
**Request params: param=["asasas"]**

Note: when in example above I try to add content type other then JSON or XML (e.g. `.contentType(ContentType.TEXT)`), the following exception occurs:
**java.lang.IllegalArgumentException: Cannot serialize because cannot determine how to serialize content-type text/plain**

Versions:
compile 'net.serenity-bdd:serenity-core:1.1.36'
compile 'net.serenity-bdd:serenity-rest-assured:1.1.36'

**Comment by YamStranger** [comment]
Hello @viktor-klymenko!

Thanks for this issue. 

It seems that this issue of rest assured, did you try use RestAssured.given instead? 

Thanks!

**Comment by viktor-klymenko** [comment]
Yes I tried this and it works correctly. Actually, this is my workaround - I create specification with parameters in separate class using RestAssured.given which serializes correctly and then provide this specification to SerenityRest.given().specification()

**Comment by YamStranger** [comment]
Hello @viktor-klymenko 

Thanks, yes it is bug, implementation will be updated

**Comment by YamStranger** [comment]
@viktor-klymenko fixed, should be included in next release.

**Comment by viktor-klymenko** [comment]
Great, thank you very much
