### ISSUE TITLE
suggestion: cut message for failed testcases during final crossreference generation

### ISSUE THREAD

**Issue by dmitriy-grablyov** [serenity-bdd/serenity-core#445]
Hi all,

Serenity has a very good feature - in a final report wherever you see your failed test case (on the index page, in requirements directories, in tag filters etc.) if you hover it you may see a browser tooltip ('title' property for the 'a' tag) showing the failure cause.

Now imagine you have a big number of tests with an enhanced requirements structure and different tags (sprints, teams, authors and so on). So because of this cross-reference generation if some testcase has failed failure information will be stored in every html document where the link to this testcase appears. If test case design was poor or really needed to make a big comparison (i.e. needed to check that some record has to be present in some collection) failure information size multiplied by the number of cross-references in the report may lead to the excessive report size growth.

In our case failure message was about 5Mb in size. Due to a big project structure, cross reference appeared in a final report about 300 times which led to an 1.5GB of extra space used to store the reports.

I'd suggest to cut such messages using some fixed threshold (e.g. 500 symbols) allowing to see the full message only at the page storing testcase result itself.

Best Regards,
Dmytro Grablov

**Comment by wakaleo** [comment]
Implemented in 1.1.37-rc.4

**Comment by QAutomatron** [comment]
Hello, @wakaleo 

Can you please expand message limit to more than 40 symbols? 

Most of our JUnit assert messages are cut off. For example : 'Assertion Error: ' is 18 symbols, and only 22 symbols left for custom message, and for part with "expected <> but was <>". Value that the issue author offered is more appropriate.

Thanks.

**Comment by dmitriy-grablyov** [comment]
Hi Evgenii,

But it just a hint for the hyperlink. You can always open the page with the
exact report and see the full message.

Best Regards,
Dmytro Grablov

**Comment by QAutomatron** [comment]
@dmitriy-grablyov yea, i know that. It's not at problem for me to do additional click. But our managers and some other people(who likes reports) want to see a full assertion error on report page as usual. But now our assertion errors are сut off half.

So it's the main reason why we downgrade from the latest release to older one, where are no message limit is set.

**Comment by dmitriy-grablyov** [comment]
Yes, that sounds as a case. But I wouldn't really recommend to do it over
100 symbols because as described above it may lead to excessive report sizes
