### ISSUE TITLE
Implement support for MarionetteDriver from Mozilla

### ISSUE THREAD

**Issue by bvklingeren** [serenity-bdd/serenity-core#447]
Please implement support for [MarionetteDriver](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver), since it is rapidly becoming the successor as driver for tests in Firefox. Since Firefox 47.0 it is becoming increasingly difficult to use the default Firefox driver and configuring it by hand is no easy job.

**Comment by vuthelinh** [comment]
Would you like to push high priority? I have waited long time for this feature.

Thanks YamStranger

**Comment by wakaleo** [comment]
Marionette need Selenium 3, which hasn't come out of beta yet, and is not feature-complete. When Selenium 3 is officially released, and when marionette is stable, we will implement this integration.

**Comment by SolidS28** [comment]
It seems that Selenium 3 was finally officialy released, I'd really appreciate that update to work with Serenity.

**Comment by wakaleo** [comment]
We are currently working on Selenium 3 support for the next release.

**Comment by wakaleo** [comment]
An update on this issue: Selenium 3 support is ready to integrate as soon as Selenium 3 is ready for production. However, after extensive tests, we have found that:
  1) The gecko driver is incomplete and unreliable (https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status); at the time of writing, the Serenity smoke tests fail using gecko and the latest Firefox version
  2) The Gecko support in Selenium 3 is still immature (not thread safe, unreliable for high volumes of tests).
  3) Although Selenium 2 is theoretically a "drop-in replacement", there are a number of internal API changes that mean you can't simply update the version in the pom.
  4) Other than (unreliably) supporting newer versions of Firefox, Selenium 3 adds very little in terms of features or bug fixes for most users.

**Comment by hypery2k** [comment]
I already tried using serenity with Selenium 3 and causing several issues, see https://travis-ci.org/hypery2k/serenity-core/builds/171593264

**Comment by wakaleo** [comment]
As stated above, although it is released (and up to 3.0.1), Selenium 3 does not seem to be production-ready yet. You can try the selenium-3 branch (https://github.com/serenity-bdd/serenity-core/tree/selenium-3) if you want to experiment.

**Comment by YevgenShem** [comment]
Hi John,

Latest commit for the selenium-3 branch https://github.com/serenity-bdd/serenity-core/tree/selenium-3 was on Nov 20, 2016.
Are all these points (https://github.com/serenity-bdd/serenity-core/issues/447#issuecomment-258074393) still valid?

**Comment by wakaleo** [comment]
You can follow the status of Marionette here: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status

**Comment by wakaleo** [comment]
Marionette support (aka Selenium 3.x) is supported since version 1.5.x
