### ISSUE TITLE
Serenity + Rest Assured Integration: The "restQuery" in the report doesn't contain Response Body

### ISSUE THREAD

**Issue by viktor-klymenko** [serenity-bdd/serenity-core#448]
Serenity + Rest Assured Integration: The "restQuery" in the report doesn't contain Response Body - the corresponding field in HTML report is empty. Actually, there are not such field in  "restQuery" element of corresponding json generated after test execution. 
The request was sent using following code:
```
given()
                .specification(requests.getRequest(parameter1, parameter2))
                .body(data)
                .log().all()
                .post("server.php");
```

The **baseURI** is:
`RestAssured.baseURI = "http://www.angularjshub.com";`

The **basePath** is:
`.setDefaultBasePath("code/examples/servercalls/01_HTTPService/")`

Moreover, field "responseCookies" actually contains headers of response instead of cookies.

Versions:
compile 'net.serenity-bdd:serenity-core:1.1.36'
compile 'net.serenity-bdd:serenity-rest-assured:1.1.36'

**Comment by YamStranger** [comment]
Helo @viktor-klymenko 

Can you add in your code check that response body is not empty? (using `then`).

About cookies and headers - I will check

Thanks!

**Comment by viktor-klymenko** [comment]
The following code is passed:

**Comment by viktor-klymenko** [comment]
Also, this request is sent through Fiddler as a proxy and I see in Fiddler that response actually contains expected body.

**Comment by YamStranger** [comment]
I see request and response body are equal in your test. Thanks!

**Comment by viktor-klymenko** [comment]
Actually, they are not fully equal. Let me show you requests and response bodies from Fiddler for this test:
**Request URL:** 
`http://www.angularjshub.com:80/code/examples/servercalls/01_HTTPService/server.php?param1=first%20param&param2=second%20param`
**Request Body:**
`this is data`

**Response Body:**
```
POST request received!
param1 = first param
param2 = second param
POST DATA: this is data
```

**Comment by viktor-klymenko** [comment]
I've found that Response Body was not written because of Response Type - test server (see above) returns response with Content Type "text/html", which is correpond to enum `ContentType.HTML`
And this content type is absent in the following method in RestReportingHelper class:
```
private static boolean shouldRecordResponseBodyFor(Response result) {
        final ContentType type = ContentType.fromContentType(result.contentType());
        return type != null && (ContentType.JSON == type || ContentType.XML == type
                || ContentType.TEXT == type);
    }
```
It looks like a defect because body with such content type may be required for failures analysis as well as json or xml.

**Comment by viktor-klymenko** [comment]
About cookies and headers - this defect can be reproduce in case if there are no cookies in response. The problem in the following code snippet in net.serenitybdd.rest.utils.RestResponseRecordingHelper#print method:
```
try (ByteArrayOutputStream output = new ByteArrayOutputStream();
                 PrintStream recordingStream = new PrintStream(output, true, StandardCharsets.UTF_8.toString())) {
                for (final LogDetail detail : logDetail) {
                    try {
                        ResponsePrinter.print(response, response.getBody(), recordingStream, detail, shouldPrettyPrint);
                    } catch (NullPointerException e) {
                        //can be thrown if some field like cookies or headers are empty
                    }
                    recordingStream.flush();
                    String recorded = new String(output.toByteArray(), StandardCharsets.UTF_8);
                    recorded = recorded.replaceAll("^(" +
                            "(Proxy:)|(Body:)|(Cookies:)|(Headers:)|(Multiparts:)|(Request path:)" +
                            ")\\s*\\n*", "");
                    recorded = recorded.replaceAll("^(<none>)", "");
                    recorded = recorded.replaceAll("\n$", "");
                    result.put(detail, recorded);

                }
```
The variable output is not cleared after first iteration of "for" loop and in case if there were no cookies in response the variable will not be modified in ResponsePrinter.print so the result item with name "COOKIES" will contain headers captured during previous interation

**Comment by YamStranger** [comment]
@viktor-klymenko Thanks a lot!

**Comment by YamStranger** [comment]
It seems that this bug is solved
