### ISSUE TITLE
Stories marked as @Manual are still being initiated

### ISSUE THREAD

**Issue by darekzborowski** [serenity-bdd/serenity-core#449]
Hello,

It seems that stories and scenarios which are marked as @Manual are still being initiated causing the overall test suite to execute longer.
Note that those tests are correctly marked as Manual and Pending in the report once the execution is done however it takes significantly longer to run the entire suite since @Manual tests are still going through the steps (initiating the web driver).
Stories and scenarios with @Manual property should simply be ignored.

Thoughts?

**Comment by wakaleo** [comment]
What version are you using?

**Comment by darekzborowski** [comment]
Sorry forgot to add.

core 1.1.31
jbehave 1.8.0
selenium 1.53.0

I looked through the change log between 31 and 36 but couldnt find anything related to this issue.

**Comment by wakaleo** [comment]
Try with 1.1.37-rc.4 on Bintray (https://bintray.com/serenity/maven)

**Comment by YamStranger** [comment]
It seems that this issue have solved, and ticket can be closed.
