### ISSUE TITLE
Webview Elements in Android Hybrid App if are not present in DOM, no exception is throwing

### ISSUE THREAD

**Issue by pisarenco92** [serenity-bdd/serenity-core#455]
hi, 

Here is a simple project: 

https://drive.google.com/file/d/0B8iGejPS1NKJUEdDZFhxTUx6cTA/view?usp=sharing

In ResetPasswordPage I have  @FindBy(id = "userInfo") WebElement emailTextField; which is present in DOM and test works well, but if an element is not found or is not present in DOM, no exceptions (change @FindBy(id = "userInfo1111") WebElement emailTextField;).

I tested without Serenity and everything is working well.

**Comment by wakaleo** [comment]
Could you give an example of the code you are using to access these elements?

**Comment by pisarenco92** [comment]
Of course.

**Comment by pisarenco92** [comment]
For iOS there aren't any problems.

**Comment by pisarenco92** [comment]
@wakaleo
 Is there any update on this issue?

**Comment by pisarenco92** [comment]
Same problem with 1.1.37-rc.6

**Comment by wakaleo** [comment]
We haven't looked at this issue yet. Most of the core Serenity developers have Macs, so reproducing it is tricky. Try stepping through the code with the debugger to understand what is going on more precisely.

**Comment by pisarenco92** [comment]
Finally found the solution.
I added the desired capability nativeWebScreenshot = true (only for Android) to make Appium use adb rather than ChromeDriver to get the screenshot.
