### ISSUE TITLE
checkPresenceOfWebElement fails for WebElementFacade even though element is present

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#459]
serenity-core : 1.1.37-rc.6 + Chrome browser ( Mac )

Below exception is thrown while executing line String name = listingCard.findBy(".card-meta-row").getText();

The element is present and visible on screen

net.serenitybdd.core.exceptions.SerenityManagedException: Timed out after 5 seconds waiting for net.serenitybdd.core.pages.WebElementFacadeImpl$1@de88ac6
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Vikrams-MBP', ip: '192.168.43.232', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_45'
Driver info: driver.version: unknown
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Vikrams-MBP', ip: '192.168.43.232', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at net.serenitybdd.core.pages.WebElementFacadeImpl.throwShouldBeVisibleErrorWithCauseIfPresent(WebElementFacadeImpl.java:766)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.checkPresenceOfWebElement(WebElementFacadeImpl.java:721)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.getText(WebElementFacadeImpl.java:902)
	at net.thucydides.showcase.cucumber.pages.SearchResultsPage.selectListing(SearchResultsPage.java:44)
	at net.thucydides.showcase.cucumber.steps.serenity.BuyerSteps.selects_listing(BuyerSteps.java:50)

**Comment by wakaleo** [comment]
Can you locate the element using native Selenium?

**Comment by vikramvi** [comment]
I used below code

List<WebElement> listingCards = getDriver().findElements(By.cssSelector(".listing-card:nth-child(" + listingNumber + ")"));
        WebElement listingCard = listingCards.get(0);
        String name = listingCard.findElement(By.cssSelector(".card-meta-row")).getText();

This doesn't throw any exception; but value of name variable is "". 
May be this null is causing to throw exception ? 

Thanks,
Vikram

**Comment by wakaleo** [comment]
The test may have failed at a previous point, in which case the driver will be disabled for the remainder of the test.

**Comment by vikramvi** [comment]
Checked in debug mode few times and found driver is alive. Also there is no failure before this step.

**Comment by wakaleo** [comment]
Then it sound's like a genuine issue with the element you are selecting not
being accessible from Selenium's perspective. Step through the code, but I
think you will find that it is just calling Selenium directly for this
logic. Try seeing if you can access the element via native WebDriver.

On 23 June 2016 at 13:47, Vikram Ingleshwar <notifications@github.com>
wrote:

> Checked in debug mode few times and found driver is alive. Also there is
> no failure before this step.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/459#issuecomment-228038969>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AADasvl-RmflmzboVHvU46FCve42ORyrks5qOoBMgaJpZM4I8mgv>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://johnfergusonsmart.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops
<http://johnfergusonsmart.com/programs/> in Agile Product Planning
<http://johnfergusonsmart.com/programs-courses/next-generation-agile-delivery-product-planning/>,
BDD Requirements Discovery
<http://johnfergusonsmart.com/programs-courses/mastering-agile-requirements-behaviour-driven-development/>,
 BDD, TDD and Clean Coding
<http://johnfergusonsmart.com/programs-courses/bdd-tdd-clean-coding/>,
and Advanced
BDD Test Automation
<http://johnfergusonsmart.com/programs-courses/advanced-bdd-test-automation/>
.
___________________________________________________

**Comment by vikramvi** [comment]
For this particular element; I found that isEnabled() is TRUE but isDisplayed() is FALSE.

Let me see how to solve this issue and update back

**Comment by vikramvi** [comment]
I could get this issue resolved with below solution

String name = getDriver().findElements(By.xpath("//div[@id='content']//div[@class='clearfix']//div[1]/a//div[contains(@class,'card-title')]")).get(listingNumber).getText();
    	double price = Double.parseDouble( getDriver().findElements(By.xpath("//div[@id='content']//div[@class='clearfix']//div[1]/a//span[contains(@class,'currency text')]")).get(listingNumber).getText());
    	
    
    	List<WebElement> listingCards = getDriver().findElements(By.cssSelector(".listing-card:nth-child(" + listingNumber + ")"));
        WebElement listingCard = listingCards.get(1);

Can you please clarify when to use WebElement vs WebElementFacade ?

**Comment by wakaleo** [comment]
If this page is dynamic, retrieving lists of elements and then accessing an element within the list is likely to be slow and error-prone; this may be one cause of the issues. Normally, WebElementFacade and WebElement should be interchangeable.

**Comment by vikramvi** [comment]
Thanks John for clarification. etsay site front end coding is not really automation friendly sadly. I have done fixes , will test again and submit PR on Monday.
