### ISSUE TITLE
Show steps for ignored scenarios in report

### ISSUE THREAD

**Issue by Invictum** [serenity-bdd/serenity-core#46]
I am using Serenity with jBehave and filter test scope via tags.
mvn clean integration-test -Dmetafilter=-manual serenity:aggregate
It works perfectly except one thing, in report whole scenario is marked as ignored and there are no steps related for it.

Is there a way to show all steps names for ignored scenario?

**Comment by wakaleo** [comment]
That is the normal behaviour of JBehave metafilters. You can use the @pending annotation in the story metadata to report on the steps in the pending scenario, e.g.

Scenario: Search for articles by keyword
Meta:
@pending
Given I want to buy a wool scarf
When I search for '<article>'
Then I should see only articles related to '<keyword>'
Examples:
| article      | keyword |
| wool scarf   | wool    |
| cotton shirt | cotton  |
