### ISSUE TITLE
Assert messages are corrupted in HTML report

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#460]
Assert messages from `org.junit.Assert` asserts like `assertEquals()` or `assertThat()` are not displayed in HTML report ‒ they are interpreted as part of HTML markup, please have a look at the screen below.
Original assert message (displayed in console):
`Password validation error message is incorect! expected:<Sorry, we don[Тt recognize that e-mail address. Please try a different e-mail address].> but was:<Sorry, we don['t recognize that email address. Please try again].>`
Generated HTML report page:
![screen](https://cloud.githubusercontent.com/assets/6312221/16299815/e5526cbe-3944-11e6-872f-3535931fc0b9.png)

Used versions:
**Serenity core:** ~~1.1.36~~ 1.1.37-rc.5 (switched from 1.1.21)
**Serenity-Jbehave:** 1.13.0
**Java:** 1.8.0_65
**OS:** WIndows 7x64

**Comment by hazmeister** [comment]
Was this working previously?  I moved from Hamcrest to AssertJ because it works better with the reports (and actually offers a reasonable syntax for asserts).

**Comment by scormaq** [comment]
Hi @hazmeister,
> Was this working previously?

As I can see, stack trace wasn't displayed well either in 1.1.21 version, but there was a helping preview message (so I didn't worry about stack trace a lot):
![Report for version 1.1.21](https://cloud.githubusercontent.com/assets/6312221/16483752/80fe0334-3ebe-11e6-85aa-3d79b81039dd.png)
(this one is same for 1.1.36 version - I was confused a little bit with new versions, original post contains screen for 1.1.37-rc.5)

_But_ in 1.1.37-rc.5 version this message has gone, so I have to view stack trace to find out failure cause:
![Report for version 1.1.37-rc.5](https://cloud.githubusercontent.com/assets/6312221/16483980/85a3047e-3ebf-11e6-94d2-ee6e20687c37.png)

>I moved from Hamcrest to AssertJ because it works better with the reports 

I agree, the issue is not reproducible for AssertJ, because it generates slightly different message:
**AssertJ**:
``[Password validation error message is incorect!] expected:<"Sorry, we don[`]t recognize that ema...> but was:<"Sorry, we don[']t recognize that ema...>``

**JUnit**:
``Password validation error message is incorect! expected:<Sorry, we don[`]t recognize that ema...> but was:<Sorry, we don[']t recognize that ema...>``
Unfortunately, for big projects like mine there not always a possibility to replace Hamcrest with AssertJ just for having nice stack traces in Serenity reports.

**Comment by YamStranger** [comment]
@scormaq, @hazmeister sure it is as bug and it will be fixed. 

Thanks for this ticket!!!
