### ISSUE TITLE
Instantiate two drivers.

### ISSUE THREAD

**Issue by pisarenco92** [serenity-bdd/serenity-core#461]
Hi,

I would appreciate if somebody show me how can I instantiate two drivers with Serenity, sure if this is possible?
 
Thanks.

**Comment by wakaleo** [comment]
You can do this very easily with the ScreenPlay pattern

**Comment by YamStranger** [comment]
@pisarenco92 please close this ticket, it seems to be solved. 

Thanks!!!

**Comment by pisarenco92** [comment]
Thanks @wakaleo
