### ISSUE TITLE
Aggregate report is not showing untested count properly (I got detail to reopen this)

### ISSUE THREAD

**Issue by aquadrehz** [serenity-bdd/serenity-core#465]
Refereed to closed issue from missing detail #304 

I've check on the test result execution via Eclipse.
The project downloaded from [Serenity demo project.](https://github.com/serenity-bdd/serenity-demos)

But the "Untested" column always calculated incorrectly.

**1st Execution report**
![serenity-304 untestmiscalculated](https://cloud.githubusercontent.com/assets/3850078/16439920/29ad9d7e-3de7-11e6-98f8-08bcce872138.png)

**2nd Execution report**
![serenity-304 untestmiscalculated002](https://cloud.githubusercontent.com/assets/3850078/16440348/3cf1fe62-3deb-11e6-8507-5360345e6172.png)

How does this calculate?
However, I'm sure it's bug.

FYI: the demo seem follow the example correctly.

**Comment by aquadrehz** [comment]
Is "Untested" = "Pending" amount + "Ignored" amount for each category?
For example: 2 pending, 3 ignored would count as **5 untested?**

**Comment by wakaleo** [comment]
"Untested" is literally any requirement without a test mapped against it. The inconsistency between the untested count and the total count.

**Comment by wakaleo** [comment]
The total will include any untested tests in the next version

**Comment by aquadrehz** [comment]
I saw the untested column is **not available anymore** so I recommend closing this task
@wakaleo 

![image](https://cloud.githubusercontent.com/assets/3850078/21128245/e159c052-c12b-11e6-82e7-4960038225e5.png)
