### ISSUE TITLE
Execute cucumber feature file via Maven ignore -Dtags parameter

### ISSUE THREAD

**Issue by aquadrehz** [serenity-bdd/serenity-core#466]
Using [cucumber-serenity demo project](https://github.com/serenity-bdd/serenity-demos/tree/master/cucumber-webtests)
And follow the [running scenario by tag manual](https://github.com/serenity-bdd/serenity-documentation/blob/master/src/asciidoc/tags.adoc).

I've try to execute Maven by following goals **but all are ignore the tag parameter.**
- clean verify -Dwebdriver.driver=firefox -Dtags="version:Release-2"
- clean verify -Dwebdriver.driver=firefox -Dtags="Release-2"

Add manual tag to file **but still not work.**
- clean verify -Dwebdriver.driver=firefox -Dtags="web"

Below is example feature need to included by these goal

```
@component:ui
@version:Release-2
@issue:ETSY-102

@web
Feature: Search by keyword
  In order for buyers to find what they are looking for more efficiently
  As a seller
  I want buyers to be able to search for articles by keywords

  Scenario: Search for articles by keyword
    Given I want to buy a wool scarf
    When I search for 'wool'
    Then I should see only articles related to 'wool'

......
```

**Comment by wakaleo** [comment]
Have you configured surefire/failsafe to pass the "tags" property into the test JVM?

**Comment by aquadrehz** [comment]
I modify and one from demo.
Can you give me the parsing example?

I use maven failsafe plugin.

**Comment by aquadrehz** [comment]
My current project use parameter follow the new updated document and passed correctly.
**-Dcucumber.options="--tags @declaration"**
instead of
-Dtags="web"

This's not bug anymore @wakaleo
