### ISSUE TITLE
Report resources are not copied when using IDEA dynamic classpath feature

### ISSUE THREAD

**Issue by misostc** [serenity-bdd/serenity-core#467]
I am manually running the tests from IDEA with a custom Main class, where dependencies are added to classpath in the command line. If the command line gets too long, IDEA suggests shortening the classpath, where it creates a new JAR file containing all the dependencies needed to run the program. The MANIFEST of the generated JAR file goes as follows: 

```
Manifest-Version: 1.0
Class-Path: file:/C:/Install/jdk-8u91-x64/jre/lib/charsets.jar file:/C
 :/Install/jdk-8u91-x64/jre/lib/deploy.jar file:/C:/Install/jdk-8u91-x
 64/jre/lib/ext/access-bridge-64.jar file:/C:/Install/jdk-8u91-x64/jre
 /lib/ext/cldrdata.jar.....
```

The tests run fine with this JAR on its classpath, however the test reports are missing resources needed to properly view the HTML document (javascript, styles and so on)

I suspect it might be from this method extracting resources from JAR which does not handle the case where JAR points to another JARs:

https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/thucydides/core/resources/ResourceList.java#L132

**Comment by wakaleo** [comment]
Thanks for raising this. Out of curiosity, why are you running the tests this way?

**Comment by wakaleo** [comment]
And no, the code is not designed to cater for jar files containing jar files.

**Comment by misostc** [comment]
Well, it's a bit complicated :smiley:. Basically, I want to have the tests compiled as one giant JAR file containing all the dependencies, but while developing, I constantly run the tests through IDEA, which has this feature.

**Comment by YamStranger** [comment]
@misostc can you push your project to github with idea as well. It seems quite interesting case, and it will be nice to make it work properly

Thanks!

**Comment by misostc** [comment]
@YamStranger unfortunately i cannot, it's work related. But if when I'll have some spare time, I will prepare some demo for you.

**Comment by YamStranger** [comment]
@misostc thanks!

Sure I will try to find some way to reproduce it, but for now it sounds not so ordinary (

**Comment by misostc** [comment]
I understand that this is not something critical, just a very miniscule issue :D although, it took me some time to detect what was going on.

**Comment by wakaleo** [comment]
We won't  be implementing this, but PRs are welcome.
