### ISSUE TITLE
Skip method parameters in report if description of step provided

### ISSUE THREAD

**Issue by a-en** [serenity-bdd/serenity-core#469]
Hi there!
Due to some specifics, toString() method of the parameter, that I pass to step is huge & non-readable. I thought that the one of the solution would be something like

`
@Step("Perform step1")
public void step1(Object someObj) {
  step2(object.getName());
}

@Step
public void step2(String name) {
//do something with name
}
`

So in the report I expected to see:
- Perform step1
  - Step 2: John

I wanted to completely replace the output from step1 in the report by providing explicit description without '{}' and avoid invoke toString() on someObj. This step1() should call step2(), which would produce much prettier output. But now I still get output of someObj's toString(). Is it somehow possible to handle this?

**Comment by Invictum** [comment]
@a-en
You may redefine toString of your object if this acceptable. In this case normal data will be displayed in report.

**Comment by a-en** [comment]
@Invictum 
Unfortunately it is not possible.

**Comment by YamStranger** [comment]
Hello @a-en 

Unfortunately now  such behaving is not implemented, so you should redefine toString method to do what you need. 

As for me such functionality can be implemented in future, some object can be passed as parameter to Step annotation to make it possible provide custom toString convention rules (as  @Qualifier for parameterized tests)

May be if you can not redefine toString method you can create some wrapper for it, and redefine only toString method - and delegate others?

**Comment by a-en** [comment]
Hi Yam!
Thanks for proposal, I was considering this option as well. Couple of thins preventing me from moving in that direction: amount of the wrappers that should be created and quantify of fields in these objects. I mean, it would be complicated to create universal toString() because based on the context some fields might be needed(initialized) or not.

So, I believe there are a couple of possible ways to add more flexibility to @Step annotation:
- add some method like `boolean skipParameters()`, so as result something like `@Step(skipParameters = true)` would result to skipping toString() calls for passed params;
- pass object which contains custom rules for processing passed parameters to report.

**Comment by YamStranger** [comment]
@a-en thanks for your ideas!!!
