### ISSUE TITLE
Serenity creates a failed report when working in a maven module

### ISSUE THREAD

**Issue by raphaeldovale** [serenity-bdd/serenity-core#47]
I have a multi-module maven project. We are creating a specific module for BDD scenarios and test cases using Serenity and I think I found an issue:

Say I have a module called 'documentation' where I write my stories. If I type something like this:

> mvn verify

or 

> mvn -pl documentation verify

Both commands will create a broken report site where some data will not be presented while the header menu will be incomplete (only "overall test results" and "requirements" are shown). But, if I type the following commands it works:

> cd documentation
> mvn verify

In that case, the data will be correctly presented and also the menu will be built in accordance.

I think the problem is something about the goal serenity:aggregate that, as far as I know, works grouping several data provided by jbehavior and build the reporting site.

**Comment by raphaeldovale** [comment]
Maybe I should write this issue in serenity-maven-plugin project?

**Comment by wakaleo** [comment]
Yes, this is related to the serenity-maven-plugin module. Thanks.

On 9 April 2015 at 01:06, Raphael do Vale A. Gomes <notifications@github.com
> wrote:

> Maybe I should write this issue in serenity-maven-plugin project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/47#issuecomment-90944474>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________
