### ISSUE TITLE
Test report is broken with serenity_version = "1.1.37-rc.6"

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#473]
Hi all,

I have tried using the latest serenity version - 1.1.37-rc.6. However, it seems like it has problems with test report - cannot open the details of failed tests
![step_details](https://cloud.githubusercontent.com/assets/2085160/16557800/802b9370-41ea-11e6-8394-925e19a4f885.png)

I was able to reproduce this issue on my test project, and using - https://github.com/serenity-bdd/serenity-demos/tree/master/jbehave-webtest-todomvc, with updated build.gradle:

`ext{
    serenity_version = "1.1.37-rc.6"
    serenity_jbehave_version = "1.13.0"
    serenity_cucumber_version = "1.1.6"
}
....
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.1.37-rc.6")
    }
....
compile group: 'net.serenity-bdd', name: 'browse-the-web', version: '1.1.34'
`

**Comment by cliviu** [comment]
hi, @ilzul . Thanks for the issue, we will take a look on it.

**Comment by cliviu** [comment]
hi @ilzul: I was not able to reproduce the isssue  with your gradle . I attach my gradle.build .. 
[build.gradle.zip](https://github.com/serenity-bdd/serenity-core/files/348730/build.gradle.zip)
I will need more details from you. Have you modified the project? because I have no failure when I run the project  https://github.com/serenity-bdd/serenity-demos/tree/master/jbehave-webtest-todomvc .
Please give me more information about  "cannot open the details of failed tests" . Is it a wrong link ? 
Thanks !

**Comment by ilzul** [comment]
Hi @cliviu 

I attached the project with test report (I hope that the archive file is acceptable) - 
[jbehave-webtest-todomvc.zip](https://github.com/serenity-bdd/serenity-core/files/349306/jbehave-webtest-todomvc.zip)
Could you please check it.

My issue is that I cannot open the content of failed test - js error occurs when I'm using the serenity_version = "1.1.37-rc.6". 

But when I'm changing the serenity_version to "1.1.36", everything works as expected.

Many thanks for your support!

**Comment by ilzul** [comment]
Also, I've noticed the following errors in console:

This one is expected, I haven't configured the webdriver.driver = phantomjs
`net.serenitybdd.demos.todos.OneUserAddTodoManyTimes > net.serenitybdd.demos.todos.jbehave.stepdefinitions.RecordTodoStepDefinitions.Given I need to <definition1>?? FAILED
    net.thucydides.core.webdriver.UnsupportedDriverException at RecordTodoStepDefinitions.java:14
        Caused by: net.thucydides.core.webdriver.UnsupportedDriverException at RecordTodoStepDefinitions.java:14
            Caused by: java.lang.IllegalStateException at RecordTodoStepDefinitions.java:14
`

Not sure why I got this error:
`net.serenitybdd.demos.todos.OneUserAddTodoUsingExamples > one_user_add_todo_many_times.story.classMethod FAILED
    java.lang.AssertionError                                      
    java.lang.RuntimeException                                    
        Caused by: net.thucydides.core.reports.ReportGenerationFailedError
            Caused by: java.util.concurrent.ExecutionException    
                Caused by: net.thucydides.core.reports.ReportGenerationFailedError
                    Caused by: java.nio.charset.UnmappableCharacterException
`
`102 tests completed, 48 failed, 51 skipped                         
:test FAILED                                                       
:aggregate                 
Generating Serenity Reports for jbehave-webtest-todomvc to directory D:\serenity-demos-master\jbehave-webtest-todomvc\target\site\serenity
Updating project.build.directory to D:\serenity-demos-master\jbehave-webtest-todomvcUpdating project.serenity.outputDirectory to D:\serenity-demos-master\jbehave-webtest-todomvc\target\site\serenity
FAILURE: Build failed with an exception.
               
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///D:/serenity-demos-master/jbehave-webtest-todomvc/build/reports/tests/index.html
               
* Try:         
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
               
BUILD FAILED   
               
Total time: 33.319 secs
`

**Comment by viktor-klymenko** [comment]
@ilzul take a look at this issue - #462 
Probably this is the reason of report generation failure in your case. You can apply workaround described in the issue and try to run your tests again
