### ISSUE TITLE
Annotating scenarios with tags - run two times(Serenity 1.1.37-rc.6)

### ISSUE THREAD

**Issue by pisarenco92** [serenity-bdd/serenity-core#474]
If I am annotating methods with 'WithTag' is executing two times, for example I have: 

@Story(Application.AppNavigation.NavigationMenu.class)
@RunWith(SerenityRunner.class)
public class AppNavigationTest {
@Managed(driver = "appium")
WebDriver driver;
@Steps
public HomePageSteps homeSteps;

@Test
@WithTag("Priority:High")
@Title("Product icon - 151")
public void selectProductIcon() {
homeSteps.selectProduct();
homeSteps.loadedHomePage();
}
}

When I run: mvn clean verify -Dtags="Priority:High",  the method is running two times.

**Comment by wakaleo** [comment]
I can't reproduce this with 1.1.37, could you check with this version?

**Comment by pisarenco92** [comment]
I checked with 1.1.37-rc.8 and no problems.

Thanks.
