### ISSUE TITLE
Query: How about using custom selenium grid from Groupon ?

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#476]
@wakaleo  can you please review this project https://github.com/groupon/Selenium-Grid-Extras

Instead of using standard grid , if serenity can use the one given by Groupon can be of more use IMHO

Please review.

Thanks & Regards,
Vikram

**Comment by wakaleo** [comment]
This is out of scope of Serenity as far as I can tell - Serenity will run against any URL you give it, it isn't coupled to any particular grid solution.
