### ISSUE TITLE
Incorrect Serenity Dashboard when last iteration failed using scenario outline

### ISSUE THREAD

**Issue by ankurindia07** [serenity-bdd/serenity-core#477]
Hi, In serenity dashboard I am facing this issue:
Dashboard not gets updated with pass scenario, while using scenario outline whenever there is fail occur in last iteration using scenario outline

In Attached scenario snapshot, there is 1 iteration which gets passed but still in dashboard pass count not gets updated.

Using serenity.version 1.1.36
![step1](https://cloud.githubusercontent.com/assets/20414559/16758435/0f61d6c2-482f-11e6-95be-b00187b3e99b.jpg)
![step2](https://cloud.githubusercontent.com/assets/20414559/16758445/233aad36-482f-11e6-84c9-de325dec5956.jpg)
![step3](https://cloud.githubusercontent.com/assets/20414559/16758446/29440aa6-482f-11e6-8b5a-02b57e73134a.jpg)

**Comment by YamStranger** [comment]
Hello @ankurindia07. 

Please refer to original [documentation](http://thucydides.info/docs/serenity-staging/#_detailed_description_of_aggregation_reports), if one example (**iteration**) failed - this test will be marked as failed, and counters of failed tests will be increased in amount of these examples (in failed test).

**Comment by ankurindia07** [comment]
Hello Sir
You are right but please see the attached snapshots. Passed test count shown as 0 but it should be 1 as there is 1 iteration which gets passed from total 3 iterations.

**Comment by YamStranger** [comment]
@ankurindia07 report is correct. 

in you test, there is failed iteration, that is why all test (and all iterations of it even successful) is marked as failed. 

If you test will contain only passed iterations (no failed iterations at all) then it will be marked as green.

**Comment by ankurindia07** [comment]
Sir, Have a look at these snapshots, this time my last example iterator gets passed and dashboard also gets updated with Pass count 1 but it should not be if i follow the concept what you have mentioned.
![step2_1](https://cloud.githubusercontent.com/assets/20414559/16834839/479c5e98-497b-11e6-8a38-f1037707e1f8.jpg)
![step2_2](https://cloud.githubusercontent.com/assets/20414559/16834853/51200780-497b-11e6-952e-9039267256ce.jpg)

**Comment by YamStranger** [comment]
@ankurindia07 this is known bug #205. All test should be marked as failed, if one of examples failed.

**Comment by YamStranger** [comment]
@ankurindia07  thanks this question, it seems to be solved. 

Please follow updates at #205 - fix will be provided soon. 

Thanks!!
