### ISSUE TITLE
Reporting: exception with message has missed root cause

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#482]
**Summary**: when test _re-throws_ occurred exception using constructor `public Throwable(String message, Throwable cause)`, the `cause` is missed in report (when used constructor without `message`, cause is present - see below).

**Description:** in some cases I would like to catch occurred exceptions and re-throw more specific exception, so I can get the failure reason more quickly. 
For example, I have next code in my page object:

```
    public boolean isProductFound() {
        try {
            return !findBy("//label[@id='search_results']").getText().isEmpty();
        } catch (final NoSuchElementException e) {
            // constructor takes message + cause
            throw new RuntimeException("Search engine is down!!!", e); 
        }
    }
```

_I exactly know, when element is not found (and WebDriver throws `NoSuchElementException`) - this happened because my Search engine is down, so I'm re-throwing occurred exception with corresponding message._

However, in HTML report I don't see the root cause of this re-thrown exception:
**Actual result:**
![baderror](https://cloud.githubusercontent.com/assets/6312221/16922432/20599c8c-4d1e-11e6-8ac7-9683c0c4ee20.png)

When thrown exception does not have message in constructor - everything is fine:

```
    public boolean isProductFound() {
        try {
            return !findBy("//label[@id='search_results']").getText().isEmpty();
        } catch (final NoSuchElementException e) {
            // constructor takes only cause
            throw new RuntimeException(e);
        }
    }
```

**Expected result:**
![gooderror](https://cloud.githubusercontent.com/assets/6312221/16922474/55fd8614-4d1e-11e6-8452-7f96f544b853.png)

Preconditions:
**Serenity-core**: 1.1.36
**Serenity-JBehave**: 1.13.0
**Java**: 1.8.0_65
**OS**: Windows 7x64

**Comment by YamStranger** [comment]
Thanks!! Will try to reproduce and will return to you

**Comment by scormaq** [comment]
Hi @YamStranger,
any luck with reproducing this issue?

**Comment by daivanov** [comment]
I have the same issue. In fail-safe log I have the following:

<error message="uk.co.jemos.podam.test.unit.steps.PodamInvocationSteps$$EnhancerByCGLIB$$262f6019 cannot be cast to java.lang.String" type="java.lang.ClassCastException">java.lang.ClassCastException: uk.co.jemos.podam.test.unit.steps.PodamInvocationSteps$$EnhancerByCGLIB$$262f6019 cannot be cast to java.lang.String
	at uk.co.jemos.podam.test.unit.features.basicTypes.PodamFactoryBasicTypesTest.podamShouldFillJavaStringType(PodamFactoryBasicTypesTest.java:172)
</error>

Which is not useful to say the least.

And in UI I see the following:

    uk.co.jemos.podam.typeManufacturers.TypeMultiplexerImpl.getValueForType(TypeMultiplexerImpl.java :76)     uk.co.jemos.podam.typeManufacturers.TypeMultiplexerImpl.getTypeValue(TypeMultiplexerImpl.java :57) uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java :519)     uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoWithFullData(PodamFactoryImpl.java :149)     uk.co.jemos.podam.test.unit.steps.PodamInvocationSteps.whenIInvokeTheFactoryForClassWithFullConstructor(PodamInvocationSteps.java :33)     uk.co.jemos.podam.test.unit.features.basicTypes.PodamFactoryBasicTypesTest.podamShouldFillJavaStringTypeWithFullConstructor(PodamFactoryBasicTypesTest.java :182) 

Root cause is not available anywhere. This make fixing tests a really huge pain.

**Comment by daivanov** [comment]
I have to wrap a failing line and log exception as a workaround to get a full error trace:

		try {
			thisCallWillThrowException();
		} catch (Exception e) {
			LOG.error("I cannot believe I have to do this", e);
			throw e;
		}

**Comment by loveshjain** [comment]
Hi @daivanov @YamStranger @scormaq Were you guys able to find the solution. I am also looking for something to report the exception in my serenity report
