### ISSUE TITLE
Need help in setting up thucydides BMP plugin into Jbehave

### ISSUE THREAD

**Issue by andrewcaksd** [serenity-bdd/serenity-core#483]
Hi,
I am bit new to serenity and would like to integrate thucydides bmp plugin into my project. I am using Demo Project using Serenity and JBehave as my project structure. I need to get the har files for each story. My test will be covering IE, chrome and FF browsers. Is there any documentation that I can follow.
My concerns are 
1. How do I pass proxy capabilities to the webdriver created. 
capabilities.setCapability(CapabilityType.PROXY, proxy);
I dont want to use this.driver = new ChromeDriver(capabilities); as I am using super constructor of page object. Is it possible to set from serenity.properties file? If yes then how?

2. Where do I need to create har file to record end to end test
server.newHar("test");

3. I get null when I call getHar() from @AfterStory. Is there a way I can get the same har object which was created earlier. At the moment I am creating har in @BeforeStory

@BeforeStory
	  public void setup() {
		ClasspathFixtureProviderService classpathFixtureProviderService = new ClasspathFixtureProviderService();
        List<FixtureService> fixtureServices = classpathFixtureProviderService.getFixtureServices();
        for(FixtureService fixtureService: fixtureServices){
            if(fixtureService instanceof BrowserMobFixtureService ) {
                service = (BrowserMobFixtureService) fixtureService;
                proxy = service.getProxyServer();
                proxy.newHar("testproxy");
          }
    }
}

Any suggestions would be really helpful.

**Comment by wakaleo** [comment]
Hi Andrew, this question is probably more appropriate for the Serenity Users Google Group list, where you will get answers and suggestions from the whole Serenity community.

**Comment by andrewcaksd** [comment]
Thanks.
