### ISSUE TITLE
Importing serenity-core into Eclipse via Gradle import feature

### ISSUE THREAD

**Issue by rrussell39** [serenity-bdd/serenity-core#486]
Hi - I'm trying to import the serenity-core project into Eclipse using the Gradle import feature.  I'm using STS (Spring Tool Suite 3.8 which implements Eclipse) and Eclipse Buildship (Eclipse Plug-ins for Gradle - STS Gradle migration).

When I choose to import gradle project and point it at serenity-bdd/serenity-core/gradle I get, "Could not find 'build.gradle' in the root folder. Is it a Gradle project?"

I'm a total newbie to Gradle so I think this is easily answered, but what is the best way for me to develop/extend serenity core using Eclipse/STS as my IDE?

Thanks,
Rob

**Comment by rrussell39** [comment]
Got a little further.  Now seeing an error ("One of setGitDir or setWorkTree must be called.") after clicking the 'Build Model' button.

<img width="586" alt="screen shot 2016-07-21 at 8 30 00 am" src="https://cloud.githubusercontent.com/assets/8116184/17028793/820178aa-4f1d-11e6-9d06-7a597da8cfb8.png">

Any help here appreciated.  
What IDE's are others using to work w/ the Serenity-core/java project?

**Comment by cliviu** [comment]
Hi, I'm using IntelliJ

**Comment by wakaleo** [comment]
I think most of the core contributors are using IntelliJ.

**Comment by rrussell39** [comment]
@wakaleo 
![screen shot 2016-08-25 at 1 30 40 pm](https://cloud.githubusercontent.com/assets/8116184/17985084/0f9aad32-6ac9-11e6-9cec-d1500f07e62e.png)

Hmm - Ok so I used IntelliJ and I had some success building (at least the log indicated so.)  I've recently installed IntelliJ Community Edition (2016.1.4 version Aug 2, 2016).  I decided to start fresh and reimport the Gradle project for serenity-core.  I get a Resolve Error after importing, "A conflict was found between the following modules: - org.seleniumhq.selenium:htmlunit-driver:2.20, org.seleniumhq.selenium:htmlunit-driver:2.21.  
Using MacOs/Java 8 and serenity code: 8b8165dd17c792a93231e0c34bd3f6dd4b588de2 "Updated Selenium to 2.53.1 to support Firefox 47"

Is this a known issue or a bone-head move on my part?

**Comment by rrussell39** [comment]
@wakaleo Ok - I have the project imported into IntelliJ CE 2016.1.4 version.  I can run build, make module, etc...but I'm so new to this IDE and gradle in general, I cannot find the resulting serenity-core 1.1.37 version after building.  I see a _build_ directory with _classes_ and _resources_ but I don't see a resulting built jar file.  I'm sure I'm missing something very basic about how do I build the serenity-core-1.1.3x.jar file?  Where are the assets created?

**Comment by wakaleo** [comment]
Closed for lack of activity.
