### ISSUE TITLE
JIRA comments for Serenity not appending but overwriting

### ISSUE THREAD

**Issue by amitAutoS** [serenity-bdd/serenity-core#491]
Hi!
I am trying to get the 2-way connectivity with Serenity & JIRA.
And I am noticing that every time I run a particular story, the comments are updated (which is OK), but it doesn't append the results.
Rather it over writes the entry already there.
Now, what if I have to look at the historical results of this particular issue in JIRA.

Is this something which should work(appending each run results)?

Thanks!

**Comment by cliviu** [comment]
Hi @amitAutoS . You are right, the current implementation updates the existing comment with the last test result. Currently there is no support for such historical view of the results.

**Comment by amitAutoS** [comment]
Thanks @cliviu 
I wanted to log all the historical runs for a particular issue if in case I want to refer to old runs.

**Comment by wakaleo** [comment]
Hi @amitAutoS, I'm afraid this wouldn't be feasible in the current version for a number of reasons, including that it would have to point to a different test result set each time (so they would all have to be stored somewhere), and when you run builds several times a day, it would result in a LOT of comments.

**Comment by mehakaggarwal** [comment]
Hi John,

We are using the  serenity version 1.9.45 and still facing the issue "JIRA comments for Serenity not appending but overwriting".
when can we expect the issue to be resolved.
Is there any workaround for this?

Thanks,
Mehak

**Comment by wakaleo** [comment]
This is intended behaviour but if you would like to contribute a PR to provide a different behaviour as an option, I’d be happy to review it.
