### ISSUE TITLE
Serenity capability tag is missing in Jenkins report

### ISSUE THREAD

**Issue by shreyTech** [serenity-bdd/serenity-core#493]
Hi, I am facing an issue while publishing Serenity reports in Jenkins using HTML publisher plugin.
The report seems fine but capability and theme tags are missing, the only tab which appears on the report are "Overall Test Results" and "Requirement", worth mrntioning that I can see the missing tags when running the reports locally its only an issue while generating reports in Jenkins.

Below is the plugin, which I have used.
https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin

Any help in resolving this issue will be very helpful.

Thanks,
Shrey

**Comment by wakaleo** [comment]
This is a known issue with recent versions of Jenkins and the HTML Publisher Plugin - it is not a Serenity issue, it is related to the Jenkins configuration that now by default puts severe limitation on the reported HTML.  (https://issues.jenkins-ci.org/browse/JENKINS-32026 and https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy for more details and on how to configure Jenkins to get it to work).

**Comment by shreyTech** [comment]
The issue we are seeing seems to be different from the issue reported in here (https://issues.jenkins-ci.org/browse/JENKINS-32026), we are seeing the reports, but Capability, epic and feature tabs are missing in the reports, we can only see requirements tab in it.
The jenkins issue you have mentioned seems to suggest that none of the reports were visible, please let me know if you think I am wrong here.

**Comment by wakaleo** [comment]
Are they only missing on Jenkins, or also on your local reports?

**Comment by shreyTech** [comment]
Just in Jenkins, I can see these in local reports.

**Comment by wakaleo** [comment]
This might be related to an issue with the requirements reporting that will be fixed in the next release.
