### ISSUE TITLE
Log information in serenity steps, so that it is readable in the report

### ISSUE THREAD

**Issue by ak120684** [serenity-bdd/serenity-core#494]
How to log some information so that it gets printed in the test report? I mean in the scenario steps, how would I print some important IDs and stuff, so that it is clearly visible whoever sees the report.

**Comment by wakaleo** [comment]
This feature will be integrated into an upcoming version in the near future.

**Comment by ak120684** [comment]
Hi @wakaleo - I want to provide some runtime information to the report - like for example, I want to provide a "request-id" to the report, so each step in the report has this information.
This is very critical for us in the report. 

How do I do this ?

**Comment by wakaleo** [comment]
Add a step method like this:

```
@Step
public void log(String message){}
```

Then just call this method:

```
log("My message");
```
