### ISSUE TITLE
Using webdriver 2.53.1 with Serenity Core » 1.1.37-rc.6 is throwing  upper bound dependencies error

### ISSUE THREAD

**Issue by lovetemple** [serenity-bdd/serenity-core#496]
After updating my firefox version to 47 and having known that webdriver 2.53.1 is version to use for browser tests to work.  I have updated Serenity Core from 1.1.36 to  1.1.37-rc.6 as suggested.  This hasn't solved the issue with firefox. so i have decided to add webdriver 2.53.1 dependecy in the POM. runing via maven ( mvn verify) throws below error . I have attached my POM file for your reference and please help how to use driver  2.53.1  with  serenity core 1.1.36  or .1.37-rc.6 ?
I have used (mvn dependency:resolve) and build is success.... but running the tests (mvn verify) throws error throwing  upper bound dependencies..
 Please modify the attached POM file for my tests to run .
[pom.txt](https://github.com/serenity-bdd/serenity-core/files/388300/pom.txt)

c:\cucumberSerenityDemo\mail>mvn verify
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Sample Serenity Cucumber project 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce) @ mail ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed
 with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.google.guava:guava:18.0 paths to
dependency are:
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-core:1.1.37-rc.6
    +-com.google.guava:guava:18.0
and
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-junit:1.1.37-rc.6
    +-com.google.guava:guava:18.0
and
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-rest-assured:1.1.37-rc.6
    +-com.google.guava:guava:18.0
and
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-core:1.1.37-rc.6
    +-net.serenity-bdd:serenity-report-resources:1.1.37-rc.6
      +-com.google.guava:guava:18.0
and
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-cucumber:1.1.8
    +-net.serenity-bdd:serenity-screenplay:1.1.34
      +-com.google.guava:guava:18.0
and
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-cucumber:1.1.8
    +-net.serenity-bdd:browse-the-web:1.1.34
      +-com.google.guava:guava:18.0
and
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-java:2.53.1
    +-org.seleniumhq.selenium:selenium-chrome-driver:2.53.1
      +-org.seleniumhq.selenium:selenium-remote-driver:2.53.1
        +-com.google.guava:guava:19.0
and
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-java:2.53.1
    +-org.seleniumhq.selenium:selenium-chrome-driver:2.53.1
      +-org.seleniumhq.selenium:selenium-remote-driver:2.53.1
        +-org.seleniumhq.selenium:selenium-api:2.53.1
          +-com.google.guava:guava:19.0
,
Require upper bound dependencies error for net.sourceforge.htmlunit:htmlunit:2.2
0 paths to dependency are:
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-core:1.1.37-rc.6
    +-net.sourceforge.htmlunit:htmlunit:2.20
and
+-com.bdd.serenitycorp:mail:0.0.1-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-java:2.53.1
    +-org.seleniumhq.selenium:htmlunit-driver:2.21
      +-net.sourceforge.htmlunit:htmlunit:2.21
]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.794 s
[INFO] Finished at: 2016-07-28T21:53:52+10:00
[INFO] Final Memory: 10M/26M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.
4:enforce (enforce) on project mail: Some Enforcer rules have failed. Look above
 for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

c:\cucumberSerenityDemo\mail>

**Comment by wakaleo** [comment]
This is a Maven configuration issue, not a Serenity bug, so it would be better answered on the Serenity Google Groups. You have a dependency conflict between Guava 18 (used by Serenity) and Guava 19 (used by "com.bdd.serenitycorp:mail"). To find out how to resolve this, see http://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html and http://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html.
