### ISSUE TITLE
After updating from Serenity 1.1.34 to 1.1.36 or 1.1.37-rc.6 -Dtags parameter opens two browser instance

### ISSUE THREAD

**Issue by birgerHB** [serenity-bdd/serenity-core#499]
I execute my test also with the -Dtags parameter when I write new tests to execute only one test.

In Version 1.1.36 and 1.1.37-rc.6 Serenity starts two browser instance and the test is fail.
In Version 1.1.34 is all ok.

**Comment by wakaleo** [comment]
Thanks for raising this; could you provide a sample project that reproduces the problem?

**Comment by birgerHB** [comment]
I have a simular project where two browser instance are starting in Version 1.1.36 and 1.1.37-rc.6.

[serenity_sample-master_V2.zip](https://github.com/serenity-bdd/serenity-core/files/399062/serenity_sample-master_V2.zip)

To execute the project in a grid I use this command:
`gradle clean test aggregate -Dwebdriver.remote.url=http://localhost:4444/wd/hub -Dtags="user:serenity"`

Only one test should start. The tag is defined in the class WikipediaHelpStoryIT.java

In Serenity Version 1.1.34 only one browser instance is open and in Version 1.1.36 and 1.1.37-rc.6 there are two browser instance.

**Comment by wakaleo** [comment]
Thanks for your sample project, this will certainly help trouble shoot the issue. We are looking at this issue now.

**Comment by spillai98** [comment]
Hi, 

I'm also experiencing this same behaviour in my project, both with and without -Dtags. 
I've a simple code that goes to a login page in chrome browser, enters username and password and then logs in. 

Right after the login, another browser instance gets opened and focus moves to it and the test fails. 

Waiting for this issue to get fixed. (Let me know if my sample project is needed for debugging). 

Thanks.

**Comment by wakaleo** [comment]
Hi,

Could you attach your sample project?

Thanks.

**Comment by spillai98** [comment]
This is a sample project for logging into Facebook and verifying the user name on Login page. 
After successful login, another browser instance gets opened. Please update the feature file for correct username and password for debugging. 

Thanks .

[SC_login.zip](https://github.com/serenity-bdd/serenity-core/files/405478/SC_login.zip)

**Comment by spillai98** [comment]
Hi,
Any update on this? Did you get a chance to see as to why it happens?

**Comment by wakaleo** [comment]
I tried but could not reproduce the issue; I intend to investigate the tagging issues further, but try with 1.1.37-rc.7 as there are some fixes in the browser session logic.

**Comment by hypery2k** [comment]
seems to be an threading/synchronize issue. We access the inject driver property to switch to iframe. if instead user getDriver() it's working with new versions

**Comment by wakaleo** [comment]
So it is working in 1.1.37-rc.7 or 1.1.37-rc.8?

**Comment by birgerHB** [comment]
yes it's working in 1.1.37-rc.7

**Comment by wakaleo** [comment]
Thanks for the update.
