### ISSUE TITLE
'No BaseStepListener has been registered' while using Serenity-rest-assured

### ISSUE THREAD

**Issue by himukin** [serenity-bdd/serenity-core#500]
Hi,
I am trying to usering serenity-rest-assured in place of rest-assured, but i get the following exception:

java.lang.NullPointerException: No BaseStepListener has been registered

```
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:96)
at net.serenitybdd.rest.utils.RestReportingHelper.registerCall(RestReportingHelper.java:77)
at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:257)
at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:72)
at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:62)
at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:25)
```

**Comment by wakaleo** [comment]
Could you provide a sample project to reproduce the issue?

**Comment by himukin** [comment]
Please find attached the sample project which is reproducing the issue.
[serenity-rest-assured-sample.zip](https://github.com/serenity-bdd/serenity-core/files/397235/serenity-rest-assured-sample.zip)

**Comment by himukin** [comment]
were you able to reproduce the issue with the sample project?

**Comment by tunovic** [comment]
I have the similar setup as @himukin using Serenity with Serenity Rest Assured.

This the only dependencies and plugins I have in the Maven POM:
 ```
 <properties>
	<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	<java.version>1.8</java.version>

	<serenity.version>1.1.42</serenity.version>
	<serenity.cucumber.version>1.1.10</serenity.cucumber.version>
</properties>

<dependencies>
	<dependency>
		<groupId>net.serenity-bdd</groupId>
		<artifactId>serenity-core</artifactId>
		<version>${serenity.version}</version>
	</dependency>
	<dependency>
		<groupId>net.serenity-bdd</groupId>
		<artifactId>serenity-rest-assured</artifactId>
		<version>${serenity.version}</version>
	</dependency>
	<dependency>
		<groupId>net.serenity-bdd</groupId>
		<artifactId>serenity-cucumber</artifactId>
		<version>${serenity.cucumber.version}</version>
	</dependency>

	<dependency>
		<groupId>org.codehaus.groovy</groupId>
		<artifactId>groovy-json</artifactId>
		<version>2.2.2</version>
	</dependency>
</dependencies>

<build>
	<pluginManagement>
		<plugins>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
				</configuration>
				<executions>
					<execution>
						<id>default-test</id>
						<configuration>
							<skip>true</skip>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</pluginManagement>

	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.5.1</version>
			<configuration>
				<source>${java.version}</source>
				<target>${java.version}</target>
			</configuration>
		</plugin>
	</plugins>
</build>
```

And I execute the request as following:
```
@Rule
private RestConfigurationRule rule = new RestConfigurationRule((RestConfigurationAction) SerenityRest::reset);

@Step
public String postOrder() {
	Response response = given().contentType("application/json")
			.when()
			.post("http://localhost:38080/order");

	return response.getHeader(HttpHeaders.LOCATION);
}
```

The stacktrace is also similar:
```
java.lang.NullPointerException: No BaseStepListener has been registered
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:109)
	at net.serenitybdd.rest.utils.RestReportingHelper.registerCall(RestReportingHelper.java:75)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:257)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:72)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:25)
```

Any idea?

**Comment by s2oBCN** [comment]
I have the same issue when I'm executing the feature directly from the IDE, in my case IntelliJ. But if execute this from Gradle then it's ok.
Maybe you executed the test from the IDE?

**Comment by mszalbach** [comment]
I have the same problem with the project at https://github.com/serenity-bdd/screenplay-pattern-todomvc. With Maven this works when running from IntelliJ it will fail because no BaseStepListener is registered. When not using screenplay pattern it works but when doing anything with Actors it will fail. The IntelliJ runner will set Main class to cucumber.api.cli.Main and the glue to "net.serenitybdd.demos.todos.cucumber.steps net.serenitybdd.cucumber.actors". I even tried to set one manually via StepEventBus.getEventBus().registerListener() but this did not work in the IDE. Any advice what can cause this problem in the IDE?

**Comment by himukin** [comment]
I have had the same problem while using Serenity RestAssured.
as a workaround, i switch to original RestAssured in IDE to do the
debugging and revert to Serenity with maven/gradle when the full fledged
report is needed.

**Comment by wakaleo** [comment]
How are you running the tests in IntelliJ?

**Comment by mszalbach** [comment]
Did some more tests and seems to work when running via starting an AllRunner like this:
`@RunWith(CucumberWithSerenity.class)
public class AllStories {}`

When starting directly from a feature file the cucumber plugin of IntelliJ will create an run config with a Cucumber Main class (cucumber.api.cli.Main). This will work for serenity tests but will fail when serenity RestAssured is involved in any step. Guess this is how the others are starting them from IntellliJ?

Exception for me is:

`java.lang.NullPointerException: No BaseStepListener has been registered`
`java.lang.ClassCastException: net.thucydides.core.webdriver.stubs.WebDriverStub cannot be cast to org.openqa.selenium.JavascriptExecutor`

I commented out all RestAssured code lines and the error is not thrown anymore. Seems the problem is always an other exception which is not correctly thrown because BaseStepListener is not correctly set when running via the IDE Cucumber Plugin. So seems to be a problem of the Cucumber Plugin since for Maven and the AllRunner everything is working. Will do some more tests tomorrow to also include screenplay but I guess this will also work as long as I start all my tests via AllStories.

**Comment by wakaleo** [comment]
Are you trying to run the tests directly from the feature files?

**Comment by mszalbach** [comment]
Yes the problems happen when running directly from the feature file.

**Comment by wakaleo** [comment]
OK, that's not supported (IntelliJ would need to know about the CucumberWithSerenity runner, which it doesn't). I don't know if there is a way to do that with IntelliJ, but it certainly won't work out of the box.

**Comment by wakaleo** [comment]
With Screenplay tests it may work better as they are more independent of instrumentation

**Comment by mszalbach** [comment]
Thanks for clarification. For me this is fine and I will go with the CucumberWithSerenity runner classes which I can be used from the IDE.

**Comment by wakaleo** [comment]
Thanks for the update.

**Comment by himukin** [comment]
Hi John,
the sample project i had attached earlier, reproduces this issue with maven.

**Comment by wakaleo** [comment]
You need to use the CucumberWithSerenity runner: http://serenity-bdd.info/docs/serenity/#_writing_executable_specifications_with_cucumber_and_serenity

**Comment by savita20** [comment]
I am also getting this same error. This is quite weird earlier I was able to run it from feature file also but not suddenly when I try to run it from feature file it is giving me this below error. I was not sure if I did something wrong in my code. I tried to debug but that didn't helped me to reach out this problem.

java.lang.NullPointerException: No BaseStepListener has been registered
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:900)
	at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:133)

And this is also true that if we run with CucumberWithSerenity runner classes  then I can able to run it. But I am not sure if that this is the case then earlier how I was able to run it from feature file...

**Comment by wakaleo** [comment]
You cannot run a Serenity test directly from the feature file.

**Comment by letrongtanbs** [comment]
I have a same issue when run: mvn clean verify
on serenity junit webtests demo project 
https://github.com/serenity-bdd/serenity-demos/tree/master/junit-webtests

**Comment by wakaleo** [comment]
> I have a same issue when run: mvn clean verify on serenity junit webtests demo project https://github.com/serenity-bdd/serenity-demos/tree/master/junit-webtests

That repo is out of date and not maintained. Try with https://github.com/serenity-bdd/serenity-junit-starter.

**Comment by letrongtanbs** [comment]
but https://github.com/serenity-bdd/serenity-junit-starter. is not enough like junit-webtests

**Comment by wakaleo** [comment]
I'm not sure what you mean. Use any of the starter projects, they are up to date. The projects in the repo you mentioned are not.
