### ISSUE TITLE
Blank Reports inside the folders, 

### ISSUE THREAD

**Issue by nshiveg** [serenity-bdd/serenity-core#501]
Hi John,

When we have a multiple runner class pointing to different folders present under test/resources/features.
Then the report will show empty pie chart for the features present inside the folders. We are facing this issue when we are doing parallel execution. Since parallel execution requires multiple runner class. 

Due to this issue we are not able see the scenarios pertaining to each of the feature file. Please up us.

Please help us.
![blank report page1](https://cloud.githubusercontent.com/assets/20845350/17414265/69696fe2-5aa2-11e6-8945-6c081482a6b5.png)
![folder structure](https://cloud.githubusercontent.com/assets/20845350/17414273/6f1f9268-5aa2-11e6-8b9d-6928c8d53c5e.png)

**Comment by nshiveg** [comment]
Blank Reports when using multiple runner class and each pointing to the different folder structure,

**Comment by wakaleo** [comment]
Hi, could you post a sample project that reproduces the issue?

**Comment by SubhasishC** [comment]
I am also facing the same issue.

Also, can you suggest how to specific respective output folder for each runner class. My project is not having any modules. It is a single project having one serenity property file.

Appreciate your help.

**Comment by wakaleo** [comment]
If you can provide a sample project that reproduces the issue we will be able to take a look.

**Comment by nshiveg** [comment]
[AutomationServer_0508_git.zip](https://github.com/serenity-bdd/serenity-core/files/403751/AutomationServer_0508_git.zip)

Hi John,

Attaching the project here. I have created 3 folders inside the feautres directory(Test1, Test2,Test3).

**Comment by nshiveg** [comment]
Please help me in knowing the issue. It has become a biggest concern, we are very much dependent on serenity.

I have created 3runner class and each of them are pointing to the each directory present in features, which are Test1,Test2,Test3. 

I am attaching the report generated for the above project.
[serenity.zip](https://github.com/serenity-bdd/serenity-core/files/403763/serenity.zip).


Inside the report click on Release>Regulus>Us4871 epic data collector. 

It will be blank. Now click on Test1 or Test2 or Test3 again blank.

**Comment by Amithpn** [comment]
Hi John,

We are also facing same issue and uploaded zip is somewhat similar to what we have. It will be very helpful if you can help us in this.

Regards

**Comment by wakaleo** [comment]
Upgrade to the latest versions of serenity-core and serenity-cucumber, and include the feature file in the requirements list, e,g:

```
serenity.requirement.types=Release,Epic,User Story,Feature
```

(General comment: It seems odd to have a User Story made up of Features, normally it's the other way around because the features are more persistent than the user stories, which can be disposed of after the sprint finishes.)

**Comment by nshiveg** [comment]
Hi John,

It started working after using the serenity version 1.1.37-rc.7

Thanks  a lot. You are tool is simply amazing.

**Comment by nshiveg** [comment]
One more question I have related to the "serenity.test.root".

What this parameter exactly do?

**Comment by wakaleo** [comment]
I'll write an article on this point shortly, but it is explained in http://serenity-bdd.info/docs/serenity/
