### ISSUE TITLE
Firefox v 48 throws unsupported Driver exception

### ISSUE THREAD

**Issue by Joshli2017** [serenity-bdd/serenity-core#505]
After updating firefox to version 48, my scripts are failing. I get following error:
ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

Scripts work fine on Firefox v 47

**Comment by wakaleo** [comment]
Firefox 48 is not supported by native WebDriver, you need to use the Marionette driver: https://github.com/mozilla/geckodriver

**Comment by bhardwaj-sumit** [comment]
Hi wakaleo,
what name should we need to add in serenity.properties file to use Marionette driver.
for chrome i am using as
driver= chrome.
for Marionette driver please suggest what i can use.
