### ISSUE TITLE
Serenity BDD Not able to take the screenshot

### ISSUE THREAD

**Issue by mandardjoshi** [serenity-bdd/serenity-core#508]
@wakaleo 

I am implementing the Serenity BDD for my web based project.My Test cases are running fine and producing the reports as well with the status as Pass or Ok.But serenity is not taking any screenshot for all the steps.I am using serenity.take.screenshots=AFTER_EACH_STEP in my Serenity.properties file.Please let me know if I am missing something for the screenshot.

**Comment by wakaleo** [comment]
Can you try with BEFORE_AND_AFTER_EACH_STEP?

**Comment by mandardjoshi** [comment]
@wakaleo Tried above change but still is not taking the screenshots.

**Comment by wakaleo** [comment]
What driver are you using? Could you post a sample project reproducing the issue?

**Comment by mandardjoshi** [comment]
@wakaleo 
Am referring to Selenium WebDriver.I do not have rights to upload my project.If you want then I will paste the code format here.Thanks.

**Comment by mandardjoshi** [comment]
@wakaleo 
It's working now after some changes.we can close it now.Thanks.

**Comment by diegof00** [comment]
Hi, I have same problem, Could you tell us what kind of changes are you talking about? 
I'm using serenity with jbehave and selenium. This is my serenity.properties
serenity.console.colors = true
webdriver.driver = provided
webdriver.provided.type = firefoxDriver
webdriver.provided.firefoxDriver = com.project.bdd.WebDriverSourceImpl
serenity.take.screenshots=BEFORE_AND_AFTER_EACH_STEP

Thanks

**Comment by wakaleo** [comment]
What is your WebDriverSourceImpl class (and why do you need to use a Provided driver)?

**Comment by ASfSDlS61TLT6eoP3Qb7** [comment]
I have the same problem. I have tried the screenshot option through maven, java property and hard coded. Nothing worked!

**Comment by wakaleo** [comment]
Screenshots arr handled by the driver implementations, not by Serenity. Can you provide a sample project that reproduces the issue?

**Comment by ASfSDlS61TLT6eoP3Qb7** [comment]
I think I do something wrong, because when I download the demo todo mvc application do work ...

**Comment by Heena303** [comment]
In a serenity project, i am running opening console and running some commands from there.
Is it possible to take console screenshots??

**Comment by wakaleo** [comment]
No, Selenium screenshots are of the browse only

**Comment by Heena303** [comment]
Even Serenity Also?

**Comment by wakaleo** [comment]
Serenity screenshots are just Selenium screenshots
