### ISSUE TITLE
Can't test sites with self signed certificates when using Browsermobproxy

### ISSUE THREAD

**Issue by hazmeister** [serenity-bdd/serenity-core#512]
When testing sites with a self signed certificate, browsermobproxy fails with a General SSLEngine problem, as it is unable to validate the certificate.  This behaviour is optional, and I've attempted to add it in PR #511

**Comment by wakaleo** [comment]
This should be included in the next release (1.1.38)

**Comment by hazmeister** [comment]
Working great! Thanks for the help!
