### ISSUE TITLE
Is there any provision to maintain historical executions in the serenity report ?

### ISSUE THREAD

**Issue by sudheerpujar** [serenity-bdd/serenity-core#513]
As  tests run repetitively is there any property to be set to maintain the history of executions.  
Currently it cleans the target folder as we execute `mvn clean verify` or `mvn clean test` command. 

I am aware that there is a property **serenity.outputDirectory**  that lets to change the location to store the reports.

**Comment by wakaleo** [comment]
No, but you can do this in Jenkins (for example) easily enough.
