### ISSUE TITLE
Unable to perform drag and drop action with serenity bdd 

### ISSUE THREAD

**Issue by larisagrecu** [serenity-bdd/serenity-core#518]
Hello,

I am trying to perform drag and drop action  between content of some text-box fields, that are similar to ones that appear, for example, when you compose an email in YAHOO or any other email server (AN, CC, BCC).  I type an email address to AN field, then I want to drag and drop that address into CC or BCC text-box.
 I have tried all solutions found on google related to Selenium WebDriver in java , including JavaScript, but nothing worked. I also tried this line of code, which is specific to serenity bdd:
**withAction().dragAndDrop(from, to).build().perform();**   , but with no result.  
Can anyone suggest any solution fro this, or is there anyone that faced something similar?

Thank you!
The page on which am trying to perform this action is similar with the screenshot attached.

![drag and drop action](https://cloud.githubusercontent.com/assets/22004716/18247881/fe6ed73c-737d-11e6-9641-c7aa77407609.PNG)

**Comment by hazmeister** [comment]
Which browser and version are you running the test one? This unlikely to be Serenity's fault, but this functionality her been broken in Selenium previously.

**Comment by larisagrecu** [comment]
Now I have Firefox 45.3 and Serenity latest version (1.1.37-rc.8) but didn' t worked with lower version either (I tried with Firefox 41.0 and Serenity 1.1.21)

**Comment by wakaleo** [comment]
This is almost certainly a WebDriver-related issue. Have you tried with other browsers such as Chrome?

**Comment by larisagrecu** [comment]
The only workaround that seems to work for booth Firefox and Chrome (latest versions) is the one posted  [here](http://stackoverflow.com/questions/24742539/unable-to-perform-html5-drag-and-drop-using-javascript-for-selenium-webdriver-te)

**Comment by wakaleo** [comment]
Closing this as it is a Selenium/WebDriver issue, not a Serenity one.
