### ISSUE TITLE
Unable to run parameterized  tests in parallel with a number of threads grater than the number of parameters 

### ISSUE THREAD

**Issue by larisagrecu** [serenity-bdd/serenity-core#519]
I am trying to run parameterized Serenity tests in parallel on multiple threads. 
The framework that I am using is build with tools like jUnit - Selenium  - Serenity  - and gradle. If I want to run tests in parallel on my local  machine, I am using  „@Concurrent(threads = ’nr of threads’)” annotation in my test class and should open as many threads as I specify. In my case,  the tests are parameterized to run with 4 parameters and even if the number of threads specified in annotation is greater than 4, only 4 browsers will be opened. 
Either Serenity is limited when it comes to run parametrized tests in parallel (it will open as many threads as the number of parameters), or some other changes needs to be done in the gradle file or somewhere inside the framework. 
Can someone clarify this to me? 
Thank you!

**Comment by wakaleo** [comment]
There is no relationship between the number of parameters and the number of threads.
