### ISSUE TITLE
Add support for class level spring annotations.

### ISSUE THREAD

**Issue by ScottDennison** [serenity-bdd/serenity-core#52]
Currently, you can use a @Rule of SpringIntegration to add support for spring method level annotations, such as @DirtiesContext. However, this does not support class level annotations, such as the class level @DirtiesContext. This is required when you have two classes that require fresh contexts, but the methods inside should all run with the dirty context.

For this, a companion to SpringIntegration is required that can be used with JUnit 4.9's @ClassRule, to run RunAfterTestClassCallbacks and RunAfterTestClassCallbacks.

If it would be helpful, I have written a class to do this (and a replacement for SpringIntegration, which extends a depracated class), as well as subclass of SerenityRunner that auto-adds both rules, and I could provide these, along with appropriate test classes.

**Comment by wakaleo** [comment]
Hi Scott,

Yes, certainly: create a pull request and I will incorporate it in the next
release.

Regards

John.

On 27 April 2015 at 22:45, Scott Dennison <notifications@github.com> wrote:

> Currently, you can use a @Rule <https://github.com/Rule> of
> SpringIntegration to add support for spring method level annotations, such
> as @DirtiesContext. However, this does not support class level annotations,
> such as the class level @DirtiesContext. This is required when you have two
> classes that require fresh contexts, but the methods inside should all run
> with the dirty context.
>
> For this, a companion to SpringIntegration is required that can be used
> with JUnit 4.9's @ClassRule, to run RunAfterTestClassCallbacks and
> RunAfterTestClassCallbacks.
>
> If it would be helpful, I have written a class to do this (and a
> replacement for SpringIntegration, which extends a depracated class), as
> well as subclass of SerenityRunner that auto-adds both rules, and I could
> provide these, along with appropriate test classes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/52>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by ScottDennison** [comment]
See pull request #70.

**Comment by ScottDennison** [comment]
This has now been merged, so I am closing the issue.
