### ISSUE TITLE
Feature page become broken when execute runner with feature path point to directory.

### ISSUE THREAD

**Issue by aquadrehz** [serenity-bdd/serenity-core#521]
In a report, linked feature page become broken when use Maven executes runner with feature path point to a directory instead of feature file.

![2016-09-07_11-15-48 featurepackagemakefeaturepagebroken](https://cloud.githubusercontent.com/assets/3850078/18299688/f597f218-74ec-11e6-9bdb-3a5c153263eb.jpg)

Step to reproduce.
- Clone serenity web demo project
  https://github.com/serenity-bdd/serenity-demos/tree/master/cucumber-webtests
- Open runner file
- Remove file name from "feature"
  Now it become
  "@CucumberOptions(features="src/test/resources/features/shopping_cart")"
- Execute project via Maven
  clean verify -Dwebdriver.driver=firefox
- Investigate generated report.

Actual result
- Click feature in related tags section link to broken feature page.
- Click feature in features tab link to broken feature page.

Expected result
- Click feature on anywhere linked to feature page correctly.

**Comment by wakaleo** [comment]
Could you try with serenity-code 1.1.41 and serenity-cucumber 1.1.10?

**Comment by aquadrehz** [comment]
Try and found no issue.
Bug fixed by another fix.
@wakaleo 

>     <properties>
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <serenity.version>1.2.1-rc.6</serenity.version>
>         <serenity.maven.version>1.2.1-rc.6</serenity.maven.version>
>         <serenity.cucumber.version>1.1.13</serenity.cucumber.version> 
>     </properties>
