### ISSUE TITLE
Getting Network Requests

### ISSUE THREAD

**Issue by hypery2k** [serenity-bdd/serenity-core#526]
Are there plans to somehow provide access to the networking request the browser sends?

**Comment by wakaleo** [comment]
What did you have in mind?

**Comment by hypery2k** [comment]
I'm having a use case with a customer that I need to somehow verify that if I click a button my tracking code sends the correct request to the tracking backend.

**Comment by wakaleo** [comment]
Would it not be better to check the outcome, e.g. check that the right tracking code has been added to the backend, rather than checking that it has been sent across the network?

**Comment by hypery2k** [comment]
Thats what we already doing, but we have some tracking code, where we don't have access to the backend and also would be nice to somehow check the "pure" requests

**Comment by hazmeister** [comment]
I'm looking at addding this to my test suite currently.  In theory, you should be able to include the browser mob proxy plugin:
`<dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-browsermob-plugin</artifactId>
    <version>1.1.39</version>
</dependency>`

This ticket provides some hints as to how you can interact with the proxy to create a HAR file which you can then query for individual requests:
https://github.com/serenity-bdd/serenity-core/issues/100

**Comment by wakaleo** [comment]
I'll close this as the feature itself (beyond integration with browsermob and such) is beyond the scope of Serenity BDD.
