### ISSUE TITLE
serenity- jbehave-archetype doen't work

### ISSUE THREAD

**Issue by Dmitriy84** [serenity-bdd/serenity-core#53]
Steps:
1. mvn archetype:generate
2. choose 481
3. any version
4. run "mvn clean verify"
5. See 
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Concurrency config is parallel='classes', perCoreThreadCount=true, threadCount=2
, useUnlimitedThreads=false

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding Cp1251, i.e. b
uild is platform dependent!
[INFO]
[INFO] --- serenity-maven-plugin:1.0.23:aggregate (serenity-reports) @ webtests2
 ---
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
[INFO] Reading requirements from net.thucydides.core.requirements.FileSystemRequ
irementsTagProvider@9c3057
[INFO] Reading requirements from net.thucydides.core.requirements.PackageAnnotat
ionBasedTagProvider@1941489
[INFO] Requirements found:[]

If you will run debug with jUnit then see that all works.

**Comment by wakaleo** [comment]
Should be working now
