### ISSUE TITLE
serenity.batch.strategy=DIVIDE_EQUALLY puts the same class in multiple batches

### ISSUE THREAD

**Issue by adlenton** [serenity-bdd/serenity-core#531]
Hey guys :)
Today I tried to setup parallel tests according to the serenity manual and experience the issue that test classes are put into more than one batch which then results in failing tests (if the tests require a predefined state).
For the setup I'm using serenity.batch.strategy=DIVIDE_EQUALLY
serenity.batch.count=5
serenity.batch.number=${BATCH_NUMBER}

with 5 batches (1, 2, 3, 4, 5) as we have 23 test classes.
Is this even a bug or is the sorting just not reliable by design?

Thanks in advance! :)

**Comment by wakaleo** [comment]
Could be a bug, we'll take a look.

**Comment by cliviu** [comment]
Hi @adlenton , can you always reproduce your problem ?

**Comment by adlenton** [comment]
Hi all!
Sorry, it took me a while as I didn't really find the time to setup the project, but here we go: https://github.com/adlenton/serenity_parralel_batches
![srenity parallel 1](https://cloud.githubusercontent.com/assets/20105978/18987684/1ab10616-8703-11e6-873f-ef7ac79a095e.png)
![srenity parallel 2](https://cloud.githubusercontent.com/assets/20105978/18987685/1bd9ac14-8703-11e6-90c4-d0ee32a2950b.png)
I also added screenshots from my Jenkins setup.

**Comment by cliviu** [comment]
Hi @adlenton. Thanks for the test program. I have tried with serenity.batch.count=3 For serenity.batch.number= 1, the tests 3,5,6 were executed, for serenity.batch.number=2, the tests 1,4 were executed, for serenity.batch.number=3, the tests 2,7 were executed. Have you tried with other configuration that reproduces the problem that you have described ?
