### ISSUE TITLE
Serenity silently fails due to duplicate steps and metafilter use

### ISSUE THREAD

**Issue by desecheo** [serenity-bdd/serenity-core#534]
I've come across an issue when duplicate candidate steps are found in a story and the JBehave metafilters are used to run the stories. The [sample code repo](https://github.com/desecheo/serenity-jbehave-sample) can be used "as-is" to repro the issue.

If you run: mvn verify => an error is thrown:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18:integration-test (default) on project serenity-jbehave-sample: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18:integration-test failed: There was an error in the forked process
[ERROR] org.jbehave.core.steps.Steps$DuplicateCandidateFound: GIVEN the user is on the Wikionary home page
[ERROR] at org.jbehave.core.steps.Steps.checkForDuplicateCandidates(Steps.java:224)

If you run: mvn clean verify "-Dmetafilter=+tag testme" => no error thrown, no stories run, and build completes "successfully" :)

**Comment by desecheo** [comment]
Issue resolved by upgrading maven failsafe plugin to latest (2.19.1)

**Comment by wakaleo** [comment]
Thanks for the update.
