### ISSUE TITLE
Serenity  is  not generating screenshot with appium 

### ISSUE THREAD

**Issue by lgurrapu** [serenity-bdd/serenity-core#535]
Hi,

We are trying to integrate serenity with appium and below are the versions we are using and issue is

Serenity is not generating screenshot with appium on real devices. I am testing the app in a real device  here.  Serenity is generating a report but not screenshot in report 

java-client : 3.4.1
serenity-core : 1.1.36
serenity-cucumber : 1.1.8

String userName = "XXXXXX"
String password= "XXXXXX"

String apkPath = "APk path here";
 capabilities =  new DesiredCapabilities();
 capabilities.setCapability("device","Android");
capabilities.setCapability("deviceName","XXXXXXXXXXXX");
capabilities.setCapability("platformVersion","6.0");
 capabilities.setCapability("platformName","Android");
capabilities.setCapability("app", "settings");

File file = new File(apkPath);
capabilities.setCapability("app", file.getAbsolutePath());

driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
driver.manage().timeouts().implicitlyWait(60,TimeUnit.SECONDS);
 driver.findElement(By.id("fullLogin_customerId")).sendKeys(userName);
 driver.findElement(By.id("fullLogin_password")).sendKeys(password);

serenity.properties file is 

webdriver.timeouts.implicitlywait=3000
webdriver.wait.for.timeout = 1000
serenity.native.events=true
serenity.take.screenshots=AFTER_EACH_STEP
serenity.timeout=60
serenity.reports.show.step.details=true
serenity.project.name=TestAppiumproject
serenity.driver.capabilities="deviceName:XXXXXXXXXXXXXX"
webdriver.driver=appium
appium.hub=http://127.0.0.1:4723/wd/hub

Please let me know if I am missing any here.

**Comment by nbarrett** [comment]
Did you mean to have the issue title as it is? :smile:

**Comment by lgurrapu** [comment]
@nbarrett   Apology.. It was a typo..

**Comment by hazmeister** [comment]
What device are you running the test on? I'm using a Nexus 5 for browser based tests (without forcing the latest Java client) and I'm getting screenshots in my report.

**Comment by lgurrapu** [comment]
I am running on S7. Have you ran the app on device ? Not on browser ?

**Comment by hazmeister** [comment]
Not yet I'm afraid, we don't offer an Android app yet.  It might be worth putting together a basic project just using Appium which starts the app and takes a screenshot - then you would know if the issue was with Serenity or Appium.

**Comment by cliviu** [comment]
Hi  @lgurrapu , Have you noticed any problems in the logs ?

**Comment by lgurrapu** [comment]
Hi

No issues in logs

Thanks

**Comment by vikramvi** [comment]
@lgurrapu can you share the sample project, I would like to try out and reproduce issue

**Comment by wakaleo** [comment]
Screenshots being generated or not are generally driver-related issues. Please reopen if you have reason to believe it is something we can change in Serenity.
