### ISSUE TITLE
webdriver.chrome.binary property ignored

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#536]
When a Serenity test is run using the Chrome driver but on a machine where Chrome is installed in a non-standard location, then the following type of exception is thrown:

````
Starting ChromeDriver 2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961) on port 42345
Only local connections are allowed.
11:34:17.194 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.chrome.ChromeDriver: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
(blah)	
Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.16.333243 
````

It's not possible to supply a **webdriver.chrome.binary** property either - which is not surprising as this is not a documented property in the [Serenity Reference Manual](http://www.thucydides.info/docs/serenity/#_running_serenity_tests_from_the_command_line) :smile:

**Comment by rguimaraesr** [comment]
@nbarrett Did you succeed on this? I've same issue here.

**ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE**

**my serenity.properties:**

webdriver.driver=chrome
webdriver.chrome.driver=src/chromedriver
serenity.use.unique.browser = true
serenity.take.screenshots=AFTER_EACH_STEP
webdriver.wait.for.timeout=5000
serenity.dry.run=false

**Comment by nbarrett** [comment]
Hi @rguimaraesr - the only way to overcome this was to create this #536 which I'm waiting for merge on. Obviously there are multiple causes for FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE, so I'm not sure whether your problem is the same as mine (cannot find Chrome binary).

**Comment by rguimaraesr** [comment]
@nbarrett I think it's the same problem. I'm on Linux, and I have checked everything ($PATH, chromedriver versions (64 or 32 bits) and a lot of other thing. It's odd man...  I hope that they accepted your solution and merge it asap...  There's a lot of threads about that on a simple google search.

**Comment by rguimaraesr** [comment]
look that @nbarrett https://github.com/serenity-bdd/serenity-core/pull/537  All checks have failed
1 failing check -details https://snap-ci.com/serenity-bdd/serenity-core/pull/537/logs/defaultPipeline/1/integration-tests

**Comment by rguimaraesr** [comment]
hey @wakaleo can you help us?

**Comment by nbarrett** [comment]
Issue #536 has been merged so hopefully all good for you @rguimaraesr? Closing.
