### ISSUE TITLE
Explicit Wait in Serenity is Not Working

### ISSUE THREAD

**Issue by Gurunathan5029** [serenity-bdd/serenity-core#541]
I have tried multiple Explicit wait options specified in serenity user manual but I failed in each instance.

**Please find the used options:**
XXXXStateArrow.waitUntilVisible();
XXXXStateArrow.waitUntilClickable();
waitFor(ExpectedConditions.presenceOfElementLocated(By.xpath(XXXXXTitleString)));

Both three statements are not working, Test is failing after some time. Even Implicit wait also fails. 

**Property File Value:**
webdriver.timeouts.implicitlywait = 10000; This is also not working

How exactly I can come across this issue. I dont want use "Sleep" in between test scripts

**Comment by wakaleo** [comment]
Could you describe your use case in more detail, including the precise error messages you get, and the actual behaviour of these elements on the screen?

**Comment by Gurunathan5029** [comment]
Error Message:

Element is not clickable at point (707, 250). Other element would receive
the click: <div id="Animation" class="AnimationWrapper">

Use Case :
When I clcik on XXX button

I need to click on a button after loading new page .

In My application , When you one element to another , application moves to
loading state and come back in. At that time it is failing .

**Comment by wakaleo** [comment]
Waits (implicit or otherwise) only wait until an element is present on the screen, not that it is not covered by some other element (as appears to be the case here). Have you tried waiting for the animation to disappear?

**Comment by Gurunathan5029** [comment]
Yes I have waited , For Example there are two elements 

**Button1 and Button2**

When I click on Button1 , animation progress bar will be displayed . 

I have used all these below three things with Button2 page object repository 

XXXXStateArrow.waitUntilVisible();
XXXXStateArrow.waitUntilClickable();
waitFor(ExpectedConditions.presenceOfElementLocated(By.xpath(XXXXXTitleString)));

Button 2 Page Repository Ex:
public WebElement Button2() {
		Button2getCurrentImplicitTimeout();
		waitFor(ExpectedConditions.presenceOfElementLocated(By.id(Button2 String)));
		Button2.waitUntilVisible();
		Button2.waitUntilClickable();
		waitFor(ExpectedConditions.elementToBeClickable(Button2));
		Assert.assertTrue(Button2.isDisplayed());
		return Button2;
	}


So when Button 1 is clicked , automatically secript should wait for the presence of the Button 2 Element right. 

Why it is not happening.

**Comment by wakaleo** [comment]
Have you tried waiting for the animation to disappear? I can only see waits related to Button2.

**Comment by Gurunathan5029** [comment]
Thanks Wakaleo, Progress bar is animated over here. Thats why its failing . Fixed that as well but I am facing problem in clicking Button2 after waiting animation and for element

Error:
Timed out after 5 seconds waiting for net.serenitybdd.core.pages.WebElementFacadeImpl$1@6a950a3b

**Comment by wakaleo** [comment]
If it is timing out trying to click on an element, the usual reason is that WebDriver can't find or access the element for some reason. You could try putting a breakpoint to see what WebDriver can access at that point in the code.

**Comment by bhardwaj-sumit** [comment]
I also ran in same problem..
When we asked to wait in last step of scenario it doesn't work:

i already set webdriver.wait.for.timeout = 60000
In last step of scenario i have only 2 lines of code

For eg:
// waiting for animation to disappear from DOM(which make sure page loaded)
anyElementFacade.waitUntilNotVisible();

Assert.assertEquals(anyElementFacade.waitUntilClickable().getText(), actValue);

It doesn't wait for animation to disappear from DOM, after 5 seconds it assert the condition which make my Scenario fail.

**Comment by nbarrett** [comment]
`Element is not clickable at point` is a problem that to my knowledge only happens on the chrome driver and is not a necessarily a problem with timing, or at least is unlikely to be cureable by purely introducing waits. There is quite a bit of information on Stackoverflow about this and the best article I've found is [here](http://stackoverflow.com/questions/11908249/debugging-element-is-not-clickable-at-point-error). I've fixed this in the past by using an expected condition that waits for the offending obscuring element to disappear before attempting the actual click action.

**Comment by wakaleo** [comment]
A maxed-out timeout does sound like a WebDriver problem (WebDriver is simply not finding the element for some reason), rather than something Serenity-specific. Can you provide a simple project that reproduces the issue?

**Comment by Gurunathan5029** [comment]
This got resolved wakaleo. Thanks for the inputs, I have missed to add the element.

**Comment by wakaleo** [comment]
Thanks for the update.

**Comment by Gurunathan5029** [comment]
Hi Submit,

Did you find a way to overcome this syncronisation issue in Serenity.

My scripts failing to find the element in DOM after immediate disappearance
of animation progress bar.

Regards,
Guru

**Comment by wakaleo** [comment]
This is generally not a Serenity issue - in most cases, if Selenium says an element isn't there, when it asks, it isn't. If it times out after 5 seconds, it spent 5 seconds looking for an element that wasn't there. A good strategy is to find something you know will only be visible once the animation is finished, or wait until the animation bar disappears.

**Comment by Gurunathan5029** [comment]
When I have extra 3 more seconds on implicit wait , I can work on that
element.

Is it way to change that predefined 5 seconds . Since I could not able to
use Explicit waits , I should be going with implicit wait but which may
affect my script performance .

Is it possible for you to post all the waiting techniques in Serenity .

**Comment by tiwari90** [comment]
Hi Gurunathan, 

As you have mentioned above that "Progress bar is animated over here. Thats why its failing ."
Can you please share the solution, I am facing the same issue. It might help

**Comment by tiwari90** [comment]
@wakaleo  Do we have any method in serenity to handle this "animation to disappear" problem ??

**Comment by wakaleo** [comment]
@tiwari90 This is usually very dependant on the site, but I usually try to identify the overlay or animation on the page and just wait for it to either be invisible or not be present (depends on the site implementation).

**Comment by anujtiwari24** [comment]
@wakaleo I tried to use the element.waitUntilClickable() method from webElementFacade but its not working for me.
Scenario: Enter username, Enter password and then the login button is enabled and clickable otherwise its displayed but greyed out. So this wait i was trying to use but its not working.

**Comment by sudhir-kunchakuri** [comment]
i want to wait till all the values in my dropdown are loaded, how can i achieve it serenity?
can anyone suggest me plz..

**Comment by rameshkorla1** [comment]
How to handle JavascriptExecutor method in serenity cucumber framework. Could you please give me an example here
