### ISSUE TITLE
Serenity Report doesn't fetch last JIRA issue if JIRA user story issue is added above feature

### ISSUE THREAD

**Issue by Gurunathan5029** [serenity-bdd/serenity-core#543]
Example:
@version:Release-1.0 
@UniqueBrowser
@issue:XXX-2    **"User Story"**
Feature: XXXXXX Creation 
@issue:XXX-1      "**Task"**
Scenario: Login 
    Given I navigate to XXXLogin Page 
    When XXXX and XXXXXX
    And I XXXXX do
    Then XXXXXX Displayed 

@issue:XXX-4     **"Task"**
Scenario: Employee Creation Form Verification 
    Given I am in XXXXX XXXX Page 
    When I XXXXX  button 
    And I click on XXXXX button 

When I add **@issue:XXX-2** above Feature, then Report doesn't hold automation count for the
XXX-4.

When I remove **@issue:XXX-2** , Report is populated with correct values for Issue - XXX-4.

**Comment by cliviu** [comment]
hi @Gurunathan5029 , I was not able to reproduce your issue. The @issue which is placed directly above the @Feature is present in all the @Scenarios and it will add to the @issue annotation above @scenario. Please provide more information to be able to reproduce your issue

**Comment by Gurunathan5029** [comment]
Liviu,

The Issue which specified above Feature is appending with Serenity report but when u do that, issue specified above last scenarios is appended with zero automated count in serenity report.

**Comment by wakaleo** [comment]
I can't reproduce this with the latest versions. Please feel free to reopen (a sample project would help) if the problem persists.
