### ISSUE TITLE
Error when running jUnit tests from Intellij command line

### ISSUE THREAD

**Issue by larisagrecu** [serenity-bdd/serenity-core#544]
I tried to run a bunch of jUnit tests from Intellij command line with the following command:
**gradlew clean test aggregate -Dbart.environment=EnvName -Dtags="feature:ContactList"**
The problem is that I get very often this error: 
`Wrong page error: The page object class de.telekom.commtech.bart.pages.common.LoginPage looks dodgy:`

What could be the problem? I have the latest versions of Serenity, gradle and Firefox.

**Comment by cliviu** [comment]
Hi Larisa, please post the whole stack trace

**Comment by larisagrecu** [comment]
Hello @cliviu . This is the stack-trace:

`net.thucydides.core.pages.WrongPageError 
The page object class de.telekom.commtech.bart.pages.common.LoginPage looks dodgy: Failed to instantiate page (net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver)
de.telekom.commtech.bart.steps.AbstractScenarioSteps.getLoginPage(AbstractScenarioSteps.java :52) 
de.telekom.commtech.bart.steps.inbox.AuthNavigationSteps.loginDialogShouldAppear(AuthNavigationSteps.java :212) 
de.telekom.commtech.bart.steps.inbox.AuthNavigationSteps.completeLogin(AuthNavigationSteps.java :35) 
de.telekom.commtech.bart.testcases.BaseTest.login(BaseTest.java :445) 
de.telekom.commtech.bart.testcases.inbox.userfolder.ClearFolderTestCase.setup(ClearFolderTestCase.java :41) 
`

**Comment by wakaleo** [comment]
This looks like a problem with the Firefox driver; what version of Firefox do you have?

**Comment by larisagrecu** [comment]
Hello. I use Firefox 47.0.1

**Comment by wakaleo** [comment]
This is not a Serenity issue: Firefox 47 is not supported by Selenium - I would recommend using version 45.
