### ISSUE TITLE
Html in step descriptions is broken

### ISSUE THREAD

**Issue by DmytroMalohlovets** [serenity-bdd/serenity-core#545]
``` html
<serenity.version>1.1.41</serenity.version>
```

``` java
@Step
public void description(String html) {
    //do nothing
}

public void about() {
    description("<h2>TEST</h2>\n");
}
```

it converts to html

``` html
&lt;h2&gt;TEST&lt;/h2&gt;<br>
```

What is interesting that

``` java
 \n
```

from Java goes to

``` html
 <br>
```

in html, but

``` java
 <h2>
```

is displaying like text (not like html node)

**Comment by wakaleo** [comment]
What behaviour are you expecting? At the moment HTML tags are intentionally not supported in the step descriptions, as it introduces other issues with the reports.

**Comment by Dmitriy84** [comment]
I do expect https://thucydides-webtests.com/category/tips-and-tricks/page/2/ (Html in step descriptions)
behavior
But you've answered my question. Are we going to return such functionality?

**Comment by wakaleo** [comment]
We may allow markdown in step descriptions. Could you tell us more about your particular use case?

**Comment by robertzett** [comment]
I would also like to add that for me the new escaped HTML is a problem as well.
My use case is to embed an generated uuid into an HTML link, which is used to link to a logfile analysis tool like Kibana/Logstash.
I add markup a bit differently which at last should be no difference to what Dmitriy84 explained:
```java
@Step
public void addHyperlinkStep() {
  StepEventBus.getEventBus().updateCurrentStepTitle("Some <a href=\"link to kibana\">details see kibana</a>");
}
```

I thought there would be a possibility to have all known requirements for HTML markup supported with a small modification to the changed Formatter.formatWithFields(). But markdown would be fine for me as well.
The 3 requirements I'm aware of are:
1. The one explained by Dmitriy84 from here https://thucydides-webtests.com/category/tips-and-tricks/page/2/
2. Mine, as explained above
3. And the one from #246 which, as far as I understood, led to the now changed behaviour

**Comment by wakaleo** [comment]
As of 1.2.1-rc.1, markdown is supported in most text fields and titles.
