### ISSUE TITLE
Fail will be 100% when last scenario row in the scenario outline example fails. 

### ISSUE THREAD

**Issue by nshiveg** [serenity-bdd/serenity-core#547]
Hi John,

Critical situation for all team member in our organization, please help us out. 

When we have multiple scenario outline examples and if the last row fails, then the fail is 100%.

Example:-

  Scenario Outline: To verify Lifecycle Events Subscription API with Make, Model, Firmware criteria returns unauthorised error when Group passed in the request is inaccessible to the user
    When API Client subscribes to "tests" by passing inaccessible Name <GROUP>, make <MAKE>, model <MODEL>, firmware <FIRMWARE> and event <LIFECYCLEEVENT> with the valid header
    Then HTTP Code <HTTPSTATUSCODE> should be returned

    Examples: 
      | GROUP          | MAKE         | MODEL      | FIRMWARE | LIFECYCLEEVENT   | HTTPSTATUSCODE |
      | "DIFFCUSTOMER" | "Mformation" | ""         | ""       | "deregistration" | '401'          |
      | "DIFFCUSTOMER" | "Mformation" | ""         | ""       | "deregistration" | '401'          |
      | "DIFFCUSTOMER" | "Mformation" | ""         | ""       | "deregistration" | '200'          |

If the last row fails in this scenario outline, then the fail is 100%. Though the other rows have passed. 

I am attaching the sample project. And also screen shots for quick look out.

this is screen shot
[Report fails.zip](https://github.com/serenity-bdd/serenity-core/files/490195/Report.fails.zip)

this is sample project
[AutomationServer_0508_git (3).zip](https://github.com/serenity-bdd/serenity-core/files/490193/AutomationServer_0508_git.3.zip)

**Comment by wakaleo** [comment]
Could you try with serenity-core 1.1.41 and serenity-cucumber 1.1.10?

**Comment by nshiveg** [comment]
Wow...so quickly you responded. Thanks a lot. We will use and update you. Thanks once again.

**Comment by nshiveg** [comment]
Hi John,

I tried this with the serenity-core 1.1.41 and serenity-cucumber 1.1.10. The issue is present here also. 

It will be very helpful if you could help us in this matter

**Comment by wakaleo** [comment]
An issue with these symptoms was reproduced and fixed in 1.1.40 onwards. Could you make sure your dependencies are up to date and if the problem persists, provide a sample project illustrating this issue?

**Comment by nshiveg** [comment]
Hi John,

I checked it once again and it is identified that issue is getting reproduced. I am attaching the jar here.
please let me know if I am doing something wrong here. Thanks in advance. Thanks a lot for your valuable time.

[AutomationServer_0508_git.zip](https://github.com/serenity-bdd/serenity-core/files/491249/AutomationServer_0508_git.zip)

**Comment by wakaleo** [comment]
OK, I've reproduced this, we'll look at a fix for the next release.

**Comment by nshiveg** [comment]
Thank you sir.
