### ISSUE TITLE
Manual Scenarios does not goes in pass state

### ISSUE THREAD

**Issue by nshiveg** [serenity-bdd/serenity-core#548]
Hi John,

How to make manual scenarios which are with the tags @manual pass in our serenity reports?

Currently with the serenity version 1.1.37-rc.7, we have the status in pending. 

We saw many links but did find any useful one. Could you please guide us

**Comment by wakaleo** [comment]
This is not supported at the moment. It might be in a future version. The problem is that it is misleading - you can never guarantee that a manual test is verified for a given build run.

**Comment by nshiveg** [comment]
Ya you are correct.. Even we thought the same. But you know right "people managers" in company's don't sit quite ;).

Anyways we will ask them to wait. thanks a lot..

**Comment by nshiveg** [comment]
Hi John,

Do we have any solution for this now in the latest jars, we have made the serenity as our single point for the automation and test case execution. So it will be great advantage for us if this support is present.

**Comment by wakaleo** [comment]
I am adverse to adding this feature as it would lead to potentially misleading reports - the manual flag is more a reminder than a record of a passing manual test, as at the time of execution it is most likely impossible to have manually run the test

**Comment by nshiveg** [comment]
Thanks for your quick reply.
Actually I had an idea to how it can be done in the serenity.

We have the manual cases gets into the pending state. Now I go to each of them and change the state of them on the report, from pending to pass/fail.

This option you can leave it to the user to change it. Every run make it as pending only. Users on that generated report have the option to execute them and mention the build number(Application under test version number). In this way I can have a single point of contact for the reporting. No need to use xl to mange the pending manual cases.

Today in our organisation(Nokia) we are showing the serenity and xl for the results status.

Let me know your opion on this. 

And serenity is our blood and butter today in our org. Great work you people are doing
