### ISSUE TITLE
Can we get logging output of calls to Page methods for the duration of Steps that fail?

### ISSUE THREAD

**Issue by swalkersbw** [serenity-bdd/serenity-core#55]
When there are multiple page method calls within a step and one of them throws an exception there is little or no visibility as to exactly where where within the Step the failure occurred.

It would aid debugging if logging output (of calls to Page methods) was kept for the duration of the Step so that in event of an Exception being thrown then the output could be included in the report, (logging would be thrown away for Steps that pass).

**Comment by YamStranger** [comment]
Hello @swalkersbw!

Please check it in current version, it should be much better!!

Thanks a lot!

**Comment by YamStranger** [comment]
It seems that this issue already fixed or not an issue any more.
