### ISSUE TITLE
Valuable error message being is truncated in Serenity report

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#553]
When a Serenity / Screenplay step fails, the error message is truncated at an important point. See example below:

![image](https://cloud.githubusercontent.com/assets/626941/18910313/61f06cfa-856f-11e6-85ac-c11af2dc5ea1.png)

Whilst the popup dialog is useful to display the entire stack trace, it seems an unnecessary extra step to have to go there to see the full exception message. So in the above example, I think it would be better to show the message in the main report as:

 `Expected: to display 'workflowStep' as (TR Approve) but: displayed 'workflowStep' as (PC Enrichment)`

Rather than: 

`Assertion error: Expected: to display 'workflowStep' as <TR Approve> but: displayed...`

**Comment by wakaleo** [comment]
The exception is shown because it is not always an assertion error - tests can be configured to use domain-specific exception classes which provide more meaning (for example UnknownCustomerException). I think you should be able to see the full message by hovering over the error.

**Comment by nbarrett** [comment]
Actually @wakaleo - the message is the same on hover :smiley_cat: 
![image](https://cloud.githubusercontent.com/assets/626941/18920782/58a9e9ac-859a-11e6-97b0-c3f0271f9c9e.png)

Also, regarding your previous comment, I'm happy to create my own RuntimeExceptions, but will this work around the truncation? I still want to see the whole message as often on assertion failures we want to see the 'but was... bit!)

**Comment by wakaleo** [comment]
Fair enough, I think the issue is WebDriver exceptions, which go on and on and on, with all the possible and imaginable details of the driver etc. All on the same line. 
I will see if we can extend the message size to 80 chars with wrapping and make sure the full message is displayed in the tip.

**Comment by nbarrett** [comment]
Or maybe do some regex on the message if it's a webDriverException and goes on a bit. Yes I agree they are crazily verbose and perhaps the original creator of that hadn't put `cause` to good use and no one has fixed it since? :smile:
