### ISSUE TITLE
A test can't find browser-remote.properties

### ISSUE THREAD

**Issue by igor-rubis** [serenity-bdd/serenity-core#554]
Hello.

I encounter an issue in tests which I think is rather framework related. During the test run I get the following exception:
> 03:11:12 java.io.FileNotFoundException: target/site/serenity/browser-remote.properties (No such file or directory)
> 03:11:12 	at java.io.FileOutputStream.open0(Native Method)
> 03:11:12 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
> 03:11:12 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
> 03:11:12 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
> 03:11:12 	at java.io.FileWriter.<init>(FileWriter.java:90)
> 03:11:12 	at net.serenitybdd.core.buildinfo.PropertyBasedDriverCapabilityRecord.registerCapabilities(PropertyBasedDriverCapabilityRecord.java:47)
> 03:11:12 	at net.thucydides.core.webdriver.WebdriverInstanceFactory.newRemoteDriver(WebdriverInstanceFactory.java:53)
> 03:11:12 	at net.thucydides.core.webdriver.WebDriverFactory.buildRemoteDriver(WebDriverFactory.java:294)
> 03:11:12 	at net.thucydides.core.webdriver.WebDriverFactory.newRemoteDriver(WebDriverFactory.java:286)
> 03:11:12 	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:175)
> 03:11:12 	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:142)
> 03:11:12 	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:133)
> 03:11:12 	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:103)
> 03:11:12 	at net.thucydides.core.webdriver.WebDriverFacade.manage(WebDriverFacade.java:344)
> 03:11:12 	at com.some_package.pages.product.ProductPage.go(ProductPage.java:957)

The issue appears in a middle of a test. 
Tests are running in a single batch in a sequence in a remote browser in selenium grid. The job starts as usual but then in some moment some test fails with the above exception and the rest of tests also fail with the following stacktrace:
> 03:14:23 Running some_package.SomeTest
> 03:14:23 Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE! - in some_package.SomeTest
> 03:14:23 initializationError(some_package.SomeTest)  Time elapsed: 0 sec  <<< ERROR!
> 03:14:23 java.lang.NullPointerException: null
> 03:14:23 	at org.jbehave.core.io.CodeLocations.getPathFromURL(CodeLocations.java:86)
> 03:14:23 	at org.jbehave.core.io.CodeLocations.codeLocationFromClass(CodeLocations.java:26)
> 03:14:23 	at net.serenitybdd.jbehave.SerenityJBehave.defaultConfiguration(SerenityJBehave.java:59)
> 03:14:23 	at net.serenitybdd.jbehave.SerenityStories.configuration(SerenityStories.java:77)
> 03:14:23 	at org.jbehave.core.ConfigurableEmbedder.configuredEmbedder(ConfigurableEmbedder.java:118)
> 03:14:23 	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.<init>(SerenityReportingRunner.java:79)
> 03:14:23 	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.<init>(SerenityReportingRunner.java:73)
> 03:14:23 	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
> 03:14:23 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 03:14:23 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 03:14:23 	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
> 03:14:23 	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
> 03:14:23 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 03:14:23 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
> 03:14:23 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 03:14:23 	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
> 03:14:23 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
> 03:14:23 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
> 03:14:23 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
> 03:14:23 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
> 03:14:23 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
> 03:14:23 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Serenity version: 1.1.36

1. What's the exact purpose of the browser-remote.properties file?
2. Is it created once and for the whole test run or it's unique for each story/scenario?

Could you please help me with this issue?

**Comment by wakaleo** [comment]
Does it affect the execution of the tests?

**Comment by igor-rubis** [comment]
Seems like it doesn't. A batch tries to run tests after the 'browser-remote.properties' issue, but all of them fail with initializationError.

**Comment by wakaleo** [comment]
What is the exact initializationError?

**Comment by igor-rubis** [comment]
It's 
> java.lang.NullPointerException: null

The only stacktrace available in console is:
> 03:14:23 Running some_package.SomeTest
> 03:14:23 Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE! - in some_package.SomeTest
> 03:14:23 initializationError(some_package.SomeTest) Time elapsed: 0 sec <<< ERROR!
> 03:14:23 java.lang.NullPointerException: null
> 03:14:23 at org.jbehave.core.io.CodeLocations.getPathFromURL(CodeLocations.java:86)
> 03:14:23 at org.jbehave.core.io.CodeLocations.codeLocationFromClass(CodeLocations.java:26)
> 03:14:23 at net.serenitybdd.jbehave.SerenityJBehave.defaultConfiguration(SerenityJBehave.java:59)
> 03:14:23 at net.serenitybdd.jbehave.SerenityStories.configuration(SerenityStories.java:77)
> 03:14:23 at org.jbehave.core.ConfigurableEmbedder.configuredEmbedder(ConfigurableEmbedder.java:118)
> 03:14:23 at net.serenitybdd.jbehave.runners.SerenityReportingRunner.(SerenityReportingRunner.java:79)
> 03:14:23 at net.serenitybdd.jbehave.runners.SerenityReportingRunner.(SerenityReportingRunner.java:73)
> 03:14:23 at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
> 03:14:23 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 03:14:23 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 03:14:23 at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
> 03:14:23 at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
> 03:14:23 at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 03:14:23 at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
> 03:14:23 at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 03:14:23 at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
> 03:14:23 at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
> 03:14:23 at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
> 03:14:23 at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
> 03:14:23 at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
> 03:14:23 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
> 03:14:23 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by wakaleo** [comment]
The first exception is unrelated to the second; the first is just a warning (which shouldn't be reported, but shouldn't affect the tests). The second is JBehave-related; you're best bet is to put a breakpoint in SerenityJBehave line 59 to see what is going on.

**Comment by igor-rubis** [comment]
Thank you. I'll try to debug it.

**Comment by igor-rubis** [comment]
The issue stopped reproducing. Thank you for your advise.
