### ISSUE TITLE
Is is possible to nest Screenplay when/then steps in html report?

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#557]
I have an acceptance suite that (unfortunately at the moment) requires all of the setup for data to be done through the UI. This means that to get to the **when** of quite a few scenarios, I have to execute some other scenarios first. To shortcut this process I've created a runner to quickly inject this data, so I do have something like this:
```
        Actor actor = Actors.selectOneWithRole(workflowRole);
        givenThat(actor).has(LoggedIn.andCreatedANewFrontOfficeBookWithDetails(templateName, templateBookName, system));
        givenThat(actor).has(SearchFromDashboard.forTheFrontOfficeBook());
        givenThat(actor).should(seeThat(SearchResultsQuestion.row(), displays("workflowStep", equalTo(exitStep))));
```
(note that I fudged the `PerformsTasks` to be a `givenThat`)

However, when I look at the report, I always see the 'when' and 'then' steps outside of the indenting as follows:
![image](https://cloud.githubusercontent.com/assets/626941/19046113/ea896dfa-8993-11e6-9d5d-4a21578ff5bd.png)

Ideally, I'd like to be able to choose whether these lines fall into the indenting or not so I can hide away **all** of my 'setup' steps in one go. Is this possible?

**Comment by wakaleo** [comment]
Just wrap them all in higher-level task.

**Comment by nbarrett** [comment]
Thanks @wakaleo - I've done that now and everything looks great.
