### ISSUE TITLE
Can not cast driver to other driver using getProxiedDriver when running test on saucelabs

### ISSUE THREAD

**Issue by loveshjain** [serenity-bdd/serenity-core#559]
Unable to cast driver to any other driver when we give serenity property "saucelabs.url"

Code :- 

AndroidDriver<WebElement> androidDriver = ((AndroidDriver<WebElement>)((WebDriverFacade) getDriver()).getProxiedDriver()); 
Set<String> contextNames = androidDriver.getContextHandles();
      for (String contextName : contextNames) {
        System.out.println(contextName);
            System.out.println(contextNames); //prints out something like [NATIVE_APP, WEBVIEW_<APP_PKG_NAME>]
        }
        androidDriver.context("NATIVE_APP");

**Error**:org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$d2f9355c cannot be cast to io.appium.java_client.android.AndroidDriver

Serenity Properties file :- 

saucelabs.test.name = Test-Saucelabs-Android
webdriver.driver = appium
appium.hub = http://username:accesskey@localhost:4445/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1
appium.deviceName = Android Emulator
appium.browserName = Browser
appium.deviceType = phone
appium.deviceOrientation = portrait
saucelabs.url=url
saucelabs.access.key=key

The test does not give error when we comment out saucelabs.url property. But in that case index.html does not have saucelabs video link attached to it.

**Comment by loveshjain** [comment]
@wakaleo Hi John, Could you please help me out. Although the report wasn't having the saucelabs video link was fine with me but now the issue is if the test fails at any step then the test tries to get the screenshot but fails to take it and script get stuck there for 30 minutes until saucelab timeout which is set to default as 30 minutes. If I set the serenity property #serenity.take.screenshots=DISABLED then there is no issue but in that case I wont be able to get screenshot for my fail steps.

Please suggest any solution.

**Comment by wakaleo** [comment]
Could you post the full stack dump?

**Comment by loveshjain** [comment]
Hi John,

Please find below the stack dump.

**Issue 1**. When sauelabs.url is provided then :-

**Serenity properties** :- 

##Saucelabs-Android-phone
saucelabs.test.name = Test-Saucelabs-Android 
webdriver.driver = appium
appium.hub = http://username:accesskey@localhost:4445/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1
appium.deviceName = Android Emulator
appium.browserName = Browser
appium.deviceType = phone
appium.deviceOrientation = portrait
saucelabs.url=http://username:accesskey@localhost:4445/wd/hub
saucelabs.access.key=accesskey
saucelabs.user.id=username

**Console Output**

driver is :- net.thucydides.core.webdriver.WebDriverFacade@1e6cc850
Message -->> Error:org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$ba56f2e cannot be cast to io.appium.java_client.android.AndroidDriver

Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'loveshjain-lp', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-45-generic', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={}, takesHeapSnapshot=true, hasMetadata=true, databaseEnabled=false, hasTouchScreen=false, handlesAlerts=true, version=39.0.0.0, platform=ANDROID, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=e598c1cerfdf474b8e840cb4be10ee9744, webStorageEnabled=true, locationContextEnabled=true, takesScreenshot=true, browserName=chrome, javascriptEnabled=true, cssSelectorsEnabled=true}]

[main] ERROR net.serenitybdd.core.Serenity - [91m
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            


_I think the issue is when saucelabs.url is provided it considered the driver as RemoteDriver and therefore it is unable to cast it. When I comment out saucelabs.url, the driver is considered as Androiddriver and it work fine._

**Issue 2**. When saucelabs.url is not provided, casting to Android driver works fine when test case gets failed the test tries to take screenshot (since serenity.take.screenshots=FOR_FAILURES) and it is unable to do that fails after 30 minutes which is when saucelabs timeout. If serenity.take.screenshots=Disabled the it works fine but I don't get a screenshot for failed step. I think when I don't provide saucelabs.url it does not goes into the logic of takescreen for remotedriver.

Serenity properties :- 

##Saucelabs-Android-phone
saucelabs.test.name = Test-Saucelabs-Android 
webdriver.driver = appium
appium.hub = http://username:accesskey@localhost:4445/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1
appium.deviceName = Android Emulator
appium.browserName = Browser
appium.deviceType = phone
appium.deviceOrientation = portrait
saucelabs.access.key=accesskey
saucelabs.user.id=username
serenity.take.screenshots=FOR_FAILURES

**Console output** :- When any step failed then 

Nov 03, 2016 12:01:46 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:4445: The target server failed to respond
Nov 03, 2016 12:01:46 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:4445
Nov 03, 2016 12:06:46 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:4445: The target server failed to respond
Nov 03, 2016 12:06:46 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:4445
Nov 03, 2016 12:11:46 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:4445: The target server failed to respond
Nov 03, 2016 12:11:46 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:4445
Nov 03, 2016 12:21:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:4445: The target server failed to respond
Nov 03, 2016 12:21:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:4445
Nov 03, 2016 12:26:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:4445: The target server failed to respond
Nov 03, 2016 12:26:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:4445
[main] WARN net.thucydides.core.webdriver.WebDriverFacade - Failed to take screenshot - driver closed already? (ERROR The test with session id ee1ff3bedd3d46a3a1873dbfb6faf7e5 has already finished, and can't receive further commands.

For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
Command duration or timeout: 1917.27 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'loveshjain-lp', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-45-generic', java.version: '1.8.0_91'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={}, takesHeapSnapshot=true, hasMetadata=true, databaseEnabled=false, hasTouchScreen=false, handlesAlerts=true, version=39.0.0.0, platform=ANDROID, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=ee1ff3bedd3d46a3awer1873dbfb6faf7e5, webStorageEnabled=true, locationContextEnabled=true, takesScreenshot=true, browserName=chrome, javascriptEnabled=true, cssSelectorsEnabled=true}]

Session ID: ee1ff3bedd3d46awrewe3a1873dbfb6faf7e5
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:511)
	at net.thucydides.core.webdriver.WebDriverFacade.getPageSource(WebDriverFacade.java:255)
	at net.serenitybdd.core.photography.PageSourceRecorder.pageSource(PageSourceRecorder.java:39)
	at net.serenitybdd.core.photography.PageSourceRecorder.intoDirectory(PageSourceRecorder.java:29)
	at net.thucydides.core.steps.BaseStepListener.grabScreenshot(BaseStepListener.java:717)
	at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:622)
	at net.thucydides.core.steps.BaseStepListener.takeEndOfStepScreenshotFor(BaseStepListener.java:603)
	at net.thucydides.core.steps.BaseStepListener.stepFailed(BaseStepListener.java:525)
	at net.thucydides.core.steps.StepEventBus.stepFailed(StepEventBus.java:314)
	at net.thucydides.core.steps.StepInterceptor.notifyOfStepFailure(StepInterceptor.java:441)
	at net.thucydides.core.steps.StepInterceptor.reportMethodError(StepInterceptor.java:284)
	at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:22)
	at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:269)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:127)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at com.Automation.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$29274b3e.VerifyPageNavigatedCorrectly(<generated>)
	at com.Automation.steps.BOACDefinitionSteps.RealMeLogin(BOACDefinitionSteps.java:442)
	at ✽.And user log in to RealMe succesfully(src/test/resources/features/BOAC/Profile - Save_filters_as_preferences.feature:12)

**Comment by wakaleo** [comment]
This should work in 1.6.9
