### ISSUE TITLE
enhancement request - please add support to have multiple drivers using webdriver.driver

### ISSUE THREAD

**Issue by mrkk** [serenity-bdd/serenity-core#568]
webdriver.driver=chrome

works fine and tests for chrome driver

But obviously any web project needs to be tested for different browsers

If I run the maven task twice with specifying system property, the previous report will be overwritten

I would like to see serentiy run with multiple browsers, and report generated in tabbed format for all of the specified drivers

**Comment by wakaleo** [comment]
Would form would you imagine the report taking?

**Comment by mrkk** [comment]
the same stories/features etc but in tabs for different browsers

e.g. all tests could have passed in chrome, but not in firefox
