### ISSUE TITLE
WebDriverFactory doesn't add remote Capabilities properties

### ISSUE THREAD

**Issue by koffskiy** [serenity-bdd/serenity-core#57]
When I use Serenity with Selenium Grid, then WebDriverFactory ignore "platform" and "version" properties.

I investigated this issue and if I use parameter webdriver.remote.driver=iexplorer then WebDriverFactory will create real browser capabilities, because it creates remote capabilities only for Remote driver.

**Comment by wakaleo** [comment]
Could you indicate all of the system properties you are providing, including in particular webdriver.driver, webdriver.remote.browser.version etc?

**Comment by wakaleo** [comment]
Also refer to the Serenity documentation on the topic: http://serenity-bdd.info/docs/serenity/#_running_remote_tests

**Comment by koffskiy** [comment]
I am using serenity 1.0.47 with parameters: 
-Dproperties=serenity-grid.properties 
-Dwebdriver.remote.driver=iexplorer 
-Dwebdriver.remote.browser.version=11

in selenium-grid-properteis:

story.timeout.in.secs=3000
serenity.take.screenshots=FOR_FAILURES
thucydides.requirement.types=theme,epic
thucydides.report.show.manual.tests=false
thucydides.jira.workflow.active=false
thucydides.skip.jira.updates=true
jira.project=PROJECT
jira.url=https://project.jira.com
jira.username=jira_username
jira.password=password
thucydides.project.key=PROJECT_KEY
webdriver.remote.url=http://localhost:4444/wd/hub

**Comment by koffskiy** [comment]
I've debugged WebDriverFactory and found that it calls such methods with my configuration:
1) buildRemoteCapabilities
2) capabilitiesForDriver("iexplorer")
3) realBrowserCapabilities(SupportedWebDriver.IEXPLORER)

and it doesn't call remoteCapabilities method in which WebDriverFactory reads WEBDRIVER_REMOTE_OS and WEBDRIVER_REMOTE_BROWSER_VERSION properties

**Comment by wakaleo** [comment]
Could you try running with -Dwebdriver.driver=remote in addition to the other variables. Also, where are you setting the remote OS and remote browser version?

**Comment by eskape** [comment]
I have the same issue. Adding -Dwebdriver.driver=remote does not work. driverTypeFor method in WebDriverFactory returns IEXPLORER.

**Comment by YamStranger** [comment]
@eskape Hello!

It seems that your pull request merged, and this issue is solved. Could you close this issue if so please. 

Thanks

**Comment by eskape** [comment]
Hi YamStranger,

I'm glad it fixes the issue. I'm not able to close it.
@wakaleo Can you close it?

**Comment by wakaleo** [comment]
Done
