### ISSUE TITLE
Level of precision rather high on average steps per test

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#570]
We probably don't need the level of precision quite this high on the average number of steps per test. Rounding down to 0 decimal places would probably be okay given that fractions of steps don't exist :smile: See below screenshot:

![image](https://cloud.githubusercontent.com/assets/626941/19355533/9de1ffe0-9162-11e6-9733-951f93cc0bf4.png)

(but don't ask me why the tests in my suite have quite so many steps in them!)

**Comment by wakaleo** [comment]
Easy enough to do, but this view is experimental and likely to disappear in the updated reports view which will come out in the next couple of months.
