### ISSUE TITLE
Serenity Report: JIRA Integration One way

### ISSUE THREAD

**Issue by SumantaSarathiChakraborty** [serenity-bdd/serenity-core#572]
I was using serenity core version 1.1.37-rc.6 where the Jira integration was working fine and the serenity report was fetching the Story Names from JIRA and showing in the Report.

But as I upgrade the serenity core this stopped working. Could you please help.

**Description:**
Serenity Report -> Test Count Tab:
The Story number was given in the scenario. Serenity maps with JIRA and instead of serenity.requirement.types = capability, epic, story; this shows Jira story names and test case count.

**Comment by cliviu** [comment]
hi @SumantaSarathiChakraborty . a new jira-plugin release candidate will come soon. I will let you know.
