### ISSUE TITLE
setting an user agent phantomjs 

### ISSUE THREAD

**Issue by ak120684** [serenity-bdd/serenity-core#574]
hi @wakaleo .
is there a way to pass the user-agent information thru serenity.properties file ?
I want to test mobile site and so, want phantomjs to mimic a mobile (useragent) browser.

i have asked this question on stackoverflow - https://stackoverflow.com/questions/40092957/how-to-set-useragent-for-phantomjs-in-serenity-bdd

**Comment by wakaleo** [comment]
Closing - please feel free to continue the conversation on StackOverflow (there is a question pending).
