### ISSUE TITLE
PageObject.open("outlook", withParameters("")); opening wrong url

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#575]
Hi,

I've below scenario

@DefaultUrl("http://dummy.dummy")
@NamedUrls(
		  {
		    @NamedUrl(name = "outlook", url = "https://login.live.com/login.srf?wa=wsignin1.0&ct=1409066173&rver=6.1.6206.0&sa=1&ntprob=-1&wp=MBI_SSL_SHARED&wreply=https:%2F%2Fmail.live.com%2F%3Fowa%3D1%26owasuffix%3Dowa%252f&id=64855&snsc=1&cbcxt=mail")
		  }
		)
public class ThirdParty_EmailPage extends PageObject {

AND

@DefaultUrl("https://test_app.me/login")
public class AppLoginPage extends PageObject {

When I call 
PageObject.open("outlook", withParameters(""));

It opens https://test_app.me/login/login.srf?wa=wsignin1.0&ct=1409066173....
observe the first portion of URL is different.

I open new url in 2nd tab , 1st tab has got the app url

Please clarify what I'm doing wrong there or there is bug with open method itself ?

**Comment by wakaleo** [comment]
What object are you calling the open() method on?

**Comment by vikramvi** [comment]
Object of class ThirdParty_EmailPage

**Comment by vikramvi** [comment]
I forgot to mention one point , I'm passing -Dwebdriver.base.url from command line , will this replace @DefaultUrl for ThirdParty_EmailPage in which I need to use @NamedUrl ?

**Comment by vikramvi** [comment]
So here bug is open method with parameters is ignoring DefaultUrl value of class ThirdParty_EmailPage and instead taking value supplied to webdriver.base.url  . Kindly review and fix this request

**Comment by wakaleo** [comment]
This is not a bug - the purpose of the webdriver.base.url system is to override the DefaultUrl value for a page object.

**Comment by vikramvi** [comment]
Is there any way to call explicit url with open("outlook", withParameters(""));

**Comment by vikramvi** [comment]
@wakaleo can you please clarify
