### ISSUE TITLE
Black screenshot in reports for serenity and error Expected enabled element was not enabled

### ISSUE THREAD

**Issue by sudheerpujar** [serenity-bdd/serenity-core#576]
Hi  
Please find the issues details, kindly let me know if any thing wrong in the configuration that need to be corrected.

**Background**
Using selenium plugin on Jenkins, selenium grid (hub and node on same windows machine) is configured  to run the automation tests using serenity api. 

**Issue**
-  Black screenshot in the reports when tests run with IE driver
-  Error ```net.serenitybdd.core.exceptions.SerenityWebDriverException: Expected enabled element was not enabled
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'XYZ00434566', ip: '128.162.94.224', os.name: 'Windows Server 2012 R2', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_66'
Driver info: driver.version: unknown```

**What works**
Same tests works for firefox

**Version Details**
IE Driver version - _2.53.1_
Selenium Grid version -  _2.53.0_
Jenkins version - _1.609.3_
Jenkins OS - _Windows Server 2012 R2_
serenity-core version _1.1.3_

**JSON configuration**

_X11 display_ `  ` 
_Not sure what should be the value for **X11 display** if Jenkins is on windows._

_JVM system properties_
`webdriver.ie.driver=C:\\selenium\\drivers\\ie\\2.53.0\\32\\IEDriverServer.exe`

_Additionnal selenium arguments_
```
-browserSideLog 
-debug 
-trustAllSSLCertificates 
-browserSessionReuse
```

_JSON config_
```
{
"class": "org.openqa.grid.common.RegistrationRequest",
"capabilities": [
 {
 "seleniumProtocol": "WebDriver",
 "browserName": "internet explorer",
 "version": "11",
 "maxInstances": 5,
 "platform" : "WINDOWS",
 "idle-timeout":180,
 "ensureCleanSession": true,
 "record-screenshots":true,
 "ignoreProtectedModeSettings" :true
 },
 {
 "seleniumProtocol": "WebDriver",
 "browserName": "firefox",
 "version": "31",
 "maxInstances": 5,
 "platform" : "WINDOWS",
 "idle-timeout":180,
 "ensureCleanSession": true,
 "record-screenshots":true
  }
],
"configuration": {
 "port": 5555,
 "register": true,
 "host": "localhost",
 "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
 "maxSession": 2,
 "hubHost": "localhost",
 "role": "webdriver",
 "registerCycle": 5000,
 "hub": "http://localhost:4444/grid/register",
 "hubPort": 4444,
 "remoteHost": "http://localhost:5555"
}
}
```

**Comment by wakaleo** [comment]
If it works on Firefox it is most likely a Selenium issue, not a Serenity one.

**Comment by sudheerpujar** [comment]
Hi John,
Thanks for quick reply.  May be you are right.
The code fails whilst using IE driver with or without selenium plugin under Jenkins job or pipeline.
However the same code works with IE driver on the same windows box outside Jenkins (without selenium grid), I need to try using selenium grid setup outside Jenkins on same windows box where Jenkins has been installed. 
Let me try that and get back to  you and I will close this issue post that scenario.

**Comment by nbarrett** [comment]
I've seen this before - it's not a Serenity problem. It seems like the frequently reported problem with headless/screensaver enabled IE operation. See whether the suggestion documented [here](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3536#issuecomment-191999802) works?

**Comment by sudheerpujar** [comment]
@wakaleo 
Agreed this is not serenity problem, this absolutely selenium problem. we did a small prototype to prove this. 

@nbarrett, I have already tried the suggestion mentioned in the link before, couldn't succeed. 

I am closing this issue. Let you know if I find the resolution I will document the steps for others benefit.

**Comment by mandardjoshi** [comment]
@sudheerpujar have u find any resolution for above issue ?
