### ISSUE TITLE
How to make tests that are uploading files to work remotely also?

### ISSUE THREAD

**Issue by larisagrecu** [serenity-bdd/serenity-core#578]
It is possible to make tests that are uploading files from my local machine, to work on remote machines also? or integrate them with Jenkins to run on a cloud platform like Sauce Labs?
I am using this method from Serenity to upload files from my local Windows machine: `upload(path to the file).to(element input),`  but I don't understand exactly how it works.

**Comment by wakaleo** [comment]
The file needs to be accessible on the file system of the machine where the tests are being run.

**Comment by larisagrecu** [comment]
What does that mean more exactly? Do I have to put the files in a certain folder on my Windows machine? Currently, I give the whole path to the file,  like this: `C\\Work\\Files\\FileName.pdf`, in order for that method to work.

**Comment by wakaleo** [comment]
If the tests are running on a remote machine, then they won't have access to C\\Work\\Files\\FileName.pdf. You need to ensure that the file path you provide refers to a file that exists and is accessible no matter where the tests are run.

**Comment by slasva** [comment]
put file in project resource folder and use relative path

**Comment by larisagrecu** [comment]
Thank you for your suggestion. I will do the proper modifications

**Comment by loveshjain** [comment]
Using RemoteWebDriver

In order to enable the transfer of the file from your local machine to the remote machine so it can be uploaded, you need to set what's called a File Detector. Java example:

    driver.setFileDetector(new LocalFileDetector());
    WebElement upload = driver.findElement(By.id("myfile"));
    upload.sendKeys("/Users/sso/the/local/path/to/darkbulb.jpg");

for more details, have a look at "http://sqa.stackexchange.com/questions/12851/how-can-i-work-with-file-uploads-during-a-webdriver-test"

It worked for me uploading files on Saucelabs
