### ISSUE TITLE
WebElementFacade.waitUntilNotVisible() throws NoSuchElementException

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#579]
When `WebElementFacade.waitUntilNotVisible()` is called and the element doesn't exist at the point of invocation then a `NoSuchElementException` is thrown. This seems like an undesirable side effect and doesn't create a reliable/deterministic implementation in the following Screenplay Task:

```
public class TargetToBecomeInvisible implements Interaction {

    private final Target target;

    @Override
    @Step("{0} waits for #target to become invisible")
    public <T extends Actor> void performAs(T actor) {
        target.resolveFor(actor).waitUntilNotVisible();
    }

    public TargetToBecomeInvisible(Target target) {
        this.target = target;
    }

}
```

What I've had to do instead is to put some defensive coding in that task as follows:

```
    @Override
    @Step("{0} waits for #target to become invisible")
    public <T extends Actor> void performAs(T actor) {
        if (ResolveImmediately.isDisplayed(target, actor))
            target.resolveFor(actor).waitUntilNotVisible();
    }
```

Where `ResolveImmediately.isDisplayed` is implemented as described in [#558](https://github.com/serenity-bdd/serenity-core/issues/558#issue-180697663). But like that issue, this also seems like a hack and I wonder whether I'm missing a more idiomatic way of doing this.

**Comment by wakaleo** [comment]
`Target.resolveFor()` is really intended to be used internally - the semantics of the method is to resolve the element using the same logic as the `PageObject.element()` or `PageObject.$()` method, which will use the default implicit wait. 

Why not say:
```
actor.should(eventually(seeThat(target), isNotVisible()))
```

**Comment by nbarrett** [comment]
I tried your suggestion and changed this:

`actor.attemptsTo(WaitFor.targetToBecomeInvisible(WorkflowDetails.container));`
to
`actor.should(eventually(seeThat(the(WorkflowDetails.container), not(isVisible()))));`
and I got
`org.openqa.selenium.NoSuchElementException: Unable to find element with css selector == #singleEditContainerId (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.24 seconds`

Note that I've got the following properties set because the environment we have for uat can be very slow in places:

`webdriver.wait.for.timeout=60000
webdriver.timeouts.implicitlywait=60000
`

Until I've got a better understanding of what to do I will revert to what I was doing before as that works as I want it....

**Comment by nbarrett** [comment]
One further investigation - I tried a Selenium Expected Condition with a zero wait duration and passed this into wait method exposed by `RenderedPageObjectView` as follows:

    @Override
    @Step("{0} waits for #target to become invisible")
    public <T extends Actor> void performAs(T actor) {
        BrowseTheWeb.as(actor)
                .withTimeoutOf(0, TimeUnit.SECONDS)
                .waitFor(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(target.getCssOrXPathSelector())));
    }


This STILL takes `webdriver.timeouts.implicitlywait=60000` to complete. So it appears that the `withTimeoutOf()` is being ignored in the above. Perhaps that should be the subject of another issue?

**Comment by wakaleo** [comment]
The problem was the `resolveFor()` method, which checked that the actor could see the resolved target before proceeding. If the field wasn't present, it failed before getting to the `waitUntilNotVisible()` method. This check turns out to be unnecessary, and can be done later on.
