### ISSUE TITLE
Question: How to use serenity to execute WebDriver remotely (eg. via saucelabs)

### ISSUE THREAD

**Issue by markwinspear** [serenity-bdd/serenity-core#58]
Hi
I have a simple basic project set up which uses Selenium, Cucumber, Java in a Page Object Model setup (see github repo https://github.com/markwinspear/SeleniumCucumberJavaBasicTest2).  I noticed the flexibility and reporting capabilities of Serenity and am interested in seting up a project to try it out, however, my current project uses JUnit Rule to set up capabilities and interface with Sauce labs to execute and report on tests executed in the cloud.

Could you please advise how this could be done using Serenity please?

Note: I only have relatively basic developer skills (coming from a testing background)

**Comment by wakaleo** [comment]
This would be a better question for the Serenity User Group (https://groups.google.com/forum/#!forum/thucydides-users). But you should probably start with the Serenity documentation, and in particular: http://serenity-bdd.info/docs/serenity/#_running_remote_tests.

I'll close this issue as it isn't really a bug but more a request for information.

**Comment by roshanmpaul** [comment]
Hi we are trying to run remote tests using serenity in saucelab. Is there a way to pass the sauce connect tunnel information for executing tests remotely.  We are unable to use an existing tunnel to run the remote tests. 

Could you please advise?

Thanks!

**Comment by jyotimittal01** [comment]
I am looking for the same solution as @roshanmpaul.

Can we use saucelabs.url property to configure an existing sauce connect tunnel?

Thanks!

**Comment by nickpohle** [comment]
I'm a little late for you guys back in the '15-'17. But leaving the info for whoever comes after.
When you open your Saucelabs tunnel, you should include a **tunnel identifier** as:

`sc -u <userid> -k <accesskey> --tunnel-identifier "My Tunnel Identifier Name" --se-port 9001`

So then, in your **serenity.properties** file you can add:

`saucelabs.tunnelIdentifier = My Tunnel Identifier Name`

or in your serenity.conf:
```
saucelabs {
      tunnelIdentifier = My Tunnel Identifier Name
}
```
I've got the saucelabs.tunnelIdentifier property from: https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options

Hope this helps. Regards.
