### ISSUE TITLE
Running Serenity tests in parallel batches not working

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#580]
Tried to split tests in batches fallowing the examples provided in http://thucydides.info/docs/serenity-staging/#_running_serenity_tests_in_parallel_batches

The runner is not splitting the in separate batches.

Using:

```
serenity.batch.strategy=DIVIDE_BY_TEST_COUNT
serenity.batch.number=1
serenity.batch.size=2
```

We get an empty test run:

``` console
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.batch.number=1
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.batch.strategy=DIVIDE_BY_TEST_COUNT
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.batch.size=2
Running net.serenity.samples.batch.junit.features.registration.LoginUserTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in net.serenity.samples.batch.junit.features.registration.LoginUserTest
Running net.serenity.samples.batch.junit.features.registration.RegisterUserTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in net.serenity.samples.batch.junit.features.registration.RegisterUserTest
Running net.serenity.samples.batch.junit.features.registration.UserActivationProcessTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in net.serenity.samples.batch.junit.features.registration.UserActivationProcessTest

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- serenity-maven-plugin:1.1.42:aggregate (serenity-reports) @ serenity-junit-webtests ---
[INFO] serenity.batch.number=1
[INFO] serenity.batch.strategy=DIVIDE_BY_TEST_COUNT
[INFO] serenity.batch.size=2
[INFO] current_project.base.dir: D:\web_ser_try\serenity-demos-master\junit-batch-configuration-example
Generating HTML Story Reports from D:\web_ser_try\serenity-demos-master\junit-batch-configuration-example\target\site\serenity
Generating HTML Story Reports to D:\web_ser_try\serenity-demos-master\junit-batch-configuration-example\target\site\serenity
[WARNING] To generate correct requirements coverage reports you need to set the 'serenity.test.root' property to the package representing the top of your requirements hierarchy.
GENERATE CUSTOM REPORTS
[INFO]
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default) @ serenity-junit-webtests ---
[INFO] Failsafe report directory: D:\web_ser_try\serenity-demos-master\junit-batch-configuration-example\target\failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

If we use:

```
serenity.batch.strategy=DIVIDE_BY_TEST_COUNT
serenity.batch.number=2
serenity.batch.size=2
```

We run all the tests:  https://pastebin.mozilla.org/8920127

Is there something wrong with batch testing? Am I doing something wrong?

Here is the project: https://github.com/bebef1987/serenity_batches

**Comment by cliviu** [comment]
Hi @bebef1987. For the moment try to completely remove the maven-surefire-plugin from your pom.xml and run your batches again, let me know how it goes please.

**Comment by soap6gal** [comment]
I can't get DIVIDE_BY_TEST_COUNT nor DIVIDE_EQUALLY batches to run on Cucumber tests however junit tests are fine. I have the same build.grade settings in https://github.com/serenity-bdd/serenity-demos/tree/master/junit-batch-configuration-example and run the test via "gradle clean test aggregate". Any obvious reason why this wouldn't work on Cucumber tests?

**Comment by cliviu** [comment]
hi @soap6gal ! The batch functionality is not working on Cucumber tests.

**Comment by wakaleo** [comment]
At this stage batch testing is only supported for JUnit tests.

**Comment by soap6gal** [comment]
Thanks for clarifying. Does the batch feature support running the tests in different browsers?

**Comment by wakaleo** [comment]
No, but this is in the backlog as well.

**Comment by kxramas** [comment]
Serenity batch feature for JBehave and Cucumber will be of massive help. At this point I have Serenity-JBehave tests in my project and trying to convince other teams in the company to use Serenity. Not having parallel execution will be a highly minus point.

I have also noticed I can NOT use JBehave's external resource feature for parameterisation with Serenity. This is another short coming I face at the moment. Otherwise Serenity is a great tool!

Is it possible to provide these two features at the earliest ? 

Many thanks!

**Comment by wakaleo** [comment]
The simplest way to do parallel testing in both Cucumber and JBehave at the moment is to have multiple runners and run them in parallel with Maven or Gradle.

**Comment by wakaleo** [comment]
I'm closing this issue for now as it related to batch processing in Cucumber, which is not supported and probably won't be in that form.

**Comment by vitoo** [comment]
Hello @wakaleo 

is parallel execution & cucumber working for current version ?

Thanks you

**Comment by wakaleo** [comment]
No, it can't be done at the Serenity level since Serenity does not control scenario execution. But you can use https://github.com/temyers/cucumber-jvm-parallel-plugin

**Comment by wakaleo** [comment]
If you run batches on separate machines, you need to merge the results and generate an overall report from the combined results. If you are running tests in parallel on a single machine, you just need to use the cucumber-jvm-parallel-plugin plugin in "feature" mode.
