### ISSUE TITLE
Reading testdata from Excel

### ISSUE THREAD

**Issue by varunanilgupta** [serenity-bdd/serenity-core#581]
Hi,

I am running Automation test cases with @RunWith(CucumberWithSerenity.class).
We want to expose and maintain the Testdata separately in the Excel sheets instead of placing it in the Feature files.

The Template for Excel Testdata looks like:
|Scenario| UserName|Password|Name|Address|City|Pincode|
|Testcase1|testuser1|pass1|testUser1|US|Jersy|12345|
|Testcase1|testuser2|pass1|testUser1|US|Virginia|78955|

We have chose to use Primary Key as 'Scenario' which would be present in both Feature file and Excel sheet and based on that we will read the specific row from excel and refer the specific row data as Testdata for that particular Scenario.

Questions:
1. Is there a way to get the Scenario Name at run time from Feature file when Test is running, so that we can get the Excel sheet the extract the data for it from the Excel Sheets?
2. Is there a default way/method available in above mentioned use case, so that we can use it for above use case?

Any help around this would be appreciated.

**Comment by wakaleo** [comment]
As this is a question and not a bug, could you place it on StackOverflow with the #serenity-bdd tag?

**Comment by varunanilgupta** [comment]
Thanks !
I have opened the question on the StackOverflow:http://stackoverflow.com/questions/40523757/serenitycucumber-reading-testdata-from-excel

Please let me know if anyone have any info around this!!

**Comment by wakaleo** [comment]
Answered on StackOverflow

**Comment by CesarSalcedoCh** [comment]
Buenos días, estoy empezando una automatización con serenity y en el momento de crear el informe me aparece esto:
 error: package excelfile does not exist ... nota el paquete si existe 
 cannot find symbol
ayuda plis para darle solución.
