### ISSUE TITLE
FirefoxDriver does not use enhanced capabilities from fixtures

### ISSUE THREAD

**Issue by utwyko** [serenity-bdd/serenity-core#583]
FirefoxDriverBuilder does not use the CapabilityEnhancer and thus Firefox drivers creating using Serenity do not have their capabilities modified. I experienced this while using 1.1.42 with the browsermob plugin. The proxy that should be added to the driver's capabilities when using this plugin was not being set in the created driver.

**Comment by wakaleo** [comment]
This feature will be included in the next release

**Comment by utwyko** [comment]
Fixed in pull request #584

**Comment by wakaleo** [comment]
Fixed in 1.2.1-rc.3
