### ISSUE TITLE
resetImplicitTimeout() does not reset implicit wait timeout

### ISSUE THREAD

**Issue by stefanschenk** [serenity-bdd/serenity-core#59]
I've got a simple check if a certain element is present. For this check I have set the implicit timeout (per this [blog post] (http://thucydides-webtests.com/2015/03/20/serenity-2-0-42-and-the-new-timeout-api/)

I noticed that the resetImplicitTimeout does not reset the timeout value.

```java
setImplicitTimeout(1000, TimeUnit.MILLISECONDS);
Boolean loggedIn = navbar.isPresent();
resetImplicitTimeout();
```
I checked it with some logging of getImplicitWaitTimeout() and I can see that the Implicit timeout is not reset after de resetImplicitTimeout() call.

```java
before set: 2000 MILLISECONDS
after set: 1000 MILLISECONDS
after reset: 1000 MILLISECONDS
```

**Comment by wakaleo** [comment]
What driver are you using?

**Comment by wakaleo** [comment]
I can't reproduce this, could you write a test to illustrate the probem?
