### ISSUE TITLE
Serenity Unit tests fail when using @DefaultUrl("classpath:<static-site.html>")

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#595]
If I wish to create some unit tests to TDD my page objects, and I use the following static website pattern:
```
@DefaultUrl("classpath:static-site/error-modal-on-search/my-application.html")
public class SearchResultsErrorModalPage extends PageObject {
}
```

and then reference this as follows:

```
    @Managed(driver = "htmlunit")
    WebDriver browser;
    Actor actor = new Actor("MDM");
    actor.can(BrowseTheWeb.with(browser));

    SearchResultsErrorModalPage searchResultsErrorModalPage;
    givenThat(actor).attemptsTo(Open.browserOn().the(searchResultsErrorModalPage));
```

I find that when I run `@Test` cases individually, they work fine but when I run the whole test class or run all tests in the suite some fail. The nature of failure is that the website I expect to be there is not being rendered properly. Is there a different way to scope/instantiate the page object correctly/reliably?

**Comment by wakaleo** [comment]
Could be an HtmlUnit bug, have you tried with other drivers?

**Comment by nbarrett** [comment]
hmm, no it actually fails on all browsers.  Error is `org.openqa.selenium.NoSuchElementException: Returned node was not a DOM element`, Say 1 out of 4 tests fail - oddly enough it's the last one each time! 

![image](https://cloud.githubusercontent.com/assets/626941/20142696/cd142e74-a68d-11e6-9ef1-929575301533.png)

I see this sometimes when I run all tests in `net.serenitybdd.screenplay.webtests` directory in the `serenity-screenplay-webdriver` project
