### ISSUE TITLE
Possibility to change capability before tests

### ISSUE THREAD

**Issue by egorvas** [serenity-bdd/serenity-core#596]
Hi I am trying to use Serenity + Appium + Android for automated testing. And I faced with problem that I need run my Android application with different intents in different test classes. 
In appium I'm able to do that just setting special capability "optionalIntentArguments".
But in selenium I'm not able to do that because all capabilities for driver initialization I should have in properties file. 

So I need a way to set custom capability in test class during initialization of driver after @Manage annotation. Is it possible to do that?

**Comment by wakaleo** [comment]
For complete control you can use a provided driver (http://serenity-bdd.info/docs/serenity/#_custom_webdriver_implementations).
