### ISSUE TITLE
How to annotate lambda expressions?

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#597]
Given that I'm happily using Java 8 (yay!) then my inclination would be to use lambda expressions where possible to remove unnecessary boilerplate. So to this effect, I tried to refactor this:

```
       public Question<String> activity() {
            return new Question<String>() {
                @Subject("current activity")
                @Override
                public String answeredBy(Actor actor) {
                    return Text.of(activity).viewedBy(actor).value();
                }
            };

        }
```

to this:

```
        @Subject("current activity")
        public Question<String> activity() {
            return actor -> Text.of(activity).viewedBy(actor).value();
        }
```

however when I run the test, whilst the test still executes correctly,  the `@Subject` annotation does not work and I end up with this in my html report:

![image](https://cloud.githubusercontent.com/assets/626941/20149200/2d288764-a6a8-11e6-95d7-b3bfbf4c0f96.png)

rather than:

![image](https://cloud.githubusercontent.com/assets/626941/20149176/0edd8278-a6a8-11e6-9263-724af9c1e447.png)
 
What can I do to fix this please?

**Comment by wakaleo** [comment]
Lambda expressions don't support annotations. You need to add a parameter to the `seeThat()` method, as shown here:

```
        theActorInTheSpotlight().should(
                seeThat("Cheapest price", TheAvailableJourneys.lowestPrice(), isPresent()),
                seeThat("Origin station", TheAvailableJourneys.origin(), equalToIgnoringCase(expectedOrigin)),
                seeThat("Destination station", TheAvailableJourneys.destination(), equalToIgnoringCase(expectedDestination))
        );
```
