### ISSUE TITLE
Running serenity with Geb gives Tests skipped

### ISSUE THREAD

**Issue by Subrahmanyam83** [serenity-bdd/serenity-core#598]
This is my Runner Class:

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features="src/test/groovy/Features/",format = ["pretty","json:target/cucumber.json"],tags=["@smoketest"])
class GoogleRunnerSpec {
}

This is my test class:

class GoogleGSpec extends GebTest {

    @Given("^I open the Google Page")
    public void i_open_the_Google_Page(){
        to GooglePage
    }

    @Then("I type \"(.*?)\" in Search")
    public void search(String searchText){
        insertTextInSearchTextBox(searchText)
    }
}

This is my feature File:

Feature: New Feature

@smoketest
Scenario:   As a user, I should be able to search for a text
  Given     I open the Google Page
  Then       I type "Subrahmanyam" in Search

Running the feature file directly runs my tests but onrunning the Runner class it skips the tests.

Can someone let me know what I am missing ?

**Comment by wakaleo** [comment]
You are combining Geb with Serenity, which isn't really supported.

**Comment by Subrahmanyam83** [comment]
@wakaleo : Thanls for responding, But I was able to run the feature file and test cases were running. Its only when I run the Runner class, it says Tests Skipped. I would like to share my sample framework which I created. If you can just give me your email-id,I can share it with you. 
Thanks. Waiting for your response.

**Comment by Subrahmanyam83** [comment]
@wakaleo : It worked now !! The reason why the tests were skipping were because the Step definitions and Runner Class were not under the same package. I kept them under the same package now and now the tests are running.

Integartion of Serenity with Geb is now sucessfully running.

**Comment by wakaleo** [comment]
Thanks for the update!
