### ISSUE TITLE
Error when running jUnit tests with updated versions of Serenity bdd and Firefox

### ISSUE THREAD

**Issue by larisagrecu** [serenity-bdd/serenity-core#599]
I keep having very often the below error when running jUnit tests from Intellij command line with the following command: `gradlew clean test aggregate -Dtags="domain:SmokeTests"`

`The page object class de.telekom.commtech.bart.pages.common.TelekomLandingPageObject looks dodgy: Failed to instantiate page (net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver)
de.telekom.commtech.bart.steps.AbstractScenarioSteps.getTelekomLandingPageObject(AbstractScenarioSteps.java :52) 
de.telekom.commtech.bart.steps.inbox.AuthNavigationSteps.landingPageShouldAppear(AuthNavigationSteps.java :245) 
de.telekom.commtech.bart.testcases.BaseTest.login(BaseTest.java :447) 
de.telekom.commtech.bart.testcases.adressbook.lefthandnavigation.AdressBookContactsGroupTestCase.setup(AdressBookContactsGroupTestCase.java :46)`

I use latest version of `Serenity bdd` (1.1.42) and `Firefox 47.0.2`
If I run individual tests with `Run Configuration`, I don't get that error.

**Comment by wakaleo** [comment]
This is a Selenium rather than a Serenity problem - there may be some more information further on in the logs, but Selenium is unable to talk to the Firefox browser for some reason.

**Comment by larisagrecu** [comment]
Ok, thank you. I hope to find a workaround somehow.
