### ISSUE TITLE
unit tests flaky/intermittent following switch to phantomjs

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#600]
See screenshot following run of `net.serenitybdd.screenplay.webtests.WhenDanaBrowsesTheWeb`:

![image](https://cloud.githubusercontent.com/assets/626941/20322116/baa731dc-ab6f-11e6-94b4-3958dd46b8f2.png)

This is due to `org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.` Different tests fail on each run. This makes debugging and creating a PR for #595 really hard!!

Switching to this returns reliability:

```
    @Managed(driver = "htmlunit")
    WebDriver firstBrowser;

    @Managed(driver = "htmlunit")
    WebDriver anotherBrowser;
```

**Comment by wakaleo** [comment]
What version of PhantomJS do you have installed?

**Comment by wakaleo** [comment]
This sounds like a WebDriver issue rather than a Serenity issue. I'm not seeing it at all locally or on the CI server (I am using PhantomJS 2.1.1)

**Comment by nbarrett** [comment]
I'm using Negotiated Capabilities: `{"browserName":"phantomjs","version":"1.9.2","driverName":"ghostdriver","driverVersion":"1.0.4","platform":"windows-7-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}`

**Comment by wakaleo** [comment]
Could you try with a more recent version of Phantom (this looks like it is using 1.9.2)

**Comment by nbarrett** [comment]
ah great -  2.1.1\bin\phantomjs.exe fixed it! Sorry for any concern @wakaleo!
