### ISSUE TITLE
How can I run tests on Chromium browser?

### ISSUE THREAD

**Issue by im-zeeshan** [serenity-bdd/serenity-core#604]
Do I have to implement a custom web driver as mentioned in Serenity Manual Section 10 (http://thucydides.info/docs/serenity-staging/#_custom_webdriver_implementations) or is there a property that I can set in 'serenity.properties' file which will launch Chromium browser for all my tests?

**Comment by wakaleo** [comment]
set the webdriver.driver property to "chrome", on the command line or in your Serenity properties file.

**Comment by heerqa** [comment]
Also, add path to chromedriver in serenity.properties file
webdriver.chrome.driver=full path

**Comment by wakaleo** [comment]
Thanks @heerqa. You can either use the webdriver.chrome.driver property, or just make sure the chromedriver binary is on the system path. Using the webdriver.chrome.driver can make your tests machine or platform-specific.

**Comment by heerqa** [comment]
Thanks John!
I was not aware, i will use chromedriver binary going forward.

Thanks so much!!
