### ISSUE TITLE
No index.html in target/site/serenity (With Gradle)

### ISSUE THREAD

**Issue by juribes** [serenity-bdd/serenity-core#607]
Hi, I want to know if do you know of the same issue: No index.html in target/site/serenity (https://github.com/serenity-bdd/serenity-core/issues/83) but with gradle?

In http://www.thucydides.info/docs/serenity/ you have this comment for maven, but I'm using gradle, may be can you help me? Thx

"Tip: It is possible to use a Junit Run Configuration to run a Serenity Testrunner. This will not generate an aggregate report. If you find your index.html file is missing, check that you are using a Maven build Run Configuration with goal verify to run your test and get the aggregate report."

**Comment by wakaleo** [comment]
The Gradle equivalent is `gradle aggregate` (see http://www.thucydides.info/docs/serenity/#_building_serenity_projects_in_gradle)
