### ISSUE TITLE
Support for @SpringBootTest

### ISSUE THREAD

**Issue by csabakoncz** [serenity-bdd/serenity-core#608]
Spring Boot 1.4 introduces a new annotation called SpringBootTest (https://spring.io/blog/2016/04/15/testing-improvements-in-spring-boot-1-4). 
Unfortunately, it does not include `@ContextConfiguration` so it is not recognized as a Spring annotated class by Serenity's SpringDependencyInjector.

It would be nice if the check at https://github.com/serenity-bdd/serenity-core/blob/master/serenity-spring/src/main/java/net/serenitybdd/core/di/SpringDependencyInjector.java#L28 would include this new annotation so that Spring Boot integration tests can be easily driven by Serenity.
(right now the workaround is to add a `@ContextConfiguration` that points to the `@SpringBootApplication` and the other necessary `@Configurations`)

**Comment by wakaleo** [comment]
This is a good idea, and would be a great idea for a pull request ;-).

**Comment by csabakoncz** [comment]
Created a PR: https://github.com/serenity-bdd/serenity-core/pull/614

Unfortunately the tests require spring-boot-test:1.4 and Spring version upgrade to 4.3. 
The production code is fine without these, but I think testing is really important for Serenity :-)

**Comment by wakaleo** [comment]
This PR will be integrated into 1.2.1-rc.7
