### ISSUE TITLE
Is property "serenity.linked.tags" still supported?

### ISSUE THREAD

**Issue by klingerr** [serenity-bdd/serenity-core#609]
Hello,

I try to get linkable HTML pages and found the property "serenity.linked.tags". But it seems to have no effect. Is it still supported? There is no entry in the reference manual.

Is there another possibillity to get linkable HTML reports?

Cheers Ralf

**Comment by wakaleo** [comment]
What tags are you trying to link to?

**Comment by klingerr** [comment]
Custom tags from my cucmber feature files, like "@Block", "@Admin" used in this form "serenity.linked.tags = Block, Admin".

**Comment by klingerr** [comment]
Hello,

I've found my mistake. Tags are not my custom cucumber tags but your "related tags" like epic or feature. My currnt configuration looks like:

serenity.requirement.types = epic,feature,szenario
serenity.lowest.requirement.type = szenario
serenity.linked.tags = feature, epic

and now I get HTML files like "feature_projekt_verwalten_suchen.html" or "epic_login.html". So the property is still working (even not documented anymore).
