### ISSUE TITLE
HTML report rendering escapes underscore incorrectly

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#611]
The latest version of Serenity now  escapes the underscore (_) character incorrectly when rendering reports. So for a string `S6_FW_BOB_43999583_20161029_001231`, all but the last underscore character is removed from the visible report as follows:

![image](https://cloud.githubusercontent.com/assets/626941/20560056/57561264-b16f-11e6-9163-f676d1f81613.png)

And the html markup shows embedded `<em>` as follows:

![image](https://cloud.githubusercontent.com/assets/626941/20559921/b8c35b02-b16e-11e6-8221-2d7ebd988627.png)

**Comment by wakaleo** [comment]
Is that in a step description?

**Comment by nbarrett** [comment]
Sorry, yes - at all levels (top and drilldown). This is what the whole test report would look like: 

![image](https://cloud.githubusercontent.com/assets/626941/20564433/3a1913f2-b185-11e6-8d11-93a398670bbf.png)

**Comment by nbarrett** [comment]
Actually, I've just noticed this on the modal exception popup too:

![image](https://cloud.githubusercontent.com/assets/626941/21149936/325bc526-c155-11e6-8c36-518366f7c351.png)

When Inspected I can see some interesting markup :smile: :

![image](https://cloud.githubusercontent.com/assets/626941/21149973/59bda878-c155-11e6-92b0-873dca03fa7b.png)

**Comment by wakaleo** [comment]
It should be all good in version 1.2.1-rc.7

**Comment by wakaleo** [comment]
Fixed in 1.2.1-rc.7 onwards.
