### ISSUE TITLE
 junit.retry.tests=true does not rerun the failed tests

### ISSUE THREAD

**Issue by kajaleprashant24** [serenity-bdd/serenity-core#613]
HI,

I am trying to rerun the failed tests by specifying the following property in serenity.properties.

max.retries=2
junit.retry.tests=true

But the failed tests does not rerun.

**Comment by wakaleo** [comment]
This feature was deprecated some time ago, when JUnit added their own built-in equivalent (http://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html), and is no longer supported. We are currently working on a solution that will provide this capability across all platforms (JUnit, Cucumber, JBehave)

**Comment by kajaleprashant24** [comment]
SO will -DrerunFailingTestsCount=true rerun the failing tests?

**Comment by wakaleo** [comment]
It should do, yes.

**Comment by kajaleprashant24** [comment]
Hi John,

I am using maven fail safe plugin.

I tried both 

mvn -Dfailsafe.rerunFailingTestsCount=2 verify.

and 
mvn -Dsurefire.rerunFailingTestsCount=2 verify.

but none of this re ran my failed test.


Thanks,
Prashant

**Comment by wakaleo** [comment]
The retry logic is part of the Maven surefire/failsafe plugins; Serenity doesn't do anything particular in this area.

**Comment by rrussell39** [comment]
I am playing around this and got it to work.  Going here: http://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html
shows a pom file addition.  You then pass surefire.rerunFailingTestsCount=1 on the command line or set this value in your pom file. (assuming Maven)
And I was seeing my test retried.  I did also see the 'flaky' value when it failed but then succeeded on retry.  
The thing I'm researching is why JUnit's test reporting files are not sufficient to explain rerun tests whereas the Serenity docs suggest it's version is better (http://serenity-bdd.info/docs/serenity/#_retrying_failed_tests)

**Comment by ckurban** [comment]
Hi 

I have the same issue and it does not retry, here is my pom: 

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <rerunFailingTestsCount>3</rerunFailingTestsCount>
                    <includes>
                        <include>**/feature/document/*CukesTest.java</include>
                    </includes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit47</artifactId>
                        <version>2.20</version>
                    </dependency>
                </dependencies>
            </plugin>

Any help appreciated 

Thanks

**Comment by cliviu** [comment]
Hi, Can you please try to set the system property **test.retry.count** to the number of maximum retries for the failures, let me know please how it goes.

**Comment by BlacktoBlue** [comment]
Will this retry the entire run or just the individual tests that fail?

**Comment by Venue007** [comment]
I am also facing same issue. can anyone help me with how to rerun failed test cases in jenkins with surefire. Can you pls mention steps it will help for me.
