### ISSUE TITLE
Serenity Reports: Wrong number of tests when using Meta-Tags?

### ISSUE THREAD

**Issue by spcial** [serenity-bdd/serenity-core#617]
Hi!

We are using serenity with version 1.1.10, JBehave and PhantomJS for our testing. We are also using Meta-Tags in our testdata files and Meta Filtering when executing tests with maven. Currently we have a scenario with a testdata file where we have 8 testdata-sets. When using Tag-Filtering, only 4 of 8 testdata sets are executed (this is correct). But in the generated report we get following result:

![image](https://cloud.githubusercontent.com/assets/13414244/20670209/2eb89cf2-b578-11e6-88a5-f63b5b92ecff.png)

The pie is displayed correctly but actually the numbers in the table and the bars are irritation for me... the table says that there are 8 automated tests and 4 were executed successfuly. But no one is pending and no is ignored? Still the bar chart under the table let assume that 4 of 8 testsets were "pending". Why is that so?

Second question: Is there a possibility to show ONLY test-sets which are not excluded by tag-filtering? Because I'm only interested into the testcases which have the needed tag. So my wish would be a report where I get the information that 4 tests are automated and 4 passed. No intereset in the amount of tests which are not included by tag-filtering.

Thanks for any information!

**Comment by wakaleo** [comment]
Could you try with a more recent version of Serenity?

**Comment by spcial** [comment]
I tried localy with 1.1.36 but get exactly the same behaviour. Furthermore I found another bug:

![image](https://cloud.githubusercontent.com/assets/13414244/20701879/8a5f9982-b615-11e6-827a-ef9694dc5e1e.png)

As you can see the wrong testdata-set was marked. I would expect the second line with "@domain SDKGDSM" to be marked orange (I was using the meta-filter +domain SDKGDSM) because this exemple failed execution. But in this case the line with "@domain GELBAV" was marked (but was ignored). I can see this error on nearly all other test storys. Do I miss anything?

**Comment by wakaleo** [comment]
Please check for the latest version on search.maven.org. The latest stable release is 1.4.2, and the latest RC is 1.2.1-rc.6

**Comment by wakaleo** [comment]
Regarding your second comment, negative tags (using the ~ notation, e.g. -Dtags="~color:red" for all tests that are not red) has been introduced in the 1.2.x release stream.

**Comment by spcial** [comment]
Thank you for your help! I tried again with 1.1.42 and it truly looks different:

![image](https://cloud.githubusercontent.com/assets/13414244/20758416/0a1d0c04-b71a-11e6-99bc-2f2255e1e37e.png)

Still one question left: Is it possible to completely fade out ignored testcases? Example: I have 100 testcases and 4 different meta-tags (each meta-tag has 25 testcases). Depending on the case I would always only execute testcases which belong to 1 meta-tag. I would always get 75% ignored testcases in the pie chart which affects clarity of the report negatively. Is there another approach?

Thanks in advance.

**Comment by wakaleo** [comment]
Not yet, but in the next release ignores tests will be able to report on only on tests with a particular tag, and not the whole test suite.

**Comment by spcial** [comment]
OK. I closed the issue because no qestions left from my side. Can you tell in which release the feature will be available and when approx. the release will be available? Thanks.
