### ISSUE TITLE
net.thucydides.core.pages.WrongPageError: The page object class xylooks dodgy

### ISSUE THREAD

**Issue by spcial** [serenity-bdd/serenity-core#619]
When using serenity bdd 1.1.42 or 1.2.1-rc.6 I get following error message when executing a scenario with a certain pageObject:

> net.thucydides.core.pages.WrongPageError: The page object class com.generali.appl.betrieb.innendienst.pages.InnendienstPortal looks dodgy:
> Failed to instantiate page (java.lang.NullPointerException)
> 	at net.thucydides.core.pages.Pages.thisPageObjectLooksDodgy(Pages.java:267)
> 	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:218)
> 	at net.thucydides.core.pages.Pages.getPage(Pages.java:89)
> 	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:54)
> 	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:32)
> 	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:142)
> 	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:132)
> 	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:118)
> 	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:83)
> 	at net.thucydides.core.steps.StepFactory.getStepLibraryFor(StepFactory.java:77)
> 	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:52)
> 	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:41)
> 	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:23)
> 	at net.serenitybdd.jbehave.SerenityStepFactory.createInstanceOfType(SerenityStepFactory.java:82)
> 	at org.jbehave.core.steps.StepCreator.stepsInstance(StepCreator.java:85)
> 	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:599)
> 	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:340)
> 	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1072)
> 	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:938)
> 	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1011)
> 	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:883)
> 	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:811)
> 	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:784)
> 	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
> 	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
> 	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
> 	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:273)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1176)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:795)

The strange thing is that I don't get this error with older version e.g. 1.1.0

Any ideas why I could get this error?

**Comment by wakaleo** [comment]
Could you post your InnendienstPortal page object?

**Comment by spcial** [comment]
Sure. I just replaced the method code with //XY to make it a little bit smaller and deleted the comments.

```
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import net.serenitybdd.core.annotations.findby.FindBy;
import net.serenitybdd.core.pages.PageObject;
import net.thucydides.core.util.EnvironmentVariables;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;

import com.google.common.base.Predicate;


public class InnendienstPortal extends PageObject {

public InnendienstPortal(WebDriver driver,EnvironmentVariables environmentVariables) {
		super(driver, environmentVariables);
		// TODO Auto-generated constructor stub
 }

public InnendienstPortal(WebDriver driver, int ajaxTimeout) {
		super(driver, ajaxTimeout);
		// TODO Auto-generated constructor stub
}

public InnendienstPortal(WebDriver driver,Predicate<? super PageObject> callback) {
		super(driver, callback);
		// TODO Auto-generated constructor stub
}

String winHandle = null;

    private static final String CLASS_INFO_BOX = "infoBox";

    @FindBy(linkText = "Mein Profil")
    WebElement linkMeinProfil;

    @FindBy(linkText = "Abmelden")
    WebElement linkAbmelden;

    @FindBy(linkText = "Postkorb")
    WebElement hoverPostkorb;

    @FindBy(linkText = "Kunden, Verträge und Schäden")
    WebElement hoverKundenVertraegeUndSchaeden;

    @FindBy(linkText = "Bestandssuche")
    WebElement hoverKVSElementBestandssuche;

    @FindBy(linkText = "Neuen Kunden anlegen")
    WebElement hoverKVSElementNeuenKundenAnlegen;

    @FindBy(linkText = "Services")
    WebElement hoverServices;

    @FindBy(linkText = "Labor")
    WebElement hoverLabor;

    @FindBy(id = "newTab")
    WebElement linkNeuerArbeitsplatz;

    @FindBy(id = "portalSearchId")
    WebElement inputPortalSuche;

    @FindBy(id = "submitPortalSearchBtn")
    WebElement linkPortalSuche;

    public InnendienstPortal(WebDriver webdriver) {
        super(webdriver);
        winHandle = this.getDriver().getWindowHandle();
    }

    public void oeffnen(URL url) {
        setDefaultBaseUrl(url.toString());
        open();
    }

    public void oeffneKundenVertraegeUndSchaeden() {
        // XY
    }

    public void geheZuBestandssuche() {
        // XY
    }

    public void geheZuPostkorbAnsicht() {
        // XY
    }

    public void abmelden() {
        // XY
    }

    public boolean werdenHinweiseAngezeigt() {
        // XY
    }

    public List<String> getHinweise() {
        // XY
    }


    public void wechsleZuAltemFenster() {
        // XY
    }


    public void wechsleZuNeuemFenster() {
        // XY
    }

}`

**Comment by wakaleo** [comment]
I can't reproduce the issue with this code, could you post the @Step class that is using it?

**Comment by spcial** [comment]
I just tried to reproduce this error with version 1.2.1-rc.8 and I don't get the error anymore. Beside of changing the version I changed the encoding to UTF-8. Probably this fixed the error? I don't know what the reason was. If this error appears again in the future I will reopen the ticket. Thank you for your support (I'm closing this ticket) :-)

**Comment by SiKing** [comment]
Hello.

I realize this issue has been closed for some time, but I am facing the same problem. I can open a new ticket if that is preferred?

I am using **serenity-cucumber 1.9.20** (latest release at this time).

I created the following case that reproduces this error:

```cucumber
Feature: Open Google page

  Scenario: Open Google page
    Given I open Google page
    Then The page title should contain "Google"
```

```java
package steps;

import org.junit.Assert;

import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import pages.GooglePage;

public class GoogleSteps {

    GooglePage googlePage;

    @Given("^I open Google page$")
    public void i_open_Google_page() {
	googlePage.open();
    }

    @Then("^The page title should contain \"([^\"]*)\"$")
    public void the_page_title_should_contain(String value) {
	Assert.assertEquals(value, googlePage.getTitle());
    }
}
```

```java
package pages;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import net.serenitybdd.core.annotations.findby.By;
import net.thucydides.core.annotations.DefaultUrl;
import net.thucydides.core.pages.PageObject;

@DefaultUrl("https://www.google.com")
public class GooglePage extends PageObject {

    public GooglePage(WebDriver driver) {
	super(driver);

	/*
	 * I need to perform additional setup here!
	 * 
	 * The setup involves reading information from the page - touching
	 * WebElements. Just to show the error, either ONE of the following
	 * produces this error.
	 */
	q.isDisplayed();
	getDriver().findElement(By.id("q")).isDisplayed();
    }

    public String getTitle() {
	return getDriver().getTitle();
    }

    // search box
    private WebElement q;

    public void setSearch(String value) {
	q.sendKeys(value);
    }
}
```

This produces the error:

> net.thucydides.core.pages.WrongPageError: The page object class pages.GooglePage looks dodgy:
Failed to instantiate page (org.openqa.selenium.NoSuchElementException: Timed out after 2 seconds. Element not found

Any advice?

**Comment by wakaleo** [comment]
There should be no WebDriver code in the constructor

**Comment by SiKing** [comment]
@wakaleo 
If I try just:

```java
    protected GooglePage() {
	super();

	/*
	 * I need to perform additional setup here!
	 */
	q.isDisplayed();
	getDriver().findElement(By.id("q")).isDisplayed();
    }
```

Then I get:

>net.thucydides.core.pages.WrongPageError: The page object class pages.GooglePage looks dodgy:
This page object does not appear have a constructor that takes a WebDriver parameter

**Comment by wakaleo** [comment]
Don’t put any code in the Page Object constructor

**Comment by SiKing** [comment]
Really?
How do people populate PageObjectMaps?
Do you guys have any plans to address this?

**Comment by wakaleo** [comment]
It’s just the way Page Objects work. Page Object  should never interact with the page as you don’t know when the object will be create. Use last loading and dynamic element resolution.

**Comment by SiKing** [comment]
I have always done this with Selenium PageObejcts. I only recently started looking at Serenity.
It appears that Serenity manipulates PageObjects differently, so I guess PageObjectMaps will be slower as I have to call the creation from every method.
:(

**Comment by tdudhale** [comment]
@DefaultUrl("https://www.fitflop.com/uk/en/login/auth#/")
public class HomePage extends PageObject {

    @FindBy(css = "button[value='Search']")
    WebElementFacade searchButton;

    private final static String SHOP_SUGGESTION = "//div[@class='as-suggestion' and contains(.,'%s')]";

    public void enterSearchTerms(String keyword) {
        $("#features-query").type(keyword);
        withTimeoutOf(10, TimeUnit.SECONDS).waitForPresenceOf(By.xpath(String.format(SHOP_SUGGESTION, keyword.toLowerCase())));
        waitForKeywordToBeUpdatedTo(keyword);
    }

    private void waitForKeywordToBeUpdatedTo(String keyword) {
        waitForCondition()
                .withTimeout(5, TimeUnit.SECONDS)
                .pollingEvery(250, TimeUnit.MILLISECONDS)
                .until(keywordFieldIsUpdatedTo(keyword));
    }

    private Function<? super WebDriver, Boolean> keywordFieldIsUpdatedTo(String keyword) {
        return webDriver -> $("#features-query").getValue().equalsIgnoreCase(keyword);
    }

    public void search() {
        searchButton.click();
    }

    public void searchForShopCalled(String shopName) {
        enterSearchTerms(shopName);
        $(String.format(SHOP_SUGGESTION, shopName)).click();
    }

    public void dismissLocationMessage() {
        if (!findAll(By.cssSelector("input[value='Okay']")).isEmpty()) {
            find(By.cssSelector("input[value='Okay']")).click();
        }
    }

    @FindBy(xpath = ".//div[@id='UmaThurmanBarComponent']")
    private WebElement header;

    @FindBy(xpath = "//div[@class='menu']/ul/li")
    private WebElement menuBar;

    @FindBy(className = "product-list__slider-image")
    private List<WebElement> products;

    @FindBy(xpath = "//ul[@class='menu-level-three']/li")
    List<WebElement> umaCategary;
    private List<WebElementFacade> webElementFacades;

    @FindBy(id = "email")
    WebElement email;

    @FindBy(css = "span.form-checkbox__checkbox")
    WebElement choiceWomen;

    @FindBy(css = "button.button--stretch")
    WebElement btnContinue;

    public void getAllTabs(List<String> categories) {
        List<String> categaries = new ArrayList<>();
        webElementFacades = findAll(By.cssSelector("ul.menu-level-one>li>a"));
        webElementFacades.forEach(
                webElementFacade -> {
                    System.out.println("cate" + webElementFacade.getText());
                    categaries.add(webElementFacade.getText());
                }
        );

    }

    public void clickOnCategory(String category) {
        find(By.cssSelector("a[data-titleen='" + category + "']")).click();
    }

    public void clickOnSubCategory(String subcat) {
        find(By.cssSelector("data-titleen='" + subcat + "']")).click();
        //umaCategary.get(0).click();
    }

    public void clickOnProduct() {
        clickOn(products.get(1));
        List<WebElementFacade> all = findAll(By.cssSelector("a[title='Black']"));
    }

    public void selectColorAndSizeAndAddProduct(String color, String size) {
        WebElement webElementColor = find(By.cssSelector("a[title='" + color + "']"));
        webElementColor.click();
        List<WebElementFacade> sizes = findAll(By.cssSelector("li.pdp__size-selector-item"));
        for (WebElementFacade webElementFacadeSize : sizes
        ) {
            if (webElementFacadeSize.getText().equalsIgnoreCase(size)) {
                webElementFacadeSize.click();
                break;
            }
        }
        clickOn(find(By.cssSelector("span.pdp__add-to-bag-button-text")));
    }

    public void goToCart() throws InterruptedException {
        WebElementFacade button = find(By.xpath("//button[@class='nav-btn nav-btn__bag ']"));
        // WebElementFacade webElementFacades = find(By.xpath("//span[@class='nav-btn__label-inner']/span[text()='Bag']"));
        button.click();
        button.click();
        Thread.sleep(2000);
    }

    public void goToCheckout() {
        find(By.cssSelector("button.cart-order-summary__cta-btn")).click();
    }

    public void selectGuestCheckout() {
        find(By.cssSelector("div.section-option__content")).click();
    }

}

**Comment by jeevan1987cool** [comment]
> Don’t put any code in the Page Object constructor

I have tried this way. But it is still causing same error.

I have a BasePage class and other Pages extends this class.

**BasePage**
```
public class BaseClass extends PageObject {
  public BaseClass(final WebDriver driver) {
         super();
       }
}
```
**RegistrationPage**
```
public class RegistrationPage extends BasePage {
public RegistrationPage(WebDriver driver) {
		super(driver);
	}
}
```

Still, I get the error "net.thucydides.core.pages.WrongPageError: The page object class com.test.iOSAutomation.pages.RegistrationPage looks dodgy:"

and if I remove constructor from BasePage and other classes then it gives null pointer.

Not sure how to instantiate it properly.

I am using:
<serenity.version>2.0.81</serenity.version>
<serenity.cucumber.version>1.9.45</serenity.cucumber.version>

Using Mac, trying iOS Automation on a real device.

**Comment by arm235** [comment]
I am also facing similar issue for only one page. Could you please help me with this.
net.thucydides.core.pages.WrongPageError: The page object class com.qa.pages.PermissionPage looks dodgy:
Failed to instantiate page (java.lang.NullPointerException)

**Comment by anweshadhal** [comment]
@SiKing did you get a solution for this kind of errors? as i'm also getting the error
