### ISSUE TITLE
Serenity jbehave issue when using multiple scenario outlines in a single .feature file

### ISSUE THREAD

**Issue by njagadee** [serenity-bdd/serenity-core#62]
We are using Serenity with JBehave. We are facing issues when we have multiple scenario outlines with examples table in a single .feature file.

we have something like this in our .feature file.

 Scenario Outline: title 1
 Given
 When
 Then
 Examples:
 |data|

Scenario Outline: title 2
Given 2
When 2
Then 2
Examples:
|Data|
In this case after executing “Examples” of Scenario 1, it is considering Scenario outline 2 also as an input to scenario 1 example table, instead of treating it as a new scenario.

This is how the output looks like:

 Scenario Outline: title 1
 Given
 When
 Then
 Examples:
 |data|
 |Scenario Outline: title 2|
 |Given 2|
 |When 2|
 |Then 2|
 |Examples:|
 |Data|

Here are the versions of plugins: 
jbehave.core.version - 3.9.5; 
serenity.version - 1.0.47; 
serenity.jbehave.version - 1.0.21

Can someone please help resolve this? We seem to be blocked by this issue.

Note: I have seen posts where people had same issues when using "scenario" with examples table rather than using "scenario outline" with examples. Here I am using "scenario outline" only, but still have the same issue.

**Comment by wakaleo** [comment]
I'm not seeing this reproduced - could you create a sample project that reproduces the issue?

**Comment by YamStranger** [comment]
Hello @njagadee. Thanks for creating this issue.  
I updated feature under [serenity-demo](https://github.com/serenity-bdd/serenity-demos/blob/master/cucumber-webtests/src/test/resources/features/search/search_by_keyword.feature) to reproduce your issue. 
feature file was used
```
@component:ui
@version:Release-2
@issue:ETSY-102
Feature: Search by keyword
  In order for buyers to find what they are looking for more efficiently
  As a seller
  I want buyers to be able to search for articles by keywords

  Scenario: Search for articles by keyword
    Given I want to buy a wool scarf
    When I search for 'wool'
    Then I should see only articles related to 'wool'

  Scenario Outline: Search by shop name
    Given I want to see articles from a particular shop
    When I search by shop for '<shopname>'
    Then I should find 1 shop called '<shopname>'
  Examples:
    | shopname      |
    | agdesignworks |
    | docksmith     |

  Scenario Outline: Search for many articles by keyword
    Given I would like to buy a <article>
    When I search for '<article>'
    Then I should see only articles related to '<keyword>'
  Examples:
    | article        | keyword |
    | wool scarf     | wool    |
    | cotton shirt   | cotton  |
```

To check results I execute
```
mvn clean verify
```
Here is results report for this scenario:
![62_issue](https://cloud.githubusercontent.com/assets/1667699/11226585/97b4a4b6-8d89-11e5-8101-19ed42627b81.png)

It seems that all executed correctly, and in report we can find agdesignworks  and docksmith. 
I hope it helps you. 

Thanks!!

**Comment by njagadee** [comment]
Thank you! Was this an issue with Serenity? If so, which version has this fix?

**Comment by YamStranger** [comment]
@njagadee I tested it on last version. There was no bug. You can check it by my previous comment )
