### ISSUE TITLE
Step details are difficult to read in screen shots

### ISSUE THREAD

**Issue by rrussell39** [serenity-bdd/serenity-core#622]
![screen shot 2016-12-06 at 2 59 12 pm](https://cloud.githubusercontent.com/assets/8116184/20947653/059ab1a4-bbc5-11e6-8d68-6787958cea86.png)

Is there a way to change the color of the font for the Step details in the screen shots?  (See attached).  The readability is very poor and I'm wondering if this is a configuration property, and if not, consider this an enhancement request.

More specifically - the method name shows in white on black and the method args are in blue.  If you have a dark header (like the portal I'm testing) then it's really hard to debug.

Thanks!
Keyword: readable

**Comment by wakaleo** [comment]
This might be fixed in the next release (1.2.1-rc.7)
