### ISSUE TITLE
SelectByValueFromTarget uses visibleText

### ISSUE THREAD

**Issue by renardeau** [serenity-bdd/serenity-core#623]
While attempting a selection by value I noticed the selector is using visibleText rather than by value

`
    @Step("{0} clicks on #target")
    public <T extends Actor> void performAs(T theUser) {
        target.resolveFor(theUser).selectByVisibleText(value);
    }
`
Suggested correction:
`    @Step("{0} clicks on #target")
    public <T extends Actor> void performAs(T theUser) {
        target.resolveFor(theUser).selectByValue(value);
    }` 
Problem only present when selecting from Target
See also https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/actions/selectactions/SelectByValueFromTarget.java

**Comment by wakaleo** [comment]
Thanks, you are absolutely correct - I'll fix this in the next RC, or feel free to create a pull request if you would like your name in the list of committers :-).

**Comment by renardeau** [comment]
Thanks for the fast reaction!
No need for a pull request, if it gets fixed, that's more than enough for me ;-)

**Comment by wakaleo** [comment]
This should be fixed in 1.2.1-rc.7

**Comment by wakaleo** [comment]
Fixed.
