### ISSUE TITLE
Getting two output directories when trying to customize outputDirectory

### ISSUE THREAD

**Issue by rrussell39** [serenity-bdd/serenity-core#63]
Has anyone been able to redirect output for either Thucydides or Serenity to a custom directory?

The default report dir is <$project root>/target/site/thucydides
Or
<$project root>/target/site/serenity
Depending on the version of thucydides/serenity you are using.

When I choose to customize the output directory using:
serenity.source=target/site/thucydides/
serenity.outputDirectory=target/site/thucydides/
I've also tried:
thucydides.outputDirectory=target/site/thucydides

The reporting pieces are correctly generated in target/site/thucydides/
But when the <b>aggregate</b> command is executed, the final index.html file is generated in the target/site/serenity directory and it is non-functional as the reporting files are split between the thucydides and serenity dirs.

My environment:
Serenity 1.0.47
MacOS 10.10
Firefox 38

Thanks,
Rob

**Comment by rrussell39** [comment]
Ok - since posting this I have got it to work. I had to set this property on the command line:
thucydides.outputDirectory=target/site/thucydides
The tricky part is that the log warnings indicate:
2015-05-18 14:12:46,919 [main] WARN net.thucydides.core.ThucydidesSystemProperty.legacyPropertyValueIfPresentIn:712 Legacy property format detected for thucydides.outputDirectory, please use the serenity.* format instead.
However, using serenity.outputDirectory DOES NOT work. Further, setting either value in the thucydides.properties file DOES NOT work.
Is that a bug?

**Comment by wakaleo** [comment]
Yes, it's a bug with the Maven plugin - should be fixed in the next release. Thanks for hunting down all the details.

**Comment by rrussell39** [comment]
Ok great - thanks for confirming.  Can you confirm the details of the fix?  I will be able to use "serenity.outputDirectory" or "thucydides.outputDirectory" in the thucydides.properties file OR on the command line?

**Comment by wakaleo** [comment]
You will be able to use "serenity.outputDirectory" both on the command line and in the thucydides.properties file.

**Comment by rrussell39** [comment]
Thanks!

**Comment by rrussell39** [comment]
Sorry to reopen this but, if I cannot wait until the next release, what is the best workaround?  I really need to have a way to configure the output directory in the code via a property or even to hack it in myself such that the plugin will honor it.  Any ideas?  I would even build a local version of the plugin myself if I had an idea of what the issue was.

**Comment by rrussell39** [comment]
I'm simply setting the outputDirectory property to be the old directory so that it will work for clients who have not updated and those who have.

**Comment by c-mu** [comment]
I see the same behavior with the gradle plugin. When using the outputDirectory property test results are being stored there, but the index.html is created in the default directory target/site/serenity.
