### ISSUE TITLE
Mark @manual in cucumber feature file not ignore steps in background

### ISSUE THREAD

**Issue by aquadrehz** [serenity-bdd/serenity-core#630]
Marking the **@manual** before 'Feature:' should work as **@skip**

**Expected result**
 - Treat all scenario and background steps as manual pending
No script executed here
 - Report count these scenarios as pending (manual correctly) 
![serenity-coreissues 630 skipbeforefeatureworked](https://cloud.githubusercontent.com/assets/3850078/21133099/bf1bc2ec-c149-11e6-97de-70d45e5ecbb0.jpg)

**Actual result**
 - Steps in the background section are executed.
 - Report count as passed
![serenity-coreissues 630 manualbeforefeaturenotwork](https://cloud.githubusercontent.com/assets/3850078/21133100/bf4df2da-c149-11e6-8528-a73647032fea.jpg)

**Comment by wakaleo** [comment]
Could you try with 1.2.1 (serenity-core) and 1.1.4 (serenity-cucumber)?

**Comment by aquadrehz** [comment]
The scenario status and report result page are correct.
But each **steps status still incorrect.**

> serenity.version = 1.2.1-rc.8
> serenity.maven.version = 1.2.1-rc.8
> serenity.cucumber.version = 1.1.14

![630 statusshouldskipped](https://cloud.githubusercontent.com/assets/3850078/21345249/0ae6b3fc-c6d2-11e6-99ab-168de92c9c74.jpg)

**Comment by wakaleo** [comment]
Could you try with 1.2.1, not 1.2.1-rc.8?

**Comment by aquadrehz** [comment]
Tried again and the **result still incorrect.**
![630 statusshouldskipped121](https://cloud.githubusercontent.com/assets/3850078/21345722/def1357c-c6d3-11e6-8385-d6e212014b82.jpg)

**Comment by wakaleo** [comment]
Should be fixed in 1.2.1-rc.5 and 1.1.18
