### ISSUE TITLE
Junit test case not failing when exception occurred in step class when timeout is specified in the main class

### ISSUE THREAD

**Issue by harishgarg0502** [serenity-bdd/serenity-core#635]
Hi,

we are trying to run a Junit test case with serenity. Test case uses step class and a main class. when @Test(timeout=2000) is specified in the main class and if any exception occurred in the step class, the same exception is not propagated in the main class and test case is not getting failed and it gets successfully passed.Can anyone please explain this behavior and how to resolve it. Below is the sample what the problem is:-

Class Abc{

@Steps 
XYZ xyz;

@Test(timeout=20000)
public void abc throws Exception{
xyz.func();
}
}

public class XYZ{
@step
public void func(){
System.out.println(1/0);
}
}

**Comment by wakaleo** [comment]
JUnit seems to create a new thread for timeout tests, which upsets the Serenity event bus, and gives no obvious way to catch the timeout exception, so timeout tests are not supported for now.

**Comment by sneharora** [comment]
isn't this a basic requirement for any test case automation framework? Could you suggest any alternate way of handling this?  Also is there a plan to address this in near future?

**Comment by wakaleo** [comment]
Sorry, I misread your original issue. This has been fixed and will be available in the next release.

**Comment by sneharora** [comment]
@wakaleo  Thanks a lot! Could you also let know the relaese version in which this will be available and the timelines! Thanks in advance!

**Comment by wakaleo** [comment]
It is available in version 1.1.2-rc.9
