### ISSUE TITLE
Retry failed test isn't working

### ISSUE THREAD

**Issue by volnoboy** [serenity-bdd/serenity-core#638]
I have found a serenity feature to retry failed test. For some reason it is not working.
 I have added:
```
max.retries=3
junit.retry.tests=true
```

to Serenity settings. I am using serenity 1.1.39 with Jbehave. 
Is anything else I have to do?

**Comment by wakaleo** [comment]
This feature was never supported for JBehave, and has been replaced by the native JUnit/surefire equivalent for JUnit.

**Comment by rakeshnambiar** [comment]
@wakaleo I tried the Steps mentioned in the below link and it's not worked. Do you have any sample project or POM?

http://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html

**Comment by wakaleo** [comment]
The Surefire plugin will only work for JUnit. There is no equivalent feature for JBehave.

**Comment by rakeshnambiar** [comment]
Sorry - I tried for JUnit-Cucumber and Not for JBehave

**Comment by wakaleo** [comment]
As I said, the Surefire plugin retries will only work for JUnit.

**Comment by rakeshnambiar** [comment]
Ok, Thanks. Is there any plan to accommodate this feature as an enhancement in serenity list?
