### ISSUE TITLE
Use @manual tag cause ClassCastException in cucumber feature file

### ISSUE THREAD

**Issue by aquadrehz** [serenity-bdd/serenity-core#639]
Step definition method passed correctly when executing with not @manual
**But when add @manual** to a scenario, it display error message

**Feature file and result**
![639 classcastexceptionfaetureandresult](https://cloud.githubusercontent.com/assets/3850078/21490237/eb94acae-cc24-11e6-825a-0cfbbdfa03ac.jpg)

**Class detail**
![639 classcastexceptiondestination](https://cloud.githubusercontent.com/assets/3850078/21490234/ea212744-cc24-11e6-8658-1a079dfc48e6.jpg)

**Comment by wakaleo** [comment]
Fixed in 1.1.18

**Comment by aquadrehz** [comment]
Thank you @wakaleo
