### ISSUE TITLE
reset implicitly timeout issue. **CRITICAL**

### ISSUE THREAD

**Issue by alexamber** [serenity-bdd/serenity-core#64]
Seems to be a recall to **[present issue](https://github.com/serenity-bdd/serenity-core/issues/59)**
**Serenity 1.0.47**
Implicitly timeout in WebDriver is not reset to the previous value correctly. For example after isCurrentlyVisible method was called it creates **two similar** entries in TimeoutStack instance with value "0" that is used in net.thucydides.core.webdriver.WebDriverFactory.resetTimeouts() method so the implicitly timeout is not reset to the previous value and stays equal to "0" causing unexpected failures. It seems that operation with TimeoutStack while finding elements has some bugs that cause creating of duplicates of timeout values. Please investigate what can be done to fix the issue. I suggest in to be critical for those who move to serenity and actively use implicitly waits.

**Comment by wakaleo** [comment]
Can you create a test case to reproduce the issue this is causing? Here is the test that seems to exercise the scenario you describe:

```
    def "You can override the implicit wait during test execution"() {
        given: "The #slow-loader field takes 3 seconds to load"
            page = openTestPageUsing("phantomjs")
        when: "We override the implicit timeout to allow the slow-loader field to load"
            page.setImplicitTimeout(5, SECONDS)
        then: "we should be able to access the slow-loader field"
            page.slowLoadingField.isVisible()
        and: "we can reset the driver timeouts to the default value once we are done"
            page.resetImplicitTimeout()
        and:
            page.driver.currentImplicitTimeout.in(SECONDS) == 2
    }
```

**Comment by alexamber** [comment]
Hi. I`ve created a demo project which I hope will help to reproduce the bug on your side.
You just need to import it to IDE and set paths to the chromedriver\phantomjs in your system.
https://drive.google.com/file/d/0BxvxRApe_YizdUgxYmNiZTlZQ1k/view?usp=sharing

In the demo test story tries to check visibility of different elements(present and absent in DOM). While playing around please see how implicitly wait in webdriver and pageobject is changing, how timeoutstack is filling and resetTimeout method works.
I`ve got the following log on y side:

[pool-1-thread-1] INFO HomePage - Checking if existent element visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 260
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Checking if non-existent element visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 5054
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Checking if non-existent element currently visible (isCurrentlyVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 56
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Checking if non-existent element 2 visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 22
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Restoring WebDriver Timeout manually by getDriver().manage().timeouts().implicitlyWait
[pool-1-thread-1] INFO HomePage - Checking if non-existent element 2 visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 5049
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Setting implicitly wait to 0 by setImplicitTimeout()
[pool-1-thread-1] INFO HomePage - Checking if non-existent element 2 currently visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 16
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 0 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Restoring WebDriver Timeout manually by resetImplicitTimeout()
[pool-1-thread-1] INFO HomePage - Checking if non-existent element 2 currently visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 10
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 0 MILLISECONDS

Thank You.
Hi. I`ve created a demo project which I hope will help to reproduce the bug on your side.
You just need to import it to IDE and set paths to the chromedriver\phantomjs in your system.
https://drive.google.com/file/d/0BxvxRApe_YizdUgxYmNiZTlZQ1k/view?usp=sharing

In the demo test story tries to check visibility of different elements(present and absent in DOM). While playing around please see how implicitly wait in webdriver and pageobject is changing, how timeoutstack is filling and resetTimeout method works.
I`ve got the following log on y side:

[pool-1-thread-1] INFO HomePage - Checking if existent element visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 260
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Checking if non-existent element visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 5054
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Checking if non-existent element currently visible (isCurrentlyVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 56
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Checking if non-existent element 2 visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 22
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Restoring WebDriver Timeout manually by getDriver().manage().timeouts().implicitlyWait
[pool-1-thread-1] INFO HomePage - Checking if non-existent element 2 visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 5049
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 5000 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Setting implicitly wait to 0 by setImplicitTimeout()
[pool-1-thread-1] INFO HomePage - Checking if non-existent element 2 currently visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 16
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 0 MILLISECONDS
[pool-1-thread-1] INFO HomePage - Restoring WebDriver Timeout manually by resetImplicitTimeout()
[pool-1-thread-1] INFO HomePage - Checking if non-existent element 2 currently visible (isVisible)
[pool-1-thread-1] INFO HomePage - TOOK: 10
[pool-1-thread-1] INFO HomePage - Current Implicitly timeout in Page Object: 0 MILLISECONDS

Thank You.

**Comment by alexamber** [comment]
As I can see the problem have not been fixed fully by the committed changes. Each method, after isCurrentlyVisible() method, is performed with 0 implicitlywait timeout despite the fact that I can see non-zero value of implicitlytimeout wait in PageObject. WebDriverFactory, WebElementImpl classes during test execution. Also I discovered that everything works as expected if we place         resetImplicitTimeout() method after isCurrentlyVisible().
So the code below works incorrectly:
```
searchButton.
searchButton.isCurrentlyVisible();
nonExistentInDomElement.isVisible()
//the timeout for the last method is unexpectedly 0 
```
So the code below works correctly but needs excessive method:
```
searchButton.
searchButton.isCurrentlyVisible();
resetImplicitTimeout();
nonExistentInDomElement.isVisible()
//the timeout for the last method is default implicitlytimeout set in properties
```
Please try to do additional investigation in the scope of the issue.
