### ISSUE TITLE
InvalidManagedWebDriverFieldException when "@Managed was found in the test case"

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#641]
I use Serenity `1.2.1` to execute REST API tests. The code below is valid and performs without any error. 

```
@RunWith(SerenityParameterizedRunner.class)
@Concurrent
public class ExampleDataDriven {

    @TestData
    public static Collection<Object[]> testData() {
        return Arrays.asList(new Object[][]{
            {"S"}
        });

    }
    private final String type;

    public ExampleDataDriven(String type) {
        this.type = type;
    }

    @Test
    public void example() {
    }
} 
```

Unfortunately in `1.2.2-rc.6` the same test invokes `InvalidManagedWebDriverFieldException`. I don't use WebDriver and it seems strange to make `@Managed`parameter mandatory.

> Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (default) on project autotests-api: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: There was an error in the forked process
> org.apache.maven.surefire.testset.TestSetFailedException: net.thucydides.core.annotations.InvalidManagedWebDriverFieldException: No WebDriver field annotated with @Managed was found in the test case.

**Comment by wakaleo** [comment]
Thanks for the feedback, this is indeed a regression.

**Comment by wakaleo** [comment]
This will be fixed in the next release.
