### ISSUE TITLE
Method toString() in parameterized tests is no longer respected

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#643]
I use `toString()` for populating test names with additional information in a report. It seems that after Serenity `1.2.0` was released this method is no longer respected.

```
@RunWith(SerenityParameterizedRunner.class)
@Concurrent
public class ExampleDataDriven {

    @TestData
    public static Collection<Object[]> testData() {
        return Arrays.asList(new Object[][]{
            {"s"}
        });
    }

    @Override
    public String toString() {
        return String.format(" something to add after test name");
    }

    private final String s;

    public ExampleDataDriven(String s) {
        this.s = s;
    }

    @Test
    public void example() {
        << any step >>
    }
}
```

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/zX48AszO8bmDlXO5G2zYv0SucXLw7z/Example%2B2017-01-04%2B19-00-23.png?Expires=1483632061&Signature=nUNlmWXgKU9VaqOnAd-X9Rn5hbnw4qRHptYe-pfJR~aieBp~B-NXLobWHHCpKn2ZCPK7embYFnzGjWrS1PnCLbwWdDc7wETKF9-Dnu~fUjA5-9b7K8vYKy9f-en5wgte1rK5~flx5mfROxHCnEP27BkQCKBCKyBlDf04C2vUOR1LA9py0d~t0Tp2ooB56vIPIUd~vuBLMt6OrXATmUR6HqB1Y6dkqKdq8sSrAXcxtYy1dpKHkdxrwlwV5ZhOXTlwQy7sX7Mvs0CVOuNxzb~164A-ljlFFGzY4FHmtr0spRkDPIbKw0D9fTSQ2DgRoq5Xl1BLtzpW0yRUrgTMlqztcw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by wakaleo** [comment]
Using toString caused issues in some cases: the recommended way to do this now is to use the `@Qualifier` annotation, e.g.
```
    @Qualifier
    public String qualifier() {return s;}
```

This will append the qualifying text to the end of the name of the test. You can use @Title to fine-tune the name of the test in conjunction with this.
