### ISSUE TITLE
How can i keep browser still opening after testcase fail

### ISSUE THREAD

**Issue by huanleapp** [serenity-bdd/serenity-core#648]
[Serenity Question]
incase, i want still opening browser after testcase fail to modify action. but current, when a testcase finished (fail or success) browser is automatic closed.
How can i keep browser still opening after testcase fail.
Thanks and regards
Huan

**Comment by wakaleo** [comment]
Could you please post questions on StackOverflow with the tag #serenity-bdd? Thanks.
