### ISSUE TITLE
No option to provide test case specific chrome.switches for managed webdriver

### ISSUE THREAD

**Issue by AmanTyagi11** [serenity-bdd/serenity-core#649]
I am using managed chrome driver, but some of my test cases need to use specific chrome.switches. There seems no way to pass chrome.switches for individual instances of managed driver. I do not want to set these switches for all test cases. Is there some workaround to achieve this?

**Comment by wakaleo** [comment]
This is not possible at the moment, but could be an enhancement of the @Managed annotation (if you are using JUnit) or via a tag (in Cucumber or JBehave).

**Comment by AmanTyagi11** [comment]
I am using JUnit, so I will love to see this change in @Managed annotation.
