### ISSUE TITLE
Cannot start stories on serenity_jbehave_version = "1.21.0"

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#650]
![Uploading Capture.PNG…]()
Hello,

I'm trying to update the serenity version to the latest:
-     serenity_version = "1.2.2"
-     serenity_rest_version = "1.2.2-rc.10"
-     serenity_jbehave_version = "1.21.0"
-     serenity_jira_version = "1.1.3-rc.2"

I've faced with a problem on serenity_jbehave_version = "1.21.0". 
For some reasons, stories cannot be started, log:
`Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=false,ignoreFailureInView=true,verboseFailures=false,verboseFiltering=false,storyTimeouts=1020,threads=1,failOnStoryTimeout=false]
12:33:06.791 [main] DEBUG n.s.jbehave.SerenityReporter - before story BeforeStories
12:33:06.826 [main] INFO  net.serenitybdd.core.Serenity - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
-------------------------------------------------------------------------------------

(BeforeStories)12:33:06.873 [main] DEBUG n.s.jbehave.SerenityReporter - afterStory false

Running story stories/test.story
12:33:06.890 [pool-1-thread-1] INFO  n.s.j.e.m.ReportingEmbedderMonitor - 1531200408story running with path stories/test.story
12:33:06.894 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - before story test.story
12:33:06.902 [pool-1-thread-1] DEBUG n.thucydides.core.steps.StepEventBus - Test suite started for story net.thucydides.core.model.Story@63465183
Using timeout for story test.story of 1020 secs.
12:33:08.152 [pool-1-thread-1] DEBUG n.thucydides.core.steps.StepEventBus - Registering custom listener net.serenitybdd.plugins.jira.JiraStepListener@563f40e2
12:33:08.153 [pool-1-thread-1] INFO  net.serenitybdd.core.Serenity - Test Suite Started: Test

(stories/test.story)
12:33:08.220 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - narrative Narrative[inOrderTo=,asA=user,iWantTo=perform an action,soThat=I can achieve a business goal]
Narrative:
As a user
I want to perform an action
So that I can achieve a business goal
12:33:08.221 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - lifecyle Lifecycle[before=Lifecycle.Steps[outcome=<null>,metaFilter=<null>,steps=[]],after={}]
12:33:08.222 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - before scenario started Test
12:33:08.305 [pool-1-thread-1] INFO  net.serenitybdd.core.Serenity - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: Test
-------------------------------------------------------------------(stories/test.story;Test)
12:33:08.419 [main] DEBUG n.s.jbehave.SerenityReporter - before story AfterStories

(AfterStories)
12:33:08.423 [main] DEBUG n.s.jbehave.SerenityReporter - afterStory false
12:33:08.873 [pool-3-thread-1] INFO  n.t.c.r.json.JSONTestOutcomeReporter - Generating JSON report for Test to file`

When I switch back to serenity_jbehave_version = "1.18.0", the stories are starting fine..

**Comment by wakaleo** [comment]
This is most likely a dependency conflict - version 1.21.0 needs JBehave 4.1, so that would be a good place to start checking.

**Comment by ilzul** [comment]
Sorry for the late responce. 

Nope, this doesn't resolve my issue. 

I can see in the logs, that story file was properly found, but then it stops without any execution:
`Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=false,ignoreFailureInView=true,verboseFailures=false,verboseFiltering=false,storyTimeouts=1020,threads=1,failOnStoryTimeout=false]

(BeforeStories)
14:06:17.816 [main] DEBUG n.s.jbehave.SerenityReporter - before story BeforeStories
14:06:17.860 [main] INFO  net.serenitybdd.core.Serenity - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
-------------------------------------------------------------------------------------

14:06:17.924 [main] DEBUG n.s.jbehave.SerenityReporter - afterStory false
Running story stories/Test.story
14:06:17.940 [pool-1-thread-1] INFO  n.s.j.e.m.ReportingEmbedderMonitor - 1528195520story running with path stories/Test.story

(stories/Test.story)
14:06:17.944 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - before story Test.story
14:06:17.951 [pool-1-thread-1] DEBUG n.thucydides.core.steps.StepEventBus - Test suite started for story net.thucydides.core.model.Story@d8553d83
Using timeout for story Test.story of 1020 secs.
14:06:19.414 [pool-1-thread-1] DEBUG n.thucydides.core.steps.StepEventBus - Registering custom listener net.serenitybdd.plugins.jira.JiraStepListener@21e62494
14:06:19.415 [pool-1-thread-1] INFO  net.serenitybdd.core.Serenity - Test Suite Started: Test
Narrative:
As a user
I want to perform an action
So that I can achieve a business goal
14:06:19.482 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - narrative Narrative[inOrderTo=,asA=user,iWantTo=perform an action,soThat=I can achieve a business goal]
14:06:19.483 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - lifecyle Lifecycle[before=Lifecycle.Steps[outcome=<null>,metaFilter=<null>,steps=[]],after={}]
Scenario: For debugg
14:06:19.485 [pool-1-thread-1] DEBUG n.s.jbehave.SerenityReporter - before scenario started For debugg
14:06:19.586 [pool-1-thread-1] INFO  net.serenitybdd.core.Serenity - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: For debugg
-------------------------------------------------------------------(stories/Test.story;For debugg)

(AfterStories)
14:06:19.792 [main] DEBUG n.s.jbehave.SerenityReporter - before story AfterStories

14:06:19.802 [main] DEBUG n.s.jbehave.SerenityReporter - afterStory false
14:06:20.290 [pool-3-thread-1] INFO  n.t.c.r.json.JSONTestOutcomeReporter - Generating JSON report for For debugg to file C:\AT\tests\target\site\serenity\f6bc25d398b8bbd6663d67e4a768b406.json (using temp file C:\AT\tests\target\site\serenity\f6bc25d398b8bbd6663d67e4a768b406.jsonb5ad6b46-18c9-44b1-b0ca-19f41afa5722)
14:06:20.599 [pool-3-thread-2] INFO  n.t.c.r.h.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR Test:For debugg in f6bc25d398b8bbd6663d67e4a768b406.html in directory target\site\serenity  
Generating reports view to 'C:\AT\tests\build\classes\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 0 stories (of which 0 pending) containing 0 scenarios (of which 0 pending)`

Note: with serenity_jbehave_version = "1.18.0", I don't have such issues ...

**Comment by wakaleo** [comment]
Have you checked your dependency tree for version conflicts?

**Comment by ilzul** [comment]
Yes, everything seems to be correct. I have the jbehave.core version - 4.1

**Comment by wakaleo** [comment]
Can you produce a sample project that reproduces the issue?

**Comment by ilzul** [comment]
Unfortunately, I cannot send my project... I have tried to reproduce this issue on jbehave-webtest-todomvc, but everything works fine there.

I have noticed one more issue with my project - for some reasons, story file names are not displayed in the report, when I updated to the latest serenity versions.

![2017-01-17_1234](https://cloud.githubusercontent.com/assets/2085160/22017112/9547b830-dcb1-11e6-881e-ac791a51faab.png)

Probably this is a root cause of my problem with starting the tests.. Do I need to set some new property for displaying this information in the report ?

**Comment by wakaleo** [comment]
No, JBehave stories should work out of the box. I'm afraid with these symptoms it's very hard to diagnose anything specific without a sample project that reproduces the issue.
