### ISSUE TITLE
It's not possible to catch exceptions thrown by Tasks

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#652]
There are often cases where I wish to be able to catch exceptions that might be thrown within automation code and deal with them. However it has recently come to light that exception handling is never invoked in the following code:

```
        Target openTarget = Target.the();
        try {
            actor.attemptsTo(Click.on(openTarget));
        } catch (Throwable e) {
// we never get here
        }
```

However using the 'core' interactions does:

```
        try {
            openTarget.resolveFor(actor).click();;
        } catch (Throwable e) {
// we can get here
        }
```

To me, there should be no difference in exception handling between the two approaches. In fact, this limits the degree of decomposition that I can have in my Task infrastructure (e.g. the moment I delegate anything to a task then deterministic exception handling is threatened).

**Comment by wakaleo** [comment]
This is not possible from within a task at the moment, because Serenity needs to handle all exceptions in order to continue to execute the steps in "dry-run" mode after a task has failed. Without this, the reporting capability wouldn't work. However, you can 

- Use  `StepEventBus.getEventBus().getBaseStepListener().aStepHasFailed()` and `StepEventBus.getEventBus().getBaseStepListener().getTestFailureCause()` to know when and why a test fails.  
- Use Questions to determine UI state, rather than waiting for the exception to be thrown, e.g.
    ```
        dana.attemptsTo(
                Check.whether(BUTTON.resolveFor(dana).isCurrentlyVisible())
                     .andIfSo(Click.on(BUTTON)).otherwise(Click.on(THE_OTHER_BUTTON))
        );
```

**Comment by nbarrett** [comment]
Thanks for your suggestions. Yes, I am increasingly using the pattern 1 you describe, but I also have to take it a step further as the driver can easily become disabled and effectively inoperable unless defensive coding like the following is used:    

```
      if (StepEventBus.getEventBus().aStepInTheCurrentTestHasFailed()) {
                LOGGER.warn("Resetting event bus due to previous failure");
                StepEventBus.getEventBus().clearStepFailures();
            }
```
(note: I'm not using `.getBaseStepListener()` here - is that a problem?). 

The reason I am needing to reset the event bus is that the current application under test is extremely unstable and a more elaborate form of orchestration is  required over and above the normal Task/Question cycle, which also won't work I assume unless .clearStepFailures() is called? 

One particular problem is that elements can momentarily disappear from the DOM (but not for a period of time long enough for a user to see this). This can cause exceptions of type `WebDriverException` to be thrown. The distinction here is that these are not test failures as such, but are more transient errors that occur in simply reading the application state. An example of this is that I wish to parse a set of search results from the application and this may take a couple of seconds to achieve and mid-way through the process, the DOM might have shifted slightly. This is normally quite easily handled by means of exception handling, but I've discovered that I can't call any tasks within this code.

**Comment by wakaleo** [comment]
One option would be to write your own Action classes that encapsulate the exception handling (using `openTarget.resolveFor(actor).click();` under the hood).
