### ISSUE TITLE
Failed tests have a wrong site layout style in Issue block

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#653]
If Issue annotation is used, the report has the wrong layout style in issue id block with closing parenthesis.

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/HivNJOfWnnvDFddCwDTp9QmNq3lLNL/Serenity%2BReports%2B2017-01-11%2B16-17-08.png?Expires=1484227045&Signature=C~JoiZvlLCLaR8a0eZ7GkPNxIBfi63qAH1Nj8PzUukJUWLPPyymTUoem-DAdOLeGFUc4u1FFG1lprCqn4uBubTIGjSbvPMEa7sYbCY4m9O7Obi8rpm34MLIc~3Br-Rnl9VhL0FzdctT9FCjqffrPlLfOOk~baCax9tah878sF1oSi5P9KsXkMxmx41aBS2P2KrsU5JbWC-PjaUhydG930KZJ0WNioTLTcnLi1ZlJE4ZjmUVFN-APQlaWtxvooIO9-kTxtox~9zmvwsW4hlaKDQBTduyTYK9gMLac18jO9Y63sapVnBvNKlvcp0m1oUikfNE6oJlpJ2P--h1ThEbjsA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by wakaleo** [comment]
Probably fixed in the new reports
