### ISSUE TITLE
StepEventBus.getEventBus().clearStepFailures() breaks report layout for inner steps

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#654]
Suppose I want to make several checks in particular state and I want to do all of them despite occurring failures.

To achieve this I use `StepEventBus.getEventBus().clearStepFailures();` Unfortunately if failure occurs in the inner step, all other inner steps jump one level upper.

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/BOXoFuzHDp9WNAA3kmE7x8if4r4MZv/Example%2Btest%2B2017-01-11%2B16-40-07.png?Expires=1484228411&Signature=SH2LryYlVoCTsspWcfk~4-0I5JjYtGffdvl3ouD7A6VTP1UbxURdgpcbCadUDLe7O0RkVIIBFVf~KN7Udi3woc6XdDFbQVGnhUTwq6FrWAPZGJ6iEsDry5E4uuqZ-4Le851NqLC-QB4WK3PE7ielDsuCiG~t7jkCJjuaMA-kdgpX44UcIlPmMYG5WXhvNH9328vN864occZhEyiW2KVrX9SiITA-aayy3HtMyszsHddPIv8iOX8vipL2lBVAAXT5oxxhnroqWdKtfbRHcK9bOxVrMEO2iBPQdGvvMvADotHM1VRO8Mhgd~cQ9fXUQRe~APZKwHIxYc2~ooWF~uAR-A__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/bFPKBS6Zc2FFS2LywSd4gNAXLnPIyz/Example%2Btest%2B2017-01-11%2B16-37-02.png?Expires=1484228245&Signature=DzrW7ERRHHDqx3-YeXOnsOCUcmZKOWVOng5FPjX8fjOc~eTKh23KTuxKnsMsHi70nC-Sech4soOp-OEURgiqJ-oQ2ZSNnVOB7HnSc2G-DM-xXgvh-FaS8uWSEcOeJK8P-Sdh29hd-HY8gtrwpWqRrcem6CjUVT7SNHzQP8XGcLxtOEjk2c08v0prZzJTPxlXkJFEaDMNT4kGksNKaISFHbcqabIhvCqboy6vcPSXfScVQsqSDOLYXHfkVYfb7zWaoZFcwyXynDggve0GA0Upph54CX~KsvvBtRFJl4HImUky-EVl2eUGrD7KPt6u32w1IEE3Q1ftaiHwA1HrMkKSbg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Here is how to reproduce this issue:

```
@RunWith(SerenityRunner.class)
public class ExampleTest {

    @Steps
    private ExampleSteps exampleSteps;

    @Test
    public void exampleTest() {
        exampleSteps.firstLevelStep();
    }
}
```

```
public class ExampleSteps {

    @Step
    public void firstLevelStep() {
        secondLevelSuccessStep();
        secondLevelFailureStep();
        secondLevelSuccessStep();
        secondLevelSuccessStep();
    }

    @Step
    public void secondLevelFailureStep() {
        try {
            Assert.fail();
        } catch (AssertionError e) {
            StepEventBus.getEventBus().stepFailed(new StepFailure(withTitle(null), e));
            StepEventBus.getEventBus().clearStepFailures();
        }
    }

    @Step
    public void secondLevelSuccessStep() {
    }
}
```

**Comment by wakaleo** [comment]
This is as intended. `clearStepFailures()` is an internal method, not really meant for use outside of framework code. It lets you continue executing the tests, but keeps a record of the failed steps. What you are trying to do sounds like soft asserts, which is supported using Screenplay but not yet using in @Step methods.
