### ISSUE TITLE
Grouping feature for testdata examples removed?

### ISSUE THREAD

**Issue by spcial** [serenity-bdd/serenity-core#656]
We did  a version upgrade from 1.1.0 to 1.2.2 and everything runs fine at the moment. There is only one question regarding the generated reports. In version 1.1.0 each test run of an example data set ist collapsed into one line which can be extended by clicking on a plus-symbol, see:

![image](https://cloud.githubusercontent.com/assets/13414244/22061077/b2bcbe98-dd73-11e6-805c-452cba842c85.png)

In the new version this feature is missing. If you have an example table with a lot of examples / datasets the site gets quite messy because it is not clear where it starts and where it ends. Furthermore I don't want to see all steps of all data set examples directly at the beginning (especially of successful test runs). See:

![image](https://cloud.githubusercontent.com/assets/13414244/22061276/827bf978-dd74-11e6-8291-67bb458d5cc1.png)

It there any way to get the desired behaviour that I can collapse/group steps which belong together? Did I miss something?

Thanks in advance!

**Comment by wakaleo** [comment]
Could you provide a sample project to reproduce this? It should normally behave as before.

**Comment by sacredvor** [comment]
Hi John,
I also faced with the same issue. If I have tests with an example table with a lot of examples / data-sets the result will be the list of huge amount of steps but not the list of collapsed items sorted by data-set.

Best Regards,
Oleksandr

**Comment by wakaleo** [comment]
Once again, issues with sample projects go to the top of the queue ;-)

**Comment by sacredvor** [comment]
I found that I used old version of serenity-jbehave (1.13.0) and issue was reproduced. If I use serenity-jbehave(1.18.0), all works correctly.

Thanks

**Comment by wakaleo** [comment]
Thanks for the update!
