### ISSUE TITLE
can't pass automationName capability needed for iOS 10.x automation

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#659]
@wakaleo 

With iOS 10.X one need to pass automationName = "XCUITest"

But this flag is missing in serenity framework, please fix this problem.

Thanks in advance.

Regards,
Vikram

**Comment by wakaleo** [comment]
Could you provide a code sample of how this would be added, or better still, a pull request ;-)

**Comment by vikramvi** [comment]
@wakaleo I've below entries in appium.txt

[caps]
automationName = "XCUITest"
#platformName
platformName = "iOS"
xcodeConfigFile = "/Users/vikram-anna/Documents/Noa/Workspace/Mobile-Automation/iOS-Automation/Crew-App-Automation/myconfig.xcconfig"
app = "/Users/vikram-anna/.../AppUnderTest.ipa"
#deviceName random comment
deviceName = "Vikram's iPhone"
platformVersion = "10.2"
udid = "97d9bb791384407fa67dxxxxxxx"


With these I can launch app in REPL mode with help of arc. I'm struck how to pass this through serenity.properties ?

Let me have a look at framework code and see if I can submit PR

**Comment by vikramvi** [comment]
@wakaleo Please find some update on this issue

had below in my serenity.properties

webdriver.driver= appium
#automationName = "XCUITest"
appium.platformName = iOS
appium.platformVersion = 10.2
appium.deviceName  = iPhone SE
appium.app =  /Users/../serenityAppiumFlipkart/SauceGuineaPig.app
appium.hub = http://localhost:4723/wd/hub

The sample script worked even with and without automationName capability, but I'm not sure how and why ?

can you please clarify. 

I've committed code to existing demo appium and serenity project

https://github.com/vikramvi/AppiumSerenityPOC/commit/c87bedc8a54a55d1878152619090e1d1bddafb8d

**Comment by pisarenco92** [comment]
@vikramvi  Add the: 
`appium.automationName = XCUITest` capability

**Comment by vikramvi** [comment]
@pisarenco92 Thanks but strangely I could able to launch .app on iOS Simulator running with 10.2. 

I'm wondering if this is taken internally by framework itself ?

**Comment by cliviu** [comment]
Hi @vikramvi . For clarification : all properties which are starting with "appium" in serenity.properties  will be forwarded to the appium driver. So, for example setting in serenity.properties   `appium.automationName = XCUITest` will have as end effect setting the property `automationName=XCUITest` in the  Appium driver capabilities.

**Comment by vikramvi** [comment]
@cliviu Thanks for detailed clarification.

I'll keep this issue open and submit PR for documentation for the benefit of others; who refer to Appium related queries in it.

**Comment by vikramvi** [comment]
closing as PR is submitted https://github.com/serenity-bdd/serenity-documentation/pull/102
