### ISSUE TITLE
IOSDrive methods are not exposed

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#660]
@wakaleo please refer to commit

https://github.com/vikramvi/AppiumSerenityPOC/commit/c87bedc8a54a55d1878152619090e1d1bddafb8d

I tried doing getDriver().hideKeyboard() but this doesn't work.

How can I get hold of methods exposed by appium driver ?

**Comment by pisarenco92** [comment]
@vikramvi I did something like:
```
public IOSDriver<IOSElement> iOSDriver() {
		return (IOSDriver<IOSElement>) ((WebDriverFacade) driver).getProxiedDriver();
	}
```
and then use iOSDriver() to get all methods exposed by iOSDriver.

**Comment by vikramvi** [comment]
@pisarenco92 thanks a ton for quick update, will check and update back here.

can you please have a look at one more related bug https://github.com/serenity-bdd/serenity-core/issues/661

Thanks in advance

**Comment by vikramvi** [comment]
@pisarenco92 Thanks it worked perfectly.

@wakaleo I will close after submitting PR for documentation for the benefit of others with this critical info.

**Comment by wakaleo** [comment]
Hi @vikramvi, is this issue ready to close?
