### ISSUE TITLE
Avoid @Step description in the reports

### ISSUE THREAD

**Issue by ManuelAbril** [serenity-bdd/serenity-core#662]
I am wondering if it is possible to not display the `@Step` description in the report. I mean, I am using Jbehave and I think it is enough information if a have per each GWT statement its description and the detail of the logic itself.

http://imgur.com/a/8Pz6Y

**Comment by wakaleo** [comment]
If you don't want a step appearing in the report, don't use the @Step annotation.

**Comment by ManuelAbril** [comment]
Sorry, I was focus on avoiding it with same code when the answer was obviously. Thanks
