### ISSUE TITLE
No sign that story timed out

### ISSUE THREAD

**Issue by volnoboy** [serenity-bdd/serenity-core#663]
Few days ago, I have released that only Chrome shows reports on all scenarios. Firefox and IExplorer not for all. Result in all three browsers were green and completely successful. After investigation(took me more then a day), I have released that some stories timing out and skipped some (usually last) scenarios. If it is possible to make an improvement and show in report a message, that some scenarios were skipped because of story timeout.

**Comment by wakaleo** [comment]
Are you using JBehave?

**Comment by volnoboy** [comment]
Yes:
<serenity.version>1.1.42</serenity.version>
 <serenity.jbehave.version>1.13.0</serenity.jbehave.version>

**Comment by wakaleo** [comment]
These versions are pretty dated, I would recommend using the latest ones. However the timeout is a common JBehave issue, and there is very little that can be done other than increase the `story.timeout.in.secs` to a very large value. This value is the maximum time for ALL of the stories, and defaults to 300 seconds. If it times out, JBehave interrupts the test with no warning at all, so there is no way to intercept the error.

**Comment by volnoboy** [comment]
Thanks. I did increase the value. Pretty sad that it cannot be intercepted.
