### ISSUE TITLE
@Managed(driver = "Appium", uniqueSession = true) not working

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#664]
I need to run multiple test cases on iOS native app and I've below 
    @Managed(driver = "Appium", uniqueSession = true)
    WebDriver webdriver;

even with this, after each test case run app is closed along with simulator with message

`[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 62741)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 62746)
[XCUITest] Simulator log exited with code 'null'
[debug] [XCUITest] Running iOS simulator reset flow
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [XCUITest] Cleaning simulator state.
[debug] [iOSSim] Cleaning app data files for `

@pisarenco92 if you have solved this problem, can you please clarify

**Comment by wakaleo** [comment]
Try using the `serenity.restart.browser.for.each` system property (takes values of scenario, story, feature, never) instead.

**Comment by vikramvi** [comment]
Thanks @wakaleo it worked. 

I'll add this info as well to documentation PR. I think it'll be nice to have separate section in documentation related to appium.

As majority of selenium users are doing native app automation with appium, it will benefit them in migrating quickly with same framework.

I've already shared demo project which can be highlighted in documentation as well.

Let me know your thoughts on this please

**Comment by wakaleo** [comment]
I agree, thanks for your contributions1

**Comment by wakaleo** [comment]
By the way, uniqueSession=true should also be working with version 1.2.2: what version are you using?

**Comment by vikramvi** [comment]
1.2.3-rc.4
