### ISSUE TITLE
How to make failed "should" statements skip subsequent tests

### ISSUE THREAD

**Issue by gamerkhang** [serenity-bdd/serenity-core#666]
Hi,

I am currently using Cucumber combined with Serenity screenplay to test my web UI. There are currently some fields in the UI that I temporarily cannot get to pass acceptance tests. If I try to test these fields alongside other fields, the tests after the failed test will get skipped. Is there a way to make it so that steps after the failed step can still be run?

This is the error I receive:

![screen shot 2017-01-26 at 12 46 09 pm](https://cloud.githubusercontent.com/assets/7456803/22349688/9b524586-e3c5-11e6-9310-b071245fdf7d.png)

**Comment by wakaleo** [comment]
You can do this with soft asserts (http://thucydides.info/docs/articles/soft-asserts.html) if the fields are on the same page.
