### ISSUE TITLE
Time Stamp is not displayed for the log statement in console

### ISSUE THREAD

**Issue by heerqa** [serenity-bdd/serenity-core#667]
HI John,

I have a requirement, where I need to match the test step execution time with server logs.
But during test run, in console i do not see the time stamp.
Can you please help me how to display the timestamp for the logs,
Currently, I am getting these logs:

[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM /Users/heer/assetrabbit-qa/serenity.properties 
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM /Users/heer/assetrabbit-qa/serenity.properties 
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM /Users/heer/assetrabbit-qa/serenity.properties 
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - webdriver.driver=chrome

**Comment by wakaleo** [comment]
Serenity uses slf4j for logging. The [slf4j website](https://www.slf4j.org/manual.html)  explains how to configure logging in a number of different ways.
