### ISSUE TITLE
Links to tests in reports are broken in version 1.2.2

### ISSUE THREAD

**Issue by michaelgx** [serenity-bdd/serenity-core#668]
The links to tests in reports are broken in version 1.2.2. They were working find in version 1.2.1-rc.6

**Comment by wakaleo** [comment]
Could you provide a sample project? I'm not seeing this behaviour in 1.2.2 or 1.2.3-rc.3

**Comment by michaelgx** [comment]
https://github.com/michaelgx/testing

**Comment by michaelgx** [comment]
The command is:
gradle clean intTest aggregate -Dwebdriver.driver=firefox -Dcucumber.options="--tags ~@sikuli" --debug -Dserenity.public.url=http://localhost:8080/job/saucelabs/HTML_Report

**Comment by nikitaratkevich** [comment]
I can confirm. There is a problem in 1.2.2 or 1.2.3-rc.3 version. I switched back to 1.2.1-rc.8. It works well.
Index.html has incorrect links for all tests. 

For e.g. a test link is target/site/serenity/5fa6d1a3438b8cfae9bea7b90801e75b.html in index file
But folder does not containt this file.
Story links are ok.

I have found a working test file in serenity folder. It names fcf80a03685c7dff98481b0e40136e63.html 
But index.html navigates me for related test to a not existed file: 760c17fcc53018c17956f9a5337b9bc4.html

I tested reports on my local machine via cmd: gradle clean test aggregate 
And I tested reports on remote machine via jenkins.
Both environments do not work.

**Comment by wakaleo** [comment]
Are you sure that the serenity-maven-plugin has the same version as core?

**Comment by nikitaratkevich** [comment]
I'm using gradle. I think I don't use any plugin..
dependencies {
    testCompile('org.slf4j:slf4j-simple:1.7.7')
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('junit:junit:4.12')
    compile 'net.serenity-bdd:serenity-core:1.2.1-rc.8'
    compile 'net.serenity-bdd:serenity-junit:1.2.1-rc.8'
    compile 'net.serenity-bdd:serenity-screenplay:1.2.1-rc.8'
    compile 'net.serenity-bdd:browse-the-web:1.1.34'
    compile 'com.googlecode.lambdaj:lambdaj:2.3.3'
    compile 'org.seleniumhq.selenium:selenium-server:2.53.1'
    compile 'org.seleniumhq.selenium:selenium-java:2.53.1'
    compile 'com.thoughtworks.xstream:xstream:1.4.9'
    compile 'com.beust:jcommander:1.58'
    compile 'org.testng:testng:6.9.13.6'

}

**Comment by michaelgx** [comment]
It works now. Thanks for your help

**Comment by wakaleo** [comment]
Could you try with 1.2.3-rc4?

**Comment by nikitaratkevich** [comment]
ERR_FILE_NOT_FOUND - it's after click on any item in Tests section

dependencies {
    testCompile('org.slf4j:slf4j-simple:1.7.7')
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('junit:junit:4.12')
    compile 'net.serenity-bdd:serenity-core:1.2.3-rc.4'
    compile 'net.serenity-bdd:serenity-junit:1.2.3-rc.4'
    compile 'net.serenity-bdd:serenity-screenplay:1.2.3-rc.4'
    compile 'net.serenity-bdd:browse-the-web:1.1.34'
    compile 'com.googlecode.lambdaj:lambdaj:2.3.3'
    compile 'org.seleniumhq.selenium:selenium-server:2.53.1'
    compile 'org.seleniumhq.selenium:selenium-java:2.53.1'
    compile 'com.thoughtworks.xstream:xstream:1.4.9'
    compile 'com.beust:jcommander:1.58'
    compile 'org.testng:testng:6.9.13.6'

}

**Comment by wakaleo** [comment]
Try removing the dependency on browse-the-web

**Comment by michaelgx** [comment]
Still happening with 1.2.3-rc4

**Comment by nikitaratkevich** [comment]
@wakaleo 
Removing of browse-the-web have not helped ;(
dependencies {
    testCompile('org.slf4j:slf4j-simple:1.7.7')
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('junit:junit:4.12')
    compile 'net.serenity-bdd:serenity-core:1.2.3-rc.4'
    compile 'net.serenity-bdd:serenity-junit:1.2.3-rc.4'
    compile 'net.serenity-bdd:serenity-screenplay:1.2.3-rc.4'
    //compile 'net.serenity-bdd:browse-the-web:1.1.34'
    compile 'com.googlecode.lambdaj:lambdaj:2.3.3'
    compile 'org.seleniumhq.selenium:selenium-server:2.53.1'
    compile 'org.seleniumhq.selenium:selenium-java:2.53.1'
    compile 'com.thoughtworks.xstream:xstream:1.4.9'
    compile 'com.beust:jcommander:1.58'
    compile 'org.testng:testng:6.9.13.6'
}

**Comment by wakaleo** [comment]
@michaelgx: I reproduced the issue in your project (thanks for providing it). Running with the follow versions, the links seem to work correctly:

```
serenityVersion=1.2.3-rc.4
serenityJiraVersion=1.1.3-rc.2
serenityCucumberVersion=1.1.23
```

**Comment by michaelgx** [comment]
Thanks. 1.2.3-rc.4 is not on mavencentral.

**Comment by wakaleo** [comment]
1.2.3-rc.4 (and  1.2.3-rc.5) should be on Central within the next 24 hours.

**Comment by michaelgx** [comment]
Thank you!

**Comment by nikitaratkevich** [comment]
Wakaleo. I still have the issue ;(
I tried my old dependecies list with 1.2.3-rc.5 version:
dependencies {
    testCompile('org.slf4j:slf4j-simple:1.7.7')
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('junit:junit:4.12')
    compile 'net.serenity-bdd:serenity-core:1.2.3-rc.5'
    compile 'net.serenity-bdd:serenity-junit:1.2.3-rc.5'
    compile 'net.serenity-bdd:serenity-screenplay:1.2.3-rc.5'
    compile 'net.serenity-bdd:browse-the-web:1.1.34'
    compile 'com.googlecode.lambdaj:lambdaj:2.3.3'
    compile 'org.seleniumhq.selenium:selenium-server:2.53.1'
    compile 'org.seleniumhq.selenium:selenium-java:2.53.1'
    compile 'com.thoughtworks.xstream:xstream:1.4.9'
    compile 'com.beust:jcommander:1.58'
    compile 'org.testng:testng:6.9.13.6'
}

I tried to remove the dependency on browse-the-web and add serenityJiraVersion=1.1.3-rc.2 and serenityCucumberVersion=1.1.23. The same picture:

dependencies {
    testCompile('org.slf4j:slf4j-simple:1.7.7')
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('junit:junit:4.12')
    compile 'net.serenity-bdd:serenity-core:1.2.3-rc.5'
    compile 'net.serenity-bdd:serenity-junit:1.2.3-rc.5'
    compile 'net.serenity-bdd:serenity-screenplay:1.2.3-rc.5'
    compile 'net.serenity-bdd:serenity-jira-plugin:1.1.3-rc.2'
    compile 'net.serenity-bdd:serenity-cucumber:1.1.23'
    //compile 'net.serenity-bdd:browse-the-web:1.1.34'
    compile 'com.googlecode.lambdaj:lambdaj:2.3.3'
    compile 'org.seleniumhq.selenium:selenium-server:2.53.1'
    compile 'org.seleniumhq.selenium:selenium-java:2.53.1'
    compile 'com.thoughtworks.xstream:xstream:1.4.9'
    compile 'com.beust:jcommander:1.58'
    compile 'org.testng:testng:6.9.13.6'
}

What to do?)

**Comment by slasva** [comment]
@nikitaratkevich add and setup serenity-gradle-plugin same version as core.

**Comment by wakaleo** [comment]
This is not a bug but rather a dependency configuration issue. All of the core dependencies, and the maven/gradle plugin versions, need to be the same version. The report naming format changed in version 1.3.x, so if the plugin is an older version, the report names will be different.

If you have broken links with the versions correctly configured, please create a simple sample project to reproduce the issue and we will take a look.

**Comment by nikitaratkevich** [comment]
Thanks guys! It helps!
