### ISSUE TITLE
JUnit test passes (with expect = <error>.class) but report shows errors?

### ISSUE THREAD

**Issue by mtedone** [serenity-bdd/serenity-core#67]
Hi, I've got the following JUnit test that passes:
```
   @Test(expected = IllegalArgumentException.class)
    @Title("Podam should throw an IllegalArgumentException if the @PodamIntValue annotation contains invalid format")
    public void podamShouldThrowExceptionWhenThePodamIntValueAnnotationHasGotAnInvalidFormat() throws Exception {
        PodamFactory podamFactory = podamFactorySteps.givenAStandardPodamFactory();
        podamInvocationSteps.whenIInvokeTheFactoryForClass(IntegerValueWithErrorPojo.class, podamFactory);
    }
```

However the reports show Errors. How does Serenity integrates with JUnit for (expected = ...)?

**Comment by wakaleo** [comment]
Fixed in 1.0.48

**Comment by mtedone** [comment]
Thanks, when is this going to be released?

**Comment by wakaleo** [comment]
It's already on Bintray, should be on Maven central within 24 hours.

On 2 June 2015 at 07:13, Marco Tedone <notifications@github.com> wrote:

> Thanks, when is this going to be released?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/67#issuecomment-107714335>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by mtedone** [comment]
Hi, 1.0.48 doesn't appear on Maven central yet? http://mvnrepository.com/artifact/net.serenity-bdd

BTW, would you be available for some consultancy if it was needed? If so what's your tariff?

**Comment by wakaleo** [comment]
mvnrepository.com is pretty slow on the update in my experience:
http://search.maven.org/#artifactdetails%7Cnet.serenity-bdd%7Cserenity-core%7C1.0.50%7Cjar

I certainly do do consultancy work - ping me via email or via the contact
form on http://wakaleo.com/about-us/contact-us and we can discuss further.


On 4 June 2015 at 15:56, Marco Tedone <notifications@github.com> wrote:

> Hi, 1.0.48 doesn't appear on Maven central yet?
> http://mvnrepository.com/artifact/net.serenity-bdd
>
> BTW, would you be available for some consultancy if it was needed? If so
> what's your tariff?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/67#issuecomment-108738265>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by mtedone** [comment]
Sent a contact request.

**Comment by mtedone** [comment]
Using 1.0.51 but the problem still persists
