### ISSUE TITLE
Report unstable test failures in junit xml output

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#670]
There are  tools out there that are using the flaky tests (ie. tests that sometimes pass and sometimes fail when run multiple times) ex: for example [maven ](https://github.com/apache/maven-surefire/commit/fefaae7f0534a59f52c046a64c96987e8561dd48)and the [jenkins flaky test handler plugin](https://wiki.jenkins-ci.org/display/JENKINS/Flaky+Test+Handler+Plugin). The flaky tests are marked with `<flakyFailure/>` elements instead of `<failure/>` elements in the junit output 

Can we add the `<flakyFailure/>` tag to the unstable tests. Those who are run with `test.retry.count`.

**Comment by wakaleo** [comment]
That's a good idea, I'll take a look.

**Comment by bebef1987** [comment]
@wakaleo I would might help but not sure where to start

**Comment by wakaleo** [comment]
Thanks for the offer - It should only be a couple of lines of code, and quite useful, so not hard to do I think.

**Comment by bebef1987** [comment]
❤️  Thanks for taking care of this @cliviu
