### ISSUE TITLE
Acronym and underscore processing don't work well together

### ISSUE THREAD

**Issue by wskb** [serenity-bdd/serenity-core#671]
The acronym processing doesn't work well with the conversion of underscores into whitespace which is then trimmed. If the acronym is at the end of the string, the report fails to be produced.

[sample project](https://github.com/serenity-bdd/serenity-core/files/739511/acronym_and_underscore.zip)

**Comment by wakaleo** [comment]
So in this case:
```
Feature: __leading underscores are a FAIL when combined with acronyms
  Scenario: __check out how these NAMES are mangled in the report
    Given an admittedly odd naming convention
    When features are named using the convention
    Then serenity reporting should not produce wierd output when not exploding!
```

what output would you expect?

**Comment by wskb** [comment]
The feature name in the report is:
>    Leading Underscores Are A FaFAILhen Combined With Acronyms

I would expect something like
>    Leading Underscores Are A FAIL When Combined With Acronyms

The scenario name in the report is:
>    Check Out How These NaNAMESre Mangled In The Report

I would expect something like
>    Check Out How These NAMES Are Mangled In The Report
