### ISSUE TITLE
Please update io.appium:java-client

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#672]
Kindly update java client to latest version.

Serenity has got 4.0.0 and there are many fixes with latest version.

Thanks,
Vikram

**Comment by vikramvi** [comment]
@wakaleo please refer to issue

https://github.com/appium/java-client/issues/563

can you please update to latest java appium client ?

**Comment by wakaleo** [comment]
The latest version (5.0.0-BETA1) has non-trivial breaking API changes (in particular it adds the findElements(by, using) method to the FindsByFluentSelector. This is a protected method of RemoteWebDriver, and is therefore not accessible to the WebElementFacadeImpl class. It is not impossible to implement, but involves non-trivial code changes. I'm happy to consider a PR ;-).

**Comment by vikramvi** [comment]
Thanks for detailed clarifications. 
To start with I'm planning to submit PR for documentation additions related to appium usage with framework.

**Comment by vikramvi** [comment]
@wakaleo https://github.com/serenity-bdd/serenity-core/blob/bef307ad0c61cabc2f0d4b3157ce0d2985ef200b/gradle.properties

I saw `appiumJavaClientVersion = 5.0.0-BETA9` , have you done changed to accomodate appium java latest versions ?

**Comment by wakaleo** [comment]
Yes.

**Comment by vikramvi** [comment]
@wakaleo  Thanks :)
Can you also please clarify about Appium support with Serenity framework ?

Last time; you informed that as there was no client need; thus you won't be updating Serenity with latest Appium related changes as quickly compared to Selenium.

It will be really helpful if you can provide details of roadmap.

**Comment by wakaleo** [comment]
For now we intend to keep the client versions up to date (the biggest change was moving to Selenium 3).
