### ISSUE TITLE
Serenity-Managed WebDriver Closes Between BDD Scenarios of both Cucumber and JBehave

### ISSUE THREAD

**Issue by djkieras** [serenity-bdd/serenity-core#673]
Using 
- Serenity 1.2.2
- Serenity-Cucumber 1.1.9
- Serenity-JBehave 1.21.0
- Chromedriver 2.27
- Geckodriver 0.14.0

The  Serenity-managed WebDriver is closed after each scenario within a Feature (Cucumber)/Story (JBehave), regardless of the settings of 
- serenity.use.unique.browser
- restart.browser.each.scenario 
- thucycides.use.unique.browser

This behavior is exhibited both when running tests within the IDE (Eclipse) and when running them in Maven.

This occurs when multiple scenarios exist within a Feature/Story.  This makes it difficult to test a workflow as a series of independently tested units where, each scenario builds upon the prior scenario.

For example: in the following Gherkin, the second scenario fails because the browser closes and the user no longer is logged in when the browser restarts.

```
Feature: Example for new issue

Scenario: Successful Login with Valid Credentials
	Given User is on Home Page
	When User Navigate to LogIn Page
	And User enters UserName and Password
	Then Message displayed Login Successfully
	
Scenario: Add Item to Cart
	When User chooses Product Category
	And User adds first item to the cart
	Then Message displayed Added Item
	
Scenario: Go to Checkout
	When User chooses Go To Checkout
	Then Message displayed Ready to Check Out

Scenario: Successful LogOut
	When User LogOut from the Application
	Then Message displayed LogOut Successfully
```

**Comment by wakaleo** [comment]
It is generally considered best practice for BDD scenarios (like unit tests) to be independent, and not rely on each other. However, if you really need to keep  the browser open, you can use the following configuration in both Cucumber and JBehave: 

```
serenity.restart.browser.for.each=feature
```
