### ISSUE TITLE
serenity.logging property is not affecting logging

### ISSUE THREAD

**Issue by sneharora** [serenity-bdd/serenity-core#674]
I am using serenity version 1.2.2. I have set serenity.logging to Normal in serenity.properties  file, still its showing debug logs in console.

**Comment by wakaleo** [comment]
Serenity uses slf4j (https://www.slf4j.org/manual.html), so you will need to configure this in your project. For example, if you want to use logback, you could add the following dependency to your project:
```
  <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>1.0.13</version>
    </dependency>
```
Then add the following `logback.xml` into your `src/main/resources` directory:

```
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <logger name="net.serenitybdd" level="WARN"/>
    <logger name="net.thucydides" level="WARN"/>

    <root level="INFO">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```
