### ISSUE TITLE
Help to get the features pulled from jira

### ISSUE THREAD

**Issue by michaelgx** [serenity-bdd/serenity-core#676]
Could you let me know what I am doing wrong with my project when I am trying to get the list of epics and  features from JIRA but only the following is displaying:
 
I am using a project similar to the one called "testing" in my profile

Here is a screenshot
![screenshot](https://cloud.githubusercontent.com/assets/24270507/22511324/389e903a-e88d-11e6-9e7c-32e5b9c3a28f.png)

I am having difficulty getting the Release management to work aswell.

**Comment by michaelgx** [comment]
Look like it is the msame problem as in: https://github.com/serenity-bdd/serenity-jira/issues/62

**Comment by cliviu** [comment]
hi @michaelgx , Can you please post your mvn/gradle file  ?

**Comment by michaelgx** [comment]
It is here:

https://github.com/michaelgx/testing/blob/master/gradle.properties

**Comment by michaelgx** [comment]
Here is the serenity properties file:

webdriver.base.url=https://business.aib.ie/businesslogin
webdriver.phantomjs.driver=/usr/bin
phantomjs.binary.path=/usr/bin/phantomjs2
jira.url=https://jira.aib.pri
serenity.jira.workflow.active=true
serenity.skip.jira.updates=true
serenity.logging=VERBOSE
serenity.jira.workflow=workflow.groovy
serenity.outputDirectory=build/serenity
jira.project=DBBC
serenity.use.requirements.directories=false

**Comment by cliviu** [comment]
try to add serenity-jira-requirements-provider dependency in gradle build script dependency : under dependencies {
		classpath "org.akhikhl.gretty:gretty:1.4.0"
                classpath("net.serenity-bdd:serenity-gradle-plugin:1.1.42")
} By the way serenity-gradle-plugin version should be actualized to some newer version , for example 1.2.2

**Comment by michaelgx** [comment]
Thanks. Did that and still the same. Here is the log:

[features.txt](https://github.com/serenity-bdd/serenity-core/files/750034/features.txt)

**Comment by cliviu** [comment]
ok, please use everywhere version 1.1.3-rc.2 of serenity-jira-plugin/serenity-jira-requirements-provider

**Comment by michaelgx** [comment]
It mostly works now. Thank you. Just the bug for version 1.2.2 of BDD core is affecting it now.(https://github.com/serenity-bdd/serenity-core/issues/668)

**Comment by cliviu** [comment]
welcome !

**Comment by michaelgx** [comment]
![coverage](https://cloud.githubusercontent.com/assets/24270507/22592589/68df33b8-ea12-11e6-8099-633c3b5139b2.png)
Do you see how there are extra columns in the documentation screenshot (above) and my report(below) does not have them? Is there some way to get these? Thanks
