### ISSUE TITLE
BeanMatcher checkThat method does not fail when it should

### ISSUE THREAD

**Issue by Grunf911** [serenity-bdd/serenity-core#677]
Hereby i am assuming that checkThat from the
net.thucydides.core.matchers.BeanMatchers.checkThat;

is supposed to work exactly like:
org.hamcrest.MatcherAssert.assertThat;

with the difference that checkThat is a soft assert that will fail the current example being run but continue with others where assertThat shall fail the current example and skip others and continue with next test case.

Assuming the above is the case checkThat( method is not failing tests when it should
in example same test:

assertThat(searchRecyclePage.getErrorMessage(), containsString(expectedErrorMessage));
checkThat(searchRecyclePage.getErrorMessage(), containsString(expectedErrorMessage));

where the 
searchRecyclePage.getErrorMessage() = "Please consider to input a valid msisdn of 5-15 digits!";    and
expectedErrorMessage = "blabla"

the assertThat throws:
rg.jbehave.core.embedder.PerformableTree$SomethingHappened@2e760e29: java.lang.AssertionError: 
Expected: a string containing "blabla"
     but: was "Please consider to input a valid msisdn of 5-15 digits!"

...where the checkThat passes the test case

**Comment by Grunf911** [comment]
The reason why i prefer using checkThat rather then assertThat is that i have to verify multiple examples, and i would like to use soft asserts as i want my test to resume with other examples in one of them fail

**Comment by wakaleo** [comment]
Your assumption is incorrect. `checkThat()` is used internally by Serenity, it is not an implementation of the soft asserts feature. Soft Asserts are available using Screenplay, but not yet supported in stand-alone tests.
