### ISSUE TITLE
Report scenario order = scenario execution

### ISSUE THREAD

**Issue by ManuelAbril** [serenity-bdd/serenity-core#678]
I want to have an HTML report where the scenarios are listed in the same order which were executed. Is it possible?

**Comment by ThirumalaiVigneshM** [comment]
Happy to have this feature. But how/where to set this feature? Is there any property that needs to be set in the serenity.properties file ?


Thanks, 
Thiru

**Comment by wakaleo** [comment]
There is now a "Started" column which allows you to sort scenarios by time of execution.

**Comment by ThirumalaiVigneshM** [comment]
Thank You :)
