### ISSUE TITLE
How to extract serenity test result to external tools

### ISSUE THREAD

**Issue by Juny0508** [serenity-bdd/serenity-core#679]
I would like to extract the serenity result to external tool(Excel sheet), and I refered below reference manual which doesn't work. @wakaleo could you help?

20. Importing test results generated by Serenity BDD
During execution of test Serenity BDD generate Test Outcomes and use them to build aggregated report. It is possible for some external tools load test outcomes and analise them.

20.1. Loading Test OutComes from folder
Test outcomes by default are generated in XML and JSON format, both format contains same information - testcase, suites, test results, rest queries and so on. Serenity BDD uses recreation of these test result - TestOutcome and some extra features available in TestOutcomes.

To load test outcome you should know their format and folder:

**....
**_OutcomeFormat format = OutcomeFormat.XML;
TestOutcomes outcomes = TestOutcomeLoader.loadTestOutcomes().inFormat(format)_**
....**
20.2. Analysing Test OutComes
It is easy to analise test outcomes, for example for getting all passed test you should:

....
outcomes.getPassingTests();
....
Also you can get a lot of information from test ourcomes about execute tests, for example:

....
 for (final TestOutcome outcome : outcomes.getOutcomes()) {
     System.out.println(outcome.getCompleteName());
     System.out.println(outcome.getTestCaseName());
     System.out.println(outcome.getResult());
     System.out.println(outcome.getDurationInSeconds());
     System.out.println(outcome.getDataTable()); // if test was with some data table
     System.out.println(outcome.getIssueKeys());
 }
....

**Comment by ak120684** [comment]
@Juny0508 were you able to figure out extracting testcase result thru code?
I am running into same issue - wanting to dump each testcase's result into external test management tool, so need to extract testcase-result after every test (or at the end of the execution)
