### ISSUE TITLE
Is it possible to add to generated HTML report custom images?

### ISSUE THREAD

**Issue by Invictum** [serenity-bdd/serenity-core#68]
I am using Serenity with jBehave + jUnit.
During test run I store screenshots and adding to them custom overlay via third-party libs. Now I am trying to add generated images to report, but actually don't know how to handle it.

I look through method:
`Serenity.takeScreenshot();`
It takes screenshot and adds it to Step context. But there is no way to add some custom image to context.

Is there any way to do it? Please advise.

**Comment by wakaleo** [comment]
Not at this stage.

**Comment by mugar97** [comment]
Please, add this feature, we need it too

**Comment by AndreasScharfCPB** [comment]
@wakaleo could you give us a hint where this is possible now? Or did you just close it?
Thanks!
