### ISSUE TITLE
How to change driver capabilites form test.

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#681]
I would like to update driver capabilities before i launch the browser.

The use case is this
I would like to set the test name to browserstack, so I need to add: browserstack.name to capabilities.

Is there any way to update/add the set capability to the driver?

**Comment by wakaleo** [comment]
Any serenity property that starts with "browserstack" will be passed  through as a property, so setting browserstack.name should do the trick.

**Comment by bebef1987** [comment]
Yep that's true. But I wanted to add the new capability from the test:

```
    @Test
    public void MyTest() {
        <Set capability here>
        home.openHomePage();
        <Other checks>
    }
```

**Comment by wakaleo** [comment]
Is browserstack.name the only field you need to set?

**Comment by bebef1987** [comment]
@wakaleo this was intended to be used for setting the test name. Issue that was fixed some time ago. 
https://github.com/serenity-bdd/serenity-core/pull/682

Not sure if this would be usable for anyone else.
