### ISSUE TITLE
Parameter serenity.restart.browser.frequency doesn't work

### ISSUE THREAD

**Issue by spyofmossad** [serenity-bdd/serenity-core#683]
I'm using `@Managed(uniqueSession = true)` parameter with `serenity.restart.browser.frequency=20` to run tests in the one browser instance and restart browser after each 20 tests and I noticed this feature works well in 1.1.42, and doesn't works in version 1.2.2, browser doesn't restarts.

**Comment by wakaleo** [comment]
For now, you can use `serenity.restart.browser.for.each` (possible values: scenario, story, feature, never) instead.
