### ISSUE TITLE
Serenity Report displays incorrect Scenario Outline

### ISSUE THREAD

**Issue by Kvolovoy** [serenity-bdd/serenity-core#684]
Hello,

When I execute Serenity tests with JBehave it produces incorrect Scenario Outline for tests with empty parameter in Examples. Please see below.
Scenario is the following (password parameter is empty):

Given user is on the login page
When user fills login form with <username> and <password>
And user clicks login button
Then user <username> sees home page
And user sees approval inbox

Examples:
|username|password|
|testuser||

It gives the following in the report:

![bug 001 10-02-2017](https://cloud.githubusercontent.com/assets/25686657/22826769/bae1b4f8-ef9c-11e6-9659-d2a8c2e23f00.png)

Serenity and serenity plugin version is 1.2.2, I also tried 1.2.3-rc.3 and issue still exists.
Serenity jbehave version is 1.21.0

Please have this fixed.
Thank you.

**Comment by wakaleo** [comment]
We will put it in the backlog. If you provide a sample project that reproduces the issue, it is likely to be picked up sooner.
