### ISSUE TITLE
Report index is not generated

### ISSUE THREAD

**Issue by knludi** [serenity-bdd/serenity-core#687]
I'm testing Serenity and I can not solve a problem.

The tests pass but the report's index is not generated. What can this be?

9 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM C:\SGO\regressao\serenity.properties 
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - webdriver.driver=chrome
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - webdriver.chrome.driver=C:\SGO-Sistema_de_Gestao_de_Ocorrencias\SGO-Produto\docs\validacao_verificacao\WebDriver\chromedriver\chromedriver.exe
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.browser,height=1200
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.outputDirectory=C:\Serenity\relatorios
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.dry.run=false
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.project.name=SGO - RegressÃ£o
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.browser,width=1200
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.use.unique.browser=true
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - webdriver.timeouts.implicitlywait=5000
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.take.screenshots=AFTER_EACH_STEP
10 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM C:\SGO\regressao\serenity.properties 
108 [main] INFO net.serenitybdd.core.Serenity - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
-------------------------------------------------------------------------------------

216 [main] INFO net.serenitybdd.core.Serenity - Test Suite Started: Login
272 [main] INFO net.serenitybdd.core.Serenity - 
  _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
 |_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
   | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
   | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
   |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                   

TEST STARTED: efetuarLoginComSucesso
--------------------------------------------------------------------
272 [main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
300 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: Login.efetuarLoginComSucesso - acessarOLinkDoSistema
Starting ChromeDriver 2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf) on port 35123
Only local connections are allowed.
7648 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot: C:\Users\ANALUD~1\AppData\Local\Temp\screenshot1843007617400491009
7649 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: acessarOLinkDoSistema
7651 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: Login.efetuarLoginComSucesso - inserirDadosValidos
7661 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot completed
8374 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot: C:\Users\ANALUD~1\AppData\Local\Temp\screenshot8128784897362933077
8374 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: inserirDadosValidos
8375 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: Login.efetuarLoginComSucesso - acionarOBotaoDeLogin
8382 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot completed
9490 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot: C:\Users\ANALUD~1\AppData\Local\Temp\screenshot8414306845595197139
9490 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: acionarOBotaoDeLogin
9492 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: Login.efetuarLoginComSucesso - verificarSeExibiuAPaginaInicial
9497 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot completed
9923 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot: C:\Users\ANALUD~1\AppData\Local\Temp\screenshot6982462683854354631
9923 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: verificarSeExibiuAPaginaInicial
9929 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot completed
9952 [main] INFO net.serenitybdd.core.Serenity - 
        __    _____ _____ ____ _____   ____   _    ____  ____  _____ ____  
  _     \ \  |_   _| ____/ ___|_   _| |  _ \ / \  / ___|/ ___|| ____|  _ \ 
 (_)_____| |   | | |  _| \___ \ | |   | |_) / _ \ \___ \\___ \|  _| | | | |
  _|_____| |   | | | |___ ___) || |   |  __/ ___ \ ___) |___) | |___| |_| |
 (_)     | |   |_| |_____|____/ |_|   |_| /_/   \_\____/|____/|_____|____/ 
        /_/                                                                

TEST PASSED: Valida se o sistema efetua o login corretamente ao informar dados válidos
----------------------------------------------------------------------------
11137 [main] INFO net.serenitybdd.core.Serenity - Test Suite Started: Login
11137 [main] INFO net.serenitybdd.core.Serenity - 
  _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
 |_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
   | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
   | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
   |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                   

TEST STARTED: efetuarLoginComFalha
--------------------------------------------------------------------
11137 [main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 2
11139 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: Login.efetuarLoginComFalha - acessarOLinkDoSistema
Starting ChromeDriver 2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf) on port 36604
Only local connections are allowed.
16648 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: acessarOLinkDoSistema
16650 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: Login.efetuarLoginComFalha - inserirDadosInvalidos
17280 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot: C:\Users\ANALUD~1\AppData\Local\Temp\screenshot2180628288799548339
17280 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: inserirDadosInvalidos
17281 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: Login.efetuarLoginComFalha - acionarOBotaoDeLogin
17289 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot completed
18037 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot: C:\Users\ANALUD~1\AppData\Local\Temp\screenshot8557979984438021393
18037 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: acionarOBotaoDeLogin
18039 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: Login.efetuarLoginComFalha - verificarSeExibiuMensagemDeExcecao
18046 [Screenshot Processor] INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot completed
18504 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: verificarSeExibiuMensagemDeExcecao
18511 [main] INFO net.serenitybdd.core.Serenity - 
        __    _____ _____ ____ _____   ____   _    ____  ____  _____ ____  
  _     \ \  |_   _| ____/ ___|_   _| |  _ \ / \  / ___|/ ___|| ____|  _ \ 
 (_)_____| |   | | |  _| \___ \ | |   | |_) / _ \ \___ \\___ \|  _| | | | |
  _|_____| |   | | | |___ ___) || |   |  __/ ___ \ ___) |___) | |___| |_| |
 (_)     | |   |_| |_____|____/ |_|   |_| /_/   \_\____/|____/|_____|____/ 
        /_/                                                                

TEST PASSED: Valida se o sistema exibe mensagem de exceção ao informar dados inválidos
----------------------------------------------------------------------------
18513 [main] INFO net.thucydides.core.reports.ReportService - Reporting formats: [JSON, XML, HTML]
18516 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@3b00856b(format = Optional.of(XML))
18516 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@3b00856b
18517 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@fade1fc(format = Optional.of(JSON))
18517 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@fade1fc
18561 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6b7906b3(format = Optional.of(HTML))
18561 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6b7906b3
18563 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@3b00856b
18567 [main] INFO net.thucydides.core.reports.ReportService - Processing test outcome Login:efetuarLoginComSucesso
18567 [main] INFO net.thucydides.core.reports.ReportService - net.thucydides.core.reports.xml.XMLTestOutcomeReporter@3b00856b: Generating report for test outcome: Login:efetuarLoginComSucesso
18641 [main] INFO net.thucydides.core.reports.xml.XMLTestOutcomeReporter - Generating XML report for Valida se o sistema efetua o login corretamente ao informar dados válidos to file C:\Serenity\relatorios\822ae03714fc77b79bcd7461759a9603500d36339e17d204e90ef4dd5e14545f.xml
18685 [main] INFO net.thucydides.core.reports.xml.XMLTestOutcomeReporter - XML report generated (C:\Serenity\relatorios\822ae03714fc77b79bcd7461759a9603500d36339e17d204e90ef4dd5e14545f.xml bytes) 1365
18692 [main] INFO net.thucydides.core.reports.ReportService - Report generated for Login:efetuarLoginComSucesso
18692 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
18692 [pool-1-thread-1] INFO net.thucydides.core.reports.ReportService - Processing test outcome Login:efetuarLoginComFalha
18692 [pool-1-thread-1] INFO net.thucydides.core.reports.ReportService - net.thucydides.core.reports.xml.XMLTestOutcomeReporter@3b00856b: Generating report for test outcome: Login:efetuarLoginComFalha
18693 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORT SERENITY-JUNIT-822ae03714fc77b79bcd7461759a9603500d36339e17d204e90ef4dd5e14545f.xml
18694 [pool-1-thread-1] INFO net.thucydides.core.reports.xml.XMLTestOutcomeReporter - Generating XML report for Valida se o sistema exibe mensagem de exceção ao informar dados inválidos to file C:\Serenity\relatorios\27ec0b260ee65884c5b397d761081aa7378574dd3f54e42533bdc9e4b7e22292.xml
18696 [pool-1-thread-1] INFO net.thucydides.core.reports.xml.XMLTestOutcomeReporter - XML report generated (C:\Serenity\relatorios\27ec0b260ee65884c5b397d761081aa7378574dd3f54e42533bdc9e4b7e22292.xml bytes) 1380
18699 [pool-1-thread-1] INFO net.thucydides.core.reports.ReportService - Report generated for Login:efetuarLoginComFalha
18899 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 336
18899 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@fade1fc
18899 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
18899 [pool-2-thread-1] INFO net.thucydides.core.reports.ReportService - Processing test outcome Login:efetuarLoginComSucesso
18899 [pool-2-thread-2] INFO net.thucydides.core.reports.ReportService - Processing test outcome Login:efetuarLoginComFalha
18899 [pool-2-thread-2] INFO net.thucydides.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@fade1fc: Generating report for test outcome: Login:efetuarLoginComFalha
18899 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORT SERENITY-JUNIT-822ae03714fc77b79bcd7461759a9603500d36339e17d204e90ef4dd5e14545f.xml
18899 [pool-2-thread-1] INFO net.thucydides.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@fade1fc: Generating report for test outcome: Login:efetuarLoginComSucesso
18919 [pool-2-thread-1] INFO net.thucydides.core.reports.ReportService - Report generated for Login:efetuarLoginComSucesso
18919 [pool-2-thread-2] INFO net.thucydides.core.reports.ReportService - Report generated for Login:efetuarLoginComFalha
18957 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 58
18957 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6b7906b3
18957 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
18957 [pool-3-thread-1] INFO net.thucydides.core.reports.ReportService - Processing test outcome Login:efetuarLoginComSucesso
18957 [pool-3-thread-1] INFO net.thucydides.core.reports.ReportService - net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6b7906b3: Generating report for test outcome: Login:efetuarLoginComSucesso
18957 [pool-3-thread-2] INFO net.thucydides.core.reports.ReportService - Processing test outcome Login:efetuarLoginComFalha
18957 [pool-3-thread-2] INFO net.thucydides.core.reports.ReportService - net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6b7906b3: Generating report for test outcome: Login:efetuarLoginComFalha
18957 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORT SERENITY-JUNIT-822ae03714fc77b79bcd7461759a9603500d36339e17d204e90ef4dd5e14545f.xml
18959 [pool-3-thread-1] INFO net.thucydides.core.requirements.RequirementsTagProvider - Reading requirements from net.thucydides.core.requirements.FileSystemRequirementsTagProvider@1eca8054
18959 [pool-3-thread-1] INFO net.thucydides.core.requirements.RequirementsTagProvider - Reading requirements from net.thucydides.core.requirements.PackageAnnotationBasedTagProvider@1b07ff80
18959 [pool-3-thread-1] INFO net.thucydides.core.requirements.RequirementsTagProvider - Requirements found:[]
18974 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Resizing image C:\Serenity\relatorios\ffaad20c6700c47367ce00556e08ef07_NONE.png
18975 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Resizing image C:\Serenity\relatorios\ffaad20c6700c47367ce00556e08ef07_NONE.png
18980 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Scaled image saved to C:\Serenity\relatorios\scaled_ffaad20c6700c47367ce00556e08ef07_NONE.png
18981 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Replace original screenshot with scaled version
18983 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Scaled image saved to C:\Serenity\relatorios\scaled_ffaad20c6700c47367ce00556e08ef07_NONE.png
18984 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Replace original screenshot with scaled version
18984 [pool-3-thread-1] INFO net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - NOTE: I couldn't convert scaled screenshot for ffaad20c6700c47367ce00556e08ef07_NONE.png: C:\Serenity\relatorios\scaled_ffaad20c6700c47367ce00556e08ef07_NONE.png
18984 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Resizing image C:\Serenity\relatorios\8136321628fd95465a17d8af2081cd81_NONE.png
java.nio.file.NoSuchFileException: C:\Serenity\relatorios\scaled_ffaad20c6700c47367ce00556e08ef07_NONE.png
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.resizedImage(ScreenshotFormatter.java:73)
	at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight(ScreenshotFormatter.java:48)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:201)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:188)
	at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
	at ch.lambdaj.Lambda.convert(Lambda.java:986)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.expandScreenshots(HtmlAcceptanceTestReporter.java:185)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:170)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:87)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:210)
	at net.thucydides.core.reports.ReportService.generateQueuedReport(ReportService.java:159)
	at net.thucydides.core.reports.ReportService.access$000(ReportService.java:25)
	at net.thucydides.core.reports.ReportService$2.run(ReportService.java:120)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91)
	at java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
	at java.util.concurrent.FutureTask.set(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
18985 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Resizing image C:\Serenity\relatorios\7f23269511a500089e7f49a9a49dc443_NONE.png
18989 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Scaled image saved to C:\Serenity\relatorios\scaled_8136321628fd95465a17d8af2081cd81_NONE.png
18989 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Replace original screenshot with scaled version
18989 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Scaled image saved to C:\Serenity\relatorios\scaled_7f23269511a500089e7f49a9a49dc443_NONE.png
18989 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Replace original screenshot with scaled version
18991 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Resizing image C:\Serenity\relatorios\8c7661c3e88c1f96d867da5e1bf7f1f8_NONE.png
18991 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Resizing image C:\Serenity\relatorios\d564d0b9f20bd71abee8e54af7178feb_NONE.png
18994 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Scaled image saved to C:\Serenity\relatorios\scaled_8c7661c3e88c1f96d867da5e1bf7f1f8_NONE.png
18994 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Replace original screenshot with scaled version
18996 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Scaled image saved to C:\Serenity\relatorios\scaled_d564d0b9f20bd71abee8e54af7178feb_NONE.png
18996 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Replace original screenshot with scaled version
18998 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Resizing image C:\Serenity\relatorios\1fcf275bdb825958bb9c053cf9be1631_NONE.png
18999 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Resizing image C:\Serenity\relatorios\d564d0b9f20bd71abee8e54af7178feb_NONE.png
19000 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Scaled image saved to C:\Serenity\relatorios\scaled_1fcf275bdb825958bb9c053cf9be1631_NONE.png
19000 [pool-3-thread-1] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Replace original screenshot with scaled version
19020 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Scaled image saved to C:\Serenity\relatorios\scaled_d564d0b9f20bd71abee8e54af7178feb_NONE.png
19020 [pool-3-thread-2] INFO net.thucydides.core.reports.html.screenshots.ScreenshotFormatter - Replace original screenshot with scaled version
19355 [pool-3-thread-2] INFO net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR Login:efetuarLoginComFalha => 27ec0b260ee65884c5b397d761081aa7378574dd3f54e42533bdc9e4b7e22292.html
19369 [pool-3-thread-2] INFO net.thucydides.core.reports.ReportService - Report generated for Login:efetuarLoginComFalha
20928 [pool-3-thread-1] INFO net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR Login:efetuarLoginComSucesso => 822ae03714fc77b79bcd7461759a9603500d36339e17d204e90ef4dd5e14545f.html
20937 [pool-3-thread-1] INFO net.thucydides.core.reports.ReportService - Report generated for Login:efetuarLoginComSucesso
20985 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 2028

![image](https://cloud.githubusercontent.com/assets/22732624/22927856/997d0ac8-f29a-11e6-87ce-8f36a18d2008.png)

**Comment by rrussell39** [comment]
You need to either generate it yourself on the command line:
mvn serenity:aggregate
Or, more likely, you'd like this done automatically in which case you add an instruction in your pom file (this is all assuming you're using maven for your test project) to call the serenity maven plugin
			`<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.plugin.version}</version>
				<executions>
					<execution>
						<id>thucydides-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>`

**Comment by knludi** [comment]
Funcionou!

Obrigada pela ajuda!

**Comment by wakaleo** [comment]
Thanks Russell

**Comment by mandardjoshi** [comment]
It worked for me as well. Thanks Russel.
