### ISSUE TITLE
Generating focused reports do not work with Jbehave?

### ISSUE THREAD

**Issue by spcial** [serenity-bdd/serenity-core#688]
I'm trying to generate focused reports by using the property `serenity.exclude.unrelated.requirements.of.type` in my serenity.properties file, see:
`serenity.exclude.unrelated.requirements.of.type= capabilities, features, stories`

I'm using maven and jbehave and therefore jbehave metafilter instead the serenity tags function to execute my tests, e.g.:
`clean verify serenity:aggregate -Dmetafilter="+test"`

Still I get the following results:

![image](https://cloud.githubusercontent.com/assets/13414244/22970031/de053f72-f370-11e6-95cc-3669b882fa94.png)

Seems that the property has absolutely no effect but I would assume that it should not show capabilities, features and stories in the report anymore.

Used versions:
<serenity.version>1.2.3-rc.4</serenity.version>
<serenity.maven.version>1.2.2</serenity.maven.version>
<serenity.jbehave.version>1.21.0</serenity.jbehave.version>

Anything wrong with that? Do I miss something or is this a bug?

**Comment by wakaleo** [comment]
This feature is designed to work with the tags system property, I don't think it will work with JBehave meta filters.

**Comment by spcial** [comment]
Is there any way that this function will work with jbehave meta filters in the future? This feature, in my opinion, is quite important for bigger test sets and I would realy love to use it.

**Comment by wakaleo** [comment]
Possibly, but if you want it to happen quickly, your best bet is to take a look at the current implementation and propose a pull request.
