### ISSUE TITLE
Report index with errors

### ISSUE THREAD

**Issue by knludi** [serenity-bdd/serenity-core#689]
Is there any place I can set so that index is generated without these errors?

![image](https://cloud.githubusercontent.com/assets/22732624/22974229/752fd8ca-f368-11e6-9e2a-01e55bdc397f.png)

**Comment by wakaleo** [comment]
I'm not sure I understand the question - displaying failed tests is what the reports are supposed to do. This question would be more appropriate on stackoverflow - could you please raise it there?

**Comment by knludi** [comment]
Yes, thank you very much!

I apologize because I did not quite understand the purpose here. I just saw some issues solved and I figured I'd get this kind of help here!
But now I understand that there is another channel so I can get help too!

Forgive me, I'm starting to use Serenity now and I do not speak English, so sometimes I do not communicate properly...

Thank you for your help!
