### ISSUE TITLE
Failed to copy the screenshot to the destination directory

### ISSUE THREAD

**Issue by dip56** [serenity-bdd/serenity-core#69]
This error has appeared in version 1.0.48 and reproduced in the current 1.0.50

```
INFO net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Processing screenshot: /tmp/screenshot1472783073628648310
INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: simpleStep
WARN net.thucydides.core.screenshots.SingleThreadScreenshotProcessor - Failed to copy the screenshot to the destination directory: /tmp/screenshot1472783073628648310 -> target/site/serenity/fb8da3cb95894d7b08ae2402fb4b14a9_NONE.png: Invalid cross-device link
```

**Comment by smlionceau** [comment]
On current version 1.0.51 issue is still reproduced (on the same environment with version 1.0.47 or lower screenshots are working correct)

**Comment by mikezx6r** [comment]
On a Bamboo build server. 

1.0.50 produced broken images.  
1.0.51 has screenshots as expected.

So it helped in some scenarios. Unfortunately not yours.

**Comment by dip56** [comment]
issue fixed only for linux, but for windows still reproduced...

**Comment by dip56** [comment]
John, the issue is not reproduced on version 1.0.52. thx

**Comment by wakaleo** [comment]
Awesome, thanks for the feedback. Could people try it on Linux etc as well
to be sure?

On 11 June 2015 at 10:52, dip <notifications@github.com> wrote:

> John, the issue is not reproduced on version 1.0.52. thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/69#issuecomment-111071179>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by dip56** [comment]
I tested it on windows 7 and linux. everything is good =)
