### ISSUE TITLE
Index.html is displaying as blank pie chart

### ISSUE THREAD

**Issue by siva90144** [serenity-bdd/serenity-core#692]
index.html is displaying as blank it is not generating any pie chart. here i am keeping maven goal as     

[pom.txt](https://github.com/serenity-bdd/serenity-core/files/784166/pom.txt)
![report](https://cloud.githubusercontent.com/assets/19613704/23081131/16abec00-f519-11e6-90d1-d3158944d2c6.png)

verify serenity:aggregate

PFA..

POM.xml and report

**Comment by siva90144** [comment]
[pom.txt](https://github.com/serenity-bdd/serenity-core/files/784168/pom.txt)

Here is the POM.xml

**Comment by wakaleo** [comment]
Serenity will produce a report if no Serenity tests were executed in the build.

**Comment by siva90144** [comment]
I am able to get the individual report . But it is not merging

**Comment by wakaleo** [comment]
Can you provide a sample project reproducing the issue (the pom.xml file alone is not enough)?

**Comment by siva90144** [comment]
Here is the project and pass the parameters as shown below.

service.endpointUrl=http://www.webservicex.net/CurrencyConvertor.asmx
Also sample project.
[currencyConverter.zip](https://github.com/serenity-bdd/serenity-core/files/788488/currencyConverter.zip)

**Comment by wakaleo** [comment]
There are several issues with this project:
  1) The pom.xml file is not configured correctly, so no tests will ever be executed in the Maven build. You need to configure the surefire or failsafe plugins, e.g.

```
	<build>
		<plugins>
			<plugin>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>2.18.1</version>
					<configuration>
							<includes>
								<include>**/*Test.java</include>
								<include>**/*TestSuite.java</include>
							</includes>
					</configuration>
					<executions>
							<execution>
									<goals>
											<goal>integration-test</goal>
											<goal>verify</goal>
									</goals>
							</execution>
					</executions>
			</plugin>
                       ...
```

  2) The JBehave scenario has no name. All JBehave scenarios should have a name (the text that comes after "scenario:"):

```
Story: Currency sample story
Meta:
@author Siva
@environment

Narrative:
In order to verity the Currency service functionality 
As a user
I want to test Currency From and To operation with required parameters

Scenario: Converting currencies
Meta:
```

  3) You should upgrade the Serenity dependencies to the latest versions:
```
		<serenity.version>1.2.3-rc.4</serenity.version>
		<serenity.maven.version>1.2.2</serenity.maven.version>
		<serenity.jbehave.version>1.21.0</serenity.jbehave.version>
```
