### ISSUE TITLE
index.html is not generated iwhen execute test using context menu

### ISSUE THREAD

**Issue by yarafed** [serenity-bdd/serenity-core#693]
Config: JUnit, Java 1.8, Serenity core 1.2.2, Serenity Maven Plugin 1.2.2

index.html is only generated when I execute tests by command 'mvn -verify'.
index.html is not generated, when I try to execute test using context menu command 'Run test_name'.

Thanks in advance for any help!

**Comment by wakaleo** [comment]
This is normal, generating the index happens when you calll the aggregate task, not for each test.

**Comment by yarafed** [comment]
@wakaleo Thank you so much for your help!
