### ISSUE TITLE
Ability to use SerenityRest from a plain JUnit runner

### ISSUE THREAD

**Issue by marcin-caban** [serenity-bdd/serenity-core#695]
To be able to share test code between Serenity tests (e.g. these run with CucumberWithSerenity) and plain JUnit tests (e.g. run with BlockJUnit4ClassRunner) I want to be able to use SerenityRest without a proper setup of Serenity, particularly without BaseStepListener registered.

Some people prefer to skip the Gherkin layer and also all the complexity of Serenity for tests which are not originated from stories and examples delivered by product owners. By using SerenityRest instead of Rest Assured they can deliver steps definitions which can be shared between plain JUnit tests and Serenity tests. 

SerenityRunner cannot be used for another reason.

**Comment by wakaleo** [comment]
Included in 1.2.3-rc.5
