### ISSUE TITLE
SerenityRest.setDefaultRootPath does not work

### ISSUE THREAD

**Issue by hybaken** [serenity-bdd/serenity-core#697]
Hi,

I have set SerenityRest.setDefaultRootPath("someurl"), but in test when I create post request it always tries to connect to localhost.
I debugged test and SerenityRest.getDefaultRootPath() returns correct value ("someurl").

When I use baseUri it does work for a specific test. However I am looking for a generic solution for all tests. Setting baseUri for each request is annoying.

Notice: SerenityRest.setDefaultPort(number) works correct. 

I am using serenity of version 1.2.2, I tried if with latest rc, but it was the same.

**Comment by wakaleo** [comment]
This is the expected behaviour: the `setDefaultRootPath()` method, like the `setDefaultPort()` method, simply calls the corresponding RestAssured code:

```
public static String setDefaultBasePath(final String basePath) {
        return RestAssured.basePath = basePath;
}
```

If you describe your requirement in terms of a configurable base url, it may make a good enhancement request.
