### ISSUE TITLE
Question: How to add @Step methods inside PageObject

### ISSUE THREAD

**Issue by breinjhel** [serenity-bdd/serenity-core#698]
I have a PageObject class with its fields and methods. I want to skip using step libraries and just use simple Page Object and Test class. But I want to take advantage the @Step annotations so that my report would have detailed steps. Is there any way to add @Step annotations inside the Page Object class? Ive tried it but the steps doesnt display in the report

**Comment by wakaleo** [comment]
Not directly. The best way to document the UI interactions in your test is to use the ScreenPlay pattern (see http://serenity-bdd.info/docs/articles/screenplay-tutorial.html). This is more a question for StackOverflow (with the #serenitybdd tag).
