### ISSUE TITLE
Serenity restarts the browser for each scenario/example

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#699]
Hello,

I'm trying to update the serenity to latest version - 1.2.3-rc.5.
I have many story files where I need to have an open browser during the story execution.

In  1.2.3-rc.5 version, the serenity.use.unique.browser property was deprecated.

So tried to set the serenity.restart.browser.for.each to story, but the browser is reopening for each example/scenario. 
I've also tried to set the serenity.restart.browser.for.each to never, and I have the same behavior.

Could someone clarify please, which property should I use to have a unique browser session ?

Note: sample project can be found here - https://github.com/ilzul/serenity-jbehave-sample

**Comment by wakaleo** [comment]
Make sure all your dependencies are up to date. In particular, replace:
    compile("net.serenity-bdd:serenity-screenplay:1.1.31")
    compile("net.serenity-bdd:browse-the-web:1.1.31")
with
    compile("net.serenity-bdd:serenity-screenplay:$serenity_version")
    compile("net.serenity-bdd:serenity-screenplay-webdriver:$serenity_version")

**Comment by ilzul** [comment]
Looks like there is no '1.2.3-rc.5' version for 'browse-the-web'. The latest available version is
    compile("net.serenity-bdd:serenity-screenplay:$serenity_version")
    compile("net.serenity-bdd:browse-the-web:1.1.34")

**Comment by wakaleo** [comment]
Yes, it was renamed some tile ago to serenity-screenplay-webdriver

**Comment by ilzul** [comment]
Ah, thanks ! I didn't know that.
I updated dependencies, but the browser still reopens for each scenario/example:

serenity.restart.browser.for.each = story

ext{
    serenity_version = "1.2.3-rc.5"
    serenity_jbehave_version = "1.21.0"
}
dependencies {
    compile localGroovy()
    compile "net.serenity-bdd:serenity-core:$serenity_version"
    compile "net.serenity-bdd:serenity-junit:$serenity_version"
    compile("net.serenity-bdd:serenity-screenplay:$serenity_version")
    compile("net.serenity-bdd:serenity-screenplay-webdriver:$serenity_version")
    compile("net.serenity-bdd:serenity-jbehave:$serenity_jbehave_version")
...

@wakaleo do you know what could be the reason ? Maybe I need to use some another propertyfor jbehvae ?
Note: I've also updated the project sample, where I could reproduce this issue - https://github.com/ilzul/serenity-jbehave-sample

**Comment by ilzul** [comment]
Cannot reproduce this issue on v1.2.3-rc.7
