### ISSUE TITLE
Serenity is using @FindBy annotation for searching an element for native UI after context change from WebView To Native.

### ISSUE THREAD

**Issue by jain0nikhil** [serenity-bdd/serenity-core#703]
Scenario:
Same app for three platforms and UI some UI is native to platform or some in web view.

Example:
The login page is created for all three platform (Android,iOS,Web) with a native components.
-> Create a page object in your automation as given below:
@iOSFindBy(id = "CONTINUE AS A GUEST >")
@FindBy(id="continue_as_guest_btn")
@AndroidFindBy(id = "guest_login")
public WebElement lnkContinueAsGuest;

//Event on element
public void clickContinueAsGuest(){
lnkContinueAsGuest.click();
}

Expected: While running for iOS, Serenity should use platform-specific locator strategy
Result: Serenity is using only @FIndBy locator strategy for finding an element for Android and iOS.

**Comment by wakaleo** [comment]
That is an interesting requirement, but it isn't supported at this stage.
