### ISSUE TITLE
Step Listener contract differs in jUnit and jBehave style tests for DDT

### ISSUE THREAD

**Issue by Invictum** [serenity-bdd/serenity-core#707]
Serenity version 1.2.3-rc5

I am working on integration Serenity with 3-party services and use `StepListener` interface for that. I investigated it and find out that sequence of method calls different for jUnit and jBehave style tests in case of data driven tests.

jBehave
```
* testSuiteStarted
* testStarted
* useExamplesFrom
* exampleStarted
* exampleFinished
* testFinished
* testSuiteFinished
```

jUnit
```
* testSuiteStarted
* testStarted
* useExamplesFrom
* exampleStarted
* testFinished
* exampleFinished (called twice)
```

So potentially there are two issues:
1) `exampleFinished` method is called twice in jUnit DDT
2) `testSuiteFinished` method isn't called at all in jUnit DDT

And I assume methods calls sequence should be the same for jUnit, jBehave etc, I am right?

**Comment by wakaleo** [comment]
I'll take a look. In theory they should behave similarly.

**Comment by nstbushneva** [comment]
Hello @wakaleo, 
Would it be possible for you to provide any updates for the issue? 
Thank you in advance!
