### ISSUE TITLE
Serenity Report does not show all parameters values in examples of Scenario outline.

### ISSUE THREAD

**Issue by loveshjain** [serenity-bdd/serenity-core#711]
Hi John,

I am currently using 

<serenity.version>1.2.2</serenity.version>
<serenity.cucumber.version>1.1.18</serenity.cucumber.version>

I am facing couple of issues :-

1. I have Scenario Outlines with Examples having many parameters, but Serenity report only show 8 parameters. That is not the case with Serenity version 

<serenity.version>1.1.36</serenity.version>
<serenity.cucumber.version>1.1.8</serenity.cucumber.version>

2. I am passing parameter in Scenario Outline Title as well. At the "Overall Test Results" tab, it show only one scenario with 1st value of the Parameter.

3. All the detailed Test steps are automatically expanded and shown in the report. What I need to do to shown them only when I expand the main steps, which is the case when we run normal scenarios and not scenario outline.

4. If I have null value in any of the parameters then incorrect data with that parameter is shown at Scenario outline space. See "https://github.com/serenity-bdd/serenity-core/issues/684"

**with Serenit version** :- 1.2.2

![image](https://cloud.githubusercontent.com/assets/20214999/23638453/a16f5ad0-0346-11e7-9b30-7f37a1c16151.png)

**with Serenity version** :- 1.1.36

![image](https://cloud.githubusercontent.com/assets/20214999/23638469/bbe8ba64-0346-11e7-9ac4-2400aeef6e20.png)

Thanks,
Lovesh

**Comment by wakaleo** [comment]
This is related to several issues:
1) Will be fixed in the next release
2) From the next release, variable expressions will be conserved in the example titles.
3) Pull Requests are welcome
4) Fixed
