### ISSUE TITLE
Chrome not navigating to URL

### ISSUE THREAD

**Issue by yanurag** [serenity-bdd/serenity-core#714]
Hi Team,

I have using serenity-jbehave to automate my tests integrated with maven.
Issue is when opening chrome browser it is not navigating to URL.
The version of chrome is 57. Its throws up below exception.

FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.chrome.ChromeDriver: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver

Thanks in Advance.

**Comment by wakaleo** [comment]
This is most likely a problem with your chromedriver version.

**Comment by yanurag** [comment]
Thanks for response.

But I am able to open chrome browser with the same chromedriver using simple selenium scripts.

**Comment by wakaleo** [comment]
Is there any more information in the logs?

**Comment by yanurag** [comment]
Actually not much. I am just running jbehave stories using mvn commands. Maven version 3.3.9
The browser details are stored in serenity.properties.

Any information you would like to know to help resolve this issue

**Comment by wakaleo** [comment]
There should be a more complete stack trace that will give you more details. If the driver cannot be instantiated, it is a Selenium issue, or a configuration issue, not a Serenity bug. Make sure your chromedriver executable is the correct version and is accessible on the path (https://sites.google.com/a/chromium.org/chromedriver/downloads).

**Comment by yanurag** [comment]
Thanks for your response.
Will again check the chromedriver and chrome version compatibility.
If issue still persists will give you more stack trace for the issue by next week.

**Comment by yanurag** [comment]
This is related to chrome version and chrome driver compatibility issue.

**Comment by hazmeister** [comment]
@yanurag I'm seeing this on a machine with Chrome 57 and ChromeDriver 2.28, what platform where you using, and what did you find worked?

**Comment by yanurag** [comment]
@hazmeister I had to downgrade my chrome version to 56.
I was unable to make it work with chrome 57 and ChromeDriver 2.28 and serenity.

Hope this helps
