### ISSUE TITLE
Navigation to test html file is broken in 1.2.3-SNAPSHOT

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#716]
I am finding that with the code at the latest release level **1.2.3-SNAPSHOT**, a navigation down to the lowest level test file is broken. It seems that the filename being generated for the `@Test` file is incorrect and looks too long. For example:
* In **1.2.1-SNAPSHOT** the file is generated and navigated as `5a69e8f941872accb50b661b044c79fd.html`
* In **1.2.3-SNAPSHOT** the file that is generated is `169447c9540ef9db942c9710a751859b6ef17f641d0c80df85f7fd26dbbde21a.html` but anchor url is pointing at `6c7dcbed7ef3581b36b3b09071214a4c.html`

**Comment by wakaleo** [comment]
This should be sorted out with the final release versions. It could be due to using an older version of the Maven plugin (e.g. 1.2.2) and the latest snapshot (which uses SHA rather than MD5 for filenames).

**Comment by nbarrett** [comment]
Ah... I used both 1.1.42 and 1.2.2 of the maven plugin and it made no difference. Do you think that if I build the latest version of the maven plugin from source it would work? (I tried on the company network but it failed to connect to some of the repos due to network restrictions but I could try and home).

**Comment by wakaleo** [comment]
Just add the serenity-core snapshot dependency to the Serenity Maven plugin.

**Comment by wakaleo** [comment]
Could you let me know if versions 1.2.3 work for you?

**Comment by nbarrett** [comment]
Hi @wakaleo - all fixed now thanks. I've rebuilt our serenity application and plugin to 1.2.5-SNAPSHOT and navigation works fine.
