### ISSUE TITLE
Report for scenario outline is not appering under serenity index.html file though I can see it is running under console.

### ISSUE THREAD

**Issue by PratapSingh09** [serenity-bdd/serenity-core#717]
Report for scenario outline is not appering under serenity index.html file though I can see it is running under console. 
Getting below error:
[WARNING] this file was not a valid JSON Serenity test report: 5886ad7d04be3ebbe448bd1fabd784696523876d0f4e0bbc4d00efe069492efb.json
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4127 path $.dataTable.currentRow
 used below version: 
serenity.version 1.1.24
serenity.cucumber.version: 1.1.3
serenity.maven.version: 1.1.17

written scenario outline in below formate:
 Given I open the application
 When I enter details as username "<username>", password "<password>" and title  "<title>"
 Then  able to see the homepage

Examples:

| username | password | title |

| Rob      | xyz1      | title1 |

| Bob      | xyz1      | title2 |

Please help me to resove this issue

**Comment by wakaleo** [comment]
Could you update to the latest version of Serenity? These versions are very old.

**Comment by PratapSingh09** [comment]
[WARNING] This file was not a valid JSON Serenity test report: 9fa847618450676d77ab74af707daedc5273bc0a3459a285fda501a007c7cf92.json
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 2868 path $.dataTable.currentRow
 Still getting above message not able to get scenario outline scenario under index.html report  though i can se it is generated seperately.
I have used latest version as well.
 <serenity.version>1.1.29</serenity.version>
        <serenity.cucumber.version>1.1.8</serenity.cucumber.version>
        <serenity.maven.version>1.1.18</serenity.maven.version>
      
        <surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
        <rest-assured.plugin.version>2.4.1</rest-assured.plugin.version>

Please help

**Comment by wakaleo** [comment]
The latest versions are:
  <serenity.version>1.2.5-rc.1</serenity.version>
<serenity.cucumber.version>1.1.28</serenity.cucumber.version>
<serenity.maven.version>1.2.5-rc.1</serenity.maven.version>

(see http://search.maven.org/#search%7Cga%7C1%7Cserenity-core)

**Comment by PratapSingh09** [comment]
Getting below results with blank index.html and below error under consol:
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.readLines(Ljava/io/File;Ljava/nio/charset/Charset;)Ljava/util/List;


Results :

Tests in error:
  RunTest.com.abc.api.xyz.steps.RunTest » NoSuchMethod org.apache.commons.io...



![image](https://cloud.githubusercontent.com/assets/17722170/24868087/4ffa71d8-1e0f-11e7-9af2-d19254845401.png)


Please refer the pom.xml for the same:
 <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.2.5-rc.1</serenity.version>
        <serenity.cucumber.version>1.1.28</serenity.cucumber.version>
        <serenity.maven.version>1.2.5-rc.1</serenity.maven.version>
      
        <surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
        <rest-assured.plugin.version>2.4.1</rest-assured.plugin.version>
        <resource.directory>src/test/resources</resource.directory>
        
        <spring-framework.version>4.1.5.RELEASE</spring-framework.version>
        
        <log4j.version>1.2.17</log4j.version>
        <slf4j.version>1.6.1</slf4j.version>
        <maven.test.failure.ignore>true</maven.test.failure.ignore>
    </properties>
    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>javax.servlet-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey.contribs</groupId>
            <artifactId>jersey-multipart</artifactId>
            <version>1.8</version>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-client</artifactId>
            <version>1.17.1</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20090211</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.4.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>3.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring-framework.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-spring</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-path</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path-assert</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>1.1.2-rc.1</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.5.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.6.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.6.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18</version>
                <configuration>
                    <includes>
                        <include>**/test/**/*.java</include>
                        <include>**/features/**/*.java</include>
                    </includes>
                    <systemProperties>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                    </systemProperties>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
               
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
        <resources>
        
        <resource>

        <directory>src/test/resources/properties/${application.properties}</directory>

        <filtering>true</filtering>
        </resource>
        </resources>


    </build>
</project>

**Comment by wakaleo** [comment]
This is not a Serenity issue but rather a dependency conflict. Check your maven dependencies for conflicts.

**Comment by aivann1** [comment]
Hi,
I had the same problem. I updated the pom dependencies according wakaleo proposal:
"(see http://search.maven.org/#search%7Cga%7C1%7Cserenity-core)"
Now is working perfectly. Thank you!!!

**Comment by wakaleo** [comment]
Thanks for the update!
