### ISSUE TITLE
Serenity rest assured Report: in Index.html content type and content body isnot highlighted 

### ISSUE THREAD

**Issue by siva90144** [serenity-bdd/serenity-core#718]
![serenity](https://cloud.githubusercontent.com/assets/19613704/24010181/19053182-0a45-11e7-84c8-420b31f1d094.png)
Hi,

I am using serenity rest assured framework for rest api testing. When i am generating report and after clicking Query it is opening in pop up . In that Content type content body cookies ...etc are not displaying properly. i.e de-highlighted. Can you help us to fix this issue in report. 
Thanks in Advance

**Comment by wakaleo** [comment]
That's a CSS style defined in the core/css file. If you define a style more to your liking, I'm happy to accept pull requests.

**Comment by siva90144** [comment]
Color: green;

**Comment by wakaleo** [comment]
Fixed in the latest version.

**Comment by siva90144** [comment]
Hey John Can you please give me in which version you have implemented and comparability JBehave , Serenity-core, JBehave maven versions. Thanks :)
