### ISSUE TITLE
Empty report for parallel run using junit

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#72]
Hi John,

When I'm running parallel methods in single class file, the report which generates is completely empty.

can you please look into this issue

Thanks,
Vikram

**Comment by wakaleo** [comment]
Hi Vikram,

Can you produce a sample project that reproduces this issue?

**Comment by vikramvi** [comment]
Hi John,

Can you please use https://github.com/serenity-bdd/serenity-demos/tree/master/junit-webtests

with below changes to its pom.xml



<plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                    <parallel>methods</parallel>     
	            <threadCount>1</threadCount>
                    <reuseForks>true</reuseForks>
                    <argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
                    <systemPropertyVariables>
                        <tags>${tags}</tags>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>


Note:

I've added 2 lines to existing pom.xml entries
<parallel>methods</parallel>     
<threadCount>1</threadCount>

Please review

Thanks & Regards,
Vikram

**Comment by vikramvi** [comment]
output----


Vikrams-MacBook-Pro:junit-webtests vikram-anna$ mvn clean verify
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Sample Serenity JUnit project 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ serenity-junit-webtests ---
[INFO] Deleting /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ serenity-junit-webtests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ serenity-junit-webtests ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ serenity-junit-webtests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ serenity-junit-webtests ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.18:test (default-test) @ serenity-junit-webtests ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ serenity-junit-webtests ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/target/serenity-junit-webtests-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18:integration-test (default) @ serenity-junit-webtests ---
[INFO] Failsafe report directory: /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/target/failsafe-reports
[INFO] parallel='methods', perCoreThreadCount=true, threadCount=1, useUnlimitedThreads=false, threadCountSuites=0, threadCountClasses=0, threadCountMethods=0, parallelOptimized=true

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
12 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/serenity.properties 
13 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.browser,width=1200
13 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - webdriver.driver=phantomjs
13 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.test.root=net.thucydides.showcase.junit.features
13 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.project.name=Demo Project using Serenity and Cucumber
13 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.dry.run=false
13 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.browser,height=1200
13 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.requirement.types=feature, story
13 [main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/serenity.properties 
133 [main] INFO net.serenitybdd.core.Serenity - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
-------------------------------------------------------------------------------------

153 [main] INFO net.serenitybdd.core.Serenity - PREPARING TO EXECUTE 4 TESTS
7742 [main] INFO net.thucydides.core.reports.ReportService - Reporting formats: [JSON, XML, HTML]
7745 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@2a3b5b47(format = Optional.of(XML))
7746 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@2a3b5b47
7751 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@692f203f(format = Optional.of(JSON))
7751 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@692f203f
7809 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@4c39bec8(format = Optional.of(HTML))
7809 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@4c39bec8
7815 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@2a3b5b47
7817 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
7817 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 2
7817 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@692f203f
7817 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
7817 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 0
7817 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@4c39bec8
7817 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
7817 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 0
Running net.thucydides.showcase.junit.features.cart.AddItemsToCartTest
357 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: AddItemsToCartTest.add_item_to_cart - opens_home_page
434 [pool-1-thread-1] INFO net.thucydides.core.webdriver.WebDriverFactory - PhantomJS not on path, trying to get path from PHANTOMJS_BINARY_PATH
434 [pool-1-thread-1] INFO net.thucydides.core.webdriver.WebDriverFactory - PHANTOMJS_BINARY_PATH = null
435 [pool-1-thread-1] INFO net.thucydides.core.webdriver.WebDriverFactory - PHANTOMJS_EXECUTABLE_PATH_PROPERTY = null
Jun 22, 2015 11:21:19 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /usr/bin/phantomjs
Jun 22, 2015 11:21:19 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 45061
Jun 22, 2015 11:21:19 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true, --webdriver-loglevel=OFF, --webdriver=45061, --webdriver-logfile=/Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/phantomjsdriver.log]
Jun 22, 2015 11:21:19 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
3650 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: opens_home_page
3651 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: AddItemsToCartTest.add_item_to_cart - searches_by_keyword
7583 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: searches_by_keyword
7583 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: AddItemsToCartTest.add_item_to_cart - selects_listing
7692 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - STEP FAILED: selects_listing - For input string: "€31.71"
7697 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - SKIPPED STEP: adds_current_listing_to_cart
7730 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - SKIPPED STEP: should_see_item_in_cart
7732 [pool-1-thread-1] INFO net.thucydides.core.steps.StepInterceptor - SKIPPED STEP: should_see_total_including_shipping_for
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.383 sec - in net.thucydides.showcase.junit.features.cart.AddItemsToCartTest
19603 [main] INFO net.thucydides.core.reports.ReportService - Reporting formats: [JSON, XML, HTML]
19604 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@4c309d4d(format = Optional.of(XML))
19604 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@4c309d4d
19604 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@38102d01(format = Optional.of(JSON))
19604 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@38102d01
19604 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@37883b97(format = Optional.of(HTML))
19604 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@37883b97
19605 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@4c309d4d
19605 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
19605 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 0
19605 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@38102d01
19605 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
19605 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 0
19605 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@37883b97
19605 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
19605 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 0
Running net.thucydides.showcase.junit.features.display_product.DisplayProductDetailsTest
7829 [pool-1-thread-2] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: DisplayProductDetailsTest.display_product_details_from_the_search_list - opens_home_page
7887 [pool-1-thread-2] INFO net.thucydides.core.webdriver.WebDriverFactory - PhantomJS not on path, trying to get path from PHANTOMJS_BINARY_PATH
7887 [pool-1-thread-2] INFO net.thucydides.core.webdriver.WebDriverFactory - PHANTOMJS_BINARY_PATH = null
7887 [pool-1-thread-2] INFO net.thucydides.core.webdriver.WebDriverFactory - PHANTOMJS_EXECUTABLE_PATH_PROPERTY = null
Jun 22, 2015 11:21:27 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /usr/bin/phantomjs
Jun 22, 2015 11:21:27 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 14886
Jun 22, 2015 11:21:27 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true, --webdriver-loglevel=OFF, --webdriver=14886, --webdriver-logfile=/Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/phantomjsdriver.log]
Jun 22, 2015 11:21:27 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
10630 [pool-1-thread-2] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: opens_home_page
10630 [pool-1-thread-2] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: DisplayProductDetailsTest.display_product_details_from_the_search_list - searches_by_keyword
14404 [pool-1-thread-2] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: searches_by_keyword
14404 [pool-1-thread-2] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: DisplayProductDetailsTest.display_product_details_from_the_search_list - selects_listing
14541 [pool-1-thread-2] INFO net.thucydides.core.steps.StepInterceptor - STEP FAILED: selects_listing - For input string: "€36.24"
19603 [pool-1-thread-2] INFO net.thucydides.core.steps.StepInterceptor - SKIPPED STEP: should_see_product_details_for
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.779 sec - in net.thucydides.showcase.junit.features.display_product.DisplayProductDetailsTest
27554 [main] INFO net.thucydides.core.reports.ReportService - Reporting formats: [JSON, XML, HTML]
27555 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@58ea606c(format = Optional.of(XML))
27555 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@58ea606c
27555 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@6f45df59(format = Optional.of(JSON))
27555 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@6f45df59
27555 [main] INFO net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@38e79ae3(format = Optional.of(HTML))
27555 [main] INFO net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@38e79ae3
27555 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@58ea606c
27555 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
27555 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 0
27555 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@6f45df59
27555 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
27556 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 1
27556 [main] INFO net.thucydides.core.reports.ReportService - Generating reports using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@38e79ae3
27556 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
27556 [main] INFO net.thucydides.core.reports.ReportService - Reports generated in: 0
Running net.thucydides.showcase.junit.features.search.SearchByKeywordTest
19614 [pool-1-thread-3] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: SearchByKeywordTest.search_for_articles_by_shop_name - opens_home_page
19653 [pool-1-thread-3] INFO net.thucydides.core.webdriver.WebDriverFactory - PhantomJS not on path, trying to get path from PHANTOMJS_BINARY_PATH
19654 [pool-1-thread-3] INFO net.thucydides.core.webdriver.WebDriverFactory - PHANTOMJS_BINARY_PATH = null
19654 [pool-1-thread-3] INFO net.thucydides.core.webdriver.WebDriverFactory - PHANTOMJS_EXECUTABLE_PATH_PROPERTY = null
Jun 22, 2015 11:21:38 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /usr/bin/phantomjs
Jun 22, 2015 11:21:38 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 5202
Jun 22, 2015 11:21:38 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true, --webdriver-loglevel=OFF, --webdriver=5202, --webdriver-logfile=/Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/phantomjsdriver.log]
Jun 22, 2015 11:21:38 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
22580 [pool-1-thread-3] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: opens_home_page
22580 [pool-1-thread-3] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: SearchByKeywordTest.search_for_articles_by_shop_name - searches_for_shop_called
23948 [pool-1-thread-3] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: searches_for_shop_called
23949 [pool-1-thread-3] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: SearchByKeywordTest.search_for_articles_by_shop_name - should_see_shop_search_result_summary_of
23988 [pool-1-thread-3] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: should_see_shop_search_result_summary_of
19616 [pool-1-thread-4] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: SearchByKeywordTest.search_for_articles_by_keyword - opens_home_page
20210 [pool-1-thread-4] INFO net.thucydides.core.webdriver.WebDriverFactory - PhantomJS not on path, trying to get path from PHANTOMJS_BINARY_PATH
20210 [pool-1-thread-4] INFO net.thucydides.core.webdriver.WebDriverFactory - PHANTOMJS_BINARY_PATH = null
20210 [pool-1-thread-4] INFO net.thucydides.core.webdriver.WebDriverFactory - PHANTOMJS_EXECUTABLE_PATH_PROPERTY = null
Jun 22, 2015 11:21:39 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /usr/bin/phantomjs
Jun 22, 2015 11:21:39 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 14307
Jun 22, 2015 11:21:39 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true, --webdriver-loglevel=OFF, --webdriver=14307, --webdriver-logfile=/Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/phantomjsdriver.log]
Jun 22, 2015 11:21:39 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
23317 [pool-1-thread-4] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: opens_home_page
23317 [pool-1-thread-4] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: SearchByKeywordTest.search_for_articles_by_keyword - searches_by_keyword
27513 [pool-1-thread-4] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: searches_by_keyword
27513 [pool-1-thread-4] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: SearchByKeywordTest.search_for_articles_by_keyword - should_see_results_summary_containing
27553 [pool-1-thread-4] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: should_see_results_summary_containing
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.317 sec - in net.thucydides.showcase.junit.features.search.SearchByKeywordTest

Results :




Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- serenity-maven-plugin:1.0.49:aggregate (serenity-reports) @ serenity-junit-webtests ---
[INFO] LOADING LOCAL PROPERTIES FROM /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/serenity.properties 
[INFO] serenity.browser,width=1200
[INFO] webdriver.driver=phantomjs
[INFO] serenity.test.root=net.thucydides.showcase.junit.features
[INFO] serenity.project.name=Demo Project using Serenity and Cucumber
[INFO] serenity.dry.run=false
[INFO] serenity.browser,height=1200
[INFO] serenity.requirement.types=feature, story
[INFO] LOADING LOCAL PROPERTIES FROM /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/serenity.properties 
Merging requirements = [Requirement{name='Display product', type='feature' parent = 'null', cardNumber='null'}, Requirement{name='Search', type='feature' parent = 'null', cardNumber='null'}]
Merging requirements = []
Merged requirements set = [Requirement{name='Display product', type='feature' parent = 'null', cardNumber='null'}, Requirement{name='Search', type='feature' parent = 'null', cardNumber='null'}]
[INFO] Reading requirements from net.thucydides.core.requirements.FileSystemRequirementsTagProvider@7336fd8f
[INFO] Requirement ancestors for:Requirement{name='Display product', type='feature' parent = 'null', cardNumber='null'} = [Requirement{name='Display product', type='feature' parent = 'null', cardNumber='null'}]
[INFO] Requirement ancestors for:Requirement{name='Search', type='feature' parent = 'null', cardNumber='null'} = [Requirement{name='Search', type='feature' parent = 'null', cardNumber='null'}]
[INFO] Requirements found:[Requirement{name='Display product', type='feature' parent = 'null', cardNumber='null'}, Requirement{name='Search', type='feature' parent = 'null', cardNumber='null'}]
[INFO] REPORTS GENERATED IN /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/target/site/serenity
[INFO] REPORT HOME PAGE: /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/target/site/serenity/index.html
[INFO] Generating release reports for: []
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18:verify (default) @ serenity-junit-webtests ---
[INFO] Failsafe report directory: /Users/vikram-anna/Documents/workspace/Web/serenity-demos/junit-webtests/target/failsafe-reports
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.697 s
[INFO] Finished at: 2015-06-22T11:21:49+02:00
[INFO] Final Memory: 36M/482M
[INFO] ------------------------------------------------------------------------

**Comment by vikramvi** [comment]
Hi John,

Today I tried again parallel run with serenity-core 1.1.3 with below configuration in pom.xml


<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18</version>
                <configuration>
                    <parallel>classes</parallel>
                    <threadCount>5</threadCount>
                </configuration>
            </plugin>

It only creates individual reports under target > site > surefire-reports but under target > site > serenity there is no index.html file which gets generated.

can you please clarify ?

Thanks & Regards,
Vikram

**Comment by vikramvi** [comment]
One need to run mvn serenity:aggregate to generate serenity report

**Comment by rajonwebs** [comment]
Hi Vikram, May I have ur email id? I using serenity 1.1.17 but still I am getting the same error as urs.

**Comment by YamStranger** [comment]
Hello @rajonwebs. 
If you feel that this issue is reproduced, we can reopen it. 
Please try to run 
```
mvn clean verify
```
using last version of https://github.com/serenity-bdd/serenity-demos/tree/master/junit-webtests. 

result will be report in target/site/serenity directory: 
![image](https://cloud.githubusercontent.com/assets/1667699/12670796/21ed2986-c620-11e5-9527-bf28be220ed3.png)

**Comment by manisha-A** [comment]
Hi,

I tried using maven-surfire-plugin to run tests in parallel. Later, I ran
`mvn serenity:aggregate`
which generated report in `target/site/index.html`

But, the total execution time (of running tests) from command line  and the execution time from index.html is hugely different. 

Is there a way to fix this?

**Comment by wakaleo** [comment]
Hi,

The execution time in the index.html file is currently the total execution
time for all of the tests,rather than the clock-time that the test suite
took to run.

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better

http://johnfergusonsmart.com  | reachme@johnfergusonsmart.com
<john.smart@wakaleo.com>___________________________________________________


On 24 May 2016 at 2:25:59 PM, manisha-A (notifications@github.com) wrote:

Hi,

I tried using maven-surfire-plugin to run tests in parallel. Later, I ran
mvn serenity:aggregate
which generated report in target/site/index.html

But, the total execution time (of running tests) from command line and the
execution time from index.html is hugely different.

Is there a way to fix this?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/serenity-bdd/serenity-core/issues/72#issuecomment-221267452>

**Comment by manisha-A** [comment]
Hi John,

What I mean is, console shows
BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21:35 min

where the index.html shows total time as 	`51 minutes 20 seconds`

**Comment by wakaleo** [comment]
Yes, this is correct. Maven shows the clock time. Serenity cannot know this value, as Serenity only sees the lengths of individual tests (or test suites), not the total clock time taken for the suite.

**Comment by manisha-A** [comment]
ok. So, Is it possible that build took lesser time than the actual test execution time?

As, build finished in 21 minutes but tests took 51 mins.
If, this is correct, then parallel execution took more time than single scenario execution. If I don't use parallel execution, total time in index.html is 31 minutes.

This is confusing me.

**Comment by wakaleo** [comment]
Yes, running tests in parallel adds more load on the selenium server, which
slows things down a bit.

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better

http://johnfergusonsmart.com  | reachme@johnfergusonsmart.com
<john.smart@wakaleo.com>___________________________________________________


On 24 May 2016 at 2:54:05 PM, manisha-A (notifications@github.com) wrote:

ok. So, Is it possible that build took lesser time than the actual test
execution time?

As, build finished in 21 minutes but tests took 51 mins.
If, this is correct, then parallel execution took more time than single
scenario execution. If I don't use parallel execution, total time in
index.html is 31 minutes.

This is confusing me.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/serenity-bdd/serenity-core/issues/72#issuecomment-221277079>

**Comment by manisha-A** [comment]
Thanks a lot. 

What is the best strategy according to you for parallel execution? Should I look into Grid or using the failsafe-plugin with threads is enough?

Any information will be useful.

Thanks!
