### ISSUE TITLE
Error in compilation serenity with maven in jenkins

### ISSUE THREAD

**Issue by jomejia23** [serenity-bdd/serenity-core#720]
Hi,

I have problem, because I'm trying run the tests cases with serenity and mvn in jenkins and the compilation show this error:

[INFO] Building BDDCoreSura 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ BDDCore ---
[INFO] Deleting D:\jenkins-slave-Serenity\workspace\Core_Seguros\PolicyCenter\1_Desarrollo\PolicyCenter-PruebasAceptacionDLLO-Lote4\target
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ BDDCore ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\jenkins-slave-Serenity\workspace\Core_Seguros\PolicyCenter\1_Desarrollo\PolicyCenter-PruebasAceptacionDLLO-Lote4\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ BDDCore ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 509 source files to D:\jenkins-slave-Serenity\workspace\Core_Seguros\PolicyCenter\1_Desarrollo\PolicyCenter-PruebasAceptacionDLLO-Lote4\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error reading C:\Users\ArquCore\.m2\repository\net\serenity-bdd\serenity-core\1.1.42\serenity-core-1.1.42.jar; error in opening zip file
[ERROR] error reading C:\Users\ArquCore\.m2\repository\net\serenity-bdd\serenity-report-resources\1.1.42\serenity-report-resources-1.1.42.jar; error in opening zip file
[ERROR] error reading C:\Users\ArquCore\.m2\repository\net\serenity-bdd\serenity-core\1.1.42\serenity-core-1.1.42.jar; error in opening zip file
[ERROR] error reading C:\Users\ArquCore\.m2\repository\net\serenity-bdd\serenity-report-resources\1.1.42\serenity-report-resources-1.1.42.jar; error in opening zip file

this is the POM:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.sura</groupId>
    <artifactId>BDDCore</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>BDDCoreSura</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.42</serenity.version>
        <serenity.jbehave.version>1.13.0</serenity.jbehave.version>
        <junit.version>4.12</junit.version>
        <slf4j.simple.version>1.7.7</slf4j.simple.version>
        <assertj.core.version>3.4.0</assertj.core.version>
        <lambdaj.version>2.3.3</lambdaj.version>
        <jbehave.core.version>4.0.5</jbehave.core.version>
        <serenity.maven.plugin.version>1.1.42</serenity.maven.plugin.version>
        <maven.surefire.plugin>2.19.1</maven.surefire.plugin>
        <maven.failsafe.plugin>2.19.1</maven.failsafe.plugin>
        <maven.compiler.plugin>3.2</maven.compiler.plugin>
        <maven.compiler.plugin.source>1.7</maven.compiler.plugin.source>
        <maven.compiler.plugin.target>1.7</maven.compiler.plugin.target>
        
        
        <webdriver.driver>chrome</webdriver.driver>
        <webdriver.chrome.driver>chromedriver.exe</webdriver.chrome.driver>
    </properties>

    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray-plugins</name>
            <url>http://jcenter.bintray.com</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jbehave</artifactId>
            <version>${serenity.jbehave.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.simple.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>${lambdaj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jbehave</groupId>
            <artifactId>jbehave-core</artifactId>
            <version>${jbehave.core.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin}</version>
            </plugin>

            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin}</version>
                <configuration>
                    <includes>
                        <include>**/policycenter/*.java</include>
                    </includes>
                    <excludes>
                        <exclude>**/policycenter/MainStories.java</exclude>
                    </excludes>
                    <reuseForks>false</reuseForks>
                    <forkCount>1C</forkCount>
                    <forkedProcessTimeoutInSeconds>1500</forkedProcessTimeoutInSeconds>
                    <argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                        <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin}</version>
                <configuration>
                    <source>${maven.compiler.plugin.source}</source>
                    <target>${maven.compiler.plugin.target}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>

I' try changue the version in maven and serenity, but that not run good

please help me:

thanks

**Comment by wakaleo** [comment]
You have a corrupted Maven repository (this is not related to Serenity):

C:\Users\ArquCore.m2\repository\net\serenity-bdd\serenity-core\1.1.42\serenity-core-1.1.42.jar; **error in opening zip file**

Try deleting the Maven repository (C:\Users\ArquCore.m2\repository) and rerunning

**Comment by jomejia23** [comment]
hi, @wakaleo 

Thanks, I'm going to try it.
