### ISSUE TITLE
Serenity "wait" methods vs WebDriver 3.2.0+

### ISSUE THREAD

**Issue by spinning10** [serenity-bdd/serenity-core#721]
Testing with WebDriver 3.3.1 (latest at the moment of writing the issue).
Methods that use deprecated FluentWait from WebDriver do not work.
There is workaround in fact, to add to POM.xml that section:
```
<dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-support</artifactId>
        <version>3.0.1</version>
</dependency>
```

But in general the issue can be looked through.
Methods, that without POM altering do not work, are being used in a manner like this:
element(someWebElement).waitUntilPresent();

**Comment by wakaleo** [comment]
Thanks for the information. For now, Selenium 3.x is not yet supported in Serenity (it will be when the gecko driver for Firefox is complete).

**Comment by spinning10** [comment]
Ok, understand. But FYI it can be worked together. I use latest Serenity and latest WebDriver.
There were some issues but it's longer subject and some of it may have been the result of my incompetence :)
