### ISSUE TITLE
Index.html is displaying as blank pie chart

### ISSUE THREAD

**Issue by AliceIgorevna** [serenity-bdd/serenity-core#722]
Well, I have Jbehave tests and want to generate Serenity report, but, I get an empty index.html report. It seems that Serenity can't see my JBehave tests. What am I doing wrong?
![image](https://cloud.githubusercontent.com/assets/15718892/24106133/a85ba9d6-0d8f-11e7-9ded-d3554c9b7edb.png)

Here is my IDE log during test run:
![ide_log](https://cloud.githubusercontent.com/assets/15718892/24106156/beb14c90-0d8f-11e7-8e3c-8f469b717395.png)

I run my test via maven, I have failsafe maven plugin, my tests run through 

> mvn clean verify

 command.
I have tried both failsafe and surfire plugins for my tests, but, for both I have the same result.
pom.xml:
`... <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <surefireVersion>2.19.1</surefireVersion>
        <compilerPluginVersion>3.6.1</compilerPluginVersion>
        <serenityMavenPluginVersion>1.2.2</serenityMavenPluginVersion>
        <failsafePluginVersion>2.19.1</failsafePluginVersion>
        <jbehaveMavenPluginVersion>4.1</jbehaveMavenPluginVersion>

        <junitVersion>4.12</junitVersion>
        <seleniumVersion>2.53.0</seleniumVersion>
        <jbehaveCoreVersion>4.1</jbehaveCoreVersion>
        <jsonSimpleVersion>1.1.1</jsonSimpleVersion>
        <serenityJbehaveVersion>1.21.0</serenityJbehaveVersion>
        <serenityJUnitVersion>1.2.2</serenityJUnitVersion>
        <slf4jVersion>1.7.24</slf4jVersion>
        <log4jVersion>1.2.17</log4jVersion>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junitVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${seleniumVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.jbehave</groupId>
            <artifactId>jbehave-core</artifactId>
            <version>${jbehaveCoreVersion}</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>${jsonSimpleVersion}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jbehave</artifactId>
            <version>${serenityJbehaveVersion}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenityJUnitVersion}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenityJUnitVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.4.1</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compilerPluginVersion}</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefireVersion}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${surefireVersion}</version>
            </plugin>

            
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenityMavenPluginVersion}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-log4j12</artifactId>
                        <version>${slf4jVersion}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                        <version>${slf4jVersion}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>acceptance</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${failsafePluginVersion}</version>
                        <configuration>
                            <includes>
                                <include>**/*TestSuite.java</include>
                            </includes>
                            <systemPropertyVariables>
                                <config>single.conf.json</config>
                            </systemPropertyVariables>
                        </configuration>
                        <executions>
                            <execution>
                                <id>failsafe-integration-tests</id>
                                <phase>integration-test</phase>
                                <goals>
                                    <goal>integration-test</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>failsafe-verify</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>`

**Comment by wakaleo** [comment]
Hard to say from the logs. Try using the latest version (1.2.3-rc.8).

**Comment by AliceIgorevna** [comment]
@wakaleo well, I can give you any information you want.

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces the issue?

**Comment by AliceIgorevna** [comment]
@wakaleo yes, of course.

**Comment by AliceIgorevna** [comment]
@wakaleo https://github.com/AliceIgorevna/bdd-jbehave-demo

**Comment by wakaleo** [comment]
The sample project seems to have heavily modified the usual Serenity/JBehave integration, and potentially overridden key Serenity methods which may have broken the reporting. I would suggest starting from a fresh Serenity/JBehave project, rather than trying to adapt your existing project to work with Serenity.

**Comment by AliceIgorevna** [comment]
@wakaleo okay, thank you 👍

**Comment by wakaleo** [comment]
Closing this for now, as it is not related to a specific Serenity issue - it might be better suited for StackOverflow (hashtag #serenitybdd) or the Serenity Google group to ask questions of a broader audience if you have other questions.
