### ISSUE TITLE
Running tests in parallel using selenium grid

### ISSUE THREAD

**Issue by yanurag** [serenity-bdd/serenity-core#727]
Hi,

I am using selenium grid + serenity + jbehave story for automation and executing stories parallel for execution.
I have created a hub and registered a  2 nodes and 3 browsers in each node. All in local machine.
I have added below lines in pom.xml but still it is launching only single browser and executing tests sequentially.

< artifactId >maven-failsafe-plugin< /artifactId >
< version >2.18.1< /version >
				< configuration >
					< includes >
						< include >**/*Test.java < /include >
					< /includes >
					< forkCount >2< /forkCount >
					< threadCount> 2< /threadCount >
				</configuration>

Running tests through maven using below command
clean install -Dwebdriver.remote.url=http://<ipaddress>:4444/wd/hub -Dwebdriver.driver=chrome

Please advise if I am missing anything

**Comment by wakaleo** [comment]
This is unlikely to be a Serenity issue, as Serenity does not manage test execution. Are you running your Serenity tests with Surefire or Failsafe?

**Comment by yanurag** [comment]
using maven-failsafe-plugin plugin.
Also is there any other configuration I need to do like creating a java class for each story and extending it by serenityStories? I had searched this in some websites

**Comment by wakaleo** [comment]
Yes, if you are using failsafe you must configure failsafe. The example above configures surefire.

**Comment by yanurag** [comment]
sorry I did not get your answer.
Do I need to create empty classes manually for each story and extend it by serenityStories?

**Comment by wakaleo** [comment]
In your Pom file, you need to configure the failsafe plugin to run in parallel, not the surefire one.

**Comment by yanurag** [comment]
sorry I pasted wrong pom.xml code. I am using fail-safe plugin.
Updated the pom.xml code in original question

< artifactId >maven-failsafe-plugin< /artifactId >
< version >2.18.1< /version >
				< configuration >
					< includes >
						< include >**/*Test.java < /include >
					< /includes >
					< forkCount >2< /forkCount >
					< threadCount> 2< /threadCount >
				</configuration>

**Comment by wakaleo** [comment]
That configuration is correct. The issue most likely lies with the Selenium Hub configuration.

**Comment by yanurag** [comment]
thanks.
So I do not need to create empty classes manually for each story and extend it by serenityStories. Right?

**Comment by wakaleo** [comment]
Ah yes, sorry I missed that detail. Yes this will run the classes in parallel, but if you only have one class, you won't get any parallelisation. One class per story is a good way to do this

**Comment by yanurag** [comment]
ok. I have single class which extends SerenityStories which overrides some methods like storyPaths() and so on customized w.r.t to project.
But have multiple Step classes for each story.
Do I need to extend those classes with SerenityStories ?

Is there any other way in which I can achieve parallelisation.

**Comment by wakaleo** [comment]
Just write SerenityStory classes with the same name as your story files.

In the next release you will be able to use the `jbehave.threads` properties, though I'm not sure how reliable this JBehave feature is.

**Comment by wakaleo** [comment]
Closing this issue as it does not relate to a Serenity defect. If you have further questions please place them on StackOverflow with the #serenitybdd tag.
