### ISSUE TITLE
org.openqa.selenium.ElementNotVisibleException: Timed out after 30 seconds waiting for net.serenitybdd.core.pages.WebElementFacadeImpl$1@7966baa7

### ISSUE THREAD

**Issue by shubhamyannawar** [serenity-bdd/serenity-core#728]
org.openqa.selenium.ElementNotVisibleException: Timed out after 30 seconds waiting for net.serenitybdd.core.pages.WebElementFacadeImpl$1@7966baa7

Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'

os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'

**Comment by wakaleo** [comment]
This just means that the element you are looking for is not visible or accessible to Serenity. Without further evidence there is no sign of a Serenity bug here.

**Comment by shubhamyannawar** [comment]
Ok.
Thank you

**Comment by wakaleo** [comment]
Closing this for now. Please reopen if you think this is due to a serenity defect and not due to a regular Selenium timeout.
