### ISSUE TITLE
1.0.52 missing from mvn repo

### ISSUE THREAD

**Issue by nikolaykolev** [serenity-bdd/serenity-core#73]
I can't find 1.0.52 release in any maven repo. Can you upload it somewhere please?

**Comment by wakaleo** [comment]
It probably hasn't synced with Maven Central yet, should be good within 24
hours.

On 11 June 2015 at 11:27, nikolaykolev <notifications@github.com> wrote:

> I can't find 1.0.52 release in any maven repo. Can you upload it somewhere
> please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/73>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by nikolaykolev** [comment]
Ok thank you.

**Comment by derTobsch** [comment]
also 1.0.58 is missing or? I do not get anything greater than 1.0.47 from mvn central.

http://search.maven.org/#search|gav|1|g%3A%22net.serenity-bdd%22%20AND%20a%3A%22core%22

MvnRepository does list it...strange? :)
http://mvnrepository.com/artifact/net.serenity-bdd/serenity-core

**Comment by wakaleo** [comment]
Try
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22net.serenity-bdd%22%20AND%20a%3A%22serenity-core%22



On 24 June 2015 at 10:28, Tobias Schneider <notifications@github.com> wrote:

> also 1.0.58 is missing or? I do not get anything greater than 1.0.47 from
> mvn central.
>
>
> http://search.maven.org/#search|gav|1|g%3A%22net.serenity-bdd%22%20AND%20a%3A%22core%22
> <http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.serenity-bdd%22%20AND%20a%3A%22core%22>
>
> MvnRepository does list it...strange? :)
> http://mvnrepository.com/artifact/net.serenity-bdd/serenity-core
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/73#issuecomment-114803533>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by derTobsch** [comment]
Argl. I told everyone today at work how good the new documentation is...please update them :)

http://serenity-bdd.info/docs/serenity/#_building_serenity_projects_in_maven

i know there is version 1.0.47 but please update them with 1.0.58 and serenity-core. This took me over an hour now :/

Thanks for your fast reply!

**Comment by wakaleo** [comment]
Thanks for the pointer, I'll get that sorted shortly.

On 24 June 2015 at 10:37, Tobias Schneider <notifications@github.com> wrote:

> Argl. I told everyone today at work how good the new documentation
> is...please update them :)
>
>
> http://serenity-bdd.info/docs/serenity/#_building_serenity_projects_in_maven
>
> i know there is version 1.0.47 but please update them with 1.0.58 and
> serenity-core. This took me over an hour now :/
>
> Thanks for your fast reply!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/73#issuecomment-114806937>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by rrussell39** [comment]
It appears the artifactId changed from 'core' to 'serenity-core'.  Can someone point me to release notes that document this change?
