### ISSUE TITLE
Scenario Outline if edited or modifed, the index.html is still picking the old and new outlines and showing them as 2 test cases

### ISSUE THREAD

**Issue by rituoarora** [serenity-bdd/serenity-core#734]

**Comment by rituoarora** [comment]
For example:
The original scenario outline was: **Login with expired password- must change password error**
The aggregation report was run and resulted in correct test cases count.

But, when, the same scenario was changed to: **Login with expired password**
Then aggregation report showed OLD and NEW both scenarios as 2 different test cases; and therefore, causing conflict in actual test cases.

Is there anything can be done?

**Comment by wakaleo** [comment]
The test report is derived from the name of the scenario. If this changes, you will get a new test report that will appear in the aggregate report. To avoid this, simply clean the target directory (e.g. `mvn clean verify`.
