### ISSUE TITLE
SelectByValueFromTarget actually selects by visible text!

### ISSUE THREAD

**Issue by PhuongLam94** [serenity-bdd/serenity-core#735]
Hi there,

I'm using Serenity and following screenplay pattern. The function I mention above is actually call the selectByVisibleText from ElementFacade. Please fix it because it can cause users confuse about why their code goes wrong.

More over, the select methods for screenplay pattern do not come along with a static function to a instrumented instance. So I have to call the Instrumented.instanceOf inside my code instead of use like Click.on(target). So please synchronous all of your methods for screenplay pattern so that we can use them in a same way.

Last but not least, can you please provide an API document? I'm really surprised because I can't find any of document about API, which makes me really hard when I want to know what your method does.

Thank you.

**Comment by wakaleo** [comment]
What version are you using?

**Comment by wakaleo** [comment]
On your second point, the SelectBy* classes should not be called directly, but rather called via the SelectFromOptions builder class, like this:

    actor.attemptsTo(SelectFromOptions.byValue(code).from(COUNTRY));

**Comment by PhuongLam94** [comment]
Hi,

I'm using version 1.2.2-rc.1. I checked Serenity code on Github and saw that that error is fixed. But I starts my project by using archetype on Maven several days ago. So maybe you should update the Serenity version on the archetype?

And again please think about my suggestion of writing API document for your code.

**Comment by wakaleo** [comment]
We will update the archetype soon. Thanks for your suggestion, documentation is always an area that benefits from more love.
