### ISSUE TITLE
Serenity rest response.then() not working

### ISSUE THREAD

**Issue by jaspreetmanchinda** [serenity-bdd/serenity-core#739]
When i try to assert the response code in serenity-rest it gives the below error but when i try same directly in restassured then it works below are the details
```
public boolean assertServiceResponseCode(Response resp, intresponseCode){
			resp.then().assertThat().statusCode(responseCode);
	}
```

```
import static com.jayway.restassured.RestAssured.given;
test case passes
```

```
import static net.serenitybdd.rest.SerenityRest.given;
(net.serenitybdd.core.exceptions.SerenityManagedException: net.serenitybdd.rest.decorators.ResponseDecorated.then()Lcom/jayway/restassured/response/ValidatableResponseOptions;)
```

Request sample snippet,

```
RequestSpecification spc = given();

if(object!=null){
			List<String> mapKeysfilePath = new ArrayList<>(object.keySet());
			for(int i = 0 ; i < object.size(); i++)
			{
				if( object.get(mapKeysfilePath.get(i)) instanceof String ){
					spc.multiPart(mapKeysfilePath.get(i), object.get(mapKeysfilePath.get(i)).toString());
				}else{
					spc.multiPart(mapKeysfilePath.get(i), object.get(mapKeysfilePath.get(i)));
				}
			}
		}
		try{
			if(headers!=null)
			{
				response = spc
						.headers(headers)
						.when()
						.body(body)
						.baseUri(baseUrl)
						.post(endpoint);
			}else
			{
				response = spc
						.when()
						.body(body)
						.baseUri(baseUrl)
						.post(endpoint);
			}
			return response;
		}catch(Exception e){
			e.printStackTrace();
			return response;

		}
```

**Comment by cliviu** [comment]
Hi, can you please your project configuration, or better, a simple project that helps us to reproduce the problem ?

**Comment by siva90144** [comment]
What version of serenity rest assured you are using ?? For me working fine with 1.1.39

**Comment by cliviu** [comment]
can you please post your pom.xml ? I think that you have a class dependencies problem.

**Comment by jaspreetmanchinda** [comment]
Sorry for the delayed response, below is the sample POM,

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.sample.sample</groupId>
	<artifactId>automation-be-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>Sample Serenity project using JBehave and WebDriver</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>1.2.3-rc.5</serenity.version>
		<serenity.jbehave.version>1.21.0</serenity.jbehave.version>
		<envType>qa</envType>
	</properties>

	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>http://jcenter.bintray.com</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jbehave</artifactId>
			<version>${serenity.jbehave.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>1.2.3-rc.5</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.15</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.15</version>
		</dependency>
		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.5</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-io</artifactId>
			<version>1.3.2</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.24</version>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.6.2</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<testSourceDirectory>${basedir}/src/test/java/
					</testSourceDirectory>
					<testResourceDirectory>${basedir}/src/test/resources/
					</testResourceDirectory>
					<testClassesDirectory>${project.build.directory}/classes/
					</testClassesDirectory>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<includes>
						<include>**/*Test.java</include>
						<include>**/*TestSuite.java</include>
						<include>**/Test*.java</include>
						<include>**/When*.java</include>
					</includes>
					<argLine>-Xmx512m</argLine>
					<systemPropertyVariables>
						<webdriver.driver>${webdriver.driver}</webdriver.driver>
						<surefire.rerunFailingTestsCount>2</surefire.rerunFailingTestsCount>
						<surefire.rerunFailingTestsCount>2</surefire.rerunFailingTestsCount>
						<propertyName>${envType}</propertyName>
						<buildDirectory>${project.build.directory}</buildDirectory>
					</systemPropertyVariables>
					
							<metaFilters>
								<metaFilter>+theme *</metaFilter>
							</metaFilters>
					
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<fork>true</fork>
					<verbose>true</verbose>
					<forceJavacCompilerUse>true</forceJavacCompilerUse>
					<source>1.8</source>
					<target>1.8</target>
					<encoding>UTF-8</encoding>
					<maxmem>1024m</maxmem>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>1.2.2</version>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>.</directory>
				<includes>
					<include>**/*.properties</include>
				</includes>
			</resource>
		</resources>
	</build>
</project>
`

**Comment by cliviu** [comment]
Hi, I was not able to reproduce your issues using your pom xml. Can you please post a simplified JUnit test reproducing your problem and attach also the complete stack trace that you receive when you try to execute the test in your environment ? Thanks !

**Comment by jaspreetmanchinda** [comment]
Hi ,
below is the entire
`(net.serenitybdd.core.exceptions.SerenityManagedException: com.jayway.restassured.response.Response.then()Lcom/jayway/restassured/response/ValidatableResponse;)


net.serenitybdd.core.exceptions.SerenityManagedException: com.jayway.restassured.response.Response.then()Lcom/jayway/restassured/response/ValidatableResponse;
	at net.thucydides.core.steps.ErrorConvertor.convertToAssertion(ErrorConvertor.java:22)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:342)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at myclass.CommonHowSteps$$EnhancerByCGLIB$$852dd1b9.assertResponseCode(<generated>)
	at myclass.CommonValidationWhatSteps.validateResponseCode(CommonValidationWhatSteps.java:42)
	(reflection-invoke)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)`

**Comment by cliviu** [comment]
Hi, I'm sorry but I cannot reproduce your issue. I will need an as small as possible running example which reproduces your problem. Thanks !

**Comment by jaspreetmanchinda** [comment]
Hi,

I created a sample project using maven archetype and its working in that, i had a one more company's dependent dependency which was internally referring to some other version  of  rest assured dependency 
its working now Thanks.

**Comment by jaspreetmanchinda** [comment]
i was using 1.2.3-rc.5 version of serenity-rest-assured which was referring to 2.4.1 version of rest-assured and my internal dependency was using 2.9.0.
