### ISSUE TITLE
Ability to continue scenario execution in case of step failure

### ISSUE THREAD

**Issue by varadha2k** [serenity-bdd/serenity-core#74]
I have a requirement to continue the scenario execution in case of step failure.

I am looking for a soft asset option.

I am using hamcrest for assetion and when ever a step fails, serenity jumps in the next step.

Could you please provide a solution to this problem?

**Comment by wakaleo** [comment]
Possibly, though it is not high on the priority list at the moment - pull requests are welcome.

**Comment by varadha2k** [comment]
@wakaleo did you had a chance to work on this request?

**Comment by wakaleo** [comment]
No, not yet. Feel free to have a look at the StepInspector class if you want to have a play.

**Comment by kadamprasad** [comment]
Hi I have the same requirement so just wanted to check if this feature available now in serenity

**Comment by wakaleo** [comment]
If you need to make assertions after a step failure, use AssertJ soft asserts (or multiple consequences in the same should() statement in Screenplay). If you need to tidy up after your test, use a method that isn't annotated with the @Step annotation.
