### ISSUE TITLE
Serenity JBehave: HTML reports are broken after Jenkins upgrade to 2.5

### ISSUE THREAD

**Issue by prathimak** [serenity-bdd/serenity-core#740]
Hi,

I have updated jenkins to 2.5, serenity html reports are broken, serenity reports are broken and screenshots are displayed but i can't open them to see those screenshots i have to manually save those.

And '+' is not displayed i can't open the steps

**Comment by wakaleo** [comment]
This is a Jenkins bug (or "feature", depending on who you ask). Recent versions of Jenkins by default don't render complex HTML reports correctly. The problem and a solution are discussed here: http://stackoverflow.com/questions/35783964/jenkins-html-publisher-plugin-no-css-is-displayed-when-report-is-viewed-in-j

**Comment by prathimak** [comment]
Thank you so much its really helpful

**Comment by murthysp** [comment]
it worked for me.

**Comment by vikramvi** [comment]
@prat23k  @murthysp can you please share your **JAVA_ARGS** value.

I tried below but it's only working partially

`JAVA_ARGS="-Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"sandbox allow-forms allow-scripts; default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src data:;\""
`
I can't see screen shots. 
Refer to https://github.com/serenity-bdd/serenity-cucumber/issues/66#issuecomment-365657798
