### ISSUE TITLE
Getting text of a hidden element

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#742]
For reasons that I won't bore you with, when we run our tests on a Jenkins infra via a Selenium grid some elements **do not** render in a visible way on the page, which means when I try to get the element text, an `ElementShouldBeVisibleException` is thrown. To overcome this, I've ended up crafting the method below, but wondered if there is a more idiomatic way of obtaining hidden element text using Serenity?

```
    public static String potentiallyHiddenElementText(Target target, Actor actor) {
        WebElementFacade element = target.resolveFor(actor);
        String textValue = element.getTextValue();
        if (textValue.isEmpty()) {
            StepEventBus.getEventBus().clearStepFailures();
            return BrowseTheWeb.as(actor).evaluateJavascript("return arguments[0].innerText;", element).toString().trim();
        } else {
            return textValue;
        }
    }
```

**Comment by wakaleo** [comment]
Have you tried checking with isCurrentlyVisible()?

**Comment by nbarrett** [comment]
Yes but when then? I just need the text. Oh do you mean not resorting to getting the text and resetting the bus? Good suggestion!

**Comment by wakaleo** [comment]
Yes, just check visibility before trying to get the text, and avoiding resetting the bus.

**Comment by nbarrett** [comment]
Great that worked.... I guess my question was really about not having to do this to get the text:

`BrowseTheWeb.as(actor).evaluateJavascript("return arguments[0].innerText;", element)`

**Comment by wakaleo** [comment]
Hmmm, I'm not sure why that would return a different value from getText(), but it might be some quirky JS magic

**Comment by nbarrett** [comment]
Because my experience is that `getText()` fires an `ElementShouldBeVisibleException` when the element is hidden... My assumption is that Serenity enforces visibility as that's more in keeping with the user experience?

**Comment by wakaleo** [comment]
Possibly (I'd have to check the code), but that could be something that Webdriver is doing as well.

**Comment by slasva** [comment]
User should not see invisible text. So and getText() should not return text of invisible element. You can use js (as you do) or .getAttribute("innerText") ) .
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebElement.html#getText-- 
Get the visible (i.e. not hidden by CSS) innerText of this element, including sub-elements, without any leading or trailing whitespace.

**Comment by nbarrett** [comment]
In my experience there are cases when from a test orchestration perspective there is a need to inspect data in the DOM that is not visible to the user.  `.getAttribute("innerText")` seems like the best choice so I'll use that instead of the JS solution.
