### ISSUE TITLE
REST-API test execution time increase

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#743]
After updating Serenity version `1.2.2` to `1.2.4` I noticed drastically test execution time increase (to be more specific I use Serenity to run REST_API tests).

For instance, running 30 tests with `Serenity 1.2.2` takes 3 minutes while with with `Serenity 1.2.4` it takes 10+ minutes. Running 2k+ tests takes infinity instead of 5 minutes.

This slowness was brought in `v1.2.3-rc.9` https://github.com/serenity-bdd/serenity-core/compare/d4d003a...12cd888 unfortunately, I have no idea what goes wrong. Maybe someone can look into code or has the same problem? Later I'll try to reproduce it in the sample project.

**Comment by wakaleo** [comment]
If you could reproduce the issue in a sample project that would be great. RestAssured was updated from 2.4 to 2.9, and we switched to using ByteBuddy (but that shouldn't produce much overhead).

**Comment by dsmt** [comment]
I hope this sample project will help you https://github.com/dsmt/serenity-sample-api

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/83Yj5UQXN3WtdrcXHIBtCqBwPWIMQ2/Serenity%2BReports%2B2017-03-31%2B16-41-36.png?Expires=1491054148&Signature=jFzScq0hz5GXPuSKFUs7FyXvSxk~PPSiuV0apW4ol~gYdWX6LeVD6g0q0rLYOUX70QREpo38wYmUsyJj7-rH-x4EEXq95zYeSv-xT0Gh9YC7f2v32~vykuRu1ltManjghtdQbjV6ZBDx3IiZnOf-Qo6GYFTV~QkXKYHlbEWtMM~18wW5nHNGGWwBIsBDOzfk02y7QwpyYaKQzrX3AWjkrxKJLXZPFEw-kdadvKVOqsREbIJIlEoHPSgcbDuqMilaWcD7zIYpZcTaJ4Bt59rJj85iFHZYK6voY8duQLryBuSMg5J7KQ0AManFZBHWC70SPLygdLN0BK4qz5VJ4lGWmQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/Qhr4PUiaguhlzRlGEVLqM7RNZJFvNj/Serenity%2BReports%2B2017-03-31%2B16-43-16.png?Expires=1491054219&Signature=UtQlohN0-qGrZp6-Vhp8PsB939ud3~vvFRN-BA8zf6MoYFERZ2ttN-5DwaODG~NF6Iz6Z5PJEHCAyLTFfvJ6rH4U8lWUrRdJEqxygU~EEfkEweQZnrBoIbxSgAjkQ9df8FlvsFVHjgSM29aLeYSyubzvhcd7R4oOCCMooKhd~uIN5G2xPvp1rs4v1iLHGsQZdBRd~R8x2UeBdlP7uGH3G6GcDaQTwC4O12mWlqHcd46AUjcSFbrEn-V3k9Seqtp1RKbVMSf8pI6Rf5Yu~QVuL4FqhViqgcoh07xhJGJ1UZWQp6iAbu3lhdHL2Q6Q0~2pRq8jS5QGm~84pvvsKcJsIw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by cliviu** [comment]
Thanks for the sample project. We are on it.

**Comment by dsmt** [comment]
Great news! Thank you very much!

**Comment by wakaleo** [comment]
Could you try with the latest version?

**Comment by dsmt** [comment]
It seems to be fixed right now, thanks!
