### ISSUE TITLE
total fail percentage is shown wrong in the serenity report

### ISSUE THREAD

**Issue by drvgao** [serenity-bdd/serenity-core#744]
Total Tests: 4, Passed 2, and failed 2. The fail percentage is shown as 0 it should be 50%

             Total    Pass         Fail
Total	4	2 (50%)	2 (0%)

<serenity.version>1.2.4</serenity.version>
<serenity.jbehave.version>1.24.0</serenity.jbehave.version>

![image](https://cloud.githubusercontent.com/assets/13764217/24599314/3cd9b958-186d-11e7-9c60-cc7774baca24.png)

**Comment by wakaleo** [comment]
Thanks for spotting this, there will be a fix in the next release.

**Comment by drvgao** [comment]
Thank you! Any rough date for the next release?

**Comment by wakaleo** [comment]
Try with 1.2.5-rc.2

**Comment by wakaleo** [comment]
I believe this works now, please feel free to reopen if not.
