### ISSUE TITLE
Remaining test cases in class are absent in report when driver fails to be instantiated properly

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#746]
We have intermittent problems instantiating our IE driver on our build system. This seems to be a fact of life and much is documented on the internet about the flakiness of IE. Often on the next  `@Test` method execution, the instantiation is successful, which means that we **ought** to get a small number of failing test cases. In this situation, we see exceptions thrown as follows:

```
2017-04-04 21:10:30.840 ERROR net.serenitybdd.core.Serenity - Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
net.thucydides.core.webdriver.UnsupportedDriverException: 
Could not instantiate new WebDriver instance of type class org.openqa.selenium.ie.InternetExplorerDriver (Unexpected error launching Internet Explorer. 

java.lang.ClassCastException: net.thucydides.core.webdriver.stubs.WebDriverStub cannot be cast to org.openqa.selenium.JavascriptExecutor

```
However what actually happens when this kind of exception is thrown is that the total number of test cases actually run and reported on are quite significantly lower that the expected total. (e.g. these test cases do not appear in the ignored or error bucket, they are completely absent). My observation is that no attempt is made to run 'remaining' test cases in a class after the first initial test fails in the way described above. 

This is a significant problem when we have say 10 `@Test` methods in a class and the test fails on the first because the other 9 go missing. Is there anything that can be done to force serenity to at least attempt every test case, otherwise our stats go completely haywire and important data is lost?

One thing that is notable when mode of failure occurs is that we see `TEST STARTED: Initialisation`  rather than `TEST STARTED: testMethodName`. In the code this seems to originate from `JUnitStepListener.java`:

![image](https://cloud.githubusercontent.com/assets/626941/24701983/9e37b0c8-19f4-11e7-8077-66061b68dd7a.png)

..implying that the description cannot be resolved in this mode of failure. Not sure what that means or how to fix though!

**Comment by wakaleo** [comment]
I think this should be fixed in the latest version - could you check on your side?
