### ISSUE TITLE
Ability to use several drivers in one test

### ISSUE THREAD

**Issue by jeromevdl** [serenity-bdd/serenity-core#748]
Maybe it is already possible but I can't figure out how to do it. The use cas is the following one:

I have two users (one that enter some information, the other who validates this info). For the moment I do login with one user, enter the info, logout, login with the other, validate,... and sometimes there are even more roundtrips. So it takes quite a long time to logout/login each time. 

I'd like to use two browsers (two drivers instances but only one kind of browser: chrome, FF, phantom), one for each user, so i can play with one or the other without disconnecting.

Currently, I have the following : 
- cucumber feature file
- integration test : 
```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features = "src/test/resources/features/advisor", glue = "x.y.z.advisor")
public class AdvisorIT {}
```
- StepDefinitions :
```
public class AdvisorStepDefinitions {
    @Managed(uniqueSession = true, clearCookies = ClearCookiesPolicy.Never)
    protected static WebDriver         driver;

    @Steps
    protected static BaseSteps         baseSteps;

   @Steps
    private static AdvisorSteps advisorSteps;
    // ....
}
```
- Steps : 
```
public class BaseSteps extends ScenarioSteps {
	LoginPage loginPage;
	HomePage homePage;

	@Step("User {0} is connecting")
	public void user_is_connecting(UserProfile userProfile) {
		loginPage.open();
		loginPage.login(userProfile, true);
	}
    // ....
}
```
I have seen that there is a setDriver() in the PageObject, a setPages() in the ScenarioSteps. But  everything is injected automatically and i can't find the link between Pages and PageObject.
I've seen there is also a ManagedPages annotations but don't know if I can play with two ones and two drivers...

So question : Is it possible to manipulate two drivers and how ? Or if not, would it be possible to add the feature ?

**Comment by wakaleo** [comment]
You can do this very easily using the ScreenPlay pattern (and this would be the recommended approach), since it is actor-centric and not step-centric.

**Comment by jeromevdl** [comment]
Thanks, indeed, it's elegant. But quite a huge refactoring... Actor, Actions, Tasks, Questions, ... I need to rewrite all the steps, and a big part of the pages. I'll see if i can do it with 2 managed drivers...

**Comment by wakaleo** [comment]
I don't think that would work as-is, but if you have a look at the way drivers are handled in Screenplay WebDriver, you might be able to use that instead (there is basically a map of drivers, where each driver is mapped to an actor name)

**Comment by wakaleo** [comment]
Closing, presumed answered.

**Comment by tiwari90** [comment]
@jeromevdl 
Do you have any update on this, as I am facing an issue similar to this one?
