### ISSUE TITLE
webdriver.gecko.driver is ignored when instantiating new Firefox driver

### ISSUE THREAD

**Issue by gciltaru** [serenity-bdd/serenity-core#751]
Given
webdriver.gecko.driver with a valid geckodriver file path
and geckodriver executable is not found in the current Path
Then
I expect that Marionette driver is instantiated
Issue: Firefox driver is instantiated

Note: FirefoxDriverProvider.java only evaluates if geckodriver is found in the classpath, not also if webdriver.gecko.driver is set.

**Comment by wakaleo** [comment]
Thanks for raising this. PRs are welcome ;-).

**Comment by wakaleo** [comment]
This should working in the latest version
