### ISSUE TITLE
Add ability to see response body for responses with 'octet-stream' content type in report

### ISSUE THREAD

**Issue by Vamsi447** [serenity-bdd/serenity-core#755]
Response body in the Serenity Report for Rest Assured is not Recorded for the Content Type "octet-stream".

Add this ability to see the response body.

Response is not captured for Content Type: "octet-stream" by the method shouldRecordResponseBodyFor(Response result) . Sample code is as shown below.

public class RestReportingHelper {

    public RestReportingHelper() {
        getEventBus().registerListener(new RestStepListener());
    }

    private static boolean shouldRecordResponseBodyFor(Response result) {
        final ContentType type = ContentType.fromContentType(result.contentType());
        return type != null && (ContentType.JSON == type || ContentType.XML == type
                || ContentType.TEXT == type || ContentType.HTML == type);
    }

![reponsebody_blank](https://cloud.githubusercontent.com/assets/27009181/24798984/7e72144a-1bb6-11e7-98a8-e998d0011e03.JPG)

**Comment by wakaleo** [comment]
An octet stream would not be particularly meaningful in an HTML report, and would need special processing to be rendered in HTML. Pull requests welcome.

**Comment by Vamsi447** [comment]
@wakaleo : Thank you for your quick response. By reading your above comment, I am not able to come to conclusion. Could you please elaborate more on "Pull requests welcome.".

**Comment by wakaleo** [comment]
I'm not sure of how generally useful (displaying a stream of bytes, even in hexadecimal form in an HTML report) this feature would be, but you are welcome to try to implement a solution and submit a Pull Request.

**Comment by Vamsi447** [comment]
@wakaleo : 
As you suggested i have taken source code and made changes to build solutions.

but unfortunately when i am trying to build, i have observed build failed with below error.

* What went wrong:
A problem occurred evaluating root project 'serenity-core-master'.
> One of setGitDir or setWorkTree must be called.

i have made below changes in the RestReportingHelper class as
private static boolean shouldRecordResponseBodyFor(Response result) {
        final ContentType type = ContentType.fromContentType(result.contentType());
        return type != null && (ContentType.JSON == type || ContentType.XML == type
                || ContentType.TEXT == type || ContentType.HTML == type **|| ContentType.BINARY == type**);
    }

can you please help me on how to build and apply the changes or else can you pick my changes and commit.

Thanks in advance.

**Comment by wakaleo** [comment]
Normally "gradle test integrationTest install" should build the project. What command are you using?

Also: your solution will record binary content, but I'm not sure it will render it correctly. Make sure you have some unit tests as well to demonstrate how (and that) the feature works.

**Comment by Vamsi447** [comment]
I have used mentioned command "gradle test integrationTest install" and I got following build error:

PS D:\Source\Serenity_Mars\serenity-core-master> gradle test integrateTest install

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Source\Serenity_Mars\**serenity-core-master\serenity-core\build.gradle' line: 10**

* What went wrong:
A problem occurred evaluating project ':serenity-core'.
> Cannot invoke method status() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by Vamsi447** [comment]
But, the above mentioned solution will record the response for the contentType: **application/octet-stream**.  Where as current serenity report is skipping the recording the response when the Content Type is **application/octet-stream**. 
Where currently I am not able to build the solution
. I have tried initially with gradle  3.3 version and later with 2.10.

**Comment by wakaleo** [comment]
We don't add any code without tests that demonstrate the code. If you can provide a test to illustrate the change (including at the reporting level), I will be able to take a look. Otherwise we will need to wait until someone can write a test for the change.

**Comment by Vamsi447** [comment]
I have identified that while build is failing is that, I did not do: git clone. 
But, Now I am getting following error:
PS ~\serenity-core> gradle test integrateTest install
Publishing serenity-ant-task:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-core:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-report-resources:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-browsermob-plugin:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-gradle-plugin:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-junit:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-rest-assured:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-sample-alternative-resources:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-screenplay:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-screenplay-webdriver:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-spring:net.serenity-bdd:1.2.5-rc.3
Publishing serenity-test-utils:net.serenity-bdd:1.2.5-rc.3

FAILURE: Build failed with an exception.

* What went wrong:
Task 'integrateTest' not found in root project 'serenity-core'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info
or
-debug
option to get more log output.

BUILD FAILED


Can you help me How to resolve this. 
Thanks in advance..

**Comment by wakaleo** [comment]
It should be "gradle test integrationTests install". Or "gradle test" if you just want to run the unit tests, or "gradle install" to install a snapshot into your local maven repo for testing.
