### ISSUE TITLE
Offer hook for custom webdriver configuration

### ISSUE THREAD

**Issue by obecker** [serenity-bdd/serenity-core#758]
Currently Serenity offers only limited support for changing or extending the configuration of the available ```DriverProvider``` classes.

In our use case we need to customize Chrome to always use English as accepted language header. This would require to set a special ```prefs``` property as experimental option, however I don't see how to achieve this with the current ```ChromeDriverProvider```.

**Comment by obecker** [comment]
I think https://github.com/serenity-bdd/bdd-starter/issues/1 could be solved with this API extension as well.

**Comment by wakaleo** [comment]
This already exists in the form of custom provided drivers.
