### ISSUE TITLE
Not able to run all the scenarios of one feature file in single browser instance

### ISSUE THREAD

**Issue by narottamgla** [serenity-bdd/serenity-core#759]
I am not able to execute selenium,cucumber & serenity scenarios of one feature file in single browser instance and currently each scenario is running in new browser instance
Below are my configuration:
**Serenity and Cucumber version:**
        <serenity.version>1.2.2-rc.1</serenity.version>
        <serenity.cucumber.version>1.1.16</serenity.cucumber.version>
**serenity.properties details:**
serenity.use.unique.browser=true
restart.browser.each.scenario=false

Please let me know what other configuration i need to do to run all scenarios in one browser instance

**Comment by wakaleo** [comment]
Please ask questions on StackOverflow with the #serenity-bdd tag.
