### ISSUE TITLE
serenity BDD is failing to execute step after a comment is inserted in story file

### ISSUE THREAD

**Issue by gvprashanth** [serenity-bdd/serenity-core#760]
Hi,

I have taken latest version of Serenity which 1.2.5 which is failing to execute the steps after a comment is inserted in story file.

For example

Given user is logged in
!-- this is step process the login
When the user clicks on register button
Then user is taken to registration page

in the above example after 2nd line, Serenity is failing to execute When and then statement which is line 3 and 4.

Please help me in resolving this issue

**Comment by wakaleo** [comment]
This is not a Serenity issue - JBehave does not support comments in scenarios.

**Comment by gvprashanth** [comment]
Thanks for the response can you please let me know how to achieve this in Serenty. My requirement is need to put Requirement ID to all the then statement for traceability. Is there a way to achieve this

**Comment by wakaleo** [comment]
You could add a tag in the step code, e.g.

```        StepEventBus.getEventBus().addTagsToCurrentTest(ImmutableList.of(TestTag.withValue("requirement:req123")));
```
