### ISSUE TITLE
serenity.driver.capabilities is not working for ie driver

### ISSUE THREAD

**Issue by prathimak** [serenity-bdd/serenity-core#762]
Hi,

I tried to set the DesiredCapabilities for internet explorer, below is my code
serenity.only.save.failing.screenshots=true
serenity.verbose.steps=true
thucydides.adaptors.zephyr=net.thucydides.plugins.jira.adaptors.ZephyrAdaptor
thucycides.step.delay=001
story.timeout.in.secs=100000
webdriver.timeouts.implicitlywait=1000
serenity.driver.capabilities=INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS:true
driver=iexplorer

but i am getting below exception

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.ie.InternetExplorerDriver (Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. 

But with selenium3 using below code I am able to launch browser without any issues

    System.setProperty("webdriver.gecko.driver", "C:\\\\Downloads\\geckodriver-v0.15.0-win64\\geckodriver.exe");
        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
        capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        try {
            WebDriver driver = new InternetExplorerDriver(capabilities);
            driver.get("http://google.com");
            Thread.sleep(1800);
        } catch (Exception e){
            System.out.println(e);
        }

**Comment by wakaleo** [comment]
"Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones." - this is a known IExplorer issue, unrelated to Serenity,

**Comment by prathimak** [comment]
Yes but i am ble to by pass this issue using INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS property,its working with selenium3

**Comment by prathimak** [comment]
@wakaleo Ignore i managed to create my own driver like below able to run tests
public class IeDriver implements DriverSource {

	@Override
    public WebDriver newDriver() {
        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
        capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
		return new InternetExplorerDriver(capabilities);
    }

	@Override
	public boolean takesScreenshots() {
		// TODO Auto-generated method stub
		return true;
	}
