### ISSUE TITLE
Extract test meta values in testoutcomes

### ISSUE THREAD

**Issue by jaspreetmanchinda** [serenity-bdd/serenity-core#765]
Extracting meta values in test outcomes is missing.

**Comment by wakaleo** [comment]
You'll need to be a little bit more precise. Could you explain what you are trying to do, or even better, provide a failing scenario or test case that illustrates the problem?

**Comment by jaspreetmanchinda** [comment]
Considering a scenario in feature file as below,

Scenario: Looking up the definition of 'apple'
Meta:
@suite smoke
Given the user is on the Wikionary home page
When the user looks up the definition of the word 'apple'
Then they should see the definition 'A common, round fruit produced by the tree Malus domestica, cultivated in temperate climates.'

now using TestOutcomes I want to extract meta information for specific scenario, but  there is no such facility.

**Comment by jaspreetmanchinda** [comment]
Creating a separate thread as this is closed.
