### ISSUE TITLE
Extracting meta information for a scenario using test outcomes.

### ISSUE THREAD

**Issue by jaspreetmanchinda** [serenity-bdd/serenity-core#766]
Considering a scenario in feature file as below,

Scenario: Looking up the definition of 'apple'
Meta:
@suite smoke
Given the user is on the Wikionary home page
When the user looks up the definition of the word 'apple'
Then they should see the definition 'A common, round fruit produced by the tree Malus domestica, cultivated in temperate climates.'

now using TestOutcomes I want to extract meta information for specific scenario, but there is no such information in the outcomes.

**Comment by wakaleo** [comment]
So this is a question rather than a defect? If this is the case, StackOverflow is the preferred forum. Have you tried `Serenity.getCurrentSession().getMetaData()`
