### ISSUE TITLE
WebDriverFacade fails to remove closed timeouts, thus introducing a memory leak

### ISSUE THREAD

**Issue by richardLuko** [serenity-bdd/serenity-core#767]
There is a memory leak in WebDriverFacade, if multiple tests are running continuously. 
Even though class manages to close the resource, but it fails to remove its instances from the map, which grows to infinity.

After debugging I found out:
After WebDriverFacade.quit() is initialised, RemoteWebDriver closes and nullifies SessionId, but webDriverFactory.timeoutStack still has the object reference in the Map.

To fix this issue add:
` webDriverFactory.timeoutStack.popTimeoutFor(getProxiedDriver());`
to WebDriverFacade.quit() method

**Comment by wakaleo** [comment]
Thanks for spotting this, I'll run some checks and push a patch in the next day or two.

**Comment by richardLuk** [comment]
Hi @wakaleo 
Thank you for such a quick response and fix!

Sadly, it did not fix the issue. Apparently TimeoutStack.popTimeoutFor(<...>) does not remove map entry if stack is empty.
I have created a patch for this issue, which removes map entry from timeoutStack
[767.patch.zip](https://github.com/serenity-bdd/serenity-core/files/954665/767.patch.zip)

**Comment by wakaleo** [comment]
Hi Richard,

Could you submit this patch as a PR (that way you get credit as a contributor :-) )

**Comment by wakaleo** [comment]
Fixed.
