### ISSUE TITLE
Failure in execution when maven and serenity concatenate stories 

### ISSUE THREAD

**Issue by jomejia23** [serenity-bdd/serenity-core#770]
Hi,

We're trying to execute some concatenate stories , but We have one error with it,

**POM:**
_________________________________________________________________________________________________________________

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.sura.bdd</groupId>
    <artifactId>groupcenter</artifactId>
    <version>1</version>
    <packaging>jar</packaging>

    <name>BDD SURA - MenuProducto</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.42</serenity.version>
        <serenity.jbehave.version>1.13.0</serenity.jbehave.version>
        <junit.version>4.12</junit.version>
        <slf4j.simple.version>1.7.7</slf4j.simple.version>
        <lambdaj.version>2.3.3</lambdaj.version>
        <jbehave.core.version>4.0.5</jbehave.core.version>
        <serenity.maven.plugin.version>1.1.42</serenity.maven.plugin.version>
        <maven.surefire.plugin>2.19.1</maven.surefire.plugin>
        <maven.failsafe.plugin>2.19.1</maven.failsafe.plugin>
        <maven.compiler.plugin>3.2</maven.compiler.plugin>
        <maven.compiler.plugin.source>1.7</maven.compiler.plugin.source>
        <maven.compiler.plugin.target>1.7</maven.compiler.plugin.target>
        <webdriver.driver>chrome</webdriver.driver>
        <webdriver.chrome.driver>chromedriver.exe</webdriver.chrome.driver>
        <assertj.core.version>3.4.0</assertj.core.version>
    </properties>

    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>bintray-plugins</name>
            <url>http://jcenter.bintray.com</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>xml-path</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jbehave</artifactId>
            <version>${serenity.jbehave.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.simple.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>${lambdaj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jbehave</groupId>
            <artifactId>jbehave-core</artifactId>
            <version>${jbehave.core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.6.2</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin}</version>
            </plugin>

            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin}</version>
                <configuration>
                    <includes>
                        <include>ResultadoCotizacionPrimas.java</include>
                    </includes>
                    
                    <reuseForks>false</reuseForks>
                    <forkCount>1C</forkCount>
                    <forkedProcessTimeoutInSeconds>1500</forkedProcessTimeoutInSeconds>
                    <argLine>-Xmx3096m -XX:MaxPermSize=3096m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                        <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin}</version>
                <configuration>
                    <source>${maven.compiler.plugin.source}</source>
                    <target>${maven.compiler.plugin.target}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>

# **FIRS .STORY**
Scenario: validar resumen en datos basicos de para una cotizacion
Meta: @id pasarSiguienteParaCotizacion
GivenStories: stories/groupcenter/autenticacionGroupCenter/autenticacion_group_center.story#{id:ingresoAplicacionDashBoard},
              stories/groupcenter/navegacionMenu/navegacion_menu.story#{id:ingresaAutosCotizacion},
              stories/groupcenter/datosTomador/datos_tomador_ingreso.story#{id:tomadorResultadoCoticacionPrimas},
When quiera ver el resumen de los datos basicos
And debe mostrar toda la informacion de datos basicos
Then debe redirigir a la seccion de riesgos

**___________**

# **SECOUND STORY**
Scenario: Ingresar en el formulario varios riesgos para evaluar cotizacion de priemas
Meta: @id ingresarVariosRiesgosMasivos
When ingresar a adicionar riesgo
And se ingresa toda la informacion en la lista y se guarda:
|placa  |modelo|codigoFasecolda |bonificacionTecnica |claseDeVehiculo    |ciudadCirculacion   |servicio  |valorAccesorios |valorAccesoriosEspeciales|plan                |bonificacionComecial|transportaCombustible|blindado|descuentoDispositivo|descuentoRiesgo|recargoDelRiesgo|
|ABC345 |2014  |00608001        |13                  |Camperos y pickups |mede                |Particular|30              |12                       |Plan Autos Global   |12                  |no                   |Si      |Coltrack            |12             |12              |
Then se debe visualizar el riesgo con toda su informacion en la tabla de datos

**________**

# **THIRD STORY "main"**
Scenario: tarifar un grupo de riesgos
Meta: @id tarifacionGrupoDeRiesgos
GivenStories: stories/**FIRS_STORY**.story#{id:pasarSiguienteParaCotizacion},
stories/SECOUND_STORY.story#{id:ingresarVariosRiesgosMasivos}
When quiera ver el resumen de la cotizacion

________________________________________________________________________________________________________________
**When I executed the THIRD STORY then FIRS_STORY and SECOUND_STORY finished good, but the step of the THIRD STORY -> "When" wasn't executed.** 

**This is the log:**  
_________________________________________________________________________________________________________________
Then debe redirigir a la seccion de riesgos
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - FINISHING STEP
[pool-1-thread-1] WARN net.thucydides.core.requirements.PackageRequirementsTagProvider - To generate correct requirements coverage reports you need to set the 'serenity.test.root' property to the package representing the top of your requirements hierarchy.
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - 
        __    _____ _____ ____ _____   ____   _    ____  ____  _____ ____  
  _     \ \  |_   _| ____/ ___|_   _| |  _ \ / \  / ___|/ ___|| ____|  _ \ 
 (_)_____| |   | | |  _| \___ \ | |   | |_) / _ \ \___ \\___ \|  _| | | | |
  _|_____| |   | | | |___ ___) || |   |  __/ ___ \ ___) |___) | |___| |_| |
 (_)     | |   |_| |_____|____/ |_|   |_| /_/   \_\____/|____/|_____|____/ 
        /_/                                                                

TEST PASSED: tarifar un grupo de riesgos
----------------------------------------------------------------------------
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP Ingresar en el formulario varios riesgos para evaluar cotizacion de priemas
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP When ingresar a adicionar riesgo

[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP Clic agregar riesgo

(stories/groupcenter/formularioInformacionRiesgosDbAutocompletarAutos/formulario_informacion_riesgos_db_autocompletar_autos.story)
Meta:
@Sprint 002
@issue CD5331
@local 
@rcritica true
@tag equipo: Verde

Scenario: Ingresar en el formulario varios riesgos para evaluar cotizacion de priemas
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - FINISHING STEP
When ingresar a adicionar riesgo
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - FINISHING STEP
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP And se ingresa toda la informacion en la lista y se guarda:
|placa  |modelo|codigoFasecolda |bonificacionTecnica |claseDeVehiculo    |ciudadCirculacion   |servicio  |valorAccesorios |valorAccesoriosEspeciales|plan                |bonificacionComecial|transportaCombustible|blindado|descuentoDispositivo|descuentoRiesgo|recargoDelRiesgo|
|ABC345 |2014  |00608001        |13                  |Camperos y pickups |mede                |Particular|30              |12                       |Plan Autos Global   |12                  |no                   |Si      |Coltrack            |12             |12              |
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP Ingresar datos de informacion para ingresar: ExamplesTable[tableAsString=|placa  |modelo|codigoFasecolda |bonificacionTecnica |claseDeVehiculo    |ciudadCirculacion   |servicio  |valorAccesorios |valorAccesoriosEspeciales|plan                |bonificacionComecial|transportaCombustible|blindado|descuentoDispositivo|descuentoRiesgo|recargoDelRiesgo|
|ABC345 |2014  |00608001        |13                  |Camperos y pickups |mede                |Particular|30              |12                       |Plan Autos Global   |12                  |no                   |Si      |Coltrack            |12             |12              |,headerSeparator=|,valueSeparator=|,ignorableSeparator=|--,parameterConverters=org.jbehave.core.steps.ParameterConverters@60971131,tableTransformers=org.jbehave.core.model.TableTransformers@5308314f,defaults=org.jbehave.core.steps.ConvertedParameters@4060f7a4,headers=[placa, modelo, codigoFasecolda, bonificacionTecnica, claseDeVehiculo, ciudadCirculacion, servicio, valorAccesorios, valorAccesoriosEspeciales, plan, bonificacionComecial, transportaCombustible, blindado, descuentoDispositivo, descuentoRiesgo, recargoDelRiesgo],data=[{placa=ABC345, modelo=2014, codigoFasecolda=00608001, bonificacionTecnica=13, claseDeVehiculo=Camperos y pickups, ciudadCirculacion=mede, servicio=Particular, valorAccesorios=30, valorAccesoriosEspeciales=12, plan=Plan Autos Global, bonificacionComecial=12, transportaCombustible=no, blindado=Si, descuentoDispositivo=Coltrack, descuentoRiesgo=12, recargoDelRiesgo=12}],properties={headerSeparator=|, valueSeparator=|, ignorableSeparator=|--},propertiesAsString=,namedParameters={id=ingresarVariosRiesgosMasivos, Sprint=002, tag=equipo: Verde, issue=CD5331, local=, rcritica=true},trim=true]
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - FINISHING STEP
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - FINISHING STEP
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP Then se debe visualizar el riesgo con toda su informacion en la tabla de datos
|Placa |Modelo|Codigo Fasecolda|Bonificacion Técnica|Clase de vehículo  |Ciudad de circulación|Valor accesorios|Valor Accesorios Especiales|Plan                 |Estado    |
|ABC345 |2014  |00608001        |13                  |Camperos y pickups |MEDELLIN             |30              |12                         |Plan Autos Global   |Incompleto|
And se ingresa toda la informacion en la lista y se guarda:

|placa|modelo|codigoFasecolda|bonificacionTecnica|claseDeVehiculo|ciudadCirculacion|servicio|valorAccesorios|valorAccesoriosEspeciales|plan|bonificacionComecial|transportaCombustible|blindado|descuentoDispositivo|descuentoRiesgo|recargoDelRiesgo|
|ABC345|2014|00608001|13|Camperos y pickups|mede|Particular|30|12|Plan Autos Global|12|no|Si|Coltrack|12|12|

[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - STARTING STEP Visualizar informacion tabla de datos: ExamplesTable[tableAsString=|Placa |Modelo|Codigo Fasecolda|Bonificacion Técnica|Clase de vehículo  |Ciudad de circulación|Valor accesorios|Valor Accesorios Especiales|Plan                 |Estado    |
|ABC345 |2014  |00608001        |13                  |Camperos y pickups |MEDELLIN             |30              |12                         |Plan Autos Global   |Incompleto|,headerSeparator=|,valueSeparator=|,ignorableSeparator=|--,parameterConverters=org.jbehave.core.steps.ParameterConverters@60971131,tableTransformers=org.jbehave.core.model.TableTransformers@5308314f,defaults=org.jbehave.core.steps.ConvertedParameters@4037a14d,headers=[Placa, Modelo, Codigo Fasecolda, Bonificacion Técnica, Clase de vehículo, Ciudad de circulación, Valor accesorios, Valor Accesorios Especiales, Plan, Estado],data=[{Placa=ABC345, Modelo=2014, Codigo Fasecolda=00608001, Bonificacion Técnica=13, Clase de vehículo=Camperos y pickups, Ciudad de circulación=MEDELLIN, Valor accesorios=30, Valor Accesorios Especiales=12, Plan=Plan Autos Global, Estado=Incompleto}],properties={headerSeparator=|, valueSeparator=|, ignorableSeparator=|--},propertiesAsString=,namedParameters={id=ingresarVariosRiesgosMasivos, Sprint=002, tag=equipo: Verde, issue=CD5331, local=, rcritica=true},trim=true]
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - FINISHING STEP
Then se debe visualizar el riesgo con toda su informacion en la tabla de datos

|Placa|Modelo|Codigo Fasecolda|Bonificacion Técnica|Clase de vehículo|Ciudad de circulación|Valor accesorios|Valor Accesorios Especiales|Plan|Estado|
|ABC345|2014|00608001|13|Camperos y pickups|MEDELLIN|30|12|Plan Autos Global|Incompleto|

[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - FINISHING STEP

(AfterStories)

**_Generating reports view to 'C:\Users\jonamele\Documents\BDDGroupCenter\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 0 stories (of which 0 pending) containing 0 scenarios (of which 0 pending)
Disconnected from the target VM, address: '127.0.0.1:58310', transport: 'socket'
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=3096m; support was removed in 8.0_**

Process finished with exit code -2

---------------------------------------------------------------------------------------------------------------------

I changed the MAVEN's memory and JAVA's memory in the SO (Windows 7), but I didn't get success.

Thanks: Jonathan Mejia

**Comment by wakaleo** [comment]
Have you tried with the latest versions of serenity-core and serenity-jbehave?

**Comment by jomejia23** [comment]
Yes, I've tried but I didn't get success

When I'm trying with the new version then the execution open two browsers of chrome and the test failure, I've tried combined the following:

**First combine**
<serenity.version>1.1.42</serenity.version>
<serenity.maven.plugin.version>1.1.42</serenity.maven.plugin.version>
 <serenity.jbehave.version>1.21.0</serenity.jbehave.version>
 <jbehave.core.version>4.1</jbehave.core.version>

**second combine**
<serenity.version>1.1.42</serenity.version>
<serenity.maven.plugin.version>1.1.42</serenity.maven.plugin.version>
 <serenity.jbehave.version>**1.24.0**</serenity.jbehave.version>
 <jbehave.core.version>4.1</jbehave.core.version>

**third combine**
<serenity.version>1.1.42</serenity.version>
<serenity.maven.plugin.version>1.1.42</serenity.maven.plugin.version>
 <serenity.jbehave.version>**1.24.0**</serenity.jbehave.version>
 <jbehave.core.version>4.1</jbehave.core.version>

**quarter combine**
<serenity.version>**1.2.4**</serenity.version>
<serenity.maven.plugin.version>**1.2.4**</serenity.maven.plugin.version>
 <serenity.jbehave.version>**1.21.0**</serenity.jbehave.version>
 <jbehave.core.version>**4.1**</jbehave.core.version>

The last combination it's with error, becouse this open two browsers of chrome and test failure.

Do you have other idea for me?

The log is this:

________________________________________________________________________________________________________________
-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
-------------------------------------------------------------------------------------


(BeforeStories)
[pool-1-thread-1] INFO net.serenitybdd.jbehave.embedders.monitors.ReportingEmbedderMonitor - 1484171695story running with path stories/groupcenter/cotizacion/resultado_cotizacion_primas.story
Running story stories/groupcenter/cotizacion/resultado_cotizacion_primas.story
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - Test Suite Started: Resultado cotizacion primas
Using timeout for story resultado_cotizacion_primas.story of 3000 secs.

(stories/groupcenter/cotizacion/resultado_cotizacion_primas.story)

(AfterStories)

Generating reports view to 'C:\Users\jonamele\Documents\BDDGroupCenter\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 0 stories (of which 0 pending) containing 0 scenarios (of which 0 pending)
_**Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=156m; support was removed in 8.0**_

Process finished with exit code -2
________________________________________________________________________________

**Comment by wakaleo** [comment]
The issue may be because you have several levels of nested GivenStories. This isn't supported by Serenity, and is in my opinion an anti-pattern - if you have preconditions, it is preferable to define them as a Given step (not a GivenStory) and use a @Step or Screenplay Task under the hood to achieve the reuse.

**Comment by jomejia23** [comment]
Hi Jhon

I was loading all to jbehave, this is  anti-pattern because la logic of bussines should is in java (Serenity Framework), you are right,  I changed all the levels the project and did get success. thanks jhon

Jonathan

**Comment by wakaleo** [comment]
Thanks for the update Jonathan.
