### ISSUE TITLE
BaseStepListener trying to get TestOutcome from latest absent TestOutcome

### ISSUE THREAD

**Issue by aietcn** [serenity-bdd/serenity-core#772]
I'm using Serenity with JBehave and Spring integration. The BaseStepListener always complain about getting an absent latest TestOutcome even if the story test has passed, resulting in a failed integration test.

```
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value

	at com.google.common.base.Absent.get(Absent.java:45)
	at net.thucydides.core.steps.BaseStepListener.getCurrentTestOutcome(BaseStepListener.java:295)
```

Then I checked on the source code: [net.thucydides.core.steps.BaseStepListener.java#latestTestOutcome](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java#L298). The method`latestTestOutcome()` output can be an absent Optional, but [`getCurrentTestOutcome()`](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/thucydides/core/steps/BaseStepListener.java#L294) method is trying to `get()` from a possible absent Optional value.

I think we need to add a check on absent Optional value here.

-------------------------

dependencies:

```xml
<serenity.version>1.2.5-rc.11</serenity.version>
<serenity.jbehave.version>1.24.0</serenity.jbehave.version>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jbehave</artifactId>
            <version>${serenity.jbehave.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-spring</artifactId>
            <version>${serenity.version}</version>
        </dependency>
```

**Comment by wakaleo** [comment]
At what point is this error occurring? Could you provide a sample project?

**Comment by aietcn** [comment]
@wakaleo Here's a minimal working example that reproduces the exception I mentioned: https://github.com/aietcn/serenity-jbehave-spring-sample

You can run `mvn clean verify` directly and see the error, or run the test class `cn.aiet.serenity.rest.CompanyRegisterTest` in your IDE.

**Comment by wakaleo** [comment]
Thanks for the example, that helped me isolate and fix the issue - it will be available in the next release.

**Comment by aietcn** [comment]
@wakaleo glad it helped. Really enjoyed Serenity. Thanks for the excellent work!😉
