### ISSUE TITLE
Problem with russian features name in reports

### ISSUE THREAD

**Issue by abogdanov37** [serenity-bdd/serenity-core#773]
Hi. I am newby in Serenity and I have small problem. When I run `gradlew aggregate` i get report. It's ok. On tab _outcomes test_  i see right russian letters but on tabs _features_ and _requriments_ i see wrong letters. It's very important for me use russian language. Thanks.

**Comment by wakaleo** [comment]
Can you produce a sample project and indicate what you should see where?

**Comment by abogdanov37** [comment]
Of course

**Comment by abogdanov37** [comment]
![image](https://cloud.githubusercontent.com/assets/15830587/25527938/d6a10770-2c23-11e7-8f3f-bb05dd7d3d9c.png)

**Comment by abogdanov37** [comment]
Project url is https://github.com/abogdanov37/serenity-ui-tests

**Comment by cliviu** [comment]
Hi @abogdanov37 . Try to set export GRADLE_OPTS="-Dfile.encoding=utf-8" . see this link : http://stackoverflow.com/questions/21267234/show-utf-8-text-properly-in-gradle

**Comment by abogdanov37** [comment]
Thanks for reply. It does not help me. But I found solution. First of all I updated `serenity-core` to rc25 and I added option `feature.file.encoding = utf8`

**Comment by abogdanov37** [comment]
I have another one question.  Serenity add test class names in report as requirements. Can I some how (add annotation for  example) change this behavior?

**Comment by abogdanov37** [comment]
Sorry for stupid question. Solution had been found. Issue can be closed. Thank you.

**Comment by wakaleo** [comment]
Thanks for the update :-).
