### ISSUE TITLE
How to configure serenity reporting to include results from all parallel tests?

### ISSUE THREAD

**Issue by gohilrl** [serenity-bdd/serenity-core#774]
I have a project where I have configured cucumber to run in parallel on browserstack. Each test will run and complete but the auto generated report includes results for only one of the tests. Is there a way the report can include all results from each individual test that run in parallel?

Many thanks,

Rikesh

**Comment by wakaleo** [comment]
This is more a question for Stackoverflow (with the #serenitybdd tag) than an issue, as it doesn't relate to a defect as such. To get an aggregate report from several test runs, copy the contents of the target/site/serenity directory for each test run into the target/site/serenity directory of one of the projects, and run "mvn serenity:aggregate" or "gradle aggregate".

**Comment by gohilrl** [comment]
Thank you @wakaleo for the reply.
