### ISSUE TITLE
Is it possible to hide/disable/customize requirements section?

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#775]
In my project, each test is located in a separate class. By default, each class is considered as a story, so hundreds of tests overflow requirements section in test report with useless information.

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/xZbllJ2mXkD9Yt1iZhhRuUnvqFtXOx/Serenity%2BReports%2B2017-04-30%2B20-24-50.png?Expires=1493659579&Signature=Ue6z4vnOOa2wMpWvPrcz9XOOO19sY5YM3Bal92G4AagQZTjcy199-RmwQLEyKbt~fSAvuE4SprmPfU6phwF91MfBHnXOv7N0QOFjkuqxy~1MbopKmWVTOxzfms1eyPS4RAxyv6u0uhEiz2WYSgMEl3kSanCdtOPiUkrNDSkYFwao9mu55byD7vacJT7P3rCij8rtXcWaZ8cxb2~4247R6UJ45Ib-k720iRQmc8Yrv51wNsDAC5PIvrMhuPqNoteUJ0cTrrQoZFllUVzOsgnxl8FPlR8JuFQdc4-YOT2gAyiqbAj83UOVwvdlpH1KIPXe37CB1~noMdkC1jv8HKqLrg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Ideally, I want to see aggregated information by top level folders (see screenshot) without enumeration of all classes. 

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/2B5E1IjeM4RuEitQoSDPWoeONzaJhQ/Trucker%2BPath%2BAPI%2Btests%2B-%2BNetBeans%2BIDE%2B8.1%2B2017-04-30%2B20-09-03.png?Expires=1493658604&Signature=NyKT-3qLY8Wp-btoAzJfTgMw6cgOXG2BI7~e2oolPnlgoC4C6JuUq-BCdyTY9hS~YlW4Mrgbw6E8KevxTksU7IypB-BMvU1v8vSLQvNho5HcUbHdX-fhi~bsOzHmVknXxItks8LMa5pakLgTZATPQHv2VRxgPmlt2HdReD1TZtik25xS2mR~4obf3JtJtOfgFlHGLaJX--hgXRin6cfy8vP4iRALlLvjS5qfeV8E95ntkFu4NQwtcynLVFWvg6ioRXMAY6Q6k5GuQNE71eYlkhAgBjXgIFkWlXn9OMOOrGx4Ad6Rmo1Aai40~e9Za5SulfRWXNyqgPOHgIZDo5wlZQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

If it is not implemented, maybe there is a way to disable this feature?

**Comment by Invictum** [comment]
@dsmt 
It is possible to hide story tag from report that enabled by default. Use `dashboard.excluded.tag.list=story` option to achieve it.

**Comment by dsmt** [comment]
@Invictum, thank you, this was exactly what I was looking for

**Comment by ForeverMonica** [comment]
Hi @dsmt ,

Can you please share how you implemented change for above issue,
as from reference manual it is not quite clear.

Thanks
