### ISSUE TITLE
webdriver.timeouts.implicitlywait = 30000  is not working

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#78]
Hi John,
i've set below value in serenity.properties file
webdriver.timeouts.implicitlywait = 30000 

but still webdriver times out in 8 or 9 seconds.

Can you please review this 

Thanks,
Vikram

**Comment by wakaleo** [comment]
The latest version (1.0.57) might fix this, but the issue is too general - you will need to produce a sample test case to be sure. The best thing to do is to create a pull request with a new test case in WhenManagingWebdriverTimeouts.groovy.

**Comment by vikramvi** [comment]
Hi John,

Sorry for late update , sure I will try this again with latest version of framework and also try to submit PR.

Thanks,
Vikram

**Comment by vikramvi** [comment]
working fine with latest version of framework , closing for now.

Regards,
Vikram
