### ISSUE TITLE
Browserstack capabilites are not properly sent to browserstack

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#781]
Looks like we are not adding the proper Browserstack capabilities anymore and browserstack  `build ` property is not working.

It might be related with changes in:
https://github.com/serenity-bdd/serenity-core/commit/a7f00da649e50f14b11e6f628c17fe974436c582#diff-54b0f2359550006048d4d7a309ccf4e2L60

**Comment by bebef1987** [comment]
@wakaleo do you know why this happen?
![untitled](https://cloud.githubusercontent.com/assets/703611/25855400/c2665c0e-34db-11e7-86ed-f2706c574a67.png)

**Comment by wakaleo** [comment]
How are you passing the parameters?

**Comment by bebef1987** [comment]
The same as we did before

`browserstack.build=${BUILD_NUMBER}` this would translate to '-Dbrowserstack.build=509'

There was no change in the jenkins build.

**Comment by bebef1987** [comment]
@wakaleo  any ideas why this happens?

**Comment by wakaleo** [comment]
I can't see anything in the code that would change that - try putting a breakpoint and seeing what is happening in the code.

**Comment by wakaleo** [comment]
Fixed in 1.4.1-rc.4

**Comment by SnakeB** [comment]
@wakaleo Is this issue fixed? I am using  1.5.0-rc.1 but the properties are not added i.e only browserstack.build is added to the capabilities but not build without the browserstack prefix, because of that my tests are not running on browserstack.
