### ISSUE TITLE
History gradle task finishes with an error

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#782]
Hello,

I noticed that in recent serenity release we have two new gradle tasks - history, clearHistory
However, history task runs with an exception (some test results exist in target/site/serenity):
`11:06:53 AM: Executing external task 'history'...
Updating project.build.directory to D:\Projects\jbehave-webtest-todomvc\serenity-jbehave-sample
project.serenity.outputDirectory= D:\Projects\jbehave-webtest-todomvc\serenity-jbehave-sample\target\site\serenity
:history
Updating project.build.directory to D:\Projects\jbehave-webtest-todomvc\serenity-jbehave-sample
Updating project.serenity.outputDirectory to D:\Projects\jbehave-webtest-todomvc\serenity-jbehave-sample\target\site\serenity
:history FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':history'.
> Could not find matching constructor for: net.serenitybdd.core.history.FileSystemTestOutcomeSummaryRecorder(java.io.File, java.lang.Boolean)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 23.204 secs
Could not find matching constructor for: net.serenitybdd.core.history.FileSystemTestOutcomeSummaryRecorder(java.io.File, java.lang.Boolean)
11:07:24 AM: External task execution finished 'history'.`

**Comment by wakaleo** [comment]
Are all of your Serenity versions set to the latest version (1.4.0)?

**Comment by ilzul** [comment]
Yes, I've updated everything to the 1.4.0 version.
Here is my build.gradle file - https://github.com/ilzul/serenity-jbehave-sample/blob/master/build.gradle

**Comment by wakaleo** [comment]
Is your gradle plugin version set to 1.4.0?

**Comment by ilzul** [comment]
I think yes, here is the build script:
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.4.0")
    }
}
and the build.gradle file - https://github.com/ilzul/serenity-jbehave-sample/blob/master/build.gradle

**Comment by wakaleo** [comment]
By the looks of it, Gradle is loading an old version of the FileSystemTestOutcomeSummaryRecorder class (which is in serenity-core).

**Comment by ilzul** [comment]
Sad news. Not sure how to resolve this issue for now.
I've tried to refresh dependencies with **gradlew --refresh-dependencies** command, and updated to **1.4.1-rc.3** version, but still have the same error..
It's not critical for me, but anyway.

**Comment by wakaleo** [comment]
Gradle plugin dependencies are a bit tricky. You could try including a dependency on serenity-core in the buildscript.
