### ISSUE TITLE
Log filled with [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.take.screenshots, please use the serenity.* format instead. 

### ISSUE THREAD

**Issue by hazmeister** [serenity-bdd/serenity-core#784]
I've moved to Serenity 1.4.0 and started setting some Serenity Properties in the test suite using SerenitySystemProperties class to cut down on needless repetition in my properties files used for different browsers.  Here's a sample:

        SerenitySystemProperties properties = new SerenitySystemProperties();
        properties.setValue(WEBDRIVER_WAIT_FOR_TIMEOUT, "10000");
        properties.setValue(THUCYDIDES_RESTART_BROWSER_FOR_EACH, "STORY");
        properties.setValue(THUCYDIDES_TAKE_SCREENSHOTS, "AFTER_EACH_STEP");

I'm using THUCYDIDES because there doesn't appear to be a SERENITY equivalent in all cases, but there now seems to be a warning when setting THUYDIDIES properties:

    [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.take.screenshots, please use the serenity.* format instead.
    [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.take.screenshots, please use the serenity.* format instead.
    [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.take.screenshots, please use the serenity.* format instead.
    [pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.take.screenshots, please use the serenity.* format instead.

Is there a plan to fully migrate the SerenitySystemProperty class?  Would it help if I raise a PR with duplicate properties and tag the THUCYDIDES ones as @Deprecated?

**Comment by wakaleo** [comment]
Serenity supports both, but the constants are still in the old naming convention. Yes, a PR would help :-).

**Comment by hazmeister** [comment]
Thanks John, I'll get that raised.
