### ISSUE TITLE
Is it possible to add webdriver logs to the reports?

### ISSUE THREAD

**Issue by csabakoncz** [serenity-bdd/serenity-core#785]
Similarly to including screenshots taken by webdriver when a step fails, can we add the browser logs (or any other textual information that could clarify the circumstances of the failure) to the Serenity reports?

**Comment by wakaleo** [comment]
This is a good idea; we have a backlog task to add the ability to log arbitrary information in the reports, and this would go well with that feature.

**Comment by mugar97** [comment]
Please, add this feature, we need it
