### ISSUE TITLE
Is it possible to run scenarios by tags when use SerenityParameterizedRunner

### ISSUE THREAD

**Issue by VHreptovich** [serenity-bdd/serenity-core#786]
SerenityBDD 1.3.0 and 1.4.0
Scenarios with SerenityParameterizedRunner run always (not considering tags). 
I can't filter tests by tag (@WithTag). For Scenarios with SerenityRunner it works.
For SerenityBDD 1.2.5-rc.6 it works also.

**Comment by wakaleo** [comment]
Fixed in 1.4.1-rc.2
