### ISSUE TITLE
How can I use my own WebDriver instance in Serenity.

### ISSUE THREAD

**Issue by baotrans3** [serenity-bdd/serenity-core#790]
Hi all,
I create a class loadBrowser() to load web browser base on my config in serenity.properties
(In serenity.properties file, I only have a line "testBrowser = firefox" or chrome,ie...)
in loadBrowser class I will read serenity.properties file, and open suitable browser.
In test class i use @Managed anotation to manage webdriver.
I want to Serenity use "driver" parameter in loadBrowser class. Is it possible? (Serenity doesn't need to initiate new driver, just use the existing one in loadBrowser()

Thanks for your help.

**Comment by wakaleo** [comment]
Use a provided driver (http://thucydides.info/docs/serenity-staging/#_custom_webdriver_implementations). But why do you feel you need to do this?

**Comment by baotrans3** [comment]
I can't run Serenity current version with latest Firefox version. Serenity can launch FF but do nothing else and I got error "Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms."
 (Not sure is if there is any way to make it works)
So I create my own loadBrowser class to run with Selenium WebDriver 3.3.x and easy to switch between Firefox/Chrome/IE and mobile app/web... as well.

**Comment by wakaleo** [comment]
You may have trouble because the Webdrive API contains many breaking changes between Selenium 2 and 3
