### ISSUE TITLE
How to config Serenity to user Selenium WebDriver 3

### ISSUE THREAD

**Issue by baotrans3** [serenity-bdd/serenity-core#791]
Hi all,

Selenium WebDriver version is now 3.4.0. How can I config Serenity to use new version?

Thanks for your help.

**Comment by wakaleo** [comment]
Selenium 3.x is not backward compatible with Selenium 2.53.0 and required Java 8, which many users still cannot use. Serenity 1.5 will support Selenium 3

**Comment by baotrans3** [comment]
Thanks for your quick answer. (y)

**Comment by baotrans3** [comment]
Hi @wakaleo 

Do you know when serenity 1.5 will be released?

Thanks!
