### ISSUE TITLE
How to reload page elements using pagefactory

### ISSUE THREAD

**Issue by Lucasgermani** [serenity-bdd/serenity-core#795]
Hello, i'm having a issue regarding element loading using pagefactory:

`@Findy(id = painelDeContole)
private WebElementFacade painelDeControleBtn;`

The trick is, 
![screenshot_1](https://cloud.githubusercontent.com/assets/1315828/26168352/2aa9cdfc-3b10-11e7-9f05-81b6da7cd836.jpg)

on this menu i have to do a mouse-over action on "... mais" to open a sub-menu like this:
![screenshot_2](https://cloud.githubusercontent.com/assets/1315828/26168442/7563d48c-3b10-11e7-8ad5-f4fbeeda42a8.jpg)

But when i call painelDeControleBtn.isVisible() it's return false. (Last image, second icon)
I need some way to reload the page element and truly verify if the element is visible after the mouse-over action.
I've already searched for some method to do this inside PageObject and WebElementFacade but hasn't  found any.

**Comment by wakaleo** [comment]
This is a question, rather than a defect, so would be better placed on stackoverflow (use the #serenitybdd tag). I would recommend using a dynamic selector rather than a @FindBy annotation.

**Comment by Lucasgermani** [comment]
Done: http://stackoverflow.com/questions/44032061/serenity-bdd-how-to-reload-page-elements-using-pagefactory

But i'd like to use pagefactory if possible for a better code maintainability
