### ISSUE TITLE
"$" method treats "li.user > a" as an xPath instead of a cssSelector

### ISSUE THREAD

**Issue by zhtaoang** [serenity-bdd/serenity-core#796]
After debugging, I found the [isXPath()](https://github.com/serenity-bdd/serenity-core/blob/fca1739982754f6101b833409d02fa2a87c460d8/serenity-core/src/main/java/net/serenitybdd/core/selectors/Selectors.java) returns true for "li.user > a" (basically xpath.compile(xpathExpression) does not throw exceptions somehow). A possible fix would be to add another check to see if the string starts with a "/".
```
public static boolean isXPath(String xpathExpression) {
        XPathFactory factory = XPathFactory.newInstance();
        XPath xpath = factory.newXPath();
        try {
            xpath.compile(xpathExpression);
        } catch (Exception e) {
            return false;
        }
        return xpathExpression.startsWith("/");
    }
```

**Comment by wakaleo** [comment]
This won't work as not all xpath expressions start with "/". If the Java XPath compiler can process it, it is considered valid XPath. "li.user > a" is therefore ambiguous, and you will need to use a more explicit selector.
