### ISSUE TITLE
Failed to take screenshot before driver.quit() using @After cucumber annotation

### ISSUE THREAD

**Issue by rakeshnambiar** [serenity-bdd/serenity-core#797]
I am using latest chrome browser as a custom driver and able to take a screenshot during test steps, but not able to take the screenshot in case of the test is failed:

Code 
--------------------------------

if (scenario.isFailed()) {
                if((TakesScreenshot) getDriver() != null) {
                    scenario.embed(((TakesScreenshot) getDriver()).getScreenshotAs(OutputType.BYTES), "image/png");
                }
}

Error Log 
--------------------------------
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)

**Comment by wakaleo** [comment]
What is your use case for doing this? Serenity already takes a screenshot when a test fails.

**Comment by rakeshnambiar** [comment]
True. I am aware of this feature and I have configured **serenity.take.screenshots=FOR_FAILURES. But apart from the serenity report, I have a custom report as well where I would like to attach these screenshot. Moreover, I am using custom chrome browser (to specify the download directory etc) and I guess that is causing the issue.

**Comment by wakaleo** [comment]
Judging by the stack trace, this is to do with the Cucumber lifecycle, and not under Serenity's control. It might be easier to process the Serenity json reports and use the already-recorded screenshots.

Rather than using a custom driver, did you try providing the chrome arguments using the `chrome.switches` property?

**Comment by rakeshnambiar** [comment]
Yes I tried chrome.switches option as mentioned in the Issue# https://github.com/serenity-bdd/serenity-documentation/issues/51 and It was not reading the download directory when I tried. It will be great if you could mention here the format to specify the default download directly. Moreover, default directory mentioned in my method was not considered when there is a popup browser which downloads the file.

**Comment by wakaleo** [comment]
Could you share the code for your custom driver?

**Comment by rakeshnambiar** [comment]
Please change the chrome driver path and download directory path accordingly.


public class CustomChromeDriver implements DriverSource {
    public static String downLoadDirectory;
    private static WebDriver webDriver;


    public WebDriver newDriver(){
        try{
                System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver.exe");
                HashMap<String, Object> chromePrefs = new HashMap<String, Object>();

                chromePrefs.put("download.default_directory", downLoadDirectory);
                chromePrefs.put("profile.default_content_settings.popups", 0);
                chromePrefs.put("profile.content_settings.exceptions.automatic_downloads.*.setting", 1);
                chromePrefs.put("download.prompt_for_download", false);
                chromePrefs.put("pdfjs.disabled", true);
                chromePrefs.put("credentials_enable_service", false);
                chromePrefs.put("profile.password_manager_enabled", false);

                ChromeOptions options = new ChromeOptions();
                options.setExperimentalOption("prefs", chromePrefs);
                options.addArguments("--disable-extensions");
                options.addArguments("--test-type");


                options.setExperimentalOption("prefs", chromePrefs);

                DesiredCapabilities cap = DesiredCapabilities.chrome();
                cap.setCapability(ChromeOptions.CAPABILITY, options);
                cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
                cap.setCapability(CapabilityType.SUPPORTS_ALERTS, true);

                webDriver = new ChromeDriver(ChromeDriverService.createDefaultService(), cap);
        }catch (Exception e){
            throw new Error(e);
        }
        return webDriver;
    }


    public boolean takesScreenshots() {
        return true;
    }

}

**Comment by wakaleo** [comment]
For a remote driver, you need to create a RemoteWebDriver, not a ChromeDriver

**Comment by rakeshnambiar** [comment]
Thanks @wakaleo for the support. I have decided to re-use the .png files in serenity output.

**Comment by wakaleo** [comment]
No problem :-).
