### ISSUE TITLE
Different styles are applying for different exceptions in View Stack Trace popup

### ISSUE THREAD

**Issue by AlexChernookov** [serenity-bdd/serenity-core#798]
For example if this **org.openqa.selenium.NoSuchElementException** style will be like this see picture
![style2](https://cloud.githubusercontent.com/assets/5630479/26350167/8d0eab4c-3fb2-11e7-8eb6-4bf35f459820.png)

But if it's **org.openqa.selenium.WebDriverException** the style will be different  and user couldn't select whole text form the pop-up (only 2 lines and div with class '**modal-body**' looks like disabled)
And there is no hyphenation for long test case names
![style1](https://cloud.githubusercontent.com/assets/5630479/26350140/72bbf3a8-3fb2-11e7-88a3-27c2f50ce779.png)

**Comment by wakaleo** [comment]
I can't see the differences you are referring to. Could you add more screenshots to show the actual differences in the rendered reports?

**Comment by AlexChernookov** [comment]
I'm not able to reproduce this but when it was WebDriver exception overlay was disabled. If it's appeared again I'll try to provide more details.
So now you could close the issue

**Comment by wakaleo** [comment]
Thanks for the feedback Alex.
