### ISSUE TITLE
Browsermob proxy is stopped when working with multiple tabs

### ISSUE THREAD

**Issue by hazmeister** [serenity-bdd/serenity-core#802]
I have a test which checks links which open in new tabs.  Before including the Serenity Browsermob plugin, I would close each tab after running through my checks.

When using the Serenity Browsermob plugin, calling `getDriver.close()` on the extra tab shuts down the proxy, which then kills all network for that browser session, making further testing impossible.  I believe the code responsible live in WebDriverFacade.java:

    public void close() {
        if (proxyInstanciated()) {
        	//if there is only one window closing it means quitting the web driver
        	if (areWindowHandlesAllowed(getDriverInstance()) &&
                    getDriverInstance().getWindowHandles() != null && getDriverInstance().getWindowHandles().size() == 1){
        		this.quit();
        	} else{
        		getDriverInstance().close();
        	}
            webDriverFactory.shutdownFixtureServices();  //I think this should be moved above this.quit()
        }
    }  

Does Serenity have any other fixtures that would negatively impacted by this change?

**Comment by wakaleo** [comment]
I don't think so, the BrowserMobFixtureService is the only fixture that is provided with Serenity out of the box.

**Comment by hazmeister** [comment]
Looking at this a bit closer, I'm surprised that  `shutdownFixtureServices()` doesn't get called in `quit()`.

While I'm looking at the code, there's also a method called areWindowHandlesAllowed(), which seems to check if android driver is running.  I think Android driver now supports window handles.  Should I remove it in the same PR?

**Comment by wakaleo** [comment]
It could be a legacy from previous driver versions - if you can test on your side that it isn't necessary any more, feel free to remove it.

**Comment by hazmeister** [comment]
Nearly made the change, but I don't have an Android app I can run tests against, which could be an edge case.  Best left untouched until someone actually has an issue.
