### ISSUE TITLE
 Could not instantiate new WebDriver instance when sending the browserstack.build as a Integer (en.bs_caps.build_not_string)

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#806]
Looks like Browserstack doesn't like if we sent the 'build' capability as a int.

If we use `browserstack.build = 0` then browserstack returns:

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.remote.RemoteWebDriver (translation missing: en.bs_caps.build_not_string (WARNING: The server did not provide any stacktrace information)

From the docs I don't see any restrictions: https://www.browserstack.com/automate/capabilities#other-browserstack-capabilities

**Comment by bebef1987** [comment]
As a workaround we can use:
`browserstack.build = '0'` 

this sends the value as a string

**Comment by bebef1987** [comment]
@wakaleo  should I fix this or should we reach out to BrowserStack?

**Comment by wakaleo** [comment]
I'm not sure what the best way to handle this issue would be. Serenity tries to convert the capability values to typed objects, as expected by Chrome for example, so disabling the conversions would break the Chrome integration. Surrounding the text in quotes could be a good compromise. For example, if you provide something like:

    browserstack.build = "0"

Serenity could strip the quotes and pass a String value.

**Comment by bebef1987** [comment]
I was thinking of adding a exception for the `build` capability  to always be a string 

https://github.com/bebef1987/serenity-core/commit/dd41647a8dd3ef265fe72c5a10365c64f6901d5a

**Comment by ChrisD1990** [comment]
@wakaleo  hi i meet the issue, sometimes i run the tese case on selenium grid, but it will create new webdriver fail, and i don't know how to change. please help.

> **24240 [pool-1-thread-1] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.remote.RemoteWebDriver: Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver
> net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver
> 	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:192)
> 	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:88)
> 	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:82)
> 	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:54)
> 	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:123)
> 	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:118)
> 	at com.microfocus.cdf.suiteinstaller.ui.pages.SuiteInstallerLoginPage.openLoginPage(SuiteInstallerLoginPage.java:32)
> 	at com.microfocus.cdf.suites.demo.freshinstall.DemoSuiteUIFreshInstallSteps.openSuiteInstallerLoginPage(DemoSuiteUIFreshInstallSteps.java:68)
> 	at com.microfocus.cdf.suites.demo.freshinstall.DemoSuiteUIFreshInstallSteps$$EnhancerByCGLIB$$d9e164a.CGLIB$openSuiteInstallerLoginPage$4(<generated>)
> 	at com.microfocus.cdf.suites.demo.freshinstall.DemoSuiteUIFreshInstallSteps$$EnhancerByCGLIB$$d9e164a$$FastClassByCGLIB$$3bdddfe0.invoke(<generated>)
> 	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
> 	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:300)
> 	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:285)
> 	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:261)
> 	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:125)
> 	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:51)
> 	at com.microfocus.cdf.suites.demo.freshinstall.DemoSuiteUIFreshInstallSteps$$EnhancerByCGLIB$$d9e164a.openSuiteInstallerLoginPage(<generated>)
> 	at com.microfocus.cdf.suites.demo.freshinstall.CDFUIFreshInstallTest.openSuiteInstallerInBrowser(CDFUIFreshInstallTest.java:17)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
> 	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:535)
> 	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:515)
> 	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:479)
> 	at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:445)
> 	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:305)
> 	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
> 	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
> 	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:235)
> 	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:207)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
> Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
> System info: host: 'SELWIN7EN64', ip: '16.155.198.225', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_161'
> Driver info: driver.version: unknown
> Command duration or timeout: 20.21 seconds**

i check the selenium grid node and found the following log:

> 03:49:55.038 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
> 03:49:55.085 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started ne
> w session 8e7a873aac20d7ad81640d12ea0a9759 (org.openqa.selenium.chrome.ChromeDri
> verService)
> 03:51:19.049 INFO [ActiveSessions$1.onStop] - Removing session 8e7a873aac20d7ad8
> 1640d12ea0a9759 (org.openqa.selenium.chrome.ChromeDriverService)
> 03:51:28.799 INFO [OsProcess.destroy] - Unable to drain process streams. Ignorin
> g but the exception being swallowed follows.
> org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceed
> ed (Exit value: -559038737)
>         at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandle
> r.java:295)
>         at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java
> :181)
>         at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:135)
>         at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
>         at org.openqa.selenium.remote.service.DriverService.stop(DriverService.j
> ava:223)
>         at org.openqa.selenium.remote.server.ServicedSession.stop(ServicedSessio
> n.java:84)
>         at org.openqa.selenium.remote.server.ActiveSessions.lambda$new$1(ActiveS
> essions.java:55)
>         at com.google.common.cache.LocalCache.processPendingNotifications(LocalC
> ache.java:1811)
>         at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCa
> che.java:3463)
>         at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCach
> e.java:3439)
>         at com.google.common.cache.LocalCache$Segment.remove(LocalCache.java:307
> 3)
>         at com.google.common.cache.LocalCache.remove(LocalCache.java:4234)
>         at com.google.common.cache.LocalCache$LocalManualCache.invalidate(LocalC
> ache.java:4898)
>         at org.openqa.selenium.remote.server.ActiveSessions.invalidate(ActiveSes
> sions.java:102)
>         at org.openqa.selenium.remote.server.WebDriverServlet.handle(WebDriverSe
> rvlet.java:276)
>         at org.openqa.selenium.remote.server.WebDriverServlet.doDelete(WebDriver
> Servlet.java:145)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
>         at org.openqa.selenium.remote.server.WebDriverServlet.service(WebDriverS
> ervlet.java:126)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>         at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java
> :860)
>         at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.
> java:535)
>         at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandl
> er.java:143)
>         at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler
> .java:548)
>         at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWra
> pper.java:132)
>         at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedH
> andler.java:190)
>         at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextH
> andler.java:1253)
>         at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHa
> ndler.java:168)
>         at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.j
> ava:473)
>         at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHa
> ndler.java:166)
>         at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHa
> ndler.java:1155)
>         at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandl
> er.java:141)
>         at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWra
> pper.java:132)
>         at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
>         at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
> 
>         at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection
> .java:256)
>         at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(Ab
> stractConnection.java:279)
>         at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
> 
>         at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:1
> 24)
>         at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(E
> atWhatYouKill.java:247)
>         at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(Eat
> WhatYouKill.java:140)
>         at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhat
> YouKill.java:131)
>         at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThre
> ad.run(ReservedThreadExecutor.java:382)
>         at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThrea
> dPool.java:708)
>         at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThread
> Pool.java:626)
>         at java.lang.Thread.run(Unknown Source)
> 03:51:28.830 ERROR [OsProcess.destroy] - Unable to kill process java.lang.Proces
> sImpl@1e7b7761

**Comment by wakaleo** [comment]
Does this error happen every time?

**Comment by wakaleo** [comment]
Could be an issue with the Selenium Grid or network setup then.
