### ISSUE TITLE
Underscores in steps arguments are erased in the report

### ISSUE THREAD

**Issue by a-en** [serenity-bdd/serenity-core#807]
If we provide the string, which contains underscores, as a parameter to step ("this_is_test_value"), in the report all underscores will be erased and we'll get ("thisistestvalue").

Serenity version: 1.4.0

Example of this case it available [here](https://github.com/a-en/serenity-ignore-issue-example) -- as result for test3, I get "Search: serenitybddtext" instead of "Search: serenity_bdd_text"

**Comment by wakaleo** [comment]
The step titles are being rendered as markdown-enabled texts. You can fix this by adding the following to your serenity.properties

    enable.markdown = story,narrative,scenario

The default behaviour will be fixed in the next release.
