### ISSUE TITLE
[Question] Maven build SUCCESS even when there are some stories/scenarios that failed

### ISSUE THREAD

**Issue by v-oravec** [serenity-bdd/serenity-core#808]
Hi,

i'm using the Serenity + JBehave + Maven project setup. When i run my tests with mvn clean install verify command all Serenity tests are runned and report is properly generated(http://prntscr.com/fe6spn). The problem is when i have some tests failed as on image above maven returns Build SUCCESS and i would need it to be Build FAILURE.
After completion of tests in console i get info as if no tests were run at all:

```
Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories:
org.jbehave.core.embedder.PerformableTree$SomethingHappened@19fe16cc: java.lang.AssertionError: 
Expected: is "The order is not in expected state1"
     but: was "The order is not in expected state"
        at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:553)
        at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:238)
        at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:216)
        at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
        at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:177)
        ... 24 more
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 676.317 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO]
[INFO] --- maven-failsafe-plugin:2.20:verify (integration-test) @ appname ---
[INFO]
[INFO] --- serenity-maven-plugin:1.4.0:aggregate (serenity-reports) @ appname ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO]
[INFO] --- maven-failsafe-plugin:2.20:verify (verify) @ appname ---
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ appname ---
[INFO] Installing H:\
[INFO] Installing H:\
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ appname ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory H:\* \src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ appname ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ appname  ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 57 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ appname ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ appname ---
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO]
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ appname ---
[INFO]
[INFO] --- maven-failsafe-plugin:2.20:integration-test (integration-test) @ appname ---
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO]
[INFO] --- maven-failsafe-plugin:2.20:verify (integration-test) @ appname ---
[INFO]
[INFO] --- serenity-maven-plugin:1.4.0:aggregate (serenity-reports) @ appname  ---
[INFO]
[INFO] --- maven-failsafe-plugin:2.20:verify (verify) @ appname ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:56.401s
[INFO] Finished at: Wed May 31 12:37:16 CEST 2017
[INFO] Final Memory: 43M/657M
[INFO] ------------------------------------------------------------------------

```

This is the part from my pom.xml where i have configured maven and serenity:
[snippet-from-pom.txt](https://github.com/serenity-bdd/serenity-core/files/1041179/snippet-from-pom.txt)

And all my tests are runned with SerenityStory:
```
package serenity.serenity_runners;

import net.serenitybdd.jbehave.SerenityStory;
public class EmailExists extends SerenityStory {
}
```

Could it be that you might help me out with this?

Thanks in advance!

Best regards,
Vlado

**Comment by wakaleo** [comment]
You have in your pom file:

    <testFailureIgnore>true</testFailureIgnore>

This means that failures will be ignored. 

You can force the build to fail by calling the check goal after the report generation:

            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity-maven-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity-core.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by v-oravec** [comment]
I have removed the:
`<testFailureIgnore>true</testFailureIgnore>`

and added the "check" goal into serenity-maven-plugin. 

It appears that it is working properly now, the missing piece of the puzzle was <goal>check</goal> after report aggregation. 

Thank you very much for quick response and help. 

Feel free to close this one.

Best regards,
Vlado
