### ISSUE TITLE
Firefox 53 Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

### ISSUE THREAD

**Issue by tranvanthien** [serenity-bdd/serenity-core#811]
When i updated firefox to version 53. My automation tests don't work. And i tried to updated serenity version like below:
serenity-core: 1.4.1-rc.2
serenity-jbehave: 1.24.0
selenium-firefox-driver: 3.4.0

And it can open the browser and stop immediately, here is the error:

`net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:148)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:135)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:105)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:180)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:175)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:829)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:739)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:727)`

How to fix this problem?

**Comment by wakaleo** [comment]
Selenium 3.4.0 is not currently supported.

**Comment by tranvanthien** [comment]
How can i make serenity run on firefox 53 ?

**Comment by wakaleo** [comment]
Firefox 53 only works with geckodriver and Selenium 3.x, and will be supported in Serenity 1.5.0

**Comment by tranvanthien** [comment]
Thank you

**Comment by uzigula** [comment]
I have the same error but with these versions:
serenity-core: 1.6.3
serenity-jbehave: 1.30.0
selenium-firefox-driver: 3.5.3

firefox version 55
any idea

**Comment by wakaleo** [comment]
Have you checked your version of the geckodriver binary?

**Comment by djhair01jds** [comment]
I got the following error:

[main] ERROR net.serenitybdd.core.Serenity - Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

while running [sample code](https://github.com/serenity-bdd/tutorials) from [Serenity BDD - Tutorial 1](https://www.youtube.com/watch?v=o-6CcDFn5Ug&t=922s) 

I also made an attempt at using latest gecko driver, but got the following error message:

[main] ERROR net.serenitybdd.core.Serenity - Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 

I'm using:
Firefox 57.0.4
Selenium Firefox Driver 3.7.1?  2.53.0? 2.45.0? (and a few others, not sure which one)
Serenity Core 1.8.12
geckodriver 0.9.0 (win-64)

Any guidance for a newbie whose attempting to get examples working is appreciated. Thanks.

**Comment by wakaleo** [comment]
"Could not instantiate class" is pretty much always a driver compatibility issue or a driver bug. Looks like you have an old version of geckodriver, and several incompatible versions of selenium Firefox driver.

**Comment by manobigdata** [comment]
Even im getting the same error


23711 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'md-bdadev-190.verizon.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.21.2.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'md-bdadev-190.verizon.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.21.2.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver

Please suggest me

**Comment by olegaizin** [comment]
same error here:
[main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
[main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'DESKTOP-DEIDGMN', ip: '******', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'
Driver info: driver.version: FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'DESKTOP-DEIDGMN', ip: '******', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'
Driver info: driver.version: FirefoxDriver

**Comment by Hannalee1** [comment]
I also got the same error. I have been trying to search on the google all day the still get in stuck. Some one can help me please. I tried to run with chrome and it throws the same errors too. 

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
[ERROR]   Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- serenity-maven-plugin:2.0.67:aggregate (serenity-reports) @ IoT.Ielts ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/HP800g1/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] current_project.base.dir: D:\Automation\IoT\IoT.Ielts
[INFO] Generating test results for 2 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.PackageRequirementsTagProvider@cb1c58c, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@10a064bd]
[INFO] LOADED REQUIREMENTS:
REQUIREMENTS:
    - capability : Consult dictionary {id: Consult dictionary, displayName: 'Search for definitions', path: consult_dictionary, parent: 'null'}
        - feature : Lookup a definition {id: lookup-a-definition, displayName: 'Lookup a definition', path: consult_dictionary\LookupADefinition.feature, parent: 'Consult dictionary'}
    - capability : Update definition {id: Update definition, displayName: 'Update definition', path: update_definition, parent: 'null'}

**Comment by Muchapathi** [comment]
Hi There,
1.I am getting "net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver exception when trying to use Geckodriver.
I am using selenium-firefox-driver-3.14.0,Serenity-core-2.0.81
Can someone please help me this.
2.On executing a standalone java class with gecko driver - I am getting "The driver is not executable"
Can some one please let me know what exactly is the issue?
