### ISSUE TITLE
Serenity with jbehave and spring - spring context is not loaded

### ISSUE THREAD

**Issue by jongler** [serenity-bdd/serenity-core#813]
Hi,
I'm trying to use Serenity with jbehave and Spring but I am not able to initialize Spring.

Story file (demo_story.story):

Scenario: demo scenario
Given i want to buy

Definition file:

public class DemoStepsDefinition {
  
  @Given("i want to buy")
  public void wantToBuy() {
    System.out.println("**Given I want to buy");
  }
}

@ContextConfiguration(classes = TestAppConfig.class)
public class DemoStory extends SerenityStory {
}

Spring bean TestAppConfig.java:

@Configuration
public class TestAppConfig {

  public TestAppConfig() {
    System.out.println("*** in app config...");
  }
}

When i execute DemoStory  using Junit the test is been executed and finished successfully. But unfortunately Spring is not loaded and bean TestAppConfig is not initialized.

I've also tried with spring.xml instead of java config. Same result.

Am i missing something here?

Thanks in advance,
Jon

**Comment by wakaleo** [comment]
Hmmm, have you tried putting the @contextconfiguration on the step definition class?

**Comment by jongler** [comment]
Oh, now it works!
thanks a lot
