### ISSUE TITLE
Serenity with Jbehave - report shows binary characters

### ISSUE THREAD

**Issue by jongler** [serenity-bdd/serenity-core#814]
Hi,

My jbehave story file is formatted  like that:

Scenario: demo scenario
Given i want to buy the following:
[
{"property", "value"}
]

* The input is an example of a json array string which i then deserialize in my Given method to some Java object...

Test is successful but problem is that Serenity report shows the line break as gibberish. See attached file.

![serenity_report](https://cloud.githubusercontent.com/assets/29127509/26695513/d23828c0-4713-11e7-881c-da966e318a63.PNG)

Can it be fixed ?

Thanks,
Jon

**Comment by jongler** [comment]
Note: In the built in jbehave report it displays fine. They replace the binary char with <br/> so the json looks good.

**Comment by wakaleo** [comment]
could you provide a sample of the generated reports?

**Comment by jongler** [comment]
Sure

[serenity_report.zip](https://github.com/serenity-bdd/serenity-core/files/1048498/serenity_report.zip)

**Comment by wakaleo** [comment]
Should be fixed in 1.4.1-rc.4
