### ISSUE TITLE
Periodically I see this error in while executing tests.

### ISSUE THREAD

**Issue by livastar** [serenity-bdd/serenity-core#817]
No matter if this Swipe or Click methods.

[main] INFO net.serenitybdd.core.Serenity - STEP ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

**Comment by wakaleo** [comment]
That looks like a WebDriver error (javascript) being reported by Serenity - could be a WebDriver bug.

**Comment by wakaleo** [comment]
I'm going to close this for now as the evidence points to a WebDriver issue, not a Serenity one.
