### ISSUE TITLE
uniqueSession parameter on Managed Anotation isn't working.

### ISSUE THREAD

**Issue by Lucasgermani** [serenity-bdd/serenity-core#819]
Following the documentation:

```
You can also get Serenity to open the browser at the start of the tests, and leave it open until all of the tests in this test case have been executed, using the uniqueSession parameter:

@Managed(uniqueSession=true)
```

I tryed to implement a class to run some tests as this:

`@RunWith(SerenityRunner.class)
public class NavigationTest{

    @Managed(uniqueSession = true)
    public WebDriver webdriver;

    @Steps
    public NavigationStepImpl nav;

    @Steps
    public LoginStepImpl login;

    @Before
    public void setup()
    {
        login.fazerLoginComo("adm", "adm");
    }

    @Test
    public void nevagarAtePainelDeControle() throws FluigAutomationException {
        nav.acessaPainelDeControle();
    }

    @Test
    public void nevagarAteFavoritos() throws FluigAutomationException {
        nav.acessaComunidades();
    }
}`

I expected to see nevagarAtePainelDeControle and nevagarAteFavoritos running on the same browser, but it's actually running one test, closing the browser, opening other browser instance and running the second test.

**Comment by Lucasgermani** [comment]
It's a bug? Implementation error? Something should be done different?

**Comment by wakaleo** [comment]
Here is a simple test case illustrating the uniqueSession:
```
public class CompleteATodo {

    @Managed(driver="chrome", uniqueSession = true)
    WebDriver driver;

    @Steps   TodoUserSteps james;

    @Before
    public void setup()
    {
        james.starts_with_a_todo_list_containing("Walk the dog", "Put out the garbage");
    }

    @Test
    public void should_be_able_to_complete_a_todo() {

        james.completes("Walk the dog");

        james.should_see_that_that_following_item_is_marked_as_complete("Walk the dog");

    }

    @Test
    public void should_see_the_number_of_todos_decrease_when_an_item_is_completed() {

        james.completes("Walk the dog");

        james.should_see_that_the_number_of_items_left_is(1);
    }
}
```

Only one browser will be opened and both tests will be run in the same browser. There will be a new http session for each test. I've checked this will chrome and Firefox on 1.5.0-rc.1; please reopen if you continue to have any issues.
