### ISSUE TITLE
Alternative to JUnit's @BeforeClass and @AfterClass using Serenity

### ISSUE THREAD

**Issue by IgorJoin** [serenity-bdd/serenity-core#822]
I've read somewhere here that your @steps and your @managed webdriver won't work (don't get instantiated)  in a @BeforeClass \ @AfterClass method because apparently Serenity only handles test life-cycle, not test class\suite life-cycle.  While I still can't believe this limitation of Serenity (and yet hoping this is not true), is there another approach to manage objects before \ after a test class run, **using** Serenity?

**Comment by wakaleo** [comment]
This is not a limitation of Serenity, it's just the way the JUnit lifecycle works. In @BeforeClass and @AfterClass methods, no test object has been created, hence no driver can have been initialised. The best strategy depends on what you are managing, but a hand-rolled thread-local object with lazy loading works well for many cases.

**Comment by wakaleo** [comment]
(Closing because this is a question not an issue - questions go on stackoverflow with the #serenitybdd tag).
