### ISSUE TITLE
Incorrect tags filter

### ISSUE THREAD

**Issue by ghost** [serenity-bdd/serenity-core#823]
I use _tag1, tag2_ and _tag3_ in Serenity project
When I try run tests with _tag1_ only, started tests with _tag1_ and _tag2_
Annotation example with tag:
`@WithTag("tag1")`

**Comment by wakaleo** [comment]
Which version of Serenity are you using?

**Comment by wakaleo** [comment]
How are you specifying the tags?

**Comment by beardpony** [comment]
`mvn ... -Dtags=$tag verify`

**Comment by wakaleo** [comment]
`mvn verify -Dtags=tag1` should work fine. Could you show the tag annotation for the test that is running when it shouldn't be?

**Comment by beardpony** [comment]
```
@WithTag("tag2")
@RunWith(SerenityParameterizedRunner.class)
@Story(Application.TestClass.class)
public class TestClass {
    //
}
```

**Comment by wakaleo** [comment]
I can only guess that the tags aren't being passed into the JUnit process, or they are being overridden along the way (maybe in the pom.xml file). The setup you are describing should work fine.

**Comment by wakaleo** [comment]
This is most likely a Mavan configuration issue. Can you provide a sample project?

**Comment by SergheiRidico** [comment]
When I enter in terminal:  `mvn clean test -Dtags="smoke" -Dtags="production"`
Maven runs all the tests with **producton** tag.
@wakaleo How to run tests that have both tags: "smoke" and "production"?

**Comment by wakaleo** [comment]
have you tried -Dtags="smoke, production"?

**Comment by SergheiRidico** [comment]
@wakaleo, yes, I tried, but command:
 `-Dtags="smoke, production"` runs all test that have `smoke` **OR** `production` tags.
I search for possibility to run all test that have `smoke` **AND** `production` tags.

**Comment by wakaleo** [comment]
AND constructs (or other logical constructs) aren't currently supported with JUnit.
