### ISSUE TITLE
Serenity 1.4.1-rc.6 keeps browser opened but restarts session for each @test

### ISSUE THREAD

**Issue by IgorJoin** [serenity-bdd/serenity-core#824]
Hello,

I'm using Serenity with JUnit.

I'm using a default webdriver (Firefox) with uniqueSession = true.  For each @Test in my test class, Serenity resets the browser session even keeping the browser opened. Shouldn't it keep the session for the entire test class execution?

**Comment by wakaleo** [comment]
Duplicate of #819
