### ISSUE TITLE
cucumber gradle parallel execution

### ISSUE THREAD

**Issue by nabsofken** [serenity-bdd/serenity-core#825]
Is it possible to execute the same test on different browsers in parallel. I am currently using CucumberWithSerenity runner and gradle. I tried using maxParallelForks but this runs separate tests in the same browser. Any suggestions?

**Comment by wakaleo** [comment]
This is a question and so would be better placed on StackOverflow with the #serenitybdd tag. 

Cucumber does not support running features in parallel, though you can configure separate runner classes and run these in parallel.
