### ISSUE TITLE
Applitools support

### ISSUE THREAD

**Issue by kilimandzsaro** [serenity-bdd/serenity-core#826]
Hi,

I just want to ask if there is any plan to support applitools? Applitools requires some extra lines in the "build-in" classes and I wanted to know if there is any plan or preparation to support it.

Thanks,
Natalia

**Comment by wakaleo** [comment]
I'm not familiar with Applitools, but I'd be happy to consider a Pull Request if you know what code needs to be added.

**Comment by kilimandzsaro** [comment]
Ok, thanks for the response, I'll look at it.
