### ISSUE TITLE
Underscore should not be considered if appears in the middle of the word

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#827]
I noticed that formatting in step names is not correct. I also created a sample [project](https://github.com/dsmt/serenity-sample-api) to reproduce it. 

```
    @Step(value = "--> _This_ <-- should be formatted in italics")
    public void stepWithItalicsInName() {
    }

    @Step(value = "While --> th_is and th_is <-- should not")
    public void stepWitoutItalicsInName() {
    }
```

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/sdddHCJHlguPH1fF0Io86IyWFrxmli/Formatting%2Bin%2Bstep%2Bname%2Bexample%2B2017-06-20%2B12-26-26.png?Expires=1498037196&Signature=S3TG17aVhgSEQm8GlxZapo4MNFx-k5Rb7IPKSrHIcbSGbDCQQA9B0id5vXDxyuiEJp3v3e73Sh0tjmU14-t~F9NFOZeUR50Cm5pCen4gVzHVYmnJ9IkufYKxuyZGSGh2b8z6dwuKZQjZKDvs4nVu3oiO5Zw4ZxzB-dgcERL9hTXFqtSBkrH~XBr2yoGZVY~vVrCXQVhVNqFnZF7FpMyBOM8iiRZYNXb1cB8dqRsbg4k4lRwE57pgwA~v~jsjeDPcKftoe7P8ZGY~IAA97Yn0f8JlCIzcUboY8UKR7I2sZfhlhbVktBkV8jC8xxYkIVYyzIVAn~imugKPeZAVrArm-g__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by wakaleo** [comment]
The formatting used here is simple markdown, so anything between underscores will be formatted in italics. Markdown doesn't care about word delimitations.

**Comment by dsmt** [comment]
@wakaleo is it possible to disable `markdown`?

**Comment by wakaleo** [comment]
You can set the `enable.markdown` to a comma-separated list of values from story, narrative and step. To disable for steps, you could do

```
enable.markdown=story,narrative
```

**Comment by dsmt** [comment]
Thanks
