### ISSUE TITLE
Adding custom text for steps in Reports

### ISSUE THREAD

**Issue by atulkumar93** [serenity-bdd/serenity-core#828]
Is it possible to add some custom text to the steps in serenity reports even if the step passed?

For Ex: I have a step where I am matching some UI values with DB data and I want to show some custom text that both the values are matching correctly even when test passes.
Thanks!

**Comment by Invictum** [comment]
@atulkumar93
Serenity verboses all parameters passed to step methods. So you can just construct desired string and pass its to empty step method.

**Comment by wakaleo** [comment]
@Invictum's answer is the best way to do this currently. However, your comment implies that your automated tests require manual checks, which is generally not a good habit. Maybe you are looking for soft assertions?

**Comment by nouag** [comment]
I'm using sql queries in my GIVEN steps, how can I print these queries in my serenity report ?
Thanks

**Comment by wakaleo** [comment]
That's not really supported at the moment.

**Comment by nouag** [comment]
@wakaleo thanks for your reply, but is there any way to print custom data in serenity report ? i'm using cucumber

**Comment by wakaleo** [comment]
You can print custom data by passing a string to a @Step method.

**Comment by Prasannajnaeyulu** [comment]
I think its ideal to have some class from serenity core library which could allow the user to write some text into the reports. I am bit surprised for not having such solution. Having custom @step method forcing the user to use the step in cucumber scenario as well though this step doesn't be part of behavior. I mean, If I want to include version of the Application Under Test, URL or Name of the application etc... right now I have no option to do this.

**Comment by wakaleo** [comment]
Happy to consider pull requests.

**Comment by Shanmnugasundaram** [comment]
@wakaleo is there any pull requests created for this?

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/theserenitybook/latest/living-documentation.html#_adding_additional_evidence
