### ISSUE TITLE
Extract serenity DSL's to a new library

### ISSUE THREAD

**Issue by halfo** [serenity-bdd/serenity-core#831]
Hi there. I really like the DSL serenity provides for screenplay pattern and want to introduce in ourprojects. I believe many others do so too. Serenity comes with lots of other things which I'm not really looking for. Maybe it would have been nice if we could have a simple library which only provides the DSL that we can drop into our existing project and play around with and not have to worry about changing other things. So that we can justify if it really works for us or not. I believe this will make more people to try out this awesome project. Cheers!

P.S. Though I'm still learning about these, I can help out if any help is required.

**Comment by wakaleo** [comment]
We have considered this, but it is really too much work for too little added value. If you want to just use the Screenplay logic, then just import serenity-screenplay.

**Comment by halfo** [comment]
Ah, is it possible? I thought there are some DI stuffs going on and even if I manage to use it, at some point I can get blocked. Also without serenity-screenplay-webdriver, it wouldn't add much value. I tried to port serenity-js in java, which looked really minimal and achievable at first, but now not so much.

**Comment by wakaleo** [comment]
Yes, you need to instrument the classes to benefit from the Serenity reporting. As I said, we've considered extracting it into a separate module, but it is a lot of work if you want to keep the reporting and other benefits you get from Serenity. Much easier just to use the existing code.

**Comment by halfo** [comment]
Ah, I was trying to avoid the reporting (don't want to mess with the current reporting system, even though serenity's one is much better!!). Without instrumenting, will they (serenity-screenplay and serenity-screenplay-webdriver) work? If it does (with minimal or no effort), it would be great!

**Comment by wakaleo** [comment]
I'm not sure what you are trying to achieve?

**Comment by halfo** [comment]
Ah sorry~

A library, that I can drop into an existing project. It will provide the common DSL, Abilities, Interactions etc. serenity framework provides. It will not effect the existing system like the way tests are executed or reporting, will act kind of a helper or util library. The benefit is that, we don't need to worry about anything changing. Every existing utility, reporting, test execution strategy will work the same way. If we like the library, we can keep using it. If we think it is not working for us, we can stop using it and go back to our old way.

**Comment by wakaleo** [comment]
If you want to experiment with the Screenplay pattern without any of the Serenity features, just implement the key classes yourself - it's not very complicated code.
