### ISSUE TITLE
Unable to catch net.thucydides.core.webdriver.exceptions.ElementShouldBeEnabledException

### ISSUE THREAD

**Issue by sudheerpujar** [serenity-bdd/serenity-core#833]
I am trying catch this exception , I am unable to do so. 
Any reason ?

**Comment by wakaleo** [comment]
It's just an exception, so you should be able to catch it, unless it has already been wrapped in a Serenity exception (which happens in some places). What problem are you trying to solve?

**Comment by sudheerpujar** [comment]
Thanks John for quick reply. 
I am using serenity to automate a process instead of test automation.  
I have a series of  use cases under a single process.  if a use case fails then I want to execute next use case.  

Following is sample a code as I can't post actual code

```
package com.foo;

import com.foo.usecases.UseCase1Steps;
import com.foo.usecases.UseCase2Steps;
import net.thucydides.core.annotations.Managed;
import net.thucydides.core.annotations.Steps;

@RunWith(SerenityParameterizedRunner.class)
public class ProcessClass  {
   
    @Managed(uniqueSession = true)
    public WebDriver webdriver;

   // Both UseCase1Steps  and UseCase2Steps  extend net.thucydides.core.steps.ScenarioSteps
   // which intern call methods from instance of  net.thucydides.core.pages.PageObject

   @Steps
    UseCase1Steps useCase1Steps;  
   
   @Steps
    UseCase2Steps useCase1Steps;

   @Test
   public void processMethod() {
      boolean isUseCase1Success =false;
      boolean isUseCase2Success =false;
     
       //Use Case 1
       try {
        useCase1Steps.step1(); 
        useCase1Steps.step2();
        isUseCase1Success=true;
       }catch( Throwable e){
        // do nothing
       }
      
       System.out.println("State of Use Case 1 : " + isUseCase1Success );

       //Use Case 2
       try {
        useCase2Steps.step1();
        useCase2Steps.step2();
        isUseCase2Success=true;
       }catch( Throwable e){
         // do nothing
       }

       System.out.println("State of Use Case 2 : " + isUseCase2Success );

   }
}
```


I am invoking this 
  ```
JUnitCore engine = new JUnitCore();
   engine.run( Class.forName(com.foo.ProcessClass));

```

If there is failure in  **Use Case 1** it is not reaching  **Use Case 2**
Instead following exception is thrown
`net.thucydides.core.webdriver.exceptions.ElementShouldBeEnabledException: Expected enabled element was not enabled`

**Comment by sudheerpujar** [comment]
Hi John
Please let me know if you have any updates on this.

**Comment by wakaleo** [comment]
You may need to catch the exception explicitly.

As a general rule, chaining use cases like this is not a great practice, as it becomes hard to maintain. If an exception is thrown, it may mean that the process cannot continue. Ignoring the thrown exception means that any genuine errors will not be reported, which will make troubleshooting harder. I prefer to try to structure my tests to set them up in. particular state, then perform the action under test, rather than relying on a chain of actions to test many scenarios.

**Comment by sudheerpujar** [comment]
Thank you for your suggestion
