### ISSUE TITLE
Gradle loaded serenity libs to project but can't see them at runtime

### ISSUE THREAD

**Issue by robinbobin25** [serenity-bdd/serenity-core#835]
I have this build.gradle for my project in intellij idea. I have copied that from instructions here http://thucydides.info/docs/serenity-staging/

```
group 'com.serenity.ui'
version '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    jcenter()
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.4.0")
    }
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'

dependencies {
    testCompile('net.serenity-bdd:serenity-core:1.4.0')
    testCompile('net.serenity-bdd:serenity-junit:1.4.0')
    testCompile('junit:junit:4.12')
    testCompile('org.assertj:assertj-core:1.7.0')
    testCompile('org.slf4j:slf4j-simple:1.7.7')
}
gradle.startParameter.continueOnFailure = true
```

then I created some mock tests in test module test/java/TestLoginPage.java

When I run tests by gradle command `gradle clean test aggregate` I have some error in logs as:
![screenshot_2](https://user-images.githubusercontent.com/11983594/27918641-405ae39a-6278-11e7-81cf-ec068523f058.png)

So that gradle can't see serenity libs when run tests but they do exist in External libraries
![screenshot_3](https://user-images.githubusercontent.com/11983594/27919148-923075e4-6279-11e7-813e-61f347bf86be.png)

Also in test class Steps annotation can be imported only manually like this:
![screenshot_4](https://user-images.githubusercontent.com/11983594/27919284-eb28656c-6279-11e7-8662-4c33329a099b.png)
It is not imported by itsself only if I directly type its import-path.
![screenshot_7](https://user-images.githubusercontent.com/11983594/27922300-3bb20886-6283-11e7-9e1c-ab2aada78c41.png)

So i think something wrong with build.gradle structure because libraries are not imported correctly. Maybe I should add serenity libs to classpath in some way... Could you please help me ? 

Project structure is here
![screenshot_5](https://user-images.githubusercontent.com/11983594/27919372-2effb466-627a-11e7-8c70-6682f454985c.png)

**Comment by wakaleo** [comment]
Your page objects are under src/main/java, so your dependencies need to be compile scope rather than testCompile scope

**Comment by robinbobin25** [comment]
works! thank you very much for the help.
