### ISSUE TITLE
How to increase screen resolution in saucelabs using Serenity

### ISSUE THREAD

**Issue by Jcigniti** [serenity-bdd/serenity-core#838]
Hello,
I am running selenium automated tests in Saucelabs(I use Serenity and Jbehave). I am trying to increase window size as my application is opening in mobile mode when the size is less. Saucelabs suggested that the maximum window size is 1040x784 and asked me to try increasing screen resolution. I tried below commands in my config properties file which is not working. Could you please suggest the command to increase the screen resolution.

saucelabs.browser.screenResolution=1280x768
saucelabs.chrome.screenResolution=1280x768
saucelabs.driver.screenResolution=1280x768
saucelabs.screenResolution=1280x768
saucelabs.resolution=1280x768
saucelabs.screen.resolution=1280x768

Thanks,
Jyothsna

**Comment by wakaleo** [comment]
Serenity will pass any property prefixed with "saucelabs." into the WebDriver capabilities. According to https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-SpecifyingtheScreenResolution, `saucelabs.screenResolution=1280x1024` should do the trick.

**Comment by wakaleo** [comment]
Please reopen if this doesn't work for you.
