### ISSUE TITLE
net.serenity-bdd:serenity-jbehave-archetype has pom.xml which excludes AcceptanceTestSuite.java

### ISSUE THREAD

**Issue by SreeCharanShroff** [serenity-bdd/serenity-core#84]
1. Do:
mvn archetype:generate -Dfilter=net.serenity-bdd:serenity-jbehave-archetype
fill all details
2. mvn clean verify

Expected:
Tests are executed

Actuals:
No tests are executed

generated pom.xml has:
<includes>
                        <include>**/*Test.java</include>
                        <include>**/Test*.java</include>
                        <include>**/When*.java</include>
                    </includes>

correct pom.xml to execute tests:
<includes>
                        <include>**/*Test*.java</include>
                        <include>**/When*.java</include>
                    </includes>

**Comment by cliviu** [comment]
hi @SreeCharanShroff . I'm not sure with which version have you tried, but with serenity-jbehave-archetype version 1.1.7,  in pom.xml, the following are included: 
```xml
 <includes>
       <include>**/*Test.java</include>
       <include>**/*TestSuite.java</include>
       <include>**/Test*.java</include>
       <include>**/When*.java</include>
  </includes>
```
and the tests are running .

**Comment by YamStranger** [comment]
Hello @SreeCharanShroff! Please check @cliviu message. And close this issue if it fixed.

Thanks a lot!
