### ISSUE TITLE
How can I run serenity tests on Saucelabs for mobile automation

### ISSUE THREAD

**Issue by randheerrai** [serenity-bdd/serenity-core#840]
Hi,
I can successfully run serenity tests on Suacelabs for various browser, but how can I run same test on mobile platforms provided by saucelabs.

**Comment by wakaleo** [comment]
This is more a question for StackOverflow (tag #serenitybdd) than an issue. Any property suffixed with "saucelabs." will be passed to Saucelabs. Refer to the Saucelabs documentation (https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options) and provide the properties for the platform you want.

**Comment by randheerrai** [comment]
Hi John,
thanks for Replying. I have already gone through that document in saucelabs thats how i was able to rune serenity tests on different browsers. This is different as I want to run same tests on saucelabs on mobile emulators. 
In Serenity BDD documentation you have covered how to run on appium locally, but i could not find if same can be run on remote / saucelabs

**Comment by wakaleo** [comment]
Your best bet would be to ask on the Serenity Google Groups; several users there have done this sort of thing.
