### ISSUE TITLE
Wrong check on remote host is available

### ISSUE THREAD

**Issue by dip56** [serenity-bdd/serenity-core#841]
Hello John,

serenity-core version: 1.5.0-rc.4

I think this is wrong check because remote hub responds only by 4444 port, and other ports are restricted (include ICMP protocol). Could you try some check like GET ${remoteUrl} and wait for response status 200 for example?

```
    private void ensureHostIsAvailableAt(URL remoteUrl) throws UnknownHostException {
        try {
            if (!InetAddress.getByName(remoteUrl.getHost()).isReachable(WITHIN_THREE_SECONDS)) {
                theRemoteServerIsUnavailable(remoteUrl.getHost() + " could not be reached");
            }
        } catch (IOException e) {
            theRemoteServerIsUnavailable(e.getMessage());
        }
    }
```
https://github.com/serenity-bdd/serenity-core/blame/1522b0bcb401aa3c96a0ebb786c990113c535275/serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/RemoteDriverBuilder.java#L55

**Comment by wakaleo** [comment]
Thank you, well spotted.
