### ISSUE TITLE
Empty report afterupdating 

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#843]
I get an empty report after updating to:
 serenity-core - 1.5.1
 serenity-maven-plugin - 1.5.0-rc.1

@wakaleo  I see you are working on this but thought this might help 

```
[INFO]
[INFO] --- serenity-maven-plugin:1.5.0-rc.1:aggregate (serenity-reports) @ GDPR-tests ---
[INFO] webdriver.driver=chrome
[INFO] serenity.data.dir=src/test/resources/testData/
[INFO] serenity.issue.tracker.url=https://itjira.garmin.com/browse/{0}
[INFO] serenity.report.show.releases=false
[INFO] serenity.test.root=com.garmin.gdpr.tests
[INFO] serenity.reports.show.step.details=true
[INFO] serenity.verbose.steps=true
[INFO] serenity.console.headings=normal
[INFO] serenity.report.show.manual.tests=false
[INFO] webdriver.base.url=https://www.dev.garmin.com/
[INFO] serenity.project.name=GDPR Selenium Tests
[INFO] webdriver.wait.for.timeout=10000
[INFO] serenity.native.events=true
[INFO] json.pretty.printing=true
[INFO] webdriver.timeouts.implicitlywait=10000
[INFO] current_project.base.dir: D:\web_ser_try\gdpr-selenium
[WARNING] This file was not a valid JSON Serenity test report: 09263284c2288a270d0af42fd131808930f582062e32bc5f727d75f7647021e6.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:49.596+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: 3cc54fa0087296c252c72e89407e33b1c1e9f472af4b99ecb04d41039d8638be.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:27.414+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: 7c086f735d75a50a8f8c3ba58e968a1d8726bb64d475744ac4af3f3b95b6558e.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:27.158+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: c0f03974d53a256dc830c734eb9540f6aa1040cc8bbf99ff09cc36757dd617e5.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:59.123+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: 5efdfd9312a29e3c029afec1080eaf1837d0056fae1645f1df0cb4950ab1b55b.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:29:00.222+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: 18a06ecd9f53cab69f9c1a7edb3cb26dc61ea895ce8d979036f89dfdef8b802e.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:39.385+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: be809a897ecce80664505cd1dd8cd83986ebc70936286877999bfa3450649ddb.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:45.642+03:00[Europe/Athens]"
[INFO] Generating test results for 0 tests
[INFO] 2 requirements loaded after 215 ms
[INFO] 2 related requirements found after 215 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 230 ms
[INFO] Configured report threads: 40
[INFO] Test results for 0 tests generated in 774 ms
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Automated tests for GDPR using Selenium and Java 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- serenity-maven-plugin:1.5.0-rc.1:aggregate (default-cli) @ GDPR-tests ---
[INFO] current_project.base.dir: D:\web_ser_try\gdpr-selenium
[WARNING] This file was not a valid JSON Serenity test report: 3cc54fa0087296c252c72e89407e33b1c1e9f472af4b99ecb04d41039d8638be.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:27.414+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: 5efdfd9312a29e3c029afec1080eaf1837d0056fae1645f1df0cb4950ab1b55b.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:29:00.222+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: 09263284c2288a270d0af42fd131808930f582062e32bc5f727d75f7647021e6.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:49.596+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: 7c086f735d75a50a8f8c3ba58e968a1d8726bb64d475744ac4af3f3b95b6558e.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:27.158+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: c0f03974d53a256dc830c734eb9540f6aa1040cc8bbf99ff09cc36757dd617e5.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:59.123+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: be809a897ecce80664505cd1dd8cd83986ebc70936286877999bfa3450649ddb.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:45.642+03:00[Europe/Athens]"
[WARNING] This file was not a valid JSON Serenity test report: 18a06ecd9f53cab69f9c1a7edb3cb26dc61ea895ce8d979036f89dfdef8b802e.json
java.lang.NumberFormatException: For input string: "2017-07-18T15:28:39.385+03:00[Europe/Athens]"
[INFO] Generating test results for 0 tests
[INFO] 2 requirements loaded after 1 ms
[INFO] 2 related requirements found after 2 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 2 ms
[INFO] Configured report threads: 40
[INFO] Test results for 0 tests generated in 64 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 58.622 s
[INFO] Finished at: 2017-07-18T15:29:21+03:00
[INFO] Final Memory: 38M/487M
[INFO] ------------------------------------------------------------------------
```

**Comment by wakaleo** [comment]
Could you provide a sample project and the target directory? Looks like a Locale issue of some kind

**Comment by wakaleo** [comment]
Could you also try with serenity-maven-plugin 1.5.1 (https://bintray.com/serenity/maven/serenity-maven-plugin)

**Comment by bebef1987** [comment]
https://gist.github.com/bebef1987/857db70ae6172c8decf083394a9df936

**Comment by bebef1987** [comment]
Tested with  serenity-maven-plugin 1.5.1 and all looks good

The report was generated as exepcted

**Comment by wakaleo** [comment]
Thanks for the update; the maven and core versions need to be the same.

**Comment by andriyyarish** [comment]
@wakaleo I am getting the same issue for
serenity.core.version 1.5.3
serenity.maven.plugin.version 1.5.3

[WARNING] This file was not a valid JSON Serenity test report: 84bda9a2c5df9674e10c931446f38501204e1dd0bdf762addf8195832ed4494c.json
java.lang.NumberFormatException: For input string: "2017-09-15T11:11:13.037+03:00[Europe/Helsinki]"

As a result, site/serenity contsins only screenshots, jsons, and corrupted index.html. All folders with style resources are missed.

Maybe it is related to locale configuration  on my machine ("2017-09-15T11:11:13.037+03:00[Europe/Helsinki]") ?

**Comment by wakaleo** [comment]
Could you try with the latest version (1.5.10) and, if the problem persists, provide a sample project that reproduces the issue?

**Comment by andriyyarish** [comment]
The same issue with 1.5.10 (for maven plugin and core).  It will be hard with project sample as it is huge. We are trying to upgrade from 1.1.36.

**Comment by wakaleo** [comment]
If it's an encoding issue (which is possible), a sample project could be as simple as the test mentioned above (with maybe a couple of others for completeness), but with empty step methods. If you are getting screenshots, the WebDriver interaction most likely isn't the problem.

**Comment by PashminaT** [comment]
Hi all,
            I am fairly new to Serenity/BDD automation. How ever I have managed to create a simple project following information from various sources. Aggregate report generated has empty 'Overall results tab'. At the moment I am running it by clicking on maven job on my machine.
![maven](https://user-images.githubusercontent.com/34449680/33836204-a8fc70ce-de80-11e7-9b23-14f877d0da71.PNG)


 I can't understand why I am getting 'Generating test results for 0 test' 

"C:\Program Files\Java\jdk1.8.0_65\bin\java" -Dmaven.multiModuleProjectDirectory=C:\Users\Pashmina.Tiwari\serenity-bdd-test-master-sprintReview "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2017.2.5\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2017.2.5\plugins\maven\lib\maven3\bin\m2.conf" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2017.2.5\lib\idea_rt.jar=65525:C:\Program Files\JetBrains\IntelliJ IDEA 2017.2.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2017.2.5\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2017.2.6 net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.8.5:aggregate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Sample Serenity project using Cucumber and WebDriver 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- serenity-maven-plugin:1.8.5:aggregate (default-cli) @ todo-demo ---
[INFO] current_project.base.dir: C:\Users\Pashmina.Tiwari\serenity-bdd-test-master-sprintReview
[INFO] Generating test results for 0 tests
[INFO] 3 requirements loaded after 250 ms
[INFO] 3 related requirements found after 251 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 284 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 1326 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.367 s
[INFO] Finished at: 2017-12-11T14:26:23+00:00
[INFO] Final Memory: 16M/227M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0

**pom file** I have used is same for:  https://github.com/serenity-bdd/screenplay-pattern-todomvc
with versions updated
 <serenity.version>1.8.5</serenity.version>
        <serenity.maven.version>1.8.5</serenity.maven.version>
        <serenity.cucumber.version>1.6.5</serenity.cucumber.version>

**Cucumber runner class:** 
package features;
import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

/**
 * @author Pashmina Tiwari
 */

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    plugin={"pretty","html:target/cucumber-html-report"},
    features="src/test/resources/features"

)
public class RecordTodos
{
}
Tests run successfully. Any help will be much appreciated.

**Comment by wakaleo** [comment]
According to the Serenity reports, it doesn't find any test results. Are you sure the tests are being executed successfully (or at all)?

**Comment by PashminaT** [comment]
Hi Wakaleo, yes all the test run fine.

![image](https://user-images.githubusercontent.com/34449680/33838563-c576432c-de87-11e7-9812-112a9ec37168.png)

**Comment by PashminaT** [comment]
All sorted. I had an invalid location in serenity.property file. Thanks for your help.

**Comment by oleksandrkol** [comment]
Hi, I use latest versions of Serenity, but also have issue with reports.
Dependencies in Gradle:

compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.8.20'
compile group: 'net.serenity-bdd', name: 'serenity-report-resources', version: '1.8.20'
compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.8.20'
compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '1.8.20'

5:21:58 PM: Executing task 'aggregate'...
This file was not a valid JSON Serenity test report: 0565107ef2bcbb246e4e6a29d8bcbcc407e3aa7a002fc81cdc7ee8fd07e0e7d4.json
java.lang.NumberFormatException: For input string: "2018-01-09T16:38:20.646+02:00[Europe/Helsinki]"

**Comment by lilyhoang** [comment]
Any other solution for this issue, My report is empty 
my properties
<serenity.version>1.7.0</serenity.version>
<serenity.cucumber.version>1.6.3</serenity.cucumber.version>
<webdriver.driver>firefox</webdriver.driver>

And serenty-core and serenity-maven-plugin are the same version = 1.7.0
pls help
![image](https://user-images.githubusercontent.com/20644391/42613540-a040cd2a-85cb-11e8-95e5-79f76997cf4f.png)

**Comment by wakaleo** [comment]
@lilyhoang did the reports stop generating after an update, or have they never generated?

**Comment by lilyhoang** [comment]
Thanks @wakaleo , yes it was stop generating after I update feature file, Im not sure why, when I clean this, It generate again. Now It's ok. Thankis for your replying. 

But I got other issue with report in Jenkins. I have used HTML instead of Thucydides Test Report.
Thucydides Test Report was not show the report on Jenkins when script was fail. In local slave , it's still generated.
It's seam to not copy the local report to Jenkins server when script is fail (I mean when I had some scenarios Pass, and some scenarios was fail )

Do you have any suggestion ?
