### ISSUE TITLE
No screenshots are captured by serenity after test run

### ISSUE THREAD

**Issue by robinbobin25** [serenity-bdd/serenity-core#844]
I have serenity.properties file with such configurations:
```
serenity.take.screenshots = BEFORE_AND_AFTER_EACH_STEP
webdriver.driver = "chrome"
```

Also I have PageObjects, Steps layer and Tests module

My Gradle build file looks like:
```
group 'com.am'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.4.0")
    }
}

dependencies {
    compile 'net.serenity-bdd:serenity-core:1.4.0'
    compile 'net.serenity-bdd:serenity-junit:1.4.0'
    compile 'junit:junit:4.12'
    compile 'org.assertj:assertj-core:1.7.0'
    compile 'org.slf4j:slf4j-simple:1.7.7'
    compile group: 'net.serenity-bdd', name: 'serenity-rest-assured', version: '1.4.0'
    compile group: 'org.jsoup', name: 'jsoup', version: '1.8.3'
    compile 'ru.yandex.qatools.htmlelements:htmlelements-all:1.17'
}

gradle.startParameter.continueOnFailure = true
```

I run tests with simple command
`gradle clean test aggregate`

Report is generated but without any screenshots.

My report looks like (there is no screenshots in it):
![screenshot_2](https://user-images.githubusercontent.com/11983594/28324607-80a08098-6be4-11e7-8496-d5f8520a0b2b.png)

Could anybody please give an advice where I am wrong? I think it's some simple trick but I can't understand which is... In all manuals it says that serenity makes screenshots by default but I don't have any with or without serenity properties.

**Comment by wakaleo** [comment]
This looks like normal behaviour - the test fails on the first step, so no screenshots are taken on subsequent steps. Do you have an example of a passing test where no screenshots are taken?

**Comment by robinbobin25** [comment]
Sure
it was a bad example, sorry

![screenshot_4](https://user-images.githubusercontent.com/11983594/28325260-037b69d2-6be6-11e7-81d9-1aa3f784e386.png)

**Comment by wakaleo** [comment]
Could you try with version 1.5.2?

**Comment by robinbobin25** [comment]
Yep, i've just tried and still no screenshots when I run with 'gradle clean test aggregate', furthermore when I run my test with junit - I have some new exceptions:
[logs.txt](https://github.com/serenity-bdd/serenity-core/files/1156405/logs.txt)

I updated version to 1.5.2 in all serenity dependencies:
![screenshot_6](https://user-images.githubusercontent.com/11983594/28326138-9a815574-6be8-11e7-8658-f29522d89551.png)

**Comment by wakaleo** [comment]
That's a dependency conflict. Try using the latest version of assertj as well (3.6.2) (there will be some package changes)

**Comment by wakaleo** [comment]
Also, have you made sure your chromedriver version is up to date?

**Comment by robinbobin25** [comment]
Chromedriver version is the last one - 2.30
I've fixed dependency issue.
Still the same with reports :(
Tell me if you need some more information about my framework, please.

**Comment by wakaleo** [comment]
What do you mean "I created test framework without story files. Scenarios are read from test classes at once"?

**Comment by robinbobin25** [comment]
My point was that I created tests like here
![screenshot_3](https://user-images.githubusercontent.com/11983594/28328400-231c1dfa-6bef-11e7-903b-f0f59ab90717.png)
And run this class with gradle or junit and that's all. No .story files with given/when/then e.g.

**Comment by wakaleo** [comment]
OK. I'm not sure what is going on here. Can you provide a sample project that reproduces the issue?

**Comment by robinbobin25** [comment]
Here it is. I created a sample with the same configurations. Issue is still reproduced.
https://github.com/robinbobin25/sample_serenity

**Comment by wakaleo** [comment]
You are generating your own driver instance in the BrowserFactory class. To get screenshots, you need to let Serenity handle the driver lifecycles.

**Comment by kwbhatti** [comment]
@wakaleo I had been having similar issues and I keep reading let Serenity handle driver lifecycles. Can you please provide some code for this which shows you calling the driver. I had a cucumber project and I decided to add serenity BDD for reports and screenshots. Unfortunately I cannot share my project. FYI.. I have looked into most of the samples that are there but they are nothing compared to what I am working with using maven. 
But I can provide some examples:
This is my feature file:
Feature: Testing Scenarios for the screenshots System

@screenshots
Scenario: This is a scenario to test screenshots
	When I go to the test application
	And I enter the username
	And I enter the password
This is my step definition for this
@Screenshots(beforeAndAfterEachStep=true)
	@When("^I go to the test application$")
	public void i_go_to_the_test_application() throws Exception {
		System.out.println(System.getProperty("basedir"));
		DriverHelper.openBrowser();
		DriverHelper.goToURL("https://url.com");
		Serenity.takeScreenshot();
		scenario.write(DriverHelper.driver.getTitle());
		System.out.println(scenario.getName()+"i am using scenario.getname");
	}

Following is the driver helper:
public class DriverHelper extends Constants {
        @Managed
	public static WebDriver driver;
	public static void openBrowser() throws IOException {
		System.setProperty("webdriver.gecko.driver", "src/test/resources/drivers/geckodriver.exe");
		driver = new FirefoxDriver();

**Comment by kwbhatti** [comment]
I have been added screenshots in any way possible. 
I also have a serenity.properties file in project root:
serenity.take.screenshots=FOR_EACH_ACTION
serenity.take.screenshots=BEFORE_AND_AFTER_EACH_STEP
serenity.take.screenshots=AFTER_EACH_STEP
Question here would be does serenity already knows where to look for the file, or do I need to define anything in my pom.xml file 
pom.xml:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>my-framework</groupId>
  <artifactId>my-framework</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>name</name>
  <description>my project</description>
  
	<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.9.20</serenity.version>
        <serenity.maven.version>1.9.24</serenity.maven.version>
        <serenity.cucumber.version>1.9.8</serenity.cucumber.version>
        <encoding>UTF-8</encoding>
        <tags></tags>
        <parallel.tests>1</parallel.tests>
        <webdriver.base.url></webdriver.base.url>
    </properties>

    <repositories>
        <repository>
      <id>central</id>
      <name>Central Repository</name>
      <url>http://repo.maven.apache.org/maven2</url>
      <layout>default</layout>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    </repositories>
    <pluginRepositories>
       <pluginRepository>
      <id>central</id>
      <name>Central Repository</name>
      <url>http://repo.maven.apache.org/maven2</url>
      <layout>default</layout>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
    </pluginRepository>
    </pluginRepositories>

    <dependencies>
    <dependency>
		    <groupId>io.rest-assured</groupId>
		    <artifactId>rest-assured</artifactId>
		    <version>3.1.0</version>
		    <scope>test</scope>
		</dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay-webdriver</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.6.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/Test*.java</include>
                        <include>**/*TestSuite.java</include>
                        <include>**/When*.java</include>
                    </includes>
                    <systemPropertyVariables>
                        
                    </systemPropertyVariables>
                    
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <configuration>
                  <tags>${tags}</tags>
                </configuration>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
	
</project>

**Comment by wakaleo** [comment]
https://github.com/serenity-bdd/screenplay-pattern-todomvc.

**Comment by mpuertao** [comment]
Good afternoon. I have a project with Screenplay, Java, Cucumber and Serenity. To automate testing of a StandAlone application, we are doing it with WindowsAppDriver but the Serenity Aggregate plugin is not taking the screenshots for the evidence of the live documentation report that serenity offers.

build gradle

`buildscript {

		repositories {

			maven {

				url "artifactory"
			}
		}

		dependencies {

			classpath "net.serenity-bdd:serenity-gradle-plugin:1.9.9"
		}
	}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'idea'
apply plugin: 'java-library'
apply plugin: 'net.serenity-bdd.aggregator'

group = 'co.com.certificacion.wolf'
version = '1.0-SNAPSHOT'

description = """wolf"""

sourceCompatibility = 1.8
targetCompatibility = 1.8
tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}


repositories {

     maven {

         url "artifactory"
     }
}

dependencies {

    compile group: 'net.serenity-bdd', name: 'serenity-core', version:'2.0.0'
    compile group: 'net.serenity-bdd', name: 'serenity-report-resources', version: '2.0.0'
    compile group: 'com.codoid.products', name: 'fillo', version:'1.17'
    compile group: 'net.serenity-bdd', name: 'serenity-cucumber', version:'1.9.20'
    compile group: 'org.slf4j', name: 'slf4j-simple', version:'1.7.7'
    testCompile group: 'org.assertj', name: 'assertj-core', version: '3.11.1'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile group: 'org.hamcrest', name: 'hamcrest-all', version: '1.3'
    compile group: 'net.sf.jt400', name: 'jt400', version:'9.5'
}`


Please Help
