### ISSUE TITLE
Test Name is not sent to Browserstack

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#846]
From intial debuging it looks like `callingClass.getMethod(elt.getMethodName());` sometimes returns a 
`Method threw 'java.lang.NoSuchMethodException' exception.` 

because of this we return `Optional.empty();` from the catch exception

https://github.com/serenity-bdd/serenity-core/commit/68a917b5fe85eeee75eda90a29820acabd347ff7#diff-426331a28a82097b1fb091fd9c2d1b1eR16

**Comment by bebef1987** [comment]
Before we ignored those exceptions and continued with the next class. 
As of result we don't reach to the desired method name

**Comment by wakaleo** [comment]
If the method name is unknown (which might happen if the test class is no longer on the class path during report generation), where would you expect the name to be gotten?

**Comment by bebef1987** [comment]
From my understanding in `fromCurrentTest`

We go through each value from `Thread.currentThread().getStackTrace()` and check if the `callingMethod` has `@Test` annotation.

When we try to get the `callingMethod` with `name="configureBrowserStackCapabilities"` from class `net.thucydides.core.webdriver.capabilities.BrowserStackRemoteDriverCapabilities` we get a `Method threw 'java.lang.NoSuchMethodException' exception.`

![image](https://user-images.githubusercontent.com/703611/28407649-92cb118e-6d3d-11e7-9b76-8f8a5eed4463.png)

**Comment by wakaleo** [comment]
OK, that's odd. Could you see if you can propose a PR to fix the issue?

**Comment by bebef1987** [comment]
In the previous implementation we where ignoring these exceptions and where getting the correct method name from the stack trace
![image](https://user-images.githubusercontent.com/703611/28407794-122325a2-6d3e-11e7-9761-1321eef9db06.png)

**Comment by bebef1987** [comment]
Yep.
