### ISSUE TITLE
Unable to launch the android app on Emulator through Serenity.Properties config

### ISSUE THREAD

**Issue by rakeshnambiar** [serenity-bdd/serenity-core#850]
Unable to launch the android app on Emulator through Serenity.Properties config.

Whereas it's working fine on my laptop without using the Serenity Framework. Not sure what I am missing here.

appium.hub = http://127.0.0.1:4723/wd/hub
appium.platformName = Android
appium.platformVersion = 4.4.4
appium.deviceName = AndroidEmulator
appium.app = /src/test/resources/Apps/myapp.apk
appium.appPackage = com.booking
appium.appActivity = com.booking.activity.StartActivity
autoWebview = false

**Comment by wakaleo** [comment]
Could you share the code that you would use without using Serenity?

**Comment by cliviu** [comment]
Hi, Could you share also the exception /some logs to help us to narrow the problem ?

**Comment by cliviu** [comment]
have you set 
webdriver.driver=appium ?

**Comment by rakeshnambiar** [comment]
@cliviu Of course Yes

**Comment by rakeshnambiar** [comment]
I assume with this settings, app should get open in the emulator while triggering the test-execution. Do I need to write any additional step?

**Comment by cliviu** [comment]
you will need also 
**appium.browserName=Browser**
Please let me know if you have any error messages in your appium console

**Comment by rakeshnambiar** [comment]
@cliviu ... Thanks for your support. appium.browserName=Browser was there in the Property file and it's working fine for the browser on the mobile device. But in this case, I am trying to invoke the android apk. Should I do any additional code for this? Before that, I assume Serenity framework will support the apps apart from the mobile site.

**Comment by rakeshnambiar** [comment]
Also please note, when I comment the 'webdriver.base.url' on the property file I am getting the below error as expected. Otherwise for the app serenity not throwing any error or no changes on the appium console.

Message: java.lang.AssertionError: Undefined default URL for page object PageObject
	at net.serenitybdd.core.pages.PageUrls.verified(PageUrls.java:69)
	at net.serenitybdd.core.pages.PageUrls.getStartingUrl(PageUrls.java:47)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:738)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:727)
	at net.thucydides.ebi.cucumber.steps.MobHotelSearchSteps.setup(MobHotelSearchSteps.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by rakeshnambiar** [comment]
It seems I am missing some other basic step which is unable to figure out :(

**Comment by cliviu** [comment]
no exception or strange things in the logs ? What is your actual problem ? That you do not see the application running on the emulator ?  Have you tried running a plain appium server, without the hub configuration ?

**Comment by rakeshnambiar** [comment]
I don't think it's a problem with appium hub. Because using the below code I am able to launch the app on the emulator without using serenity.

            File classpathRoot = new File(System.getProperty("user.dir"));
            File appDir = new File(classpathRoot, "/src/test/resources/Apps/");
            File app = new File(appDir, "BookingsDotCom.apk");
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
            capabilities.setCapability("platformName", "Android");
            capabilities.setCapability(CapabilityType.VERSION, TestConstants.ANDROID_VERSION);
            capabilities.setCapability("deviceName", TestConstants.ANDROID_DEF_DEVICENAME);
            capabilities.setCapability("app", app.getAbsolutePath());
            capabilities.setCapability("appPackage", "com.booking");
            capabilities.setCapability("appActivity", "com.booking.activity.StartActivity");
            driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
            driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
            Assert.assertTrue("ERROR: Application NOT installed",driver.isAppInstalled("com.booking"));

But while mentioning these configurations on the Serenity.property file and invoking the test not instrumenting the app on the emulator whereas using the same appium hub the mobile website is working properly. So do I need any extra step in order to work with the mobile app?

**Comment by cliviu** [comment]
Does your serenity test get executed ? Can you please post a sample project that reproduces the problem ? Can you please post the output of the appium server and the output of your test ? Thanks !

**Comment by rakeshnambiar** [comment]
@cliviu .. May I ask you for a sample Appium test on serenity which you may have already?

**Comment by cliviu** [comment]
@rakeshnambiar I have to clean up a bit my test project until it can be shared. I will let you know

**Comment by rakeshnambiar** [comment]
HI @cliviu .. Could you pls share the sample?

**Comment by cliviu** [comment]
hi @rakeshnambiar. Until I have a project worth to be posted, please take a look at this one  : https://github.com/vikramvi/AppiumSerenityPOC . This should get you started.

**Comment by rakeshnambiar** [comment]
Thanks @cliviu .. I will compare with this and let you know still I am facing the same problem.

**Comment by rakeshnambiar** [comment]
It's worked with me with the below appium-serenity capabilities and closing the issue.

appium.automationName = XCUITest
appium.hub = http://0.0.0.0:4723/wd/hub
appium.platformName = iOS
appium.platformVersion = 10.3
appium.deviceName = iPhone Simulator
Mob/src/test/resources/Apps/BookingsDotCom.apk
appium.app=/path/myapp.app

**Comment by rakeshnambiar** [comment]
Hi @cliviu .. It will be great if you could share the framework Skelton with proper serenity structure. The one you are mentioned earlier was just using serenity for invoking Appium and all the elements are handled the normal way. Please advise how to use the MobileElement in Serenity. Also please tell me how to use the same MobileElement for iOS and Android like :

  @FindBy(androidUIAutomator="androidLocator", iOSUIAutomation = "iosLocator")
  MobileElement login;
