### ISSUE TITLE
Print additional information when test fails

### ISSUE THREAD

**Issue by kleewho** [serenity-bdd/serenity-core#853]
In case of test failure I'd like to print additional information about system state. It requires additional http calls. Before with TestNG we were using Listeners. Is it possible to achieve the same with Serenity and JUnit?

**Comment by Invictum** [comment]
@kleewho
I assume you may achieve its with custom StepListener implementation. It is possible to recieve any events related to test execution life cycle.

**Comment by kleewho** [comment]
@Invictum thanks for the answer. Do you know any examples?

**Comment by wakaleo** [comment]
You can create your own StepListener class, e.g.
```
public class SampleStepListener implements StepListener {
    public void testSuiteStarted(Class<?> storyClass) {}

    public void testSuiteStarted(Story story) {}

    public void testSuiteFinished() {}

    public void testStarted(String description) {}
   ...
```

Then put a file called `net.thucydides.core.steps.StepListener` in the META-INF.services directory of your project, and add the full path of your listener to this file.

You can read this to learn more on how this mechanism works: https://docs.oracle.com/javase/tutorial/ext/basics/spi.html

**Comment by kleewho** [comment]
@wakaleo, Thanks! What if I want to add same information to the html report? I don't think `StepListener` can do the trick

**Comment by wakaleo** [comment]
Adding extra information in the HTML reports isn't supported at the moment.
