### ISSUE TITLE
IE unable to launch (net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE)

### ISSUE THREAD

**Issue by VIVEKSRM** [serenity-bdd/serenity-core#857]
hi There , 

We are new to this serenity selenium and trying to execute our test on IE 11 , but its not working .however i tried to run the test in Chrome and it works fine there . My serenity version is 1.4.0 and trying to run in 64-bit Window server 2008 R2 SP1 .

We are using MVN Clean Verify Command :
clean verify -Dmetafilter="+search"  -Dtest.env=local -Dwebdriver.driver=iexplorer -Dwebdriver.ie.driver=./lib/IEDriverServer_64.exe

Can you please help us , what we are missing and why the IE is not launching .
**Error message :** 
Listening on port 36920
Only local connections are allowed
15735 [pool-1-thread-1] ERROR net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider - org.openqa.selenium.remote.SessionNotFoundException happened - retrying in 2 seconds
17752 [pool-1-thread-1] WARN net.serenitybdd.core.webdriver.servicepools.InternetExplorerServicePool - Remote driver creation failed (Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)), falling back on default driver creation
Started InternetExplorerDriver server (64-bit)
3.4.0.0

Listening on port 9693
Only local connections are allowed
18813 [pool-1-thread-1] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.ie.InternetExplorerDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.ie.InternetExplorerDriver (Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 517 milliseconds

**Comment by wakaleo** [comment]
The error is "Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones". This is a constraint with running WebDriver with Internet Explorer; you need to change the Internet Explorer protection settings (see for example http://jimevansmusic.blogspot.co.uk/2012/08/youre-doing-it-wrong-protected-mode-and.html).

More generally, you probably should ask yourself if you really need to run your tests in IE, as generally it causes more pain then it is worth.

**Comment by VIVEKSRM** [comment]
Thanks a lot , let me check and get back to you with the results.
hope this will resolved our issue. Actually IE is our client requirement.

**Comment by wakaleo** [comment]
Closing this issue as it is related to Webdriver IE setup, not Serenity.

**Comment by Afez89** [comment]
@wakaleo  i did a basic selenium project and tried to launch on IE, it works only after i use the 32bit iedriversever.exe. Im now trying for serenity bdd and im not able to go to the page. its able to launch ie but unable to go to the page. for my case its quite important to make it work on ie as its a common user interface that our target audience mostly uses.  The error im getting is:
5662 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.ie.InternetExplorerDriver: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:209)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:142)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:133)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:103)
Please advise

**Comment by wakaleo** [comment]
What version are you using?

**Comment by RodrigoCarbonari** [comment]
11.1365.17134.0

**Comment by wakaleo** [comment]
Are you sure it isn't a Selenium/IE issue?
