### ISSUE TITLE
Not able to print required text in Serenity report

### ISSUE THREAD

**Issue by VIVEKSRM** [serenity-bdd/serenity-core#859]
Hi There,
We are trying to print some required text in serenity output report .But unfortunately we are not able to do this .
We just want that after executing every step we can print some test to the serenity report.

For Ex : ( in pages file) 
			userNameTextBox.type(username);
			passwordTextBox.type(password);
			loginButton.click();			

			System.out.println("Login Successful");  --> we need this message to be printed in serenity report . As of now its just printing in the console at run time.

Can you please help us in resolution.
let me know if more info needed

**Comment by wakaleo** [comment]
Create a step method like this:

```
public class Logging {
    @Step
    public void log(String message){}
}
```

Then, in your calling class, use this method:

```
@Steps 
Logging log;
...
log.message("Login Successful");
```

**Comment by VIVEKSRM** [comment]
Thanks. It worked with minor change.
public class Logging {
    @Step
    public void message(String message){}
}

**Comment by wakaleo** [comment]
Great, thanks for the update.

**Comment by VIVEKSRM** [comment]
Hi Wakaleo,

Reopening the issue . We have tested this method in one of the loginpage class and it worked fine there.
But from other page when we are calling message function it is giving null pointer exception Error Message.

Not sure ,may be we are just missing some thing , but we have checked each and every steps and all are same but it is working from only from loginpage class and not from any where else.

requesting you to please help us on this .

**Comment by wakaleo** [comment]
Are you annotating the Logging variable with @Steps each time?

**Comment by VIVEKSRM** [comment]
We are annotating the logging variable with @Steps at each classs level like in 
public class LoginPage extends PageObject {
	
	@Steps
	Logging log;
}
public class test extends PageObject {
	
	@Steps
	Logging log;
}

**Comment by wakaleo** [comment]
It is poor practice to include @Steps-annotated fields inside a PageObject (violation of layers); I'm not sure if it will work offhand.

**Comment by VIVEKSRM** [comment]
Hi Wakaleo , 

We found that this code :
          log.message("Login Successful");
works with only '@Given - And ' tab and not with '@Then - And ' and '@when - And ' . 

Can you please help us here ? (As if possible we can run this code in  'Then - And ' and 'when - And ')

**Comment by wakaleo** [comment]
There is most likely an error somewhere else, as there is no difference in the handling of different annotated methods.

**Comment by VIVEKSRM** [comment]
Thanks Wakeloe , 

Issue resolved , it seems we have messed up with @Steps in step file .
