### ISSUE TITLE
How to pass/fail a test case intentionally without using assert in Serenity BDD. Can you please help

### ISSUE THREAD

**Issue by VIVEKSRM** [serenity-bdd/serenity-core#860]

**Comment by wakaleo** [comment]
Asserts are the simplest way to do this. What is your use case?

**Comment by VIVEKSRM** [comment]
Thanks. Will go with assert for now. 
Assert put the verification in serenity report when it fails. How to add it in report when assert passes also

**Comment by wakaleo** [comment]
If the test is green, the assertion has passed. If you want to be more explicit, maybe write a step that encapsulates the check or checks.
