### ISSUE TITLE
Not able to take multiple screen shots at any desired points in serenity 

### ISSUE THREAD

**Issue by VIVEKSRM** [serenity-bdd/serenity-core#861]
Hi There , 

We are trying to take screen shot at any random steps as per our requirement, however failing to do so.
PFB the example code:

		userNameTextBox.type(username);
		"Need Screeshot"
		passwordTextBox.type(password);
		"Need Screeshot"
		loginButton.click();
		"Need Screeshot"
		
We are trying with Serenity.takescreenshot(), however it is taking just one screenshot instead of 3.

Could you please suggest.

**Comment by VIVEKSRM** [comment]
Hi,

An update, the required number of screenshots are coming , however in the result path .
How can we save them in our desired path. Please help

**Comment by wakaleo** [comment]
This is not supported; what are you trying to do with the screenshots?

**Comment by VIVEKSRM** [comment]
Thanks Wakaleo ,

We need to save the screen shots at required paths test case wise , like we have executed 10 test case in a bulk run and we need that the screen shots will be placed at 10 different folders for all 10 test cases .

And after the test we can upload the test evidences in QC ( Quality Center)

can you please help us in this

**Comment by wakaleo** [comment]
Why don't you just use the Serenity reports as evidence?

**Comment by VIVEKSRM** [comment]
Hi Wakaleo , 

Apologies for the delayed response.Yes, we are using serenity report but just to reduce the confusion and file size (MBs) .Actually here we need to add evidences in QC , and we need to attached test evidences in 10 different test cases . 
we need to attached of each test case evidence individually in QC. But in serenity report all the evidences are in one particular place. Not like we will add all the evidences in one place , we need to add then in 10 different test cases(folders) in QC .

**Comment by wakaleo** [comment]
It isn't currently on our plan to integrate with complex QC workflows. I would just add a URL to the test case in Serenity.

**Comment by VIVEKSRM** [comment]
Hi Wakaleo,

Thanks for the update .
As it is part of our delivery to integrate QC with Serenity/Selenium, can you suggest any way to implement it.

**Comment by wakaleo** [comment]
Probably nothing automated. In my experience QC is a very closed system and integrates poorly with other applications.

**Comment by ankitlodha** [comment]
Hi Wakaleo,

Is it possible to save results of each test case in individual folders during execution.

**Comment by wakaleo** [comment]
No. Your best bet would be to write a custom tool to read the JSON Serenity files and do whatever processing you need to do from them.
