### ISSUE TITLE
Stuck at the end of the last test.

### ISSUE THREAD

**Issue by stalexmr** [serenity-bdd/serenity-core#862]
Hello, I faced with the strange issue.

When my test suit reached the last test, the progress always stuck - https://www.screencast.com/t/RUDo5IwC
If I try to look at \target\site\serenity\ folder I see all *.html file for each test.

I thought that problem in serenity:aggregate, but turn off this step not affected.

I try to launch my suit in TeamCity and Jenkins with the same result.

<serenity.version>1.4.0</serenity.version>

I can give any additional information about this issue.

**Comment by wakaleo** [comment]
Is the issue reproducible?

**Comment by stalexmr** [comment]
Yes, 
I noticed it when amount of my tests reached over 300. 
I tried to increase -Xms -Xmx but it is not affected by result.
And now, when amount bigger than 300, I always faced this issue.

**Comment by wakaleo** [comment]
It looks like some sort of thread locking issue. If you could get me a sample project that does this, it would help us figure out what is going on.

**Comment by stalexmr** [comment]
The problem was on my site.
I am so sorry. 
Please, close.

**Comment by wakaleo** [comment]
Thanks for the update

**Comment by cb-duppanapudisurya** [comment]
I am also facing with the same issue can you @wakaleo help me with this.
