### ISSUE TITLE
Incorrect total test cases count in the serenity index.html report

### ISSUE THREAD

**Issue by drvgao** [serenity-bdd/serenity-core#863]
When I execute the suite on my local PC on eclipse I see 46 test cases, the same job on Jenkins shows only 39 test cases. I'm using the same Maven goals in both the cases.

The Jenkins report doesn't show up pie-chart also.

**Jenkins Report:**
![image](https://user-images.githubusercontent.com/13764217/28763002-8102ab80-75d8-11e7-835a-2945546ff760.png)

**Local Report:**
![image](https://user-images.githubusercontent.com/13764217/28762905-af86382e-75d7-11e7-8461-02a32a064369.png)

**Comment by wakaleo** [comment]
This is a known Jenkins issue with the HTML report plugin (https://issues.jenkins-ci.org/browse/JENKINS-32026), unrelated to Serenity. See the Jenkins issue for work-arounds.
