### ISSUE TITLE
How to parameterize a xpath

### ISSUE THREAD

**Issue by ankitlodha** [serenity-bdd/serenity-core#865]
Hi,

I need to parameterize the xpath based on the input parameters in a function.
String applet;
@FindBy(xpath=applet + ".//*[@text='My Homepage']")
	WebElementFacade Homepage;

Here applet is the variable. Can you please suggest the right way to do it as it is throwing error

**Comment by wakaleo** [comment]
Java annotations don't support expressions. You can do the with Screenplay locators, though, as done in https://github.com/serenity-bdd/screenplay-pattern-todomvc/blob/master/src/main/java/net/serenitybdd/demos/todos/screenplay/user_interface/TodoList.java
