### ISSUE TITLE
Question on Serenity.setSessionVariable

### ISSUE THREAD

**Issue by beetlezhuk** [serenity-bdd/serenity-core#866]
I need to store a couple of values in the serenity session.
So I'm just wondering if Serenity.setSessionVariable works as a hashmap.
For example:
If I'm calling Serenity.setSessionVariable(RESPONSE) a couple of times - does this mean that I will overwrite RESPONSE entry with another value?

Thank you in advance.

**Comment by wakaleo** [comment]
The Serenity session is a thread-local hashmap.
