### ISSUE TITLE
cucumber-jvm-parallel-plugin doesn't work with serenity

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#868]
@wakaleo  please refer to commit

https://github.com/vikramvi/junit-webtests-parallel-grid-docker-jenkins-debug/commit/c421408bcf656e74c83dddf49b9c362a1654bbb4

- when I run test cases with command **mvn clean verify -Dwebdriver.driver=chrome** , not a single test case gets executed.
- I am not seeing **cucumber** and **cucumber-parallel** directories getting generated as well

Please review

**Comment by wakaleo** [comment]
Please raise this on StackOverflow since it is a question and not a defect.

**Comment by vikramvi** [comment]
@wakaleo do you have any sample repo which has got **serenity** + **cucumber-jvm-parallel-plugin** integration ?

Can you please have a look at the code ?  As I couldn't get it working properly

**Comment by wakaleo** [comment]
I've never used cucumber-jvm-parallel-plugin but I believe there is a way to define the template to create the runner class.

**Comment by vikramvi** [comment]
Ok, can you please share best practice you follow in terms of parallel execution of gherkin scenarios / feature files ?

Currently I'm using manually created runner **@RunWith(CucumberWithSerenity.class)** for each of the feature files.

**Comment by vi123ch** [comment]
Hello, is there any sample to provide? I have similar case, single runner class that launches all tests from feature file and I need to launch them in parallel. I am using failsafe with the properties, still not working. Any example to help pls!
Thanks in advance

**Comment by wakaleo** [comment]
The simplest approach is a runner per feature file.

**Comment by vi123ch** [comment]
Thanks for your reply; but apart from that is there no option please? As it has been decided to have one single runner file for the project. Else using multithreading will it help by launching tests in parallel with a Selenium grid?

**Comment by wakaleo** [comment]
In that case you will need to rethink that decision. Selenium grid lets you run tests in parallel, but if you run them sequentially with a single runner, they will only run sequentially.

**Comment by vi123ch** [comment]
Thanks for your quick reply. So it means for each feature file I should have a runner class to make them execute in parallel? Is there a way to launch parallel the scenarios of each feature file too?  Thanks in advance.

**Comment by wakaleo** [comment]
You could have a runner class for each scenario I guess.
