### ISSUE TITLE
Accessing FindBy field after step failure still waits for timeout

### ISSUE THREAD

**Issue by Cristi003** [serenity-bdd/serenity-core#87]
Accessing FindBy field after step failure still waits for timeout instead of returning immediately.
E.g.:
````
@FindBy(...)
WebElementFacade elem;

public void someMethod() {
   // This waits the timeout duration before returning even if a previous step has failed
   elem.getText();
}
```
The wait is in `checkPresenceOfWebElement` at `waitForCondition().until(elementIsDisplayed());` and the reason is because locator returns WebElementFacadeStub which always returns `false` for `isDisplayed()`.

**Comment by wakaleo** [comment]
Well spotted!

On 29 June 2015 at 22:45, Cristi003 <notifications@github.com> wrote:

> Accessing FindBy field after step failure still waits for timeout instead
> of returning immediately.
> E.g.:
>
> @FindBy(...)
> WebElementFacade elem;
>
> public void someMethod() {
>    // This waits the timeout duration before returning even if a previous step has failed
>    elem.getText();
> }
>
> The wait is in checkPresenceOfWebElement at
> waitForCondition().until(elementIsDisplayed()); and the reason is because
> locator returns WebElementFacadeStub which always returns false for
> isDisplayed().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/87>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by Cristi003** [comment]
Posible solutions:
* detect webdriver calls disabled in checkPresenceOfWebElement and return early
* use waitForCondition that returns ThucydidesFluentWait which will return early if previous step failed instead of continue waiting.
