### ISSUE TITLE
Does serenity provide Oracle database integration

### ISSUE THREAD

**Issue by ankitlodha** [serenity-bdd/serenity-core#870]
Hi,

Wanted to check if serenity provide Oracle database integration.

Thanks

**Comment by wakaleo** [comment]
What do you mean by "Oracle database integration"?

**Comment by ankitlodha** [comment]
Hi,

We need to fire sql queries on Oracle database. Does serenity provide any custom methods for that. Or we can go with java.sql.DriverManager jars

**Comment by wakaleo** [comment]
No, you would just use whatever Java database integration library you are familiar with.

**Comment by ankitlodha** [comment]
Hi,

I am using JDBC driver for database connection. But on running below line of code.

Class.forName("oracle.jdbc.driver.OracleDriver");  

It is giving below exception
Class not found exception: oracle.jdbc.driver.OracleDriver.

Can you please suggest

**Comment by wakaleo** [comment]
You need to add the Oracle JDBC driver to your dependencies. 

I'll close this issue as it is unrelated to Serenity - please feel free to continue the conversation on StackOverflow or on the Serenity mailing list.
