### ISSUE TITLE
How to store data between Pages

### ISSUE THREAD

**Issue by ankitlodha** [serenity-bdd/serenity-core#873]
Hi,

Can you please suggest how to store data between Pages.

Thanks

**Comment by wakaleo** [comment]
See http://serenity-bdd.info/docs/serenity/#_storing_data_between_steps.

**Comment by ankitlodha** [comment]
Hi,

I had gone through this.If I am not wrong this talk about storing data between steps I need to store data between Pages without sending the data from steps to Pages. Please let me know if I am not clear in explaining the issue

**Comment by wakaleo** [comment]
You can use the same mechanism. But pages or page components should not really be storing state, they should simply query the actual web pages via WebDriver, and returning the data they receive. Placing too much logic inside a page object tends to violate the Single Responsibility principle and makes the tests harder to maintain.

**Comment by ankitlodha** [comment]
Hi,

Thanks. I will review the code again and see if I can implement the same. Will try to keep the storing in the pages at minimum.
