### ISSUE TITLE
Missing details in "View stack trace" about which element would receive the click after "Web driver exception: Element is not clickable at point"

### ISSUE THREAD

**Issue by MariuszSkomra** [serenity-bdd/serenity-core#874]
Recently I upgraded Serenity to version `1.5.3` from `1.1.42` and Selenium to version `3.4.0` from `2.53`.

When test fail because of `WebDriverException: Element is not clickable at point` in detailed report view I have details about element which receive the click after fragment `Other element would receive the click:`.
![stacktrace_01](https://user-images.githubusercontent.com/30656686/29120957-cfd295a0-7d0c-11e7-9615-7118431a937a.png)

![stacktrace_02](https://user-images.githubusercontent.com/30656686/29120961-d682b254-7d0c-11e7-8cec-49ed3c4f43fa.png)

When I open "View stack trace" window  after "Other element would receive the click: " this data is missing (in comparison to previous configuration):
![stacktrace_full](https://user-images.githubusercontent.com/30656686/29121011-13714de2-7d0d-11e7-964a-28296a0f0232.png)

I would be grateful for your feedback.

**Comment by wakaleo** [comment]
This feature was removed because it caused performance issues in some cases (it requires extra web driver calls and can cause misleading errors in some cases).
