### ISSUE TITLE
Serenity Results with no data

### ISSUE THREAD

**Issue by push2212** [serenity-bdd/serenity-core#884]
Hi,

I am running Serenity version 1.5.4-rc.1 with Firefox.however the results are not getting generated after test execution(i.e. the result html page contains no data).
I had made a change in the pom.xml , after the change the results are getting affected.
 <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>1.5.4-rc.1</version>
        </dependency>
Please suggest

**Comment by wakaleo** [comment]
1) check that your other Serenity dependencies use the latest versions
2) run mvn clean and rerun the tests
3 try running mvn serenity:aggregate directly

**Comment by wakaleo** [comment]
Closed due to inactivity
