### ISSUE TITLE
Extra point in ChromePreferences getPreparedPropertyKey method

### ISSUE THREAD

**Issue by eshvan** [serenity-bdd/serenity-core#887]
version **1.5.3**
Declare for example in serenity property file:
`chrome_preferences.profile_default_content_settings.popups = 0`
Then we supply prefix in order to parse it here:
https://github.com/serenity-bdd/serenity-core/blob/96ba9a31a1d8503622793dfbe494105de16e5ddd/serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/ChromeDriverCapabilities.java#L73
and again another dot when we actually try to grab it:
https://github.com/serenity-bdd/serenity-core/blob/96ba9a31a1d8503622793dfbe494105de16e5ddd/serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/ChromePreferences.java#L57
so second method not working as expected

**Comment by wakaleo** [comment]
Could you propose a PR?

**Comment by wakaleo** [comment]
Thanks.
