### ISSUE TITLE
Not able to print specific value in the serenity report

### ISSUE THREAD

**Issue by tremkonzah** [serenity-bdd/serenity-core#889]
Hello,

I have rest testing with serenity runner as follow:

`        HashMap<String, Object> name =
                SerenityRest.rest()
                .given()
                .when()
                .get("/list")
                .then()
                .log()
                .all()
                .statusCode(200)
                .extract()
                .path(p1 + firstName + p2);`

When test success, in the report it print all response from get("/list").
I am struggling to find a way to print extracted value from .path() method

is that possible with serenity runner?

thanks

**Comment by wakaleo** [comment]
You could write a step method to print the result, e.g.

```
@Step 
public void the_names_are(HashMap<String,Object> name){}

```

Then call this method and pass in the result of the above call.

Closing this issue as it is a question, not a defect; feel free to continue the conversation on the mailing lists or on StackOverflow (#serenitybdd tag).
