### ISSUE TITLE
Fail scenario in @BeforeScenario on particular condition

### ISSUE THREAD

**Issue by eliogrin** [serenity-bdd/serenity-core#89]
In our test framework there are several tests that can run only on particular environments. We are trying to find a way to fail scenarios by comparing current test environment and a meta-tag from scenario in @BeforeScenario method. It seems that throwing exceptions or calling Serenity.pendingStep() here does not prevent all steps from the scenario to run.
Could you please suggest how can we stop scenario execution from @BeforeScenario and possibly mark all steps as failed or run them in dry-run mode?

**Comment by Invictum** [comment]
Recheck it with 1.0.59 and it works like a charm.
If Serenity.pendingStep() was used first step in scenario is marked with error and other steps are marked as ignored.

**Comment by spcial** [comment]
Still not working for me. It just continous test execution after calling Serenity.pendingStep() in the @BeforeScenario if a particulat condition occurs.

**Comment by wakaleo** [comment]
What version are you using?

**Comment by YamStranger** [comment]
Hello @eliogrin!!

It seems that @Invictum was wright and this issue already fixed. 
To check it I used next code:
```
@RunWith(SerenityParameterizedRunner.class)
@UserStoryCode("US01")
@Concurrent
public class SampleTest {
    @Before
    public void initIt(){
        Serenity.pendingStep("Some reason");
    }


    @TestData
    public static Collection<Object[]> testData() {
        return Arrays.asList(new Object[][]{{1}, {2}, {3}});
    }

    @Steps
    TestSteps steps;
    private final int value;

    public SampleTest(int value) {
        this.value = value;
    }

    @Test
    public void shouldExecuteThisTest() {
        steps.initialization();
        steps.when_example_action_for(this.value);
        steps.then_example_result_should_be(this.value);
        throw new NullPointerException();
    }

    @Test
    public void shouldExecuteThisTestToo() {
        steps.initialization();
        steps.when_example_action_for(this.value);
        steps.then_example_result_should_be(this.value);
    }
}
```

after execution I receive next report:
![pending_screenshot](https://cloud.githubusercontent.com/assets/1667699/11324206/3d2d3e70-9123-11e5-83d0-e3de7fc88f2f.png)


All works fine. 

@eliogrin Please close this issue. 

Thanks!!

**Comment by eliogrin** [comment]
Thanks to all! I am rechecked this issue on the latest version and yes, it's work correctly.
