### ISSUE TITLE
Favicon is outdated

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#890]
Serenity got new nice logo, but favicon was not updated - is it intended? Serenity version **1.5.4-rc.2**

![screen](https://user-images.githubusercontent.com/6312221/29459674-7f7459f4-842d-11e7-9116-f9179270c237.png)

**Comment by wakaleo** [comment]
Fixed in 1.5.4, thanks for pointing this out.

**Comment by scormaq** [comment]
Hi @wakaleo ,
seems in latest Serenity (1.6.0) favicon not displayed at all (Windows 10, Firefox 52.3.0). Also, highlighted serenity version is wrong (right bottom corner - see screen attached)
![screen](https://user-images.githubusercontent.com/6312221/30918819-55733e64-a3a8-11e7-93d2-d3a2d71a5884.png)

**Comment by wakaleo** [comment]
Happy to accept PRs on this.
