### ISSUE TITLE
Serenity <- jBehave steps

### ISSUE THREAD

**Issue by beetlezhuk** [serenity-bdd/serenity-core#893]
Hi,
just want to understand what's going on on the background when we are calling some java methods from jBehave step.

So the question is - when we have step "Given do some cool stuff", which is mapped to 
[DefinitionSteps.class]
@Given("Given do some cool stuff")
public void doCoolStuff(){...};  - does Serenity create a new object of  DefinitionSteps.class everytime we're calling "Given do some cool stuff"?

**Comment by wakaleo** [comment]
This is a question about the JBehave implementation. JBehave creates a new instance of the DefinitionSteps class for each scenario it executes, but not for each method.

**Comment by beetlezhuk** [comment]
@wakaleo 
Then I don't really understand the following situation:

I have a class A, which contains some object (myObj) and sets some properties to it.
Then I call another step, which is mapped to method "doAdditionalSetup" in class B (child from A)
In case the myObj is not static - it doesn't contain the data from initial step.

**Comment by wakaleo** [comment]
If class B is inherited from class A, it will still be a different instance. What problem are you trying to solve?

**Comment by beetlezhuk** [comment]
Please take a look at the code below - I'm setting the object in two places (parent and child classes).
In case this object is not statis - the properties, that are set in parent class are null.

Scenario: Search - xxx source requested
Given Setup data for xxx
Given Check xxx event names and set as search term

public class GeneralDefinitionSteps {

    private static final Logger logger = Logger.getLogger(GeneralDefinitionSteps.class);
    protected SearchBody searchBody = new STBSearchBody();

@Given("Setup data for $content")
    public void setUpData(@Named("flow") String flow, String content){
                Serenity.getCurrentSession().put("CONTENT_TYPE", content);

//setting up STBSearchBody stbSearchBody
                BaseSteps.setSearchData(content, stbSearchBody);
    }
}

public class SearchDefinitionSteps extends GeneralDefinitionSteps {
//setting up SearchBody searchBody - additional info
    @Given("Check LTV event names and set as search term")
    public void pickSearchTerm() throws Exception {
        traxisServiceSteps.pickSearchTerm(searchBody);
    }
}

**Comment by wakaleo** [comment]
Why don't you simply use the Serenity sessions to share data between steps? Class inheritance only means that the fields are inherited, not the values, so an instance of a child class will always have different values to an instance of a parent class.

**Comment by beetlezhuk** [comment]
I have pretty much such objects. I think it can be a little hard to store lots of objects in sessions.
