### ISSUE TITLE
Rendering Hungarian characters in HTML report

### ISSUE THREAD

**Issue by zappee** [serenity-bdd/serenity-core#894]
The HTML report contains wrong characters in case of some Hungarian chars.

**This is my serenity property file:**
```
feature.file.encoding=UTF-8
serenity.report.encoding=UTF-8
serenity.project.name=Test scenarios for ... application
```

**My pom.xml file looks like this:**
```
<properties>
    <file.encoding>UTF-8</file.encoding>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
</properties>
```

The encoding of the *.story file is UTF-8.
This is the scenario which contains special chars:
```
Scenario: Érintett befogadása alapadatokkal
```

Code snippet with the relevant content of the generated index html:
```
&Eacute;rintett m&oacute;dos&iacute;t&amp;aacute;sa alapadatokkal&nbsp;(2  examples)
```

This is the correct content:
```
&Eacute;rintett m&oacute;dos&iacute;t&aacute;sa alapadatokkal&nbsp;(2  examples)
```

**As you can see there is an extra _amp;_ there:**
```
NOK: &Eacute;rintett m&oacute;dos&iacute;t&amp;aacute;sa alapadatokkal&nbsp;(2  examples)
OK_: &Eacute;rintett m&oacute;dos&iacute;t&aacute;sa alapadatokkal&nbsp;(2  examples)
```

It is so interesting that the _title_ html tag contains correct text, so when I move the mouse pointer towards to the label the _html hint_ displays the correct content:
```
<a href="30ffb0abac8f83e33eef1cd85e4f2ea8d1494510ac3064fd6c883c14a8f074e5.html" class="ellipsis" title="Érintett befogadása alapadatokkal ">
                                            Érintett befogad&amp;aacute;sa alapadatokkal
                                                <span class="related-issue-title"></span>
                                        </a>
```

Could you please check it?

**Comment by wakaleo** [comment]
Sure, we will take a look. Could you provide a sample project with (just with empty steps should be fine) to illustrate the problem?

**Comment by zappee** [comment]
I will upload a simple demo project to Git soon. Thanks.

**Comment by zappee** [comment]
@wakaleo I have created a very simple java project to demonstrate this issue.
Git: https://github.com/zappee/serenity-special-chars-issue.git

Could you pleease check it?

**Comment by cliviu** [comment]
hi @zappee , thanks for your sample project. I was able to reproduce your problem using the project that you have provided, but I have not found the cause until now. I'm on it, I will let you know when I find something

**Comment by cliviu** [comment]
Asa workaround, until we get this sorted out, please use this property in your serenity.properties file : **enable.markdown=false**

**Comment by zappee** [comment]
Thanks for your help. The workaround works like a charm.
