### ISSUE TITLE
AfterScenario and WebDriver issue

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#896]
Hello, 

I am using Serenity with JBehave.

- Windows 10 64 bits

- IntelliJ 2017.1.5

- serenity-core  version: '1.5.3'

- serenity-jbehave version: '1.27.0'

- serenity-gradle-plugin  version: '1.5.3'

- Firefox and Chrome (last versions)

I am facing a strange behavior : 

**With an @AfterScenario (JBehave annotation), I want to check if a weblement is present on the page for each scenario, and whatever the result of the test (passed or failed)**

- When the test is passed, the AfterScenario step is working well : my PageObject (extending the serenity PageObject class) find the element.

- When the test is failed, the element is not found (and it's not because the element is not present on the page, or because the browser is closed).

With some debug, when the test arrives in the AfterScenario step, if I try to call : 
```
MyPageObject.getDriver().getCurrentUrl()
MyPageObject.getDriver().findElements(...)
```
This will return nothing if the test failed, as if the driver was no longer linking to the still open browser.

However, the sessionId of the WebDriver is still the same.

Here is a sample project to reproduce this case : https://github.com/mmanach/sandbox

Thank you for your help.

**Comment by wakaleo** [comment]
This is "normal" behaviour - once a test fails, the WebDriver instance is disabled and any subsequent calls to the WebDriver instance are ignored. If you want to "reactivate" the driver, placing the following in your AfterScenario method might work:
```
StepEventBus.getEventBus().clearStepFailures();   
```

**Comment by mmanach** [comment]
Thank you for the fast response !

At first sight, it works :)

But can this cause edge effects? For example on the report, on the last failed step... ?

So, from Serenity's point of view, if the driver is no longer accessible as of the 1st error, what generic workaround would you do to retrieve a webelement without the AfterScenario annotation ?

**Comment by wakaleo** [comment]
The driver is not closed at this point, it is just not being used. This method is an internal Serenity API call that tells Serenity to pass through requests to the proxied driver, rather than blocking them. It doesn't actually alter the test results (despite the method name).

**Comment by wakaleo** [comment]
Closing this as I'm assuming the proposed fix worked - feel free to reopen if it didn't.
