### ISSUE TITLE
Can not run tests with new serenity versions (1.5.4-rc.1 - 1.5.5)

### ISSUE THREAD

**Issue by livastar** [serenity-bdd/serenity-core#897]
Hi to all, 
I've tried to run my tests with new serenity versions as 1.5.5 and 1.5.4-rc.2. 
Appium server didn't show any logs, it seems that serenity and appium don't talk.

Also, I've tried to run with 1.5.4-rc.1 and app started but appium logs stop before the first step.

Note:
I'm running my tests with 1.5.0-rc.1 and java-client 5.0.0-BETA8

**Comment by wakaleo** [comment]
Serenity doesn't interact with Appium, Selenium does, so it is most likely a dependency conflict between Selenium and Appium. Have you tried with Serenity 1.5.3 (which uses Selenium 3.4.0)?

**Comment by livastar** [comment]
I'm running my tests with 1.5.0-rc.1 and java-client 5.0.0-BETA8 and Selenium 3.0.1 and it works well for me. When I change only the selenium version to 3.4.0, at first steps when the app starts I'm presented with this error:
org.openqa.selenium.support.ui.Wait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;

**Comment by wakaleo** [comment]
This sounds like a dependency conflict between Selenium 3.4 or 3.5.1 and Appium - the error you are getting is to do with different Guava dependencies. Selenium 3.4 (or guava, more precisely) has breaking changes in recent versions, so upgrading will be tricky until they update the Appium libraries.

**Comment by livastar** [comment]
Hi guys,
@mykola-mokhnach
@jilipps
Do you know anything about this?

**Comment by mykola-mokhnach** [comment]
java_client is a separate project, which is maintained by @SrinivasanTarget and @TikhomirovSergey

**Comment by livastar** [comment]
Thanks @mykola-mokhnach for reply :)

**Comment by mykola-mokhnach** [comment]
BTW, @wakaleo is right regarding guava - @livastar make sure you use the most recent version as a dependency.

**Comment by livastar** [comment]
I've tried with latest guava (23.0 and 22.0 and 21.0) and Selenium (3.4.0; 3.5.1; and 3.5.2) and java-client (BETA8 and BETA9) and Serenity (1.5.5, 1.5.4, 1.5.4-rc.2, 1.5.4-rc.1) but with no results. :(

**Comment by mykola-mokhnach** [comment]
It is possible some third-party package still used old guava as a dependency. Go through the list of them and make sure it's really up to date and no old versions of it are present in the list of project dependencies.

**Comment by wakaleo** [comment]
Serenity uses the latest version of Selenium (3.4+), which uses the latest version of Guava. It looks like Appium uses an older version of Guava, which is not compatible with the latest version of Selenium. Since both Guava and Selenium have breaking API changes in recent versions, the only option is to wait for the Appium library to be updated.

**Comment by amedvedjev** [comment]
how about to try ?
```
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>5.0.0-BETA9</version>
            <exclusions>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.5.2</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by wakaleo** [comment]
The latest version (1.5.7) uses selenium 3.5.2 - could you try with this version?

**Comment by livastar** [comment]
@wakaleo I've tried to use:

<dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>5.0.0-BETA8</version>
</dependency>
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.5.2</version>
</dependency>
<dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>1.5.7</version>
</dependency>

**Comment by wakaleo** [comment]
The latest version (serenity-core: 1.5.11) is built with selenium 3.5.2 and java-client 5.0.2. The next version will be built with selenium 3.5.3 and java-client 5.0.3.

Selenium 3.5.x uses Java 8 Function classes instead of Guava, and if your client code (or a dependency) is built for an older version of Selenium, you could get an error like the one you mention above.

**Comment by livastar** [comment]
> Selenium 3.5.x uses Java 8 Function classes instead of Guava, and if your client code (or a dependency) is built for an older version of Selenium, you could get an error like the one you mention above.

It's about explicit waits only?

**Comment by wakaleo** [comment]
I don't recall if that is the only place they are used in the Selenium APIs.

**Comment by wakaleo** [comment]
Could you try with serenity-core 1.6.0?

**Comment by livastar** [comment]
@wakaleo hi. :) I've tried to run with serenity 1.6.0; java-client 5.0.3, and selenium 1.5.3

here are the logs from appium server:
https://gist.github.com/livastar/3fbc036c79d36c9c7e0dba1cd50d2a2b

The thing is that Test Case is failing on first step on tapOnElement 

Here are the logs from Serenity in IntelliJ :)
https://gist.github.com/livastar/97fbaa1e9438a5dea2ce572462243c16

**Comment by wakaleo** [comment]
Thanks for trying it out. Serenity 1.6.0 is built against Appium 5.0.3 and selenium 3.5.3, so the libraries should not be conflicting. Your test seems to fail with a NPE on line 226 of the `ContentTest` class. Is this your class?

**Comment by wakaleo** [comment]
Have you tried with version 1.6.6?

**Comment by livastar** [comment]
Hi @wakaleo, 
I've tried with serenity 1.6.6; the latest java-client (5.0.4); and the latest selenium (1.6.0).
BUT no success. :) The same, thing. Page Objects are returning null

**Comment by wakaleo** [comment]
I think this might be due to a known bug with the Appium client, that we have seen elsewhere - are you using the Appium @FindBy annotations in your Page Objects?

**Comment by wakaleo** [comment]
Could you try forcing the version of Appium client to 5.0.4?

**Comment by livastar** [comment]
**I've tried with serenity 1.6.6; the latest java-client (5.0.4); and the latest selenium **(1.6.0).**

**Comment by wakaleo** [comment]
Sorry, didn't see your comment fully above.

**Comment by livastar** [comment]
CC: @TikhomirovSergey, @mykola-mokhnach 
I'm using 
**@AndroidFindBy:**
@AndroidFindBy(id = "action_skip")
public WebElementFacade skipButton;)
**By**
public static final By CHANNEL_IMAGE = By.id("channel_image");
public WebElementFacade channelImage() {
        return returnElement(CHANNEL_IMAGE);
    }

**Comment by cliviu** [comment]
hi @livastar , maybe this issue can help :  https://github.com/serenity-bdd/serenity-core/issues/925 ,
try to extend your PageObject from the following class:

```
public class AppiumPageObject extends PageObject {
  public AppiumPageObject(WebDriver driver) {
      super(driver);
      PageFactory.initElements(new AppiumFieldDecorator(((WebDriverFacade) getDriver()).getProxiedDriver(),
              this.getImplicitWaitTimeout().in(TimeUnit.SECONDS), TimeUnit.SECONDS), this);
  }
}


```

**Comment by livastar** [comment]
@cliviu :) no results :(

**Comment by vikramvi** [comment]
@livastar can you try my sample project https://github.com/vikramvi/AppiumSerenityPOC and let us know if you still face any issues

**Comment by livastar** [comment]
Hi to all :) 
Thanks for your all input. @wakaleo, @vikramvi , @amedvedjev, @mykola-mokhnach, @cliviu 
We've resolved this by replacing all 
'@AndroidFindby(id = "action_skip")
public WebElementFacade skipButton;)'
by 'public static final By CHANNEL_IMAGE = By.id("channel_image");
public MobileElement channelImage() {
return returnElement(CHANNEL_IMAGE);
}'
In some cases that when we need WebElementFacade, we just casting this.

**Comment by vikramvi** [comment]
@livastar why you need to use above technique ? Is PageFactory broken ?

Why error are you getting ?

**Comment by livastar** [comment]
@vikramvi something with "Your PageObject is looking doggy"
