### ISSUE TITLE
Error with serenity.browser.maximized property

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#898]
If I set to true the serenity.browser.maximized property the browser doesn't maximize, it gets a really small size.

![image](https://user-images.githubusercontent.com/4032481/29588529-7bdbf4aa-8757-11e7-838c-4af80a54c684.png)

**Comment by wakaleo** [comment]
I'm not seeing that here. What version of Serenity and chromedriver are you using?

**Comment by wakaleo** [comment]
See also: https://stackoverflow.com/questions/41523020/cant-maximize-chrome-window-using-selenium

**Comment by ricardorlg** [comment]
I'm using the last version of chrome and firefox (it also happens in firefox), This happens with the screenplay todo app example, last version of serenity.

**Comment by wakaleo** [comment]
What version of chromedriver are you using? Can you share your serenity.properties file?

**Comment by ricardorlg** [comment]
Chrome: Version 60.0.3112.101 
Firefox: Version 55.0.2
Serenity Version 1.5.4-rc.2

[serenity.properties.txt](https://github.com/serenity-bdd/serenity-core/files/1245915/serenity.properties.txt)

**Comment by wakaleo** [comment]
What about the chromedriver binary (not the browser)? (the maximise instruction simply sends the driver, as shown here:
```
class MaximizeRedimensioner implements Redimensioner {

    @Override
    public void redimension(WebDriver driver) {
        driver.manage().window().maximize();
    }
}
```
so I suspect a driver issue. Place a breakpoint in this code to see what is going on).

**Comment by ricardorlg** [comment]
Hi, after checking the bug is in serenity, 

```java
enum RedimensionStrategy {
    DoNotRedimension,
    RedimensionToSpecifiedSize,
    Maximize;

    public static RedimensionStrategy strategyFor(WebDriver driver, EnvironmentVariables environmentVariables) {

        RedimensionConfiguration redimensionConfiguration = new RedimensionConfiguration(environmentVariables);

        if (!redimensionConfiguration.supportsScreenResizing(driver)) {
            return DoNotRedimension;
        }

        if (redimensionConfiguration.isBrowserDimensionsSpecified()) {
            return RedimensionToSpecifiedSize;
        }

        if (redimensionConfiguration.isBrowserMaximised()) {
            return RedimensionToSpecifiedSize;
        }

        return DoNotRedimension;
    }
}
```
when is getting the strategy to maximised the code is returning **RedimensionToSpecifiedSize** instead of **Maximize**

**Comment by wakaleo** [comment]
Well spotted - would you like to submit a PR?

**Comment by wakaleo** [comment]
(I can do it of course but it would deprive you of the credit for all your hard work ;-) ).

**Comment by ricardorlg** [comment]
sure, I can submit the PR

**Comment by PeterSomora** [comment]
serenity.browser.maximized = true
