### ISSUE TITLE
Received [WARNING] Error injecting: net.serenitybdd.maven.plugins.SerenityAggregatorMojo java.lang.TypeNotPresentException: Type net.serenitybdd.maven.plugins.SerenityAggregatorMojo not present

### ISSUE THREAD

**Issue by prat23k** [serenity-bdd/serenity-core#900]
Hi,
Can anyone help me to resolve following issue
Unable to build my serenity project received below error
[WARNING] Error injecting: net.serenitybdd.maven.plugins.SerenityAggregatorMojo java.lang.TypeNotPresentException: Type net.serenitybdd.maven.plugins.SerenityAggregatorMojo not present

1.5.4-rc.2:aggregate (serenity-reports)Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.5.4-rc.2:aggregate failed: Unable to load the mojo 'aggregate' in the plugin 'net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.5.4-rc.2' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: net/serenitybdd/maven/plugins/SerenityAggregatorMojo : Unsupported major.minor version 52.0
my POM Versions are 
serenity.version:1.5.4-rc.2
serenity.jbehave.version:1.24.0
serenity.maven.version:1.5.4-rc.2

Thank you

**Comment by wakaleo** [comment]
Can you provide a sample project that illustrates this issue?

**Comment by prathimak** [comment]
Ok I can provide a sample project

**Comment by prathimak** [comment]
And chrome is not working with below versions
serenity.version:1.2.2
serenity.jbehave.version:1.21.0
serenity.maven.version:1.2.2
received 
net.serenitybdd.core.exceptions.SerenityManagedException: unknown error: unsupported protocol

**Comment by wakaleo** [comment]
Please update to the latest versions of each of these libraries and see if the problem persists.

**Comment by prat23k** [comment]
@wakaleo thank you for the reply,if i am trying to  update to latest versions i am getting above issue

**Comment by wakaleo** [comment]
What command are you running to get this output?

**Comment by prat23k** [comment]
i am running maven install from eclipse

**Comment by wakaleo** [comment]
Can you share your pom.xml file?

**Comment by prat23k** [comment]
Here is the pom.xml

<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>1.5.3</serenity.version>
		<serenity.jbehave.version>1.24.0</serenity.jbehave.version>
		<serenity.maven.version>1.5.3</serenity.maven.version>
		<webdriver.firefox>firefox</webdriver.firefox>
		<webdriver.ie>webdrivers\IEDriverServer.exe</webdriver.ie> 
		<webdriver.chrome>webdrivers\chromedriver.exe</webdriver.chrome>
	</properties>

	<dependencies>
		
		<dependency>
			<groupId>com.microsoft.ews-java-api</groupId>
			<artifactId>ews-java-api</artifactId>
			<version>2.0</version>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jbehave</artifactId>
			<version>${serenity.jbehave.version}</version>
			<exclusions>
				<exclusion>
					<groupId>net.serenity-bdd</groupId>
					<artifactId>serenity-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.easytesting</groupId>
			<artifactId>fest-assert</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>2.0</version>
		</dependency>
		<dependency>
			<groupId>com.jcraft</groupId>
			<artifactId>jsch</artifactId>
			<version>0.1.54</version>
		</dependency>
		<dependency>
			<groupId>commons-httpclient</groupId>
			<artifactId>commons-httpclient</artifactId>
			<version>3.1</version>
		</dependency>
		
		<dependency>
			<groupId>jcifs</groupId>
			<artifactId>jcifs</artifactId>
			<version>1.3.17</version>
		</dependency>

		

		<dependency>
			<groupId>com.jcabi</groupId>
			<artifactId>jcabi-log</artifactId>
			<version>0.12.2</version>
		</dependency>
		
		<dependency>
			<groupId>ch.ethz.ganymed</groupId>
			<artifactId>ganymed-ssh2</artifactId>
			<version>build210</version>
		</dependency>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>12.1.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.jcabi</groupId>
			<artifactId>jcabi-aspects</artifactId>
			<version>0.14</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.7</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.7</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>2.2.2</version>
		</dependency>

		
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.7</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.13</version>
		</dependency>

		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>javax.mail-api</artifactId>
			<version>1.5.2</version>
		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-compat</artifactId>
			<version>3.0.5</version>
			<scope>test</scope>
		</dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<argLine>-Xmx8824m</argLine>
					<systemPropertyVariables>
						<jira.url>http://88.885.34.62:8080/</jira.url>
						<jira.project>xx</jira.project>
						<jira.username>xx</jira.username>
						<jira.password>xx</jira.password>
					</systemPropertyVariables>
					<webdriver.firefox.driver>${webdriver.firefox}</webdriver.firefox.driver>
					<webdriver.ie.driver>${webdriver.ie}</webdriver.ie.driver>
					<webdriver.chrome.driver>${webdriver.chrome}</webdriver.chrome.driver>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<includes>
						<include>**/*Test.java</include>
						<include>**/Test*.java</include>
						<include>**/When*.java</include>
						<include>**/*TestSuite.java</include>
					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.9</version>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<repositories>

		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>

		<repository>
			<id>codelds</id>
			<url>https://code.lds.org/nexus/content/groups/main-repo</url>
		</repository>
		<repository>
			<id>oss-sonatype</id>
			<name>oss-sonatype</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<profiles>
		<profile>
			<id>maven2</id>
			<activation>
				<file>
					<missing>${basedir}</missing>
				</file>
			</activation>
			<reporting>
				<plugins>
					<plugin>
						<groupId>net.thucydides.maven.plugins</groupId>
						<artifactId>maven-thucydides-plugin</artifactId>
						<version>${thucydides.version}</version>
					</plugin>
				</plugins>
			</reporting>
		</profile>
		<profile>
			<id>maven3</id>
			<activation>
				<file>
					<exists>${basedir}</exists>
				</file>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-site-plugin</artifactId>
						<version>3.2</version>
						<configuration>
							<reportPlugins>
								<plugin>
									<groupId>net.thucydides.maven.plugins</groupId>
									<artifactId>maven-thucydides-plugin</artifactId>
									<version>${thucydides.version}</version>
								</plugin>
							</reportPlugins>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>

**Comment by wakaleo** [comment]
There are a few things that might play up:

- You are compiling with Java 7 - Selenium 3 and Serenity 1.5.x require Java 8
- You still have references to maven-thucydides-plugin, though I'm not sure if they are being referenced
- Possible conflicts with other dependency libraries

Have a look at the pom.xml in https://github.com/serenity-bdd/screenplay-pattern-todomvc to see a working version.

**Comment by prat23k** [comment]
@wakaleo thank you i am using java8 , i am not using  maven-thucydides-plugin anymore ,and when ever i execute maven install i am removing my .m2 subfolders,will refer that thank you

**Comment by prat23k** [comment]
Thank you updated to java8 which fixed mojo plugin issue but still chrome is not working (net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: unknown error: unsupported protocol

**Comment by wakaleo** [comment]
That looks like you don't have the right version of chromedriver. Make sure you have the latest version of chromedriver on your system path.

**Comment by prat23k** [comment]
I am using latest version of chrome and chromedriver

(net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: unknown error: unsupported protocol
  (Session info: chrome=60.0.3112.101)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)

Thank you

**Comment by wakaleo** [comment]
The error is coming from WebDriver; it looks like a WebDriver issue of some kind, unrelated to Serenity. Do you have more information in the logs?

**Comment by prat23k** [comment]
starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on port 45310
Only local connections are allowed.
Aug 23, 2017 5:27:28 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Given user is on the Ops Login page (FAILED)
(net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: unknown error: unsupported protocol
  (Session info: chrome=60.0.3112.101)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 14 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'L00051294', ip: '192.168.1.104', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8), userDataDir=\AppData\Local\Temp\scoped_dir9940_7196}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=60.0.3112.101, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 71ec6dc7357b9d63299e394ab8f8a6bf)

**Comment by wakaleo** [comment]
"unknown error: unsupported protocol" could be a problem with the URL you are defining for the page.

**Comment by prat23k** [comment]
Could be but same url working with firefox and ie without any issues

**Comment by wakaleo** [comment]
Then it's a chromedriver-specific issue. What is the URL?

**Comment by prat23k** [comment]
ok I can't share my project url looks like chromedriver specific issue.

Could you suggest any reports plugin in jenkins for serenity and jbehave tests,at the moment we are using html publisher plugin but its not working properly.

Thank you

**Comment by wakaleo** [comment]
The problem with HTML Publisher actually comes from the Jenkins security settings, and would apply to any similar plugin. There are some work-arounds described here: https://stackoverflow.com/questions/35783964/jenkins-html-publisher-plugin-no-css-is-displayed-when-report-is-viewed-in-j and https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

**Comment by prat23k** [comment]
thank you so much,is there any speific reports plugin for serenity jbehave

**Comment by wakaleo** [comment]
No, not at this stage.

**Comment by prat23k** [comment]
ok thank you
