### ISSUE TITLE
report does not respect underscore character

### ISSUE THREAD

**Issue by tremkonzah** [serenity-bdd/serenity-core#901]
For some cases when we have wording with underscore e.g access_token refresh_token

reproducible using taxi-rank project when updating feature file to

```
 Scenario Outline: All the taxi ranks within a given distance should be shown
    Given Joe is at <station>
    When he access_token and refresh_token <distance> meters
```

when we run in maven project report will generate accesstoken in report step

![image](https://user-images.githubusercontent.com/16239264/29666584-7068cc50-890b-11e7-8cd5-07fba1a2f187.png)

same thing happening when we serialized pojo object to json and adding to step report

but it does not happening when we have one word with underscore on the same line
e.g
```
  Scenario Outline: All the taxi ranks within a given distance should be shown
    Given Joe is at <station>
    When he has created access_token <distance> meters
```

![image](https://user-images.githubusercontent.com/16239264/29666795-6553fbcc-890c-11e7-878e-0fcba9d234e7.png)

**Comment by wakaleo** [comment]
What version are you using?

**Comment by tremkonzah** [comment]
Hi @wakaleo am using 1.5.3 serenity-core and 1.5.4 serenity-cucumber
```
        <serenity.version>1.5.3</serenity.version>
        <serenity.maven.version>1.5.3</serenity.maven.version>
        <serenity.cucumber.version>1.5.4</serenity.cucumber.version>
```

**Comment by wakaleo** [comment]
This is normal behaviour if markdown is configured for steps. However markdown should be disabled for steps by default. Check your serenity.properties file and if in doubt, add the following:

```
markdown.enabled = story,narrative,scenario
```

**Comment by tremkonzah** [comment]
Thanks @wakaleo, test passed as expected after adding above markdown in serenity.properties

![image](https://user-images.githubusercontent.com/16239264/29667922-dc1c3004-8910-11e7-8f6d-9fd612f7775c.png)
