### ISSUE TITLE
best way to query steps test status

### ISSUE THREAD

**Issue by tremkonzah** [serenity-bdd/serenity-core#902]
Hi @wakaleo 

Is this possible?

we have external system and would like to integrate with serenity bdd.
the scenario are during when, given, or then steps execution we would like to query test status for and call different external api based on test status

e.g

```
    @Given("(?:.*) is (?:at|planning a getaway from) (.*)")
    public void userIsCurrentlyAt(@Transform(TubeStationConverter.class) TubeStation tubeStation) {
        doSomething();
		
		queryStatusOfDoSomething();
		
		if Given status == PASSED {
			call api 123;
		} else {
		    call api 999;
		}
    }
```

**Comment by wakaleo** [comment]
You can check if the current test has failed by calling `StepEventBus.getEventBus().getBaseStepListener().aStepHasFailed()`, but it would not be a very good API design (it could fail for other reasons as well). It would be better if the call to the external system reported on the status.

**Comment by tremkonzah** [comment]
Hi @wakaleo thanks for your kind response

What do you mean with `reported on the status.`?

Would you mind to provide an example of the implementation?

many thanks

**Comment by wakaleo** [comment]
The `doSomething()` method should return a value or throw an exception

**Comment by tremkonzah** [comment]
got it. Thanks @wakaleo
