### ISSUE TITLE
serenity roadmap

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#903]
Hello,

Is it possible to know the roadmap of serenity, and especially when will be integrated the latest versions of selenium (3.5.x)?

And for information : 

- https://snap-ci.com/serenity-bdd/serenity-core/branch/master is 404

- The changelog is not up to date :-(

Thank in advance

**Comment by wakaleo** [comment]
Serenity 1.5.5 integrates Selenium 3.5.1. 

SnapCI shut down in August, so we are running the CI build on a private AWS instance at the moment, including automating the change log generation.
