### ISSUE TITLE
Step not printed in the report

### ISSUE THREAD

**Issue by tremkonzah** [serenity-bdd/serenity-core#907]
Hello

I have test step with below details

```
public class StepClass {

@Step("Create user id and address")
    public static MyObject create(Integer id, String address) {

        //Do something to generate my object;

        return object;

    }	
}


public class StepDefClass {

@Steps
StepClass steps;

@Given("^create user$")
    public void create_user() throws Throwable {
        steps.create(12345, "London");
    }
}
```
I can see When step def in serenity report with success result but serenity not record step in inside Given

While it works if I add extra step method pass above step method to the empty step method

```
public class LogClass {
@Step
public static log(String message) {

}

public class StepDefClass {

@Steps
StepClass steps;
LogClass lo;

@Given("^create user$")
    public void create_user() throws Throwable {
        lo.log(steps.create(12345, "London"));
    }
}
```

using this extra work, when report generated i can see + sign in When and i could expand + sign and see step inside When

is this expected when using serenity reporting with serenity cucumber?

**Comment by wakaleo** [comment]
This is expected, as the @Step annotation will not work on a static method.

**Comment by tremkonzah** [comment]
If I remove static keyword from `public MyObject create(Integer id, String address)`
then i need to initialize under @Steps annotation, but I can not an example about that on serenity example project

is this a correct approach using @Steps annotation?
```
@Steps
StepClass steps = new StepClass();
```

**Comment by wakaleo** [comment]
No, you need to let Serenity instantiate the field:

```
@Steps
StepClass steps;
```

**Comment by tremkonzah** [comment]
Thanks @wakaleo
