### ISSUE TITLE
Null pointer exception while using withTimeOut method

### ISSUE THREAD

**Issue by ankitlodha** [serenity-bdd/serenity-core#910]
Hi,

I am getting Null pointer exception while using withTimeOut method.
private static final TimeUnit SECONDS = null;
object.withTimeoutOf(5,SECONDS).waitUntilVisible();

Error:
java.lang.NullPointerException
	at java.util.concurrent.TimeUnit$3.convert(TimeUnit.java:113).

Can you please help

**Comment by wakaleo** [comment]
Try:
```
object.withTimeoutOf(5,TimeUnit.SECONDS).waitUntilVisible();
```

**Comment by ankitlodha** [comment]
Thanks.It worked:)
