### ISSUE TITLE
How to set useragent for Firefox on serenity.properties file?

### ISSUE THREAD

**Issue by fergadipa** [serenity-bdd/serenity-core#911]
Dear Serenity,

How to set useragent for Firefox on serenity.properties file?
For Chrome, I can use `chrome.switches = --user-agent=Mozilla/5.0 (Linux; Android 6.0.1; SM-G920V Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36` and it works.
For Firefox, I already tried with `firefox.preferences = Mozilla/5.0 (Linux; Android 6.0.1; SM-G920V Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36` but does not works.

Thank you :)

**Comment by wakaleo** [comment]
How would you do this in pure Selenium?

**Comment by fergadipa** [comment]
Never had before
But based on my searching result it should be like this `myProfile.setPreference('general.useragent.override', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36');
`

**Comment by wakaleo** [comment]
The problem is the semi-colon in the agent value. In the next version, you will be able to do this with the following configuration:
```
firefox.preferences=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36
firefox.preference.separator=&
```

**Comment by fergadipa** [comment]
Ok, thank you @wakaleo
