### ISSUE TITLE
is there any variable which holds testcase pass or fail status in serenity

### ISSUE THREAD

**Issue by ankitlodha** [serenity-bdd/serenity-core#913]
Is there any variable which holds testcase pass or fail status in serenity. Actually I need to mention the test case status as Review(for manual verification) instead of marking test case pass /fail.

Thanks

**Comment by wakaleo** [comment]
Do you mean you need to programmatically set the result to a different value?

**Comment by ankitlodha** [comment]
Yes. If I can get the variable name which stores the result value I think we will be able to do that

**Comment by wakaleo** [comment]
The results are stored as enum values, and each has a well-defined meaning, so you can't add new result statuses. You could however add a tag to indicate the tests that need reviewing, e.g.

```
        StepEventBus.getEventBus().addTagsToCurrentTest(ImmutableList.of(TestTag.withValue("Pending review")));
```

**Comment by wakaleo** [comment]
Presuming answered.
