### ISSUE TITLE
Serenity-junit how to make parallel execution?

### ISSUE THREAD

**Issue by AndriiChorniak** [serenity-bdd/serenity-core#916]
We use serenity with junit. Is the any flow to run tests in parallel? I will be very  appreciate for any suggestions or examples.

**Comment by wakaleo** [comment]
Have a look at the configuration in https://github.com/serenity-bdd/screenplay-pattern-todomvc/blob/master/pom.xml

**Comment by AndriiChorniak** [comment]
Thanks!

**Comment by stepantzov** [comment]
Hi John, what about Serenity+Jbehave?

**Comment by wakaleo** [comment]
The JBehave internals make it impossible to use the JBehave parallel features (fundamentally flawed design it seems). You can always run runner classes in parallel.

**Comment by stepantzov** [comment]
ok. thanks a lot!

**Comment by jetfree7** [comment]
Hi John, does exist any way to do parallel execution by methods, not by classes as in your example above. If  I set <parallel>methods</parallel> and <threadCount>3</threadCound> it will not work, much more instances of webdriver will be created and tests will be failed.

**Comment by HollyDa** [comment]
Hi John,

After upgrading jbehave and serenity versions, to incorporate @valfirst fixes, we can now run Jbehave tests in parallel just by setting the jbehave threads parameter, and get Serenity Reports, Hoorah!

Alas, the nested steps do not report, nor do we get screenshots. Our setup is a little odd, we are using a spring steps injector, where we override the createInstance method, so as to call the Serenity Dependency Injectors on the new instances. It works perfectly when we have the thread count = 1, but stops providing the details of nested steps and screen shots when we increase that number.

Are we completely on a hiding to nothing with the JBehave threads option, or is it worth our while at all to pursue making it work?

**Comment by fransiskusak** [comment]
Hi, @HollyDa do the nested steps still not reporting or the problem is solved already? Currently, I'm developing Jbehave test( based on (serenity-jbehave-archetype Maven) in parallel. It is not done yet and there is a problem in batching the tests into specified batches so that every browser execute completely all the same test, not in batch basis. I hope your view on my problem could help me to discover the solution of this problem. Thank you, best regards! 
Cc: @wakaleo

**Comment by wakaleo** [comment]
As far as I know my comments form earlier on in this thread still stand.
