### ISSUE TITLE
Remote driver does not work behind proxy

### ISSUE THREAD

**Issue by derkoe** [serenity-bdd/serenity-core#917]
The remote driver does not work behind a proxy server (event if proxy is set). The reason seems to be `RemoteDriverBuilder#ensureHostIsAvailableAt` which tries a direct socket connection and fails.

This issues exists since version 1.5 (1.5.0-rc.1 is the last known working version).

**Comment by wakaleo** [comment]
Good point. Could you propose a PR with a fix?

**Comment by derkoe** [comment]
Here you go #918

**Comment by rakeshnambiar** [comment]
Hi @wakaleo, @derkoe  .. Is this PR merged? I am facing the similar issue. Pls confirm.

Aiming to do something mentioned in the below article
https://loadfocus.com/blog/2014/06/02/how-to-pass-traffic-through-a-proxy-with-selenium-webdriver/

**Comment by wakaleo** [comment]
It was merged 21 days ago and would be included in versions 1.5.10 onwards.

**Comment by rakeshnambiar** [comment]
Thanks for the confirmation dear @wakaleo
