### ISSUE TITLE
Serenity.takeScreenshot() not working with Appium v1.3.7  

### ISSUE THREAD

**Issue by adeemotu** [serenity-bdd/serenity-core#92]
@wakaleo 

I am evaluating serenity framework with appium for our test automation reporting stuff. However i am unable to take screenshots using Serenity.takeScreenshot(); or configuration file methods. Also reports are generating OK, but with out screenshots. I wonder if i am missing some steps. Will be great to get some tips how to fix this.

One query, can i do "webdriver.driver = appium"  in properties file ! 

<serenity.version>[1.0.59]</serenity.version>
Appium v1.3.7

**Comment by wakaleo** [comment]
Are you getting any error messages? The next Serenity release will have an updated version of Appium which might fix this issue - you could see if this helps by updating the dependency to io.appium:java-client:3.1.0

**Comment by adeemotu** [comment]
nopes not getting any errors, i tried with io.appium:java-client:3.1.0 but still no luck. Here's how my properties files look like
[INFO] serenity.report.show.releases=false
[INFO] serenity.reports.show.step.details=true
[INFO] serenity.timeout=2000
[INFO] serenity.project.name=powered by iZettle
[INFO] serenity.take.screenshots=FOR_EACH_ACTION
[INFO] serenity.report.show.manual.tests=false

I wonder i need to mention some driver information as we do for webdriver e.g. "webdriver.driver = firefox" ?

**Comment by wakaleo** [comment]
Could be a driver problem. What device are you using?

**Comment by mvitiuk** [comment]
We were trying to use real android device Samsungs and Genymotion devices such as Nexus with OS Lollipop.

I've tried also with latest Selendroid server and same devices and latest versions of Serenity, jbehave - but still no screenshots and nothing in the logs.

**Comment by wakaleo** [comment]
See if you can get it working with raw Appium with the same versions.

**Comment by mvitiuk** [comment]
we are not using appium gui, we're starting server from terminal

**Comment by mihaiserdean** [comment]
Hello,

Can someone here maybe send me/attach a working sample project with Serentiy + Appium please? I would very much appreciate it.

Best regards,
Mihai Serdean

**Comment by mihaiserdean** [comment]
I would appreciate if you send me any sample project of a working Serenity + Appium on any native app

**Comment by mvitiuk** [comment]
@mihaiserdean we were using appium during winter, it wasn't intergrated with Serenity at that time, so we were starting server from code or command line.
Now everything looks much easier, you can specify appium related stuff in serenity.properties.
I haven't try that out, but a lot of people in community did. Have you try to search there? (https://groups.google.com/forum/#!topic/thucydides-users/I87qDVELuaY  for example)

**Comment by mihaiserdean** [comment]
@mvitiuk that is Serenity + Appium + Browser
I'm interested in making it work for Serenity + Appium + Native app (Emulator and/or Real Device)

Currently it is not working, gives null pointer exception in the @Steps

**Comment by mvitiuk** [comment]
@mihaiserdean I am now working on native app and selendroid, there is no null pointer exceptions, it works, but I don't know what exactly with your framework. Do you have sample project or logs?

**Comment by mihaiserdean** [comment]
can you remove your confidential code and just send me the project/configuration as a sample. So you are using Serenity + Selendroid + Native and not Appium?

**Comment by YamStranger** [comment]
Hello @adeemotu, @mvitiuk.  It seems that this issue already fixed, or not an issue now - so I close it. 

Thanks!

**Comment by hencian** [comment]
Hello how can I use Selendroid and produce test reports? - for appim I used Serenity but I don't know how to do it for Selendroid

**Comment by mvitiuk** [comment]
@hencian same way :), we were defining selendroid caps from code, not form serenity.properties. Check here http://selendroid.io/setup.html

**Comment by YamStranger** [comment]
@hencian, @mvitiuk This issue is closed

If you need Selendroid support - please create ticket with such request 

Thanks!
