### ISSUE TITLE
I'm trying to use this strategy and TC fails when cannot find first element.

### ISSUE THREAD

**Issue by livastar** [serenity-bdd/serenity-core#920]
@HowToUseLocators(androidAutomation = ALL_POSSIBLE)
@AndroidFindBy(id = "back_button")
@AndroidFindBy(uiAutomator = "new UiSelector().descriptionContains(\"Navigate up\")")
public WebElementFacade backButton;

**Comment by livastar** [comment]
I've tried to separate find strategy into 2 elements, find by id and find by uiautomator.

The thing is that separate I can find the 2nd element, 'cause it is present on the screen.

This means that @howtouselocators strategy doesn't work as expected.

**Comment by wakaleo** [comment]
Your best best is to dig into the code and to see how Appium uses this annotation and where/how it is/should be being invoked by Serenity.

**Comment by livastar** [comment]
@TikhomirovSergey :) will appreciate your input :)

**Comment by wakaleo** [comment]
@TikhomirovSergey, @livastar, @vikramvi - if you let me know your email addresses, I will add you to the Serenity Developers slack channel, which might make coordinating the Appium integration work easier.

**Comment by livastar** [comment]
ivanostanis@gmail.com,
@pisarenco92 - pisarencogrigore@gmail.​com

Thanks a lot @wakaleo
