### ISSUE TITLE
Serenity html report : "App" test

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#922]
Hello, 

With the Serenity aggregate report, I have a green "App" test in each execution (cf. screenshot).

![serenity report - app test](https://user-images.githubusercontent.com/29480659/30064041-dfd76de6-9250-11e7-8309-45ab05de4b5a.png)

I don't have any "App" .story or java class...
Do you know where it comes from, and how to disable it ? 

Thank you

**Comment by wakaleo** [comment]
Use serenity-core 1.5.9 or higher.

**Comment by mmanach** [comment]
I was on 1.5.5 and it solved the problem, thanks.
