### ISSUE TITLE
Error with appium

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#925]
Using the last version of serenity (1.5.9), I can't use appium annotations in pageObject, I always get NPE, if I use WebelemrntFacade I get NPE, Is serenity last version working with Appium?

**Comment by cliviu** [comment]
can you please post the NPE ?

**Comment by ricardorlg** [comment]
Hi, the NPE is about element doesn't loaded, changing the type to WebElementFacade using `@AndroidFindBy` i get `net.thucydides.core.pages.WrongPageError: The page object class com.test.serenity.appium.pages.NotePage looks dodgy:
Failed to instantiate page (java.lang.IllegalArgumentException: Can not set net.serenitybdd.core.pages.WebElementFacade field com.test.serenity.appium.pages.NotePage.noteTittle to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4)
`

**Comment by cliviu** [comment]
Strange, The only change that you have done is the new library  ? Which jdk version are you using ?

**Comment by ricardorlg** [comment]
I use Java 8, last version, I start the server by code and there is no error log. If  I use this in my pageObject

```
@AndroidBy(id="com.example.android.testing.notes:id/fab_add_notes")
    private WebElement addNoteButton;
```
I get NPE with the element, like serenity doesn't init the field.

**Comment by cliviu** [comment]
I'm not sure what is the problem, I cannot reproduce it. Can you please try to extend your PageObject from the following class, let me know if it helps : 
  ```
public class AppiumPageObject extends PageObject {
    public AppiumPageObject(WebDriver driver) {
        super(driver);
        PageFactory.initElements(new AppiumFieldDecorator(((WebDriverFacade) getDriver()).getProxiedDriver(),
                this.getImplicitWaitTimeout().in(TimeUnit.SECONDS), TimeUnit.SECONDS), this);
    }
}
 ```

**Comment by ricardorlg** [comment]
Using the last approach I didn't get the NPE anymore, but now the problem is with Jbehabe or Cucumber, only one scenario runs because when another scenario starts It tries to use the previous driver instance. I will open a new ticket for this, so this one can be close.
