### ISSUE TITLE
Missing artifacts when adding Serenity

### ISSUE THREAD

**Issue by PhuongLam94** [serenity-bdd/serenity-core#926]
Hi there,

I'm trying to build a test automation framework using Serenity. As I see in Maven repo, the latest version of Serenity is 1.5.10. But when I add this dependency to my project, there are a lot of errors telling that I'm missing some artifact. If I degrade the version to older one, everything is ok. Do I miss any configuration? Please help. Thank you.

This is my pom.xml: 
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.kms.kromotus</groupId>
  <artifactId>TestAutomation</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.5.10</serenity.version>
        <webdriver.driver>firefox</webdriver.driver>
    </properties>
    <repositories>
      <repository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
      </repository>
    </repositories>
    <pluginRepositories>
      <pluginRepository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray-plugins</name>
        <url>http://jcenter.bintray.com</url>
      </pluginRepository>
    </pluginRepositories>
    
    <dependencies>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.8.0</version>
        </dependency>
  	<dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <includes>
                        <include>**/*Story.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

And this is some first rows of errors (there are 161 errors like these):
Description	Resource	Path	Location	Type
Missing artifact aopalliance:aopalliance:jar:1.0	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact cglib:cglib:jar:3.2.5	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.beust:jcommander:jar:1.48	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.codeborne:phantomjsdriver:jar:1.4.3	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.fasterxml:classmate:jar:1.0.0	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.google.code.findbugs:jsr305:jar:1.3.9	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.google.code.gson:gson:jar:2.8.0	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.google.errorprone:error_prone_annotations:jar:2.0.18	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.google.guava:guava:jar:22.0	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.google.inject:guice:jar:4.1.0	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.google.j2objc:j2objc-annotations:jar:1.1	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.google.jimfs:jimfs:jar:1.1	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.google.protobuf:protobuf-java:jar:2.4.1	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.ibm.icu:icu4j:jar:58.1	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.jhlabs:filters:jar:2.0.235	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.openhtmltopdf:openhtmltopdf-core:jar:0.0.1-RC9	pom.xml	/TestAutomation	line 1	Maven Dependency Problem
Missing artifact com.openhtmltopdf:openhtmltopdf-jsoup-dom-converter:jar:0.0.1-RC9	pom.xml	/TestAutomation	line 1	Maven Dependency Problem

**Comment by wakaleo** [comment]
This looks like a Maven issue - try deleting your local repository and doing a clean build.

**Comment by wakaleo** [comment]
I'm assuming you sorted this out - otherwise feel free to reopen or post questions on Google Groups.
