### ISSUE TITLE
Mark test as ignored in Serenity Test Report with custom @ConditionalIgnore flag

### ISSUE THREAD

**Issue by monkeyjabs** [serenity-bdd/serenity-core#93]
If my test framework uses a customized @ConditionalIgnore instead of the @Ignore tag. What needs to be done in order to make the Serenity report show the test case with gray instead of passing?

**Comment by wakaleo** [comment]
That would be tricky - what does your @ConditionalIgnore do exactly?

On 17 July 2015 at 09:54, Clyde Sy <notifications@github.com> wrote:

> If my test framework uses a customized @ConditionalIgnore instead of the
> @Ignore <https://github.com/Ignore> flag. What needs to be done in order
> to make the Serenity report show the test case with gray instead of passing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/93>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by monkeyjabs** [comment]
The @ConditionalIgnore allow me to ignore a test case based on a matching condition. For example, ignore this test case if it is only running on Safari browser but run on all other browsers.

The implementation detail his here: https://gist.github.com/rherrmann/7447571

**Comment by YamStranger** [comment]
It seems that this question already answered, and @monkeyjabs already find solution

**Comment by BushnevYuri** [comment]
@monkeyjabs We tried this approach and it works well with maven (it shows it as ignored) but serenity report shows it as green. Could you make it work with serenity as well?
