### ISSUE TITLE
[Question] Reason of java.lang.NoSuchMethodError: com.beust.jcommander.internal.Lists.newArrayList([Ljava/lang/Object;)Ljava/util/List

### ISSUE THREAD

**Issue by a-en** [serenity-bdd/serenity-core#932]
Hi,

it is rather question than a defect. I'm trying to run some mobile tests with Appium on Amazon Device Farm. For that purpose, I have to put everything in .zip file, then upload it & run.
I'm constantly getting the error, even if locally everything works fine (I have tried to run tests locally from jars to make it as closer as possible).

I have checked jcommander dependency and the method is there.

Serenity ver is 1.5.10

@wakaleo , do you have any insights about the potential reason for that?

`<failure type="java.lang.NoSuchMethodError" message="com.beust.jcommander.internal.Lists.newArrayList([Ljava/lang/Object;)Ljava/util/List;">
      <![CDATA[java.lang.NoSuchMethodError: com.beust.jcommander.internal.Lists.newArrayList([Ljava/lang/Object;)Ljava/util/List;
	at net.thucydides.core.model.screenshots.ScreenshotPreferencesByClass.interfacesFrom(ScreenshotPreferencesByClass.java:86)
	at net.thucydides.core.model.screenshots.ScreenshotPreferencesByClass.getSuperClassesAndInterfacesFrom(ScreenshotPreferencesByClass.java:78)
	at net.thucydides.core.model.screenshots.ScreenshotPreferencesByClass.getScreenshotPreference(ScreenshotPreferencesByClass.java:59)
	at net.thucydides.core.model.screenshots.ScreenshotPermission.overriddenScreenshotPreferenceForClass(ScreenshotPermission.java:73)
	at net.thucydides.core.model.screenshots.ScreenshotPermission.classOverride(ScreenshotPermission.java:66)
	at net.thucydides.core.model.screenshots.ScreenshotPermission.areAllowed(ScreenshotPermission.java:32)
	at net.thucydides.core.steps.BaseStepListener.shouldTakeEndOfStepScreenshotFor(BaseStepListener.java:853)
	at net.thucydides.core.steps.BaseStepListener.takeEndOfStepScreenshotFor(BaseStepListener.java:720)
	at net.thucydides.core.steps.BaseStepListener.stepFailed(BaseStepListener.java:633)
	at net.thucydides.core.steps.StepEventBus.stepFailed(StepEventBus.java:356)
	at net.thucydides.core.steps.StepInterceptor.notifyOfStepFailure(StepInterceptor.java:462)
	at net.thucydides.core.steps.StepInterceptor.logStepFailure(StepInterceptor.java:372)`

**Comment by wakaleo** [comment]
It looks like a dependency error related to the jcommander library. Not sure why it's not happening locally though.

**Comment by wakaleo** [comment]
Could you try with 1.5.12?

**Comment by David-Paterson** [comment]
Hi,

I am also trying to get serenity working on the device farm, from what I can see the issue relates to TestNG being used to run the tests on the device farm, even if the **JUnit** framework only is selected.

```
[TestNG] Running:
  Command line suite

[main] INFO net.serenitybdd.core.Serenity - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
-------------------------------------------------------------------------------------

[main] INFO net.serenitybdd.core.Serenity - Test Suite Started: Login story
[main] INFO net.serenitybdd.core.Serenity - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: login_should_work_when_given_valid_credentials
-------------------------------------------------------------------
[main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
[main] ERROR net.serenitybdd.core.Serenity - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: Login should work when given valid credentials
---------------------------------------------------------------------
[main] ERROR net.serenitybdd.core.Serenity - com.beust.jcommander.internal.Lists.newArrayList([Ljava/lang/Object;)Ljava/util/List;
[pool-1-thread-1] INFO net.thucydides.core.reports.json.JSONTestOutcomeReporter - Generating JSON report for Login should work when given valid credentials to file /tmp/scratchnpgF2x.scratch/test-packageETJ5vJ/target/site/reports/com.strada.assurance.mobile.features.security.loginstory_login_should_work_when_given_valid_credentials.json (using temp file /tmp/scratchnpgF2x.scratch/test-packageETJ5vJ/target/site/reports/com.strada.assurance.mobile.features.security.loginstory_login_should_work_when_given_valid_credentials.jsona3469ad7-2984-4fbe-8ebb-1fc7aa60c34f)
[pool-2-thread-1] INFO net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR Login story:login_should_work_when_given_valid_credentials in com.strada.assurance.mobile.features.security.loginstory_login_should_work_when_given_valid_credentials.html in directory target/site/reports  

===============================================
Command line suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

I did discover an issue raised a while back with the same conflicting dependency.

To confirm this I added a dependency on JCommander version 1.30 (as used by Ascii Doctor 0.1.4) into the pom which results in a test run which never completes and as no results are returned all I can assume is that the TestNG runner never starts.

The version of JCommander used in TestNG (6.3.1) is 1.12 when I change the dependency version the TestNG runner works but the issue reappears (as above).

I have repeated these tests using version 1.5.12 of Serenity, same result.

**Comment by a-en** [comment]
@David-Paterson, do you want to try with 1.6.0? I'm trying from my side and for now I don't see the original error.

**Comment by wakaleo** [comment]
Serenity 1.5.12 has no direct dependency on JCommander. The only indirect one I can see is on selenium-server (version 1.48):

```
> Task :serenity-core:dependencyInsight
com.beust:jcommander:1.48
\--- org.seleniumhq.selenium:selenium-server:3.5.3
     \--- compileClasspath
```

But I'm confused as to why you are talking about TestNG - TestNG isn't supported by Serenity.

**Comment by David-Paterson** [comment]
Sorry to be more clear, the reason TestNG is important is that the Amazon Device Farm uses it to execute JUnit based projects.

I understand that attempting to get Serenity to support TestNG is not a small feat! but it appears to be a large hurdle to running the Serenity framework on the Device Farm!

This is something I'm very keen to do as the farm is excellent for getting true device testing (without the massive headache of maintaining your own devices) but it does not support a java based acceptance testing framework!

There is support for Calabash and Ruby's great :) but the reporting from Serenity IMHO is considerably better and together with the support for Screenplay Pattern it looks like an excellent fit.

I am unable to change the TestNG version at the moment, but I will try to get some more information as to what's the class loader is finding.

**Comment by wakaleo** [comment]
In any case, the JCommander issue is not directly related to Serenity (Serenity 1.6.0 does not use JCommander directly anywhere); so if you are getting errors related to JCommander classes with Serenity stack traces, you may not be using the latest version of Serenity.

**Comment by David-Paterson** [comment]
It works using version 1.6.0 no more dependency issue 👍

**Comment by wakaleo** [comment]
Excellent - I will close the issue then.
