### ISSUE TITLE
Update from Serenity 1.5.3 to > 1.5.5 broke - webdriver.provided.type

### ISSUE THREAD

**Issue by dgracehmh** [serenity-bdd/serenity-core#933]
Hi, 

In my Serenity setup I use Custom Drivers (implementing DriverSource) and specify them in my pom file

```<plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${maven.failsafe.plugin.version}</version>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/failsafe-reports/e2e</reportsDirectory>
                            <summaryFile>${project.build.directory}/failsafe-reports/e2e/failsafe-summary.xml
                            </summaryFile>
                            <forkCount>1</forkCount>
                            <reuseForks>false</reuseForks>
                            <argLine>-XX:MaxPermSize=2G</argLine>
                            <failIfNoTests>false</failIfNoTests>
                            <skipITs>false</skipITs>
                            <includes>
                                <include>${failsafe.testrunner}</include>
                            </includes>
                            <parallel>classes</parallel>
                            <threadCount>${parallel.tests}</threadCount>
                            <forkCount>${parallel.tests}</forkCount>
                            <systemPropertyVariables>
                                <webdriver.driver>provided</webdriver.driver>
                                <webdriver.provided.type>mydriver</webdriver.provided.type>
                                <webdriver.provided.mydriver>com.xxx.xxx.customdrivers.CustomChromeDriver
                                </webdriver.provided.mydriver>
                                <serenity.driver.capabilities>provided
                                </serenity.driver.capabilities>
                            </systemPropertyVariables>


                        </configuration>

                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
```
In my serenity.properties file I comment these out
```
#webdriver.driver = provided
#webdriver.provided.type = mydriver
#webdriver.provided.mydriver = com.xxxx.xxxx.customdrivers.CustomChromeDriver
#serenity.driver.capabilities = provided
```
This all worked fine until I updated from 1.5.3 to 1.5.5, when I get this error

net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for LoginPageSteps:Failed to create step library for HmofHomePage:No provider type was specified in 'webdriver.provided.type'

So it looks like something changed between 1.5.3 and 1.5.5 that prevents us using  <systemPropertyVariables> to specify Custom Drivers

**Comment by wakaleo** [comment]
I don't recall anything changing at that level for some time now. Try placing a breakpoint in the getDriverSource() method of the ProvidedDriverConfiguration class to see if anything unusual is happening.

**Comment by dgracehmh** [comment]
I went through the commits between 1.5.3 and 1.5.5, the only one that looks like it might be interesting is this one - https://github.com/serenity-bdd/serenity-core/commit/96ba9a31a1d8503622793dfbe494105de16e5ddd

I am not familiar with the Serenity code but that could be the culprit..

**Comment by wakaleo** [comment]
That change is a required fix for an Appium issue; not sure how it would be related, but put a breakpoint there and see if the code ends up there might be one way to check.

**Comment by dgracehmh** [comment]
I added some breakpoints and found that in 
1.5.3
ProvidedDriverConfiguration ->``` public DriverSource getDriverSource()``` Is never called

1.5.5
ProvidedDriverConfiguration -> ```public DriverSource getDriverSource()``` is called but
```String providedDriverType = getDriverName();``` -> null
therefore it exits on next line
```Preconditions.checkNotNull(providedDriverType, "No provider type was specified in 'webdriver.provided.type'");```

Let me know if there is any more info I can help with.

**Comment by wakaleo** [comment]
This would mean that Serenity is not finding the webdriver.provided.type value in your serenity.properties file.

**Comment by dgracehmh** [comment]
Yes, before 1.5.5 i just needed this in my pom file (commented out in serenity.properties)
```
<systemPropertyVariables>
            <webdriver.remote.driver>chrome</webdriver.remote.driver>
            <webdriver.remote.url>${webdriver.remote.url}</webdriver.remote.url>
 </systemPropertyVariables>
```

After 1.5.5 i need to specify

```
<systemPropertyVariables>
        <webdriver.remote.driver>chrome</webdriver.remote.driver>
        <webdriver.remote.url>${webdriver.remote.url}</webdriver.remote.url>
        <webdriver.driver>provided</webdriver.driver>
        <webdriver.provided.type>mydriver</webdriver.provided.type>
        <webdriver.provided.mydriver>com.hmhco.hmof.customdrivers.CustomChromeDriver
        </webdriver.provided.mydriver>
        <serenity.driver.capabilities>provided</serenity.driver.capabilities>
</systemPropertyVariables>
```

So I have a fix, not sure how it might affect others.
Thanks for your help and hard work on Serenity, fantastic tool!

**Comment by wakaleo** [comment]
Yes, it must be reading the value from the surefire process now, so it needs to be passed explicitly. Glad we got to the bottom of it!

**Comment by dgracehmh** [comment]
Sorry, Just noticed that with the above solution I am not getting screenshots anymore in my Serenity reports.

When I take all the driver stuff out of my pom and just use serenity.properties, i.e. I want to run on Grid
```
webdriver.remote.url=http://localhost:4444/wd/hub
webdriver.remote.driver=chrome
```

I still get the error
```
Failed to create step library for HmofHomePage:No provider type was specified in 'webdriver.provided.type'
```
To get it to work using serenity.properties i need
```
webdriver.remote.url=http://localhost:4444/wd/hub
webdriver.remote.driver=chrome
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.hmhco.hmof.customdrivers.CustomChromeDriver
serenity.driver.capabilities = provided
```
But again, I do not get screenshots..

So i think there is an issue here that was introduced between 1.5.3 -> 1.5.5

**Comment by wakaleo** [comment]
Are you using the latest chromedriver binary?

**Comment by dgracehmh** [comment]
I am using the latest, I use the Selenium Docker images from here - https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.5.3-boron
```
        <serenity.version>1.5.11</serenity.version>
        <serenity.cucumber.version>1.5.7</serenity.cucumber.version>
        <selenium.version>3.5.3</selenium.version>
        <serenity.maven.version>1.5.11</serenity.maven.version>
        <maven.failsafe.plugin.version>2.20</maven.failsafe.plugin.version>
        <maven.compiler.plugin>3.6.1</maven.compiler.plugin>
```

As always, let me know what I can do to help.

**Comment by wakaleo** [comment]
Put a breakpoint in the Photographer class and see if you can drill down to see what it is doing.

**Comment by dgracehmh** [comment]
Did a bit of debugging and I see the problem is in 
```
WebDriverFacade.java
-> driverCanTakeScreenshots()
	-> return (TakesScreenshot.class.isAssignableFrom(getDriverClass()));
		-> getDriverClass()
			-> return new ProvidedDriverConfiguration(environmentVariables).getDriverSource().driverType(); // This is returning null
```

In 1.5.3
```
private boolean driverCanTakeScreenshots() {
        return (TakesScreenshot.class.isAssignableFrom(getProxiedDriver().getClass()));
}
This returns true
```
In 1.5.11 - this method has changed
```
private boolean driverCanTakeScreenshots() {
        return (TakesScreenshot.class.isAssignableFrom(getDriverClass()));
}
```
And is now returning null

**Comment by wakaleo** [comment]
Can you provide a sample project for this issue?

**Comment by dgracehmh** [comment]
I'll have it in the morning for you.

**Comment by dgracehmh** [comment]
Sorry for the delay, find repro project here - https://github.com/dgracehmh/serenitysample

To run tests via maven ```mvn clean verify -P int -P local```

**Comment by wakaleo** [comment]
Thanks for the sample project. This is fixed with the following versions:

```
        <serenity.version>1.6.0</serenity.version>
        <serenity.cucumber.version>1.5.8</serenity.cucumber.version>
        <selenium.version>3.5.3</selenium.version>
        <serenity.maven.version>1.6.0</serenity.maven.version>
```
