### ISSUE TITLE
Log level for firefox/gecko capabilities in serenity.properties

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#935]
Hello, 

Currently, the default log level for geckodriver seems to be "DEBUG" 
```
1505915407498	Marionette	INFO	Listening on port 52508
1505915408158	Marionette	WARN	TLS certificate errors will be ignored for this session
1505915408207	Marionette	DEBUG	loaded listener.js
sept. 20, 2017 3:50:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFOS: Detected dialect: W3C
1505915408341	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1505915408777	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1505915408778	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
```

I tried to modify geckodriver log level to TRACE in serenity.properties : 

- serenity.driver.capabilities = {"moz:firefoxOptions": {"log": {"level": "trace"}}};
- firefox.preferences= --log trace    //-vv 

But none seems to work. 

Is it the right way ?

**Comment by wakaleo** [comment]
Do you know if gecko supports these options?

**Comment by mmanach** [comment]
I think so :

- https://github.com/mozilla/geckodriver/issues/152#issuecomment-239446073
- https://github.com/mozilla/geckodriver/issues/152#issuecomment-254191781
- https://github.com/mozilla/geckodriver => capabilities part

**Comment by mmanach** [comment]
Hi @wakaleo ,

Having to provide a geckodriver trace for this issue (https://github.com/mozilla/geckodriver/issues/962#issuecomment-338136297), I dipped back into this problem.

So for the serenity.properties, it seems that this format is correct : 
https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
```
serenity.driver.capabilities={"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"log": {"level": "trace"}}}}}
```
For information, I tested the line below with FF 57 beta, and it works. 
```
#serenity.driver.capabilities={"capabilities": {"alwaysMatch": {moz:webdriverClick":"true"}}}
```

But for the geckodriver trace, in the console I only get few information, and not all the traces.

I only succeeded to get all logs with this implementation : http://thucydides.info/docs/serenity-staging/#_custom_webdriver_implementations

```
public class MyFirefoxDriver implements DriverSource {

        @Override
        public WebDriver newDriver() {
            FirefoxOptions options = new FirefoxOptions();
            options.setLogLevel(Level.ALL);

            return new FirefoxDriver(options);
        }

    @Override
    public boolean takesScreenshots() {
        return false;
    }

}
```

**Comment by wakaleo** [comment]
Thanks for your research into this. If you need to set the log levels programmatically, a custom driver would be the best option for now. Longer term you could propose a PR for the FirefoxDriverCapabilities class to do this in a more configurable way.

**Comment by cvarshn-cloud** [comment]
you can use options in serenity properties like below:

gecko.firefox.options={"args": ["-headless"], "log": {"level": "info"}, "prefs": {"dom.ipc.processCount": 8,"javascript.options.showInConsole": false}}
