### ISSUE TITLE
io.appium.java_client.AppiumDriver (Unrecognized platform: iOS

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#937]
<serenity.version>1.5.11</serenity.version>

webdriver.driver= appium
appium.hub = http://localhost:4723/wd/hub
####### iOS CAPS ######
appium.automationName = XCUITest
appium.platformName = iOS
appium.platformVersion = 10.3
appium.deviceName  = iPhone 7
appium.app =  /Users/vikramanna/Documents/vikram/AppiumSerenityPOC/WordPress.app

It does work with **Android** but is failing with **iOS** only

Error
```

Sep 21, 2017 2:48:04 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class io.appium.java_client.AppiumDriver: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (Unrecognized platform: iOS
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'Vikrams-MBP.fritz.box', ip: 'fe80:0:0:0:a3:8a17:f1bb:602e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: unknown
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (Unrecognized platform: iOS
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'Vikrams-MBP.fritz.box', ip: 'fe80:0:0:0:a3:8a17:f1bb:602e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: unknown
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:135)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:148)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:139)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:109)
```

As per **WhenConfiguringAnAppiumDriver.groovy**

_should derive the target platform from the environment properties_ 
  tried _IOS, iOS, ios_ but none of these worked and getting same error

The app does get installed on the iOS simulator but later script throws error, checked the appium logs & it looks fine with session getting created successfully

**Comment by wakaleo** [comment]
Put a breakpoint in AppiumDriverProvider and see what it is doing.

**Comment by vikramvi** [comment]
Please refer to attached screen shots, am not sure why Selenium is throwing this exception

<img width="1432" alt="screen shot 2017-09-22 at 4 58 49 pm" src="https://user-images.githubusercontent.com/308490/30750719-87ae2d02-9fb7-11e7-9fe2-5866c8622468.png">

<img width="1265" alt="screen shot 2017-09-22 at 4 59 53 pm" src="https://user-images.githubusercontent.com/308490/30750727-8e926d36-9fb7-11e7-84b9-367bf1bb5876.png">

**Comment by vikramvi** [comment]
may be related to https://github.com/appium/appium/issues/9042

**Comment by wakaleo** [comment]
It's something that is going on in the Selenium code, on line 46 of the Capabilities code. Visually it looks like it should work, but it is not matching "iOS" to the Platform enum value. Try stepping into the Selenium code to see what it is failing to match.

**Comment by vikramvi** [comment]
Issue has got fixed with https://github.com/serenity-bdd/serenity-core/pull/940

I'll add more details to this from debugging learnings and close later
