### ISSUE TITLE
@skip not working in the latest version of serenity

### ISSUE THREAD

**Issue by jaspreetmanchinda** [serenity-bdd/serenity-core#938]
I have updated my project to latest serenity version 1.5.11 but @skip in feature file is not working neither @manual is working 
below is the screenshot of feature file and report 

![image](https://user-images.githubusercontent.com/26487567/30699661-f551d9ae-9f02-11e7-91a8-8de60a46a96a.png)
 
![image](https://user-images.githubusercontent.com/26487567/30699695-0b42988e-9f03-11e7-9571-2e27bb85e975.png)

Adding a sample project too as zip
[random.zip](https://github.com/serenity-bdd/serenity-core/files/1321457/random.zip)

Please let me know if u require any additional details

**Comment by jaspreetmanchinda** [comment]
@wakaleo  any updates on this issue?

**Comment by wakaleo** [comment]
Should be fixed in 1.6.0 of serenity-core and 1.1.29 of serenity-jbehave.

**Comment by jaspreetmanchinda** [comment]
Tests are getting skipped but in case if there is a pending step in scenario with @skip or @manual that scenario is going in pending column in report . 
If the scenario is just marked with @Manual with all steps mapped then its getting added in automated test and even the steps are getting executed.

**Comment by jaspreetmanchinda** [comment]
issue is partially solved, so issue should be reopened.

**Comment by wakaleo** [comment]
@Manual steps should be skipped (executed in "dry-run" mode) in the next version.
Note that @Skip and @Pending are not designed to be used together, as they mean different things - @Skip means "don't run this test now" and @Pending means "work-in-progress". If you put both on the same test, @Pending takes priority.

**Comment by jaspreetmanchinda** [comment]
By pending what I meant was step is not mapped and if I skip that test case then in serenity report it is showing as pending and not skipped

**Comment by wakaleo** [comment]
Gotcha. In Serenity, a scenario with undefined step definitions is always marked as pending - skipped only applies to tests that would otherwise run. If you want to skip it in the sense of not having it appear in the reports at all, you would need to use metafilters.

**Comment by jaspreetmanchinda** [comment]
I want those scenarios in report but as skipped and not pending, in previous versions it use to work just fine.
