### ISSUE TITLE
The report cannot show the Japanese / Vietnamese characters

### ISSUE THREAD

**Issue by giangnd2508** [serenity-bdd/serenity-core#939]
The serenity report has a problem with showing the Japanese or Vietnamese font. Please check it. 
![fecd48b1785ca671b4c301612df721133766e62e0de79507fb pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/20058331/30768992-f1f5e758-a03a-11e7-8a45-1b2e677d9aef.png)

**Comment by wakaleo** [comment]
Looks like an encoding issue. Try setting the serenity.report.encoding value in your serenity.properties file to whatever you usually use (the default is UTF-8).

**Comment by giangnd2508** [comment]
Thanks for instant supporting. :D I can see japanese characters now.

**Comment by giangnd2508** [comment]
![10-06-2017 1-29-20 pm](https://user-images.githubusercontent.com/20058331/31265729-7c45202c-aa9a-11e7-971c-0c54b60d2820.png)
Sorry. I miss check this carefully.

**Comment by giangnd2508** [comment]
On Steps: It looks fine but on Senarios: It cannot show japanese.

**Comment by wakaleo** [comment]
I think Markdown doesn't support Japanese characters. Try putting this in your `serenity.properties` file:
```
enable.markdown=none
```

**Comment by giangnd2508** [comment]
Thanks. I'll try it out.

**Comment by giangnd2508** [comment]
Nothing changes. Please check it.

**Comment by wakaleo** [comment]
If you can provide a sample project that reproduces the issue we will take a look as soon as someone gets a chance. PRs are welcome.

**Comment by giangnd2508** [comment]
@wakaleo I push a sample project here: https://github.com/giangnd2508/demo-serenity

**Comment by wakaleo** [comment]
Try setting feature.file.encoding = utf8 in your serenity.properties file.

**Comment by giangnd2508** [comment]
wow, thank you. It actually works. :)
