### ISSUE TITLE
Serenity and Sikuli integration

### ISSUE THREAD

**Issue by ankitlodha** [serenity-bdd/serenity-core#942]
Hi,

Wanted to check if Serenity is integrated with Sikuli as we need to automate putty window which is windows object

**Comment by wakaleo** [comment]
No, it doesn't. But if you can call Sikuli in Java you could most likely write your own integration using Screenplay fairly easily.

**Comment by ankitlodha** [comment]
Hi,

I am not familiar with Screenplay in serenity but as Sikuli is integrated with Selenium I can call Selenium function directly within Serenity.

**Comment by ankitlodha** [comment]
I am using Serenity.takeScreenshot to capture the screenshot of putty window. But somehow it is not working.
Is there any method available to take desktop screenshot in Serenity

**Comment by wakaleo** [comment]
Serenity.takeScreenshot() calls WebDriver to take a screenshot of the current browser; WebDriver cannot take screenshots of the desktop.

**Comment by wakaleo** [comment]
Presuming answered.
