### ISSUE TITLE
browser logs with chrome.switches

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#943]
Hello, 

- Windows 10
- serenity 1.5.9

I'm trying to get chrome's logs.

Regarding :

- https://johnfergusonsmart.com/configuring-chromedriver-easily-with-serenity-bdd/
and
- https://sites.google.com/a/chromium.org/chromedriver/logging

It just seems enough to add:
```
chrome.switches =  --verbose; --log-path=D:\\chromedriver.log;
```
In serenity.properties, but it does not generate any file. Yet, the option --incognito; passed by this way is working well.

Any idea ? Thanks !

Note : 
In serenity.properties, I tried this already too : 
```
chrome_preferences.webdriver.chrome.verboseLogging=true
chrome_preferences.webdriver.chrome.logfile=C:\\chromedriver.log
```

**Comment by wakaleo** [comment]
Using chrome.switches the way you mentioned above passes the value correctly to the ChromeDriver instance, so it may be an issue with the driver itself.

**Comment by wakaleo** [comment]
Closed for lack of activity.
