### ISSUE TITLE
Lifecycle before after not working in latest version

### ISSUE THREAD

**Issue by jaspreetmanchinda** [serenity-bdd/serenity-core#944]
Hi,
I am using serenity version as below,
<serenity.version>1.5.11</serenity.version>
<serenity.jbehave.version>1.28.0</serenity.jbehave.version>
But when i mention a step in  lifecycle or background in feature file then those steps are not getting executed,

eg:- 

lifecycle:
Before:
Given some step
or
Background: 
Given some step

**Comment by wakaleo** [comment]
I just added the following smoke test for serenity-core 1.6.0 and serenity-jbehave 1.1.29, which appears to work:
```
A scenario that uses lifecycle phases

Lifecycle:
Before:
Given I have a calculator
And I add 1

Scenario: Add a number
When I add 2
Then the total should be 3
```

Could you provide a sample project to reproduce your issue?

**Comment by jaspreetmanchinda** [comment]
I tried it on 
<serenity.version>1.5.11</serenity.version>
<serenity.jbehave.version>1.28.0</serenity.jbehave.version>

and versions mentioned by you are not available on maven repository.
Can you please check with the mentioned version or update the latest version on maven

**Comment by wakaleo** [comment]
The latest version is available on jcenter, and should be synced with Maven within 24 hours or so.

**Comment by wakaleo** [comment]
(For reference, new versions always go to JCenter first)

**Comment by jaspreetmanchinda** [comment]
I'll try with the newer version, but always updating the versions after implementation is not a good idea as there would be version conflict issues with other dependencies too.

**Comment by wakaleo** [comment]
As a general rule, the before and after lifecycles are buggy in JBehave, so many features that are doable in Cucumber are difficult in JBehave.

**Comment by wakaleo** [comment]
Did you get this working with serenity-core 1.6.0?

**Comment by jaspreetmanchinda** [comment]
The step mentioned in lifecycle before is getting executed but build is getting failed. If i remove the lifecycle before from feature file then build is not failing,
Attaching the error log
[errorlogSerenity.txt](https://github.com/serenity-bdd/serenity-core/files/1339508/errorlogSerenity.txt)

**Comment by wakaleo** [comment]
The error seems to indicate a bug in the JUnit or JBehave code, or possibly in the test itself, so I would need to see a sample project reproducing the issue.

**Comment by jaspreetmanchinda** [comment]
you can try the same in https://github.com/serenity-bdd/serenity-core/files/1321457/random.zip.
Just update the pom with latest version and add below in feature file,

Narrative:
As a abc
I want to abc
So that abc

Lifecycle: 
Before:
Given abc


I wont be able to send sample project now as I am behind org firewall. Please let me know if you are able to reproduce with the sample mentioned above.

**Comment by wakaleo** [comment]
An error does occur when the Given is in the Before section and the When is undefined, and when the scenario is run via Maven (it works correctly with Gradle). It appears to be a bug in the maven surefire integration with https://github.com/valfirst/jbehave-junit-runner. I will raise an issue here when I have time, but for now there's nothing I can do in the Serenity code.

**Comment by jaspreetmanchinda** [comment]
Working fine in 		
<serenity.version>1.6.1</serenity.version>
<serenity.jbehave.version>1.30.0</serenity.jbehave.version>
