### ISSUE TITLE
Appium Behaviour Different from WebDriver SendKeys

### ISSUE THREAD

**Issue by David-Paterson** [serenity-bdd/serenity-core#945]
When using EnterValue action the first call to sendKeys works and the value is entered correctly.

However, the second call to sendKeys using an empty followedByKeys list blanks the correct value entered.

```
    @Step("{0} enters '#theText' into #target")
    public <T extends Actor> void performAs(T theUser) {
        target.resolveFor(theUser).sendKeys(theText);
        target.resolveFor(theUser).sendKeys(getFollowedByKeys());

    }

```

I have tried adding Key Up, Key Right, Tab and Enter all replace the correct value with an undisplayable character. 

My action:

```
 actor.wasAbleTo(
	 Enter.theValue(userName).into(LoginTargets.USERNAME_FIELD),
	 Enter.theValue(password).into(LoginTargets.PASSWORD_FIELD),
	 Click.on(LoginTargets.LOGIN_BUTTON)
 );

```

Work-around:

```
WebDriver driver = BrowseTheWeb.as(actor).getDriver();

driver.findElement(By.id("com.bjss.mymapp.debug:id/edit_username")).sendKeys(userName);
driver.findElement(By.id("com.bjss.mymapp.debug:id/edit_password")).sendKeys(password);
driver.findElement(By.id("com.bjss.mymapp.debug:id/button_login")).click();

```

Platform: Android
Serenity: 1.6.0
Appium: 1.6.5

**Comment by wakaleo** [comment]
Is the issue when getFollowedByKeys() returns an empty list, or when you provide a value?

**Comment by David-Paterson** [comment]
It happens for both. 

If the list is empty it blanks the value completely.

If the list contains a Key such as Right or Tab or Return, the value is replaced by an undisplayable char.

**Comment by wakaleo** [comment]
Could you try with this action instead:
```
public class EnterValueIntoTarget extends EnterValue {

    private Target target;

    public EnterValueIntoTarget(String theText, Target target) {
        super(theText);
        this.target = target;
    }

    @Step("{0} enters '#theText' into #target")
    public <T extends Actor> void performAs(T theUser) {
        target.resolveFor(theUser).type(theText);
        if (getFollowedByKeys().length > 0) {
            target.resolveFor(theUser).sendKeys(getFollowedByKeys());
        }
    }
}
```

**Comment by David-Paterson** [comment]
That works locally and on the device farm 👍

**Comment by David-Paterson** [comment]
Sorry I've purged the dependencies and the behaviour has been corrected (no patch required).

**Comment by David-Paterson** [comment]
Sorry was closed in error.

**Comment by David-Paterson** [comment]
Sorry, John

      The change to using type method rather than sendKeys exposes a different problem, which I spotted whilst looking for a work-around.

      If the type method is called it sets focus on the control first, which is fine in webdriver but not in appium as it causes the keyboard to popup.

      If possible could it be reverted to the sendKeys call?

**Comment by wakaleo** [comment]
So this is an issue with the Appium Driver?

**Comment by David-Paterson** [comment]
It may well be, not sure as I get the inconsistent result using both the action and the work-around.

Anyway, the original issue is fixed thanks :)

**Comment by wakaleo** [comment]
It will be in the next release :-)

**Comment by David-Paterson** [comment]
I have found that setting the following prevents the soft keyboard from being displayed on Android not sure if it works for iOS.

`serenity.driver.capabilities="unicodeKeyboard:true;resetKeyboard:true"`
