### ISSUE TITLE
Cannot set useAutomationExtension setting for chromedriver

### ISSUE THREAD

**Issue by mrynduch** [serenity-bdd/serenity-core#949]
Hi,

Im trying to set experimental option for chromedriver, my serenity.conf looks like that:

`chrome_preferences {
    useAutomationExtension = "false"
}`

However its not working. I did a short investigation before adding an issue.

When debugging getCapabilities method  I can see that wrong experimentalOptions are passed to driver:

`"chrome_preferences.useAutomationExtension" -> false`

Looking into code:

In ChromeDriverCapabilities.java addPreferencesTo() is creating passing "chrome_preferences." as a prefix. 

In ChromePreferences.java. The replace() method is trying to find "chrome_prefrences." + the additional dot. I think that this dot is redundant and the cause of the problem.

`    private String getPreparedPropertyKey(String propertyKey) {
        return propertyKey.replace(prefix + ".","");
    }`

Kind Regards,
Michal

**Comment by wakaleo** [comment]
What version are you using? That code was fixed several versions back.

**Comment by mrynduch** [comment]
That's right! Thanks.

**Comment by ShaliniSujith** [comment]
Hi mryndunch,

I am facing the above mentioned issue. While running the cases I am getting a popup - unable to load extension and I am trying to disable it by mentioning below in serenity.properties file

chrome_preferences.useAutomationExtension = false

But nothing is happening. 

Can you please suggest what version or how you have solved it. 

Thanks, 
shalini

**Comment by mbn217** [comment]
I have the same issue when I try to open chrome with selenium and navigate to regular website After I click on the popup that I attached then chrome crashes.
I have tried most of everything i found online but nothing worked. Im using selenium 3.11.0 , Chrome driver 2.37 and chrome Version 65.0.3325.181 (Official Build) (64-bit). 
Please any help with be much appreciated.
Im using java for this and the code is :
		System.setProperty("webdriver.chrome.drive", "Z:\\B\\BrowserDrivers\\chromedriver.exe");
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("useAutomationExtension", false);
        driver = new ChromeDriver(options);
		driver.navigate().to(baseURL);

**Comment by wakaleo** [comment]
Please raise this issue with the chromedriver maintainers, it is unrelated to Serenity

**Comment by mbn217** [comment]
ok thanks

**Comment by ShaliniSujith** [comment]
Hi mbn217

Please set below in serenity.properties to disable 'unable to load extension' popup.

chrome.switches=--args -disable-extensions
