### ISSUE TITLE
skip scenarios with meta annotation @skip

### ISSUE THREAD

**Issue by spcial** [serenity-bdd/serenity-core#95]
I configured my meta filter like:
embedder.useMetaFilters(Arrays.asList("-skip"));

and used the Annotation:

Meta:
@skip
between Scenario and Given in my .story file. 

In the console I get the output 
[pool-1-thread-1] INFO net.serenitybdd.core.Serenity - TEST IGNORED
and in the result documentation I get the information that the test is ignored but still the scenario is completely executed. 
Why should the scenario be executed if it should be ignored at the end? Is there a way to skip the execution of the whole scenario? 
If I'm implementing new scenarios I only want to test the current scenario I'm working with and not all.
Thanks for any help!

Edit: I'm working with serenity 1.0.47 and JBehave 1.0.23

**Comment by YamStranger** [comment]
Hello @spcial 

Thanks for this issue!!!

Your request was implemented in latest serenity core (1.1.29-rc.3 )and jbehave (1.9.0)

Now we use native for jbehave filtering mechanism. 

Thanks for helping us making Serenity BDD better )

**Comment by dmitry-weirdo** [comment]
I am still struggling with this, stories marked with `@skip` in `Meta` are not skipped.

My class overrides `SerenityStories`. I've tried to override 
`configuredEmbedder().useMetaFilters(Collections.singletonList("-skip"))`
everywhere possible in my class that extends `SerenityStories`, as it is recommended in https://jbehave.org/reference/stable/meta-filtering.html.
Still all the stories present in the run and executed.

Very similar issue is present here — https://stackoverflow.com/questions/31532064/get-configured-embedder-for-use-of-meta-filters-skip-with-selenium-and-jbehav.

**Comment by wakaleo** [comment]
Feel free to dig around the JBehave Serenity integration and propose a PR if you find anything. New development work for Serenity is mainly focused on Cucumber integration.

**Comment by dmitry-weirdo** [comment]
https://stackoverflow.com/questions/31532064/get-configured-embedder-for-use-of-meta-filters-skip-with-selenium-and-jbehav/56890951#56890951 I've investigated the code working logic and described it in the related question of SO. I can make a PR, but not sure which `MetaFilters` overriding logic will be correct.
