### ISSUE TITLE
PageObjects not auto-managing WebDriver instances unless initialized when defined in step libraries

### ISSUE THREAD

**Issue by dbirch-cognitoiq** [serenity-bdd/serenity-core#951]
We're currently working to change how our Page Objects are implemented in a test suite using Serenity.

We are trying to move over to a case where any page action which changes a page causes the old page to return an instantiated version of the page we're going to.

According to the documentation I can find, as long as we define a variable in the steps libraries which use them for each of the Page Objects to be used, we should be able to assign the object instances to these variables.

Referring to docs at:
[http://thucydides.info/docs/serenity-staging/#_using_pages_in_a_step_library](url)

I have tried this in my own Step libraries, but discovered that unless I also initialize that page object in the same line, The page does not seem to be correctly initialized and has no WebDriver instance created.

This is what I find I need to do in order to get the page objects to automatically create a WebDriver instance:
`FindAJobPage jobPage = new FindAJobPage()`

I've worked around it by implementing an abstract page which caches the WebDriver and passes it through to the PageObject super constructor, and a simple page object which is initialized in my step libraries in order to make sure my first WebDriver instance is created and cached.

Is the documentation out of date here, or is this standard practice and intended behavior to manage our own WebDriver instances if we're not initializing page objects when they are defined in the step libraries?

**Comment by wakaleo** [comment]
As a rule I have found the practice of returning a new Page Object when you navigate to a new page to be an anti-pattern (you are basically re-implementing the application architecture into the test logic). This ends up needing double maintenance (what happens if the page navigation changes) and complicated handling of error conditions (what happens if you don't go to the page you expect). So generally, I don't recommend using this approach at all.

If you use a new statement, Serenity will not be able to instantiate the driver, so the Page Object won't work correctly. If you really do need to use this approach, use the Pages class, e.g.:
```
return Pages.instrumentedPageObjectUsing(MyPage.class, getDriver())
```

**Comment by dbirch-cognitoiq** [comment]
Some interesting food for thought there, I've always found the small extra bit of maintenance worthwhile for the quick and explicit test failures if we end up somewhere we don't expect to be. I guess between screenshots and good reporting, serenity would make it easier to identify these issues via other means. I shall have a ponder and possibly do some redesign.

In response to your comment on the "new" statement, just out of interest, how come this works when you use a "new" on the same line as the Page Object variable declaration, it works, but if you use the new keyword inside a step, it doesn't?

Also, is it worth updating the documentation to make this apparent? It currently suggests that just declaring the variable should be enough to use it in a step library and I really don't see this as being the case?

**Comment by wakaleo** [comment]
When you create a new instance of a Page Object field, that value gets overridden by Serenity when it instantiates the step library, so it is actually only an illusion that it works. Generally you just need to declare the field, without instantiating it.

Yes, the documentation is in need of updating. We have started migrating/updating all the docs here: https://wakaleo.gitbooks.io/the-serenity-book/content/ but it's not ready for prime-time yet.

**Comment by dbirch-cognitoiq** [comment]
Ok, now I understand :) Thanks!
