### ISSUE TITLE
Getting an error in AfterStories when we call a method from Serenity Step files in Step file

### ISSUE THREAD

**Issue by jaspreetmanchinda** [serenity-bdd/serenity-core#955]
<serenity.version>1.6.3</serenity.version>
<serenity.jbehave.version>1.30.0</serenity.jbehave.version>

I have a @AfterStories in one java class and if i call a method other class annotated with @Step then I am getting an error as **(org.jbehave.core.failures.BeforeOrAfterFailed: Method test (annotated with @AfterStories in class com.sample.random.steps.DefinitionSteps) failed: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value)**

Class A{

 @Steps
    EndUserSteps endUser;

@AfterStories()
    public void test(){
    	System.out.println(endUser.test());
    }
}

Class B{

 @Step
    public String test() {
        return "djdfwe";
    }
}

**Comment by wakaleo** [comment]
Step Libraries are only available in the lifecycle of a scenario and story. Because of the way JBehave works, @AfterStories calls happen in a different thread context to other lifecycle annotations. So, in a web test (for example)
  - In @AfterScenario you can still see the last state of the browser
  - In @AfterStory the browsers will have shut down and the test reports for the scenarios have been generated.
  - In @AfterStories, Serenity has closed shop and the thread in which Serenity was running has been shut down.

What problem are you trying to solve?

**Comment by jaspreetmanchinda** [comment]
I am using it for rest testing and in @AfterStories i am calling a delete api to clean up the database. and that method is written in RestStep file. This was working in previous versions

**Comment by wakaleo** [comment]
What is the stack dump you are getting?

**Comment by jaspreetmanchinda** [comment]
com.sample.random.steps.DefinitionSteps.test() (FAILED)
(org.jbehave.core.failures.BeforeOrAfterFailed: Method test (annotated with @AfterStories in class com.sample.random.steps.DefinitionSteps) failed: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value)

**Comment by wakaleo** [comment]
Do you have a stack trace with that error?

**Comment by jaspreetmanchinda** [comment]
nope that's the only error I am getting,

![image](https://user-images.githubusercontent.com/26487567/31268430-d7a7b980-aa99-11e7-9692-0864ac3c7473.png)

**Comment by jaspreetmanchinda** [comment]
Tried with 		
<serenity.version>1.6.6</serenity.version>
<serenity.jbehave.version>1.30.0</serenity.jbehave.version>

but method with @step is not getting called in failed scenario

**Comment by wakaleo** [comment]
This cannot be done in JBehave. Steps are initialised in the context of the thread they are running in (usually within a scenario). They are intended to represent actions that happen inside the context of a thread. @AfterStory methods get called from another thread, so they will use a different step library. If you need to perform actions after the end of the stories, you need to use another mechanism to do this.

**Comment by jaspreetmanchinda** [comment]
Sorry forgot to mention this I am geting in @AfterScenario

**Comment by wakaleo** [comment]
In @AfterScenario, the step library will still be present. However if a scenario fails, all subsequent @Step methods will not be called (this is by design). If you need the method to be called from the @AfterScenario even if the test fails, don't annotate it with @Step.
