### ISSUE TITLE
my api  request is having escape characters(\"guidelines for\") but RestAssued library not sending  same formate.  

### ISSUE THREAD

**Issue by muli09** [serenity-bdd/serenity-core#957]
My query should go like this but
{
    "header": {
        "apiName": "getSubscriberDeviceCounts"
    },
    "request": {
        "startDate": "5/11/16",
        "endDate": "6/15/16",
        "query": " (keyword=\"guidelines for\")"
    }
}

my RestAssured send in the below formate 

{
    "header": {
        "apiName": "getSubscriberDeviceCounts"
    },
    "request": {
        "startDate": "5/11/16",
        "endDate": "6/15/16",
        "query": " (keyword=guidelines for)"
    }
}
becuse of that getting error message from Server

**Comment by wakaleo** [comment]
I think this would be a better question for the REST-Assured community.

**Comment by muli09** [comment]
The issue here ..im reading the data from csv file by using "@UseTestDataFrom(value = "testdata/techno/technographic.csv")" have escpse character,if i use sysout also those escape  charactes are removed.

**Comment by wakaleo** [comment]
Can you create a sample test that illustrates what you want and what you are seeing?
