### ISSUE TITLE
@Test should be finished when one of steps is failed

### ISSUE THREAD

**Issue by leonidasos** [serenity-bdd/serenity-core#96]
Serenity goes to next @Step when AssertionError error occurs or some other exception and executes it. 
In my opinion Serenity should failure test and remark next common steps as skipped or not executed.
@Test should be atomic, so it should pass or fail.

**Comment by wakaleo** [comment]
The behaviour you describe is the normal behaviour of Serenity - after a step fails, subsequent steps are executed in "dry-run" mode, which means that any web driver calls will not be executed, and recorded as "skipped".

In the next version, Serenity will by default only record subsequent @Step methods as executed, without actually executing them. You will be able to use the 'deep.step.execution.after.failures' system property to turn this behaviour on or off.

**Comment by leonidasos** [comment]
Great news. Can't wait for the new version.

Cheers

**Comment by SrivaniChennupati** [comment]
@leonidasos  :  deep.step.execution.after.failures' helped you ? Its not working in my project when I configured the same to avoid the recording of the subsequent steps if any step got failed
