### ISSUE TITLE
Not able to generate index.html file .No such method error

### ISSUE THREAD

**Issue by Shafic777** [serenity-bdd/serenity-core#960]
Serenity Version:
------------------
 <serenity.version>1.6.3</serenity.version>
 <serenity.maven.version>1.6.0</serenity.maven.version>
 <serenity.jbehave.version>1.30.0</serenity.jbehave.version>

Sample Project : https://github.com/Shafic777/serenityAPITestFramework

Logs:
-----
 org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:183)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.6.0:aggregate: ja
va.lang.NoSuchMethodError: net.thucydides.core.reports.html.HtmlAggregateStoryReporter.setTags(Ljava/lang/String;)V
-----------------------------------------------------

**Comment by wakaleo** [comment]
Have you tried using the same version of serenity-core and serenity-maven-plugin (1.6.3)?

**Comment by Shafic777** [comment]
Yes i did ...Still same issue.

[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.6.0:aggregate (serenity-reports) on project serenity-jbehave-showcase: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.6.0:aggregate
failed: An API incompatibility was encountered while executing net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.6.0:aggregate: java.lang.NoSuchMethodError: net.thucydides.core.reports.html.HtmlAggregateStoryReporter.setTags(Ljava/lang/String;)V
[ERROR] -----------------------------------------------------

**Comment by wakaleo** [comment]
It’s a depencency conflict due to the dependencies in your pom,xml file. Remove all the references to Serenity core 1.0.47 and the make sure The maven and Junit dependencies are all on 1.6.3

**Comment by Shafic777** [comment]
Its working fine now.Thanks for the quick turnaround.
