### ISSUE TITLE
findall function is always returning XPath selector

### ISSUE THREAD

**Issue by balajilinks** [serenity-bdd/serenity-core#963]
serenity-core/src/main/java/net/serenitybdd/core/selectors/Selectors.java

isXPath function is returning true for both CSS and xPath selectors.   So findAll function is working only for XPath queries and not for CSS queries.

**Comment by wakaleo** [comment]
Can you give an example of a CSS query that is being interpreted as xPath?

**Comment by balajilinks** [comment]
def isXPath(String xpathExpression) {
XPathFactory factory = XPathFactory.newInstance();
XPath xpath = factory.newXPath();
try {
    xpath.compile(xpathExpression);
} catch (Exception e) {
    return false;
}
return true;
}
assert isXPath("Input[contains(@id,'userName')]")
assert isXPath("span[name='cars']")
assert isXPath("input#email")
assert isXPath("input.submitbtn")

**Comment by balajilinks** [comment]
[Abc.zip](https://github.com/serenity-bdd/serenity-core/files/1372567/Abc.zip)

    println(getDriver().findElements(By.cssSelector("button.tablinks")).size())  = Result 3
    println(getDriver().findElements(By.xpath("button.tablinks")).size())   =  Result 0

Result :

**Comment by wakaleo** [comment]
OK. The problem is that Java 8 compiles those expressions as syntactically correct XPath (this might be new to Java 8). I'm open to suggestions but I can't see any other simple way to check the validity of CSS or XPath in Java.

So at the moment, you would need to use a By.cssSelector() for those.

**Comment by wakaleo** [comment]
Not so much a "won't-fix" as a "can't fix"; PRs are welcome if you know a foolproof way of distinguishing XPath from CSS, or of validating a CSS selector expression in Java.
