### ISSUE TITLE
No index.html running SerenityReportingRunner 

### ISSUE THREAD

**Issue by blaltarriba** [serenity-bdd/serenity-core#966]
I'm running Serenity test using `SerenityReportingRunner`, something like:

````
SerenityReportingRunner runner = new SerenityReportingRunner(SerenityStories.class);
runner.run(new RunNotifier());
````
I see all reports are generated at default folder `target/site/serenity` but any `index.html` file was generated.

I found in http://www.thucydides.info/docs/serenity/ :
"Tip: It is possible to use a Junit Run Configuration to run a Serenity Testrunner. This will not generate an aggregate report. If you find your index.html file is missing, check that you are using a Maven build Run Configuration with goal verify to run your test and get the aggregate report."

Is it possible to generate the aggregate report using `SerenityReportingRunner`?

Thank you in advance!

**Comment by wakaleo** [comment]
No, the SerenityReportingRunner is not designed to perform the report aggregation, just the test reports for the individual tests.

**Comment by blaltarriba** [comment]
Ok, is good to know. Is this feature in the roadmap?

Thank you for your quickly answer as always!

**Comment by wakaleo** [comment]
Not currently, but it wouldn't be a hard PR ;-).

**Comment by blaltarriba** [comment]
I will research how to do it then. 

Thank you @wakaleo
