### ISSUE TITLE
Performance loss after upgrading from v1.5.12 to v1.6.0

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#969]
I have noticed significant performance loss after upgrading from v1.5.12 to v1.6.0.
Normally it takes about 6 minutes while with v1.6.0 more than 8 minutes which is at least 30% longer.

`Refactored the way step libraries are instantiated`may be the issue

**Comment by wakaleo** [comment]
Try putting `setting step.creation.strategy=legacy` in your serenity.properties file.

**Comment by dsmt** [comment]
It helps, thank you!

**Comment by wakaleo** [comment]
In 1.6.0 the default behaviour is to create a new step library for each scenario. If your step libraries are expensive to create, use the legacy mode or mark them as shared.

**Comment by dsmt** [comment]
I was going to use `shared` but decided to let you know first. Thank you for quick response

**Comment by wakaleo** [comment]
Works as intended
