### ISSUE TITLE
While executing selenium scripts from Bamboo tool using Serenity Runner getting error: net.serenitybdd.core.pages.WebElementFacadeImpl$

### ISSUE THREAD

**Issue by sampathgoud42** [serenity-bdd/serenity-core#97]
While executing selenium scripts using maven 3 and Serenity Runner getting error: net.serenitybdd.core.pages.WebElementFacadeImpl$

Statement where I am getting error: " element(createButton).waitUntilVisible(); "

The waitUntilVisible is causing the error which is defined as "net.serenitybdd.core.pages.WebElementFacade.waitUntilVisible()"

Please help me to resolve the error.

Error Message:
" INFO net.thucydides.core.steps.StepInterceptor - STEP FAILED: createButton - Timed out after 5 seconds waiting for net.serenitybdd.core.pages.WebElementFacadeImpl$1@5abce6eb
error	27-Jul-2015 15:37:06	Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
error	27-Jul-2015 15:37:06	System info: host: 'XXXXXX', ip: '201.17.XX.XXX', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_80-ea'  "

**Comment by wakaleo** [comment]
Issue unrelated to Serenity.
