### ISSUE TITLE
First curly brace is always shifted in JSON response

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#970]
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/PKcxHPqvZprNMac5bYfC3ouj5MeOeQ/Owner%2Bshould%2Bbe%2Bable%2Bto%2Bfilter%2Btheir%2Bshipments%2Bby%2Bdrop%2Boff%2Blocation%2B2017-10-16%2B14-34-13.png?Expires=1508240075&Signature=V-Aj757F535AEV98eb1TVzgrTmow91DYtH2Ppgkj1qcV2mqYRcmqq3zrPrtsNlH2EP8Db9MLVEqMPLcpWv-ed15ygYJ99M2ZErrB2svp1wDzzOj8RAwpCwzAGIikLZufm88fsN7qGhuJ-auXDIMy6EXj4Gd9hI7qw-CjQNoRcKP-EQ849VJUfaymdRECpVxv9FL4TVW6roFQE5i-25L63etF-A98LNY8K1ExuOU6BgP28uEEIhah2O-LbmTE45IDdKXcIgeZSgbQEdYXcEqDTeIV93R9bGvXFnr1RGYsGV~3gq3jvpw5T-jt4WGx82XTSU00U7SNB-p-sPd4Irrx1Q__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by cliviu** [comment]
hi @dsmt, can you please provide a small project to reproduce your issue ?

**Comment by dsmt** [comment]
Hi, @cliviu!
Sorry for the delay. I believe this defect needs additional clarification. This shift I mentioned in the title occurs not only for JSON content type in a response, I believe it occurs every time body has content.
Here is my [sample project](https://github.com/dsmt/serenity-sample-api) for reproducing this defect.

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_86337/MVzMEHMT6QHn3vwsH0WKDTBk9kiGYC/First%2Bline%2Bin%2Bresponse%2Bbody%2Bis%2Balways%2Bshifted%2B2017-10-27%2B12-58-26.png?Expires=1509184720&Signature=cnKIGa9~3g4zroSHBCTomPiRGFbL25~uSDDn5LJEFwiozdCh1iFxFobyl5FPrbrADJA2LQ08j-6YoH61efS2gNEZyB2I3mEh-MKQZJRgQ4DEZDW5FZMrO1ad2v25IDX2~e8PSSRWaiIrSdBHjcVJ7aI80GLqQhYQAdeRk-zXb6kE1mReQ9czMFC6lrueZQcnLoZDgQlApYvoedyruysdV8DuGhglzpLYE6jreW6dFyvOpWhQ3C30bqBx0hV0DXTScSkYJGvOQyK-AdV62G9Q4szeU3puZ1LBZiMAD2hGKZ00RqQ9LbPWN1wYOzlzIinys8mLguFLEqAaR3U04WpMhA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by cliviu** [comment]
Hi @dsmt , thanks for your test project. The issue should be fixed in the next version

**Comment by wakaleo** [comment]
Should be fixed in 1.6.7.
