### ISSUE TITLE
screenshot for each action : often bad screenshot

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#973]
Hello, 

When I use the option : 
```
serenity.take.screenshots=FOR_EACH_ACTION
```
Screenshot are taken for each step / action.
But unfortunately, there is often some bad screenshot.

![bad screenshot](https://user-images.githubusercontent.com/29480659/31620442-8c727404-b297-11e7-8147-05a97dea3c11.png)
For instance in this case, the four screenshots are from the previously page (the login page), while the steps are on the home page.

Or some steps with "filling fields" action are on a screenshort with blank field, and others not...

**Comment by wakaleo** [comment]
We can't really do much about this. Sometimes there is a delay in taking the screenshot with WebDriver, so they can be slightly out of phase.
