### ISSUE TITLE
serenity report : need some explanation

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#974]
Hi @wakaleo !

As usual, test are made with the last version of serenity (currently 1.6.5).

![serenity report issues](https://user-images.githubusercontent.com/29480659/31620890-b7fff53c-b298-11e7-9df5-6742d992456c.png)

I have some trouble with the features / stories tabs on the report.
I don't understand why there is only the story "Logout", and why all the stories are blank expect Logout.

Indeed, I think I respect directories / stories / runners naming in the project.

And in the report, there is still the version 1.5.1 displayed. :-)

Thanks for your help.

**Comment by wakaleo** [comment]
This looks like it could be a blank line at the start of the JBehave story file; if not, I would need a sample project to see what is going on. 
The version is a known issue, but is fairly low on the priority list - though PRs are always welcome.

**Comment by mmanach** [comment]
Hi, with this project, you can reproduce some behaviors concerning the "blank line" of the report : https://github.com/mmanach/serenity-issue-972

**Comment by wakaleo** [comment]
Try placing the name of the story on the first line of the .story files, not just starting with the Meta: statement.

**Comment by mmanach** [comment]
Ok, it seems to solved some cases, but still misunderstanding what is the expected and good jbehave syntax.

![serenity meta tag](https://user-images.githubusercontent.com/29480659/31675562-53473b8c-b365-11e7-8115-da074cead7ba.png)

- The blank line is a .story with "Meta :" on start. (orange on screen)
- But if you have this .story with a "@issue" tag on meta, then it's work. (the #lol-3)

- Concerning the red, I dont understand why there is not the #LIL-4 on the first page

**Comment by wakaleo** [comment]
For JBehave stories, you should write the title of the story on the first line of the story file. 

Some guidelines:
- The directories that contain the story files should represent features or capabilities, so it makes no sense for them to have the same name as the story file. 
- Don't have empty Meta: or Lifecycle: sections, only put them if you need to put something in them. They add noise, reduce readability, and defeat the purpose of BDD tools as communication tools.

**Comment by wakaleo** [comment]
Could you check with version 1.6.6?

**Comment by mmanach** [comment]
Hello @wakaleo 

Quite strange, since update to 1.6.6 with my sandbox project, all test are failled : 
```
Incompatible class change error: Expected static method net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(Ljava/lang/Object;Lnet/thucydides/core/steps/StepFactory;)V
```
But anyway, with other project it's ok 😕 

**To be sure, when you speak about "the title of the story", it's the "Scenario:" statement, right ?** 

Now it seems to be good for this part ! thanks

**Comment by wakaleo** [comment]
Sounds like you have an old version of Serenity referred to in your project somewhere. 
The title of the story is the title of the story as a whole, not the title of the individual scenarios.

**Comment by wakaleo** [comment]
@mmanach did you get this sorted out?

**Comment by mmanach** [comment]
Yes I think that I can close for now, the report looks better :)
