### ISSUE TITLE
Unable to click on a link having link javascript:void(0)

### ISSUE THREAD

**Issue by khalistan** [serenity-bdd/serenity-core#975]
Hallo i am trying to click on a link which have href="javascript:void(0)" but somehow click function is not working. I tried to click with native javascript click` ((JavascriptExecutor) driver).executeScript("arguments[0].click()", element);`
I have also tried to do click with event 
```
String onClickScript = "if(document.createEvent){var evObj = document.createEvent('MouseEvents');evObj.initEvent('click',true, false); arguments[0].dispatchEvent(evObj);} else if(document.createEventObject){ arguments[0].fireEvent('onclick');}";
		((JavascriptExecutor) driver).executeScript(onClickScript, element);
```
But still can't click on element. As normal user (human), I can click on link but with 
```
WebElementFacade element = find(By.cssSelector(".hereSelector"));
element.click();
```

Element is in view so really don't know what to do.
----------Thanks

**Comment by wakaleo** [comment]
If neither click() or javascript click is working, then most likely your selector is not identifying the correct element (the one that accepts the click event). Unlikely to be either a Serenity or a WebDriver issue.

**Comment by khalistan** [comment]
Selector is correct. If I use same selector and try to get element from browser console, then it finds the hyper-link.
i mean:
`document.querySelector(".hereSelector");`

**Comment by wakaleo** [comment]
See if this works:
```
getDriver().findElement(By.cssSelector(".hereSelector")).click();
```
If it does, it's a Serenity issue (you can step into the click() method to see what it is doing. 
If nothing happens, it is either a Selenium bug (unlikely at this level in my experience), possibly a bug with the driver (also would seem unlikely for a click), or the element identified by the selector is not the one that handles the click event on the page (usually the most common scenario)

**Comment by wakaleo** [comment]
Did you get this issue sorted out?

**Comment by wakaleo** [comment]
Closed due to inactivity.
