### ISSUE TITLE
Error running Serenity from jar archive

### ISSUE THREAD

**Issue by volnoboy** [serenity-bdd/serenity-core#979]
Since around version 1.6.0 I cannot run tests from jar archive(I package my project with maven-assembly-plugin), I get this error:

[pool-1-thread-1] ERROR net.serenitybdd.core.Serenity - Expected static method net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(Ljava/lang/Object;Lnet/thucydides/core/steps/StepFactory;)V

java.lang.IncompatibleClassChangeError: Expected static method net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(Ljava/lang/Object;Lnet/thucydides/core/steps/StepFactory;)V
        at net.serenitybdd.jbehave.SerenityStepFactory.createInstanceOfType(SerenityStepFactory.java:71)
        at org.jbehave.core.steps.StepCreator.stepsInstance(StepCreator.java:93)
        at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
        at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)

On version 1.5.3 everything works fine.

**Comment by wakaleo** [comment]
That is not really a supported feature; are you using the latest version of serenity-jbehave?

**Comment by volnoboy** [comment]
I am running Serenity this way for about a year. It was working fine on version 1.5.3. Then I couldn't update because of some dependency issues. And now since 1.6.0 this issue started, it is reproducing on every version of Serenity until latest 1.6.7-rc.1.

**Comment by wakaleo** [comment]
As I said, it's not a supported feature so there are no acceptance or regression tests for it. However, java.lang.IncompatibleClassChangeError sounds like you are using an incompatible version of serenity-jbehave. Are you using serenity-jbehave 1.30.0?

**Comment by volnoboy** [comment]
You are right, it was the wrong version of serenity-jbehave. Everything seems to work fine now, I will close this issue.
