### ISSUE TITLE
Conflict with testng

### ISSUE THREAD

**Issue by mikyone** [serenity-bdd/serenity-core#98]
Hello, 

I tried to embedded serenity with an existing project which already have its own dependencies. I noticed I can execute the serenity plugin to perform my test ("mvn verify" don't execute any test). If I excluded testng of my project it works.
The problem is the project use needs testng.
Could you tell me if there is a workaround  ?

**Comment by wakaleo** [comment]
Serenity does not support TestNG, but the problem you are describing sounds more like a classic dependency conflict. Try using the Maven Dependency plugin to identify and resolve any dependency conflicts.

**Comment by mikyone** [comment]
Before writting this ticket I used the dependency maven plugin  and   I found out that if I included testng in my project that could break the phase verify.
I tried to add the testng dependency project in your example project [webservice  demo master] (https://github.com/thucydides-webtests/webservice-demo) to see if I was able to execute the phase verify. And I noticed that I got the same behaviour, impossible to run the BDD.
I updated the pom.xml from the thucidides to serinity just to be sure. 
Let me know if you have a clue. Thanks again.
Here is the pom.xml of "webservice  demo master":
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.wakaleo.training.webservices</groupId>
    <artifactId>bdddemo</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Sample Thucydides project</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.1</serenity.version>
        <serenity.jbehave.version>1.1.0</serenity.jbehave.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.8.21</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jbehave</artifactId>
            <version>${serenity.jbehave.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.easytesting</groupId>
            <artifactId>fest-assert</artifactId>
            <version>1.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>
        <!--<dependency>-->
            <!--<groupId>com.googlecode.lambdaj</groupId>-->
            <!--<artifactId>lambdaj</artifactId>-->
            <!--<version>2.3.3</version>-->
        <!--</dependency>-->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>4.0.3.RELEASE</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>jsonassert</artifactId>
            <version>1.2.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.1.0</version>
            <scope>test</scope>
        </dependency>


    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.11</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.11</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/Test*.java</include>
                        <include>**/When*.java</include>
                        <include>**/*TestSuite.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9</version>
            </plugin>
            <plugin>
                <groupId>net.thucydides.maven.plugins</groupId>
                <artifactId>maven-thucydides-plugin</artifactId>
                <version>${thucydides.version}</version>
                <executions>
                    <execution>
                        <id>thucydides-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>maven2</id>
            <activation>
                <file>
                    <missing>${basedir}</missing>
                </file>
            </activation>
            <reporting>
                <plugins>
                    <plugin>
                        <groupId>net.thucydides.maven.plugins</groupId>
                        <artifactId>maven-thucydides-plugin</artifactId>
                        <version>${thucydides.version}</version>
                    </plugin>
                </plugins>
            </reporting>
        </profile>
        <profile>
            <id>maven3</id>
            <activation>
                <file>
                    <exists>${basedir}</exists>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-site-plugin</artifactId>
                        <version>3.2</version>
                        <configuration>
                            <reportPlugins>
                                <plugin>
                                    <groupId>net.thucydides.maven.plugins</groupId>
                                    <artifactId>maven-thucydides-plugin</artifactId>
                                    <version>${thucydides.version}</version>
                                </plugin>
                            </reportPlugins>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>


</project>
```

**Comment by wakaleo** [comment]
Without seeing the specific question, it is very hard to say. You will need to identify the dependency conflict (try running mvn dependency:tree -Dverbose) and resolve them in your pom.xml file (see https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html).

**Comment by mikyone** [comment]
Sorry for my english. I m going to reexplain what I have done and what is my goal.
I want to execute this maven phase  *mvn verify* and be able to see the  serenity maven pluggin  executes my BDD test. 

As   an example I took the project [webservice  demo master] (https://github.com/thucydides-webtests/webservice-demo)  you made to reproduce my problem.
If I execute *mvn  verify* without adding the testng dependency in the pom.xml I can execute the serenety maven pluggin. But if I add testng then the serenity pluggin skipped everything. 

When I embedded the testng and execute *mvn dependency:tree* I can see 
```
[INFO] com.wakaleo.training.webservices:bdddemo:jar:1.0.0-SNAPSHOT
[INFO] +- org.testng:testng:jar:6.8.21:compile
[INFO] |  +- org.beanshell:bsh:jar:2.0b4:compile
[INFO] |  \- com.beust:jcommander:jar:1.27:compile
[INFO] +- net.serenity-bdd:serenity-core:jar:1.1.1:compile
```

I tried to exclude jcommander and bean shell from the testng to see if it improves something. Unfortunatlly I still have  the same issue. As I told you, this test on your project seems useless because you don't need testng, but on my side I need it. So  I would like to fix this error. 
Let me know if you it's not really understandable. 
Thanks for your answer.

By the way I was at your conference in Dublin in June. It was very instructive.

**Comment by wakaleo** [comment]
Try running  *mvn dependency:tree -v *to see what conflicts there are.

On 30 July 2015 at 16:42, mikyone <notifications@github.com> wrote:

> Sorry for my english. I m going to reexplain what I have done and what is
> my goal.
> I want to execute this maven phase *mvn verify* and be able to see the
> serenity maven pluggin executes my BDD test.
>
> As an example I took the project webservice demo master
> <https://github.com/thucydides-webtests/webservice-demo> you made to
> reproduce my problem.
> If I execute *mvn verify* without adding the testng dependency in the
> pom.xml I can execute the serenety maven pluggin. But if I add testng then
> the serenity pluggin skipped everything.
>
> When I embedded the testng and execute *mvn dependency:tree* I can see
>
> [INFO] com.wakaleo.training.webservices:bdddemo:jar:1.0.0-SNAPSHOT
> [INFO] +- org.testng:testng:jar:6.8.21:compile
> [INFO] |  +- org.beanshell:bsh:jar:2.0b4:compile
> [INFO] |  \- com.beust:jcommander:jar:1.27:compile
> [INFO] +- net.serenity-bdd:serenity-core:jar:1.1.1:compile
>
> I tried to exclude jcommander and bean shell from the testng to see if it
> improves something. Unfortunatlly I still have the same issue. As I told
> you, this test on your project seems useless because you don't need testng,
> but on my side I need it. So I would like to fix this error.
> Let me know if you it's not really understandable.
> Thanks for your answer.
>
> By the way I was at your conference in Dublin in June. It was very
> instructive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/98#issuecomment-126374069>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by AvinKumar** [comment]
Hi mikyone,
It's been a long time since you posted the question. But I just wanted to know whether were you able to integrate the TestNg with Serenity. Were you able to resolve your dependency issues and run through testng.?  If so then can you please let me know the steps to be followed to integrate my existing project in TestNg with Serenity.

-Avin

**Comment by wakaleo** [comment]
Serenity does not support TestNG at this stage.

**Comment by AvinKumar** [comment]
Hey John,
Any plans to integrate TestNg with Serenity in the near future.

**Comment by wakaleo** [comment]
Not at this stage; I think more modern Java testing frameworks like Spock or Spectrum would take priority.

**Comment by AvinKumar** [comment]
Oh okie thanks. 
One suggestion I would like to know from you. 
What it takes if I want to build a wrapper class or something to integrate testng with serenity for my project. From where I should start.

**Comment by wakaleo** [comment]
You would need to write a TestNG runner, similar to the JUnit runner, and set up the appropriate hooks to trigger the corresponding events in the EventBus. So the serenity-junit module would probably be the place to start looking.

**Comment by AvinKumar** [comment]
Ok thanks for the info John. I will start looking into it.

**Comment by pk-tcassian** [comment]
I am lookinmg for a similar solution. I already have cucumber-testng integration in place and I have a Cucumber Testng Runner in place. Can I integrate this setup with serenity-bdd alone?

**Comment by pushprajsingh05** [comment]
@wakaleo Does it support TestNg now? You have also commented that if not TestNg it would spock or spectrum. Any update.

**Comment by wakaleo** [comment]
Not at this stage.

**Comment by Nachiket26** [comment]
Does it support testNG now?

**Comment by wakaleo** [comment]
No

**Comment by priyaKN** [comment]
@wakaleo Hello Sir. I am looking to plugin reporting feature of serenity into my existing Functional Test Automation Project which uses another project (the another project, we have build as common framework to use across organization) as library in our Automation project. All the classes in existing project uses method from the common library which makes use of TestNG. Can you give any insight on how can i plugin in just the reporting ability alone into my project (since serenity doesn't support TestNG)

**Comment by priyaKN** [comment]
@mikyone Hello, Is it possible for you to answer the above question?

**Comment by wakaleo** [comment]
@priyaKN It would depend on your project; this isn't generally how Serenity operates.

**Comment by vlad230** [comment]
Guys, if you are mainly interested in seeing reports, there are multiple other libraries that handle reporting for you. 
For example, you can use Java + TestNG + Cucumber + Allure Reports ( http://allure.qatools.ru/ ).

**Comment by wakaleo** [comment]
Indeed; Serenity is about BDD-style living documentation and about enabling testers to write solid automation test faster; if you just want simple test reports, Allure is fine.

**Comment by gizdolok** [comment]
I would love to be able to run Scenarios Outlines Examples in Parallel with Serenity-BDD.

But currently since it does not integrate with TestNG, with JUnit we can only get parallelisation by running each feature file in a separate threat.

**Comment by globalworming** [comment]
afaik, you can also run the different scenarios in a feature file in parallel with junit and the maven surefire/failsafe plugin. Not sure about examples though.

**Comment by Arun3948** [comment]
@wakaleo Does it support testNG now?
sorry for asking same qus....

**Comment by globalworming** [comment]
still no
