### ISSUE TITLE
File Upload using htmlunitdriverwith Serenity Frame work

### ISSUE THREAD

**Issue by karimmd73** [serenity-bdd/serenity-core#980]
File Upload  (  upload(filename).to(logoField);)using htmlunit driver fails.It works fine with IEdriver.
I get an error that object should be visible performing file upload.

**Comment by wakaleo** [comment]
Are you sure this is a Serenity issue rather than an HTMLUnit bug? What is the stack trace of the message?

**Comment by wakaleo** [comment]
Did you get this issue sorted out?

**Comment by karimmd73** [comment]
This is still an issue, File upload does it work with htmlunit driver.

**Comment by karimmd73** [comment]
File upload does not work with htmlunit driver.

**Comment by wakaleo** [comment]
If it works with IE and not with HTMLUnit, then it is most likely an HTMLUnit issue. See if you can write the equivalent code in plain Selenium to upload the code. If that code works in HTMLUnit, it could be related to the Serenity implementation (though the code makes no distinction with regard to which driver it uses). If that code works in IE and not in HTMLUnit, then you can close this issue and raise a separate issue with the HTMLUnit project.

**Comment by karimmd73** [comment]
I am not sure about the workaround for this issue using equivalent code in Selenium at this point.I will try to work on it  as soon as I can.

**Comment by wakaleo** [comment]
Closed for lack of activity
