### ISSUE TITLE
Clarification on OnStage usage

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#982]
On my latest serenity project I'm using the `OnStage` class to manage my actors and I use `OnStage.setTheStage(new OnlineCast());` in a @Before annotation (cucumber). This is a pattern I've copied from the [todo demo project](https://github.com/serenity-bdd/screenplay-pattern-todomvc/blob/a4163781e4d901bcd3b4237ca014d70317229ffa/src/test/java/net/serenitybdd/demos/todos/cucumber/steps/TodoUserSteps.java#L28). 

I see that there is also a `OnStage.drawTheCurtain();` static method, however when I look for usage in the codebase I can't find anything. What's the recommendation for using this method please?

**Comment by wakaleo** [comment]
`OnStage.drawTheCurtain()` dismisses the cast, which deletes all the actors from the current cast. You can add this in an @after method (symmetrically with the `setTheStage()` method.

**Comment by nbarrett** [comment]
Thanks - I've done that in my project now for good practice. Would be good to see a unit test in core for this so we can see how calling `OnStage.drawTheCurtain();` affects system behaviour. Happy to provide a PR to add this, but not quite sure what behaviour I should be testing..
