### ISSUE TITLE
window.open(..) javascript call returns null when invoked via Serenity

### ISSUE THREAD

**Issue by lalitrnagpal** [serenity-bdd/serenity-core#983]
OS: Windows 7 Enterprise
Serenity Version: 1.1.42
Browser: Internet Explorer 11

I click on a button using the following code

`actor.attemptsTo(Click.on(MyMenu.sortDialog)); 
`

where the sortDialog is pointing to the button below

```
<button class="button actimizeIconButton" id="mySortButton" 
onclick="openSortDialog()" type="button" alt="advanced sort"></button>

```

this should invoke the openSortDialog() function which contains the line

` win = window.open("/BlankWithIndicator.jsp", "dynamicSortWindowName", "width=450,height=325,left=575,top=191"); 
`

The variable win here is coming as null and so the code breaks, when this is executed via Serenity.

This works fine when we run it manually but breaks with serenity. Somehow the win.open is returning null when invoked via Serenity code.

This is a 3rd party code of Actimize reports so I cannot change any code here, can just do things on Serenity side

**Comment by wakaleo** [comment]
How are you executing this Javascript code?

**Comment by lalitrnagpal** [comment]
Its a UI page of Actimize Reports. It has a button which opens a child window that offers options to select fields to filter on.

**Comment by wakaleo** [comment]
Does it work in raw Selenium/WebDriver?

**Comment by lalitrnagpal** [comment]
I also tried with

`theBrowser.findElement(By.id("openAdvancedSortButton")).click();
`

and same behavior 

`window.open("/BlankWithIndicator.jsp", "dynamicSortWindowName", "width=450,height=325,left=575,top=191");` 

is returning null. Is there any other way I should try? Thanks

**Comment by wakaleo** [comment]
Could you post the code that is returning null, showing how you are using it?

**Comment by lalitrnagpal** [comment]
We are using Actimize reports and its the actimize reports code that fails internally and I can see that via Developer Tools of IE 11. It fails with null reference saying "Unable to get property 'focus' of undefined or null reference". The actimize javascript code where it fails is as below

```
		// open a new window and set it as the target of the form submission
		win = window.open("/BlankWithIndicator.jsp", "dynamicSortWindowName", "width=450,height=325,left=575,top=191");
		win.focus();
		
		// keep window reference in map
		this.windowsMap.put(this.getTask(), win);
```

It breaks on win.focus() since win is null.

In my test case I am clicking on the button that invokes the function which has these lines above.
I tried with both
`actor.attemptsTo(Click.on(AppMenuOptions.Open_Advanced_Sort_Dialog));
`and selenium approach
`theBrowser.findElement(By.id("openAdvancedSortButton")).click();
`

**Comment by MrSamadhiya** [comment]
In both the cases - with Serenity and manaully using the application, parameteres being passed to window.open(..) are excatly same. But, incase of serenity, it returns null or undefined.

**Comment by wakaleo** [comment]
So it would seem that this is not related to Serenity, but more how the IE WebDriver implementation invokes the JavaScript in the browser?

**Comment by MrSamadhiya** [comment]
Does IE WebDriver manipulates/affects the behaviour of the application java script ?  since java script call to a standard Javasciprt function is behaving differntly in this case.

**Comment by wakaleo** [comment]
I have no idea, maybe try with another browser (IE is one of the least reliable generally speaking).

**Comment by MrSamadhiya** [comment]
The UI is provided by a 3rd Party and it only supports IE. So, browser change is not an option. 

Can you please suggest any other appraoch to handle this ? 

Any other ways to click on the link apart from below two ?  

1.    actor.attemptsTo(Click.on(MyMenu.sortDialog)); 
2.    webDriver.findElement(By.id("openAdvancedSortButton")).click(); 

Not sure if it's relevent - The child browser window does open with serenity but it's not loaded with the contents and just shows blank page.

**Comment by wakaleo** [comment]
Both approaches simply call a WebDriver click() method. You could try invoking Javascript directly, e.g. 

Since this is not a Selenium or Serenity issue, but more a Selenium usage question, could you close this issue and move the conversation to StackOverflow and possibly Rocket Chat (https://serenity-bdd.rocket.chat/home), as there may be other people who have encountered this problem.

**Comment by lalitrnagpal** [comment]
The javascript call to window.open(...) clearly isn't working when invoked via selenium, the window handle being returned is null. As you mentioned, this might be a driver issue, so closing. Thanks for your help.
