### ISSUE TITLE
Different Actors cannot be made to share same browser

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#989]
I'm configuring my Screenplay environment using `OnStage.setTheStage(new OnlineCast());`, and then obtaining actor references using`OnStage.theActorCalled(<actor name>)`, however I find a new browser window is created for each actor, regardless of the value of property `serenity.use.unique.browser`. On the system under test, this actually causes problems with the running of the system. This behaviour can be reproduced in the [todo demo project](https://github.com/serenity-bdd/screenplay-pattern-todomvc/blob/a4163781e4d901bcd3b4237ca014d70317229ffa/src/test/java/net/serenitybdd/demos/todos/cucumber/steps/TodoUserSteps.java)  by:

* setting the following configuration:

```
serenity {
  restart.browser.for.each = NEVER
  use.unique.browser = true
}
```

* changing features/record_todos/add_new_items_to_the_todo_list.feature to

```
  Scenario: Adding an item to an empty list in Cucumber
    Given that James has an empty todo list
    Given that John has an empty todo list
    Given that Joe has an empty todo list
```
* running `net.serenitybdd.demos.todos.cucumber.RecordTodos`

Outcome is that 3 browsers are fired up.

How can I ensure that all actors share the same browser please?

**Comment by nbarrett** [comment]
Actually, having played around with things, I can get one browser to be used like this:
`theActorCalled(actorName).can(BrowseTheWeb.with(ThucydidesWebDriverSupport.getWebdriverManager().getWebdriverByName("same actor")));`

But that seems like a hack - is there a better way than this?

**Comment by wakaleo** [comment]
The best way would be to write your own `OnlineCast` class, and hide this logic inside. Look at the implementation of the standard `OnlineCast` and go from there.

**Comment by wakaleo** [comment]
I'm assuming this question is answered?

**Comment by nbarrett** [comment]
I might submit a PR as the current behaviour is not as expected?

**Comment by wakaleo** [comment]
Sure, please do.

**Comment by wakaleo** [comment]
Which current behaviour is not as expected?

**Comment by nbarrett** [comment]
E.g serenity.use.unique.browser property should affect browser instantation, so my proposal would be to invoke the workaround code I suggested above if this property is set true.

**Comment by wakaleo** [comment]
Good point, but `use.unique.browser` is no longer used - it has been replaced by `serenity.restart.browser.for.each`

**Comment by nbarrett** [comment]
Okay, will do but I always had `serenity.restart.browser.for.each=NEVER` set all along, but I thought that property was controlling browser restarts rather than browser instances which to me are different concerns. I've seen [another issue](https://github.com/serenity-bdd/serenity-core/issues/683) where `serenity.restart.browser.frequency` was discussed as the deprecated property!
