### ISSUE TITLE
Valuable information in Exception messages lost due to html formatting

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#990]
Applies to Serenity 1.5.7 - exception messages in the bootstrap popup messages would benefit from being formatted in a `<pre>` tag to avoid loss of important information. For instance in the serenity report, the exception message looks like this:

![image](https://user-images.githubusercontent.com/626941/32092607-320e8964-baf1-11e7-864d-e06b4f4f666a.png)

Whereas the Cucumber plugin version of the same error is in a `<pre>` tag as follows which seems much preferable:

![image](https://user-images.githubusercontent.com/626941/32092653-5d0d60cc-baf1-11e7-83f2-d98036f80411.png)

**Comment by wakaleo** [comment]
Could you propose a pr?

**Comment by nbarrett** [comment]
I'll have a go! I've not delved into the serenity-reporting yet, but I'll report back shortly :-)
