### ISSUE TITLE
Asychronous method in  'Afterscenario' to write report back to the called method

### ISSUE THREAD

**Issue by saranyas** [serenity-bdd/serenity-core#994]
Hi,

I have scenario in which the last step includes database check and that longer time. Hence I created a asynchronous method and to be called after each scenario. this will help to avoid unnecessary waits for each scenario to complete.

But the asynchronous method not returning result (Assertions) back to the called method to write report back to that scenario.

Is it possible from serenity to handle this or would you suggest anyways to achieve this ?

Thanks

**Comment by saranyas** [comment]
Hi, could you suggest to handle this.

**Comment by wakaleo** [comment]
Nothing like this is supported in Serenity, you would need to implement this yourself. If the database check is so long that you need to consider asynchronous call-backs, perhaps you should try to optimise this?

**Comment by saranyas** [comment]
Thanks for the reply. Since system has been designed such a way it will be delayed 2 to 3 minutes. Since we use serenity looking for better way to handle this.
