### ISSUE TITLE
Issue executing test on selenium grid(remote machine)-

### ISSUE THREAD

**Issue by karimmd73** [serenity-bdd/serenity-core#996]
Unable to execute test on a remote machine using serenity framework.

Using    -  serenityVersion = '1.2.5-rc.5' , serenityCucumberVersion = '1.1.29'

Remote Machine:  Selenium Standalone server 3.6.0
JVM arguments : -Dwebdriver.remote.url=http://192.168.2.53:4444/wd/hub -Dwebdriver.remote.driver=ie -Dwebdriver.remote.os=WINDOWS

Please advise whether  3.6.0 is compatible with serenity.

Please review log attached.
[Griderror.docx](https://github.com/serenity-bdd/serenity-core/files/1423884/Griderror.docx)

**Comment by karimmd73** [comment]
[Griderror.docx](https://github.com/serenity-bdd/serenity-core/files/1423885/Griderror.docx)

**Comment by wakaleo** [comment]
You need to use the most recent versions of serenity-core and Serenity-cucumber

**Comment by karimmd73** [comment]
Same issue, Attaching build.gradle and error log
[buil.gradle.docx](https://github.com/serenity-bdd/serenity-core/files/1424327/buil.gradle.docx)
[Remoteexecutionerror.docx](https://github.com/serenity-bdd/serenity-core/files/1424328/Remoteexecutionerror.docx)

**Comment by wakaleo** [comment]
Selenium is unable to connect to Internet Explorer. This is generally a configuration issue on the Selenium grid server (the logs don’t indicate a Serenity issue)

**Comment by karimmd73** [comment]
Closing this issue , this is related to configuration on grid.
