### ISSUE TITLE
Serenity tests running incorrectly in IE browser

### ISSUE THREAD

**Issue by Harryneni** [serenity-bdd/serenity-core#997]
Hi,
I see below issues when trying to run serenity test suite using IEDriver.

- Cannot perform click on the buttons
-  When there is a button click in a table row the focus switches to the next row.

The configuration and code changes i have tried-

**In Thucydides.properties file i have this**

webdriver.driver=iexplorer
serenity.driver.capabilities=INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS:true;ACCEPT_SSL_CERTS:true
capabilities.setCapability(InternetExplorerDriver.NATIVE_EVENTS, false);

I run the test suite using below command
**> mvn verify -Dwebdriver.ie.driver=C:\IEDriverServer.exe**

I have the added IEdriver location to the path(environment vars)

I have the below code in my test class

@RunWith(SerenityRunner.class)  
public class RegionTest {
	
	@Managed(driver = "iexplorer", uniqueSession = true)
    WebDriver driver;
    
    @Steps
    RegionTestSteps regionTestSteps;
    
    @Test
    @Title("Empty username/password on login screen")
    
   public void region_serinity_test() throws InterruptedException {  

    	DesiredCapabilities ieCapabilities = DesiredCapabilities.internetExplorer();
        ieCapabilities.setCapability("nativeEvents", false);
    	ieCapabilities.setCapability("unexpectedAlertBehaviour", "accept");
    	ieCapabilities.setCapability("ignoreProtectedModeSettings", true);
    	ieCapabilities.setCapability("disable-popup-blocking", true);
    	
        // GIVEN
    	regionTestSteps.open_region_page();
    	// Then
    	regionTestSteps.navigate_to_userRoles();
    }

I have made sure my IE11 browser has below settings

- zoom(100%)
- Enhanced protected mode setting disabled
- Made sure all the Internet, local Intranet,  trusted sites, restricted sites  have security level medium-high and all have same protected mode setting
- have entries in Reg edit for 32 and 64 bit as recommened

Not sure what is still breaking, same code runs fine in chrome.

**Comment by wakaleo** [comment]
Setting the desired capabilities inside the test as you do it here will have no effect - you would need to use a custom driver to do this. However, in general, if it works in Chrome but not in IE, it's most likely an IE Driver bug, and unrelated to Serenity. So it would be better to raise this issue in the Selenium/IE circles.
