### ISSUE TITLE
browser closes immediately after the last assertion even when there are statements to execute

### ISSUE THREAD

**Issue by RamnathRaghu** [serenity-bdd/serenity-core#998]
Hi 

I am using cucumber-jvm with serenity. I am using @Managed annotation which manages the browser instantiation and its removal. But in the last step (Then) of my BDD scenario, where I am asserting, I observed the below:

1) I have two assertions and if I have any statements before or in-between the assertions, it gets executed. However, if I have any statements after my last assertion, it does not get executed. My understanding of the expected is that all the statements after the last assertion would get executed.
2) In addition, I am unable to use the browser to in cucumber's @After annotation to undo the changes that I have done as part of test execution, since the browser gets closed immediately after the last assertion in the test.

**Comment by wakaleo** [comment]
Do the assertions pass or fail?

**Comment by RamnathRaghu** [comment]
When the Assertions pass, the statements following the last assertion and also the code block in the @After  method are executed successfully. It is only when the assertions fail, none of the following statements are getting executed. When the assertions fail, the browser closes immediately not waiting for the code inside the @After method to run.

**Comment by wakaleo** [comment]
This is expected behaviour. As soon as an assertion fails, or any other error occurs, subsequent steps or WebDriver calls are skipped. Ideally, a test should only contain one assertion at the end. If you need to do clean-up actions after the test, it is better to do them via non-web API calls.

**Comment by RamnathRaghu** [comment]
Thanks, John for looking into this.
